### ISSUE TITLE
Threaded view on servers without THREADS capability

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#2798]
_Reported by nagus69 on 27 Apr 2010 12:23 UTC as Trac ticket #1486677_

I am using a fresh install of 0.4-beta and can't seem to get threaded view to work. I tried IE 8 (also compatibility mode) and Firefox 3.6. They are not showing. Can't find any settin where i have to activate it. 

_Migrated-From: http://trac.roundcube.net/ticket/1486677_

**Comment by alecpl** [comment]
Really, it looks that no one is interested in working on implementing a code that would be used only in rare cases. Two best open source imap servers (cyrus and dovecot) already support this. Such client-side code would be much slower than server side threading. Wontfix.
