### ISSUE TITLE
automatically reply with correct virtual identities/aliases/personalities

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#3272]
_Reported by awayand on 5 Feb 2011 21:42 UTC as Trac ticket #1487763_

For those of us using sub-domain addressing to fight spam, it would be helpful to have roundcube auto-reply with the correct From: header. The workaround at the moment is using the custom_from plugin, but it means manually changing the From: header for every single email.

Example:
I am using different aliases with sub-domain addressing for each website:

amazoncouk@subdomain.domain.com
amazoncom@subdomain.domain.com
britishairwayscouk@subdomain.domain.com

All of the above arrive in my inbox. When I respond, I want roundcube to automatically select the right From: header to match the address the email was sent to.

Thanks!

_Keywords: personalities aliases compose edit address envelope envelope-from identity_
_Migrated-From: http://trac.roundcube.net/ticket/1487763_

**Comment by OJFord** [comment]
I'd also like this feature; it's not just about subdomains either, point is just to reply `From` whatever `alias@[sub.]domain.tld` the email was sent `To` by default.

Useful, as OP says, when one person uses the whole domain and has a catch-all (or 'catch many') configured.

I found an old forum post asking for it while trying to find if this was possible, too:
https://www.roundcubeforum.net/index.php/topic,4760.msg19079.html?PHPSESSID=50gqs6j17hlvd1qi9njstm6jdl#msg19079

**Comment by alecpl** [comment]
Wontfix. This is a case for a plugin. And I see some exist.
