### ISSUE TITLE
html code when reply to an html email

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#3900]
_Reported by sylvaing on 28 Aug 2012 08:06 UTC as Trac ticket #1488649_

Hi,
I use settings of rouncube to compose always in html, and when i reply to an HTML email, there is rapid apparition of html code and "Police Taille Police", and to finish the good composer.

I use roundcube with  a "slow computer" core2duo with 1go RAM. With a modern computer, this is very fast, and user can't see this.

_Migrated-From: http://trac.roundcube.net/ticket/1488649_

**Comment by alecpl** [comment]
No one commented on this in 7 years. I'm guessing that's a very rare issue. Not worth spending time on it.
