### ISSUE TITLE
Request to add additional field for Address Apartment/Building/Floor etc.

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4010]
_Reported by amaramrahul on 20 Nov 2012 07:38 UTC as Trac ticket #1488822_

It is extremely common, almost a standard, to have a field for Apartment#/Building# in addition to the Street field for addresses. Keeping this in mind, could an additional field be added to the address for contacts?

_Migrated-From: http://trac.roundcube.net/ticket/1488822_

**Comment by alecpl** [comment]
Wontfix. 
```
  Experience with vCard 3 has shown that the first two components
  (post office box and extended address) are plagued with many
  interoperability issues.  To ensure maximal interoperability,
  their values SHOULD be empty.
```
