### ISSUE TITLE
Attachment Managment Tool

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4968]
_Reported by goeko at goecke dolan dot com on 15 Jun 2006 14:40 UTC as Trac ticket #1483842_

I would like to see a tool in round cube that would list all the attachments you have.  You should have the ability to sort by name, or size or date received or what ever.  It would list the most current files with a drill down to see older versions of the file.

_Migrated-From: http://trac.roundcube.net/ticket/1483842_

**Comment by alecpl** [comment]
Maybe a good idea for a plugin, but I don't see it in core. Lack of interest here confirms that.
