### ISSUE TITLE
Master Account Features

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4969]
_Reported by Creature on 15 Jun 2006 19:16 UTC as Trac ticket #1483844_

Not to compare RC to Horde because I find RC to far better but there is a feature Ijust could not do without. When I login to Horde as the master account of a domain I have access to all accounts on the server. I.E. if I login into my domain as master@mydomain.com I can see the inbox, outbox and sent folders ect.. for sales@mtdomain.com, support@mydoamin.com so on and so on. This feature would finalize RC as the best webmail app by far.

_Migrated-From: http://trac.roundcube.net/ticket/1483844_

**Comment by alecpl** [comment]
This is not going to happen.
