### ISSUE TITLE
Automatically add to addressbook on send.

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4971]
_Reported by Zelest on 5 Aug 2006 21:24 UTC as Trac ticket #1483935_

It would be nice to have an option (could be turned off by default) which allow you to automatically add someone in your addressbook when you send a mail to them. I for one would love this as my antispam system could take advantage of it.

If you consider adding this feature, what about having 3 options? One that disables it (default?), a second one that automatically adds addresses to the addressbook and a third option which simply ask the user "do you want to add foo@bar.tld to your addressbook?".

_Migrated-From: http://trac.roundcube.net/ticket/1483935_

**Comment by bostjan** [comment]
My inconvenience with the automatic_addressbook is the fact that it uses separate table for address collection. Any good reason for that? If address is missing from all current address books, it should add it to Personal address book and optionally assign it to group (if and which should be configurable).

b.

**Comment by alecpl** [comment]
I must admit that I didn't think about using groups for this purpose. In Kolab you can have many personal addressbooks so using a book sounded reasonable to me. Also other clients use a separate addressbook (e.g. Thunderbird). I kind of liked the idea of using groups, but... we don't have in Addressbook an option to skip selected group (show all contacts except this one group), so when user would want to browse his addressbook he would see all contacts and collected addresses at once which may be not so nice.

**Comment by bostjan** [comment]
Yes, on this edge use case I agree that using multiple address books is reasonable :)

Joking aside, my itch has already been scratched, here:
https://plugins.roundcube.net/packages/teon/automatic_addressbook_ng

I must admit that I really do not remember WHY I disliked the multi-addressbook idea originally - it might have something to do with address autocompletion work I was doing at the time (https://plugins.roundcube.net/packages/teon/smart_autocomplete), as that work was done with RoundCube webmail as primary and only mail interface in mind.

**Comment by kodemafia** [comment]
automatic_addressbook is not working if we are hiding the global address book. The saved ids are not comming in compose window in autocompletion.

**Comment by labcerouno** [comment]
wow! This is 14 years old...

**Comment by alecpl** [comment]
Feature implemented.

**Comment by antonical** [comment]
I have the latest version installed and connot find this option to enable it. Can you advise how to enable this functionality please.

Cheers
Tony

**Comment by navossoc** [comment]
> I have the latest version installed and connot find this option to enable it. Can you advise how to enable this functionality please.
> 
> Cheers Tony

On Roundcube 1.5:
`Settings -> Preferences -> Contacts`

Look for `Collected addresses`
