### ISSUE TITLE
Merge 2 different folders

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4974]
_Reported by bugreporter on 11 Mar 2007 09:50 UTC as Trac ticket #1484278_

It would be great to see an option to merge 2 folders. E.g. merge .INBOX.Drafts with Drafts.

_Migrated-From: http://trac.roundcube.net/ticket/1484278_

**Comment by alecpl** [comment]
I'm closing this old ticket. The use-case and scope is not clear.
