### ISSUE TITLE
Why do we need special treatment for RTL email and Thunderbird implementation

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4978]
_Reported by moish on 3 Mar 2008 16:13 UTC as Trac ticket #1484825_
1. Some remarks from Drupal developer as to why do we need special treatment for RTL  
   emails. Also some design ideas which are not so relevant to RC.
   http://groups.drupal.org/node/4463
2. Source files ( js ) from BidiMail Thunderbird extension, showing their
   solution for plain text RTL emails. ( Mainly bidimailpack-common.js ).
   https://addons.mozilla.org/en-US/thunderbird/addon/310

_Keywords: rtl plain text bidi_
_Migrated-From: http://trac.roundcube.net/ticket/1484825_

**Comment by alecpl** [comment]
This is not going to happen until someone's step in and clarify what exactly needs to be done.
