### ISSUE TITLE
support to notes

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4979]
_Reported by zedstar on 29 Apr 2008 12:51 UTC as Trac ticket #1485023_

allow roundcube to support notes similar to horde/squirrel.

_Migrated-From: http://trac.roundcube.net/ticket/1485023_

**Comment by alecpl** [comment]
Some plugins exist:
https://plugins.roundcube.net/packages/offerel/primitivenotes
https://git.kolab.org/diffusion/RPK/browse/master/plugins/kolab_notes/

**Comment by alecpl** [comment]
A feature not for core.
