### ISSUE TITLE
Side-by-side email view / email list

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4980]
_Reported by ihuxley on 7 Aug 2008 06:25 UTC as Trac ticket #1485255_

It'd be great to have an option to allow the preview pane to be along side the message list and not always at the bottom.  A lot of wide screens these days :).

Would be nice to allow the folder area to be horizontally resizable too (scrolling if too small) as this would be more important in this case.

_Migrated-From: http://trac.roundcube.net/ticket/1485255_

**Comment by alecpl** [comment]
Duplicate of #5093.
