### ISSUE TITLE
On reply, truncate subject prefix in foreign languages

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4981]
_Reported by abaum on 8 Aug 2008 08:18 UTC as Trac ticket #1485258_

There are a lot of misconfigured mail clients (e.g. MS Outlook) out there who use wrong, non-english subject prefixes (e.g. the german edition of Outlook uses "AW:" instead of "Re:"). Now, if you reply on such a mail, the subject will become "Re: AW: Subject" instead of "Re: Subject". Other mail clients can detect this.
We could make an additional entry in the translation files and truncate the wrong prefix.

_Keywords: subject prefix translation_
_Migrated-From: http://trac.roundcube.net/ticket/1485258_

**Comment by frontierpsycho** [comment]
I encountered this bug, it's quite annoying. Are there any plans to work on it? 

If not, if I find time I'll look into it.

**Comment by alecpl** [comment]
Configuration options implemented.

A future scope might be to make these options available to the end-user via Preferences > Composing messages > Advanced options. Pull requests would be appreciated. @tpayen maybe, you?
