### ISSUE TITLE
Off-line access to e-mail

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4982]
_Reported by AsgrimTheMighty on 11 Sep 2008 08:20 UTC as Trac ticket #1485333_

A very cool new feature would be to integrate with Google Gears to allow Roundcube and emails to be accessed when offline.

_Migrated-From: http://trac.roundcube.net/ticket/1485333_

**Comment by alecpl** [comment]
This is not going to happen.
