### ISSUE TITLE
Speed Up User Interface - Client Cache Message List & Update List in Background

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4984]
_Reported by jond10 on 30 Jan 2009 20:38 UTC as Trac ticket #1485710_

When I click inbox, then double click a message, I wait for it to load (my imap server is slow).  When I click the inbox, I wait for the page to reload, even if I only glance at the message for 5 seconds.

Why does the inbox need to reload when I click it?  The content is the same.

It should work like this:
First opening of a folder loads the content (json, or whatever), stores it, and fires off a timer to update the list.

When I view a message, and go back, the page is loaded from the json variable locally eliminating any call to the server.

If I need an immediate update from the server, I can bypass the timer by clicking the foldername a second time.

Instead of having all the folders act this way,just the most recent 2.  This way if I'm comparing messages from one folder to another,I'm not waiting for my server to resend the list.

This also prevents too much data being stored locally.

_Migrated-From: http://trac.roundcube.net/ticket/1485710_

**Comment by alecpl** [comment]
This would be hard to implement with not so much of improvement. If you're worried about perf. in such a scenario use preview window or open messages in a separate window/tab instead of using a new page.
