### ISSUE TITLE
E-Mail - Redirect  Bounce

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4985]
_Reported by lacri on 11 Mar 2009 10:06 UTC as Trac ticket #1485774_

A beautiful feature for Roundcube would be possible that it is for messages to be redirect/rerouted/bounce.

As a message forward only that the receiver does not see that the message one forwarded.

The feature gives it for example also with Squirrelmail and in the The Bat! Just see it as a interactive BCC. The message is send as is to another mail address. This option is often called bounce.

_Keywords: redirect reroute bounce_
_Migrated-From: http://trac.roundcube.net/ticket/1485774_

**Comment by incase** [comment]
This request has been put on the "later" milestone and is now closed, but I didn't find a comment saying "we are not going to do it" or "we did it as part of xyz" or any commit referring to this feature request.
Has it been silently abandoned?
The feature seems relatively easy to implement (but I have no familiarity with PHP or the roundcube codebase to do it myself) and is rather useful for several people. Any chance it can be added to roundcube itself?

**Comment by incase** [comment]
Sorry, I was confused by the last "What is 'Bounce the message'" reference (which is closed). This request still is open TTBOMK.
However, my other question still stands: Any chance this could be implemented soon?

**Comment by alecpl** [comment]
Implemented. https://kolabian.wordpress.com/2017/07/12/email-resend-bounce-feature/#more-1009

**Comment by CRCinAU** [comment]
This  has broken sending of mail.

When composing a message, pressing the send button causes a javascript error stating "Please enter at least one recipient.".

Looking at the svn log, this appears to occur with any commit at or beyond the following:
------------------------------------------------------------------------
r11654 | aleksander.machniak | 2017-07-12 19:56:41 +1000 (Wed, 12 Jul 2017) | 2 lines

Email Resent (Bounce) feature (#4985)

The previous commit (r11649) works fine.

**Comment by alecpl** [comment]
@CRCinAU Thanks, fixed in b7e42de7ac.

**Comment by CRCinAU** [comment]
Fix confirmed working.

**Comment by sffax** [comment]
How do I get this feature? It's not available even with the latest release.

**Comment by braindumped** [comment]
sry for asking stupid questions: how to enable the bounce feature in my rc 1.3.9?

**Comment by alecpl** [comment]
As milestone suggests it's a 1.4 feature.
