### ISSUE TITLE
Replace image urls by cid urls when composing/sending a message

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4988]
_Reported by rosali on 9 Jul 2009 12:28 UTC as Trac ticket #1485968_

I'd like to see a feature to embed images as cid url attachments.

Something like here:

http://www.phpeveryday.com/articles/PHP-Email-Using-Embedded-Images-in-HTML-Email-P113.html

_Migrated-From: http://trac.roundcube.net/ticket/1485968_

**Comment by alecpl** [comment]
So, at the moment it looks that the last thing is attaching external images. I'm not a big fan of this feature. It is possible to write a plugin. Closing.
