### ISSUE TITLE
Email grouping (like in Outlook)

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4990]
_Reported by monkeyman on 10 Sep 2009 07:51 UTC as Trac ticket #1486110_

I would like to suggest to add a grouping of emails by days, like Outlook does. Right now all emails just stack inline.

**Monday**
[Email 1
[[BR]([BR]]*)]\* Email 2
[Email 3
[[BR]([BR]]*)]**Tuesday**
[Email 1
[[BR]([BR]]*)]\* Email 2
[Email 3
[[BR]([BR]]*)]**Wednesday**
[Email 1
[[BR]([BR]]*)]\* Email 2
[[BR]]\* Email 3

And so on. This is very user friendly.

_Migrated-From: http://trac.roundcube.net/ticket/1486110_

**Comment by alecpl** [comment]
Wontfix.
