### ISSUE TITLE
Disable upload button as long as no file is selected

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4991]
_Reported by duelli on 27 Nov 2009 09:22 UTC as Trac ticket #1486318_

When composing an email, it is somewhat confusing that users can click the upload button although no file is selected.

If no file is given, no action will be conducted.

I vote for disabling the upload button as long as no file is selected by the user.

_Migrated-From: http://trac.roundcube.net/ticket/1486318_

**Comment by alecpl** [comment]
If we implement #5024 this will become irrelevant.

**Comment by alecpl** [comment]
Done.
