### ISSUE TITLE
password plugin: using LDAP EXOP for changing passwords (RFC3062)

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4992]
_Reported by timeos on 8 Dec 2009 20:37 UTC as Trac ticket #1486349_

Hello

please append EXOP (ldap EXtended OPeraton) form of change password operation in LDAP. It's due to password syncing along multiple password attributes (userPassword, sambaLMpassword, sambaNTpassword, kerberos pass) through openLDAP trigger named smbk5pwd. this trigger is only triggered by ldap passwd exop operation. when that operation is catched by this trigger, it's responsible for automatic change of all password attributes for specific user.

thanks

_Keywords: ldap exop, password_
_Migrated-From: http://trac.roundcube.net/ticket/1486349_

**Comment by alecpl** [comment]
PHP itself does not support LDAP EXOP: https://bugs.php.net/bug.php?id=69445. Until this is implemented we can do nothing about it.

**Comment by alecpl** [comment]
Implemented in PHP 7.2 (http://php.net/manual/en/function.ldap-exop-passwd.php). Anyone would like to provide a pull request?

**Comment by army1349** [comment]
Has anyone started? If not, I will do it.

**Comment by alecpl** [comment]
Go ahead!

**Comment by army1349** [comment]
Proposing patch:
[patch.zip](https://github.com/roundcube/roundcubemail/files/2930043/patch.zip)

**Comment by alecpl** [comment]
I propose to create a separate driver. And could you create a pull request?

**Comment by army1349** [comment]
OK, I thought about that possibility too.
Do I have rights to push commit here?

**Comment by alecpl** [comment]
You have rights to create github pull requests.

**Comment by alecpl** [comment]
Done.
