### ISSUE TITLE
Cumulative attachment size limit

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4993]
_Reported by JohnDoh on 23 Dec 2009 16:15 UTC as Trac ticket #1486389_

As well as a restriction on the size of each file that can be attached when composing an email would it be possible to have a restriction on the total size of all attachments added together?

I think that would actually be more useful than a per file limit since it is the overall size of the email which will be restricted by the server.

_Migrated-From: http://trac.roundcube.net/ticket/1486389_

**Comment by alecpl** [comment]
Added option max_message_size. Default: 100M.
