### ISSUE TITLE
Roundcube quota notification

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4995]
_Reported by kamil ondrus on 21 Jan 2010 10:31 UTC as Trac ticket #1486445_

I do need notification for user, which is about to exceed his quota limit. For example, if his data exceeds appx. 90% of his quota, I want from Roundcube, that after login system will display information message (which can be set by administrator). Login process will continue only when user acknowledge this message.

_Keywords: quota login_
_Migrated-From: http://trac.roundcube.net/ticket/1486445_

**Comment by alecpl** [comment]
This is also implemented in https://github.com/jfcherng/roundcube-quota-plugin.
