### ISSUE TITLE
Messages in threads with no parent count as separate threads in mailbox list limit

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#4999]
_Reported by trisk on 25 Mar 2010 20:09 UTC as Trac ticket #1486581_

Some threads can have many messages referring to a parent which is not present (an example is the emails from this Trac instance, if I am CC'ed on a ticket I did not create). These threads cannot be expanded/unexpanded, as discussed in #1486571 and RFC 5256 says they should have a dummy message as their parent. The messages still count as separate threads or rows towards the mailbox list limit (default 40) while threads with a single parent only count the parent. This is a problem if the thread is particularly long as it can take up more than the thread limit and keep all other messages on previous pages.

Counting them as a single thread for the purposes of the mailbox list is a possible solution, but that could make the mailbox view a display lot more rows than is reasonable.

_Migrated-From: http://trac.roundcube.net/ticket/1486581_

**Comment by alecpl** [comment]
Fixed.
