### ISSUE TITLE
Wrong units: the units used in roundcube are IEC (base 2), but the abbreviations are SI (KB,GB,MB).

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5001]
_Reported by epinter on 29 Mar 2010 14:11 UTC as Trac ticket #1486590_

The patch adds an option for use SI or IEC units, correcting the label to KiB,MiB and GiB when using IEC units.

_Migrated-From: http://trac.roundcube.net/ticket/1486590_

**Comment by alecpl** [comment]
Added `show_bytes` hook, so you can write a plugin. The rest is wontfix.

**Comment by breard-r** [comment]
Hello,

First of all, thank you for the `show_bytes` hook, it's much appreciated. Unfortunately, I think this hook this hook has a few limits:
1. Some values are manipulated with the 1024 factor **before** being passed to `show_bytes` (eg: the [quota](https://github.com/roundcube/roundcubemail/blob/4e2e8761017f1a67a71fd7b8037c79a806c02cf4/program/include/rcmail.php#L1923-L1924)).
2. Some values are manipulated in [the JavaScript](https://github.com/roundcube/roundcubemail/blob/4e2e8761017f1a67a71fd7b8037c79a806c02cf4/program/js/app.js#L9628-L9652).

I completely understand that you might not want to invest time on fixing this issue. However, if someone else would submit a PR that fixes it, would you accept this contribution?

**Comment by n3vu0r** [comment]
I've released the [roundcube-signifix](https://packagist.org/packages/qu1x/roundcube-signifix) plugin which makes use of the `show_bytes` hook. It allows bytes to be formatted with metric or binary prefixes. According to the [IMAP4 QUOTA extension](https://www.rfc-editor.org/rfc/rfc2087), quota usage and limit is reported in units of 1 KiB. So binary prefixes are the default but I've documented how to use metric prefixes without rounding issues in [`config.inc.php.dist`](https://github.com/qu1x/roundcube-signifix/blob/main/config.inc.php.dist). Any ideas how to replace the JavaScript [function](https://github.com/roundcube/roundcubemail/blob/81ac3c342a4f288deb275590895b52ec3785cf8a/program/js/app.js#L9705) are welcome.

**Comment by tomsommer** [comment]
Thank you @n3vu0r - odd this is a wontfix
