### ISSUE TITLE
IP ban after multiple login failures - Anti Brute Force Login

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5002]
_Reported by redbullpeter on 14 Apr 2010 17:43 UTC as Trac ticket #1486636_

Hi,

Roundcube currently allows users to attempt numerous login attempts. This leaves the system exposed to the risk of dictionary attacks.

I'd like to request a feature which would automatically ban an IP address for, say, 30 mins after 3 failed login attempts. This would make dictionary attacks infeasible.

Regards,

Red

_Migrated-From: http://trac.roundcube.net/ticket/1486636_

**Comment by alecpl** [comment]
Since Roundcube 1.2 we already have login_rate_limit feature. Any more sophisticated code need to be implemented as a plugin.
