### ISSUE TITLE
Quota indicator hide/show switch

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5005]
_Reported by dziobak on 18 Jun 2010 09:39 UTC as Trac ticket #1486804_

My suggestion is to move quota progress bar to the new bar under mail list. It could be on left of preview checkbox. Now it's alone at the bottom of site.

_Migrated-From: http://trac.roundcube.net/ticket/1486804_

**Comment by alecpl** [comment]
Well, no one's going to work on the quota widget hiding. Not much of interest in this and gain questionable. Wontfix.
