### ISSUE TITLE
One button to mark all messages in a folder

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5006]
_Reported by phq on 25 Jul 2010 18:36 UTC as Trac ticket #1486877_

This is a feature request similar to #1486417 but with the emphasis on *one button*

hi guys! please, add button "mark all messages in current folder as read"

The motivation for this is that when you have mailing lists sorted to their own folder you usually read through the interesting ones and then when done you want to mark all messages as read.

The motivation for one button is that this is a common operation and therefore there is value in making it as quick and simple as possible.

_Migrated-From: http://trac.roundcube.net/ticket/1486877_

**Comment by alecpl** [comment]
Implemented.
