### ISSUE TITLE
Add to plugin markasjunk a confirmation popup

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5008]
_Reported by agueijo on 31 Aug 2010 16:16 UTC as Trac ticket #1486966_

Hello,

It may add to plugin markasjunk a confirmation popup 
before moving the junk mail folder.

My users often confuse the icon to delete with the icon mark as junk

Thank, Agustin

_Keywords: markasjunk popup_
_Migrated-From: http://trac.roundcube.net/ticket/1486966_

**Comment by alecpl** [comment]
We do not ask for confirmation when moving to Trash, so we should not ask when moving to Junk. We ask questions only for irreversible operations.
