### ISSUE TITLE
[patch] disable export of (ldap) addressbook

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5009]
_Reported by synapse on 6 Sep 2010 18:10 UTC as Trac ticket #1486978_

Sometimes it's a good idea to prevent users from downloading all the addresses in the company LDAP catalog, especially when there're thousands of them.
I would like to control this by adding 'exportable'=>false to the ```$rcmail_config[array.

Here is the patch for export.inc

``````

diff -u  export.inc_orig export.inc |tee export.inc.patch 
--- export.inc_orig     2010-06-23 16:55:08.000000000 +0700
+++ export.inc  2010-09-07 00:43:31.199718049 +0700
@@ -29,6 +29,11 @@
 header('Content-Type: text/x-vcard; charset='.RCMAIL_CHARSET);
 header('Content-Disposition: attachment; filename="rcube_contacts.vcf"');

+if ($CONTACTS->prop["exportable"]('ldap_public']['XXX']```) === false) {
+    echo "No exportable cards were found.";
+    exit;
+}
+
 while ($result && ($row = $result->next())) {
   $vcard = new rcube_vcard($row[  $vcard->set('displayname', $row['name']('vcard']);
));

``````

_Keywords: disable ldap export_
_Migrated-From: http://trac.roundcube.net/ticket/1486978_

**Comment by alecpl** [comment]
Wontfix. Write a plugin or create a pull request then we'll reconsider.
