### ISSUE TITLE
Improve message list item-count display

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5010]
_Reported by brandond on 12 Oct 2010 00:25 UTC as Trac ticket #1487050_

It would be nice if there was a display of:
1. Total messages in folder vs number of messages found by search filter (if a search is active)
2. Number of messages selected (if any messages are selected)

Item 1 is mostly a convenience request; it's nice to know how many items were searched as well as how many matched the criteria.

Item 2 is more important, as there is no way to know whether you've selected the current page, or all messages, or if some other set of actions resulted in selecting a set of messages that are not visible on the current page. 

This has resulted in some amount of user confusion and folks accidentally deleting all messages in a folder when they only intended to delete a single page.

_Migrated-From: http://trac.roundcube.net/ticket/1487050_

**Comment by alecpl** [comment]
Wontfix. In 10 years no one commented in the ticket. Looks no one shares the opinion.
