### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5011]
_Reported by vminakov on 18 Oct 2010 09:29 UTC as Trac ticket #1487064_

http://trac.roundcube.net/wiki/Dev_Guidelines describes coding standards for roundcube. Those standars are based on PEAR standards with slight modifications. However, I guess there is no obligatory requirement to follow them:

```
phpcs --standard=PEAR rcmail.php
...
--------------------------------------------------------------------
FOUND 948 ERROR(S) AND 116 WARNING(S) AFFECTING 846 LINE(S)
--------------------------------------------------------------------
```

Will it make sense, if I write a new coding standard for PHP_CodeSniffer based on PEAR standars? This will make it easier to check the code for coding standards errors before actually commiting it. Anyway, sticking to coding conventions would increase code homogenity, which in turn would result in better maintainability. 

_Migrated-From: http://trac.roundcube.net/ticket/1487064_

**Comment by alecpl** [comment]
No volunteers? Sorry.
