### ISSUE TITLE
Better treatment for namespace roots

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5012]
_Reported by brandond on 26 Oct 2010 09:09 UTC as Trac ticket #1487084_

Namespace roots are currently displayed as just a regular unselectable top-level folder, and they and their children are just sorted in with the normal list of folders.

It would be nice if there was some indication (a special icon perhaps) of the special status of the root folder, and if it was sorted specially in the folder list. I'm not sure if it belongs at the top, or bottom, or what, though.

_Migrated-From: http://trac.roundcube.net/ticket/1487084_

**Comment by alecpl** [comment]
PR created. Ready for testing. For now different icons are only applied in the Elastic skin.
