### ISSUE TITLE
Message on a common thread viewed on a single page

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5014]
_Reported by Jehan on 7 Nov 2010 18:23 UTC as Trac ticket #1487106_

Hi,

currently messages in email boxes can be seen either individually or by threads (the display can be chosen), which is nice. But I think either the thread view can be improved or else a third view can be added: when selecting a branch in the thread, the whole discussion would be displayed (with possibility to hide message's contents). 

This would probably look similar to the Gmail interface, which is pretty good on the matter, but with a better tree-view display: if A is the first message, and B1 and B2 are answers to A, and C1 is answer to B1, clicking B1 or C1 would show only A, B1 and C1 (and not B2 on another branch).
And for instance if I click A, it could show me B1 and B2, with the possibility to read further in one branch by clicking.

Of course a plain "all messages in the same thread" view (Gmail-like) can also be useful sometimes (it can be a fourth display option).

Most of the time, a discussion with only a few messages is "ok", but when I begin to have from 5 or 6 messages (up to a lot lot lot), then trying to find back some old message, having to click through dozens of them, that's just annoying. Or worse, sometimes I get my answer but then I want to re-read the initial message, so I must reload it: what a waste of time, whereas with the thread view in one page, I can see question and response in the same page with one single load.

Plus, it is more efficient to see the whole discussion at once. Participating at stuffs like IETF mailing list, some on a Gmail account, some on my personal email server which runs Roundcube, I can assure you, having to read dozen of messages individually is such a hassle compared to when I can read the whole discussion in a single page.

Thanks for Roundcube anyway, that's a nice software!

_Keywords: thread gmail_
_Migrated-From: http://trac.roundcube.net/ticket/1487106_

**Comment by alecpl** [comment]
Duplicate of #499.
