### ISSUE TITLE
Support salted passwords

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5016]
_Reported by tex on 19 Dec 2010 15:45 UTC as Trac ticket #1487642_

Please support the use of salted passwords in the _password_ plugins sql driver.

Changing salted passwords works using the dovecotpw method, but it'd be great if there were a way to verify these passwords, too.

At the moment it is possible to change the password, but one must not include the current/old password in the SQL update query. It is not sufficient to just hash the current password since it must be hashed with the salt that was used when the current password was initially hashed.

The solution would require extracting the salt from the existing hash in the database and hashing the supplied _current_ passwords with the given salt to be able to compare the hashes.

For more information see the [Dovecot Wiki on Salting](http://wiki.dovecot.org/Authentication/PasswordSchemes#Salting). There is also information on how this can be done in Perl. If nobody is working on this yet and my PHP knowledge is sufficient, I'll try to supply a patch later.

_Migrated-From: http://trac.roundcube.net/ticket/1487642_

**Comment by alecpl** [comment]
It looks to me that in 11 years no one needed that feature. Provide a PR and we'll re-consider.
