### ISSUE TITLE
Update identies from query/file even after user creation

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5018]
_Reported by framelio on 15 Jan 2011 12:02 UTC as Trac ticket #1487691_

Sometimes the identities are changing after the first user login and when identities_level is set to 1 (many identities with possibility to edit all params but not email address) there is no way to add new email addresses.

This happens in setup where the Provider is adding new services (i.e. a new domain and mailboxes for the user).

Would be nice to have a possibility to execute "virtuser_query" or "virtuser_file" (and update the identities) either everytime the users goes to the identities settings page or when the user is requesting it (with a button?).

_Keywords: identities_
_Migrated-From: http://trac.roundcube.net/ticket/1487691_

**Comment by alecpl** [comment]
Wontfix. You can write a plugin.
