### ISSUE TITLE
Mail count in folder list

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5019]
_Reported by repli2dev on 16 Jan 2011 20:43 UTC as Trac ticket #1487695_

It would be great to enable showing of total mail count in folder list.
As I use some folders to divide different task I need to known they are some mails in it ;-)

_Keywords: mail, count_
_Migrated-From: http://trac.roundcube.net/ticket/1487695_

**Comment by alecpl** [comment]
I don't see much interst in this feature. Wontfix. Write a plugin.
