### ISSUE TITLE
Attach files method

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5024]
_Reported by lingfude on 18 Feb 2011 11:25 UTC as Trac ticket #1487793_

Hi[think the current method of attach files has to many steps and clicks to do a simple task as attach files.[[BR]([BR]]
I)]
In the image attached I show you what is redundant and what is only need to attach files.[[BR]]
I hope you accept my suggestion and change the way Roundcube attach files.

_Migrated-From: http://trac.roundcube.net/ticket/1487793_

**Comment by alecpl** [comment]
We're dropping legacy browsers support in 1.3. Now it should be simpler to implement this. I hope to have time to implement this in 1.3.

**Comment by alecpl** [comment]
Done.
