### ISSUE TITLE
A config option for custom watermark

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5025]
_Reported by brandond on 3 Mar 2011 02:16 UTC as Trac ticket #1487816_

A recent change to trunk added a new config option for custom logo. It would be nice if there was a similar option for the watermark image. Having both of these made configurable would remove almost all of my local skin customizations, and let me go back to the stock files.

_Migrated-From: http://trac.roundcube.net/ticket/1487816_

**Comment by ad221282** [comment]
I can change the watermark to my logo, open the root file where roundcube is hosted, C:/roundcube/skins/larry and classic/images put your logo .gif, then in the larry/classic folder there is a watermar.html, open it with dreamweaver and replace the path of the old watermark for the new one, save it and ready!
PS. dont forget to clear your browsing data in order to check if it works or not!

**Comment by thomascube** [comment]
There's a plugin for this: https://plugins.roundcube.net/packages/roundcube/customizr

**Comment by tomsommer** [comment]
At least allow us to modify it using CSS/LESS? There is no CSS file imported in `watermark.html`

**Comment by alecpl** [comment]
There's undocumented `blankpage_url` (default: `/watermark.html`). I guess we should document that and see if that's it.

Extending `skin_logo` to work on watermark page will be much more complicated.

**Comment by gianlucagiacometti** [comment]
I used a tmp file if it may be useful:
https://github.com/gianlucagiacometti/roundcube-toolbox

**Comment by alecpl** [comment]
Option documented with
```
// Location of the blank (watermark) frame page. By default it is the watermark.html
// file from the currently selected skin. Prepend name/path with a slash to use
// current skin folder. Remove the slash to point to a file in the Roundcube
// root directory. It can be also a full URL.
$config['blankpage_url'] = '/watermark.html';
```
