### ISSUE TITLE
Add "Junk" column

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5026]
_Reported by gerundt on 21 Mar 2011 14:39 UTC as Trac ticket #1487839_

I like the "Junk" column from Thunderbird where you can see the junk status from a mail. This patch adds the column for roundcube too.

It checks the JUNK imap flag of a mail and show a exclamation icon ("exclamation.png" from the FamFamFam silk icon set) in the column.

A next step could be to also set the junk status from the column (like the flagged column do), but this is my first patch to the project and I need more experience. So be not too hard, if something is not perfect with the patch. ;-)

Greetings,
Tim Gerundt

_Migrated-From: http://trac.roundcube.net/ticket/1487839_

**Comment by alecpl** [comment]
I think this will not happen in the 3-column layout we use these days.
