### ISSUE TITLE
QR-Code Support

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5030]
_Reported by lacri on 26 May 2011 07:06 UTC as Trac ticket #1487936_

a nice Feature for the Roundcube Addressbook are QR-Code Support ... Display in Addressbook for every User the vcard without photo as QR-Code so can users add quickly with a mobile phone eg android or iphone contacts to the mobile phone. A other nice place for QR-Code is send optional as attachment like as vcard.

See http://en.wikipedia.org/wiki/QR_code
http://phpqrcode.sourceforge.net/
http://code.google.com/intl/de-DE/apis/chart/image/docs/gallery/qr_codes.html

_Migrated-From: http://trac.roundcube.net/ticket/1487936_

**Comment by alecpl** [comment]
Some useful links:
https://github.com/endroid/QrCode
http://blog.qr4.nl/page/QR-Code-Data-Capacity.aspx

**Comment by alecpl** [comment]
Implemented.

**Comment by Takika** [comment]
I also done this with the same library as a plugin for myself :)
