### ISSUE TITLE
Calculate default folders list width

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5035]
_Reported by @alecpl on 13 Sep 2011 06:55 UTC as Trac ticket #1488082_

There are some users that doesn't like cookies (and are removing them when closing browser). There are also some users wanted full folder names to be displayed on folders list.

The request is to add an option to change (calculate) splitter position, when cookie is not set, to display not truncated folder names. Of course there should be some limit of max width, e.g. 1/3 of page width.

Another option is to store splitter position in database instead of cookies. The decission should be per-user (via user preferences).

_Migrated-From: http://trac.roundcube.net/ticket/1488082_

**Comment by alecpl** [comment]
This actually is too rare case to bother.
