### ISSUE TITLE
Password Plugin - more password strength checking options

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5040]
_Reported by fraggy on 20 Dec 2011 10:49 UTC as Trac ticket #1488268_

Hi,

we are using the password plugin to change passwords in LDAP.
It would be nice, if there are options to be more strict when choosing a new password.

required:
- Password Minimum Length: 8 chars (password_minimum_length allready implemented)
- Contain characters from 3 of the following 4 categories: English uppercase characters (A through Z), English lowercase characters (a through z), Base 10 digits (0 through 9), Non-alphabetic characters (for example, !, $, #, %)

nice to have:
- min. 2 different chars between old and new password (pam_cracklib Option difok=2)
- Not contain the user's account name or parts of the user's full name that exceed two consecutive characters

regards,
Maik

_Migrated-From: http://trac.roundcube.net/ticket/1488268_

**Comment by crazy4chrissi** [comment]
I think it would be perfect if you could integrate zxcvbn, which is the password strength estimation developed at Dropbox:
https://blogs.dropbox.com/tech/2012/04/zxcvbn-realistic-password-strength-estimation/
https://github.com/dropbox/zxcvbn
https://github.com/bjeavons/zxcvbn-php

It allows much better password strength checks than these simple rules. And it allows to show the user a rank of his password strength as he types.

**Comment by razyr** [comment]
I'd like to add my voice to the requests for ZXCVBN integration.  It does a far better job than simple rules such as "must contain at least one special character" and is relatively easy to integrate into existing portals or applications.   As crazy4chrissi mentions, it provides the user direct password strength feedback as they are entering their password and it has a nice clean UI.

![2016-12-06_09-31-54](https://cloud.githubusercontent.com/assets/8116645/20930554/d7c27218-bb9b-11e6-9d5f-58b2a9579bab.png)

**Comment by torbjo** [comment]
Just a side note: When using ldap I think its more sane to implement
password policy checking on the (ldap) server.

With OpenLDAP use the ppolicy module/overlay:
* <http://www.openldap.org/doc/admin24/overlays.html>
* <http://www.zytrax.com/books/ldap/ch6/ppolicy.html>

But for the other password backends it's a nice feature to have.

**Comment by alecpl** [comment]
An option could be also HaveIBeenPwned.com API use: https://haveibeenpwned.com/API/v2#SearchingPwnedPasswordsByRange

**Comment by crazy4chrissi** [comment]
@alecpl Good point. Or we could just add haveIBeenPwned as a matcher to zxcvbn. Which is what I just did:

https://github.com/crazy4chrissi/zxcvbn-php/commit/181e49465a4bc2c56bc3a4bd78ca1f01e5d58d5c

**Comment by alecpl** [comment]
API extended. Added zxcvbn driver.
