### ISSUE TITLE
Add a field to contacts table to reflect the contact source

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5042]
_Reported by neubauer on 7 Jan 2012 09:19 UTC as Trac ticket #1488294_

Some plugins are using a copy of the contacts table to store their data, this way lacking the contact group allocation functionality. To get the group allocated, the "contact_id" is not unique within all the contacts.
To get things together it would be helpful to store those records within the contacts table, giving the plugings a field like "contact_source" to manage the contact sync for a plugin differently in a pre/post update situation.
All those 3rd party addressbooks could then benefit from the group allocation system as well.

_Keywords: 3rd-party contacts field request_
_Migrated-From: http://trac.roundcube.net/ticket/1488294_

**Comment by alecpl** [comment]
Wontfix.
