### ISSUE TITLE
Plugin 'markasjunk': Move spam to another IMAP folder

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5044]
_Reported by Bibby on 16 Mar 2012 04:36 UTC as Trac ticket #1488400_

Dear developer,

Can we configure plugin 'markasjunk' to move spam to another IMAP folder instead of 'junk_mbox ' configured in main.inc.php? Then we can configure SpamAssassin to auto-learn SPAM in this folder.

Folder 'Junk' will be used to store system detected spam, but another folder (e.g. Spam) will be used to store user reported spam.

Another solution is merging third-party plugin here: http://www.tehinterweb.co.uk/roundcube/#pimarkasjunk2

It "adds a new button to the mailbox toolbar to mark the selected messages as Junk/Not Junk, optionally detaching original messages from spam reports if the message is not junk and learning junk/not junk using various methods (sa-learn, etc.)."

_Keywords: markasjunk_
_Migrated-From: http://trac.roundcube.net/ticket/1488400_

**Comment by alecpl** [comment]
Done with #6504.
