### ISSUE TITLE
Don't save "always show images from" as contacts

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5046]
_Reported by helix45 on 10 Jul 2012 15:20 UTC as Trac ticket #1488559_

Whenever I click "Always show images from user@domain.tld" a new contact is made in the addressbook. After selecting some verified senders the addressbook get's bigger, without using these contacts as reciepients (ex. newsletters). I don't really like that. Why not using a whitelist off from the addressbook? The images from known senders AND the whitelist are displayed always (when selected in preferences). I've seen this feature in a lot of other web clients (gmail, gmx, yahoo).

_Migrated-From: http://trac.roundcube.net/ticket/1488559_

**Comment by alecpl** [comment]
We'll most likely create a separate (special) addressbook.

**Comment by alecpl** [comment]
Implemented "trusted senders" addressbook feature.
