### ISSUE TITLE
Make width of list columns adjustable from the UI

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5049]
_Reported by rejkelie on 7 Sep 2012 05:26 UTC as Trac ticket #1488679_

Feature request:

It would be very useful if the columns in the mail list (Subject, From etc.) would be adjustable from the UI.

As it is now they all have fixed width which is defined in the CSS for the theme.

_Keywords: columns, width_
_Migrated-From: http://trac.roundcube.net/ticket/1488679_

**Comment by alecpl** [comment]
Not that important in 3-column view we use these days.
