### ISSUE TITLE
Regex-restricted alternate e-mail addresses

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5058]
_Reported by Guillaume Outters on 27 Jan 2013 16:59 UTC as Trac ticket #1488932_

For a provider allowing users to receive e-mails on arbitrarily suffixed e-mail addresses, it would be nice that _sent_ e-mails too could come from the suffixed address, without the user having to configure an alternate address.

For example, I have configured my mail server so that all xxx-yyy@host.eu go to the xxx@host.eu mailbox. Thus, my wife can generate safe one-round-use (she-ykh67kjfz@host.eu), contextual (she-order-67832@host.eu) or service-linked (she-yahoo@host.eu) addresses, and use them to hide her real address from potential mass-marketers, exposure on website, or spammers crawling badly protected address books of friends; or to track, for example, some e-commerce orders or files with administration.

Now, what do I want?
1. When I receive an email to me-gmail@host.eu, I would like my reply to be automatically coming from me-gmail@host.eu.
2. Even better, I would like to be able to start an e-mail from scratch while typing such an address. Of course, my server admin wants to ensure I only modify the suffix part of my address.

The attached patch (working against version 0.8.5) implements my 1.
It allows the admin to add a parameter:
$rcmail_config[= '%u([-_]('identities_email_restriction'])[-a-z0-9_]*)@%d';
which does the job.

(I have made the patch trying to respect the coding conventions of the files I was in; however, if new developments in old files are asked to respect the new coding guidelines, I would be glad to submit the patch reformatted)

_Migrated-From: http://trac.roundcube.net/ticket/1488932_

**Comment by alecpl** [comment]
Sounded interesting, but it's not a common request and requires server-side support. Write a plugin.
