### ISSUE TITLE
Persian Date Plugins

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5061]
_Reported by respinar on 12 Mar 2013 17:10 UTC as Trac ticket #1488993_

Is it possible to have a Persian Date Plugins. I wrote a date class, but I don't know how to write a plugins. So, can you help me?

_Keywords: date_
_Migrated-From: http://trac.roundcube.net/ticket/1488993_

**Comment by alecpl** [comment]
We could add plugin API hooks where needed if we receive a specific request, but we'll probably not work on this any time soon. Pull requests welcome.
