### ISSUE TITLE
Compose icon in top navigation bar

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5063]
_Reported by rosali on 11 Apr 2013 05:27 UTC as Trac ticket #1489041_

We have now compose in new window feature. It would be handy to have a compose icon in the top navigation bar.

Usecase example:

A user is in a plugin page (f.e. calendar/sticky_notes/planner/tasks) and wants to compose a message. It would be handy not having to leave the (plugin) task to compose a message.

_Migrated-From: http://trac.roundcube.net/ticket/1489041_

**Comment by alecpl** [comment]
Done in Elastic, we do not plan to implement this in other skins.
