### ISSUE TITLE
Retina optimised icons

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5064]
_Reported by vatter69 on 18 Apr 2013 10:34 UTC as Trac ticket #1489049_

Using Roundcube 0.9 and all icons and other graphics look quite fuzzy when used on a Retina or other form of HighDPI screen.

Maybe something to consider to include hi-res icons, at least as an option during the install in future releases.

_Migrated-From: http://trac.roundcube.net/ticket/1489049_

**Comment by alecpl** [comment]
Elastic skin uses font-icons, we do not plan to work on old skins in this context. Wontfix.

**Comment by paulmenzel** [comment]
Could you please elaborate? Currently the three skins *classic*, *elastic*, and *larry* are shipped, where *larry* is the default.

https://github.com/roundcube/roundcubemail/blob/1423536ce0cb4b740b7a3f18f4f0553484c97833/config/defaults.inc.php#L1054

I am using the lastest version from the master branch, and the icons are blurry with that. Is *larry* considered an “old” skin?
