### ISSUE TITLE
Allow to omit Subject header

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5068]
_Reported by Filou on 26 May 2013 19:45 UTC as Trac ticket #1489126_

When composing an email message I can leave the Subject field empty resulting in a "Subject: " header. I would love to be able to completely omit the Subject header just as I can using mutt. Of course most tech people see the Subject header as an important part of an email that should provide a kind of abstract. But fact is most messages I receive from friends and family nowadays don't have a useful Subject. Many people do email on the go and use it as an SMS or chat alternative--quick and to the point. The Gmail web UI works around this problem by displaying the first words of the actual message next to the subject.

So adding a delete button next to the Subject field would be a great enhancement. A setting to omit the Subject field by default just as the fields Cc, Bcc, etc. would be perfect. BTW there is no RFC that describes the Subject header as mandatory.

Keep up the good work!

_Migrated-From: http://trac.roundcube.net/ticket/1489126_

**Comment by alecpl** [comment]
Done without touching how we display no-subject messages for now.
