### ISSUE TITLE
Drag & Drop for Contacts from "To" to "CC"

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5069]
_Reported by backi on 1 Jun 2013 19:50 UTC as Trac ticket #1489141_

I dont know if this is a browser issue or a possible feature for roundcube. Mark Emailadresses/contacts from "To" or an other field and move or copy them to CC or BCC

_Keywords: Drag&Drop_
_Migrated-From: http://trac.roundcube.net/ticket/1489141_

**Comment by chilek** [comment]
Copy&paste shortcuts do not work for ELASTIC skin so it's mission impossible for that.
You have to copy mail address using web browser dom inspector :(

**Comment by chilek** [comment]
Ohhh I use release-1.4 branch HEAD.

**Comment by alecpl** [comment]
Done for Elastic.
