### ISSUE TITLE
Do not mark automatically as read

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5071]
_Reported by dtech on 11 Jun 2013 21:18 UTC as Trac ticket #1489165_

As I like to mark messages as read only when I processed them (i.e. they require no further attention) I like to disable email clients automatically marking messages as read. However this is unavailable in Roundcube 0.9.1 except for the preview pane

Functionality should be similar to Thunderbird's Option in Advanced->Reading & Display->"Automatically mark messages as read" which is check by default (and should be default behavior in roundcube too)

I'm not sure what this option should do with the existing "Mark previewed messages as read" (which only applies to the preview pane). I guess this this should be renamed "Mark previewed messages as read in preview pane" and a new option "Mark previewed messages as read when opening" should be added.

_Migrated-From: http://trac.roundcube.net/ticket/1489165_

**Comment by alecpl** [comment]
I think we should keep the old option and make it working in both scenarios. It would be really a rare case when someone wanted two different behaviors for each case. Either someone is using preview pane or not. I'm not sure we can keep "previewed messages", maybe we'd need to use "opened messages" instead.

**Comment by alecpl** [comment]
This is now implemented in dev-layouts branch, which is planned for inclusion in 1.3-beta.

**Comment by alecpl** [comment]
Merged into master.

**Comment by urusha** [comment]
Just want to mention that some people like previous behavior (view in preview panel doesn't mark messages as read), that would be nice to have an option to get this back.
