### ISSUE TITLE
Implement disable_sent_date_sort as configurable option

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5072]
_Reported by burnleyvic on 18 Jun 2013 00:04 UTC as Trac ticket #1489177_

Initial discussion started here:
http://trac.roundcube.net/ticket/1488171#comment:7
I've seen cases involving mailboxes with large numbers of messages where the IMAP server is really struggling to respond to a command like this one:
A0007 FETCH 1:\* (UID INTERNALDATE BODY.PEEK[(DATE)](HEADER.FIELDS))
The response time dropped from more than 3-4 minutes at times to less than 30 seconds when the command used was:
A0007 FETCH 1:\* (UID INTERNALDATE)
This implies disabling sort by sent date, in which case only sorting by arrival date is available. In our environment using this IMAP command is a reasonable compromise between features/usability and performance, we can afford to make this sacrifice to improve the IMAP server, hence webmail responsiveness.
Having a tunable we can flick on/off if needed would be useful because we won't have to maintain a custom rcube_imap_generic.php just to disable the messages sort by sent date. The idea can be taken even further and we can use another tunable named disable_sent_date_sort_limit which defines the maximum number of messages in a mailbox beyond which the sort by sent date will be disabled.

_Migrated-From: http://trac.roundcube.net/ticket/1489177_

**Comment by alecpl** [comment]
In general for (slow) servers without SORT capability I propose to use sort_col='', which will sort messages by uid, which is almost the same as sort_col=arrival.
