### ISSUE TITLE
Files outside of imap root exposed despite setting imap_ns_* options

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5073]
_Reported by cepheid on 18 Jun 2013 00:42 UTC as Trac ticket #1489181_

I don't know if this counts as a bug or not, but I couldn't find any solutions for it and it feels like a bug.  On my new install (RC 0.9.2 on CentOS 5.8, php 5.2.17, using sqlite3 DB, with uw-imap 2007b [Pro Control Panel version](Parallels)), RC is exposing all files in a user's home directory despite the namespace override options being set in main.config.inc.

All of the user mail folders are in ~/mail ... The ancient imapd that my server must run does not support namespaces but, for example, SquirrelMail allows setting of the "default mail folder" to artificially restrict the client to only the mail folder (so setting it to "mail/" shows only the files in that directory, and nothing else).  I saw that RC used to have an imap_root config option, but this does not seem to be supported any longer -- at least, it's not present in the main.config.inc.  I did set all of the imap_ns_\* options (imap_ns_personal, imap_ns_shared, imap_ns_other) to "mail/" but this did not help...

Specifically, while setting the imap_ns_\* options _DID_ clean up the folder display on the main page (i.e. it no longer showed the mail/ directory itself, just the folders within it), the folder subscription page (Settings -> Folders) still exposes everything in the user's home directory (the mail directory itself, public_html, etc.).

Shouldn't the imap_ns_\* options restrict RC from showing things outside of these directories?

How can I get RC to show _only_ those folders in the mail directory, and nothing else?  Is imap_root still supported, or is there some other option I'm missing?  Or is this a bug and the imap_ns_\* options are not working fully correctly?

I am happy to post screenshots, logs, whatever is needed.  Please provide instructions if you need logs with debugging info.  Thanks.

_Migrated-From: http://trac.roundcube.net/ticket/1489181_

**Comment by alecpl** [comment]
With the above commit following configuration can be used to achieve the requested behavior:
```
$config['imap_ns_personal'] = 'mail/';
$config['imap_ns_other'] = null;
$config['imap_ns_shared'] = null;
```
