### ISSUE TITLE
Increase mail composing area size

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5074]
_Reported by rd228c on 24 Jun 2013 03:46 UTC as Trac ticket #1489198_

The area for composing email is too short (even with the new window feature).
In the main window, with all the to/cc/subject and tinymce there isn't half of the window available.
In a new window, there is just half of the window available.

Ideas: The to,cc,bcc boxes could be 1 line height by default and extend to 2 lines if there are a lot of recipients.
The top menu icons (which is quite big) could be shifted to the left area on top of contacts tab (at least for the separate composing window).

Note: I am using roundcube on a laptop with 1366x768 resolution. 

_Migrated-From: http://trac.roundcube.net/ticket/1489198_

**Comment by thomascube** [comment]
Wontfix. Likely to become obsolete with the elastic skin.
