### ISSUE TITLE
Mark all messages in subfolders as read

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5076]
_Reported by backi on 30 Jun 2013 06:21 UTC as Trac ticket #1489212_

I dont know I this would be useful for all users, but I'd like to have a feature that marks all messages in alle subfolders as read. So I do not have to click in each folder an mark the messages as read. (I'm sorting incoming mail on server-side in subfolders)

_Keywords: mark messages_
_Migrated-From: http://trac.roundcube.net/ticket/1489212_

**Comment by alecpl** [comment]
Implemented.
