### ISSUE TITLE
Store contacts w/o mail-address

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5079]
_Reported by mrtux on 13 Jul 2013 18:02 UTC as Trac ticket #1489243_

Roundcube should allow to store contacts w/o mail-addresses.

I use Roundcube to store all my contacts and do not want to use another tool to store contacts w/o email-addresses...

_Migrated-From: http://trac.roundcube.net/ticket/1489243_

**Comment by alecpl** [comment]
Done.
