### ISSUE TITLE
Show message flagged status in message view

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5080]
_Reported by gary on 2 Aug 2013 15:01 UTC as Trac ticket #1489272_

Can you please add some indication of an email's flagged status while reading the email? Currently the email is highlighted in the mailbox view, but once the email is opened there's no way to tell if it's flagged or not.

My workflow is often to go through my "to followup" folder, opening an email to read it, and then moving it to the proper mailbox from the message view screen. However, if I had flagged the email for attention, I want to clear that flag before filing the email away. Right now I have to either compulsively "Mark as unflagged" all emails before moving them to their proper mailbox, or I have to go back to mailbox view to see if the email was flagged so that I remember to mark it as unflagged.

Thanks,
Gary

_Migrated-From: http://trac.roundcube.net/ticket/1489272_

**Comment by alecpl** [comment]
I think the main problem here was that you didn't used a preview, but opened messages in full screen mode.

Anyway, I think it makes sense, especially now in Elastic mobile mode.

**Comment by alecpl** [comment]
Done for Larry and Elastic.
