### ISSUE TITLE
Integrate Sabre VObject 3 into Roundcube

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5082]
_Reported by phs on 9 Aug 2013 06:36 UTC as Trac ticket #1489278_

I'm not sure, if it would add value compared to using rcube_vcard.php.

But maybe it should be evaluated.

_Migrated-From: http://trac.roundcube.net/ticket/1489278_

**Comment by alecpl** [comment]
Looks like no one was interested in doing that. Patches welcome, but I'm closing this ticket.
