### ISSUE TITLE
Compose screen resized when keyboard appears in Android 4

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5083]
_Reported by lucaferr on 2 Sep 2013 09:00 UTC as Trac ticket #1489315_

Hi,
while on the iPad touching the compose textarea makes the keyboard appear over the page and the screen centered on the textarea, so it's comfortable to write the message, in Android 4 (tested on a Galaxy Note 10.1 running Android 4.1.2, stock browser) the whole screen is automatically resized and the the screen is not centered on the textarea. The message area becomes so tiny that it's very difficult to write the message (it is necessary to scrool the tiny area until the textarea appears and then it's necessary to scroll again every 2 rows).
See the screenshot attached.

_Migrated-From: http://trac.roundcube.net/ticket/1489315_

**Comment by alecpl** [comment]
This is not an issue in the Elastic skin. We do not plan fixes for other skins.
