### ISSUE TITLE
Automatic identity selection based on Received: header content

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5085]
_Reported by jeround on 27 Sep 2013 12:44 UTC as Trac ticket #1489360_

Hi.

When I reply to a message, the identity is automatically selected to match the address the message was sent to.

But this fails when the original message was received through a list.

I didn't look in the code (yet) but it looks like the test is on the To: field.

To get the expected behaviour, the address to use would be in one of the Received headers.

Received: from xxx.com (xxx.com [ip.ip.ip.ip])
    by domain.tld (Postfix) with SMTP id DEADBEEF
    for alias@domain.tld; Sun, 15 Sep 2013 11:22:29 +0200 (CEST)

The Delivered-To: fields don't provide the alias we need to select the correct identity. Neither does the To: field, obviously.

Is this a bug, or a known limitation ? Feel free to change into feature request, if appropriate.

Software version: 0.7.2-9~bpo60+1 from Debian Squeeze backports.

Thanks.

_Migrated-From: http://trac.roundcube.net/ticket/1489360_

**Comment by alecpl** [comment]
Done.
