### ISSUE TITLE
Password change plugin - Windows AD and Local SQL mixed users

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5086]
_Reported by leo the one on 9 Oct 2013 06:52 UTC as Trac ticket #1489367_

Hello,

I've configured and it's working the password change plugin for the local SQL database but is it possible to have at the same time tha password change also for the Windows AD LDAP users?
Actually dovecot is authenticating against SQL and LDAP (Windows AD) and i would like to also have the Roundcube password change plugin able to change on both (SQL and LDAP).
Thanks,

Leo.

_Migrated-From: http://trac.roundcube.net/ticket/1489367_

**Comment by alecpl** [comment]
After more thinking... Wontfix. This is really rare use-case.
