### ISSUE TITLE
Filter/delete messages by specific date

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5087]
_Reported by azurtem on 18 Oct 2013 07:09 UTC as Trac ticket #1489384_

Hi

My client's users have accumulated a history of received and deleted messages which I am required to 'clean up'

For the Trash there is no complication, just empty its contents

But for the Sent Items folder it's a little more complicated because I need to retain messages received after the 1st of June of this year

Is there a way to filter messages in a folder based on date ?

_Migrated-From: http://trac.roundcube.net/ticket/1489384_

**Comment by alecpl** [comment]
There are "younger/older than a year" filters in Roundcube 1.2. So, not a precise date, but close.

**Comment by MarceloPedra** [comment]
Hello guys, would you wonder to add this feature to Roundcube to allow to find emails in a given range of time? It woud be very useful.

**Comment by johndoh** [comment]
there are in the search options. if you open the menu in the message search box there is a date filter dropdown

**Comment by alecpl** [comment]
Close in favor of #6006.
