### ISSUE TITLE
Managesieve: Mailman tool

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5088]
_Reported by Hlhj on 19 Oct 2013 14:19 UTC as Trac ticket #1489385_

If you've just signed up to a bunch of lists, making filters  and folders to sort them is tedious. Manually sorting the old messages is also tedious. 

To reduce the tedium:
1. A tool to apply a filter to already-received mail would be good (I can't see one, sorry). 
2. Allowing the user to create the target folder as they create the filter (in the same form/page) would save time.
3. Best of all, a tool that would automatically recognize Mailman mailing lists, create a set of folders and filters to match, and offer it up for my approval (e.g. make a folder "Foo", and put every message with "[Foo]" in the subject in it). 

The last tool could offer itself once by default when the user first gets a mailing list message.

I don't think I can get this functionality by editing the Sieve file as it would involve making folders and using variables.

_Keywords: filter, create folder, Mailman, list, mailing list_
_Migrated-From: http://trac.roundcube.net/ticket/1489385_

**Comment by alecpl** [comment]
Sounds like an idea for an extra plugin. Not in core.

**Comment by trasherdk** [comment]
While this sounds like a great feature, not only for mailman, but recognizing mail lists in general, github springs to mind, it sounds like a serious job.

I'd love to see something like this in the future.
