### ISSUE TITLE
Cleanup compose session data

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5089]
_Reported by @alecpl on 7 Nov 2013 10:52 UTC as Trac ticket #1489418_

The session data of compose action (e.g. attachments list) is cleaned up only after the message is sent. If user leaves composed message this data is not cleaned up. This may cause infinite session data size growth.

_Migrated-From: http://trac.roundcube.net/ticket/1489418_

**Comment by alecpl** [comment]
Actually, since users can open another window with Shift+Right click from compose window, the only way to do this is compose-keep-alive method described above. This however, is not simple and tricky. I abandon the idea. We'll get back to it when it becomes a real issue.
