### ISSUE TITLE
Acceppt ";" also as address-separator (additional to ",")

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5092]
_Reported by backi on 8 Dec 2013 20:08 UTC as Trac ticket #1489466_

I think currently is only "," allowed as separator between mail-addresses. I think it would be useful also to allow ";" as this is the "outlook standard"
Thanks

_Migrated-From: http://trac.roundcube.net/ticket/1489466_

**Comment by alecpl** [comment]
Fixed.
