### ISSUE TITLE
Compose attachment pane too large using browser zoom

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5095]
_Reported by mrjoel on 20 Jan 2014 19:36 UTC as Trac ticket #1489528_

When using a high resolution display and increase browser zoom level (to 150-200%), the compose window shows the attachment pane filling way too much of the editing space. At 200%, the attachment pane is about 80% of the total editor space and nearly unusable. It looks like some relative scaling between the two is needed.

_Migrated-From: http://trac.roundcube.net/ticket/1489528_

**Comment by alecpl** [comment]
I can't reproduce. What browser and window size? Works for me on desktop and Roundcube skins are not designed for mobile devices.
