### ISSUE TITLE
Allow downloading/vieweing attachments from compose window

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5096]
_Reported by mrjoel on 25 Jan 2014 16:12 UTC as Trac ticket #1489537_

I have many times wanted to download attachments from the compose windows, usually when continuing a draft and wanting to confirm version of attachments.

The down arrow image in the attachments pane always make me think it is to download attachments instead of a drop upload target.

_Migrated-From: http://trac.roundcube.net/ticket/1489537_

**Comment by alecpl** [comment]
Duplicate of #5053.
