### ISSUE TITLE
Settings - Composing Messages: cant change default action of replying to "do not quote" action directly

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5097]
_Reported by nergall on 21 Feb 2014 10:14 UTC as Trac ticket #1489636_

Hi there.

There seems to be some kind of bug, in

Settings -> Preferences -> Composing Messages -> When replying

The default action here is "start new above". If you want to change it to "do not quote", you must at first change it to "reply below".

After that, it works fine in any way.

The important thing is, that it realy must be the default vaule, so the setting is not already present in database. When in db is, in table 'users' in 'preferences' in that account, the "reply_mode" set to anything, it works ok. When you remove the "reply_mode" from serialised array, you can see the problem again.

Thank you for looking into this.

_Migrated-From: http://trac.roundcube.net/ticket/1489636_

**Comment by alecpl** [comment]
I'm unable to reproduce in 1.1.
