### ISSUE TITLE
Login Page: send header "X-Robots-Tag: noindex,nofollow"

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5098]
_Reported by Steffen on 21 Mar 2014 14:06 UTC as Trac ticket #1489710_

The Roundcube login page contains the following meta tag:

```
<meta name="Robots" content="noindex,nofollow" />
```

But this meta tag has no effect because Roundcube's robots.txt tells Google not to look at the contents of any file:

```
User-agent: *
Disallow: /
```

Result: Google does not index any contents but shows an entry for the domain on its search results page like this:

```
mail.example.org
A description for this result is not available because of this site's robots.txt
```

You can remove this entry by sending the HTTP header "X-Robots-Tag" on the login page:

```
header('X-Robots-Tag: noindex,nofollow');
```

See https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag

_Migrated-From: http://trac.roundcube.net/ticket/1489710_

**Comment by alecpl** [comment]
Removed robots.txt and <meta> tags. Added X-Robots-Tag in .htaccess.
