### ISSUE TITLE
Image proxy

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5099]
_Reported by Chumba on 9 Apr 2014 17:33 UTC as Trac ticket #1489786_

Hi,

It would be nice to consider adding an image proxy to Roundcube.

First, an image proxy proxies all remote image requests through the server on which Roundcube is installed, thus maintaining the privacy of the individual user who is accessing his mail account via Roundcube and viewing mails with remote images.

Second, an image proxy allows https pages to remain "secure" - i.e. you can avoid the mixed-content warnings that modern browsers now flag with a triangle or similar.

See here for some implementation suggestions:
- http://gmailblog.blogspot.ch/2013/12/images-now-showing.html
- https://github.com/blog/1766-proxying-user-images
- http://xenforo.com/community/threads/exif-rotation-acp-searching-proxying-and-change-logging.66592/

Chumbi

_Migrated-From: http://trac.roundcube.net/ticket/1489786_

**Comment by alecpl** [comment]
For privacy CSP/no-referrer should be used. In my opinion mixed content prevention is not enough to spend time on this. Anyway, something for a plugin.
