### ISSUE TITLE
support replying to plain-text part of a multipart message even when viewing html

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5100]
_Reported by apaku on 11 Apr 2014 10:32 UTC as Trac ticket #1489797_

Our commit mails are multipart to leverage some html features, they have the same content in a plain text and a html form (the latter just has links and a bit of coloring applied).

So users want to view the html part since that makes the reading much easier. However when replying the stripping of html tags and de-duplication of whitespace completely breaks the diffs that are part of the commit mails.

So what we'd like to have is a way to reply to multi-part mails and enforce usage of the plain-text part of the mail for composing the reply.

The only way right now to get that is to disable the html-preview, but as I said thats not an option for us.

_Migrated-From: http://trac.roundcube.net/ticket/1489797_

**Comment by rmcaninch** [comment]
In the case that the plain text part looks like a generic "this is a HTML formatted message" could the HTML then be converted to plain text and dropped in as the reply? While keeping the HTML multipart of the message.

I would prefer taking the chance on having a generic text reply. At that point I could make the choice to reply in HTML if necessary.

The message prior to this is spam, if you have a way to remove it.

**Comment by alecpl** [comment]
In my opinion current solution is good. Here, you're assuming user knows that plain text part is better suited for reply (without viewing that part), but I don't think this is a common scenario. Anyway, toggling from html to plain before hitting compose is quite clear. This is also the only way to use "Compose HTML messages - always, except when replying to plain text" option.

Another story is html2text converter, it should convert <pre> elements reasonably well, maybe we should handle <code> or other tags there. We'd need some examples to fix this. Please, open a new ticket for this if you're interested.
