### ISSUE TITLE
Option to disable line-wrapping when replying to mails

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5101]
_Reported by apaku on 11 Apr 2014 10:35 UTC as Trac ticket #1489798_

We regularly reply to commit-mails which contain the diff of the changes done in the commit. The automatically applied line-wrapping often breaks the diff and one has to reconstruct it manually to make the reply keep its meaning.

For such cases a way to either revert the wrapping or always disabling the wrapping when replying to mails would helping us avoid the nuisance.

As a temporary measure we increased the maximum line length so that the wrapping does not occur, but this is of course not liked that much for 'normal' mails.

_Migrated-From: http://trac.roundcube.net/ticket/1489798_

**Comment by alecpl** [comment]
Another option would be a UI element (checkbox?) in mail compose page.

**Comment by falstaff84** [comment]
It would be nice to be able to disable line wrapping while composing. I send kernel stack traces which look to mailing list which do look rather messed up with line wrapping. Current work around is to edit the setting on server side before sending the email :blush:

**Comment by onlime** [comment]
That issue still exists in Roundcube 1.3.9 and in my opinion is a major problem. Because of that, I can't recommend my customers to use Roundcube webmail on a regular basis, even though I love Roundcube in every other aspect.

Will this be addressed soon or did I just miss a configuration option to turn this line-wrapping of quotations off?

**Comment by dmak** [comment]
As to issue #5305 I can tune line wrapping by editing `/etc/roundcube/defaults.inc.php` but it would be nice to have the option to control max line width in UI as well as disable line wrapping.

**Comment by alecpl** [comment]
Implemented.

**Comment by alecpl** [comment]
This was about composing a new mail. For replies we have #6974.
