### ISSUE TITLE
copy&paste addresses from/to recipient field

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5103]
_Reported by backi on 7 May 2014 06:12 UTC as Trac ticket #1489863_

I think a feature to copy several mailaddresses out of die reciepient-field of an existing mail and paste these addresses into the recipient-field of a new mail would be useful.

Currently with the addresses also the "tag" ("Add contact") of the add-function is copied and I have to remove it manually.

_Migrated-From: http://trac.roundcube.net/ticket/1489863_

**Comment by alecpl** [comment]
Fixed.
