### ISSUE TITLE
markasjunk - add "Not Junk" option

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5104]
_Reported by brendan on 8 May 2014 00:33 UTC as Trac ticket #1489865_

If moving a message into the Junk folder or adding the JUNK imap flags are used by a system to retrain it's spam scanning system, being able to easily revert that change would be desirable.

When viewing the Junk folder, the Junk button should change to NotJunk and behave in the opposite way (reversing the imap flags and taking the message out of the Junk folder).

_Keywords: markasjunk_
_Migrated-From: http://trac.roundcube.net/ticket/1489865_

**Comment by alecpl** [comment]
Implemented with #6504
