### ISSUE TITLE
timezone detection not working without login form

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5106]
_Reported by tomsommer on 17 May 2014 16:35 UTC as Trac ticket #1489900_

Timezone detection will not work when set to 'auto', if login is done by a plugin without displaying the default login form.
This is  because detection is currently only done during the login - so the call to jstz never happens.

To fix this, timezone detection should be done in the app itself and not only during login.
It would also be nice if a fallback was put in place to PHP's default timezone, if timezone detection fails for any reason.

_Keywords: timezone,jstz_
_Migrated-From: http://trac.roundcube.net/ticket/1489900_

**Comment by alecpl** [comment]
As it was said, set $_SESSION['timezone'] from the plugin. Other cases are not supported. We could try to fix some cases, but it would not work for all e.g. for the initial request. Wontfix.
