### ISSUE TITLE
draft autosaving generates lots of messages in trash when using GMail

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5107]
_Reported by mikky on 7 Jun 2014 22:33 UTC as Trac ticket #1489934_

When using GMail as IMAP backend and draft_autosave is enabled, each time a draft is saved a message is created in Trash folder. This could result in a huge number of trashed messages when a draft is being written a long time.

I was unable to reproduce this using my own Dovecot IMAP backend on the same Roundcube installation, therefore I assume it is a GMail-related problem.

I'm not sure what logs are relevant and I don't want to spam so I will provide any logs I will be asked for, including Dovecot logs if applicable.

Submitting for version 1.0.0, although it is probably present in 1.0.1 too.

_Keywords: draft autosave gmail_
_Migrated-From: http://trac.roundcube.net/ticket/1489934_

**Comment by alecpl** [comment]
I'm not able to reproduce the issue anymore.
