### ISSUE TITLE
execution list_identities plugin hook inconsistent

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5108]
_Reported by JohnDoh on 11 Jun 2014 07:15 UTC as Trac ticket #1489939_

at the moment the list_identities hook is only called when identities are listed in the settings section. but identities are listed in other places too - e.g. on message compose.

may be move the hook from settings/func.inc::rcmail_identities_list() to rcube_user::list_identities()? that way it will be called when ever identities are listed.

_Migrated-From: http://trac.roundcube.net/ticket/1489939_

**Comment by alecpl** [comment]
As you see in my last comment the number of hooks would be quite big. A better approach would probably be to create a separate class for identities management and possibility to replace it from a plugin. Anyone would like to try creating a PR?

**Comment by alecpl** [comment]
Wontfix. If we need any new hooks we need more clear idea of what and why.
