### ISSUE TITLE
Fix gender in addressbook

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5110]
_Reported by Guillaume   on 11 Jul 2014 22:41 UTC as Trac ticket #1489984_

Hey !

Currently, roundcube uses X-GENDER, as it isn't compatible w/ rfc6350. I've fixed that to include gender diversity, by having the sex and gender as a common field in the addressbook, as specified in the rfc, and switched to using the GENDER standard field, to ease communication.

G

_Migrated-From: http://trac.roundcube.net/ticket/1489984_

**Comment by alecpl** [comment]
Using both GENDER and X-GENDER in vCard data should be backward compatible. It's not specified in vCard v3 specification, but I guess apps just ignore unknown properties. So, I suppose we could support both. Provide a pull request or it won't happen.

**Comment by nonbinary** [comment]
Any progress on this? I can look into a pull request if needed.

**Comment by alecpl** [comment]
Nothing changed since my last comment.

**Comment by nonbinary** [comment]
disturbio, depends on what your goal is. If you want behaviour that is helpful and inclusive for users, you'd want to have at least the option to specify gender as a cleartext field. Trying to capture all possible variations requires research and updates.
Having F/M/none is not very helpful for users outside of that norm, but is at least not as openly offensive as e.g Skype's behaviour.

**Comment by alecpl** [comment]
Want it to happen, provide a pull request.
