### ISSUE TITLE
Replace and enhance custom client code with jQuery++

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5113]
_Reported by @thomascube on 30 Jul 2014 06:16 UTC as Trac ticket #1490008_

http://jquerypp.com has some nice utility functions for drag & drop, text ranges, etc. Could replace some of the old and home-grown functions in Roundcube

_Migrated-From: http://trac.roundcube.net/ticket/1490008_

**Comment by alecpl** [comment]
Well, I think we can close this.
