### ISSUE TITLE
Add toggle to hide/show contacts widget on compose screen

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5117]
_Reported by jugmac00 on 28 Aug 2014 07:10 UTC as Trac ticket #1490048_

Hi there,

after upgrading form 0.95 to 1.02 our users complain about the contacts column, showing up while composing an email.

I do not find any option to hide this. I found the area in the code (the javascript snippet + the div containers in compose.html), but of course I do not want to fork neither the software nor the theme.

Is there an option which I could not find? Will there be one?

Thank you

P.S.: As behaviour was changed, I consider this as an bug report, not an feature request, but feel free to re-type my issue.

_Keywords: contact compose_
_Migrated-From: http://trac.roundcube.net/ticket/1490048_

**Comment by alecpl** [comment]
This is not needed in Elastic and I don't think anyone will work on this for Larry or Classic. So, wontfix.
