### ISSUE TITLE
Contact display name is removed if equal to firstname + surname

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5119]
_Reported by @thomascube on 23 Sep 2014 08:22 UTC as Trac ticket #1490079_

When displaying or editing a contact, the displayname field is empty even if previously entered. From a user perspective, this is a bit too magic when data I entered in the form disappears again. With the new configuration options for list display name and sorting, this old magic could probably be removed.

_Migrated-From: http://trac.roundcube.net/ticket/1490079_

**Comment by alecpl** [comment]
The patch is lost, but anyway I don't really see why it would be a significant change. @thomascude?
