### ISSUE TITLE
Print button does not work for pdfs in Firefox

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5125]
_Reported by jugmac00 on 4 Nov 2014 09:02 UTC as Trac ticket #1490131_

Reproduce:
- Get an email with pdf
- click on email and click on pdf attachment
- in new window click on printer icon of roundcube gui
- nothing happens

What did I expect?
- clicking on print icon should pop up printer dialog

Additional infos:
- no problems in chrome
- printing with inline pdf functions of firefox works
- "normal" printing works

_Migrated-From: http://trac.roundcube.net/ticket/1490131_

**Comment by alecpl** [comment]
According to the Mozilla's bugtracker we might have something working in Firefox 75.

**Comment by alecpl** [comment]
Fixed. The print button is now enabled (and works) on Firefox >= 75.
