### ISSUE TITLE
search progress bar

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5126]
_Reported by arekm on 14 Nov 2014 08:15 UTC as Trac ticket #1490151_

Dovecot IMAP server provides information with search progress. There are two possible messages:

... [S: \* OK Searched 2% of the mailbox, ETA 7:49
... [6D43](6D43]) S: \* OK Searched 2% of the mailbox, ETA 11:57

code from dovecot:
text = t_strdup_printf("Searched %d%% of the mailbox, "
                             "ETA %d:%02d", (int)percentage,
                              secs/60, secs%60);

and also when does initial indexes:
http://wiki2.dovecot.org/Plugins/FTS

... [S: \* OK Indexed 2% of the mailbox, ETA 7:49
... [6D43](6D43]) S: \* OK Indexed 2% of the mailbox, ETA 11:57

code from dovecot:
text = t_strdup_printf("Indexed %d%% of the mailbox, "
                 "ETA %d:%02d", ctx->percentage,
                  eta_secs/60, eta_secs%60);

These informations make it possible for roundcube to show nice search progress bar to a user.

This report is feature request about adding such functionality.

_Migrated-From: http://trac.roundcube.net/ticket/1490151_

**Comment by alecpl** [comment]
And that would not really work with multi-folder search.
