### ISSUE TITLE
GMail Go-To Action support

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5127]
_Reported by brodock on 20 Nov 2014 18:12 UTC as Trac ticket #1490162_

I would like to request that the under standarization Email Actions Button that was created by Gmail, be integrated with roundcube.

As an example, when I receive an E-mail from a Github new Issue, it adds a small "View Issue" at email listing page.

Here is an example of what goes insided the message:

```
<div itemscope itemtype="http://schema.org/EmailMessage">
  <div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
    <link itemprop="url" href="https://github.com/..."></link>
    <meta itemprop="name" content="View Issue"></meta>
  </div>
  <meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>
```

Here are some additional documentation and a broader explanation of the feature:
- https://developers.google.com/gmail/markup/reference/go-to-action

_Keywords: gmail, email actions_
_Migrated-From: http://trac.roundcube.net/ticket/1490162_

**Comment by alecpl** [comment]
Not a core feature, write a plugin.
