### ISSUE TITLE
Add 'max_disclosed_recipients' option

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5132]
_Reported by quabla on 24 Jan 2015 23:39 UTC as Trac ticket #1490245_

The existing 'max_recipients' option (#1484542) limits the maximum number of recipients in To, Cc, **and** Bcc.

I am interested in having an option that limits the number of disclosed recipients (To, Cc) only. If the limit is exceeded the user should be reminded that every address contained in To and Cc is visible to all recipients. I would even suggest to set a default value of 10.

A more complicated implementation might allow the user to ignore the limitation after acknowledging the warning. For Thunderbird this might become an official feature for version 38 (1).

(1) https://bugzilla.mozilla.org/show_bug.cgi?id=271405

_Migrated-From: http://trac.roundcube.net/ticket/1490245_

**Comment by alecpl** [comment]
Still not implemented in Thunderbird, maybe we could have it first. I like the idea.

**Comment by alecpl** [comment]
Implemented.
