### ISSUE TITLE
Mass-undelete mails

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5133]
_Reported by cwickert on 28 Jan 2015 11:52 UTC as Trac ticket #1490250_

If messages are flagged for deletion, one can unflag them by clicking on the 'gear' icon in the 'flags' column. This however only works for single messages.

It would be nice to have an option to do this for any set of mails marked, e.g. with "Mark -> As not deleted" or "More -> Undelete".

_Migrated-From: http://trac.roundcube.net/ticket/1490250_

**Comment by aitorserra** [comment]
I also vote for this.

**Comment by alecpl** [comment]
Implemented.
