### ISSUE TITLE
IE 11 / Apache and SSL

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5135]
_Reported by jeanpralo on 19 Mar 2015 03:37 UTC as Trac ticket #1490328_

Hi there,

It seems there is a *bug* with Roundcube and IE11.

While using roundcube with IE11 over SSL ( didn't test other IE browsers ) some users were complaining that deleted or moved messages where coming back in their Inbox.

After a bit of troubleshooting it appears that sometimes IE throw this error during the roundcube refresh : XMLHttpRequest: Network Error 0x2ef3.

A bit of tcpdump later it seems that IE does not close properly the socket and think it is still open. So when it tries to refresh the data in Ajax it shows this errors ( sometimes ).

I am using Apache 2.4.7. The KeepAliveTimeout is set to 5. The refresh_interval is the default one under roundcube so 60 seconds.

I have create a small page that does an ajax request every 10 seconds. The connection is still not properly closed but at least IE is opening a new one straight after realizing it is closed.

If you need more clarification let me know.

For now I have disabled keepalive on the server and the problem doesn't occur.

Regards,

_Migrated-From: http://trac.roundcube.net/ticket/1490328_

**Comment by srsbiz** [comment]
Try modifying your vhost configuration in apache conf file by adding

`BrowserMatch ".*MSIE.*" nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0`

**Comment by fuco809** [comment]
is your problem solved, because IE11 needs an other browsermatch string - its name is "Trident7" instead of MSIE.
