### ISSUE TITLE
It should be possible to specify imap_conn_options per host

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5136]
_Reported by dstoykov on 20 Mar 2015 14:10 UTC as Trac ticket #1490335_

Currently imap_conn_options is a global setting. However, it should be possible to specify ssl-related options per host as different hosts might have their certificates issued by different CAs, etc. 

It should probably be an array like mail_domain.

_Migrated-From: http://trac.roundcube.net/ticket/1490335_

**Comment by alecpl** [comment]
Anyway, done.
