### ISSUE TITLE
scroll by keyboard

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5139]
_Reported by nerijus on 29 Apr 2015 11:40 UTC as Trac ticket #1490373_

If I open a message by doubleclicking it I cannot scroll it down by pressing down arrow. I have to press mouse first (focus) somewhere in the message.

_Migrated-From: http://trac.roundcube.net/ticket/1490373_

**Comment by guitarmanusa** [comment]
See PR:  https://github.com/roundcube/roundcubemail/pull/5184

**Comment by alecpl** [comment]
PR merged.
