### ISSUE TITLE
SOLVED - "Download all attachments" damages file names with Czech encoding

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5141]
_Reported by kolaloka on 22 Jun 2015 13:07 UTC as Trac ticket #1490440_

It is the plugin-zipdownload where it happens. The zip file must somehow mutilate downloaded filenames, as if they are downloaded separately, everything is ok. This implies for both Linux and Windows with Czech encoding, I wonder if Polish or French special accent and similar signs remain?

A name like:
"ebek Kukumk"
will be reproduced as:
"ebek Kukumk"

Horrible, isnt it?
:-(

_Keywords: enclose_
_Migrated-From: http://trac.roundcube.net/ticket/1490440_

**Comment by thomascube** [comment]
Close as per user report

**Comment by mybsdc** [comment]
ok

2016-03-21 6:35 GMT+08:00 Thomas B. <notifications@github.com>:
