### ISSUE TITLE
archive - add "Mark as read" option

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5142]
_Reported by maxqia on 1 Sep 2015 01:51 UTC as Trac ticket #1490515_

I would like to have the option to mark my messages as read when I archive them like when I delete them with the option in Preferances-Server Settings "Mark the message as read on delete"

_Migrated-From: http://trac.roundcube.net/ticket/1490515_

**Comment by alecpl** [comment]
Done.
