### ISSUE TITLE
IMAP search string hook

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5145]
_Reported by aik on 18 Dec 2015 08:53 UTC as Trac ticket #1490612_

Hello.

I want to edit search string(ex:Add since, before).

ex: program/steps/mail/search.inc line 107

+ $search_str = rcmail::get_instance()->plugins->exec_hook('imap_search_before', $search_str);
$search_str  = trim($search_str);

_Keywords: search_
_Migrated-From: http://trac.roundcube.net/ticket/1490612_

**Comment by alecpl** [comment]
Implemented in Roundcube 1.1.
