### ISSUE TITLE
Plugin install process still completely broken

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5148]
_Reported by DigiAngel on 30 Dec 2015 19:31 UTC as Trac ticket #1490628_

The plugin process for Roundcube is still completely broken.  Per the install at [every change to composer.json run

php composer.phar install

to download and install all dependencies.

Out of the box (so to speak) I see this:

[12:05:21 gateway64:/var/www/html/roundcubemail$](plugins.roundcube[.]net/]:

After) php composer.phar install
All settings correct for using Composer
Downloading...

Composer successfully installed to: /var/www/html/roundcubemail/composer.phar
Use it: php composer.phar

[gateway64:/var/www/html/roundcubemail$](12:05:34) php composer.phar install
Loading composer repositories with package information
Initializing PEAR repository pear.php[ [RuntimeException](.]net

)
  Failed to execute git clone --mirror 'git.kolab['/home/jlay/.composer/cache/vcs/https---git.kolab.org-diffusion-PNL-php-net-ldap[.](.]org/diffusion/PNL/php-net_ldap.git')git/'
  Cloning into bare repository '/home/jlay/.composer/cache/vcs/https---git.kolab.org-diffusion-PNL-php-net-ldap.git'...
  fatal: unable to access 'git.kolab[server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none

install [--prefer-source](.]org/diffusion/PNL/php-net_ldap.git/':) [[--dry-run](--prefer-dist]) [[--no-dev](--dev]) [[--no-custom-installers](--no-plugins]) [[--no-scripts](--no-autoloader]) [[-v|vv|vvv|--verbose](--no-progress]) [[-a|--classmap-authoritative](-o|--optimize-autoloader]) [[--](--ignore-platform-reqs]) [have to delete out:

```
   {
        "type": "vcs",
        "url": "git.kolab[.](<packages>]...
```

I)org/diffusion/PNL/php-net_ldap.git"
        }
to get this to work.

Interestingly enough, wgetting the file works fine:
[gateway:~$](12:16:53) wget git.kolab[12:16:57--  git.kolab[.](.]org/diffusion/PNL/php-net_ldap.git
--2015-12-30)org/diffusion/PNL/php-net_ldap.git
Resolving git.kolab.org (git.kolab[95.128.36.55
Connecting to git.kolab.org (git.kolab[.](.]org)...)org)|95.128.36.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [to: php-net_ldap.git

```
[           ](text/html]
```

Saving) 11,812      --.-K/s   in 0.005s

2015-12-30 12:16:58 (2.32 MB/s) - php-net_ldap.git saved [11812]

_Migrated-From: http://trac.roundcube.net/ticket/1490628_

**Comment by alecpl** [comment]
Nothing we can do about this.

**Comment by tohuwabohu** [comment]
> Nothing we can do about this.

That's unfortunate. I support the author of the issue, please have a review of the plugin installation process.

The current guide on [http://plugins.roundcube.net/] instructs to use and update the `composer.json` that is shipped with roundcube. But having a default configuration that doesn't work out of the box - how does this encourage me to install additional plugins? If this approach is no longer recommend please provide an alternative soluation.

As a side note: the `dist-composer.json` ships with a `"minimum-stability": "dev"` setting which from what I know effectively upgrades the dependencies to the latest development snapshots rather than the latest stable release.

**Comment by thomascube** [comment]
Unfortunately we cannot fix a 3rd party vendor's certificate chain issues. Maybe cloning the repo and linking to an alternative source could help...

**Comment by thomascube** [comment]
Created a mirrored repo at https://gitlab.com/roundcube/net_ldap3 and registered as a package at https://packagist.org/packages/kolab/net_ldap3. With this public package, we can now remove the custom repo from composer.json

**Comment by alecpl** [comment]
@thomascube, can we add some versioning? Then we could maybe change minimum-stability to stable.

**Comment by thomascube** [comment]
I created tags that match the syntax expected by packagist. However, the latest is 1.0.4 and git master is ahead some commits.

**Comment by alecpl** [comment]
1.0.5 is now tagged upstream.

**Comment by alecpl** [comment]
@thomascube, I removed the custom repo and set "kolab/net_ldap3": "~1.0.4" in composer.json, but got:
```
Installing kolab/net_ldap3 (1.0.4)
Downloading: Connecting...
Could not fetch https://gitlab.com/api/v3/projects/roundcube%2Fnet_ldap3/repository/archive.zip?sha=7339e3aa0fdcb1f52feb4da3924de078846c09d7, enter your gitlab.com credentials to access private repos
```

**Comment by thomascube** [comment]
Strange, the repo is set as "public"... I'll try to investigate

**Comment by alecpl** [comment]
@thomascube, maybe because the gitlab API requires authentication. Would it be possible to use other uri? E.g. https://gitlab.com/roundcube/net_ldap3/repository/archive.zip?ref=v1.0.5

**Comment by thomascube** [comment]
@alecpl I don't know how composer comes to these /api/ URL it tries to fetch and we cannot influence that. Installation works when using the `--prefer-source` option for Composer. Then it simply fetches from git which doesn't require authentication.

**Comment by alecpl** [comment]
Indeed Dist and Source user different URIs. https://github.com/composer/composer/blob/7c62e2b5346a6a656dd9587203719e35bb768056/src/Composer/Repository/Vcs/GitLabDriver.php#L166

I found we can prefer source in composer.json, but didn't test it yet:
```
{
 "config": {
     "preferred-install": "source"
 }
}
```
Not sure this refers to our or net_ldap3 config.

**Comment by alecpl** [comment]
@thomascube: here's what I've got when using --prefer-source:
```
Failed to download kolab/net_ldap3 from source: Failed to execute git clone --no-checkout 'git@gitlab.com:roundcube/net_ldap3.git' '/home/alec/git/roundcubemail/vendor/kolab/net_ldap3' && cd '/home/alec/git/roundcubemail/vendor/kolab/net_ldap3' && git remote add composer 'git@gitlab.com:roundcube/net_ldap3.git' && git fetch composer

Permission denied (publickey).
fatal: The remote end hung up unexpectedly
```
If I try to clone using https://gitlab.com/roundcube/net_ldap3.git it works, but how to inform composer to use https://? Can you change this on packagist?

**Comment by thomascube** [comment]
Changed the repo url to https in packagist. Works for me now with
```
 "config": {
     "preferred-install": "source"
 }
```

**Comment by alecpl** [comment]
Still does not work for me, as nothing changed. I tried clean installation (removed vendor folder and composer.lock), but it still uses git@gitlab.com and not https:// Maybe there's some cache involved?

**Comment by alecpl** [comment]
I tried many ways and checked composer source. I'm afraid this is a dead end.

**Comment by thomascube** [comment]
That's really strange. There are other compose modules hosted by gitlab... including some Roundcube plugins.

Anyway, since git.kolab.org uses a CA which is not recognized by some operating systems, and Github doesn't do repository mirroring, we can only do the mirroring ourselves by pushing the git.kolab.org repo to a Github fork by hand.

**Comment by alecpl** [comment]
Well, another option is to fix composer. There's already a ticket for this issue https://github.com/composer/composer/issues/4744

**Comment by carloscarcamo** [comment]
I have this problem:

```
$ composer install --no-dev
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
                                                              
                                                                                                                          
  [RuntimeException]                                                                                                      
  Failed to execute git clone --mirror 'https://git.kolab.org/diffusion/PNL/php-net_ldap.git' '/root/.cache/composer/vcs  
  /https---git.kolab.org-diffusion-PNL-php-net-ldap.git/'                                                                 
  Cloning into bare repository '/root/.cache/composer/vcs/https---git.kolab.org-diffusion-PNL-php-net-ldap.git'...        
  fatal: unable to access 'https://git.kolab.org/diffusion/PNL/php-net_ldap.git/': Failed to connect to git.kolab.org po  
  rt 443: Connection timed out                                                                                            
                                                                                                                          

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...

```

**Comment by alecpl** [comment]
Still not implemented by gitlab and composer. Re-assigned to "later" as we can't do anything about it at the moment.

**Comment by alecpl** [comment]
Gitlab is still working on this. Some references:
https://gitlab.com/gitlab-org/gitlab-ce/issues/29662
https://gitlab.com/gitlab-org/gitlab-ce/issues/32226

**Comment by alecpl** [comment]
@thomascube It looks that composer can finally use public gitlab repos. https://github.com/composer/composer/issues/6453. So, I tested this and we can finally get rid of the kolab repository and use packagist. We should also switch from git-master to ~1.0.6. One issue with this, the mirrored project on gitlab is not up-to-date, we need to make sure it's updated and add 1.0.6 tag there.

**Comment by alecpl** [comment]
I created the v1.0.6 tag in gitlab repo. We're now using packagist for every dependency.
