### ISSUE TITLE
Enigma: Mail containing text + PGP encrypted part is not decrypted

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5149]
_Reported by devotedmystic on 5 Jan 2016 07:16 UTC as Trac ticket #1490633_

If there is other text before
```
-----BEGIN PGP MESSAGE-----
```
or after
```
-----END PGP MESSAGE-----
```
decryption fails. It seems Roundcube cannot extract/handle correctly the PGP part.

I tested the same message in Gmail with Mailvelope and it works. So, it's a Roundcube decryption error.

_Migrated-From: http://trac.roundcube.net/ticket/1490633_

**Comment by alecpl** [comment]
Fixed.
