### ISSUE TITLE
Plugin Password - Virtualmin driver does not work for user names with custom domain name suffix.

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5150]
_Reported by monstrfolk on 20 Jan 2016 18:52 UTC as Trac ticket #1490644_

This is for those of us using Virtualmin and custom user name suffixes.

The password plugin will not work for us. I have created a fix for this and currently works for a single domain. This fix can be changed slightly to use an associative array of key/value pairs such as domain_suffix => domain_name (stored in the plugin config) and a loop searching for the right pair to support multiple domains (the loop can be added to the amended code below for 'case 8'). 

In drivers/virtualmin.php add this at line 65 under 'case 7'.

```
case 8: // username.domain_suffix
    $domain = $rcmail->config->get('password_virtualmin_domain', '');
    break;
```

Then in your config file for the plugin in add

```
$config[= 'exmple.com'; //change to your domain name
```

change the setting for 'password_virtualmin_format' to 8

```
$config['password_virtualmin_format']('password_virtualmin_domain']) = 8;
```

I have tested this setup and works.

_Keywords: password, virtualmin_
_Migrated-From: http://trac.roundcube.net/ticket/1490644_

**Comment by alecpl** [comment]
How about allowing variables in password_virtualmin_format? By variables I mean the same set of variables that can be used in default_host option:
```
// Supported replacement variables:
// %n - hostname ($_SERVER['SERVER_NAME'])
// %t - hostname without the first part
// %d - domain (http hostname $_SERVER['HTTP_HOST'] without the first part)
// %s - domain name after the '@' from e-mail address provided at login screen
// For example %n = mail.domain.tld, %t = domain.tld
```
Would that work for you? We could consider adding another variable to the supported set.

**Comment by alecpl** [comment]
No feedback.
