### ISSUE TITLE
Remote port logging

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#5151]
_Reported by aure on 29 Jan 2016 16:31 UTC as Trac ticket #1490651_

Hi,

I do need to log not only REMOTE_ADDR but also REMOTE_PORT. This is useful to identify NATed / carrier-grade NAT users.

So here is a patch that adds it in the $remote_ip[] string.
It also works for X-Real-IP and X-Forwarded-For if set.

Would be great have it in future release for me to not patch it each time :-)

Cheers,
Aur

_Keywords: log_
_Migrated-From: http://trac.roundcube.net/ticket/1490651_

**Comment by thomascube** [comment]
Could/should be implemented in a plugin as it's a very rare case. Could be considered/evaluated in #5116.
