### ISSUE TITLE
[Wishlist] sign releases with gpg

### ISSUE THREAD

**Issue by tessus** [roundcube/roundcubemail#5169]
I was wondering, if you could create a Roundcube Release key and sign the releases.

**Comment by thomascube** [comment]
Done with latest releases 1.0.9, 1.1.5 and 1.2-rc

**Comment by tessus** [comment]
@thomascube Maybe I'm missing something, but there is no roundcubemail-1.0.9.tar.gz.asc file in the release downloads. While the tag is signed, the release .tar.gz is not.

**Comment by thomascube** [comment]
Sorry, my bad. I assumed you mean tag signing with this issue.

**Comment by tessus** [comment]
No worries, using signed tags is a good practice anyway. But signing the release tar.gz is also very helpful for peope who do not pull the releases from the repo, but download the release tarball.

**Comment by thomascube** [comment]
Signatures now created and described on the downloads page: https://roundcube.net/download/
Will also write a short announcement later on.
