### ISSUE TITLE
Password Plugin Not working

### ISSUE THREAD

**Issue by cgilbe27** [roundcube/roundcubemail#5170]
What's your PHP version? **5.5.9-1ubunutu4.14**
What's your mail server? **I am using iRedMail**
What browser/operating system did you use, any special settings/plugins? **I tried on google chrome and internet explorer, windows 8**
What did the logs say? 

**I got it to where it doesn't send error logs to /var/log/mail.log anymore but it still doesn't work.
But these were my last few errors:**

Mar 25 13:10:01 mailserver roundcube: <nfd5cpci> DB Error: SQLSTATE[42000] [1044] Access denied for user 'roundcube'@'localhost' to database 'maildb' in /opt/www/roundcubemail-1.1.4/program/lib/Roundcube/rcube_db.php on line 177 (POST /mail/?_task=settings&_action=plugin.password-save?_task=&_action=)

**I have given 'roundcube'@'localhost' full access to all databases**

Mar 25 13:14:21 mailserver roundcube: <nfd5cpci> DB Error: SQLSTATE[42000] [1049] Unknown database 'maildb' in /opt/www/roundcubemail-1.1.4/program/lib/Roundcube/rcube_db.php on line 177 (POST /mail/?_task=settings&_action=plugin.password-save?_task=&_action=)
I change my password_db_dsn from /opt/www/roundcubemail-1.1.4/config/config.inc.php to  /opt/www/roundcubemail-1.1.4/plugins/password/config.inc.php

**I know maildb isn't the correct database and have changed it to vmail, but now I get no error logs and it still can't save my password**

**Heres my current config.inc.php:**

$config['password_driver'] = "sql";
// Determine whether current password is required to change password.
// Default: false.
$config['password_confirm_current'] = true;
// Require the new password to be a certain length.
// set to blank to allow passwords of any length
$config['password_minimum_length'] = 8;
// Require the new password to contain a letter and punctuation character
// Change to false to remove this check.
$config['password_require_nonalpha'] = true;
// Enables logging of password changes into logs/password
$config['password_log'] = true;
// Comma-separated list of login exceptions for which password change
// will be not available (no Password tab in Settings)
$config['password_login_exceptions'] = true;
// Array of hosts that support password changing. Default is NULL.
// Listed hosts will feature a Password option in Settings; others will not.
// Example:
//$config['password_hosts'] = array('mail.example.com', 'mail2.example.org');
$config['password_hosts'] = null;
// Enables saving the new password even if it matches the old password. Useful
// for upgrading the stored passwords after the encryption scheme has changed.
$config['password_force_save'] = false;
// Enables forcing new users to change their password at their first login.
$config['password_force_new_user'] = false;

// SQL Driver options
// ------------------
// PEAR database DSN for performing the query. By default
// Roundcube DB settings are used.
$config['password_db_dsn'] = 'mysqli://roundcube:iRLrjRxxxxxxxxxxxxxxxxDDV5FOur@127.0.0.1/vmail';
// The SQL query used to change the password.
// The query can contain the following macros that will be expanded as follows:
//      %p is replaced with the plaintext new password
//      %c is replaced with the crypt version of the new password, MD5 if available
//         otherwise DES. More hash function can be enabled using the password_crypt_hash 
//         configuration parameter.
//      %D is replaced with the dovecotpw-crypted version of the new password
//      %o is replaced with the password before the change
//      %n is replaced with the hashed version of the new password
//      %q is replaced with the hashed password before the change
//      %h is replaced with the imap host (from the session info)
//      %u is replaced with the username (from the session info)
//      %l is replaced with the local part of the username
//         (in case the username is an email address)
//      %d is replaced with the domain part of the username
//         (in case the username is an email address)
// Escaping of macros is handled by this module.
// Default: "SELECT update_passwd(%c, %u)"
$config['password_query'] = "UPDATE mailbox SET password=%D,passwordlastchange=NOW() WHERE username=%u";
// By default the crypt() function which is used to create the '%c' 
// parameter uses the md5 algorithm. To use different algorithms 
// you can choose between: des, md5, blowfish, sha256, sha512.
// Before using other hash functions than des or md5 please make sure
// your operating system supports the other hash functions.
$config['password_crypt_hash'] = 'md5';
// By default domains in variables are using unicode.
// Enable this option to use punycoded names
$config['password_idn_ascii'] = false;
// Path for dovecotpw (if not in $PATH)
$config['password_dovecotpw'] = "/usr/bin/doveadm pw";
// Dovecot method (dovecotpw -s 'method')
$config['password_dovecotpw_method'] = "SSHA512";
// Enables use of password with crypt method prefix in %D, e.g. {MD5}$1$LUiMYWqx$fEkg/ggr/L6Mb2X7be4i1/
$config['password_dovecotpw_with_method'] = true;
// Using a password hash for %n and %q variables.
// Determine which hashing algorithm should be used to generate
// the hashed new and current password for using them within the
// SQL query. Requires PHP's 'hash' extension.
$config['password_hash_algorithm'] = 'sha1';
// You can also decide whether the hash should be provided
// as hex string or in base64 encoded format.
$config['password_hash_base64'] = false;
// Iteration count parameter for Blowfish-based hashing algo.
// It must be between 4 and 31. Default: 12.
// Be aware, the higher the value, the longer it takes to generate the password hashes.
$config['password_blowfish_cost'] = 12;

**Comment by alecpl** [comment]
Does not look like Roundcube issue. Maybe the query is invalid. Enable sql_debug to see what exactly is sent to the database.

**Comment by cgilbe27** [comment]
Heres the output of the log: http://pastebin.com/C8ah6AFj

**Comment by alecpl** [comment]
Don't use debug_level=4. Anyway, the query looks fine. If it does not work it's not Roundcube issue.

**Comment by cgilbe27** [comment]
What could the problem possibly be?

**Comment by hoc1190** [comment]
same issue. any suggestion?

[22-Apr-2024 00:38:21 +0000]: <m6h75r17> DB Error: [1] near "%": syntax error (SQL Query: UPDATE users SET password=%D WHERE email='****') in /usr/local/lib/roundcubemail/program/lib/Roundcube/rcube_db.php on line 564 (POST /mail/?_task=settings&_action=plugin.password-save)

**Comment by cgilbe27** [comment]
Use mailcow
