### ISSUE TITLE
Upgrade pt_BR translations

### ISSUE THREAD

**Issue by filhocf** [roundcube/roundcubemail#5172]
Hi

I found some untranslated strings in the last package (1.1.4) for pt_BR, and when i saw in Transifex, are all translated. Taking a look inside $SRCROOT/program/localization/pt_BR/labels.inc and its en_US file, is possible to see that many strings aren't in pt_BR but are in en_US. 
Can you upgrade the pt_BR/*.inc files to last version of inc files?

```
localization # for i in en_US/*; do wc -l $i; done                                                                                                   
112 en_US/csv2vcard.inc                                                                                                                 
651 en_US/labels.inc                                                                                                                    
194 en_US/messages.inc                                                                                                                  
localization # for i in pt_BR/*; do wc -l $i; done                                                                                                   
582 pt_BR/labels.inc                                                                                                                    
190 pt_BR/messages.inc                               
```

**Comment by alecpl** [comment]
We usually do this before a release. I did it for git-master now. However, because we do not do versioning for localizations we can't just update localizations in 1.1 branch. There are some labels that we removed, but are still used in 1.1.

**Comment by alecpl** [comment]
We'll accept a PR to release-1.1 branch which adds missing translations, though.
