### ISSUE TITLE
Move messages fails after Select >> Current Page

### ISSUE THREAD

**Issue by dapphp** [roundcube/roundcubemail#5174]
**Symptom:**
Attempt to drag and drop a selection of messages from one folder to another fails with message: **An error occurred.  Server Error! (OK)** and no messages are moved

**Cause:**
It appears that the `rcmail.message_list.selection` array contains duplicate uids prior to the move.

**Steps to reproduce:**
I have the message list set to display 50 messages per page.  Click the *Select* button, choose *Current Page*.  Use the control key to de-select 5-10 messages.  Try to drag and drop the remaining selections to another folder.
Should fail with the **Server Error! (OK)** message.  Inspecting the POST data shows there are duplicate message ID's in the uid move list.

**Other Info:**
Further investigation reveals the following (50 messages per page)
-  The `_uid[]` POST array contained 1569 elements (including duplicates) as a result of deselecting only 5 messages on the page prior to moving
- Each message uid appears to have 32 entries in the selection list
- When I deselect only 2 messages, the move succeeds but there are 197 uids in the POST array, each duplicated about 4 times

This is probably directly related to [issue #5173 ](https://github.com/roundcube/roundcubemail/issues/5173) in that after deselecting enough messages, this list grows so large it consumes massive amounts of memory and takes a very long time to iterate.

**Comment by dapphp** [comment]
To add to this, I noticed that the deselected messages also are moved.  This is probably because not all of the duplicates are getting removed from the list.

So if I Select >> All, and deselect 2 messages, this still results in all the messages on the page getting moved (assuming it doesn't fail with the Server Error (OK)).

**Comment by dapphp** [comment]
I found the source of the problem.  In list.js on line 1266, the line `var p = $.inArray(id, this.selection),` attempts to check if current row being unselected is in the selection list but `id` is a string and `this.selection` is an array of integers.

This only happens when using the Select All function because when looping `for (n in this.rows) {` in list.js line 1129 the value of `n` gets cast to a string causing the subsequent `inArray` call to return false.

**Comment by alecpl** [comment]
Could you confirm that 8bbb45452440746e fixes the issue?

**Comment by dapphp** [comment]
Hi Alec,  That looks promising.  I will test in the morning when I'm back at work.  Thanks for pointing out that commit.

**Comment by dapphp** [comment]
I just tried list.js from that commit and I was able to deselect and reselect a lot of messages without the duplicates getting added to the selection, but it seems to have broke multieselection for me.  Tried both in Chrome (Iron) & FF.

Multiselect itself works fine still, but when I use Select All, deselection is broken.  Trying to deselect certain items doesn't work (nothing gets deselected), and deselecting certain other rows causes them to stay selected and a different row below it gets deselected.  I found I had to Ctrl + Click on certain rows 2-3 times before they would deselect.

Additionally, if I clicked without a modifier (shift or control), the normal behaviour was to deselect everything and then select the row clicked.  Now it doesn't deselect anything and I still need to regular click on an item a few times to unselect it.

The temporary fix I've implemented to list.js in 1.1.4 line 1266 was to change:

    var p = $.inArray(id, this.selection),

to

    var p = $.inArray(id+'', this.selection),

With or without this fix, there does seem to be an issue during multiselection where if I multiselect a message, then deselect it and try to multiselect it again, it won't re-add it to the selection on subsequent times, but that seems lower priority and for another issue.

**Comment by alecpl** [comment]
I can't reproduce described issues using current release-1.1 branch. There's no inArray() in line 1266. Could you try the release-1.1 branch? Could you test with disabled all plugins?

**Comment by dapphp** [comment]
I have the file referencing this commit [`5e6f6ac`](https://github.com/roundcube/roundcubemail/blob/5e6f6ac5395323cc1c1b93ed6d7f6ce83945b251/program/js/list.js#L1266).  It looks like its the commit before the one you referenced.  It looks like after that version `inArray` is no longer used but I had other problems using that commit on a fresh install (from 1.1.4) with no plugins.

I didn't use Git to install, but instead used release 1.1.4 dependent from https://downloads.sourceforge.net/project/roundcubemail/roundcubemail/1.1.4/roundcubemail-1.1.4.tar.gz
