### ISSUE TITLE
REQUEST CHECK FAILED

### ISSUE THREAD

**Issue by dbwebconsultant** [roundcube/roundcubemail#5175]
I have a massive issue with Roundcube mail since this afternoon. (Please note nothing has been changed on our server). 

REQUEST CHECK FAILED

For your protection, access to this resource is secured against CSRF.
If you see this, you probably didn't log out before leaving the web application.

Human interaction is now required to continue.
Please contact your server-administrator.

I have searched for the error across Google but nothing is coming up on it. This is appearing on all email addresses across numerous domains that use the roundcubemail client on my VPS centos server. 

In addition, no emails whatsoever are displaying in any of the mail folders. 

Can someone please advise me as to what it is that is happening with this? It has me driven nuts and has never happened in the past at all.

**Comment by sebix** [comment]
Getting the same error on my instance for all logouts. Additionally, the mail lists do not show any mails (in all folders). I experience this at least since beginning of march. Also, no roundcube updates at the doubtful time frame. Haven't digged into the issue yet, as I don't really use roundcube (except updating).

Additionally I get these lines in syslog:
> roundcube: <xxx> PHP Error: Request security check failed (GET /webmail/?_task=logout)

**Comment by dbwebconsultant** [comment]
Thanks Sebastian. Yes no mails showing in all folders for me also. I have to say for me its only today that I have noticed this. If anyone can shed some light on this, then great.

**Comment by dbwebconsultant** [comment]
Sebastian, If you can would you try adding https:// before the link that you use to login to your webmail? It seems to be doing something for me and actually loading mail. By the seems of it, definitely a security related issue.

**Comment by sebix** [comment]
I use HTTPS everywhere in my installation, nothing is sent over HTTP here. Ensured by using HSTS too. All links are `https://`, including the logout.

**Comment by dbwebconsultant** [comment]
Thats weird so because it sorted my problem when switched to https


On Tue, Mar 29, 2016 at 9:59 PM, Sebastian <notifications@github.com> wrote:

> I use HTTPS everywhere in my installation, nothing is sent over HTTP here.
> Ensured by using HSTS too. All links are https://, including the logout.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/roundcube/roundcubemail/issues/5175#issuecomment-203100486>
>



-- 

*Darragh Bourke Web & Tech Consultant*+353-85-1094903
darragh@dbwebconsultant.com
http://www.dbwebconsultant.com

<darragh@dbwebconsultant.com>

**Comment by alecpl** [comment]
@sebix: maybe something changed in http server config?
Is there some http proxy involved? Looks like something is messing with request headers or cookies. Not Roundcube issue.

**Comment by secustor** [comment]
@alecpl 
I get the same error and also doesn't see any emails, but I don't use any kind proxy or redirect. 
This issue occured when I have upgraded my instance to 1.2.0, 

OS: Ubuntu 14.04
Web: Nginx 1.4.6
Roundcube: 1.2.0
Webserver & IMAP are running on the same server

**Comment by stmllr** [comment]
After upgrading from 1.1.4 to 1.1.5 I get this error when clicking on an attachment.

When clicking on the attachment the url request is https://example.com/?_task=mail&_framed=1&_action=get&_mbox=INBOX&_uid=11364&_part=2&_download=1

If click "open in new tab" in my browser it works. the url is then: https://example.com/?_task=mail&_action=get&_mbox=INBOX&_uid=11364&_token=TOKEN_HERE&_part=2

**Comment by alecpl** [comment]
This maybe a cache issue. Force your browser to reload at least app.js (app.min.js) file.

**Comment by stmllr** [comment]
When I set a breakpoint in app.js at https://github.com/roundcube/roundcubemail/blob/1.1.5/program/js/app.js#L993,
And click the attachment link,
And add the token parameter to qstring
Then the attachment is downloads

**Comment by alecpl** [comment]
What attachment type? Can you reproduce this with PDF and e.g. images or plain text files?

**Comment by stmllr** [comment]
@alecpl cleared browser cache, problem remains. Tried with latest chrome 51 and firefox 45.

**Comment by stmllr** [comment]
The attachment was ods (libreoffice spreadsheet).

When opening a pdf file, then a popup window opens with the following content:
> WARNING! This attachment is suspicious because its type doesn't match the type declared in the message. If you do not trust the sender, you shouldn't open it in the browser because it may contain malicious contents.
>
>Expected: application/pdf (.pdf); found: application/octet-stream (.bin)
[ Show it anyway ]

The pdf is shown as expected when clicking `[ Show it anyway ]` button

**Comment by jult** [comment]
This is still occurring. rc 1.6.* and debian 12, nginx, php-fpm 8.2. It is server-side error.

**Comment by OopsError4o4** [comment]
I'd this issue until just now.
(Im running Roundcube on AlmaLinux-10 from the complete package "roundcubemail-1.6.11.tar.gz".)

It seems that at least the file "jquery.min.js" was missing in "ROUNDCUBE_HOME/program/js/".
After i put it in the logout process was possible again.



Here are the exact steps i went through:

**$ cd ROUNDCUBE_HOME/program/js/
$ wget https://code.jquery.com/jquery-3.7.1.min.js -O jquery.min.js

$ chown 1000:1000 jquery.min.js
$ chmod 644 jquery.min.js

$ rm -rf /var/cache/roundcubemail/*
$ systemctl restart php-fpm httpd**


Apart from a few dispaly errors this worked fine (Those could be fixed by modify the file "rcmail_output_html.php" a little..).
Maybe this works on debian similary..
