### ISSUE TITLE
Empty sieve script causes managesieve hiccup

### ISSUE THREAD

**Issue by cwickert** [roundcube/roundcubemail#5176]
## How to reproduce
* Go to "Settings -> Filters"
* Switch to the "Advanced editor"
* Mark the whole text of the sieve script and delete it
* Press "Save"

## Result
managesieve switches back to the simple editor, but all navigation etc. is lost. It's just a white page with only the "Edit filter" iframe.

**Comment by cwickert** [comment]
For the record, this is roundcube 1.1.4.

**Comment by alecpl** [comment]
Hmm... There's no "Advanced editor" in Managesieve plugin. You're probably using sievefilters plugin which we do not support.
