### ISSUE TITLE
TLS indicator for received mails

### ISSUE THREAD

**Issue by mschilt** [roundcube/roundcubemail#5177]
I would like to have an indicator whether an email was received over TLS.

GMail recently introduced a similar feature on safer internet day that shows users potentially unsafe senders.

For this feature
1. email header needs to be parsed for the right 'Received' line
2. indicator tag (lock symbol) needs to be placed somewhere in the message 
3. Optional: displaying the used cipher suite would be a plus (can also be parsed from the header). Maybe as a mouse-over hint on the indicator tag.

References:
https://googleblog.blogspot.ch/2016/02/building-safer-web-for-everyone.html
https://security.googleblog.com/2016/03/more-encryption-more-notifications-more.html

**Comment by sebix** [comment]
It is hard to determine which transport is relevant, if the underlying mail infrastructure is completely unknown. Roundcube does only know the first hop outgoing, but nothing about the ingoing queue, internal networks and hops etc.

What could be done are heuristics based on FQDNs and IPs.

**Comment by alecpl** [comment]
Question is. Can we trust Received header information? Either we assume it's good enough or you are talking about other ways to detect secure channel?

**Comment by mschilt** [comment]
That's a valid point since some Received headers may be attached by (potentially) unsafe sources. 

I am not aware of other ways to detect secure channels without modifying the underlying mail system (like appending a specific header to each mail at incoming server using milter, etc).

IMHO the Received header at the border of the organization/mail system should be trustworthy.
Automatically detecting/guessing the right Received header might be tricky but as I said the admin knows which server is at the border and in the 'manual' state the admin is free to configure this.

Auto-detection would need to be done based on FQDN and IP as @sebix pointed out. 
Time resolution of the Received lines is 'seconds' (as specified by RFC821) so latency differences (border smtp server <> internet) completely disappear. 

If we decide that the 'auto-detect' way is not really feasible/reliable I would be happy to reduce this feature to either off/manual states.

What would be the right approach to implement this in Roundcube? (Did not yet have an in-depth look at the codebase).

**Comment by alecpl** [comment]
See show_additional_headers plugin. It shows how to do handling of specific message header when the message is displayed.
