### ISSUE TITLE
TLS for DB (MariaDB) connection

### ISSUE THREAD

**Issue by martinstefany** [roundcube/roundcubemail#5180]
I would like to explore/deploy roundcubemail on Apache with separate MariaDB server, separate SMTP/IMAP server, etc. and while all SMTP/IMAP/HTTPS access is secure, I can't seem to figure out configuration options to make roundcubemail communicate with MariaDB server via TLS.
From the source code I was able to figure out that PHP PDO is used and even that dsn_options function in '`program/lib/Roundcube/rcube_db_mysql.php`' handles some '`PDO::MYSQL_ATTR_SSL_*`' options, but I don't see how to turn this into effective config.

Is it possible without patching of the code and just documentation is missing or is it not supported currently?

Thank you!
Martin

**Comment by alecpl** [comment]
E.g. via dsn string: mysql://roundcube:@localhost/roundcubemail?cipher=something&cert=something&capath=something
