### ISSUE TITLE
Allow Math ML tag display

### ISSUE THREAD

**Issue by thomasysliu** [roundcube/roundcubemail#5182]
Thunderbird allow insert math ML tag. While roundcube will filter that tags

The test file in shown below

https://gist.github.com/thomasysliu/f4b8f8115cc10302cef92edc90960c07

**Comment by thomasysliu** [comment]
The filtered tags

![mathml](https://cloud.githubusercontent.com/assets/358963/14191734/2629686a-f7cc-11e5-9af0-f5ea79626b86.png)

**Comment by alecpl** [comment]
Now when we support svg we could probably support mathml.
