### ISSUE TITLE
What does this plugin error mean?

### ISSUE THREAD

**Issue by 118masterman** [roundcube/roundcubemail#5185]
Configuration issue. There can be only one enabled plugin for attachments handling

These are the plugins installed: 

http://puu.sh/o3Pw2/22d2745341.png
http://puu.sh/o3PA2/5cff5813b0.png
http://puu.sh/o3PAT/67357909ca.png
http://puu.sh/o3PCh/31ce464608.png
http://puu.sh/o3PDi/1304edc1b5.png

**Comment by alecpl** [comment]
You can't have both database_attachments and filesystem_attachments enabled.

**Comment by salman7557** [comment]
how can i resolve this issue

**Comment by shadablaxmaya** [comment]
Sorry for late but for those who are still searching try just removing any two of these( database_attachments, filesystem_attachments and redundant_attachments) from $config['plugins'] in config/config.inc.php and keep one that you like to manage your attchments to and this will work
