### ISSUE TITLE
defaults.inc.php not clear on how to use UTF-8 for password charset

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#5186]
The file defaults.inc.php includes:

```
// Password charset.
// Use it if your authentication backend doesn't support UTF-8.
// Defaults to ISO-8859-1 for backward compatibility
$config['password_charset'] = 'ISO-8859-1';
```

I'd like to use UTF-8.  But what do I set it to exactly? 'UTF-8', 'utf8', etc.?  The comments don't say.

Also, shouldn't this default to UTF-8 these days?

**Comment by alecpl** [comment]
UTF-8 or utf8, both should work.

**Comment by seanm** [comment]
@alecpl , I shared a change to improve the comments.

I'm still curious about why it isn't UTF-8 by default.  "Defaults to ISO-8859-1 for backward compatibility" ok, but backwards compatible with what? and how long ago was it?  Maybe it's time to modernise the default?

**Comment by rmcaninch** [comment]
There is Roundcube Next, that would be the place to modernize and I assume they are.

**Comment by seanm** [comment]
Is that 1.3?  I'm looking at <https://github.com/roundcube/roundcubemail/milestones> for some clues...

**Comment by rmcaninch** [comment]
No. Roundcube Next is the next generation project. 
https://roundcube.net/news/2015/05/03/roundcube-next-is-coming
