### ISSUE TITLE
Q: What is 'Bounce the message'

### ISSUE THREAD

**Issue by keunes** [roundcube/roundcubemail#5187]
My university provides a Roundcube installation to access one's inbox, and when selecting an email there's the option "Bounce" in the row with 'delete' and 'forward' buttons.

I know 'bounce' only for emails that get rejected by servers because there's something wrong with the receiving inbox. **What does a 'bounce' do in Roundcube? What happens with the email address that I enter in the 'Bounce To' field?**

Couldn't find this info in the forum or the wiki.

Roundcube v. 0.9.5
Plugins: jqueryui managesieve new_user_dialog show_additional_headers
subscriptions_option userinfo vcard_attachments virtuser_file

**Comment by alecpl** [comment]
That's not standard Roundcube feature, must be some plugin. We have already a request for such an option here: #4985.
