### ISSUE TITLE
Sent Items Roundcubemail - I Phone

### ISSUE THREAD

**Issue by andyweston** [roundcube/roundcubemail#5188]
I have noticed that when I send emails from my I-Phone, they don't come up in my sent items either on my phone or on my laptop.

Also I'm not being able to delete emails directly using the 'bin' button. 

Can anyone help with this please?

**Comment by rmcaninch** [comment]
Is this sending email using the Apple Mail client? Or Roundcube via website? In Apple Mail you're dealing with Apple Mail and the IMAP server agreeing on what to do with Sent emails. Roundcube is not part of that. The iPhone can store Sent email on the device itself rather than on the IMAP server.

**Comment by andyweston** [comment]
Hi ya

I've just managed to sort it by going into the Mailbox Behaviour settings on my I Phone. Seems to be working now.

One thing that does frustrate is sending emails in HTML so that I can underline certain things and bold up words etc. A number of people have said that the email comes out all strangely formatted. Is there any way of sorting that at my end or do I just have to make do with sending email as Plain Text and not risking sending on HTML, especially to prospective clients. Bit annoying/frustrating though.

**Comment by rmcaninch** [comment]
Is that also sending from the iPhone? :) This really isn't the place for that. Not a Roundcube issue.

HTML email can still be a crapshoot no matter how you try it. Consider something like the Notability app to markup a PDF and send that.

Now if you mean the HTML email composing within Roundcube, then can you be more specific and someone may be able to help.

**Comment by andyweston** [comment]
It's the HTML email composing within Roundcube that I am having the issue with.

**Comment by alecpl** [comment]
I don't see a bug description here. Use mailing list or forum for discussion.
