### ISSUE TITLE
Roundcube does not create or subscribe to the Trash folder

### ISSUE THREAD

**Issue by qua-bla** [roundcube/roundcubemail#5192]
Following #2900, Roundcube should "create Sent/Draft/Trash folders when it needs them". I tested this and it is only true for Sent and Draft. It does not create the Trash folder and also fails to subscribe to it.

**Comment by alecpl** [comment]
If configured, Trash is created on every user log in. But I suppose you're talking about a situation when user removes that folder after log in. From what I see, the only case when we should check and create Trash is when we move messages to Trash. Is this correct?

**Comment by alecpl** [comment]
Fixed.
