### ISSUE TITLE
Cannot login with PHP7 and Roundcube version 1.1.4

### ISSUE THREAD

**Issue by chrisriteco** [roundcube/roundcubemail#5195]
Directly after login, got a http 500 and the PHP error:

Got error 'PHP message: PHP Warning:  Declaration of rcmail::get_instance($env = '') should be compatible with rcube::get_instance($mode = 0, $env = '') in /var/www/html/roundcubemail-1.1.4/program/include/rcmail.php on line 30\n'

**Comment by alecpl** [comment]
For PHP7 you'd need Roundcube 1.2.
