### ISSUE TITLE
Intelligent autocomplete - request for information

### ISSUE THREAD

**Issue by bostjan** [roundcube/roundcubemail#5196]
Current RC address autocomplete functionality is pretty basic - annoying after a bit of use, more annoying when realised it is annoying:) More intelligent results are needed by applying statistics to destination addresses of emails sent.

I would like to know how to go about making RC autocomplete better. Namely:
- the frontend part is OK, looks decent
- backend that responds to queries from frontend ("mail/autocomplete" task/action) does not look extendable right now, and this is the problem.

Now, I have two questions:

**Question no.1:**
If I go and try to implement better autocomplete **NOW**, what would be the best way to do it?
a) Patch roundcube (program/steps/mail/autocomplete.inc? or
b) Do some JS wizardry to redirect autocomplette ajax requests to some other task/action (preferably in plugin)?

**Question set no.2:**
If we commit to getting this functionality in near future, RC needs refactoring so that such functionality will be possible to integrate into RC via plugin by using plugin hooks.
If we set out to refactor RC to support hook for this, and make it backward compatible when installed plugins do not provide better implementation, would this change be accepted in the next minor release?
Additionally: who would review and merge such refactoring?

Tnx for info,
b.

**Comment by alecpl** [comment]
Could you provide more details on what you're going to improve and how?

**Comment by bostjan** [comment]
I am aiming at providing better ordering of autocomplete suggestions, to improve it statistically. Namely, on the first entry of "b" I expect all "b*" contacts in alphabetical list, exactly like now. But once I select "bostjan@mydomain" for sending email a couple of times, I would appreciate if "bostjan@mydomain" was the first autocomplete suggestion when hitting letter "b".

So sum it up: statistical analysis of either To/Cc/Bcc addresses of emails sent, or, even better, accepted autocomplete suggestions which is subsequently used for better ordering of autocomplete suggestions to make finding desired recipients as fast as possible once certain amount of stats is collected. All of this per-user, of course.

Am I making myself clear now?
(asking before I proceed with "how" part of the answer, which also depends on your answer :) )

**Comment by alecpl** [comment]
I think this indeed should be a plugin. I imagine it as a database of email-to-prio map, which is updated when user sends an email (similar to automatic_addressbook plugin). Probably with some code when contacts are modified/deleted.

So, I think a plugin API hook here https://github.com/roundcube/roundcubemail/blob/master/program/steps/mail/autocomplete.inc#L177 would allow you to modify the result from a plugin. Re-order it or replace/add some entries. That should be good enough, if you'd like to skip the whole searching code, then you can use 'ready' hook.

**Comment by bostjan** [comment]
Tnx for info, this is somewhere along the lines I was thinking about.

Do you have any suggestions about what this hook should be called? I have fairly basic overview of RC internal structure, so I am not really the right person to recommend a consistent name/id.

b.

**Comment by alecpl** [comment]
Probably something like contact_autocomplete, maybe with _after suffix.

**Comment by bostjan** [comment]
PR #5203 is the next step in this direction. Discussion should continue there. This issue should be closed.
