### ISSUE TITLE
str_replacement display error

### ISSUE THREAD

**Issue by Globulino** [roundcube/roundcubemail#5197]
Not really sure, if this is a roundcube error.

1. Add a string `ttt@www.test` to the body of a mail.
2. Send mail.
3. Text ist displayed as `ttt@##str_replacement_0##`.

This does not happen with `ttt@xxx.test`.

**Comment by alecpl** [comment]
This ##str_replacement_0## may indeed come from Roundcube. However, I'm unable to reproduce. What version? Are you using html or plain text? Try with disabled plugins.

**Comment by Globulino** [comment]
Version 1.1.4
plain-text only
html mail is diplayed correctly
plugins (cannot disable by now):
archive 	2.3
filesystem_attachments 	1.0
jqueryui 	1.10.4
zipdownload 	3.0

**Comment by Globulino** [comment]
Firefox shows this as source:
`<div class="pre"><a href="mailto:ttt@##str_replacement" onclick="return rcmail.command('compose','ttt@##str_replacement',this)">ttt@##str_replacement</a>_0## </div>`

**Comment by alecpl** [comment]
Ok. I can reproduce in 1.1, but not in 1.2.

**Comment by alecpl** [comment]
Fixed.
