### ISSUE TITLE
seems that '-' (dash) cannot be used in an email address

### ISSUE THREAD

**Issue by ServiceDesk-VelzArt** [roundcube/roundcubemail#5201]
If i use an email address with the - sign (for instance test@test-domain.com) there is an error message. If i change the email address to an address with no - it will work.
There is no error message in the logs of the mailserver / webserver so i assume that this is some kind of Java script? Tested this with Chrome, Edge and Firefox, in all browsers the error occurs.

The exact error is: (see screenshot)

Invalid e-mail address 

![error](https://cloud.githubusercontent.com/assets/18449533/14506750/ad01cbc8-01bf-11e6-8d82-c3b65cddbfc3.PNG)

**Comment by rmcaninch** [comment]
I'm not seeing that error on a 1.1.2 test system. I do get an SMTP error. I assume that's the bogus domain name I'm using. 

Just tried with a valid domain name and it sent. Hope I didn't email anyone real.

**Comment by ServiceDesk-VelzArt** [comment]
Guess you are right..... just tested it with another domainname with a - (dash) in it and this works.
The thing is that the domainname that goes wrong do work in the other webmail. (Squirrelmail)
The remedy is for this domain to use the other webmail for now i guess....
But i still want to know what the issue is. I've tried:

- change the identity
- logged in on the webmail with the IP name
- other browsers
- checked DNS

it all seems right. Because there is no error message in the logs i stil think it's the browser / java script that blocks this.

Maybe i can bypass this script.....

**Comment by alecpl** [comment]
Maybe you have email_dns_check enabled in Roundcube config? I don't see other reason to it to not accept such address/domain.

**Comment by ServiceDesk-VelzArt** [comment]
That did the trick. In the config file i've changed the option: 

$config['email_dns_check'] = false;

I can't figure it out yet... why this option responds on this this way.

**Comment by ServiceDesk-VelzArt** [comment]
Hmmmm nevermind the server responds with unknown host if we resolve it.
Seems that here's our issue. Thanks all for the support!

**Comment by ServiceDesk-VelzArt** [comment]
(final) update this domainname was moved in with an option on DNSSEC, this causes this issue at our front DNS server(s) to resolve it correctly. In some cases it worked and some not.
