### ISSUE TITLE
Refresh Button doesn't update message list

### ISSUE THREAD

**Issue by ertyu** [roundcube/roundcubemail#5202]
I've noticed that the refresh button doesn't seem to do anything.
I have my mail window open with the folder list open and my Inbox selected with it's message list displayed. At some point I can see the unread count increase on my inbox, with it's count now greater than the unread messages I can see in the message list. But the new messages aren't displayed in the message list yet. I click the Refresh button and nothing changes, the unread count stays the same and so does the message list. If I click to another mailbox, then click back to the Inbox the new message(s) show up in the message list.
I've experienced this with Roundcube 1.1.3 and 1.1.4.

**Comment by alecpl** [comment]
What PHP/OS version? What IMAP server? Are you using imap_cache/messages_cache?

**Comment by ertyu** [comment]
PHP 5.5/Apache 2.4/FreeBSD 10/Dovecot 2.2
Not using either imap_cache or message_cache

**Comment by alecpl** [comment]
Could you try with 1.2-rc? If it still happens there... Is this 100% reproducible? If so, I'd propose to enable imap_debug and do steps:
0. Start debugging
1. Goto INBOX
2. Using other client send a message to yourself
3. Click Refresh
4. Stop debugging
Then show us the log. Please, do tests on an account with small number of messages.

**Comment by alecpl** [comment]
No feedback.

**Comment by ertyu** [comment]
I have recreated it on 1.2-rc and 1.2 release. It doesn't occur 100% of the time however. I have caught it with imap debugging, but it's on my normal account full of messages.

**Comment by Oakwv** [comment]
refresh buttin elestric skin 1.4 rc does not work. Click the "mail" button on left does work,
