### ISSUE TITLE
Engima plugin won't accept key passphrase for sending a new email signed or encrypted

### ISSUE THREAD

**Issue by fsantiago07044** [roundcube/roundcubemail#5204]
I keep trying to use engima in RC 1.2-RC and when i try to sign or encrypt a message, it keeps asking for a passphrase but never seems to accept it or perform any pgp function. 

It's a 4096 bit key i just generated and my pgp keys RC interface under settings seems normal and correct. 

any ideas?

**Comment by alecpl** [comment]
How did you generate the key? Does the passphrase contain any special characters?
Works for me. Any errors in log? What gnupg version?

ps. when you only encrypt the message you should not be asked for passphrase. It's needed to decrypt or sign, but not encrypt.

**Comment by fsantiago07044** [comment]
key generated using the enigma interface.

no special characters.

gnupg v2.0.22

no relevant logs i can see.

even in the gui there isn't an error per say; it simply just keeps 
asking for the passphrase and doesn't proceed past that point. and 
you're right, i was only trying to sign a message.

---
--

Sincerely,

- Fabian S.

**Comment by fsantiago07044** [comment]
importing a key created elsewhere produces the same errant result.

**Comment by alecpl** [comment]
I see where may be the issue. If you used the Roundcube complete tarball and not composer, there's wrong path to pinentry program in couple of places of Crypt_GPG package.

**Comment by alecpl** [comment]
Hopefully this commit fixes the issue: https://github.com/pear/Crypt_GPG/commit/6b15b4721ebef1931aff2d953087a1b881d76318. I'll close the ticket after we have Crypt_GPG 1.4.1 released.

**Comment by fsantiago07044** [comment]
excuse my naivety but how does one install enigma via composer?

---
--

Sincerely,

- Fabian S.

**Comment by alecpl** [comment]
Not enigma alone, but Roundcube where Crypt_GPG is a dependency.

**Comment by alecpl** [comment]
Done in 6e4642b12ca
