### ISSUE TITLE
Email Formatting - New Line 

### ISSUE THREAD

**Issue by marshamarrings** [roundcube/roundcubemail#5205]
I have 2 admin emails (new customer created and new order received) from opencart only read by roundcube via tools -> view as .eml. 

Other clients like gmail, squirrelmail and outlook view these 2 emails as body text. I would like to read the emails as body text in roundcube too. 

The problem is newline is not there in roundcube. I'm sure it's quite impossible for roundcube to strip newline format. I thought I'd ask about the topic of new lines here. With the hope that if I knew more about how roundcube expects newline, I could force the newline formatting in these two emails in opencart. All other text and html emails from opencart display fine.

I experimented by adding extra \n's in opencart - same no newline in roundcube, and double spaced text in other clients. I've also tried changing content-type without effect. I've spent time studying the source .php from other opencart emails to find a clue about why these 2 are different. 

The environment is windows2012 server. Opencart 1.5.6. hmailserver 5.6.2-B2234 Roundcube Webmail 1.1.1. Zero issues, works flawlessly (Roundcube) otherwise.

When I copied and pasted an example of the text from the .eml (to show the lack of newlines) here, in this issue reporting box, the lines displayed single spaced and double spaced. Prompted me to try roundcube in all browsers. No difference. Attached is an example of the roundcube text from tools->view .eml
[New customer.eml-3.txt](https://github.com/roundcube/roundcubemail/files/219889/New.customer.eml-3.txt)

Any information about new line formatting, escaping in headers or any experience with this opencart issue to shed light on a solution would be appreciated.

**Comment by alecpl** [comment]
This message is malformed. As Roundcube depends on IMAP server BODYSTRUCTURE response we can do nothing about it.
