### ISSUE TITLE
can't add identities

### ISSUE THREAD

**Issue by agodlydeciple** [roundcube/roundcubemail#5206]
I have been fumbling around with this for a while now and no matter what I try I can't seem to be able to add/remove identities through the web interface.  I have edited the defaults.inc.php file and have adjusted the $config['identities_level'] value a dozen times and nothing.

here is how it is set currently in my defaults.inc.php file:
```
// Set identities access level:
// 0 - many identities with possibility to edit all params
// 1 - many identities with possibility to edit all params but not email address
// 2 - one identity with possibility to edit all params
// 3 - one identity with possibility to edit all params but not email address
// 4 - one identity with possibility to edit only signature
$config['identities_level'] = 0;
```

and yet in my web interface this is what I see:
![untitled](https://cloud.githubusercontent.com/assets/683837/14566400/0eceaee4-02f5-11e6-8080-7738a83e2a62.jpg)

the white box is only my current identity/email address and as you can see there is no '+' at the bottom to add a new one. Does anyone have any thoughts? 

setup:
1. CentOS 7
2. Apache Web Server
3. Exim email

**Comment by alecpl** [comment]
You're setting this in config.inc.php or defaults.inc.php? What version? Works for me.

**Comment by agodlydeciple** [comment]
version 1.1.4 - and in defaults.inc.php only.  Don't have a config.inc.php currently.  I tried to use a config.inc.php and it there was no change.
