### ISSUE TITLE
Roundcube Performance - Everything very slow

### ISSUE THREAD

**Issue by Sebi94nbg** [roundcube/roundcubemail#5207]
First of all: Thank you very much for such an awesome software!

Are there any performance guides to improve the loading times of each action? Any button/link I click takes up to 10 seconds to load. Also if I only want to open a new and simple plain-text email: It takes up to 10s, until I can see anything of it.

I'm using following configuration:

- nginx/1.4.6
- php5-fpm/5.5.9
- memcached/1.4.14
- mysql-server-5.5
- Roundcube Webmail 1.2-git

I've hopefully already removed/disabled all plugins in the _config/config.inc.php_ from the variable, but this didn't improved the performance at all.

I found this via Google: http://www.stefanolocati.it/blog/?p=236

He had the same issue and improved the loading times from 10s to <1 seconds.

Are there any guides, how I can improve the loading time(s) of my Roundcube installation? Did I missconfigured anything or are there any settings for?

**Comment by alecpl** [comment]
This is not a support forum. Ask on our mailing list or forum. Most likely this is not Roundcube issue. Looks like you have some delay on IMAP connection or something. Maybe enabling debug options would reveal something in log.

**Comment by shadinamrouti** [comment]
I am facing the same performance issue after moving from version 1.3.8 to 1.4
Any action is taking more than 6 seconds instead of 0.6 second although I'm running both versions in parallel and on different databases, which means there is something wrong with version 1.4 compared to the previous one. I even chose the same skin for both versions.

**Comment by shadinamrouti** [comment]
Performance issue fixed after using
`$config['default_host'] = 'localhost';`

instead of
`$config['default_host'] = 'mail.seowebsitemaker.net';
`
I hope this helps someone in the world. Thumb up if you're saved.

**Comment by mckaygerhard** [comment]
thanks @shadinamrouti currently roundcube have a bad preformance in large mailboxes with thread enabled, as we discuss in the courier mail suite mail list

**Comment by mckaygerhard** [comment]
@shadinamrouti  @Sebi94nbg  i opened a issue due found a partial solution, are the newer versions of roundcube.. with inbox more than 4000+ mails.. but that problem does not happened with older 0.9.5 version.. see #7300 seems newer version of roundcube has performance issues.. very !
