### ISSUE TITLE
Automatic new message check shouldn't display feedback

### ISSUE THREAD

**Issue by backinside** [roundcube/roundcubemail#5208]
There was an issue before about this (https://github.com/roundcube/roundcubemail/issues/1706) I personally totally agree with the request, is there a way to disable this behaviour?

"When checking for new messages RoundCube displays a loading message. This feedback is useful when the user has click the "Check for new message" button, but it is also displayed when RoundCube automatically checks for new mail."

**Comment by alecpl** [comment]
This is a locking operation. So, I think it's good to display the message, so user is not surprised he can't do any action while it's ongoing.

**Comment by backinside** [comment]
I use the webmail on a dedicated display, to monitor the email my inboxes.
The previous implementation I used was much better for my usecase, where the loading animation was more subtle, this way it did not seek my attention.
Is there a way, to change the look of this window?
Why not delay the window in the first seconds, and not show it if the operation finishes within a short amount of time?
