### ISSUE TITLE
Re: Automatic new message check shouldn't display feedback #5208

### ISSUE THREAD

**Issue by backinside** [roundcube/roundcubemail#5210]
Since I can't reopen an issue here, I've created a new one, can you please consider this?

I use the webmail on a dedicated display, to monitor the email my inboxes.
The previous implementation I used was much better for my usecase, where the loading animation was more subtle, this way it did not seek my attention.
Is there a way, to change the look of this window?
Why not delay the window in the first seconds, and not show it if the operation finishes within a short amount of time?

**Comment by alecpl** [comment]
I don't know what do you mean about "previous implementation". You mean classic skin? It's still there. We'll not change the default skin. You're first person that complaints about it.
