### ISSUE TITLE
Re: Automatic new message check shouldn't display feedback #5208 #5210

### ISSUE THREAD

**Issue by backinside** [roundcube/roundcubemail#5211]
Hi,

Can you not instantly close my issues please?
Previous implementation i mean:
V0.9.5 that we've been running for a while now
Where it was under the bottom toolbar of the message list, here:
![image](https://cloud.githubusercontent.com/assets/454430/14601094/679ce906-0560-11e6-808a-3239f45a44fa.png)
In both instances, we run the default Larry skin, the Classic is worse in this case

**Comment by alecpl** [comment]
No, I can't not close non-issues. If you want to discuss this, go to mailing list or forum.

**Comment by backinside** [comment]
Thank you, I'll find another webmail client to use in the future
