### ISSUE TITLE
Spelling errors email vs e-mail

### ISSUE THREAD

**Issue by Yahoe001** [roundcube/roundcubemail#5212]
We have six instances of email being spelled e-mail. They should be corrected.

Thanks

French language coordinator

**Comment by alecpl** [comment]
You mean in en_US? Yes, we should be consistent. As there's no clear winner in "email vs e-mail" war, I'll choose "e-mail".

**Comment by Yahoe001** [comment]
Hello Aleksander,

The spelling differences are in the source strings in Transifex, so yes it
is Englis US. As a language coordinator for over 30 projects, I can say
that "email" is the most common spelling. In Roundcube Webmail, there is 17
instances of "email", 6 instances of "e-mail", in Roundcube Webmail Help,
there is 65 instances of "email", 0 instances of "e-mail". So i'D strongly
advice to gor for "email" to minimize changes and stay mainstream.

Alain-Olivier
French language coordinator
Lo <http://www.localizationlab.org/>calization Lab
<http://www.localizationlab.org/> / OTF
<https://www.transifex.com/otf/teams/>

2016-04-19 2:59 GMT-04:00 Aleksander Machniak <notifications@github.com>:
