### ISSUE TITLE
5.000+ warning notices on single page load when using E_ALL

### ISSUE THREAD

**Issue by bostjan** [roundcube/roundcubemail#5216]
When I switched Roundcube from what it currently has defined to E_ALL, a single page load issued 5503 notices (undefined index, property, variable, constant, uninit string offset) and only 8 of those were from plugins.

```diff
diff --git a/program/lib/Roundcube/bootstrap.php b/program/lib/Roundcube/bootstrap.php
index 17139ca..dac2352 100644
--- a/program/lib/Roundcube/bootstrap.php
+++ b/program/lib/Roundcube/bootstrap.php
@@ -26,7 +26,8 @@
  */
 
 $config = array(
-    'error_reporting'         => E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED,
+    'error_reporting'         => E_ALL,
     // Some users are not using Installer, so we'll check some
     // critical PHP settings here. Only these, which doesn't provide
     // an error/warning in the logs later. See (#1486307).
```

**This makes developing quality plugins practically impossible.**

Will something be done on this by core developers, or is "Patches welcome" the only option here?

Best,
b.

**Comment by alecpl** [comment]
We do not plan to change that, but if you provide PRs we'll likely accept them.

**Comment by bostjan** [comment]
Hipotetical question: if someone creates pull request that cleans whole RC core of all warnings, would default behaviour be switched to E_ALL despite the fact this might cause certain disruption in plugin world?

@alecpl: It seems like 1.2.0 release would be appropriate for such transition, don't you?

**Comment by alecpl** [comment]
I'm not a big fan of E_ALL. And definitely that would not go to 1.2 as we're after release candidate.

**Comment by thomascube** [comment]
We had this discussion multiple times in the past. The conclusion is: as long as Roundcube still depends on PEAR modules and other 3rd party libraries which do not play nice with E_ALL, there's no point in changing the entire code base.

So, please save your time for other useful things than refactoring the Roundcube codebase. It's simply not worth the effort.

**Comment by bostjan** [comment]
Tnx for clarification, I did not find any of this in old issues.

b.
