### ISSUE TITLE
RC internals question - contacts->get_record() and stale results

### ISSUE THREAD

**Issue by bostjan** [roundcube/roundcubemail#5218]
If I call rcmail_contacts->get_record() with ID that is either non-existent, or deleted, I get stale results from previous query (if any).

Workaround:
Using rcmail_contacts->reset() before that restores expected behaviour.

Is this by design for some reason, or is the design just bad (not necessarily by itself, but not matching what one would expect from it by looking at class method names)?

Tnx for clarification,
b.

**Comment by alecpl** [comment]
Definitely a bug. Fixed.
