### ISSUE TITLE
Message list multi-select / deselect issue

### ISSUE THREAD

**Issue by dapphp** [roundcube/roundcubemail#5219]
I noticed this in 1.1.4, and tried a clean install of 1.1.5 and can confirm it still appears present in that version.

**Symptoms:**
When using the Ctrl key to select and unselect multiple messages in the message list, deselecting a message results in all messages below it in the message list being deselected as well, but the rows are still highlighted.

**Expected Behaviour:**
Only the message clicked on should be deselected.

**Steps to Reproduce:**
- Open the Inbox in Roundcube to bring up the message list
- Select the first 5 messages
- To test, use the Mark menu to mark messages as read or unread (all selected messages are flagged properly)
- Deselect the 2nd message in the list (the row is unselected)
- Use the Mark menu to mark messages as read or unread (only the first message is flagged even though rows 3-5 are still highlighted.  They are no longer in `rcmail.message_list.selection`).

It doesn't matter which messages you select, but the actual behaviour seems consistent in that when one messages is deselected, all message rows below it are removed from the selection but remain highlighted.

**Comment by dapphp** [comment]
I was able to do further debugging on this after submitting the report and found the source of the problem.  It stems from [list.js#1267](https://github.com/roundcube/roundcubemail/blob/master/program/js/list.js#L1267) where the array is sliced from the point of the selected element.

It appears that `rcube_list_widget.in_selection()` is returning a string representation of a number causing the `p+1` in `slice` to return the wrong value.

It's strange, when I run the "in_selection" code directly in the debugger (writing the exact same code but not using the actual function), the `n` value is an integer and that is what appears to be returned.  Actually, the debugger is playing tricks.  It makes the array index look like an integer (no quotes), but calling `typeof n` => (string).

But in reality, in the debugger, this is the result:

    > this.in_selection(125333, 1)
    < "3"

Here is the code in question from list.js that is failing because of the return type:

    else { // unselect row     p = "3"
      pre = this.selection.slice(0, p);      pre = [125342, 125339, 125337], p = "3"
      post = this.selection.slice(p+1, this.selection.length);       post = []
      // > p+1
      // < "31"  (should be 4)
      this.selection = pre.concat(post);

In this case, I think the return value from `in_selection` should be run through `parseInt()`.  Who knows what else might break if the return value from `in_selection` was cast there as it may expect a string in other places.

**Comment by alecpl** [comment]
Indeed, I could not find why it's not an int. Anyway, proposed fix looks good.
