### ISSUE TITLE
Hook to change message when moving to trash

### ISSUE THREAD

**Issue by fabioperrella** [roundcube/roundcubemail#5220]
It would be nice if there was a hook to change the message to show when moving the message to the trash folder

In this line:
https://github.com/roundcube/roundcubemail/blob/master/program/steps/mail/move_del.inc#L59

Another suggestion would be to improve the message 'messagemoved', showing to what folder the message was moved, ex: "Message(s) moved successfully to folder {FOLDER}"

**Comment by alecpl** [comment]
I don't like the idea of a plugin hook for this. I'd agree to the improvement of the message. I'm not sure we should add a folder name to all moves or only when we move to Trash.

**Comment by fabioperrella** [comment]
yeah, I agree changing only the message when moving to trash folder!
