### ISSUE TITLE
Attachment file smaller 780 kb

### ISSUE THREAD

**Issue by dungvietnam** [roundcube/roundcubemail#5221]
When I attach a file larger 780 kb to 64MB .. It is ok.. 
When I attach a file smaller 750 kb not OK..
I don't understand..
My system: Windows 10, Wampserver, Mysql, Roundcube. Hmailserver..
Thanks

**Comment by alecpl** [comment]
This is not Roundcube issue. Maybe some antivirus is involved? Works for me. What version(s)? What plugins?

**Comment by dungvietnam** [comment]
Roundcube is 1.2 beta..
I test many file.. .docx, .doc, .pdf... if larger 780kb is OK.. but smaller 750kb it is not attachment..
