### ISSUE TITLE
Duplicate session entry on MySQL when using replication

### ISSUE THREAD

**Issue by Shadok** [roundcube/roundcubemail#5222]
Using Roundcube 1.1.4 (upgrade coming) with MySQL 5.5 and master-slave replication.
$config['db_dsnw'] is set on the master with read/write privileges and $config['db_dsnr'] is set to the slave with readonly privileges.

$config['db_dsnw_noread'] is set to false (tried to true without any change).
$config['db_persistent'] is set to false.

When i'm trying to connect to the webmail, i got this error :
```
[21-Apr-2016 10:26:42 +0200]: <runaj8la> DB Error: [1062] Duplicate entry 'runaj8la6pf3f99dm09ddlgmv1' for key 'PRIMARY' (SQL Query: INSERT INTO `session` .... in /var/www/webmail/program/lib/Roundcube/rcube_db.php on line 543 (GET /?_task=mail)
```

Issue or misconfiguration on my side ?

**Comment by alecpl** [comment]
Does it work when you set both dsn options to master? Check your replication delay (Seconds_Behind_Master).

**Comment by Shadok** [comment]
It works with both options to master and Seconds_Behind_Master value is 0.

**Comment by Shadok** [comment]
Seems fixed with 1.1.5.

**Comment by alecpl** [comment]
So, when Roundcube creates a session it writes to master and in this request master is used for session operations. However, after successful login the next request will read session from the slave.
Could you try $config['db_table_dsn'] = array('session' => 'w'); ? This should force using master for all session operations. Anyway, I think the issue is on slave replication side.

**Comment by Shadok** [comment]
It seems to work that way, thanks.
But there's something i don't understand. The error I got before was because on an INSERT query, so each time, the issue is with the master sql server since it's the only one which has writing rights.

**Comment by alecpl** [comment]
Here's what are the steps. First it does SELECT, if session entry exist it will do UPDATE, if not INSERT. So, in your case duplicate on INSERT means it didn't find the entry on slave and then executed INSERT on master, but there the entry existed. Which means replication does not work or is too slow.

**Comment by Shadok** [comment]
I'm positive the replication works, and i don't know why it would be slow.
Ping between master and slave is 0.545 (average).

**Comment by alecpl** [comment]
Maybe session handling is just too fragile for replication. I suppose http request/redirect can be faster than replication between master and slave. Anyway, I don't see what more we can do here. Either you stay with db_table_dsn or use memcache/redis session handler.

**Comment by Shadok** [comment]
I am fine with db_table_dsn but i will explore memcache session handler.
THanks for the help.
