### ISSUE TITLE
Savedraft lose focus on current active input field

### ISSUE THREAD

**Issue by fabioperrella** [roundcube/roundcubemail#5223]
Hi!

When `rcmail.submit_messageform(true)` is called to save draft, the focus on current element is lost.

For example, if I'm writing the subject, the cursor is moved to the message body

I think the problem is the form is inside an iframe and after submiting on form.subimt() (https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L4149) the focus is moved to the iframe (tinymce)

One possible solution would be to use `$.ajax({ type: 'POST', url: form.action, data: $(form).serialize())`

**Comment by alecpl** [comment]
What are the steps to reproduce? I don't see this on draft auto-save. What browser?

**Comment by fabioperrella** [comment]
The steps are:
- change config "draft_autosave" to 10
- go to compose page
- switch the editor type to HTML
- place the cursor on the "TO" field
- wait autosave runs and you will see the cursor focus moving to tinymce editor

**Comment by alecpl** [comment]
OK, confirmed, using Firefox.

**Comment by alecpl** [comment]
Problem is here https://github.com/roundcube/roundcubemail/blob/master/program/js/editor.js#L453 Either we investigate this line is needed at all or we have two options:
1. put the focus on the previously focused element after getting editor content
2. or I think we could just call this focus() only when args.selection=true.
