### ISSUE TITLE
URL/Link in subject field

### ISSUE THREAD

**Issue by mgilberties** [roundcube/roundcubemail#5224]
When putting a url in the subject field, the mail fails to send and appears to sit in a loop. I have also experienced this previously when php code was in the message of the body.

**Comment by alecpl** [comment]
Works for me. What version? What PHP/OS version? Did you try with disabled plugins? Any errors in error log or browser console?

**Comment by mgilberties** [comment]
Roundcube Version: 1.0.6
OS:  CLOUDLINUX 6.7
PHP Version: 5.6
Haven't got any plugins enabled, just the standard setup. There are no errors in the console either, just the usual logging.

**Comment by alecpl** [comment]
Enable smtp_debug/imap_debug to see if it tries to connect to smtp or fails earlier. Check browser console to see if it submits the form or it fails in the browser.  Check http server logs, maybe that's some mod_security or sth like that? 

What exactly did you put in the subject?

**Comment by alecpl** [comment]
No feedback.
