### ISSUE TITLE
Can't log with some special characters in passwords

### ISSUE THREAD

**Issue by sedric** [roundcube/roundcubemail#5226]
Hi,

One of my user reports that it can't log on roundcube. After some investigation, it seems that it was because he got an "é" in his password.

Logs says : `LOGIN: Login failed: authentication failure in /usr/share/roundcube/program/lib/Roundcube/rcube_imap.php on line 197`

PHP version : 5.6.19
Roundcube version : 1.1.4

**Comment by alecpl** [comment]
See password_charset in config.
