### ISSUE TITLE
Search box should be displayed when showing message in the same window

### ISSUE THREAD

**Issue by bostjan** [roundcube/roundcubemail#5228]
Currently searchbox is only displayed in mailbox listing mode (RC's main screen). I see no reason for not displaying it too when showing a message (action=show) when that is not happening in in a new window. Do you?

Any objections if I go forward and create a pull request for this?

Displaying is the simple part, switching RC context back from message view to mailbox view is what I am currently uncertain about. Any hint/guidance on this one would be greatly appreciated.

b.

**Comment by thomascube** [comment]
The latter is basically the reason why it isn't already shown in the message view :-/

As full message views are new page loads, going back to the mailbox view requires the ability to pass along the search terms (as query parameter) and execute the search again on load.

**Comment by alecpl** [comment]
Of course, we could search without the list, but I think it's a rare need. Usually people want to see all results when searching and then open (or do any action on) specified messages

**Comment by bostjan** [comment]
Is there currently no way to "deeplink" to search result (/?task=mail&action=search&_q=search+string), so we could simply forward browser to given deeplink, from "show message" context?

**Comment by alecpl** [comment]
No, the search request handler is ajax only. The search is stored in session, so most simple way would be to search with ajax, return the search id and then redirect with ?task=mail&_search=<searchID>, but that would require some changes in search.inc I suppose.

**Comment by alecpl** [comment]
This will not gonna happen, especially in Elastic UI.
