### ISSUE TITLE
Plugin configuration should be centralised

### ISSUE THREAD

**Issue by bostjan** [roundcube/roundcubemail#5229]
Hi,

this is more of an opinion than an actual issue.

Configuring roundcube ATM is split between main config file and then configuring each plugin separately. I think RC should offer facilities for plugins to fetch their deployment configuration overrides from main RC configuration location.

For example, the way Symphony Framework does it, is not bad, IMHO.

If some unification will be done on this front, my recommendation is that general gist should be:
- plugin passes to RC a list of defaults (either via class method and if that does not exist, plugin/XXX/config/defaults.inc.php file returns multidimensional array)
- RC parses defaults in single global config, then reads its config/... directory  and everything from $config['plugin'][$pluginName] is merged with defaults from corresponding plugins,
- plugin then uses RC config foundations to retrieve updated configuration

Just a suggestion. ATM tracking what config changes to plugins were made is a bit of a PITA (many files in many locations).

(If this or sth similar is already implemented and I have missed it, I apologize.)

b.

**Comment by alecpl** [comment]
You can already put all plugin config in main config file and it will be used. That should work for all plugins, until some reads its config.inc.php.dist file, that would reset these settings.
