### ISSUE TITLE
wrong auto timezone

### ISSUE THREAD

**Issue by simpleuser99** [roundcube/roundcubemail#5230]
Hello!
In /etc/roundcubemail/defaults.inc.php I set $config['timezone'] = 'auto';
But if my user from Moscow, autoset = Asia/Baghdad

How I fix it?

**Comment by alecpl** [comment]
Timezone detection is done by this javascript library: http://pellepim.bitbucket.org/jstz/. It's not designed for precise timezone detection. I suppose Baghdad is in the same timezone offset as Moscow. You could try replacing program/js/jstz.min.js with the newer version to see if it provides better results.

**Comment by simpleuser99** [comment]
I try to update this js lib, but I haven't result. It's bad. May be I will  use other lib?

**Comment by alecpl** [comment]
Let us know if you find some.

**Comment by simpleuser99** [comment]
Ok. Thanks you for answear
