### ISSUE TITLE
Rename Addressbook to Contacts

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5233]
I think most apps use "Contacts" rather than Addressbook these days. Also, since multiple addressbooks are supported the singular term is a bit odd. Perhaps we should consider changing the (user-visible) name of the component from Addressbook to Contacts?

**Comment by ricardo777** [comment]
+1 from me, same as the big other mail hosting like gmail.

**Comment by alecpl** [comment]
Additionally the list of contact sources now called "Groups" should probably be changed to "Address books". The top level items there aren't groups, but books.

**Comment by thomascube** [comment]
I think the term "Groups" more adequately describes what's listed in that column: books and groups. Once can consider address books as a way of "grouping" contacts but groups aren't really "address books" to me.

**Comment by skaero** [comment]
I like "Contacts" but would keep "Groups" while other systems still used "Address books" I don't think its a name we need to keep.
