### ISSUE TITLE
Latest git, text disappears in preview pane while scrolling

### ISSUE THREAD

**Issue by lhorace** [roundcube/roundcubemail#5234]
Distro: Fedora 23
Browser: Firefox 46.0
Roundcube: https://github.com/roundcube/roundcubemail/commit/0eece8222babd9ea87fbb39ea1a594a7ae979b73

Steps to reproduce
1. Make sure preview pane is in enabled in config
2. Click on message
3. Scroll by mouse wheel or using scroll bar

Expected Result:
Scroll normally

Actual Result:
Text disappears for a few seconds

Additional info:
None atm

Edit: This issue occurs in all scrollable panes. I had a sneaking suspicion that perhaps it was re-pulling the request from the server when scrolling but I don't see any network activity using Firefox developer tools

**Comment by alecpl** [comment]
Works for me. Try with disabled all plugins, Roundcube as well as browser plugins.

**Comment by lhorace** [comment]
On Sun, 01 May 2016 07:12:12 -0700
Aleksander Machniak <notifications@github.com> wrote:

> Works for me. Try with disabled all plugins, Roundcube as well as
> browser plugins.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/roundcube/roundcubemail/issues/5234#issuecomment-216044128

I will download the latest git into a separate directory, disabling
plugins in browser, roundcube and report back later today.

-- 
Lutchy Horace
Owner/Operator/Administrator [http://www.lhprojects.net]
Owner/Operator/Administrator [http://www.bombshellz.net]
Owner/Operator/Administrator [http://www.animehouse.club]
About Me [http://about.me/lhprojects]
USA

**Comment by alecpl** [comment]
Any news on this?

**Comment by lhorace** [comment]
Sorry, I got caught up with other things atm, thanks for the reminder. I'll add this to my todo list for this week.

Regards

**Comment by lhorace** [comment]
I appologize about the delay. I went ahead and pulled https://github.com/roundcube/roundcubemail/tree/release-1.2, did not enable any plugins, aside for the ones that are enabled by default. 

See https://www.youtube.com/watch?v=6dF1qQ-DdoA&feature=youtu.be

Firefox is running with a new profile, with Safe Mode enabled, and the issue still manifest itself in Firefox version 46 but not in Chrome 50.

Interestingly enough, I am able to reproduce the same issue here on github.com. For example, when viewing repository, click on branch and while scrolling. The pane disappears for a moment, sometimes not reappearing.

I'll report this issue to Firefox, perhaps it's a Firefox bug? I am not sure where to look to aide in debugging this problem.

**Comment by alecpl** [comment]
Yes, looks like Firefox bug with scrolling. However, works for me.

**Comment by lhorace** [comment]
In case, for those who may land here from search engines. 

This issue is not reproduciple with Firefox 47b

Regards
