### ISSUE TITLE
Please restore upgrade tutorial

### ISSUE THREAD

**Issue by iredmail** [roundcube/roundcubemail#5236]
Dear developers,

Could you please help restore the Roundcube upgrade tutorial? Old link is:
http://trac.roundcube.net/wiki/Howto_Upgrade

It's not available in wiki of github repo. It's very important to sysadmins who need to upgrade. Thanks.

**Comment by alecpl** [comment]
Done. https://github.com/roundcube/roundcubemail/wiki/Upgrade
