### ISSUE TITLE
When using enigma for singing  / encrypting no mail is sent

### ISSUE THREAD

**Issue by linuxpronl** [roundcube/roundcubemail#5237]
When using the enigma plugin, decrypting email is working fine. When I want to sent a signed or encrypted messages the email is not sent. Roundcube keeps on telling "sending" but never does. Turning siging/encrypting off, email is sent without a problem. Can't find anything in the logs (debug enabled) .

Any hints

**Comment by alecpl** [comment]
What Roundcube version? What GnuPG version? Does it ask for a password? Does it hang or returns an error on http request (you could check browser console)?

**Comment by linuxpronl** [comment]
Roudcube pulled from git, (1.2 rc?)
 gpg v1.4.19 / gpg2 v2.0.28 
It asks for a password. 
have to check on possible error / timeout from webserver (nginx/php-fpm)

**Comment by linuxpronl** [comment]
Excuses, it doesn't ask for a password

**Comment by alecpl** [comment]
If it's from git, did you do composer update to get dependencies? It should ask for a password when you sign the message, until you provided the password before and it's still available in session. See also #5215.

**Comment by linuxpronl** [comment]
there is also this line in the webserver log:
PHP Fatal error:  Call to undefined method Mail_mime::isMultipart() in /data/nginx/sites/roundcubemail/plugins/enigma/lib/enigma_mime_message.php on line 82"

**Comment by alecpl** [comment]
Means, you need never Mail_Mime package.
