### ISSUE TITLE
Memcached session storage

### ISSUE THREAD

**Issue by radekaz** [roundcube/roundcubemail#5238]
According to Roundcube documentation, section about Memcache (https://github.com/roundcube/roundcubemail/wiki/Configuration:-Load-balanced-Setup#memcache) I read that memcached (http://php.net/manual/en/book.memcached.php) can be used to store session data. But then, there is written about Memcache extension which is older extension comparing to memcached.

Also, in Roundcube source code (https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php) I see, that code uses Memcache extension (not Memcached).
My question is if I can use Memcached session storage without patching Roundcube source code?
If I undestand well, Roundcube documentation has wrong information about Memcache session storage, there is written about using Memcached when in fact this is all about Memcache.

**Comment by CRtEurope** [comment]
On my server I use it without any issues. Just put the following code in your php.ini and restart apache and other dependencies...
session.save_handler = memcached
session.save_path = "localhost:11211"

**Comment by alecpl** [comment]
@radekaz, the doc is fine, it says "Memcache extension" with correct link. "Memcached" is the name of the service.
Note that using PHP native session for memcache/memcached is not exactly the same as using Roundcube's memcache session.
Here's an article about PHP memcache extensions that explains why it might not be the best idea to switch to memcached, but I suppose we could consider this in future.

**Comment by radekaz** [comment]
@alecpl You mentioned about article, cound you send an url to this article?

**Comment by alecpl** [comment]
http://brian.moonspot.net/php-memcached-issues, yes, it's old but memcached bugs are still not resolved. Both extensions actually suck in lack of active development. I think we may want to abandon memcache(d) at all in favor of Redis in future.

**Comment by jmvacdmon** [comment]
You can use php5-redis to save sessions



El 06/05/16 a les 17:15, Aleksander Machniak ha escrit:
