### ISSUE TITLE
Sent messages are lost if they cannot be stored immediately

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#5245]
Today I've sent a message through RoundCube mail. The message could be sent out through SMTP (according to the mail logs on the server) but the IMAP server had a problem, dropping client connections. RC did show error messages, but it lost the message I wrote. I didn't have a chance to fix the server and have the message stored again. Thunderbird does this, for example. If a message could not be stored to the IMAP server Sent folder, it asks me to try again. RC should do the same.

**Comment by alecpl** [comment]
It was already implemented in 1.2-beta by c5c8e73351c3. So, I guess you've been using the older version.
