### ISSUE TITLE
PHP7 options in htaccess

### ISSUE THREAD

**Issue by elopez** [roundcube/roundcubemail#5249]
Currently there are a number of PHP options being set on htaccess, guarded by

    <IfModule mod_php5.c>
    ...
    </IfModule>
</pre>

It should be checked if those are needed for PHP 7.0 and the guard changed or a new set added.

**Comment by binarykitchen** [comment]
good question. any news on this??

**Comment by alecpl** [comment]
Good point. All settings there are still valid in PHP7, some are redundant, so the content is fine for both PHP versions. However, how should we fix that, acknowledging that the .htaccess file is only an example? I think we can't just replace mod_php5.c with mod_php7.c. Putting two IfModule sections for both PHP versions could be also confusing. I propose to just add a big fat warning on top that the module need to be changed on PHP7.
