### ISSUE TITLE
Migration notes from PHP5 to PHP7

### ISSUE THREAD

**Issue by binarykitchen** [roundcube/roundcubemail#5250]
Have installed PHP7 via apt-get on my server, but now Roundcube seems down. Probably I did something wrong and wonder if there are any migration notes?

**Comment by bytesplit** [comment]
Seems like you missed that Roundcube supports PHP7 only starting with v1.2 which hasn't been released yet. There is a RC-release you might want to check out though...

**Comment by binarykitchen** [comment]
@bytesplit i am keen to check it out. how? which git branch it is?

**Comment by bytesplit** [comment]
There is branch release-1.2 and in releases there also is a tag called 1.2-rc. Check our the releases tab and scroll down below 1.0 and 1.1 security updates. There even is a zip to download.

**Comment by binarykitchen** [comment]
@bytesplit I am using the latest master branch here. It should already include code of release-1.2, doesnt it?

**Comment by alecpl** [comment]
Check you error log. Probably you need to update some Roundcube dependencies. Did you run composer update (with updated composer.json)?

**Comment by binarykitchen** [comment]
right, I did that and it worked afterwards
