### ISSUE TITLE
Mail Filter Errors In Log

### ISSUE THREAD

**Issue by vectr0n** [roundcube/roundcubemail#5257]
Whenever I create or edit a mail filter in roundcube I get the following two errors, nothing appears in roundcube itself, and it doesn't seem to hamper the function as the filter saves and works without any issues or errors. Just seems when you create or edit a filter these two errors appear in /var/log/mail.log.

`May 17 11:58:13 mail roundcube: PHP Warning: Declaration of rcube_sieve_vacation::load_script() should be compatible with rcube_sieve_engine::load_script($script_name = NULL) in  /opt/www/roundcubemail-1.1.5/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php on line 24`

`May 17 11:58:18 mail roundcube: PHP Warning: Declaration of rcube_sieve_vacation::load_script() should be compatible with rcube_sieve_engine::load_script($script_name = NULL) in /opt/www/roundcubemail-1.1.5/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php on line 0`

**Comment by alecpl** [comment]
What PHP and Roundcube version? Looks like PHP7 and for PHP7 you need Roundcube 1.2. But I'd expect other errors as well on PHP7 and Roundcube 1.1.

**Comment by vectr0n** [comment]
PHP 7 and Roundcube 1.1.5. I will let the iRedMail maintainer know this is the issue.
