### ISSUE TITLE
Multi-folder search does not work properly for INBOX

### ISSUE THREAD

**Issue by mgurm** [roundcube/roundcubemail#5259]
Hello

When using the quicksearchbar in the mail view, there is an option to search in "this and subfolders". This works perfectly for normal folders, but (at least in my case) does not work for the INBOX folder. It only returns results from subfolders, but not from the INBOX folder itself.

I have not yet found out if this is a general problem that always happens or if there is anything special needed to trigger it (maybe someone can try to reproduce it?). I will do some more testing next week.

I am using Roundcube 1.1.5.

**Comment by alecpl** [comment]
Works for me in 1.2, I didn't try 1.1. Enable imap_debug and check what's going on on IMAP level.

**Comment by mgurm** [comment]
The imap log shows that a `SELECT INBOX` command is never sent to the server, there are only some `SELECT` commands for the subdirectories. So it looks like this:

```
S: A0003 OK [CAPABILITY IMAP4rev1 UNSELECT IDLE NAMESPACE QUOTA CHILDREN ID] Logged in
C: A0004 LSUB INBOX "*"
S: * LSUB () "." "INBOX.some_subdirectory"
S: A0004 OK Lsub completed.
C: A0005 LIST INBOX "*"
S: * LIST (\HasChildren) "." "INBOX"
S: * LIST (\HasNoChildren) "." "INBOX.some_subdirectory"
S: A0005 OK List completed.
C: A0006 SELECT INBOX.some_subdirectory
S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft \*)] Flags permitted.
S: * 1 EXISTS
S: * 0 RECENT
S: * OK [UIDVALIDITY 1462977609] UIDs valid
S: * OK [UIDNEXT 2] Predicted next UID
S: * OK [HIGHESTMODSEQ 2] Highest
S: A0006 OK [READ-WRITE] Select completed.
C: A0007 UID SORT (DATE) US-ASCII ALL OR HEADER SUBJECT test HEADER FROM test
S: * SORT 1
S: A0007 OK Sort completed (0.000 secs).
```

However, we believe that we have already found the reason: in commit 6521c20 an if-condition in rcube_imap.php was modified, adding `!strlen($root)`. I don't know why this was added, but I think it causes INBOX to be excluded in some cases.

I tried the same search without the `!strlen($root)` and then it worked. The relevant code now looks like this:

```php
        if ((!$filter || $filter == 'mail') && !in_array('INBOX', $a_mboxes)) {
            array_unshift($a_mboxes, 'INBOX');
        }
```

Btw: testing this with two different code-versions is a bit difficult because there is some caching involved. But I did delete the cache in-between, so I am confident that my result is correct.

**Comment by alecpl** [comment]
Your INBOX is not subscribed, just subscribe it.
