### ISSUE TITLE
password plugin error

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5260]
I was about to change my password. But there is an existing issue now.
The password can not be changed because it is not in the settings tab anymore. It disappeared...
And I get the following error:
`PHP Warning:  in_array() expects parameter 2 to be array, string given in /plugins/password/password.php on line 372`

I do not know how to handle this.
It occurs on different systems with php5.6 and php7.0 and I use the master-branch.

![rc](https://cloud.githubusercontent.com/assets/16518395/15390052/fb49d472-1db9-11e6-96b6-6f1cdb58bd76.png)

**Comment by alecpl** [comment]
You have an invalid value in password_hosts option in the plugin config. This is supposed to be an array. We'll fix that warning later.

**Comment by CRtEurope** [comment]
Does this mean that it'll be shown in the settings tab when this has been fixed?

**Comment by alecpl** [comment]
Depends on what you have set in password_hosts ;)

**Comment by CRtEurope** [comment]
This is in there:
`$config['password_hosts'] = array('mail.cesidianroot.eu');`

**Comment by alecpl** [comment]
It must be something else according to the php warning. Maybe you have the option duplicated later in the config file or sth.

**Comment by CRtEurope** [comment]
This is my config for driver sql. It has always worked...

`<?php

// Password Plugin options
// -----------------------
// A driver to use for password change. Default: "sql".
// See README file for list of supported driver names.
$config['password_driver'] = 'sql';

// Determine whether current password is required to change password.
// Default: false.
$config['password_confirm_current'] = true;

// Require the new password to be a certain length.
// set to blank to allow passwords of any length
$config['password_minimum_length'] = 5;

// Require the new password to contain a letter and punctuation character
// Change to false to remove this check.
$config['password_require_nonalpha'] = false;

// Enables logging of password changes into logs/password
$config['password_log'] = true;

// Comma-separated list of login exceptions for which password change
// will be not available (no Password tab in Settings)
$config['password_login_exceptions'] = null;

// Array of hosts that support password changing. Default is NULL.
// Listed hosts will feature a Password option in Settings; others will not.
// Example:
//$config['password_hosts'] = array('mail.example.com', 'mail2.example.org');
$config['password_hosts'] = array('mail.cesidianroot.eu');

// Enables saving the new password even if it matches the old password. Useful
// for upgrading the stored passwords after the encryption scheme has changed.
$config['password_force_save'] = true;

// Enables forcing new users to change their password at their first login.
$config['password_force_new_user'] = true;


// SQL Driver options
// ------------------
// PEAR database DSN for performing the query. By default
// Roundcube DB settings are used.
$config['password_db_dsn'] = 'mysql://xxx:xxx@localhost/postfix';

// The SQL query used to change the password.
// The query can contain the following macros that will be expanded as follows:
//      %p is replaced with the plaintext new password
//      %c is replaced with the crypt version of the new password, MD5 if available
//         otherwise DES. More hash function can be enabled using the password_crypt_hash 
//         configuration parameter.
//      %D is replaced with the dovecotpw-crypted version of the new password
//      %o is replaced with the password before the change
//      %n is replaced with the hashed version of the new password
//      %q is replaced with the hashed password before the change
//      %h is replaced with the imap host (from the session info)
//      %u is replaced with the username (from the session info)
//      %l is replaced with the local part of the username
//         (in case the username is an email address)
//      %d is replaced with the domain part of the username
//         (in case the username is an email address)
// Escaping of macros is handled by this module.
// Default: "SELECT update_passwd(%c, %u)"
$config['password_query'] = 'UPDATE mailbox SET password=%c WHERE username=%u';

// By default the crypt() function which is used to create the '%c' 
// parameter uses the md5 algorithm. To use different algorithms 
// you can choose between: des, md5, blowfish, sha256, sha512.
// Before using other hash functions than des or md5 please make sure
// your operating system supports the other hash functions.
$config['password_crypt_hash'] = 'md5';

// By default domains in variables are using unicode.
// Enable this option to use punycoded names
$config['password_idn_ascii'] = true;

// Path for dovecotpw (if not in $PATH)
$config['password_dovecotpw'] = '/usr/local/sbin/dovecotpw';

// Dovecot method (dovecotpw -s 'method')
$config['password_dovecotpw_method'] = 'CRAM-MD5';

// Enables use of password with crypt method prefix in %D, e.g. {MD5}$1$LUiMYWqx$fEkg/ggr/L6Mb2X7be4i1/
$config['password_dovecotpw_with_method'] = false;

// Using a password hash for %n and %q variables.
// Determine which hashing algorithm should be used to generate
// the hashed new and current password for using them within the
// SQL query. Requires PHP's 'hash' extension.
$config['password_hash_algorithm'] = 'sha1';

// You can also decide whether the hash should be provided
// as hex string or in base64 encoded format.
$config['password_hash_base64'] = false;

// Iteration count parameter for Blowfish-based hashing algo.
// It must be between 4 and 31. Default: 12.
// Be aware, the higher the value, the longer it takes to generate the password hashes.
$config['password_blowfish_cost'] = 12;`

**Comment by alecpl** [comment]
I don't know what to say more. The warning message says that password_host option value is not empty and is not an array. Goto line 371 and add print_r($hosts); to see what's there. Maybe that would give you some hints on what to search for in your configs.

**Comment by CRtEurope** [comment]
hold on, please

**Comment by CRtEurope** [comment]
I got it. Found the issue. However many thanks for your help.

Changed `// $config['password_dovecotpw'] = '/usr/local/sbin/dovecotpw';`

to

`$config['password_dovecotpw'] = '/usr/local/sbin/dovecotpw';`
Rebooted the whole server and everything is working now. Some php files have been in the opcache, still.

Again, many thanks Alec.
