### ISSUE TITLE
Refused to display in a frame because it set 'X-Frame-Options' to 'DENY, sameorigin'.

### ISSUE THREAD

**Issue by DustinUtecht** [roundcube/roundcubemail#5261]
How to fix following error ?

Refused to display 'https://DOMAIN/roundcube/?_task=settings&_action=plugin.managesieve-action&_framed=1&_unlock=loading1463681466464' in a frame because it set 'X-Frame-Options' to 'DENY, sameorigin'.

**Comment by DustinUtecht** [comment]
btw i get the same error on all pages  'https://DOMAIN/roundcube/skins/larry/watermark.html'

**Comment by alecpl** [comment]
Check your http server config. Not Roundcube issue.
