### ISSUE TITLE
Can not send list with several addresses

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5262]
Maybe an issue or not.
When I send a message with a list I have created with 15 addresses in the list the e-mail is not sent.
When I do the same with Thunderbird everything works properly. So I can take it that this is not a postfix issue.
There is no error in the log files.

PHP 5.6 and PHP 7.0, master-branch

**Comment by alecpl** [comment]
But you get any message in UI? Enable smtp_debug and check the log.

**Comment by CRtEurope** [comment]
There is not message in UI, unfortunately. I'm a enable smtp_debug now and will test it.

**Comment by CRtEurope** [comment]
This ticket can be closed.

It was `$config['email_dns_check'] = true;`

changed it to

`$config['email_dns_check'] = false;`

Maybe it is not a good idea to use it...

Alec, thanks fot he heads up with the debug option.
