### ISSUE TITLE
Can't delete "invalid name" folders.

### ISSUE THREAD

**Issue by mscullin** [roundcube/roundcubemail#5263]
Three folders were migrated from previous email, that have invalid names (start with ~). I've emptied them, but can't delete because names are invalid. Delete should be allowed for empty folder regardless of name.

**Comment by rmcaninch** [comment]
They could be deleted at the file system level. If you still need to get rid of them.

Round cube needs to be careful on what it allows a user to delete. The tilde could be used in a backup name for instance (that admittedly should probably not have landed in the email folder anyhow).

**Comment by alecpl** [comment]
What do you mean you can't? Is there an error or sth? There's no technical limit for deletion of such folders in Roundcube, so I expect it's IMAP server issue.

**Comment by mscullin** [comment]
Aleksander, 

I choose the folder tool, then the folder I want to delete. Then I touch
the tools icon at the bottom of the list and touch Delete, which is the
only option available. Then I get an error box. 

Please see the attached screen shot. 

I'm using Safari on an iPad Mini. The mail server is through htva.net 

Thanks. 

Mike

On 2016-05-22 01:25, Aleksander Machniak wrote:

> What do you mean you can't? Is there an error or sth? There's no technical limit for deletion of such folders in Roundcube, so I expect it's IMAP server issue. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/5263#issuecomment-220815068

**Comment by alecpl** [comment]
I don't need a screenshot, what the error says? Enable imap_debug and check the log.

**Comment by mscullin** [comment]
I am using the web client onn Safari on iPad Mini.  

How do I turn on imap_debug? Can't find it anywhere. 

Also, I think the folders are on the server, so I can't delete at file
system level. 

thanks for your help. 

Mike

On 2016-05-23 02:14, Aleksander Machniak wrote:

> I don't need a screenshot, what the error says? Enable imap_debug and check the log. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
 

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/5263#issuecomment-220895326

**Comment by alecpl** [comment]
We can't fix this, it does not look like Rundcube issue., You have to contact your system administrator.

**Comment by mscullin** [comment]
You have been not very helpful. 

First you demand a log but will not tell me how to create it.  

Now you tell me it is not your problem. 

It looks to me like the error comes from your software, yet you cannot
track it from a screen shot. 

I will contact my ISP, who provides the email server. You may hear from
him. 

Mike 

On 2016-05-26 04:55, Aleksander Machniak wrote:

> Closed #5263 [1]. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [2]
 

Links:
------
[1] https://github.com/roundcube/roundcubemail/issues/5263
[2]
https://github.com/roundcube/roundcubemail/issues/5263#event-672880080
