### ISSUE TITLE
Don't use insecure RNGs for password salts

### ISSUE THREAD

**Issue by paragonie-scott** [roundcube/roundcubemail#5266]
https://github.com/roundcube/roundcubemail/blob/ab6fdfa8bc3a441590778b026b52225473424eec/plugins/password/password.php#L657-L673

Recommendation:

1. Use [password_compat](https://github.com/ircmaxell/password_compat).
2. Failing that, use [random_compat](https://github.com/paragonie/random_compat) to polyfill `random_int()` from PHP 7 and use that function instead.

**Comment by alecpl** [comment]
We already have rcube_utils::random_bytes() which we could probably use.

**Comment by paragonie-scott** [comment]
I was suggesting `random_int()` (with random_compat for PHP 5) as a drop-in replacement for `rand()`.

I'll send a PR in a bit.

**Comment by alecpl** [comment]
Done. I only changed security-related code. Other uses of mt_rand() can be left as it is.
