### ISSUE TITLE
$RCMAIL->output is null -> returns a fatal error

### ISSUE THREAD

**Issue by Littlericket** [roundcube/roundcubemail#5270]
Hi,

im currently running into an issue which I never encountered yet while using roundcube.
After updating to 1.2, the application returns a 500 with the following exception in the php error log:

```php
PHP Fatal error:  Call to a member function nocacheing_headers() on null in /var/www/roundcube/index.php on line 47
```

I'm running on PHP 5.6.15
```
PHP 5.6.15 (cli) (built: Mar 23 2016 15:55:35)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Any ideas why "$RCMAIL->output" could be null? It hasn't started logging either so I don't really know what to do now.

Thanks in advance,

**Comment by alecpl** [comment]
It may happen if $_SERVER['REMOTE_ADDR'] does not exist. So, something on PHP level. Is it normal that you have PHP 5.x and Opcache 7.x?

**Comment by Littlericket** [comment]
Hi @alecpl 

i've built PHP from source some time ago and included the OPCache module with it - I dont really know why it used v7.0.6 but it seems that this is not the problem, since every other application runs fine (Wordpress, Drupal). I've disabled OPCache and it still gives the 500.

$_SERVER["REMOTE_ADDR"] is replaced by http-x-real-ip since there's a reverse proxy infront of the server.

I haven't found out what the problem is yet. Do you have any more ideas?

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail.php#L127-L132 It looks like empty REMOTE_ADDR is the only possibility to skip output object initialization. If REMOTE_ADDR is indeed empty this is a bug in your server configuration. It should never be empty.
