### ISSUE TITLE
Frequent popups - 'Connection Error (Failed to reach the server)'

### ISSUE THREAD

**Issue by benjymous** [roundcube/roundcubemail#5273]
After functioning perfectly normally for a while, RC1.2 will start displaying popups with the message "Connection Error (Failed to reach the server)!"

Looking at the network tab in Chrome's developer tools, I see calls to https://mydomain/roundcube/?_task=settings&_action=keep-alive&_remote=1&_unlock=0&_=1464123105782 being called rougly 100 times a second (1000 counted in 10 seconds) which appears to be the culprit - after a while these start failing with  jquery ERR_INSUFFICIENT_RESOURCES errors, which appears to trigger the popup.

Running RoundCube 1.2 (Upgraded from an old install that was previously running 0.6) on Debian Linux

Let me know if there are any other diagnostics I can provide.

**Comment by benjymous** [comment]
After debugging this myself, I tracked down the cause

in  config.inc.php  I had the following setting
   $config['session_lifetime'] = 1000000;
intended to prevent logouts.

It turns out that this was causing this function:

    this.start_keepalive = function() {
        !this.env.session_lifetime || this.env.framed || this.env.extwin || "login" == this.task || "print" == this.env.action || (this._keepalive && clearInterval(this._keepalive),
        this._keepalive = setInterval(function() {
            f.keep_alive()
        }, 500 * this.env.session_lifetime))
    }

to basically keep calling itself immediately - presumably integer overflow.

Changing the session_lifetime down to 1000 seems to fix the issue, and greatly speeds up RC's performance too!

Suggestion would be to have a sanity check for session_lifetime to prevent large numbers causing issues.

**Comment by alecpl** [comment]
Fixed.

**Comment by austinfacility** [comment]
May someone tell me what I need to do to fix this reoccurring problem I have. When I am on ROUNDCUBE - I get a message every minute it seems to have logged me off automatically. the message reads -- CONNECTION ERROR (failed to reach server) Let's say emailing is as tech savy as I get. So may someone explain to me in JOE BLOW terms what I need to do? THANK YOU!!!!
