### ISSUE TITLE
Completely blank text part confuses some mail clients

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#5283]
If you compose a blank mail with html, some mail clients (e.g. Gmail, iOS Mail) will display the MIME attachment delineation text instead of blank space.

**Comment by thomascube** [comment]
The problem seems more to be on the Gmail side which apparently converts the (correctly) sent `Content-Type: multipart/alternative;` header into `Content-Type: text/html` if not actual content is found...

**Comment by thomascube** [comment]
Let's do some more testing before back-porting the change to 1.2 and 1.1

**Comment by alecpl** [comment]
Skipping blank text part is good anyway. Improved the change and cherry-picked to 1.2.

**Comment by alecpl** [comment]
I backported these changes to 1.0 and 1.1 as it sounds as a major issue. Not sure we should release them yet, as we stopped supporting 1.1, and 1.0 contains only two fixes.
