### ISSUE TITLE
Enigma: Use Public Keyserver to get a public key

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#5286]
most users dont send their public key as an attachement with their mails. It would be nice if there is a possibilty to import public keys from a public keyserver

**Comment by alecpl** [comment]
Yes. And we could re-use some code we already have for Mailvelope integration. Assigned 1.3-beta milestone, but we should consider backport to 1.2 as soon as we have it implemented.

**Comment by CRtEurope** [comment]
Also I would like to see to get keys over dns using pka like e.g.:

'gpg --trust-model always --auto-key-locate pka -ea -r your.name@example.com'

I am just publishing keys over dns and it is very fast and has lots of advantages.

**First look for a public key in dns then use a key server**

Maybe one of you could really implement this item.

**Comment by alecpl** [comment]
Implemented key-server search on mail compose and key import. Please, open a separate ticket for PKA, but I think there are other features with higher prio than this.
