### ISSUE TITLE
Syslog ID problem

### ISSUE THREAD

**Issue by wizzent** [roundcube/roundcubemail#5289]
When using syslog as log driver, the application is not calling the function closelog() at the end of the script. This is causing the problem that the same apache thread used to execute the script will continue using the same Syslog ID set by the appication ("roundcube" by default) instead of the standard one ("apache2").
Calling closelog() before the end of the script should fix the problem.

**Comment by alecpl** [comment]
This sounds like PHP bug, but we can add closelog() in shutdown function, I suppose.

**Comment by wizzent** [comment]
I've added some hours ago a call to closelog() in the shutdown function to see if this fixes the problem, I can tell you something more about this in the next days.
About to consider this a PHP bug, indeed I think it's quite border line. The documentation indicates the usage of both openlog() and closelog() as optional, since sending logs to syslog could be done even without calling them - but not calling closelog() won't allow to customize the ID. Probably they intented openlog() to be used always in conjunction with closelog() - even if the documentation is incomplete on this point.

**Comment by wizzent** [comment]
Hi,
it seems that adding the closelog() call in the shutdown() function fixes the problem.
I've changed the file /program/lib/Roundcube/rcube.php adding this piece of code at the end of the function:

`if ($this->config->get('log_driver') == 'syslog') { closelog(); }`

Bye
