### ISSUE TITLE
regression: can't paste into message body editor when 'editor type' is 'html'

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#5290]
In roundcube 1.2, when I compose (or reply to) a message and use the html editor, I cannot paste text into the message body.  Pasting works fine in plain text mode.

This is a regression.  It does *not* occur with roundcube 1.1.5.

It does occur with several browsers on several OSes.  I tried OS X Safari, OS X Firefox, Windows Firefox, Windows Chrome, etc.

**Comment by CRtEurope** [comment]
Everything works fine here...

Can you enable debug logs?

**Comment by alecpl** [comment]
Works for me too. Could you check browser console for javascript errors?

**Comment by seanm** [comment]
Thanks for the very fast replies!

@CRtEurope I haven't turned on any extra debug logging, but on my server, in my roundcube/1.2/logs/error, file I basically see these two things over and over:

```
[2016-05-30T11:04:38-04:00]: <140v9u9v> Warning: Call to deprecated function rcube_label(); See bc.inc for replacement
[30-May-2016 11:06:38 America/Montreal] PHP Fatal error:  Call to undefined method rcube_imap::set_mailbox() in /usr/local/topicdesk/roundcube/1.2/plugins/html5_notifier/html5_notifier.php on line 44
```

@alecpl if I turn on Safari's "Show Error Console" I do see this every time I try to paste:

```
[Error] TypeError: undefined is not an object (evaluating 'items.length')
	(anonymous function) (image_paster.js:22)
	i (tinymce.min.js:7:17473)
	fire (tinymce.min.js:7:19355)
	i (tinymce.min.js:9:11970)
	i (tinymce.min.js:2:5890)
	m (tinymce.min.js:2:6227)
```

Now I suspect the 'image_paster' plugin, and indeed removing it fixes my problem.  I forgot that my change from 1.1.5 to 1.2 also involved adding/removing some plugins.

Is this plugin part of the roundcube project itself?

**Comment by CRtEurope** [comment]
I wasn't aware of the existance of this plugin... But it does not belong to roundcube core.

**Comment by seanm** [comment]
To complete the circle, I gave this feedback to the topic desk folks (who create a roundcube installer for OS X that includes that plugin):

https://topicdesk.com/downloads/tools/roundcube-for-os-x-server/comment-page-5/#comment-1711
