### ISSUE TITLE
Contact entries with multiple e-mail addresses not recognized as "known senders"

### ISSUE THREAD

**Issue by sffax** [roundcube/roundcubemail#5291]
Since upgrading to Roundcube 1.2.0, contact entries with multiple e-mail addresses don't seem to be recognized as "known senders". Although I have the "Display remote inline images" configuration parameter set to "from known senders", I'm always getting the warning message bar (To protect your privacy, remote images are blocked in this message.) when viewing their e-mail content. Clicking the "Always show images from..." button will add them as a separate contact entry in the address book although that particular e-mail address is already listed in a separate (previous) contact object.

**Comment by alecpl** [comment]
Confirmed. This is because the separator on update is comma, but when we search we use space.
