### ISSUE TITLE
Call to undefined method rcmail::html2text()

### ISSUE THREAD

**Issue by felixendres** [roundcube/roundcubemail#5293]
Hi,
I have roundcube 1.2.0 installed on my server. When forwarding/replying/editing-as-new I get a blank page in the browser and the following error messag in the log

`PHP Fatal error:  Call to undefined method rcmail::html2text() in /var/www/services/roundcube/roundcubemail-1.2.0/program/steps/mail/compose.inc on line 920`

and also (but at a very different time, so I am not sure if it is related to the forward/reply/edit-as-new problem)

`PHP Fatal error:  Call to undefined function rcmail_save_attachment() in /var/www/services/roundcube/roundcubemail-1.2.0/program/steps/mail/compose.inc on line 1292`

I tried to debug, but my knowlede of php is a bit rusty, so I didn't get too far.

**Comment by alecpl** [comment]
Something is wrong with your installation, like some files are from 1.2 and some from an older version.

**Comment by felixendres** [comment]
thanks
