### ISSUE TITLE
Incorrect command format for moduserprefs.sh

### ISSUE THREAD

**Issue by mjnewton** [roundcube/roundcubemail#5296]
I had cause to use the bin/moduserprefs.sh command to remove some user preferences and according to the script the command format is:

> Usage: moduserprefs.sh [options] pref-name [pref-value]
>   Options:
>     --user=user-id User ID in local database
>     --config=path Location of additional configuration file
>     --delete Unset the given preference
>     --type=type Pref-value type: int, bool, string

However, running the following command didn't work:

> moduserprefs.sh --delete message_extwin

What did work though was:

> moduserprefs.sh message_extwin --delete

I believe that the command format should therefore be described as:

> Usage: moduserprefs.sh [options] pref-name [pref-value | --delete]
> Options:
>--user=user-id User ID in local database
>--config=path Location of additional configuration file
>--type=type Pref-value type: int, bool, string

(I haven't tried the --config and --type options so don't now if they too should be before the pref-name or after)

**Comment by rmcaninch** [comment]
It used to start out something like:

    print "Usage: moduserprefs.sh [--user=user-id] pref-name [pref-value|--delete]\n";

That is probably clearer that you follow the pref-name with either a value or the --delete flag.

**Comment by mjnewton** [comment]
Yes, it did seem altogether more intuitive to me to be either setting the preference *or* deleting it.

**Comment by alecpl** [comment]
--delete is an option as other options so I think the description is correct and ```moduserprefs.sh --delete pref-name``` should work as expected. No?

**Comment by mjnewton** [comment]
No; as mentioned it does not work if you supply --delete as an option:

> $ ./moduserprefs.sh --delete message_extwin
> Missing required parameters.
> Usage: moduserprefs.sh [options] pref-name [pref-value]
> Options:
> --user=user-id User ID in local database
> --config=path Location of additional configuration file
> --delete Unset the given preference
> --type=type Pref-value type: int, bool, string

It has to be supplied instead of pref-value

**Comment by alecpl** [comment]
Sorry, I didn't check. So, looks like a bug.

**Comment by mjnewton** [comment]
Thanks Aleksander!
