### ISSUE TITLE
cleandb.sh on Debian 8 / Roundcube 1.1.5

### ISSUE THREAD

**Issue by rmcaninch** [roundcube/roundcubemail#5297]
When I try to use the `cleandb.sh` I get the following error:
```
php cleandb.sh 
ERROR: Configuration error. Unsupported database driver:
```
I know the Debian Maintainers have modified how the database login credentials are handled in the main config.inc.php so I am assuming that at least the $driver is not getting passed into this properly. But I'm not sure where to start on adapting this script.

**Comment by alecpl** [comment]
Ask Debian maintainers, please.

**Comment by rmcaninch** [comment]
Just a FYI. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=824676
