### ISSUE TITLE
Include a 'Show All' button to show all messages in a folder

### ISSUE THREAD

**Issue by mjnewton** [roundcube/roundcubemail#5300]
I recognise that to minimise resource loading a folder is paginated (to a maximum of 200 messages per page it seems?) but on occasion I have a requirement to manipulate hundreds, if not thousands, of messages in one go e.g. moving a few month's worth of messages to another folder.

I was wondering if consideration could be given to adding a 'Show All' button next to the page buttons to allow a user to view a folder in its entirety? If there's one feature I unexpectedly miss from Squirrelmail this is it!

Given the potential resource issue perhaps this ought to be a configurable option that the administrator could disable if required?

**Comment by pvzweden** [comment]
I think, if you take a look at the „infinite scroll” plugin. You find something that might be of some help.

https://plugins.roundcube.net/packages/melanie2/infinitescroll

Patrick

--
Life’s short, the world is wide

**Comment by mjnewton** [comment]
Thanks for the pointer Patrick.

I have been experimenting with the 'infinite scroll' plugin however for this scenario it is not ideal as, quite understandably, it loads additional messages on an on-demand basis and so it can take quite some time to drag the scrollbar down, wait for the update, drag it again, wait for the update, drag etc etc.

Also, in removing the page buttons the plugin also removes the message count and so it is not always clear how many drag-update-drag-update cycles there are going to be! It was at the point that I realised how useful a Show All button would be!

**Comment by alecpl** [comment]
Note that while you can't see all messages at a time, you can actually select all messages in a folder and do action on this selection. I don't think we need such button.

**Comment by mjnewton** [comment]
For selecting all messages it is indeed not a problem - it is more for selecting ranges of messages that don't fit on a single page where the issue arises.

Perhaps if a button in unwarranted in your view (I'd be interested in the reasons why) then the maximum limit of 200 messages per page could be raised?

**Comment by alecpl** [comment]
max_pagesize option in config file, but if you set it to very big value you may make roundcube slow.

**Comment by mjnewton** [comment]
I suppose that's the problem of allowing large page sizes - it could have ongoing consequences whereas a 'Show All' button only has an impact during the specific usage of it (which I concede is few and far between).

Is having such a button a 'will not consider' i.e. am I pushing against a closed door on this one?

**Comment by alecpl** [comment]
The implementation may be too complicated for such a rare scenario.

**Comment by mjnewton** [comment]
Understood.

I've set max_pagesize to 10,000 and it works without any issue so for those users that require it they should hopefully be able to find their page size setting and ramp it up to that if need be (I won't set it for them as there's no reason this needs to be the default).
