### ISSUE TITLE
Add specific icon for application/pgp-keys attachment

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5301]
Now when we support PGP would be nice to display a nicer icon on attached keys.

BTW, we already have an icon for application/pgp-signature attachment, but it's no so nice. Maybe we could improve also this one.

**Comment by alecpl** [comment]
Also, an icon for encrypted part is requested here #5279. So, we need three nice icons.

**Comment by thomascube** [comment]
Icon and CSS styles added to master
