### ISSUE TITLE
Line wrapping not working

### ISSUE THREAD

**Issue by pabelenda** [roundcube/roundcubemail#5305]
Hi,

I've configured my roundcube with the following option:

`// number of chars allowed for line when wrapping text.`
`// text wrapping is done when composing/sending messages`
`$config['line_length'] = 72;`

Despite this, during composition, text lines go far beyond this limit.

**Comment by alecpl** [comment]
The text is wrapped when you send the message, not in the textarea. Also, this is for plain text only, not for HTML.

**Comment by pabelenda** [comment]
Once I send the message, the lines are still no wrapped at all, sorry, I should have said that on the initial report.

I am using plain text to compose. Roundcube version is 1.2.0, but this is also happening on 1.1.5 version.

**Comment by alecpl** [comment]
Did you check the message source? Maybe you're using format=flowed and the lines are re-wrapped on the receiving end. See ```send_format_flowed``` option.

**Comment by pabelenda** [comment]
It was this indeed. Many thanks.
