### ISSUE TITLE
Enigma plugin: store keys encrypted?

### ISSUE THREAD

**Issue by jolichter** [roundcube/roundcubemail#5306]
Hi, I would like to know if it is possible to store the private key encrypted in the sql database?
Maybe in a new release?

**Comment by alecpl** [comment]
Not possible at the moment and because you still need to decrypt them this would not make the solution much more secure. Patches welcome.

**Comment by alecpl** [comment]
Beside, the key is actually encrypted by gnupg and requires a password, so where's the point?
