### ISSUE TITLE
Enigma plugin: which key is outbound email msg encrypted to?

### ISSUE THREAD

**Issue by fsantiago07044** [roundcube/roundcubemail#5308]
i send an email to myself from my email server with RCU / engima to my gmail address in a browser using mailvelope plugin, while selecting all three options (sign, encrypt, attach) and it asks me for my (sender's) passphrase. seems to work fine from there but on the receiving side, for decryption, it asks me for the sender's passphrase....? shouldn't it be the recipient's passphrase asked for here?

**Comment by fsantiago07044** [comment]
mailvelope works as expected where it's encrypted to the recipient address's key.

**Comment by alecpl** [comment]
The passphrase is for the key used to sign the message only. Encryption is done using sender's and recipient's keys. Could you use another client, e.g. Thunderbird+Enigmail? I think it might be Mailvelope issue.

**Comment by alecpl** [comment]
... or just goto Sent folder and see if Enigma can handle this message.

**Comment by fsantiago07044** [comment]
i re-tested using a git clone of latest RC; same behavior as described. Initially i was using the official 1.2 release. 

I checked sent folder and I also tried enigma + Thunderbird; same result. on the recipient side, it asks for the sender's passphrase. I also tried only encrypting and eliminating signing and public key attachment just in case and yet same result.

**Comment by alecpl** [comment]
Try with enabled enigma_debug option. The log should give you some hints. I have no issues with Enigma.

**Comment by fsantiago07044** [comment]
i see no obvious errors in the debug log but i have saved it. see attached. i redacted my email addresses from it.
[enigma_log.txt](https://github.com/roundcube/roundcubemail/files/302677/enigma_log.txt)


i also noticed that in the rc engima interface, both my sender and recipient keys have the same identity name. so i imported a new dummy recipient public key with a different name but this made no difference.

**Comment by alecpl** [comment]
Hmm... The log is from "encrypt-only" operation, but I don't see any issues.

**Comment by fsantiago07044** [comment]
Just fetched current git which is actually from 6/6 it seems and still the same issue persists.

**Comment by alecpl** [comment]
I'm unable to reproduce with 1.2.1 nor with git-master.

**Comment by alecpl** [comment]
I'm not sure this is the same case, but I've found explanation for a case when enigma asks for passphrase for the sender key. It is when you have both secret keys (sender and recipient) in the keyring. In such a case we could check if the email address of the key already exists in user identities, but this would not help for cases when both email addresses are in identities. In my opinions it's not a bug and I don't really see how we could handle that better.
