### ISSUE TITLE
Copy-pasted text (from Word) converted to an image in TinyMCE

### ISSUE THREAD

**Issue by arthurku** [roundcube/roundcubemail#5309]
Hi there,

i am focusing with the following issue:
I am using a mac with office word (15.22). When opening the roundcube mail editor in chrome and want to copy a formatted text from word to the editor, the text will get converted into Image/png

eg.
Word:
Hello
This is a
test

will get converted to 
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAcUAAAA7CAYAAAAKLpFZAAAFwklEQVR4Ae3dO6xtQxwH4B+uR4hXQUFDcxWCwqvRqjwaGomEECSiE2p6rQjRSSSUHhFRSVQoJCoiHgkFCq94P/OLmZuVc/be9+SSc8/mm2TfPXtm1jqzvlv8M7PWmkkkAgQIECBAgAABAgQIECDwbwlcl+TUcbKb/q2TOg8BAgQIEDieAick+TPJiYtO3J/kocXvVdkec3gct/P4Ve2VESBAgACBAy2wDITLjp6RpJ9N6eskv4yAuqmdOgIECBAgsBUCy6D4x6LH3y/y543A19HgRztGlItmR7IvLtofbbR55CAZAgQIECBwEATm9OnrSRrQZlCbAa3BcN4zfHLUt99fJbkoyTy+AfaxERB7r7F1Pfayg3CR+kCAAAECBI4mcGjRoAHtxyQ/JTlrlM8HaW5McmWSC5I0vy49mOTyJD8n+TjJS0luSfLuugOUEyBAgACBgyKwDIodIc70XJLzk5wyCp5J8k2SZ5PcNRut+O59xgbEZVpOxS7L5QkQIECAwIESWN5TXObnQzbfjd6eO0Z7Hyb5bcMVvJHk1TGl2nuRHVU2kEoECBAgQODACywD4brOdjr0hXF/8Nck169rmOTWJOck6UM7XyR5OMlnG9qrIkCAAAECWymwlwA6L6wP30gECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIE/hcCF45VaVZd7F4futlru1V/QxkBAgQIENhXgQatLsXWT5dt66f5rnF6T5IHVvSmy7f9voc1UPfabsWfUESAAAECBPZfoEGxS7r1Zf3nk7wy8pcm6Uo0n6/o0idJLh7vIq6oPlK013ZHDpAhQIAAAQLHU6BBsavW/JDkgyTvj3x/Nyh2X8U5emx+po4k+y7iXPS7o8s7Z+Xie7Zr23cWo9Kd7zHOhcR7ni46LhEgQIAAgX0XONo9vwa9a8ci34/vmDJtYGvQu3kEyJfX9L7t7khy9mjXUebO1OXjTkpyWpJ7k/R+pkSAAAECBPZVYFNQ7JTqo2P0uG6Xi6fGEnDdWurLDT1/bYwqOyL8dIwYl82fSHJDkrtH4cnLSnkCBAgQILAfApuC4vLv75zunHX3Jbl6BMZOj65LXf+09y4vSdL1U09fNOy5u1bqbUneXJTLEiBAgACBfRXYa1Bc16mrkrw9AuMV6xqNUWL3apybFXfXjZm6gHjT7UneG3lfBAgQIEBg3wX+aVB8ekyFvjXuLa67gGvGCLEP0nTj4eXOGX2Qp2V9zePbdSdQToAAAQIEtkFg3dTqqr5varupbtW5lBEgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIEjrPAsa412vccj/XY43zJ/jwBAgQIENgt0PcD+1L9sbzIP3fJ2H1WJQQIECBAYAsFutNFg2I/r4/+dxuoWfbIKJsBsOWtP2/RpmWtlwgQIECAwFYLdB3SBrUGuUNjOrS/zxxbPTXfKdJ+z7VL27bpulHeBb6tSDNQfBEgQIDA9grM6dMZ1LqZcANgR4j9NP/Q2Px3GRh7xTNYbu/V6zkBAgQIEFgI9F5ig928p9gA2N+Hk1w2vjuCbOquGK2b20Q1KHZBb4kAAQIECPxnBBroGvAaGBsI+7vTp02dXm1QbH3TDIzNz/uMrZ8jzb9b+ZcAAQIECGypwBwdvjj6/9gIjA2O/TQwdnQ4f897iw2EHSm23IM2W/qfr9sECBAgsFtg50ivv1eV7T5yd7tVbZQRIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAwFqBvwAHn7EHx1HH1AAAAABJRU5ErkJggg==" alt="" />

Actually, in this editor the same thing is happening :(
Can anyone help me?

Thanks
Cheers
Arthur

**Comment by alecpl** [comment]
You mean the HTML editor in Roundcube? Then it would be TinyMCE issue. Or Chrome issue. So, we can do nothing about it. Please, check if the same happens on https://www.tinymce.com/.

**Comment by arthurku** [comment]
thanks for your message. Yes I meant the HTML editor in Roundcube.
But when inserting a text from a word file in this html editor for instance the same thing is happening.
When inserting the same text in the tinymce editor on the homepage of https://www.tinymce.com it is working

**Comment by alecpl** [comment]
It is possible that the bug is fixed in most recent version of TinyMCE or there's some additional plugin enabled we don't use.

**Comment by arthurku** [comment]
I see. thanks

**Comment by arthurku** [comment]
thanks

**Comment by alecpl** [comment]
I committed the newest version of TinyMCE to the master branch. As such changes should be carefully tested I'm not sure we should just cherry-pick this into 1.2 branch. Probably better to wait for 1.3.

**Comment by alecpl** [comment]
Backported to 1.2.
