### ISSUE TITLE
Mail compose copy-paste from Excel looses table - pasted as flat text

### ISSUE THREAD

**Issue by lv01jsi** [roundcube/roundcubemail#5311]
Copy-paste into mail compose (HTML mode) from Excel looses "table" - pasted as flat text.
Roundcube v 1.2.0
Was ok on 1.5.

**Comment by alecpl** [comment]
Please, test the most recent TinyMCE version at https://www.tinymce.com/

**Comment by lv01jsi** [comment]
Copy-paste table from Excel into mail compose (HTML):
Tinymce - 4.2.7 (distributed with Roundcube 1.2.0) - NOK (flat text pasted)
Tinymce - 4.3.13 (current tinymce) - OK (table pasted)

**Comment by alecpl** [comment]
TinyMCE was updated in master (https://github.com/roundcube/roundcubemail/commit/5e5eab3e53300290a050e7032ce94bd4064d6177). Need more testing before backporting to 1.2.

**Comment by alecpl** [comment]
Backported.

**Comment by dattabutte** [comment]
After installing Tinymce - 4.4.1,  Copy-paste table from Excel into mail compose not resolved, kindly let us know how we can resolve this issue

**Comment by satishdhanakotti** [comment]
In the Round Cube, if you copy paste the spread sheet from Drive, it will loose the table. In order to overcome this issue, **just make a copy of that sheet in your local spread sheet, format it and then copy paste into the Round Cube**. It will work.
