### ISSUE TITLE
Lack of a 'Run Search' button

### ISSUE THREAD

**Issue by mjnewton** [roundcube/roundcubemail#5312]
Having recently migrated to Roundcube I have been asking users for their feedback. Very few problems have been reported with the exception of some variation of 'search is not working'.

In every single case further investigation has revealed that the user has been typing their search string in to the search field but not knowing how to then run the search. Most have been clicking the Reset Search button or the magnifying glass modifier button at least once until they realise neither it. What they haven't realised is that they of course just need to hit Enter.

Whilst I am entirely comfortable with keyboard shortcuts, tabbing between form fields, hitting Enter for the default action etc all without a mouse, it is clear that this knowledge and familiarity is not universal. With a GUI interface I can fully understand the intuitive expectation of having a button to hit to implement an action (even if a keyboard shortcut also exists) and, as far as I can tell, this is the case in all virtually all other aspects of Roundcube (with the notable exception of 'Select All' or other range selections perhaps).

I would therefore like to suggest consideration of introducing a 'Run Search' button alongside 'Reset Search' if at all possible?

**Comment by alecpl** [comment]
I see some options here:
1. Split the search options icon into two separate icons, so arrow displays options and the magnifying glass starts the search - gmail way. Optionally the arrow icon could be put on the left of Cancel icon.
2. detect when user stops entering text, e.g. wait for a second or two (after each key stroke) and start searching automatically - that's what Thunderbird does.
3. Add "Search" button in options popup (could be inactive if the input is empty).
4. Add "Enter search string in the input and press <Enter> key to start searching." in options popup.

**Comment by bbraybrook** [comment]
i'm in favour of option 1. options dropdown icon on the left side of the dialog and search/go icon to the right of the clear field X icon at the far right of the dialog.

**Comment by mjnewton** [comment]
Took the words out of my mouth! I've just knocked up a quick mock-up to illustrate:

[Search box](http://www.newtonnet.co.uk/permanent/roundcubesearchbox.png)

**Comment by rmcaninch** [comment]
I like option 1. Like the graphic above with options on the left, search and cancel on the right. The hour glass might have a tool tip like "Hit Enter to Search".

**Comment by thomascube** [comment]
IMO starting a search by pressing Enter is quite a common pattern and people are used to do so in many programs. Most desktop programs don't have buttons to start the search. I'd close this issue in favor of adding an advanced search form (with buttons) as requested in #5052.

**Comment by mjnewton** [comment]
I'm intrigued by your observation re the UI on most desktop programs. A cursory check of a variety of programs on this Windows machine showed them all to have a button to search (in addition to the pressing Enter option) - Firefox, IE, Edge, Word, Excel, File Explorer, Adobe Reader, Autodata, iPlayer, Jalbum, Kompozer... I thought the exception was going to be Skype but interestingly it shows a button only once you start typing! Not that it matters too much but what GUI programs were you referring to that are keyboard only?

**Comment by thomascube** [comment]
I might have a different view on this as I'm a Mac user. On Mac OS, none of the commonly used applications like Apple Mail, Calendar, Contacts, Safari, Google Chrome, Thunderbird, BusyCal, Twitter have a submit button attached to the search box. So at least Mac users are used to press Enter when they search.

**Comment by mjnewton** [comment]
Ah okay, that's interesting. I suppose ways of working and interaction tend to follow patterns - as they should given that meeting expectation is a key part of good human-computer interaction. The problem is though; when multiple patterns exist which should Roundcube align with given that a web interface should ideally be platform agnostic?

Taking a different angle on this, do you see a downside to having a search button beyond, say, loss of on-screen real estate? If not, might you regard having one as merely redundant at worst?

**Comment by alecpl** [comment]
I'm also not a fan of search box modification. However, I think we can have the Search button in the search menu. This actually gives us also:
1. Possibility to search with date filter only (search box empty).
2. Easier re-searching, e.g. when you already have active search, but want to modify search criteria.
People not familiar with "[Enter] key search" will easily find the button in search options. So, it is implemented.
