### ISSUE TITLE
Enigma: GnuPG 2.1 support

### ISSUE THREAD

**Issue by lrosenman** [roundcube/roundcubemail#5313]
What is the timeframe for gpg 2.1 support?  I can decrypt/verify, but pinentry doesn't work, and gpg 2.1 is specifically called out as a reason

**Comment by lrosenman** [comment]
I get the following in the roundcube errors log:
Crypt_GPG object, and file a bug report at http://pear.php.net/bugs/report.php?package=Crypt_GPG in /usr/local/www/roundcube/plugins/enigma/lib/enigma_engine.php on line 888 (POST /?_task=mail&_unlock=loading1465568729685&_lang=en_US&_framed=1&_action=send)
thebighonker.lerctr.org /usr/local/www/roundcube/logs $

**Comment by alecpl** [comment]
There's no timeframe and this is not a prio for me. Patches welcome.

**Comment by lrosenman** [comment]
Is there a description of what the issue is and what's needed to fix it?

**Comment by alecpl** [comment]
No. I saw a few tickets here and there, but no clear description of the problem. Unfortunately the log produced by enigma_debug option is not enough and this requires more investigation.

**Comment by alecpl** [comment]
I'm working on it. There's work to be done on Crypt_GPG side and Enigma as well. In GnuPG 2.1 passphrase is required for all operations on private key including import/export. There were also some changes in "the API" but I already managed to fix them. So, this will take some time, but should be ready for Roundcube 1.3.

**Comment by alecpl** [comment]
Work in progress here: https://github.com/pear/Crypt_GPG/pull/27

**Comment by alecpl** [comment]
Patch for Crypt_GPG is almost ready. What need to happen on Enigma's side is:
1. Passphrase prompt on secret keys import.
2. Passphrase prompt on secret keys export.
3. Passing passphrase to gpg on generated key import.
The last one should be simple, but 1-2 not so much.

**Comment by alecpl** [comment]
Done. Requires Crypt_GPG 1.6.0b1.
