### ISSUE TITLE
Support responses (snippets) in HTML format

### ISSUE THREAD

**Issue by JulienCharge** [roundcube/roundcubemail#5315]
Hello everyone,

I have a few predefined response in roundcube . This avoids me to re- enter it every time the same answer.

To improve these messages , is it possible to grasp this message in html ?

For when I done my answer contains all html tags.

I would add a header footer

Thank you for your help ,

Julien

**Comment by alecpl** [comment]
Not, possible at the moment.

**Comment by abumalick** [comment]
I hope it will be available soon !
Thanks

**Comment by NLLucifer** [comment]
Is there any news on this? I'd really like to use HTML snippets (URL, Images, Bold/Italic) in my responses!

**Comment by fodorgeza** [comment]
OK, not implemented, it's clear. But why? It is not a big challenge, is it? ;)

**Comment by alecpl** [comment]
Maybe that's why it's not implemented ;) Seriously, there's a limited set of developers in the project and that's not the highest prio. Pull requests appreciated.

**Comment by fodorgeza** [comment]
Well, but since 2016... We all know, that UI is far more important for the users as any not visible backand hack.
Thank you, we think about it.

**Comment by alecpl** [comment]
Implemented.

**Comment by fodorgeza** [comment]
Thank.


Aleksander Machniak ***@***.***> ezt írta (időpont: 2021.
aug. 28., Szo 19:17):

**Comment by MysticMedusa** [comment]
Hello, I came here looking for a solution to my Text-only Response fields. It says above it's been implemented - thank you - but I don't see any editing options in my Roundcube back end. How do I enable this please? Being able to have live links in Responses would save a huge amount of time.

**Comment by alecpl** [comment]
You need at least Roundcube 1.6.

**Comment by MysticMedusa** [comment]
Thanks for this - I access mine via C-panel and assumed it was auto-updated but apparently not!
