### ISSUE TITLE
Server Error: APPEND: Invalid APPEND command syntax...

### ISSUE THREAD

**Issue by leonkyneur** [roundcube/roundcubemail#5317]
Roundcube 1.2.0

Recently put Dovecot in proxy mode in front of my IMAP server and seeing now 'Invalid APPEND command syntax' error when saving to Drafts.

Testing with other clients not having an issue - Thunderbird, outlook and atmail webmail are fine. Can see in tcpdump that this may be a \r\n handling error - not sure if in RC or Dovecot. Given this is working on other clients I am assuming RC here...

```
A0003 OK LIST completed
A0004 APPEND Drafts (\Seen) {271+} <- + in the braces should be server response '+READY ?'
```

Side by side wireshark images where I am seeing the error (left side is working):

![screenshot from 2016-06-12 02-04-54](https://cloud.githubusercontent.com/assets/933768/15986732/170ed3ca-3042-11e6-8540-9a3ccba5b4bc.png)

Also found the following ref links:

1. http://www.heidler.eu/2014/03/05/strange-imap-proxy.html

2. http://www.roundcubeforum.net/index.php?topic=23269.0

**Comment by alecpl** [comment]
It looks that Roundcube uses LITERAL+ here, so "+ READY" response is not expected. \r\n is also correct. So, maybe that's some proxy issue in LITERAL+ handling.You can disable use of LITERAL+ feature in Roundcube by adding "LITERAL+" to the imap_disabled_caps array in config.

**Comment by leonkyneur** [comment]
Thanks tried your suggestion very quickly however I seemed to get other errors accessing folders. 

I'll test again later when I have some more time

**Comment by alecpl** [comment]
You may want to try also imap_force_caps=true.
