### ISSUE TITLE
Issue with saving vcard data

### ISSUE THREAD

**Issue by yanky83** [roundcube/roundcubemail#5318]
Hello,

this may actually lack of knowledge on how to use the classes correctly, but I am having an issue with importing vcard data via the rcube_contacts->insert method:

Following code snippet
				$new_contact = array();
				$new_contact['name'] = $sql_arr_contacts['name'];
				$new_contact['email'] = $sql_arr_contacts['email'];
				$new_contact['firstname'] = $sql_arr_contacts['firstname'];
				$new_contact['surname'] = $sql_arr_contacts['surname'];
				$new_contact['vcard'] = $sql_arr_contacts['vcard'];
				$contacts->insert($new_contact);

This is the input data (from $sql_arr_contacts['vcard']):

BEGIN:VCARD
VERSION:3.0
N:Hahn;Peter;;;
FN:Peter Hahn
EMAIL;TYPE=INTERNET;TYPE=HOME:phahn@web.de
EMAIL;TYPE=INTERNET;TYPE=WORK:phahn@web.com
END:VCARD

and this is what ends up getting stored in the database:

BEGIN:VCARD
 VERSION:3.0
 N:Hahn;Peter;;;
 FN:Peter Hahn
 EMAIL;TYPE=INTERNET:phahn@web.de,phahn@web.com,
 END:VCARD

which obviously leads to data being displayed incorrectly.

Any advice much appreciated, and my apologies if the mistake seems obvious.

Latest roundcube install on PHP7 and Apache2.4, MySQL 5.7

Regards

**Comment by alecpl** [comment]
It's because rcube_contacts::insert() method calls rcube_contacts::convert_save_data() which overwrites vcard fields by values defined in input array. So, instead of 'email' element you have to define 'email:home', 'email:work', etc. However, I'm not sure we already support two home emails.

**Comment by yanky83** [comment]
Thanks alecpl

The behavior seems odd, because when I import the same vcard data via the roundcube webinterface, it works as expected.

How would I correctly import the vcard data via PHP, without writing it directly to the DB (via SQL)?
