### ISSUE TITLE
Plugin installation via composer removes pear

### ISSUE THREAD

**Issue by yanky83** [roundcube/roundcubemail#5319]
The default install of roundcube comes with pear/pear-core-minimal. 

This is however missing from composer.json, meaning, once compser runs to install plugins, PEAR is removed, which obviously breaks roundcube.

Could this be added to default composer.json file?

**Comment by alecpl** [comment]
Roundcube itself does not require pear/exception, this is a dependency of other packages. I don't see why it would have been removed. Could you describe your steps?

**Comment by yanky83** [comment]
When roundcube is downloaded, the vendor folder contains pear/pear-core-minimal.
Once composer is run with unchanged json file, this folder is removed (by composer, since its missing in json).
On a system with no Pear installed elsewhere, this breaks e.g. the roundcube installer, throwing error messages at Pear check. It further breaks at several other instances.

This can easily be rectified by adding pear/pear-core-minimal to composer.json. I was wondering, if this could be included by default to avoid potential hassles.

Is that understandable?

**Comment by alecpl** [comment]
I understand, but this should not happen. You use original composer.json-dist? You just execute composer update? I'd say something is wrong there, maybe some composer bug. Are you using most recent version?

pear/pear-core-minimal is a dependency of roundcube/net_sieve at least.

**Comment by yanky83** [comment]
Ah, that may be the issue, I removed net_sieve. However, it may be preferable to explicitly add pear, since it still seems to be required, even without sieve.

**Comment by alecpl** [comment]
Hmm... From what I see PEAR.php is required by: Net_LDAP2, Auth_SASL, Mail_Mime, Net_Socket, Net_SMTP. Problem probably is that they are installed from PEAR not from packagist, so their dependencies aren't resolved correctly. So, indeed we should explicitly require it in composer.json.
