### ISSUE TITLE
Enigma: Export private keys

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5321]
When I export my own key then the public key is exported only. Not the private key. Is there a chance to export the private key too, for example, for importing it into Thunderbird or something?

Master-branch
PHP7

**Comment by alecpl** [comment]
Not possible at the moment. Need to implement this first in Crypt_GPG. Then we'd need a dialog for the user so he can select (and be aware of) the export scope.

**Comment by alecpl** [comment]
And/Or we could add "Export private key" button in key information frame only where the private key exists.

**Comment by CRtEurope** [comment]
That would be really awesome, Alec. Keys are generated server-side and people ask for this possibility.

**Comment by alecpl** [comment]
Implemented.

**Comment by CRtEurope** [comment]
Unfortunately I have to re-open it.
It is not working to export the private key. I get a page with file not found.

![file_not_found](https://cloud.githubusercontent.com/assets/16518395/16205257/419bbf58-3723-11e6-9ad8-534f8e4fa3ef.jpg)

Exporting the public key is working.

Master-branch
PHP 7.0

**Comment by CRtEurope** [comment]
```
  thrown in /plugins/enigma/lib/enigma_driver_gnupg.php on line 228
[20-Jun-2016 20:18:05 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method Crypt_GPG::exportPrivateKey() in /plugins/enigma/lib/enigma_driver_gnupg.php:228
Stack trace:
#0 /plugins/enigma/lib/enigma_engine.php(1136): enigma_driver_gnupg->export('4ABD47726EEE907...', true)
#1 /plugins/enigma/lib/enigma_ui.php(486): enigma_engine->export_key('4ABD47726EEE907...', Resource id #25, true)
#2 /plugins/enigma/lib/enigma_ui.php(63): enigma_ui->key_export()
#3 /plugins/enigma/enigma.php(420): enigma_ui->init()
#4 /program/lib/Roundcube/rcube_plugin_api.php(491): enigma->preferences_ui()
#5 /index.php(277): rcube_plugin_api->exec_action('plugin.enigmake...')
#6 {main}

```

**Comment by alecpl** [comment]
You need Crypt_GPG 1.4.2.

**Comment by CRtEurope** [comment]
Now I get this error and a blank page after updating with composer:
`[20-Jun-2016 21:18:47 Europe/Berlin] PHP Fatal error:  Cannot declare class rcube_plugin_api, because the name is already in use in /program/lib/Roundcube/rcube_plugin.php on line 30`

**Comment by CRtEurope** [comment]
Can be closed. it is working now. Somehow the package mail_mimedecode was missing... Very strange. Installed, restarted apache and memcached, everything is working great...

**Comment by ClocxHD** [comment]
I've upgraded to Roundcube 1.2.1, but there is no "Export private button".
Isn't it implemented?
I use Enigma 0.5.

**Comment by CRtEurope** [comment]
It is there...

![pgp_export](https://cloud.githubusercontent.com/assets/16518395/17901173/96906358-6962-11e6-8600-14affad33378.png)

**Comment by ClocxHD** [comment]
If i click on the "Export"-Button on the top left side in Settings --> PGP-Keys it directly downloads the public key, i cannot choose.
These are the available Buttons:
![Buttons](https://puu.sh/qLE0d/ef9fa14bcf.png)
(Import, Export all and export selection) Both just downloads the public keys.

**Comment by CRtEurope** [comment]
What's your Crypt_GPG version?

**Comment by ClocxHD** [comment]
My Crypt_GPG-Version: 1.4.20-1ubuntu3.1

**Comment by CRtEurope** [comment]
Install composer and use composer to install it. Take a look in the root folder of roundcube, there is a description how to use it.

**Comment by ClocxHD** [comment]
This is the line in my composer.json:
"pear-pear.php.net/crypt_gpg": "~1.4.2"
(I downloaded the roundcube.tar.gz today, so the composer.json should be up to date.)
Composer says that all packages are up to date
