### ISSUE TITLE
BCC visible in recieved e-mails

### ISSUE THREAD

**Issue by berthz** [roundcube/roundcubemail#5322]
I have noticed that when using more than 5 or 6 e-mail addresses in the BCC the recipients see all the BCC e-mail addresses in the sent-from box. This should not happen. BCC should always be invisible to all recipients. 

Using Roundcuibe webmail 1.2.0. Attached a screenshot of the sent mail and the recieved mail.

Sent mail:
![sent](https://cloud.githubusercontent.com/assets/6369504/16035953/0f313b14-321a-11e6-8213-39222268a658.jpg)

Recieved mail:
![recieved](https://cloud.githubusercontent.com/assets/6369504/16035955/11d8c8dc-321a-11e6-8220-f6f2c1844b67.jpg)

**Comment by alecpl** [comment]
I'm unable to reproduce. Disable all plugins for test and enable smtp_debug. Then see what's really send to the SMTP server.

**Comment by berthz** [comment]
We will test this. Thanks for the reply. Please be aware that BCC is working when all the recipient e-mail addresses fit in one line. As soon as the BCC line extends to the second line the recievers see all e-mail addresses.

**Comment by berthz** [comment]
Alexander. That is correct indeed! We already figured that out, but I should have updated this issue. The server setting was using php's mail() function instead of the smtp server. After changing everything worked like a charm.
