### ISSUE TITLE
Suspect Message Warning in Message Read Pane

### ISSUE THREAD

**Issue by rob9** [roundcube/roundcubemail#5325]
I would like to out a yellow banner warning abut certain email messages

- the banner should appear in the message pane below the date, immediately above the message content
- the banner should appear for suspicious messages
- the color should be yellow 

The banner should appear in the following cases:
1. header Received-SPF exists and does not begin with Pass
2. header Authentication-Results exists and does not contain dkim=pass
3. the top-most Received header does not contain "Verified OK" (ie. sender's server has trusted certificate)

Does something like this already exist?

If writing a plugin or code change is required, could friendly reader please suggest how this could be done?

**Comment by Takika** [comment]
Try this plugin: https://github.com/pimlie/authres_status
