### ISSUE TITLE
Session invalid every few seconds

### ISSUE THREAD

**Issue by jmzbond** [roundcube/roundcubemail#5328]
Every once in awhile, I'll have a period of sheer frustration where (let's say for 30 minutes), I'll log into RoundCube and almost immediately it will kick me out with a session invalid error. There seems to be no rhyme/reason to when I get kicked out. Sometimes literally I'll have just logged in, not clicked anything else, and will get booted to log in screen. Other times I will be reading/ composing a message (or reply) when it will do so. I've noticed that when I'm composing a message or reply, it won't boot me to the log in screen, just pop up an alert. I can still type the message, but when I try to send it will give me an error. Does anyone else have this issue?

**Comment by alecpl** [comment]
Not enough information. Ask on mailing list or forum. Provide information about your system and configuration.

**Comment by dsoares** [comment]
Suggestion: enable the configuration options in `config/config.inc.php`:
```
$config['debug_level'] = 1;
$config['log_session'] = true;
```
and check the logs.
