### ISSUE TITLE
Error in  program/steps/addressbook/func.inc

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5331]
The following error now appears in the log file:
`[17-Jun-2016 14:07:16 Europe/Berlin] PHP Parse error: syntax error, unexpected '$edit_mode' (T_VARIABLE) in /program/steps/addressbook/func.inc on line 536`

hopefully this can be reviewed.

System php7 and master-branch

**Comment by alecpl** [comment]
Fixed
