### ISSUE TITLE
Outlook emails with base64 encoding are not displayed properly

### ISSUE THREAD

**Issue by scriptPilot** [roundcube/roundcubemail#5332]
Hello, thanks for the great piece of application!

Unfortunately there is a bug while displaying Outlook emails.

Base64 encoded content is not displayed - the code as following:

![bild 40](https://cloud.githubusercontent.com/assets/19615586/16171341/b8d9a9c6-356c-11e6-84a5-5d30f1f5aab8.png)

**Comment by scriptPilot** [comment]
I have detected the same behaviour now with wuoted-printable code ... maybe it's because of the boundary? Next not shown content:


_--_000_e16be91c26d64f7488cf636d5abb082aDE044DAG02P01centralmai_
Content-Type: text/html; charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft ...._

**Comment by alecpl** [comment]
Most likely this is IMAP server issue as Roundcube depends on BODYSTRUCTURE responses. It does not parse email. Enable imap_debug and check the log. It may be also problem with BINARY extension, again on IMAP server side.

**Comment by scriptPilot** [comment]
Okay, so where could I find that config file within an ownCloud installation?

**Comment by scriptPilot** [comment]
I have interchanged two applications, the issue occured in RainLoop.
So, the bug could be closed here ... sorry for the circumstances!
