### ISSUE TITLE
Not working union of few emails to one conversation in Roundсube

### ISSUE THREAD

**Issue by mahmadinurov** [roundcube/roundcubemail#5333]
Hi there!

I have a problem when using Roundcube will be grateful for your help.

1. I send a new message in Roundcube to the email address xxxxxx@mail.ru (popular email service in Russia)
2. I went to the mail.ru and write a response to this letter.
3. The answer comes on Roundcube server, but is shown as a single message - it is not stick together to the first letter.

As a result, all the letters in a single conversation is not united, it is very inconvenient.

The source code messages always contain the 'Message-ID' and 'In-Reply-To' information:
In-Reply-To: <1466417956.531326155@f406.i.mail.ru>
Message-ID: <3f36040e3e6250e81bd6f174461762b8@xxx.ru>

Not clear to me why the letters are not joined.

**We use:**
Roundcube Webmail 1.1.4
archive 2.3
filesystem_attachments 1.0
jqueryui 1.10.4
zipdownload 3.0

**Comment by alecpl** [comment]
Did you set view mode to threading? Enable imap_debug in Roundcube and check the log. This is likely IMAP server issue.
