### ISSUE TITLE
Roundcube depends on www-data being Apache's username

### ISSUE THREAD

**Issue by Yhoko** [roundcube/roundcubemail#5337]
The installation already failed because I renamed my Apache's user and group names. I got around this by temporarily renaming both so Roundcube could install. However now I get this error from the cron daemon:

error: roundcube-core:2 unknown user 'www-data'

The error log in /var/log/roundcube/errors is empty.

**Comment by alecpl** [comment]
I have no idea what roundcube-core is. This looks like a packaging issue.
