### ISSUE TITLE
error sending email to same domain

### ISSUE THREAD

**Issue by Daaru00** [roundcube/roundcubemail#5338]
receiving an error on Roundcube Webmail 1.1.4 when I try to send an email to an other email address with same domain (example info@mydomain.com to test@mydomain.com), if I send to an other domain name everything work both sending and receiving.

I can't find any specific information about this error, a popup error in frontend show me "Unable to send the message", roundcube's log is empty (I activate sql_debug, imap_debug, ldap_debug, smtp_debug) no error messages neither in apache error log.
Seems roundcube not starting at all the sending procedure.

my system is:

Ubuntu 14.04
Apache 2.4.7
PHP 5.5.9-1ubuntu4.17 (cli)

**Comment by alecpl** [comment]
... or your logging configuration is wrong. And I don't see "Unable to send the message" string in Roundcube. It may be "Failed to send message" and this can have a few reasons, but I expect something in log. Disable all plugins. Make sure logging works.

**Comment by Daaru00** [comment]
I have a different language therefore I translate the error messsage. 
The debugging log work, I try to send message, save to draft and I correct see the log, but when I try to replicate that error no line is written. 

Now I tried  to disable all plugins but the issue persist.

my configuration file is:

```
...default configurations...

// skin name: folder from skins/
$config['skin'] = 'larry';
$config['db_dsnw'] = 'mysql://connection_string';
$config['default_host'] = 'mail.mydomain.it';
$config['product_name'] = 'Webmail';
$config['mdn_use_from'] = true;
$config['language'] = 'it_IT';
$config['smtp_server'] = '';
$config['smtp_port']= 465;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
//$config['plugins'] = array('archive', 'zipdownload', 'managesieve' );
$config['plugins'] = array();

// system error reporting, sum of: 1 = log; 4 = show
$config['debug_level'] = 4;

// Log SQL queries
$config['sql_debug'] = true;

// Log IMAP conversation
$config['imap_debug'] = true;

// Log LDAP conversation
$config['ldap_debug'] = true;

// Log SMTP conversation
$config['smtp_debug'] = true;
```

**Comment by alecpl** [comment]
Don't ever use debug_level=4, set it to 1, please.

**Comment by Daaru00** [comment]
ok, but I still no see any information about that mail transaction. 
Every other mail is correctly logged.

cat logs/errors
```
[27-Jun-2016 08:49:15 +0000]: <hnqgqhr5> IMAP Error: Login failed for presidente@mydomain.it from 87.15.205.147. AUTHENTICATE PLAIN: * OK Waiting for authentication master process to respond.. in /var/www/webmail/program/lib/Roundcube/rcube_imap.php on line 197 (POST /?_task=mail&_action=refresh?_task=&_action=)
```
It's only a incorrect login but the mail that I try to send is test@mydomain.it to info@mydomain.it

tail -n 30 logs/sendmail
```
[26-Jun-2016 17:22:39 +0000]: <3t8kjg3o> User presidente@mydomain.it [87.15.205.147]; Message for conilvento2@otherdomain.it; 
[26-Jun-2016 17:26:12 +0000]: <3t8kjg3o> User presidente@mydomain.it [87.15.205.147]; Message for segreteria@otherdomain.com; 
[26-Jun-2016 18:37:51 +0000]: <0d6g8mv6> User presidente@mydomain.it [87.15.205.147]; Message for arrighikatia@otherdomain.com; 
[27-Jun-2016 08:29:59 +0000]: <fk71dk7i> User amministrazione@mydomain.it [213.144.74.226]; Message for testa_valentina@otherdomain.it; 
[27-Jun-2016 08:30:25 +0000]: <fk71dk7i> User amministrazione@firp.it [213.144.74.226]; Message for mx.passera@otherdomain.com; 
[27-Jun-2016 08:31:05 +0000]: <fk71dk7i> User amministrazione@firp.it [213.144.74.226]; Message for michelacanova268@otherdomain.com; 
```
imap and sql log is too long to paste here

**Comment by alecpl** [comment]
Is there any reason to not use SMTP server? According to your config you use PHP mail functionality and I wouldn't call it reliable. Set smtp_server, this would give you at least some better debug information.

**Comment by Daaru00** [comment]
If I set that option I reach a connection timeout error

```
$config['smtp_server'] = 'mail.mydomain.it';
```
also with
```
$config['smtp_server'] = 'tls://mail.mydomain.it';
```

**Comment by alecpl** [comment]
Firewall or DNS issue or wrong smtp_port.

**Comment by Daaru00** [comment]
If I send email to an other hostname everything goes right, mydomain to otherdomain, both incoming and outcoming.

Seems the DNS configuration is correct, if I use a desktop client I have not problem.

**Comment by alecpl** [comment]
Anyway configuration issue.

**Comment by Daaru00** [comment]
seriously? 
there is a setting $config['send_same_domain'] = false?

It's no currently resolved, I'll using a different version or different application

**Comment by rmcaninch** [comment]
@Daaru00 try the support forum. http://www.roundcubeforum.net
For configuration help.

**Comment by Daaru00** [comment]
@rmcaninch the problem is "**error sending email to same domain**", is a configuration error?

**Comment by rmcaninch** [comment]
Aleksander Would know better than me. Certainly sounds like it. Try using telnet from the server that has roundcube to manually do a smtp session. Check google if you're not sure how.

**Comment by Daaru00** [comment]
@rmcaninch if I use a desktop client I haven't any problem, therefore the problem in not in the STMP protocol.

I downgrade to 1.1.3 and the problem is solved.
