### ISSUE TITLE
RC release-1.2 dont_override skin

### ISSUE THREAD

**Issue by andypl78** [roundcube/roundcubemail#5343]
Latest release 1.2 dont_override not working
source config.inc.php

`$config['dont_override'] = array('skin'); `

**Comment by alecpl** [comment]
Works for me. I set dont_override=array('skin') and skin='classic' in config.inc.php and the skin changes immediately to classic.

**Comment by andypl78** [comment]
I have set on config.inc.php and i can select another skin
$config['skin'] = 'classic';
$config['dont_override'] = array('skin');

![rc-theme](https://cloud.githubusercontent.com/assets/7813646/16534916/b16c5e3c-3fe3-11e6-8640-94793d4ea322.jpg)

**Comment by alecpl** [comment]
Maybe you have dont_override option twice in the config file? Or you have it in some plugin config or sth.

**Comment by andypl78** [comment]
The problem is in your plugin authres_status
He was the overrides settings: dont_override

https://plugins.roundcube.net/packages/roundcube/authres_status

**Comment by alecpl** [comment]
This is not our problem.
