### ISSUE TITLE
Idea for new Feature

### ISSUE THREAD

**Issue by Kuurusch** [roundcube/roundcubemail#5344]
Hey, have you already thought about a feature which would make it possible, that all the mails in the incoming and outgoing folder are encrypted and are only decrypted with the password I youse for my mail-account?
Would something like this be possible? So than it is not necessary to store the secret key on the server or at least only a password-protected one.

**Comment by alecpl** [comment]
That would make more sense if implemented server-side. So, the incoming message is encrypted when it comes to the server, not when you access it with Roundcube. Probably some scripting with sieve filters would allow this. Anyway, I don't see much sense in such a feature.
