### ISSUE TITLE
message_before_send return issues

### ISSUE THREAD

**Issue by smelliott100** [roundcube/roundcubemail#5347]
it appears that the return on message_before_send does not function for:
1) mailto: if sending from php mail  in rcube.php (1622)  the to address is taken from: $to  = $headers['To'], not from the returned  $mailto 

2) when returning error  the message is not displayed in the error box and there are two warnings entered in errorlog   PHP Warning:  Illegal string offset 'label' (and 'vars') in /home/../../program/steps/mail/sendmail.inc on line 539

**Comment by alecpl** [comment]
1. Indeed, we should fix this, but anyway we intend to drop php mail support.
2. Indeed, we should support error as simple string.
