### ISSUE TITLE
Export entire folder

### ISSUE THREAD

**Issue by filhocf** [roundcube/roundcubemail#5348]
Hi

I tried to follow the help of Roundcube[1] to export a folder, but I haven't the options explained in to help. I'm using the version 1.2.0. Do I need enable some plugin to this action?

Thanks in advance,
Claudio Ferreira

[1]https://docs.roundcube.net/doc/help/1.1/en_US/mail/importexport.html#export-an-entire-folder

**Comment by filhocf** [comment]
Any update?

**Comment by alecpl** [comment]
There's indeed no such feature in 1.2. You can however, select all messages in a folder and then use More > Download... (if zipdownload plugin is enabled).

**Comment by alfista-sk** [comment]
Hi, I try it too but it doesn't work.
I have also activated the zip download plugin, but still no change. It will not work.

Please canyon help me?
I use RC 1.1.4 and see that the zip download plugin is active in about.

Thanks.

**Comment by QaisarMahmood** [comment]
Any update about this topic yet no any option to export zip folder of all emails?

**Comment by filhocf** [comment]
Sorry @alecpl , but i agree with @QaisarMahmood. 

Haven't a option to download an entire folder or yet a selected mails set as you suggested.

**Comment by alecpl** [comment]
Configure zipdownload plugin! I mean see the config file of the plugin.

**Comment by QaisarMahmood** [comment]
Thanks for Immediately response. 
I'm using shared server of Godady, it is not possible to put plugin into plugins directory of Roundcube.
Please can you elaborate how is it possible?

**Comment by filhocf** [comment]
Now I saw. The problem is a conflict with menucontext plugin. I will open a issue for then.

Anyway, it is a recorrent feature for comercial users. I have a base with +3k users and a lot of then ask about this resource.

**Comment by ibikhan1234** [comment]
Amazing tool for Roundscube Bulk email sending and Automation

https://www.fiverr.com/s2/9c05060dfd
