### ISSUE TITLE
CSS are not correctly displayed

### ISSUE THREAD

**Issue by emilio-valencia** [roundcube/roundcubemail#5349]
Hi,

I have configured roundcube 1.2.0 complete version in a Solaris 11 server with Apache 2.4 and PHP 5.6. When I logon into the roundcube webmail with Chrome V51, the page is not correctly displayed, I can see the mails but it is not displayed in a proper way. If I use IE8 with legacy_browser plugin the page is correctly displayed. With the developer tool in Chrome I get the error: "Resource interpreted as Stylesheet but transferred with MIME type text/html"

I guess it is due to a misconfiguration but after days fighting with it I cannot fix it. Could you help me?

Regards.

**Comment by alecpl** [comment]
Ask on mailing list or forum. Not a bug.
