### ISSUE TITLE
Cannot forward/reply randomly over 10k message

### ISSUE THREAD

**Issue by sixdayhun** [roundcube/roundcubemail#5355]
Hi,

I'm running a freshly installed mailserver with roundcube 1.1.5, with a couple of hundred mailboxes.
The problem is that in mailboxes where more than 10k emails in the inbox I'm having the following errors (this specific box has 14k emails in the inbox):

[12-Jul-2016 12:52:04 +0200]: <9fmm72vo> PHP Error: Invalid compose ID in /usr/local/www/roundcube/program/steps/mail/sendmail.inc on line 39 (POST /webmail/?_task=mail&_unlock=loading1468320724249&_lang=undefined&_framed=1?_task=mail&_action=send)

I found an old thread about this issue in roundcube forum as well, no solutions there unfortuantely.

http://www.roundcubeforum.net/index.php?topic=10913.0

Thanks.
Gabor

**Comment by alecpl** [comment]
Upgrade. We do not support this version and there was some related fixes in 1.2.

**Comment by sixdayhun** [comment]
Thanks, I'll upgrade then.
But please upgrade your Downloads page (https://roundcube.net/download/), because it says 1.1.5 is the LTS version, not "unsupported".
Cheers.

**Comment by Vladimir99999** [comment]
HI,
Problem still exists (1.2.4). In the logs it looks like this:
[17-Mar-2017 08:39:04 +0200]: <uek2cp64> PHP Error: Invalid compose ID
in /usr/local/www/roundcube/program/steps/mail/sendmail.inc on line 39
(POST
/?_task=mail&_unlock=loading1489732744474&_lang=ru&_framed=1&_action=send)

Thanks.

**Comment by dbucher** [comment]
Same problem ! Version 1.2.5
