### ISSUE TITLE
Provide a better way to set dynamic labels to views

### ISSUE THREAD

**Issue by fabioperrella** [roundcube/roundcubemail#5356]
Hi, I have a view which I would like to use a dynamic variable (error_message) set in action to print a message, like this:

```html
<label><roundcube:label name="error_message" /></label>
```
So it would be necessary set this label dynamically, like bellow, but it is not possible:

```php
if(any_condition)
  $this->rcmail->output->set_label('error_message', "some message...");
else
  $this->rcmail->output->set_label('error_message', "other message...");
```

Is there a better way to do so?

Otherwise, what about creating a method `set_env` in rcmail_output class?

**Comment by alecpl** [comment]
There's set_env() method in rcube_output.

**Comment by fabioperrella** [comment]
@alecpl set_env calls `html::quote`. I was trying to use a label with option `quoting=no`

What about adding an option "quoting" to envs?
