### ISSUE TITLE
Cannot download attachment-only message

### ISSUE THREAD

**Issue by rigrig** [roundcube/roundcubemail#5357]
I received a DMARC report from Google, in an e-mail that only contains a zip file, no other content whatsoever:
```
Content-Type: application/zip; 
	name="google.com!tubul.net!1468281600!1468367999.zip"
Content-Disposition: attachment; 
	filename="google.com!tubul.net!1468281600!1468367999.zip"
```
Roundcube doesn't let me download the zip file: the message panel shows the header, but no content or list of files, so no way to download the attachment.
Disabling all plugins, using another theme, or opening the message in a new window doesn't help.
Forwarding the message works: it includes the attachment and adds some text content, and I can download the attachment from the forwarded message.

Steps to reproduce:
1) Receive a message that consists solely of a single attached zip file
  (I don't know how to send one of these, and forwarding it adds content, so doesn't reproduce the issue)
2) View the message

Actual result:
-> See an empty panel, with no way to download the attachment

Expected result:
-> See an empty panel and the list of attached files
or
-> See a message indicating that there was no text content, and the list of attached files

Software versions:
Roundcube Webmail 1.3-git \[GIT 20160701.1012\] revision 3d9e170d8b2aed545749a86028d4e17758f562c1
Apache/2.4.10
PHP 7.0.8-1~dotdeb+8.1
PostgreSQL 9.4.8

Message: [message.eml.txt](https://github.com/roundcube/roundcubemail/files/362191/message.eml.txt)
![screenshot](https://cloud.githubusercontent.com/assets/2941436/16815338/ba75c978-4939-11e6-8c74-6e7d8e30a545.png)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
It was a regression from 323fa20bc8. Fixed. Thanks for such a detailed report.

**Comment by rigrig** [comment]
Confirmed it works now. Thanks for fixing it this quickly.
