### ISSUE TITLE
PHP: faulty sourcing of directive error_reporting may trigger failure of installation wizzard and Roundcube

### ISSUE THREAD

**Issue by pmattern** [roundcube/roundcubemail#5358]
Faulty sourcing of PHP directive `error_reporting` can make both the installation wizzard and Roundcube itself fail and throw a warning
> ERROR: Wrong 'error_reporting' option value and it wasn't possible to set it to required value (30711). Check your PHP configuration (including php_admin_flag).

The problem gets manifest when `error_reporting` is set to `32759` which is corresponding to `E_ALL & ~E_NOTICE` in PHP ≥ 5.4 within a [host or path specific section](http://php.net/manual/en/ini.sections.php) of the PHP configuration as e. g. used by nginx / PHP-FPM or via Apache directive `php_[admin_]value` within a virtual host section of the web server's configuration.
Both times the value of `error_reporting` was set to its expected value `32759` according to `phpinfo()` invoked in Roundcube's root directory.
The problem ceases when `32759` is replaced with `30711` or when `32759` is set in section `[PHP]` of the main PHP configuration. As for Apache it cannot be seen either when the same `php_[admin_]_value` directive is added to `.htaccess` in Roundcube's root directory.

Integer `30711` was corresponding to `E_ALL & ~E_NOTICE` in PHP 5.3, see [Predefined Constants](http://php.net/manual/en/errorfunc.constants.php#errorfunc.constants.errorlevels.e-all) of the PHP manual. So is a specific setup as depicted above by any chance preventing Roundcube from recognizing the PHP version in use?

Seen on Arch Linux x86_64 running either Apache 2.4.23, PHP 7.0.8 via the Apache module and Roundcube 3d9e170 or nginx 1.6.1, PHP 5.5.15 via PHP-FPM and Roundcube 58c0361.
A similar problem was solved in #4331.

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/bootstrap.php#L28

We actually use constants, so the number value is displayed only in the error message for specified PHP version. Indeed for every PHP version the number can be different. Maybe I don't understand the problem in all aspects, but it doesn't sound serious. What fix do you expect?

**Comment by pmattern** [comment]
Well, what I'd expect is wizzard and Roundcube don't fail claiming the configuration of the underlying server is faulty when it isn't.

Tbh. I can only figure there's some misunderstanding so here's an attempt to explain more verbosely:
As for Apache / PHP module all PHP directives were imported in an Apache configuration file `/etc/httpd/conf/vhosts/foo.conf` which is in turn sourced by `/etc/httpd/conf/httpd.conf` and states
```
<Directory "/usr/share/roundcube">
  [...]
  php_admin_value error_reporting "32759"
  [...]
```
As for nginx / PHP-FPM the directive was set in a application-specific section of `/etc/conf.d/vhosts.ini` which is sourced by `/etc/php.ini` and states
```
[PATH=/usr/share/roundcube]
[...]
error_reporting = 32759
[...]
```
Both times the correct value is applied as indicated by `phpinfo()` invoked in Roundcube's root directory
![roundcube_error-reporting-faulty-sourcing_phpinfo-correct](https://cloud.githubusercontent.com/assets/9860801/16877391/1a78b4ce-4aa8-11e6-90cd-570cad2fc0f8.png)
but the installer fails throwing the message posted in the first comment.
The problem ceases when `32759` gets replaced with `30711` (which is *not* corresponding to `E_ALL & ~E_NOTICE` in PHP ≥ 5.4 any longer) in the two files stated above, when `32759` is not set in any of the two files but on a per server basis in `/etc/php/php.ini` or as for Apache as well when the directive is set in `./.htaccess` in the FHS.
Problem can be seen with Roundcube itself the same way when directive `error_reporting` had been set in a way circumventing the problem during installation and gets changed afterwards only.

**Comment by alecpl** [comment]
If the code says it should be 30711, you have to set it to 30711. That's it!

**Comment by pmattern** [comment]
`error_reporting` is set to 32759 as indicated by `phpinfo()`, see screenshot in my previous comment.

30711 is the wrong value as of PHP ≥ 5.4.
`E_NOTICE` is and has always been corresponding to integer `8`. `E_ALL` is corresponding to 32767 as of PHP 5.4 and was corresponding to 30719 in PHP 5.3.
Hence `E_ALL & ~E_NOTICE` was corresponding go 30711 in PHP 5.3 but is 32759 as of PHP 5.4.

**Comment by alecpl** [comment]
I pointed you to the code. Roundcube requires  E_ALL & ~E_NOTICE & ~E_STRICT, which in your PHP version is 30711. In different Roundcube version it could be different (e.g. in 1.1 it also excluded E_DEPRECATED). You have to set it to the value that is required. Sorry, I don't see an issue here.

**Comment by Drakota** [comment]
Sorry to reopen this, but I have the same issue as @pmattern, I'd like some help on how to fix it. I tried changing the variable in the code @alecpl linked, but to no avail. It changes the error to different code like 0, -32768 or 32768. Some help would be appreciated.

**Comment by hawk2012** [comment]
This error has been noticed by me in ISPmanager 5 and 6, it appears when installing the original Roundcube on the system PHP. The last time was PHP 7.4. I removed it by entering into index.php in this section:
```
error_reporting(30711);

// include environment
require_once 'program/include/iniset.php';

// init application, start session, init output class, etc.
$RCMAIL = rcmail::get_instance(0, $GLOBALS['env']);
```
By default, the file looks like this:
```
// include environment
require_once 'program/include/iniset.php';

// init application, start session, init output class, etc.
$RCMAIL = rcmail::get_instance(0, $GLOBALS['env']);
```
Maybe my method will help someone, or maybe not, I'm not entirely sure yet.
