### ISSUE TITLE
thumbnail not workin

### ISSUE THREAD

**Issue by rahulchandyok** [roundcube/roundcubemail#5359]
Roundcube Webmail 1.1.3: I can see attachments in my emails.
Display attached images below the message

But on Roundcube Webmail 1.2.0: Can't able to see attachments in my emails.
Display attached images below the message not working. 

Any idea?

I would really appreciate if any 1 can help on this.

Regards,
Rahul

**Comment by alecpl** [comment]
Is this the same system? What PHP version? Any errors in log or in browser console? Works for me.

**Comment by rahulchandyok** [comment]
Yes on same system I have checked but with different URL but not working.
Using PHP version 5.3.3.
No error logs in browser console. 
Attached screenshot.
![1 2-roundcube](https://cloud.githubusercontent.com/assets/14847054/16867661/9feb4792-4a90-11e6-8179-a6d528441e74.png)

**Comment by alecpl** [comment]
The same config files? Try to disable all plugins.

**Comment by alecpl** [comment]
It may be related with security tokens handling. Make sure the browser does not use cached app.js (app.min.js) file.

**Comment by rahulchandyok** [comment]
same config files how It can be possible?
both versions have different files, and how about the SQL file which I 'm restoring mysql.initial.sql

It may be related with security tokens handling. Make sure the browser does not use cached app.js (app.min.js) file.
>> I did not get this?

**Comment by rahulchandyok** [comment]
I have tried with disable plugins but no luck.
If you want please share with me your email ID, I ''ll share my login credentials.

**Comment by rahulchandyok** [comment]
Server Requirements
Apache, Lighttpd, Nginx, Cherokee or Hiawatha web server
PHP Version 5.4 or greater
MySQL, PostgreSQL, SQLite, MSSQL or Oracle database
An IMAP server which supports IMAP4 rev1
An SMTP server (recommended) or PHP configured for mail delivery

NOTE: Do I need to upgrade PHP for 1.2 version?

**Comment by alecpl** [comment]
INSTALL file says 5.3.7, but I think it still should work with 5.3.3 if 1.1 worked with it. I'd expect some errors/warnings in server logs (Roundcube or Apache) if there would be PHP issues.

**Comment by rahulchandyok** [comment]
Yes, I have found some PHP warning below and reset the permission of folders and its fixed now.
Thanks lot. :+1: :dancers:  

[Fri Jul 15 17:04:23 2016] [error] [client 116.6.49.235] PHP Warning:  Error writing to log file roundcubemail/logs/sendmail; Please check permissions in roundcubemail/program/lib/Roundcube/rcube.php on line 1196, referer: https://xxxxxxxxxxxxxxxxxx/_task=mail&_action=compose&_id=5071788095788a70941e9f&_extwin=1
