### ISSUE TITLE
password change is not possible with PostgresSQL backend

### ISSUE THREAD

**Issue by Typnix** [roundcube/roundcubemail#5367]
Hi,

I'm using Roundcube with Dovecot with an PostgreSQL backend. And it is not possible to change password through the 'password' module.

The only error that I'm getting is:
function update_passwd(unknown, unknown) does not exist
LINE 1: SELECT update_passwd('SHA256-CRYPT HASH', '...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts. (SQL Query: SELECT update_passwd('SHA256-CRYPT HASH', 'username')) in /var/w
ww/roundcubemail-1.1.5/program/lib/Roundcube/rcube.php on line 1441

**Comment by alecpl** [comment]
Configuration issue. You have to configure the plugin with valid SQL query. We don't know what database structure or password scheme your system uses.
