### ISSUE TITLE
FollowSymLinks can be an invalid option

### ISSUE THREAD

**Issue by stevleibelt** [roundcube/roundcubemail#5370]
I am using roundcube on an [uberspace](https://uberspace.de/) account.
Whenever I do an update, I get a mail (and a 500) that the .htaccess contains an invalid option called "FollowSymLinks".

By replacing:
```
Options +FollowSymLinks 
```
with:
```
Options +SymLinksIfOwnerMatch
```
everything is working again.

I know that [SymLinksIfOwnerMatch](http://httpd.apache.org/docs/2.2/misc/perf-tuning.html#symlinks) can have a performance impact but it is a more secure option.

**Comment by alecpl** [comment]
Fixed in 30668879b.

**Comment by stevleibelt** [comment]
thanks :+1:
