### ISSUE TITLE
Timeout issue when uploading big files as attachment

### ISSUE THREAD

**Issue by nicolasbadia** [roundcube/roundcubemail#5373]
I have a user complaining about timeout issues when it upload attachment files. If I understand the code correctly, the timeout is defined to 180 seconds by the env variable `request_timeout`.
I think it would be great to increase it a bit (at least for files upload).

Also, it would be nice to be able to configure it from the config file, as I currently have to directly change it in the code.

**Comment by alecpl** [comment]
I'm afraid I can't reproduce the issue. I modified the code to set request_timeout=10 and added sleep(20) to attachments.inc and see no issues. Could you describe the problem in more details with steps to reproduce?

**Comment by CRtEurope** [comment]
Check your php.ini. This is not a roundcube issue.

**Comment by nicolasbadia** [comment]
Thanks for checking this.
I will ask more details to my users to see where this issue can come from.
As suggested by @CRtEurope I will also make sure the issue doesn't come from my php.ini which has a timeout set to 300...
