### ISSUE TITLE
Roundcube 2.x doesn't check for imap CA file

### ISSUE THREAD

**Issue by accuraz** [roundcube/roundcubemail#5377]
I discovered something strange.

With one of my project I use cyrus-imap as imap server. Like every imap server cyrus needs server certificate, private key and finally a CA certificate.

As a test, I tried to use an invalid CA certificate and restart the imap's daemon.

All tested mail clients like Thunderbird, KMail and Evolution could not connect to the imap server witch is fair.

The problem is Roundcube was still working, receiving and sending emails, witch is not fair !

I suppose the is the kind of miss-validation coming from Roundcube

Best...

**Comment by alecpl** [comment]
Defaults depend on PHP defaults (which differ across PHP versions). You have to set socket options (imap_conn_options). See https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L144

**Comment by accuraz** [comment]
Ok thanks @alecpl 

I'll make the modifications.
