### ISSUE TITLE
Empty sender in read notification

### ISSUE THREAD

**Issue by inpos** [roundcube/roundcubemail#5382]
Привет. 
Когда я открываю письмо с запросом подтверждения о прочтении и подтверждаю отправку уведомления, сервер сообщает ,что адрес отправителя пуст. Я специально заблокировал на сервере отправку сообщений без отправителя. В настройках профиля поле E-mail содержит мой e-mail.

Hi, when I open message with read confirmation and confirm send notification, server warn that sender address is '' (empty). I configured smtp server to not permit messages with empty sender.
In profile settings e-mail field contain my email address.

**Comment by alecpl** [comment]
```
// According to RFC2298, return receipt envelope sender address must be empty.
// If this option is true, Roundcube will use user's identity as envelope sender for MDN responses.
$config['mdn_use_from'] = false;
```

**Comment by inpos** [comment]
Thanks
