### ISSUE TITLE
roundcube & ldap configuration, "bad search filter".

### ISSUE THREAD

**Issue by ducdung0909** [roundcube/roundcubemail#5384]
Hi,
   I got the problem why using ldap with roundcube webmail. Here is my ldap configuration in 'config.inc.php'.
###############
// LDAP CONFIGURATION
$config['ldap_public'] = array(GAL);
$config['ldap_public']['GAL'] = array(
'name' => 'GAL',
'hosts' => array('localhost'),
'port' => 389,
'use_tls' => false,
'user_specific' => true,
'base_dn' => 'vd=%d,o=hosting,dc=server,dc=com',
'bind_dn' => 'cn=phamm,o=hosting,dc=server,dc=com',
'bind_pass' => 'abcd1236',
'writable' => false,
'LDAP_Object_Classes' => array("top", "inetOrgPerson"),
'required_fields' => array("cn", "sn", "mail"),
'LDAP_rdn' => 'mail',
'ldap_version' => 3,
'search_fields' => array('mail', 'cn'),
'name_field' => 'cn',
'email_field' => 'mail',
'surname_field' => 'sn',
'firstname_field' => 'gn',
'sort' => 'cn',
'scope' => 'sub',
'filter' => '(&(|(objectClass=VirtualMailAccount)objectClass=VirtualMailAlias))(accountActive=TRUE))',
'fuzzy_search' => true
);
$config['autocomplete_addressbooks'] = array('sql','GAL');
#################
But I got the waring as below why sending an email:
ldap_search failed for dn=vd=run.biz,o=hosting,dc=server,dc=com: Bad search filter.

How can I eliminate the "dn=" and correct the format for ldap_search ? Thanks.

**Comment by alecpl** [comment]
Your problem is in filter which does not look valid. Try this:
``` 
 '(&(|(objectClass=VirtualMailAccount)(objectClass=VirtualMailAlias))(accountActive=TRUE))'
```
and remove this invalid line:
```
$config['ldap_public'] = array(GAL);
```
For configuration help ask on mailing list or forum.
