### ISSUE TITLE
message-id domain part tied to username instead of current identity

### ISSUE THREAD

**Issue by karolaug** [roundcube/roundcubemail#5385]
Currently function gen_message_id() is using $domain_part = $this->user->get_username('domain'), which in setup with usernames in form user@example.com is always yielding example.com as message-id domain part. If user has multiple identities with different domains she is disclosing her primary domain name in every e-mail.

Emails sent from identity user@example.org has message-id blah@excample.com if username is user@example.org. Message-id should be taking domain part from selected identity.

**Comment by alecpl** [comment]
Solved.
