### ISSUE TITLE
plugin newmail_notifier typo in french translation

### ISSUE THREAD

**Issue by survietamine** [roundcube/roundcubemail#5386]
hello,
in localization/fr_FR.inc:
$labels['basic'] = 'Afficher les notifications du navigateur pour les nouveaux courriels';
$labels['desktop'] = 'Afficher les notifications du navigateur pour les nouveaux courriels';

should be:
$labels['basic'] = 'Afficher les notifications du navigateur pour les nouveaux courriels';
$labels['desktop'] = 'Afficher les notifications de bureau pour les nouveaux courriels';

**Comment by alecpl** [comment]
Fixed in Transifex.
