### ISSUE TITLE
plugin newmail_notifier desktop delay not used

### ISSUE THREAD

**Issue by survietamine** [roundcube/roundcubemail#5387]
roundcube 1.2.0 (loadbalancer setup nginx+memcache), running on Ubuntu 14.04 with PHP 5.5.9.

In preferences, the user changed the delay for desktop notification ; I can see the setting is saved in MySQL : 
s:24:"newmail_notifier_desktop";b:1;s:32:"newmail_notifier_desktop_timeout";i:60;

But the notification always remain the same amount of time (around 10 seconds)

I tried to enabled everything in the config.inc.php file of the plugin but still.

**Comment by alecpl** [comment]
Desktop notifications behaviour depends on the client implementation. If I'm correct some browsers ignore timeout settings, e.g. Firefox. There's no workaround.

**Comment by alecpl** [comment]
E.g. https://bugzilla.mozilla.org/show_bug.cgi?id=862395

**Comment by survietamine** [comment]
thanks for your answer. Our users are mainly in Firefox (linux and Windows), I've also tested with Chromium.

Should I check which browser is capable to "understand" that ?

**Comment by survietamine** [comment]
I don't know why, "browser notification" doesn't do anything on Firefox and Chromium, Windows or linux.
Sorry about my ignorance for that.
