### ISSUE TITLE
HTML email not rendering

### ISSUE THREAD

**Issue by linux203** [roundcube/roundcubemail#5391]
I have an issue with the attached email rendering the html in roundcube.  The content area is blank in Firefox and Chrome. (The nav pane and header render correctly.)  The web server doesn't report any 500 errors when the email is opened.  The email renders correctly in Thunderbird.

Roundcube 1.2.0 on Ubuntu 14.04 LTS, apache 2.4.7-1ubuntu4.13, php 5.5.9+dfsg-1ubuntu4.17

[ASSP-Block-Report.txt](https://github.com/roundcube/roundcubemail/files/410211/ASSP-Block-Report.txt)

**Comment by alecpl** [comment]
Works for me with 1.2.1 (php7). I see some text and two buttons. However, I think you might be using dovecot version with a bug in BINARY extension.  ```$config['imap_disabled_caps'] = array('BINARY');``` should fix it.

**Comment by linux203** [comment]
adding $config['imap_disabled_caps'] = array('BINARY'); to defaults.inc.php renders the email correctly.  Thank You!

For others' benefit, dovecot-core on the server is  1:2.2.9-1ubuntu2.1
