### ISSUE TITLE
Missing locker icon in compose bar

### ISSUE THREAD

**Issue by sixtyfive** [roundcube/roundcubemail#5394]
I've installed RoundCube 1.2.1 (`git clone`; `git checkout release-1.2` instead of a zip file/etc. if it matters) and am using it with my old 1.1 `config.inc.php`. In Chromium, I've installed and configured Mailvelope and enabled it's "API" switch for the RCM installation's domain. I can receive and decrypt emails by way of Mailvelope fine. In RCM's compose window, however, no locker icon is shown; there doesn't seem to be any UI present for encrypting emails.

**Comment by alecpl** [comment]
Do you use the default Larry or classic skin? Did you really activated the API? Activating the Mailvelope plugin on the page is not enough. You have to go to Options > List of Email Providers > <your roundcube domain> Edit and enable API there.

**Comment by sixtyfive** [comment]
I used Larry but then switched to Classic. Neither show a locker icon. I'm aware that the API needs to be enabled manually. The automatic entry in Mailvelope was for `*.subdomain.domain.tld`. I enabled the API there. Just to be sure, I also created a second entry `*.domain.tld` and enable the API there, which didn't change anything either.

**Comment by alecpl** [comment]
I'm afraid it might be mailvelope issue. Try without * in the name.

**Comment by alecpl** [comment]
What Mailvelope version?

**Comment by alecpl** [comment]
Works for me with Chromium 51 and Mailvelope 1.5.1.

**Comment by sixtyfive** [comment]
According to Chromium's Extensions page, it's Mailvelope 1.5.1. I tried to create another E-mail Provider in Mailvelope using no * in its Domain pattern at all, but that causes Mailvelope to complain ("Domain match pattern should begin with *"). What I find curious is that email _de_cryption works just fine.

**Comment by alecpl** [comment]
Decryption may work with disabled API, I suppose. Did you check browser console for errors? What if you use +Add button in Mailvelope menu instead providing domain name?

**Comment by sixtyfive** [comment]
I deleted all E-mail Providers. I then reloaded RCM and clicked Mailvelope's "Add" button, went into the Mailvelope settings and enabled API for the newly created entry, which has the pattern "*.subdomain.domain.tld". I then reloaded RCM again while looking at Chromium's console. There was one error due to the uBlock extension, which I disabled, afterwards reloading RCM once more. No errors remain in the console, but there is still no locker icon present.

**Comment by sixtyfive** [comment]
@alecpl Is there any way of troubleshooting this from RCM's side? To see what it's trying and where it's failing or something?

**Comment by alecpl** [comment]
Not really, but if you know javascript you can start investigating here https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L3456

**Comment by sixtyfive** [comment]
Thank you! I haven't gotten around to investigating yet, but in the meantime a friend sent me an encrypted email and I hit the "reply" button and, voila, there was a Mailvelope editor for the first time. That (replying) is a case I forgot to try out. Writing a fresh email that's encrypted still doesn't work but perhaps your link will help...

**Comment by sixtyfive** [comment]
@alecpl I've figured it out. According to the 1.1->1.2 upgrade instructions I had `rsync`'d, among other things, the `skins` folder which had overwritten the 1.2 `classic` and `larry` themes with the 1.1 ones which do not know how to respond to `enable_command('compose-encrypted'`. I've the correct versions of both skins now, so it works just fine. Thank you  for your patience while figuring this out!
