### ISSUE TITLE
Saving a draft with large attachment takes abnormally long or does not complete

### ISSUE THREAD

**Issue by ThPcoder** [roundcube/roundcubemail#5395]
Saving an email which has an attachment greater 5MB (to draft folder) during compose does not seem to complete after 2 mins or takes at least that long, even though the upload only took < 5 seconds (by the connection I used).

Php ini settings of upload size and post size are set to values of 20MB.

**Comment by alecpl** [comment]
What plugins are you using? If it does not complete, what errors in error log? Enable imap_debug to see what's going on. What Roundcube version? What IMAP server, what PHP version, etc.?

**Comment by alecpl** [comment]
No feedback. Works for me.
