### ISSUE TITLE
Improve cache busting strategy

### ISSUE THREAD

**Issue by fabioperrella** [roundcube/roundcubemail#5397]
Hi,

we are using roundcube as the base of our webmail app.

We noticed that the cache busting strategy (using querystring `?s=timestamp`) is not working so well

A better strategy would be changing the asset file name, for example:

program/js/jquery-1469707857.min.js

In our code, we changed the method `file_mod` in class `rcmail_output_html` to do so and also changed nginx configurations to "redirect" (or rewrite) these requests to the correct file in filesystem using a `location` rule.

If you agree, I can send a merge request with this implementation

**Comment by alecpl** [comment]
We've had such a request (for css files) in the past (#3927) and it was decided we don't want it in core. It should be possible to write such a plugin.

**Comment by fabioperrella** [comment]
So what about add a hook inside method `file_mod`? Without this, I think is not possible to do so via plugin, is it?

**Comment by alecpl** [comment]
You can use render_page or send_page hooks.

**Comment by alecpl** [comment]
Create PR with the new hook and we'll consider this.

**Comment by fabioperrella** [comment]
ok, great!
