### ISSUE TITLE
Mail sending broken in RC 1.2.1

### ISSUE THREAD

**Issue by lv01jsi** [roundcube/roundcubemail#5399]
After upgrade to RC 1.2.1

When sending mail - error loged:

PHP Fatal error:  Class 'Mail_mime' not found in /var/www/mail/htdocs/program/steps/mail/sendmail.inc on line 361

Was ok on RC 1.2.0.

**Comment by alecpl** [comment]
You somehow removed Mail_mime library. It is included in the Roundcube package (in vendor/ folder).

**Comment by lv01jsi** [comment]
Just performed the standard upgrade as usually ( > bin/installto.sh <your-existing-roundcube-directory>)
Will double check this later.
So far fall back to 1.2.0.

**Comment by lv01jsi** [comment]
Download roundcubemail-1.2.1.tar.gz does not contains vendor folder.
On current setup (1.2.0) Mail_mime is in program/lib/mail folder instead.
Was it removed by bin/installto.sh ?

**Comment by alecpl** [comment]
You get the wrong file, use "complete" version. The same was for 1.2.0. And program/lib should contain only Roundcube folder in 1.2.x.

**Comment by lv01jsi** [comment]
Using  roundcubemail-1.2.2-complete.tar.gz for upgrade from version 1.2.0 with ./bin/installto.sh.
Result = ok.

Thanks a lot for advice!
