### ISSUE TITLE
Huge logfile

### ISSUE THREAD

**Issue by bramwittendorp** [roundcube/roundcubemail#5405]
Hi!

I was looking into an issue where my RoundCube installation would give me internalserver errors so i decided to open my logfile. I used a cat on the logfile resulting in a lot of rules thrown in my command line. My logfile has a size of 642MB, is it possible to clear the roundcube logfiles monthly or weekly so this won't happen?

**Comment by alecpl** [comment]
Yes, use configure your syslog service.
