### ISSUE TITLE
Failing to save mails to 'Sent' folder (1.2.1)

### ISSUE THREAD

**Issue by DavidAnderson684** [roundcube/roundcubemail#5409]
I just upgraded Roundcube to 1.2.1 (running on PHP 5.6, with a Dovecot IMAP server on CentOS 6).

Soon afterwards, a customer reported that his outgoing mails were not being saved. I logged into his account; the problem occurs every time. The mail is sent, but the compose window shows "Sending..." for a long time, until that message disappears, with no message sent.

The user's settings are set to save outgoing mails to a "Sent" folder, which is a 450Mb mbox file.

Rolling back to the previous install (Roundcube 1.1.5) immediately resolved the issue.

**Comment by alecpl** [comment]
Do you use any external plugins? Try to disable them. Do you see any errors in log or browser console?

**Comment by thomascube** [comment]
Please read our wiki article about [how to report issues](/roundcube/roundcubemail/wiki/Howto-Report-Issues) and supply additional information and logs if possible.

**Comment by lo-windigo** [comment]
I'm receiving the same behavior on Roundcube 1.2.1, and seeing the following message in the console:

    Load denied by X-Frame-Options: https://mail.fragdev.com/?_task=mail&_unlock=loading1471902891011&_lang=en_US&_framed=1 does not permit framing.

I have the "X-Frame-Options" header set to DENY on my web server. DavidAnderson684, do you have a similar configuration?

**Comment by DavidAnderson684** [comment]
@thomascube : Thanks for the tips. This turned out to be a buggy plugin, recipient_to_contact, that needed a bit of patching for use with RC 1.2.

@lo-windigo No, I didn't have that configuration.
