### ISSUE TITLE
One-click upload button does not work in IE>9 and Edge

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5410]
It looks like IE does not support "form" attribute. https://wpdev.uservoice.com/forums/257854-microsoft-edge-developer/suggestions/7327649-add-support-for-the-form-attribute

**Comment by CRtEurope** [comment]
I have just tested it with IE 11 and used a demo page: https://www.impressivewebs.com/demo-files/html5-form-attribute/

Unfortunately the "comments" in the query string were missing. I thought indeed that IE would second that...

**Comment by alecpl** [comment]
Looks like we can do this in a simpler way. We can put the file input in a form as before (outside of the main compose form). And made buttons to invoke input.click() in onclick handler. This way we don't need "form" attribute support and click() on file input should work in most supported browsers. At least works in IE11, FF and Chrome.

**Comment by CRtEurope** [comment]
I absolutely agree to put it in a form as before... But Microsoft will add this HTML5 atrribute at some time...
It should at least support IE11, former version are obsolete anyway.

**Comment by alecpl** [comment]
Fixed.
