### ISSUE TITLE
managesieve advanced editor

### ISSUE THREAD

**Issue by 4nd3r** [roundcube/roundcubemail#5414]
one of the best features of https://github.com/JohnDoh/Roundcube-Plugin-SieveRules-Managesieve is ability to use "advanced editor" to view and edit sieve rules in "raw". since that plugin is no longer maintained, please consider adding this feature to managesieve plugin (with ability to enforce advanced editor). without that it's impossible to edit more complex sieve rules or activate special server-side filters. thank you!

**Comment by Andrei-Pozolotin** [comment]
+1

**Comment by Andrei-Pozolotin** [comment]
see #5416 #5417 #5418

**Comment by Andrei-Pozolotin** [comment]
@4nd3r 
1) I think this should really be called `basic editor` :-)
2) do you think we could pull a PR here for raw edit mode?

**Comment by Andrei-Pozolotin** [comment]
@JohnDoh can you please offer any advice on this?

**Comment by 4nd3r** [comment]
@Andrei-Pozolotin 
1) raw or basic or advanced - the name is not important here at the moment
2) this issue is blocker for me and "my users", so I probably hack something together before end of this year. not sure about PR because my PHP is really rusty since I mostly use it as tool aka get things done :-)

**Comment by Andrei-Pozolotin** [comment]
@4nd3r if you hack something before I do, please share here, and I'll do the same.

**Comment by Andrei-Pozolotin** [comment]
@alecpl please review #5473

**Comment by alecpl** [comment]
PR merged and improved. Done.

**Comment by Andrei-Pozolotin** [comment]
thank you
