### ISSUE TITLE
webmail show some email after one day

### ISSUE THREAD

**Issue by savageroundcube** [roundcube/roundcubemail#5415]
Some time the webmail show email of one day before

This is the headers of one email viewed today but received yesterday from the system

Aug 25 18:46:06 srv1 postfix/smtpd[5979]: 661AD1A0404: client=unknown[127.0.0.1]
Aug 25 18:46:06 srv1 postfix/cleanup[5975]: 661AD1A0404: message-id=<CAENA8QoYyh37h96D5rnERfedqgd7HUs6wK+PNRYNbuhpCNAs+w@mail.gmail.com>
Aug 25 18:46:06 srv1 opendkim[1442]: 661AD1A0404: no signing table match for 'xxxx@gmail.com'
Aug 25 18:46:06 srv1 opendkim[1442]: 661AD1A0404: DKIM verification successful
Aug 25 18:46:06 srv1 postfix/qmgr[1756]: 661AD1A0404: from=<xxxx@gmail.com>, size=487280, nrcpt=1 (queue active)
Aug 25 18:46:06 srv1 postfix/smtpd[5979]: disconnect from unknown[127.0.0.1]
Aug 25 18:46:06 srv1 amavis[4370]: (04370-07) FWD from <xxxx@gmail.com> -> <yyyy@tttt>,BODY=7BIT 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 661AD1A0404
Aug 25 18:46:06 srv1 amavis[4370]: (04370-07) Passed CLEAN {RelayedInbound}, [74.125.82.51]:36406 [74.125.82.51] <xxxx@gmail.com> -> <yyyy@tttt>, Message-ID: <CAENA8QoYyh37h96D5rnERfedqgd7HUs6wK+PNRYNbuhpCNAs+w@mail.gmail.com>, mail_id: ILusUIND6aKZ, Hits: -1.999, size: 486561, queued_as: 661AD1A0404, dkim_sd=20120113:gmail.com, 773 ms
Aug 25 18:46:06 srv1 postfix/smtp[5976]: 8A3C71A02E4: to=<yyyy@tttt>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.2, delays=0.42/0/0/0.77, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 661AD1A0404)
Aug 25 18:46:06 srv1 postfix/qmgr[1756]: 8A3C71A02E4: removed
Aug 25 18:46:06 srv1 postfix/pipe[5981]: 661AD1A0404: to=<yyyy@tttt>, relay=dovecot, delay=0.14, delays=0.08/0/0/0.05, dsn=2.0.0, status=sent (delivered via dovecot service)
Aug 25 18:46:06 srv1 postfix/qmgr[1756]: 661AD1A0404: removed

**Comment by CRtEurope** [comment]
But that's not a roundcube issue. There's either something wrong with your postfix configuration or amavis configuration.

**Comment by savageroundcube** [comment]
The datetime zone is correct configured with UTC also in PHP and the date is corrected viewed

The amavis have processed the email in 773ms as you can see from headers attached in my post

Can be a roundcube indexing in viewing procedures ?

Can be a roundcube reading email list error in some case?

**Comment by alecpl** [comment]
Roundcube gets the order from IMAP server. So, if there's issue it's most likely on the server. I don't really understand your issue, provide screenshot and imap_debug log from Roundcube.

**Comment by savageroundcube** [comment]
thank you for this reply

About the screenshot it is not a problem, but can you say me where I can get the imap_debug.log?

regards

**Comment by savageroundcube** [comment]
dear alecpl, I try to give you most clear informations

Our system is a CWP with CentOS release 6.8, PHP 5.4.45, Apache/2.2.27

Here the log from our maillog for this email.

The server receive the email on Aug 25, but we show it today on Aug 26

In the bottom the screenshot

regards

----------------------
Aug 25 18:46:06 srv1 postfix/smtpd[5979]: 661AD1A0404: client=unknown[127.0.0.1]
Aug 25 18:46:06 srv1 postfix/cleanup[5975]: 661AD1A0404: message-id=<CAENA8QoYyh37h96D5rnERfedqgd7HUs6wK+PNRYNbuhpCNAs+w@mail.gmail.com>
Aug 25 18:46:06 srv1 opendkim[1442]: 661AD1A0404: no signing table match for 'bet63info@gmail.com'
Aug 25 18:46:06 srv1 opendkim[1442]: 661AD1A0404: DKIM verification successful
Aug 25 18:46:06 srv1 postfix/qmgr[1756]: 661AD1A0404: from=<bet63info@gmail.com>, size=487280, nrcpt=1 (queue active)
Aug 25 18:46:06 srv1 postfix/smtpd[5979]: disconnect from unknown[127.0.0.1]
Aug 25 18:46:06 srv1 amavis[4370]: (04370-07) FWD from <bet63info@gmail.com> -> <helpdesk@vincitu.net>,BODY=7BIT 250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 661AD1A0404
Aug 25 18:46:06 srv1 amavis[4370]: (04370-07) Passed CLEAN {RelayedInbound}, [74.125.82.51]:36406 [74.125.82.51] <bet63info@gmail.com> -> <helpdesk@vincitu.net>, Message-ID: <CAENA8QoYyh37h96D5rnERfedqgd7HUs6wK+PNRYNbuhpCNAs+w@mail.gmail.com>, mail_id: ILusUIND6aKZ, Hits: -1.999, size: 486561, queued_as: 661AD1A0404, dkim_sd=20120113:gmail.com, 773 ms
Aug 25 18:46:06 srv1 postfix/smtp[5976]: 8A3C71A02E4: to=<helpdesk@vincitu.net>, relay=127.0.0.1[127.0.0.1]:10024, delay=1.2, delays=0.42/0/0/0.77, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 661AD1A0404)
Aug 25 18:46:06 srv1 postfix/qmgr[1756]: 8A3C71A02E4: removed
Aug 25 18:46:06 srv1 postfix/pipe[5981]: 661AD1A0404: to=<helpdesk@vincitu.net>, relay=dovecot, delay=0.14, delays=0.08/0/0/0.05, dsn=2.0.0, status=sent (delivered via dovecot service)
Aug 25 18:46:06 srv1 postfix/qmgr[1756]: 661AD1A0404: removed

--------------------------

![email_problem](https://cloud.githubusercontent.com/assets/21260889/18008436/62c5b2f6-6ba8-11e6-965a-2b251c1bfd90.PNG)

**Comment by alecpl** [comment]
SMTP log is not really relevant here. Anyway, the date displayed is taken from the Date: header of the email, it is probably wrong in the message. What is set in Date: header? What timezone is set in Roundcube settings and your desktop? Also, do you know you can sort messages list by "Arrival date" or "Sent date"?

**Comment by savageroundcube** [comment]
yes you are right, roundcube get the message date and it is correct

date.timezone="UTC"
date in the message is: Date: Thu, 25 Aug 2016 15:48:39 +0200

both are correct.

As you can see from th logs the server manage the message correctly on 25 August, but we see this email in the webmail only on 26 August

This problem make me crazy, and haven't other way to control it

I don't know the mechanism of roundcube code then cannot evaluate other

We have same problem on 2 different server for different domains

I hope you can help me to investigate in the right way and solve it

**Comment by CRtEurope** [comment]
What's your config for $config['timezone'] = '';
Mine is set to $config['timezone'] = 'auto'; and all is working fine

**Comment by savageroundcube** [comment]
I haven't roundcube config timezone

I have in php.ini date.timezone = "UTC"

so I try to add it and say you more on the next days.

thank you for this suggest

**Comment by CRtEurope** [comment]
In the folder /config either in the config.inc.php or in the defaults.inc.php look for the setting $config['imap_debug'] = false; and set it to true.
It is then recommended to restart your webserver and if you use a cached server like memcached restart it as well.

In the folder /logs you can see the file imap after testing.

**Comment by savageroundcube** [comment]
hi guys, the problem still persist.

In while I have analized two of email with problem and my final consideration are the following.

The email arrive on the server on August 25, 2016 and the server process it in 773ms deliveryng to the destination folder

This email have .jpeg images as attachment

The operator view the email the next day in right order date (then the day before)

regards,

**Comment by CRtEurope** [comment]
What's about the imap debug log?

**Comment by savageroundcube** [comment]
you ask me before this log but I don't found any specific log for imap

please could you say me where I can found it?

regards

**Comment by alecpl** [comment]
You provide completely irrelevant information. How to get imap debug log was already provided by @CRtEurope . This does not look like Roundcube issue. Ask on mailing list or forum.

**Comment by savageroundcube** [comment]
you are right I forgot to read this post of@CRtEurope

I try to do this change and hope obtain more informations
