### ISSUE TITLE
managesieve breaks some extensions

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5417]
before plugin edit
```
require "include";
require "fileinto";
require "envelope";
require "regex";
require "imap4flags";
require "vnd.dovecot.filter";
```

after plugin edit
```
require ["fileinto","imap4flags","include","regex"];
```

the extensions are gone:
```
require "envelope";
require "vnd.dovecot.filter";
```

**Comment by alecpl** [comment]
Yes. The plugin has some limitations and does not support all possible extensions.

**Comment by Andrei-Pozolotin** [comment]
please revert to "raw edit" functionality as default editing mode: #5414

**Comment by alecpl** [comment]
Wontfix.

**Comment by Andrei-Pozolotin** [comment]
can you please change managesieve behavior,
 so it keeps, not kills the things id does not understand?

**Comment by alecpl** [comment]
Maybe "raw script editor" would be a solution for this. I.e. when parsing a script we'd detect unsupported syntax and in such case switch to "raw script editor" mode. There's another ticket for "raw script editor" feature.
