### ISSUE TITLE
How to encrypt emails or make them not land in spam folder

### ISSUE THREAD

**Issue by Kamran14** [roundcube/roundcubemail#5419]
How would I make it so the emails being sent from roundcube are encrypted and land in the inbox, not the spam folder?

**Comment by alecpl** [comment]
I don't know what encryption has to do with the fact mail is treated as spam by some servers. Could you explain?

**Comment by CRtEurope** [comment]
Yo, bro, you have to configure your smtp and imap server correctly. This has nothing to do with roundcube.

**Comment by alecpl** [comment]
Invalid.
