### ISSUE TITLE
mail attachment view page should support image auto size / css

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5421]
1) problem:

`mail/get.inc` + `templates/messagepart.html`  inject  `iframe` attachment view page w/o any style information in it, which results in `img` attachments displayed with maximum size, with scroll, no resize, etc - not very usable.

2) workaround:
```
	function init_message_part_frame() {
		var frame = $('#messagepartframe');
		var style = "<style type='text/css'> img { max-width:100%; max-height:100%; } </style>";
		frame.load(function() {
			var head = frame.contents().find('head');
			head.append($(style));
		});
	}

	rcmail.addEventListener('init', function(param) {
		init_message_part_frame();
	});

```

3) proper solution:
expose normal skin styles during `iframe` object build

**Comment by alecpl** [comment]
These frames do not have html content at all, so I don't think your workaround would work. I agree we could do better with images. We could even consider some kind of image gallery implementation, which would nicely scale images, but also provide a way to view all images in a message.

**Comment by alecpl** [comment]
Actually your workaround works. I added "body { margin: 0; }" to get rid of a useless scrollbar (Firefox).

**Comment by Andrei-Pozolotin** [comment]
thank you
