### ISSUE TITLE
task=mail should restore mailbox context

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5425]
1) problem:
when switching form some current mail box
```
http://roundcube/?_task=mail&_mbox=path-1/to/mailbox-1
```
to other task, such as the settings:
```
http://roundcube/?_task=settings
```
and back, the mail task goes to `INBOX`
```
http://roundcube/?_task=mail&_mbox=INBOX
```

2) solution
instead, task=mail should restore mailbox context present before the switch

**Comment by alecpl** [comment]
I can't find the ticket, but it was already discussed and it was wontfix back then. There are pros and cons.

**Comment by Takika** [comment]
Original PR:
https://github.com/roundcube/roundcubemail/pull/214

**Comment by alecpl** [comment]
Thanks. So, it looks that the main reason is "most common user expectation". Until you prove we're wrong about this, this is a wontfix.

**Comment by Andrei-Pozolotin** [comment]
@alecpl you may be right, but how about exposing this as a configurable feature?
