### ISSUE TITLE
div id="topline" should not flicker on page reload

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5426]
1) problem:
`includes/header.html` + `ui.js` produces the following behavior of the ui top line element: when user activates `class="minmodetoggle"` then `div id="topline"` becomes hidden, however on any page navigation or page reload, the `div id="topline"` element will briefly be shown again, before it gets hidden, i.e. it is "flickering"

2) solution:
`ui.js` logic should be more flexible

**Comment by alecpl** [comment]
I don't see this flicker. What browser?

**Comment by alecpl** [comment]
I can imagine the flicker if the browser is slow in processing the HTML content (slow connection, slow computer). So, we have two solutions here:

1. Use cookies to store the state instead of local storage. We can read cookie from template/php and set the class of body before the page is send to the browser.
2. Move UI variable initialization from footer.html to top of header.html.

I don't really like any of these.

**Comment by alecpl** [comment]
@thomascube, ideas?

**Comment by Andrei-Pozolotin** [comment]
re: "browser is slow"
* no, fast computer, local connection, fast browser
* environment: archlinux
* browser: chromium Version 53.0.2785.116 (64-bit)

**Comment by thomascube** [comment]
Cannot reproduce this flickering on any of the browsers I have at hand. The `minimal` class is set to the body node even before DOM is ready and apparently "almost all browsers" behave as expected on this. The only improvement I could see here is to move the UI startup call from `footer.html` to `header.html`. Can those who actually witness this bug confirm this would help?

**Comment by thomascube** [comment]
Correction: after pulling the latest Chrome version, I can see the flickering myself. And to give the answer to my own question: moving the `new rcube_mail_ui();` call above the actual header nodes fixes the issue. I currently don't see a reason why not to do this. @alecpl, any objections?

**Comment by alecpl** [comment]
@thomascube you mean move it to header.html? Well, I said I don't like such solutions, but that's not so much code to execute, so I suppose we can do this, but remember to keep this object initialization operation lightwight.

**Comment by thomascube** [comment]
It's just moving the `<script>` part (6 lines of code) to `header.html` and therefore to the top of the `<body>`. The work being done here is rather lightweight I think. I'd place it at the end of `<head>`if we had a proper hook for that :-)
