### ISSUE TITLE
'Select: All' selects not yet displayed messages

### ISSUE THREAD

**Issue by 9dogs** [roundcube/roundcubemail#5427]
'Select: All' button highlight all displayed messages in folder, but in addition it implicitly "selects" messages which were delivered in that folder but not yet displayed. The following action (e.g. move or delete) will affect these non-displayed messages as well. 
This can cause unobvious loss of user data. For example, while digging through Junk folder and selecting all messages for purge, new non-spam message can be moved to Junk folder and be deleted without any notice.

"Empty" action on folder has the same behavior while in this case it's more intuitive.

**Comment by alecpl** [comment]
Well, there are a few selection options, one is "All", but another is "Current page". I think the difference is clear. You're the first person complaining.

**Comment by 9dogs** [comment]
Indeed. but current page sometimes not an option then you deal with a lot of messages. The point I was trying to make is there can be an inconsistency between highlighted messages and actual messages that will be affected by an action.
