### ISSUE TITLE
Add ":from" parameter in vacation command automatically

### ISSUE THREAD

**Issue by jurim76** [roundcube/roundcubemail#5428]
#5077 

If user is a member of mail alias, the field From in autoreplay filled with an address of mail alias, not user's email address.
For example, if user1@test.com email belongs to alias alias1@test.com and user user1 has a vacation rule, when sender send email to alias1@test.com, the sender will received the autoreply from alias1@test.com (in From field), but not from user1@test.com and it makes sender confused.
It would be useful to add an option to automatically add :from string with current user's primary email address. For example $config['managesieve_vacation_from_init'] = true;

PS
In our company, every user's email address is a member of some mail alias and senders are sending email to alias mostly, not to user's email directly.

**Comment by alecpl** [comment]
In my opinion it is better to reply with the address used in the original message, but I suppose we could add such option.

**Comment by alecpl** [comment]
Done.
