### ISSUE TITLE
PDF gets corrupt when sent via Roundcube

### ISSUE THREAD

**Issue by Infern1** [roundcube/roundcubemail#5429]
When sending a mail with a pdf (small ones seem to work) the PDF are getting corrupt

Roundcube 1.2.1
Nginx 1.10.1
PHP 7.0.10

I also run horde (IMP webmail) on the same server and when the same PDF is sent it is working

The message send via Roundcube: https://gist.github.com/Infern1/0658e8e98e0e00793437728ce2373ca5
Same message send via Horde: https://gist.github.com/Infern1/8135276b4333ff1e2dd555326f34fe38

Just the orignal PDF here: https://www.ets.org/Media/Tests/GRE/pdf/gre_research_validity_data.pdf

**Comment by alecpl** [comment]
Do you use mail() method for sending (smtp_server setting unset)? Please, disable all plugins and configure Roundcube to use smtp connection. Also, is it invalid also i Sent folder?

**Comment by Infern1** [comment]
I use the smtp method already

Mail is not corrupt in the sent folder
No plugins enabled (have to check, but didn't enable one as far as I know)

**Comment by alecpl** [comment]
> I use the smtp method already

Hmm... `X-PHP-Originating-Script: 501:rcube.php` suggests something different.

> Mail is not corrupt in the sent folder

Enable smtp_debug and check the log to make sure the attachment body is not or isn't malformed when talking to SMTP server. Increase this value (https://github.com/roundcube/roundcubemail/blob/release-1.2/program/lib/Roundcube/rcube_smtp.php#L37) to get not truncated content.

**Comment by Infern1** [comment]
@alecpl was right smtp sending was not activated. When enabling smtp sending problem was gone.

Thanks for the help!
