### ISSUE TITLE
mimetypes.php not updated when upgrading

### ISSUE THREAD

**Issue by romanb52** [roundcube/roundcubemail#5430]
We found problem that we were unable to send pdfs via roundcube.
I noticed that it is because pdf is not part of config/mimetypes.php

We had 1.0rc version. I downloaded 1.2.1 and run installto.sh to update it. But mimetypes.php remained old one.

Should not be updated as well??

**Comment by alecpl** [comment]
Well, it could, but this is a configuration file, so if we update it automatically, we might loose use modifications to it.

I don't see how it could cause inability to send pdf attachments. There was some error in log? Did you disable all old plugins on upgrade?

**Comment by CRtEurope** [comment]
When I would not remind of all my modifications of this file and it'll be upgraded, nothing would work anymore...

**Comment by romanb52** [comment]
We are in 2016, use class inheritance. Base class can have hardcoded list of mime types and class extended by user can add or remove any other. Class derived by user can be created automatically if not exists and will never be changed by upgrade...

**Comment by alecpl** [comment]
But could you explain what was the problem with sending pdf attachments? Did you get any errors in log?

P.s. mimetypes list can be even empty if your server is properly configured to detect file types.
