### ISSUE TITLE
We open a link to our RoundCube Site from our product's site Uncaught SecurityError: Blocked a frame with origin "https://vcomm.xxxxxxs.com" from accessing a frame with origin "https://intuition.product.com". Protocols, domains, and ports must match.

### ISSUE THREAD

**Issue by ChrisLongo61** [roundcube/roundcubemail#5433]
We open a link to our RoundCube Site from our product's site
<a href="https://vmessaging.vertexsystems.com" target="_blank" class="label sm-no-user-select" title="VComm">

When we press the compose button our RoundCude site generates the following message.

VM855:1 Uncaught SecurityError: Blocked a frame with origin "https://vcomm.xxxxxxs.com" from accessing a frame with origin "https://intuition.product.com". Protocols, domains, and ports must match.
f                  @VM855:1
(anonymous function)   @?_task=mail&_action=compose&_id=1523118…:395
fire                 @jquery.min.js?s=1473687074:3094
fireWith              @jquery.min.js?s=1473687074:3206
ready                 @jquery.min.js?s=1473687074:3412
completed             @jquery.min.js?s=1473687074:3428

Any direction on how to get around or fix this issue would be appreciated.

Chris
Modify message

**Comment by CRtEurope** [comment]
https://www.w3.org/TR/2008/WD-access-control-20080912/

**Comment by alecpl** [comment]
Not Roundcube issue.
