### ISSUE TITLE
public key match is case sensitive: Encryption failed. Public key not found for ...

### ISSUE THREAD

**Issue by chaos-prevails** [roundcube/roundcubemail#5434]
although the local-part is defined as case sensitive (https://tools.ietf.org/html/rfc5321), AFAIK in reality email addresses treated case insensitive. Also enigmail in Thunderbird ignores the case, thus finds the public key.

Some users in my organization tend to capitalize the first letter of their given name in their email address when they create their keypair. However, other people write to those users without capitalization and then find themselves having troubles writing encrypted emails.

**Comment by alecpl** [comment]
Comparison in enigma_key::find_subkey() need to be modified, but maybe in some other places.

**Comment by alecpl** [comment]
I didn't find any other places where it could be a problem. Fixed.
