### ISSUE TITLE
Roundcubemail filter (managesieve)

### ISSUE THREAD

**Issue by Blisk** [roundcube/roundcubemail#5435]
I have installed roudcubemail 1.2 and when I have created a filter to transfer all mails from server@mydomain.com to folder /server under /inbox, I still get those mail in inbox instead to folder /server
and have no errors about managesieve

**Comment by alecpl** [comment]
This is not Roundcube issue. Look into your IMAP server configuration/logs.

**Comment by Blisk** [comment]
there is no errors at all

**Comment by rmcaninch** [comment]
After creating the filter, you did enable it?

As he said, look at your IMAP server configuration. See how to enable its debugging logs to track what happens to the email message. You should be able to see if sieve rules are being evaluated.

**Comment by Blisk** [comment]
Ok I have enabled debug in dovecot and this is only error which I get and don't know it is related to this problem.

Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl: initializing backend with data: vfile
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl: acl username = dennis@mydomain.com
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl: owner = 0
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: Global ACL directory: (none)
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: file /var/vmail/vmail/mydomain.com/d/a/m/dennis-2016.09.12.15.49.37//Maildir/.Drafts/dovecot-acl not found
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: file /var/vmail/vmail/mydomain.com/d/a/m/dennis-2016.09.12.15.49.37//Maildir/.Sent/dovecot-acl not found
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: file /var/vmail/vmail/mydomain.com/d/a/m/dennis-2016.09.12.15.49.37//Maildir/.Junk/dovecot-acl not found
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: file /var/vmail/vmail/mydomain.com/d/a/m/dennis-2016.09.12.15.49.37//Maildir/.Trash/dovecot-acl not found
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: file /var/vmail/vmail/mydomain.com/d/a/m/dennis-2016.09.12.15.49.37//Maildir/.INBOX.cron/dovecot-acl not found
Sep 18 15:02:47 imap(dennis@mydomain.com): Debug: acl vfile: file /var/vmail/vmail/mydomain.com/d/a/m/dennis-2016.09.12.15.49.37//Maildir/dovecot-acl not found
