### ISSUE TITLE
Plugin "Enigma": Cannot import public key

### ISSUE THREAD

**Issue by 74cmonty** [roundcube/roundcubemail#5437]
Hi,

I followed the instructions for setting up Enigma plugin, however I cannot import a public key.
Creating a new key works w/o any issue.

How can I import a public key?

THX

**Comment by alecpl** [comment]
Enable enigma_debug and provide the log.

**Comment by 74cmonty** [comment]
OK.
I have enabled enigma_debug and executed these steps:
1. login to roundcube
2. settings
3. PGP keys
4. create new PGP key pair

I cannot import keys here.

Debug log is attached
[enigma.txt](https://github.com/roundcube/roundcubemail/files/478602/enigma.txt)

**Comment by alecpl** [comment]
I don't see import operation in the log. Did you use key import form? I don't understand your steps to reproduce. What has key generation to do with key import?

**Comment by 74cmonty** [comment]
I agree... key generation has nothing to do with key import.
However, I can see no function that allows me to import a key.

Can you advise how key import should be done?

**Comment by alecpl** [comment]
Don't you see Import and Export buttons in the toolbar above the keys list?

**Comment by 74cmonty** [comment]
got it... solved!
