### ISSUE TITLE
Real PHP version required for Roundcube >= 1.2.0

### ISSUE THREAD

**Issue by nuxwin** [roundcube/roundcubemail#5438]
Hello,

In https://github.com/roundcube/roundcubemail/wiki/Install-Requirements, it is stated that PHP >= 5.4.45 is required. However, in the composer file, we can see: That PHP >= 5.3.7 is required.

https://github.com/roundcube/roundcubemail/blob/1.2.1/composer.json-dist#L24

We provide Roundcube for our control panel and we have not seen any issue by running Roundcube with PHP 5.3.10  which is the version that is available in the Ubuntu 12.04 repository.

Could you clarify the situation a bit?

Thank you.

**Comment by alecpl** [comment]
Roundcube 1.2 works with PHP >= 5.3.7. Roundcube 1.3 (current git-master) requires PHP 5.4.

**Comment by nuxwin** [comment]
@alecpl 

So please, fix https://github.com/roundcube/roundcubemail/wiki/Install-Requirements because this is confusing. See https://github.com/i-MSCP/roundcube/pull/4#issuecomment-248142560

Thank you.
