### ISSUE TITLE
Primary Keys missing for some tables

### ISSUE THREAD

**Issue by Supertimothy** [roundcube/roundcubemail#5439]
When using roundcube with a galera cluster, all tables need to have a primary key, see for example here: https://mariadb.com/kb/en/mariadb/mariadb-galera-cluster-known-limitations/

The following tables have no primary key:
cache
cache_shared
dictionary

If there is no possibiltiy to use one of the existing fields as primary key, an AUTO_INCREMENT column could be added easily.

**Comment by alecpl** [comment]
No problem for 'dictionary', we could probably just replace the unique key. For 'cache' table maybe a primary key on 'user_id', 'cache_key' and 'created' would work (and similar on 'cache_shared'), but it will not be perfect (duplicates still possible).

**Comment by thomascube** [comment]
For `cache` table, I'd assume that there can/should only be one single entry for  `user_id + cache_key`, no? Therefore this perfectly qualifies for a primary key. In which cases can we expect multiple entries for this pair which is a desired result in Roundcube?

**Comment by alecpl** [comment]
@thomascube No, there can be more than one `user_id + cache_key` entry. To workaround "duplicate key error" on insert I decided to allow many entries for that key and on select we use `sort by date with limit 1`. So, we could create such primary key if we workaround "duplicate key errors" on insert in another way, e.g. by ignoring them (`ignore_key_errors` option of `rcube_db`). The key should be `user_id + cache_key + created`.

**Comment by thomascube** [comment]
Suppressing such errors likely isn't the way to go. It means that the cache entry is not updated and the old value (with the same key) remains active. Using `REPLACE INTO` could be a way around it but only for MySQL. Preferably we fix it with a recovery routine which re-tries with an UPDATE in case the initial INSERT failed with a duplicate key error.

**Comment by alecpl** [comment]
Done.
