### ISSUE TITLE
Atachment bug virus attachment

### ISSUE THREAD

**Issue by founded** [roundcube/roundcubemail#5441]
MIME-Version: 1.0
Content-Type: multipart/related;

`--boundary_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
Content-Type: application/zip; name="1aaaa1aaa.zip"
Content-Transfer-Encoding: base64`

the product wil not view. The new spam(virus) atachments wil not visable as atachment en make it dangerous. So people thinks that is hasnt a attachment so it cant have a virus and open that mail.

please is it posible to have a (notdecripted)sumcheck on sended attachment (64bit encoded)  so it is posible to remove  fast mails with virus.(if we can add that sumcheck(intersection) as spam/virus)

**Comment by alecpl** [comment]
I don't know what are you talking about. Virus checking is not MUA's responsibility, but server's.

**Comment by founded** [comment]
Mmm , if there is an attachment on the mail source ,and you cant see it as attachment so it moved to het visual message and simple users wil not see it and has the problems.
If they do something ok, if they dont do something ok . So its not my problem and only for simple users.
