### ISSUE TITLE
enigma plugin not compatible with roundcube mobile plugin

### ISSUE THREAD

**Issue by chaos-prevails** [roundcube/roundcubemail#5444]
When activating the mobile view of the roundcube mobile plugin (https://github.com/messagerie-melanie2/Roundcube-Plugin-Mobile), I cannot encrypt messages (no icon to click). Decrypting only works if I've previously entered my secret key passphrase and then switched to mobile view.

**Comment by alecpl** [comment]
Well, if something works with larry, but not with another skin it's the skin issue.
