### ISSUE TITLE
calendar plugin does not work with mobile view

### ISSUE THREAD

**Issue by chaos-prevails** [roundcube/roundcubemail#5445]
Dear,

we use the caldav compatible calendar from http://git.faster-it.de/roundcube_calendar/about/ (forked from https://gitlab.awesome-it.de/kolab/roundcube-plugins/tree/feature_caldav). The reason is that we also use the carddav plugin from https://github.com/blind-coder/rcmcarddav/tree/master. 

In the mobile view in the right-hand menu, there is no link to the calendar. If I open the link to the calendar directly (_task=calendar), I get a file not found error

kind regards,

**Comment by alecpl** [comment]
This is not Roundcube core issue. We do not support mobile skin, nor calendar plugins.
