### ISSUE TITLE
Release .tar.gz misses public_html directory

### ISSUE THREAD

**Issue by tyranron** [roundcube/roundcubemail#5446]
There is a [directory `public_html`](https://github.com/roundcube/roundcubemail/tree/master/public_html) in repo [added 3 years ago](https://github.com/roundcube/roundcubemail/commit/38c9df8e97311bdd960e555ee7dbc4beed0d2e96) with symlinks. But release archives (at least `1.2.1` and `1.2.0`) do not contain one. Why?

**Comment by thomascube** [comment]
Good point! This was added as an experimental thing and for some reason we never confirmed that setups using the public_html as document root do work as expected.

Anyway, let's keep it in the release package and wait for replies.

**Comment by thomascube** [comment]
Build script updated accordingly: https://gist.github.com/thomascube/2725894

**Comment by tyranron** [comment]
@thomascube, thank you for explanation.

I can confirm that using `public_html/` works as expected. I'm successfully using it in php-fpm Docker container which is accessible by Nginx.
