### ISSUE TITLE
Allowing username with spaces after dot symbol '.'

### ISSUE THREAD

**Issue by ddsmes** [roundcube/roundcubemail#5451]
User can put the space symbol after a dot when logging in.
RoundCube creates new user_id and new identity_id.
For example user has username "gorlova.i.n"
User types "gorlova. i. n" to username input field.
RoundCube succesfully authenticates to IMAP server as "gorlova.i.n" (without spaces) and creates new user_id and identity_id (with spaces !!!!) in the mysql database.

RoundCube must
*) do not allow spaces in the username
or
*) completely remove ALL (!!!!!) spaces from user entered username

**Comment by alecpl** [comment]
Spaces might be valid in some environments. So, I suppose this is a wontfix. You can already block access for usernames with spaces, e.g.
```
// Logon username filter. Regular expression for use with preg_match().
// Example: '/^[a-z0-9_@.-]+$/'
$config['login_username_filter'] = '/^[^\s]+$/';
```
