### ISSUE TITLE
max_packet prevents >2MB cache data

### ISSUE THREAD

**Issue by marknl** [roundcube/roundcubemail#5452]
In [rcube_cache.php](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_cache.php#L637) there is a function called max_packet_size. With a variable max_packet set to 2MB as default/max.

This function prevents saving attachments bigger than 2MB into the caching mechanism when using the database_attachments plugin. This plugin uses the rcube_cache, which (in my setup) is set to use memcache with max item size of 5MB.

Apparently the holy grail to define what $this->max_packet should be for memcache, is dividing the remaining amount of free memory by 5 and see if it's smaller than 2MB? Looks arbitrary to me. The same applies on the 'apc' mechanism. The 'db' mechanism is setup correctly.

**Comment by alecpl** [comment]
Indeed the way how min() is used here is wrong.

**Comment by alecpl** [comment]
Also, we should rather use item_size_max from `stats settings`, but I'm not sure this is supported by php. There's no such thing for apc. I suppose we should also add possibility to configure these values.

**Comment by thomascube** [comment]
I don't think the min() here is wrong but intentionally. What IMO needs to be fixed is the database_attachments plugin here to actually use the database and not the cache.

**Comment by alecpl** [comment]
database_attachments plugin uses configured cache type and can be used with db, memcache and apc. I don't see a bug here. Redundant_attachments plugin requires both db and memcache, if configured so. So, we need/expect possibility to use >2MB items in memcache.

**Comment by alecpl** [comment]
So, I propose to get rid of the stats calculation and use configured value (with 2MB as a default). Current code doesn't really prevent the user from exceeding the cache size and as we can't get the real max object size, does not make sense.

**Comment by marknl** [comment]
Maybe it's an option (since we're not able to get the size from apc or memcache) to create a configuration setting in which the user can set the size of $this->max_packet so you shouldn't have to dive into the code to change it?

**Comment by alecpl** [comment]
That's what I'm talking about.

**Comment by alecpl** [comment]
Fixed.
