### ISSUE TITLE
Attachment not shown

### ISSUE THREAD

**Issue by thomasysliu** [roundcube/roundcubemail#5453]
The attachment cannot have download link for the email below
[attachment.eml.zip](https://github.com/roundcube/roundcubemail/files/504482/attachment.eml.zip)

**Comment by alecpl** [comment]
What version? I cannot reproduce with 1.2.2. There was the same issue fixed in 1.3 too (#5357).

**Comment by alecpl** [comment]
????

**Comment by alecpl** [comment]
No feedback.
