### ISSUE TITLE
'Exception' with message 'DateTime::__construct(): on 1.2.2

### ISSUE THREAD

**Issue by borisstoqnov** [roundcube/roundcubemail#5455]
Upgraded from 1.0.5 to 1.2.2, when I input the wrong password for an existing user I get HTTP 500

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone.' in program/lib/Roundcube/rcube_user.php:491

This is the code:

`function failed_login()
    {
        if ($this->ID && ($rate = (int) $this->rc->config->get('login_rate_limit', 3))) {
            if (empty($this->data['failed_login'])) {
                $failed_login = new DateTime('now');
                $counter      = 1;
            }
`
PHP version >5.4

**Comment by alecpl** [comment]
What PHP version? It should not throw an exception. Anyway, the error message is clear, no? Set date.timezone in PHP config.

**Comment by borisstoqnov** [comment]
That was a pretty fast response :)

Yes, crystal clear, think it should be added as a requirement in upgrade or install .txts to save people some time as I was looking for the issue elsewhere, but that is just an opinion.

**Comment by alecpl** [comment]
First time I see it throws exception. What PHP version exactly? I'll create a ticket in PHP bugtracker.

**Comment by alecpl** [comment]
Nevermind, I reproduced on PHP 7.0.11.

**Comment by borisstoqnov** [comment]
Tested with 5.4.16, added to initial comment too.

**Comment by alecpl** [comment]
https://bugs.php.net/bug.php?id=73239, let's see what PHP devs think about this.

**Comment by alecpl** [comment]
Anyway, as the error message is clear and we already have date.timezone value check in installer, I think there's not much left on our side. I don't think we should check this also in "production code path".
