### ISSUE TITLE
responses: add 'format' param to rcube_text_editor.replace()

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5456]
while developing
https://github.com/random-cuber/responses

we were forced to replace `rcube_text_editor.replace()`
https://github.com/roundcube/roundcubemail/blob/master/program/js/editor.js#L410

since it ignores `format` parameter, the change is as follows:
https://github.com/random-cuber/responses/blob/master/responses.js#L110
```
	// function replacement: see editor.js/rcube_text_editor.replace()
	this.rcube_text_editor_replace = function rcube_text_editor_replace(text,
			format) {
		var ed = this.editor;
		// insert into tinymce editor
		if (ed) {
			ed.getWin().focus(); // correct focus in IE & Chrome
			format = format ? format : 'text';
			var content = '[invalid]';
			if (format == 'html') {
				content = text;
			}
			if (format == 'text') {
				content = rcmail.quote_html(text).replace(/\r?\n/g, '<br/>');
			}
			ed.selection.setContent(content, {
				format : format
			});
		}
		// replace selection in compose textarea
		else if (ed = rcube_find_object(this.id)) {
			var selection = $(ed).is(':focus') ? rcmail.get_input_selection(ed)
					: {
						start : 0,
						end : 0
					}, inp_value = ed.value;
			pre = inp_value.substring(0, selection.start), end = inp_value
					.substring(selection.end, inp_value.length);

			// insert response text
			ed.value = pre + text + end;

			// set caret after inserted text
			rcmail.set_caret_pos(ed, selection.start + text.length);
			ed.focus();
		}
	};
```

please apply similar change to `editor.js`

**Comment by alecpl** [comment]
Unfortunately this does not look complete. when html editor is disabled and you use replace with html format it won't work properly. As we can't properly convert html to plain text here (we use html2text for this) maybe we should do here what we do with identities, i.e. we expect the input to already contain html and text version. In other words, you do the conversion on your own and call replace() with an object containing 'html' and 'text' properties. That's what I'd probably do if I was implementing HTML support for responses.

**Comment by alecpl** [comment]
Done.

**Comment by Andrei-Pozolotin** [comment]
thank you. what is 1.3-beta release time frame?

**Comment by alecpl** [comment]
There's no deadline set, but I'd like to release beta in this year.
