### ISSUE TITLE
responses: externalize rcube_webmail.insert_response()

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [roundcube/roundcubemail#5457]
while developing
https://github.com/random-cuber/responses

we were forced to replace `rcube_webmail.insert_response()` as follows
https://github.com/random-cuber/responses/blob/master/responses.js#L147

since there is no provision for `php hook` :
https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail.php#L376

nor is there `js event listener / hook` provision :
https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L4354

please expose a legitimate way to inject responses template processor from a plugin

**Comment by alecpl** [comment]
I think it should be solved with a hook in get_compose_responses(). However, maybe we should implement html responses first, then it would look completely different, because e.g. we'd not get all responses at once, but one by one.

**Comment by alecpl** [comment]
Done.

**Comment by Andrei-Pozolotin** [comment]
thank you
