### ISSUE TITLE
enigma: search with keyword containing accents (above ASCII-7?) delivers empty search result

### ISSUE THREAD

**Issue by chaos-prevails** [roundcube/roundcubemail#5459]
Function: Settings -> PGP Keys -> search box in the top right corner.

Symptom:
A search keyword containing accents does not deliver any search result.

Desired outcome:
Show users with accents in their name when search keyword contains the accent.

We have a user called Hélène, so I have to search with "h" only, to find her. If I search for "hé", she does not show up in the search result. The same happens with a user called Niccolò. If I search for "niccol", he shows up, if I search for "niccolò", he doesn't show up any more.

kind regards,

**Comment by alecpl** [comment]
Could you confirm if removing urlencode() call here fixes the issue https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/enigma/enigma.js#L269 ? I see this may not be all as in one key generated by openpgp.js characters are encoded.

**Comment by alecpl** [comment]
Now I found that adding --utf8-strings argument to gpg --list-public-keys/--list-secret-keys calls fixes the issue (together with the above proposed change). Here we assume all user IDs use utf-8, if they use other encoding we can do nothing about it. So, we need a fix for Crypt_GPG.

**Comment by alecpl** [comment]
https://pear.php.net/bugs/bug.php?id=21121

**Comment by alecpl** [comment]
Crypt_GPG 1.4.3 has been release with the fix. Closing.
