### ISSUE TITLE
Do not show inline images of unsupported mimetype

### ISSUE THREAD

**Issue by waiwaizu** [roundcube/roundcubemail#5463]
When I use Roundcube to send dwg file to other, which is become a image to preview, then it fail to load it, but it can download using laptop/pc. Please help.

<img width="413" alt="screen shot 2016-10-08 at 11 23 36 pm" src="https://cloud.githubusercontent.com/assets/20066492/19214086/6e1d578a-8dae-11e6-96bb-19c33f1906f1.png">

**Comment by alecpl** [comment]
DWG is an image format not supported by any web browser nor ImageMagick. So, it just can't be displayed. I suppose we should probably not even try to display a thumbnail like we did here. We just don't check if the image type is supported here, we try to display thumbnails for all attachments with content type image/*.

**Comment by waiwaizu** [comment]
Thanks
Have any methods to display dwg attachment is  look better? Not like this, because when using mobile phone to read the email. The attachment will become a blank box.

**Comment by alecpl** [comment]
As I said it is not possible. All we could do is to not display it at all. I was thinking about a solution that ignores all images of types that aren't natively supported by web browsers and that couldn't be converted by Roundcube, but what if a browser have some extension installed? Maybe we could read supported image mimetypes in javascript and use this list.

**Comment by alecpl** [comment]
So, my final idea is to hide the inline attachment block until onload on the img tag fires. This way images that cannot be displayed will not be displayed to the user.
