### ISSUE TITLE
Content overlaps

### ISSUE THREAD

**Issue by lexon0011** [roundcube/roundcubemail#5467]
We have problems with our Roundcube webmail: On some mails the content overlaps, whereby the content is no longer displayed legibly.

![mailprobleme](https://cloud.githubusercontent.com/assets/16290662/19260867/74f67718-8f8d-11e6-8c05-8d1af7b7a7eb.jpg)

Is the problem already known? Is there a fix available?

Thanks!

**Comment by alecpl** [comment]
What version? Could you provide the source of this message?

**Comment by lexon0011** [comment]
Roundcube Webmail 0.9.5

What does you mean with the source of the message? Should I redirect the message to your mail address?

**Comment by alecpl** [comment]
Forward as attachment to alec at alec.pl, please.
ps. we do not support 0.9.

**Comment by alecpl** [comment]
This issue has been fixed in Roundcube 1.0.2. https://github.com/roundcube/roundcubemail/commit/49e260ba584d3545e75a374178f47a103da50893
