### ISSUE TITLE
Less terse error messages

### ISSUE THREAD

**Issue by petamem** [roundcube/roundcubemail#5469]
This is a general comment about the error messages used in roundcube using just one example:

"File upload failed"

This is not an error message, it's captain obvious stating the obvious. What/Why it went wrong - no one knows, except the source code I guess. The file in question has the right size (not exceeding upload limit), it's readable etc.

So all the user is left with is the message above and many question marks in his head.

Please, try to make more sensible/useful messages in the versions to come.

checking the logs reveals:
*38126 client intended to send too large body: 1650857 bytes,

which is interesting, because the limit is set to 2MB and that's also what roundcube itself claims as max limit.

**Comment by alecpl** [comment]
Looks like you have a limit set on a higher (than PHP) level, so Roundcube can't get it's value and present more verbose message to the user. It might be on http server.

**Comment by petamem** [comment]
You are right.

Nginx client_max_body_size was not set, so I looked up the default value, which is 1M.
Setting this explicitely to 2M resolves that particular issue.

However, the general requirement to make error messages more sensible/useful remains, which is why I think the close is premature.

File upload failed - blocked by HTTP server.

Should be detectable/doable by roundcube (as it IMHO sees php.ini cannot be the reason).

**Comment by alecpl** [comment]
If we can't detect it for sure it would be a guess, so might be misleading. Also, "blocked by HTTP server" is not really much more useful for the user.

**Comment by petamem** [comment]
Well - *your* guess helped.

Maybe put a "maybe" before the "Blocked by..." message.

While I agree that a user may not gain anything from that, guess who will get that message from the user next. Maybe the admin?

Don't worry: this is my last take on it. If you consider the roundcube error messages to be perfect, so be it.
