### ISSUE TITLE
IMAP password exposed via error dialog box

### ISSUE THREAD

**Issue by gahr** [roundcube/roundcubemail#5472]
Error conditions at IMAP server side (such as failure to response because of extremely high machine load) could expose a user's password when the LOGIN command fails and the `"Unable to send command: $request")` string is displayed.

https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_imap_generic.php#L2031

**Comment by alecpl** [comment]
Yup, it should be anonymized as we do for debug logging. Or we should use only the command name (e.g. UID FETCH, SEARCH, etc.) instead of the full command with arguments.

**Comment by alecpl** [comment]
Fixed.
