### ISSUE TITLE
Recipient header (To:) is not properly encoded

### ISSUE THREAD

**Issue by MirLach** [roundcube/roundcubemail#5475]
If recipient header contains some diacritics UTF-8 characters they are not sanitized - not converted to quoted string: =?UTF-8?Q?=
From and Subject is properly sanitized. I think it is related to some $mailto / $headers['To'] changes in recent version.

It results in this error and message is undeliverable:

```
Diagnostic-Code: X-Postfix; SMTPUTF8 is required, but was not offered by host
    mx1.seznam.cz[77.75.76.42]
```

Works in Roundcube 1.2.0. does not work in 1.2.2.

**Comment by alecpl** [comment]
Works for me. Disable all plugins and try again. You can also enable smtp_debug to see what exactly is being sent to SMTP server.

**Comment by MirLach** [comment]
I forget to note - we are using PHP mail() function, not SMTP connect.
Another instance with older 1.2.0 is using SMTP TLS connection.

On October 14, 2016 6:28:50 PM CEST, Aleksander Machniak <notifications@github.com> wrote:
>Works for me. Disable all plugins and try again. You can also enable
>smtp_debug to see what exactly is being sent to SMTP server.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/roundcube/roundcubemail/issues/5475#issuecomment-253851647

-- 
Odeslano z maleho zarizeni. Prosim omluvte mou strucnost.

**Comment by alecpl** [comment]
Ok, confirmed with mail(). I'll fix this for 1.2, but keep in mind mail() method will not be supported in 1.3.

**Comment by alecpl** [comment]
Fixed.

**Comment by MirLach** [comment]
Thank you!
