### ISSUE TITLE
Attaching path with period fails and crashes Chromium

### ISSUE THREAD

**Issue by resolutecake** [roundcube/roundcubemail#5477]
SYMPTOM
When composing email click Attach a file
Navigate to a file with a directory name containing period, click Open
My path began with “161015 Node.js more words here”

BUG1
The Attach a file popup displays two files

click Upload

BUG2
Chromium tab crashes

GETAROUND
Move the file to a directory path that does not contain a period
Attaching now works

dpkg --status chromium-browser | egrep "^(V|Pa)"
Package: chromium-browser
Version: 53.0.2785.143-0ubuntu0.16.04.1.1254

dpkg --status roundcube-core | egrep "^(V|Pa)"
Package: roundcube-core
Version: 1.2~beta+dfsg.1-0ubuntu1

**Comment by alecpl** [comment]
Could you try with something that is not beta? ps. We don't use Node.js, so could you try with disabled all addons in the browser and all plugins in Roundcube?

**Comment by alecpl** [comment]
Works for me.

**Comment by resolutecake** [comment]
This works in 1.2.1
