### ISSUE TITLE
Existing attachment not Indicated on Forward

### ISSUE THREAD

**Issue by resolutecake** [roundcube/roundcubemail#5478]
Navigate to a previously sent email in the Sent email directory
click Forward

BUG
The right pane of the email does not indicate that there is an attachment

EXPECTED
A file attachment to be present in the right pane

GET_AROUND
click pop-out
The attachment is properly indicated

MY PROBLEM
I attached a second file, or as I though only attachment, and clicked Send
The email was sent with two attachments

**Comment by alecpl** [comment]
Could you try with stable version?

**Comment by alecpl** [comment]
Works for me.

**Comment by resolutecake** [comment]
Yes, this works in version 1.2.1

Ubuntu 16.04 LTS is still on the broken version
