### ISSUE TITLE
Plugin hook for max_recipients violation

### ISSUE THREAD

**Issue by hansmaulwurf23** [roundcube/roundcubemail#5481]
The benefit is the ability to handle violations in a plugin. One could count the number of violations and disable login (and/or kick the session) for that user upon exceeding a threshold. Since compromised accounts are often used as spam bots with a large number of recipients we want to count the number of violations of the max_recipients restriction in a plugin. It is also possible to allow certain users to be part of some kind of whitelist regarding the max_recipients restriction (for instance if the hook is expecting a boolean return value).

I would implement this in a PR if wanted and considered useful. The only other way of achieving the described behavior I can think of is using the ```message_before_send``` hook and handling max_recipients completely there.

**Comment by alecpl** [comment]
`message_before_send` or `message_ready`. I don't think we need another specific to only max_recipients handling.

**Comment by hansmaulwurf23** [comment]
Unfortunately the argument ```mailto``` in ```message_before_send``` (https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#message_before_send) does not pass an array and holds only To-recipients (not CC nor BCC). Therefore the whole parsing and splitting of To, CC and BCC must be done again. Relying on ```global $RECIPIENT_COUNT;``` (coming from sendmail.inc) is probably not the best idea as well ;-)

**Comment by alecpl** [comment]
The parsing should not be a big problem. use `message_ready` hook. Get headers from the message and parse them with rcube_mime::parse_address_list().

**Comment by hansmaulwurf23** [comment]
Using ```message_ready``` and ```rcube::decode_address_list``` works like a charm. Thanks for the help!

**Comment by salmanmohammad** [comment]
How can I access mailto value, my code is 
`$to= $comp['mailto'];`
but I am getting empty value.
please help me.
