### ISSUE TITLE
Enigma signature verification failure when message encrypted

### ISSUE THREAD

**Issue by lbdroid** [roundcube/roundcubemail#5482]
I'm testing using THREE email clients; roundcubemail+enigma, thunderbird+enigmail, and k9mail+openkeychain (https://github.com/k9mail/k-9 + https://github.com/open-keychain/open-keychain)

The situation is as follows;

When generating a message that is both encrypted AND signed, from EITHER thunderbird or k9mail, roundcubemail is unable to verify the signature.

In addition, when generating the same kind of message from roundcubemail, only thunderbird is able to verify the signature -- k9mail is not.

Messages between thunderbird and k9mail work flawlessly, all email clients are able to correctly read messages that they generated themselves.

Since every failure involves roundcubemail, I suspect that the problem must lie there. That thunderbird is able to correctly verify the signature from roundcube could imply an additional flaw in k9mail, or it could be that thunderbird is more resilient to malformed messages.

I am using a single public/private key set, and addressing the test messages to self.

I have reported an issue on k9mail as well, but I do not believe that the problem lies there.
https://github.com/k9mail/k-9/issues/1731

**Comment by alecpl** [comment]
You're on 1.2, right? It has been fixed in git-master and will not be backported to 1.2. Could you try git-master?

**Comment by lbdroid** [comment]
Yes, 1.2.2.
I tested master and yes, it is working correctly.
Thank you.
