### ISSUE TITLE
Attachments upload - files count limit check

### ISSUE THREAD

**Issue by skiner68** [roundcube/roundcubemail#5483]
Hello,
max. count of attachments uploaded at once is limited by PHP directive **max_file_uploads**. I think user should be informed about this and count of selected files should be checked by Javascript after selection (there is a html file input with multiple option in attachment composer form).

If user selects more files than actual max_file_uploads limit, only "max_file_uploads" files are uploaded, others are ignored silently. This is an bug in user interface.

I have made a temporary solution using plugin template hook to let user know about the limit, sample code here for others...

```
$this->add_hook('template_object_composeattachmentform', array($this, 'fix_attachment_form'));
.....
public function fix_attachment_form($params)
    {
        $text_params = array(
            'name' => 'attachment_count_limit',
            'vars' => array(
                'limit' => ini_get('max_file_uploads')
        ));

        $hook = '</form>';
        $new = '<div class="hint">' . $this->gettext($text_params) . '</div>' . $hook;

        $params['content'] = str_replace($hook, $new, $params['content']);

        return $params;
    }
```
![attach](https://cloud.githubusercontent.com/assets/11733592/19511714/b060b78a-95e8-11e6-9c63-02b92a8d0a18.png)

**Comment by alecpl** [comment]
We should display an error and abort upload. In git-master version we don't really have a place to display the hint as you proposed and I think the hint itself is not so much important.

**Comment by skiner68** [comment]
Thanks for your reply :thumbsup:  Yes, the hint is less important then some error info. But it was easier for me to implement using plugin hooks.

**Comment by alecpl** [comment]
Done.
