### ISSUE TITLE
Thumbnail generator should also make sure that the file is an image

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5485]
As suggested in https://github.com/roundcube/roundcubemail/issues/4151#issuecomment-255319205 it is possible to bypass security checks by using e.g. swf-file with jpg extension and image/jpeg mimetype. If the image resize fails we should make sure the file is an image before sending it to the browser as we do for inline images.

**Comment by rpv-tomsk** [comment]
As reporter, I think these security checks by file content are excessive.
Propose to discuss this. )

**Comment by alecpl** [comment]
#4014 talks about an iframe, maybe with <img> there's no such issue in browsers, but I don't know.

As for the CSRF check, I'm not sure.

**Comment by alecpl** [comment]
Fixed. For other considerations use mailing list.
