### ISSUE TITLE
Cannot see any messages

### ISSUE THREAD

**Issue by nswadlin** [roundcube/roundcubemail#5487]
When I log into my mailbox there is no way for me to view any messages. Now that I have been messing with things to try and change the settings back to default, I have changed a lot. If you could just tell me how to reset all of the settings back to normal it might help. Or if there is one setting or something specific I have to do to get it to not be how it is that would be great as well. I have the picture of what I see when I log in attached. In the picture I have the inbox tab opened, and there are 123 messages that I cant view. Same with all of the other folders.

Someone please help me. I have things to do and I have no way to see ANY of my messages
<img width="1280" alt="screen shot 2016-10-24 at 10 33 58 am" src="https://cloud.githubusercontent.com/assets/23033408/19649960/b4dd48be-99d5-11e6-9ece-3d29e14b9c78.png">

**Comment by alecpl** [comment]
Likely a javascript error in the browser. Disable all plugins.

**Comment by nswadlin** [comment]
how do I do that?? @alecpl
