### ISSUE TITLE
Filter: reply with message doesn't work

### ISSUE THREAD

**Issue by tomdereub** [roundcube/roundcubemail#5489]
Hi,
I'm trying do make an auto-reply on roundcube (installed on Yunohost), but it doesn't work. I made a filter with the action "Reply with message" and "move message to", the filter is working because it moves the messages, but it doesn't send any response and I have no trace of it in the logs.
Any Idea ?

**Comment by alecpl** [comment]
This is not Roundcube issue. The responder need to be configured on imap server side.
