### ISSUE TITLE
ssl cert auth instead of login/password feature

### ISSUE THREAD

**Issue by billybons2006** [roundcube/roundcubemail#5491]
I very sorry if my question is not for that place, but, because my question connected with main security, I think, this place (crowded of people knowing roundcube better than others) is the best choise!

Is there plugin/method to authenticate using ssl cert (e.g. from httpd cert auth) instead of using login/password? I look through rcube.php, rcmail.php, http_authentication.php and other and, because I not very professional in it, cant see, how can I do auth in roundcube, if httpd accept cert (since this time there are correct $_SERVER[SSL_CLIENT_I_DN_Email], $_SERVER[SSL_CLIENT_I_DN_CN] vars).

From time to time in scripts I see used password ($_SESSION['password'], $_SERVER['PHP_AUTH_PW']). And, if I don't have password from user, it can lead error in unusuall places.

So, can you tell me if there is regular|best method to implement ssl cert auth instead of login using password?

**Comment by billybons2006** [comment]
As I see, the problem is that password is used in a lot of tasks and if I even auth by cert, I still need password in different files, i.e. rcube_imap.php and others. Ok. As passwords is usually hashed so I need to edit a lot of functions... Very bad. And not flexible.

**So, the issue**: in order to make easier implement different auth methods, may be good idea is to create one point of auth and since this point works/check only with auth token. Benefits: easy use of cert, smart card and other exept login/password.

**Comment by alecpl** [comment]
We need to authenticate the user at least in IMAP and SMTP. So, I think you'll need to configure also these services to use Kerberos/GSSAPI or something like that. In such a case take a look at krb_authentication plugin.

**Comment by billybons2006** [comment]
Oh, I'm to late to close. You answer what I think later. Don't know why I forget that password needs to auth via IMAP. Sure.
