### ISSUE TITLE
Charset problem in Roundcube Settings

### ISSUE THREAD

**Issue by RixzZ** [roundcube/roundcubemail#5492]
Hello,

I noticed that if I go to Roundcube Settings and I write there something like my signature or you full name for an identity, I can't use accents or other characters like é, ñ, etc.

If I'm composing an email I can use them, so seems that the settings section is using another charset or something.

Any workarounds for that?

**Comment by alecpl** [comment]
What do you mean you can't use them. They do not appear when you type, or they disappear/broke when you save the identity. What browser? What Roundcube version? Did you try with plugins disabled?

**Comment by RixzZ** [comment]
Hi,

After a bit more investigation, I saw that the problem is that the CSS of that section of Roundcube uses "Lucida Grande" which is okay on macOS but it works weird on Windows in this case. It was displaying wrong characters.

It's not a roundcube issue.

Sorry for the trouble and thanks for your attention. I'm closing the issue then.
