### ISSUE TITLE
After migration Can't login

### ISSUE THREAD

**Issue by alimaserrat** [roundcube/roundcubemail#5494]
After migrating the Cpanel account with RoundCube. 
Now we can't login anymore, after login it goes to blank page and also the URL shows:
https://webmail.********.net/?_task=login

I dont know what to do with this, tried everything.

**Comment by alecpl** [comment]
Check error log (Roundcube's or Apache's).

**Comment by alimaserrat** [comment]
I dont know how to check the log, can you guid me?

**Comment by alimaserrat** [comment]
There is not much in the error. All of our clients can access their round cube via domain.com/webmail

but for one of our client that we have https://webmail.domain.com

it goes to blank page after migration of cpanel account

**Comment by alimaserrat** [comment]
after migration of Cpanel from our old server to new Centos 6, our client with SSL can't login at their subdomain of: https://webmail.*****.net

after login the page goes to blank page with 500 error. the following is the log and i'm sure i have the right user and pass..

[2016-10-28 23:40:41 -0700] info [cpsrvd] 72.137.211.9 - ali@***.net "POST /login/?login_only=1 HTTP/1.1" FAILED LOGIN webmaild: user password incorrect
[2016-10-28 23:41:41 -0700] info [cpsrvd] 72.137.211.9 - ali@.net "POST /login/?login_only=1 HTTP/1.1" FAILED LOGIN webmaild: user password incorrect
[2016-10-28 23:41:47 -0700] info [cpsrvd] 72.137.211.9 - ali@.net"POST /login/?login_only=1 HTTP/1.1" FAILED LOGIN webmaild: user password incorrect
[2016-10-28 23:42:11 -0700] info [cpsrvd] 72.137.211.9 - ali@***.net "POST /login/?login_only=1 HTTP/1.1" FAILED LOGIN webmaild: user password incorrect

**Comment by alecpl** [comment]
Please, use mailing list or forum. I'm afraid this has nothing to do with Roundcube itself.

**Comment by alimaserrat** [comment]
Which forum would you recommand?

**Comment by rmcaninch** [comment]
There is a web forum or mailing list. https://roundcube.net/support/

**Comment by alimaserrat** [comment]
Guys, I finally got this fixed, Writing the solution here for anyone else that has the issue. 

The mbstring wasn't enabled on apache, so I used the following step to fix the issue:
Source: 
https://forums.cpanel.net/threads/enable-install-mbstring-module.158165/

Steps:
1. You can access EasyApache by going to the Software section of WHM and clicking on EasyApache. Command-line folks can just use /scripts/easyapache.

2. If you're asked to update, do so then come back to this screen. Updates often contain enhancements to allow EasyApache to support updated technologies.

3. On the first screen ("1. Profile"), select "Previously Saved Config (** DEFAULT **)" and then click on "Start customizing based on profile."

This setting will display your current settings throughout the rest of the EasyApache interface. This way you don't need to lookup what your current configuration is, you just change the items you want to have changed (e.g. adding mbstring support to PHP)

4. Continue clicking "Next" until you get to "5. Short Options List" then click "Exhaustive Options List" at the bottom of the page.

5. Under PHP, check the checkbox for "Mbstring" then click "Save and Build"

6. Follow any further on-screen instructions that appear.

The cool thing about EasyApache is that it will ensure everything will work before attempting to apply it to your server. In the relatively rare event that something fails, your current configuration is restored and you will be prompted to allow us to investigate what happened so we can resolve the issue.
#4
