### ISSUE TITLE
Add ability to disable filter sets in managesieve

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#5496]
Some of my users are confused about the filter sets after switching from SieveRules to managesieve. Any chance you can add an option to disable filter sets?

**Comment by alecpl** [comment]
Implemented. Thanks @JohnDoh.

**Comment by tuxayo** [comment]
@smares 

> Some of my users are confused about the filter sets after switching from SieveRules to managesieve. 

What do you mean by confused?

Sorry for necrobumping, I think I'm also confused and I'm trying to know if more than one filter set can be active at the same time.

That's how I found this issue.

**Comment by Disassembler0** [comment]
No, just one set can be active at a time.

My users were also confused, so I have disabled the possibility to create or select another set via
```
$config['managesieve_disabled_actions'] = array('list_sets');
```

**Comment by tuxayo** [comment]
Thanks for confirming this/
