### ISSUE TITLE
Unable to login after upgrade to PHP7

### ISSUE THREAD

**Issue by QkiZMR** [roundcube/roundcubemail#5497]
Before system upgrade Roundcube works perfectly. I had `Ubuntu 14.04.5, PHP5.5.9, Mysql 5.5.53, Apache 2.4.10`. After system upgrade now I have following versions: `Ubuntu 16.04.1, PHP 7.0.8, Mysql 5.7.16, Apache 2.4.18`.

In Apache logs nothing, even in debug logging. In Dovecot also nothing. It looks like Roundcube don't try to connect to dovecot on localhost. Error in web browser:
![zrzut ekranu z 2016-10-30 21-07-48](https://cloud.githubusercontent.com/assets/7574087/19839596/1d7ca162-9ee5-11e6-838a-c7ecaab2e41f.png)
which means "Can't connect to server".

In Roundcube logs I have following error:
`[30-Oct-2016 21:11:30 +0100]: <7kd6h0aq> IMAP Error: Login failed for someuser@example.com from 94.214.172.33. Could not connect to ssl://localhost:993: Unknown reason in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 193 (POST /?_task=login&_action=login)`

Port 993 is open for world. Desktop and mobile clients connects without any problems.

**Comment by QkiZMR** [comment]
Problem was in `localhost` hostname. When I changed config `$config['default_host']` to my domain name (FQDN) it start working again.

**Comment by alecpl** [comment]
Not Roundcube issue.
