### ISSUE TITLE
No IMAP and SMTP connections when running under php-fpm

### ISSUE THREAD

**Issue by alvar-freude** [roundcube/roundcubemail#5501]
Hi,

when running with php-fpm in a FreeBSD Jail, then there is no connection made the IMAP server via login screen or IMAP/SMTP via installation scripts.

When roundcube runs via Apache 2.4  and mod_php, everything is fine.

I checked it via tcpdump and firewall logging, logs of IMAP-Server (Cyrus IMAPd) and more: with php-fpm, there is no TCP connection attempt to the given hosts. The same configuration works fine with Apache.

There are a few SQL queries to the PostgreSQL server.

Roundcube runs inside a Jail, IMAP server etc. in other jails. (FreeBSD jails are lightweight virtual machines). I have an Apache server as frontend (in other jail), which makes SSL encryption and more and proxies all connection via mod_proxy (_http or _fcgi) to the backend.

Rainloop runs in the same jail and same php-fpm without problems, and with Apache+mod_php too.

I enabled full logging, but there appear no messages from roundcube in the log(s) with php-fpm. 

Feel free to ask me, if you need more informations. I tried a lot of things before switching to Apache, but maybe I missed something.

Ciao
  Alvar

**Comment by alecpl** [comment]
I think you should fix logging first. There should be something in the log. What Roundcube version? Packaged or vanilla? Is the logs directory properly set in config and the dir is writeable for the php-fpm process user?

**Comment by alvar-freude** [comment]
Sorry, i missed this: I use roundcube from the FreebSD Ports/Packages, version is roundcube-1.2.2,1 

Logging is configured to use syslog.

  ```
  $config['debug_level'] = 4; 
  $config['log_driver'] = 'syslog';
  $config['imap_debug'] = true;
  $config['sql_debug'] = true;``
```

Syslog is configured to log everything (*.*).

After successful login, all IMAP traffic is logged; but nothing before login.
No login failure is logged to syslog.

When logging to file in default location /usr/local/www/roundcube/log instead of syslog, then some SQL queries for session handling (including DELETE+INSERT instead of UPDATE) are logged, but nothing else. 


It's very strange, that this only happens with php-fpm, not with mod_php. 

For me it's OK to use mod_php, I stripped down Apache a lot so that it's not using much more memory then with php-fpm; but that's not a clear solution ;-)

**Comment by alecpl** [comment]
debug_level=1, never use debug_level=4, please.

**Comment by alvar-freude** [comment]
I used 4, after 1 was  not logging anything ;-)
4 logs more then 1, or not?

Maybe I can check it again tomorrow.

**Comment by alecpl** [comment]
No, this does not work this way.  See defaults.inc.php for options explanation.

**Comment by alvar-freude** [comment]
Ah sorry, I missed the „sum of“ and thought it would be the usual way (higher = more logging), not as bit mask.
So, maybe the description should be more descriptive.

Why not 7 to log all (or is 2 not defined) or 5?

In my first try, I used 1, but expected that the log would be written to the php-fpm log (like apache error log), this was one reason more for my confusion; perhaps the documentation in the default config should give more information and some examples.

**Comment by alecpl** [comment]
It's 1 or 5. Really 4 (5) should be used by developers only, it has side effects. So, please don't use it.

**Comment by alecpl** [comment]
No feedback. No issue.
