### ISSUE TITLE
CRAM-MD5 is not working

### ISSUE THREAD

**Issue by tinodj** [roundcube/roundcubemail#5502]
Hi,

When using CRAM-MD5 I'm getting the following:

AUTHENTICATE CRAM-MD5: A0003 NO [AUTHENTICATIONFAILED] Authentication failed.

When using Plain/Login - all good. 

connection is over TLS to 127.0.0.1

If I can help more, let me know.

Valentin

**Comment by alecpl** [comment]
But does it work with other clients? Enable imap_debug in Roundcube to see more details.

**Comment by tinodj** [comment]
hi, 
you were right to the point there :) 

it was my fault. Actually after enabling this in dovecot (and not really reading documentation about it) I was roundcube started using it (as the best of all)  and generated errros, so I filled in this issue. 

But, yes, you are correct, dovecot was not set correctly in this case, using non-plain passwords and non-cram-md5, so this authentication mechanism could not work at all. 

All good, closing this one. Thanks for the fast response.
