### ISSUE TITLE
Ubuntu 16.04 LTS Unable to uninstall roundcube packages

### ISSUE THREAD

**Issue by khalidshaheen** [roundcube/roundcubemail#5503]
After upgrading from ubuntu 14.04 LTS to 16.04 LTS, trials to uninstall roundcube fails so far with the following error related to memcached followed by the dependency errors below.
------------------------------------------
//
//  excerpt from uninstall trials 
// 
# apt-get remove --auto-remove roundcube
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'roundcube' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
3 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up roundcube-core (1.2~beta+dfsg.1-0ubuntu1) ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: writing config to /etc/dbconfig-common/roundcube.conf
ERROR: Failed to connect to memcached. Please check configuration
dpkg: error processing package roundcube-core (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of roundcube-plugins:
 roundcube-plugins depends on roundcube-core (= 1.2~beta+dfsg.1-0ubuntu1); however:
  Package roundcube-core is not configured yet.

dpkg: error processing package roundcube-plugins (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of roundcube-plugins-extra:
 roundcube-plugins-extra depends on roundcube-core (>= 1.1.2); however:
  Package roundcube-core is not configured yet.

dpkg: error processing package roundcube-plugins-extra (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 roundcube-core
 roundcube-plugins
 roundcube-plugins-extra
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by alecpl** [comment]
Packaging issue. We're not packagers.
