### ISSUE TITLE
Option to switch from <br> and <p> on the text editor

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#5505]
Howdy,

I'd like to have an option for the text editor (MCE), to define the default for the enter key, either if it is a `<br>` or `<p>`.
Of course I can set this manually but on every update the setting will go away/overwrite with the new files.

I've searched the config bug didn't saw anything to do this.
Is this possible to add?

Thanks in advanced,
Jorge Bastos

**Comment by alecpl** [comment]
You can use this plugin https://git.kolab.org/diffusion/RPK/browse/master/plugins/tinymce_config/

We'll not add such an option. There are various issues in TinyMCE in this mode we don't want to deal with.
