### ISSUE TITLE
CGI Generic SQL Injection (blind)

### ISSUE THREAD

**Issue by takenek** [roundcube/roundcubemail#5506]
Helo
I just scan my RoundCube server using Nessus scanner and he detect SQL Injection:

Using the POST HTTP method, Nessus found that :

+ The following resources may be vulnerable to blind SQL injection :

+ The '_user' parameter of the / CGI :

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=&_user=zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_time
zone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2floca
lhost&_pass=&_user=yy]

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=&_user=zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_time
zone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2floca
lhost&_pass=&_user=yy] {2}

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=&_user=zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_time
zone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2floca
lhost&_pass=&_user=yy] {3}

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=&_user=257685zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87
&_timezone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%
2flocalhost&_pass=&_user=257685yy]

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="257685" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="257685yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=&_user=257685zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87
&_timezone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%
2flocalhost&_pass=&_user=257685yy] {2}

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="257685" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="257685yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=&_user=257685zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87
&_timezone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%
2flocalhost&_pass=&_user=257685yy] {3}

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="257685" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="257685yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=594381&_user=zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87
&_timezone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%
2flocalhost&_pass=594381&_user=yy]

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=594381&_user=zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87
&_timezone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%
2flocalhost&_pass=594381&_user=yy] {2}

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

/ [_task=login&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87&_timezone=_
default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%2flocalhost&
_pass=594381&_user=zzlogin&_url=&_token=2ea4925d13401d158a1ef3a0fc60cb87
&_timezone=_default_&_action=login&_dstactive=_default_&_host=ssl%3a%2f%
2flocalhost&_pass=594381&_user=yy] {3}

-------- output --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
-------- vs --------
<input type="hidden" name="_task" value="login" /><input type="hid [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" autocomplete="of
f" value="yy" type="text" /></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Has..o</label>
------------------------

**Comment by alecpl** [comment]
I don't see an issue here.

**Comment by takenek** [comment]
So this is false positive alert?
