### ISSUE TITLE
String should be an array

### ISSUE THREAD

**Issue by MaMaKow** [roundcube/roundcubemail#5508]
/program/lib/Roundcube/rcube.php
line 1325 (since 21 Sep)
**$post_query = '';**
should probably be 
**$post_query = array();**

It causes the following error in 1.2.2:

> Warning: Illegal string offset '_action' in /var/www/html/roundcubemail-1.2.2/program/lib/Roundcube/rcube.php on line 1330 Warning: http_build_query(): Parameter 1 expected to be Array or Object. Incorrect value given in /var/www/html/roundcubemail-1.2.2/program/lib/Roundcube/rcube.php on line 1336

PHP 7.1.0RC5 
Apache/2.2.15 (Unix)

**Comment by alecpl** [comment]
I suppose this is new in PHP 7.1.

**Comment by alecpl** [comment]
Fixed.
