### ISSUE TITLE
*_mbox settings ignored

### ISSUE THREAD

**Issue by tronsgaard** [roundcube/roundcubemail#5509]
I am setting up a RC 1.2.2 installation talking to a dovecot imap server. The existing special folders are `mail/INBOX.Sent`, `mail/INBOX.Drafts` etc., so I have set the following in config.inc.php:

```
$config['sent_mbox'] = 'mail/INBOX.Sent'
$config['drafts_mbox'] = 'mail/INBOX.Drafts'
...
```

It works perfectly in some cases - but if there is a file named 'Sent' (in the root, outside the mail/ directory), Roundcube will forget everything about the settings above, and use the empty file 'Sent' as the folder for sent mail. It even adds this to the user settings. Same thing happens with 'Drafts', except that it does not add it to the user settings.

~~After reading #4782 I tried setting `$config['imap_disabled_caps'] = array('SPECIAL_USE')` but it had no effect. I also tried changing the setting in defaults.inc.php, but the problem persisted.~~

Any clue what is going on? Did I miss something? If there is a bug, I would be happy to help fix it.

EDIT: Just realized that I mistyped the "-" in "SPECIAL-USE" as a "_". This fixed my problem. But if I understand #4782 right, the roundcube settings are not supposed to be overridden by imap SPECIAL-USE settings?

**Comment by alecpl** [comment]
I'm almost sure the "mail/" prefix is redundant here. Also it looks like an UW-IMAP problem described in #5073.
