### ISSUE TITLE
"Settings>Folders" gives HTTP 500

### ISSUE THREAD

**Issue by tronsgaard** [roundcube/roundcubemail#5510]
On RoundCube 1.2.2, when I go to Settings -> Folders, the request gives a HTTP 500 error.

The following error appears in the log:

```
Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20456091 bytes) in /var/webmail/roundcube/program/include/rcmail_output_html.php on line 776
Stack trace:
  1. {main}() /var/webmail/roundcube/index.php:0
  2. include_once() /var/webmail/roundcube/index.php:291
  3. rcmail_output_html->send() /var/webmail/roundcube/program/steps/settings/folders.inc:196
  4. rcmail_output_html->parse() /var/webmail/roundcube/program/include/rcmail_output_html.php:478
  5. rcmail_output_html->write() /var/webmail/roundcube/program/include/rcmail_output_html.php:639
  6. rcmail_output_html->_write() /var/webmail/roundcube/program/include/rcmail_output_html.php:526
  7. rcmail_output_html->parse_with_globals() /var/webmail/roundcube/program/include/rcmail_output_html.php:1635
  8. preg_replace_callback() /var/webmail/roundcube/program/include/rcmail_output_html.php:776
```

I have also tested with version 1.1.6, and here it works (but the page loads very slowly). 

I assume that the error is caused by the list of files and folders being too long (for historic reasons, our IMAP server is set up with the user home directoriy as root, instead of the mail/ directory). However, if version 1.1.6 can handle it, I think newer versions should be able to handle it as well.

**Comment by alecpl** [comment]
If your server returns files on folders list it is just wrong. See #5073.
