### ISSUE TITLE
$config['force_uri'] = "domain.com";

### ISSUE THREAD

**Issue by smtalk** [roundcube/roundcubemail#5511]
It'd be great to have an ability to set domain which roundcube should redirect to. When having a global alias in apache configuration, it's not possible to do that without changing apache config or RoundCube .htaccess. A simple configuration option:
`$config['force_uri'] = 'domain.com';`

Would solve it.

Change to index.php:
Find:
`$host  = preg_replace('/:[0-9]+$/', '', $_SERVER['HTTP_HOST']);`

Replace with:
`$host  = preg_replace('/:[0-9]+$/', '', $RCMAIL->config->get('force_uri', $_SERVER['HTTP_HOST']));`

**Comment by alecpl** [comment]
I'd rather extend meaning of force_https, so it can contain host:port value. Patches welcome.

**Comment by ArvydasR** [comment]
[patch.txt](https://github.com/roundcube/roundcubemail/files/600293/patch.txt)

Added host support for $force_https configuration option to redirect to a specified domain.

**Comment by alecpl** [comment]
Thanks. I modified the code slightly.
