### ISSUE TITLE
Mails sent by Mailvelope not recognized as PGP

### ISSUE THREAD

**Issue by m0urs** [roundcube/roundcubemail#5513]
If I send a mail with the Chrome plugin "Mailvelope", the mail is not recognized by Enigma as PGP encrypted.

The mail is instead just displayed like normal text with a 

-----BEGIN PGP MESSAGE-----
Version: Mailvelope v1.5.2
Comment: https://www.mailvelope.com

......

-----END PGP MESSAGE-----

(If I send a mail from Roundcube encrypted by Enigma, then Mailvelope can decrypt it correctly.)

**Comment by alecpl** [comment]
Could you provide a sample? Are you using Mailvelope API integration or not?

**Comment by m0urs** [comment]
"Are you using Mailvelope API integration or not?"

What exactly do you mean with that? I have installed the Chrome Mailvelope plugin in Chrome and just added my keys and tried to send a mail to my Roundcube account.

The mail looks like that:

MIME-Version: 1.0
Received: by 10.80.153.12 with HTTP; Sun, 13 Nov 2016 08:01:43 -0800 (PST)
From: Michael Urspringer <xxx.yyy@zzz.com>
Date: Sun, 13 Nov 2016 17:01:43 +0100
Message-ID: <CAEFLL-9aNdJU-Kysxh25o9nTfxmqs14ztbckQdS5=7X1DdXYsg@mail.gmail.com>
Subject: TEST
To: "Michael Urspringer <abc.def@ggg.com>" <abc.def@ggg.com>
Content-Type: multipart/alternative; boundary=001a1148ebcafc52ff054130d677

--001a1148ebcafc52ff054130d677
Content-Type: text/plain; charset=UTF-8

-----BEGIN PGP MESSAGE-----
Version: Mailvelope v1.5.2
Comment: https://www.mailvelope.com

wcBMA06RvXvVMxwZAQf9EyFAlThb7NSyYeKFUA7e6GOb9B0yYqhtEF2wa+Ds
46Aq+ZZxXJPhWMBV7ZHajVuIro86g2uH9vUT2FDL8xJxMe1qAo4lN1/lVk+n
yBE3+LHPdp+Qyio5KzuHBt3KeM831GUJnIl1QsPS5wQWuZKTTuOvmDQsZ1FQ
W4L0M6ltfTaM2yKOJhndG6z28jn2Ukt17MPhT5itfdaEMN/RobS/V9Bi6HZv
MnbjdDZcz9IUhYE2lsJMDshwhDhqtInfYpCHCjmxsBu5HlIfj1hZSdhYwNte
BBprf2sBbQzyEk6q9OXiiHQR320in47a2UaKpXon2D8sv7GRpiXEnF2fqrom
5cHBTANKC5cg/iTXEAEP/RzS+V9Zo5P0JdXnPnVboCx7zjJAGOmQURrnzLgD
LlNNlNNh9UhIRV4J2ddICS3tXPlYvtegDokFFBTh2nZFgktzRT63nLZ6otTe
dzJ0jrCCJ0CuG7KipX+1fLY+RovNspo4TXyIXY7gVH5kJErsExh7Wteez7d1
xazzarUD7Kfck84FFg+rJow59I8m01s3pBRyCdCKdixZkVZGLTUfxEzA/0em
WAerjKiZCgh+FSd015kgbwwh86z7N+Q41Snt4+PhNo4DvEISIWfecSj5cLaI
v98HGkZo+pxe0+WZPQEFpZAT6U9HVz3s+yLfy7Fe3MpGwpKSxH0ivnhbaOgo
Vel4BYeqsJ7V2V/rLiGc7Cqgq+WvJufDIR/kOfCfgsPn9k+T1xUQ+Lc/WZZ0
UfBwH9ObtQEHj15X+AvWvSt8eUv8azoYNdxigRJ7As9h7pDSa7fWIfhxkhtx
i3qC2HxG3Z9hZMrBW2q5uStk6LKNP4bpQnGnyaYXyoQnKAlYxqR5C37ahohX
x5W3XMEF9u8hS6XGsHf+sgXDr0PuQWX4AwTg/yqYWtOPN+pRfS3PR1VrTbnK
fhvOpZssg26fLT7Px8nbyeR9tbsnxFxoKigZREEvy3sD4jm2ra5MPcuP8Gjd
ue01urhUjHTO1q8HgODMIjXU69w4vSihw5pYeN9uXw6h0jwB1hH2zDbg4rNU
1jMikqK1MfKrNdYOft6HFDuKWpoqQcVawzSq9D4mUJJ3sjgA3Zo0hziKnk+y
6iD2YhQ=
=PX1L
-----END PGP MESSAGE-----

--001a1148ebcafc52ff054130d677
Content-Type: text/html; charset=UTF-8

<div dir="ltr"><pre>-----BEGIN PGP MESSAGE-----
Version: Mailvelope v1.5.2
Comment: <a href="https://www.mailvelope.com">https://www.mailvelope.com</a>

wcBMA06RvXvVMxwZAQf9EyFAlThb7NSyYeKFUA7e6GOb9B0yYqhtEF2wa+Ds
46Aq+ZZxXJPhWMBV7ZHajVuIro86g2uH9vUT2FDL8xJxMe1qAo4lN1/lVk+n
yBE3+LHPdp+Qyio5KzuHBt3KeM831GUJnIl1QsPS5wQWuZKTTuOvmDQsZ1FQ
W4L0M6ltfTaM2yKOJhndG6z28jn2Ukt17MPhT5itfdaEMN/RobS/V9Bi6HZv
MnbjdDZcz9IUhYE2lsJMDshwhDhqtInfYpCHCjmxsBu5HlIfj1hZSdhYwNte
BBprf2sBbQzyEk6q9OXiiHQR320in47a2UaKpXon2D8sv7GRpiXEnF2fqrom
5cHBTANKC5cg/iTXEAEP/RzS+V9Zo5P0JdXnPnVboCx7zjJAGOmQURrnzLgD
LlNNlNNh9UhIRV4J2ddICS3tXPlYvtegDokFFBTh2nZFgktzRT63nLZ6otTe
dzJ0jrCCJ0CuG7KipX+1fLY+RovNspo4TXyIXY7gVH5kJErsExh7Wteez7d1
xazzarUD7Kfck84FFg+rJow59I8m01s3pBRyCdCKdixZkVZGLTUfxEzA/0em
WAerjKiZCgh+FSd015kgbwwh86z7N+Q41Snt4+PhNo4DvEISIWfecSj5cLaI
v98HGkZo+pxe0+WZPQEFpZAT6U9HVz3s+yLfy7Fe3MpGwpKSxH0ivnhbaOgo
Vel4BYeqsJ7V2V/rLiGc7Cqgq+WvJufDIR/kOfCfgsPn9k+T1xUQ+Lc/WZZ0
UfBwH9ObtQEHj15X+AvWvSt8eUv8azoYNdxigRJ7As9h7pDSa7fWIfhxkhtx
i3qC2HxG3Z9hZMrBW2q5uStk6LKNP4bpQnGnyaYXyoQnKAlYxqR5C37ahohX
x5W3XMEF9u8hS6XGsHf+sgXDr0PuQWX4AwTg/yqYWtOPN+pRfS3PR1VrTbnK
fhvOpZssg26fLT7Px8nbyeR9tbsnxFxoKigZREEvy3sD4jm2ra5MPcuP8Gjd
ue01urhUjHTO1q8HgODMIjXU69w4vSihw5pYeN9uXw6h0jwB1hH2zDbg4rNU
1jMikqK1MfKrNdYOft6HFDuKWpoqQcVawzSq9D4mUJJ3sjgA3Zo0hziKnk+y
6iD2YhQ=
=PX1L
-----END PGP MESSAGE-----
<pre></pre></pre></div>

--001a1148ebcafc52ff054130d677--

**Comment by alecpl** [comment]
You should disable HTML editor when you tend to use encryption. This is not supported by Enigma and I don't think it will.

Roundcube 1.2 contains Mailvelope integration code which is not as feature-rich as a standalone Mailvelope plugin (looks like you use this mode), but has some pros, e.g. it does not create multipart/alternative messages.

**Comment by alecpl** [comment]
BTW, I'm not 100% sure, but Enigma should detect encryption in this message if you switch message view mode from HTML to plain text. This is still not supported message structure.

**Comment by m0urs** [comment]
Thanks, switching from HTML to Text format in GMail while using the Mailvelope plugin, did the trick. Enigma is then correctly able to decrypt the message. That is ok for me. BTW: Switching to Textmode in Roundcube was not successful.
