### ISSUE TITLE
Question: reconfiguring tables for round cube

### ISSUE THREAD

**Issue by Morketh** [roundcube/roundcubemail#5515]
Well i have written a webpage for a group that im maintaining and i have a few questions concerning the webmail part of roundcube. Before i dig too far into ripping round cube apart the questions i had were these:
- Is it possible to reconfigure the users and email to fit with what i already have? I'm currently using Postfix and Dovecot with a custom table layout for my groups website and secondlife?
- Or just for simplicity sake would it be easier to just reconfigure the postfix, dovecot and preexisting website to integrate into roundcube?

Currently i have a way of adding usernames/passwords/emails through my own webpage using a Secondlife script and PHP interface for the Roleplay Group in question. Im honestly thinking it would be easier for the end user to reconfigure Roundcube to integrate into what i already have. If i rebuilt everything id have to reconfigure scripts and MySQL tables for the website as well as several Items in world that every one in group has access to. I dug through some of the code to find what tables were accessed and it seems like the users table is pretty deeply integrated into roundcube. I can merge the tables for roundcube directly into the MySQL that i already have but i want to avoid setting up 2 separate user tables when the one i have already tracks ID, username, and email address. I would need to add the other dependent fields from roundcube users that pertain to the Roundcube configuration directly. I guess it really just boils down to:
- Where do i change the "user_id", "username" fields to match my configuration?
- And how does the "mail_host" field in the database work? Would that be "username@domain.ext" or is that just the "domain.ext"? If this is the "username@domain.ext" this would need to be changed to "email" in order to work correctly with the existing website structure.

This isnt really a big issue rather just a question on how to configure as i couldn't find any documentation on how this could be achieved. Ive used round cube before in other configurations and its a very well made product. Keep up the good work.

**Comment by rmcaninch** [comment]
Roundcube is a client. You manage your users in the email server backend. You can then set Roundcube to automatically create users as folks successfully login to the IMAP server.

The field names would have no need to match.

mail_host is the IMAP server that your users login to. You can make that match different domains connecting to different servers if need be. See the defaults.inc.php for the comments.

**Comment by Morketh** [comment]
Ive dug through all those configuration settings. even tweaked a few things to match my current layout. so if im understanding you correctly what i have shouldn't need to be changed. and roundcube will take care of its own clients? now trying to log into roundcube with my Username and password (that i use for my thunderbird client) gives me "Connection to storage server failed." im assuming i have a database connection problem. the defaults.inc.php has some MySQL settings but it doesnt look like theres a place i set the Roundcube user and password (ive created one and used that durring the configuration script) I honestly think im making this more complicated then it has to be

**Comment by rmcaninch** [comment]
The better place for this discussion is somewhere in http://www.roundcubeforum.net or the mailing list.

But yes, if you want to use Roundcube as webmail for an existing IMAP server then you just follow the INSTALL file. 

Don't change defaults.inc.php there should be a config.inc.php, or make one as the instructions advise. If you installed a Debian Roundcube package then the database login will be split out to a separate file (as commented in the config.inc.php file).

**Comment by alecpl** [comment]
Configuration issue not a bug.
