### ISSUE TITLE
Managesieve: RAW editor improvements

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5518]
It would be nice to have code highlighting and line numbering. There are two javascript editors worth looking at, it's Ace and CodeMirror. Ace have no Sieve support, so it looks like we'll use CodeMirror.

When we have line numbering we could also display precise errors from managesieve server which usually contain line numbers.

**Comment by trippleflux** [comment]
I vote +1 for this being merged 👍

**Comment by alecpl** [comment]
Done.
