### ISSUE TITLE
Error when store 0 in roundcube cache

### ISSUE THREAD

**Issue by dioubernardo** [roundcube/roundcubemail#5519]
If I store 0 in the database cache as packed = false, when I use the get function it is always returned null

program/lib/Roundcube/rcube_cache.php in line 306

$md5sum = $sql_arr['data'] ? md5($sql_arr['data']) : null;
if ($sql_arr['data']) {
	$data = $this->unserialize($sql_arr['data']);
}

if ($sql_arr['data']) when $sql_arr['data'] = 0 is false

**Comment by alecpl** [comment]
Fixed.
