### ISSUE TITLE
UI Layout issue in Safari/iOS 10

### ISSUE THREAD

**Issue by YoKoGFX** [roundcube/roundcubemail#5521]
Hi there :)
I just found a Bug in Roundcube...
I have tested it on an iPad Air 2 and iPad Mini 2
It looks always the same :/

**Version**
It runs the Roundcube Version 1.2.2

**Comment by alecpl** [comment]
I remove the SPAM image. Are you using any plugins or skin modifications? What exactly is the browser version there?

**Comment by YoKoGFX** [comment]
## PLUGINS
jqueryui **Version 1.10.4**
and
filesystem_attachments **Version 1.0**

## Skin
The Skin used is the Larry with a modified Logo

## Browser
Browser used is the standard **Safari** from iOS 10.1.1 and also tested with iOS 10.2 Beta 3

**Comment by YoKoGFX** [comment]
I made a Patch for this Issue :)
You can see above...

**Comment by alecpl** [comment]
This is strange and looks more like Safari issue. There's no issue in iPad/iOS 9. I don't really like the proposed solution.

**Comment by YoKoGFX** [comment]
Have you tried it with two apps side by side?

**Comment by alecpl** [comment]
For tablets we have Elastic skin now in git-master.
