### ISSUE TITLE
Nicely handle contact deletion on contact edit

### ISSUE THREAD

**Issue by sblaisot** [roundcube/roundcubemail#5522]
Hi,

Some user of automatic_addressbook plugin report the following message in his error log:

`PHP Warning: array_intersect_key(): Argument #1 is not an array in /usr/share/roundcube/program/steps/addressbook/save.inc on line 178`

https://github.com/sblaisot/automatic_addressbook/issues/11

I suspect a bug in save.inc but maybe there is also a bug in automatic_addressbook.

any hint ?

**Comment by sblaisot** [comment]
I think I found why.
automatically collected addressbook work in a different way. Each edited entry is moved to the default addressbook resulting in the deletion of that entry in the automatically collected addressbook.

I think this case is handled properly by save.inc only in the case of an LDAP DN change (with result being a string). This case is also a change in contact id, but with id being an int.

**Comment by alecpl** [comment]
All we can do here is to throw an error if get_record() does not return an array.

**Comment by sblaisot** [comment]
If get_record() doesn't return an array, can't you just stop refreshing the view ?
I mean, if(is_array($CONTACT_RECORD)) lines 170-187 ?

just to handle the case where a plugin removed the contact from that addressbook on update.

**Comment by alecpl** [comment]
I suppose we could force a list refresh in such cases, so it would also bring the watermark page to the contact frame.

**Comment by alecpl** [comment]
Done.

**Comment by sblaisot** [comment]
Thanks
