### ISSUE TITLE
Multiple undefined indexes in rcube_imap_generic

### ISSUE THREAD

**Issue by truckee** [roundcube/roundcubemail#5523]
This may be an example of working out of my depth, but...

A call (in v1.2.2) to `rcube_imap_generic->connect($host, $user, $password)` results in multiple indexes not found. The method signature is `connect($host, $user, $password, $options = null)` and its first line is `$this->set_prefs($options);`  Thus when no options are provided the class property `prefs` is null.  So when the protected method `_connect()` is called, and that method does things like:
````
        if (!$this->prefs['port']) {
            $this->prefs['port'] = 143;
        }
````
there is no `prefs` array element for port. One could correct the resulting error with `array_key_exists(...)` I suppose.  Or one could pass an options array that contains all of the expected keys, in which case it should not default to `null`.

**Comment by alecpl** [comment]
Fixed.
