### ISSUE TITLE
Implement Google Authenticator

### ISSUE THREAD

**Issue by Dennis1993** [roundcube/roundcubemail#5524]
To make the login secure, I think a 2 factor authentication is useful (e.g. Google Authenticator).
It is possible to integrate this functionality?

**Comment by thomascube** [comment]
A 2-factor authentication plugin exists as part of the Kolab Roundcube Plugins. See `plugins/kolab_2fa` in https://git.kolab.org/diffusion/RPK/

This plugin supports different 2nd factors like TOTP (Google Authenticator) HOTP or Yubikey.

We shall publish this at some point as a standalone module installable through the Roundcube plugin repository.

**Comment by Takika** [comment]
I tried this plugin, but everytime I got a code verification error message :(

**Comment by Dennis1993** [comment]
Would it be useful to offer the 2 factor authentication from home with?
This simple class can help: https://github.com/PHPGangsta/GoogleAuthenticator
Now the user can activate it after the first login or not. Maybe it is just an idea. 👍

**Comment by alecpl** [comment]
There are other 2-factor auth plugins. https://plugins.roundcube.net/search/?tags=Authentication. This is anyway a work for a plugin. I'm closing the ticket.
