### ISSUE TITLE
BUG: incorrect error = DATABASE ERROR: CONNECTION FAILED!

### ISSUE THREAD

**Issue by pedromorgan** [roundcube/roundcubemail#5525]
So a search.. and at top of list is...
http://lmgtfy.com/?q=DATABASE+ERROR%3A+CONNECTION+FAILED!

So in my case.. with 1.2.2

-  database user/db setup and credentials validated
-  hit installer and cut and paste into nano online
-  the error above.. when hit page...

What I did not do was import the "schema from sql"..

and that is the bug ..
the message needs changing to..
>> database connection established, but your and idiot cos no tables".. or something like that..

Indeed the "CONNECTION FAILED".. threw we down a path.. 

I tried to find the message in code to patch but php is outtta my zone atmo..

Otherwise when setup it worked cool

**Comment by alecpl** [comment]
What is displayed to the user is one thing, but I'd expect more useful error in log. There was no error?

**Comment by pedromorgan** [comment]
correct, no error

**Comment by alecpl** [comment]
I can't confirm that. I made a test and the error in log is `DB Error: [1146] Table 'rctest.session' doesn't exist (SQL Query: INSERT INTO...` So, it looks you also have logging not configured correctly. I don't think there's much we can improve here.
