### ISSUE TITLE
Add ability the attachment icon to show only real attachments

### ISSUE THREAD

**Issue by neterbg** [roundcube/roundcubemail#5528]
Currently there is attachment icon in the list for messages that don't have attachments for download, but sign keys and html/plain parts too. I know that these message parts are basically attachments too and some people want to see attachment icon for them, but some people (like me and many people around me) want to see attachment icon only for messages that have attachments for download (the files that are displayed in the right pane of the message).
Please, add an option the attachment icon in the messages list to be shown only for messages with such attachments.

**Comment by alecpl** [comment]
For performance reasons I don't see a possibility to do more sophisticated attachment detection.
