### ISSUE TITLE
Merge of config files not working with debian-db.php

### ISSUE THREAD

**Issue by shaneonabike** [roundcube/roundcubemail#5533]
So I just upgraded from 0.95 (installed on Ubuntu 14.04) to 1.2.2 and noticed that when running the upgrade script the merge does not include the section that grabs all the DB information from the dpkg-config settings.

It would need to include the following at the top to make things work properly:
`include_once("/etc/roundcube/debian-db.php");

switch ($dbtype) {
 case "sqlite":
 case "sqlite3":
   $config['db_dsnw'] = "sqlite:///$basepath/$dbname?mode=0640";
   break;
 default:
   if ($dbport != '') $dbport=":$dbport";
   if ($dbserver == '') $dbserver="localhost";
   $config['db_dsnw'] = "$dbtype://$dbuser:$dbpass@$dbserver$dbport/$dbname";
   break;
 }

`

I modified that to use the current `$config` array rather than the previous

**Comment by alecpl** [comment]
This is a file added by distribution an should be fixed there.
