### ISSUE TITLE
Add to dictionary

### ISSUE THREAD

**Issue by domtylerlovett** [roundcube/roundcubemail#5534]
Issue: Spellcheck doesn't pickup browser dictionary and/or allow addition of new words.

Effect: Words in autosig for example are picked up every time compose a new email.

Suggestion: Email body text to use built-in browser dictionary

**Comment by alecpl** [comment]
There are two dictionaries/spellcheckers used in mail composer:
1. Browser spellchecker - squiggly red line, works "as you type". On mouse right-click provides a way to add a word to dictionary. Dictionary is stored in the browser.
2. Roundcube spellchecker - solid red line, requires pressing the Spellcheck button. On mouse left-click provides a way to add a word to dictionary. Dictionary is stored on the server.
As I know there's no way to merge both dictionaries. So, you have to decide which spellchecker are you going to use and add words to its dictionary.

I don't see a bug here. If you see a bug, please be more specific and provide information about used Roundcube version and web browser.

**Comment by domtylerlovett** [comment]
Thanks Alec

It's the best open source email client we've seen so certainly not criticizing and apologies if we came across that way.

Option 1: This would be ideal although because it's browser-based it doesn't of course intervene pre-send.

Option 2: This is therefore is how we'd want to use RoundCube, but we don't see an option to add to dictionary when we left or right click a word

Thank you for your help

**Comment by alecpl** [comment]
Then maybe you're using some ancient version?

**Comment by domtylerlovett** [comment]
Possibly Alec.  The About screen shows "Roundcube Webmail 1.2.2".  I'll try to attach a screenshot

**Comment by alecpl** [comment]
The version is fine. I just reminded myself that spellcheck_dictionary option is disabled by default.

**Comment by domtylerlovett** [comment]
Thanks Alec - could you let us know how to modify that option?

**Comment by alecpl** [comment]
As any other option in config.inc.php

**Comment by TerrySouthgate** [comment]
Dom

Wow, on behalf of the general development community I apologise for how rude and unhelpful Alec has been throughout this issue, he clearly has some communication problems!!

I will send you a separate message explaining how to edit the config file **_because I understand not everyone is a programming expert_**.

Best wishes

Terry

**Comment by domtylerlovett** [comment]
Thanks Terry - I'm definitely not a programming expert so that would be great :)

I'll keep future messages regarding RoundCube off this forum - when I signed up it asks what level of development I'm at so I assumed it catered for programmers of all levels.

Dom

**Comment by alecpl** [comment]
Come on guys! If you're a user you can't change config options. If you're an admin, you already configured Roundcube and you should know how to do this. I such a case I provided all needed information.

Anyway! This is bugtracker, not support forum.

**Comment by Abatjour3407** [comment]
Hi

I am really starting to like this platform a lot! In many ways I believe it is even better than Gmail... Thank you so much for this amazing contribution to the web!

A small bug though, I am encountering this same problem described above:

I am using Roundcube 1.4 RC1 with the elastic theme. I am using the 'enchant' spell checker and have disabled the spell-checker in my browser. I cannot see the _add to dictionary_ option (see screenshot). I have checked the config file and only see a place to change the dictionary used there. 

**Also a related feature idea that would fit in well with this amazing platform could be automatically adding contact names from the address books to the dictionary (like what mobile phones do).**

Thanks again for this excitingly good platform!


![bug10002](https://user-images.githubusercontent.com/50051640/61035788-16a1cd00-a3c8-11e9-93db-41a3602f306e.png).

**Comment by alecpl** [comment]
Search for `spellcheck_dictionary` in `config/defaults.inc.php` and move the option to `config/config.inc.php` with changing the value.

**Comment by roundcubeuser** [comment]
@alecpl in your screenshot that your showing, the "add to dictionary" option is not showing

**Comment by roundcubeuser** [comment]
@alecpl 
I am also fan of roundcube webmail. When I type new email the first letter is not capitalized, and also "add to dictionary" option is not showing. 
I wish these could be easy fixes..

Thanks
