### ISSUE TITLE
Remove external javascript code from the git repo and dependent package

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5535]
I propose to remove external javascript libraries from the repository. I mean, we have now jquery, jstz, tinymce, openpgpjs, codemirror. All of them could be removed. We'd add an installation script. There's also jquery-ui, but this one we patch and may be not so simple to install.

@thomascube what do you think?

**Comment by thomascube** [comment]
I generally agree if we keep an eye on the used versions. Maybe consider using something like [bower](https://bower.io) for easy installation of the dependencies for development.

One tricky part will be to assign the correct headers with `@licstart`, `@licend` and `@source` for the awful LibreJS support we have. These are currently hand-picked and inserted manually.

**Comment by alecpl** [comment]
I was actually going to get rid of librejs support for external libs.

**Comment by alecpl** [comment]
@thomascube really I don't want to use anything complicated and anything that uses node.js. And I'm not sure it would handle all our deps anyway. Ready for review: https://github.com/roundcube/roundcubemail/compare/dev-remove-js-deps

**Comment by thomascube** [comment]
OK, I do understand that we don't want to add more dependencies but your proposed script doesn't yet provide a full replacement for what we currently have in our repo. The license and source link topics are still pending and we should not step back from being good free software citizens.

I suggest to specify the license type for each script and then prepend the downloaded files with the according license header. And could we make the script more generic and let it read in a json file specifying the dependencies?

```
{
  "dependencies": [
    {
      "lib": "jquery",
      "version": "3.1.1",
      "url": "https://code.jquery.com/jquery-3.1.1.min.js",
      "dest": "program/js/jquery.min.js",
      "sha": "f647a6d37dc4ca055ced3cf64bbc1f490070acba",
      "license": "MIT",
      "copyright": "Copyright 2005, 2016 jQuery Foundation, Inc.",
      "source": "https://github.com/jquery/jquery/tree/3.1.1"
    },
    ...
  ]
}
```

The information from "license", "copyright" and "source" could be used to compose the according comment block for the destination file.

**Comment by thomascube** [comment]
I'm working on it...

**Comment by thomascube** [comment]
@alecpl Please review my more generic installer script

**Comment by alecpl** [comment]
@thomascube I applied some improvements. It looks good. Merged into master.
