### ISSUE TITLE
Recent git update fails mysql db schema update

### ISSUE THREAD

**Issue by fsantiago07044** [roundcube/roundcubemail#5536]
This from trying to run schema update for mysql: 2016112200.sql:

Error
SQL query:

ALTER TABLE `dictionary` ADD COLUMN `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY FIRST
MySQL said: Documentation

#1060 - Duplicate column name 'id'

./bin/update.sh fails schema update. This was obtained running manually. 

Updating from an October git master rev.

**Comment by alecpl** [comment]
Strange. This table didn't have an id column before. https://github.com/roundcube/roundcubemail/commit/a1f679adcacb865c8b692d4427bde65cd4065b43#diff-cba810499e8c041b6c13e80f385a2664L178
Did you add it manually for some reason (e.g. clastering)?

**Comment by fsantiago07044** [comment]
No, if anything it must have been applied by previous git update. I wouldn't manually manipulate the db. 


On November 29, 2016 2:36:09 AM EST, Aleksander Machniak <notifications@github.com> wrote:
>Strange. This table didn't have an id column before.
>https://github.com/roundcube/roundcubemail/commit/a1f679adcacb865c8b692d4427bde65cd4065b43#diff-cba810499e8c041b6c13e80f385a2664L178
>Did you add it manually for some reason (e.g. clastering)?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/roundcube/roundcubemail/issues/5536#issuecomment-263497765

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by alecpl** [comment]
I have no idea how that could happen. It works for me. I've had Roundcube 1.2 and in mysql it returned:
```
MariaDB [roundcube]> describe dictionary;
+----------+------------------+------+-----+---------+-------+
| Field    | Type             | Null | Key | Default | Extra |
+----------+------------------+------+-----+---------+-------+
| user_id  | int(10) unsigned | YES  | MUL | NULL    |       |
| language | varchar(5)       | NO   |     | NULL    |       |
| data     | longtext         | NO   |     | NULL    |       |
+----------+------------------+------+-----+---------+-------+
 rows in set (0.01 sec)
MariaDB [roundcube]> show create table dictionary;
 CREATE TABLE `dictionary` (
  `user_id` int(10) unsigned DEFAULT NULL,
  `language` varchar(5) NOT NULL,
  `data` longtext NOT NULL,
  UNIQUE KEY `uniqueness` (`user_id`,`language`),
  CONSTRAINT `user_id_fk_dictionary` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
Then update process worked without errors.
