### ISSUE TITLE
Failure when importing sieve vacations from Horde with nested ifs

### ISSUE THREAD

**Issue by tpokorra** [roundcube/roundcubemail#5540]
We have sieve vacation scripts from Horde with nested ifs. If we try to reuse them, we have had bad results, because the parser does not cope well with the nested ifs, and we end up with emails discarded because the next rule was not processed correclty.

Sample sieve script:

```
# Sieve Filter
# Erzeugt von Ingo (http://www.horde.org/ingo/) (30.09.2016, 16:02)

require ["vacation", "regex"];

# Abwesenheit
if allof ( not exists ["list-help", "list-unsubscribe", "list-subscribe", "list-owner", "list-post", "list-archive", "list-id", "Mailing-List"], not header :comparator "i;ascii-casemap" :is "Precedence" ["list", "bulk", "junk"], not header :comparator "i;ascii-casemap" :matches "To" "Multiple recipients of*" ) {
    if header :regex "Received" "^.*(2016) (\\(.*\\) )?..:..:.. (\\(.*\\) )?(\\+|\\-)....( \\(.*\\))?$" {
    if header :regex "Received" "^.*(Oct) (\\(.*\\) )?.... (\\(.*\\) )?..:..:.. (\\(.*\\) )?(\\+|\\-)....( \\(.*\\))?$" {
    if header :regex "Received" "^.*([0 ]4|[0 ]5|[0 ]6|[0 ]7) (\\(.*\\) )?... (\\(.*\\) )?.... (\\(.*\\) )?..:..:.. (\\(.*\\) )?(\\+|\\-)....( \\(.*\\))?$" {
    vacation :days 7 :addresses "test@company.com" :subject "vacation" "blablabla";
}
}
}

}

# Ausgeschlossene Adressen
if address :all :comparator "i;ascii-casemap" :is ["From", "Sender", "Resent-From"] ["noreply@example.org"]  {
    discard;
    stop;
}
```

turned into this by Roundcube when I change the name of the first rule to Abwesenheit2:

```
# Sieve Filter
# Erzeugt von Ingo (http://www.horde.org/ingo/) (30.09.2016, 16:02)

require ["vacation"];
# EDITOR Roundcube (Managesieve)
# EDITOR_VERSION 8.6
# rule:[Abwesenheit2]
if allof (not exists ["list-help","list-unsubscribe","list-subscribe","list-owner","list-post","list-archive","list-id","Mailing-List"], not header :is "precedence" ["list","bulk","junk"], not header :matches "to" "Multiple recipients of*")
{
        vacation :days 7 :addresses "test@company.com" :subject "vacation" "blablabla";
}
discard;
stop;
```

We already had quite some data loss.

We have now deleted all the old scripts, but for other customers we still need to migrate, and for other users of Roundcube it would be better to have a clean solution.

**Comment by tpokorra** [comment]
one quick and dirty workaround would be to drop all rules with action discard, that don't have a test.

in ./plugins/managesieve/lib/Roundcube/rcube_sieve_script.php, in private function _parse_text($script), section Simple commands:

             if ($rule['actions'][0]['type'] == 'discard') {
                        $rule = null;
             }

**Comment by alecpl** [comment]
Handling of nested rules is really not simple and I would rather not work on this. So, I propose a simple fix that will ignore all rules with "nested content". In such a case it would mean that the vacation rule would be ignore and the output would be:
```
# Sieve Filter
# Erzeugt von Ingo (http://www.horde.org/ingo/) (30.09.2016, 16:02)

# rule:[Ausgeschlossene Adressen]
if address :all :is ["From","Sender","Resent-From"] ["noreply@example.org"]
{
    discard;
    stop;
}
```
What do you think?

**Comment by tpokorra** [comment]
ok, I understand that the nested ifs are too complicated to convert.

Yes, dropping the rule with nested ifs makes sense. It is a lot better than the current bug :)

Thank you, @alecpl !

**Comment by alecpl** [comment]
Done.
