### ISSUE TITLE
When clicking on Compose button, there is no loading message

### ISSUE THREAD

**Issue by tpokorra** [roundcube/roundcubemail#5541]
for my automated tests, it would be useful to have a message displayed: "loading" while the compose screen builds up.
There is already the loading message for canceling a message.
And the compose screen sometimes can take longer than anticipated. If there is a message displayed, I can wait for that to disappear... (https://github.com/TBits/KolabScripts/blob/master/pySeleniumTests/helperKolabWAP.py#L687 and https://github.com/TBits/KolabScripts/blob/master/pySeleniumTests/helperKolabWAP.py#L123)

see this patch: https://github.com/TBits/KolabScripts/blob/master/kolab/patches/roundcubeComposeLoading.patch

Do you think this is something useful? Then I could prepare a pull request...

**Comment by alecpl** [comment]
I'm not sure we should display the loading message on page change. But if we did, it should be done in some general way, i.e.:
```
--- a/program/js/app.js
+++ b/program/js/app.js
@@ -8214,8 +8214,8 @@ function rcube_webmail()
 
   this.redirect = function(url, lock)
   {
-    if (lock || lock === null)
-      this.set_busy(true);
+    if (lock || lock === null || lock === undefined)
+      this.set_busy(true, 'loading');
 
     if (this.is_framed()) {
       parent.rcmail.redirect(url, lock);

```
@thomascube what do you think?

**Comment by alecpl** [comment]
Done.
