### ISSUE TITLE
Problem with attachments

### ISSUE THREAD

**Issue by MarveloRus** [roundcube/roundcubemail#5543]
Hello! I look forward to your advice. If you download an attachment through a round cube, it is cut off from 6Kb to 30KB.
Screenshots in the attachment.
When downloading mail through a mail client is not present problems.
To test updated to version 1.2.3 and change the language to en_US. Did not help.

![1](https://cloud.githubusercontent.com/assets/24265799/20743418/473cae42-b6e7-11e6-9d43-0a60d9a2b53b.jpg)
![2](https://cloud.githubusercontent.com/assets/24265799/20743683/c7faf45c-b6e8-11e6-88f0-913ed1d4d009.jpg)

**Comment by alecpl** [comment]
What IMAP server? What PHP version? Try with disabled BINARY extension (imap_disabled_caps). Try with disabled all plugins. Does it happen also for plain text or e.g. pdf files? Try testing with imap_debug to see what exactly is returned by IMAP server.

**Comment by MarveloRus** [comment]
Спасибо за ответ.!
IMAP server Communigate pro
PHP 5.5.38-1
imap_disabled_caps  - I switched mode to true, did not help.

Same with .txt.

PDF
![image](https://cloud.githubusercontent.com/assets/24265799/20744791/fd14ded6-b6ee-11e6-9537-629be9473379.png)
![image](https://cloud.githubusercontent.com/assets/24265799/20744803/05f07394-b6ef-11e6-8235-f748c74eca22.png)


Сейчас попробую imap дебаг..

**Comment by MarveloRus** [comment]
[Log.txt](https://github.com/roundcube/roundcubemail/files/621405/Log.txt)
Error no.
In the log, the correct size.
Content-Disposition: attachment;
  filename = EN.rar;
  size = 14826

I tried a different browser. Those 14820 output, where it was lost 6b

**Comment by alecpl** [comment]
That size is not used (in 1.2.3) and does not matter. Did you check the binary content of the file fetched from the imap server?

**Comment by MarveloRus** [comment]
Maybe I did not understand the question.
If i use  e-mail program or another web interface downloaded the correct file. Ie in the IMAP server does not have the problem, possible compatibility problem?

**Comment by alecpl** [comment]
Different programs may use different methods to retrieve attachment content from the IMAP server. So, some methods will work and some may reveal some bugs. That's why I'd like to find out if it's IMAP issue or Roundcube issue by checking IMAP server result for specified commands sent by Roundcube.

There's another possibility for such issues - http server compression. You may want to try with disabled compression if it's already enabled.

**Comment by Takika** [comment]
@MarveloRus : you have to set this:
`imap_disabled_caps = array('BINARY')`
I think this is the correct method to disable an IMAP capability.

**Comment by MarveloRus** [comment]
**@Takika** Thanks for the advice, but it did not help.
**@alecpl** Server on Linux Centos, webserver  Apache. Compression is disabled by default.

**Comment by alecpl** [comment]
@MarveloRus, Did you check the imap_debug after disabling the BINARY extension? Did you re-login after changing this option? I see `FETCH (BINARY[1] ~{14820}` in your log, which means it is the server fault.

**Comment by phenolog** [comment]
Hello alecpl,
I have the same issue. In the incoming mail, attachments are not fully downloaded.
----------
IMAP server Communigate pro
apache2  2.2.22
php5   5.6.30-1
compression disabled
roundcubemail-1.2.3
$config['imap_disabled_caps'] = array('BINARY');

**Comment by coobic** [comment]
@alecpl ,

Sorry for posting in older topic, but this BUG is exist in CommunigatePro 6.2.
On zip attachments - CommunigatePro return invalid file size:
Request:
````
s-inp: A0011 UID FETCH 14 (BINARY.PEEK[3.3])
````

Response:

```
s-out: * 2 FETCH (BINARY[3.3] ~{567150}\r
s-out:  UID 14)\r\nA0011 OK completed\r\n
```

**567150** is file length - which is 6 bytes less than the actual file size

Disabling BINARY Capability helps on actual verion of ROUNDCUBE.
