### ISSUE TITLE
Mouse pointer not the same on every clickable object

### ISSUE THREAD

**Issue by Supertimothy** [roundcube/roundcubemail#5545]
Hello
The mouse turns in to a hand symbol whenever hovering over a clickable object. This is not the case in mail selection window and also not on the left taskbar. 
I got feedback from my testusers: They did not understand this, it seemst this confuses the users.
I would suggest to turn the mouse into a hand symbol on every clickable object.

**Comment by alecpl** [comment]
Well, I don't think everything needs to be a hand (pointer) icon. Some elements should use arrow (default) icon. This is because our aim is to have a desktop-like application. We use consistently two rules
1. Buttons (the elements that look like buttons) and table records - default cursor,
2. Icon buttons/links - pointer icon.

What do you mean by "left taskbar"? What browser are you talking about?

**Comment by Supertimothy** [comment]
Here is a picture of what I meant.

![taskbar](https://cloud.githubusercontent.com/assets/6417486/20761843/a9167aa2-b724-11e6-964c-6eb37d717f4e.jpg)

The following picutres show that this is somehow inconsistent, in my opinion:

![case1](https://cloud.githubusercontent.com/assets/6417486/20762008/2b48b01c-b725-11e6-80c2-53e3a2a93957.jpg)

![case2](https://cloud.githubusercontent.com/assets/6417486/20762011/2faf1fa6-b725-11e6-9ebc-1e490572f7d7.jpg)

If I compare this with the github bugtracker that I'm using while writing, it seems to me that the mouse pointer changes to a hand symbol on every clickable element.

**Comment by alecpl** [comment]
Github links use a hand, but checkboxes use an arrow. You'll call this inconsistent too?

I kind of like current Roundcube solution in this area. It's meant to be a desktop-like application where we mostly use arrow pointer on interface elements and form elements, but a hand on links. In other words if an element looks like clickable use arrow, if it does not look like clickable we give a hint to the user by displaying a hand pointer. So, in some way it is consistent. You can always modify the skin or create your own. I don't think we should change this now.

@thomascube what do you think?

**Comment by rmcaninch** [comment]
Just a bit of feedback. I like the current mouse pointer. Just rolled out Roundcube here for a couple hundred users a few months ago. Haven't had anyone say they were confused by them.

**Comment by alecpl** [comment]
Wontfix.
