### ISSUE TITLE
Forwarder deleted but still working

### ISSUE THREAD

**Issue by hannahharvey** [roundcube/roundcubemail#5546]
I had a Forwarder in place to a Gmail account and although I have deleted the rule, the emails are still being forwarded to the Gmail account. Please could you advise if there is anything else I need to check?

**Comment by alecpl** [comment]
What forwarder exactly? What Roundcube version? Anyway, does not look like a Roundcube issue.

**Comment by hannahharvey** [comment]
I am using cPanel,  56.0.39 - should I go to them instead if yourselves?

**Comment by alecpl** [comment]
Yes, this is most likely a plugin that we do not support.
