### ISSUE TITLE
roundcube ignores 250 from smtp server when sending attachments

### ISSUE THREAD

**Issue by chrcoluk** [roundcube/roundcubemail#5547]
Ok so the problem presented itself like this.

Send an email with attachment to someone.
Roundcube sits there saying sending for about 3 minutes and then eventually says timed out.

I analysed both exim smtp logs and debug smtp logs from roundcube and this is what is actually happening.

The email is submitted successfully and within 1-2 seconds exim sends a 250 success back to roundcube.
Roundcube then seems to ignore the 250 and not react to it.
Eventually after 3 minutes exim times out the connection at which point roundcube prints timed out to the end user.

If a email is sent without an attachment, roundcube responds properly to the 250 and works properly.

extract from log with no attachment

> [06-Dec-2016 11:36:32 +0000]: <sdeqh3rq> Send: 
.
[06-Dec-2016 11:36:32 +0000]: <sdeqh3rq> Recv: 250 OK id=1cEE2y-000MpW-5c
[06-Dec-2016 11:36:32 +0000]: <sdeqh3rq> Send: QUIT
[06-Dec-2016 11:36:32 +0000]: <sdeqh3rq> Recv: 221 hope.chrysalisnet.org closing connection

extract from log with attachment

> nD81uAo/1Nb1nwADAL7+eugNCmVuZHN0cmVhbQ1lbmRvYm... [truncated 253490 bytes]
[06-Dec-2016 10:24:29 +0000]: <npk18mkg> Send: .
[06-Dec-2016 10:24:30 +0000]: <npk18mkg> Recv: 250 OK id=1cECvF-0002NM-CQ
[06-Dec-2016 10:25:58 +0000]: <6u26besk> Send: QUIT
[06-Dec-2016 10:25:58 +0000]: <6u26besk> Recv: 421 hope.chrysalisnet.org: SMTP command timeout - closing connection

**Comment by chrcoluk** [comment]
To add, php and apache error logs are clean, php is latest 5.6 version, apache is latest 2.4 version and roundcube is also latest.

**Comment by alecpl** [comment]
After the message is sent over SMTP it is being saved to IMAP server, that's where it "hangs" more likely. Check with imap_debug enabled.

**Comment by chrcoluk** [comment]
ok thanks, will report back.

**Comment by chrcoluk** [comment]
right so good news is you are right the error was imap side, since the dovecot log didnt show any errors, I took a educated guess as to what might be wrong and managed to fix dovecot.

The imap debug log didnt show anything useful tho, that was similar to the smtp debug log where it simply showed a successful connection, however the normal errors log started showing could not save errors, is it possible to have those errors not need imap debugging enabled?

Here is an example of one of the errors, nothing privacy exposed.

[06-Dec-2016 15:46:44 +0000]: <b1pbs5nr> IMAP Error: Could not save message in INBOX.Sent in /var/www/html/roundcubemail-1.2.3/program/steps/mail/sendmail.inc on line 648 (POST /webmail/?_task=mail&_unlock=loading1481039091755&_lang=en_US&_framed=1&_action=send)

This was logged in the errors file not the imap debug file, but it didnt log until I enabled imap debug setting.

Also interesting is that I see all the earlier tests my attachments did save.

**Comment by alecpl** [comment]
Maybe the command succeeds on the storage side, but does not return a proper result code or sth. I don't know how's that possible that it didn't log the error until you enabled the debug logging. I'm not sure there's anything we can do here.

**Comment by gnadelwartz** [comment]
hm, sounds similar to my problem #5745 , but not with atachment.
Ich can send to local users without problem, but mail to external user roundcube stalls for some time and then come back with a timeout. smtp_debug shows normal behavoir. I swichted now imap_debug on to see if its related to imap

**Comment by chrcoluk** [comment]
still broken guys just had another report
