### ISSUE TITLE
Zimbra folders

### ISSUE THREAD

**Issue by dioubernardo** [roundcube/roundcubemail#5552]
Roundcube does not show folders on a zimbra server.

In Zimbra default folders plus one extra
![image](https://cloud.githubusercontent.com/assets/3487994/20991092/863289d2-bcc3-11e6-8819-cd8dd9bcc88d.png)

In Roundcube "dashboard"
![image](https://cloud.githubusercontent.com/assets/3487994/20991145/e58545fa-bcc3-11e6-938c-79e73cdebdaa.png)

but in folder manager
![image](https://cloud.githubusercontent.com/assets/3487994/20991160/074f49d8-bcc4-11e6-993c-140a8227f7eb.png)

All roundcube settings are set to their default values.

To show the folders I changed the line
 $result = $this->conn->listMailboxes($root, $name, NULL, array('SUBSCRIBED'));
in function list_folders_subscribed_direct in file program\lib\Roundcube\rcube_imap.php
to
$result = $this->conn->listMailboxes($root, $name, NULL, array());
i

**Comment by alecpl** [comment]
I guess this is a bug in LIST-EXTENDED on Zimbra side, but to be sure I'd need imap_debug log from Roundcube. Could you provide it?
In any case, I think setting `$config['imap_disabled_caps'] = array('LIST-EXTENDED');` should also fix the issue.

**Comment by alecpl** [comment]
Or it is not a bug, but just folders aren't subscribed. Roundcube displays only subscribed folders in the "dashboard".

**Comment by dioubernardo** [comment]
Now looking better I think it is not a bug, only the folders are not "SUBSCRIBED", if I "enable" them in the control panel they are shown.

I try $config['imap_disabled_caps'] = array('LIST-EXTENDED'); but not resolved.

If I set "create_default_folders" to TRUE roundcube "enables" the folders, and the problem is "resolved".

**Comment by alecpl** [comment]
Yes, create_default_folders makes sure that default folders exist and are subscribed. But note that it will not automatically subscribe any other folder that may exist. This is a common mail client behavior to display only relevant (subscribed) folders. We have a feature request already to optionally display all folders.

**Comment by dioubernardo** [comment]
ok
