### ISSUE TITLE
Version 1.2.3 all messages won't show using Internet Explorer

### ISSUE THREAD

**Issue by zorenleo** [roundcube/roundcubemail#5553]
All messages won't show in Roundcube 1.2.3 using Internet Explorer except Google Chrome and Firefox.

**Comment by alecpl** [comment]
Which version of IE? Could you check browser console for javascript errors? Are you using any Roundcube plugins? Try to disable them.

**Comment by zorenleo** [comment]
I've used IE 9 to old. I've tried disabled plugins but still won't work. Okay I'll to check browser console for javascript errors. Thank you.

**Comment by CRtEurope** [comment]
You definately have to update your browser version. IE9 is not supported by Microsoft anymore. With IE11 everything works great.

**Comment by zorenleo** [comment]
Alright thank you for that.

**Comment by alecpl** [comment]
This is still a supported browser for Roundcube 1.2.3, so if you find the javascript error we might fix it.

**Comment by CRtEurope** [comment]
Alec, then a question to you. Why is an outdated browser still supported? Due to a high security risk I would never use an outdated browser. I would like to see that you take this into your consideration.

Cheers

**Comment by alecpl** [comment]
I'm aware of this and we actually dropped IE9 support in Roundcube 1.3, but we should not do this for stable Roundcube versions we still support, for which we claimed the IE9 is supported.

**Comment by rmcaninch** [comment]
Is the legacy_browser plugin enabled?

**Comment by troystevenhunt** [comment]
On Dec 8, 2016 8:36 AM, "rmcaninch" <notifications@github.com> wrote:

Is the legacy_browser plugin enabled?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/roundcube/roundcubemail/issues/5553#issuecomment-265770089>,
or mute the thread

**Comment by alecpl** [comment]
The plugin is not required for IE9.

**Comment by rmcaninch** [comment]
Sorry, didn't realize that. I definitely had some issues with IE9 and more recently with IE10. Just assumed it was because I didn't have the legacy plugin loaded. Already updated them to IE11 and/or Firefox so I can't really say what the issue was.
