### ISSUE TITLE
DKIM body hash verification fails

### ISSUE THREAD

**Issue by rdelia** [roundcube/roundcubemail#5558]
Hi,

DKIM body hash verification fails when roundcube is used to send messages containing pictures (HTML messages with pictures or text-only message with an image attached).

With text-only messages no problem occurs, DKIM body hash verification is successful.

Other info: I've configured Roundcube 1.1.4 to send messages via SMTP. SMTP server is localhost. I'm using  opendkim v2.10.3. The issue described above doesn't occur if I use other email clients (e.g. Thunderbird)

**Comment by alecpl** [comment]
I don't see how's that a Roundcube issue. Enable smtp_debug in Roundcube to see what Roundcube sends to the SMTP server and compare that with the message source at recipient's end.
