### ISSUE TITLE
Set message internal date on import

### ISSUE THREAD

**Issue by zorenleo** [roundcube/roundcubemail#5559]
Version 1.2.3 newly restored messages are being dated today not the actual date when it was received. I've downloaded all the messages as a backup then delete it but when I've tried to restore it the date problem begins.

**Comment by alecpl** [comment]
That is correct. Roundcube does not support extracting dates from messages and using it as an internal (received) date of the imported message. So, looks like a good feature request.

**Comment by zorenleo** [comment]
Alright, so it is also the reason why it was being duplicated if though I've tried to overwritten it when importing?

**Comment by alecpl** [comment]
There's no de-duplication mechanism, so if you import the same message many times it does not check if it already exists.

**Comment by alecpl** [comment]
Implemented. Of course it works only with mbox format which stores the date in "from line".
