### ISSUE TITLE
Problems decrypting mails

### ISSUE THREAD

**Issue by Supertimothy** [roundcube/roundcubemail#5561]
Hi 

It seems there is a problem whith decrypting mails with PHP7. I did the following:
- Created a Public an Private Key (deleted the directory in enigma/home to have a clean start)
- Took an easy password: abcdefg
- Sent encrypted mail to myself
- The password field appers
- I typed the password, but the mail can't be decrypted, the password field appears again.
- The error is: ERROR: gpg: decryption failed: No secret key

This worked for me with PHP5.4.
See attachment for more details. 

[enigma_error.txt](https://github.com/roundcube/roundcubemail/files/646684/enigma_error.txt)

**Comment by alecpl** [comment]
I don't have problems with PHP7. What Roundcube version? Are you using /vendor directory from the release package or distribiution/system packages? What version of Crypt_GPG and Console_CommandLine. Did you try to execute vendor/bin/crypt-gpg-pinentry in command line?

**Comment by Supertimothy** [comment]
This is roundcube version 1.2.0. I installed the "Complete package" and am using the vendor directory form the release package. 
Executing vendor/bin/crypt-gpg-pinentry in command line:
[root@sw92 html]# vendor/bin/crypt-gpg-pinentry
OK Crypt_GPG pinentry ready and waiting

**Comment by alecpl** [comment]
Please, update to Rouncube 1.2.3.

**Comment by Supertimothy** [comment]
Ok. Just updated to Roundcube 1.2.3. Clean installation, the only activated plugin is enigma. The same error occurs.

[13-Dec-2016 11:13:32 +0100]: <g11mars1> GPG: ERROR: gpg: problem with the agent: No pinentry
[13-Dec-2016 11:13:32 +0100]: <g11mars1> GPG: ERROR: gpg: encrypted with 2048-bit RSA key, ID 1AF243E8, created 2016-12-13
[13-Dec-2016 11:13:32 +0100]: <g11mars1> GPG: ERROR:       "vojo <vojo@mailing-test.li>"
[13-Dec-2016 11:13:32 +0100]: <g11mars1> GPG: ERROR: gpg: public key decryption failed: Operation cancelled
[13-Dec-2016 11:13:32 +0100]: <g11mars1> GPG: ERROR: gpg: decryption failed: No secret key

**Comment by alecpl** [comment]
This `problem with the agent: No pinentry` is however not the same as previous `problem with the agent: End of file`.

**Comment by Supertimothy** [comment]
Ok, I see. I just now that the password field appears and it does not accept my password - as before with roundcube 1.2.0. 
I can test if it works with php5, if that helps.

**Comment by Supertimothy** [comment]
Just switched back to php 5.4 and it works. 
Am I missing something, is it possible that there is a package not installed, which is needed?

**Comment by alecpl** [comment]
Check if your PHP7 installation has mbstring, dom, xml and posix extensions (the last one is not really required).

**Comment by Supertimothy** [comment]
All of them are available, I checked via phpinfo.

**Comment by alecpl** [comment]
Maybe in command line it's different, check `php -m`.

**Comment by Supertimothy** [comment]
[root@sw92 bin]# php -v
PHP 7.0.10 (cli) (built: Nov  2 2016 13:59:40) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

[root@sw92 bin]# php -m | grep -e dom -e mbstring -e xml -e posix
dom
libxml
mbstring
posix
xml
xmlreader
xmlwriter

Seems ok for me.

**Comment by alecpl** [comment]
System libraries may have a preference over these from /vendor. Could you check if you have PEAR, Console_CommandLine or Crypt_GPG installed in your system? Remove them.

**Comment by alecpl** [comment]
I don't understand what you said. So, there was no /usr/bin/php at all? In that case I'd expect crypt-gpg-pinentry script to fail, but you said before it works.

**Comment by alecpl** [comment]
Oh, and BTW the script uses `#! /usr/bin/env php` shebang. So, I don't really see how we could improve that on our side.

**Comment by Supertimothy** [comment]
That's correct. There is no /usr/bin/php at all. 
But I can execute gpg-pinentry:
[root@sw92 bin]# /var/www/html/vendor/bin/crypt-gpg-pinentry 
OK Crypt_GPG pinentry ready and waiting

But decryption does not work. As soon as I create the symlink in /usr/bin, decryption works.
You are probably right, seems to me quite RedHat specific. I have no idea why it does not work. The output of /usr/bin/env shows the correct path, its the first one in the list. 

/usr/bin/env | grep php
...
PATH=/opt/rh/rh-php70/root/usr/bin:/opt/rh/rh-php70/root/usr/sbin:/opt/rh/rh-php70/root/usr/bin:/opt/rh/rh-php70/root/usr/sbin:/opt/rh/rh-php70/root/usr/bin:/opt/rh/rh-php70/root/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin

However, I'm glad I found the solution. Thanks a lot!

**Comment by Supertimothy** [comment]
Yes, thats correct:
[root@sw92 bin]# sudo -u apache /usr/bin/env
PATH=/sbin:/bin:/usr/sbin:/usr/bin

**Comment by alecpl** [comment]
Thanks for confirmation. I'll add some hints about this in README file.

**Comment by xm74** [comment]
I believe this issue does not related to Bug #5462 
> root@beta:~ # php --version
> PHP 5.6.29 (cli) (built: Dec 13 2016 12:22:14)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
> root@beta:~ # whereis php
> php: /usr/local/bin/php /usr/local/man/man1/php.1.gz
> root@beta:~ # sudo -u www env
> PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
