### ISSUE TITLE
Upgrading from 1.2.0 to 1.2.3 doesn't work

### ISSUE THREAD

**Issue by lug-gh** [roundcube/roundcubemail#5562]
Hi,
I have roundcube 1.2.0 installed, i'm not really sure in which directory.

I have **/opt/www/roundcubemail/** and **/opt/www/roundcubemail-1.2.0/**
so I updated both with bin/installto.sh, this is the console output:

```
./installto.sh /opt/www/roundcubemail-1.2.0/
Upgrading from 1.2.0. Do you want to continue? (y/N)
y

Copying files to target location...done.
```

But when I repeat this step, it still shows "Upgrading from 1.2.0", so I guess the update failed?
In the Roundcube Panel its also listed as 1.2.0 (even after reboot)

**Comment by lug-gh** [comment]
Additional Information:

Ubuntu 16.04.1
PHP 7.0.8

I'm using roundcubemail with iredmail

**Comment by alecpl** [comment]
Looks like error handling could be better. Do you have rsync installed?

**Comment by lug-gh** [comment]
Yes, I have.
Shall I just copy a fresh installation of roundcube 1.2.3?
Will my configs stay?

**Comment by alecpl** [comment]
Yes. 1.2.0 -> 1.2.x is pretty safe update.

**Comment by lug-gh** [comment]
Ok it worked, ty :)

**Comment by alecpl** [comment]
Done.

**Comment by scroom** [comment]
@lug-gh @alecpl I'm experiencing the same. What have you done to make it work?

**Comment by scroom** [comment]
The iRedMail-developer ZhangHuangbin gave me a hint how to solve this issue. In PHP the system function has been disabled. I've enabled it and the update worked as expected.

**Comment by lug-gh** [comment]
@scroom as written above, i copied a fresh installation of the newest roundcube folder and replaced the old version with that files, then restarted the server.

**Comment by scroom** [comment]
@lug-gh I've meant the php function "system" in the php.ini. In my case it has been marked in the php.ini as disabled function. I've deleted it from the list and the update worked as expected:

http://www.iredmail.org/forum/post54229.html#p54229
