### ISSUE TITLE
AUTHENTICATE LOGIN not supported for IMAP

### ISSUE THREAD

**Issue by towo** [roundcube/roundcubemail#5563]
Cheers,

the Sieve management has support for using "AUTHENTICATE LOGIN"  integrated, but the generic IMAP handler does not.

A standard Dovecot with SASL-IR and LOGIN as the only auth method will not allow successful connections from Roundcube as it only tries "LOGIN", not "AUTHENTICATE LOGIN".

**Comment by alecpl** [comment]
First time see this. Why would server not allow `LOGIN` command, allowing `AUTHENTICATE LOGIN` at the same time? RFC3501 says: "While client and server implementations MUST implement the AUTHENTICATE command itself, it is not required to implement any authentication mechanisms other than the PLAIN mechanism described in [IMAP-TLS]." At the same time it says that `LOGIN` command should not be used when `LOGINDISABLED` capability was send.

So, did your server advertise both `AUTH=LOGIN` and `LOGINDISABLED` or what?

**Comment by towo** [comment]
AUTHENTICATE LOGIN and LOGIN are not the same types of beer here: AUTHENTICATE LOGIN is the SASL LOGIN mechanism (which is, more or less, the same as plaintext, at least for dovecot, and more of a Outlook compatability thing) and LOGIN is the plain IMAP LOGIN command.

Server advertisement is
`< * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=LOGIN AUTH=PLAIN] Dovecot ready.`

Which is equivalent to the dovecot defaults of:

     # cat conf.d/10-auth.conf  | grep -v '^#' | sed -e '/^$/d'
    disable_plaintext_auth = no
    auth_mechanisms = login plain

(It works when I set roundcube to use plain, of course, but it may lead to some confusion in general.)

**Comment by alecpl** [comment]
I know the difference. And I know we do not do `AUTHENTICATE LOGIN` for IMAP, but it's like this for 10 years now and no one complained. I was just curious if it's possible (and how) to configure dovecot (or any other server) to require `AUTHENTICATE LOGIN` instead of `LOGIN`. If it's not possible then there's really no issue.

**Comment by alecpl** [comment]
And what's also important, would we break anything if we just start using `AUTHENTICATE LOGIN` instead of `LOGIN`?

**Comment by alecpl** [comment]
Finally, there's no `LOGIN` in managesieve protocol that's why we use `AUTHENTICATE LOGIN` there. But for IMAP the `LOGIN` command exist.

**Comment by towo** [comment]
Possibly, it's a SUSE system - haven't had time to look into it yet and vacation time is nao, so I'll ping back when I'm back from vacation.

**Comment by alecpl** [comment]
Fixed. In your strange case imap_auth_type=LOGIN need to be used.
