### ISSUE TITLE
Upgrade 0.9.5 > 1.2.3 - Issue with "Fix "DB Write" test (#5479)"

### ISSUE THREAD

**Issue by Ubunthon** [roundcube/roundcubemail#5564]
I'm upgrading from 0.9.5 to 1.2.3.  I downloaded the software from the Roundcube webpage.  I followed the instructions.  My 'installer' webpage shows all green checkmarks --  but I can't open the webmail.  I get this error in my error log:

`[14-Dec-2016 12:39:28 -0800]: <16iu28lb> DB Error: [1054] Unknown column 'created' in 'field list' (SQL Query: INSERT INTO `session` (`sess_id`, `vars`, `ip`, `created`, `changed`) VALUES ('16iu28lbbdnalhvvoipdt3ge14', 'dGVtcHxiOjE7bGFuZ3VhZ2V8czo1OiJlbl9VUyI7dGFza3xzOjU6ImxvZ2luIjs=', '108.162.246.77', now(), now())) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 539 (GET /)`

I tracked down the code changes on this bug report:
https://github.com/ZiBiS/roundcubemail/commit/eb208824334e0de7be5c6532eab48d6fcac5fdf7

The issues seems to be with rcube_db.php starting at line 523 with the Helper method:
https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_db.php

```
    protected function handle_error($query)
    {
        $error = $this->dbh->errorInfo();
        if (empty($this->options['ignore_key_errors']) || !in_array($error[0], array('23000', '23505'))) {
            $this->db_error = true;
            $this->db_error_msg = sprintf('[%s] %s', $error[1], $error[2]);
            rcube::raise_error(array('code' => 500, 'type' => 'db',
                'line' => __LINE__, 'file' => __FILE__,
                'message' => $this->db_error_msg . " (SQL Query: $query)"
                ), true, false);
        }
        return false;
    }
```

Line #539 is this line:
  **'line' => __LINE__, 'file' => __FILE__,**

I made all the changes, but I'm still getting this error.  Now I'm not sure what to do.  I could use some assistance.

**Comment by Ubunthon** [comment]
I created the 'created' column of the SESSION table of the DB.  That seems to have made the error go away...but it's still not working.

**Comment by alecpl** [comment]
That column has been removed in git-master version only, but it's still there in 1.2.3. https://github.com/roundcube/roundcubemail/blob/release-1.2/SQL/mysql.initial.sql#L10 So, I have no idea how's that possible.

**Comment by alecpl** [comment]
Invalid.
