### ISSUE TITLE
Replies to email with blocked images get a mysterious blocked.gif attachment

### ISSUE THREAD

**Issue by resolutecake** [roundcube/roundcubemail#5567]
If a message with remote images is received, those are blocked and a yellow banner is displayed “To protect your privacy, remote images are blocked in this message.”

BUG
if Reply is clicked on such message, the reply has a mysterious 118 byte blocked.gif image attached, which is the pink square displayed at remote images location

EXPECTED
The reply to have no attachments

Maybe this isn’t a bug…

blocked.gif (118 B)
- is the pink image that replaces blocked remote images

Package: roundcube
Version: 1.2.1+dfsg.1-2

**Comment by alecpl** [comment]
This is not a bug. If there are "blocked images" they will be replaced by the pink image. You have to allow remote images in mail preview first, then in compose you will see no pink image attached.

**Comment by mvorisek** [comment]
What about not attaching the `blocked.gif` and inlining the image instead?

**Comment by alecpl** [comment]
Would be possible, but what's the problem with attaching it?

**Comment by mvorisek** [comment]
The `blocked.gif` attachment is at least confusing:
* confuse people as when email has an attachment, almost every email client indicates that the email has at least one attachment
* some people try to unblock the attachment as they are used to unblock external images
* some people do not understand at all and they may possible open this tech GitHub thread

**Comment by alecpl** [comment]
The attachment is marked as inline. Roundcube and Thunderbird will not display the attachment icon, nor display it on the attachments list. I didn't try other clients. Some of your points might be valid, but I don't think it's a big issue. Your second point can't be solved with inlining the image into the html code.

**Comment by mvorisek** [comment]
I meant primary the 2nd point as some people try to unlock the `blocked.gif` attachment as they do not expect it as it is RC specific. I got this reported several times as it seems that even big players like the biggest one here in the Czech Republic - Seznam.cz - does not hide it and shows it as a regular image attachment.

Does RC supports images with inlined data (src with data uri) and is PR with it welcomed?

**Comment by alecpl** [comment]
Roundcube supports data uris, but we don't use them in sent mail for interoperability. I don't know, maybe it could change.
