### ISSUE TITLE
mailboxes content not displyed when 'window.name' blocked

### ISSUE THREAD

**Issue by cm-mc** [roundcube/roundcubemail#5568]
If `Protect window.name` (Options > Script Injection Options) is set in [https://github.com/dillbyrne/random-agent-spoofer](url) mailboxes content is not displayed; if it's not set, content is displayed.

**Comment by alecpl** [comment]
I don't know how that works, but this is not Roundcube issue. Looks like this feature of random-agent-spoofer is broken anyway: https://github.com/dillbyrne/random-agent-spoofer/issues/468.
