### ISSUE TITLE
Monospace font for plain text messages

### ISSUE THREAD

**Issue by fturco** [roundcube/roundcubemail#5571]
I can't find an option in Roundcube for using a monospace (fixed width) font when displaying or composing plain text messages. In my opinion variable width fonts should be used only for HTML messages. What do you think?

**Comment by alecpl** [comment]
Works for me. The `font-family: monospace` is set in css rules. What version, what browser? Try with disabled all plugins. Provide a screenshot.

**Comment by fturco** [comment]
![roundcube](https://cloud.githubusercontent.com/assets/5459866/21478612/89b537b0-cb4d-11e6-8a10-1465ad245e2c.png)

My browser is Firefox 50.1.0. My OS is Gentoo Linux.

I don't know how to retrieve Roundcube version number. I have not installed it myself. I'm using the Posteo e-mail service.

**Comment by alecpl** [comment]
So, you should ask Posteo. It looks like they modified the skin and it's a bug in that modification.
