### ISSUE TITLE
Advanced search is broken with several address books

### ISSUE THREAD

**Issue by pyhalov** [roundcube/roundcubemail#5572]
I have roundcube 1.2.3 installed. After updating from previous version (I don't remember exactly which one), advanced search seems to be broken.

I have ldap address book configured and default sql address book for personal addresses. When working with address book I run 'Advanced Search' without selecting anything in 'Groups', contact is found in ldap catalog, but when I select it, in 'Contact properties' I see:
Address Book: Personal Addresses (not ldap catalog) and error 'The requested contact was not found'.
In error log I can see:
```
<k0oc94s5> DB Error: [7] ERROR:  invalid input syntax for integer: "Q049TWVyemxpYWtvdiBWYXNpbGlpIEFuYXRvbCdldmljaCxPVT1TRkVEVSxEQz1hZCxEQz1zZmVkdSxEQz1ydQ-SFEDU"
LINE 1: SELECT * FROM "contacts" WHERE "contact_id" = 'Q049TWVyemxpY...
                                                      ^ (SQL Query: SELECT * FROM "contacts" WHERE "contact_id" = 'Q049TWVyemxpYWtvdiBWYXNpbGlpIEFuYXRvbCdldmljaCxPVT1TRkVEVSxEQz1hZCxEQz1zZmVkdSxEQz1ydQ-SFEDU' AND "user_id" = '421' AND "del" <> 1) in /http/roundcube/program/lib/Roundcube/rcube_db.php on line 539 (GET /?_task=addressbook&_framed=1&_action=show&_source=0&_cid=Q049TWVyemxpYWtvdiBWYXNpbGlpIEFuYXRvbCdldmljaCxPVT1TRkVEVSxEQz1hZCxEQz1zZmVkdSxEQz1ydQ-SFEDU)
```

But when I select global address book in 'Groups' field, advanced search works as expected. It seems after finding contact, advanced search doesn't remember where it came from and tries to search for detailed information in wrong address book.

**Comment by alecpl** [comment]
Confirmed in git-master. Also, it is not possible to save the search.
