### ISSUE TITLE
Make 'imap_cache' work with Redis

### ISSUE THREAD

**Issue by tomsommer** [roundcube/roundcubemail#5574]
It would be nice if `imap_cache` (or `rcube_cache_shared`) could work with Redis.

**Comment by alecpl** [comment]
Extending rcube_cache and rcube_cache_shared classes with Redis support should be pretty simple. See rcube_session_redis for some examples. Pull requests are most welcome.

**Comment by alecpl** [comment]
Implemented in git-master.

**Comment by tomsommer** [comment]
As far as I can see, rcube_imap_cache only supports db still?

**Comment by alecpl** [comment]
Yes, that is controlled by `messages_cache` option, the cache from `imap_cache` supports redis.
