### ISSUE TITLE
pl_PL translation for managesieve plugin

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#5575]
pl_PL translation for managesieve plugin is wrong

AS IS:
$messages['deactivated'] = 'Filtr(y) włączono pomyślnie.';
$messages['activated'] = 'Filtr(y) wyłączono pomyślnie.';

TO BE:
$messages['deactivated'] = 'Filtr(y) wyłączono pomyślnie.';
$messages['activated'] = 'Filtr(y) włączono pomyślnie.';

**Comment by alecpl** [comment]
Fixed on Transifex. Dzięki.
