### ISSUE TITLE
preview pane issues when using hardened apache ssl settings

### ISSUE THREAD

**Issue by aw1604** [roundcube/roundcubemail#5576]
Hello,

I just applied a set of recommended apache ssl settings (https://cipherli.st) and noticed that the preview pane stopped working. I was able to track this down to this two config lines in ssl.conf - when enabled, all ajax stuff (preview pane, but more painful also the settings) stops working.

ssl.conf / from Cipherli.st:

Header always set X-Frame-Options DENY
Header always set X-Content-Type-Options nosniff

Can anybody please try to reproduce / test this issue ?

Best Rgds,
aw1604

**Comment by alecpl** [comment]
`X-Frame-Options DENY` disables possibility to use `iframe` elements on a page and that's why it's incompatible with Roundcube.

**Comment by aw1604** [comment]
ok, thanks
