### ISSUE TITLE
Prerequisites check is not checking for php imap capability

### ISSUE THREAD

**Issue by schurlix** [roundcube/roundcubemail#5577]
It took me a long time fiddling, the installer did not complain.
Please add checks.
thanks,

   George

**Comment by alecpl** [comment]
We do not use IMAP extension. What exactly do you mean?

**Comment by CRtEurope** [comment]
I guess he means php-imap

**Comment by alecpl** [comment]
We don't use php-imap, maybe some plugin? I'm closing this.

**Comment by schurlix** [comment]
Actually on my system the imap functionality is installed (or not, in my case) as a separate package.
It was missing (also a bug in the FreeBSD port).

The roundcube installer (nor the logs, nothing in fact (!!!) did not in any way complain about not available imap_* functionality in my php setup. Everything had the green OK.

When tcpdumping the webserver's path to the imap server I was puzzled about not seeing a single packet.

**Comment by alecpl** [comment]
I said, Roundcube core and core plugins does not use any of imap_* functions.

**Comment by schurlix** [comment]
This is interesting, as installing the php_imap packages immediately solved my problem.
