### ISSUE TITLE
PHP Error: Request security check failed (GET /?_task=logout)

### ISSUE THREAD

**Issue by asterismo** [roundcube/roundcubemail#5579]
I did a 'git pull' of master 5 min ago and i can login into my mail, but cannot see any mail, only empty folders, when trying to logout, i get this message in the browser:

---------------------------------------
HA FALLADO LA SOLICITUD DE COMPROBACIÓN
Por su seguridad, se ha protegido el acceso a este recurso contra CSRF.
Si lee esto probablemente no ha cerrado la sesión antes de dejar la aplicación web.

Ahora hace falta interacción humana para continuar.

Por favor, póngase en contacto con el administrador de su servidor.
--------------------------------------

My log error is this:

PHP Error: Request security check failed (GET /?_task=logout)

**Comment by asterismo** [comment]
pulled from f351b487711a128de8c52f837be26cea0e865bfe to f78e2a43674722e132df2fa2bcd4765aaa20d003 pull: Fast-forward

**Comment by asterismo** [comment]
I just wiped out and cloned again and still the same issue.

**Comment by alecpl** [comment]
I cannot confirm. Any plugins or modified skin?

**Comment by asterismo** [comment]
I commented the whole plugin section, and commented the larry skin,i got the same. Maybe php version? i'm running Debian 8 Jessie and PHP 5.6.29-0+deb8u1

**Comment by asterismo** [comment]
nginx logges this:

2017/01/04 14:44:12 [error] 1627#0: *471406 open() "/var/www/html/mail/program/js/jquery.min.js" failed (2: No such file or directory), client: 127.0.0.1, server: mail.undernet.uy, request: "GET /program/js/jquery.min.js HTTP/1.1", host: "mail.undernet.uy", referrer: "https://mail.undernet.uy/?_task=logout"
2017/01/04 14:44:13 [error] 1627#0: *471406 open() "/var/www/html/mail/program/js/jquery.min.js" failed (2: No such file or directory), client: 127.0.0.1, server: mail.undernet.uy, request: "GET /program/js/jquery.min.js HTTP/1.1", host: "mail.undernet.uy", referrer: "https://mail.undernet.uy/?_task=logout"

**Comment by alecpl** [comment]
You have to install javascript dependencies. See INSTALL and bin/install-jsdeps.sh. Though, missing js files should not cause such issues. This looks strange.

**Comment by asterismo** [comment]
@alecpl Yes, that did the trick. Closing the issue. Thanks.

**Comment by reubenfarrelly** [comment]
I've just run into this issue as well - exact same symptoms and exact same fix.  In my case it was an upgrade from 1.2 to 1.3-git.  This was quite tricky to get to the bottom of so could there be something a little more explicit logged either on screen or in logs if these files are missing?

**Comment by Strubbl** [comment]
Same here, i tried to use composer for installing dependencies, but it did not work. The script in bin/ worked.

**Comment by tomperys** [comment]
Same issue but I have no bin/install-jsdeps.sh file...
