### ISSUE TITLE
Cannot import GPG secret key

### ISSUE THREAD

**Issue by asterismo** [roundcube/roundcubemail#5581]
i get this in log:

PHP Fatal error:  Call to undefined method Crypt_GPG_SubKey::usage() in /var/www/html/mail/plugins/enigma/lib/enigma_driver_gnupg.php on line 495

I'm using Debian 8 jessie and PHP 5.6.29-0+deb8u1

**Comment by alecpl** [comment]
You need more recent Crypt_GPG package.

**Comment by asterismo** [comment]
Is there anyway to upgrade this package in Debian stable? What version of which package is needed?

**Comment by rmcaninch** [comment]
Not with a stable package. Have to install it manually.

**Comment by asterismo** [comment]
And how i do that? cannot find the /vendor folder. Where do i download it? Do i have to declare the lib path manually somewhere? Thanks.

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/releases/download/1.2.3/roundcubemail-1.2.3-complete.tar.gz
