### ISSUE TITLE
Managesieve: Support 'subaddress' extension (RFC5233)

### ISSUE THREAD

**Issue by internethering** [roundcube/roundcubemail#5582]
see https://tools.ietf.org/html/rfc5233

It's a easy way to filter mails: example+github@example.org, example+lkml@example.org:

```
require ["envelope","fileinto","subaddress"];
if envelope :detail "to" "github"
{
	fileinto "Github";
}
if envelope :detail "to" "lkml"
{
	fileinto "LinuxKernelML";
}
```

**Comment by alecpl** [comment]
The subaddress extension is supported since version 5.0 of the plugin, i.e. for more than five years.
