### ISSUE TITLE
Privacy Leak Bug

### ISSUE THREAD

**Issue by mikecardwell** [roundcube/roundcubemail#5583]
When viewing an email in Roundcube as HTML, remote content is blocked and there is a message saying:

> To protect your privacy, remote images are blocked in this message. Display images

However, remote content loaded from input tags of type "image" *is* loaded, without even clicking "Display images". I.e:

```html
<input type="image" src="http://TRACKING_URL/">
```

I discovered this issue when testing two unrelated Roundcube installations using https://www.emailprivacytester.com (a website I built and run myself)

One of the installations also loads autoplay video tag content under the same circumstances. I am not sure why the other doesn't. I.e:

```html
<video autoplay="true" src="http://TRACKING_URL/"></video>
```

Typically I would report an issue like this using non-public channels, however you don't seem to have a published mechanism for reporting security issues privately. I signed up for your dev mailing list and sent an email there to ask how to report it, but the message bounced. I would suggest you set up a dedicated address for reporting security issues, and have a dedicated webpage on your website detailing how to report them, preferably with a PGP key.

**Comment by alecpl** [comment]
Fixed.
