### ISSUE TITLE
Can not add new email address

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5587]
Using the latest master branch. When adding a new email address to an exising contact and click save noting will be saved and get the following error in the log file:

```
Stack trace:
#0 program/steps/addressbook/edit.inc(189): rcmail_contact_form(Array, Array, Array)
#1 program/include/rcmail_output_html.php(1156): rcmail_contact_editform(Array)
#2 [internal function]: rcmail_output_html->xml_command(Array)
#3 program/include/rcmail_output_html.php(1022): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...')
#4 program/include/rcmail_output_html.php(635): rcmail_output_html->parse_xml('<roundcube:obje...')
#5 program/include/rcmail_output_html.php(489): rcmail_output_html->parse('contactedit', false)
#6 program/steps/addressbook/edit.inc(79): rcma in program/steps/addressbook/func.inc on line 675
```

**Comment by alecpl** [comment]
Where is the error?

**Comment by CRtEurope** [comment]
![save](https://cloud.githubusercontent.com/assets/16518395/21782411/a18330c4-d6b3-11e6-9db3-0652729f764b.jpg)

**Comment by alecpl** [comment]
It works for me. You use built-in sql addressbook or some plugin? You provided a stack trace, but no error message.

**Comment by CRtEurope** [comment]
I use the built-in addressbook. Did not about a plugin for it... That's the only lines in the error.log I get.

**Comment by CRtEurope** [comment]
Maybe it is important to say that I use PHP 7.1.0-5

**Comment by alecpl** [comment]
Maybe, but still I need precise error message.

**Comment by CRtEurope** [comment]
which debug level?

**Comment by alecpl** [comment]
I think I might know what's the problem. Find line https://github.com/roundcube/roundcubemail/blob/release-1.2/program/steps/addressbook/func.inc#L674 and replace it with `$values = array('');`

**Comment by CRtEurope** [comment]
Changed and it is working. Thanks Alec.

Please apply the in the master branch.

Thanks

**Comment by alecpl** [comment]
Fixed. This BC break of PHP 7.1 is really annoying. And as you see there's a bug in the error message. "rcma" should be a user-understandable message. Probably something to request on bugs.php.net.
