### ISSUE TITLE
Add Extended TLD's

### ISSUE THREAD

**Issue by tdavidscott3** [roundcube/roundcubemail#5588]
I've tried to make a branch to perform a Pull Request with the modifications for review, however I do not have access, so I'll drop the modifications here.

"Adjusting files to add inclusive namespacing. This modification will allow the use of numbers in TLD's; such as 2legit2quit. This was performed in a production environment using email.ucann2 as the domain name"
```
dscott@dscott-Aspire-Z5610:~/git/roundcube$ git show
commit 29632d064e62bea06ec10883a6697f65f5ef8593
Author: David Scott <tdavid.scott3@gmail.com>
Date:   Tue Jan 10 08:13:14 2017 -0500

    Adjusting files to add inclusive namespacing. This modification will allow the use of numbers in TLD's; such as 2legit2quit. This was performed in a production envirnoment using email.ucann2 as the domain name

diff --git a/program/js/common.js b/program/js/common.js
index 2abc594..e729b02 100644
--- a/program/js/common.js
+++ b/program/js/common.js
@@ -427,7 +427,7 @@ function rcube_check_email(input, inline, count)
       //domain_literal = '\\x5b('+dtext+'|'+quoted_pair+')*\\x5d',
       //sub_domain = '('+atom+'|'+domain_literal+')',
       // allow punycode/unicode top-level domain
-      domain = '(('+ip_addr+')|(([^@\\x2e]+\\x2e)+([^\\x00-\\x40\\x5b-\\x60\\x7b-\\x7f]{2,}|xn--[a-z0-9]{2,})))',
+      domain = '(('+ip_addr+')|(([^@\\x2e]+\\x2e)+([^\\x00-\\x40\\x5b-\\x60\\x7b-\\x7f]{2,}|[a-z0-9]{2,})))',
       // ICANN e-mail test (http://idn.icann.org/E-mail_test)
       icann_domains = [
         '\\u0645\\u062b\\u0627\\u0644\\x2e\\u0625\\u062e\\u062a\\u0628\\u0627\\u0631',
diff --git a/program/lib/Roundcube/rcube_utils.php b/program/lib/Roundcube/rcube_utils.php
index d7d7c96..4e1ef44 100644
--- a/program/lib/Roundcube/rcube_utils.php
+++ b/program/lib/Roundcube/rcube_utils.php
@@ -110,7 +110,7 @@ class rcube_utils
 
             // last domain part
             $last_part = array_pop($domain_array);
-            if (strpos($last_part, 'xn--') !== 0 && preg_match('/[^a-zA-Z]/', $last_part)) {
+            if (strpos($last_part, 'xn--') !== 0 && preg_match('/[^a-zA-Z0-9]/', $last_part)) {
                 return false;
             }

```

**Comment by CRtEurope** [comment]
There is a pull request. https://github.com/roundcube/roundcubemail/pull/5589

**Comment by thomascube** [comment]
@CRtEurope please see the comments in that pull request. We're willing to merge it if you can provide a clean and functional PR with the changes requested by this ticket.

**Comment by alecpl** [comment]
I couldn't find any RFC or other specification that explains format of "extended TLD". Though I'm not sure about this change. Still, relaxing the domain validation might not be a bad idea. Should a mail client be responsible for very strict format validation of email addresses? Probably not.

**Comment by CRtEurope** [comment]
It is designed for companies and/or private networks that do not use ICANN TLD's. An RFC for this method does not exist indeed. Our company and my own mail server use this patch as well to send emails in a secure way.
If you want I can provide a new PR.

**Comment by alecpl** [comment]
Fixed.
