### ISSUE TITLE
CC: headers not formatted properly.

### ISSUE THREAD

**Issue by renaudallard** [roundcube/roundcubemail#5591]
Hello,

Some users reported me emails which were refused because of bad headers. They got back a reply from their mailer daemon with the full headers, and from what I can see the display name is not quoted in the headers. This is very problematic if the display name contains the "," sign, which is used to separate email addresses.
For example: `"John, L, Doe" <john.l.doe@example.com>`
appears in the headers as: `John, L, Doe <john.l.doe@example.com>`
Which is refused by the remote MTA because neither John nor L is a valid email address.
The version of roundcube used is 1.2.3.
Unfortunately, I don't know exactly how the contact is stored.

**Comment by alecpl** [comment]
Do you have smtp_server set or not? Any plugins?

**Comment by renaudallard** [comment]
I don't know the exact configuration, I am reporting this on behalf of someone else.
Is this kind of behavior normal or could it be a local bug?

**Comment by alecpl** [comment]
I can't reproduce. Maybe that's one of corner cases when php mail() function does not work properly (which is used when smtp_server is not set in config).

**Comment by renaudallard** [comment]
OK, I have found multiple reports of this problem when using php mail(). The display name must be escape quoted. Maybe it could be interesting to add this edge case in roundcube tough.

**Comment by alecpl** [comment]
We removed mail() function support in Roundcube 1.3. So, not really interesting. If no one provides a patch we'll probably close the ticket soon.

**Comment by renaudallard** [comment]
If it's going to be removed, it's indeed not that useful to waste time on this anymore.
