### ISSUE TITLE
jQuery missing on master branch?

### ISSUE THREAD

**Issue by binarykitchen** [roundcube/roundcubemail#5592]
Just pulled from master and seeing a 404 in the browser when loading `https://mysite.com/program/js/jquery.min.js`

**Comment by alecpl** [comment]
We removed js dependencies from the repo. Now you have to run bin/install-jsdeps.sh script.

**Comment by binarykitchen** [comment]
ah, each time after a git pull?

**Comment by alecpl** [comment]
No, but if we bump up dependencies versions you'll have to do this. Note that executing this script for the second time will be fast as it caches the downloaded files.

**Comment by binarykitchen** [comment]
i see, sweet as - are there any other scripts i should run after a git pull, in general?

**Comment by alecpl** [comment]
Probably `composer update` and bin/update.sh. All of them are needed only when some dependency or database structure changes.

**Comment by binarykitchen** [comment]
ok - i think a single entrance to update everything would be good. then the above issue wouldn't have been asked ...

**Comment by evs-xsarus** [comment]
@alecpl it might be an option to install jQuery using composer: https://stackoverflow.com/a/16974088/1025437
