### ISSUE TITLE
unable to add attachment

### ISSUE THREAD

**Issue by gvermeiren** [roundcube/roundcubemail#5594]
I'm unable to add attachments to my emails, all the rest is working fine. In the logs I get the following error.

> PHP Warning:  move_uploaded_file(): Unable to move '/tmp/phpMf9eAO' to '/home/***/public_html/mail/temp/rcmAttmntXgu9XJ' in /home/***/public_html/mail/plugins/filesystem_attachments/filesystem_attachments.php on line 59

What did I do wrong?

Thanks already

**Comment by alecpl** [comment]
Looks like something's wrong with your file system.

**Comment by CRtEurope** [comment]
Looks like wrong permission settings
