### ISSUE TITLE
How to write about the password plug-in configuration of SQL statements

### ISSUE THREAD

**Issue by lilongen1** [roundcube/roundcubemail#5595]
I ask, what I use is 1.2.3 version, want to use the password plug-ins, but configuration stumped by SQL statements. I don't know which table is to save the password.
So I wrote:
## The UPDATE  table SET password = % c WHERE the username = % u
What should be on the table in the sentence? Another wrote SQL sentence right?
thanks!

<img src="https://raw.githubusercontent.com/lilongen1/ziluopao/master/roundcube%20sql.png"/>

**Comment by rmcaninch** [comment]
Roundcube does not store the password. The SQL driver would be used, for example, on a SQL backend that the IMAP server is configured to use. Check what your IMAP server uses for its user authentication.
