### ISSUE TITLE
Roundecube webmail - lost the function to sort emails

### ISSUE THREAD

**Issue by Gclubber72** [roundcube/roundcubemail#5596]
I use Roundcube Webmail hosted by TSO Host who tell me they use version 0.9.

In the last week or two I have noticed that emails are not in date order and I can no longer sort emails, by 'date' or 'from' or 'to'. 

I used to be able to click the words 'date' 'from' 'to' at the top of the columns and this would sort them. I can't do this now.

TSO say they don't know what the problem is.

I have also tried changing the preferences in the 'list options' icon to sort by ascending, descending etc but that just reverses the order, rather than sorting them correctly.

Can anyone help?

**Comment by alecpl** [comment]
We do not support this old version. It might be also an IMAP server issue.
