### ISSUE TITLE
Password plug-in can modify the stored password but can't enable new password problem

### ISSUE THREAD

**Issue by lilongen1** [roundcube/roundcubemail#5597]
Password plug-in can modify the stored password, but after the cancellation of the user, with the newly saved password can not login, this is what reason!
New password may not save in, but if there are no saved successfully, supposedly old password can be used, but also can't use. Of course, when I was in save the new password, suggests that saved successfully.
thanks!

**Comment by alecpl** [comment]
I have no idea what are you talking about. This probably has nothing to do with password plugin. COuld you be more precise. What driver are you suing? What are the steps to reproduce the issue?

**Comment by lilongen1** [comment]
I made A contrast in the database, established A, B two E-mail, then A password into A and B. The observation database that the encryption method using password plug-in and postfix encrypted in a different way.
, of course, it's certainly not the plug-in question, where is my Settings has a problem, but I have a problem
I use in the postfix is CRAM - MD5 encryption, in the plug-in configuration file in this way, I was set up in the right place?
