### ISSUE TITLE
Installer doesn't copy jsdeps.json

### ISSUE THREAD

**Issue by dapphp** [roundcube/roundcubemail#5598]
Testing an upgrade from 1.2.3 to 1.3-beta, I noticed that bin/installto.sh doesn't copy jsdeps.json to the target.

Since this was a new migration, I followed the instructions [here](https://roundcube.net/news/2017/01/05/roundcube-webmail-1.3-beta-out-now) and the first time running that it told me it couldn't find that file.  Only took a moment to realize it wasn't copied by the script and I had to copy it manually.

installto.sh:64

`foreach (array('index.php','.htaccess','config/defaults.inc.php','composer.json-dist','CHANGELOG','README.md','UPGRADING','LICENSE','INSTALL') as $file) {`

Oh yeah, and also, when doing an install on a VM, I got an error running that, something along the lines of "sh: -o does not exist".

Turned out it was because unzip was not installed.  So install-jsdeps.sh might want to have a check relating to `$UNZIP = trim(`which unzip`);` to make sure it actually found something.

EDIT:  Otherwise, very awesome work so far.  1.3 looks great!

**Comment by alecpl** [comment]
Fixed.
