### ISSUE TITLE
Missing information (send-to) in 3-columns view

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#5601]
actually you can see directly to which mail-adress an e-mail was send. 
in 3-columns-view you have to open the mail in a new window to see the receipient. 

if you are using multiple identities or getting mails in bcc the direct information would be nice.

**Comment by alecpl** [comment]
I don't think we should add that. The record layout in widescreen mode is limited for obvious reasons. We can't put there all data available in desktop (wide table) mode.

**Comment by thomascube** [comment]
Agreed with @alecpl
