### ISSUE TITLE
Logs errors

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [roundcube/roundcubemail#5602]
Versions: roundcubemail-1.2.3

[12-Jan-2017 11:39:39 +0100]: <1dthqrtp> Warning: Call to deprecated function Q(); See bc.inc for replacement
[12-Jan-2017 11:51:56 +0100]: <1dthqrtp> Warning: Call to deprecated function get_input_value(); See bc.inc for replacement

**Comment by alecpl** [comment]
I guess you're using some external plugins that use deprecated Roundcube functions. Is that right?

**Comment by alecpl** [comment]
Anyway, not a bug.

**Comment by mariuszkrzaczkowski** [comment]
This is a bug, see:
https://github.com/roundcube/roundcubemail/blob/release-1.2/program/include/bc.php#L116
https://github.com/roundcube/roundcubemail/blob/release-1.2/program/include/bc.php#L104
Error occurs in php 7.x

**Comment by alecpl** [comment]
PHP version is irrelevant. It's not PHP warning, but Roundcube warning. I know the functions are there. The question was what is using these deprecated functions?

**Comment by mariuszkrzaczkowski** [comment]
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/acl/acl.php#L192
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/acl/acl.php#L216
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/archive/archive.php#L276
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/enigma/lib/enigma_ui.php#L450
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/enigma/lib/enigma_ui.php#L565
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/enigma/lib/enigma_ui.php#L655
https://github.com/roundcube/roundcubemail/blob/release-1.2/plugins/enigma/lib/enigma_ui.php#L663

**Comment by alecpl** [comment]
Hmm... but you know the difference between rcube::Q() and Q()?
