### ISSUE TITLE
group-expand limited to 1000 in code

### ISSUE THREAD

**Issue by nodo50** [roundcube/roundcubemail#5604]
Hi, I detected a issue using groups of addresses bigger than 1000 members. When I compose a new message and click in the button BCC+ only around 1000 addresses are added to BCC field.
I tested with groups of 1600 and 3000 addresses.

Looking for the cause I found in the code a value hardcoded is causing the issue.

File: program/steps/mail/autocomplete.inc
Line number 27:

   $abook->set_pagesize(1000);  // TODO: limit number of group members by config

The issue is solved when I increasing the value.
 
Could you change the hardcored value to a config option to avoid the change will be overwrited on next RC update?

I'm using RC 1.2.3. In my config/config.inc.php I have 

$config['max_pagesize'] = 2500;

I'm using the default values for max recipients and max group members:

$config['max_recipients'] = 0;
$config['max_group_members'] = 0;

Thanks in advance.

**Comment by alecpl** [comment]
I suppose we should use min($config['max_recipients'], $config['max_group_members']) and if this is 0 fallback to 9999.

**Comment by alecpl** [comment]
Hmm... That would silently limit the list, so it's not a good solution. I suppose setting the pagelimit to 9999 is the only option. Usability of such a big group is another story.

**Comment by alecpl** [comment]
Fixed.

**Comment by nodo50** [comment]
Hi, the limit of 9999 is reasonable. We always suggest our users to use a mailing list services for that amount of recipients. Thanks
