### ISSUE TITLE
widescreen looks strange

### ISSUE THREAD

**Issue by roccolord** [roundcube/roundcubemail#5605]
The new widescreen is great but  looks a little strange see [link](http://x0.se/Selection_001.png).

Also I can't set is as default have to set it everytime I login.

**Comment by alecpl** [comment]
Not for me. What browser (and version)? Do you use any plugins? Try without plugins.

**Comment by roccolord** [comment]
Chrome Linux latest. And Firefox Linux latest also. You mean browser
plugins?

Den lör 14 jan. 2017 10:45Aleksander Machniak <notifications@github.com>
skrev:

**Comment by alecpl** [comment]
Browser or Roundcube plugins.

**Comment by roccolord** [comment]
The layout issue was resolved by unchecking "read status" column. Now the only problem is that the widescreen view is lost on reload, or clicking roundcube logo.

**Comment by alecpl** [comment]
Still I can't reproduce.

**Comment by roccolord** [comment]
I can't either any longer. I balme it on opcache. really strange.

lör 14 jan. 2017 kl 17:14 skrev Aleksander Machniak <
notifications@github.com>:
