### ISSUE TITLE
Cannot close address auto-completion popup with group matches

### ISSUE THREAD

**Issue by hfp** [roundcube/roundcubemail#5606]
For instance, typing a To-address shows a popup of the suggested addresses (which is expected). For me the popup always stays open, and it cannot be closed by clicking outside of the popup (there is also no obvious key to close it; is there such a key?). The real problem is however, the final list remains with only contact groups in it (group names are perhaps matched due to one member of that group matching?). In any case, using the Tab-key fills out the To-address with the e-mails of all members of the (unwanted) group match. This is very annoying and dangerous as it might send a message to a huge number of recipients.

How to disable auto-completion as a workaround for the above behavior?
How to cancel the result of the auto-completion popup (i.e., close it)?
Is there a way to avoid matching groups?

**Comment by alecpl** [comment]
Esc key in the input field should close the popup, but I agree that mouse click anywhere on the page should also hide it.

**Comment by alecpl** [comment]
Fixed. Now also click outside of the autocomplete input as well as Tab key will close the popup.
