### ISSUE TITLE
Error PHP Warning:  date(): It is not safe to rely on the system's timezone settings. 

### ISSUE THREAD

**Issue by mediaiberia** [roundcube/roundcubemail#5607]
This error happens in: 
/program/lib/Roundcube/rcube_session.php on line 630

The problem arises because the time zone is not specified in the PHP.ini file

To solve it there are two options:
A) Put the timezone value in PHP.ini
B) Correct the source of ROUNDCUBE so that it supports a default value. This should be incorporated by the developers in the original source:
BEFORE
        // fallback to server's timezone
        return date_default_timezone_get();

WRITE
		if( ! ini_get('date.timezone') )
{			   date_default_timezone_set('GMT');
		}

**Comment by alecpl** [comment]
Not Roundcube issue. There are similar warnings when the timezone in config is invalid. I think in both cases it's up to the user to set correct timezone in php.ini.
