### ISSUE TITLE
Misleading translation when canceling a draft

### ISSUE THREAD

**Issue by dapphp** [roundcube/roundcubemail#5610]
It looks like canceling a saved draft shows the same message as when canceling an unsent mail message.

This can be a bit misleading as we got a report that a person thought their existing draft might be deleted if they accepted the prompt.

It looks like both screens reference `messages.inc:$messages['notsentwarning']`.

Maybe in an upcoming release we could see a separate translation string for that?

In English, perhaps something to the effect of, `Draft has not been sent.  Do you want to discard your changes?` as opposed to `Message has not been sent. Do you want to discard your message?`

Thanks!

**Comment by alecpl** [comment]
I suppose we could do this.

**Comment by alecpl** [comment]
Every message would become a draft after you click Save (or on autosave action). I'm curious if we could handle all cases with one message. E.g. "There are unsaved changes in the message. Do you want to discard them?"

Thunderbird displays the same "Message has not been sent. Do you want to save the message in your drafts folder (Drafts)?" message in all cases, so imho, it's not perfect either.

**Comment by thomascube** [comment]
I'd go with @dapphp's suggestions although with autosave enabled, it's very likely that users may only see the one message about draft not sent. Anyway it's probably more clear about the consequences of leaving the compose step.

**Comment by alecpl** [comment]
That's my point, to not use two messages. Is my message proposition not clear enough? I think it's better to warn about "unsaved changes" and that they could be lost instead of "state of the message/draft".

**Comment by thomascube** [comment]
Indeed. What about `The message has not been sent and has unsaved changes. Do you want to discard your changes?`

**Comment by dapphp** [comment]
Sorry for going dark on this one.  I appreciate you guys taking a look.  I'm all for keeping it simple by not adding a new message to the translations.  I think the last suggestion from @thomascube clearly describes what the cancel action would do for both a previously saved draft and a new message.

**Comment by alecpl** [comment]
Fixed.
