### ISSUE TITLE
widescreen view + search + threads issue

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#5613]
Hi.
I use 1.3-beta without plugins. Widescreen view and threads.

When I search for messages in the inbox there is only first message from thread displayed on the results list.
This small button to expand thread is missing.
Issue only occurs in widescreen layout.

![rc](https://cloud.githubusercontent.com/assets/24810145/22065727/ccf4990a-dd89-11e6-87fc-3f5708eafbbd.jpg)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
