### ISSUE TITLE
Skin image files with incorrect extention are not shown in IE11 and Edge

### ISSUE THREAD

**Issue by hamat** [roundcube/roundcubemail#5614]
Some PNG files in classic theme has ".gif" extension, so that IE11 and Edge does not show these images.

- pagenav.gif
- searchfield.gif
- tabs-left.gif
- tabs-right.gif
- taskicons.gif
- watermark.gif

**Comment by alecpl** [comment]
Oh. Confirmed.

**Comment by alecpl** [comment]
Fixed.
