### ISSUE TITLE
1.2.3 version in Download is really 1.2.2

### ISSUE THREAD

**Issue by QkiZMR** [roundcube/roundcubemail#5615]
I have a 1.2.2 version on my server and I see that is new version (1.2.3) on main Roundcube website. When I try to download https://github.com/roundcube/roundcubemail/releases/download/1.2.3/roundcubemail-1.2.3-complete.tar.gz file and install it I got an error:
`Error 500: Installation at target location is up-to-date!`
Version in index.php file is 1.2.2 but archive file is named 1.2.3.

**Comment by alecpl** [comment]
No, it is not. Try again. Works for me.

**Comment by QkiZMR** [comment]
Now it's ok.
