### ISSUE TITLE
Strange line overlapping icons in Larry theme

### ISSUE THREAD

**Issue by asterismo** [roundcube/roundcubemail#5617]
Any ideas what this comes from?

[img]https://jabber.undernet.uy:5281/upload/fb028660-43d6-42bc-8f15-97d299ddb65a/IMG_20170120_023340.jpg[/img]

**Comment by asterismo** [comment]
https://jabber.undernet.uy:5281/upload/fb028660-43d6-42bc-8f15-97d299ddb65a/IMG_20170120_023340.jpg

**Comment by alecpl** [comment]
Fixed some time ago by f65f4bbca859.

**Comment by asterismo** [comment]
Yes you are right, pulled again and vanished.
