### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by founded** [roundcube/roundcubemail#5618]
Many trouble with login (if you has a old screen open it locks very fast)if there is an screen with an old sessionid also . Other screens wil not unlock if i relogin

**Comment by alecpl** [comment]
Could you be more specific?

**Comment by founded** [comment]
Could youu be more specific what not undersand ?
 Test you wil see.

**Comment by alecpl** [comment]
What is "very fast"? What is "old screen open"?

**Comment by founded** [comment]
You login and    you get an screen by richt click    wait then you dont has acces when session var lostby time .so you neet an other login and the old sceen is open and sendsome jquery data and kill the sesion that is opened . It kills also other data so you lost data

**Comment by alecpl** [comment]
This is how session works, no? Sorry, still not get it.
