### ISSUE TITLE
Failed generate/import key

### ISSUE THREAD

**Issue by psyche699** [roundcube/roundcubemail#5619]
Hello,

i have a problem for create or import key..
But i have no log..

I think is a problem for accessin the folder.
I use plesk 17.0.17 Onyx, on Centos 7.3

How to up the debug mode ?

Thanks in advance

**Comment by alecpl** [comment]
There's enigma_debug option in the plugin config. Are you using the enigma plugin? Provide the log. What version? Works for me.
