### ISSUE TITLE
Enigma: failed unlock sercret key

### ISSUE THREAD

**Issue by psyche699** [roundcube/roundcubemail#5620]
Hello,

ok, i have a other installation to Roundcube, i have activate enigma.

Test env : 
Roundcube 1.2.3
i use one adress mail test@mymail.com
Enigma only is activate.

1- I'm login to my mail : test@mymail.com
2- I generate a key.
3a- I use this key for crypt the mail.
3b- If try to sign the mail he ask my password, and dont work (CFAFD9B8) 
4- I send the mail crypted to test@mymail.com
5- I receive my mail from test@mymail.com
6- i open the mail, and , he asks me for my password,  (D7ADDF83)

I insert it, but this one does not work.

Look my key http://imgur.com/a/Ki6Oh

My password is correct, i did the 6x test.
And my password is simple for test : "1234"

no log for this...
please help me

**Comment by alecpl** [comment]
Enable enigma_debug option and provide the log.

**Comment by nonbinary** [comment]
I'm not sure if it's the same issue, but I've got the same symptoms.

OS: CentOS 7
PHP: 5.6.29
Roundcube: 1.2.3
gpg: 2.0.22
libgcrypt: 1.5.3
crypt-gpg-pinentry: 1.4.3

I've created a gpg key, and have an alphanumerical password. I can use enigma to encrypt mails, that part works. But signing or decrypting mails does not work.
I'm attaching a part of the debug log:
[enigma_errors.txt](https://github.com/roundcube/roundcubemail/files/757544/enigma_errors.txt)

**Comment by alecpl** [comment]
So, the log says "Operation cancelled" and it confirms there's some system issue with using pinentry program. It is not possible to guess what that can be without some internals debugging. It does not look like a Roundcube/Crypt_GPG issue though and I don't know how to help you.

**Comment by CRtEurope** [comment]
This eror shows that pinentry is not installed or not installed correctly.
If it is installed (correctly) open the gpg-agent.conf and check if the entry `pinentry-program` is there.
If it is absent or exists modify the path as for example:` pinentry-program /usr/bin/pinentry-curses`

**Comment by nonbinary** [comment]
Pinentry is installed, and specified in gpg-agent.conf. `pinentry --version` gives me pinentry-curses 0.8.1.

**Comment by alecpl** [comment]
This has nothing to do with pinentry settings in gpg-agent.conf. Crypt_GPG uses custom pinentry program which you can see in the debug log. Also, every user has its homedir with no gpg-agent.conf, so default configuration is used.

**Comment by nonbinary** [comment]
Quite true, and that program seems to run like it should. Now that I'm looking again, I even listed the version number up there in my first post.
I'm not sure how to error-check it further. But I think I'll try another install, with a PHP v5.4. If that doesn't do it, I'll try PHP 7. But I've seen posts where installations on CentOS have worked, with PHP 5.4.

**Comment by nonbinary** [comment]
I've tested this a bit further, and it's an selinux issue. If I set the httpd_unified sebool, it works. This solution is to broad, and I'd like to find a more precise one. If I'm not mistaken, the httpd_unified sebool isn't great for security.

**Comment by alecpl** [comment]
Nice you found it. Another solution could be use of gpg-1.4 or 2.1 (this one requires Roundcube 1.3).

**Comment by nonbinary** [comment]
I'll try gpg 2.1 later, see if that resolvs it.

**Comment by alecpl** [comment]
Added a note to Known Issues section of the plugin's README file. We can't do much more here, I suppose.
