### ISSUE TITLE
subscriptions_option plugin: show \\Noselect folders greyed out

### ISSUE THREAD

**Issue by leo-b** [roundcube/roundcubemail#5621]
If ``$config['use_subscriptions'] = false``, all folders returned by ``$storage->list_folders_direct()`` are returned. Unfortunately this includes namespaces and other "virtual" folders that are not selectable.

The following patch excludes folders that have the ``\\Noselect`` attribute set, so that they are shown as greyed out and are not selectable. This avoids an error message returned by the IMAP STATUS command if the user clicks on them.

```php
--- plugins/subscriptions_option/subscriptions_option.php.orig  2017-01-24 14:08:11.377284496 +0100
+++ plugins/subscriptions_option/subscriptions_option.php       2017-01-24 14:25:03.050127991 +0100
@@ -77,7 +77,16 @@
     {
         $rcmail = rcmail::get_instance();
         if (!$rcmail->config->get('use_subscriptions', true)) {
-            $args['folders'] = $rcmail->get_storage()->list_folders_direct();
+            $storage = $rcmail->get_storage();
+            $folders = array();
+            $all_folders = $storage->list_folders_direct();
+            foreach ($all_folders as $i => $folder) {
+                $attrs = $storage->folder_attributes($folder);
+                if (! in_array_nocase('\\Noselect', $attrs)) {
+                    $folders[] = $folder;
+                }
+            }
+            $args['folders'] = $folders;
         }
         return $args;
     }
```

**Comment by alecpl** [comment]
First of all, I think this plugin should use list_folders() instead of list_folders_direct(), but aside of this the problem with proposed solution is that some servers add \Noselect flag to selectable folders sometimes. If we decide to do this, we should probably do this "globally" in list_folders().

**Comment by leo-b** [comment]
> the problem with proposed solution is that some servers add \Noselect flag to selectable folders sometimes

IMHO those folders wouldn't be selectable for subscription anyway. ``rcmail_subscription_form()`` contains a similar check for ``\Noselect``.

**Comment by alecpl** [comment]
Indeed, but this does not remove them from the list. Your patch will remove them from the list if they have no subfolders. That may be a problem on some buggy servers. I'm not saying we'll not do this, but we should think twice. The only issue I remember regarding this is Courier IMAP adding \Noselect to INBOX folder. So, maybe we need to take care about this one case only.

**Comment by alecpl** [comment]
Done.
