### ISSUE TITLE
Crashed attachment with PostgreSQL

### ISSUE THREAD

**Issue by dmitrygribenchuk** [roundcube/roundcubemail#5622]
Hey! I'm using Roundcube 1.2.0 (mysql percona 5.6) and 1.2.3 (postgresql 9.4). I Do a clean install without the database migrations. Both Roundcube instance work with one imap server at the same time. With mysql all ok. If I open attachment with postgresql database backend some files is broken (random files, without regularity by size or type).

**Comment by alecpl** [comment]
More precise steps to reproduce, please. What plugins?

**Comment by dmitrygribenchuk** [comment]
Only standart plugins. I'm try to open attached files and some of them crashed

**Comment by alecpl** [comment]
What plugins, exactly? Any errors in log? How the files are broken? What types of files? I don't see a connection with database in use.

**Comment by dmitrygribenchuk** [comment]
Type of files:
jpg
docx
pdf

List of of plugins:
archive
zipdownload
show_gravatar (https://github.com/kepi/show-gravatar)

Sorry, I have a custom plugin show_gravatar
I swhitch off the blugin and all ok
