### ISSUE TITLE
Enigma: Always use detached signatures

### ISSUE THREAD

**Issue by fearedbliss** [roundcube/roundcubemail#5624]
Hello folks,

I've been testing out 1.3-beta and I have to admit, it is really really good. Thanks for the great work.

I noticed that for the enigma plugin, If I sign a message, it will do a inline sign of it so it looks really ugly for the recipients that don't have a client that can render/understand the inline signature. Normally I would just detach sig (default in thunderbird) and the person wouldn't have to see all of the noise but the important bits are included in the attachment via S/MIME. In roundcube/enigma, I was able to do this only by selecting both "Signing the message" AND also "Including the public key". Including both is definitely a good idea, but sometimes people just need to sign the message (detached) and the recipient can look for the key themselves.

Can this be added? If this is the wrong place to report this, feel free to let me know and I can forward it to the right place.

**Comment by alecpl** [comment]
Sounds reasonable. I think we could make it the default. Need to investigate possible interoperability issues.

**Comment by alecpl** [comment]
Done.

**Comment by fearedbliss** [comment]
Thanks for the work Aleksandr :).

On February 1, 2017 3:40:46 AM EST, Aleksander Machniak <notifications@github.com> wrote:
>Done.

--
This message is NOT signed or encrypted. If in doubt, please ask for a signed reply.

Learn how to sign and encrypt your messages at https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)
