### ISSUE TITLE
filesystem attachment plugin window still shows in compositer even if plugin disabled (1.3-rc)

### ISSUE THREAD

**Issue by fearedbliss** [roundcube/roundcubemail#5625]
If one disables the filesystem_attachments plugin, the attachment screen still shows up in the compositor. This is misleading since it won't actually work.

**Comment by alecpl** [comment]
What won't work? At least one attachments handling plugin is required, so if you disable all in the config filesystem_attachments plugin will be used.

**Comment by fearedbliss** [comment]
Ah ok. I thought that I was suppose to explicitly declare the plugin in order for it to work. You can close this if the plugin will always reactivate.

On January 29, 2017 5:51:01 AM EST, Aleksander Machniak <notifications@github.com> wrote:
>What won't work? At least one attachments handling plugin is required,
>so if you disable all in the config filesystem_attachments plugin will
>be used.

--
This message is NOT signed or encrypted. If in doubt, please ask for a signed reply.

Learn how to sign and encrypt your messages at https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)
