### ISSUE TITLE
filesystem attachment plugin won't attempt another file upload with the same if you click the trash icon for attachment and attempt to reupload

### ISSUE THREAD

**Issue by fearedbliss** [roundcube/roundcubemail#5626]
If you attach a file in the filesystem attachment plugin window in the compositor, it will upload the file and display it in the list correctly, however, if you click the trash icon to remove the attachment and then you attempt to attach it again, it won't let you. In order for you to get the same file to attempt to be reuploaded, you need to attach another file with a different name, or close the compositor completely. This is for 1.3-rc.

**Comment by alecpl** [comment]
I'm not able to reproduce. What do you mean "it won't let you to attach it again"? What browser?

**Comment by fearedbliss** [comment]
If you try to attach the same file after you remove it from attach list ,it won't attach.

On January 29, 2017 5:56:38 AM EST, Aleksander Machniak <notifications@github.com> wrote:
>I'm not able to reproduce. What do you mean "it won't let you to attach
>it again"? What browser?

--
This message is NOT signed or encrypted. If in doubt, please ask for a signed reply.

Learn how to sign and encrypt your messages at https://emailselfdefense.fsf.org/en/

Jonathan Vasquez (0xFB8590B7C4CA5279)

**Comment by alecpl** [comment]
Ok, but how? Is it the browser file selector dialog, or there's any error in log or in browser console, or what?

**Comment by fearedbliss** [comment]
I just tested it again and I'm unable to repro. Please close.
