### ISSUE TITLE
Not getting mailto value in message_before_send hook

### ISSUE THREAD

**Issue by salmanmohammad** [roundcube/roundcubemail#5629]
How can I access mailto value, my code is
function init()
{
$this->add_hook('message_before_send', array($this,'bfsend'));
}

function bfsend($args)
{
$to= $args['mailto'];
}
but I am getting empty value in $to.
please help me.

**Comment by alecpl** [comment]
Works for me in additional_message_headers plugin. What version? Log the whole $args array to see what's there. E.g.: `rcube::console($args);`

**Comment by salmanmohammad** [comment]
@alecpl i tried rcube::console($args); and got
[01-Feb-2017 08:43:16 +0000]: NULL
[01-Feb-2017 08:43:16 +0000]: NULL

NULL values
any idea how can I get recipient email address before sending mail

**Comment by alecpl** [comment]
I have no idea how do you get NULL. That should just work. What version? What other plugins are you using?

**Comment by salmanmohammad** [comment]
current version is 0.9
and I am not using any new plugin all are these
array('taskbar','demologin','help','trace_outgoing');

**Comment by alecpl** [comment]
I would disable all of them just to be sure none is interfering.

**Comment by salmanmohammad** [comment]
Ok I just check by disable all the plugins

**Comment by salmanmohammad** [comment]
same problem :(

**Comment by alecpl** [comment]
I'm unable to reproduce and 0.9 is not supported anymore.

**Comment by salmanmohammad** [comment]
Thank you @alecpl for your support
I will try it on newer version
