### ISSUE TITLE
default file permissions of composer-php / composer-php.bat

### ISSUE THREAD

**Issue by mschilt** [roundcube/roundcubemail#5630]
By default permissions of vendor/bin/composer-php and vendor/bin/composer-php.bat are set to 777 (everyone / full control). 
These files are served as text files by the server because of the file ending. So direct code execution does not seem to be viable by any local user. Good composer-php does not end in .php.

However I would vote for changing the files to 755 (least privileges principle).

**Comment by alecpl** [comment]
These files are created by composer. I don't see a danger in their permissions. Maybe we should just disable access to vendor folder in .htaccess file.

**Comment by thomascube** [comment]
That's probably a good idea. To make it a bit less restrictive maybe only access to `vendor/bin` could be disallowed.

**Comment by alecpl** [comment]
Done.

**Comment by thomascube** [comment]
@mschilt The permission thing might be something to report to the Composer folks.

Merci und Gruess, T
