### ISSUE TITLE
Emails Forwarded As Attachments, Winmail.dat and Zero Byte Files

### ISSUE THREAD

**Issue by tonyphillipson** [roundcube/roundcubemail#5632]
I'm seeing an issue where email(s) forwarded as attachments aren't understood correctly.  The content of the attached email(s) cannot be viewed within Roundcube.
I think it relates to TNEF encoding Outlook uses as I don't see the issue when email(s) are sent in HTML format.

For each "forwarded as attachment" email Roundcube lists an item in the attachment list, however the icon considers this to be an unknown item (document with 3 question marks).
URL to the item is similar to this:
https://xxx.xxx.com/mail/?_task=mail&_action=get&_uid=118&_mbox=INBOX&_part=winmail.2.0

When the link is clicked the browser attempts to save the file, which is seen as "application/octet-stream", and results in a 0 byte file.

I've tested this on 3 different versions, and see the same behaviour in:
Version 0.8.2
Version 1.1.7
Version 1.2.3

Getting the email in text format from the message store and opening with Outlook allows the attached email(s) to be viewed.

**Comment by alecpl** [comment]
Could you provide a sample message?

**Comment by tonyphillipson** [comment]
I can but didn't want to post that publicly.  How can I get this to you?

**Comment by alecpl** [comment]
alec at alec dot pl

**Comment by tonyphillipson** [comment]
Thank you, example message on way to you now.

**Comment by alecpl** [comment]
So, I can confirm the issue, but it might be hard to fix. Need investigation in our TNEF decoder which is very simple and does not support full TNEF specification.

**Comment by alecpl** [comment]
The forwarded message attachment inside the winmail.dat "structure" is in MAPI format. Our decoder does not support that. I see that Horde's decoder is a little bit better in this regard, we could reuse some code from there. https://github.com/horde/horde/blob/master/framework/Compress/lib/Horde/Compress/Tnef.php

**Comment by hlmyhlm** [comment]
Hi,

Just checking if this bug can be fixed? Will Roundcube be able to decode winmail.dat file anytime soon? Please help to suggest any work around to decode winmail.dat received when email is received from Outlook users. Appreciate your assistance.

Thank you.

**Comment by alecpl** [comment]
Fixed. The forwarded message is likely to be in RTF format, so it will require an external program, but it now has proper attachment name and size and can be downloaded.

If there's still some incorrect result please open a new ticket and attach a sample message.
