### ISSUE TITLE
SQL injection possible for RC 1.1.1. - found with Nessus

### ISSUE THREAD

**Issue by kolaloka** [roundcube/roundcubemail#5636]
Dear devs, I run webmail with RC 1.1.1.
- our company did a security inspection with serveral tools, and Nessus Found the following:

Using the POST HTTP method, Nessus found that :
+ The following resources may be vulnerable to blind SQL injection :
+ The '_user' parameter of the // CGI :
// [_token=480e344739c37107c2ef88588b270c2a&_url=&_action=login&_pass=&_
task=login&_timezone=_default_&_user=zz480e344739c37107c2ef88588b270c2a&
_url=&_action=login&_pass=&_task=login&_timezone=_default_&_user=yy]
-------- output --------
<input type="hidden" name="_task" value="login"><input type="hidde [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" required="requir
ed" autocapitalize="off" autocomplete="off" **value=""** type="text"></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Heslo</label>
-------- vs --------
<input type="hidden" name="_task" value="login"><input type="hidde [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" required="requir
ed" autocapitalize="off" autocomplete="off" **value="yy"** type="text"></td>
</tr>
<tr><td class="title"><label for="rcmloginpwd">Heslo</label>
------------------------
+ The '_url' parameter of the // CGI :
// [_token=480e344739c37107c2ef88588b270c2a&_user=&_action=login&_pass=&
_task=login&_timezone=_default_&_url=zz480e344739c37107c2ef88588b270c2a&
_user=&_action=login&_pass=&_task=login&_timezone=_default_&_url=yy]
-------- output --------
<form name="form" method="post" action="./?_task=login">
<input type="hidden" name="_token" value="c1f8200a2d8d8dffc60268cb [...]
11<input type="hidden" name="_task" value="login"><input type="hidden" nam
e="_action" value="login"><input type="hidden" name="_timezone" id="rcml
ogintz" value="_default_"><input type="hidden" name="_url" id="rcmloginu
rl" value=""><table summary="" border="0"><tbody><tr><td class="ti [...]
</td>
<td class="input"><input name="_user" id="rcmloginuser" required=" [...]
-------- vs --------
<form name="form" method="post" action="./?_task=login">
<input type="hidden" name="_token" value="c1f8200a2d8d8dffc60268cb [...]
<input type="hidden" name="_task" value="login"><input type="hidden" nam
e="_action" [...]

**Comment by alecpl** [comment]
That is a false positive. So, no action on our side needed, until you prove it's a real bug.

**Comment by kolaloka** [comment]
Thank you.
Peter

Aleksander Machniak wrote:
