### ISSUE TITLE
Excel formatting lost when copying/pasting into Roundcube compose area

### ISSUE THREAD

**Issue by cPRex** [roundcube/roundcubemail#5638]
Hey crew!

It looks like the bug mentioned here:

https://github.com/roundcube/roundcubemail/issues/5311

is still happening in version 1.2.3.  Just wanted to let you know.  Thanks!

**Comment by alecpl** [comment]
This is TinyMCE bug, we can't do much with it.

**Comment by cPRex** [comment]
Do you know if there is a specific version of TinyMCE that can be used as a workaround?

**Comment by alecpl** [comment]
You can test the most recent version at https://www.tinymce.com/. If it works there we could consider update.

**Comment by CRtEurope** [comment]
Which files should be replaced with the new version? `/program/js/tinymce` only?

I would like to test it

**Comment by alecpl** [comment]
You can test it on tinymce.com page and let me know if it works or not.

**Comment by CRtEurope** [comment]
I don't know but maybe this here is useful for the programers.
http://non-stop-ext.blogspot.de/2014/05/paste-excel-data-into-tinymce.html
