### ISSUE TITLE
Can not set Content-Type charset to 7-bit encoding (e.g., ISO-2022-JP)

### ISSUE THREAD

**Issue by dfukagaw28** [roundcube/roundcubemail#5640]
I can not send a mail with "Content-Type: text/plain; charset=ISO-2022-JP".

Some non-ASCII character encodings use only 7-bit bytes [0x00-0x7F].
Currently, a message encoded by such a 7-bit encoding is unexpectedly sent with "charset=US-ASCII", because of the following judge.

https://github.com/roundcube/roundcubemail/blob/3e427b4a429754906f73a31a4bf29be1c0bf8b40/program/steps/mail/sendmail.inc#L489

Pull request #5639 may solve this.

**Comment by alecpl** [comment]
What if we just replace the regexp with `/[^\x09\x0A\x0D\x20-\x7E]/`?

**Comment by dfukagaw28** [comment]
In that case, the Content-Transfer-Encoding of an ISO-2022-JP message will be either "8-bit" or "quoted-printable", which may cause problems in some situations.

I believe that Content-Transfer-Encoding for an ISO-2022-JP message should be "7-bit", as most people do so.

To encode an ISO-2022-JP message by using "quoted-printable" is nonsence, because ISO-2022-JP does not use the 8th bit in any octet.
"8-bit" seems acceptable as for me, but I heard that some systems re-encode every message sent with "Content-Transfer-Encoding: 8-bit" by using "quoted-printable" (to transfer them in 7-bit).

**Comment by alecpl** [comment]
Fixed.

**Comment by dfukagaw28** [comment]
Thanks!

But, the changes may have a problem as it has been pointed out in a comment to the commit 6f87a32, 
https://github.com/roundcube/roundcubemail/commit/6f87a320528f21f5804620dfa74e8ce7c2dafb63#commitcomment-22816595
