### ISSUE TITLE
enigma/lib/enigma_driver_gnupg.php

### ISSUE THREAD

**Issue by wisekaa03** [roundcube/roundcubemail#5641]
`
require_once 'Crypt/GPG.php';
require_once 'Crypt/GPG/KeyGenerator.php';
`
I added these lines, I had no time to investigate.
You can say that it was?

**Comment by alecpl** [comment]
Yeah, the first require is already there. We need the second for when we use the key generator. This is a change for 1.2 only, as in 1.3 we don't use that key generator.

**Comment by alecpl** [comment]
Fixed.
