### ISSUE TITLE
Make the default personal adressbook removeable

### ISSUE THREAD

**Issue by Xeniac-at** [roundcube/roundcubemail#5643]
Im using the roundcube carddav plugin for a central adressbook shared between roundcube, thunderbird and nextcloud. It works like a charm by the way! Thank you!

Because of this i don't have any need for an local personal adressbook. 
So it would be nice if i could delete it, or at least make the carddav account the default. So that it will open by default, instead of the emptyness of the local adressbook.

**My suggestion:** Allow the user to delete his personal adressbook if at least one other adressbook exists.

Yeah i know it's not a big deal, but it would be a nice polish. :-)

**Comment by alecpl** [comment]
Depending on how the carddav plugin is implemented, it should be possible to disable sql addressbook in configuration file. Try address_book_type='ldap' (or empty string. There's also default_addressbook setting. So, nothing for the core code here, imho.

**Comment by Xeniac-at** [comment]
Thank you for this tip @alecpl, address_book_type='' does the trick.
