### ISSUE TITLE
Add option to specifies the algorithms used in Enigma Plugin

### ISSUE THREAD

**Issue by HacKurx** [roundcube/roundcubemail#5645]
Hi,

All my messages signed by enigma are in SHA-1 but SHA1 is weak...
Please add a Enigma Plugin options to specifies the algorithms used by GnuPG for Enigma.

For my part I edited this file (See [patch-Enginephp.txt](https://github.com/roundcube/roundcubemail/files/774379/patch-Enginephp.txt)) :
/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/Engine.php

I had to force it like this because the configuration file was not read, The location was:
/plugins/enigma/home/me/.gnupg/gpg.conf
/plugins/enigma/home/me/gpg.conf

Thanks for your works,

Best regards,

Loic

**Comment by CRtEurope** [comment]
Your patched version works great. Thanks for it.

**Comment by alecpl** [comment]
This should be made a config option(s) in Enigma and Crypt_GPG.

**Comment by alecpl** [comment]
Implemented. Requires Crypt_GPG 1.6.2.

**Comment by HacKurx** [comment]
Great thanks ;)
