### ISSUE TITLE
UI updates on contact group rename

### ISSUE THREAD

**Issue by JohnDoh** [roundcube/roundcubemail#5648]
When you rename a contact group the name is updated in the groups list on the left hand side of the page but the name displayed at the top of the list of contents in the second column stays as the old one. I thought I could make a PR to improve this but the code for this is a little fractured and, possibly, out of date.

It looks like there are 2 JS functions rcmail.set_group_prop and rcmail.update_contact_group. update_contact_group is called when a group is renamed but only updates the groups list (and triggers JS event `group_update`). While set_group_prop is used when the groups contents is listed and sets the title in the second column (and triggers JS event `groupupdate`). I think that second JS event is wrong, I'm guessing it should be group_update, the same format as group_insert and group_delete. But also I'm wondering if these 2 JS functions shouldn't be combined into 1 that updates both the list and the title (if the group is open).

EDIT: On reflection I think that rcmail.set_group_prop should not trigger the update event at all since its only called on list and not update.

**Comment by alecpl** [comment]
I think the `groupupdate` event should be removed and set_group_prop() should be called from update_contact_group().

**Comment by alecpl** [comment]
Fixed.
