### ISSUE TITLE
rcmail::get_instance() signature compatibility

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#5649]
We should fix the method signatures to match in order to avoid these warnings:

> Warning: Declaration of rcmail::get_instance($env = '') should be compatible with rcube::get_instance($mode = 0, $env = '') in roundcube/program/include/rcmail.php on line 30

**Comment by alecpl** [comment]
As I see it is already fixed in 1.2.

**Comment by thomascube** [comment]
Agreed with @alecpl

**Comment by thomascube** [comment]
Oh, yes. Sorry for the noise and the confusing comment which was meant to go into another tab :-)

**Comment by thomascube** [comment]
For the record: fixed in 1b39d9a6
