### ISSUE TITLE
Adding new key does nothing in Chrome

### ISSUE THREAD

**Issue by conspacer** [roundcube/roundcubemail#5651]
When trying to generate a new key, clicking the "+" button does nothing in Chrome. 
Same server in FireFox works fine.

![rcmail-enigma-add-small](https://cloud.githubusercontent.com/assets/23648459/23064058/9b44ea0a-f516-11e6-92a3-ce4609a43527.png)

**Comment by alecpl** [comment]
What version of Chrome and Roundcube? Any errors in javascript console?

**Comment by conspacer** [comment]
@alecpl Chrome Version 56.0.2924.87 on Windows 10 64
No errors or issues reported in the console.
I noticed my enigma plugin version is 0.6, i just did a clone last week. Do I need to upgrade it somehow?
![rcmail-plugins](https://cloud.githubusercontent.com/assets/23648459/23064480/fa1dbb18-f518-11e6-8572-4938e2f52663.PNG)

**Comment by alecpl** [comment]
Works for me. So, you're saying the form in the content frame on the right side does not appear? The same code is used to display import form, does the Import button work? Try with disabled all other plugins.

**Comment by conspacer** [comment]
No, Import and "+" do nothing in Chrome. I was able to add a pubkey from someone who sent me one via email, but clicking on the key does not display its details in the rightside pane either.

Ill have to wait for the sysadmin to test with no other plugins enabled. Ill let you know.

**Comment by alecpl** [comment]
No feedback.
