### ISSUE TITLE
Too easy to accidentally move folders when subscribing/unsubscribing several folders at once

### ISSUE THREAD

**Issue by lp0** [roundcube/roundcubemail#5655]
In Settings -> Folders, it is far too easy to accidentally move folders when subscribing/unsubscribing several folders at once. If the mouse happens to be released slightly too late the folder suddenly ends up being moved to the grandparent folder.

It doesn't help that the first click to subscribe/unsubscribe a folder makes the folder frame scroll back to the top.

**Comment by alecpl** [comment]
What version do you use? The scrolling issue has been fixed in 1.2.3 (#5447).

As for the rest, I've never heard of such an issue, but maybe indeed we could do something to ignore dragging on checkboxes.

**Comment by lp0** [comment]
1.2~beta+dfsg.1-0ubuntu1 (which I agree is quite out of date)

Dragging folders in the main Mail view requires significantly more mouse movement before it starts compared to the Settings view.

**Comment by alecpl** [comment]
Fixed.
