### ISSUE TITLE
Your connection must be encrypted.

### ISSUE THREAD

**Issue by ben29** [roundcube/roundcubemail#5656]
according to this guide:
http://forum.directadmin.com/showthread.php?t=43500
now roundcube give an error:

> (Your connection must be encrypted.) SMTP (550): 

i did:
$config['smtp_auth_type'] = 'check';
$config['force_https'] = true;
$config['use_https'] = true;

**Comment by alecpl** [comment]
The error is about SMTP, so you need to set smtp_server (an smtp_port) accordingly.

**Comment by CRtEurope** [comment]
Also check this as follows. Should work.
```
$config['force_https'] = false;
$config['use_https'] = true;
```

**Comment by ben29** [comment]
1. i did smtp_server like the domain with the ssl (as config with outlook)
2. i config the port like outlook - port 587
