### ISSUE TITLE
tab no longer works in recipient autocomplete

### ISSUE THREAD

**Issue by JohnDoh** [roundcube/roundcubemail#5659]
The behaviour of the tab key in the recipient autocomplete function on the compose screen was changed in 9cf1e83 so that it does not insert the recipient. I did not see this change at the time and I realise this might just be personal preference but I think hitting tab should insert the selected recipient just as it does in other mail clients such as Outlook and (I think) Thunderbird, it is what I am used to any way. Similairy when your browser has auto complete enabled on regular form fields pressing tab fills in the selected value and moves focus to the next field. So I am opening this ticket because I think the change needs more discussion regarding "expected behaviour".

**Comment by alecpl** [comment]
For me it was an annoying behavior, I want Tab to just jump to another field without using the selected recipient. That's the common use of TAB key - to jump to another field.

In Thunderbird it indeed inserts selected AND jumps to another field. Firefox does the same, but with on difference. In Thunderbird and Roundcube there's always one entry selected on the autocomplete list, in a standard browser input you can have the list with no selection. So, you can hit TAB and jump to another field without inserting anything.

**Comment by JohnDoh** [comment]
I see your point about firefox and how you have to first select an item first before it will fill in the field. Just to summarise things a little:

|     | Tab | Enter |
| --- | --- | --- |
| **Current solution** | Move focus to next field | Insert selected value, focus remains in field |
| **Previous solution** | Insert selected value, focus remains in field | Insert selected value, focus remains in field |

In both the current and previous solutions the first entry in the suggestion list is selected by default.


|     | Tab | Enter |
| --- | --- | --- |
| **Suggestion 1** | Insert selected value, move focus to next field | Insert selected value, focus remains in field |

This would mimic the current behaviour in Outlook (note: I am used to using Outlook) but it still might be no good for people who don't like tab putting the information in the the field. So another modification could be to NOT select the first suggestion in the list by default - if you want to use the first entry you have to press down and then tab.

**Comment by alecpl** [comment]
From all the options I still like best the current behavior. Even if different than Outlook/Thunderbird behavior. @thomascube what do you think?

**Comment by thomascube** [comment]
I'd go back to the old behavior, that's also how Gmail behaves (just to add another reference). Jumping to the next field with tab is IMO like skipping one step. Tab is used to jump from one element to the next. When autocompletion is open, that's the element which has focus and tab closes this element and jumps to the next one which is the input field autocompletion is bound to.

But to make a distinction to <Enter>, I'm also OK with @JohnDoh's Suggestion 1.

**Comment by alecpl** [comment]
@thomascube I agree that TAB key should jump to next field, I just don't agree that it should do any other actions like inserting selected element. However, I'll not force my solution if you all think different. So, I'll implement the Suggestion 1.

**Comment by alecpl** [comment]
Done.
