### ISSUE TITLE
feature request: return "401 Unauthorized" http status when login fails

### ISSUE THREAD

**Issue by cinaplenrek** [roundcube/roundcubemail#5663]
We use roundcube behind a reverse proxy and would like to monitor
failed login attempts in the proxy log...

Would it be possible to return appropriate error status on the login form?

I have patched our rather old version of roundcube to return the appropiate
header by inserting a single header() line in rcmail.php... But this might not
be the right place todo it...

**Comment by alecpl** [comment]
I suppose we could. You can write a simple plugin for `login_failed` (or `unauthenticated`) hook that all it does is:
```
header('HTTP/1.0 401 Unauthorized');
```

**Comment by alecpl** [comment]
Done.

**Comment by EoleDev** [comment]
Hi,
As @Jean-Daniel, i don't understand why this was implemented in the main source.
As you previously said (@alecpl ) this change which is only asked by one user may be done with a plugin. Maybe it's the best solution as to not impact the other users?

**Comment by alecpl** [comment]
In f1ee6d7906 I added possibility to modify the behavior via 'unauthenticated' hook. 401 is still the default.

**Comment by katzenmayer** [comment]
This change seems to break the http_authentication plugin.

When a logout_url is set for the http_authentication plugin the plugin does a 307 redirect after logging out. Unfortunately, this 307 redirect is then overwritten with the 401 unauthorized.

I understand that I could probably write my own plugin to work around that, but having to dive into roundcube plugin development just to make a standard plugin work (again) doesn't seem right to me.

**Comment by alecpl** [comment]
@katzenmayer adding `exit;` after https://github.com/roundcube/roundcubemail/blob/master/plugins/http_authentication/http_authentication.php#L87 should fix it. Could you confirm?

**Comment by katzenmayer** [comment]
Your fix works.

**Comment by fabianbur** [comment]
I had configured haproxy through http (layer 7) authentication with debian 9 and php 7.0
When upgrading to Debian Buster with php 7.3, it no longer allowed http, only tcp (layer 4)

I could fix it by commenting on the file:
nano /var/www/roundcube/index.php

    $plugin = $RCMAIL->plugins->exec_hook('unauthenticated', array(
            'task'      => 'login',
            'error'     => $session_error,
            'http_code' => !$session_error ? 401 : 200
    ));

    $RCMAIL->set_task($plugin['task']);

//    if ($plugin['http_code'] == 401) {
//        header('HTTP/1.0 401 Unauthorized');
//    }

    $OUTPUT->send($plugin['task']);
}


The way to verify the virtual server by command line:
curl -iv -H "Host: correonuevo" "http://192.168.0.14"

Response after the change:
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Sat, 14 Sep 2019 04:34:16 GMT
Date: Sat, 14 Sep 2019 04:34:16 GMT
< Server: Apache
Server: Apache

Response before change:
* HTTP 1.0, assume close after body
< HTTP/1.0 401 Unauthorized
HTTP/1.0 401 Unauthorized
< Date: Sat, 14 Sep 2019 04:31:12 GMT
Date: Sat, 14 Sep 2019 04:31:12 GMT
< Server: Apache

I do not know why it is, but before it worked and had roundcube 1.4 rc1 in debian 9 and php7.0
