### ISSUE TITLE
Roundcube Error 554 Transaction failed: Duplicate header

### ISSUE THREAD

**Issue by drhouse7** [roundcube/roundcubemail#5664]
I'm really in trouble...
On my Ubuntu 14.04 server I have Postfix Dovecot and Roundcube.

Yesterday, I upgraded Roundcube from 0.9.5 to 1.2.3 and now I'm not more able to send emails.

From error log file I get 

    Feb 24 09:09:22 ip-***-***-***-*** postfix/pickup[2920]: D22341082D: uid=33 from=<info@example.com>
    Feb 24 09:09:22 ip-***-***-***-*** postfix/cleanup[3288]: D22341082D: message-id=<72415efb250c3abd729df45f9a0ec672@example.com>
    Feb 24 09:09:22 ip-***-***-***-*** postfix/qmgr[12617]: D22341082D: from=<info@example.com>, size=1483, nrcpt=1 (queue active)
    Feb 24 09:09:22 ip-***-***-***-*** dovecot: imap-login: Login: user=<mailwebmaster>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=3292, secured, session=<HmnqFUNJIAB/AAAB>
    Feb 24 09:09:22 ip-***-***-***-*** dovecot: imap(mailwebmaster): Disconnected: Logged out in=1406 out=576
    Feb 24 09:09:23 ip-***-***-***-*** postfix/smtp[3291]: D22341082D: to=<example@gmail.com>, relay=email-smtp.eu-west-1.amazonaws.com[***.***.***.***]:25, delay=0.28, delays=0.03/0.03/0.14/0.08, dsn=5.0.0, status=bounced (host email-smtp.eu-west-1.amazonaws.com[***.***.***.***] said: 554 Transaction failed: Duplicate header 'Subject'. (in reply to end of DATA command))
    Feb 24 09:09:23 ip-***-***-***-*** postfix/cleanup[3288]: 230EB1A2EA: message-id=<20170224090923.230EB1A2EA@example.com>
    Feb 24 09:09:23 ip-***-***-***-*** postfix/qmgr[12617]: 230EB1A2EA: from=<>, size=3361, nrcpt=1 (queue active)
    Feb 24 09:09:23 ip-***-***-***-*** postfix/bounce[3293]: D22341082D: sender non-delivery notification: 230EB1A2EA
    Feb 24 09:09:23 ip-***-***-***-*** postfix/qmgr[12617]: D22341082D: removed
    Feb 24 09:09:23 ip-***-***-***-*** postfix/local[3294]: 230EB1A2EA: to=<mailwebmaster@example.com>, orig_to=<info@example.com>, relay=local, delay=0.01, delays=0/0/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
    Feb 24 09:09:23 ip-***-***-***-*** postfix/qmgr[12617]: 230EB1A2EA: removed
    Feb 24 09:09:23 ip-***-***-***-*** dovecot: imap-login: Login: user=<mailwebmaster>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=3298, secured, session=<vmj3FUNJIgB/AAAB>
    Feb 24 09:09:23 ip-***-***-***-*** dovecot: imap(mailwebmaster): Disconnected: Logged out in=44 out=644
    Feb 24 09:09:24 ip-***-***-***-*** dovecot: imap-login: Login: user=<mailwebmaster>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=3300, secured, session=<MmoDFkNJJAB/AAAB>
    Feb 24 09:09:24 ip-***-***-***-*** dovecot: imap(mailwebmaster): Disconnected: Logged out in=534 out=26015
    Feb 24 09:09:24 ip-***-***-***-*** dovecot: imap-login: Login: user=<mailwebmaster>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, mpid=3302, secured, session=<jMQHFkNJJQB/AAAB>
    Feb 24 09:09:24 ip-***-***-***-*** dovecot: imap(mailwebmaster): Disconnected: Logged out in=120 out=781

And this is my message:

    Return-Path: <info@example.com>
    Received: by example.com (Postfix, from userid 33)
    	id 335A110325; Fri, 24 Feb 2017 09:06:27 +0000 (UTC)
    To: example@gmail.com
    Subject: prova 2017
    X-PHP-Originating-Script: 33:rcube.php
    MIME-Version: 1.0
    Content-Type: multipart/alternative;
     boundary="=_9219c7385324108d3186b2a5d900b4e0"
    Date: Fri, 24 Feb 2017 10:06:27 +0100
    From: Support <info@example.com>
    To: 
    Subject: 
    Organization: Example
    Message-ID: <d4ee2b3d20f8390ce69b163ce4f83174@example.com>
    X-Sender: info@example.com
    User-Agent: Roundcube Webmail/1.2.3
    
    --=_9219c7385324108d3186b2a5d900b4e0
    Content-Transfer-Encoding: 7bit
    Content-Type: text/plain; charset=US-ASCII
    
    Body message 

It's clear that I have a problem with a double header (evident in the email above, `To` and `Subject` are empty) but how can I solve this issue?

Regards

**Comment by alecpl** [comment]
Did you install the version with /vendor folder included?

**Comment by drhouse7** [comment]
Hi @alecpl ,
I've downloaded and installed from the [official page](https://roundcube.net/download/) this version: **roundcubemail-1.2.3-complete.tar.gz**

**Comment by drhouse7** [comment]
I think there is something wrong with my configuration...yesterday for upgrade I selected this path:

`/usr/share/roundcube/`

But as I see the script takes config infos from:

`/var/lib/roundcube/`

I tried to upgrade again with this path instead, but it doesn't allow me it says that is already updated.

So now this is my situation:

```
ubuntu@ip-******:/usr/share/roundcube$ ls -Al
total 296
drwxr-xr-x  2 root     root         4096 Feb 23 23:50 bin
-rw-rw-r--  1 www-data webmasters 137948 Nov 27 16:07 CHANGELOG
-rw-rw-r--  1 www-data webmasters   1353 Nov 27 16:07 composer.json-dist
drwxr-xr-x  2 root     root         4096 Feb 24 12:23 config
-rw-rw-r--  1 www-data webmasters   1940 Nov 27 16:07 .htaccess
-rw-r--r--  1 root     root         1345 Feb 23 23:50 .htaccess.orig
-rw-rw-r--  1 www-data webmasters  12412 Nov 27 16:07 index.php
-rw-rw-r--  1 www-data webmasters   9954 Nov 27 16:07 INSTALL
drwxr-xr-x  3 root     root         4096 Feb 23 23:50 installer
-rw-rw-r--  1 www-data webmasters  35147 Nov 27 16:07 LICENSE
-rw-r--r--  1 root     root        38774 Jan 21  2014 main.inc.php.dist
drwxr-xr-x 35 root     root         4096 Feb 23 23:50 plugins
drwxr-xr-x  8 root     root         4096 Feb 23 23:50 program
-rw-rw-r--  1 www-data webmasters   3736 Nov 27 16:07 README.md
-rw-r--r--  1 root     root           26 Oct 21  2013 robots.txt
drwxr-xr-x  4 root     root         4096 Mar 30  2016 skins
drwxr-xr-x  7 root     root         4096 Feb 23 23:50 SQL
-rw-rw-r--  1 www-data webmasters   3403 Nov 27 16:07 UPGRADING
drwxr-xr-x  8 root     root         4096 Feb 23 23:50 vendor

ubuntu@ip-********:/var/lib/roundcube$ ls -Al
total 16
drwxr-xr-x 2 root     root     4096 Feb 24 12:21 config
lrwxrwxrwx 1 root     root       23 Jan 21  2014 .htaccess -> /etc/roundcube/htaccess
lrwxrwxrwx 1 root     root       30 Jan 21  2014 index.php -> /usr/share/roundcube/index.php
lrwxrwxrwx 1 root     root       19 Jan 21  2014 logs -> ../../log/roundcube
drwxr-xr-x 2 root     root     4096 Mar 30  2016 plugins
lrwxrwxrwx 1 root     root       28 Jan 21  2014 program -> /usr/share/roundcube/program
lrwxrwxrwx 1 root     root       31 Jan 21  2014 robots.txt -> /usr/share/roundcube/robots.txt
drwxr-xr-x 2 root     root     4096 Mar 30  2016 skins
drwxr-x--- 2 www-data www-data 4096 Jan 18 18:02 temp
```

**Comment by alecpl** [comment]
This anyway looks like a deployment/config issue.

**Comment by rmcaninch** [comment]
Looks like you started with a Debian / Ubuntu packaged install and then did the upstream Roundcube install. The two do not put files in the same places. 

Either stick with Ununtu packages, look at testing or unstable, or read the RC docs on installing and configuring outside of the apt package manager.
