### ISSUE TITLE
Roundcube UI freezes after sending mail or viewing Settings 

### ISSUE THREAD

**Issue by law** [roundcube/roundcubemail#5666]
This is Roundcube 1.2.3, on Ubuntu 16.04, with nginx, MariaDB, PHP 7.0.15, and fpm.  Receiving email via IMAP works great, sending via SMTP actually sends email, but the interface just sits and 'spins', frozen, until some timeout condition is met.  Then it puts me back at the send-mail screen as if my message was never sent.  Similar behavior happens when clicking Settings -> User Interface (any sub-option) - interface acts like it's loading something, but it never actually completes the task.  Setting 'debug' to 4 and smtp/sql/sendmail logging to 'true' doesn't produce anything useful - 'error' log is completely blank, smtp/sendmail are as-normal, sql debug is below for review.  

Here is my (lightly anonymized) nginx config: 
https://paste.fedoraproject.org/paste/290kKKDGkIdj6-~O-cGnF15M1UNdIGYhyRLivL9gydE=

Here is the php-fpm webmail pool definition: 
https://paste.fedoraproject.org/paste/2dLwAhXJaX4n08jMmrYzCV5M1UNdIGYhyRLivL9gydE=

Here is FPM's php.ini: 
https://paste.fedoraproject.org/paste/VhBidsGe48hHGtyruG3ewF5M1UNdIGYhyRLivL9gydE=

Here is roundcube's config.php (anonymized):
https://paste.fedoraproject.org/paste/YOM3OX5B0K9-rjvGGdTKuV5M1UNdIGYhyRLivL9gydE=

Here is the debug SQL output when sending a mail, with scary binary blobs removed in case it's something sensitive: 
https://paste.fedoraproject.org/paste/Mhf1KWCZwLFys5aig5c0mV5M1UNdIGYhyRLivL9gydE=

Any thoughts on how I can further debug this?

**Comment by alecpl** [comment]
Remove this `add_header X-Frame-Options DENY;` Roundcube is using frames, you can't deny them.

**Comment by law** [comment]
Thanks Aleksander, that sorted it right out.  Out of curiosity, is there any documentation around an approved/working Roundcube setup for NGinx?  Happy to contribute a pull-request if there's any interest.
