### ISSUE TITLE
use_secure_urls

### ISSUE THREAD

**Issue by ben29** [roundcube/roundcubemail#5670]
HI.
On apache config i did:

`Alias /roundcube "/var/www/html/roundcube/"`

on /var/www/html/roundcube/.htaccess

i have :
```
RewriteEngine On
RewriteRule ^/[a-zA-Z0-9]{16}/(.*) /$1 [PT]
```

i'm getting 404 page.
my request for example...
https://site.com/roundcube/6azYNJj0FPmwiWax/?_task=mail

thanks

**Comment by alecpl** [comment]
Maybe `RewriteBase /roundcube/`? Not Roundcube issue.
