### ISSUE TITLE
setting composing html message is not working on mobile browser

### ISSUE THREAD

**Issue by tianhaopan** [roundcube/roundcubemail#5671]
user can go to preferences and select composing messages and go to the options to select whether they want to compose html message. There are several options which are "never,always,on reply to html message and on forward or reply to html message". All of those things work perfectly on desktop browser. However, if a user is trying to change the setting on mobile browser, the things going to be wrong. For example, if I change from "never" to "always" and save it. Afterwards, I leave this page and go back to this page again, the setting becomes "never" again which supposed to be "always".

**Comment by rmcaninch** [comment]
Typical first try is to disable any plugins to rule them out.

Then the version of Roundcube you're using and the version of mobile browser would help the more experienced look at this.

**Comment by alecpl** [comment]
And what skin? Roundcube skins are not designed for mobile browsers.

**Comment by tianhaopan** [comment]
I am using roundcube 1.1.7 and I am using default mobile browser to open it. I use safari actually on my ipone. Actually it doesn't matter what mobile browser that I use, I have tried many other ones.

**Comment by tianhaopan** [comment]
Hi alecpl, I use default skin. Actually, It won't make any differences if I change to other skins, the issue is still there.

**Comment by tianhaopan** [comment]
The trick thing is on the same page, there are other options which use exactly the same methods (e.g. select and option) for user to select and post to server if a user saved the changes. For example, if a user wants to set up sending message as "line" or "attachment", which works perfectly on both mobile and desktop side.

**Comment by alecpl** [comment]
You should check some never version we don't support 1.1.

**Comment by alecpl** [comment]
Also, try with disabled all plugins.
