### ISSUE TITLE
password plugin cannot write to tmp file

### ISSUE THREAD

**Issue by saspol** [roundcube/roundcubemail#5672]
Hello,
I use `password` plugin with `sql` database and `dovecot` password crypter.
What i found is when plugin encrypt new passwod, it cannot write encrypted new password to temporary file. File created but always empty. This file owned by `www-data` with 0600 mode.
Problem with this `fwrite` part in `password.php`:

            $pipe = popen("$dovecotpw -s '$method' > '$tmpfile'", "w");
            if (!$pipe) {                                                                                                                                          
                unlink($tmpfile);                                                                                                                                  
                return false;                                                                                                                                      
            }                                                                                                                                                      
            else {                                                                                                                                                 
                fwrite($pipe, $password . "\n", 1+strlen($password)); usleep(1000);                                                                                
                fwrite($pipe, $password . "\n", 1+strlen($password));                                                                                              
                pclose($pipe);
                $crypted = trim(file_get_contents($tmpfile), "\n");                                                                                                
                unlink($tmpfile);

If comment out second `unlink`, can see `$tmpfile` file is empty and further code does not work.
Also i tried replace this code with just

`exec("$dovecotpw -s '$method' -p '$password' > '$tmpfile'");`

which become

`[28-Feb-2017 13:19:02 Etc/GMT+8] /usr/bin/doveadm pw -s CRAM-MD5 -p PASSWORD > /var/www/roundcubemail-1.2.3/temp/roundcube-qQdNjb`

and situation exactly same. From command line this working just fine.
Looks like i miss something, maybe some php.ini settings? 
I use PHP 5.6.29 with RoundCube 1.2.3
Suggestion please.

**Comment by alecpl** [comment]
Since d41db75d823 we do not use temp file for this purpose. I don't know where's the problem with the old code. Maybe www-data has no permission to execute doveadm? Or maybe the usleep() value is too small. Please, note that we don't use -p argument, so it's not exactly the same as your exec() sample.

**Comment by saspol** [comment]
Ok, i update plugin to latest version, but same problem remain.
`doveadm` executing(i checked with wrapper) but php cannot get any result from it.
Increasing `usleep()` value also no helps.

**Comment by alecpl** [comment]
SELinux? It looks like something we can do nothing about.

**Comment by saspol** [comment]
This problem NOT solved. I just giveup this plugin. All other plugins works just fine.

**Comment by alecpl** [comment]
I understand, but it does not look like something we can fix on the side of code.
