### ISSUE TITLE
An Error Occurred! Server Error! (Unauthorised) 

### ISSUE THREAD

**Issue by Bertieio** [roundcube/roundcubemail#5673]
Using:
Cpanel 
Roundcube version: 1.2.3-1.cp1162
Safari 
OsX  

When one of my users is trying to write an email they have this message pop up repeatedly, it disappears after a couple of seconds they also have issues sending the email and attaching items.

Any idea what is causing this?

![image1-21](https://cloud.githubusercontent.com/assets/9221294/23465534/713923a6-fe90-11e6-882e-9f42a6713490.JPG)

**Comment by alecpl** [comment]
This error does not come from Roundcube. Probably from http server or some plugin. You should ask cPanel.
