### ISSUE TITLE
Trying to send email, only get "Can't connect to server"

### ISSUE THREAD

**Issue by mortenn** [roundcube/roundcubemail#5677]
I tried enabling debug in config, but nothing showed up in syslog.
Changed my config to send logs to file rather than syslog, no change.
Upgraded to 1.2.3, no change.

Looking at the net console, this is the response from the backend to the UI;
```json
{"Action":"SendMessage","Result":false,"ErrorCode":104,"ErrorMessage":"","ErrorMessageAdditional":"","Time":59}
```
As I am not getting any logs, I am unsure of how to proceed.

I have tested telnetting to port 25 on the SMTP server in config, and that works.

**Comment by alecpl** [comment]
I have no idea from where you get this console output, but this is not Roundcube's output. Configuration issue, ask on mailing list or forum.

**Comment by mortenn** [comment]
the json is the response from the server as I click the send button.
