### ISSUE TITLE
enigma - disable "Digitally sign this message & Attach my public key" checkbox when "Encrypt this message" checkbox checked

### ISSUE THREAD

**Issue by trippleflux** [roundcube/roundcubemail#5679]
As per-title, it would be practically useless these two checkbox doesn't have any check for "Encrypt these message", what would be any practical reasons attaching public key on encrypted message without user having the private key to decrypt it ?. These two "Digitally sign this message & Attach my public key" checkbox should be disabled once using ticked/checked Encrypt this message".

I think that this usability need to be address soon, as it wasting server resources and confusing brand new user.

**Comment by alecpl** [comment]
I don't get the meaning of your first sentence. If you send an encrypted message to someone, he has his private key and can decrypt the message. No?

As for the rest, it is possible to send encrypted message without signing it. So, the "Sign this message" makes always sense. I agree OpenPGP is not best user-friendly.

**Comment by trippleflux** [comment]
Isn't it that's the function of openpgp encrypted message?, the encrypted message only can be opened by the author original private key ?.

I have tested encrypting and also signing it, it doesn't do much difference other than the message is encrypted as if the message is encrypted only, so signing an encrypted message is useless in enigma, go ahead try it, the content inside encrypted message is not signed.

**Comment by alecpl** [comment]
OpenPGP has a feature to sign and encrypt at once, i.e. in one encrypted blob.

To decrypt a message encrypted using your public key, you need your private key.

I'm not a pgp expert, but looks you are neither.  So, I'm closing this ticket.
