### ISSUE TITLE
enigma - update included openpgpjs dependecy

### ISSUE THREAD

**Issue by trippleflux** [roundcube/roundcubemail#5680]
The opengpgjs that is included on current master git branch is really old version which is version 1.6.0 from back june 2016, there is new version 2.4.0 ( https://github.com/openpgpjs/openpgpjs/releases ) already released few hours ago, i have tested to drop in replacement into enigma plugin folder, and i haven't had noticed any error or functionality dysfunctional from the 2.4.0 updated version.

There is lot's of bug fixes and new features being added from 1.6.0 into 2.4.0, so it should be worth looking at.

**Comment by alecpl** [comment]
It's 70kB bigger. We use it only for key generation. I don't see much fixes in this area. I see they implemented key expiration time, but I suppose we should not add this feature until we have possibility to extend key's expiration time.

**Comment by trippleflux** [comment]
Haven't thoroughly checked the changelog but there is no bugs on the key generation part o_0;, if yes then it's a pretty well-made library!

**Comment by CRtEurope** [comment]
**By only replacing the openpgp.min.js creating keys won't work anymore.**

Reading keys is ok and decrypting is ok too as well as encrypting.
So accommodations will be necessary.

**Comment by alecpl** [comment]
Wontfix until we have a real need in a new version.
