### ISSUE TITLE
Empty username

### ISSUE THREAD

**Issue by inteninten** [roundcube/roundcubemail#5684]
Hello.

Roundcube Version 1.1.7

ICU compiled with '--with-data-packaging=archive' and php 5.6.30 intl extension uses
this ICU.

On that environment, roundcube 1.1.7 has empty $username on SQL query, and don't
try auth in dovecot.
Also when $username is empty, roundcube don't return any error/info/message.

**Comment by alecpl** [comment]
Looks like a PHP level issue. From intl extension we use idn_to_ascii() function. I guess it returns empty string instead of a properly converted string or sth. I see this issue for the first time and likely there's nothing we can do about it.

**Comment by inteninten** [comment]
Yes i know that's PHP issue, but we spend hours to diagnose. Roundcube should shows/log
any message/warning abount empty $username when debug is on.
