### ISSUE TITLE
Possible defect in source code (CWE-570)

### ISSUE THREAD

**Issue by AppChecker** [roundcube/roundcubemail#5685]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bug:

https://github.com/roundcube/roundcubemail/blob/ad83610a5e54f3dac45fa7c023b401c57150d202/plugins/managesieve/lib/Roundcube/rcube_sieve_script.php#L1263

```
else  if ($str[$position] == "\r" && $str[$position] == "\n") {
                            $position += 2;
                        }

```
$str[$position] can't be equal to "\r" and "\n" at the same time.

if ($str[$position] == "\n") is checked earlier so we think that code should be like:

```
else  if ($str[$position] == "\r" && $str[$position + 1] == "\n") {
                            $position += 2;
                        }
```

Possible defect was found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by alecpl** [comment]
Thanks. Fixed.
