### ISSUE TITLE
Signature appears always at bottom

### ISSUE THREAD

**Issue by jugmac00** [roundcube/roundcubemail#5686]
Hi,

when replying to an email,  no matter if I check "Place signature below the quoted message" or not, the signature appears always at the bottom of the email after the quoted text.

We use Roundcube 1.1.7

Is this a known bug or could our config.inc.php (which has quite a history of updates) be the reason for this behaviour?

Best

**Comment by alecpl** [comment]
Duplicate of #5628

**Comment by jugmac00** [comment]
@alecpl Thank you! Deployed version 1.2.3 on staging and can confirm it is fixed - cannot update though, as one custom plugin is broken with 1.2 line - have to fix this first.
