### ISSUE TITLE
what to do after download?

### ISSUE THREAD

**Issue by lfodz** [roundcube/roundcubemail#5687]
Hi! I am a very novice open source software user. I wanted to download roundcubemail, but after downloading version 1.2.3, a folder with a series of more folders, documents, and text appeared. Immediately, I did not know what to do or where to start. I think if there were accessible directions, or maybe less documents, texts and folders downloaded, Roundcubemail would be easier to install and then use. Maybe this could be an area of improvement? Thanks!! -lfodz

**Comment by rmcaninch** [comment]
As with most open source software, start with the Readme file, it is displayed here on Github. That points to the INSTALL file. If that doesn't explain it to you, look at what your operating system offers prepackaged while it is very likely an older version it can be a gentler introduction.

The Readme also points you to http://roundcube.net and http://www.roundcubeforum.net/ both good sources of instructions and assistance and they are the _intended_ starting points for someone who is wanting to _use_ the software and is not yet ready to roll up their sleeves and dig into the code.

Hope that helps.
