### ISSUE TITLE
Question: Do you like the idea of an roundcube update script

### ISSUE THREAD

**Issue by Tronde** [roundcube/roundcubemail#5689]
Hi,
I wrote a small bash script called ['updating_roundcube.sh'](https://github.com/Tronde/My-IT-Scripts/blob/master/bash/updating_roundcube.sh). The main idea is to enter the path to your roundcube installation, the database name, the root user for the database and the download url of the new roundcube version. The script creates a backup of the document_root and the database before it starts the update, downloads the archive of the new version and installs it.

The current version of the script is written with German instructions and comments. If you like to have such a script, I could translate it to offer an English version, too.

What do you think about it?

Regards,
Tronde

**Comment by alecpl** [comment]
I'd not want to support such scripts.
