### ISSUE TITLE
Emails not showing up in spam special folder

### ISSUE THREAD

**Issue by medusared** [roundcube/roundcubemail#5691]
We use Roundcube 1.2.3. All our users have a folder called "spambox". They are auto-subscribed to this folder with dovecot and it's correctly setup in Roundcube's config "$config['junk_mbox'] = 'INBOX.spambox';" The problem is that the folder always appears empty in Roundcube even when there are emails in the folder! Logging in with any other imap client (squirrelmail, thunderbird, outlook etc) fixes the problem and the emails are then visible in Roundcube and works correctly from then onward. Changing the view to "Threads" view in Roundcube also makes the emails suddenly appear and then everything works, even when going back to "List" view. The problem only occurs with the "spambox" folder, and only in Roundcube (all other imap clients show emails in the spambox folder). 

What could be causing this? Is this a bug? If so, how do we fix it? Many Thanks

**Comment by medusared** [comment]
It ONLY happens in Roundcube. Every other Webmail client works fine showing emails in this folder, as does all other email software. Therefore I would say it is definitely a Roundcube issue. I did enable imap_debug and it didn't show anything unusual - it just said "STATUS INBOX.spambox (MESSAGES 0 UNSEEN 0)" even when there are hundreds of unseen messages. Any ideas?

**Comment by alecpl** [comment]
`STATUS INBOX.spambox (MESSAGES 0 UNSEEN 0)` is a server response. SO, it is actually a proof that this is a server bug.

**Comment by medusared** [comment]
If it is a server bug, why would it work perfectly in ALL other imap clients and webmail systems and just not work in roundcube ONLY? Surely that shows this is something very specific to roundcube?

**Comment by alecpl** [comment]
Maybe others just do not use the STATUS command to get a number of messages in a folder.

**Comment by alecpl** [comment]
What imap server software and version it is?

**Comment by medusared** [comment]
And why would it suddenly start working OK when clicking the Thread view button in Roundcube? I'll check the versions and let you know

**Comment by medusared** [comment]
It's Dovecot 2.2.27

**Comment by medusared** [comment]
So I re-enabled imap_debug, logged in and got "STATUS INBOX.spambox (MESSAGES 0 UNSEEN 0)" then in Roundcube clicked the Thread view button, and all the messages showed up as I said previously, and then got "STATUS INBOX.spambox (MESSAGES 264 UNSEEN 264)". Then everything works fine even in List view, logging out and back in etc

**Comment by lrosenman** [comment]
Sounds like the index got rebuilt.

**Comment by alecpl** [comment]
Please, write to dovecot mailing list with the debug.

**Comment by medusared** [comment]
Thanks for your help

**Comment by medusared** [comment]
I upgraded RC to 1.2.4 and this issue is still ongoing. Everyone I've spoken to about it (assp / dovecot / cpanel) all seem to think it's a roundcube problem because it doesn't happen with ANY other webmail or email software/app. They say that RC should update the dovecot index file when checking all the folders upon login. If RC doesn't do that like other webmail/software, this seems to be the problem.

So...
1. Can you think of a fix or workaround that will make the new emails show up?
2. Can I set the Threads view as the default for just that one folder? 
3. Where is the Threads/List view type for a folder stored - in the database and if so where?

Any help would be massively appreciated as this issue is causing us lots of problems because users can't check their spam folders since we switched from squirrelmail to roundcube! Thanks

**Comment by alecpl** [comment]
IMAP clients have no idea about any indexes on the server. They can execute a set of commands, but there's no standard that says "this command rebuilds index". So, if you encounter a not updated index, it is a server issue.

The setting you ask works per-folder and is stored in user preferences, but you can't set it for the user only for one folder. You can set only the default mode (see default_list_mode option).

**Comment by medusared** [comment]
Thanks, I just wanted to double check with you because other people said it was a RC issue. Although it does seem very strange that the Threads view works fine with the new emails, but List view doesn't - why is that - is there a difference in the way those two view types behave or talk to the imap server (dovecot)? I'm trying to understand the issue because no-one at dovecot/assp/roundcube seems to be able to help so I'm struggling to try to diagnose the issue myself! Thanks for any help or insight you can provide. We really like RC but this is causing us problems!

**Comment by alecpl** [comment]
Yes. Enable imap_debug in Roundcube config to log complete IMAP conversation.
