### ISSUE TITLE
Upload session breaks in plugin

### ISSUE THREAD

**Issue by tunis78** [roundcube/roundcubemail#5694]
When I make plugin that use the HTML editor the file uploading not working.
It is in the /program/steps/settings/upload.inc that get the session wrong by the function `$RCMAIL->session->append($type . '.files', $id, $attachment);`
This happens when $type contains "." as in plugin.pluginname.
It works fine if I add
`$type = str_replace('.', '-', $type);`

**Comment by alecpl** [comment]
This is not exactly a part of plugin API, but I think we can fix it this way.
