### ISSUE TITLE
Settings > Folders shows folder prefix

### ISSUE THREAD

**Issue by medusared** [roundcube/roundcubemail#5695]
When $config['show_real_foldernames'] = true, the folder prefix is displayed in Settings > Folders. This is not the case when the show_real_foldernames = false. The folder names are shown correctly without the prefix in the left folders list on the main Roundcube Mail page, but in Settings > Folders the prefix is shown. Is there any way to change it so that the folder prefix is NOT shown when show_real_foldernames = true? Many Thanks

**Comment by alecpl** [comment]
Sounds like a bug. What version?

**Comment by medusared** [comment]
Version 1.2.3

**Comment by medusared** [comment]
Is this a bug, and is there anyway I can change it by changing the code?

**Comment by alecpl** [comment]
Yes and yes, but I'm not sure yet where. Could you provide an account, so I could connect with my Roundcube instance and do some tests?

**Comment by medusared** [comment]
Yes I can provide a test email account for you - what details do you need and how should I send them to you so they remain private?

**Comment by alecpl** [comment]
My email is alec@alec.pl, you can find my pgp key on public key servers if needed.

**Comment by alecpl** [comment]
Fixed. Thanks @medusared for providing the test account.

**Comment by medusared** [comment]
Brilliant, thanks a lot!
