### ISSUE TITLE
Enable zipdownload selection by default

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#5696]
We're seeing several support requests for downloading multiple messages as ZIP. Although the zipdownload plugin offers this functionality, it needs to be enabled by config.

I propose to change the default to
```
$config['zipdownload_selection'] = true;
```

Those who don't want to offer this function can still disabled it by config.

**Comment by alecpl** [comment]
I noticed this too, but... It has performance/security implications. So, I'm not sure we should just switch the default without implementing some kind of a size limit (with safe default) for this feature.

**Comment by thomascube** [comment]
And what are these implications? If the feature is unstable or insecure, we should maybe not offer it at all.

**Comment by alecpl** [comment]
It is stable, but I'm talking about a user with 10000 messages in a folder trying to compress and download all of them.

**Comment by dol** [comment]
We enabled this feature for our customers recently and today one customer almost filled our server storage space with a download of his entire mailbox.
In total ~10Gb of zipdownload* data chunk in the configured tmp folder. A size limit would be nice.

**Comment by alecpl** [comment]
Done. Default limit is 50MB.
