### ISSUE TITLE
Firefox 52.0.1 update breaks roundcube

### ISSUE THREAD

**Issue by Sp1l** [roundcube/roundcubemail#5698]
Just updated Firefox from 52.0 to 52.0.1 and now roundcube is broken. Login is OK but I get an empty message-list with the js popup banner "Connection Error (Failed to reach the server)!"

Direct connections from an IMAP client to my dovecot server are OK, so is Chrome 57

**Comment by alecpl** [comment]
That's a connection error. I don't know what we can do about it. Maybe that's some browser addon issue?

**Comment by Sp1l** [comment]
Hi Alexander, Sorry for the noise...

Just checked with an new profile in Firefox and I see the message-list now.
I'll try and find the offending plugin. Same behavior experienced in Rainloop webmail...

**Comment by Sp1l** [comment]
Isolated the issue. Problem caused by NoScript. No indication yet how or why, NoScript is disabled for the domain where Roundcube is hosted.
