### ISSUE TITLE
Image thumbnail doesn't show.

### ISSUE THREAD

**Issue by MadaSociety** [roundcube/roundcubemail#5699]
Hello,
If the message contains an image the thumbnail doesn't show.

![roundcube-capture](https://cloud.githubusercontent.com/assets/13943732/24100111/a1a14954-0d83-11e7-9ea8-fd9c3782ec10.PNG)

Thank you.

**Comment by alecpl** [comment]
There might be many reasons for that. What version? What browser? What errors in log or browser console?

**Comment by MadaSociety** [comment]
Roundcube Webmail 1.2.4
Browser : Google Chrome
Console : No error

![roundcube-plugin](https://cloud.githubusercontent.com/assets/13943732/24134469/92b1ae92-0e15-11e7-98a3-fcb55881d35b.PNG)

Thank you.

**Comment by alecpl** [comment]
What IMAP server version? Enable imap_debug in Roundcube and investigate IMAP conversation to see if the image body is correctly returned by the server. And try with disabled all plugins.

**Comment by MadaSociety** [comment]
I try disable all plugins and activate imap_debug but no success.
I try open thumbnail link in other tab and remove "**&_thumb=1**", The picture appears.
If I add "**&_thumb=1**", I have blank page.

Thank you.

**Comment by alecpl** [comment]
Roundcube uses ImageMagick or GD to scale the image. Looks like this process fails. Check if you have GD or Imagick extension for PHP installed or im_convert_path properly configured (in Roundcube config). Also, does it create any files in /temp folder? Any errors in Roundcube log?

**Comment by MadaSociety** [comment]
I change the permissions folder of "temp" and "log" and it's work.
Thank you.
