### ISSUE TITLE
Add more fonts and text sizes to HTML formatting

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#5700]
I'd like to use the Segoe UI font in e-mails. This is the standard UI font in all Windows systems for the last ten years. As I've seen, helvetica/sans-serif are specified as fallback in the style attributes anyway, so this is a common and safe formatting. I do the same in my custom stationary for Thunderbird.

I'd also like to have finer control over the font size. It's a big leap from 8pt to 10pt. There could be 9pt as well to format signature text a bit smaller, but not too small to read. And as we're here, 7, 11 and 13pt might fit nicely, too. This is not a numeric spinbox with free number entry, it's only a pick-one list.

All in all this should be just some more entries to existing drop-down lists.

**Comment by alecpl** [comment]
I don't like these ideas. E-mail agents should use only "safe" fonts. I don't think Segoe UI is one of them.
As for the font-size, I don't think we have to be so precise in font selection. Some mail clients do not even provide such size selection, they use predefined set of formats (mostly for headings). Maybe we should also think about simplifying the editor toolbar even more in the future. The more HTML features you use the more chances you have to break on a receiving client.

**Comment by ygoe** [comment]
I don't see how Andale Mono is a safe font. What does that even mean? Most of the fonts listed are only available on Windows, and Segoe UI is certainly available there, too. If you want it safe, don't specify fonts at all or provide them as web font (which MUAs don't support).

Can I enter the raw HTML for my signature? If you want signatures with anything like a certain style you need fine control over the formatting. I do test what works and what doesn't in other MUAs like Outlook or web mail services. And what I want works just fine in most places and doesn't break in others. Roundcube is clearly the over-simplifying limiting factor for me now.

**Comment by alecpl** [comment]
Of course you can use custom HTML code. See "Source code" button in the editor toolbar.

**Comment by alecpl** [comment]
Maybe we should review our current fonts set (especially for when we implement a new skin with mobile devices support) with help of http://www.cssfontstack.com/. As you see Segoe UI has only 75% coverage on Windows and 0% on Mac (and Linux/Android I guess).

**Comment by ygoe** [comment]
Thanks, I didn't know the source code button. The editor seems to filter the source code anyway so that doesn't help much. The editor really seems to be the limiting factor here. And since the font in the signature is replaced with the main mail font (if nothing is specified) that doesn't help either.

Those font availability numbers have no source provided and seem very outdated. Segoe UI came with Windows Vista which is about to be falling out of support. XP is long deprecated and should not be connected to the internet anymore. 100% of all current Windows versions have that font. XP distribution varies somewhere between 1 and 15% depending on the source (I can't provide one now).

**Comment by webertrlz** [comment]
is this still a pending request?

**Comment by alecpl** [comment]
Yes. 9pt and 11pt sizes has been added recently to the list, but there was no work on font families list.

**Comment by ygoe** [comment]
Thanks for adding some more font sizes.

Oh, one more note about the fonts selection. You're talking about mobile platforms. They tend to not have any fonts at all. Apple may be more homogenous, but for Android (which is way more popular in parts of the world) it's a decision of each device maker. And they can even misconfigure Android to largely break fonts support if the app doesn't work around that (like Sony). So if you want > 90% coverage, stick with "sans-serif", "serif" and "monospace".

But do we want to discard any style in e-mails because some limited platforms don't fully support it? After all, it's not like a mail formatted with "Segoe UI, sans-serif" would be unreadable on a Mac or iPhone or Android. It's just not exactly the desired font but still a very good alternative, in fact each platform's standard UI font. It's just Windows that doesn't push its default UI font as much as others do. But those 90 % of my correspondence will see a consistent style with my desktop mails. YMMV. JM2C.

**Comment by d19dotca** [comment]
@alecpl Any idea if 13pt font size will be added soon? I have no idea why it's missing other than maybe superstitious reasons as 13 is an "unlucky" number in some cultures...? Its absence is leading to discrepancies in font sizes between some client apps (like macOS Mail, Thunderbird, etc) and Roundcube webmail. 😞  Hoping that'll be added someday soon.

**Comment by codegain** [comment]
@alecpl I stumbled upon this issue while figuring out how to add some font sizes <8pt. Instead of adding sizes/font-families, would it be possible to add some sort of default config for the font-families in https://github.com/roundcube/roundcubemail/blob/14522d7108a49ddf7a5c2094637365d88875a07f/program/include/rcmail_action.php#L737
which could be overwritten or appended by the user? Or just a hook like `font_defs` for plugins to add font-families? Same would need to be implemented for `font-size` (config or plugin hook) to easily add font sizes.

**Comment by avatar1024** [comment]
Hello,

I have just noticed that most fonts (if not all) are proprietary. Is it now possible to manually to add more fonts, especially I'd like to add open source ones. I had to use Arial to write emails which was just painful...

**Comment by alecpl** [comment]
Configuration options have been implemented (#9177). A more sensible defaults is story for another time.

ps. please be aware, the fact that you use in an email a font that exists on your computer does not mean it will exist on the recipient's computer. We need to investigate or find a list somewhere of fonts that are most common and create a better default list.

**Comment by loxK** [comment]
@alecpl please read this : [System Font Stack](https://css-tricks.com/snippets/css/system-font-stack/)
