### ISSUE TITLE
LDAP SSO with Addressbook AD

### ISSUE THREAD

**Issue by sotor-rus** [roundcube/roundcubemail#5703]
I try to setup SSO access from Roundcube to LDAP Address Book using pear-net_ldap3 plugin and apache2 with krb5 authentication.
My Address Book code:
```
$config['ldap_public'] = array(
    'MyAdLdap' =>array (
        'name' => 'Big Company, Inc',
        'hosts' => array('dce.dome.teste'),
        'sizelimit' => 6000,
        //'port' => 3268, # See comments below
        'port' => 389, # See comments below
        'use_tls' => false,
        'user_specific' => true,
        'base_dn' => 'CN=Users,DC=dome,DC=teste',
        'bind_dn' => '',
        'bind_pass' => 'xv',
        'bind_user' => '',
        'writable' => false,
        'ldap_version' => 3,
        'search_fields' => array(
           'mail',
           'cn',
        ),
        'auth_method' => 'GSSAPI',
        'name_field' => 'cn',
        'email_field' => 'mail',
        'surname_field' => 'sn',
        'firstname_field' => 'givenName',
        'sort' => 'sn',
        'scope' => 'list',
        'filter' => '(&(mail=*)(|(&(objectClass=user)(!(objectClass=computer)))(objectClass=group)))',
        'global_search' => true,
        'fuzzy_search' => true
    ),
);
```
It works when i added in LDAP3.php "function sasl_bind" this line:
` putenv("KRB5CCNAME={$_SERVER['KRB5CCNAME']}");`
with this varible php function ldap_sasl_bind work via GSSAPI nice.
But for the roundcube to use this function, I need to leave the 'bind_dn' field empty, and in the 'bind_pass' field specify random password, then roundcube use the necessary function ldap_sasl_bind.
Here is the part of the code in rcube_ldap.php responsible for this behavior:
```
           if (empty($bind_pass)) {
                $this->ready = true;
            }
            else {
                if (!empty($bind_dn)) {
                    $this->ready = $this->ldap->bind($bind_dn, $bind_pass);
                }
                else if (!empty($this->prop['auth_cid'])) {
                    $this->ready = $this->ldap->sasl_bind($this->prop['auth_cid'], $bind_pass, $bind_user);
                }
                else {
                    $this->ready = $this->ldap->sasl_bind($bind_user, $bind_pass);
                }
            }
```
Did I do properly? Could you make that if empty fields 'bind_dn' and 'bind_pass', then Roundcube used the function 'sasl_bind' from 'pear-net_ldap3'.

**Comment by alecpl** [comment]
Instead of an empty password we should rather check auth_method and act accordingly, i.e. use call putenv() and sasl_bind(). We should probably also add `gssapi_cn` property to `ldap_public` array, so you set it to `$_SERVER['KRB5CCNAME']` in the config (or from a plugin).

Maybe some part of this should be moved to LDAP3.

**Comment by sotor-rus** [comment]
I do this patch please look http://git.altlinux.org/people/sotor/packages/?p=roundcube.git;a=blob;f=roundcube-1.2.4-sso-alt.patch;h=d99ade2ecc9dbfa99fce371ddd36b7867b4216dc;hb=491dac81fe5baf498e019a57036bb4c80beb75cd

**Comment by alecpl** [comment]
Done.
