### ISSUE TITLE
Subscribing to folders being reset

### ISSUE THREAD

**Issue by LeoGraper** [roundcube/roundcubemail#5709]
Hello there all,
I'm having an issue with RoundCube Webmail;
Scenario;
We used to use a Webmail app of our provider SoHosted in the Netherlands.
As it has its ups-and-downs we wanted to use Outlook 2010 with IMAP access.
This works, but the folders underneath the Inbox weren’t visible.
I found out via our alternative mail being RoundCube the subscriptions weren’t set on all subfolders.
So I went to the Map settings and tried to turn them ON.
This worked, RoundCube saw a lot more and also O2K10.
When we went back to the subscription part we saw that the subscriptions were turned off again!
Strange, so we started with one folder and subfolders, and went to the email, all was there, we did this for say 10 folders, and all of a sudden they were turned off again.
It’s driving us crazy and mad!
So, is there something wrong in RoundCube, are the maximum values I don’t know about?
I’m not sure how many folders there are, my best guess is about 40 folders and within these it depends, but at least more than 200 grand total.

**Comment by alecpl** [comment]
There's no such limit in Roundcube. I guess it's some IMAP server issue. To make sure, you can enable imap_debug in Roundcube config to log the whole IMAP conversation.

**Comment by LeoGraper** [comment]
Thanks Alecpl for your swift reply!
How do I go about this, as it's webmail (browser) I have no idea where I can change this.
Do you have a link or something else that can direct me to this please?
Thanks, Leo.

**Comment by alecpl** [comment]
Ah, you can't do this on the browser side. Did you ask SoHosted? Use another client e.g. Thunderbird to see where's the problem.

**Comment by LeoGraper** [comment]
I did try Outlook (via Imap) and the other (own) Webmail of SoHosted, problem is I only see the standard folders, and not the one's she created in a meantime.
It appears as if RoundCube is the only one to make them visible to Oulook, but I will try TB.
Thanks, Leo.

**Comment by LeoGraper** [comment]
Hello Alecpl, today I had word with the helpdesk of SoHosted, the only thing they could come up with was resetting en re-indexing this specific mailbox, and first tests look promising.
Original webmail shows all folders, RoundCube lets me subscribe to all (I would really like a select all there if possible, my indexfinger is sore ;-) ) and after logout en back in, all is still selected!
Next thing is Outlook tomorrow, and see what MickeySoft makes out of all this.
Thanks for the help, highly appreciated!
Regards, Leo.
