### ISSUE TITLE
Double table header appears with Larry skin in folder listing after expanding toolbar

### ISSUE THREAD

**Issue by blakawk** [roundcube/roundcubemail#5711]
![screenshot from 2017-03-29 23-01-47](https://cloud.githubusercontent.com/assets/1149069/24476556/ffaee248-14d3-11e7-920c-06842a3cd4f7.png)
As shown in the screenshot, after expanding the top toolbar, clicking on "About" link, then closing the About popup by clicking on the cross, then, shrinking the toolbar, the header of the folder mail listing appears twice. Then expanding/shrinking the toolbar makes the two headers staying above it, until either the refresh timer elapses or the page is reloaded.

**Comment by alecpl** [comment]
Works for me. What version? What browser?

**Comment by blakawk** [comment]
Roundcube 1.2.4 with chrome browser in Ubuntu Gnome 16.10

**Comment by alecpl** [comment]
Works for me with Chromium 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.04 (64-bit). Try with disabled all plugins in Roundcube and the browser as well. Check browser console for javascript errors.

**Comment by blakawk** [comment]
Even with all plugins disabled, with Chrome Version 57.0.2987.110 (64-bit), there is no javascript errors on the console. I inspected the header and it seems that there is two table header for the messagelistcontainer, as shown below.
![screenshot from 2017-03-30 21-16-55](https://cloud.githubusercontent.com/assets/1149069/24522053/9f5ad5bc-158e-11e7-84a8-9580ada97541.png)
![screenshot from 2017-03-30 21-17-01](https://cloud.githubusercontent.com/assets/1149069/24522055/a1996ed8-158e-11e7-95b8-62ef7bd2b75b.png)

**Comment by alecpl** [comment]
There are two headers, this is normal. Problem is with re-positioning.

**Comment by alecpl** [comment]
I was able to reproduce the issue with 1.2.4 now. There's no issue in git-master though.

**Comment by blakawk** [comment]
Nice then 😎

**Comment by alecpl** [comment]
Ok, so what we know. It happens only with the About dialog (which uses an iframe), but not others, e.g. messages list options dialog. Second, it does not happen in git-master, but I didn't find a specific change that fixed that. For now I didn't find a simple solution. Because the issue is rare and 1.3-rc is comming this month, we probably will not fix the issue until someone comes with a solution.

**Comment by alecpl** [comment]
Ok, it looks that I've found a hack. Fixed.
