### ISSUE TITLE
Address book search isn't matching simple results

### ISSUE THREAD

**Issue by p0087** [roundcube/roundcubemail#5712]
I (on RC1.2.4) have an address book full of "Chan"s. It matches the first few fine, but ignores others (e.g. "Josy Chan"). Searching for "Josy" has a result for "Josy Chan", so something is messed up in the search.

**Comment by alecpl** [comment]
Search in Addressbook UI or autocomplete in mail compose screen? Do you search in "All fields" or only in Name or Lastname? Is this the built-in sql addressbook? Take a look at records in the contacts table using SQL to see where's the difference. You can also try executing bin/indexcontacts.sh script.

**Comment by p0087** [comment]
The issue is in both mail compose screen and addressbook UI. In the mail compose screen I just associated it with intentionally showing a limited subset of results (although this might not be the case). I am searching with 'All fields' ticked in the addressbook UI, using 'CardDav 2.0.4' for syncing (all the contacts are present this way, nothing is local).  There's nothing different in any of their "card:address-data" to explain not returning as a result either

**Comment by alecpl** [comment]
If "nothing is local" then I suppose that's some carddav plugin issue.
