### ISSUE TITLE
LDAP "Fuzzy Search" fails with introduction of SEARCH_GROUPS in $mode

### ISSUE THREAD

**Issue by vidarberg** [roundcube/roundcubemail#5713]
After upgrading to RoundCube 1.2.4 (from 0.8.4) the LDAP search always becomes a prefix search, even if addressbook_search_mode is set to 0, and fuzzy_search is true.

Following the code, it looks like the $mode variable going into fulltext_search_filter in rcube_ldap.php line 843 is 4 (after being or'ed with SEARCH_GROUPS) - but fulltext_search_filter in rcube_ldap_generic.php line 335 does not seem to understand $mode = 4.

My LDAP server does not support VLV or groups.

**Comment by alecpl** [comment]
Looks like you might be right.

**Comment by alecpl** [comment]
How about this?
```diff
--- a/program/lib/Roundcube/rcube_ldap.php
+++ b/program/lib/Roundcube/rcube_ldap.php
@@ -840,7 +840,7 @@ class rcube_ldap extends rcube_addressbook
             }
 
             // compose a full-text-like search filter
-            $filter = rcube_ldap_generic::fulltext_search_filter($value, $attributes, $mode);
+            $filter = rcube_ldap_generic::fulltext_search_filter($value, $attributes, $mode & ~rcube_addressbook::SEARCH_GROUPS);
         }
 
         // add required (non empty) fields filter

```

**Comment by vidarberg** [comment]
That'll probably do it, I'll check it out.

**Comment by alecpl** [comment]
Fixed.
