### ISSUE TITLE
thread expansion icon disappears in widescreen view when new message is received

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#5714]
Hi.
I use 1.3-beta (version as of 5th of January 2017). No plugins.
I use widescreen view + threads.
Problem is that when new message is received in the inbox, then thread expansion icons disappear
![rc](https://cloud.githubusercontent.com/assets/24810145/24546334/0f66ed88-160b-11e7-92b7-24895859e8bd.jpg)

This issue may be related to this:
https://github.com/roundcube/roundcubemail/issues/5613
However I am not able to say if #5613 resolves it, because I don't run RC from github.

**Comment by alecpl** [comment]
What if you use Larry skin? Works for me with current code.

**Comment by rc-pl** [comment]
The same issue with Lary skin, but it may be that #5613 resolves this problem.
Thanks for confirmation.
