### ISSUE TITLE
No ability to block attachments

### ISSUE THREAD

**Issue by JamBoi** [roundcube/roundcubemail#5716]
In this time when attachments pose severe security and energy usage threats, it is unconscionable that RoundCube Webmail offers no ability to block attachments, especially those over a certain size or by file type.  Please prioritize this desperately needed feature.

**Comment by alecpl** [comment]
Could you explain more? This is a mail server responsibility to block messages of certain size or with attachments with insecure attachments. Not a client.

**Comment by CRtEurope** [comment]
RC is a client, not a server. You need to block extensions (attachments) on server side - for e..g on your postfix side if you use postfix with some regex commands. This is the wrong platform to discuss it.

**Comment by alecpl** [comment]
You can always write a plugin.
