### ISSUE TITLE
New users cannot log in

### ISSUE THREAD

**Issue by Zefiro** [roundcube/roundcubemail#5717]
I'm installing a new home server to replace my rather old one. I'm using Ubuntu Server 16.4 LTS and installed roundcube via the package manager. This got me version 1.2~beta+dfsg.1-0ubuntu1, with the option to have the DB set up for me. As I wanted to re-use my existing DB from the old installation, I opted out of that. I'm not aware of any migration logic.

I could log in with my existing users as expected. Then I wanted to log in with a new user, and got this message in /var/log/roundcube/errors
`[02-Apr-2017 18:39:40 +0200]: <73j76i0l> DB Error: [1364] Field 'alias' doesn't have a default value (SQL Query: INSERT INTO `users` (`created`, `last_login`, `username`, `mail_host`, `language`) VALUES (now(), now(), 'testuser2', 'localhost', 'en_US')) in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 540 (POST /mail/?_task=login?_task=login&_action=login)
[02-Apr-2017 18:39:40 +0200]: <73j76i0l> PHP Error: Failed to create new user in /usr/share/roundcube/program/lib/Roundcube/rcube_user.php on line 684 (POST /mail/?_task=login?_task=login&_action=login)
[02-Apr-2017 18:39:40 +0200]: <73j76i0l> PHP Error: Failed to create a user record. Maybe aborted by a plugin? in /usr/share/roundcube/program/include/rcmail.php on line 641 (POST /mail/?_task=login?_task=login&_action=login)`

Googling for it I only found this one German page:
https://www.debacher.de/wiki/Root-Server_mit_OpenSuSE_13.2
It states that this is because MySQL is now more picky about not giving a value for a column marked as "not null". The workaround would be to allow null values.

It also mentions this bug trac ID:
http://trac.roundcube.net/ticket/1489709

Since this bug tracker is not existing anymore, and I couldn't find any open bug with the search for "alias" on github, I'm opening this new issue for you to consider.

Thanks.

**Comment by alecpl** [comment]
Don't use beta releases! There's no alias column in users table in 1.2.4.

**Comment by alecpl** [comment]
I mean old beta releases. Sadly, it looks there's no active maintainer for Roundcube package in Ubuntu. You should install from vanilla release package.

**Comment by rmcaninch** [comment]
You might look at installing the ubuntu zesty package. It's newer (not current). If you want to stick with packages.
