### ISSUE TITLE
GPG signed message altered upon sending

### ISSUE THREAD

**Issue by wxl** [roundcube/roundcubemail#5718]
**NOTE**: this has nothing to do with Mailvelope or Enigma or anything other GPG solution expressly interacting with Roundcube, although I have a suspicion there may be some interaction with the issues expressed in #5504.

I made a message and signed it using `gpg --clearsign` and then pasted the result in a Roundcube 1.2.4 editor. I can confirm that this is properly signed if I paste it somewhere else and verify it with `gpg`. The message in Sent is immediately wrong, not to mention the message if sent to myself.

Specifically, the text consists of:

    Just testing
    
     testing

The resulting message ends up with an extra space before that second line:

    Just testing
    
      testing

Very curiously, the Roundcube displays the message properly in a fixed width font, but the message source is not the same.

I do have compose HTML messages set to never and use the plain text editor, too.

Following the exact same (albeit unnecessary) procedure in `mutt`, everything works fine.

That said, I'm left to conclude that something about Roundcube is seeing that space and adding another one for some reason.

**Comment by alecpl** [comment]
If this happens when you use plain text mode, then that's probably format=flowed. You can try with send_format_flowed=false.

**Comment by alecpl** [comment]
Note that Roundcube can also add footers to the message body, wrap it or do anything with it by plugins. So, this scenario is just not supported and probably never be.

**Comment by wxl** [comment]
Additional content outside of the signed message does not affect the validity of the signature. Regardless, how do we expect to support the full functionality of Mailvelope?
