### ISSUE TITLE
base_dn setting ignored inside group_filters after upgrade to 1.1.8

### ISSUE THREAD

**Issue by SergeyPV** [roundcube/roundcubemail#5720]
Updated Roundcube from 1.1.5 to 1.1.8 and found that the LDAP address book began working incorrectly. After making some debug I found that base_dn parameter inside any array included in group filters is ignored.

For example, I have:
$config['ldap_public']['Private'] = array(
 'name' => 'GLOBAL BOOK' ,
 'use_tls'       => false,
 'hosts'         => array('myaddress'),
 'port'          => 663,
 'ldap_version'  => 3,
 'use_tls'       => false,
 'network_timeout' => 30,
 'user_specific' => true,
 'base_dn'       => 'DC=some,DC=domain', //First dn
........
 'group_filters' => array(
    'users' => array(
      'name'    => 'somebook',
      'scope'   => 'sub',
      'base_dn' => 'OU=Users,DC=some,DC=domain', //Second dn
      'filter'  => '(objectClass=inetOrgPerson)',
      'name_attr' => 'sn',
    ),
    'customers' => array(
      'name'    => 'somebook2',
      'scope'   => 'sub',
      'base_dn' => 'ou=Clients,DC=some,DC=domain', //Third dn
      'filter'  => '(objectClass=inetOrgPerson)',
      'name_attr' => 'sn',
    ),
 ),
.......

After update "Second dn" and "Third dn" are always ignored and roundecube stubbornly use "First dn" for ANY LDAP search. All other options inside 'group_filters' work perfectly. As a result LDAP search is incorrect and I see the same search result in 'GLOBAL BOOK', 'somebook' and 'somebook2' (they should be different because of base_dn).

I temporary solved the problem by replacing the file "rcube_ldap.php" in roundcube 1.1.8 by the same file from previous version 1.1.5. The php script from version 1.1.5 still works fine.

Could you give us some patch to solve this problem?

**Comment by alecpl** [comment]
How about this:
```diff
--- a/program/lib/Roundcube/rcube_ldap.php
+++ b/program/lib/Roundcube/rcube_ldap.php
@@ -912,7 +912,7 @@ class rcube_ldap extends rcube_addressbook
     protected function extended_search($count = false)
     {
         $prop    = $this->group_id ? $this->group_data : $this->prop;
-        $base_dn = $this->group_id ? $this->groups_base_dn : $this->base_dn;
+        $base_dn = $this->group_id ? $prop['base_dn'] : $this->base_dn;
         $attrs   = $count ? array('dn') : $this->prop['attributes'];
         $entries = array();
 

```

**Comment by SergeyPV** [comment]
Sorry for delay. I've just tested and everything works fine.
Thank you for a patch.

**Comment by alecpl** [comment]
Fixed.
