### ISSUE TITLE
Password plugin: easier configuration for ldap

### ISSUE THREAD

**Issue by torbjo** [roundcube/roundcubemail#5724]
When configuring the password changing plugin with ldap, I found it slightly confusing.

I thought it was enough to just enable the plugin and add these lines to `config.inc.php`.

    $config['password_driver'] = 'ldap_simple';
    $config['password_confirm_current'] = true;
    $config['password_ldap_host'] = 'ldapi://';
    $config['password_ldap_userDN_mask'] = 'uid=%login,ou=users,dc=example,dc=com';
    $config['password_ldap_encodage'] = 'clear';

But it did not work untill I also added these:

    $config['password_ldap_version'] = '3';
    $config['password_ldap_pwattr'] = 'userPassword';

The error messages I got was not very help full in resolving the issue.

To be fair, the documentation does state "*Copy config.inc.php.dist to config.inc.php and set the options as described within the file*".

But it would be nice with some sane defaults for these settings.

I'll be glad to prepare a patch.

**Comment by alecpl** [comment]
Indeed, all options described as having a default value should have the default value set in the code in case the option is not set, i.e. as a 2nd argument of rcmail->config->get() call. Create a PR, please.

**Comment by torbjo** [comment]
Great! Done.
- - -
I did not touch `password_ldap_method`, since it already works. But it is (IMHO) implemented kind of fragile. https://github.com/roundcube/roundcubemail/blob/master/plugins/password/drivers/ldap_simple.php#L96

The documentation says it expects 'admin' or 'user', but it accepts every possible value, and behaves as 'user' on invalid values. Wouldn't it be better to throw an error on invalid values? Or show a warning in the log? I don't know what the current policies are.

**Comment by alecpl** [comment]
Merged.
