### ISSUE TITLE
Doesn't Put Signature Above Quoted Message

### ISSUE THREAD

**Issue by Multimastery** [roundcube/roundcubemail#5725]
Hello,

The bug is that signatures no longer appear above the message when replying (only below). I have tried the setting and it doesn't work anymore. Been having this error for the past several weeks. I have report it to my webhosts but they have no control or fix over this. This is a new flaw in your email system. Please check ASAP, thanks!

**Comment by alecpl** [comment]
This issue has been fixed in version 1.2.4 (#5628).

**Comment by Multimastery** [comment]
Well it doesn't look like it's fixed. I just tested it and it's doing the exact same thing. Where do I check the roundcube version? I assume it's the latest version being that it's integrated with my hosting company: Siteground

**Comment by rmcaninch** [comment]
Check under the About tab.

**Comment by Multimastery** [comment]
There is no about tab. This is integrated in Webmail through hosting accounts, so seems like it would already be updated.

**Comment by rmcaninch** [comment]
If you don't have an About tab. Contact the host. No telling what version they have.
