### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by lhermann** [roundcube/roundcubemail#5728]
I needed an SVG version of the roundcube logo, so I made one. Here it is if you would like to use it: http://files.codethink.de/lts/logo-roundcube.svg

Thanks for your great tool!

**Comment by thomascube** [comment]
Thanks for this. We actually also have an SVG version if the original logo which I just uploaded to Github: https://github.com/roundcube/roundcube.github.com/blob/master/images/roundcube_logo_icon.svg
