### ISSUE TITLE
Database schema check fails with all engines except mysql

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#5730]
Since a1f679adca mysql database schema is different than other databases. Table `dictionary` contains additional `id` column which is not used by other engines.

This is a problem for database schema check in rcmail_install::db_schema_check() which uses mysql.initial.sql file as a reference for all database engines. This causes the chack to fail with `Missing columns in table 'dictionary': id` for all engines except mysql.

**Comment by alecpl** [comment]
Fixed.

**Comment by Nepherim** [comment]
Just upgraded from 1.2.2 to 1.3.9 and have this same error.
