### ISSUE TITLE
persistens_login plugin gives error 500

### ISSUE THREAD

**Issue by andipfaff** [roundcube/roundcubemail#5731]
Version 1.2.4
When using the persistent login checkbox I receive HTTP 500 when trying to Login. 
PHP Fatal error:  Call to undefined method rcmail::setcookie() in .....\webmail\plugins\persistent_login\persistent_login.php on line 400

**Comment by alecpl** [comment]
We do not support this plugin. It should be `rcube_utils::setcookie()`.

**Comment by thomascube** [comment]
Please report this issue to the author of that particular plugin.
