### ISSUE TITLE
attachment issue

### ISSUE THREAD

**Issue by ternes3** [roundcube/roundcubemail#5734]
Hey there, 
i use currently roundecube 1.2.4. 

I have follwing issue, pdf files are plain text (.asc) and not visible. It doesnt matter if the file is downloaded or inline. Pictures are a pink box. 

mime_type and mime_magic are both null. 

Thunderbird works fine with the imap and smtp server. 

I use php7.1 and nginx as webserver.

**Comment by alecpl** [comment]
What do you mean plain text and not visible? Do you have mime magic database installed in your system at all? There kind of issues are configuration or PHP issues we can't do much about.

**Comment by alecpl** [comment]
No feedback.
