### ISSUE TITLE
Incorrectly creating new default identity upon login

### ISSUE THREAD

**Issue by medusared** [roundcube/roundcubemail#5736]
Since upgrading to roundcube 1.2.4 we have a strange issue where new identities are being created for some users when they login. We have $config['identities_level'] = 3 which shouldn't allow more than one identity but a new default identity is created meaning there are then two identities. This is a problem because (a) any user customisations to their identity are not in the new identity which is now used as the default and (b) we don't want to allow more than one identity as it is very confusing for users. We use sqlite and here are a couple of examples of multiple identities from the identities tables:

1|1|2017-04-22 18:25:12|0|1|||admin@thisisatestdomain.com||||0
2|1|2017-04-25 09:58:13|0|1|||admin@thisisatestdomain.com||||0

1|1|2017-04-22 18:20:31|0|1|Ian Smith||ian@anothertestdomain.com|||Regards
Ian Smith
123456789|0
2|1|2017-04-25 09:06:43|0|1|||ian@anothertestdomain.com||||0

Do you know why this is happening and how to fix it? I have already written and executed a script to delete the extra new identities from the sqlite dbs, but the new identity is simply recreated when the user next logs in! Why? How to stop it? Is this a known bug?

Many Thanks

**Comment by alecpl** [comment]
Why sqlite? While we support it, I wouldn't recommend to use it on a multi-user production installation. 

Anyway, what plugins do you use? Also, the user_id and identity_id does not make sense in your samples. Do both identities have the same user_id or different? Do you have also duplicates in users table?

**Comment by medusared** [comment]
sqlite is better for us - databases for each user are stored separately so easier to move users between servers, restore user accounts, disk space is allocated to the user etc. sqlite works well.

We use cpanel and a custom skin (roundcubeskins) which includes some plugins but none of this has changed, only the upgrade to RC 1.2.4 so I assumed it was the RC upgrade causing the problem.

The identity_id seems OK but the user_id is the same for both identities. This is the same for all the users that have two identities. None of them have more than one user listed in the users table. Only one extra identity is ever created so there are never more than 2 - it's like it doesn't see the existing default identity so creates a new one and then it's happy after that! I can't work out why the second one is being created though.

**Comment by alecpl** [comment]
It might be some plugin incompatibility. Roundcube creates new identities for new users only. So, either it thinks it is a new user (no record in users table, or select query does return the existing record), but in this case I'd expect some errors on insert to users table, or this is some plugin's fault.

**Comment by medusared** [comment]
There is definitely a single user listed in the users table for each user, with the correct email address matching the identity. So I can't see why it would think this is a new user. The plugins I have are:

        'xskin',
        'cpanellogin',
        'cpanellogout',
        'newmail_notifier',
        'zipdownload',
        'xcalendar',
        'xnews_feed',
        'xvertical_preview',
        'xmessage_list',

None of them have changed but I'll contact cpanel and the roundcubeskins people to see if their plugins could be causing this. Unless you can think of anything else that could be the cause? Thanks

**Comment by alecpl** [comment]
I don't know these plugins. Is their source publicly available? I'd propose to try without cpanellogin, but I wouldn't be surprise if it's caused by some sqlite hickup.

**Comment by medusared** [comment]
The plugins are mostly either related to the custom skin or cpanel. I'll contact those guys to see if they can shed any light on the matter
