### ISSUE TITLE
Session expired Message by using German Translation

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#5737]
For Authentication, i use the http_authentication Plugin. If i close the Browser, the Session should be destroyed (i hope so). If i change the GUI to use German Language and i reopen the Browser with the Inbox, i get the Message that the session is not valid or expired. I must reload the Browser and then im logged in. If i change the language to English (Us), the Login via http_authentication works as desired and i must not reload the Browser Window.

The same problem occurs, if i don't use the http_authentication Plugin.

**Comment by alecpl** [comment]
So, you say it depends on the Roundcube language? No, I can't believe that. There must be another difference.

When you close the browser the session is not destroyed. It expires after configured time (depending on system settings).

**Comment by Offerel** [comment]
I have played now a little bit and changed language and theme a lot. Now i get the Message "Your session is invalid or expired" also with English Language and Classic and Larry Skins. 

I don't know where this message come from, since after hitting F5 or reload the Browser Window, im successfully logged in.

**Comment by alecpl** [comment]
So, you see IP address of the client changes. You can disable this check in the config.

**Comment by Offerel** [comment]
I have now set $config['ip_check'] = false; and changed $config['session_storage'] = 'php'; (was memcache before). I hope it works now. Is there a way to destroy the Session, if the Browser Window closes?

Anyway, do you know a Way via PHP/HTML to set and destroy the http_basic Authentication Headers? This has nothing to do with Roundcube. I use http Authentication a lot with Nginx in my case and i use a Single htpasswd file for my Users in all my Apps. It would be cool, if i could use a html page to Login to all this Applications. If i search for this in Google, i have found only some examples with the help of JavaScript. But i would like to avoid Client Side Techniques for such things.

**Comment by alecpl** [comment]
No, there's no way to destroy session on browser window close. That's why most systems have Logout button.

You could try:
```
     header('WWW-Authenticate: Basic realm="My App");
     header('HTTP/1.1 401 Unauthorized');
```
but I guess the client-side magic is there for some reason.
