### ISSUE TITLE
Roundcube silently discards invalid recipients

### ISSUE THREAD

**Issue by dpc22** [roundcube/roundcubemail#5739]
Email addresses on our systems are typically accountname@domain

One of my users noticed that if they forgot the domain and enter the following into the To: dialogue on the compose screen:

  dpc99, dpc22@domain

and then click "Send", Roundcube silently drops the invalid "dpc99" part and transforms this into:

  dpc22@domain

Some testing reveals that this true of all versions of Roundcube from 1.0.2 to 1.3-rc. The culprit appears to be:

program/steps/mail/sendmail.inc

    function rcmail_email_input_format($mailto, $count=false, $check=true)
        ...
        foreach ($items as $item) {
            ...
            else if (trim($item)) {
                continue;
            }
I'm curious about the "continue". If I comment out that single line, Roundcube sticks up an error dialogue:

  Incorrect e-mail address: dpc99

which seems like more correct behaviour to me. What I am missing?

**Comment by alecpl** [comment]
While this is most likely my code, now when I look at it, it does not make much sense indeed.

First change that started ignoring such entries was c58c0aed (0.7.4), but before we did not validate them at all. We added validation later.

So, I think it makes sense to remove this `else if`.

**Comment by alecpl** [comment]
Fixed.
