### ISSUE TITLE
Modernized User Experience

### ISSUE THREAD

**Issue by martindale** [roundcube/roundcubemail#5743]
Roundcube is great, but the interface is clunky and dated.  Modernizing the interface could compel more users to choose Roundcube over other solutions — but an improvement to the experience of those of us who are already users would be an immediate gain.

**Wishlist:**
- [ ] **Responsive layout**: the mail client should progressively enhance from a basic HTML client up to a robust, AJAX-enabled single-page application, depending on client features such as viewport size and technology availability.
- [ ] **Offline-first support**: as a mail client, it'd be useful to have access to mail locally, without requiring a network connection.  Using `ServiceWorkers` and `IndexedDB`, we can provide an interactive version of the mail store which can later be synchronized with the server once network connectivity is again available.
- [ ] **Improved Visual Design & Appearance**: without incurring significant cost (in bytes), using a modern design for the visual theme of Roundcube would "freshen" the look and feel of the interface.  Off-the-shelf design libraries exist to provide simple, modern interfaces with reduced effort.

I've been using a packaged roundcube install for some time through [@MailInABox](https://github.com/mail-in-a-box/mailinabox), but I've just forked and cloned the source for the first time and I'm doing some digging around.  Wish me luck.

**Comment by alecpl** [comment]
We're already working on the new skin here https://github.com/roundcube/elastic. We have already tickets for these features.

**Comment by martindale** [comment]
Cool.  To save me some time, mind linking to each?
