### ISSUE TITLE
is it possible to switch to old 3 panel layout?

### ISSUE THREAD

**Issue by gnadelwartz** [roundcube/roundcubemail#5746]
if I remember correctly we had in the past a different panel layout:
![bildschirmfoto vom 2017-05-02 15-19-56](https://cloud.githubusercontent.com/assets/4593242/25619404/05a6c01c-2f4b-11e7-8137-b896fb87c844.png)
I found not option to switch back to this layout

**Comment by alecpl** [comment]
It is a "desktop" mode in the messages list options menu.

**Comment by gnadelwartz** [comment]
thanks! I was an unsusal place for me to look :-) I expected its in Options -> Preferences - User Interface

Can I change the default settings for new users in config.inc.php?
