### ISSUE TITLE
Roundcube 1.2.5 - Comment notations within style tag issues

### ISSUE THREAD

**Issue by stefanogironella** [roundcube/roundcubemail#5747]
Hi, I've noticed a strange behaviour after upgrading from RC 1.2.3 to 1.2.5.
HTML e-mails seems to be a little broken when dealing with "comment notations" in style tag.
Removing comments from the style tag, obviously, fix the issue.

This is how a test massage looks in RC 1.2.3:
![preview_1 2 3](https://cloud.githubusercontent.com/assets/6747447/25620592/371b6220-2f4f-11e7-85d5-ef4e19234223.png)

And this is how same message looks in RC 1.2.5 and 1.2.4 too (note the missing formatting, colors, ...):
![preview_1 2 5](https://cloud.githubusercontent.com/assets/6747447/25620614/4535d232-2f4f-11e7-9edb-6bd20469736c.png)

To reproduce this, I've used same configuration on both testing environments.

Attached below, the e-mail template used in this example.

[email-template.html.zip](https://github.com/roundcube/roundcubemail/files/970659/email-template.html.zip)

Anyone else is facing the same issue or have an idea on how to fix this?

Thanks

**Comment by thomascube** [comment]
Seems like the recently added `strip_tags` removes the entire style tag content... not quite what was intended.

**Comment by stefanogironella** [comment]
Do you refer to ./roundcubemail-1.2.5/program/lib/Roundcube/rcube_utils.php (line 505)?

`$out = strip_tags($out);`

Doing a quick test, commenting this line out, seems to fix my issue but I'm not aware of related drawbacks (if any).

**Comment by alecpl** [comment]
This was added to fix a security issue, so we can't just remove the command. We'd rather strip comments the way we do it in https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_washtml.php#L635.

**Comment by alecpl** [comment]
Actually we have to strip only the comment marks not the content inside. While this is an old technique to put comments inside the <style> tag it's not needed at least since 10 years. Anyway, we could remove those markers if found on the content start and end.

**Comment by stefanogironella** [comment]
Ok, fixed while reading messages but issue still remains when trying to reply a message containing comments within style tag.
Any help?

**Comment by alecpl** [comment]
Did it work before 1.2.5?

**Comment by stefanogironella** [comment]
I really don't know... but i think it should.

note: I've opened a new issue for that, do I have to close it?
