### ISSUE TITLE
PHP Error: Could not perform encryption

### ISSUE THREAD

**Issue by xingxing9688** [roundcube/roundcubemail#5749]
PHP Error: Could not perform encryption; make sure Mcrypt is installed or lib/des.inc is available in /usr/share/roundcubemail/program/lib/Roundcube/rcube.php on line 826 (POST /?_task=login?_task=login&_action=login)

This is due to what problems lead to？

**Comment by alecpl** [comment]
Looks like some old version we do not support. Anyway, looks like you miss some files. INstall php-mcrypt extension and it should work.
