### ISSUE TITLE
Style tag in HTML message ignored on reply

### ISSUE THREAD

**Issue by stefanogironella** [roundcube/roundcubemail#5751]
Issue still remains when trying to reply a message containing comments within style tag.

[Go to original issue](https://github.com/roundcube/roundcubemail/issues/5747)

Reading message:
![reading](https://cloud.githubusercontent.com/assets/6747447/25742477/f7f6a0d0-318f-11e7-9746-2af43449641e.png)

Replying to:
![replying](https://cloud.githubusercontent.com/assets/6747447/25742484/0126eb6a-3190-11e7-95ae-1bef910d9d42.png)

**Comment by alecpl** [comment]
Let's keep it as a separate issue. Before, I'll go to test this, could you check that the <style> tag is not empty in the page source code? This may be a TinyMCE issue.

**Comment by stefanogironella** [comment]
This is what I got (rename .txt files to .html, as editor don't leave me attach html files):

Full page source:
[full_page_source.txt](https://github.com/roundcube/roundcubemail/files/978982/full_page_source.txt)

This is the text-area content used by TinyMCE:
[text_area_content.txt](https://github.com/roundcube/roundcubemail/files/978985/text_area_content.txt)

And this is the same text-area content, after decoded html entities:
[text_area_content_decoded.txt](https://github.com/roundcube/roundcubemail/files/978986/text_area_content_decoded.txt)

Decoded content is what I expect to be there, maybe a TinyMCE issue?

**Comment by alecpl** [comment]
Looks like sthe tyle tag is removed by TinyMCE also if you put the whole source into the source input on https://www.tinymce.com/. I'm not sure if it was ever working.

**Comment by alecpl** [comment]
It can be fixed with
```
valid_children: '+body[style]'
```
in TinyMCE config, but it would require some more testing. It might not be safe to allow any style.

**Comment by alecpl** [comment]
This would cause all styles apply to body element or any content outside of the replied message body e.g. user entered text and signature. We don't want that, we'd need to make sure the styles apply only to the replied message content.

**Comment by alecpl** [comment]
Fixed.
