### ISSUE TITLE
Attackers might be able to set arbitrary SMTP servers

### ISSUE THREAD

**Issue by Arinerron** [roundcube/roundcubemail#5752]
https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L128

`$_SERVER['SERVER_NAME']` can be modified via the `Host` header. I'm not sure about the severity of this issue, but it's worth reporting.

See:
https://expressionengine.com/blog/http-host-and-server-name-security-issues
http://php.net/manual/en/reserved.variables.server.php
![screenshot](https://cloud.githubusercontent.com/assets/3926753/25749599/ed8d7c94-3163-11e7-9ca2-7bfa8374898c.png)

**Comment by alecpl** [comment]
I don't know if we can make Roundcube more secure by default in this context. It looks that the only option to prevent issues related to Host header spoofing is to implement host checker, like trusted_host_patterns in Drupal: https://www.drupal.org/node/1992030.

**Comment by phoikoi** [comment]
Just for purposes of research and planning on this issue, it might be worth noting that Django (the Python web framework) also has [a similar config setting](https://docs.djangoproject.com/en/1.11/ref/settings/#allowed-hosts).  It was introduced several years ago; here is [a link to the release notes for that version](https://docs.djangoproject.com/en/1.11/releases/1.4.4/) in case it might be helpful to look at their thinking on the issue in general.  Hope it helps you.

**Comment by Jean-Daniel** [comment]
This issue can be easily mitigated by properly configuring your web server as the Host header is also the one used to route to the target vhost. If your webmail is hosted on anything but the default vhost, the Host header is guarantee to be the vhost server name.

**Comment by alecpl** [comment]
Implemented.
