### ISSUE TITLE
Incorrect Azerbaijan week day names

### ISSUE THREAD

**Issue by 038291** [roundcube/roundcubemail#5753]
program/localization/az_AZ/labels.inc

65: - $labels['tue'] = 'Ç';
66: - $labels['wed'] = 'Ça';
67: - $labels['thu'] = 'C';
68: - $labels['fri'] = 'Ca';
-------------------------
65: + $labels['tue'] = 'Ça';
66: + $labels['wed'] = 'Ç';
67: + $labels['thu'] = 'Ca';
68: + $labels['fri'] = 'C';

#########################################

72: - $labels['tuesday']   = 'Çərçənbə';
73: - $labels['wednesday'] = 'Çərşənbə axşamı';
74: - $labels['thursday']  = 'Cümə';
75: - $labels['friday']    = 'Cümə axşamı';

72: - $labels['tuesday']   = 'Çərşənbə axşamı';
73: - $labels['wednesday'] = 'Çərçənbə';
74: - $labels['thursday']  = 'Cümə axşamı';
75: - $labels['friday']    = 'Cümə';

Please replace.

ps: examples:  https://www.timeanddate.com/calendar/custom.html?year=2017&country=85&lang=az&df=1

**Comment by alecpl** [comment]
Please, use Transifex service (https://www.transifex.com/roundcube/roundcube-webmail) for localization fixes.
