### ISSUE TITLE
Search in all folder does fail

### ISSUE THREAD

**Issue by peterkroon** [roundcube/roundcubemail#5756]
Steps to Reproduce.

- Create a folder named "MAIN"
- Create a folder in "MAIN" named "__test"
- Send an email to yourself with subject "FOLDER_SEARCH_TEST"
- When email received move email to folder "__test"
- Go to INBOX
- Set option in search: check all folder
- Type in field "FOLDER_SEARCH_TEST"
- Hit ``enter`` key

Expected result:  the email should be in the list

Given result: all email from inbox are shown

```

Roundcube Webmail 1.2.4

Copyright © 2005-2016, The Roundcube Dev Team

This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Some exceptions for skins & plugins apply.

Geïnstalleerde plug-ins

Invoegtoepassing	Versie	Licentie	Broncode
archive	2.4	GPLv3+	
filesystem_attachments	1.0	GPLv3+	
filters	2.1.6	GNU GPLv3+	Download
jqueryui	1.10.4	GPLv3+	
password	4.1	GPLv3+	
zipdownload	3.1	GPLv3+	

```

**Comment by alecpl** [comment]
Works for me. Try with disabled filters plugin. If there's still an issue, enable imap_debug and provide the log from when you hit Enter for search.

**Comment by peterkroon** [comment]
When ``filter`` plugin disabled search does work as expected

**Comment by peterkroon** [comment]
Proposed a fix here: https://github.com/6ec123321/filters/pull/25
