### ISSUE TITLE
Address Book Advanced Search - bug on gender

### ISSUE THREAD

**Issue by koljanep** [roundcube/roundcubemail#5757]
If I do an advanced search in the address book for anyone marked "female" it works fine but if I search for anyone who is marked "male" I get also females.

**Comment by alecpl** [comment]
Works for me. What version? What plugins? Try with disabled all plugins. What addressbook, the sql or ldap or other?

**Comment by rmcaninch** [comment]
In 1.1.5 (with some security patches), all plugins disabled, SQL addressbook. I see the same issue.

Female shows up in a search for male.

**Comment by alecpl** [comment]
Confirmed. I did a mistake while testing before.

**Comment by alecpl** [comment]
Fixed.
