### ISSUE TITLE
PHP 7.0 Support?

### ISSUE THREAD

**Issue by coderxx** [roundcube/roundcubemail#5758]
PHP 7.0 on LAMP stack running Apache2 on Ubuntu 16.04
======================================
I'm using **PHP 7.0** and have installed the **php7.0-zip** module. 
I'm unable to get it working yet.

Do I have to manually link a library?

Error:
`<mcqf5cmu> PHP Error: php_zip extension is required for the zipdownload plugin in /usr/share/roundcube/plugins/zipdownload/zipdownload.php on line 30 (GET /?_task=mail&_action=list&_refresh=1&_mbox=INBOX&_remote=1&_unlock=loading1494368935394&_=1494368935179)
`

**Comment by alecpl** [comment]
That's a PHP configuration issue/question. Ask on mailing list or forum, but it has nothing to do with Roundcube itself.

**Comment by coderxx** [comment]
@alecpl Does roundcube support PHP 7.0?

**Comment by alecpl** [comment]
Yes, since version 1.2.

**Comment by coderxx** [comment]
Then it must work? Is it not a bug in the program?

**Comment by alecpl** [comment]
The error says it's missing extension. So, it is a bug in the PHP configuration.

**Comment by coderxx** [comment]
Not true.
I have tested PHP Zip and it works fine.
My test file:
```
<?php 
        $zip = new ZipArchive; 
    $zip->open('test.zip'); 
    $zip->extractTo('unzipped/'); 
    $zip->close(); 
        echo "Ok!"; 
?>
```
This script seems to work perfectly - extracting files to the desired folder. phpinfo() shows that Zip extensions are loaded and functioning.

**Comment by alecpl** [comment]
In the browser or in CLI? They might use different configuration. Here's how we check for the extension: https://github.com/roundcube/roundcubemail/blob/master/plugins/zipdownload/zipdownload.php#L30

**Comment by coderxx** [comment]
This was working in browser. Will test in CLI. Thanks.
