### ISSUE TITLE
I can't get loggin to Roundcube recently installed iRedMail 0.9.6 with PostgreSQL

### ISSUE THREAD

**Issue by joseluisbz** [roundcube/roundcubemail#5760]
I want to test my recently installed my iRedMail with PostgreSQL.

https://my.mail.server/mail/?_task=login

Appears a page with title: **Roundcube Webmail :: Welcome to Roundcube Webmail**
According to iRedMail-0.9.6/iRedMail.tips
What is the Username in my case? because **postmaster@my.mail.server** is not working with password  of (Password for the main domain administrator).
What is the Password according to iRedMail.sh dialog?

I have this messages: "Connection to storage server failed."

How check if my installation was good and location log files?

My Linux Version is CentOS 7

**Comment by alecpl** [comment]
Ask on iRedMail forum. Logs are in logs directory.

**Comment by joseluisbz** [comment]
My password is correct, I don't know why I can't get access, Its a problem wihi Roundcube, because all another tools are working using my browser.
What is the specific log file of roundcube (where is located in installation time)?
