### ISSUE TITLE
Roundcube's personal adressbook won't open in IE and Chrome

### ISSUE THREAD

**Issue by JeroenvdBr** [roundcube/roundcubemail#5763]
Hi there,

Users of our roundcube mail cant  open, their personal adresbook, 
The button / link won't open the adress list when you use IE and Chrome.
Firefox users don't have this problem.

regards,

Jeroen van den Broek

**Comment by alecpl** [comment]
What version of Roundcube? What plugins? Any errors in log or in browser console?

**Comment by JeroenvdBr** [comment]
Its Roundcube versie 1.2.5
Plugins: blockspamsending en persistent_login
As far as I can see.. no errors in the console

**Comment by alecpl** [comment]
Do you use Google Analytics on the page? What Roundcube skin? You mean the button in top menu does not work, does not load the Addressbook page or what?

**Comment by JeroenvdBr** [comment]
Yes, we do use Google Analytuycs. We use the larry skin. Its the button 'Personal adressbook' in the top left when composing a new e-mail.
![webmail](https://cloud.githubusercontent.com/assets/28729525/26143580/e09e591e-3ae5-11e7-8a94-74bd3fdfdccc.jpg)

**Comment by alecpl** [comment]
Check this 9ff7b78c7e1f

**Comment by JeroenvdBr** [comment]
Thanks for the answer. It worked, we solved the problem.
