### ISSUE TITLE
plugin::enigma - issues with ubuntu-security-announce mails

### ISSUE THREAD

**Issue by ka7** [roundcube/roundcubemail#5764]
mails from 
ubuntu-security-announce@lists.ubuntu.com
( https://lists.ubuntu.com/mailman/listinfo/ubuntu-security-announce )

seem to be broken in general with enigma. (internal errors and/or invalid signature)
(other clients, like android with k9/openkeychain seems to work, so signatures are kind-of-valid )

--> might give some nice examples and corner-cases for further development
(the similar debian list works like a charm.. ;-) )

**Comment by alecpl** [comment]
What Roundcube version? Examples, please.

**Comment by ka7** [comment]
argh, sorry.
it's the debian jessie-backports package, version = 1.1.5 , so its old.
Thought I had install it fresh, but looks like I mixed stuff up.
(waiting for debian stretch/9, 1.2.3 -  there we will land)
