### ISSUE TITLE
since last update now the roundcube interface are "malware site"

### ISSUE THREAD

**Issue by mckaygerhard** [roundcube/roundcubemail#5765]
since apr 17, i updated to version 1.0.9 of roundcube and then my mail web interface are reported by google chrome and firefox as malware web site!

NOTE: versions 1.0.10 and 1.0.11 not have any changes respect that! it seems something in the js or html changes! i guest!

**Comment by alecpl** [comment]
Does it show the warning immediately on logon screen or later? Anyway 1.0 is in maintenance mode, you should upgrade to 1.2.

**Comment by mckaygerhard** [comment]
this happened since the stupid wannacry incident (that only affects stupid guindows OS) 

now firefox and chromiun does not allow to enter to my site unless some actions from users!

"you should upgrade" please i'm tyred of "upgrades" i upgrade to 1.1.X due i NOT GOIN UPDATE ENTIRE PHP AND MYSQL SYSTEM !

**Comment by alecpl** [comment]
We're not going to support old versions.

**Comment by mckaygerhard** [comment]
well then it's time to migrate to something that hear to the community.. u are acting like owncloud developers and u know what happened to
