### ISSUE TITLE
newmail_notifier plugin

### ISSUE THREAD

**Issue by ggrike** [roundcube/roundcubemail#5769]
Seems to have stopped working right around the time of the Junk Mail Filter fix.  None of my end users can see if they have new messages anymore in a minimized window or in a non active tab on the current window.  They just stopped working one day out of nowhere.  I thought it was something our email provider did but they didn't touch anything.  Any insight into this would be great since it is not very useful to have to keep checking to see if new mail has arrived.  We are using 1.2.4

**Comment by alecpl** [comment]
What fix are you talking about? What kind of notification does not work (desktop, sound, focus, all)? Specific web browser/version? What's the refresh interval in Preferences > User Interface > Main Options?

**Comment by ggrike** [comment]
I probably should have left the fix out as it is irrelevant.  About 2 to 3 weeks ago all of my round cube users stopped having the ability to see if they have new emails by looking at title on a minimized round cube window in ie11 or Google Chrome.  It used to be if they had it minimized that they could see a number in bold in the title that told them they had new emails.  I just learned that this coincided with the upgrade of our email providers c panel and round cube as they were both updated to new versions.  So in the previous version of round cube this told them how many new emails they had when minimized and now on 1.2.4 it no longer does that.  They all use a mixture of classic and Larry interfaces and there is nothing in the settings on the end user to change this feature, turn it on and off.  Any help is appreciated.  If it needs to be re-enabled on the server itself I can have my provider do that but it has worked the past 10 years and stopped at 1.2.4 update.  Let me know


Geoff GrikeDirector of Information TechnologyLester Glenn Auto Groupggrike@lesterglenn.com

-------- Original message --------From: Aleksander Machniak <notifications@github.com> Date: 5/23/17  2:48 AM  (GMT-05:00) To: roundcube/roundcubemail <roundcubemail@noreply.github.com> Cc: ggrike <ggrike@lesterglenn.com>, Author <author@noreply.github.com> Subject: Re: [roundcube/roundcubemail] newmail_notifier plugin (#5769) 
What fix are you talking about? What kind of notification does not work (desktop, sound, focus, all)? Specific web browser/version? What's the refresh interval in Preferences > User Interface > Main Options?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/roundcube/roundcubemail","title":"roundcube/roundcubemail","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/roundcube/roundcubemail"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alecpl in #5769: What fix are you talking about? What kind of notification does not work (desktop, sound, focus, all)? Specific web browser/version? What's the refresh interval in Preferences \u003e User Interface \u003e Main Options?"}],"action":{"name":"View Issue","url":"https://github.com/roundcube/roundcubemail/issues/5769#issuecomment-303305946"}}}

**Comment by alecpl** [comment]
The newmail_notifier plugin can change the icon to contain a star, but not a number. The number in the title is added by the core functionality. What version were you using before the upgrade?

**Comment by ggrike** [comment]
My contact at the email company said it should only have been a minor release update on our server so he believes it was 1.2.2

 

 

Geoff Grike

Director of Information Technology

Lester Glenn Auto Group

(732) 349-4200 ext 14313

Direct Line: (732) 557-7888

 <mailto:ggrike@lesterglenn.com> ggrike@lesterglenn.com

**Comment by alecpl** [comment]
I see nothing related in the changelog. Please, make sure refresh interval is set and try with disabled all plugins. Works for me.

**Comment by ggrike** [comment]
I had our server people change the refresh rate and that seemed to get it working again on some of our pcs.  I am sure the ones still not working is browser setting related so that should be easy to rectify.  Thanks for your assistance in this

 

 

Geoff Grike

Director of Information Technology

Lester Glenn Auto Group

(732) 349-4200 ext 14313

Direct Line: (732) 557-7888

 <mailto:ggrike@lesterglenn.com> ggrike@lesterglenn.com
