### ISSUE TITLE
Images In Junk Folder

### ISSUE THREAD

**Issue by Huendli** [roundcube/roundcubemail#5770]
Remote images (HTML embed I suppose) are blocked in the Inbox (yellow bar with option to display them), but not in Junk folder. This is annoying as it always confirms spammers that the address they've used is valid and active, especially since I have to open at least two of the Junk messages in order to delete them (no 'empty Junk folder button').

Roundcube Webmail 1.2.1

**Comment by alecpl** [comment]
Works for me. Update to most recent version. Check with disabled plugins.
