### ISSUE TITLE
Not working Calendar and Task

### ISSUE THREAD

**Issue by chusmsanchez** [roundcube/roundcubemail#5771]
First, thank you all for your contribution of roundcube plugins.

I have installed Calendar and Task following all the steps of the manual, but I get the following problem:

-I go to roundcube and enter Calendar: If I want to add a new calendar, it works correctly and registers well in the database, but if I want to create a new event, when saving the event I get a "500 Internal Server" error and Does not show the event, but if I access phpmyadmin, I see that it has been correctly registered in the database.

- I do not care about homework.

Sorry my english is not very good, thank you.

**Comment by alecpl** [comment]
We do not support these plugins. In case of 500 error you should see an error in the Roundcube or webserver logs.

**Comment by chusmsanchez** [comment]
Could you tell me where to go for the kolab calendar plugin support?

How can I see the error in the Roundcube?

Thank you

**Comment by thomascube** [comment]
> Could you tell me where to go for the kolab calendar plugin support?

https://kolab.org/

> How can I see the error in the Roundcube?

https://github.com/roundcube/roundcubemail/wiki/Howto-Report-Issues#how-to-use-the-logs
