### ISSUE TITLE
mariadb 10.2 syntax error

### ISSUE THREAD

**Issue by panayotb** [roundcube/roundcubemail#5774]
Roundcube 1.2.5
MariaDB 10.2

MariaDB does not like when 'rows' is used as column name. The query is in rcube_contacts.php
in "private function _count()"

Error log:

26-May-2017 19:59:33 +0300]: <f66r76ge> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows FROM `contacts` AS c WHERE c.`del` <> 1 AND c.`user_id` = '2' AND ((((`emai' at line 1 (SQL Query: SELECT COUNT(c.`contact_id`) AS rows FROM `contacts` AS c WHERE c.`del` <> 1 AND c.`user_id` = '2' AND ((((`email` LIKE 'example@example.com' OR `email` LIKE 'example@example.com,%' OR `email` LIKE '%,example@example.com,%' OR `email` LIKE '%,example@example.com'))))) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php

**Comment by alecpl** [comment]
It is indeed reserved word in MySQL. I suppose we can just rename that alias to `cnt`.

**Comment by alecpl** [comment]
Fixed.

**Comment by andipfaff** [comment]
The correct syntax if using reserved words should be:
...  AS `rows` FROM contacts ...

use backticks to enclose reserved word
