### ISSUE TITLE
Navbar view problem

### ISSUE THREAD

**Issue by fodorgeza** [roundcube/roundcubemail#5775]
Please try to log in on a machine that has portrait screen. You will see, that the navbar cannot fit, generates a horizontal scrollbar. When you navigate to the settings menu, the navbar fixes itself but navigate back (email view) it appears wrong again.

**Comment by alecpl** [comment]
Could you be more precise? What screen size? What browser? Screenshots, please.

**Comment by fodorgeza** [comment]
I tested it on Chrome and Firefox browsers, the screen resolution was 1200x1600. 
![image](https://cloud.githubusercontent.com/assets/22645914/26553576/87638206-448c-11e7-9d03-8b8095ad0461.png)

**Comment by alecpl** [comment]
This is not our theme/skin. It should not happen with Larry skin. Does it happen with Larry? What version?

**Comment by fodorgeza** [comment]
Hm... You're right, sorry. This is the Droid skin based on Larry, created by Roundcubeplus.
