### ISSUE TITLE
CSRF message when tab reloading tab

### ISSUE THREAD

**Issue by cellsheet** [roundcube/roundcubemail#5776]
Hello, I have an issue with the CSRF mechanism implemented in roundcube. After I login and I close the tab with roundcube if I didn't logout, and re-open the tab, I get the message regarding the CSRF warning.

I could think of a million reasons why someone didn't logout before closing the tab (persistent login plugin, restarting chrome, rebooting without closing chrome, power outage, etc). I do not for this reason it is practical to assume the user can successfully close their session in the same time they opened it without these things occurring sometimes.

Is there a way to disable this or at least move it into config.php, or even make this a plugin? I believe this should be left up to the user if they want to enable it due to the aforementioned reasons. I cannot imagine what would happen to gmail if no-one could suddenly re-access email if everyone just forgot to log out.

EDIT: Deleting line https://github.com/roundcube/roundcubemail/blob/master/index.php#L252 fixes it, however I would like to see this addressed regarding these scenario's.

**Comment by alecpl** [comment]
What version? Looks like you're using use_secure_url=true, right? Then there should be a link below the warning, clicking it should open the requested page.

This is CSRF protection, user has to "confirm" he's not a (hacker) robot. I don't see how that could be improved.

**Comment by cellsheet** [comment]
For me it shows "Please contact your server administrator", no link to resume your session. I also had that disabled, which I think I'll be re-enabling. That could have been possibly the issue? Roundcube 1.2.5 complete.

**Comment by alecpl** [comment]
How exactly do you "re-open the tab"? What URL are you using?

**Comment by cellsheet** [comment]
Essentially I just opened a new tab, copy/pasted the roundcube root folder where I login to, and it displays the message. That or just simply deleting `?_task=mail&_mbox=INBOX` off the URL then loading that.

**Comment by alecpl** [comment]
I'm not able to reproduce.

**Comment by cellsheet** [comment]
I don't know if I cleared everything, but even after wiping the whole roundcube install, and dropping the database, it still persisted. I don't know if I left anything out though..

**Comment by alecpl** [comment]
I believe you. There's indeed a code that displays the warning without the link. It's used in rare cases (but valid imo) However, I can't reproduce it with the steps you describe. Maybe be more precise. So, what browser, what URLs (precisely, what was the url before you closed the tab and what is the URL of the new tab, do you close the browser or only the tab), what timings (you do this immediately or wait some time), where you click and what you press?

**Comment by cellsheet** [comment]
I think it started happening after I installed a few plugins, notably the google authenticator 2fa, and persistent login. However, since then I wiped the directory and then I was able to still reproduce this on first use. I also did `delete from session` in the roundcube table before clearing the cache as well as cookies for the login portal and hard reloading it.

**Comment by alecpl** [comment]
According to https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php#L972 there are two possibilities:
- the session cookie is not set
- security token is not set or is different than the one in session and POST is not empty.
And one more is that you have referer_check=true and Referer mismatch is detected.

So, how precisely do you re-navigate to the page?

**Comment by cellsheet** [comment]
I will either delete every part of the url except the part for the root of the roundcube install part, so like in my case, I have it in the mail folder in `/home/www/mail`, and I will go to `https://example.com/mail` to login. So while a session is active, I will delete everything from the url to match `https://example.com/mail`, and press enter to load it. That or just ctrl+n for new tab, and load `https://example.com/mail`. With that being said, I can check my headers too once I get another unrelated issue resolved if needed against those conditions.

**Comment by alecpl** [comment]
Not sure it's the problem here, but your rewrite regexp is wrong (old). For version >=1.2 it should be `rewrite "^/mail/[a-zA-Z0-9]{16}/(.*)" /mail/$1;`. But you don't use use_secure_urls=true, right?

I see no roundcube_sessauth cookie in the second request headers you provided.

**Comment by cellsheet** [comment]
That would be correct, I have the feature set to false because of bad re-writes from the regex

**Comment by alecpl** [comment]
No feedback.

**Comment by ajuanjojjj** [comment]
Happened to me today; navigating to the inbox via the left menu fixed it. Using chrome 96.0.4664.110 and Roundcube Webmail 1.4.11 via Plesk, and Apache 2.4.41 and Nginx 1.20.1. It did not have the resume sesion link, rather "Please contact your administrator". Happy to provide more info (assuming i'm able to get it)
