### ISSUE TITLE
managesieve plugin does not work with gssapi / krb_authentication plugin

### ISSUE THREAD

**Issue by dl8bh** [roundcube/roundcubemail#5779]
Hi guys,

after I finally managed to configure gssapi / krb_authentication correctly, I failed to get the managesieve plugin running with this setup.
After a bit of research, I found out, that this functionality is not included in the managesieve plugin.

For gssapi / Kerberos enabled environments, this would be really nice to have.

Best regards,

Bernd

**Comment by alecpl** [comment]
We have some code in rcube_imap_generic so it shouldn't be very hard to copy it to Net_Sieve. Patches welcome.

**Comment by neilmunday** [comment]
Hi,

As suggested I have updated the Net_Sieve class and also the ManageSieve plugin to work with my modification.

See the two pull requests above for details.

**Comment by alecpl** [comment]
Done. Requires Net_Sieve 1.4.3.

**Comment by dl8bh** [comment]
Wow, cool, will definitely check this out!
