### ISSUE TITLE
[wiki] Install information confusing / out-of-date regarding Mcrypt (I think)

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#5780]
I'm not sure, but some searching seems to suggest that Mcrypt is no longer used by current roundcube (1.2.5).

The install requirements don't mention it:
https://github.com/roundcube/roundcubemail/wiki/Install-Requirements

but the wiki install instructions do:
https://github.com/roundcube/roundcubemail/wiki/Installation

They say to install php5-mcrypt.

Mcrypt is of course obsolete, unmaintained, and deprecated:
http://php.net/manual/en/intro.mcrypt.php

So hopefully roundcube doesn't actually use it, and if so there's a few lingering places to un-document it.

**Comment by alecpl** [comment]
Roundcube >= 1.2 does not use it, indeed. These install scripts in the wiki are outdated. I'd remove them.

**Comment by alecpl** [comment]
Fixed wiki page.
