### ISSUE TITLE
[dev docs] Is there an overview of all actions used by roundcubemail, task mail

### ISSUE THREAD

**Issue by pimlie** [roundcube/roundcubemail#5787]
For my [pimlie/authres_status](https://github.com/pimlie/authres_status) plugin I check within the `init` method which `action` is requested so i add the correct hooks for that action.

Last week I fixed 2 issues that were caused by not listing the required action in one of the `if`'s, so now I am looking for an overview of all available `action`'s in roundcubemail (but at least the task `mail`). Unfortunately I am unable to find such a listing in the Wiki or docs. Does it not exists or am I just a bit cross-eyed?

**Comment by alecpl** [comment]
There's no overview. Plugins can also add actions. To get a list of basic mail actions you generally have to list files in `program/steps/mail/` (that will be their names without the extension). Also you should check for $RCMAIL->register_action_map() call in 'program/steps/mail/func.inc' (that adds some of action aliases).

For your specific plugin, I don't think you should do action checking. Just register hooks no matter what's the current action.
