### ISSUE TITLE
rcube_utils::bin2ascii Uninitialized string offset

### ISSUE THREAD

**Issue by oittaa** [roundcube/roundcubemail#5788]
`$char & $mask` can have larger values than the length of `$hextab`

See for example: https://3v4l.org/0RLI6

**Comment by alecpl** [comment]
Yeah. I don't want to extend the $hextab with non-alpha characters. It looks that we don't expect this function to return a result that could be converted back to binary. It's used only to make a binary (random data) safe for use in URLs, etc.

So, I'll just propose to add "01" at the end of $hextab so its length is 64.

**Comment by oittaa** [comment]
You're using it to generate passwords and other critical data. Adding 01 to the end pretty much guarantees a new CVE. Those two characters would be twice as likely as others.

**Comment by alecpl** [comment]
So, $nbits=5 is the only possible change I can think of if we don't want to add more chars to the set.

**Comment by oittaa** [comment]
That's a possibility.

Aren't `-` and `_` safe characters in urls? I don't know if the resulting strings are used somewhere else, where those might be a problem.

**Comment by alecpl** [comment]
They are safe, but I wouldn't like to see them on the beginning or end of the resulting string. And it would require some configuration changes for those using use_secure_urls=true. Maybe some code changes too.

**Comment by oittaa** [comment]
I don't know if you're willing to add extra dependencies, but you might want to consider adding https://github.com/paragonie/random_compat to composer.

Then you could simplify the whole `rcube_utils::random_bytes()` function to something like the following:
```
	public static function random_bytes($length, $raw = false)
	{
		if ($raw) {
			return random_bytes($length);
		}

		$hextab = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
		$result = '';
		while(strlen($result) < $length) {
			$result .= $hextab[random_int(0, strlen($hextab) - 1)];
		}
		return $result;
	}
```

That would keep all 62 character possibilities. Example: https://3v4l.org/QLWQc

**Comment by oittaa** [comment]
That happens only on completely broken systems without any random sources. 

But whatever you do, just remember that the current fallback to OpenSSL isn't completely safe either. IMHO it's better to throw an exception on a broken systems than[ let people generate "randomness" that isn't safe to use](https://www.google.com/search?q=php|python|ruby+cve+random).

**Comment by alecpl** [comment]
We'll consider using random_int() in future versions. For now I'm going to fix this with this function:
```
public static function bin2ascii($input)
{
    $base62_convert = function($char) {
        $hextab = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
        $num    = ord($char);
        $result = '';
        do {
            $result = $hextab[$num % 62] . $result;
            $num    = intval($num / 62);
        }
        while ($num > 0);

        return $result;
    };

    return implode('', array_map($base62_convert, str_split($input)));
}
```

**Comment by oittaa** [comment]
That function is in no way suitable for password generation.

Do you realize there's going to be a huge bias? Do you have any members in your team who could help you with these functions that are security critical?

https://3v4l.org/PhAsW

**Comment by oittaa** [comment]
It's better, but the first 8 letters in `$hextab` are 5/4 more likely than others (https://3v4l.org/bTKUt) as 4*62=248 < 256. Probably not a huge deal, but at least keep in mind that you really should use just `random_bytes` and `random_int` here, when you move to PHP 7.0 or add random_compat dependency.

**Comment by alecpl** [comment]
Fixed.
