### ISSUE TITLE
[1.3-rc] preview pane setting is not saved

### ISSUE THREAD

**Issue by xkpd3** [roundcube/roundcubemail#5791]
Hello,

In 1.3-rc, the `$config['preview_pane']` setting has no effect anymore and is being removed from the config by the upgrade script.

However, when enabling the preview pane on the UI by setting it to "Desktop" or "Widescreen", the setting is not saved. Refreshing the browser (F5) will disable the preview pane again.

Best Regards,
Stefan

**Comment by alecpl** [comment]
Works for me. What skin? What browser?

Note that `preview_pane` option does not exist anymore. Now we use `layout`.

**Comment by xkpd3** [comment]
It is reproducible with Chrome and Firefox. I'm hosting roundcube on NGINX with php 5.6.30.

**Comment by xkpd3** [comment]
I figured it out! The issue was, that I installed pear (the new roundcube dependency) without actually restarting php-fpm. Once I did that, the layout saving started to work!

Strange enough, that everything else was saved, just not the preview pane position.
