### ISSUE TITLE
UID MOVE: IMAP 

### ISSUE THREAD

**Issue by Math94** [roundcube/roundcubemail#5793]
Hi, 

On my Roundcubemail (Gandi), I have a problem. My problem is that the client sometimes multiplies the mail in several times. And I can not delete these mails because I have an error: **UID MOVE: IMAP session state is inconsistent.**
I use outlook to read my mails but this error is in webmail rouncube. I don't know how to resolve that. 

Thanks

**Comment by alecpl** [comment]
Looks like an imap server issue.
