### ISSUE TITLE
RoundCube does not recognize Maria

### ISSUE THREAD

**Issue by ncswi** [roundcube/roundcubemail#5794]
New to the forum, but lifelong linux guy.  It appears MySQL has completed their fork to MariaDB.  Just installed new Fedora25 version.  Roundcube does not recognize mysql as being installed.  Just retested this issue (prior to posting this) on a new  barebones rebuild of F25 and same issue is found.  In previous versions of Fedora, rpm -qa | grep -i mysql would still return packages named mysql.  In this latest Fedora release, this is not the case.  rpm -qa returns nothing, even tho Mariadb is installed and running.  Additionally, the php5-mysql package is no longer available for F25 and newer.  This package is completely depricated now.  We could really use a patch for this issue, so we can get our Webmail back up and running.

**Comment by alecpl** [comment]
There's no separate driver in PHP for MariaDB. Roundcube uses http://php.net/manual/en/ref.pdo-mysql.php and the check in the installer is looking for pdo_mysql extension. So, I guess the package will be php-pdo-mysql or sth like that.
