### ISSUE TITLE
links disappearing when signature conversion html to plain text (reopen #4473)

### ISSUE THREAD

**Issue by chaos-prevails** [roundcube/roundcubemail#5795]
Hello,

I posted some days ago a comment on bug #4473 because I still experience the issue with roundcube 1.2.1. I tried it out with another identity and a minimal html signature and the same issue occurs.

steps to reproduce:
1. create a new identity with a html signature, enter below code html into the source code window, click save
....
```
text before <a href="http://link1">
<img style="border: 0; width: 215px; height: 16px;" src="http://link1.logo-text.png" width="215" height="16">
</a> text after
```
....

2. compose a new message, choose "plain text" as type
3. the link will not show

expected outcome:
the link should be visible (and underlined) in the plain text-converted signature e.g.:
http://link1

Also, when I add text instead of the image within the a href tag, the link gets lost and only the text stays. I think it would be preferable to show the href attribute instead.

**Comment by alecpl** [comment]
That's not exactly the same issue. The problem comes probably from the fact that you use an image inside of the link. So, when we remove the image the link becomes empty. I'm not sure maybe it could work if the `<img>` had an `alt` attribute. Anyway, it probably indeed makes sense to use link's `href` as the text in such cases.

**Comment by chaos-prevails** [comment]
hello,
thank you for your reply. no the alt attribute is not helping and I think it would also not be useful when the image is inside a a-href tag. Rather, the href attribute should be shown.

**Comment by alecpl** [comment]
So, for both:
```
this is <a href="http://test.com">test</a>
```
and 
```
this is <a href="http://test.com"><img src=http://other.com/image" alt="test" /></a>
```
output should be:
```
this is http://test.com
```
Right?

**Comment by alecpl** [comment]
Actually I decided that it makes sense only for cases when the link text is empty like with the image above. Fixed.

**Comment by chaos-prevails** [comment]
thank you! Wouldn't it be in both of your described cases be useful (also for a tags with text inside)?

**Comment by alecpl** [comment]
I think it would depend on the context. Imho, current solution is more likely to match expectation of most of the users. And you can always use HTML if something's wrong with the conversion.
