### ISSUE TITLE
Roundcube Migration Errors

### ISSUE THREAD

**Issue by jerbear05** [roundcube/roundcubemail#5797]
I have a standalone Apache web server as well as MySQL database standalone for hMailserver. I also installed PHP 5.xx and copied it to c:\php. Somehow I am getting errors " ';echo' " and telling me they changed the confi files structure. I am on http://localhost/installer and that is the roundcube page saying those errors. I have yet to figure out how in the world to get this working. I have my own working hMailserver email with Thunderbird, but want to get a webmail going. Please help and guide! I have it on a Windows Vista machine. I created the sql database, tried to follow the guides out there but no luck.

**Comment by alecpl** [comment]
That does not look like a bug. Ask on mailing list or forum.
