### ISSUE TITLE
Viewing email attachment from TNEF format causes Apache Internal Error 500 

### ISSUE THREAD

**Issue by Agnis-LV** [roundcube/roundcubemail#5799]
In file `/program/steps/mail/get.inc` line ` 328` may rise apache internal error 500
`header("Content-Disposition: $disposition; filename=\"$filename\"");`
reason beeing a bad file name containing illegal characters.

In my debug example the attachement file name should look like "Pavadzīme (lv) EL7877 .pdf"  but from winmail.dat it gets decoded with some non-ascii chars in it "Pavadz+me (lv) EL7877     .pdf".

It looks like in file
`/program/lib/Roundcube/rcube_message.php` 
the function `function fix_attachment_name(..)` is not fixing the file name properly.

Attached is original email causing this issue. 
[email.txt](https://github.com/roundcube/roundcubemail/files/1081396/email.txt)
[winmail.zip](https://github.com/roundcube/roundcubemail/files/1081398/winmail.zip)

My setup: roundcube 1.2.5; PHP 5.4.16; Apache/2.4.6 (CentOS 7)

**Comment by alecpl** [comment]
That's likely caused by two issues here: #5646 and #5772.

**Comment by alecpl** [comment]
Fixed.

**Comment by Agnis-LV** [comment]
Tried to apply commits 0bef84c and b4c877b.

Found that in
./program/lib/Roundcube/rcube_tnef_decoder.php
function convertString() line 
`$str = rtrim($str, "\0");` maybe strips too much from right side.

In my debug example bin2hex string before rtrim is
`500061007600610064007a002b016d006500200028006c0076002900200045004c003700380037003700200020002000200020002e007000640066000000`
but afterwards it is 
`500061007600610064007a002b016d006500200028006c0076002900200045004c003700380037003700200020002000200020002e007000640066`
and therefore UTF-16LE -> UTF-8 mb_convert_encoding truncates the last char.

**Comment by alecpl** [comment]
@Agnis-LV Thanks. The rtrim() is probably not needed here at all, but I moved it to the end of the method, so it's called after charset conversion.
