### ISSUE TITLE
Generic CSS class in managesieve plugin impacts other plugins

### ISSUE THREAD

**Issue by JohnDoh** [roundcube/roundcubemail#5800]
The managesieve plugin uses a CSS class a.button and because manageseive.css is always included when ever you are in the Settings section of Roundcube then the CSS can mistakenly be applied to other plugins. This means that other plugins have to first override the CSS from managesieve before adding their own if they also wish to use the CSS class a.button.

 From [managesieve/skins/larry/managesieve.css](https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/skins/larry/managesieve.css#L283) line 283
```css
a.button
{
  margin: 0;
  padding: 0;
}
```

**Comment by alecpl** [comment]
All a.button styles there should be prefixed with `#filter-form .rowbuttons`.

**Comment by alecpl** [comment]
Fixed.
