### ISSUE TITLE
Add UI option in composition window to disable format=flowed

### ISSUE THREAD

**Issue by simark** [roundcube/roundcubemail#5801]
I sometimes have to send a patch as a reply in Roundcube.  Obviously, patches don't play well with format=flowed.  For these occasions, it would be nice if I could simply untick a box in the composition window to disable format=flowed for this message.

**Comment by alecpl** [comment]
That would be not only disabling format=flowed itself, but also line wrapping, right?

**Comment by simark** [comment]
Yes, probably (I'm not really aware of the different processing steps).  I think you got the idea, that it wouldn't do any formatting and send the text "as-is".

**Comment by alecpl** [comment]
I just noticed that we already have #5101.
