### ISSUE TITLE
enigma: Unknown error importing GPG key (when creating new key)

### ISSUE THREAD

**Issue by mejo-** [roundcube/roundcubemail#5806]
Hello,

I just gave the enigma plugin a first try and faced an issue when trying to create a new key. Seems like only the public key is imported and I always get the following error message:

> [20-Jun-2017 04:22:21 +0200]: <pd9v9n3i> PHP Error: Enigma plugin: Unknown error importing GPG key. Please use the 'debug' option when creating the Crypt_GPG object, and file a bug report at http://pear.php.net/bugs/report.php?package=Crypt_GPG in /var/www/roundcube/plugins/enigma/lib/enigma_engine.php on line 1074 (POST /?_task=settings&_framed=1&_action=plugin.enigmakeys)

I'm using latest Roundcube (1.2.5) on an up-to-date Debian Stretch system with PHP 7.0 running as FCGI.

The enigma debug log shows the following:

> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --always-trust --homedir '/var/www/roundcube/plugins/enigma/home/user@example.org' --version
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: BEGIN PROCESSING
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG output stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG output
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 643 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 3
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG output stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG output
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 0 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG error stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG error
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 0 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG status stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG status
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 0 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: END PROCESSING
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: CLOSING GPG SUBPROCESS
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: USING GPG 2.1.18 with PHP 7.0.19-1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: OPENING GPG-AGENT SUBPROCESS WITH THE FOLLOWING COMMAND:
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: /usr/bin/gpg-agent --daemon --options /dev/null --csh --keep-display --no-grab --ignore-cache-for-signing --pinentry-touch-file /dev/null --disable-scdaemon --no-use-standard-socket --pinentry-program '/var/www/roundcube/vendor/pear-pear.php.net/Crypt_GPG/Crypt/GPG/../../bin/crypt-gpg-pinentry' --homedir '/var/www/roundcube/plugins/enigma/home/user@example.org'
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: CLOSING GPG-AGENT LAUNCH PROCESS
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG-AGENT LAUNCH PROCESS CLOSED
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --homedir '/var/www/roundcube/plugins/enigma/home/user@example.org' --import
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: BEGIN PROCESSING
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG is ready for input
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to write 3627 bytes to GPG input
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => wrote 3627 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG is ready for input
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to write 0 bytes to GPG input
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => broken pipe on GPG input
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => closing pipe GPG input
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG status stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG status
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 260 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: STATUS: KEY_CONSIDERED 6F89626CF2CDC19AE4E8EBEB2351619FEAB05C0E 0
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: STATUS: IMPORTED 2351619FEAB05C0E user <user@example.org>
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: STATUS: IMPORT_OK 1 6F89626CF2CDC19AE4E8EBEB2351619FEAB05C0E
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: STATUS: KEY_CONSIDERED 6F89626CF2CDC19AE4E8EBEB2351619FEAB05C0E 0
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG error stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG error
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 78 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: ERROR: gpg: key 2351619FEAB05C0E: public key "user <user@example.org>" imported
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG status stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG status
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 36 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: STATUS: PINENTRY_LAUNCHED 27580   
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG error stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG error
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 233 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: ERROR: gpg: key 2351619FEAB05C0E/2351619FEAB05C0E: error sending to agent: No passphrase given
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: ERROR: gpg: error building skey array: No passphrase given
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: ERROR: gpg: Total number processed: 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: ERROR: gpg:               imported: 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: ERROR: gpg:       secret keys read: 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 3
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG output stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG output
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 0 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG error stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG error
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 0 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG status stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG status
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 50 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: STATUS: IMPORT_RES 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: selecting streams
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => got 1
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: GPG status stream ready for reading
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => about to read 65536 bytes from GPG status
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => read 0 bytes
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: END PROCESSING
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: CLOSING GPG SUBPROCESS
> [20-Jun-2017 04:26:52 +0200]: <pd9v9n3i> GPG: => subprocess returned an unexpected exit code: 2

**Comment by mejo-** [comment]
Just tested the import of a secret key and got exactly the same error.

**Comment by alecpl** [comment]
You need Roundcube 1.3 for GnuPG 2.1 support.

**Comment by mejo-** [comment]
Ah, thanks for the explanation. Will give 1.3 a try soon.
