### ISSUE TITLE
Fatal error when using DMY- or MDY-based date format in PostgreSQL

### ISSUE THREAD

**Issue by ccastello** [roundcube/roundcubemail#5808]
If you use a postgresql existing database with a different date style of ISO, there may be problems and a blank page...
the solution : 
alter database roundcube set datestyle = 'ISO';

**Comment by alecpl** [comment]
Could you check the error log so we know what error it was exactly? We may find a solution for specific part of the code or apply some date format setting on DB connection/session (as we do for MSSQL) e.g. `SET DATESTYLE ISO;` (we already call `SET NAMES...`).

**Comment by ccastello** [comment]
My PostgreSQL was with the default date style "sql, dmy". So I have this error :

`[21-Jun-2017 09:32:41 Europe/Paris] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (20/06/2017 15:50:08 GMT) at position 0 (2): Unexpected character' in /[...]/program/lib/Roundcube/rcube_user.php:523
Stack trace:
#0 /[...]/program/lib/Roundcube/rcube_user.php(523): DateTime->__construct('20/06/2017 15:5...')
#1 /[...]/program/include/rcmail.php(608): rcube_user->is_locked()
#2 /[...]/index.php(109): rcmail->login('[...]', '[...]', '[...]', true)
#3 {main}
  thrown in /[...]/program/lib/Roundcube/rcube_user.php on line 523`

**Comment by alecpl** [comment]
Fixed.
