### ISSUE TITLE
Roundcube 1.2.5 - highlight message after delete another

### ISSUE THREAD

**Issue by vbuscemi** [roundcube/roundcubemail#5810]
Hi, I've noticed a strange behaviour after delete a message.

Reproduced by -

I have this settings:

![schermata 2017-06-22 alle 11 00 42](https://user-images.githubusercontent.com/29624972/27429760-89b27fe0-5746-11e7-95d2-aaa4e3a08af5.png)

Assume multiple pages of messages displaied.

page view 50 messages.

select a message by clicking on icon

click delete, or use delete key.

when this occurs, highlight other email don't work.

**Comment by alecpl** [comment]
Check Preferences > Displaying Messages > After message delete/move display the next message.

**Comment by vbuscemi** [comment]
Alredy checked, seems the issue occours when messages list gets updated after a message deletion.

Please note that my setup is to move deleted messages directly in to the trash folder instead of mark them as "deleted".

there is my starting point:
![schermata 2017-06-22 alle 12 53 22](https://user-images.githubusercontent.com/29624972/27431428-cd35c528-574c-11e7-8763-31a04b90cc25.png)

and this is after a message deletion(note the last message):
![schermata 2017-06-22 alle 12 53 41](https://user-images.githubusercontent.com/29624972/27431456-e5c2398c-574c-11e7-8a4c-59c24a1fa19e.png)

at this point i'm not able to highlight or select other messages but clicking twice over one of them i can get into a message views.

regards

**Comment by alecpl** [comment]
I see you're using many external plugins. So, I'd propose to check with all plugins disabled. Also, see browser console for errors.

**Comment by vbuscemi** [comment]
I have a bug in my rcube_dbmail.php.

thanks for support.
