### ISSUE TITLE
Blank Page After Login (?_task=login)

### ISSUE THREAD

**Issue by leabhart** [roundcube/roundcubemail#5812]
I've been looking for an answer to this for a while now and can't find anything. Maybe I'm missing something simple... I'm having an issue where after users enter their username and password they get a blank page instead of having their inbox load. When the user manually removes "?_task=login" from the end of the URL everything works as expected. Wouldn't be that big of a deal except not all users understand removing "?_task=login" will take them to their inbox. Any help is appreciated! I'm on version 1.2.4.
![image](https://user-images.githubusercontent.com/14226609/27503041-63a9a55a-583e-11e7-8e7e-b8266e56d25c.png)

**Comment by alecpl** [comment]
In such cases a PHP fatal error or other error should be logged to the error log (of Roundcube or http server).

**Comment by leabhart** [comment]
Sorry it took so long for me to get back to this. I saw you responded but things kept coming up every night when I got home from work. 

I checked the error log as you suggested and identified the problem as being the carddav plugin was failing to connect.

We don't need carddav so I resolved the issue by disabling it.
