### ISSUE TITLE
blank mailbox folder (spam folder)

### ISSUE THREAD

**Issue by johnnereth** [roundcube/roundcubemail#5813]
Hi there, while its probably technically not a bug, this issue only happens in roundcube (not horde or squirrelmail).

when using the assp spam filter and the extra spambox that comes with the deluxe version, when a user logs into roundcube webmail the spambox is usually blank. If you witch to one of the other mail applications (in cpanel) click on the spam box and then go back to roundcube the mail shows up. Like wise if you toggle from list view to conversation and back, the mail will show up. 

apparently it has to do with the way assp modifies the delivery of the mail to the spambox it does not and can not use doveadm to do it which from my talks with cpanel support, breaks the indexes of the box causing it to not show the mail. However the other mail programs have no issue with displaying the mail so it leads me to 2 possibilities

a) horde and squirrel re-index the mailbox everytime you login or view a folder
b) there is a bug or something in roundcube preventing the folder from displaying properly.

eitherway it seems like it would be helpful if you could just make sure indexes are re-run when a user logs in to help solve this issue.

thanks!

**Comment by alecpl** [comment]
I think I saw similar issues already. This don't have to be a bug in Roundcube. Rather a bug in IMAP server. Roundcube just uses a different set of IMAP commands.

I don't think we'll change our code until you prove it's our bug. To investigate more enable imap_debug to see what's exactly sent to the IMAP server and what it returns. Roundcube has no way to force re-indexing on the server, there's no such thing in IMAP protocol.

What Roundcube version and what imap server?

**Comment by johnnereth** [comment]
Sorry for the delay, dealing with too much right now.  I have enabled the log and have a file i can send you showing the details when the spambox is empty, and then when i switch to horde, and then back to roundcube, it shows the spambox mail showing again. this issue only exists in roundcube, so if its a bug in IMAP, its only showing its head with roundcube so something else is going on as well then would be my guess.

roundcube version 1.2.4 (part of cpanel)
imap: dovecot --version
2.2.28 (bed8434)

would prefer to share the logs privately.

**Comment by alecpl** [comment]
You can send it to alec at alec.pl

**Comment by alecpl** [comment]
This is dovecot issue:
```
C: A0011 STATUS INBOX.spambox (MESSAGES UNSEEN)
S: * STATUS INBOX.spambox (MESSAGES 0 UNSEEN 0)
```
There's no workaround for this.

**Comment by johnnereth** [comment]
Hi Alec

 

Oh ok Thanks but it doesn’t happen with horde or squirrel mail? How do you explain that?

 

John

**Comment by alecpl** [comment]
They don't use STATUS command to count messages.

**Comment by johnnereth** [comment]
Hi Alec

 

Hmm ok thanks, can you tell me why if I switch views in Roundcube that also solves the issue, what changes to make it work when I do that (if I change to list from conversation or vice versa)

 

So I should report to dovcot then?

 

Thanks

John

**Comment by alecpl** [comment]
I have no idea, I guess some command makes it to refresh some index or sth.
