### ISSUE TITLE
Upload form visible at wrong place in UI

### ISSUE THREAD

**Issue by simark** [roundcube/roundcubemail#5814]
Hi!

I just upgraded to 1.3.0, and noticed this UI quirk:

![img](http://nova.polymtl.ca/~simark/ss/fileJIafIq.png)

Some browse button is visible behind the titlebar, as seen on the screen shot.  The button is part of a form with id "uploadformFrm".  From what I understand, it's a form related to uploading/importing messages.  Any idea why it's there?

**Comment by simark** [comment]
I did a fresh install, because I also had some other UI issues, and now everything is fine.  It might have been a plugin I had installed.

**Comment by x539** [comment]
Having the same issue, after upgrade from v1.2.0 to v1.3.0.
I am using the roundcubemail-1.3.0-complete.tar.gz

Using the the clean v1.3.0 webroot with the sample-colfig (except smtp, db, imap settings) did not solve the for me.

**Comment by m4tek** [comment]
Same here. I issue happening even after reinstalling all plugins.
