### ISSUE TITLE
no messages displayed, grey "compose message" after upgrade to 1.3

### ISSUE THREAD

**Issue by lutel** [roundcube/roundcubemail#5816]
Hello there,

After upgrade to 1.3 there are no messages displayed in any layout. IMAP log shows sessions as usual, with no errors. Number of unread messages is correctly displayed on the left panel. I've cleaned cached records in db for the user, but no improvement. 

Icon on the top (compose message) is greyed-out, although it is clickable.

After logging out, I get CSRF warning message, in error log I get:
 PHP Error: Request security check failed (GET /?_task=logout)

Thats all with latest Chrome on Mac, Server - PHP 5.6.30 + NGINX.

**Comment by alecpl** [comment]
Are you using any plugins or skins that are not part of Roundcube release? Likely they cause this issue. See browser error console for errors.

**Comment by lutel** [comment]
I've disabled all plugins i've used ( $config['plugins'] = array('enigma','password','managesieve','markasjunk','newmail_notifier');) - but no improvement in any issue.

**Comment by alecpl** [comment]
Maybe you used the package without javascript dependencies?

**Comment by lutel** [comment]
I've updated gentoo ebuild to 1.3 which sources from:
SRC_URI="https://github.com/${PN}/${MY_PN}/releases/download/${PV/_/-}/${MY_P}.tar.gz"

Is there any other package which includes JS dependencies? In Chrome/dev tools I see jquery 1.12.0 is used.
