### ISSUE TITLE
Widescreen not working any more after upgrade from 1.3-rc to 1.3?

### ISSUE THREAD

**Issue by ilgrosso** [roundcube/roundcubemail#5817]
Among other things, I've been enjoying the widescreen / 3-cols view since 1.3-beta, which survived the upgrade to 1.3-rc.
This morning, however, after upgrading to 1.3 the widescreen is not enabled and I can't find the place to enable it any more.

Am I missing something?
Thanks.

**Comment by aicta** [comment]
I have the same problem.
A mail account has a "widescreen" view and another "list"!

**Comment by alecpl** [comment]
The setting is in messages list options popup. Maybe we should also add a select field in Preferences > Mailbox view.

**Comment by ilgrosso** [comment]
Is it here:

![image](https://user-images.githubusercontent.com/1064664/27577849-6b26bfb6-5b22-11e7-8007-56cd2f9afba9.png)

or here:

![image](https://user-images.githubusercontent.com/1064664/27577874-823f2382-5b22-11e7-9ac2-c3dbed7c5fe6.png)

?

**Comment by aicta** [comment]
I have to servers.
One: Roundcube 1.3 RC -> Roundcube 1.3 everything is OK with "$config['layout'] = 'widescreen';" for all account.
Two: Roundcube 1.2.5 -> Roundcube 1.3 is not OK  for my mail account. In this case if i change "$config['layout'] = 'widescreen'; to another option, this had no effect. For another account on the same server everything is OK!

**Comment by alecpl** [comment]
It is in the messages list menu. I can't be more clear.

**Comment by ilgrosso** [comment]
Thanks @alecpl I have found that.

**Comment by thomascube** [comment]
@alec, perhaps we should bring back an option in the preference settings as the preview pane used to be?

**Comment by alecpl** [comment]
@thomascube Yes, I'll implement that. See #5829.
