### ISSUE TITLE
Use SVG instead of PNG images

### ISSUE THREAD

**Issue by mcnesium** [roundcube/roundcubemail#5824]
Larry theme uses PNG images in CSS sprites for most graphic items. On a HiDPI screen this makes them look fuzzy:

![screenshot from 2017-06-29 13-13-42](https://user-images.githubusercontent.com/476060/27685045-d6787164-5ccc-11e7-91b8-496fa8508b0f.png)

In 2017 it is alright IMHO to use vector graphics in web engineering in general, so this would be a feature request for a future release to use SVG instead of pixel graphics for icons, buttons, logo etc.

**Comment by alecpl** [comment]
The next theme we implement will use fontawesome, so that should be ok. We do not plan to work on changes for the Larry skin.

**Comment by mcnesium** [comment]
OK that sounds good so far. But please reconsider the choice of vector graphics instead of fontawesome. [This comparison might help you decide](https://css-tricks.com/icon-fonts-vs-svg/).

**Comment by alecpl** [comment]
Fontawesome 5 will provide svg framework, so the change shouldn't be a problem. We'll see what we  got from Fontawesome 5.

**Comment by mcnesium** [comment]
Are there any vector graphics which the PNG images are created from? And if so, would you provide them so that someone else (eg me) could create larger image sprites for larry?

**Comment by alecpl** [comment]
Elastic skin uses font-icons, so it should be fine. We do not plan to work on this for other skins.

@thomascube do you have some vector graphics for Larry?

**Comment by thomascube** [comment]
I don't have vectorised sources for all Larry icons. The sprites are composed in a Photoshop file with (partial) Illustrator vector masks. I assume they could be upscaled from there. If there's general interest (@mcnesium) I'm willing to share these files.

**Comment by mcnesium** [comment]
@thomascube thanks for offering, but if there will be a new theme for roundcube soon, which [looks pretty good](https://kolabian.wordpress.com/2017/09/23/elastic/) actually, I will just go ahead and use that one ;)
