### ISSUE TITLE
Possibilty to open RoundCube on a filter, at the place of the Inbox

### ISSUE THREAD

**Issue by gloony** [roundcube/roundcubemail#5825]
Hi, it would be nice if I can open my roundcube instance with the filter "Unread, on all folder".
I was searching a way to do that with an app, but I cannot reach my goal at this day.
Or the possibility to set a advanced search by th url.

**Comment by alecpl** [comment]
This is not possible at the moment. Searching is done with ajax and parameters are stored in session.

**Comment by alecpl** [comment]
Done. You can use &_filter=UNSEEN&_scope=ALL in the URL.
