### ISSUE TITLE
Keyboard control again broken

### ISSUE THREAD

**Issue by mclei** [roundcube/roundcubemail#5826]
I installed latest 1.3.0 version and keyboard control in again broken.
I have Google Chrome 58 on Linux.

Examples:
- when I delete message it is not possible to navigate again in message list using arrow keys
- when I press Home key I also lose arrow keys in message list

**Comment by alecpl** [comment]
Works for me. What skin and plugins are you using? Any errors in browser console?

**Comment by mclei** [comment]
I do not know why, but I cannot simulate it again. Sorry.
