### ISSUE TITLE
[Docker] Became an "Official Image"

### ISSUE THREAD

**Issue by J0WI** [roundcube/roundcubemail#5827]
It would be great if you could do the steps to get into Dockers standard library aka "Official Images". 

There are some administrative steps to fulfill:
https://github.com/docker-library/official-images#contributing-to-the-standard-library

This will enhance maintenance and trust in you Docker image.

**Comment by alecpl** [comment]
Our Docker support is fully based on community contribiutions. So, if anyone's interested provide pull requests, please.

**Comment by J0WI** [comment]
I just created #5874 to rewrite the Dockerfile using some "best practices" (see 'official' Dockerfile of other popular php applications, like Drupal, Joomla or Wordpress).

But the administrative steps can only be fulfilled by a project owner.

**Comment by thomascube** [comment]
First image published at https://hub.docker.com/r/roundcube/roundcubemail/

**Comment by mcnesium** [comment]
Where is the Dockerfile for this image?

**Comment by J0WI** [comment]
> Where is the Dockerfile for this image?

See here https://github.com/roundcube/roundcubemail/blob/master/docker/Dockerfile

**Comment by J0WI** [comment]
@thomascube please use the automated build feature of docker hub: https://docs.docker.com/docker-hub/github/#creating-an-automated-build
Then the Dockerfile here will be linked from there.

**Comment by J0WI** [comment]
Can we move the Docker stuff into a dedicated repo?

**Comment by J0WI** [comment]
@thomascube thanks for the fix and the clarification in https://github.com/roundcube/roundcubemail/issues/6148#issuecomment-366182428.
A `/var/www/html` is required for #6116. I don't think that round-robin is a common use case for Docker, since there are already tools like Docker Swarm and Kubernetes to manage clustered set ups. Personally I would also prefer to use the FPM variant with a proxy in such a scenario.

I hope @tianon or @yosifkit can share some of their experience to find the best defaults for Docker volumes (context is _which volumes should be exposed by default?_).

**Comment by thomascube** [comment]
@J0WI I don't quite understand why the PHP FPM container needs a `/var/www/html` volume. How is that different from the default Apache container?

Also, to my understanding, even with Kubernetes one needs volumes in order to share files across multiple nodes. And Roundcube stores uploaded attachment files in a temp folder on the local file system.

**Comment by thomascube** [comment]
Created a dedicated repo for Docker files: https://github.com/roundcube/roundcubemail-docker

**Comment by J0WI** [comment]
@thomascube please have a look at some other Docker repositories, they have a better structure.

> I don't quite understand why the PHP FPM container needs a /var/www/html volume. How is that different from the default Apache container?

Because the volume is shared between PHP FPM and the proxy. PHP FPM does only compile the PHP code, the proxy delivers it and all static files.

> Also, to my understanding, even with Kubernetes one needs volumes in order to share files across multiple nodes. And Roundcube stores uploaded attachment files in a temp folder on the local file system.

What about `/var/www/html/temp`?

**Comment by alecpl** [comment]
Please, continue on https://github.com/roundcube/roundcubemail-docker. Closing.
