### ISSUE TITLE
jsdeps check in installto.sh fails on complete packages

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#5830]
The complete package doesn't contain `jsdeps.json` nor `bin/install-jsdeps.sh`. Thus the `installto.sh` script should not attempt to check and install javascript dependencies.

http://lists.roundcube.net/pipermail/users/2017-June/011556.html

**Comment by alecpl** [comment]
I fixed that in https://github.com/roundcube/roundcubemail/commit/5597ff2107c3206070420d1eef010d0004a951d4.

**Comment by thomascube** [comment]
Sorry, I somehow missed that. 6d53c6b9 is for 1.3.1
