### ISSUE TITLE
bin/update.sh fails if sql_mode contains NO_ZERO_IN_DATE,NO_ZERO_DATE

### ISSUE THREAD

**Issue by paulschreiber** [roundcube/roundcubemail#5833]
(Using MySQL)

I attempted to update my schema:
```
What version are you upgrading from? Type '?' if you don't know.
?
Executing database schema update.
Updating database schema (2015111100)... [FAILED]
NOTE: Update dependencies by running `php composer.phar update --no-dev`
```
Here's the SQL it's trying:
```
# more 2015111100.sql 
ALTER TABLE `users`
  ADD `failed_login` datetime DEFAULT NULL,
  ADD `failed_login_counter` int(10) UNSIGNED DEFAULT NULL;
```

Running this manually:
```
mysql> ALTER TABLE `users`
    ->   ADD `failed_login` datetime DEFAULT NULL,
    ->   ADD `failed_login_counter` int(10) UNSIGNED DEFAULT NULL;
ERROR 1067 (42000): Invalid default value for 'created'
```

Looking in `mysql.initial.sql`, I see the default values for created are `1000-01-01 00:00:00`.

[Per StackOverflow](https://stackoverflow.com/questions/36882149/error-1067-42000-invalid-default-value-for-created-at), this is due to `sql_mode` containing `NO_ZERO_IN_DATE,NO_ZERO_DATE`.

Workaround was to run:
```
alter table users modify created datetime NOT NULL default '1000-01-01 00:00:00';
alter table session modify changed datetime NOT NULL default '1000-01-01 00:00:00',
   modify created datetime NOT NULL default '1000-01-01 00:00:00';
```

This let me run the `.sql` files manually (bin/update.sh still failed).

**Comment by alecpl** [comment]
So, it complaints about a column that already is in the database when we add new columns to the table. Stupid. Strange also because we use '1000-01-01' not '0000-00-00'. So, how that happened that your columns had '0000-00-00' as default value? What MySQL version?

**Comment by paulschreiber** [comment]
I'm using MySQL 5.7.18. The problem isn't the version; it's the `sql_mode` set to disallow zeros that causes this error.

A previous version of Roundcube used `0000-00-00 00:00:00` (or didn't specify a default value) instead of `1000-01-01 00:00:00` in the schema. This was fixed way back in 2009 with 37974e2. I suspect existing users were never migrated.

**Comment by alecpl** [comment]
Indeed. I don't see how we could fix this now. And there's not many such old installations. Wontfix.

**Comment by paulschreiber** [comment]
The fix would be to check the 

```sql
SELECT TABLE_NAME, COLUMN_NAME,COLUMN_DEFAULT
FROM information_schema.columns
WHERE TABLE_SCHEMA='roundcube' AND COLUMN_DEFAULT='0000-00-00 00:00:00'
  AND ((TABLE_NAME='users' AND COLUMN_NAME='created') 
   OR (TABLE_NAME='session' AND COLUMN_NAME IN ('created', 'changed')))
```

If that returns > 0 rows, you could example the results and run the appropriate `ALTER TABLE` commands (or print an error with instructions).

**Comment by Philippe23** [comment]
@paulschreiber: Thanks for posting that SQL, just saved my bacon in https://github.com/roundcube/roundcubemail/issues/8120.  Just wanted to let you know the time you spent to document this here is greatly appreciated.
