### ISSUE TITLE
[widescreen] manipulate columns in message list

### ISSUE THREAD

**Issue by pimlie** [roundcube/roundcubemail#5835]
For the roundcube plugin `authres_status` I have hooked `messages_list` to be able to add a column. As the widescreen layout has a fixed set of columns, the plugin doesnt work anymore.

I still would like to be able to add the authentication status, maybe in a similar way as for `message_headers_output` where you can manipulate the from output as html. I tried adding html directly to `$p['messages'][$index]->from` but that doesnt work unfortunately, the html is escaped and displayed as text.

Probably this cant be fixed without some code changes, so I would like to know your recommendations for fixing this? Thanks!

**Comment by alecpl** [comment]
In javascript you could try to modify env.widescreen_list_template, but I wouldn't recommend that. Maybe best solution would be to modify the 'from' element from javascript using 'insertrow' event of rcmail object.

**Comment by pimlie** [comment]
Hi Alex, thanks for your response. Unfortunately only the returned data that are really used are available in the `insertrow` event. The command `list` currently still returns the `authres_status` column information in the second parameter of `add_message_row`, but it seems there are no hooks/trigger which are passed that cols parameters so I can access the returned value. Would it be possible to either add an extra trigger or to pass all parameters to `insertrow`?
Otherwise I would need to add a second xhr after each list command but I would think that is not favorable.

**Comment by alecpl** [comment]
You can try extra_flags (https://github.com/roundcube/roundcubemail/blob/release-1.3/program/js/app.js#L2070) or just set a separate env variable using `$OUTPUT->set_env()`. No need to do a separate request.

**Comment by pimlie** [comment]
@alecpl , thanks again for your help. It took a while before I had time to look in to this unfortunately but I was able to use `$OUTPUT->set_env()` for this. 
Using `extra_flags` seemed not to be an option really because in `messages_list` you can set any `extra_flags` you need but in javascript `extra_flags` is always an integer. So if multiple plugins would use `extra_flags` it seems it would become very difficult to extract the correct status for a specific plugin.
