### ISSUE TITLE
Check schema version on startup

### ISSUE THREAD

**Issue by paulschreiber** [roundcube/roundcubemail#5836]
Recently, after upgrading from 1.2.5 to 1.3.0, logins failed (see #5833, #5834). The failure turned out to be due to an outdated schema.

It would be very helpful if each version of Roundcube checked the current version of the schema against the supported version, and either:
(a) printed an error message ("Your database schema it out of date. It is at 20150102 and needs to be at 20160405.")
(b) upgraded itself (perhaps calling `rcmail_utils::db_update(...)`

WordPress does something like this. It stores `$wp_db_version = 35700;` in `version.php`. The admin page checks the version number whenever you use it:

```
if ( get_option('db_version') != $wp_db_version && empty($_POST) ) {
```
and prompts you to click a button to update the schema.

**Comment by alecpl** [comment]
I don't see a reason to slow down every request to solve such a rare case. Also, in general if there's something wrong with the schema you would get an error in the log anyway. Wontfix.

**Comment by paulschreiber** [comment]
1. There were no errors any of the logs (imap, errors, smtp, sql, sendmail), which is what led to these issues being written up.

2. This will take < 0.01s. You can cache the value of the database query for a fairly long time (an hour). Even uncached, the query is fast:
```
mysql> select value from system where name='roundcube-version';
+------------+
| value      |
+------------+
| 2016112200 |
+------------+
1 row in set (0.00 sec)
```
