### ISSUE TITLE
PHP Error: Invalid compose ID

### ISSUE THREAD

**Issue by MarcinOrlowski** [roundcube/roundcubemail#5840]
While reviewing error log I spotted 

> PHP Error: Invalid compose ID in /app/program/steps/mail/sendmail.inc on line 39 (POST /?_task=mail&_unlock=loading1499162474116&_lang=pl&_framed=1&_action=send)

occuring a few times (not a flood, yet 2-3 per day). Unfortunately I got no more information about the env this happened. 

RC v1.2.5

PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by alecpl** [comment]
That's normal, and we have a ticket about this already. Update to 1.3 and you'll not see them.

**Comment by MarcinOrlowski** [comment]
What ticket you refer to exactly? I cannot update instantly so I'd like to check the details

**Comment by tech-support-nqc** [comment]
alecpl, not all of us want to use 1.3, some of us want to stick with the 1.1.9 LTS release provided on Epel.

**Comment by alecpl** [comment]
1.1 is not supported. The ticket is #5869.

**Comment by jarifr** [comment]
I have the same problem in my Roundcube Webmail 1.3.1

![image](https://user-images.githubusercontent.com/15037853/32162178-b45302f8-bd60-11e7-902f-7c63b974e707.png)
