### ISSUE TITLE
Error message is not vissible

### ISSUE THREAD

**Issue by tomperys** [roundcube/roundcubemail#5841]
Hi,

we use roundcube and there is problem with errors - for example if you set filters for automatic reply and fill in some text instead of email address in "Sender address" and try to save the filter, the error will not show up anywhere on the page.

- with default skin (Larry - by FLINT / Büro für Gestaltung, Switzerland) the filed have only Shalimar color on background of the filed and the error will appear only if you hover over that field (see [webmail1.jpg](https://tomperys.cz/webmail1.jpg) image)

- with another skin (w21 - by Roundcube Plus  http://roundcubeplus.com) the field even doesnt change the color so there is no clue for ordinary users what can be wrong (see [webmail2.jpg](https://tomperys.cz/webmail2.jpg) image)

Our question is - would it be possible to display the errors next to the badly filled field or under it, not hide it and show it just on hover because ordinary users will not know what is wrong even if the field have different background color, they will not think of hovering cursor over the fields......

**Comment by alecpl** [comment]
But it displays "Filter form contains errors" warning (in right/bottom)? It does for me.

**Comment by tomperys** [comment]
No, no warning in right bottom

**Comment by alecpl** [comment]
Then you need a newer version. I think that warning + color on the input field (and popup) is good enough.
