### ISSUE TITLE
Two kolab plugins greyes out

### ISSUE THREAD

**Issue by CRtEurope** [roundcube/roundcubemail#5844]
Upgraded to the latest rc master-branch version and I noticed that the kolab plugins calender and tasklist are greyed out and cannot be clicked anymore. There are no errors in the logfiles. Before everything was working perfectly. I have no idea why this is happening.

PHP 7.1
Roundcube latest master-branch
all necessary depencies installed

![greyed_out](https://user-images.githubusercontent.com/16518395/27986225-a903e1aa-63fc-11e7-857a-2d5f5e74afcf.jpg)

**Comment by alecpl** [comment]
There were quite heavy changes in git-master recently. Kolab plugins would need to be updated. We do not support them here.
