### ISSUE TITLE
Managesieve plugin: Actions notify and vacation does not encode diacritics in subject

### ISSUE THREAD

**Issue by skiner68** [roundcube/roundcubemail#5848]
Hello, 
diacritics are not supported in these two actions. Subject is directly saved 'as it is', then send with broken symbols. 

Sample subject string: "Diacritics: ščřžýáíéúů"

I have done some work on this. RFC says that vacation subject must be encoded in case non-ascii characters are present: https://tools.ietf.org/html/rfc5230#page-6

According to my experiments, simple mb_encode_mimeheader on save would be ok.

Unfortunatelly  I was not able to create some working example of code - the situation is too complex - both set & get actions must taken care of- the subject must be decoded for UI, but must not be decoded in case user wants to download the rule as text etc.

Can somebody at least give me a clue where the encoding & decoding should be placed not to break the rest of logic?

**Comment by alecpl** [comment]
The RFC says that implementations must convert the string. "Implementations" here means the imap/sieve server. Wontfix.

**Comment by skiner68** [comment]
oh, I see. Thanks anyway.
