### ISSUE TITLE
Password plugin issue

### ISSUE THREAD

**Issue by sohaib0lbhja** [roundcube/roundcubemail#5849]
Hello,
I'm trying to use the password plugin to change my password but I'm stuck here for about a month now.
I don't see any solution. is it a bug? can we accually change the password in this version of the roundcubemail (1.1.9) ?

if so, can you please tell me what's the Sql request for changing the password?

This is my SQL request in the config.inc.php password config file plugin:
$config['password_query'] = 'UPDATE users SET password=ENCRYPT(%p,CONCAT(_utf8\'$5$\',RIGHT(MD5(RAND()),8),_utf8\'$\')) WHERE username=%u LIMIT 1';

DB :
![321](https://user-images.githubusercontent.com/8728092/28020268-fec4a452-6583-11e7-83a8-1a993aee54ce.PNG)

Log:
![qsdf](https://user-images.githubusercontent.com/8728092/28020356-5a2b726c-6584-11e7-8725-d24f374fece2.PNG)

**Comment by alecpl** [comment]
Roundcube does not store user passwords. You have to setup the plugin for the backend you're using. The query does not make sense as you see users table in Roundcube database does not have password column.

**Comment by sohaib0lbhja** [comment]
Thanks !!
