### ISSUE TITLE
Disable double-click on the list when preview pane is on ...

### ISSUE THREAD

**Issue by JeroenvdBr** [roundcube/roundcubemail#5851]
I dont think disabling the double-click on the list in version 1.3 was a good idea.
I want to (double) click on a new message so I can answer this message in a new window.
Just like Outlook and Gmail.
Not click on a message and answer the message in a window below the message.

Why was the counterintuitive feature added?

**Comment by alecpl** [comment]
There were a few reasons:
1. We needed to do this to remove 500ms delay when opening a message.
2. When the preview pane is enabled it's a rare situation to open a message in full window, and if there's a need you can do this with Enter key or using the extwindow button visible in the preview pane.
3. You can configure Roundcube to always open mail compose in a separate window/tab.

If enyone is able to provide a solution that works for everyone we'll re-think. Pull requests welcome. For now it's a wontfix.

**Comment by flightsupport** [comment]
I liked the old behavior better. Although I just learned to use the Enter key.
I liked it better especially on small screens where you wanted to read the message without scrolling.

**Comment by JeroenvdBr** [comment]
True... using the 'enter' key is counterintuitive

**Comment by tjharman** [comment]
Couldn't we just have a tickbox or a config.php option to enable this feature?

I understand why it was disabled, but couldn't it be a toggle?
