### ISSUE TITLE
Bring back Message Preview checkbox

### ISSUE THREAD

**Issue by yanky83** [roundcube/roundcubemail#5852]
Hey,
the three column layout in 1.3 is a nice feature, but the way to switch between the modes is too hard to access. Previously one could switch with one click using the checkbox (basically whenever needed). Now you have to go through the dialogue - which slows down significantly.

Could the checkbox be brought back, or some other way be added to switch between views/turn message view on/off?

Thanks

**Comment by alecpl** [comment]
We added an option in preferences (#5829), but not to make it faster. There will be no checkbox.

**Comment by yanky83** [comment]
Hey, as long as it doesn't reset the message selection, they should do. 

The current way does reset it, which is fairly annoying.

**Comment by alecpl** [comment]
Really, how often do you switch modes? Either you're happy with preview or not. That's not something you switch all the time. Isn't it?

**Comment by yanky83** [comment]
It is - big time.

The issue being, when message preview is active, it takes quite a while to load the message, during that time you cant e.g. delete it.

Very often, I would clear spam without message preview (much quicker), and then read individual clicking the checkbox on and off.

Must admit, I would revert back to 1.2 if no workaround is found. I assume the suggested layout switch button would be OK (ideally with a keyboard short cut), if it doesnt reset message selection.

Cheers

**Comment by alecpl** [comment]
You don't have to open a message to delete it. Use Ctrl+click for selection.

**Comment by yanky83** [comment]
Im aware of that, and I use that function a lot - however, when selecting the first message, roundcube starts loading the message (which depending on connection) can take seconds. This is avoided with the preview being inactive.
