### ISSUE TITLE
Skin localization files

### ISSUE THREAD

**Issue by sintro** [roundcube/roundcubemail#5853]
As I can understand, there are no ways of include some localization files for the skin, something like skin-domain localizations for some unique intefrace objects, which are presented only on the skin (which for example could be in /skins/<skin_name>/localization/ folder). 
This is strange, because one need to modify global localization files (which can be easily overwrited) if you want to include custom label in you unique skin element.
Are there some workarounds for such tasks?

**Comment by alecpl** [comment]
There's no such feature. But I think that idea is not bad. This should probably be controlled by some option in meta.json file. Pull requests, welcome.

**Comment by sintro** [comment]
@thomascube , thank for advice! Didn`t see that tip.
But anyway, I think it is not very handy way of defining of localized texts, especially if there are plans of adding of many languages and many labels in skin. So it still could be worth realizing of skin-domain localization files loading mechanism (actually, such way of i18n is used in most systems and CMSes, where are both "global" and "skin" locales, which extend and override "global"). It is even more weird that there is no such feature in Roundcube yet, while the part of it is realized with plugins localizations (why plugins can have its own locales, but skins do not?)

**Comment by alecpl** [comment]
It's simply because noone really asked for this before you. As I said we probably will add such a feature.  Pull request would help to make it sooner than later.

**Comment by alecpl** [comment]
Implemented. The meta.json file now can contain "localization" entry with localization folder name or be set to `true` to use default `localization/` folder inside the skin folder. The localization format is the same as the one we use for plugins.
