### ISSUE TITLE
Chrome attach file button didnt work

### ISSUE THREAD

**Issue by AntteC** [roundcube/roundcubemail#5854]
Chrome 57.0.2987.133 (64-bit)
1. Add any file (click attach button)
2. Delete this file (click trash button)
3. Try to add this file again (click attach button and select the same file) - file didnt add to attach files.

PS Roundcube Webmail 1.3.0 (contextmenu filesystem_attachments html5_notifier jqueryui managesieve markasjunk2 password persistent_login)

**Comment by alecpl** [comment]
Confirmed with Chromium 59 on Linux.

**Comment by alecpl** [comment]
Fixed.
