### ISSUE TITLE
Browser Cache Consumption

### ISSUE THREAD

**Issue by karlmendes** [roundcube/roundcubemail#5855]
Good Morning

Only if i change the mails ( with preview panel ) the RAM consumption increases and dont decreases, only if close the page..

**Comment by alecpl** [comment]
Any more details?

**Comment by karlmendes** [comment]
Searching, i thing the problem is in iframe, because in settings screen, if i change the menus, same fact occur

**Comment by karlmendes** [comment]
![photo1](https://user-images.githubusercontent.com/11417196/28212070-275f8798-6876-11e7-9be6-219ce74234b0.png)
![photo2](https://user-images.githubusercontent.com/11417196/28212071-27957b64-6876-11e7-89ee-6a814f2e8506.png)

**Comment by alecpl** [comment]
You don't provide any details. What Roundcube version? What browser version? Does it happen if you disable all plugins and switch to the default skin. Does the memory grow infinitely? How much it grows on every message load?

**Comment by karlmendes** [comment]
Roundcube Version: Release 1.1.5
Chrome Version: 59

Disabled all plugins, skin, same thing occur.

Appearly the memory grow while there space in the memory

Every message grows 3 ~ 6 MB, its randon

**Comment by alecpl** [comment]
This version is not supported, but I don't think you'll get better results with 1.3. This is most likely a browser bug. See https://bugs.chromium.org/p/chromium/issues/detail?id=609137

**Comment by karlmendes** [comment]
I try to reproduce on http://roundcubeskins.net/ demo page, but appearly refresh all page every change message.

On firefox occur too.

**Comment by alecpl** [comment]
I'm unable to reproduce on Roundcube 1.3 and Chromium 59 on Linux.

**Comment by karlmendes** [comment]
with top command i can see the %MEM consuption increased, but on windows is more easy to see with task manager

**Comment by CRtEurope** [comment]
That's not RC. It's your skin you are using.
Address this case to http://roundcubeskins.net/

**Comment by karlmendes** [comment]
But commented all plugins (and skins) same problem occur.

i think its problem with cached iframe and browser, but we can't try fix ?

**Comment by alecpl** [comment]
It's browser issue and we can't fix it. Maybe if we remove the iframe element all the time the message is loaded we could workaround this issue, but I don't like this idea. Please, reopen if you find any solution.

**Comment by karlmendes** [comment]
I'm install the version 1.3.0 on VM and i got better results, now i'm installing all plugins and i'll test again.

**Comment by karlmendes** [comment]
The problem is in jquery.min.js version, but too many plugins isn't compatible with the newest version, update to most recent 2.x version and done.
