### ISSUE TITLE
layout error

### ISSUE THREAD

**Issue by GustavoMastromano** [roundcube/roundcubemail#5856]
Hello. Today I logged in roundcube and i saw that problem, the page has a white bar in left who makes all the rest of the page goes to right.

Please, help me fixing that. 

Thank you for attention.

![print erro email 2](https://user-images.githubusercontent.com/30176912/28211846-229beab8-6875-11e7-9abf-8d4142517171.png)

**Comment by alecpl** [comment]
Check browser console for errors. What version, what plugins, what browser?

**Comment by alecpl** [comment]
No feedback.
