### ISSUE TITLE
Allow plugins access to rcmail_bounce_mail

### ISSUE THREAD

**Issue by JohnDoh** [roundcube/roundcubemail#5861]
Please consider moving the rcmail_bounce_mail class out of the bounce step file and into its own class file so that plugins can make use of it.

**Comment by alecpl** [comment]
The class is very specific to mail bounce feature, i.e. it takes care about Resent-* headers. What use-case do you have?

**Comment by JohnDoh** [comment]
I would like to use it in my markasjunk2 plugin for the [email_learn](https://github.com/JohnDoh/Roundcube-Plugin-Mark-as-Junk-2/blob/master/drivers/email_learn.php) driver.

I think it could also be useful for client side filter plugins, to bounce/redirect a message automatically.

**Comment by alecpl** [comment]
Done.
