### ISSUE TITLE
Folder view incorrect after removing mails 

### ISSUE THREAD

**Issue by joostbekkers** [roundcube/roundcubemail#5862]
When a folder contains more than 1 page worth of emails and you then delete multiple emails so the list is less than 1 page. The list of emails shown is incorrect.

example:

Page-size is set to 50 and a folder contains 60 emails. Lets call the top email on the first page mail#1 and the bottom one on the second page mail#60.

select mail#11 through mail#29 and delete them

The listing now shows mail#30 through to mail#50 and mail#41 through to mail#60.
mail#41 through to mail#50 are shown twice. Clicking on the first instance of one of the duplicate entries selects the second instance.

I've seen this behavior with 1.2.5 and with 1.3.0.

**Comment by alecpl** [comment]
Do you have imap_cache and messages_cache enabled or not? This is with threading disabled? All plugins disabled? What PHP version and what IMAP server?

**Comment by joostbekkers** [comment]
$config['imap_cache'] = null;
$config['messages_cache'] = false;
$config['plugins'] = array();

threading is disabled.

# php -v
PHP 5.6.30 (cli) (built: Jul  2 2017 13:58:30) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

# dovecot --version
2.2.21 (5345f22)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
