### ISSUE TITLE
return Server Error! (OK) message trying lists the emails without imap error

### ISSUE THREAD

**Issue by javierjurado** [roundcube/roundcubemail#5865]
I've installed and configured roundcube 1.3 with Apache 2.4, PHP 5.4 and Mysql 5.5.52-MariaDB.
I can login with a user perfectly and lists his folders but appears a message when list the emails: Server error! (OK).
I've configure debug=4 and imap and sql logs actived, but no errors are displayed, in fact in the imap log is displayed the correct connection to imap server and the list of user emails.
Every time I access a folder the error message appears.

![seleccion_525](https://user-images.githubusercontent.com/30267124/28327068-b31aea42-6be2-11e7-9b81-df1eb9c8917f.png)

Some possible solution?
Thanks

**Comment by alecpl** [comment]
Just don't use debug=4.
