### ISSUE TITLE
File size limit for imagick processed files

### ISSUE THREAD

**Issue by MarcinOrlowski** [roundcube/roundcubemail#5866]
Today I was looking for a reason of problems with had with one of RC powered webmail box and I discovered lot of **massive** files int `/tmp` folder like that:

```
-rw------- 1 roundcube roundcube 278843904 Jul 14 10:23 magick-12616Ve9d0j3L0Wps
-rw------- 1 roundcube roundcube 278843904 Jul 14 10:23 magick-12619EPbbgjFEjQvO
```

as you noticed each of this file is 266MiB in size and they all managed to fill up the partition. Unfortunately I am unable to get my hands on source message this file came from, yet I'd love to be able to set some file size limits to prevent such situation from happening again.

**Comment by alecpl** [comment]
We have two modes of operation for Imagick use. Did you set im_convert_path?

Imagick has some policy settings, but I think none allows setting limit of temp file size. Also, have no idea if these policies can be set in command line. I also don't know if in the im_convert_path=null mode temp files are used or not.

**Comment by MarcinOrlowski** [comment]
What is imagic used for exactly? Can I have this feature fully disabled?

**Comment by MarcinOrlowski** [comment]
I found this: https://github.com/ImageMagick/ImageMagick/issues/395

**Comment by alecpl** [comment]
We use it to resize images, detect image types/sizes and convert image types (from those that are not supported by browsers). To disable use of Imagick make sure the php-imagick module is not installed (or disabled) and unset im_convert_path (default is unset) option in Roundcube config.

**Comment by idl0r** [comment]
So this is affecting me for quite some time and it's really annoying. im_convert_path is not set in my case but it's still using imagick to convert stuff and leave it there until /tmp explodes. There seems to be no cleanup or whatsoever.
Uninstalling the modul is not an option.
The module seems to check only whether Imagick exists, if so, it either uses the convert CLI utility or the imagick PHP module. There should be a toggle to just disable it entirely or something like this.

**Comment by idl0r** [comment]
@alecpl or @MarcinOrlowski can you reopen please?
