### ISSUE TITLE
Out of Office auto-reply continuing to send after deleting filter

### ISSUE THREAD

**Issue by kmshaw201** [roundcube/roundcubemail#5868]
After setting up an out of office auto-reply for about a week I deleted it and, over the course of the next ten days the auto reply doesn't send most of the time, but it has send at least 3 random times.

Is there a reason this is happening and a way that I can fix it?

**Comment by alecpl** [comment]
I don't think it's Roundcube issue. Chock your IMAP server config/logs/etc.
