### ISSUE TITLE
Message-ID in sendmail log

### ISSUE THREAD

**Issue by skeyby** [roundcube/roundcubemail#5871]
Hi

I wanted to ask if you could track message-if of the outgoing message to the sendmail.log

I did it on my copy of round cube but I have not forked the main project so I can't send you a direct pull request. By the way the difference is in program/lib/Roundcube/rcube.php, and this is the resulting code...

```
            if ($this->config->get('smtp_log')) {
                // get all recipient addresses
                $mailto = implode(',', $a_recipients);
                $mailto = rcube_mime::decode_address_list($mailto, null, false, null, true);

                self::write_log('sendmail', sprintf("User %s [%s]; Message %s for %s; %s",
                    $this->user->get_username(),
                    rcube_utils::remote_addr(),
                    $headers['Message-ID'],
                    implode(', ', $mailto),
                    !empty($response) ? join('; ', $response) : ''));
            }
```

(there is a %s more in the log and the $headers["Message-ID"] in the parameters)

**Comment by Takika** [comment]
I think it's better to do with a new **smtp_log_prepare** hook which returns $log_msg variable which can be passed to write_log to write out to the logfile.

**Comment by alecpl** [comment]
Implemented.
