### ISSUE TITLE
Can't run SQL/mysql/2016112200.sql (errno: 150)

### ISSUE THREAD

**Issue by Haran** [roundcube/roundcubemail#5875]
The SQL/mysql/2016112200.sql fails upon executing if `users` table is still uses MyISAM storage engine. In my case it was the issue, because I was updating roundcube ever since without reinstalling. MyISAM doesn't support foreign keys, so update fails with:

``` 
MariaDB [webmail]> ALTER TABLE `cache` ADD CONSTRAINT `user_id_fk_cache` FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ERROR 1005 (HY000): Can't create table 'webmail.#sql-968_519cce' (errno: 150)
```

The fix is simple: convert MyISAM to InnoDB/XtraDB before.
```
MariaDB [webmail]> ALTER TABLE `users` ENGINE=InnoDB;    
Query OK, 700 rows affected (0.31 sec)             
Records: 700  Duplicates: 0  Warnings: 0

MariaDB [webmail]> ALTER TABLE `cache` ADD CONSTRAINT `user_id_fk_cache` FOREIGN KEY (`user_id`) REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
Query OK, 0 rows affected (0.07 sec)               
Records: 0  Duplicates: 0  Warnings: 0
```

Yet there're more MyISAM tables in the databases. Is more FKs will be added in the future, keep an eye on them to avoid the same issue.

**Comment by alecpl** [comment]
Maybe you didn't update properly in the past. The engine has been changed in https://github.com/roundcube/roundcubemail/blob/master/SQL/mysql/2008092100.sql. Anyway, I don't think we should support such old releases and this rare issue.

**Comment by jorrit** [comment]
Happened to me too. I don't know why I missed that update in the past.
