### ISSUE TITLE
option to disable refresh notification

### ISSUE THREAD

**Issue by lutel** [roundcube/roundcubemail#5876]
I've got short refresh interval (5s) in order to get see arriving email as soon as possible. The problem is, there is notification box on bottom lower corner each time refresh is performed. Actually this is annoying and unnecessary, is it possible to disable this notification?

**Comment by alecpl** [comment]
Nope. In the code at https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L9114 set `lock` to false and remove `this.set_busy()` call.

**Comment by lutel** [comment]
After change I had to "minify" it to app.min.js, works like a charm, dziękuję :)
