### ISSUE TITLE
Sanitize attachment names

### ISSUE THREAD

**Issue by iHeadRu** [roundcube/roundcubemail#5880]
Need add some replacements in 
https://github.com/roundcube/roundcubemail/blob/master/program/steps/mail/func.inc#L1957
`$filename = str_replace(array("\r", "\n"), '', $filename);`

I have some incoming e-mails with invalid attachment's names.
When i download them i see Apache 500 errror with following messages in log

> AH02430: Response header 'Content-Disposition' value of 'attachment; filename="!:@8= \x109EM4.png"' contains invalid characters, aborting request

> AH02430: Response header 'Content-Disposition' value of 'inline; filename="\x1d>20O 0=:5B0 \x18\x1f.PDF"' contains invalid characters, aborting request

If i replace that line with
$filename = str_replace(array("\r", "\n", "\x10", "\x18", "\x1f", "\x1d"), '', $filename);
files are downloaded correctly.

Probably there are other characters (all lower than 32 code of ASCII?) that will raise the problem. Please fix it.

+
https://stackoverflow.com/questions/1176904/php-how-to-remove-all-non-printable-characters-in-a-string

**Comment by alecpl** [comment]
Are you using git master?

**Comment by iHeadRu** [comment]
no

**Comment by alecpl** [comment]
Ok. I think it's fixed in git-master as we use proper encoding now. This however, is not and will not be backported. Maybe for 1.3 we should indeed just cleanup non-printable ascii chars.

**Comment by alecpl** [comment]
Fixed.
