### ISSUE TITLE
undefined function rcube_table_output

### ISSUE THREAD

**Issue by xabispacebiker** [roundcube/roundcubemail#5881]
After upgrading roundcubemail to 1.3 version ISPConfig module throws an error:

PHP Fatal error:  Call to undefined function rcube_table_output() in /usr/share/roundcube/plugins/ispconfig3_account/ispconfig3_account.php on line 132

I checked that this function is included in program/include/main.inc which does not exist in the 1.3 version.

**Comment by alecpl** [comment]
ispconfig3_account plugin need to be updated. Some functions like this one have been deprecated in 1.2 and removed in 1.3.

https://github.com/roundcube/roundcubemail/blob/release-1.2/program/include/bc.php#L140
