### ISSUE TITLE
IE11 Redirect Error

### ISSUE THREAD

**Issue by gmariani** [roundcube/roundcubemail#5883]
I'm experiencing an issue on my WHM server running cPanel ( CENTOS 7.3 x86_64 kvm – host cPanel & WHM 64.0 (build 36) ) and RoundCube version 1.2.4. Using RoundCube with IE11 and Windows 7, occasionally CSS or JS files won't load properly. The HTML document will request the main styles.css or jQuery.js file with a correct content type, but the server SOMETIMES responds with a 308 redirect with a content type of text/html. The redirected document loads the correct file, but due to this redirect, IE11 claims a type mis-match and refuses to load the file. The server has 'X-Content-Type-Options' set to 'nosniff', which may be a factor in this as well but that is there for security reasons. I don't see this happening on Chrome or Firefox or even IE11 on Windows 10. Attached is the IE11 version of a HAR file detailing the issue, rename it back to XML.

From a clients perspective, when this happens, they sometimes get a white screen, no CSS loading, or instead of the RoundCube interface, they see the raw JSON response from the server and that's it. ANy help diagnosing this issue would be appreciated.

Sample redirect
<html><head><META HTTP-EQUIV="refresh" CONTENT="2;URL=/styled/current_style/styles.css?1494938694"></head><body></body></html>

Captured traffic with the redirect
[NetworkData2.txt](https://github.com/roundcube/roundcubemail/files/1183706/NetworkData2.txt)

Captured traffic with jquery-ui-1.10.4.custom.css, jquery.min.js and ui.min.js fail to load
SEC7113: CSS was ignored due to mime type mismatch
File: jquery-ui-1.10.4.custom.css
SEC7112: Script from http://webmail.windberboro.com/cpsess1638020311/3rdparty/roundcube/skins/larry/ui.min.js?s=1489164033 was blocked due to mime type mismatch
File: index.php
SEC7112: Script from http://webmail.windberboro.com/cpsess1638020311/3rdparty/roundcube/skins/larry/jquery.min.js?s=1489164033 was blocked due to mime type mismatch
File: index.php
[NetworkData.txt](https://github.com/roundcube/roundcubemail/files/1183703/NetworkData.txt)

**Comment by alecpl** [comment]
Why the server responds with the redirect? That's not something Roundcube does. We can't help you here.

**Comment by gmariani** [comment]
Wow thanks dude. I'm sorry I don't know how your program works and didn't delve into why it was sending a 308 response with a meta redirect instead of the file itself. Thanks for glazing over this.
