### ISSUE TITLE
help sent mail not showing up across platforms or roundcube web.

### ISSUE THREAD

**Issue by mvitalepcm** [roundcube/roundcubemail#5884]
Hello, new here and need a little help if possible.

I recently had a domain registered and am using roundcube to host the email.
I am able to easily set it up on outlook desktop. all of my incoming mail works fine and I can get it pretty quick on outlook desktop, outlook on android (s7) and the basic mail app on android.

Sent mail is a big problem.
Sent from outlook desktop will show in the desktop sent folder and on the roundcube website when logged in.
Sent mail from any app on the phone (outlook or other mail) will only show up in the sent folder on the phone. Not in roundcube web site sent folder and not in outlook.  
I would expect that I wont see it across any platform if its not making it in the roundcube web site

But yes my mail is going through even when not showing it is sent so it is sending.

I went over the imap settings with my web host company but still no help.. what do I do?

**Comment by rmcaninch** [comment]
Nothing to do with Roundcube. You need to adjust the settings on your phone to save Sent mail to the server.

**Comment by mvitalepcm** [comment]
any idea how to do that? i dont see any options on outlook for android or the android mail app. all other emails (aol) respond from the phone and dont have the sent mail issue so it strikes me as odd
