### ISSUE TITLE
Diacritic issue on EDGE

### ISSUE THREAD

**Issue by tomperys** [roundcube/roundcubemail#5885]
Hi
there is issue with diacritics (CZ or DE for example) in Roundcube. We tried versions 1.2.1 and even the new  1.3.0. The issues is in EDGE browser, when you choose new mail message and HTML editor and try to paste some text from a website in the HTML message, all the characters with diacritic are broken (see attached image - correct encoding is below).
 
![diacritic](https://user-images.githubusercontent.com/4435945/28822915-75a3a404-76bb-11e7-9032-ca2f6241d127.jpg)

THE CORRECT DIACRITIC (encoding):
Zdravím Vás všechny, kterým se podařilo ke mně zabloudit – ať už náhodou anebo cíleně. Jsem turistka ve vlastnictví dvou psů se sklony zapomenout úplně všechno, co si nevyfotí, takže fotím pro jistotu úplně všechno. Můžete si vybrat:
Fotky a zážitky z výletů
Psí fotky a články ze života vlčích špiců
Fotografie z jiných akcí, třeba hudebních nebo psích
Původní web s fotkami mezi roky 2008 – 2015 a fotkami z akcí Hnutí Brontosaurus
Tento nový kabátek má web od léta 2016, takže doufám, že se Vám tu bude líbit a že najdete zajímavou turistickou inspiraci pro Vaše vlastní výlety, nebo se pokocháte místy, která jste viděli v jiné roční době. Nebo Vás spíš zajímají starosti a radosti ze života se psem? Určitě i pro Vás se tu najdou nějaké střípky, které dotvoří skládačku. Doufám, že se Vám tu bude líbit.

**Comment by alecpl** [comment]
So, this looks like TinyMCE issue. Can you reproduce on most recent version at https://www.tinymce.com/ ?

**Comment by tomperys** [comment]
Yes, the editor that is directly on the page is working correctly, so there is old version in Roundcube?

**Comment by alecpl** [comment]
In Roundcube 1.3.0 we use TinyMCE 4.5.7, while the most recent is 4.6.something. We can't upgrade to this version in >= 1.3 because it e.g. dropped some older browsers support. We will consider 4.6 for Roundcube 1.4.

However, we're not 100% sure this is a solution, there might be other factors involved. E.g. Did you try with disabled all Roundcube plugins and with the default skin? What Edge version and OS?

**Comment by tomperys** [comment]
Ok we tried the 1.3 without any plugins and with default skin and the issue is still there... Iam testing it on Microsoft Edge 40.15063.0.0 on Windows 10 Pro 64bit.

**Comment by alecpl** [comment]
Fixed by upgrade to TinyMCE 4.5.8.
