### ISSUE TITLE
Add more then one email addresses, contact details and address information in address book tab

### ISSUE THREAD

**Issue by mgsf08m002** [roundcube/roundcubemail#5886]

**Comment by alecpl** [comment]
You can do this. Use select on bottom of the form to add additional fields.

**Comment by mgsf08m002** [comment]
It only provides the prefix, Middle Name, Suffix, Display Name, Organization, Department and job.
What if I want to add to email addresses or More then one phone numbers

**Comment by alecpl** [comment]
It provides everything, below. What roundcube version? What skin? What plugins? What browser? Provide a screenshot.

**Comment by mgsf08m002** [comment]
![more detaisl](https://user-images.githubusercontent.com/5829136/28871655-7e3f800c-777d-11e7-91d7-4cc10936b152.png)

Skin: Larry
Browser: Google Chrome

**Comment by alecpl** [comment]
This is not one of Roundcube default skins. In Larry/Classic skiins you canfind another "Add field" element in the bottom of the page - scroll it.

**Comment by mgsf08m002** [comment]
Dear 

Thank You very much for helping.
I just fixed that issue on my site.
