### ISSUE TITLE
SMTP Settings

### ISSUE THREAD

**Issue by Killdore** [roundcube/roundcubemail#5888]
I cannot find the SMTP settings I can use for a XenForo-forum. Any help?

I know the username & password, just need the SMTP Hostname and port.

**Comment by alecpl** [comment]
We also do not know.

**Comment by Killdore** [comment]
What?

**Comment by alecpl** [comment]
This is Roundcube webmail software, we have no idea what XenForo-forum is.

**Comment by Killdore** [comment]
Yes, you're roundcube, i know. But I don't know what I'm going to put as Hostname and/or Port.
