### ISSUE TITLE
if php.ini does not have date.timezone set, roundcube 1.2.5 fails in an ungracefully way

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#5889]
If the php.ini file does not have date.timezone set to anything, then roundcube will get as far as showing the login screen, then after that just shows a blank/empty page of nothingness.

It would be nice if it could fail in a nicer way.  Barfing out an error message in the browser or server log would be sufficient.

I, and many others, encountered this when upgrading server software:

https://topicdesk.com/downloads/tools/roundcube-for-os-x-server/comment-page-5/#comment-1376

https://topicdesk.com/faqs/roundcube-installer/error-when-sending-mail-from-roundcube-webmail/comment-page-1/#comment-3538

https://topicdesk.com/downloads/tools/roundcube-for-os-x-server/comment-page-6/#comment-13892

In macOS 10.11 & Server.app 5.1.7, there's a /Library/Server/Web/Config/php/php.ini file that seems to automatically include something for date.timezone.  Starting in macOS 10.12, Apple made a deliberate change to deprecate that file, and it's no longer loaded, and thus PHP & roundcube see no timezone at all (I guess) and fail without any error message.

**Comment by alecpl** [comment]
I don't really see a reason to handle this nicely. This is a php exception I suppose and should be logged to the http server or roundcube error log.  If it didn't log anything then the system is broken even more. We can't handle this. There are many other similar things that we do not handle nicely. We don't want to check everything for performance reasons.

**Comment by alecpl** [comment]
Imho this is PHP bug: https://bugs.php.net/bug.php?id=73239.

**Comment by marclaporte** [comment]
Here is a Server Check feature for Tiki Wiki CMS Groupware: https://doc.tiki.org/Server-Check 

It provides 50+ contextual warnings (including this timezone one) to help site admin configure the server. It can be ran as a standalone (so before the web app is installed) or as part of Tiki.

Perhaps there could be something similar within Roundcube?

**Comment by alecpl** [comment]
@marclaporte Yes, we have already such check in the Roundcube installer. We also do a couple of checks in Roundcube itself, but we do this only for PHP settings that cause wrong behavior and no errors. In this case a clear error is produced in the log, so I don't see a point in adding this.
