### ISSUE TITLE
managesieve vacation doesn't find template in v1.3

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#5892]
While upgrading RC to v 1.3.0 I got several problems.

One of them is that the managesieve plugin works only partly.

If I use `$config['managesieve_vacation'] = 1;` in config I got the "Vacation" menu item, but if I click on it I get the following error message:

`PHP Error in /program/include/rcmail_output_html.php (614): Error loading template for`

A debug_print_backtrace brings the following:
```
#0 rcmail_output_html->parse(, ) called at [/program/include/rcmail_output_html.php:489] 
#1 rcmail_output_html->send() called at [/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php:318] 
#2 rcube_sieve_vacation->vacation_post() called at [/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php:37] 
#3 rcube_sieve_vacation->actions() called at [/plugins/managesieve/managesieve.php:209] 
#4 managesieve->managesieve_actions() called at [/program/lib/Roundcube/rcube_plugin_api.php:491] 
#5 rcube_plugin_api->exec_action(plugin.managesieve-vacation) called at [/index.php:289]
```

So it seams it doesn't provide a template file

**Comment by alecpl** [comment]
Works for me. The backtrace is strange. If you just click the Vacation menu a GET request is send, so $_POST variable is supposed to be empty in this case and it should not end up in line 318, but return immediately https://github.com/roundcube/roundcubemail/blob/04d9e8addcb6e7a7b6686dd99d9a3631234c3cb0/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php#L169

**Comment by alecpl** [comment]
No feedback.
