### ISSUE TITLE
Memory Leak on Internet Explorer

### ISSUE THREAD

**Issue by karlmendes** [roundcube/roundcubemail#5893]
If i used to open message on new window, the memory increase 15MB on new window, and if i close the windows, decrease 10MB.

**Comment by thomascube** [comment]
Deallocating memory after closing a window is the browser's job and out of reach for a web application developer. The fact that IE doesn't free all memory previously assigned isn't necessarily an indication of a memory leak but the browser's very own way to handle resources.

Please re-open if you have more details or evidence that this behaviour is only observable with Roundcube and no other web application.
