### ISSUE TITLE
Can't save multiple e-mails in eml format. Single e-mail possible

### ISSUE THREAD

**Issue by daniel56** [roundcube/roundcubemail#5896]
Hi! When you select a single email you can download it to your computer in .eml format but when you select multiple e-mails the option is grayed out. This is not very productive. Is it possible to enable this function?

**Comment by thomascube** [comment]
That's correct because .eml files can only contain one single message. You can however enable the `zipdownload` plugin in Roundcube which will allow you to download multiple messages as a zip file containing individual .eml files.

**Comment by daniel56** [comment]
Thanks for answering my question. Much appreciated.
