### ISSUE TITLE
Wrong behavior of the savetarget frame when check spelling is on

### ISSUE THREAD

**Issue by dsoares** [roundcube/roundcubemail#5897]
Since commit 46c96bf0, if the option `Check spelling before sending a message` is `on` and the message has spelling errors, the compose window after sending an email does not close. A blank page is opened like it was a new tab/window (i suppose it is the `savetarget iframe`), the email is sent, but the blank page remains open and the loading gear "Sending message..." stays forever spinning. The user can't click anything (does nothing), until he/she reloads the page. 

If `Check spelling before sending a message` is `off`, everything works ok.

Steps to reproduce:
1. Roundcube updated to a commit after 46c96bf0.
2. Settings -> Preferences -> Composing Messages -> Check spelling before sending a message (TRUE)
3. Mail -> Compose
4. Write something with spelling errors.
5. Click send.
6. A window opens alerting for the spelling errors. Close it.
7. Click send.

**Comment by dsoares** [comment]
The "problem" is this line: https://github.com/roundcube/roundcubemail/blob/46c96bf0c0daacd1310d6e64f90045c51f846142/program/js/app.js#L4777

without it, no blank page appears, message is sent and the screen is refreshed.

**Comment by alecpl** [comment]
I'm unable to reproduce on a current master.

**Comment by dsoares** [comment]
I will only be able to reproduce it next monday; please don't close the ticket yet.

**Comment by dsoares** [comment]
I've made a demo video, available at: 
https://www.fc.up.pt/pessoas/dsoares/files/roundcube_480.mov

Essential steps:
1. git clone https://github.com/roundcube/roundcubemail.git roundcube-git
1. cd roundcube-git
1. cp composer.json-dist composer.json
1. composer.phar install --no-dev
1. cp $MYDIR/config.inc.php config/.
1. bin/install-jsdeps.sh 
1. chown -R www:users . && chown apache:apache temp logs

Basic configuration:

[root@webmail rcgit]# grep -vE "^/" config/config.inc.php | sed -e '/^$/d'
```
<?php
$config['enable_installer'] = false;
$config['db_dsnw'] = 'mysql://rcuser:rcpass@localhost/rcdbname';
$config['default_host'] = 'ssl://myimapserver';
$config['default_port'] = 993;
$config['smtp_server'] = 'ssl://mysmtpserver';
$config['smtp_port'] = 465;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['support_url'] = '';
$config['ip_check'] = false;
$config['des_key'] = 'mydeskey';
$config['product_name'] = 'Roundcube Webmail GIT';
$config['plugins'] = array();
$config['language'] = 'pt_PT';
$config['spellcheck_engine'] = 'pspell';

```

**Comment by alecpl** [comment]
Confirmed using Chrome. There's no issue in Firefox.

**Comment by alecpl** [comment]
Fixed.
