### ISSUE TITLE
Unable to connect to managesieve server in ssl mode

### ISSUE THREAD

**Issue by tuxmaster** [roundcube/roundcubemail#5901]
OS: CentOS 7.3
PHP: php-5.4.16-42.el7
Sieve: dovecot-pigeonhole-2.2.10-7
RC version: 1.1.9

Rc can't connect to the sieve server.

An local connect via:
`openssl s_client -connect localhost:4190`
will work.
Errors, that I can see:
ERROR: Not currently in AUTHORISATION state (1)
ERROR: Failed to read from socket ()
PHP Error: Unable to connect to managesieve on localhost:4190

Settings:
```
$config['debug_level'] = 1;
$config['managesieve_usetls'] = true;
$config['managesieve_debug'] = true;
$config['managesieve_host'] = 'tls://localhost';
```
Disable SSL on the server will work, but it is not an option.

**Comment by alecpl** [comment]
Roundcube 1.1.9 is not supported. TLS works for me with Roundcube 1.3.0.
