### ISSUE TITLE
Roundcube search() function - Search criteria provided by array missing

### ISSUE THREAD

**Issue by Cuiry** [roundcube/roundcubemail#5906]
Hello, 

I'd like to kindly ask you if there is a chance that this TODO will be fullfiled?
**TODO**: Search criteria should be provided in non-IMAP format, eg. array
It is located in these files:
_lib/Roundcube/rcube_imap.php
lib/Roundcube/rcube_storage.php_
$str parameter is String and I'd really need that I can input Array as a parameter and it's going to filter emails according to the array values.

Thanks in advance for your reply.

**Comment by alecpl** [comment]
The idea was to make the input format more general and not imap protocol specific. But as noone yet have a need for non-imap storage support we do not plan on working on this.
