### ISSUE TITLE
Message error (FR) : "Quota d'envoi de mails dépassé"

### ISSUE THREAD

**Issue by YKA01** [roundcube/roundcubemail#5908]
Hello,
I could not send mail anymore from my  email adress Free when using Roundcude webmail site.
Indeed if I click to "send" I get always the following message error (in French):
"Quota d'envoi de mails dépassé"

This happend today. I used my mail still 15 years and it is the first time I am blocked !

Note that I have no message error if I use outlook...

What could I do to fixe this issue?

Thank you and regards,
Yves

**Comment by alecpl** [comment]
You exceeded disk size limit. Ask your mail provider for more size or just delete some mail.

**Comment by YKA01** [comment]
Thanks for your reply.
This is what I thought at first but my disk is filled at 4% and I could send mail if I do not used roundcube (outlook...).
For me the issue is in Roundcube application

**Comment by YKA01** [comment]
Hello again!
I check this morning and it is working again!

**Comment by YKA01** [comment]
Issue is fixe
