### ISSUE TITLE
Roundcube password with foreign chars

### ISSUE THREAD

**Issue by kaarpik** [roundcube/roundcubemail#5909]
Hey everyone,
I have a problem with new password which I just set. The new password have Polish characters (e.g like "Miś6pyś"). System accepted new password and I save it in a google Chrome. After my logging out roundcube claim that given password is wrong. I tried to type my old password and a new one by hand and by using Chrome but none of it work. What happened and what should I do ?

**Comment by alecpl** [comment]
```
/ Password character set.
// If your authentication backend supports it, use "UTF-8".
// Otherwise, use the appropriate character set.
// Defaults to ISO-8859-1 for backward compatibility.
$config['password_charset'] = 'ISO-8859-1';
```
So, it depends on your backend if these special characters are handled correctly. I'd try using UTF-8, but it might not work for everyone.
