### ISSUE TITLE
Enigma plugin: Fallback to no encryption if no key present

### ISSUE THREAD

**Issue by taalas** [roundcube/roundcubemail#5913]
Hi!

If the option to encrypt messages is enabled globally, sending a message will fail if no key is present for the intended receiver. Would it be possible to include a fallback to send messages non-encrypted if no key is present (while informing the user) or possibly add a button to the modal dialog to send the message unencrypted?

Currently the user has to enable/disable encryption based on key availability when switching between sending encrypted and non-encrypted messages.

**Comment by alecpl** [comment]
A button in the dialog to send unencrypted is not a bad idea.

**Comment by taalas** [comment]
That would be excellent, thank you.

**Comment by taalas** [comment]
Sorry, wasn't sure if you needed this closed or not...

**Comment by alecpl** [comment]
Done.

**Comment by taalas** [comment]
Thanks for implementing this. Is there any chance release could be bumped to a 1.3.x release? This should not interfere with other mechanisms, right?

**Comment by alecpl** [comment]
This is not a big change, but 1.3 is for bugfixes only.
