### ISSUE TITLE
Enigma plugin: decrypting a signed message if signature check fails

### ISSUE THREAD

**Issue by taalas** [roundcube/roundcubemail#5914]
Hi!

When receiving a signed and encrypted message decryption fails if the sender's signature cannot be verified (because the receiver does not know the sender's public key). Is this intended behaviour? Wouldn't it be possible to decrypt the contents without signature verification (and thus being able to read the contents)?

**Comment by alecpl** [comment]
What version are you using? If it does not decrypt the message it might be a bug.

**Comment by taalas** [comment]
This happens in Roundcube 1.3.0 when receiving a signed and encrypted message while not having the sender's public key. As soon as the public key is added to the key ring the message's signature is validated and the message decrypts. When not having the public key, validation fails and the message stays encrypted (which afaik should be independent from the signature validation).

**Comment by alecpl** [comment]
Works for me. So, it might depend on the message format or GnuPG version. Is this pgp/plain or pgp/mime format? Could you provide enigma_debug output?

**Comment by taalas** [comment]
This is a standard Roundcube 1.3 installation without using a specific configuration file for enigma (so I assume it uses standard values). Could you provide information where I can identify whether pgp/plain or pgp/mime is used? Should I upload a debug log to a gist or post it here directly?

**Comment by alecpl** [comment]
I was talking about the message format. So, provide the message source (you can remove binary blob). Yes, you can post debug here.

**Comment by taalas** [comment]
Hi!

GnuPG version is 1.4.16.

A gist containing the debug log:
https://gist.github.com/taalas/4d3b20050f0f8768d6e2f40f7ffb49a9

This is the part of the log that happened when opening a signed and encrypted mail without being able to confirm the signature (message window shows "decryption failed").

As for the message format, would the mail's header be sufficient?

**Comment by taalas** [comment]
Thank you for confirming this. Do you have a rough estimate as to when this might be resolved (since we are using this feature in a productive environment)?

**Comment by alecpl** [comment]
I'll try to work on this this week, but I can't promise anything.

**Comment by taalas** [comment]
That's totally fine. A rough estimate is all we needed ;) Thanks!

**Comment by alecpl** [comment]
This is fixed now. Note that this requires Crypt_GPG 1.6.1 to work.
