### ISSUE TITLE
Responsive signature: Roundcube filters <!-- comments -->

### ISSUE THREAD

**Issue by osos** [roundcube/roundcubemail#5915]
I am trying to implement a responsive signature based on the knowledge here: https://www.codetwo.com/kb/responsive-signature/

The concept works fine, however, Roundcube HTML-signature editor filters and deletes this:

`<!--[if gte mso 9]>`
`    <table><tr><td>`
`<![endif]-->`
`<DIV style="float: left;">`
`            BLOCK A`
`</DIV>`
`<!--[if gte mso 9]>`
`    </td><td>`
`<![endif]-->`
`<DIV style="float: left;">`
`            BLOCK B`
`​</DIV>`
`<!--[if gte mso 9]>    `
`</td></tr></table>`
`<![endif]-->`

to become:

`<DIV style="float: left;">`
`            BLOCK A`
`</DIV>`
`<DIV style="float: left;">`
`            BLOCK B`
`​</DIV>`

Which renders the signature not shown correctly in Outlook 2010 - 2016.

Any suggestions?

**Comment by alecpl** [comment]
Just don't use conditional comments. We'll not modify TinyMCE editor to support them.
