### ISSUE TITLE
is it possible to rewrite the email search logic?

### ISSUE THREAD

**Issue by vtista** [roundcube/roundcubemail#5919]
for some imap servers they don't allowed to excute imap_search.
my idea is set message cahe to 100000 and store into database then search from databse and display.
can you help me on this?

**Comment by alecpl** [comment]
Saving 100000 entries to the cache when it is empty will most likely exceed script execution limit. Anyway, that would be a significant work. What help do you expect?

**Comment by vtista** [comment]
saving 100000 entries is fine,i've tested . only first time ,the loading gonna be long.after loading all the emails , we can change back to 50 to display.
i want to know how to search from cached messages insteaded of imap_search from imap server?

**Comment by alecpl** [comment]
This is not possible with current format of cached messages. They are stored in a serialized form, so you can search directly only (some) message flags. You'll need to redesign internal format, and split the search data to separate columns.
