### ISSUE TITLE
Message Body not showing - nginx (Roundcube 1.3.0)

### ISSUE THREAD

**Issue by bennabiy** [roundcube/roundcubemail#5923]
I am able to bring up roundcube, log in, and see the message lists in my inbox, but I do not get anything in the preview pane, and when I click a message, I just get loading....

Looking at the DOM errors, I get this (slightly sanitized)

> Refused to display 'https://webmail.somewhere.net/skins/larry/watermark.html' in a frame because it set 'X-Frame-Options' to 'deny'.
> ?_task=mail&_mbox=INBOX&_token=aWbFdryWq0KFUsuyZkePnKYYVO80d0BH:418 GET https://webmail.somewhere.net/skins/larry/watermark.html net::ERR_BLOCKED_BY_RESPONSE
> /?_task=mail&_mbox=INBOX:1 Refused to display 'https://webmail.somewhere.net/skins/larry/watermark.html' in a frame because it set 'X-Frame-Options' to 'deny'.
> app.min.js?s=1498503408:125 GET https://webmail.somewhere.net/skins/larry/watermark.html net::ERR_BLOCKED_BY_RESPONSE
> show_contentframe @ app.min.js?s=1498503408:125
> clear_message_list @ app.min.js?s=1498503408:129
> list_mailbox @ app.min.js?s=1498503408:128
> command @ app.min.js?s=1498503408:70
> init @ app.min.js?s=1498503408:43
> (anonymous) @ ?_task=mail&_mbox=INBOX&_token=aWbFdryWq0KFUsuyZkePnKYYVO80d0BH:551
> j @ jquery.min.js?s=1498503424:36
> k @ jquery.min.js?s=1498503424:36
> setTimeout (async)
> (anonymous) @ jquery.min.js?s=1498503424:36
> i @ jquery.min.js?s=1498503424:36
> fireWith @ jquery.min.js?s=1498503424:36
> fire @ jquery.min.js?s=1498503424:36
> i @ jquery.min.js?s=1498503424:36
> fireWith @ jquery.min.js?s=1498503424:36
> ready @ jquery.min.js?s=1498503424:36
> S @ jquery.min.js?s=1498503424:37
> app.min.js?s=1498503408:124 Uncaught DOMException: Blocked a frame with origin "https://webmail.somewhere.net" from accessing a cross-origin frame.
>     at rcube_webmail.show_contentframe (https://webmail.somewhere.net/program/js/app.min.js?s=1498503408:124:459)
>     at rcube_webmail.msglist_select (https://webmail.somewhere.net/program/js/app.min.js?s=1498503408:104:160)
>     at https://webmail.somewhere.net/program/js/app.min.js?s=1498503408:42:15
>     at rcube_list_widget.triggerEvent (https://webmail.somewhere.net/program/js/common.min.js?s=1498503408:40:218)
>     at rcube_webmail.http_response (https://webmail.somewhere.net/program/js/app.min.js?s=1498503408:315:502)
>     at Object.success (https://webmail.somewhere.net/program/js/app.min.js?s=1498503408:309:464)
>     at i (https://webmail.somewhere.net/program/js/jquery.min.js?s=1498503424:36:28017)
>     at Object.fireWith [as resolveWith] (https://webmail.somewhere.net/program/js/jquery.min.js?s=1498503424:36:28783)
>     at A (https://webmail.somewhere.net/program/js/jquery.min.js?s=1498503424:38:14035)
>     at XMLHttpRequest.<anonymous> (https://webmail.somewhere.net/program/js/jquery.min.js?s=1498503424:38:16323)

**Comment by alecpl** [comment]
Check you http server configuration. Rouncube requires frames.

**Comment by bennabiy** [comment]
I fixed it. It was an error on my part.
