### ISSUE TITLE
Message no longer marked as read when opened

### ISSUE THREAD

**Issue by dapphp** [roundcube/roundcubemail#5925]
In 1.3.0, this happens for all layouts (Widescreen, Desktop, and List).  I compared the behavior between 1.2.5 and 1.3 and something has changed in how messages are marked upon opening.

My setting for "Mark previewed messages as read" is either set to 5 seconds, or never when testing.

In List view, double clicking a message to open it and then waiting a few seconds and pressing back results in the message still being unread.  In previous versions, as soon as the message is opened it would be marked read, regardless of the "previewed" setting.

If I set the preview value to 5 seconds, I have to open the message for at least 5 seconds to have it marked read.  Since I'm not previewing and am actually opening the message, it should be marked read immediately upon opening like previous versions, especially when that value is set to never.  Otherwise messages have to be marked manually.

In the new widescreen mode, the same thing happens.  If "Open messages in a new windows" is disabled, and my preview time is set to 5 seconds, pressing Enter to open a message results in it opening on top of the message list and preview.  Pressing back within 5 seconds, the message is still unread.  In this scenario, I think it should also be marked read after opening.

Let me know if I can provide further information.

Tested in 2 production environments (1.3.0, 1.2.6) and in a clean install of RC 1.3.0 in a testing environment.

**Comment by alecpl** [comment]
Yes, this is an intended change. Now the option applies to both preview frame and full page preview. So, not a bug.

**Comment by thomascube** [comment]
For reference, this was changed in #5071.

Probably we should adapt the label from "Mark previewed messages as read" to "Mark viewed messages as read" in order to be more clear.

**Comment by dapphp** [comment]
Hi Thomas,

Thanks for pointing out the reference.  I suppose that makes sense and RC seems to be in line with Thunderbird's behavior now.  I agree though that the translation should be updated to reflect the change so it's more clear.
