### ISSUE TITLE
Roundcube Webmail - Settings - Filters Tab is not responding

### ISSUE THREAD

**Issue by pinalalliance** [roundcube/roundcubemail#5926]
the "Filters" tab under settings is not loading at all. I need the page to load so that I can forward my emails to a different address.

**Comment by alecpl** [comment]
Check the log for any errors. Works for me.

**Comment by thomascube** [comment]
This is an invalid ticket. Please contact your internet hosting provider or IT responsible for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Roundcube is not a service but free software which your hosting provider installed on their servers.
