### ISSUE TITLE
new_user_dialog email check can be circumvented by deleting / abandoning session

### ISSUE THREAD

**Issue by duk3luk3** [roundcube/roundcubemail#5929]
Because `new_user_dialog` uses a session flag to check whether to pop up the dialog:

https://github.com/roundcube/roundcubemail/blob/e61121dc2f6a3fd154b9f16c41789fb6ae721ff8/plugins/new_user_dialog/new_user_dialog.php#L38

The dialog, and email validation, can be circumvented by invalidating the user session (by abandoning it until it expires or deleting the session cookie), resulting in a potentially invalid email in an identity if the email address is automatically determined from the login name and then login name contains an '@', but is not a valid email address:

https://github.com/roundcube/roundcubemail/blob/e61121dc2f6a3fd154b9f16c41789fb6ae721ff8/program/lib/Roundcube/rcube_user.php#L648-L653

There are at least two approaches to solving this problem:

1. Making the email guessing in `rcube_user::create` more robust
2. Making new_user_dialog more persistent

Since imho it would be nice not to duplicate the "is this a valid email address" check ([here](https://github.com/roundcube/roundcubemail/blob/master/plugins/new_user_dialog/new_user_dialog.php#L160), also [here](https://github.com/roundcube/roundcubemail/blob/master/program/steps/settings/save_identity.inc#L79)) through even more places, and adjusting the email guessing can never be perfect and is doing a "good enough" job for common usecases (uncommon usecases will just have to make adjustments for their own roundcube setups), I believe that the second solution would be more suited.

It could probably be achieved by checking for invalid identities on login and then popping up the dialog, irrespective of session flags; or by adjusting how the 'incomplete' flag for identities work (I haven't investigated this in detail which is why I'm being a big vague.)

If a consensus can be reached here about what to do I'll be happy to contribute a PR.

**Comment by alecpl** [comment]
`identity_create` hook is invoked when the user record already exists so we could store the flag in user preferences, e.g.
```
$rcmail->user->save_prefs(array('newuserdialog' => true));
```
then we can read that using config object
```
$rcmail->config->get('newuserdialog');
```
and unset it with:
```
$rcmail->user->save_prefs(array('newuserdialog' => null)); // or false if null does not work
```

**Comment by alecpl** [comment]
Fixed.
