### ISSUE TITLE
show preview pane - classic skin - ver 1.3.0

### ISSUE THREAD

**Issue by devops365** [roundcube/roundcubemail#5930]
Hello,

So I updated from a far old version to 1.3.0. I only use classic skin on my roundcube.

While browsing the mailbox, the checkbox that used to say show preview pane, is now gone.
If I tamper with my user on the database and change the s:1:0 , its always on.
So the function of preview works, however the checkbox is missing.

I also don't see the preview pane option in my user's settings from within roundcube.

Did I miss something while updating or this is a bug ? I've searched the configs as well, nothing seems to be wrong on my side.

Thanks

**Comment by alecpl** [comment]
The checkbox has been replaced with layout switch. https://kolabian.wordpress.com/2016/09/17/widescreen-layout-aka-three-column-view/

**Comment by devops365** [comment]
Hello Alexpl,

Thank you for your swift response.
I saw that as well, however, my roundcube also doesn't open as a three column view on my user, also not finding such an option on my user preferences.
In the defaults config I've set widescreen as default.
So maybe there is a bug for existing users possibly ?
