### ISSUE TITLE
New email missing bullets and numbers

### ISSUE THREAD

**Issue by deZillium** [roundcube/roundcubemail#5931]
In v1.3 when typing a new message, the editor is missing bullets and numbers buttons, ie there is no way to type the following without manually typing them:

- item 1
- item 2
- item 3

1. item 1
2. item 2
3. item 3

This funtionality was available in previous versions and is a much needed feature.

**Comment by alecpl** [comment]
Works for me. I see the buttons. Do you have HTML editor enabled at all? What browser? What skin? Any javascript errors in console?

**Comment by alecpl** [comment]
No feedback.

**Comment by deZillium** [comment]
Yes, HTML editor is enabled
Chrome and Firefox browsers
Classic skin
No javascript errors in console
