### ISSUE TITLE
RC 1.3.0 does not write image thumbnails but tries to read them

### ISSUE THREAD

**Issue by duk3luk3** [roundcube/roundcubemail#5933]
With rc 1.3.0 I get pink rectangles instead of picture thumbnails, with this error in the log:

```
PHP Warning:  file_get_contents(/srv/roundcubemail-1.3.0/temp/95b2b487745247921bfbd4779004322e.tmp): failed to open stream: No such file or directory in /srv/roundcubemail-1.3.0/program/steps/mail/get.inc on line 536
```

With rc 1.2.5 it works fine so this might be a bug.

**Comment by alecpl** [comment]
Works for me. Is the folder writeable? Does it happen for every mail with attached images? What PHP version?

**Comment by duk3luk3** [comment]
> Is the folder writeable?

Yes.

> Does it happen for every mail with attached images?

I only tested jpeg images, but I can see that nothing is ever written to the temp folder.

> What PHP version?

apache2 mod_php 5.6

I actually went and put in some logging, and it seems the file is deleted too early:

```
Sep 01 17:02:52 vmrbg98 roundcube[14926]: <8fcmvruq> wrote body_file: /srv/roundcubemail-1.3.0/temp/f649ef3e893800ae568dbbfd4b25c070.tmp
Sep 01 17:02:52 vmrbg98 roundcube[14926]: <8fcmvruq> unlinked in line 99: /srv/roundcubemail-1.3.0/temp/f649ef3e893800ae568dbbfd4b25c070.tmp
Sep 01 17:02:52 vmrbg98 roundcube[14926]: PHP Warning:  file_get_contents(/srv/roundcubemail-1.3.0/temp/f649ef3e893800ae568dbbfd4b25c070.tmp): failed to open stream: No such file or directory in /srv/roundcubemail-1.3.0/program/steps/mail/get.inc on line 538
```

The "line 99" referred to by the log is line 98 of steps/mail/get.inc:

https://github.com/roundcube/roundcubemail/blob/e61121dc2f6a3fd154b9f16c41789fb6ae721ff8/program/steps/mail/get.inc#L77-L99

**Comment by alecpl** [comment]
Ok, it looks that the image resize fails for some reason. I think we should move the unlink() call. I think I know what's going on here now. Thanks, will investigate more.

**Comment by alecpl** [comment]
Actually we can just remove the unlink() at all, because we do this in rcmail_attachment_handler destructor. Why the image resize fails is another story and you should investigate this too.

**Comment by duk3luk3** [comment]
I agree with you that just removing the unlink call entirely looks like the correct solution.

After following the rabbit hole down into `rcube_image.php` I started to suspect Imagemagick; installing php-imagick and restarting apache actually fixed the problem.

Should imagick be listed in the "suggest" or "require" section of composer.json? It's not mentioned in the INSTALL document either; the only place I can find any reference to it is in [defaults.inc.php](https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L615).

Would you like me to make a PR that removes the unlink call and adds imagick to composer.json?

**Comment by alecpl** [comment]
No need for a PR as it's simple enough for me ;) It will wait anyway for 1.3.2, as we're in a release process right now.

If php-imagick is not installed, you can still configure Roundcube to use Imagemagick. And there's fallback to php-gd. So, I guess you also didn't have the php-gd installed, right?

We do not list suggested/required PHP modules in composer.json at all. We do this in INSTALL file, but indeed there's no word about imagick and gd. So, I'll add that, as well as some Installer checks.

**Comment by alecpl** [comment]
Done.
