### ISSUE TITLE
An official Roundcube installer on Packagist.org

### ISSUE THREAD

**Issue by marclaporte** [roundcube/roundcubemail#5938]
Roundcube already has some packages on Packagist.org:
https://packagist.org/packages/roundcube/

Roundcube uses Composer and its own instance of Packagist to manage Roundcube plugins:
https://plugins.roundcube.net

An unofficial Roundcube installer has over 40 000 installs:
https://packagist.org/packages/imscp/roundcube

How far can we be to using Packagist as an official way to manage Roundcube?

Thanks!

**Comment by thomascube** [comment]
Composer is primarily used to install modules into a project of your own (you need to create a composer.json file first before you can `composer install` or `composer require`). Like the i-MSCP project from your example above.

Roundcube is not a package you usually pull into another project but a standalone application which needs proper setup and configuration. I honestly don't see the point for using Composer to install and manage Roundcube. The more convenient way is to use OS package managers and we're already in the major ones.

**Comment by alecpl** [comment]
And too much effort for something that does not really improve Roundcube itself. As for the official docker container, I'm not interested in working on this.

**Comment by marclaporte** [comment]
@thomascube: "I honestly don't see the point for using Composer to install and manage Roundcube"
44k installs see a point :-)
https://packagist.org/packages/imscp/roundcube

@alecpl: I didn't mention anything about Docker. Perhaps this is for another thread?

**Comment by com2** [comment]
I think "composer update" is a strong argument. Ubuntu's repository version is always behind and I am not sure if all sucurity patches are backported to that still version 1.3.6. 

I think that a packagist package that links to a github repository would be more easy to update and maintain. Why not use composer to integrate roundcube in an OS? This is done with other application like Drupal where composer is the recommended way of installing and maintaining.
