### ISSUE TITLE
Race condition when deleting all messages from a mailbox folder

### ISSUE THREAD

**Issue by sffax** [roundcube/roundcubemail#5941]
After upgrading Roundcube to version 1.3.1, I started noticing an issue when users click the 'delete' button in quick succession to remove all messages from a folder one by one (a popular way to empty the trash folder apparently). After the last email is removed, the preview frame will display a re-render of the entire window content (along with clickable links and all) instead of an empty space. This only happens -- from what I can tell --  if the last 'delete' click comes in before the button gets disabled in the UI. It is hard to reproduce on a fast connection, but it becomes very reproducible on a slower link.

Also worth mentioning that I can trigger this with both the new 3-column layout and the traditional desktop layout so it is not layout specific. Older versions did not have this problem.

Below is an image which highlights the problem:
_(when the mailbox is empty, the right side should be blank)_

![image](https://user-images.githubusercontent.com/10953134/30146570-0f098698-9356-11e7-841b-e117e80b334c.png)

**Comment by alecpl** [comment]
@thomascube This might be a regression caused by the double-click fix.

**Comment by alecpl** [comment]
There's some error in console: TypeError: rows[uid] is undefined in app.js:2854:7.
There's also a bug in the template caused by 1b4fa60a9025.

**Comment by alecpl** [comment]
Template issue is resolved now. The race condition is not and it needs addressing because beside the preview problem we have javascript error and a dummy entry on the list.

**Comment by alecpl** [comment]
I added some code to prevent from ghost messages that can cause the issue. I consider this fixed.
