### ISSUE TITLE
$config['managesieve_vacation'] = 1 not work version 1.3

### ISSUE THREAD

**Issue by freexmonster** [roundcube/roundcubemail#5942]
Hello! I upgrade  Roundcubemail server to 1.3 version, missing settings Vocation
**$config['managesieve_vacation'] = 1**  on to config.inc.php
I need to help! We have 3,000 customers who want to leave xD

**Comment by alecpl** [comment]
Works for me. Exactly what version? What skin? What other plugins installed?

**Comment by freexmonster** [comment]
Roundcube Webmail 1.3.0 
default theme Larry
acl | 1.6 | GPLv3+ |  
additional_message_headers | 1.2.1 | GPLv2 |  
archive | 3.0 | GPLv3+ |  
attachment_reminder | 1.1 | GPLv3+ |  
autologon | 1.0 | GPLv3+ |  
automatic_addressbook |   | GPL-3.0+ | Загрузить
calendar | 3.2.9.1 | AGPLv3 | Загрузить
contextmenu | 2.1-git | GPL-3.0 | Загрузить
dovecot_impersonate | dev-master | GPL-2.0 | Загрузить
emoticons | 2.0 | GPLv3+ |  
filesystem_attachments | 1.0 | GPLv3+ |  
help | 1.4 | GPLv3+ |  
image_paster |   | GPL-3.0+ | Загрузить
jqueryui | 1.12.0 | GPLv3+ |  
libcalendaring | dev-master | AGPLv3 | Загрузить
managesieve | 8.7 | GPLv3+ |  
markasjunk | 1.2 | GPLv3+ |  
newmail_notifier | 0.8 | GPLv3+ |  
new_user_dialog | 2.1 | GPLv3+ |  
new_user_identity | 1.1 | GPLv3+ |  
persistent_login | 5.0.0 | GPL-3.0+ | Загрузить
subscriptions_option | 1.3 | GPLv3+ |  
vcard_attachments | 4.0 | GPLv3+ |  
zipdownload | 3.3 | GPLv3+ |  

You responded so quickly that I was surprised xD

**Comment by alecpl** [comment]
First make sure the config is readable. Then check error log and javascript console for errors. Make sure upgrade properly updated managesieve plugin files. Then you can test with disabled all plugins except managesieve. I don't know what that could be.

**Comment by alecpl** [comment]
No feedback.
