### ISSUE TITLE
"Flattened" larry theme

### ISSUE THREAD

**Issue by julianwap** [roundcube/roundcubemail#5947]
I'm a very optical person and the patterns, gradients and shadows of the larry theme made it and the roundcube application so special to me. In my opinion, roundcube looks like every other boring website with the flat theme.

A new theme ("LarryFlat") or a option should be created if such a major change, like making it flat, is done to a theme to give the users the chance to switch back to the original theme.

Sorry if this is not really a bug but I'm one of those person which dislike this "Flat UI-Hype".

**Comment by julianwap** [comment]
Not resolved.

**Comment by thomascube** [comment]
Apologies for the rejection of your issue. Design is always a matter of taste and whatever we do, we can't make it right to everybody. The flattened Larry theme was a reaction on various complaints that Roundcube looks outdated and crappy. Please understand that we're lacking the resources to maintain a number of themes and "old versions" simultaneously and the decision was made to continue like this while an entirely new responsive skin is in the works.

However, Roundcube is free software and the skins we provide(d) are under a creative commons license. Thus everybody is free to copy an old or new version of the Larry theme, modify it and maintain it as an alternative to the upstream themes we provide.

**Comment by julianwap** [comment]
Thank you for taking me serious and writing a normal response.
If well argued I can accept your decision.
