### ISSUE TITLE
dead link: /var/www/sites/roundcubemail/vendor/pear/net_smtp/README.rst

### ISSUE THREAD

**Issue by cgzones** [roundcube/roundcubemail#5949]
Roundcube 1.3.1 ships a dead link `/var/www/sites/roundcubemail/vendor/pear/net_smtp/README.rst` with a target `docs/guide.txt`

**Comment by alecpl** [comment]
@thomascube Please add this path for removal in your scripts for generating release tarballs.

**Comment by thomascube** [comment]
Fixed in build script at https://gist.github.com/thomascube/2725894
