### ISSUE TITLE
Error: rewind(): stream does not support seeking

### ISSUE THREAD

**Issue by dol** [roundcube/roundcubemail#5950]
rcube_message::get_part_body performs a rewind() on the stream.
In the file https://github.com/roundcube/roundcubemail/blob/1.2.6/program/steps/mail/get.inc#L503  a 'php://output' is created, which not supports rewinding. This will trigger an error.
Possible solution could be: https://github.com/thephpleague/glide/pull/137/files

This part was removed in 1.3 and we are safe.

**Comment by alecpl** [comment]
I hesitate to use ftell() because of "ftell() gives undefined results for append-only streams" in the documentation. We could use stream_get_meta_data(), but I think it's too much effort, we can just ignore the warning. Fixed in master and backported to release-1.2 branch.

**Comment by dol** [comment]
Thx
