### ISSUE TITLE
Wrong timezone detection in IE

### ISSUE THREAD

**Issue by urfin73** [roundcube/roundcubemail#5951]
Hello!
I updated roundcube to version 1.3.1, and got the following problem: When setting the time zone in roundcube - auto, chrome browser gets the correct timezone +3, and Internet Explorer browser gets not the correct +4.
How can I fix it?

**Comment by alecpl** [comment]
For timezone detection we're using https://bitbucket.org/pellepim/jstimezonedetect library, most recent version. There's not much we can do about your issue.

**Comment by alecpl** [comment]
An option would be Internationalization API (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/resolvedOptions), but this does not work in IE anyway.

There's another timezone detection lib https://github.com/moment/moment-timezone/, but it also has some issues.

**Comment by alecpl** [comment]
One correction. Jstz already uses Internationalization API.

**Comment by urfin73** [comment]
Thank you for your assistance. I personally also dislike IE. But it is still widely used. We will save ourselves by setting the local time zone in roundcube.

**Comment by alecpl** [comment]
It looks we can do nothing about this issue. Closing.
