### ISSUE TITLE
Marking messages as read when opening via double-click

### ISSUE THREAD

**Issue by taalas** [roundcube/roundcubemail#5952]
When opening a message via double-click the message used to be marked as read regardless of the setting for marking messages when previewing them (in 1.1.x). On the latest version the message stays unread even when opening it. Is this planned behaviour or is the functionality missing in the latest version?

**Comment by alecpl** [comment]
You're talking about "Mark previewed messages as read" setting? Yes, in 1.3 it applies to both preview frame and full screen preview. We'll consider small rename (s/previewed/viewed/ or sth like that) to make it less confusing.

**Comment by taalas** [comment]
Thanks! Yes, that is the setting I was referring to.

So, setting this to "never" will currently prevent a status change to "read" on:
- single clicking a message and previewing it
- double clicking a message and viewing it in either a full screen frame or a new window/tab

The only way to mark a message as read is then to explicitely change the star icon e.g.?

Is there any plan to incorporate a distinction as in 1.1.x LTS between previewing and viewing in the future in regards to the status? We have many users that are accustomed to this behaviour (from Roundcube but also other mail clients).

**Comment by alecpl** [comment]
There's no plan to revert that change. Fixed wording.

**Comment by taalas** [comment]
Would you consider

- either adding another option for this setting that allows to preview messages without marking them read but marking them as read when "opened" via double click (as many desktop mail clients do it)
- or adding another setting that toggles this behaviour

to be able to revert the user experience to what it was in earlier Roundcube versions?

**Comment by inforpsm** [comment]
Hello. Same problem with our users. After update from 1.2.x to 1.3.x they cannot mark as read after open e-mail with double-click. They have "never" on "Mark previewed messages as read" but opening with double-click is not preview and the e-mail not changes its state and we need to mark as read manually. With 1.2.x version or olders worked fine. Just we need that works same as all e-mail apps. Thank you for your empathy.
