### ISSUE TITLE
Freebsd/openbsd passwd plugin?

### ISSUE THREAD

**Issue by anexit1** [roundcube/roundcubemail#5953]
pw_usermod.php file use to work but the devs made it so you have to be root to run anything in pw.  Even if you attempt to do it with sudo it will fail.  Passwd would be a much better option, anyone willing to hack this?  I suspect chpasswd plugin would be the same with minor tweaking.

**Comment by alecpl** [comment]
I don't use *BSD so I'm not going to work on this. It looks you need a new driver, this is not something we'll work on.
