### ISSUE TITLE
Add the possibility to use the session variable %h in password plugin

### ISSUE THREAD

**Issue by jorgeasbastos** [roundcube/roundcubemail#5955]
Hi,

I have roundcube configured with the %h session variable in managesieve, and i want to use it also in the password plugin, so that i can update the password in the correct server.
The %h variable gives me the change to have several email servers, and just ONE roundcube instalation, which is sooooo fantastic !
Thing is, it doesn't work, I have:

$config['password_db_dsn'] = 'mysql://webmail:bdk#%%dz@%h/postfix';

but nothing! 
Is it possible to make it work, or am I doing something wrong?

Thanks in advanced,
Jorge Bastos

**Comment by alecpl** [comment]
There's no such feature indeed. It's because even with multi-server setups usually there's only one user master database. However, I agree we should add support for %h here.

**Comment by dddns** [comment]
Hi Alec,

Thank you for it!
In my instalations the only commun DB is for roundcube, the server info stays in each server.
At last for the host (after the @), for example the managesieve supports it.
That the only thing that is pending for me to finish my multiserver/centralized instalation.
If it's possible to add this to git master I'll pull it from there.

Thanks once again,
Jorge,

**Comment by dddns** [comment]
Alec,

As a workarround, could I use something like:

$_SESSION['config']['imap_host'] ?

**Comment by dddns** [comment]
Ok doesn't work, never mind.
What should be added if possible and in my opinion, is just the %h after the @ for host selection.

Any idea when will be added in trunk? Sorry for the question..

**Comment by alecpl** [comment]
That would be `$_SESSION['storage_host']`.

**Comment by alecpl** [comment]
Implemented.

**Comment by dddns** [comment]
Thank you thank you!!!
Best whishes for you Alec!

**Comment by dddns** [comment]
Hi Alec,

This is not included in 1.3.3, only for 1.4 branch?
Just to confirm.

**Comment by alecpl** [comment]
That's right. I think you should have no problems with using password plugin from master with 1.3.

**Comment by dddns** [comment]
Alec,

Thanks, that's what I've been doing, i compared the files and only change is the support you added on this ticket.
Thanks for your help,
