### ISSUE TITLE
html not rendering in roundcube

### ISSUE THREAD

**Issue by turbopascalwiz** [roundcube/roundcubemail#5957]
system - ubuntu 16.04
php - 7.0.22-0ubuntu0.16.04.1 
it's a very straightforward install, no real fancy stuff, but it is not working out of the box, i get basically the 'code' not a rendering of the html.

the release indicated by the CHANGELOG is 1.3.1

*plain text works fine

**Comment by alecpl** [comment]
Are you talking about mail preview or composing? Any errors in log? Any errors in javascript console? Did you try with disabled all plugins? Did you try with different browser? What browser?

**Comment by turbopascalwiz** [comment]
->mail preview
I use firefox or chrome-google and both yield the same result.

i used all the plugins originally, but then I disabled all of them, same result.

in firefox, under the browser console (JS) this error consistently pops up:
`can't access dead object WebRequestCommon.jsm:49
	typeMatches resource://gre/modules/WebRequestCommon.jsm:49:5
	shouldRunListener resource://gre/modules/WebRequest.jsm:687:12
	runChannelListener resource://gre/modules/WebRequest.jsm:878:14
	examine resource://gre/modules/WebRequest.jsm:1048:7
	observe`

In the error log for roundcube...

nothing shows up at all, except for the early errors while establishing the service, i page through the emails in preview of the html code, nothing pops up under tail -f ./errors log is set to 1 or 4, same result (defaults).

I imagine that there is a process where the code is flipped from text to code inside the pane, but it's not happening. Any suggestions are welcome. It's been a while since i trouble-shot j/s & html5. not terribly interested, but if i get a clue/direction I can try.

**Comment by turbopascalwiz** [comment]
well this fixed it, now i just need to get the images working, probably one of the plugins i disabled.

>>> http://www.roundcubeforum.net/index.php/topic,24510.0.html <<<<

$node->tagName ==> $node->nodeName

**Comment by alecpl** [comment]
That's interesting. DOMElement has tagName property defined, but DOMNode does not. Still I have no idea why that does not work for you.

**Comment by alecpl** [comment]
Fixed.
