### ISSUE TITLE
Enigma does not correctly decrypt if message body is charset=utf-8

### ISSUE THREAD

**Issue by osenft** [roundcube/roundcubemail#5962]
Message that have the PGP MESSAGE block in the message body is encoded in utf-8 cannot be decrypted by Enigma.

Example:

```
MIME-Version: 1.0
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable


-----BEGIN PGP MESSAGE-----
Charset: utf-8
Version: GnuPG v2
=C2=A0
hQQOA+oWyIZvKMksEA/8DhnwxWuYe7bhdoNMBrytmv+ubzF8RGJFpy+B9yswBtse
7nKtb0b+3Jf+fnAn/UVPC4xrKwYxUv2FtNYpb3WEvdpPVor8RVew0BWl4a4/Sna/
SRPHgVNSP7z17X0F9Zz0CbSRTPnB8BHholTBISP7eQJTJueshD8evrf1OAseAKVM
E35ij6AX+CFlrpWknFeXexCnUUSyISeIk9p4tUzravkd6SUMFp+FH7OUXw+x682c
...
```

After enabling enigma_debug, I see the following in /var/log/roundcube/enigma:
```
[22-Sep-2017 10:26:24 -0400]: <gk8a58b6> GPG: ERROR: gpg: invalid armor header:  \r\n
[22-Sep-2017 10:26:24 -0400]: <gk8a58b6> GPG: ERROR: gpg: invalid radix64 character C2 skipped
[22-Sep-2017 10:26:24 -0400]: <gk8a58b6> GPG: ERROR: gpg: invalid radix64 character A0 skipped

```

**Comment by osenft** [comment]
This case is handled by plugins/enigma/lib/enigma_engine.php get_part_body(). I printed the retrieved $body into a log file and found that the '=C2=A0' is literally included as 0xc2 0xa0:

```
00000000  2d 2d 2d 2d 2d 42 45 47  49 4e 20 50 47 50 20 4d  |-----BEGIN PGP M|
00000010  45 53 53 41 47 45 2d 2d  2d 2d 2d 0a 43 68 61 72  |ESSAGE-----.Char|
00000020  73 65 74 3a 20 75 74 66  2d 38 0a 56 65 72 73 69  |set: utf-8.Versi|
00000030  6f 6e 3a 20 47 6e 75 50  47 20 76 32 0a c2 a0 0a  |on: GnuPG v2....|
00000040  68 51 51 4f 41 2b 6f 57  79 49 5a 76 4b 4d 6b 73  |hQQOA+oWyIZvKMks|
...
```

These characters are indeed not valid to be passed to GPG.

I further found that get_part_body explicitly disables encoding conversion if the whole body is retrieved.

The fix seems to add an explicit conversion from the part's charset to US-ASCII:
```
--- plugins/enigma/lib/enigma_engine.php.orig	2017-09-22 11:51:26.974404213 -0400
+++ plugins/enigma/lib/enigma_engine.php	2017-09-22 11:37:45.892960537 -0400
@@ -1196,6 +1196,7 @@
         }
         else {
 	    $body = $msg->get_part_body($part->mime_id, false);
+            $body = rcube_charset::convert($body, $part->charset, 'US-ASCII');
         }
 
         return $body;
```

With this additional line, Enigma is able to correctly decrypt UTF-8 and ISO-8859-15 encoded messages.

**Comment by alecpl** [comment]
It's not a matter of charset. The \r\n sequence is just not allowed there. However, if that's a common case we could add a workaround. What client was this message created with?

**Comment by alecpl** [comment]
Sorry, it's not \r\n, it's a no-break space in unicode. So, maybe indeed the best way will be to use conversion to ASCII.

**Comment by osenft** [comment]
I'm not sure where the \r\n (0x0D 0x0A) is coming from - it's not in the hexdump.

However, the fact that the UTF-8 sequence 0xC2 0xA0 (non-breakable space) was included is definitely an issue. The sequence does not exist in ASCII so is omitted by the rcube_charset::convert() call:

```
00000000  2d 2d 2d 2d 2d 42 45 47  49 4e 20 50 47 50 20 4d  |-----BEGIN PGP M|
00000010  45 53 53 41 47 45 2d 2d  2d 2d 2d 0a 43 68 61 72  |ESSAGE-----.Char|
00000020  73 65 74 3a 20 75 74 66  2d 38 0a 56 65 72 73 69  |set: utf-8.Versi|
00000030  6f 6e 3a 20 47 6e 75 50  47 20 76 32 0a 0a 68 51  |on: GnuPG v2..hQ|
00000040  51 4f 41 2b 6f 57 79 49  5a 76 4b 4d 6b 73 45 41  |QOA+oWyIZvKMksEA|
...
```

The problem really is that we're passing in UTF-8 data into GPG which doesn't expect that. My understanding from skimming the spec is that only 7-bit data should be passed in. Right?

To answer your question:
```
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101
 Thunderbird/52.3.0
```

**Comment by alecpl** [comment]
Fixed.

**Comment by osenft** [comment]
Thank you, I appreciate the quick turnaround!
