### ISSUE TITLE
When I close my browser tab round-cube email session is not expired!!

### ISSUE THREAD

**Issue by asradmin** [roundcube/roundcubemail#5963]
When I close my browser tab and open my round-cube email page again it opens without any authentication! What I must  do to authenticate again when closing a tab and opening my email page again?

**Comment by alecpl** [comment]
Use logout button.

**Comment by asradmin** [comment]
I know what logging out done...!! but when a user forget to do logout and close his browser tab in the public area, it makes a security hole...
Most mail clients have an issue to expire the session when browser tab is closed...
What option in the round-cube's setting file make it possible (...inc.php)?

**Comment by alecpl** [comment]
It is not possible, you can only set the time for how long the session is valid, session_lifetime option.
