### ISSUE TITLE
Spellcheck crashes on special chars

### ISSUE THREAD

**Issue by maureenf** [roundcube/roundcubemail#5967]
We are facing a problem that sometimes it's a little bit difficult to be reproduced.
Sometimes an error occurs and sometimes not.
We are using spell checker (pspell) and when trying to send an email with some specific special chars like º or ª, it crashes and we are unable to send emails. We realize that this error occurs on pspell_suggest() function from pspell's library. In the is_exception() function there is no condition that can handle those special chars.
How about including those specials chars at is_exception(), at rcube_spellchecker.php file?
Here is the [pull request](https://github.com/roundcube/roundcubemail/pull/5966) link.

PHP Version - 5.6.30
Mail server - Imap 
FastCGI
pspell

Log:

![error_send_email3](https://user-images.githubusercontent.com/32273503/30822054-ec4d0998-a1fd-11e7-8e9b-19009460eef2.png)

**Comment by alecpl** [comment]
Maybe you should switch to using enchant. Works for me with enchant. I don't like the proposed solution.

**Comment by alecpl** [comment]
Wontfix.
