### ISSUE TITLE
Release1.3.1 attachmet not working

### ISSUE THREAD

**Issue by andreacappelli** [roundcube/roundcubemail#5968]
Hi,
I just upgraded from 1.2.5 to 1.3.1 and noticed 2 errors

1) In all pages I see the uploadform in the top left corner (see attached image), I think It should be hidden
![home](https://user-images.githubusercontent.com/1110403/30834734-cb40fbd6-a254-11e7-99c4-c179d03a579a.png)

2) When composing a new e-mail attachments didn't work

Any hints?

**Comment by alecpl** [comment]
How about a page refresh? Looks like a caching issue.

**Comment by andreacappelli** [comment]
Hi @alecpl this happens also with empty cache and lso if I do a fresh install (not upgrade)

I worked around it putting

#uploadform {
        display: none;
}

**Comment by alecpl** [comment]
The `#uploadform` element has no style and it has only one child `form.smart-upload` with style:
```
    visibility: hidden;
    width: 1px;
    height: 1px;
    opacity: 0;
```
So, I see no reason why it would be visible. Could you check the style of that form element? Also, check browser console for errors, please.

**Comment by alecpl** [comment]
What browser?

**Comment by andreacappelli** [comment]
Firefox 55.0.2 on Linux, but also other friend with Windows 10 using

Version 61.0.3163.79 (Official Build) (64-bit)(Chrome)
FF  55.0.3 (64-bit)

Also upload button didn't work for me, the only working are is the "arrow" on right bottom with drag and drop

**Comment by andreacappelli** [comment]
Hi @alecpl I noticed that I'm missing this file
program/js/tinymce/roundcube/browser.css

the whole directory roundcube is missing

**Comment by alecpl** [comment]
That is now program/resources/tinymce directory. I think your upgrade was broken somehow. Looks like it contains files from 1.2.

**Comment by andreacappelli** [comment]
@alecpl can you give me a hint for checking the upgrade? I fixed the missing css but this didn't resolve the issue so maybe I have other problems

I run the utility bin/installto.sh in a 1.2.5 working setup

**Comment by andreacappelli** [comment]
@alecpl I just redo a fresh setup with no upgrade and seems ok, so maybe there is something broken in the installto.sh script

Thank you

**Comment by scitor** [comment]
still broken in [1.3.2](https://github.com/roundcube/roundcubemail/releases/download/1.3.2/roundcubemail-1.3.2-complete.tar.gz)
