### ISSUE TITLE
Different content not showing up (e.g. content of mail folder, about popup, ...) starting in 1.3.0

### ISSUE THREAD

**Issue by justinotherguy** [roundcube/roundcubemail#5972]
Hi there,

my favorite web mailer for years - thank you guys - great job!

Starting with 1.3.0 I experience the following:
- I log into rc
a)
- I can see the folder on my map server
- clicking on one of the folders (no matter which one - same behavior for all) I see an empty folder - no mail
(up to 1.2.6: the list of mails in the folder shows)
- it's the same with 1.3.1 (and 1.3-beta)

b)
- I can see the "about" button on the top left
- clicking on it, nothing happens - the popup with the version etc. is not showing
(up to 1.2.6: the popup shows)

c)
- I click on "settings" -> "Preferences" -> "User interface"
-> nothing happens - the settings for the user interface are not showing up
(up to 1.2.6: the content shows)

My setup:
- Debian stretch
- apache2.4.25
- php7.0.19
- running imaps against dovecot 2.2.27
- theme Larry (same with "Classic" - except for the "about" button not being present)
- language German (same with "English US")
- FF 55.0.3 (same in Safari 11.0)
To test I do this:
- I have cloned the repo from github
- to switch between version I do
  ``` git checkout <Version> ``` in the roundcube dir, e.g. ``` git checkout 1.3.0 ``` or ``` git checkout 1.2.6 ```
  ``` apachectl restart ```
  reload the page in the browser
  delete the cache in the browser

Any more details or tests that could help?

Thx!

Regards, J.

**Comment by alecpl** [comment]
If you use git version you have to install javascript dependencies. Run `bin/install-jsdeps.sh`.

**Comment by justinotherguy** [comment]
excellent - that helped! :)
Thanks for the quick response!

Regards, J.
