### ISSUE TITLE
Classic skin - no editor

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#5975]
The e-mail editor does not initiate when Classic skin is used so users can't write messages. HTML/text does not matter. Right below 'Subject' field the 'Attachments' form appears, but there is no e-mail editor form. Sometimes, after Ctrl+F5 i can see this message:

"Failed to load plugin: code from url https://xxxx.xxxx.com/program/js/tinymce/plugins/code/plugin.min.js"
But the script exists in this location. There is absolutely no problem with "larry" skin.

Tested on 2 different mail servers with different PHP versions (5.4.16, 7.1.8). Roundcube version: 1.3.1.

**Comment by alecpl** [comment]
Check the browser console for errors.

**Comment by Skygge666** [comment]
Oh yes.
"NetworkError: 404 Not Found - https://xxxx.xxxx.com/plugins/tasklist/skins/classic/tasklist.css"
tasklist.css
TypeError: a.indexOf is not a function

So "tasklist" disables mail editing in Classic skin. I knew, that "tasklist" doesn't work with this skin, but I didn't know, that core functions are affected by this.
