### ISSUE TITLE
[1.3.1] Reply message and cursor position

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#5976]
On "Reply all" - the cursor goes to the "Cc" field.
On "Reply" - the cursor is gone and no field is focused.

In both cases the cursor should go to the message editor.

Roundcube 1.3.1, skin: "larry".
Config:
$config['reply_mode'] = 1;

**Comment by alecpl** [comment]
Sounds like a duplicate of #5969.
