### ISSUE TITLE
[1.3.1] Auto-refresh not working

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#5977]
Auto-refresh doesn't work. I have to refresh Roundcube manually to get new mails.  :(

defaults: $config['refresh_interval'] = 60;
my personal config: 60s.

Tested on 2 servers, 2 PHP versions. Cyrus IMAP.
Previously installed v0.8.4 worked like a charm, the problem appeared after update to 1.3.1.

**Comment by alecpl** [comment]
Did you try with disabled all plugins? Works for me. Provide your config.

**Comment by Skygge666** [comment]
Without plugins auto-refresh works. The plugin that disables auto-refresh is "Contextmenu".

**Comment by Skygge666** [comment]
One note for those who may encounter this problem too: there are at least 2 versions of "contextmenu" plugin: first maintained bu JohnDoh, second by Rene Schuster. The problem is witch Rene Schuster's fork. Version developed by JohnDoh works OK.

**Comment by andrewhearn** [comment]
Further hep for other readers - I had this problem recently on stock Debian 10 Roundcube (v1.3.8) - I was running an older version of JohnDoh's contextmenu. I upgraded contextmenu to v2.2, and the inbox now refreshed again.

**Comment by rokj** [comment]
How does one disables auto-refresh for particular plugin. 

I would like to this for password plugin.

I tried adding `$this->rc->output->set_env('refresh_interval', 0);` to init method, but does not seem to work?
