### ISSUE TITLE
Sessions aren't multi-stack aware

### ISSUE THREAD

**Issue by r3pek** [roundcube/roundcubemail#5978]
My Internet connection is multistack (IPv4 and IPv6) and so is my server.

This problem occurs when you login with one IP (v4 for example), and during the session, you ocasionaly change to IPv6 (or vice versa). This of course forces a refresh but that isn't what the user wanted.

Access log example:
```
2001:818::xxxx - - [04/Oct/2017:19:39:52 +0100] "POST /?_task=mail&_action=refresh HTTP/1.1" 200 717 "https://mail.example.com/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
46.189.xxx.xxx - - [04/Oct/2017:19:40:52 +0100] "POST /?_task=mail&_action=refresh HTTP/1.1" 200 754 "https://mail.example.com/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
46.189.xxx.xxx - - [04/Oct/2017:19:40:54 +0100] "GET /?_task=mail&_err=session HTTP/1.1" 200 2268 "https://mail.example.com/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (X11; Linux x86_64; rv:55.0) Gecko/20100101 Firefox/55.0"
```

**Comment by alecpl** [comment]
How do you think we could workaround that?

**Comment by alecpl** [comment]
Please, note that 
```
// check client IP in session authorization
$config['ip_check'] = false;
```
is the default. So, if you don't want to check the client IP address just disable the option. I don't see how we could workaround that without disabling the check.
