### ISSUE TITLE
[1.3.1] Session does not expire

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#5979]
Session does not expire. Users stay logged in.
$config['session_lifetime'] = 10;
On one server (php 7.1.8):
$config['session_storage'] = 'db';
On second (php 5.4.16):
$config['session_storage'] = 'php';

I was away from the computer with Roundcube opened for 2 hours and I was not logged out.

**Comment by Skygge666** [comment]
I have old plugin "idle_timeout", I was using it in the old version. I modified it a little to run it with 1.3.1 and it almost works, but when it logged me out I got error message referencing to CSRF.

I switch back to 0.8.

**Comment by alecpl** [comment]
If the connection is active it's keeped alive, you have to close the browser.

**Comment by Skygge666** [comment]
I reworked this old "idle_timeout" plugin to run with the new version of Roundcube and now it works perfectly.

**Comment by wesleyhuang** [comment]
> I reworked this old "idle_timeout" plugin to run with the new version of Roundcube and now it works perfectly.

Hi Skygge666. Are you willing to share your modifications on the idle_timeout plugin?

**Comment by Skygge666** [comment]
Hi, very gladly but I don't know Github. If you find it useful or interesting, please share it or whatever.
Link: https://www.skygge.com/temp/idle_timeout.tar.bz2

**Comment by wesleyhuang** [comment]
> Hi, very gladly but I don't know Github. If you find it useful or interesting, please share it or whatever.
> Link: https://www.skygge.com/temp/idle_timeout.tar.bz2

Great, Thanks!
