### ISSUE TITLE
Incorrect email date received from thunderbird 

### ISSUE THREAD

**Issue by GNUUU** [roundcube/roundcubemail#5981]
hello everyone :)

There is a behavior that I do not understand in Roundcube, it is when I send an email using Thunderbird with an incoherent system date (Wrong date )  the receiver receives this email in its webmail (Roundcube) with an incorrect date.you can test it.
I want to know if there is a solution for this problem :(
normal behavior i receive the email with a correct date according to the preferences I have configured on my Roundcube account (Time Zone).
With gmail or hotmail I get the email with correct date even if the sender with Thunderbird has an incorrect system date.
To understand well the problem you can change the date of your system with an incorrect date and send an email with thunderbird to your mailbox roundcube you will see an incorrect date of the email in roundcube interface.

**Comment by alecpl** [comment]
Someone invented Date header in email. So, we display it as is. If you change the sorting column of messages list you'll see the Received date on the list. Still the date from the Date header will be used in mail preview. I think it's ok.

**Comment by GNUUU** [comment]
Hello and thank you for your answer,

but in the Roundcube webmail there is no such Received Date there are Arrival date and sent Date and both the same, display the same date wrong date!

the  normal behavior i receive the email with a correct date according to the preferences I have configured on my Roundcube account (Time Zone).

roundcoube display date email according to the value Date  at the header of the email ! and the date may be set wrong !

I hope that you understand me :)


________________________________
De : Aleksander Machniak <notifications@github.com>
Envoyé : jeudi 5 octobre 2017 10:38
À : roundcube/roundcubemail
Cc : Gnu_Gnu; Author
Objet : Re: [roundcube/roundcubemail] Incorrect email date received from thunderbird (#5981)


Someone invented Date header in email. So, we display it as is. If you change the sorting column of messages list you'll see the Received date on the list. Still the date from the Date header will be used in mail preview. I think it's ok.

**Comment by alecpl** [comment]
Sorry, I meant Arrival not Received. What version are you using?

**Comment by GNUUU** [comment]
i'm using the version 1.0.9 Roundcube


________________________________
De : Aleksander Machniak <notifications@github.com>
Envoyé : jeudi 5 octobre 2017 10:56
À : roundcube/roundcubemail
Cc : Gnu_Gnu; Author
Objet : Re: [roundcube/roundcubemail] Incorrect email date received from thunderbird (#5981)


Sorry, I meant Arrival not Received. What version are you using?

**Comment by alecpl** [comment]
Then you should upgrade.

**Comment by GNUUU** [comment]
ok thanks i will test with the last version :)
