### ISSUE TITLE
COPYUID response can be untagged

### ISSUE THREAD

**Issue by gyurco** [roundcube/roundcubemail#5982]
According to RFC6851, COPYUID can be in an untagged response. However rcube_imap_generic.php
parseResult() only parses tagged responses. This is a problem with Cyrus-imapd 3.0.x and Kolab.

Example:
````
       C: a UID MOVE 42:69 foo
       S: * OK [COPYUID 432432 42:69 1202:1229]
       S: * 22 EXPUNGE
       S: (more expunges)
       S: a OK Done
````
This COPYUID is not caught by Roundcube, so data['COPYUID'] won't filled in.

**Comment by alecpl** [comment]
Fixed.

**Comment by gyurco** [comment]
Thanks!

**Comment by gyurco** [comment]
For some reason, the fix doesn't work. However, omitting the substr_compare($line, '* OK', 0, 4, true) makes it work. I didn't find the reason, had to fix quickly a production system, but this check is also redundant, since the next preg_match also checks for '* OK'.

**Comment by alecpl** [comment]
Damn. It should be `substr_compare($line, '* OK', 0, 4, true)) === 0`.

**Comment by alecpl** [comment]
Fixed by removing the substr_compare(), it's indeed redundant.

**Comment by gyurco** [comment]
Yepp, C-style strcmp :) Thanks for fixing again!
