### ISSUE TITLE
Mail headers not generated correctly (MIME_HEADER_CTYPE_ONLY)

### ISSUE THREAD

**Issue by breogan-s** [roundcube/roundcubemail#5984]
Hello,

I am using **roundcube webmail 1.3.1.**

I have tested a mail delivery to mail-tester.com and I am getting **-1.9 points in spamassassin** complaining that the headers have not been generated correctly. This is the error:

> -1.996 | MIME_HEADER_CTYPE_ONLY | 'Content-Type' found without required MIME headers

And further information can be found here:

> https://wiki.apache.org/spamassassin/Rules/MIME_HEADER_CTYPE_ONLY

I hope you can have a look at the issue.

Thank you.

**Comment by alecpl** [comment]
It adds MIME-Version header always. So, it works for me. Enable smtp_debug in Roundcube to see what exactly is being send. Maybe it's your SMTP server. Disable all plugins. Provide steps to reproduce, provide message headers.

**Comment by breogan-s** [comment]
Hello,

Thank you for your reply. I did some testing and it looks like it was an issue on my side.

Sorry about that.
