### ISSUE TITLE
Filters error

### ISSUE THREAD

**Issue by teoberi** [roundcube/roundcubemail#5985]
PHP 7.1.10
Roundcube 1.3.1
Plugin: Filters 2.1.6
I'm trying to add a new rule, I fill in all the fields but when saving appears "The field 'Contains' cannot be empty".
In maillog I have:
Oct  9 14:16:22 <servename> roundcube: PHP Warning:  A non-numeric value encountered in /var/www/htdocs/roundcube/program/lib/Roundcube/rcube_utils.php on line 270
Oct  9 14:16:22 <servename> roundcube: PHP Warning:  A non-numeric value encountered in /var/www/htdocs/roundcube/program/lib/Roundcube/rcube_utils.php on line 274
Oct  9 14:16:22 <servename> roundcube: PHP Warning:  A non-numeric value encountered in /var/www/htdocs/roundcube/program/lib/Roundcube/rcube_utils.php on line 278

**Comment by alecpl** [comment]
We do not support this plugin.
