### ISSUE TITLE
Smtp> force sender in mail header

### ISSUE THREAD

**Issue by h2lsoft** [roundcube/roundcubemail#5987]
Hi,

when I send a mail Sender header is different from sender origin,
how can I force mail's sender header ?

php has a 4 parameters to force expeditor with -f, where can I change roundcube mail parameters ?

Thanks

**Comment by alecpl** [comment]
Roundcube does not set the Sender header. Since version 1.3 we do not support PHP mail() function. We depend on smtp_* options in config file (e.g. smtp_user).

**Comment by MarcProe** [comment]
@h2lsoft have a look at this plugin, maybe it does what you want: 
https://github.com/MarcProe/roundcube-send-on-behalf-of

**Comment by h2lsoft** [comment]
Thank you my roundcube version is Roundcube Webmail 1.1-git used in Kolab Groupware
