### ISSUE TITLE
Still no cursor in HTML mode reply

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#5990]
Hello!
Because #5969 is closed, I have to open new issue.
#5969 fix does not resolve completely this bug. Is better, but not perfect.

Click on email, give "Reply" (in HTML mode). The cursor is missing. Start typing. The cursor appears in the editor after first letter and the first letter is gone.

Tried with current master with no plugins.

**Comment by alecpl** [comment]
Works for me on current master. Chrome and Firefox.

**Comment by alecpl** [comment]
Would you mind providing some information about browsers you checked, list of used plugins, etc.?

**Comment by Skygge666** [comment]
Oh yes. Sorry I forgot a little about this (lot of work) ;)
All plugins disabled, browser: recent Firefox under Kubuntu.
Pozdrawiam!

**Comment by Skygge666** [comment]
Checked in 1.3.4 and it works OK. Closing this issue. Pzdr/Regards!
