### ISSUE TITLE
httpd dies sometimes

### ISSUE THREAD

**Issue by samjaninf** [roundcube/roundcubemail#5992]
Not sure if I should post this here or elsewhere. But every now and then httpd seems to just die leaving a trace in the logs.

I have included the trace: 

https://gist.githubusercontent.com/samjaninf/0e3435934e0312e6ff2645b9859a81e7/raw/2f028aee951b9e40914ecd29d093e6fb38997fc8/httpd_trace_log

It shows *** Error in `/usr/sbin/httpd': free(): invalid pointer: 0x00005640ab4b4a90 ***
at the start of the trace.

**Comment by alecpl** [comment]
If this happens with Roundcube then it will be a PHP (or some library it uses) bug. We can do nothing about it.

**Comment by samjaninf** [comment]
Only reason I brought it up here was because it does load through several of the kolab components.
But I did also look through some php and apache bugs and it seems like it might be an apc issue. Might try it with php 71 though if that's compatible.

Thanks anyways!
