### ISSUE TITLE
"List" / "Threads" view different behaviour in delete messages

### ISSUE THREAD

**Issue by nikita65** [roundcube/roundcubemail#5995]
Hello developers,
I've set the option "view next message after deleting/moving" one.

This works for both view but there is an issue with the Trash button (or keyboard DELETE):

. in "List" view mode after deleting a message, next one is shown ok but - I think - not actually selected and therefore I cannot delete/trash it without re-selecting it by hand, also "Trash/Delete" button is greyed out - see images:

![can-delete-first](https://user-images.githubusercontent.com/6203977/31498152-87e822e6-af61-11e7-9a41-45e684116bb8.jpg)

![cannot-delete-second](https://user-images.githubusercontent.com/6203977/31498168-953cb7e0-af61-11e7-9743-a3db05933580.jpg)

. in "Threads" view mode delete one-by-one works fine.

Am I missing something or is this an issue?

PS: RCube version 1.3.1 complete.

Thanks and best compliment for the great job you've done!

Bye nIc

**Comment by alecpl** [comment]
This is a matter of focus. The list widget have to be focused to receive Delete key event. I can confirm that after using Delete button on the toolbar the focus is not returned to the list.

**Comment by alecpl** [comment]
Hmm... However, I cannot confirm the issue with button state. So, we'd need more info. Did you try with different browser? What browser? Did you try with disabled all plugins? Did you see any errors in browser console?

**Comment by nikita65** [comment]
Tried with firefox 45.0.2 on linux and latest Chrome/Firefox on Windows. Same issue. No erros in logs.

Had some plugins ('archive','managesieve','squirrelmail_usercopy','password'), I disabled all of them and the issue is still there (both with Delete-icon and Delete on the keyboard) on the above browsers.

**Comment by alecpl** [comment]
How about browser console?

**Comment by nikita65** [comment]
only some css errors only in styles.min.css, mail.min.css and jquery-ui.css (larry skin). I attach it, sorry it's in italian ... the rest is ok.
[css-console.txt](https://github.com/roundcube/roundcubemail/files/1379634/css-console.txt)

**Comment by alecpl** [comment]
Did you by any chance tracked this down? I'm still unable to reproduce. Maybe upgrade to 1.3.2?

**Comment by nikita65** [comment]
Hi there,
didn't do any other tests.

But, just now I tried on Firefox 56.0.2 on OSX and it works better but not completely:

I can "keyboard-Delete" several messages but after some 4/5/6/7 deletes still the Delete-icon gets grayed out. This happens in "Inbox" wether in "Trash" it never happened.

When working on "Inbox" I saw several errors "Killed (lost mailbox lock)" but not always with greyed out button, it happened only once when working on "Trash".

The same happens on "Safari", may that be a problem with imapd (using cyrus)?

Bye nIc

**Comment by alecpl** [comment]
The error message comes from the IMAP server, so the root cause will be there, I guess. There might be also an issue in error handling on our side or some race condition. There was similar issue recently and I modified some code. I propose you to try most recent version. You should upgrade anyway because of a serious security issue fixed in  1.3.3.

**Comment by alecpl** [comment]
Not reproduceable.
