### ISSUE TITLE
Popup: Unable to close

### ISSUE THREAD

**Issue by uli-heller** [roundcube/roundcubemail#5997]
I'm using roundcube-1.3.1.

When looking at a mail having lots of receivers, there is a link named "3 weitere ..." ("3 more...").
Clicking on the link opens a popup window. Unfortunately, there is no obvious way to close the
popup.

![image](https://user-images.githubusercontent.com/1677414/31595936-48efde86-b23f-11e7-8605-568996c6ecf1.png)

**Comment by alecpl** [comment]
Esc key should work. Also, for me there's a Close button in right-upper corner of the dialog.

Is there any error in browser console? Did you try with disabled all plugins? What browser/version?

**Comment by uli-heller** [comment]
I'm using chrome on Linux:
Version 61.0.3163.79 (Offizieller Build) (64-Bit)

I tried again and this time, there is a Close button
and no output in the console. I used exactly the same
mail message than before. Strange...

**Comment by alecpl** [comment]
Maybe some caching/connection issue. I'm closing this ticket.
