### ISSUE TITLE
Add more options in address book add field dropdown

### ISSUE THREAD

**Issue by mgsf08m002** [roundcube/roundcubemail#6001]
I want to add more options in add filed drop down at edit contact address.

Please help.
![28871655-7e3f800c-777d-11e7-91d7-4cc10936b152](https://user-images.githubusercontent.com/5829136/31729231-dfe256a2-b447-11e7-9b23-bda432662feb.png)

**Comment by alecpl** [comment]
This is not so simple and requires changes in many places. You need e.g. to extend vCard handling code to store the new property in it.

**Comment by mgsf08m002** [comment]
can you please provide more information about this. which files i have to review other then vCard handling.
