### ISSUE TITLE
Session destroyed after short time for one user only

### ISSUE THREAD

**Issue by andreasspeck** [roundcube/roundcubemail#6003]
We are using Roundcube-1.2.x, and have been facing a session problem with one user (or domain) only. 
In the logs I can see: PHP Warning:  session_start(): Failed to decode session object. Session has been destroyed in /var/www/clients/client1/web88/web/program/lib/Roundcube/rcube_session.php on line 129

When I login as this user, I get to see the inbox, and I can even click on one mail in this inbox. Clicking on any other folder or returning to the inbox after reading the one mail gets me a:

**Your session is invalid or has expired.**

Session storage is in MySQL (5.5.53-0+deb8u1 - Debian Jessie)

We have not had any other user reporting the issue, and this user has no problems connecting via Thunderbird.

**Comment by andreasspeck** [comment]
We have now also installed Rainloop to provide the user with an alternative. We don't have the session issue in Rainloop, but we do see when going to Settings->Folders in Rainloop:

"You have too many folders!
We have shown only a part of them, to avoid performance problems."

Could the number of imap folders cause the session issue in Roundcube?

**Comment by alecpl** [comment]
Maybe the column size is too small. In that case the stored session data string would be truncated. We use mediumtext for sessions.vars column. You could try longtext.

How many folders?

**Comment by andreasspeck** [comment]
I try the longtext next.
The user has more than 1200 folders incl subfolders (that's the number of lines in Dovecot's subscription file).

**Comment by alecpl** [comment]
See if disabling "Check all folders for new messages" in Preferences > Mailbox View > New message will help. To change this from UI user would need to point the browser to `&_task=settings` first.

**Comment by andreasspeck** [comment]
Our session.vars column was still on TEXT, chaning this to MEDIUMTEXT seems to already have solved the issue - at least I can now go into different folders without being thrown out.

**Comment by alecpl** [comment]
Strange. It was mediumtext since 0.3.1.
