### ISSUE TITLE
BUG: Full path to email in global search results

### ISSUE THREAD

**Issue by nixprosoft** [roundcube/roundcubemail#6004]
RC cutting of path names & not showing full path even in title hint.
![2017-10-19_15-40-32](https://user-images.githubusercontent.com/5313478/31771236-02e528e0-b4e4-11e7-8746-f79d6cc79cac.png)

**Comment by alecpl** [comment]
What version?

**Comment by alecpl** [comment]
And what browser? Works for me.

**Comment by alecpl** [comment]
Sorry, I was too fast. I can reproduce now.

**Comment by alecpl** [comment]
Fixed.
