### ISSUE TITLE
No impact when changing imap_delimiter in defaults config

### ISSUE THREAD

**Issue by binarykitchen** [roundcube/roundcubemail#6012]
Because I am unable to set parent folders (see error in screenshot) ...

<img width="507" alt="screen shot 2017-10-24 at 12 07 32" src="https://user-images.githubusercontent.com/177641/31917432-15c4735c-b8b4-11e7-833a-7b5122c36c36.png">

... I tried to make it work by changing the `imap_delimiter` to `.` in defaults.inc.php but that didn't help. Any clues what's missing?

Using the latest version from your master branch here.

**Comment by alecpl** [comment]
You should not modify defaults.inc.php, use config.inc.php. Also, in this case you have to re-login.

**Comment by binarykitchen** [comment]
reverted - and yes, re-login helped. solved!
