### ISSUE TITLE
In IE11, LDAP Address browser in compose window breaks

### ISSUE THREAD

**Issue by travisburnside** [roundcube/roundcubemail#6014]
When composing a message, a list of LDAP address books appears on the left.  Clicking on the address book correctly lists member addresses on other browsers, but fails with a JavaScript error on IE 11.  This happens on RC 1.2.5 and 1.3.0.

Any ideas?  Thanks.

![screen shot 2017-10-25 at 9 06 43 am](https://user-images.githubusercontent.com/5873742/32009405-dc18f51e-b963-11e7-8ebd-07760a0e4856.png)
![image 1](https://user-images.githubusercontent.com/5873742/32009413-e172fa78-b963-11e7-9f42-c1dee8209738.png)
![image](https://user-images.githubusercontent.com/5873742/32009417-e57b6b82-b963-11e7-86b6-3c859e04141e.png)

**Comment by alecpl** [comment]
What plugins are you using? Try with disabled all plugins. Try to delete app.min.js file, then it should show more precise error (line of code). Try 1.3.1.

**Comment by travisburnside** [comment]
The two versions are using the following plugins, respectively.

<img width="564" alt="screen shot 2017-10-25 at 9 31 31 am" src="https://user-images.githubusercontent.com/5873742/32015979-8500a182-b977-11e7-8693-97e738f6a5be.png">
![screen shot 2017-10-25 at 9 30 51 am](https://user-images.githubusercontent.com/5873742/32015981-86a6e6a4-b977-11e7-845b-a54f797e3337.png)

I tried disabling all plugins on the 1.3.0 version, and the error persists.  I removed the minified JS file, and here's the error with updated line numbers:

![image](https://user-images.githubusercontent.com/5873742/32016012-9eff5d4e-b977-11e7-8f73-237760364cb3.png)

This time I left the developer console on upon opening the compose window, and noticed an error loading jquery:

![image 1](https://user-images.githubusercontent.com/5873742/32016062-c50ad8c4-b977-11e7-8783-d7f41f225de5.png)

Based on that error, I added our webmail site to the Trusted Zones in IE11, and it's working now.  I don't know if there's anything you can do from a development side for this, but it's an acceptable workaround for us.  Thanks.

**Comment by alecpl** [comment]
Indeed, there's probably nothing we can do and you're first with such an issue. So, it's rare.
