### ISSUE TITLE
Installation on Composer Fails?

### ISSUE THREAD

**Issue by peternemser** [roundcube/roundcubemail#6015]
I am trying to install jqueryui on roundcube via Composer and get the following error

   _- The requested package roundcube/jqueryui could not be found in any version , there may be a typo in the package name._
  
In composer.json for the require I am using 

  "roundcube/jqueryui": "~1.12.0",

Any ideas on what is wrong?

**Comment by alecpl** [comment]
This is a core (and required) plugin, there's no need to install it.
