### ISSUE TITLE
Emails goes to SPAM folder for no reason

### ISSUE THREAD

**Issue by waltercs** [roundcube/roundcubemail#6017]
Hello everyone,

I have a problem with roundcube where the message from just one email (specific writer), all messages send goes to the SPAM folder, everytime. The message stay 3 seconds on the Inbox and for no reason go to a SPAM folder.

I have SpamAssassin but for this case I shut down the entire antispam system and this messages continuous drop on SPAM.

I'm work in a Hosting Company and we have 2 cases of that.

**Comment by waltercs** [comment]
Hello everyone,

I have a problem with roundcube where the message from just one email (specific writer), all messages send goes to the SPAM folder, everytime. The message stay 3 seconds on the Inbox and for no reason go to a SPAM folder.

I have SpamAssassin but for this case I shut down the entire antispam system and this messages continuous drop on SPAM.

I'm work in a Hosting Company and we have 2 cases of that.

**Comment by alecpl** [comment]
Roundcube does not move messages by itself. I guess you're using some filtering plugin.

**Comment by waltercs** [comment]
Thanks for your reply alecpl.

So, I turn off everything what should possible move the message (plugins, filters), is like if one configurations bug out and mark this adress with "bad" and move all the messages. 

I don't have any clue about whats is going on, so if anyone have any idea for help us, I thankfully your help.

Thanks!
