### ISSUE TITLE
Mailto: links containig "+" sign do not work correctly in html messages

### ISSUE THREAD

**Issue by netesa** [roundcube/roundcubemail#6020]
Please look at the attached test message: [test.zip](https://github.com/roundcube/roundcubemail/files/1433078/test.zip)

It containes the followning link `mailto:addr+ext@example.com`, however Roundcube renders it as `mailto:ext@example.com`. It's a html message, in case of a plain text message everything works correctly.

**Comment by alecpl** [comment]
Fixed.
