### ISSUE TITLE
managesieve: new settings dialog for simple forwarding of emails

### ISSUE THREAD

**Issue by tpokorra** [roundcube/roundcubemail#6021]
I have created a settings dialog very similar to the vacation settings.

In this forwarding dialog you can set very simple forwarding, only `redirect to` or `send copy to`, and setting the status to `on` or `off`.

I needed to do this for a customer who often uses forwarding and says that the filters are too powerful for them to configure.

I will create a push request for this, perhaps it is useful for other users too. It can be enabled/disabled in the `managesieve.inc.php`, similar to vacation.

**Comment by alecpl** [comment]
Your changeset removes too much in managesieve.html. Other than that I think we could consider merging this feature. Please, create a PR.

**Comment by tpokorra** [comment]
yes the first commit was wrong, I used an old version of managesieve.html. I have created a clean pull request.

Thanks for thinking about merging. If you have any questions or concerns or need changes, let me know!
