### ISSUE TITLE
Roundcube not sending emails

### ISSUE THREAD

**Issue by Tiffaani23** [roundcube/roundcubemail#6023]
Since Thursday, I have been unable to send emails to Outlook address from my  Roundcube email. I've spoken to Outlook and they said this is an issues with Roundcube. Now today I'm hardly receiving emails and the ones I try to send are not being received. please can some one help!?

**Comment by alecpl** [comment]
Roundcube is an email client software installed by someone for you. We can't help you. Ask your mail server admin/provider.

**Comment by Woo71** [comment]
Tiffaani23,
Did you manage to resolve this in the end as we are having the same issue and not really getting any resolution.  Many thanks!  W

**Comment by Tiffaani23** [comment]
It seem to fixed itself for a few days but has started to happen again today! It might be possible Outlook has put a limit to how many emails you can send to their addresses for some reason, I'm still waiting for a reply about this from Outlook.. 
But not had much luck trying to resolve the issue!

**Comment by Woo71** [comment]
This is what is happening to us, and we aren't sending that may emails out.
If I have any luck, I'll let you know.

**Comment by Tiffaani23** [comment]
I'm not sending any out either, which is strange because it was working completely fine up until last week!
That would be brilliant, thank you and likewise if I do.
