### ISSUE TITLE
Apostrophe encoding character problem

### ISSUE THREAD

**Issue by AndreaMonzini** [roundcube/roundcubemail#6024]
Hello, in the last few days when i send messages with apostrophe, the sent messages have wrong encoded character:

instead of` " ' "` i see `" \' "`

it happen with plain text or HTML.
Previously i did not have the problem.

Roundcube Webmail 1.3.2

**Comment by alecpl** [comment]
Please, provide a sample message and/or precise steps to reproduce.

**Comment by AndreaMonzini** [comment]
Thank you for the answer, here the message sent

MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII;
    format=flowed
Content-Transfer-Encoding: 7bit
Date: Sun, 05 Nov 2017 16:49:31 +0100
From: Andrea Monzini <primary email>
MIME-Version: 1.0
Content-Type: text/plain; charset=US-ASCII;
    format=flowed
Content-Transfer-Encoding: 7bit
Date: Sun, 05 Nov 2017 16:49:31 +0100
From: Andrea Monzini <primary email>
To: Monzini Andrea <secondary email>
Subject: Test
Return-Receipt-To: Andrea Monzini <primary email>
Disposition-Notification-To: Andrea Monzini <primary emai>
Message-ID: <37dbefb247523c34f8d62b80b4d98d0e@primary emai>
X-Sender: primary emai
User-Agent: Roundcube Webmail/1.3.2

Message Body
Hello,  i\'m Andrea and i don\'t see correct encoded characters ;)

**Comment by alecpl** [comment]
Works for me. What PHP version and OS? Did you try with disabled all plugins? Enable smtp_debug to log the mail sent from Roundcube and make sure it's Roundcube's fault or not. Maybe that's something on the SMTP server/transport.

**Comment by AndreaMonzini** [comment]
Thank you for the support, i will contact the server manager.
