### ISSUE TITLE
Roundcube mangles non-ASCII characters in HTML links when displaying messages

### ISSUE THREAD

**Issue by svetlozaraleksiev** [roundcube/roundcubemail#6028]
When displaying HTML links in e-mail messages Roundcube incorrectly mangles any non-ASCII characters. Specifically, in our case, we have URLs with cyrillic alphabet paths.

For example,
http://www.example.com/somepath/ = works ok
http://www.example.com/някакъвпът/ = is mangled

<img width="827" alt="screenshot" src="https://user-images.githubusercontent.com/16590673/32544870-802d932a-c482-11e7-9743-e428c4ba03ca.png">

We've seen this issue on Roundcube 1.3.1 and 1.3.2.

The messages are using UTF8 encoding. We tested this with quoted-printable and base64 encoding, and the issue is the same.

Here's a complete sample message:

[Test.txt](https://github.com/roundcube/roundcubemail/files/1453520/Test.txt)

**Comment by alecpl** [comment]
Confirmed. Problem in html::parse_attrib_string().

**Comment by alecpl** [comment]
Fixed.
