### ISSUE TITLE
SMTP Error: Message size exceeds server limit

### ISSUE THREAD

**Issue by il3ctro** [roundcube/roundcubemail#6032]
Hello developers,

When i send a email via Thunderbird and the size exceeds the server limit i get following error message:
"SMTP Error: Message size exceeds server limit" which is exactly what it should do.

But would it be possible to rewrite this error message that the actual limit or by how much i exceeded is shown? 
I was thinking of something like this:
"SMTP Error: Message size exceeds server limit (52428800)"
or
"SMTP Error: Message size exceeds server limit by XXX"

Thanks in advance 
il3ctro

**Comment by rmcaninch** [comment]
That message is from the SMTP server, not Roundcube, so you would want to check the documentation for your SMTP server on how to change the message.

**Comment by alecpl** [comment]
The message is generated by Net_SMTP code, but because SMTP server returns the limit in SIZE response we can build a proper message in Roundcube. The request is valid.

**Comment by alecpl** [comment]
Implemented.
