### ISSUE TITLE
Filename to long; Attachment size doesn't show

### ISSUE THREAD

**Issue by il3ctro** [roundcube/roundcubemail#6033]
Hello developers,

When i try to send some files via email attachment and the filename is to long, it doesnt show what the actual size of the attachment is neither does it show me, what the full filename is. (gets cut off)
Example:
![dateiname](https://user-images.githubusercontent.com/33520270/32610996-adae6bfc-c564-11e7-8ca1-e4c2ba62c707.png)

Is there a possibility to implement a fix, that shows the size no matter how long the filename is?

Thanks in advance
il3ctro

**Comment by alecpl** [comment]
That might be tricky in old skins, but should be easy in the new skin I'm working on right now (because there we can use flexbox).

**Comment by alecpl** [comment]
Fixed.
