### ISSUE TITLE
Search box not working properly

### ISSUE THREAD

**Issue by bmilanov89** [roundcube/roundcubemail#6041]
When i search my Inbox or Sent the search box does not work properly. Sometimes it shows me e-mails sometimes it doesn`t. When try searchin with another mail provider everything is ok.

**Comment by alecpl** [comment]
That will be more likely an IMAP server issue. Maybe the request times out? The only think you can do is to check Roundcube error log or enable imap_debug and see what IMAP server says on search request.

**Comment by bmilanov89** [comment]
How do i do that ?

---
Branimir Milanov
/ Business Developer /

M: 359 897 86 15 82

BETIATRUST CORP.
www.gienterprise.com
www.hotelinvarna.com
www.studioestetico.com
www.carrentalsbulgaria.com

**Comment by alecpl** [comment]
If you don't know how to configure Roundcube or IMAP server we can't really help you here.
