### ISSUE TITLE
PDF is detected as TXT file

### ISSUE THREAD

**Issue by Thingmand** [roundcube/roundcubemail#6044]
We are seeing problems with customers on Roundcube, when sending mails from Mandrill with attached PDF files. RC sees the file as TXT and gives a warning and won't open it. 

![warning](https://user-images.githubusercontent.com/1589561/32772396-02db19e4-c926-11e7-9806-4792282de846.png)

It works flawless in other mail clients and Mandrill has tested the headers and verified everything is good from their end.

**Comment by alecpl** [comment]
Could you provide a sample message source?

**Comment by Thingmand** [comment]
EML file:
[mail.zip](https://github.com/roundcube/roundcubemail/files/1470361/mail.zip)

**Comment by alecpl** [comment]
Are you sure this is the same message? This one has application/octet-stream content type for the attachment and I'm not even able to open it. BTW, what Roundcube version do you use?

**Comment by Thingmand** [comment]
I'm not the owner of the webmail provider, I'm just trying to send to a customer who uses it.

The EML is the mail forwarded fra RC as attached file and then downloaded. It opens fine in Apple mail? How would you like the e-mail source? I can send an example of the original mail if you have a test mai?.

**Comment by Thingmand** [comment]
Can I see the version from the web interface?

**Comment by alecpl** [comment]
No, you can't. We'll probably not be able to help you if you are not the server admin. You can send the message to alec at alec.pl.
