### ISSUE TITLE
Better handling of temp_dir misconfiguration

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6045]
Recent changes to attachments plugin(s) revealed an issue related to `open_basedir`. When `open_basedir` restriction is set and configured Roundcube `temp_dir` is not allowed by `open_basedir`. `tempnam()` will fallback to system temp directory (e.g. /tmp). In such a case path verification (in attachments plugin) will fail.

A proposed solution is to allow, aside of configured `temp_dir`, the system temp directory (result of `sys_get_temp_dir()`) in `verify_path()`. Optionally we could log a warning when we see that system temp directory is in use and it's different than the configured for Roundcube.

**Comment by DavidAnderson684** [comment]
In my case, after an update, the configured temp directory was not writeable. open_basedir was not in use. I think that "can't write to the temp_dir for any reason" is the more general issue, rather than  just because of open_basedir.

**Comment by alecpl** [comment]
You're right. Done.
