### ISSUE TITLE
Installer DB schema check bug

### ISSUE THREAD

**Issue by skiner68** [roundcube/roundcubemail#6047]
Hello, 
I am trying to update from 1.2.7 to 1.3.3 nad I have found a strange situation - installer does not check db schema correctly:

Steps to reproduce:

1.  make a copy of current db used by my prod 1.2.7,  database user has rights for **both source and copy database**
2. connect my dev RC 1.2.7 installation to copy db, perform manual files update etc., run installer to check db schema, update to 1.3.3 db => no problem
3.  Ok, everything worked, now let's update my production database: create another copy of my prod1.2.7. db. Now I have 3 dbs: original 1.2.7, copy of 1.2.7 as a backup and recently upgraded 1.3.3. used for testing. My db user has rights for each of these dbs.
4.  My prod installation config is pointing to original 1.2.7. When I try to check & update db structure using installer (I mean PHP installer application in web broswer), installer do not find any differences in DB. But my prod 1.2.7. does not match 1.3.3. db schema

The problem is that my database user can read to more than one databases which contains tables with same names. 

I have gone thru application, the problematic check is in **rcube_db**, method **list_cols**. Method uses this select:

```
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'some_rc_table_name'
```

But this returns columns names of all tables of with provided  name from all databases my user has rights for. Installer then compares array of needed columns in table and present columns. using rcube_utils::db_schema_check

```
$diff    = array_diff(array_keys($cols), $db_cols);

if (!empty($diff)) {
    $errors[] = "Missing columns in table '$table': " . join(',', $diff);
}
```
array $db_cols here contains columns names from

not_updated_db.some_rc_table_name
backup_db.some_rc_table_name
already_updated_db.some_rc_table_name

and because of this, the diff condition is not met.

If I patch the select to 

```
SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'some_rc_table_name'
AND TABLE_SCHEMA = 'my_roundcube_database_name'
```
everything works as desired - $db_cols contains only columns names from my_roundcube_database_name.some_rc_table_name

I have checked installation "how to" - yes there is a sentence saying _create a database with any name you want and grant privileges to a separate database user._ But I thing it is quite ussual to create copy of database for quick recovery in case of failure. 

I think it would be useful to fetch the used database name to private property in rcube_db and then update the select asi I mentioned above. Sorry for not providing pull request with fix for this, I am not aware of the whole situation in rcube_db that good.

**Comment by alecpl** [comment]
Fixed.
