### ISSUE TITLE
Tabbed Interface

### ISSUE THREAD

**Issue by rcubetrac** [roundcube/roundcubemail#605]
_Reported by alex t king on 2 Mar 2006 22:48 UTC as Trac ticket #1442108_

I'd love to see a tabbed interface, I've got a blog
post here:

http://www.alexking.org/blog/2006/03/02/tabbed-e-mail/

and some mock-ups on Flickr:

http://www.flickr.com/photos/alexkingorg/sets/72057594073609360/

I'd be willing to talk with someone about the best way
to implement this if a patch would be considered for
inclusion.

_Keywords: Tabbed Interface_
_Migrated-From: http://trac.roundcube.net/ticket/1442108_

**Comment by filhocf** [comment]
Any update about this feature? 

I believe that is a "killer" feature. In Brazil, we have a "common" webmail called ExpressoLivre (that today is a dead project) and Zimbra are winning land with its webmail.

All, Expresso and Zimbra, beyond Yahoo, Gmail, Outlook and Tbird (email clients), use tabs.

**Comment by alecpl** [comment]
Since we have possibility to compose a message in a separate window or browser tab the priority for such a feature is not high.

**Comment by filhocf** [comment]
@alecpl, is a PoV. For final user (low profile), is easy to work with tabs, or in case of Gmail, open a float window to compose new e-mail, giving to user the possibility to see other email or thing in his interface.

Occurs with frequency of I start a new email and to forget some thing that force me to return to main page, take a look, and return to compose.

Maybe the best is to compose in a modal window. The tab was a idea in there time, that today can be outdated.

**Comment by alecpl** [comment]
I don't see it happening. Closing.
