### ISSUE TITLE
Bug writing font

### ISSUE THREAD

**Issue by Alex-fr75** [roundcube/roundcubemail#6050]
Hello, I wanted to report a bug, when we copy a text in "helvetica" on our mailbox to copy it on a new e-mail the font becomes "monospace" while it should remain in "helvetica".

**Comment by alecpl** [comment]
You're talking about HTML editor, right? I don't know it's at all possible. I think if there's a bug it's in TinyMCE. Did you try on https://www.tinymce.com/docs/demo/full-featured/ ? Provide more precise steps to reproduce.

**Comment by alecpl** [comment]
No feedback.
