### ISSUE TITLE
Allow plugins to include Less files

### ISSUE THREAD

**Issue by JohnDoh** [roundcube/roundcubemail#6051]
This is a skin specific issue (for Elastic) but I think if it can be solved at all it can only be solved in the core. The CSS for official Roundcube plugins is being done directly in the Elastic skin but external plugins do not have that luxury. Could `rcube_plugin::include_stylesheet()` be extended in some way or a new method added which would allow external plugins to load in Less files when appropriate (i.e. the skin supports them and Roundcube is in `devel_mode`)?

**Comment by alecpl** [comment]
Right. There's the new $if_exists argument. We could redefine it so, when enabled it not only checks the file existence  but also prefers file with .less extension in devel_mode. Maybe at some point we should even get rid of this argument and make it a default behavior.

It would require a small change in rcmail_output_html::_write() to add the file with proper type attribute.

**Comment by alecpl** [comment]
I'm working on it.

**Comment by alecpl** [comment]
Done in 1cf72fa2b6 and 9ce8948294.
