### ISSUE TITLE
Can't install roundcube

### ISSUE THREAD

**Issue by SanaRinomi** [roundcube/roundcubemail#6052]
I've just gotten into the world of Ubuntu servers and decided to setup a mail service. Problem is that, I can't install Roundcube, even if it's a fresh install, setup the sql server 2 times, enabled all php features and whatnot. Even so, it still doesn't allow me to install.

`| +-------------------------------------------------------------------------+ */ ini_set('error_reporting', E_ALL &~ (E_NOTICE | E_STRICT)); ini_set('display_errors', 1); define('INSTALL_PATH', realpath(dirname(__FILE__) . '/../').'/'); define('RCUBE_INSTALL_PATH', INSTALL_PATH); define('RCUBE_CONFIG_DIR', INSTALL_PATH . 'config/'); $include_path = INSTALL_PATH . 'program/lib' . PATH_SEPARATOR; $include_path .= INSTALL_PATH . 'program/include' . PATH_SEPARATOR; $include_path .= ini_get('include_path'); set_include_path($include_path); require_once 'Roundcube/bootstrap.php'; require_once 'rcube_install.php'; // deprecated aliases (to be removed) require_once 'bc.php'; -session_start(); +if (function_exists('session_start')) + session_start(); $RCI = rcube_install::get_instance(); $RCI->load_config(); if (isset($_GET['_getconfig'])) { $filename = 'config.inc.php'; if (!empty($_SESSION['config'])) { header('Content-type: text/plain'); header('Content-Disposition: attachment; filename="'.$filename.'"'); echo $_SESSION['config']; exit; } else { header('HTTP/1.0 404 Not found'); die("The requested configuration was not found. Please run the installer from the beginning."); } } if ($RCI->configured && ($RCI->getprop('enable_installer') || $_SESSION['allowinstaller']) && !empty($_GET['_mergeconfig'])) { $filename = 'config.inc.php'; header('Content-type: text/plain'); header('Content-Disposition: attachment; filename="'.$filename.'"'); $RCI->merge_config(); echo $RCI->create_config(); exit; } // go to 'check env' step if we have a local configuration if ($RCI->configured && empty($_REQUEST['_step'])) { header("Location: ./?_step=1"); exit; } ?>
Roundcube - open source webmail software
How-to Wiki
configured && !$RCI->getprop('enable_installer') && !$_SESSION['allowinstaller']) { // header("HTTP/1.0 404 Not Found"); if ($RCI->configured && $RCI->legacy_config) { echo '
Your configuration needs to be migrated!
'; echo '

We changed the configuration files structure and your installation needs to be updated accordingly.
'; echo '

Please run the bin/update.sh script from the command line or set

  $rcmail_config[\'enable_installer\'] = true;
'; echo ' in your RCUBE_CONFIG_DIR/main.inc.php to let the installer help you migrating it.

'; } else { echo '
The installer is disabled!
'; echo '

To enable it again, set $rcmail_config[\'enable_installer\'] = true; in RCUBE_CONFIG_DIR/config.inc.php
'; } echo '
'; exit; } ?>
Roundcube Webmail Installer

    './check.php', 2 => './config.php', 3 => './test.php', ); if (!in_array($RCI->step, array_keys($include_steps))) { $RCI->step = 1; } foreach (array('Check environment', 'Create config', 'Test config') as $i => $item) { $j = $i + 1; $link = ($RCI->step >= $j || $RCI->configured) ? '' . Q($item) . '' : Q($item); printf('
    %s
    ', $j+1, $RCI->step > $j ? ' passed' : ($RCI->step == $j ? ' current' : ''), $link); } ?> 

step]; ?>
Installer by the Roundcube Dev Team. Copyright © 2008-2012 Published under the GNU Public License;  Icons by famfamfam`

**Comment by alecpl** [comment]
This is not Rouncube issue. You have problem with setting up your http server to work with PHP.

**Comment by RussellisNobody** [comment]
I have the same issue and can't find way out of it ? Would you please help me?

**Comment by ISNewton** [comment]
> > I have the same issue and can't find way out of it ? Would you please help me?
> 
> Managed to solve it on apache2 server. (probably you should do the same for nginx)
> 
> sudo a2enmod proxy_fcgi setenvif sudo a2enconf php7.4-fpm sudo systemctl restart apache2

That solved my problem
