### ISSUE TITLE
Pressing Enter in the new confirm_dialog() box goes to undefined page

### ISSUE THREAD

**Issue by dsoares** [roundcube/roundcubemail#6055]
Tested in Google Chrome 62.0 and Firefox 56.0 in a macOS 10.12.6.

How to reproduce:
SHIFT delete a message, the new confirmation dialog appears. If you press Enter to confirm, message is deleted but roundcube goes to an unknown page. This behavior does not occur when you click the Delete button inside the dialog to confirm, only when you press Enter.

**Comment by dsoares** [comment]
Sorry. Forget the issue, it works OK.

**Comment by dsoares** [comment]
It still happens in Google Chrome. Does anyone else have this problem with the new confirmation box?

**Comment by alecpl** [comment]
I confirm the issue. It has something to do with focus not being grabbed from the message list. While the Delete button looks focused (has an outline) you can see that the list record is also focused. So, the keyboard event is propagated to the list widget.

I guess we can just stop propagation on all events closing the dialog.

**Comment by alecpl** [comment]
Fixed.
