### ISSUE TITLE
How to run roundcube inside iFrame

### ISSUE THREAD

**Issue by mcnesium** [roundcube/roundcubemail#6057]
I am trying to run roundcube 1.3.3 [within an iFrame in my Nextcloud application](https://apps.nextcloud.com/apps/external). In order to allow that, I found that a setting needs to be added to `config.inc.php`

    $config['x_frame_options'] = 'ALLOW-FROM https://nextcloud.domain.name/';

Before I added that, the iFrame just showed a blank page. After setting, the roundcube login page appeared, but a red notification below the login form stated

> **Blocked: Possible clickjacking attack!**

So I wonder what else I need to do to have roundcube running inside Nextcloud?

**Comment by alecpl** [comment]
The code is in https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L180-L195. So, if you know some javascript you can dig there.

**Comment by alecpl** [comment]
Hmmm. This code does not look right. Replace:
```javascript
else if (/^allow-from[\s\t]+(.+)$/i.test(n) && RegExp.$1.indexOf(top.location.origin) != 0)
  throw 1;
```
with
```javascript
else if (/^allow-from[\s\t]+(.+)$/i.test(n) && RegExp.$1.indexOf(top.location.origin) === 0) {
  // do nothing
}
```
and let me know if this works.

**Comment by mcnesium** [comment]
Since the app is loading `app.min.js` I removed that file and symlinked `ln -s app.js app.min.js` for a better overview. Then I edited the code as seen below (added some logging to see where I am)

    // clickjacking protection
    if (n = this.env.x_frame_options) {
      try {
        // bust frame if not allowed
        if (n.toLowerCase() == 'deny' && top.location.href != self.location.href)
          top.location.href = self.location.href;
        else if (/^allow-from[\s\t]+(.+)$/i.test(n) && RegExp.$1.indexOf(top.location.origin) === 0)
          //throw 1;
          console.log('do nothing', top.location.origin);
        else if (top.location.hostname != self.location.hostname)
          throw 1;
          console.log('throw 1', top.location.hostname, self.location.hostname);
      } catch (e) {
        // possible clickjacking attack: disable all form elements
          $('form').each(function(){ ref.lock_form(this, true); });
          this.display_message("Blocked: possible clickjacking attack!", 'error');
          console.log('block', e);
          return;
      }
    }

Turns out that when I try to load roundcube inside the iFrame, the console says `block > DOMException {  }`, so the third option is fired.

Also, when I load roundcube on its original domain, the console says `throw 1 roundcube.domain.name roundcube.domain.name` which seems kinda weird to me, because the if-clause should actually fire, if the domains do *not* match, right?

**Comment by alecpl** [comment]
Could you test my patch?

**Comment by mcnesium** [comment]
which one?

**Comment by alecpl** [comment]
In my second comment here in the ticket.

**Comment by mcnesium** [comment]
uhm… yes. I wrote about it in [the comment thereafter](https://github.com/roundcube/roundcubemail/issues/6057#issuecomment-346829710).

**Comment by alecpl** [comment]
Hmm... When you say you load it in an iframe it means the parent window origin is https://nextcloud.domain.name/ or not? You could also log top.location.origin. Last but not least, where you log 'throw 1' you probably missed to comment out `throw 1;` line. Note it will log 'throw 1' even if none of the ifs matches.

**Comment by alecpl** [comment]
This is strange. Either I'm doing something wrong or something changed in browsers. In both Firefox and Chrome reading top.location properties throws cross-origin exception. Even if the parent is in a domain set for X-Frame-Options. That would mean this code don't have a chance to work at all. @thomascube ideas?

**Comment by thomascube** [comment]
Maybe we also need to send a `Content-Security-Policy` header with a [frame-src](https://w3c.github.io/webappsec-csp/#frame-src) directive.

**Comment by thomascube** [comment]
Actually, it's the embedding app (nextcloud) which needs to send the correct CSP headers in order to allow Roundcube to run inside an iframe.

I think it's actually correct that accessing `top.location` throws an error because the top page runs on another domain. The `X-Frame-Options` only controls "whether or not a browser should be allowed to render a page in a frame". It doesn't say anything about javascript access across domains. Setting the config option `x_frame_options` to `false` should disable the clickjacking checks and thus not fail. However, that would weaken your Roundcube installation.

**Comment by thomascube** [comment]
The client-side check in app.js is basically a fallback to provide the same protection for browsers that ignore the `X-Frame-Options` header. Nowadays all of the supported browsers do support it and therefore the entire check could probably be removed. And with it will go away the failing check which is due to more restrictions in newer browsers.

**Comment by alecpl** [comment]
Thanks for confirming my impression that removing our custom protection is the way to go. Done.
