### ISSUE TITLE
PHP-LDAP binding missing in Docker image?

### ISSUE THREAD

**Issue by HenriWahl** [roundcube/roundcubemail#6058]
Hi,
when including a LDAP address book in Roundcube in latest Docker image with version 1.3.2 I get this error in the log:

`[Fri Nov 24 13:55:10.631467 2017] [php7:error] [pid 22] [client 172.17.0.1:57562] PHP Fatal error:  Uncaught Error: Call to undefined function ldap_set_option() in /var/www/html/vendor/kolab/net_ldap3/lib/Net/LDAP3.php:1934\nStack trace:\n#0 /var/www/html/vendor/kolab/net_ldap3/lib/Net/LDAP3.php(570): Net_LDAP3->config_set_debug(false)\n#1 /var/www/html/vendor/kolab/net_ldap3/lib/Net/LDAP3.php(561): Net_LDAP3->config_set('debug', false)\n#2 /var/www/html/program/lib/Roundcube/rcube_ldap.php(251): Net_LDAP3->config_set(Array)\n#3 /var/www/html/program/include/rcmail.php(218): rcube_ldap->__construct(Array, false, 'ifw-dresden.de')\n#4 /var/www/html/program/steps/mail/autocomplete.inc(69): rcmail->get_address_book('IFW')\n#5 /var/www/html/index.php(303): include_once('/var/www/html/p...')\n#6 {main}\n  thrown in /var/www/html/vendor/kolab/net_ldap3/lib/Net/LDAP3.php on line 1934, referer: https://webmail2.ifw-dresden.de/?_task=mail&_action=compose&_id=5455091075a1824b57d6b4`

Looks like some PHP-LDAP binding is missing there?

**Comment by alecpl** [comment]
What Docker image?

**Comment by HenriWahl** [comment]
https://hub.docker.com/r/roundcube/roundcubemail/ which is mentioned in https://github.com/roundcube/roundcubemail/tree/master/docker.

**Comment by alecpl** [comment]
@thomascube It would be also good to bump the version to 1.3.3.

**Comment by thomascube** [comment]
Indeed, the ldap extension is not included in the base PHP docker image.

**Comment by thomascube** [comment]
Fixed in Dockerfile and pushed new version to Docker Hub
