### ISSUE TITLE
Upgrading from 1.0.11 to 1.0.12 break attachment 

### ISSUE THREAD

**Issue by phweill** [roundcube/roundcubemail#6063]
https://bugzilla.redhat.com/show_bug.cgi?id=1517907

**Comment by alecpl** [comment]
Any errors in Roundcube error log? Make sure configured temp_dir (in Roundcube config) is writeable. Verify if open_basedir setting in php.ini that could interfere. The recent security fix made the attachment handling code more strict.

Are you suing filesystem_attachments plugin or some other?

**Comment by phweill** [comment]
fixed in $config['temp_dir']
replacing $config['temp_dir']='${_tmppath}';  by 
$config['temp_dir'] = '/tmp';

**Comment by paradoxbound** [comment]
Using a world readable and writeable directory as a location to store sensitive data is bad security. Why isn't /var/tmp/roundcube with suitable permissions an option?

**Comment by alecpl** [comment]
It can be any folder, but must exist and be writable by web server. Note, that open_basedir setting might be involved. Problem here was that some systems were misconfigured, i.e. didn't set the temp_dir option properly, which led to use of default /tmp. Our latest change revealed this misconfiguration.
