### ISSUE TITLE
html class/id for signature in order to help robot

### ISSUE THREAD

**Issue by inkhey** [roundcube/roundcubemail#6073]
Similar issue as #6049, but for signature.

As far i know roundcube render html signature this way : 
```
        <div>-- <br>
        <p>Test</p>
        </div>
```

There is no semantic way to distinct a signature from main content. Having some special class or id to distinct signature from the rest of the mail is a good idea to help robot.

After simple search, it look like this signature has a special tag during composing but this one is drop during sending (see : https://github.com/roundcube/roundcubemail/search?utf8=%E2%9C%93&q=_rc_sig&type= ), is there any good reason for that ?

**Comment by alecpl** [comment]
There might be unwanted behavior when you "edit as new" a message with such signature element. However, I think we can instead of remove, replace the id with something different.

**Comment by alecpl** [comment]
Done.
