### ISSUE TITLE
Rename "responses" to "templates"

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6077]
Many users find "responses" name confusing. Consider rename to "templates".

**Comment by thomascube** [comment]
We deliberately chose this term as the responses feature is not the same as templates. How "many users" did actually complain about this?

We might add real templates in the future and we should not "waste" this term for the responses feature. For me this is a wont fix.

**Comment by alecpl** [comment]
We had a UX study session on Elastic recently and this was reported as an issue. I also have heard such complaints before.

Indeed, the future-templates point is valid. Considering this, wontfix.
