### ISSUE TITLE
Copy/Move in Contacts toolbar

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6081]
It's possible with drag-n-drop, but for consistency with mail UI and to support mobile devices we should add such buttons. Probably hidden in More actions menu.

**Comment by johndoh** [comment]
@alecpl I started working on a possible solution for this, see https://github.com/johndoh/roundcubemail/tree/move_addressbook. The basic functionality is done, it still needs skinning. If you have time to review my work so far could you let me know, if I get the skinning done, if it might make it into 1.4?

I created a "more" menu for contact actions like there is for message actions and put the move/copy in there - only if there are multiple address books (move/copy does nothing in the same address book). Also I moved the remove contact from current group link from the footer into this menu and added an "assign contact to group" function for completeness.

There is also a container in there for plugins to add things to the menu - I think there is a ticket around to get the add vCard function into the contacts screen and I was thinking that could perhaps go in there.

**Comment by alecpl** [comment]
Thank you. Yes, if we have it implemented it will go to 1.4. What you described sounds good to me.

**Comment by alecpl** [comment]
I think we could also put QR Code button into this new menu.

**Comment by alecpl** [comment]
Merged. Thank you very much @johndoh
