### ISSUE TITLE
Docker: DB passwords and details are sent to log + upload limit via ENV

### ISSUE THREAD

**Issue by felixsand** [roundcube/roundcubemail#6083]
First of all - really good job with creating a docker image for Roundcube! Saved us a lot of work :-)

Now we did found a couple of issues however. The first one being that DB details such as passwords are sent do the Docker log.

The other one is that it would be really nice to be able to set the upload limit via ENV. 5MB might be a bit too low for many cases.

Keep up the good work!

**Comment by thomascube** [comment]
> DB details such as passwords are sent do the Docker log.

Any suggestions how could this be avoided? Probably by omitting to send the generated config file to stdout in `docker-entrypoint.sh`?

> set the upload limit via ENV.

Good point! I didn't actually look at the defaults used by the php base image.

**Comment by felixsand** [comment]
One way is to break out the configuration parts of docker-entrypoint.sh to a separat .sh file. Then call this from docker-entrypoint.sh and send stdout to dev/null maybe? This might result in a cleaner docker-entrypoint file as well :)

**Comment by thomascube** [comment]
Pushed new version of the Docker image with tag `latest`
