### ISSUE TITLE
Any value of address field in advanced contact search return all contacts from ldap

### ISSUE THREAD

**Issue by inpos** [roundcube/roundcubemail#6084]
Hi.
In Address book go to advanced search.
Fill only address field with any value and click search.
Return all contacts from all user address books.

Roundcube version: 1.3.1

**Comment by alecpl** [comment]
Works for me. Please, update to 1.3.3 and try again. What type of addressbooks are you using? Try with disabled all plugins.

**Comment by inpos** [comment]
I've disabled all plugins. Same result.
I use LDAP Address book.
I was wrong said that search returns all contacts from all user address book.
I've created contact in SQL Address book and fill city with come name (ex. GreatCity).
When search with address "abra-kadabra" it's return all contacts from LDAP address book.
When search with address "GreatCity" it's return all contacts from LDAP address book and one contact from SQL address book with city "GreatCity".
What I must configure to proper address search in LDAP address book?
My fieldmap in LDAP address book config
```
'fieldmap' => 
    array (
      'name' => 'displayName',
      'surname' => 'sn',
      'firstname' => 'givenName',
      'email' => 'mail:*',
      'phone:home' => 'homePhone',
      'phone:work' => 'telephoneNumber',
      'phone:mobile' => 'mobile',
      'phone:pager' => 'otherTelephone',
      'phone:workfax' => 'facsimileTelephoneNumber',
      'street' => 'street',
      'zipcode' => 'postalCode',
      'region' => 'st',
      'locality' => 'l',
      'country' => 'c',
      'organization' => 'company',
      'department' => 'department',
      'jobtitle' => 'title',
      'notes' => 'description',
      'photo' => 'thumbnailPhoto',
    ),
```

**Comment by alecpl** [comment]
Enable ldap_debug and provide the log, please. Could you be more specific on exactly which fields are problematic?

**Comment by inpos** [comment]
I've done debug myself and determined that I must specify address fieldmaps in ldap config like this:
```
      'address:street' => 'street',
      'address:zipcode' => 'postalCode',
      'address:region' => 'st',
      'address:locality' => 'l',
      'address:country' => 'c',
```
Otherwise [this code block](https://github.com/roundcube/roundcubemail/blob/5d26de4467fec2f7d04bd3b28ab92fe1515a175a/program/lib/Roundcube/rcube_ldap.php#L132) don't create subarray "attributes" for array-item "address".
Therefore generated ldap filter don't contain necessary ldap attributes (street, postalcode, st, l, c).

I think correct address field map must be documented.

By the way, [this code block](https://github.com/roundcube/roundcubemail/blob/5d26de4467fec2f7d04bd3b28ab92fe1515a175a/program/lib/Roundcube/rcube_ldap.php#L169) don't work at all.

**Comment by alecpl** [comment]
The configuration format you used initially is still supported, but there was a regression. Fixed.
