### ISSUE TITLE
Date parsing hangs with certain malformed headers

### ISSUE THREAD

**Issue by bbraybrook** [roundcube/roundcubemail#6087]
Somehow a user ended up with a message with headers like:

To: <sarah@blahblah.com>,
	<cath@blahblah.com>,
	<justin@blahblah.com>,
Date: 16 Sep 2015 12:03:32 +0100
	<danielle@blahblah.com>,
	<timothy@blahblah.com>,

When roundcube tries to call list_messages on the message set containing this message, the process hangs (in my case, the php-fpm process eventually times out, not sure what happens with php as a module).

Ideally, roundcube would gracefully handle this condition.

**Comment by alecpl** [comment]
What PHP version? Could you provide a sample message?

**Comment by bbraybrook** [comment]
php 5.4.45

i added a bunch of trace logging, and it was the date parsing call that it would get stuck at - the string it passes is the date plus a huge list of email addresses, all separated by space (from the header folding)

message attached. it's pretty extreme with the number of email addresses in the headers.

[bad_headers_hangs_roundcube.msg.gz](https://github.com/roundcube/roundcubemail/files/1552638/bad_headers_hangs_roundcube.msg.gz)

**Comment by alecpl** [comment]
Thanks. This was a very long running loop in rcube_utils::strtotime(). I think my fix is slightly better, but I will also add some checks in rcube_imap_generic::fetch().

**Comment by bbraybrook** [comment]
fixing it in rcube_utils seems like the better way to go. :)
