### ISSUE TITLE
Change password issue in Virtualmin - Error: Could not save new password.

### ISSUE THREAD

**Issue by pankajpragma** [roundcube/roundcubemail#6092]
Hi,

I have installed Roundcube v1.3.3 in Virtualmin version 5.05 and activated "password" plugin by editing "/config/config.inc.php" 

```
# /config/config.inc.php
// List of active plugins (in plugins/ directory)
$config['plugins'] = array(
   'virtuser_file',
    'archive',
    'zipdownload',
    'password',
);
```

Then rename  "/plugins/password/config.inc.php.dist" to "/plugins/password/config.inc.php" and I can see Password reset field in "Roundcube > Settings > Password".

<img src="http://storage2.static.itmages.com/i/17/1214/h_1513250239_7318713_1d45f2edc9.jpeg" />

But when I am trying to change password then it shows error: <strong>"Error: Could not save new password."</strong>
It does check the current password so it means that it is able to connect to the database. 

I also tried to run following commands from "/plugins/password/helpers" directory:

```
gcc -o chgvirtualminpasswd chgvirtualminpasswd.c
chown root:<FCGId domain owner user> chgvirtualminpasswd
strip chgvirtualminpasswd
chmod 4550 chgvirtualminpasswd 
```

```
# /plugins/password/config.inc.php
$config['password_driver'] = 'virtualmin';
```

But it is still showing the same error. Can anyone please help?

**Comment by alecpl** [comment]
Any errors in log? See plugins/password/drivers/virtualmin.php file for example commands and execute them by hand.

**Comment by pankajpragma** [comment]
After further investigation, I found that "chgvirtualminpasswd" is not executing: 

Log: _**Password plugin: Unable to execute plugins/password/helpers/chgvirtualminpasswd**_ 

I tried all possibilities to fix it permission but it is still not working: 

```
chown root.<domain owner user> plugins/password/helpers/chgvirtualminpasswd
chown root:<domain owner user> plugins/password/helpers/chgvirtualminpasswd
chown <domain owner user>:<domain owner user> plugins/password/helpers/chgvirtualminpasswd

chmod 0755 plugins/password/helpers/chgvirtualminpasswd
chmod 0777 plugins/password/helpers/chgvirtualminpasswd

```

I tried to execute the file using php exec() and it shows error "**_/usr/sbin/virtualmin must be run as root"_** 

`echo exec('plugins/password/helpers/chgvirtualminpasswd');
`

I am using Ubuntu 16.04.

**Comment by pankajpragma** [comment]
**_SOLVED:_**

After banging my head against the wall, finally, I could FIX it

Output of  this line was:
```
# /plugins/password/drivers/virtualmin.php
exec("$curdir/chgvirtualminpasswd modify-user --domain $domain --user $username --pass $newpass", $output, $returnvalue);
```

> plugins/password/helpers/chgvirtualminpasswd modify-user --domain 'localhost' --user 'testmail-example.com' --pass 'testmail123'

Where User format is wrong. So I have manually added a lines bellow it "$username = $_SESSION['username']" to replace "-" with "@":

```
$username = $_SESSION['username'];
$username = str_replace("-", "@", $username);
```
And it's been FIXED....

<img src="http://storage4.static.itmages.com/i/17/1214/h_1513260357_3942962_f6d2fe8e9c.jpeg
" />


**Notes:**
I also had to adjust the chown & chmod as per suggested in README: 
```
gcc -o plugins/password/helpers/chgvirtualminpasswd plugins/password/helpers/chgvirtualminpasswd.c
chown root:doman_user plugins/password/helpers/chgvirtualminpasswd
chmod 4550 plugins/password/helpers/chgvirtualminpasswd
```

**General Query**
Why didn't it manage to change the user email format even if I had specified it in config file:

```
# /plugins/password/config.inc.php 
$rcmail_config['password_virtualmin_format'] = 0;
```

Is this a bug Or did I add it in wrong place?

@alecpl Thanks for your help.

**Comment by alecpl** [comment]
Where did you find password_virtualmin_format option? It does not exist.

**Comment by pankajpragma** [comment]
I could found it while Googling and also it was written at the top of the /plugins/password/drivers/virtualmin.php file so I thought I should try to set it in the config file but unfortunately it didn't work and I had to overwrite  ` $username = $_SESSION['username']; $username = str_replace("-", "@", $username); `


```
class rcube_virtualmin_password
{
    function save($currpass, $newpass)
    {
        $rcmail   = rcmail::get_instance();
        $format   = $rcmail->config->get('password_virtualmin_format', 0);
        $username = $_SESSION['username'];
```

**Comment by alecpl** [comment]
Ah, the option has been removed here https://github.com/roundcube/roundcubemail/pull/5759. I'm closing this ticket.

**Comment by kalyankalapala** [comment]
I am trying to update the password of my mailserver. But i am getting error as COULD NOT SET NEW PASSWORD. 
      When I checked my log files, I got this as an issue.
[passwd error.txt](https://github.com/roundcube/roundcubemail/files/5678666/passwd.error.txt)

**Comment by kalyankalapala** [comment]
I am trying to update the password of my mailserver. But i am getting error as COULD NOT SET NEW PASSWORD.
When I checked my log files, I got this as an issue.

Table 'roundcube.mailbox' doesn't exist (SQL Query: UPDATE `mailbox` SET `password`= '$1$uNQpUyO6$as4HhUuydZep1N3xVpQ6/.', modified=now() WHERE `username` = 'user@mailserver.com' LIMIT 1) in /var/www/webmail.com/html/program/lib/Roundcube/rcube_db.php on line 543

Please help me to fix this
