### ISSUE TITLE
Roundcube should clean up attachments when deleting draft email

### ISSUE THREAD

**Issue by paradoxbound** [roundcube/roundcubemail#6094]
Roundcube doesn't clean up any attachments uploaded to a draft email when that draft is deleted. The code that deletes an attachment in the temp directory when a email is sent should also be called when an draft is deleted.

To reproduce: 
- create a draft email
- attach a file to email
- delete draft. 
The attachment can still be found in the "$config['temp_dir']" directory.

**Comment by alecpl** [comment]
What exactly did you do between step 2 and 3? What Roundcube version? What attachments plugin?

**Comment by alecpl** [comment]
I guess it might be an issue described in #5089 and has nothing to do with deleting email. If not, please be more specific.

**Comment by paradoxbound** [comment]
thank you for the prompt reply. 
I create and email attach a small PDF to the email then press the cancel button and confirm.

Roundcube version is 1.3.3 setup via the mail-in-a-box scripts, the only change being I changed the "$config['temp_dir']" to "/var/tmp/roundcube" and making it readable and writeable by "www-data"

I will reply in a few minutes with the attachment plugin details, sorry I don't know the code very well.

Doesn't seem like session data but could be wrong.

**Comment by paradoxbound** [comment]
Doesn't seem to use a specific attachment plugin according to the install script, so I am guessing it uses a default?
https://github.com/mail-in-a-box/mailinabox/blob/master/setup/webmail.sh

This is the contents of my roundcube temp dir. First an attachment on a draft and the attachment is gone once sent. The second shows the attachment remains once I cancel the draft.

jim@box:~$ ls -l /var/tmp/roundcubemail/
total 12
-rw------- 1 www-data www-data 10771 Dec 15 09:33 rcmAttmntPD1zDC
jim@box:~$ ls -l /var/tmp/roundcubemail/
total 0
jim@box:~$ ls -l /var/tmp/roundcubemail/
total 12
-rw------- 1 www-data www-data 10771 Dec 15 09:34 rcmAttmntPUeOJU
jim@box:~$ ls -l /var/tmp/roundcubemail/
total 12
-rw------- 1 www-data www-data 10771 Dec 15 09:34 rcmAttmntPUeOJU

**Comment by alecpl** [comment]
Good you used word "cancel", as it's not the same as "delete". Anyway, that's the ticket I referred before is talking about too. When you cancel composing session related attachments are not removed. It is because it's not simple to do reliably. Any temp_dir contents are removed after a while, depending on configuration.

I'll leave this ticket to settle for some time, but it will be probably wontfix as the other ticket.

**Comment by paradoxbound** [comment]
Thank you, could you point me in the right direction to check that my config does in fact cleanup the temp directory please?

**Comment by alecpl** [comment]
temp_dir_ttl. Note that garbage collector depends on PHP session settings (gc_divisor, gc_probability), so you should verify these too.
