### ISSUE TITLE
[composer] No full installation available?

### ISSUE THREAD

**Issue by mmjjb** [roundcube/roundcubemail#6096]
I just wanted to install roundcube, and the suggested approach in the manual is just to download the zip and unzip it.. And how about updates then? Am I seriously supposed to check for new zips once in an while?...

So I wanted to download and keep roundcube updated trough composer... but this is not supported? Or am I reading things wrong?

**Comment by alecpl** [comment]
That's right. You can't install/update fully automatically.

**Comment by thomascube** [comment]
Except using pre-built packages from your OS distribution as described in the "Other sources and downloads" section of the download page.

**Comment by mmjjb** [comment]
Thanks for replying.

But is this not an very important lacking feature?
That there is good way to install & update roundcube?
