### ISSUE TITLE
PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#6098]
Hello!

RELEASE 1.3.3.  I have the following warnings in the log:

    Dec 19 16:04:38 mail roundcube[2174]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/vendor/pear/mail_mime/Mail/mimePart.php on line 314
    Dec 19 17:21:17 mail roundcube[2188]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 1435
    Dec 19 17:21:17 mail roundcube[2188]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 1534
    Dec 19 17:21:17 mail roundcube[2188]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 1938
    Dec 19 17:24:43 mail roundcube[2185]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/program/steps/mail/move_del.inc on line 47
    Dec 19 17:25:02 mail roundcube[2184]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/program/steps/mail/move_del.inc on line 78

One issue I've already fixed with #5845 fix.

**Comment by alecpl** [comment]
For first warning you need newer Mail_Mime package. Sieve warnings were fixed in 7c6bbd81b0a, but I have to verify and backport to 1.3. The last two does not look fixed yet.

**Comment by quicktrick** [comment]
One more warning:

    Dec 19 18:46:57 mail roundcube[2175]: PHP Warning:  Use of undefined constant href - assumed 'href' (this will throw an Error in a future version of PHP) in /srv/www/mydomain.tld/roundcubemail/program/steps/settings/about.inc on line 96

**Comment by quicktrick** [comment]
> For first warning you need newer Mail_Mime package.

I'm afraid, not.  I didn't have Mail_Mime package on my server at all.  Yesterday I installed it.  And after that I have the same warnings:

    Dec 20 14:06:37 mail roundcube[2592]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/vendor/pear/mail_mime/Mail/mimePart.php on line 314

**Comment by alecpl** [comment]
It uses the package from Roundcube vendor folder. You have to update it with composer or wait for the next Roundcube release.

**Comment by alecpl** [comment]
All the above are now fixed in master and release-1.3 branch. Some were already fixed in master.

**Comment by quicktrick** [comment]
It's working fine on my servers so far!  Thanks a lot!

**Comment by quicktrick** [comment]
Hi @alecpl ,

There is one more issue of the same type:

    Jan 20 13:02:54 mail roundcube[3294]: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /srv/www/mydomain.tld/roundcubemail/program/steps/mail/sendmail.inc on line 892

**Comment by alecpl** [comment]
@quicktrick I fixed this one. Please, create new tickets in future.
