### ISSUE TITLE
Root folder level

### ISSUE THREAD

**Issue by Egyptions** [roundcube/roundcubemail#6099]
Hi, Excuse my ignorance, but is there any way of creating folders above "INBOX" in the hierarchy? My mail client automaticaly creates folders like "Sent" that are the same level as "INBOX" and not subfolders of "INBOX"

**Comment by alecpl** [comment]
If the server allows that (not all do) you can. As a user, just delete them and create under INBOX, then set the new folders in Special Folders preferences. As an admin, add INBOX. prefix to special folders in configuration file.

**Comment by Egyptions** [comment]
Problem is that my mail client (EM Client) automatically creates folders like "Sent" at the same level as the inbox. This automatically created file is created as a special folder in the mail client and you cannot delete or moe this folder.
