### ISSUE TITLE
kolab/net_ldap3 has a new commit, roundcube-1.2.7-complete.tar.gz should be updated.

### ISSUE THREAD

**Issue by seriv** [roundcube/roundcubemail#6100]
Otherwise we get <code>The .git directory is missing from /var/www/sites/webmail/roundcubemail-1.2.7/vendor/kolab/net_ldap3, see https://getcomposer.org/commit-deps for more information</code>
Running composer in the roundcubemail directory gives:
<code>
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
Updating dependencies                                          
Package operations: 0 installs, 1 update, 0 removals
  - Updating kolab/net_ldap3 dev-master (4c21bde => d2d74d6): 
                                                                                                                                                                                 
  [RuntimeException]                                                                                                                                                             
  The .git directory is missing from /var/www/sites/webmail.cs.umd.edu/roundcubemail-1.2.7/vendor/kolab/net_ldap3, see https://getcomposer.org/commit-deps for more information  
                                                                                                                                                                                 

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
</code>

**Comment by alecpl** [comment]
I have no idea what that means, but in master we change the way we use net_ldap3 package. See e61121dc2f6.

ps. Not all commits in net_ldap3 are important from Roundcube point of view.

**Comment by alecpl** [comment]
This is a wontfix for 1.2.
