### ISSUE TITLE
Export selected contact only exports the first 10

### ISSUE THREAD

**Issue by ychaouche** [roundcube/roundcubemail#6103]
Hello,

In 1.2.4, the export selected contacts feature of the address book only exports the first ten selected contacts.

Screencast available here : https://vimeo.com/248124644

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.

**Comment by ychaouche** [comment]
Works in here too, thanks a lot for the quick fix @alecpl !
