### ISSUE TITLE
managesieve breaks when theres no SASL auth method before TLS

### ISSUE THREAD

**Issue by Littlericket** [roundcube/roundcubemail#6106]
Hi,

managesieve doenst work well when theres no sasl auth method before tls (disable_plaintext_auth = yes).
![image](https://user-images.githubusercontent.com/1573629/34244697-da83f632-e626-11e7-8281-dbacdd192ed2.png)

also i noticed that managesieve's behaviour is strange when doing tls negotiation without a sasl (it logouts?? after the tls negotiation confirmation from managesieve):
![image](https://user-images.githubusercontent.com/1573629/34244756-2eb4242a-e627-11e7-869b-15cbaf9cf2d9.png)

**Comment by alecpl** [comment]
According to RFC5804: "After the TLS layer is established, the server MUST re-issue the capability results, followed by an OK response". I don't see this here. Looks like dovecot bug.

**Comment by alecpl** [comment]
Sorry, I should read more carefully. It looks the TLS wasn't established successfully. Are there any errors in the log?

**Comment by Littlericket** [comment]
Hi alec,

yup, managesieve quits with
![image](https://user-images.githubusercontent.com/1573629/34246260-0fe9f270-e62e-11e7-8cfb-69571bad1141.png)

**Comment by alecpl** [comment]
Strange, because on successful TLS negotiation I expect "STARTTLS negotiation successful" in debug log. And only then we try to authenticate.

What Roundcube, Net_Sieve and PHP version?

**Comment by Littlericket** [comment]
`PHP 7.1.11 (fpm-fcgi) (built: Nov  4 2017 10:40:04)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11, Copyright (c) 1999-2017, by Zend Technologies
`

Roundcube is on 1.3.3, managesieve on 8.7
How do I get the net_sieve version?

**Comment by alecpl** [comment]
If that's a "complete" vanilla package (or composer-installed, you'll find Net_Sieve somewhere in /vendor folder, but it may be a distribution package of your system.

If you know PHP a little you can do some debug in _startTLS() method in Sieve.php file.

**Comment by Littlericket** [comment]
Latest changelog entry in net_sieve package.xml is release 1.3.4. I've added a debug log entry when trying to enable stream_socket_enable_crypto(), it quits with false there. Exploring the dovecot ssl verbose log, the following gets shown for managesieve-login

![image](https://user-images.githubusercontent.com/1573629/34248154-405fb668-e635-11e7-84c4-43cb010505f9.png)

Looks to me that the Sieve.php somehow quits the negotiation w/o any following login ...

**Comment by alecpl** [comment]
But you didn't find "Failed to establish TLS connection" in error log? Anyway, if this method fails it will be PHP issue, we can't do much about. Maybe you can make it working changing crypto_method (see lines above stream_socket_enable_crypto() call).

**Comment by Littlericket** [comment]
Hi,

unfortunatly no, thats all I get in the managesieve debug log
![image](https://user-images.githubusercontent.com/1573629/34248554-d9279658-e636-11e7-92b2-7df51882225a.png)

i though about maybe a wrong openssl version, but that could not be the case here, could it?
`OpenSSL 1.0.2k  26 Jan 2017 (Library: OpenSSL 1.0.2n  7 Dec 2017)`

**Comment by alecpl** [comment]
I really don't see what we can do with it. Closing.

**Comment by asbachb** [comment]
I'm facing the same problem.

```
PHP 7.2.5 (fpm-fcgi) (built: Apr 24 2018 18:12:25)
```

managesieve config
```
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: "IMPLEMENTATION" "Dovecot Pigeonhole"
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric re>
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: "NOTIFY" "mailto"
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: "SASL" ""
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: "STARTTLS"
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: "VERSION" "1.0"
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: OK "Dovecot ready."
[05-May-2018 00:58:02 +0000]: <beeaaf24> C: LOGOUT
[05-May-2018 00:58:02 +0000]: <beeaaf24> S: OK "Logout completed."
```

sieve debug log
```
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: "IMPLEMENTATION" "Dovecot Pigeonhole"
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric re>
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: "NOTIFY" "mailto"
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: "SASL" ""
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: "STARTTLS"
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: "VERSION" "1.0"
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: OK "Dovecot ready."
[05-May-2018 00:47:25 +0000]: <beeaaf24> C: LOGOUT
[05-May-2018 00:47:25 +0000]: <beeaaf24> S: OK "Logout completed."
```

dovecot log
```
May  5 02:58:02 zeus dovecot: auth: Debug: auth client connected (pid=11260)
May  5 02:58:02 zeus dovecot: managesieve-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=10.0.4.206, lip=10.0.4.91, session=<NGi37WprSAAKAATO>
```

**Comment by phroggar** [comment]
For those stumbling upon this issue:

Raise your error reporting level and try the connection, example:

```
error_reporting(-1);
ini_set('display_errors','on');
$sieve = new Net_Sieve($account->imap_user, $account->imap_pass, $account->imap_host, 4190,'','',$debug=true);
```

You might get an error such as: 

**Warning:  stream_socket_enable_crypto(): Peer certificate CN=`xxxx' did not match expected CN=`yyy' in /server/xelos/vendor/pear/net_sieve/Sieve.php on line 1404**

You should then adapt the context options (depending on your issue):

```
$sieve = new Net_Sieve($account->imap_user, $account->imap_pass, $host, 4190,'','',true,false,true, [
				'ssl'=>[
				'verify_peer'=>false,
				'verify_peer_name'=>false,
			]]);
```

**Comment by iamkhalidbashir** [comment]
> I'm facing the same problem.
> 
> ```
> PHP 7.2.5 (fpm-fcgi) (built: Apr 24 2018 18:12:25)
> ```
> 
> sieve debug log
> 
> ```
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: "IMPLEMENTATION" "Dovecot Pigeonhole"
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: "SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric re>
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: "NOTIFY" "mailto"
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: "SASL" ""
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: "STARTTLS"
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: "VERSION" "1.0"
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: OK "Dovecot ready."
> [05-May-2018 00:47:25 +0000]: <beeaaf24> C: LOGOUT
> [05-May-2018 00:47:25 +0000]: <beeaaf24> S: OK "Logout completed."
> ```
> 
> dovecot log
> 
> ```
> May  5 02:58:02 zeus dovecot: auth: Debug: auth client connected (pid=11260)
> May  5 02:58:02 zeus dovecot: managesieve-login: Aborted login (no auth attempts in 0 secs): user=<>, rip=10.0.4.206, lip=10.0.4.91, session=<NGi37WprSAAKAATO>
> ```

did you find the solution?

**Comment by wolfff** [comment]
I ran into the same error and at the end it turns out that
$config['managesieve_usetls'] = true;
does not work as expected (error persist), but setting
$config['managesieve_host'] = 'tls://%h';
solved the problem.

**Comment by kangsterizer** [comment]
See https://github.com/roundcube/roundcubemail/issues/8310 and https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/config.inc.php.dist

They removed `$config['managesieve_usetls'] = true;` (without much of a warning :) and indeed `$config['managesieve_host'] = 'tls://%h'` is now the correct way to configure this.

thanks @wolfff !
