### ISSUE TITLE
Moved Messages Reappear in Inbox

### ISSUE THREAD

**Issue by jrhutchins** [roundcube/roundcubemail#6107]
Unread(?) messages moved to a folder using either menu or drag-and-drop reappear in the inbox (may not be happening with read messages).

**Comment by alecpl** [comment]
Please, provide detailed steps to reproduce. Enable imap_debug and provide the log. Disable all plugins. Use most recent version.

**Comment by jrhutchins** [comment]
This is not a known issue or expected behavior?

Where is enabling imap_debug documented?

---
Jonathan

**Comment by alecpl** [comment]
Does not sound like a valid behavior. As for the setting, just add `$config['imap_debug'] = true;` to the config.inc.php file. This will log to logs/imap. Make sure to do test with one user active or use another option `per_user_logging`. You can find config options descriptions in defaults.inc.php.

**Comment by jrhutchins** [comment]
Running 1.2.3+dfsg.1-4+deb9u1 as packaged for Debian Stable.

I have read that roundcube caches messages locally for improved 
performance.  What appears to be happening is that roundcube is failing to 
write the changes to the messages/folders back to the server.  Since I 
need working email TODAY, not some indefinite troubleshooting time in the 
future, I reverted to Alpine, and message status (read/unread) has not 
been applied to messages on the server.

Roundcube as packaged for Debian Stable is unusable.

I will file bugreports with Debian, but I'm really disappointed with the 
quality of the software released.  Roundcube seems to be a project for 
developers only.

**Comment by alecpl** [comment]
That don't have to be Roundcube issue. We can't really help without debug information.

What you say about Roundcube some people say about Debian.

**Comment by jrhutchins** [comment]
Running 1.2.3+dfsg.1-4+deb9u1 as packaged for Debian Stable.

I have read that roundcube caches messages locally for improved 
performance.
What appears to be happening is that roundcube is failing to write the 
changes
to the messages/folders back to the server.  Since I need working email 
TODAY,
not some indefinite troubleshooting time in the future, I reverted to 
Alpine,
and message status (read/unread) has not been applied to messages on the
server.

Roundcube as packaged for Debian Stable is unusable.

I will file bugreports with Debian, but I'm really disappointed with the
quality of the software released.  Roundcube seems to be a project for
developers only.

**Comment by jrhutchins** [comment]
Apologies, this is not a problem with roundcube.  Debian's 
autoconfiguration of dovecot does not allow it to write lockfiles to 
/var/mail, which prevents it from updating the inbox.

---
Jonathan
