### ISSUE TITLE
Checkbox to show/hide message pane is missing

### ISSUE THREAD

**Issue by Beckfield** [roundcube/roundcubemail#6108]
My ISP recently upgraded to RoundCube 1.3.3.  There used to be a checkbox on the toolbar below the message list to show or hide the message pane.  It is missing since the update, and I can find no other way to toggle the message pane.  Has it been removed intentionally?  If so, please restore it.

**Comment by alecpl** [comment]
Yes. The mode can be change by the messages list menu or in Preferences.

Duplicate.

**Comment by Beckfield** [comment]
I ask again that the checkbox be restored to its previous location.  I frequently toggle the message pane, and the checkbox is far more convenient than going to a menu to change views.  There is plenty of room for the checkbox.  The UI hasn't changed much in that area, so it isn't a matter of screen space.  I see no reason for this reduced convenience.

**Comment by iBeleave** [comment]
I respectfully agree with Beckfield.  The messages list menu is useful, but the toggle button was better and i used it often.
