### ISSUE TITLE
option: when I delete message, the newer by date (upper in the list) is opened

### ISSUE THREAD

**Issue by nerijus** [roundcube/roundcubemail#6109]
Lets suppose I have 5 unread messages. I select the most upper one (it is the latest message), if I delete it, I see the older one and so on. But I would like to read from the oldest unread message to the newest. How do I do that?
Now if I select the oldest unread message and delete it, the message below it is opened. I would like the next unread (the upper message) to be opened instead.

**Comment by alecpl** [comment]
Change the order and filter the list to show only unread.

**Comment by nerijus** [comment]
If I change the order, I have to go to the last page in order to see the newest messages. And I have to do that after every logout/login. Is there a setting to open the last page after the login instead of first?

**Comment by nerijus** [comment]
I change the order, go to the last page and wait until I get the new message. The list view scrolls to the top, and I don't see the new message until I scroll down. It is a bit uncomfortable.
