### ISSUE TITLE
R=dnslookup T=remote_smtp defer (110): Connection timed out

### ISSUE THREAD

**Issue by Engineer-UA** [roundcube/roundcubemail#6110]
Hello All!
Had somebody encountered such error while sending email?
I use the latest version of roundcube. All incoming letters are recieving without any problem. But while trying to send or to reply any letter I see this in the main.log:

.... R=dnslookup T=remote_smtp defer (110): Connection timed out

And after a small period of time I see in the log:

exim 4.89 daemon started: pid=415, -q1h, listening for SMTP on port 25 (IPv6 and IPv4) port 587 (IPv6 and IPv4) and for SMTPS on port 465 (IPv6 and IPv4)
Start queue run: pid=449
1eSVjc-0000GA-8b Message is frozen
1eSgW1-0001e3-Ri Message is frozen
End queue run: pid=449 

and recieve incoming message by e-Mail with subject: "Mail delivery failed: returning message to sender" 

Status: 5.0.0
Remote-MTA: dns; mxs.ukr.net
Diagnostic-Code: smtp; 550 invalid helo given

How to straggle against this task?

**Comment by alecpl** [comment]
Enable smtp_debug in Roundcube config and check the log. Also verify all smtp_* options (you can find all of them with description in defaults.inc.php). Looks like configuration issue.
