### ISSUE TITLE
feature request : Scale and rotate images in attachment preview

### ISSUE THREAD

**Issue by kalaur** [roundcube/roundcubemail#6111]
Good afternoon!
Could you make scaling (zoom in) and rotation in attachment preview for images?

**Comment by alecpl** [comment]
This is now implemented in Elastic skin. @thomascube Could you provide additional icons for Larry toolbar?

https://kolabian.wordpress.com/2018/01/28/elastic-image-tools-and-more-bugfixes/

**Comment by thomascube** [comment]
@alecpl that's "zoom in", "zoom out" and "rotate", right?

**Comment by kalaur** [comment]
yes. right

**Comment by thomascube** [comment]
Larry icons added
