### ISSUE TITLE
embedded <img> tags not honoured

### ISSUE THREAD

**Issue by winksmith** [roundcube/roundcubemail#6118]
I am running roundcube 1.1.1. i am displaying an HTML email page which looks like this:

![1](https://user-images.githubusercontent.com/1887566/34517151-b6271ebe-f0de-11e7-8859-badabbfa6c7b.png)

The broken images displayed refer to static images from a <img> tag referring to a website on a remote host. For instance this one. http://static.mapmyfitness.com/d/emails/StyleCampaign/2dot0/MapMyRun_email_logo.png

I have my settings set to display HTML for this folder.

How do I configure myself to display images?

**Comment by alecpl** [comment]
First, upgrade! Second, provide a sample message.

**Comment by winksmith** [comment]
hmmm... well it's part of a plugin package for openmediavault. i'd be afraid to upgrade if it doesn't integrate with the existing inrastructure. i can supply a snipped of HTML, is that sufficient?

**Comment by alecpl** [comment]
I don't see a reason why it would not work. Check your browser console. Roundcube 1.1 is not supported anymore.

**Comment by winksmith** [comment]
Thanks. Could I get an idea as to check my browser console? is that a roundcube feature? I'm not getting a lot of feedback on what is going on internally. Are there logs I could turn on?

Simultaneously, I'm poking openmediavault (OMV) to find out if there's a newer plugin. At the end, i could try and just install the latest and not integrate at all into OMV I suppose.
