### ISSUE TITLE
Selector

### ISSUE THREAD

**Issue by wbuk** [roundcube/roundcubemail#6121]
When you are in 3 pane mode and you click on the cog and in the first column click on Selector, then OK, the selector box does not appear.

One of our customers has lost the use of one arm due to a stroke and can not select multiple emails to delete without the selector.  She contacted us and said she was quite unwell having spent over 1 hour deleting over 100 emails then gave up with over 700 to sift through still. 

Please, can you have a look at this problem?

**Comment by alecpl** [comment]
What Selector? Sounds to me as some external plugin we do not support.

I'm working now on a new skin for Roundcube that will have checkbox selection on lists implemented. The skin is planned to be an official skin of Roundcube 1.4.
