### ISSUE TITLE
v1.3.x not creating default folder "Archive"

### ISSUE THREAD

**Issue by JesselSteele** [roundcube/roundcubemail#6122]
##### Background:
In v1.2.x, I created the "Archive" folder via the create_default_folders declaration using these lines in `defaults.inc.php`:

`$config['create_default_folders'] = true;`

`$config['archive_mbox'] = 'Archive';`

...based on the pattern `$config['drafts_mbox'] = 'Drafts';`, etc.

It was a wild guess on my part and it fully worked, even automatically set itself in the Settings of the GUI.

##### Problem:
As of v1.3.x, this stopped working completely, but still works on my identical servers with the same PHP7 LAMP install scripts with v1.2.x.

I suspect this is related to the roadmap, not an syntax error or type-o.

##### Request/Bug:
*Pretty please with sugar* make it work again. I understand roadmaps and structure and maybe it wasn't "supposed" to work in the first place, but *"Archive" should be automatically created when/if "Sent", "Drafts", "Trash", and "Junk" are if the Archive plugin is active.*

###### Considerations & What About...?:
- I've tried putting `$archive_mbox = $RCMAIL->config->get('archive_mbox');` in some files here and there (ie. `func.inc` line 274) and still can't make it work. So, no code contribution from me.
- What about just integrating the Archive plugin into the core and turning it on with a boolean setting in `config.inc.php`? Just sayin'.
- In the long run, why not do core-integration with other plugins as well, so composer doesn't break them and to bestow the "my plugin became core" honor on their authors and make everyone's life easier, including the Roundcube team? Just sayin'.

Much love.

**Comment by alecpl** [comment]
This was actually a bug. Fixed in 08f27316eeb57ca927311e4e192248f7532dbc9e.
