### ISSUE TITLE
behind reverse proxy

### ISSUE THREAD

**Issue by cuora** [roundcube/roundcubemail#6124]
I liked to have roundcube behind a reverse proxy, only the url will be the local then on the login page.
I replaced the first line of config/main.inc.php  by :
if(!empty($_SERVER['HTTP_X_FORWARDED_HOST'])){
        $domain_parts = explode(".", $_SERVER['HTTP_X_FORWARDED_HOST']);
}else{
        $domain_parts = explode(".", $_SERVER['SERVER_NAME']);
}

Also i'm using rc for multi domain and liked to have the logo's of the domain/customers so i added/replaced  in the same file:

if(file_exists ( 'images/logo_'.$domain_parts[1].'.png')) {
        $rcmail_config['skin_logo'] = 'images/logo_'.$domain_parts[1].'.png';
}elseif(file_exists ( 'images/logo_'.$domain_parts[1].'.gif')) {
        $rcmail_config['skin_logo'] = 'images/logo_'.$domain_parts[1].'.gif';
}else{
        $rcmail_config['skin_logo'] = null;
}

just my input of thus nice webmail

**Comment by alecpl** [comment]
Thanks, but nothing to do here.
