### ISSUE TITLE
Roundcube Chrome 

### ISSUE THREAD

**Issue by 111lisu** [roundcube/roundcubemail#6126]
Roundcube Webmail 1.4-git   

I have a problem with roundcube support through the Chrome browser
If I write a new email for a dozen or so seconds, the message is sent without any problems.
If the writing takes a few minutes and an empty page is displayed
**https://mail.pl/?_task=mail&_unlock=loading1515413972865&_lang=pl&_framed=1**
The browser waits a long time and displays **requesttimedout**, but the message is sent.
There are no such problems with firefox.

Mariusz

**Comment by alecpl** [comment]
It may hang on the imap connection. After the mail is sent it's being saved to Sent folder. So, investigate this e.g. with imap_debug enabled. Any errors in log? Any errors in browser error console?

**Comment by 111lisu** [comment]
Even autosave is crashing
Ok, I'll try to do it and some logs

**Comment by alecpl** [comment]
No feedback. No issue.
