### ISSUE TITLE
Multiple SMTP Servers

### ISSUE THREAD

**Issue by morno** [roundcube/roundcubemail#6129]
Hello Roundcube

i got a issue i got 2 mail servers and i want all my users to use a single roundcube installation so i have set 
$config['default_host'] = array(
  '1st.server.com' => 'first',
  '2ond.server.com' => 'second'
);

Imap is working fine but smtp isent working i have tried added 

$config['smtp_server'] = 'tls://%t';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p'; 

but i get error 

SMTP-error (-1)

The servers req that users login before sending mail. i have tried tls://%z still no dice.

Anyone know of a way to make it work?

**Comment by alecpl** [comment]
Shouldn't it be %h?

**Comment by morno** [comment]
Hello 

When i change it to %h i can send from first server but i get SMTP-error (220) on second.

**Comment by morno** [comment]
on the second server i get 

Jan  9 21:34:34 2ond postfix/smtpd[18546]: connect from 1st.server.com[iphere]
Jan  9 21:34:34 2ond postfix/smtpd[18546]: SSL_accept error from 1st.server.com[iphere]: 0
Jan  9 21:34:34 2ond postfix/smtpd[18546]: warning: TLS library problem: 18546:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1493:SSL alert number 48:
Jan  9 21:34:34 2ond postfix/smtpd[18546]: lost connection after STARTTLS from 1st.server.com[iphere]
Jan  9 21:34:34 2ond postfix/smtpd[18546]: disconnect from 1st.server.com[iphere]

So is roundcube sending connection in TLSv1 or someting? so now the roundcube server is connecting but the server is refuseing connection becouse of the TLS issue.

**Comment by alecpl** [comment]
Might depend on PHP version. You might need to use smtp_conn_options setting. Closing as not Roundcube issue.
