### ISSUE TITLE
Inbox deleted

### ISSUE THREAD

**Issue by betterworlddet** [roundcube/roundcubemail#6131]
The contents of my inbox has disappeared and new mail only sits in the inbox for half an hour before it disappears.

My Sent folder still has its contents but there is nothing in the Drafts or Deleted folders.

Can you help me retrieve the emails please? It's incredibly important. 
Thank you.

**Comment by thomascube** [comment]
I'm sorry but we can't help you with this. We don't host your e-mails and we're not responsible for the system you're using to access them. Please contact your internet hosting provider or IT responsible for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Please note that Roundcube is not a service but free software which your hosting provider installed on their servers.
