### ISSUE TITLE
Roundcube email sentence stack together

### ISSUE THREAD

**Issue by lzy90** [roundcube/roundcubemail#6133]
![problemss](https://user-images.githubusercontent.com/35323771/34810230-f9dfd1f4-f6d4-11e7-8ef1-ed73d5ade3bf.png)

any idea how to solve this issues? from ios

**Comment by alecpl** [comment]
We'd need more context. Message source, PHP/Roundcube version. Is this on message display or compose? Is this HTML or plain text?

**Comment by lzy90** [comment]
Roundcube Webmail 1.3.3,  received this email through ios outlook. this message in display. I try on Horde, or outlook the message is ok. but open in roundcube will cause that issues.

**Comment by alecpl** [comment]
Provide the sample message source, please.

**Comment by alecpl** [comment]
No feedback.
