### ISSUE TITLE
Postfix + sqlite: Roundcube locks sqlite database

### ISSUE THREAD

**Issue by RickD123** [roundcube/roundcubemail#6134]
Hi,

I am having an issue with Postfix, Sqlite and Roundcube. Essentially, when logging into Roundcube, Postfix reports an error at times given the sqlite DB is locked by Roundcube. Here is the Postfix error:

```
Jan 11 15:18:56 waldfest postfix/trivial-rewrite[18551]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='harbourviewmalta.com' AND active = '1'': database is locked?
Jan 11 15:18:56 waldfest postfix/trivial-rewrite[18551]: fatal: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL finalize failed for query 'SELECT goto FROM alias WHERE address='harbourviewmalta.com' AND active = '1'': database is locked?
Jan 11 15:50:50 waldfest postfix/trivial-rewrite[19779]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='greenbeast.com' AND active = '1'': database is locked?
Jan 11 15:50:50 waldfest postfix/trivial-rewrite[19779]: fatal: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL finalize failed for query 'SELECT goto FROM alias WHERE address='greenbeast.com' AND active = '1'': database is locked?
Jan 11 16:06:50 waldfest postfix/trivial-rewrite[20284]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='europapark.com' AND active = '1'': database is locked?
```

When looking at the modification time of the sqlite DB, Roundcube makes changes assumingely for writing session data. Relatedly, I was wondering: Is there a way to have a separate sqlite db for the session handling such that Roundcube does not touch (read: lock) the sqlite database used by Postfix?

I also tried to specify the file permissions in the sqlite connect string such that the access is read-only but that does not work. Likewhen, when taking away the write permissions from the sqlite db for the webserver user, the login via Roundcube fails.

Any hints?

Thank you.

Best regards
RickD

**Comment by alecpl** [comment]
Just use a separate database for Roundcube.

**Comment by 8751** [comment]
> 你好，
> 
> 我遇到了 Postfix、Sqlite 和 Roundcube 的问题。本质上，当登录 Roundcube 时，Postfix 有时会报告错误，因为 SQLite DB 被 Roundcube 锁定。这是后缀错误：
> 
> ```
> Jan 11 15:18:56 waldfest postfix/trivial-rewrite[18551]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='harbourviewmalta.com' AND active = '1'': database is locked?
> Jan 11 15:18:56 waldfest postfix/trivial-rewrite[18551]: fatal: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL finalize failed for query 'SELECT goto FROM alias WHERE address='harbourviewmalta.com' AND active = '1'': database is locked?
> Jan 11 15:50:50 waldfest postfix/trivial-rewrite[19779]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='greenbeast.com' AND active = '1'': database is locked?
> Jan 11 15:50:50 waldfest postfix/trivial-rewrite[19779]: fatal: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL finalize failed for query 'SELECT goto FROM alias WHERE address='greenbeast.com' AND active = '1'': database is locked?
> Jan 11 16:06:50 waldfest postfix/trivial-rewrite[20284]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='europapark.com' AND active = '1'': database is locked?
> ```
> 
> 在查看 sqlite DB 的修改时间时，Roundcube 会假设更改为写入会话数据。相关地，我想知道：有没有办法为会话处理提供一个单独的 sqlite 数据库，以便 Roundcube 不会接触（读取：锁定）Postfix 使用的 sqlite 数据库？
> 
> 我还尝试在 sqlite 连接字符串中指定文件权限，以便访问是只读的，但这不起作用。就像当从 web 服务器用户的 sqlite 数据库中删除写入权限时，通过 Roundcube 登录失败。
> 
> 任何提示？
> 
> 谢谢你。
> 
> 最好的问候 RickD

你好，我现在也想通过roundcube作为postfix的webmail，但是我不知道password插件里面怎么去连接sqlite数据库去修改密码。可以发给我一个模板么？

**Comment by 8751** [comment]
> Hi,
> 
> I am having an issue with Postfix, Sqlite and Roundcube. Essentially, when logging into Roundcube, Postfix reports an error at times given the sqlite DB is locked by Roundcube. Here is the Postfix error:
> 
> ```
> Jan 11 15:18:56 waldfest postfix/trivial-rewrite[18551]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='harbourviewmalta.com' AND active = '1'': database is locked?
> Jan 11 15:18:56 waldfest postfix/trivial-rewrite[18551]: fatal: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL finalize failed for query 'SELECT goto FROM alias WHERE address='harbourviewmalta.com' AND active = '1'': database is locked?
> Jan 11 15:50:50 waldfest postfix/trivial-rewrite[19779]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='greenbeast.com' AND active = '1'': database is locked?
> Jan 11 15:50:50 waldfest postfix/trivial-rewrite[19779]: fatal: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL finalize failed for query 'SELECT goto FROM alias WHERE address='greenbeast.com' AND active = '1'': database is locked?
> Jan 11 16:06:50 waldfest postfix/trivial-rewrite[20284]: warning: dict_sqlite_lookup: /etc/postfix/sqlite_virtual_alias_maps.cf: SQL step failed for query 'SELECT goto FROM alias WHERE address='europapark.com' AND active = '1'': database is locked?
> ```
> 
> When looking at the modification time of the sqlite DB, Roundcube makes changes assumingely for writing session data. Relatedly, I was wondering: Is there a way to have a separate sqlite db for the session handling such that Roundcube does not touch (read: lock) the sqlite database used by Postfix?
> 
> I also tried to specify the file permissions in the sqlite connect string such that the access is read-only but that does not work. Likewhen, when taking away the write permissions from the sqlite db for the webserver user, the login via Roundcube fails.
> 
> Any hints?
> 
> Thank you.
> 
> Best regards RickD

Hello, I also want to use roundcube as the postfix webmail, but I don't know how to connect to the sqlite database in the password plugin to change the password. Can you send me a template?

**Comment by alecpl** [comment]
This is not a support forum and do not comment in unrelated tickets, please.
