### ISSUE TITLE
Error: PHP Notice: Unknown: file created in the system's temporary directory

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#6135]
Hello!

release-1.3 (from Github),  PHP 7.2, Nginx.

What do such errors in Nginx's log mean?

    2018/01/12 15:24:03 [error] 3449#3449: *23848 FastCGI sent in stderr: "PHP message: PHP Notice:  Unknown: file created in the system's temporary directory in Unknown on line 0" while reading response header from upstream, client: 109.252.191.162, server: mydomain.tld, request: "POST /?_task=mail&_id=14086969965a58a8cda4de5&_uploadid=1515759838626&_from=compose&_action=upload HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "mydomain.tld", referrer: "https://mydomain.tld/?_task=mail&_action=compose&_id=14086969965a58a8cda4de5"

This was an authenticated user.

**Comment by alecpl** [comment]
Misconfigured temp_dir, I guess. Possibly the directory set in temp_dir (in Roundcube config) does not exist or access to it is restricted.

**Comment by quicktrick** [comment]
I only have

    $config['temp_dir'] = RCUBE_INSTALL_PATH . 'temp/';

in `defaults.inc.php`.  It's writable for Nginx and there are some `.thumb` files and `js_cache` directory with some files too.

The PHP Notice says that "file created in the system's temporary directory in Unknown on line 0". To be honest, I have no idea what that means.

**Comment by alecpl** [comment]
Right. It will be related to http://php.net/manual/pl/ini.core.php#ini.upload-tmp-dir

**Comment by quicktrick** [comment]
You are right, @alecpl, I've found and corrected it.  Thanks a lot!
