### ISSUE TITLE
Can't add or edit LDAP contacts

### ISSUE THREAD

**Issue by beta2k1** [roundcube/roundcubemail#6137]
I started with 1.3.2 then updated today to 1.3.4.  I've setup a domain specific config with the following

$rcmail_config['ldap_public']['public'] = array(
    'name'              => 'Public LDAP Addressbook',
    'hosts'             => array('localhost'),
    'port'              => 389,
    'writable'          => true,
    'ldap_version'      => 3,
    'user_specific'     => false,
    'LDAP_Object_Classes' => array("top","person","organizationalPerson","inetOrgPerson"),
    'LDAP_rdn'          => 'uid',
    'base_dn'           => 'ou=garfieldshvac.com,ou=addressbook,dc=garfieldshvac,dc=com',
    'bind_dn'           => 'cn=Manager,dc=garfieldshvac,dc=com',
    'bind_pass'         => '<pass>',
    'filter'            => '(objectClass=inetOrgPerson)',
    'name_field'        => 'cn',
    'email_field'       => 'mail',
    'surname_field'     => 'sn',
    'firstname_field'   => 'givenName',
    'sort'              => 'sn',
    'scope'             => 'list',
    'global_search'     => true,
    'fuzzy_search'      => true,

    'groups'            => array(
        'base_dn'         => 'ou=garfieldshvac.com,ou=addressbook,dc=garfieldshvac,dc=com',     // in this Howto, the same base_dn as for the contacts is used
        'filter'          => '(objectClass=groupOfNames)',
        'object_classes'  => array("top", "groupOfNames"),
        'search_fields' => array(
           'mail',
           'cn',
        ),
    ),
);

Using the Manager cn to eliminate possible permission issues.  

All the contacts I loaded into the directory show up fine but I can not edit or add new ones.  When I press "Save" after editing or adding a warning comes up "The form was not completely filled out"

**Comment by alecpl** [comment]
You mean it worked with 1.3.2 and now stopped? Enable ldap_debug and check the log for hints.

**Comment by alecpl** [comment]
No feedback.
