### ISSUE TITLE
Upgrade from 1.2.5 to 1.3.4 failed "Error in DDL upgrade"

### ISSUE THREAD

**Issue by dynek** [roundcube/roundcubemail#6139]
Hello,

I just upgraded from 1.2.5 to 1.3.4 and the installer was apparently not able to create table cache (see below).
I can probably fix it but, is there a reason for that and a way to resume the installation in case other db operations should have been done?

Thank you!

```
Upgrading from 1.2.5. Do you want to continue? (y/N)
Copying files to target location..../
[..]
done.

JavaScript dependencies installation skipped...
Running update script at target...
NOTICE: Obsolete config options:
(You still have some obsolete or inexistent properties set. This isn't a problem but should be noticed)
- 'preview_pane'

Do you want me to fix your local configuration? (y/N)
y
. backing up the current config file(s)...
. writing /var/www/webmail/htdocs/config/config.inc.php...
Done.
Your configuration files are now up-to-date!
Executing database schema update.
Updating database schema (2016081200)... [OK]
Updating database schema (2016100900)... [OK]
Error 500: Error in DDL upgrade 2016112200: [1005] Can't create table 'roundcubemail.cache' (errno: 150)
Updating database schema (2016112200)... [FAILED]
All done.
```

**Comment by dynek** [comment]
There's a foreign key between cache and users table on user_id. Users table is MyISAM and creation of cache table tries to use engine InnoDB - they can't be mixed.
I changed the engine to MyISAM and I was able to create the cache tables.

Is that enough or the script would maybe have done some other stuff?

**Comment by alecpl** [comment]
We do not support MyISAM. All tables should be InnoDB.

**Comment by dynek** [comment]
Noted - but as far as I remember I did not create these tables myself so they came as MyISAM in a version prior to 1.2.5 - did I miss a changelog saying tables should be "updated" to InnoDB?

Anyway I hope I'm fine with the update.

**Comment by alecpl** [comment]
InnoDB is used since 0.2-beta (sic!).

**Comment by dynek** [comment]
Then I don't remember why and how but it must be me :-) Thanks
