### ISSUE TITLE
DKIM Signature

### ISSUE THREAD

**Issue by ebroch** [roundcube/roundcubemail#6140]
I have a qmail server that adds DKIM signature to outgoing emails. When sending mail from this server with Roundcube in plain text format to port25.com, gmail, or yahoo the DKIM signature fails; however, if I send the same email in html format with Roundcube port25.com, gmail, and yahoo verify and pass the DKIM signature. If I send the same email in Thunderbird and Outlook DKIM passes. Is there something about header formatting in Roundcube plain text that can be changed to accommodate? Or is this a bug?

**Comment by alecpl** [comment]
Could you just compare working and non-working message headers to see where's the difference? I don't see how it could be a Roundcube issue.

**Comment by alecpl** [comment]
No feedback.
