### ISSUE TITLE
Request for info:  skins larry old vs new larry

### ISSUE THREAD

**Issue by supersophie** [roundcube/roundcubemail#6141]
Hi,

My RC 0.95 installation has a lovely and pleasing different larry skin compared to release 1.33.

The old skin had a texture to it and the new does not.

I have the old larry skin files.  I tried copying the images from the old larry install to new larry install in roundcube/skins/larry/images/ . But I saw no change.  

Which file(s) should I copy?

**Comment by alecpl** [comment]
That's not only about images. There were changes in css too. And old images will lack some icons. Sorry, we do not support what you're doing.

**Comment by supersophie** [comment]
I was not asking for support. Just advice.
