### ISSUE TITLE
[bug] alerts and messsages to user are not enought visibles

### ISSUE THREAD

**Issue by mckaygerhard** [roundcube/roundcubemail#6142]
all the larry skin theme messages are not well made visible to users.. 

the response in classic skin its in the middle of the screen so user "must" have to see it.. 

in larrry are at the corner so if user are distracted dont see it!

please how can i configure this or move it to more in the center, i can made by my own the pull

PLEASE FIRTS HARDCODED AND LATER A CONFIG OPTION

**Comment by thomascube** [comment]
The Larry theme has been around for years and a new responsive theme is on the way. We'll therefore not apply fundamental changes to the current skin.

You can easily create your own skin by extending the larry theme and just override certain CSS properties. See [Extending skins](https://github.com/roundcube/roundcubemail/wiki/Skins#extending-skins) in our wiki.

**Comment by mckaygerhard** [comment]
i already read the "extending skins" wiki, but i dont see exactly where are the alert/message part of the css.. also i cannot upgrade due we must support older browser on oour country.. sorry but not all countryes have "lasted fashion" browsers..

could you provide me some hints where i must see iin the css to put in center the messages/alerts of the skin? i'm not expert on css in fact i know very little, but i read and learning..

**Comment by alecpl** [comment]
In Larry it will be #messagestack element.

**Comment by mckaygerhard** [comment]
hi! @alecpl thanks for the hint , but why closing?, next roundcube elastick should be have a optuion like this!
