### ISSUE TITLE
managesieve turning a long regex into multi-line text literal

### ISSUE THREAD

**Issue by ss-17** [roundcube/roundcubemail#6143]
Hi.

The file _plugins/managesieve/lib/Roundcube/rcube_sieve_script.php_ has this section:

```
// multi-line string
if (preg_match('/[\r\n\0]/', $str) || strlen($str) > 1024) {
    return sprintf("text:\n%s\n.\n", self::escape_multiline_string($str));
}
// quoted-string
else {
    return '"' . addcslashes($str, '\\"') . '"';
}
```

which is converting my long regex to:

```
:regex "from" text:
"my long regex"
.
```

which should actually be saved as:

`:regex "from" "my long regex"`

in order to get evaluated correctly. Why the 1024 limit?

**Comment by philipwhiuk** [comment]
Probably an interpretation of:
```
  quoted                = DQUOTE *1024QUOTED-CHAR DQUOTE
                            ;; limited to 1024 octets between the <">s
```
in https://tools.ietf.org/html/draft-martin-managesieve-12

**Comment by ss-17** [comment]
Ahh ok. But does that mean we cannot have a regex longer that 1024 chars in sieve?

**Comment by alecpl** [comment]
I don't remember. You might be right that it comes from managesieve rfc. That would mean the limit is irrelevant and should be removed.

**Comment by ss-17** [comment]
As a quick workaround, I have replaced the line:

`return $output;`

in the script with:

```
if (preg_match_all('/:regex.*?(text:\r?\n(.+?)\r?\n\.\r?\n)\)/is', $output, $a)) {
	array_walk($a[2], function(&$b) {$b='"'.addcslashes($b, '\\"').'"';});
	return str_replace($a[1], $a[2], $output);        	
}
else {
	return $output;
}
```

**Comment by alecpl** [comment]
Fixed.
