### ISSUE TITLE
Signature being mistaken as spam

### ISSUE THREAD

**Issue by loopeeloo** [roundcube/roundcubemail#6146]
Not sure if this is the correct place to leave this comment. A client of mine has been adamant some of his emails aren't going through. An IT friend of his suggested it could be the logo etc on the signature which is being seen as spam so not getting through to the intended recipient.

**Comment by alecpl** [comment]
I don't see an issue here. Could you specify what do you expect from Roundcube developers?

**Comment by loopeeloo** [comment]
More of making Roundcube developers aware.

**Comment by thomascube** [comment]
This is nothing that could be resolved or improved by the Roundcube software. Please talk to your email hosting provider about SPF and DKIM settings. Or simply remove the image from your signature.
