### ISSUE TITLE
Enigma: openpgp.js error generating key in Safari (Roundcube 1.3.4)

### ISSUE THREAD

**Issue by couteau** [roundcube/roundcubemail#6149]
I'm using Roundcube 1.3.4 with the enigma plugin enabled. I cannot generate a new keypair in Safari. It works fine out of the box in FireFox.  In Safari's javascript console, the error is:

TypeError: Member RsaHashedKeyGenParams.hash is required and must be an instance of any -- openpgp.min.js:4959

It looks like an issue in the upstream openpgp.js library interacting with Safari's current implementation of the WebCrypto api.  The code where the error originates is as follows:

                        return window.crypto && window.crypto.webkitSubtle ? (k = {
                            name: "RSA-OAEP",
                            modulusLength: a,
                            publicExponent: n.subarray(0, 3)
                        }, l = g.generateKey(k, !0, ["encrypt", "decrypt"])) : (k = {
                            name: "RSASSA-PKCS1-v1_5",
                            modulusLength: a,
                            publicExponent: n.subarray(0, 3),
                            hash: {
                                name: "SHA-1"
                            }
                        }, l = g.generateKey(k, !0, ["sign", "verify"]) 
        
If I make sure the hash parameter is defined in the first set of params for the RSA-OAEP call (by adding, e.g., 'hash: {name: "SHA-1" }' to the first set of params), it works. 

It looks like either Enigma either shouldn't advertise Safari compatibility or it should distribute a patched version of openpgp.js along the lines of my tweak or it should be upgraded to a newer version of openpgp.js that works with current versions of Safari.

**Comment by alecpl** [comment]
Fixed by upgrade to OpenPGP 2.6.2.
