### ISSUE TITLE
IMAP Error: Login failed for user@ from <ip>. Empty host

### ISSUE THREAD

**Issue by schneidr** [roundcube/roundcubemail#6151]
Since upgrading RoundCube to version 1.3.4 I can't log in anymore. The error message I get in the log file:

> [30-Jan-2018 11:09:33 +0100]: <j5r1bo7m> IMAP Error: Login failed for user@ from 10.2.3.4. Empty host in /var/www/htdocs/webmail/program/lib/Roundcube/rcube_imap.php on line 196 (POST /webmail/?_task=login&_action=login)

Variables from $config.inc.php related to the IMAP login:

    $config['db_dsnw'] = 'mysql://dbuser:dbpassword@rdbms.example.com/dbname';
    $config['default_host'] = 'ssl://imap.example.com';
    $config['default_port'] = 993;
    $config['username_domain'] = 'example.com';
    // $config['username_domain_forced'] = true; // tried that, didn't make a difference
    $config['mail_domain'] = 'example.com';

I did not change anything after copying the config.inc.php to the new roundcube directory (old version was 1.2.? AFAIR).

**Comment by alecpl** [comment]
Maybe the config file or dir is not readable by the web server.

**Comment by schneidr** [comment]
RoundCube is using `$config['db_dsnw']`, `$config['default_host']`, etc. correctly. The MySQL connection works and it connects to the correct IMAP server. So I guess it can read the config file just fine.

As far as I can tell the host part of the login (the IMAP server expects the whole email address as username) is dropped.

**Comment by alecpl** [comment]
No, it connects to no imap server. "Empty host" means that the imap server hostname (default_host) is not set. Maybe you have some plugin that modifies the hostname or there's something wrong with the config.

**Comment by schneidr** [comment]
I have no plugins loaded.

    $config['plugins'] = array();

I can definitely confirm that the `config.inc.php` is being loaded, changes to `$config['product_name']` and `$config['support_url']` are reflected on the login page.

You are right that no host is set in `rcube_imap::connect()`. I added `var_dump($config)` in that function, this is the result:

    array(5) { 
        ["host"]=> NULL 
        ["user"]=> string(4) "foo@" 
        ["password"]=> string(3) "bar" 
        ["port"]=> int(993) 
        ["ssl"]=> string(3) "ssl" 
    }

Note that I entered `foo@example.com` in the login field, not `foo`. At some point the value from `$config['default_host']` gets lost, along with the domain part in the username.

I don't see anything generally wrong with the PHP file:

    $ php -l config.inc.php
    No syntax errors detected in config.inc.php

There is no second `$config['default_host'] =` declaration in that file.

**Comment by alecpl** [comment]
I have no ideas. Try to do some debug login() method in /program/include/rcmail.php.

**Comment by alecpl** [comment]
No feedback.

**Comment by janpekar** [comment]
I you have also  PHP Warning:  idn_to_ascii() expects at most 2 parameters, 3 given in rcube_utils.php on line 890, check your PHP version (see requirements in INSTALL).

**Comment by 11Vladimir** [comment]
RoundCube to version 1.4.1 I can't IMAP Test
IMAP connect:  NOT OK(Login failed for email1@task1.com against task1.com from xx.xx.xx.xx. Could not connect to ssl://task1.com:993: Unknown reason)

But SMTP SMTP send:  OK

**Comment by Shandeika** [comment]
> RoundCube to version 1.4.1 I can't IMAP Test IMAP connect: NOT OK(Login failed for [email1@task1.com](mailto:email1@task1.com) against task1.com from xx.xx.xx.xx. Could not connect to ssl://task1.com:993: Unknown reason)
> 
> But SMTP SMTP send: OK

Same problem. I can't understand why, I've already tried connecting from other clients - everything works. I tried ssl, tls and changing ports, nothing changes.
