### ISSUE TITLE
Make HTTP links clickable in the editor

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6158]
I have some emails, that have links in the body, but the editor doesn't show me the clickable option to click on them.
I think this used to work in the past.
Attached there's the raw message.
[roundcube http links.txt](https://github.com/roundcube/roundcubemail/files/1693032/roundcube.http.links.txt)

**Comment by alecpl** [comment]
What version? You talk about HTML editor in mail compose?

**Comment by dddns** [comment]
Alec,
1.3.4 and it's visualizing an email with html editor

**Comment by alecpl** [comment]
What I wanted to clarify is that it's either about composing (replying to) an email or (pre)viewing an email.

**Comment by dddns** [comment]
Alec,

I may be making some confusion.
When composing the email, for ex in msoutlook, i have links that are hightlithed because i make them like that, and other don't, so that's the thing, and not a bug!

attach'd a raw message, where only the "link1" if highlithed.

**Comment by alecpl** [comment]
I still don't get what do you expect and where. So, now if I open your email and use "Edit as new" the message will be opened for composing in HTML editor. And there you expect the first link to be clickable with Left-click as normal links, right? Or something else?

**Comment by alecpl** [comment]
No feedback.
