### ISSUE TITLE
send test mail fails

### ISSUE THREAD

**Issue by necktwi** [roundcube/roundcubemail#6159]
There is a typo in labels for sender address, recipient address and password in installer send test mail.

<img width="372" alt="screen shot 2018-02-05 at 1 18 50 am" src="https://user-images.githubusercontent.com/2793912/35781675-20eef0b2-0a13-11e8-925d-e413751ba439.png">

double sender and recipient fields!

**Comment by alecpl** [comment]
Duplicate of #6166.
