### ISSUE TITLE
Enigma: Possible UI problems

### ISSUE THREAD

**Issue by taalas** [roundcube/roundcubemail#6162]
I am not sure if these problems are related to the theme we use or the localization but there seem to be 2 problems with the current enigma menus:

When exporting PGP keys, the dialog opens with the upper part being to narrow, thus rendering the text unreadable (might be connected to the buttons being displayed in 2 rows with localized texts)
![export](https://user-images.githubusercontent.com/6582821/35812655-e7ec84f8-0a91-11e8-8508-9a29d89367c6.png)

When composing mail and opening the Encryption Menu, the text is displayed as white on white:
![compose](https://user-images.githubusercontent.com/6582821/35812680-fa226908-0a91-11e8-8f69-f93ab1a2f70f.png)

Both problems are easily fixable by overriding the relevant CSS classes, just wanted to check if this is a general problem or if it isn't.

**Comment by alecpl** [comment]
Works for me in Larry skin on git-master.
