### ISSUE TITLE
Keep getting CONNECTION ERROR (failed to connect to server) when using ROUNDCUBE

### ISSUE THREAD

**Issue by austinfacility** [roundcube/roundcubemail#6163]
May someone tell me what I need to do to fix this reoccurring problem I have. When I am on ROUNDCUBE - I get a message every minute it seems to have logged me off automatically. the message reads -- CONNECTION ERROR (failed to reach server) Let's say emailing is as tech savy as I get. So may someone explain to me in JOE BLOW terms what I need to do? THANK YOU!!!!

**Comment by alecpl** [comment]
Looks like some generic issue. We can't help you without any info. Ask on mailing list or forum.
