### ISSUE TITLE
New Hook for set_flag() in rcube_imap.php

### ISSUE THREAD

**Issue by vsaranov** [roundcube/roundcubemail#6167]
Please add Plugin Hooks call when marking messages. The plugin needs to be able to get the message headers.

**Comment by alecpl** [comment]
What is the use-case?

**Comment by vsaranov** [comment]
Integration with CRM. Replace embedded Email client CRM.

**Comment by alecpl** [comment]
That does not really explain what do you want to do in the hook. I'm not sure we should add more such low-level hooks.

**Comment by alecpl** [comment]
Wontfix.
