### ISSUE TITLE
Folder properties view shows wrong parent folder

### ISSUE THREAD

**Issue by jugmac00** [roundcube/roundcubemail#6168]
Roundcube Webmail 1.1.10 + classic theme

reproduction:
- goto settings
- goto folders
- select a folder at top level (other than inbox, sent..)
- on the "folder properties" view "INBOX" is now preselected as parent although it should be "-----"

This happens only for one of my colleagues - I run the same Roundcube / IMAP setup - for me, the parent is shown correctly.

workaround:
When renaming a folder - double check the selected parent folder and change it to the correct one (obviously, this is forgotten more often than not and I have to ssh into the mail server to fix the problem - as this would be a second problem, once a folder is appended to INBOX, it is no longer shown at the folder admin view - only on the "normal" folder/emails view).

As a side note - we use dots as separators between folders - not dot involved in above problem, though.

**Comment by alecpl** [comment]
Maybe INBOX. is your personal namespace? I'd like to see imap_debug log for the faulty user, starting from the logon and ending on the folder edit.

**Comment by alecpl** [comment]
Also, 1.1.10 is not supported, so you should check with 1.3.

**Comment by jugmac00** [comment]
Hi Alec, thank you for the quick response. I will be back at work only next week. I will get back to you then with the required infos. Updating to 1.3 is currently not possible due to plugin incompatibilities.

**Comment by jugmac00** [comment]
Hi Alec, took some time, but here are the logs
- going to settings
- going to folder settings
- selecting one folder (wrong parent got selected)

***Log excerpt***
[log.txt](https://github.com/roundcube/roundcubemail/files/1743588/log.txt)

I compared my colleagues logs with me doing the same actions, but me getting the correct parent => zero differences except the user name and so on.

**Comment by alecpl** [comment]
That's not the log I was talking about. imap_debug is a Roundcube config option and it creates a debug log in Roundcube's log directory.

**Comment by jugmac00** [comment]
Thanks - found the info how to activate it at
https://github.com/roundcube/roundcubemail/wiki/Howto-Report-Issues

Colleague is already at home - gonna get back to you next week then.

**Comment by alecpl** [comment]
I'm waiting for the debug information. Will close the ticket in a few days if I get no feedback.

**Comment by jugmac00** [comment]
Alex, due to work reasons I am not able to deliver the info this week. I try to get the logs by next week.

I am sorry, that you have to waste your time to send out reminder for overdue tickets.

**Comment by jugmac00** [comment]
Alex, I am still trying to get a meeting with the colleague in order to gather the required logs.

**Comment by alecpl** [comment]
Closing. We'll reopen when you have some feedback.

**Comment by jugmac00** [comment]
Thanks for the offer - it seems there is no reasonable chance to get a meeting with my colleague. Thanks for the patience and sorry for the fuss.
