### ISSUE TITLE
PHP Warning: exif_read_data(...): Illegal IFD size

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6169]
Hi,

I have several errors in the logs, with the information below.
I have RC 1.3.4.
It's running in PHP 7.1.13

===
Feb  9 10:52:03 fastweb roundcube: PHP Warning:  exif_read_data(2056e7578723a659a35fbc5ee171b0e8.tmp): Illegal IFD size in /home/hosting/dhosting/webmail/program/lib/Roundcube/rcube_image.php on line 261
Feb  9 10:52:03 fastweb roundcube: PHP Stack trace:
Feb  9 10:52:03 fastweb roundcube: PHP   1. {main}() /home/hosting/dhosting/webmail/index.php:0
Feb  9 10:52:03 fastweb roundcube: PHP   2. include_once() /home/hosting/dhosting/webmail/index.php:303
Feb  9 10:52:03 fastweb roundcube: PHP   3. rcube_image->resize() /home/hosting/dhosting/webmail/program/steps/mail/get.inc:88
Feb  9 10:52:03 fastweb roundcube: PHP   4. exif_read_data() /home/hosting/dhosting/webmail/program/lib/Roundcube/rcube_image.php:261

**Comment by alecpl** [comment]
Fixed. This is a PHP bug, all we could do is to ignore the warning using @-operator.

**Comment by dddns** [comment]
Thanks Alec!
