### ISSUE TITLE
Unable to disable filter in Managesieve

### ISSUE THREAD

**Issue by TJ101** [roundcube/roundcubemail#6170]
You can enable but not disable a filter.

I am able to disable a filter using a  previous version of Roundcube. 

This issue  seems to be a coding problem as the permissions seem fine and I am able to enable a disabled filter, just not the other way around.

I am using the latest git version, my previous version was 8.7.

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
