### ISSUE TITLE
windows (ntfs) path issue

### ISSUE THREAD

**Issue by bv217** [roundcube/roundcubemail#6171]
When I try to enter the enigma menu, an error appears. The log contains the following records:
PHP Error: Enigma plugin: The 'homedir' "C:\Websites\roundcube/plugins/enigma/home/<email>" is not enterable by the current user. Please check the permissions on your homedir and make sure the current user can both enter and write to the directory. in C:\Websites\roundcube\plugins\enigma\lib\enigma_engine.php on line 91 (POST /?_task=settings&_action=plugin.enigmakeys)
This looks like a problem with the rights, but the user folder itself is created successfully. In this case, the path to it in the logs looks strange, a mixture of unix and windows.

**Comment by alecpl** [comment]
Crypt_GPG does not support Windows. Here's what it does:
```
if (!is_dir($this->_homedir)) {
    if (@mkdir($this->_homedir, 0777, true)) {
        chmod($this->_homedir, 0700);
    }
}        
if (!is_executable($this->_homedir)) {
    /// here comes the error you've got
}
```
If you want to make it working with Windows, you're on your own.
