### ISSUE TITLE
enigma: sending encrypted message failed

### ISSUE THREAD

**Issue by dthpulse** [roundcube/roundcubemail#6174]
roundcube version 1.3.4

problem: while trying to send the encrypted message to user1@mailserver.com getting the error:

> Key not found! Encryption failed. Public key not found for user1@mailserver.com

Seems that enigma is looking for public key of 'user1' which is user I'm trying to send an encrypted email. 
I did check my private and secret keys exists on default location where enigma did generate them. When I try to send encrypted email to myself then it works.
There is no error message in log file.

**Comment by alecpl** [comment]
What is an email address of the sender? Are you sure user1@mailserver.com public key is in the keyring of the current user? Enable enigma_debug an provide the log.

**Comment by dthpulse** [comment]
Right from enigma log I could see, that user1 public key wasn't in my keyring. After adding it, encrypted message was sent.
thx
