### ISSUE TITLE
mail_mime old version causes PHP 7.2 deprecation warnings

### ISSUE THREAD

**Issue by hannob** [roundcube/roundcubemail#6179]
I got warnings like this in my logs when I tried to use latest roundcube with PHP 7.2:

[14-Feb-2018 18:24:00 Europe/Berlin] PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in [path]/vendor/pear/mail_mime/Mail/mimePart.php on line 625

This code is part of the mail_mime pear package, which is included via composer. Their Changelog mentions PHP 7.2 compatibility fixes in version 1.10.2:
https://pear.php.net/package/Mail_Mime/download/

In roundcube mail_mime is at version 1.10.0. I assume an update to the latest upstream version will fix these warnings.

**Comment by alecpl** [comment]
I'm aware of that. When we create a new release it should update automatically as we already change proper version specified in composer config.

You can just run `composer update`.

**Comment by hannob** [comment]
I'm actually not sure if this is true.

In the current git version of the composer config, as seen here
https://github.com/roundcube/roundcubemail/blob/master/composer.json-dist
there's the line:
        "pear/mail_mime": "~1.10.0",

This indicates to me that this is pinned to this specific version (?).

**Comment by alecpl** [comment]
No, it is pinned to most recent version in 1.10 branch, i.e. 1.10.X
