### ISSUE TITLE
Docker ENV changes still require --link

### ISSUE THREAD

**Issue by sumdog** [roundcube/roundcubemail#6181]
I noticed the Docker image for Roundcubemail has been updated: https://hub.docker.com/r/roundcube/roundcubemail/

It now takes these standard env variables:

    ROUNDCUBEMAIL_DB_{HOST,USER,PASSWORD,TYPE,NAME}

I switched over to these new variable at the same time that I switched from the default bridge network to a user defined network (therefore no longer needing container linking). I couldn't get the round cube container to connect my the mysql container and my debugging eventually led me to this block of code in the `/docker-entry-point.sh`:

```
  elif [ ! -z "${!MYSQL_ENV_MYSQL_*}" ]; then
    : "${ROUNDCUBEMAIL_DB_TYPE:=mysql}"
    : "${ROUNDCUBEMAIL_DB_HOST:=mysql}"
    : "${ROUNDCUBEMAIL_DB_USER:=${MYSQL_ENV_MYSQL_USER:-root}}"
    if [ "$ROUNDCUBEMAIL_DB_USER" = 'root' ]; then
      : "${ROUNDCUBEMAIL_DB_PASSWORD:=${MYSQL_ENV_MYSQL_ROOT_PASSWORD}}"
    else
      : "${ROUNDCUBEMAIL_DB_PASSWORD:=${MYSQL_ENV_MYSQL_PASSWORD}}"
    fi
    : "${ROUNDCUBEMAIL_DB_NAME:=${MYSQL_ENV_MYSQL_DATABASE:-roundcubemail}}"
    : "${ROUNDCUBEMAIL_DSNW:=${ROUNDCUBEMAIL_DB_TYPE}://${ROUNDCUBEMAIL_DB_USER}:${ROUNDCUBEMAIL_DB_PASSWORD}@${ROUNDCUBEMAIL_DB_HOST}/${ROUNDCUBEMAIL_DB_NAME}}"

    /wait-for-it.sh ${ROUNDCUBEMAIL_DB_HOST}:3306 -t 30
```
Because of the order of the if statements, if there are no `MYSQL_ENV_MYSQL_*` variables present, it won't go through pulling in the DB variables. Since I removed container links, these were gone. Within my configuration I just added a dummy  `MYSQL_ENV_MYSQL_1=true`, but I feel like the order of these checks should be changes; that if `ROUNDCUBE_DB_TYPE` is present, it would set these variables no matter what (especially since `--link` is depreciated as is using the default bridge network).

**Comment by thomascube** [comment]
Probably related to #6147. Although that ticket is flagged as fixed, the published docker images have not yet been updated.

**Comment by sumdog** [comment]
Ah yes @thomascube. That's the same issue. I did a few searches, but forgot to include closed issues. This can be closed.
