### ISSUE TITLE
OAUTH

### ISSUE THREAD

**Issue by fleShpaiNt** [roundcube/roundcubemail#6182]
Anyone aware of an OAUTH solution for RoundCube?  (Looks like there is already a plugin for RoundCube, but Kolab doesn't support OAUTH) :/

**Comment by alecpl** [comment]
Could you describe exactly what do you mean?

**Comment by fleShpaiNt** [comment]
https://plugins.roundcube.net/search/?q=oauth  might be the solution I'm looking for
