### ISSUE TITLE
feature request: ability to switch off popup notification

### ISSUE THREAD

**Issue by lutel** [roundcube/roundcubemail#6183]
With very frequent checking on new email arrival (~2s), the notification window popup is very annoying and there is no option to turn it off.

**Comment by alecpl** [comment]
Wontfix. Setting the interval so short does not sound reasonable to me.

**Comment by lutel** [comment]
There is no other way to check for email without delays, even setting to 10-20s and getting popup notification each time email is check is annoying to users. I don't understand why you are refusing to add such an option that would make actual improvement on UI.
