### ISSUE TITLE
SMTP Config Does not Work

### ISSUE THREAD

**Issue by stone212** [roundcube/roundcubemail#6188]
Using Debian 9 with PHP5, openssl installed, LetsEncrypt cert, and apache2.  I have deleted and re-created the config file many times.  postfix handles SMTP tls security set to "may" (ie - STARTTLS) and works fine with Thunderbird.

SSL/TLS certificate is okay and viewable with:

> openssl s_client -connect mail.myserver.io:587 -starttls smtp

I navigate to /install and enter the configuration options.  Then we get to Step 3 "test" page.

IMAP works fine (and it uses the same certificate!)

`SMTP gives this error:SMTP send:  NOT OK(Connection failed: Failed to connect socket: fsockopen(): unable to connect to ssl://mail.myserver.com:587 (Unknown error))
`

When I enter "tls://" into the first configuration page, the test page still tests "ssl://" and when I enter port "25" it still tess "587".  I manually edit config.inc.php to use the tls:// prefix and the 25 port and still the test page tests ssl and 587.

So this issue has two parts:

1.  What is preventing me from using tls and 25?

2. Why doesn't ssl:// and 587 work?  It works fine for IMAP.

What should I test?

**Comment by alecpl** [comment]
I can't confirm the Installer issue. After changing the config in "2. Create config" you have to update the config.inc.php file. Then "3. Test config" displays and uses correct information from the config file.

As for the connection issue. Maybe you need to use smtp_conn_options?

**Comment by alecpl** [comment]
No feedback.

**Comment by E-NETWORKASSOCIATES** [comment]
Same issue on  Ubuntu even after update to 3.16

**Comment by HamzaElkina** [comment]
I had the same issue

I just try to change the port from 587 to 465
