### ISSUE TITLE
Viewing email says 500 Server Error after installing 1.3.4

### ISSUE THREAD

**Issue by Kallb123** [roundcube/roundcubemail#6189]
After installing 1.3.4, opening an email in the web interface gives a 500 server error. The emails work via imap, but not webmail.

I rolled back to 1.3.0 and everything works again. Updated to 1.3.4 once more and get 500 server error.

Not sure what steps I can take to debug this, I'll have to remain on 1.3.0 until a fix is out.

**Comment by alecpl** [comment]
Check the error log. Error 500 is always logged.

**Comment by Kallb123** [comment]
@alecpl unfortunately this is installed within cPanel and the error log there is empty. There is also nothing relevant in error_log or logs/errors within roundcube.

**Comment by alecpl** [comment]
I'll not able to help you without an error message. Check syslog or http server log.

**Comment by alecpl** [comment]
No feedback.

**Comment by johnearnshaw** [comment]
I had a similar problem with error 500 immediately after attempting to log in. Nothing recorded in apache error log.

However, syslog reports an error loading mcrypt module when running php 7.2

I rolled back the server to php 7.1 and roundcube works fine. Apparently mcrypt module is not yet supported in php 7.2

Maybe this helps?
