### ISSUE TITLE
Plugin: Password, Disallow non-ascii chars in password change

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6193]
Hi,

I'd like to disallow the usage of non-ascii chars in the password change.
This because of some users are inserting password's as something like:

Bámkd#69;d

And what's recorded in the databse is just "B".
if the usage of this kind of chars is to be allowed, maybe have the possibility to define the charset to the database (utf8 in my case), would it be possible?

**Comment by alecpl** [comment]
If your password database does not accept UTF8 you should probably set password_charset option (in main config) to something different.

**Comment by dddns** [comment]
Oh,
My error Alec!
It was in latin1 (iso-8859-1)
Changed to UTF8, perfect!

Sorry for the noise.
