### ISSUE TITLE
the UTF character in the HTML comment causes bad display of the content

### ISSUE THREAD

**Issue by adamszen** [roundcube/roundcubemail#6194]
If in the HTML comment before the `<head>` section there is a character in UTF - the email content is displayed incorrectly.

The problem has been around for a long time (currently tested on the Rouncdube version 1.3.3), noticed when receiving some e-mails from Allegro.

Look, this mail: 

![2018-02-23_21-03-30-81730](https://user-images.githubusercontent.com/36774997/36614568-73becaf0-18dd-11e8-9ea6-d82e86a213d9.png)

Looks OK:

![2018-02-23_21-04-34-86185](https://user-images.githubusercontent.com/36774997/36614598-86b5c834-18dd-11e8-91a4-6f9f23aaf862.png)

But if i move html comment above `<head>` section (allegro sends hundreds of thousands of emails in this way!):

![2018-02-23_21-08-27-82322](https://user-images.githubusercontent.com/36774997/36614657-ac87d570-18dd-11e8-9db7-b96c214a6e68.png)

The email display is incorrect:

![2018-02-23_21-28-39-49220](https://user-images.githubusercontent.com/36774997/36615429-85e64d18-18e0-11e8-99da-fa7ae938cb02.png)

If i switch showing in text mode, everything is OK:

![2018-02-23_21-25-43-01095](https://user-images.githubusercontent.com/36774997/36615328-15bcd76e-18e0-11e8-8aa4-fd26023460ee.png)

PHP 5.6, PHP 7.0, RC 1.2 and 1.3.3 - the effect is the same.

**Comment by philipwhiuk** [comment]
HTML comments before `<html>` is invalid as it means the document is not well formed.

**Comment by adamszen** [comment]
You probably are right, but a few other e-mail programs deal with this without any problem. I reported this problem to allegro but i do not know if they will react and i have hundreds of customers who complain about incorrect display of e-mails in roundcube :(

**Comment by alecpl** [comment]
I'm unable to reproduce. Could you provide the sample message source?

**Comment by adamszen** [comment]
Of course, please:

[http://szyna.civ.pl/mail.txt](url)

**Comment by alecpl** [comment]
Still works for me.

**Comment by adamszen** [comment]
@alecpl what PHP version You use? This bug is from very old version roundcube as i remember. 

I use PHP 7.0:

> PHP 7.0.27 (cgi-fcgi) (built: Jan  8 2018 17:22:22)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27, Copyright (c) 1999-2017, by Zend Technologies

**Comment by adamszen** [comment]
Some other tests, HTML comment before <html>:

![2018-02-24_14-07-33-18730](https://user-images.githubusercontent.com/36774997/36630770-181a3650-196c-11e8-8947-9dfed6be8543.png)

Source of frame (chrome):

![2018-02-24_14-09-12-99010](https://user-images.githubusercontent.com/36774997/36630777-444b8b3e-196c-11e8-8c8b-5acb8bfa2ea2.png)

HTML comment in middle of messages:

![2018-02-24_14-10-06-89029](https://user-images.githubusercontent.com/36774997/36630786-6250c0fe-196c-11e8-8a22-7fc3493586fa.png)

And source in Chrome:

![2018-02-24_14-10-31-02846](https://user-images.githubusercontent.com/36774997/36630789-72fc1fe8-196c-11e8-9843-b115b4285e6e.png)

All looks good. Headers (request and response) are the same in both cases.

**Comment by adamszen** [comment]
I test with other (a little newer all libraries PHP) server and... all work's good! So, this must be bug with some old libraries :)

**Comment by adamszen** [comment]
Problem solved! Finally - new library libxml2 fix problem :-)
