### ISSUE TITLE
managesieve data-hidden conflict with Elastic

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6195]
in managesieve plugin the `data-hidden` attribute added to textareas in 550e2fc6aab6d2d0e5dce8ed4d1c8e5c93d164a6 conflicts with [ui.js#L271](https://github.com/roundcube/elastic/blob/master/ui.js#L271) causing JS error `$(...).data(...).split is not a function`

**Comment by alecpl** [comment]
Fixed in Elastic.
