### ISSUE TITLE
Add a hook to send errors to an external error tracking tool

### ISSUE THREAD

**Issue by AllanKlaus** [roundcube/roundcubemail#6199]
I'm working with roundcube and I felt the need of a hook to send a log to my error tracking tool when rouncube handles an exception. 

So I can monitor my application with this tool.

**Comment by thomascube** [comment]
We already have syslog output in Roundcube. Isn't that sufficient to connect external monitoring (e.g. via logstash)?

**Comment by alecpl** [comment]
Added 'raise_error' hook.
