### ISSUE TITLE
mysql Foreign key constraint is incorrectly formed in 2018021600 update

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6200]
running MariaDB 10.1 trying to apply the latest mysql update file generates error 'Foreign key constraint is incorrectly formed'.

Changing the line `` `user_id` int(10) NOT NULL,`` to `` `user_id` int(10) UNSIGNED NOT NULL,`` solves it.

**Comment by alecpl** [comment]
Fixed.
