### ISSUE TITLE
better CSP support

### ISSUE THREAD

**Issue by blahmutz** [roundcube/roundcubemail#6202]
I am running roundcube with nginx. I use the following csp headers:

`add_header Content-Security-Policy "default-src 'none';
			script-src 'self' 'unsafe-eval' 'unsafe-inline'; 
			style-src 'self' 'unsafe-inline'; 
			img-src 'self'; 
			frame-src 'self'; 
			connect-src 'self'; 
			frame-ancestors 'self'; 
			base-uri 'self'; 
			form-action 'self'";
`

It works that way, but i would really love to use it without unsafe-eval and unsafe-inline. Using sha256-hash(...) does not work as it seems like the scripts are somehow changing, therefore the hash changes every time i add it to my nginx conf and reload the server.

**Comment by alecpl** [comment]
It would require big architectural backward-incompatible changes. I don't think it's gonna happen in a foreseeable future. Wontfix.

**Comment by blahmutz** [comment]
why do you think its a "big architectural backward-incompatible change" ? the biggest "problem" is that the .js which is executed changes, therefore its not possible to calculate the hash and allow it (which would make it pretty easy). 
it would also help a lot to implement the csp nonce so people can at least use this to limit the scripts that get executed.

**Comment by alecpl** [comment]
I was referring to unsafe-eval and unsafe-inline.

**Comment by blahmutz** [comment]
thats what i mean to - its still possible to not use them and instead use hash'es of the .js files which are executed or add a nonce to the executed js
