### ISSUE TITLE
whу _mbox no strip_tags?

### ISSUE THREAD

**Issue by C0nstantin** [roundcube/roundcubemail#6207]
https://github.com/roundcube/roundcubemail/blob/981cd8726d296e941a6a1e913ea7abf2594ada48/program/steps/mail/func.inc#L166

Hello, why not strip_tags get param '_mbox' ?

if sent `/?_task=mail&_fra"med=2&_action=get&_mbox=<!--%20xxx><script>` 
it's commenting all page.

**Comment by alecpl** [comment]
I confirm the issue, but the problem is not in this line.

**Comment by alecpl** [comment]
Using JSON_HEX_TAG flag for json_encode() in rcube_output::json_serialize() fixes the issue.

**Comment by alecpl** [comment]
Fixed.
