### ISSUE TITLE
Huge Size (25GB) of error log

### ISSUE THREAD

**Issue by bauhaus-edward** [roundcube/roundcubemail#6209]
The error log which is under /var/www/html/roundcubemail-0.5/log/errors at our Linux server is about 26GB. We would like to delete it to free up the space.

![log file size](https://user-images.githubusercontent.com/37166439/37131147-0c1d6520-22c2-11e8-8a96-edee973a2395.PNG)
Any suggestion to delete it without service stoppage?

Can use the following command to truncate it? 
echo > /var/www/html/roundcubemail-0.5/logs/errors

Please advise.

Thanks!

**Comment by alecpl** [comment]
You can just delete it, no need to stop any services if Roundcube is configured to use "file" method (which is the default). Managing logs is out of scope, use logrotate service or sth similar.
