### ISSUE TITLE
Plugin "Enigma": Encrypt with own pub key

### ISSUE THREAD

**Issue by AdvancedStyle** [roundcube/roundcubemail#6210]
It seems when sending an encrypted message using Enigma plugin, it only encrypts the message using the recipients pub keys, so you cannot read your own messages in the sent folder.

There should be a setting to be able to encrypt all encrypted message with your own pub keys too (encrypt it will with pub keys that you also hold the private key).

**Comment by alecpl** [comment]
What version? I'm pretty sure it was working from the beginning.

**Comment by AdvancedStyle** [comment]
Roundcube | 1.3.4
enigma | 0.7

**Comment by AdvancedStyle** [comment]
Note that in my case I imported my private key (not a private key generated in roundcube)

**Comment by AdvancedStyle** [comment]
I imported my private key; I am able to send encrypted mail to myself and receive mail encrypted with my key from others.

**Comment by AdvancedStyle** [comment]
Note that if I CC to myself then it also encrypts with my key, so that I can read it in the sent...

But of course I don't want to have to CC everything to myself, normal mail clients will encrypt with your own key without needing to send it to yourself.

**Comment by alecpl** [comment]
Works for me. Please, enable enigma_debug and send an encrypted mail to yourself only. Provide the log.

**Comment by alecpl** [comment]
Also, are there any errors in log when you try to read a sent message? Could you provide debug for this too?

**Comment by AdvancedStyle** [comment]
Not quite sure how to do this, seeing as I'm using the dockerize mailu (https://github.com/Mailu/Mailu/issues)

**Comment by alecpl** [comment]
I don't know Mailu. Find where Roundcube is installed, there usually is logs folder. To enable enigma_debug find plugins/enigma/config.inc.php.

**Comment by alecpl** [comment]
No feedback.
