### ISSUE TITLE
Not an issue but something I need to do in Roundcube

### ISSUE THREAD

**Issue by scampuza** [roundcube/roundcubemail#6213]
We use Roundcube for allowing some employees at my company, to access corporate mail outside the company network.

For some business/security issues, we must restrict access to webmail, to certain users, at given times, so I developed a Roundcube plugin that gets that information from an internal REST service, and allows or blocks the user from logging in to WebMail.  

The issue is that once the user is logged in, he/she can stay logged in "forever", so I need a way to "kick out" the user from Roundcube.  Is there a way to do that? Is there a way to set and enforce a timeout?

I really appreciate your help with this !

**Comment by alecpl** [comment]
Not really, but you can check your timeout on every request (in the plugin) and logout (kill the session).
