### ISSUE TITLE
Force Logout Inside a Plugin

### ISSUE THREAD

**Issue by scampuza** [roundcube/roundcubemail#6214]
We use Roundcube for allowing some employees at my company, to access corporate mail outside the company network.

For some business/security issues, we must restrict access to webmail, to certain users, at given times, so I developed a Roundcube plugin that gets that information from an internal REST service, and allows or blocks the user from logging in to WebMail.

The issue is that once the user is logged in, he/she can stay logged in "forever", so I need a way to "kick out" the user from Roundcube.

I wrote another plugin that Hooks to the refresh event, so, every minute or so, this plugin kicks in, now I need to know how to kill the session inside the plugin, what PHP command should I execute?

I appreciate your help !

I really appreciate your help with this !

**Comment by alecpl** [comment]
Try `$RCMAIL->kill_session()`. An look into index.php file for more hints.
