### ISSUE TITLE
Refresh only shows new messages

### ISSUE THREAD

**Issue by jfallesen** [roundcube/roundcubemail#6215]
Once Roundcube 1.3.4 automatically refreshes the e-mail list view, if there are any new messages since the last refresh, only those new messages will be shown while other messages appear to have gone from the mailbox (message counters are properly indicating that they are there though). The same happens when doing a manual refresh.

Workaround is to change to another folder and then back to Inbox or to reload the whole page.

**Comment by jfallesen** [comment]
Issue is consistenly reproducible and appears to be independent of skin.
Roundcube version: 1.3.4
PHP version: 5.6.34
Plugins:
archive 3.0	
emoticons 2.0	
filesystem_attachments 1.0	
hide_blockquote 1.0	
html5_notifier		
jqueryui 1.12.0	
managesieve 8.7	
show_additional_headers 2.0	
vcard_attachments 4.0	
virtuser_file 1.0	
xskin 1.3.6

**Comment by alecpl** [comment]
I'm unable to reproduce. Try again without xskin. Check browser console for errors.

**Comment by jfallesen** [comment]
It would appear something had gone wrong with the upgrade. Removed and reinstalled and no longer able to reproduce the issue.
