### ISSUE TITLE
v1.3.5 timezone error

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#6217]
After the upgrade from v1.3.3 to v1.3.5 there is incorrect message received time displayed:  GMT -04:00  instead of  GMT +03:00  (-7 hours difference).  I had to set the timezone GMT +10:00 instead of GMT +03:00 to see the correct time.

The received time in the messages headers is correct and Thunderbird shows it correctly.

**Comment by alecpl** [comment]
What timezone (location) precisely? Is this with all messages? Could you provide sample Date: header? What PHP version? What timezone on server (in php.ini)?

There were some changes in date parsing code recently, but I don't see how they would cause such issue.

**Comment by quicktrick** [comment]
1. Timezone: Europe/Moscow  (UTC +03:00)
2. This is with all messages.  And, I'm afraid, there are even worse cases (could you contact to me in Telegram `@alexsinev`, I'll give you an access to some email account for you can see everything yourself).
3. On the server:

    mail:~ # date; date -u
    Sun Mar 18 11:10:13 MSK 2018
    Sun Mar 18 08:10:13 UTC 2018

PHP Version 7.2.2
php.ini:

    [Date]
    date.timezone = 'UTC'

**Comment by alecpl** [comment]
I'm unable to reproduce. What IMAP server? Could you enable imap_debug and provide part of the FETCH response with Date: header? Are you sure Roundcube version is the only thing updated on your server?

**Comment by quicktrick** [comment]
@alecpl ,  could you please give an example of the command for Dovecot?  Its documentation is not very clear.

**Comment by alecpl** [comment]
imap_debug is a Roundcube option. It enables logging of IMAP conversation. In this log you can find message headers sent by dovecot to Roundcube.

**Comment by quicktrick** [comment]
This one is taken after reading the Inbox contents:

    Mar 18 23:35:54 mail roundcube[2401]: <mrp7lm40> [A38E] S: * 6 FETCH (UID 999 RFC822.SIZE 36910 FLAGS (\Seen) INTERNALDATE "18-Mar-2018 03:30:34 +0300" BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY)] {237}

This one is taken after reading the message:

    Mar 18 23:37:38 mail roundcube[2390]: <mrp7lm40> [E482] S: * 6 FETCH (UID 999 RFC822.SIZE 36910 FLAGS (\Seen) INTERNALDATE "18-Mar-2018 03:30:34 +0300" BODYSTRUCTURE ("text" "plain" ("charset" "UTF-8") NIL NIL "7bit" 35170 420 NIL NIL NIL NIL) BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY IN-REPLY-TO BCC SENDER MESSAGE-ID CONTENT-TRANSFER-ENCODING REFERENCES X-DRAFT-INFO MAIL-FOLLOWUP-TO MAIL-REPLY-TO RETURN-PATH)] {341}

And this is the date shown in the browser when I set the `Time zone` to `Auto` or to `(GMT +03:00) Europe/Moscow`:

    Date 	Sat 20:30

Is it the thing you requested?

**Comment by alecpl** [comment]
Did you configure Roundcube to use "Arrival date"? If not, I'd like to see also Date: header returned by the server (should be below the line you extracted from the log). You could also check if the bug exist with both sorting column settings "Arrival date" and "Sent date"

**Comment by quicktrick** [comment]
Mar 19 10:08:41 mail roundcube[2389]: <base2fhf> [3313] C: A0004 UID FETCH 999 (UID RFC822.SIZE FLAGS INTERNALDATE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY IN-REPLY-TO BCC SENDER MESSAGE-ID CONTENT-TRANSFER-ENCODING REFERENCES X-DRAFT-INFO MAIL-FOLLOWUP-TO MAIL-REPLY-TO RETURN-PATH)])
    Mar 19 10:08:41 mail roundcube[2389]: <base2fhf> [3313] S: * 6 FETCH (UID 999 RFC822.SIZE 36910 FLAGS (\Seen) INTERNALDATE "18-Mar-2018 03:30:34 +0300" BODYSTRUCTURE ("text" "plain" ("charset" "UTF-8") NIL NIL "7bit" 35170 420 NIL NIL NIL NIL) BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY IN-REPLY-TO BCC SENDER MESSAGE-ID CONTENT-TRANSFER-ENCODING REFERENCES X-DRAFT-INFO MAIL-FOLLOWUP-TO MAIL-REPLY-TO RETURN-PATH)] {341}
    Mar 19 10:08:41 mail roundcube[2389]: [358B blob data]
    Mar 19 10:08:41 mail roundcube[2389]: <base2fhf> [3313] S: )
    Mar 19 10:08:41 mail roundcube[2389]: <base2fhf> [3313] S: A0004 OK Fetch completed (0.002 + 0.000 + 0.001 secs).
    Mar 19 10:08:41 mail roundcube[2389]: <base2fhf> [3313] C: A0005 UID FETCH 999 (BODY.PEEK[1])

Aleksander, I didn't configure Roundcube to use "Arrival date".  And, you are right, the error appears when I choose sorting column settings "None" and "Sent date", and it does not appear when I choose sorting column settings "Arrival date".

The above message's sent date is the same as its arrival date.

**Comment by alecpl** [comment]
I don't know why your logging system or editor hides the headers content, but anyway... If it works with internaldate (arrival date), but not with sent date (Date: header in the message), I guess there's something wrong with the date parsing indeed. However, to be sure I need to see some sample dates from your mail messages.

Maybe that's the same issue as in #6216 ?

**Comment by quicktrick** [comment]
Aleksander, contact me in Telegram, I'll give you access to my server.

**Comment by quicktrick** [comment]
@alecpl 

Yes, it maybe the same issue as in #6216 , the Date headers contain the timezone abbreviations as a comment in parentheses.
