### ISSUE TITLE
Enhancement: Group messages on the list in the Outlook manner: today, yesterday, this week and so on.

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#6221]
My users often ask me a question if Roundcube has a feature to group messages on the list in the MS Outlook style: "Today", "Yesterday", "This week" and so on.
I spent some time on searching plugin for this, but I found nothing, so my duty is to ask for this feature here. :)
Thanks!
Skygge

**Comment by alecpl** [comment]
Duplicate of #4990.
