### ISSUE TITLE
quicksearch no longer works for some users

### ISSUE THREAD

**Issue by mam885** [roundcube/roundcubemail#6222]
we are facing problems with quicksearch. Some users (atleast one) can no longer use the quicksearch of inbox. not even if he enters a word from the subject of a mail from two days ago into the quicksearch, the mail would appear. The same still works for mails in sent items and it also worked for inbox some days ago.

Other mailboxes, like mine, are not affected. It's working in inbox and also in sent items.

Any idea how to solve this issue?

**Comment by alecpl** [comment]
That might be IMAP server indexing issue. Enable imap_debug and check the conversation with IMAP.

**Comment by alecpl** [comment]
No feedback.
