### ISSUE TITLE
install Net_LDAP3 failed

### ISSUE THREAD

**Issue by dirtyluke** [roundcube/roundcubemail#6223]
my roundcube haven't installed Net_LDAP3, when i try to install Net_LDAP3, i got this
```
No releases available for package "pear.php.net/Net_LDAP3"
install failed
```
i'm new at php & pear, what should i do
roundcube version: 1.3.5
php version:5.6.30
@till @johndoh @weisslj @marcoliverteschke @bostjan

**Comment by alecpl** [comment]
composer.json-dist file from git-master should work. We change the source from which this package is fetched.

**Comment by alecpl** [comment]
Oh, and I have no idea from where that `pear.php.net` prefix comes from. We use `kolab` namespace also in Roundcube 1.3.
