### ISSUE TITLE
Problem with login for users with special usernames

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#6224]
Hello,

since our upgrade from RC 1.3.3. to RC 1.3.5. some users can't login to Roundcube anymore. 

The issue affects only users with a username with an combination like ".-". For example usernames like "d.-h.lastname". 

I tried it also with all plugins disabled. There is **no notification** in error or imap log like "IMAP Error: Login failed for xxx".  

Maybe you can reproduce the issue or give me a hint on how to generate a log message.

**Comment by danielh84** [comment]
There is also no contact with the imap server. no failed authorization or anything else.

**Comment by alecpl** [comment]
I'm unable to reproduce. I think you should be looking on the imap side. Imap server should have good debugging tools. On Roundcube side you can enable imap_debug, but it's possible that username will be hidden/obfuscated in the log. Did you try with all plugins disabled?

**Comment by hs** [comment]
Hi. Maybe I also encountered the same kind of problem.

When I upgrade Roundcube to 1.3.4.  "$config['login_lc'] = 0" became ineffective and an user with Upper-case character always failed to login with error like: 
[02-Apr-2018 13:20:20 +0900]: <1srkua0k> IMAP Error: Login failed for <LOGINNAME CONVERTED TO LOWER-CASE> to against localhost from XXX.XXX.XXX.XXX.

I downgrade to 1.3.3 and it works. I also try 1.3.5 and github master branch but it doesn't work.

**Comment by hs** [comment]
Hi. Maybe I also encountered the same kind of problem.

When I upgrade Roundcube to 1.3.4. "$config['login_lc'] = 0" became ineffective and an user with Upper-case character always failed to login with error like:
[02-Apr-2018 13:20:20 +0900]: <1srkua0k> IMAP Error: Login failed for <LOGINNAME CONVERTED TO LOWER-CASE> to against localhost from XXX.XXX.XXX.XXX.

I downgrade to 1.3.3 and it works. I also try "1.3.5 [GIT 20180402.0143]" and "1.4-git [GIT 20180402.0143]" versions but it doesn't work.

**Comment by danielh84** [comment]
Yes, tried with disabled plugins. There is no contact to imap authorization if i try with roundcube as client. There is also nothing in RC imap logs.

Mysterious that the authorization works with the mailadress instead of the username. "d.-h.lastname@domain.de" works, "d.-h.lastname" not. If there is no combination of ".-" in username both options work also with roundcube. 

Other Mailclients like Thunderbird work with both options as the username. 1.3.3. also works fine with my backup. Next try will be 1.3.4.

**Comment by hs** [comment]
I try to check username in program/include/rcmail.php:login() function and find rcube_utils::idn_to_ascii() overwrite it on both pattern. 

But I'm not sure why idn_to_ascii() do it, sorry.

check code:
--- program/include/rcmail.php.old	2017-11-09 03:42:05.000000000 +0900
+++ program/include/rcmail.php	2018-04-10 10:46:10.364054000 +0900
@@ -598,6 +598,7 @@
                 $username = $local . '@' . mb_strtolower($domain);
             }
         }
+	self::write_log('username', "login_lc: " . $username);
 
         // try to resolve email address from virtuser table
         if (strpos($username, '@') && ($virtuser = rcube_user::email2user($username))) {
@@ -608,6 +609,7 @@
         // Only rcube_contacts class is using domain names in Unicode
         $host     = rcube_utils::idn_to_ascii($host);
         $username = rcube_utils::idn_to_ascii($username);
+	self::write_log('username', "idn_to_ascii: " . $username);
 
         // user already registered -> overwrite username
         if ($user = rcube_user::query($username, $host)) {
@@ -619,6 +621,7 @@
                 return false;
             }
         }
+	self::write_log('username', "rcube_user::query: " . $username);
 
         $storage = $this->get_storage();

with 1.3.3:
[10-Apr-2018 10:56:11 +0900]: <l0nduehh> login_lc: H.S
[10-Apr-2018 10:56:11 +0900]: <l0nduehh> idn_to_ascii: H.S
[10-Apr-2018 10:56:11 +0900]: <l0nduehh> rcube_user::query: H.S

[10-Apr-2018 10:59:50 +0900]: <6r8269kt> login_lc: d.-h.lastname
[10-Apr-2018 10:59:50 +0900]: <6r8269kt> idn_to_ascii: d.-h.lastname
[10-Apr-2018 10:59:50 +0900]: <6r8269kt> rcube_user::query: d.-h.lastname

with 1.3.5:
[10-Apr-2018 10:46:15 +0900]: <qcc09rgo> login_lc: H.S
[10-Apr-2018 10:46:15 +0900]: <qcc09rgo> idn_to_ascii: h.s
[10-Apr-2018 10:46:15 +0900]: <qcc09rgo> rcube_user::query: h.s

[10-Apr-2018 10:59:36 +0900]: <qcc09rgo> login_lc: d.-h.lastname
[10-Apr-2018 10:59:36 +0900]: <qcc09rgo> idn_to_ascii: 
[10-Apr-2018 10:59:36 +0900]: <qcc09rgo> rcube_user::query:

**Comment by alecpl** [comment]
Nevermind, I see that it's caused by use of INTL_IDNA_VARIANT_UTS46. So, your temp. workaround could be to disable intl extension. Or just comment out the line with idn_to_ascii() call around line 610. It looks like we need to be more careful with idn_to_ascii() use on usernames now.

**Comment by alecpl** [comment]
Fixed.

**Comment by hs** [comment]
Thank you for your comment and quick fix.
I apply the fix to 1.3.5 and it works fine for me.

Thank you.
