### ISSUE TITLE
Add user ID in error messages in log

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6225]
Hi,

Is it possible to add the following in error messages like it exists normal info messages?

- the user ID (ID: 1683)
- the user IP

Normal info message:
Mar 23 13:13:16 fastweb roundcube: <48uok3io> Successful login for celia@coop.pt (ID: 1683) from 62.1.1.209 in session 48uok3iovq282emdkhgg4n4kbb

Error message:
Mar 23 13:15:21 fastweb roundcube: <48uok3io> IMAP Error: Could not save message in Sent in /home/hosting/dh.pt/webmail/program/steps/mail/sendmail.inc on line 655 (POST /webmail/?_task=mail&_unlock=loading1521810952251&_lang=pt_PT&_framed=1&_action=send)

Mar 23 17:25:47 fastweb roundcube: <etj0lj2j> PHP Error: Request security check failed (GET /webmail/?_task=logout&_token=EAWZQ53XNPOSkebyX4VyYKOuzf1xWIWw)

Mar 23 18:11:04 fastweb roundcube: PHP Warning:  strtolower() expects parameter 1 to be string, array given in /home/hosting/dh.ptt/webmail/program/lib/Roundcube/rcube_imap.php on line 2065
Mar 23 18:11:04 fastweb roundcube: PHP Stack trace:
Mar 23 18:11:04 fastweb roundcube: PHP   1. {main}() /home/hosting/dh.ptt/webmail/index.php:0
Mar 23 18:11:04 fastweb roundcube: PHP   2. include_once() /home/hosting/dh.ptt/webmail/index.php:303
Mar 23 18:11:04 fastweb roundcube: PHP   3. rcube_message->__construct() /home/hosting/dh.ptt/webmail/program/steps/mail/show.inc:50
Mar 23 18:11:04 fastweb roundcube: PHP   4. rcube_imap->get_message() /home/hosting/dh.ptt/webmail/program/lib/Roundcube/rcube_message.php:101
Mar 23 18:11:04 fastweb roundcube: PHP   5. rcube_imap->structure_part() /home/hosting/dh.ptt/webmail/program/lib/Roundcube/rcube_imap.php:1930
Mar 23 18:11:04 fastweb roundcube: PHP   6. rcube_imap->structure_part() /home/hosting/dh.ptt/webmail/program/lib/Roundcube/rcube_imap.php:2036
Mar 23 18:11:04 fastweb roundcube: PHP   7. rcube_imap->structure_part() /home/hosting/dh.ptt/webmail/program/lib/Roundcube/rcube_imap.php:2172
Mar 23 18:11:04 fastweb roundcube: PHP   8. strtolower() /home/hosting/dh.ptt/webmail/program/lib/Roundcube/rcube_imap.php:2065

and

Mar 23 18:31:36 fastweb roundcube: PHP Warning:  array_merge(): Argument #2 is not an array in /home/hosting/dh.pt/webmail/program/steps/mail/sendmail.inc on line 357
Mar 23 18:31:36 fastweb roundcube: PHP Stack trace:
Mar 23 18:31:36 fastweb roundcube: PHP   1. {main}() /home/hosting/dh.pt/webmail/index.php:0
Mar 23 18:31:36 fastweb roundcube: PHP   2. include_once() /home/hosting/dh.pt/webmail/index.php:303
Mar 23 18:31:36 fastweb roundcube: PHP   3. array_merge() /home/hosting/dh.pt/webmail/program/steps/mail/sendmail.inc:357

also this one

Mar 27 14:11:29 fastweb roundcube: PHP Warning:  file_get_contents(/home/hosting/dh.pt/webmail/temp/e4bec82d01b47177fa3d8b26a987e9ee.tmp): failed to open stream: No such file or directory in /home/hosting/dh.pt/webmail/program/steps/mail/get.inc on line 533
Mar 27 14:11:29 fastweb roundcube: PHP Stack trace:
Mar 27 14:11:29 fastweb roundcube: PHP   1. {main}() /home/hosting/dh.pt/webmail/index.php:0
Mar 27 14:11:29 fastweb roundcube: PHP   2. include_once() /home/hosting/dh.pt/webmail/index.php:303
Mar 27 14:11:29 fastweb roundcube: PHP   3. rcmail_attachment_handler->body() /home/hosting/dh.pt/webmail/program/steps/mail/get.inc:129
Mar 27 14:11:29 fastweb roundcube: PHP   4. file_get_contents() /home/hosting/dh.pt/webmail/program/steps/mail/get.inc:533

(this last one, could give you information needed to fix it, v1.3.5)

Alec, this is just to make RC even better!
Is it possible to add there two info's in this cases?
Thanks,

**Comment by alecpl** [comment]
PHP warnings/errors aren't controlled by Roundcube, so we can't really extend them. For others (the first two error messages) we could, but there's already a session id (where possible) so you can match it with userlogins entries.

**Comment by dddns** [comment]
Hi Alec,
I know, I can match the SID with the user, but if it's possible to make all logs of this type include the IP and user ID would be all with the same paterm.
Only if possible!

**Comment by alecpl** [comment]
As I said, it's impossible (or hard or tricky) for all logs. If you find a solution, create a PR.
