### ISSUE TITLE
Slow response while opening first email after login

### ISSUE THREAD

**Issue by unitronltd** [roundcube/roundcubemail#6230]
Hi Guys,

When first logging into round cube since the last update we have a very slow response opening the very first email, it will sit on loading for around 10-20 seconds then open the email, if you then reopen it there is no delay.

It is any email attachment or not, it only happens when you first login and only on first email opened,

Any ideas?

Thanks

John

**Comment by alecpl** [comment]
That is likely an imap server issue. I guess it re-builds some indexes. You can enable imap_debug in Roundcube to see what timings do you have on imap responses.
