### ISSUE TITLE
Roundcube Password Plugin Virtualmin - Unable to execute

### ISSUE THREAD

**Issue by diegoweb** [roundcube/roundcubemail#6233]
Hey guys!
I have followed this user guide: https://github.com/roundcube/roundcubemail/issues/6092#issuecomment-351724002

But I keep receiving error when I try to update the user password. I have followed all online guides from the past year and I still can't change the user password.

This user has also posted here: https://www.virtualmin.com/node/54679
Even the Virtualmin readme file: http://www.virtualmin.com/files/roundcube_virtualmin_password_change.txt

What should I do?

Error from log:

> [30/Mar/2018 21:03:33]: <bc48rg1a> PHP Error: Password plugin: Unable to execute /home/myuser/public_html/webmail/plugins/password/helpers/chgvirtualminpasswd in /home/myuser/public_html/webmail/plugins/password/drivers/virtualmin.php on line 88 (POST /webmail/?_task=settings&_action=plugin.password-save)

Used commands:
```
gcc -o plugins/password/helpers/chgvirtualminpasswd plugins/password/helpers/chgvirtualminpasswd.c
chown root:myuser plugins/password/helpers/chgvirtualminpasswd
strip plugins/password/helpers/chgvirtualminpasswd
chmod 4550 plugins/password/helpers/chgvirtualminpasswd
```

**Comment by alecpl** [comment]
You need to make the file executable by the php (apache, www, whatever) process owner.

**Comment by diegoweb** [comment]
I know the file should be executable by the PHP process.

In my case, webmin uses APACHE user to handle this situation.
I have:

MyUser => 1000
Root => 0
Apache => 48

In any combination (1000:1000, 0:1000, 0:0, 48:48, etc), the error persists: Unable to execute the file.
![image](https://user-images.githubusercontent.com/12632119/38166998-18f78fce-3504-11e8-9746-8e9775ab6a2f.png)

Available users:
![image](https://user-images.githubusercontent.com/12632119/38166991-db2e435e-3503-11e8-801d-718e89edc0e3.png)

**Comment by alecpl** [comment]
Ok, the same error is also logged when the command returns non-zero status. So, maybe try to get the output from it. Add `rcube::console($output);` in line 32 (after exec()) of plugins/password/drivers/virtualmin.php. This would log the output into logs/console.

**Comment by diegoweb** [comment]
![image](https://user-images.githubusercontent.com/12632119/38176222-9b0f9ee4-35c1-11e8-8931-99eea620531d.png)
![image](https://user-images.githubusercontent.com/12632119/38176225-a45dc2a0-35c1-11e8-8d82-b74e6043738f.png)

This is my virtualmin.php:
```
<?php

/**
 * Virtualmin Password Driver
 *
 * Driver that adds functionality to change the users Virtualmin password.
 * The code is derrived from the Squirrelmail "Change Cyrus/SASL Password" Plugin
 * by Thomas Bruederli.
 *
 * It only works with virtualmin on the same host where Roundcube runs
 * and requires shell access and gcc in order to compile the binary.
 *
 * @version 3.0
 * @author Martijn de Munnik
 *
 * Copyright (C) 2005-2013, The Roundcube Dev Team
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://www.gnu.org/licenses/.
 */

class rcube_virtualmin_password
{
    function save($currpass, $newpass)
    {
        $rcmail   = rcmail::get_instance();
        $format   = $rcmail->config->get('password_virtualmin_format', 0);
        $username = $_SESSION['username'];

        switch ($format) {
        case 1: // username%domain
            $domain = substr(strrchr($username, "%"), 1);
            break;
        case 2: // username.domain (could be bogus)
            $pieces = explode(".", $username);
            $domain = $pieces[count($pieces)-2]. "." . end($pieces);
            break;
        case 3: // domain.username (could be bogus)
            $pieces = explode(".", $username);
            $domain = $pieces[0]. "." . $pieces[1];
            break;
        case 4: // username-domain
            $domain = substr(strrchr($username, "-"), 1);
            break;
        case 5: // domain-username
            $domain = str_replace(strrchr($username, "-"), "", $username);
            break;
        case 6: // username_domain
            $domain = substr(strrchr($username, "_"), 1);
            break;
        case 7: // domain_username
            $pieces = explode("_", $username);
            $domain = $pieces[0];
            break;
        default: // username@domain
            $domain = substr(strrchr($username, "@"), 1);
        }

        if (!$domain) {
            $domain = $rcmail->user->get_username('domain');
        }

        $username = escapeshellarg($username);
        $domain   = escapeshellarg($domain);
        $newpass  = escapeshellarg($newpass);
        $curdir   = RCUBE_PLUGINS_DIR . 'password/helpers';

        exec("$curdir/chgvirtualminpasswd modify-user --domain $domain --user $username --pass $newpass", $output, $returnvalue);
		rcube::console($output);

        if ($returnvalue == 0) {
            return PASSWORD_SUCCESS;
        }
        else {
            rcube::raise_error(array(
                'code' => 600,
                'type' => 'php',
                'file' => __FILE__, 'line' => __LINE__,
                'message' => "Password plugin: Unable to execute $curdir/chgvirtualminpasswd"
                ), true, false);
        }

        return PASSWORD_ERROR;
    }
}

```

**Comment by alecpl** [comment]
Please, try the plugin version from git-master: https://github.com/roundcube/roundcubemail/blob/master/plugins/password/drivers/virtualmin.php

**Comment by diegoweb** [comment]
Using the plugin version from git-master returns a slightly different error (it doesn't detect the mail user):
This one is using `$config['password_virtualmin_format'] = 0;`
`[02/Apr/2018 09:54:04]: <nttsvenv> PHP Error: Password plugin: Unable to execute /home/myuser/public_html/webmail/plugins/password/helpers/chgvirtualminpasswd or domain for mail-user ''server.myuser'' not known to Virtualmin in /home/myuser/public_html/webmail/plugins/password/drivers/virtualmin.php on line 50 (POST /webmail/?_task=settings&_action=plugin.password-save)`

Using `$config['password_virtualmin_format'] = 2;` returns the same error from above:
`[02/Apr/2018 09:58:09]: <nttsvenv> PHP Error: Password plugin: Unable to execute /home/myuser/public_html/webmail/plugins/password/helpers/chgvirtualminpasswd or domain for mail-user ''server.myuser'' not known to Virtualmin in /home/myuser/public_html/webmail/plugins/password/drivers/virtualmin.php on line 50 (POST /webmail/?_task=settings&_action=plugin.password-save)`

**Comment by diegoweb** [comment]
@alecpl any other advice?
