### ISSUE TITLE
PHP 7.2: count(): Parameter must be an array or an object that implements Countable in program/lib/Roundcube/rcube_spellcheck_enchant.php on line 104

### ISSUE THREAD

**Issue by gravesit** [roundcube/roundcubemail#6234]
Getting the following error:

`[Tue Apr 03 13:39:36.280767 2018] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in program/lib/Roundcube/rcube_spellcheck_enchant.php on line 104`

PHP 7.2
All dependencies installed
Roundcube 1.3.5

**Comment by alecpl** [comment]
This regression in PHP is very annoying. Fixed this one.
