### ISSUE TITLE
Problem with <mark all as read> menu

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6235]
1. when try to mark all messages in folder as read by <Mark all as read> in drop down menu,
i've got an error:

C: A0004 UID STORE INVALID +FLAGS.SILENT (\Seen)
S: A0004 BAD Error in IMAP command UID STORE: Invalid uidset (0.001 + 0.000 secs).

appears after commit "Fix possible IMAP command injection and type juggling vulnerabilities (#6229)"

2. if we have unread messages in more than one folder, pressing <Mark> in drop down menu
has no effect.

**Comment by alecpl** [comment]
Fixed issue 1. Could you describe the second issue in more detail? Which drop down menu? Are you talking about multi-folder search result or what?

**Comment by grape6** [comment]
sorry, missed some details.
right click on folder name -> drop down menu -> select <Mark all as read>.
if only one folder has unread mails - pressing MARK works as expected.
if more than one folder has unread mails - pressing MARK has no effect.

**Comment by alecpl** [comment]
Fixed.
