### ISSUE TITLE
Sort conversations from recent to oldest

### ISSUE THREAD

**Issue by miqmago** [roundcube/roundcubemail#6239]
I've seen it's possible group emails in conversations. The problem is that it shows the newest email in the conversation at the bottom, so one have to open the conversation, scroll down and open the last conversation. Would it be possible to sort conversations from newest to oldest?

In fact the main problem is that when you open the oldest conversation (the first one in the list), you open the oldest and can't see following responses. So one is forced to open the newest conversation to be able to read all thread.

Roundcube version: 1.3.5

**Comment by alecpl** [comment]
No it would not be possible. This is how IMAP THREAD standard specifies threaded view. So called "Conversations view" is another feature we have a ticket for already.

**Comment by melroy89** [comment]
I'm actually also at this point now, where I would love to use Conversation View, only if clicking on the conversation will show me the latest mail (thus descending in time).

**Comment by SawkeeReemo** [comment]
Apple Mail does this. So I don’t know why someone is claiming it’s not possible back in 2018 here. It’s definitely possible, I’ve had it that way for years. Would love to see the same happen with Roundcube.

**Comment by SlugFiller** [comment]
The talk about the `THREAD` standard is superficial. `THREAD` returns a tree, not a list. Roundcube already flattens it to a list, i.e. it doesn't display it as-received, but adjusts it for a specific view. Flipping the list order shouldn't be a huge extra step over flattening it.

**Comment by SawkeeReemo** [comment]
Agreed. That would be much better.
