### ISSUE TITLE
Mail  timezone not recognized when mail sent from /bin/mail in FreeBSD

### ISSUE THREAD

**Issue by ak7777777** [roundcube/roundcubemail#6246]
Hello!

FreeBSD /bin/mail command add header which looks like
Date: Thu, 12 Apr 2018 23:04:00 +0300 (MSK)
Where MSK is name of timezone (here will be 3-5 characters name of timezone, this is same as +0300 but name). In this case Roundcube shows me time 16:04 not 23.04. Looks like we need to stripe symb. name of timezone also, as we strip GMT

such patch helped me

--- roundcubemail-1.3.5.orig/program/lib/Roundcube/rcube_utils.php        2018-03-12 23:19:26.000000000 +0300
+++ roundcubemail-1.3.5/program/lib/Roundcube/rcube_utils.php     2018-04-12 23:49:54.837866000 +0300
@@ -798,11 +798,13 @@
                 '/GMT\s*([+-][0-9]+)/',                     // support non-standard "GMTXXXX" literal
                 '/[^a-z0-9\x20\x09:+-\/]/i',                // remove any invalid characters
                 '/\s*(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s*/i',   // remove weekday names
+                               '/ ([A-Z]{3,5})\s*$/',
             ),
             array(
                 '\\1',
                 '',
                 '',
+                               '',
             ), $date);

         $date = trim($date);

BR

**Comment by alecpl** [comment]
It was fixed in 1.3.6.
