### ISSUE TITLE
Fetching publickey.js while update to 1.3.6 failed

### ISSUE THREAD

**Issue by gnadelwartz** [roundcube/roundcubemail#6248]
Hi,

the update process hangs on my box at:

```
Fetching https://raw.githubusercontent.com/diafygi/publickeyjs/0e011cb18907a1adc0313aa92e69cd8858e1ef66/publickey.js
```
the URL is listed in `jsdeps.json` in my roundcube installation ... may be it's not needed?

The reason is my host seems to be blocked by rawgit, rawgit states that this can happen* if its used to often. After asking for unblocking I got the advise to use the githup API to fetch files from github:

> the offical way to get a file from guthub is using github API:
>
> `https://api.github.com/repos/:owner/:repo/contents/:path?ref=tag/commit/branch`
>
> https://developer.github.com/v3/repos/contents/
> https://developer.github.com/v3/

so the download link for getting the publickey.js should be changed to:

```
curl -s -H "Accept:application/vnd.github.v3.raw" https://api.github.com/repos/diafygi/publickeyjs/contents/publickey.js?ref=0e011cb18907a1adc0313aa92e69cd8858e1ef66
```

(*) reference about blocking may happen: https://rawgit.com/
> Use this URL for development
  ...
  Excessive traffic will be throttled and blacklisted.

**Comment by gnadelwartz** [comment]
https://stackoverflow.com/questions/49818899/official-way-to-access-download-files-from-github

**Comment by alecpl** [comment]
So, they do have throttling on rawgit but not on api? Wasn't their advice a temporary solution? It would be not nice to start using the api just to find out it also could be blocked.

**Comment by gnadelwartz** [comment]
The answer from github support was it will not be blocked or throttled if you use the API.
Nevertheless we can ask again to be shure or implement API accaess as fallback in case rawgit access is blocked.

**Comment by alecpl** [comment]
Fixed.

**Comment by gnadelwartz** [comment]
Thanks!
