### ISSUE TITLE
Roundcubemail instructions not working

### ISSUE THREAD

**Issue by drkenrich** [roundcube/roundcubemail#6249]
I have a lot of message I need to download from my roundcube email account. The instructions say:
_**"Export an Entire Folder¶
For archiving purposes all messages from a folder can be downloaded as .zip archive without first selecting them in the list.

Switch to the folder you want to export and then select Download folder from the Folder actions menu behind the gear icon in the folders list footer."**_

Starting in the Mail > Folders screen, I try to use the gear icon at the bottom but it doesn't display either ZIP or Download. If I try to selecting a couple of files, it doesn't display either again. If I go to the Preferences > Folder, it still doesn't display either.

Either this functions has been turned off or it's not working.

Please get them on for me.

![roundcube 1](https://user-images.githubusercontent.com/34901309/38782059-de79b23c-40a2-11e8-8237-6b762448ce9e.jpg)
![roundcube 2](https://user-images.githubusercontent.com/34901309/38782060-de922f06-40a2-11e8-84bf-17aa39678f58.jpg)
![roundcube 3](https://user-images.githubusercontent.com/34901309/38782061-dea9ad5c-40a2-11e8-83b2-da74fffa74ef.jpg)

**Comment by alecpl** [comment]
You need to enable and configure zipdownload plugin.
