### ISSUE TITLE
.eml export for multiple emails

### ISSUE THREAD

**Issue by TheTrialTech** [roundcube/roundcubemail#6253]
Is there any plug-in available to be able to download more than 1 email at a time, or create a new folder to copy multiple emails to and then export the folder?

Working on a RUSH big project - any help would be very welcomed!

**Comment by alecpl** [comment]
zipdownload plugin.

**Comment by thomascube** [comment]
This might me worth some documentation in the [FAQ](/roundcube/roundcubemail/wiki/FAQ).

**Comment by alecpl** [comment]
Added FAQ entry.
