### ISSUE TITLE
Password change and symbols

### ISSUE THREAD

**Issue by CyberCr33p** [roundcube/roundcubemail#6255]
I use password plugin to change passwords through a shell script. When the password contains characters and numbers it works fine. If I put some symbols I get a 500 error with white screen. From server logs I see that password plugin doesn't call the shell script at all when password has these symbols.

Roundcube error logs:

`
[20-Apr-2018 14:56:35 Europe/Athens] PHP Fatal error:  Uncaught Error: Call to undefined function raise_error() in /usr/local/www/roundcube/plugins/password/drivers/cretapanel.php:27
Stack trace:
#0 /usr/local/www/roundcube/plugins/password/password.php(335): rcube_cretapanel_password->save('123', '!@#$%^&*(')
#1 /usr/local/www/roundcube/plugins/password/password.php(172): password->_save('123', '!@#$%^&*(')
#2 /usr/local/www/roundcube/program/lib/Roundcube/rcube_plugin_api.php(493): password->password_save()
#3 /usr/local/www/roundcube/index.php(289): rcube_plugin_api->exec_action('plugin.password...')
#4 {main}
  thrown in /usr/local/www/roundcube/plugins/password/drivers/cretapanel.php on line 27
`

**Comment by alecpl** [comment]
creatapanel.php file is not part of Roundcube. You can replace raise_error() with rcube::raise_error(), but you should contact the driver author.

**Comment by CyberCr33p** [comment]
cretapanel.php is a duplication of kpasswd.php

Do you think I have to contact Alex Cartwright ?
