### ISSUE TITLE
http://roundcube.net/ does not redirect to https://roundcube.net/

### ISSUE THREAD

**Issue by michael-k** [roundcube/roundcubemail#6257]
The link at the top of https://github.com/roundcube/roundcubemail uses HTTP instead of HTTPS.  And http://roundcube.net/ does not redirect to https://roundcube.net/.

**Comment by alecpl** [comment]
I don't see an issue here, but I modified the link to point to https://roundcube.net

**Comment by thomascube** [comment]
Works for me anyway.
