### ISSUE TITLE
Group recipent are not added, only comma's

### ISSUE THREAD

**Issue by peterkroon** [roundcube/roundcubemail#6258]
Roundcube Webmail 1.3.6

_Steps_
- Compose new email
- Add group recipient
- Click on the group you wish to add

_Result_
- Only comma's are shown

_Expected result_
- All recipients are shown

When in address book the contacts are not shown in group.
The contact does have the group checked at tab "group".

**Comment by alecpl** [comment]
Works for me. What web browser? What addressbook (ldap or sql)? Try with disabled all plugins.

**Comment by peterkroon** [comment]
Brave, Firefox and Edge
Sql

How do I disable all plugins?

archive | 3.0 | GPLv3+ |  
-- | -- | -- | --
filesystem_attachments | 1.0 | GPLv3+ |  
jqueryui | 1.12.0 | GPLv3+ |  
managesieve | 8.7 | GPLv3+ |  
password | 4.2 | GPLv3+ |  
zipdownload | 3.3 | GPLv3+ |

**Comment by peterkroon** [comment]
Same result with ````$config['plugins'] = array()````

**Comment by alecpl** [comment]
We'd need more precise steps to reproduce and maybe contacts data. Could you provide vCard export? Could you check browser network console and provide server response to the ajax request when you double-click the group in compose?

**Comment by peterkroon** [comment]
- No errors found in webconsole

````
action	autocomplete
exec	this.ksearch_query_results([{"name":"__TEST__ (2)","type":"group","id":"8","source":"sql"},{"name":"__TEST_0 <test_0@test.nl>","type":null,"id":"1146","source":"sql"},{"name":"__TEST_1 <test_1@test.nl>","type":null,"id":"1147","source":"sql"}],"test","1524379120011"); 
````

````
action	group-expand
exec	this.replace_group_recipients("8",""); 
````


contacts.vcf

````
BEGIN:VCARD
VERSION:3.0
N:;__TEST_0;;;
FN:__TEST_0
EMAIL;TYPE=INTERNET;TYPE=HOME:test_0@test.nl
CATEGORIES:__TEST__
END:VCARD
BEGIN:VCARD
VERSION:3.0
N:;__TEST_1;;;
FN:__TEST_1
EMAIL;TYPE=INTERNET;TYPE=HOME:test_1@test.nl
CATEGORIES:__TEST__
END:VCARD

````

**Comment by peterkroon** [comment]
>Could you check browser network console and provide server response to the ajax request when you double-click the group in compose?

I don't double click.
It's 1 click or the enter key.

**Comment by peterkroon** [comment]
Ah, I see what you mean. I've tried it and the result is below.
````
action | group-expand
-- | --
exec | this.replace_group_recipients("8","");


````

**Comment by alecpl** [comment]
Ok, so this is autocompletion. Still I'm unable to reproduce. Group-expand response is indeed wrong (empty), but all the rest looks correct. If you know php a little bit you could try to do some debug in program/steps/mail/autocomplete.inc.

**Comment by peterkroon** [comment]
I could do that but before I do there's also another issue happening.
In the initial report I wrote:
>When in address book the contacts are not shown in group.
The contact does have the group checked at tab "group".

Is this the default behaviour?

**Comment by alecpl** [comment]
No, it also works for me. When I select the group I see assigned contacts on the list. I guess there will be the same reason for this. You can also enable sql_debug to see what queries are executed and check them manually to see what results they give.

**Comment by peterkroon** [comment]
Where do I enable ``sql_debug``?

**Comment by alecpl** [comment]
in Roundcube config.

**Comment by peterkroon** [comment]
I've added ``$config['sql_debug'] = true;`` but no logs to be found at ``<log_dir>/sql or to syslog``

**Comment by peterkroon** [comment]
But they are at: /var/www/html/roundcubemail-1.3.6/logs

**Comment by peterkroon** [comment]
OK, found a problem.
DB: MariaDB

Query:
````sql
SELECT * FROM `contacts` AS c
LEFT JOIN `contactgroupmembers` AS m 
ON (m.`contact_id` = c.`contact_id`)
WHERE c.`del` <> 1 AND c.`user_id` = '1'
AND m.`contactgroup_id` = '8'
ORDER BY CONCAT(c.`surname`, c.`firstname`, c.`name`, c.`email`) ASC LIMIT 50;
````

The problem appears to be the ``CONCAT`` int the ``ORDER BY`` clause.
When removed the query is executed.

However the query below will execute:
````sql
SELECT c.*, m.* FROM `contacts` AS c
LEFT JOIN `contactgroupmembers` AS m 
ON (m.`contact_id` = c.`contact_id`)
WHERE c.`del` <> 1 AND c.`user_id` = '1'
AND m.`contactgroup_id` = '8'
ORDER BY m.`contact_id`  ASC LIMIT 50;
````

When replacing ``m.`contact_id` `` with ``c.`contact_id` `` the query will fail.
Not sure why this is actually.

**Comment by alecpl** [comment]
You mean the query fails with an error or just returns no records? Anyway looks like MariaDB issue. What MariaDB version?

**Comment by peterkroon** [comment]
The query fails in phpmyadmin and returns no records in the roundcube program.
Server version: 5.5.41-MariaDB - MariaDB Server 

A simple restart of the DB instance got the query going.
Solved.
