### ISSUE TITLE
IMAP errors when deleting all emails in folder selected with Select >> All

### ISSUE THREAD

**Issue by mjauvin** [roundcube/roundcubemail#6264]
I am running RoundCube 1.3.3 on a server running cPanel which uses Dovecot IMAP server. Whenever I select all email in a folder using the "Select >> All" dropdown at the bottom of the screen and click "Delete", I get the following error:

  Server Error: UID STORE: Error in IMAP command UID STORE: Invalid uidset (0.001 + 0.000 secs).

Note1: When selecting the emails using any other method (manually, per-page), the problem does not happen.

Note2: When doing the same using Horde (same server, same IMAP server), the problem does not happen.

**Comment by alecpl** [comment]
Are you sure this is 1.3.3? See this: https://www.roundcubeforum.net/index.php/topic,24829.msg67801.html

**Comment by mjauvin** [comment]
The release files seems to indicate version 1.3.3.

The bug report/patch you are refering to at https://github.com/roundcube/roundcubemail/commit/0c9074f286c5f51ac9aeeafa2f0758dae71c4620#diff-c7705ff6b22d5b6352056d325432418a seems to be pretty recent, no?

**Comment by alecpl** [comment]
Yes, but maybe cPanel applies some patches on top of vanilla 1.3.3? Is that one line of code different in your version?

**Comment by mjauvin** [comment]
You may be right, applying the patch definitely solves the problem.

I'll investigate with cPanel, thanks for your prompt support on this @alecpl

**Comment by mjauvin** [comment]
FWIW, I cloned the git repository and checked the different tags and the patch that fixes this is only available from tag 1.3.6.

Thanks.
