### ISSUE TITLE
Error creating Keys 

### ISSUE THREAD

**Issue by WildcatKSS** [roundcube/roundcubemail#6265]
I enabled enigma as pluging but during the creation of the PGP I get the following error.

Your web browser does not support cryptography. Unable to generate a key pair!

Does someone has the sollution to solve this problem.

**Comment by alecpl** [comment]
Use different browser or generate the keypair on your system (usin gnupg) and import to Enigma. What browser are you using?

**Comment by WildcatKSS** [comment]
I used Chrome and IE and i have the same problem. Is there an import functies within roundcube?

**Comment by alecpl** [comment]
There is. You don't see Import button in Settings > PGP Keys? What Roundcube version? What Chrome version (this browser should work). Also IE 11 is supported by the most recent Roundcube release.

**Comment by alecpl** [comment]
Just don't use that Roundcube version. It's buggy and insecure. Upgrade to 1.3.6.

**Comment by WildcatKSS** [comment]
Thanks i will upgrade

**Comment by WildcatKSS** [comment]
Thanks it works

**Comment by DXXS** [comment]
After enabling the 'enigma' plugin that came with my install, I'm getting the same "...browser does not support cryptography..." message : Tried Safari 15.2, FireFox 94.0.2, Chrome 101.0.4951.64... Using Roundcube Webmail 1.4.11, with Enigma 0.8...

**Comment by fpiraneo** [comment]
Same issue here with RoundCube 1.4.13 and Enigma 0.8. Any help apreciated. Tested with Safari 15.5 and Vivaldi 5.3.2679.61 (Chrome fork).
