### ISSUE TITLE
Use of undefined constant IDNA_DEFAULT

### ISSUE THREAD

**Issue by gabrielt** [roundcube/roundcubemail#6266]
Hi,

Found this in the log file:

> "Use of undefined constant IDNA_DEFAULT - assumed 'IDNA_DEFAULT' (this will throw an Error in a future version of PHP) in [redacted]/program/lib/Roundcube/rcube_utils.php on line 908"

Here:

`$options = IDNA_DEFAULT;`

Change to:

`$options = defined('IDNA_DEFAULT') ? IDNA_DEFAULT : null;`

Cheers.

**Comment by alecpl** [comment]
It has been already fixed. Duplicate.
