### ISSUE TITLE
plaintext password in log (managesieve)

### ISSUE THREAD

**Issue by pikachuprof** [roundcube/roundcubemail#6268]
I tried using the managesieve plugin but it did not work (some fatal error about a missing "Net _Sieve" class, but thats not the main issue here). So I looked up the error-log (apache2) and I found my password there in plaintext. This should obviously be removed or masked I think?

Log-File:

 [Fri Apr 27 14:41:47.401328 2018] [:error] [pid 1270] [client 137.250.17.64:58372] PHP Fatal error:  Uncaught Error: Class 'Net_Sieve' not found in /var/www/webmail/plugins/managesieve/lib/Roundcube/rcube_sieve.php:68\nStack trace:\n#0 /var/www/webmail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php(218): rcube_sieve->__construct('m----@-----...', '**PLAIN-TEXT-PASSWORD**', 'localhost', 4190, NULL, false, NULL, false, NULL, NULL, NULL, NULL, NULL)\n#1 /var/www/webmail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php(96): rcube_sieve_engine->connect(m----@-----....', '**PLAIN-TEXT-PASSWORD**')\n#2 /var/www/webmail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php(289): rcube_sieve_engine->start()\n#3 /var/www/webmail/plugins/managesieve/managesieve.php(224): rcube_sieve_engine->actions()\n#4 /var/www/webmail/program/lib/Roundcube/rcube_plugin_api.php(493): managesieve->managesieve_actions()\n#5 /var/www/webmail/index.php(293): rcube_plugin_api->exec_action('plugin.managesi...')\n#6 {main}\n  thrown in /var/www/webmail/plugins/managesieve/lib/Roundcube/rcube_sieve.php on line 68, referer: https://webmail.*****.***/?_task=settings

**Comment by alecpl** [comment]
Disable traces in PHP config. This is generated by PHP, we can't really change that.
