### ISSUE TITLE
global "mark all folders as read" does not update folder unread messages count label

### ISSUE THREAD

**Issue by fsantiago07044** [roundcube/roundcubemail#6270]
Hello. I'm running RCM 1.3.6 and viewing it in Chrome 66.0.3359.117 on fedora 27.

within the primary mail section, in folder actions i selected mark all as read, all folders, and it seems to have worked except the folders listing still shows unread message counts for each folder in question. clicking on them doesn't change it and i can see the messages have been marked read in fact. if i leave the section, for example by going to settings or contacts and then return to mail, they are now properly blank. not a biggy but just wanted to mention it. thanks for an awesome product.

**Comment by fsantiago07044** [comment]
sorry, my rcm build is from the official project website / tar ball, not from a git clone of the repo. so i guess official 1.3.6 release?

**Comment by alecpl** [comment]
Try with disabled all plugins. Check browser console for errors.

**Comment by alecpl** [comment]
No feedback. Works for me.

**Comment by grape6** [comment]
This happens very rarely, and seems only after log in. and for any folder except INBOX
Can be reproduced in that way: mark some messages as unread in any other folder (tmp), log out,
log in, select another (arch), mark all messages as read, and for (tmp) folder counter is not updated.
