### ISSUE TITLE
move watermark.html into template system

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6271]
watermark.html is a static html file if it was processed through the template system it would allow plugins to alter the content of that screen and/or perhaps allow config of the watermark image via `skin_logo` or similar option.

For example: To put different watermark images for different tasks. Or to use what is currently "empty" space immediatly after login to display tips or update news or similar.

**Comment by alecpl** [comment]
We have an old ticket for this already. Duplicate of #5025.

**Comment by thomascube** [comment]
There's a plugin for this: https://plugins.roundcube.net/packages/roundcube/customizr
