### ISSUE TITLE
Upgraded to ubuntu 18.04/php7.2 now get the following

### ISSUE THREAD

**Issue by L1ghtn1ng** [roundcube/roundcubemail#6282]
As stated above I get the following https://paste.ubuntu.com/p/y2P289J8hQ/

I am using firefox latest stable version with adblock plus. I have no logs for roundcube in the logs dir so I cannot find out what is wrong.

**Comment by alecpl** [comment]
Looks like problem with PHP not working. Not a Roundcube issue.

**Comment by L1ghtn1ng** [comment]
Okay thanks can you tell me what PHP packages roundcube actually uses then I should be able to hopefully get it working, thanks
________________________________

**Comment by alecpl** [comment]
This is not about extensions, this is a general PHP/Apache configuration issue.
