### ISSUE TITLE
Elastic: Lock icon for encrypted emails does not show in mobile layout

### ISSUE THREAD

**Issue by ryan77627** [roundcube/roundcubemail#6296]
Hello! I don't know if this is intended behavior or not but if I received a PGP protected email on Roundcube desktop using elastic, I see a lock icon in the bottom right hand corner of the email in the inbox. However, when I go to the account on mobile the lock icon isn't there. Is this intended behavior? If you guys were already aware of this, just close the issue and sorry for repeating :D.

**Comment by alecpl** [comment]
The attachment and flag icons are intentionally hidden on mobile. We'll re-consider this with a UX expert.

**Comment by alecpl** [comment]
Fixed.
