### ISSUE TITLE
No logs at all

### ISSUE THREAD

**Issue by harsszegi** [roundcube/roundcubemail#6297]
Hello,
completely lost: I have a Ubuntu 18.04 with php-fm 7.2, it "suddenly" stopped working.
I have checked phpinfo, seems to be just fine, added logging to config.inc.php, checked
/var/log/nginx for access errors, but I couldn't see anything.
Tried re-running the installer as well, no problems were seen at all, could even tested IMAP/SMTP,
everything was just fine.
Currently my roundcube installation a.) produces no logs b.) doesn't see the IMAP/SMTP servers
configured.
Any idea what to set and where to have logs again?
Thanks,

**Comment by crasheg** [comment]
Check where logs must be saved

> // log driver:  'syslog' or 'file'.
> $rcmail_config['log_driver'] = 'file';

Check enable for logging in roundcube config

> // Log sent messages to <log_dir>/sendmail or to syslog
> $rcmail_config['smtp_log'] = false;
> // Log successful logins to <log_dir>/userlogins or to syslog
> $rcmail_config['log_logins'] = true;
> // Log session authentication errors to <log_dir>/session or to syslog
> $rcmail_config['log_session'] = true;
> // Log SQL queries to <log_dir>/sql or to syslog
> $rcmail_config['sql_debug'] = true;
> // Log IMAP conversation to <log_dir>/imap or to syslog
> $rcmail_config['imap_debug'] = true;
> // Log user login-passwords
> $rcmail_config['save_passwords'] = true;
> // Log LDAP conversation to <log_dir>/ldap or to syslog
> $rcmail_config['ldap_debug'] = true;
> // Log SMTP conversation to <log_dir>/smtp or to syslog
> $rcmail_config['smtp_debug'] = true;

Logs must be saved in roundcube directory /logs

**Comment by harsszegi** [comment]
no idea :(

drwxr-xr-x  11 www-data www-data    4096 máj   20 11:25 ./
drwxr-xr-x 588 root     root       20480 máj    2 07:16 ../
drwxr-xr-x   2 www-data www-data    4096 máj    2 06:52 bin/
-rw-r--r--   1 www-data www-data  149032 szept  4  2017 CHANGELOG
-rw-r--r--   1 www-data www-data    1092 máj    2 07:08 composer.json
-rw-r--r--   1 www-data www-data    1034 szept  4  2017 composer.json-dist
-rwxr-xr-x   1 www-data www-data 1177676 nov    8  2015 composer.phar*
drwxr-xr-x   2 www-data www-data    4096 máj   20 20:43 config/
-rw-r--r--   1 www-data www-data    3848 ápr   14 20:52 config.inc.php.sample
-rw-r--r--   1 www-data www-data    3146 ápr   14 20:52 .htaccess
-rw-r--r--   1 www-data www-data   12726 ápr   11 13:14 index.php
-rw-r--r--   1 www-data www-data   10842 szept  4  2017 INSTALL
-rw-r--r--   1 www-data www-data   35147 szept  4  2017 LICENSE
drwxrwxr-x   2 www-data www-data    4096 máj   20 11:37 logs/
drwxr-xr-x  37 www-data www-data    4096 okt   25  2017 plugins/
drwxr-xr-x   8 www-data www-data    4096 okt   25  2017 program/
-rw-r--r--   1 www-data www-data    3736 szept  4  2017 README.md
drwxr-xr-x   4 www-data www-data    4096 okt   25  2017 skins/
drwxr-xr-x   7 www-data www-data    4096 máj    2 06:52 SQL/
drwxrwxr-x   2 www-data www-data    4096 máj   19  2017 temp/
-rw-r--r--   1 www-data www-data    3579 szept  4  2017 UPGRADING
drwxr-xr-x   9 www-data www-data    4096 nov    7  2015 vendor/

root@harsszegi:/usr/share/roundcube# ll logs/
drwxrwxr-x  2 www-data www-data 4096 máj   20 11:37 ./
drwxr-xr-x 11 www-data www-data 4096 máj   20 11:25 ../
-rw-rw-r--  1 www-data www-data   31 ápr   15  2013 .htaccess

// system error reporting, sum of: 1 = log; 4 = show, 8 = trace
$rcmail_config['debug_level'] = 8;

// log driver:  'syslog' or 'file'.
$rcmail_config['log_driver'] = 'file';

// log directory
$rcmail_config['log_dir'] = 'logs/';

// Log sent messages to <log_dir>/sendmail or to syslog
$rcmail_config['smtp_log'] = true;

// Log successful logins to <log_dir>/userlogins or to syslog
$rcmail_config['log_logins'] = true;

// Log session authentication errors to <log_dir>/session or to syslog
$rcmail_config['log_session'] = true;

// Log SQL queries to <log_dir>/sql or to syslog
$rcmail_config['sql_debug'] = true;

// Log IMAP conversation to <log_dir>/imap or to syslog
$rcmail_config['imap_debug'] = true;

// Log LDAP conversation to <log_dir>/ldap or to syslog
$rcmail_config['ldap_debug'] = true;

// Log SMTP conversation to <log_dir>/smtp or to syslog
$rcmail_config['smtp_debug'] = true;

**Comment by alecpl** [comment]
debug_level=1

**Comment by harsszegi** [comment]
Can I ask based upon what have you closed it? I understand that it SHOULD work as you have written, but the exact reason why I have opened the issue that it does NOT work currently on my system like that and I was looking for guidance. I have zero idea why would debug_level=1 work if trace level (=8) doesn't.

**Comment by tuxick** [comment]
config['debug_level']  was removed years ago, but if you find nothing in logs/, you might want to check apache/nginx/php-fpm logs.
