### ISSUE TITLE
Get rid of debug_level setting

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6298]
This option was always confusing
1. Some people miss the part that it is a sum of integer values (see #6297). Setting debug_level=8 disables error logging.
2. I think that no one is really using value 4. I don't. Many users don't understand that 4 can be only useful for developers, but if I'm not using it, then not so much.
3. Value 2 was never and probably will be never implemented.
4. Value 8 is not really used for anything.
5. This has nothing to do with debug, it's used for errors only (raise_error(), log_bug()).

So, the only valid use is for value 1 (or 0), with which user could disable error logging. However, is this really what we should care about? Using PHP's log_errors for this would be sufficient, imo.

ps. display_errors should be set to off. We could put it on user, but it breaks ajax and not everyone is aware of that.

@thomascube what do you think?

**Comment by thomascube** [comment]
@alecpl I absolutely agree. This was initially meant to be extended with some remote logging features but that never happened.

**Comment by alecpl** [comment]
Done.

**Comment by ivab-test** [comment]
Please add some note into Wiki https://github.com/roundcube/roundcubemail/wiki/Howto-Report-Issues#how-to-enable-them regarding this option being removed in the most recent Roundcube versions.
