### ISSUE TITLE
 Cyrillic names in addressbook after windows update (RC 1.3.6)

### ISSUE THREAD

**Issue by crasheg** [roundcube/roundcubemail#6299]
Hello, my installation is:

> Apache/2.4.33 (Win64) OpenSSL/1.0.2o PHP/7.2.5
> libmysql - mysqlnd 5.0.12-dev - 20150407
> mysqli,curl, mbstring,intl

After last update windows 10 to 1803 (biuld 17134.48) i have problem with addressbook. All contacts in list shown as empty lines (red line).
![image](https://user-images.githubusercontent.com/20423457/40296199-aba11b4e-5ce4-11e8-9213-780685594dc2.png)
If i'll try to add new contact with cyrillic letters - in error log i getting DB Error((
![image](https://user-images.githubusercontent.com/20423457/40296224-b564c914-5ce4-11e8-870c-f72af79d2a08.png)
In MySQL DB `contacts`everything is fine - cyrillic is cyrillic.
![image](https://user-images.githubusercontent.com/20423457/40296236-bbe023b0-5ce4-11e8-8b07-000dfca80385.png)
I've tried to rollback apache to 2.4.20, php to 7.0, rouncube to 1.30 and everywhere i have same problem.

Any ideas?
Temporary resolve for this problem:

/program/include/rcmail.php

replace line 181

> setlocale(LC_ALL, $lang . '.utf8', $lang . '.UTF-8', 'en_US.utf8', 'en_US.UTF-8');

to 

> setlocale(LC_ALL, 'ru_RU.CP1251', 'rus_RUS.CP1251');

But i think it's no good(

**Comment by alecpl** [comment]
It looks like it breaks contact's display name. It is generated in rcube_addressbook::compose_display_name() from firstname and surname, but I don't see how it would create such a garbage. In any case lack or broken locale should not cause such issues.

Did you try with disabled all plugins? Use most recent version.

**Comment by crasheg** [comment]
I use filter in photoshop ))
problem in red line 
![image](https://user-images.githubusercontent.com/20423457/40299292-7923ccc0-5cee-11e8-89f2-9be88c7bbc2f.png)
there is no text(
![image](https://user-images.githubusercontent.com/20423457/40299337-990ca23c-5cee-11e8-9b1f-50fbfe2e5d8a.png)
but information from this contact in right side are shown!

**Comment by alecpl** [comment]
There's no need to tell the same story more than once. Answer to the questions or we won't be able to help you.

**Comment by crasheg** [comment]
> Did you try with disabled all plugins? Use most recent version.
Yes, i tried without plugins.
Tried roundcube 1.3.6, 1.3.3, same result(( 
I think problem in MySQL charset, but as i see - roundcube DB in correct chaarset? May be information shema corrupted?

**Comment by alecpl** [comment]
This is strange. As I see in the error log when you add a new contact, the surname and firstname is correct but full name is invalid. And this is generated in rcube_addressbook::compose_display_name(). If you'd know PHP a little bit you could do some debug there. On a first look at the code I don't see a problem.

The issue on contacts list is similar, but it might be something different, though the code is almost the same for this part.

**Comment by crasheg** [comment]
Ok, if i remove
> $fn = preg_replace('/\s+/', ' ', $fn);

Everything works fine

**Comment by alecpl** [comment]
Does it work if you change that line to:
```
$fn = preg_replace('/ +/', ' ', $fn);
```
?
Could you add `rcube::console($fn);` before that line and provide the logs/console file after a test (in unmodified text format)?

**Comment by crasheg** [comment]
> $fn = preg_replace('/ +/', ' ', $fn);
Works fine in this place, and show cyrillic names, but this modification doesn't resolve problem with adding new contact.

**Comment by alecpl** [comment]
Did you do this in  rcube_addressbook::compose_display_name()?

**Comment by crasheg** [comment]
rcube_addressbook::compose_list_name()

**Comment by alecpl** [comment]
Then you have to do this in both.

**Comment by crasheg** [comment]
It's very strange, but it works! )
Checked adding, deleting, modifying - all ok.
Made same changes in rcube_addressbook::compose_search_name() (line nember 640), because while typing name in compose mode, names too was not shown.

**Comment by alecpl** [comment]
Could you please also check `$fn = mb_ereg_replace('[:space:]+', ' ', $fn);`?

**Comment by crasheg** [comment]
))
![image](https://user-images.githubusercontent.com/20423457/40533587-eb0efb3c-600b-11e8-9498-4022080e4087.png)
this contact name is "webmaster" ))

**Comment by alecpl** [comment]
Still I'm unable to reproduce this. What returns `setlocale(LC_ALL, 'en_US.utf8')` on your system?

How about `$fn = preg_replace('/\s+/u', ' ', $fn);`?

**Comment by crasheg** [comment]
> echo setlocale(LC_ALL, 'en_US.utf8')

en_US.utf8

> $fn = preg_replace('/\s+/u', ' ', $fn);
works fine

**Comment by alecpl** [comment]
Thanks. Ok, then I think we can stay with `/u`. I guess that's the same as `$fn = mb_ereg_replace('\s+', ' ', $fn)`.

**Comment by alecpl** [comment]
preg_replace() is faster so we'll use that. Fixed.
