### ISSUE TITLE
Encoding cp850

### ISSUE THREAD

**Issue by Ratiborec** [roundcube/roundcubemail#6300]
Good day. I have Server error in client. So i found that 's because some letters have encoding cp850. 
Anybody know a decision?
Error log
PHP Notice:  No suitable function found for UTF-8 encoding in /usr/share/roundcubemail/program/lib/Roundcube/rcube_charset.php on line 276

**Comment by alecpl** [comment]
This is a notice not error. What is the problem? What version? What environment? What browser, etc.

**Comment by Ratiborec** [comment]
So i had a problem, that when i open RC i see 'Server error (OK)'. after this used thunderbird where i found spam letters with cp850 encoding. When i removed it , error is gone. 
As i have 50 email , it was a bad decision. 

My current version Roundcube Webmail 1.1.10.

i downloaded  rcube_charset.php from the newest version and now it's work good
