### ISSUE TITLE
Message list is not updated after moving ALL messages

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6310]
Message list is not updated if select all messages by menu Select->All & move them to another folder.
If messages are selected and moved via keys or mouse - it's ok.

**Comment by alecpl** [comment]
What version? What do you mean it's not updated? You mean you use "Move to..." option from "More..." menu? Are there any javascript errors in browser console?

**Comment by grape6** [comment]
RMC git. 
Message list remains the same on the screen after ...More->Move to.
Messages are moved really.
Seems no js erros (Dev tools -> Console->JS window, right?)

**Comment by grape6** [comment]
only 'contextmenu' plugin is enabled.

**Comment by grape6** [comment]
Yes

**Comment by grape6** [comment]
Yes, via context menu

**Comment by grape6** [comment]
If i use toolbar ..More button situation is the same.

**Comment by alecpl** [comment]
Confirmed regression.

**Comment by alecpl** [comment]
Fixed.
