### ISSUE TITLE
Can not send emails from our Roundcube account. Error 535 Authentication failed.

### ISSUE THREAD

**Issue by alfonso8969** [roundcube/roundcubemail#6311]
We can not send emails from our Roundcube account.

Neither from php nor from the web itself.

We have not made any changes, it has stopped working. 
We try to send more of 200 mails at once.

These are the values we use in PHP, but we can not send from the web either.

                                    $mail = new PHPMailer();
                                    $mail->IsSMTP();
                                    $mail->SMTPAuth = true;
                                    $mail->SMTPSecure = "ssl";
                                    $mail->Host = "ssl0.ovh.net";
                                    $mail->Port = 465;
                                    $mail->Username = our account;
                                    $mail->Password = our password;
                                    $mail->CharSet = "UTF-8";  
                                    $mail->Encoding = "quoted-printable";

Can you help us? It's urgent.

Thank you very much.

**Comment by alecpl** [comment]
If it worked and stopped working it is not Roundcube issue. What error? Check the error log. Provide configuration. Ask on mailing list or forum.
