### ISSUE TITLE
about large size file attachments

### ISSUE THREAD

**Issue by gadguy** [roundcube/roundcubemail#6314]
hi?
I'm wonjeh from South Korea.
I'm a newbie to roundcube.
I installed roundcube and using it very well
but I found there is no way to upload large size file like more than 1GB~2GB(http maximum size)

other e-mail program can upload large size file
the way to upload large size file is that the large size file will be uploaded to the webserver and only the download url link will be in the email.

anyone know if there is plugin for that? or can anyone develope the plugin?

**Comment by alecpl** [comment]
Ask on mailing list or forum.

**Comment by gadguy** [comment]
hi?
thanks for the reply,
I asked the forum(https://www.roundcubeforum.net/index.php), but no one replies yet
and i didn't know that if there is mailing list
thanks i will ask on mailing list
