### ISSUE TITLE
Emails goes to SPAM folder for no reason 

### ISSUE THREAD

**Issue by xponcio** [roundcube/roundcubemail#6316]
Dear all,

I wuld like to request your expertise. all emails goes to SPAM folder for no reason. Would you be able to give me some guidances?

KR
João

**Comment by alecpl** [comment]
Nope. That's most likely not Roundcube issue.

**Comment by xponcio** [comment]
Roger.
I only asked because it is reported by a considerable number of users on the internet.

Thks anyway
