### ISSUE TITLE
Upload form visible at wrong place in UI

### ISSUE THREAD

**Issue by sagiadinos** [roundcube/roundcubemail#6317]
Hello,

Same issue as described here:
#https://github.com/roundcube/roundcubemail/issues/5814

Version 1.3.6 
Fresh install on Debian Jessie

regards

**Comment by thomascube** [comment]
Likely a caching issue. Restart your webserver to clear php cache and shift+reload the page in your browser.

**Comment by sagiadinos** [comment]
Thx! Apache restart worked.
