### ISSUE TITLE
Keep getting logged out after sending or responding to an email

### ISSUE THREAD

**Issue by cekirby13** [roundcube/roundcubemail#6318]
For the past few days, every time a either send or respond to an email, the system will keep me out once I go back to my inbox. This has happened 9 times this morning alone and I've only been working for an hour. What is the problem?

**Comment by alecpl** [comment]
Are you the server admin or a user?

**Comment by cekirby13** [comment]
Admin

---
Crystal Kirby
Aggressive Waste Disposal, Inc.
713-631-1900 (p)
713-633-9775 (f)
crystal@aggressivewaste.com
www.aggressivewaste.com

**Comment by alecpl** [comment]
Then why don't you provide more info. What browser? What version? What plugins? What errors in log or browser console? Etc.

**Comment by cekirby13** [comment]
I'm sorry but I misread your message. I'm the admin of our account, not 
the server. I'm a user.

CK

---
Crystal Kirby
Aggressive Waste Disposal, Inc.
713-631-1900 (p)
713-633-9775 (f)
crystal@aggressivewaste.com
www.aggressivewaste.com

**Comment by alecpl** [comment]
Then we can't help you. Ask your server admin.
