### ISSUE TITLE
Using window.open with a mailto: link will cause roundcube to call back()

### ISSUE THREAD

**Issue by def324** [roundcube/roundcubemail#6319]
We encountered an issue with a tool that we use that generates mailto: links from JavaScript. The specific method is to call window.open with a "mailto:" link.

The roundcube mailto: hanlder seems to pick up the link properly but the app.js ends up calling the window.back() function resulting in a return to the original page:
https://github.com/roundcube/roundcubemail/blob/5e3868eb1028813afee699c9fcba19bf36fe1e59/program/js/app.js#L4439

We've recreated a simple test scenario: [test.zip](https://github.com/roundcube/roundcubemail/files/2081333/test.zip)

Does anyone know what the window.back() call is supposed to achieve? For now we have simply removed the ".back()" part and it does not seem to have negative effects. We are wondering what kind of negative impact it may have.

Thanks in advance for any help!

**Comment by alecpl** [comment]
This code is supposed to be executed if you use "Open in new window" button in mail compose screen. It switches back the opener window to the previous view (first it does some checks to make sure the opener window is part of Roundcube).

**Comment by def324** [comment]
Thanks for the quick response. I've been looking through the code and trying to figure out how to fix this behavior. While I don't yet fully understand yet how this is supposed to work yet, it seems there needs to be one more check before doing the "back()" call so that scenarios like mine don't just go back to the original page. Do you think something like this may work?

if (opener.history.length > 1 && !opener_rc.env.opened_extwin)
          opener.history.back();

**Comment by alecpl** [comment]
Why do you use window.open()?

I think the fix would be rather in detecting the opener window:
```diff
diff --git a/program/js/app.js b/program/js/app.js
index be071e7..74caa93 100644
--- a/program/js/app.js
+++ b/program/js/app.js @@ -9680,7 +9680,7 @@ function rcube_webmail()

       // catch Error: Permission denied to access property rcmail
      try {
-       if (win && !win.closed) {
+       if (win && !win.closed && win !== window) {
          // try parent of the opener window, e.g. preview frame
          if (deep && (!win.rcmail || win.rcmail.env.framed) && win.parent && win.parent.rcmail)            win = win.parent;
```

**Comment by def324** [comment]
It is actually a third party application that we have no control over. It was working fine with another browser based email program that we used before but when we switched to roundcube we saw this behavior.

We will try to implement your suggestion in our environment and let you know if that fixes the problem. Thanks for your help!

**Comment by alecpl** [comment]
@def324 if you confirm the fix I will push it.

**Comment by def324** [comment]
We haven't been able to test it yet since we are waiting for a maintenance window. I'll update you by next week.

**Comment by def324** [comment]
We were able to test the fix in production and observed it for a few weeks, it's working perfectly fine on our end. Please feel free to push it and thanks for all the help!

**Comment by alecpl** [comment]
Fixed.
