### ISSUE TITLE
Garbage collector does not work

### ISSUE THREAD

**Issue by domelek** [roundcube/roundcubemail#6323]
Hi,
I was looking why the temp directory is plenty of files modified over a week ago when I have temp_dir_ttl set to 12h. It seems that the function gc_run() in program/lib/Roundcube/rcube.php is not called anywhere. RC v. 1.3.6.

**Comment by alecpl** [comment]
I guess you're using Debian which has PHP's garbage collector disabled. See session.gc_* options in php.ini. You can also run bin/gc.sh script using cron.

**Comment by domelek** [comment]
I have set these variables:
session.gc_divisor=1
session.gc_maxlifetime=21600
session.gc_probability=2

to meet the conditions on each request:

public function gc_run()
    {
        $probability = (int) ini_get('session.gc_probability');
        $divisor     = (int) ini_get('session.gc_divisor');

        if ($divisor > 0 && $probability > 0) {
            $random = mt_rand(1, $divisor);
            if ($random <= $probability) {
                $this->gc();
            }
        }

But I can't find where the gc_run is called. Running the shell is not possible in my environment.

**Comment by alecpl** [comment]
rcube::gc_run() is not used by Roundcube. Garbage collector is invoked by session handlers. 
```
$this->session->register_gc_handler(array($this, 'gc'));
```

**Comment by domelek** [comment]
Thanks for the tip. The problem is in session storage handling when the php backend is selected. For db, redis and memcache the method register_session_handler() is being run, whereas for the php not, so the handlers are not being set. Once I change the driver for the db, the GC runs well and the temp directory is flushed.
