### ISSUE TITLE
Mail preview toggle missing

### ISSUE THREAD

**Issue by upstatebreaker** [roundcube/roundcubemail#6324]
It appears that in a more recent release, the toggle for mail preview has been removed. We can no longer toggle the small preview window from within the main mail view. 

Instead, we must go into the settings > mailbox view > Layout and toggle the setting from 'List (no mail preview)' to 'Desktop (wide list and mail preview below)'.

For a single user, this would not seem like an issue, since the user would most likely choose one way or the other, without a need to toggle. However, in many business environments, there are many users utilizing the webmail client. Some users prefer having the window open, while some do not.

Was this removed due to a subsequent bug of the feature being available? Or was this just a design change? What would be the impact of reimplementing this functionality?

**Comment by alecpl** [comment]
You can also switch the mode in messages list options dialog.

**Comment by mikoladz** [comment]
Why has this issue been closed? I have just upgraded from some old version to 1.3.8 and the button to hide/unhide preview pane is gone. Can we have it back?

**Comment by alecpl** [comment]
No, the button has been replaced with the mode option in list options dialog.

**Comment by mikoladz** [comment]
The mode option in list options dialog is not that convenient as the button used to be. I know it's only 3 clicks vs 1 click, but isn't it a regression?
