### ISSUE TITLE
ISPConfig driver

### ISSUE THREAD

**Issue by marcin110987** [roundcube/roundcubemail#6327]
Hi,
is it possible to add ISPConfig driver https://www.ispconfig.org/

**Comment by alecpl** [comment]
As I know all you need is the sql driver. You should find some hints how to configure it in google.

**Comment by marcin110987** [comment]
Thx, for answer. I have searched a lot of time in google how to configure with sql driver, but I didn't find a solution. If you know any useful tutorial, I'd be grateful for the link.
