### ISSUE TITLE
Attachments not downloading

### ISSUE THREAD

**Issue by PaulaH** [roundcube/roundcubemail#6328]
Having an issue where Roundcube is not downloading an attachment.  The attachment appears in the email, but strips it out once "Send" is hit.  This has only occurred in the last week.  Have been successfully attaching attachments up until then.

**Comment by thomascube** [comment]
I'm sorry but you wrote to the wrong people. We don't host your e-mails and we're not responsible for the system you're using to access them. Please contact your internet hosting provider or IT responsible for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Roundcube is not a service but free software which your hosting provider installed on their servers.
