### ISSUE TITLE
roundcube keeps loading when I request a mail (except when double click)

### ISSUE THREAD

**Issue by ChazyTheBest** [roundcube/roundcubemail#6329]
I deleted my current installation of roundcube (including the database) and downloaded a clean latest version. I installed it, everything ok, but it is happening again.

When I login, and I click a mail, roundcube keeps loading and it never shows it. It only shows the mail if I double click, it opens a new window showing it. I've tried looking for errors but I really can't find anything, in the browser network requests, in the server journalctl (dovecot login logs looks fine)... It is possible that I'm not able to identify it, I really don't know what I'm looking for.

However I can send mail if/when roundcube is not loading anything, so the only thing I can do in roundcube is: refresh, compose, navigate the folders and options (but same when I request an option, it keeps loading), these are the few things that finish loading. I gotta mention that when I send mail, it gets sent, but roundcube doesn't know, it's like it never receives response, either that or it doesn't know it did receive one.

The only thing that changed with dovecot is the driver for the passdb, it's now getting the user info from the database, so the driver changed from passwd-file to sql. I don't see how it can be related...

Roundcube is in the same machine as dovecot and postfix and it was working until I migrated from config files to mariadb (for both). This looks like a roundcube only problem, as I can login from other clients (desktop clients) and everything works fine.

This is the specific PHP-FPM config:

```ini
[roundcube_mail]
user = http
group = http
listen = /run/php-fpm/mail.roundcube.sock
listen.owner = http
listen.group = http
listen.mode = 0660
listen.allowed_clients = 127.0.0.1
pm = dynamic
pm.max_children = 2
pm.start_servers = 1
pm.min_spare_servers = 1
pm.max_spare_servers = 2
pm.max_requests = 100
access.log = /srv/protected/roundcube/logs/php-fpm_access.log
slowlog = /srv/protected/roundcube/logs/php-fpm_slow.log
request_slowlog_timeout = 8s
request_terminate_timeout = 17s
rlimit_files = 1024
rlimit_core = 0
catch_workers_output = yes
; PHP per vhost/pool values
php_admin_value[max_execution_time] = 16                                        ; 10
php_admin_value[max_input_time] = 32                                            ; 60
php_admin_value[memory_limit] = 64M                                             ; 5M
php_admin_value[error_log] = /srv/protected/roundcube/logs/php-fpm_error.log
php_admin_value[post_max_size] = 32M                                            ; 1M
php_admin_value[sys_temp_dir] = /srv/protected/roundcube/tmp/
php_admin_value[file_uploads] = On                                              ; Off
php_admin_value[upload_tmp_dir] = /srv/protected/roundcube/uploads/
php_admin_value[upload_max_filesize] = 25M                                      ; 0
php_admin_value[max_file_uploads] = 10                                          ; 0
php_admin_value[session.save_path] = /srv/protected/roundcube/sessions/
php_admin_value[session.auto_start] = Off                                       ; ?
php_admin_value[suhosin.session.encrypt] = Off                                  ; ?
php_admin_value[mbstring.func_overload] = Off                                   ; ?
php_admin_value[soap.wsdl_cache_dir] = /srv/protected/roundcube/tmp/
```

**Comment by alecpl** [comment]
Usually this is caused by `add_header X-Frame-Options DENY` or something similar in web server config.

**Comment by ChazyTheBest** [comment]
Oops... Looks like it. Thanks.
