### ISSUE TITLE
Docker image SMTP not working

### ISSUE THREAD

**Issue by GitRon** [roundcube/roundcubemail#6332]
Hi there,

I'm using the latest docker image of roundcube. The IMAP is working like a charm but I cannot send emails.

Here's my local docker-compose.yml:

`version: '2'

services:
  roundcube:
    image: roundcube/roundcubemail
    environment:
        ROUNDCUBEMAIL_DEFAULT_HOST: ssl://mail.host.com
        ROUNDCUBEMAIL_DEFAULT_PORT: 143
        ROUNDCUBEMAIL_SMTP_SERVER: ssl://mail.host.com
        ROUNDCUBEMAIL_SMTP_PORT: 587
        ROUNDCUBEMAIL_PLUGINS: archive,zipdownload
        ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE: 5M
    ports:
      - 4000:80
    restart: always`

I experience the same problems with a different mailserver and on my deployed version as well.

I tried ssl-protocol with port 587 and 465. I switched the protocol to tls. But nothing seems to work.
When I use tls-protocol an port 465 I get the "sending mail" toast but then, in the shell I get this error: 

>  SMTP Error: Connection failed: Failed to connect socket: Connection refused in /var/www/html/program/lib/Roundcube/rcube.php on line 1667

Any ideas what I might be doing wrong?

Thanks a lot! Roundcube is really great, would be a pitty if I had to switch to something else because of this SMPT issue.

Ron

**Comment by aspettl** [comment]
Hi

Are you sure that port 465 or port 587 are open on the email host and reachable from your machine (check firewalls)? "Connection refused" sounds like it doesn't even get to the stage where encryption is negotiated.

I can confirm that the Docker image is not broken per se, I'm using it with port 587 and "tls://mail.host.com".
(Alternatively, SSL should work with port 465. One can also try port 25 with TLS, but using the submission port 587 is recommended - if available.)

Regards
Aaron

**Comment by GitRon** [comment]
Hi @aspettl,

when I use Thunderbird the connection works like a charm so the mailserver must be configured correctly.

Any suggestions? :(

Thanks
Ron

**Comment by thomascube** [comment]
You might want to try `tls://mail.host.com` for `ROUNDCUBEMAIL_SMTP_SERVER`. Compare with the exact settings in Thunderbird, especially the "connection security" setting. If that is set to STARTTLS, the suggested `tls://` prefix is needed.

**Comment by GitRon** [comment]
Thanks for the input. I did exactly as in Thunderbird :(

I tried now with tls and ssl on Port 25 but the best I get is this:

 SMTP Error: Connection failed: Failed to connect socket: fsockopen(): unable to connect to ssl://mail.host.com:25 (Unknown error) 

Any more ideas? Can't be that hard I figure...

Thanks!
Ron

**Comment by alecpl** [comment]
Usually smtp servers don't use SSL on port 25. It is either ssl:// on port 465 or tls:// on port 587 (or 25).

It may also by problem with certificate validation. Then you'd need to set smtp_conn_options, but I don't know how's that implemented in the docker container.

**Comment by GitRon** [comment]
I had a look at the extended options but I don't know how to use this with docker-compose. How can I move my custom php-config file inside the docker-image? The `run` command from the docds doesn't work for me.

**Comment by GitRon** [comment]
Alright, finally fixed it!

Add to the `docker-compose`:

```
volumes:
    - ./config/config.php:/var/roundcube/config/config.php
```

And then create a config-file:

```
<?php
// SMTP username (if required) if you use %u as the username Roundcube
// will use the current username for login
$config['smtp_user'] = '%u';

// SMTP password (if required) if you use %p as the password Roundcube
// will use the current user's password for login
$config['smtp_pass'] = '%p';
```

But still, should work by default, right? Maybe you should address this issue. Took me about 4-5h in total to get it to work.

**Comment by thomascube** [comment]
This issue is now tracked in https://github.com/roundcube/roundcubemail-docker/issues/24
