### ISSUE TITLE
Roundcoube (1.3.6) displaying "=>" when in comment line within HTML mail

### ISSUE THREAD

**Issue by axmo12** [roundcube/roundcubemail#6333]
When there's a "=>" included in a comment within an HTML mail, roundcube is displaying "=>" and some more text after that in the normal view.

![bug_roundcube_mm_02](https://user-images.githubusercontent.com/10323208/41772394-c7099468-7618-11e8-9713-cf8ba956b221.png)
![bug_roundcube_mm_01](https://user-images.githubusercontent.com/10323208/41772395-c72c26d6-7618-11e8-8423-c8e97f1f35d5.png)

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Fixed.
