### ISSUE TITLE
Error mixed active content in javascript console

### ISSUE THREAD

**Issue by gianlucagiacometti** [roundcube/roundcubemail#6335]
I experienced this error in javascript console:

Mixed active conten blockedt (mixed active content) “http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/fonts/fontawesome-webfont.woff2?v=4.3.0”

Website https://mywebmail.mydomain.tld
Ubuntu 18.04
PHP 7.2.5
RC 1.4-git
All plugins disabled

I have no idea about the reason. I searched for "maxcdn" and "bootstrapcdn" and I found nothing.
Any ideas?

**Comment by alecpl** [comment]
That comes with the email message. Reason is that it is http:// while the webmail is using https://. There is a plugin that passes such resources via proxy, but I'm not sure it works with fonts. https://github.com/evandrofisico/roundcube-imageproxy
