### ISSUE TITLE
Possibility to add "Search Folders" like Outlook

### ISSUE THREAD

**Issue by gloony** [roundcube/roundcubemail#6336]
Possibility to add **Search Folders**, like _Unreads_ items or _Flagged_.
With a proper URL for each, like _?_task=mail&_mbox=UNREAD_ or _?_task=mail&_sbox=UNREAD_
And with a counter of items in these folders.

This functionality would be awesome, I try for a while to make it by a plugins but I failed since a long time now.

In Outlook it these folders : 
![https://www.pei.com/wp-content/uploads/2016/06/SearchFoldersDefault.png](https://www.pei.com/wp-content/uploads/2016/06/SearchFoldersDefault.png)
And the result, on roundcude, will be : 
![https://i.imgur.com/n62f2To.png](https://i.imgur.com/n62f2To.png)

**Comment by alecpl** [comment]
I guess at some point we'll implement saved searches for mail. A slightly different thing would be support for virtual folders (as an imap server feature).

Anyway, we have a ticket for this already #5039.
