### ISSUE TITLE
Elastic: Install instruction don't work

### ISSUE THREAD

**Issue by michacassola** [roundcube/roundcubemail#6337]
The install instructions in the elastic readme don't work.
When will the theme that makes roundcube finally a viable option be out?
Or maybe an installable version would be nice?

**Comment by alecpl** [comment]
Works for me. Could you be more specific? Did you install javascript dependencies? It will be available with 1.4-beta (hopefully in July).

**Comment by thomascube** [comment]
I'm voting again for #6284 :-)

**Comment by michacassola** [comment]
I only followed the install instructions. If there are dependencies other than the less to css converters that are not mentioned in those instructions then I did not install them.
Please @alecpl tell me what additional dependencies I need and add them to the Install Instructions of the Elastic Readme.
Thank you very much!

**Comment by alecpl** [comment]
It's bootstrap (and lessjs for devel_mode). https://github.com/roundcube/roundcubemail/blob/master/INSTALL#L54

**Comment by michacassola** [comment]
Thank you very much @alecpl

**Comment by sblantipodi** [comment]
is there a user guide for "non developers"?
I don't want to develop on roundcube or elastic, I simply would like to install this wonderful theme on my current roundcube installation. how can I do it?

**Comment by alecpl** [comment]
You can't install it on anything than git-master.

**Comment by sblantipodi** [comment]
@alecpl Is there a guide on how to install it? But is it considered "stable"? Do you recommend using it? Thanks!

**Comment by alecpl** [comment]
When it will be considered stable we'll release 1.4.0. The guide is in INSTALL file.

**Comment by sblantipodi** [comment]
Ok thanks!!!

**Comment by michacassola** [comment]
How long until 1.4? Seems the beta milestone has been stuck on 98% for months.

**Comment by alecpl** [comment]
Soon.
