### ISSUE TITLE
The parameters of the database connection are correct, but they are not connected

### ISSUE THREAD

**Issue by jnjsj** [roundcube/roundcubemail#6338]
When I was in the /config/config. Inc.php  configuration database user name and password after, ready to install when prompted even database, began writing I thought it was a database name and password is wrong, then try again and again or not installed interface display.

My database name and password are: **roundcube**   **pxSymA7BWSacQvHi**

I wrote it this way:

**$config [' db_dsnw] = 'mysql: / / roundcube: pxSymA7BWSacQvHi @ localhost/roundcube';**

_There is absolutely no problem with the above parameters, I'm sure, because how many times have you checked them!_

I have tried many times and I don't know what's wrong. Could you help me? Thank you!

Error:
<img src="https://raw.githubusercontent.com/jnjsj/images/master/4444.png" alt="roundcube">

**Comment by alecpl** [comment]
There can be no spaces in DSN.

**Comment by jnjsj** [comment]
I checked carefully. There was no space, but there was
