### ISSUE TITLE
Elastic skin CSS doesn't work

### ISSUE THREAD

**Issue by JEEBEE123** [roundcube/roundcubemail#6339]
![untitled](https://user-images.githubusercontent.com/38722343/41975419-ca7c4bfa-7a59-11e8-9381-12371044fc68.png)

**Comment by alecpl** [comment]
Works for me. Read README.md in the skin folder. Install javascript dependencies an compile css.

**Comment by JEEBEE123** [comment]
I've done these steps

    $ lessc -x styles/styles.less > styles/styles.css
    $ lessc -x styles/print.less > styles/print.css
    $ lessc -x styles/embed.less > styles/embed.css

 bin/updatecss.sh --dir skins/elastic


Still doesnt work.

**Comment by alecpl** [comment]
How about bin/install-jsdeps.sh?  Do you use git-master?

**Comment by JEEBEE123** [comment]
Hi,

Thanks for your response. I've tried the install-sjdeps.sh, still no luck.

Maybe usefull to tell I'm using DirectAdmin Roundcube. I've placed the files in the skins folder myself.


Cheers.

**Comment by alecpl** [comment]
It works only with git-master version of Roundcube. It will not work with older versions like 1.3.

**Comment by JEEBEE123** [comment]
Hmm. Im working with Roundcube Webmail 1.3.6

**Comment by ericmode** [comment]
hi ! from a n[tuto_roundcube_yunohost_skin_larry .pdf](https://github.com/user-attachments/files/15550721/tuto_roundcube_yunohost_skin_larry.pdf)
