### ISSUE TITLE
Elastic: checkboxes add automatically an empty label tag

### ISSUE THREAD

**Issue by gianlucagiacometti** [roundcube/roundcubemail#6341]
I noticed that the function `show ` for an element `html_checkbox ` adds automatically an empty label after the input field as shown below.
I tried to use in the input flied the attributes 'title' or 'label' to fill it with no positive response.
I tried to analyse the code, but I couldn't get the point.
This happens only in RC 1.4-git, RC 1.3.6 is ok.

Ubuntu 18.04
PHP 7.2.5
RC 1.4-git
All plugins disabled

```
<tr class="form-group row form-check">
  <td class="title col-sm-4"><label for="rcmfd_prettydate" class="col-form-label">Date più leggibili</label>
  </td>
  <td class="col-sm-8">
  <input name="_pretty_date" id="rcmfd_prettydate" value="1" checked="checked" class="form-check-input icon-checkbox" type="checkbox">

  <label for="rcmfd_prettydate" title=""></label>

  </td>
</tr>
```

**Comment by alecpl** [comment]
Is this the Elastic skin? There's a code that "converts" checkboxes into "pretty checkboxes". That adds the label. If you define title attribute for the input it will be added to the label element.

What problem do you see in this actually?

**Comment by gianlucagiacometti** [comment]
Yes in Elastic and, thanks, now I can see where the code is.
I don't see any problem actually, My point is that a label with only title, which is already in the input tag, is useless and fills the html for no specific reason. You anyway need to specify another label element with the description of the checkbox.
Wouldn't it be more useful to add also the content to that pretty_checkbox label? Doing so if you need the description after the checkbox you wouldn't need to create another label element.

I'm creating a new plugin and my code looks like:

```
<input name="_additionalcss" id="rcmfd_additionalcss" value="1" class="additional-css-selector form-check-input icon-checkbox" title="CSS" type="checkbox">
<label for="rcmfd_additionalcss" title="CSS"></label>
<label for="rcmfd_additionalcss" class="additional-css-label">Additional CSS</label>
```

which looks a bit weird

**Comment by alecpl** [comment]
The label is required because that's the icon-image element. I don't think we can/should re-use the existing label for this.

**Comment by gianlucagiacometti** [comment]
Ok, I got your point of not re-using the label. I still can't get the reason why you need to double the title. Isn't it confusing?

**Comment by alecpl** [comment]
The hidden input element not always will have the same size and boundaries as the icon. So, if we want the title to be displayed over the icon...

**Comment by gianlucagiacometti** [comment]
Ok, so why not removing the attr title from the hidden input element? Just to keep the html tidy.
You can close this issue anyway, we both have more important real issues to solve and I understood that this is not an issue.

**Comment by alecpl** [comment]
We probably could remove it, yes. However, I didn't investigate all implications, e.g. screen readers.

**Comment by gianlucagiacometti** [comment]
Ok, my problem was actually connected to my lack of knowledge about CSS
I was complaining about the double label because this is what I had:

![immagine](https://user-images.githubusercontent.com/52405/42216114-fdde6b8e-7ec0-11e8-9938-582b84626cb8.png)

After studying carefully your forms.css, I successfully added in my css and I was able to manage the space between the button and the real description:

```
.additional-css-selector + label {
  padding-left: 1rem !important;
}
```

I guess this information about CSS should be shared to help plugin developers.
