### ISSUE TITLE
Elastic: save is missing in safari on mobile

### ISSUE THREAD

**Issue by gsmith-cp** [roundcube/roundcubemail#6342]
When using safari on ipad or iphone in the vertical orientation (forcing the elastic mobile layout to be used)

"save" is missing from the bottom of the screen when creating a new contact, canned response, signature, etc. when the form is first loaded. if the action is canceled and attempted again, save appears on the bottom of the screen

**Comment by alecpl** [comment]
I cannot reproduce. On my iPad the blue Save button disappears, but there's a Save button in the footer toolbar. Could you make a screenshot/photo? What is exact screen width in pixels on your device?

**Comment by gsmith-cp** [comment]
Here's what I'm seeing on iPad:

![ipad_screenshot](https://user-images.githubusercontent.com/40765833/42290464-653dc0b8-7f93-11e8-8379-e4879bdd5326.PNG)

**Comment by gsmith-cp** [comment]
More screen shots of missing save footers
:
![img_0004](https://user-images.githubusercontent.com/40765833/42291321-f9eb6b3e-7f98-11e8-9231-450336dc381d.PNG)
![img_0005](https://user-images.githubusercontent.com/40765833/42291323-fcf9bae2-7f98-11e8-805a-7de59cffe499.PNG)
![img_0006](https://user-images.githubusercontent.com/40765833/42291324-008b7fa6-7f99-11e8-846e-a9687b1105f3.PNG)

**Comment by gsmith-cp** [comment]
I'm still encountering this issue on ipad and iphone. The devices I'm using for testing are an ipad air 2, and an iphone 6  They're both set to their default resolution.

**Comment by alecpl** [comment]
Works for me with iPad 2 with iOS 9.3.5. There's a bar at the bottom of the page with Prev/Next/Save buttons. As I know it uses the same logical resolution: 768x1024. Maybe that's iOS version specific?
