### ISSUE TITLE
buttons missing since latest  ubuntu-update

### ISSUE THREAD

**Issue by ro-esp** [roundcube/roundcubemail#6343]
Hi there

I'm using ubuntu 16.04 and regularly do updates. After the one I did the day before yesterday (june 30th 2018 or so), I noticed that the buttons for previous/next message/page are missing.
My emailprovider is dds.nl , which uses roundcube. Someone in a ubuntu-usergroup suggested that I report it here. 

            groetjes, Ronaldo

**Comment by alecpl** [comment]
Without detailed information about the Roundcube installation, like version, skin used, plugins, etc. and your browser version, we can do nothing about it.

**Comment by alecpl** [comment]
Also a screenshot of the issue could help.
