### ISSUE TITLE
Roundcube filters fails when moving mail to folder containing ampersand in name

### ISSUE THREAD

**Issue by ktucows** [roundcube/roundcubemail#6344]
Hi folks, Tech Support peon here reporting a bug. I've searched for the keywords 'Roundcube' 'Filter' and 'Ampersand' and don't see any relevant results so far, so I figured I might as well report it.

Steps to replicate:

1. Create a folder or subfolder with an ampersand in its name I.E. Test & Test
2. Create a filter rule redirecting emails into this folder
3. Emails matching filter rule will arrive in inbox.

I don't know which PHP or Roundcube version we're using as that info isn't available to me, so if this issue has been fixed in a more recent update, please feel free to remove the post.

Thanks!

**Comment by alecpl** [comment]
Most likely server configuration issue. Usually it's a problem with charset encoding UTF-8 vs UTF-7-IMAP. Managesieve plugin has config option for this, imap servers sometimes also have options for this. Without debug info we can do nothing about it.
