### ISSUE TITLE
Confusing maximum allowed file size

### ISSUE THREAD

**Issue by WilliamDEdwards** [roundcube/roundcubemail#6347]
When a user uploads an attachment, Roundcube shows the PHP setting for the maximum allowed file size as can be seen here:

![Roundcube upload attachment screen](https://user-images.githubusercontent.com/12184311/42342756-5156f2b8-8097-11e8-9c4d-9ff842c2762c.png)

This can be confusing for end users, because the SMTP server can (and probably does) limit the message size. Despite the PHP setting being either lower or higher, mail can get bounced, thus causing confusion.

As far as an end user is concerned, there is only one limit.

I think there is a better way to show this.

**Comment by alecpl** [comment]
I'm listing, what's a better way?

**Comment by pixandpages** [comment]
Maybe it's also possible to show SMTP server limit somehow?
Or simply change the text to something more descriptive like "Maximum file upload is xx MB, but possibly your server has other limits for sending files."

I was getting this message: 
![afbeelding](https://user-images.githubusercontent.com/11209433/42369302-d6fa116c-8109-11e8-8b43-484ae400ed53.png)
It doesn't show the exact limit.

**Comment by alecpl** [comment]
So, the problem is with non-descriptive error message. We fixed that in git-master. The error message displays the limit value. Version 1.3 also has max_message_size option you can use.
