### ISSUE TITLE
Toolbar button "Refresh" of Roundcube (1.3.6) does not update the message list even there are changes in the current folder.

### ISSUE THREAD

**Issue by lv01jsi** [roundcube/roundcubemail#6348]
Toolbar button "Refresh" of Roundcube (1.3.6) does not update the message list even there are changes in the current folder.

**Comment by alecpl** [comment]
Works for me. So, we'll need some more info about your configuration and environment. Also an imap_debug log from the moment when you press the button.

**Comment by lv01jsi** [comment]
Please find attached scenario to reproduce.
[Scenario.pdf](https://github.com/roundcube/roundcubemail/files/2188269/Scenario.pdf)

**Comment by alecpl** [comment]
Still works for me. We need more information.

**Comment by alecpl** [comment]
No feedback.
