### ISSUE TITLE
Elastic: collapsed folder does not indicate unread messages inside

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6349]
Collapsed folder does not became bold (as larry or classic), or dos not show unread count label if
sub-folders have unread messages.

RCM git, only contextmenu plugin.

**Comment by alecpl** [comment]
Confirmed. Other skins do not display count of unread in subfolders, so we'll not do that here (yet), but we should make the folder name bold, I agree.

**Comment by alecpl** [comment]
Fixed.

**Comment by 4jNsY6fCVqZv** [comment]
@alecpl 
A brief follow-up question as to whether my scenario is covered by this topic:

I have the following folder structure:

A
 B
  C1
  C2
  C3

When I close folder B, the total number of unread messages in folders C1-C3 is not currently displayed next to B.
Instead, folder B itself should be highlighted in bold as soon as there are unread messages in one of the C folders?

**Comment by alecpl** [comment]
> When I close folder B, the total number of unread messages in folders C1-C3 is not currently displayed next to B. Instead, folder B itself should be highlighted in bold as soon as there are unread messages in one of the C folders?

Correct.

**Comment by 4jNsY6fCVqZv** [comment]
> we'll not do that here (yet)

There are also webmailers that solve this differently. Are there any changes you would like to see here seven years later?

**Comment by alecpl** [comment]
We may accept that. Feel free to provide a pull request.

**Comment by 4jNsY6fCVqZv** [comment]
>  Feel free to provide a pull request.

Thank you very much. Currently, I'm unfortunately not technically able to implement this myself. But it's nice to hear that there is an openness to look at it again.

**Comment by 4jNsY6fCVqZv** [comment]
Does it then make sense to reopen the issue?
