### ISSUE TITLE
SMTP connection error Roundcube 

### ISSUE THREAD

**Issue by dscpsyl** [roundcube/roundcubemail#6354]
Hi, 
I'm new to setting up a home server and stuff so I'm not sure where I went wrong. When I try to do an SMTP config test on Roundcube, it gives me an error:

`SMTP send:  NOT OK(Connection failed: Failed to connect socket: php_network_getaddresses: getaddrinfo failed: Name or service not known)`

I'm using ubuntu 18.04, apache2, postfix, mysql, and dovecot. 

Please help, thank you.

**Comment by alecpl** [comment]
Looks like the hostname couldn't be resolved. Not Roundcube issue.

**Comment by benlyazid** [comment]
Hi can you please tell me how did you solve this problem?
