### ISSUE TITLE
Feature request: provide a flatpak bundle

### ISSUE THREAD

**Issue by Lvaskz** [roundcube/roundcubemail#6355]
Hello, everyone, this app is should be available for many other distributions and with real-time updates from the original developers. That is why I would like to suggest you provide a universal package for linux distributions: flatpak Here we find everything related to the type of packaging and its advantages: https://flatpak.org/
In addition, the package can be hosted on the flathub: https://flathub.org/apps/
Consider it, since apparently, you can install in most distributions, a single package to maintain, or you could use snap, the problem is that it is not supported by RedHat, instead flatpak does.

A new world for application developers
Cross-distro

Create one app bundle and distribute it to the entire Linux desktop market.
Stable platforms

Runtimes provide stable sets of dependencies that can be used by applications.
Consistent environments

Develop and test your application in an environment that's identical to the one users have.
Control over dependencies

Dependencies that aren't in a runtime can be bundled as part of an application. Versions of the dependencies that are used can be fixed and patched.
Easy build tools

Flatpak's build tools are simple and easy to use, and come with a full set of documentation.
Future-proof builds

Runtimes are forward compatible, irrespective of distribution changes. Flatpak applications run on new Linux distribution versions as they are released.

**Comment by alecpl** [comment]
We don't have resources to do proper docker image. Supporting another release type will not happen anytime soon. I'm not going to work on this. If there's anybody interested in this, provide pull requests or create a separate repository. Ask if you have any questions.

**Comment by thomascube** [comment]
Flatpack is actually an interesting approach but indeed, we barely manage to provide Docker images. If anybody can kickstart this by providing a pull request with a basic flatpack manifest, please stand up.

**Comment by jdrab** [comment]
I would like to add this info from flatpak official FAQ.

**Q:**Can Flatpak be used on servers too?
**A:**Flatpak is designed to run inside a desktop session and relies on certain session services, such as a D-Bus session bus and, optionally, a systemd --user instance. This makes Flatpak not a good match for a server.

**Comment by Lvaskz** [comment]
Hi, maybe you guys can create an appimage package too. See
https://appimage.org/
https://docs.appimage.org/

**Comment by alecpl** [comment]
We can't. I think it does not make sense to keep this open. No one volunteered in a year since the ticket have been created.
