### ISSUE TITLE
attachments with certain characters issue

### ISSUE THREAD

**Issue by njoerd** [roundcube/roundcubemail#6358]
I have noticed an issue with attachments and special characters in the their names some time ago, now i have tried to investigate it.
I am living in a german speaking country, so we use the so called umlauts (ä,ö,ü). If the name of an attachment contains one of these characters the handling ends in a corrupt file.

It is easily to reproduce:
1. generate two text files. one is called "test.txt" and the other one "testü.txt". Both contain only the word "test"
2. send two emails containing one of the files (must be possible to send one containing both files, but haven't tried)
3. try to open the attachment. test.txt contains only the word test as expected, but testü.txt contains the following string:

.txt"

test

So roundcube seems to put a part of the name (in fact after the umlaut) into the file. Same issue is when trying to download the files in roundcube (file name will also be incorrect)

I'm using the last stable version of roundcube (1.3.6).
--njoerd

**Comment by alecpl** [comment]
I'm unable to reproduce.

- does it work in a different browser?
- does it work with all plugins diabled?
- does it work if you create/send the message using another client application e.g. Thunderbird?
- could you provide debug log (with imap_debug=true) from the moment when you open the attachment and the sample message?

**Comment by alecpl** [comment]
No feedback.

**Comment by njoerd** [comment]
- browser independently: used firefox, chrome and edge
- no plugins installed
- sample messages were created with several applications: Outlook, web-based (Gmail,...)
- log should be attached

[imap.txt](https://github.com/roundcube/roundcubemail/files/2329171/imap.txt)

**Comment by alecpl** [comment]
The log shows that in the imap level all is ok. The attachment body and name is fetched correctly.

What is your PHP/OS/http environment?
