### ISSUE TITLE
Elastic managesieve - vacation forward email field too small

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#6359]
The "redirect to" and "send copy to" E-Mail address field is too small (css says 1%), commit eefbbb6

![image](https://user-images.githubusercontent.com/1497730/42975229-4f70067c-8bbb-11e8-8fa7-e9924b19ea0a.png)

**Comment by alecpl** [comment]
What browser? It is `width:1%`, but also `flex:1 1 auto` and it looks like full width in Firefox for me. Anyway, we could try to use group input widget here, but it may require some additional style to get rounded corners when the input is hidden.

**Comment by HLeithner** [comment]
for me this is small on firefox 61 and vivaldi 1.6 and Chrome

Thats the css tree by firefox:

> .input-group > .custom-file, .input-group > .custom-select, .input-group > .form-control {
    position: relative;
    -ms-flex: 1 1 auto;
    flex: 1 1 auto;
    width: 1%;
    margin-bottom: 0;
}
.form-control {
    color: #2c363a;
}
.form-control {
    display: block;
    width: 100%;
    padding: .375rem .75rem;
    font-size: 1rem;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
input {
    vertical-align: middle;
}
button, input, select, textarea {
    line-height: initial;
}
body, button, input, optgroup, select, textarea, .popover {
    font-family: Roboto,sans-serif;
}
button, input {
    overflow: visible;
}
button, input, optgroup, select, textarea {
    margin: 0;
        margin-bottom: 0px;
    font-family: inherit;
    font-size: inherit;
    line-height: inherit;
}
*, ::after, ::before {
    box-sizing: border-box;
}
input:-moz-read-write, textarea:-moz-read-write {
    -moz-user-modify: read-write !important;
}
input {
    -moz-appearance: textfield;
    padding: 1px;
    border: 2px inset ThreeDLightShadow;
    background-color: -moz-Field;
    color: -moz-FieldText;
    font: -moz-field;
        font-size: ;
        line-height: normal;
        font-family: ;
    text-rendering: optimizeLegibility;
    line-height: normal;
    text-align: start;
    text-transform: none;
    word-spacing: normal;
    letter-spacing: normal;
    cursor: text;
    -moz-binding: url("chrome://global/content/platformHTMLBindings.xml#inputFields");
    text-indent: 0;
    -moz-user-select: text;
    text-shadow: none;
    overflow-clip-box: padding-box content-box;
}
td {
    text-align: inherit;
}
table {
    border-collapse: collapse;
}
table {
    border-spacing: 2px;
    border-collapse: separate;
    text-indent: 0;
}
body {
    color: #2c363a;
}
body {
    font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #212529;
    text-align: left;
}

Thats the calculated values by firefox:

> background-clip: padding-box;
background-color: rgb(255, 255, 255);
border-bottom-color: rgb(206, 212, 218);
border-bottom-left-radius: 3.5px;
border-bottom-right-radius: 3.5px;
border-bottom-style: solid;
border-bottom-width: 1px;
border-collapse: collapse;
border-image-outset: 0;
border-image-repeat: stretch stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-left-color: rgb(206, 212, 218);
border-left-style: solid;
border-left-width: 1px;
border-right-color: rgb(206, 212, 218);
border-right-style: solid;
border-right-width: 1px;
border-top-color: rgb(206, 212, 218);
border-top-left-radius: 3.5px;
border-top-right-radius: 3.5px;
border-top-style: solid;
border-top-width: 1px;
box-sizing: border-box;
color: rgb(44, 54, 58);
display: block;
flex-basis: auto;
flex-grow: 1;
flex-shrink: 1;
font-family: Roboto, sans-serif;
font-size: 14px;
font-weight: 400;
line-height: 21px;
margin-bottom: 0px;
margin-left: 0px;
margin-right: 0px;
margin-top: 0px;
overflow: visible;
overflow-x: visible;
overflow-y: visible;
padding-bottom: 5.25px;
padding-left: 10.5px;
padding-right: 10.5px;
padding-top: 5.25px;
position: relative;
text-align: start;
transition-delay: 0s, 0s;
transition-duration: 0.15s, 0.15s;
transition-property: border-color, box-shadow;
transition-timing-function: ease-in-out, ease-in-out;
vertical-align: middle;
width: 23px;


Maybe I failed to compile the css correct?

**Comment by alecpl** [comment]
I see the problem now. There's style="display:inline" added in some cases to the input's parent element. So, now I can reproduce and will work on a fix.

**Comment by HLeithner** [comment]
thx

**Comment by alecpl** [comment]
Fixed.
