### ISSUE TITLE
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/roundcube/program/steps/mail/mark.inc on line 73

### ISSUE THREAD

**Issue by 6ec123321** [roundcube/roundcubemail#6360]
Need to fixing this with PHP 7.2:

PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/roundcube/program/steps/mail/mark.inc on line 73

Warning appears when the folder does not contain any messages.

Need to use is_array() function before.

**Comment by alecpl** [comment]
Fixed as part of #6307.
