### ISSUE TITLE
managesieve: Reply with message -- empty 'Return-path' header

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#6363]
v1.3.6 (in v1.3.5 it was the same)

From the headers of `Auto-Submitted: auto-replied (vacation)` message, received by the recipient server:

    Return-path: <>
    Received-SPF: none

'Envelope From' (Return-path) is empty, so SPF isn't checked.  No settings in WebUI `managesieve Filters` change anything about that.

Could you please fix that?

**Comment by alecpl** [comment]
This is not configurable via managesieve. You have to take a look at server configuration.
