### ISSUE TITLE
Release artefact roundcubemail-1.3.7 contains unwanted roundcubemail-git sub directory

### ISSUE THREAD

**Issue by rainerjung** [roundcube/roundcubemail#6365]
The artecfact roundcubemail-1.3.7-complete.tar.gz contains a sub directory roundcubemail-git which seems to contain an additional copy of the application. This seems to be a releasing problem. It was not observed for 1.3.5 and 1.3.6 (the tarballs are smaller there) and do not contain roundcubemail-git).

**Comment by thomascube** [comment]
Confirmed. An update is on the way

**Comment by thomascube** [comment]
A new tarball has just been published. Re-download it from https://github.com/roundcube/roundcubemail/releases/tag/1.3.7
