### ISSUE TITLE
Images getting corrupted.

### ISSUE THREAD

**Issue by sblantipodi** [roundcube/roundcubemail#6366]
Hi all,
I'm experiencing an annoying problems with image attachments.

There is no way from my roundcube to open images if they are attached to an email.

Is there a solution to this issue? (using the latest roundcube version)

**Comment by alecpl** [comment]
Probably an imap server issue. What Roundcube version? Are these messages created in Roundcube or other clients? You can enable imap_debug to see what is returned by the server.

**Comment by sblantipodi** [comment]
@alecpl thanks for the answer, I appreciate it.
I exclude that is an imap server issue since I can see the images without problems with other clients like Thunderbird or Aquamail for Android.

I have the same problem even if the message is created with Roundcube or with other clients.

**Comment by alecpl** [comment]
Other clients may use different ways (imap capabilities) to get the attachment bodies. You may try setting `$config['imap_disabled_caps'] = array('BINARY');` (requires re-login).

**Comment by alecpl** [comment]
Also, test with disabled all plugins. Use most recent Roundcube version.

**Comment by sblantipodi** [comment]
@alecpl you rock! you get it. 
it was the fail2ban plugin. if I remove it, it works...

unfortunantly I want it, how can a fail2ban plugin create this problem? is there a workaround for it? thanks!!!

**Comment by alecpl** [comment]
I don't know, maybe there's some whitespace characters out of `<?php` and  `?>` tags in the plugin files. We do not support this plugin.

**Comment by sblantipodi** [comment]
@alecpl 
Ok, removed the whitespace from the plugin and now it works ok.

thanks for your work and the other guys who work for this good project, we all appreciate it.
