### ISSUE TITLE
Unable to send emails when the password has non-ascii chars

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6368]
Howdy,

I have some users that have password's with "óéá", and it works fine for login, as for sending emails, it's not working.
I have set:
$config['password_charset'] = 'UTF8';

What can i check to see if i'm doing something wrong rather than being a RC bug?

**Comment by dddns** [comment]
Here.
(ops, would it be my SASL backend that is not supporting it?)

Aug  1 09:07:47 fastweb roundcube: <rpkdjs6a> Successful login for trash@domain.tld (ID: 102) from 213.228.163.73 in session rpkdjs6avujdh0fdsg4mkg6sej
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 220 smtp.domain.tld - Microsoft Exchange 2020 (512bit)
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Send: EHLO domain.tld
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-smtp.domain.tld
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-PIPELINING
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-SIZE 52428800
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-VRFY
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-ETRN
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-STARTTLS
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-AUTH PLAIN LOGIN CRAM-MD5 DIGEST-MD5
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-AUTH=PLAIN LOGIN CRAM-MD5 DIGEST-MD5
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-ENHANCEDSTATUSCODES
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250-8BITMIME
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250 DSN
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Send: AUTH DIGEST-MD5
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 334 bm9uY2U9IlNTYTRpY0FKNkhUQitPWEk5N2VIeSsrbGl0Y3M3Zkl5ZWpnSnRycTR5MGs9IixyZWFsbT0ibGlyYSIscW9wPSJhdXRoIixjaGFyc2V0PXV0Zi0fggujkfghjtZDUtc2Vzcw==
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Send: ****** [344]
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 535 5.7.8 Error: authentication failed: authentication failure
Aug  1 09:07:57 fastweb roundcube: ERROR: Invalid response code received from server (535)
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Send: RSET
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 250 2.0.0 Ok
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Send: QUIT
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> Recv: 221 2.0.0 Bye
Aug  1 09:07:57 fastweb roundcube: <rpkdjs6a> SMTP Error: Authentication failure: Invalid response code received from server (Code: 535) in /home/hosting/domain.tld/webmail/program/lib/Roundcube/rcube.php on line 1667 (POST /webmail/?_task=mail&_unlock=loading1533110876175&_lang=en_US&_framed=1&_action=send)

**Comment by dddns** [comment]
Ok, tried both and nothing.
Tt doesn't login, always fails, i have the conscience that it would be SASL side.

Any extra help? i don't see any option to set the charset for smtpd.conf for the mysql conn

**Comment by alecpl** [comment]
Check smtpd logs, other than that I have no clue, but it does not look like Roundcube issue.

**Comment by dddns** [comment]
Ok now I know it's not RC related.
Sorry for noise Alec.
