### ISSUE TITLE
vacation does not save :addresses

### ISSUE THREAD

**Issue by sholl** [roundcube/roundcubemail#6372]
Within the current installation of the roundup-managesieve-plugin the additional addresses are not written back to the sieve-file correct. Howver, adding them by hand in the script and navigating to the sieve rule inside roundcube,  let them show up correct.
WHen hitting the "Save" button, the fields are empty and the resulting sieve-script does not contain the :addresses entries any more.

My versions:
* roundcubemail-1.1.0
* managesieve-plugin version 8.2 [2015-01-14]

Is this known?

TIA

**Comment by alecpl** [comment]
Works for me in recent version. 1.1.0 is very old.
