### ISSUE TITLE
1.3.7 rcube_imap_generic::getQuota array_chunk() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by seveN864** [roundcube/roundcubemail#6374]
RC 1.3.7 improvement 

Warning messages:
PHP message: PHP Warning:  array_chunk() expects parameter 1 to be array, null given in /var/www/(REMOVED)/program/lib/Roundcube/rcube_imap_generic.php on line 3129
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/(REMOVED)/program/lib/Roundcube/rcube_imap_generic.php on line 3129

thrown when "no" quotas set:

```
 C: a3 GETQUOTAROOT INBOX
 S: * QUOTAROOT "INBOX" "ROOT"
 S: * QUOTA "ROOT"
 S: a3 OK GETQUOTAROOT Ok.
```

quick fix check if $quotas is empty:

```
--- roundcubemail-1.3.7/program/lib/Roundcube/rcube_imap_generic.php    2018-07-29 22:04:48.000000000 +0200
+++ program/lib/Roundcube/rcube_imap_generic.php        2018-08-04 13:06:22.138743417 +0200
@@ -3126,6 +3126,9 @@
                     list(, , $quota_root) = $this->tokenizeResponse($line, 3);
 
                     $quotas = $this->tokenizeResponse($line, 1);
+                   if(empty($quotas)) { 
+                       continue;
+                   }
                     foreach (array_chunk($quotas, 3) as $quota) {
                         list($type, $used, $total) = $quota;
                         $type = strtolower($type);


```

**Comment by alecpl** [comment]
We'll apply this fix, but what IMAP server? This looks like not compatible with RFC2087.

**Comment by seveN864** [comment]
Thank you. IMAP server is Courier-IMAP 4.17.1

Output with active quota (for demonstration):
```
C: a2 GETQUOTAROOT inbox
S: * QUOTAROOT "inbox" "ROOT"
S: * QUOTA "ROOT" (STORAGE 19864 195313)
S: a2 OK GETQUOTAROOT Ok.
```
works as expected with roundcube.

Good point regarding RFC2087 ( https://tools.ietf.org/rfc/rfc2087.txt )
Refering to "5.2. QUOTAROOT Response":

> (...)
>       Resources not named in the list are not limited in the quota root.
>       Thus, an empty list means there are no administrative resource
>       limits in the quota root.
> (...)

The response seems to be valid for a unlimited IMAP account to me. YMMV
Also take a look at the example "5.2. QUOTAROOT Response".

**Comment by alecpl** [comment]
Imo, a valid response would be `* QUOTA "ROOT" ()`, because quota_list is not optional according to the Formal Syntax. I think most servers just skip that line.

**Comment by alecpl** [comment]
Fixed.
