### ISSUE TITLE
Elastic: Garbled calendar view

### ISSUE THREAD

**Issue by robert-scheck** [roundcube/roundcubemail#6375]
I'm getting the following garbled calendar view using elastic skin (Chromium 65 and 66):

![image](https://user-images.githubusercontent.com/10982488/43679430-6bc7f160-9825-11e8-8a3d-4ca4fc3d0de3.png)

Used version(s):
roundcubemail-plugin-kolab_activesync-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-acl-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-libkolab-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-jqueryui-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_tags-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-calendar-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_activesync-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_files-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-managesieve-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_notes-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-tasklist-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_tags-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_delegation-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-acl-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_delegation-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_addressbook-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-managesieve-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_files-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-libkolab-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-calendar-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_notes-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_addressbook-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-tasklist-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-jqueryui-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch

**Comment by alecpl** [comment]
We do not support Kolab Calendar here.

**Comment by robert-scheck** [comment]
May I kindly ask you to provide a link to the correct tracker then?

**Comment by alecpl** [comment]
https://git.kolab.org/

**Comment by robert-scheck** [comment]
Thanks, filed https://git.kolab.org/T4247 now.

**Comment by tanzhenchao** [comment]
We also encountered the same problem, is there a solution?

**Comment by dioobr** [comment]
How can I get access to these plugins?

**Comment by robert-scheck** [comment]
Are you looking for https://git.kolab.org/diffusion/RPK/?

**Comment by dioobr** [comment]
> Are you looking for https://git.kolab.org/diffusion/RPK/?

I already downloaded these repositories, but it seems that some CSS files are missing, like the calendar plugin.

**Comment by robert-scheck** [comment]
See https://git.kolab.org/T4247#75135 as well and/or be please specific which CSS files are missing exactly.
