### ISSUE TITLE
Elastic: Menu options "Settings" and "About" are overlapping

### ISSUE THREAD

**Issue by robert-scheck** [roundcube/roundcubemail#6376]
Menu options "Settings" and "About" (German: "Einstellungen" and "Über") are overlapping, especially when doing a "on mouse over" with the mouse pointer:

![image](https://user-images.githubusercontent.com/10982488/43679487-273b77be-9826-11e8-9063-c4b2e30c2c17.png)

Used version(s):
roundcubemail-plugin-kolab_activesync-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-acl-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-libkolab-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-jqueryui-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_tags-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-calendar-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_activesync-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_files-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-managesieve-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_notes-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-tasklist-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_tags-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_delegation-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-acl-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_delegation-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_addressbook-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-managesieve-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_files-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-skin-elastic-1.4-47.4.el7.kolab_wf.noarch
roundcubemail-plugin-libkolab-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-calendar-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_notes-skin-elastic-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-kolab_addressbook-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-tasklist-skin-elastic-assets-3.4-39.4.el7.kolab_wf.noarch
roundcubemail-plugin-jqueryui-skin-elastic-assets-1.4-47.4.el7.kolab_wf.noarch

**Comment by alecpl** [comment]
We do not support Kolab here, but I see the point. We already have a css logic to remove button labels on a small screen height like that, but I'll have to verify for how many buttons this works.

**Comment by robert-scheck** [comment]
Filed https://git.kolab.org/T4250 to move it to a supported tracking system.

**Comment by alecpl** [comment]
The optimization I was talking about is done to display up to 10 buttons in the menu. I think you're not using the most recent version of the skin. Now I also added a background color to the special buttons, so overlapping (when happens) looks slightly better. I hesitate to add js logic for this.
