### ISSUE TITLE
Add calendar week in calendar views "Week" and "Month"

### ISSUE THREAD

**Issue by robert-scheck** [roundcube/roundcubemail#6377]
Please introduce a calendar week in calendar views "Week" and "Month" as suggested in the screenshots. First suggestion is "Month" by introducing just a small column before the first existing column:

![image](https://user-images.githubusercontent.com/10982488/43679603-c1ec819e-9827-11e8-8256-475890142bbe.png)

Second suggestion is "Week" where the calendar week information can simply be put into the currently empty cell (e.g. "KW 35" in German, "CW 35" in English):

![image](https://user-images.githubusercontent.com/10982488/43679612-fb7f8672-9827-11e8-8f4e-0c1df5ce35e0.png)

**Comment by alecpl** [comment]
We do not support Kolab Calendar plugin here.

**Comment by robert-scheck** [comment]
May I kindly ask you to provide a link to the correct tracker then?

**Comment by alecpl** [comment]
https://git.kolab.org/

**Comment by robert-scheck** [comment]
Thanks, filed https://git.kolab.org/T4241 there.
