### ISSUE TITLE
[Elastic] Delete button position

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#6378]
Maybe a bit early to cry about button positions but I'm testing elastic since 2 weeks and every time I select one or more emails I search for the delete button. 

In my opinion it should be next to "select, threads, options, refresh" buttons over the list of emails.

Or is there a reason that its only at the "email view" side?

**Comment by alecpl** [comment]
There's no room for more buttons in the "middle box", also all action buttons are on the right side. Someone else would like to have Junk or Archive button there. So, I think it's a wontfix.

**Comment by HLeithner** [comment]
Ok thx for the quick response.
