### ISSUE TITLE
Vacation Option Broken

### ISSUE THREAD

**Issue by lukehaskett** [roundcube/roundcubemail#6382]
I've been using your service for two years with the out of office/vacation mode functioning perfectly through the webmail client. However, I'm now unable to deactivate the service. I unchecked vacation mode and saved it but my out of office is still active and whenever I try to change it (recheck the box) I am given the following error: "An error occurred: Error during connection"

Please advise as this is a major problem to be unable to turn off out of office!

**Comment by alecpl** [comment]
We're not a service, we create a software your service provider installed on their servers.
