### ISSUE TITLE
BINARY vs BODY and "invalid" messages

### ISSUE THREAD

**Issue by tomsommer** [roundcube/roundcubemail#6383]
Roundcube uses `BINARY.PEEK` whenever possible, however this prevents the display of broken mails, that usually work with `BODY.PEEK`

`BINARY.PEEK` returns `UID NO [PARSE] Invalid data in MIME part (0.012 + 0.000 + 0.011 secs)` whereas `BODY.PEEK` returns the mail body.

Perhaps add a fallback to `BODY.PEEK` if `BINARY.PEEK` fails?

**Comment by alecpl** [comment]
There's a fallback, but we use it only on `[UNKNOWN-CTE]` response. Maybe we should do this also for `[PARSE]`. What IMAP server/version?

**Comment by tomsommer** [comment]
Dovecot 2.3.2

**Comment by alecpl** [comment]
Looks like dovecot 2.3 uses `[PARSE]`  instead of `[UNKNOWNCTE]`. https://www.dovecot.org/list/dovecot-news/2017-December/000366.html

**Comment by tomsommer** [comment]
Good catch, Dovecot can return both `UNKNOWN-CTE` and `PARSE` now: https://github.com/dovecot/core/commit/ff17313eca2e395aa3127ebc01047386cd9cdd27

**Comment by alecpl** [comment]
Fixed.
