### ISSUE TITLE
Safari 11.1.1 - False Warning when uploading attachment 

### ISSUE THREAD

**Issue by sfxworks** [roundcube/roundcubemail#6389]
On behalf of an anonymous client:

Uploading an image/attachment since this version of safari for mac fails states "Error uploading image" but it uploads and sends successfully.

Tested with multiple images. All send ok. 

Applies to 11.1.1 and 11.1.2 (released today)

**Comment by alecpl** [comment]
What Roundcube version? Did you try with disabled all plugins? How exactly do you upload attachments?

**Comment by thomascube** [comment]
Works for me with current git master and Safari 11.1.2

**Comment by alecpl** [comment]
No feedback.
