### ISSUE TITLE
Multiple Subject fields

### ISSUE THREAD

**Issue by CoreTex** [roundcube/roundcubemail#6391]
Hi,

I have problems with some mail servers with my sent messages. I got an report like this:

`
Betreff | Array
Action: failed
Status: 5.0.0
Remote-MTA: dns; mx.spamexperts.com
Diagnostic-Code: smtp; 550 Messages should have one or no To headers, not 2.
`

**Comment by alecpl** [comment]
What version? Enable smtp_debug and check the log to make sure it's Roundcube's fault. Disable all plugins.

**Comment by alecpl** [comment]
No feedback.
