### ISSUE TITLE
SMTP Error (550): Connection to server failed.

### ISSUE THREAD

**Issue by joemillire016** [roundcube/roundcubemail#6393]
Hi am trying to send email and i foundthis issue with our roundecube webmail:

SMTP Error: Connection failed: Invalid response code received from server in /home1/enigmagi/public_html/email/program/lib/Roundcube/rcube.php on line 1667 (POST /?_task=mail&_unlock=loading1534312883079&_lang=en&_framed=1&_action=send)

I cant figureout how to fix the error, using outlook everything is fine.. Please help.. thanks in advance.

**Comment by alecpl** [comment]
Enable smtp_debug in Roundcube to see conversation with the server. That should reveal some more info.

**Comment by joemillire016** [comment]
Hi alecpl thank you for your help.. by the way smtp log show me this error.. 

i can successfully login and received new emails but the problem i cant send email... 

[15-Aug-2018 04:28:19 -0500]: <n6lkis24> Recv: 550-Message rejected because [69.89.31.218]:10503 is blacklisted see Blocked -
[15-Aug-2018 04:28:19 -0500]: <n6lkis24> Recv: 550 Too many failed logins

**Comment by alecpl** [comment]
This has nothing to do with Roundcube. These messages are quite self-explanatory. If you don't understand them ask your SMTP server admin.

**Comment by joemillire016** [comment]
actually smtp is working fine.. and using bluehost webmail and outlook app.. everything is working fine.. but from the webmail i created in our server i cant sent message..
