### ISSUE TITLE
Spam folder

### ISSUE THREAD

**Issue by mydappy** [roundcube/roundcubemail#6394]
Hi, all my sent emails goes to the spam folder

**Comment by alecpl** [comment]
You mean Spam folder on the recipient end? or Spam folder instead of Sent folder?

**Comment by mydappy** [comment]
It goes to spam folder on the recipient end

**Comment by alecpl** [comment]
Then you have to check the message headers on the recipient end. I guess your smtp server will have bad reputation or something in the message could be treated as spam. Most likely not Roundcube issue.
