### ISSUE TITLE
Classic skin: Compose zone not properly resized if Firefox window not in fullscreen

### ISSUE THREAD

**Issue by barul42** [roundcube/roundcubemail#6397]
Hello,

Not a huge issue, Roundcube is still totally usable, but using i3, when the browser window isn't in fullscreen and I'm writing a mail every fields are resized except the compose one, as shown here.
![2018-08-18-103829_1920x1080_scrot](https://user-images.githubusercontent.com/1577792/44297568-f494ed00-a2d3-11e8-9ce4-7080652ed50b.png)

**Comment by alecpl** [comment]
Since we now have three skins to maintain Classic will go to a low maintenance mode where such issues will not get much attention. However, I decided to fix it for now.
