### ISSUE TITLE
invalid range in character class at offset 74

### ISSUE THREAD

**Issue by kosfango** [roundcube/roundcubemail#6398]
Hi All,

I use latest roundcube, php73 on LEMP stack. When I started to write destination email address I saw in logs next message:

2018/08/19 00:09:59 [error] 8288#0: *111 FastCGI sent in stderr: "racter class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: in2018/08/19 00:18:51 [error] 8290#0: *129 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: invalid range in character class at offset 74 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 530PHP message: PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 71 in /usr/share/roundcubemail/program/lib/Roundcube/rcube_vcard.php on line 547PHP message: PHP Warning:  preg_replace_callback(): Compilation failed: inva

**Comment by Rotzbua** [comment]
php73 = php 7.3 or is it a typo? 7.3 is not released yet.

**Comment by kosfango** [comment]
Yes, I just made some tests, perhaps it will be helpful

**Comment by alecpl** [comment]
Fixed.
