### ISSUE TITLE
Collapse thread with left arrow key on any message in a thread

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#6399]
If possible please close an open thread if any message of a thread is selected and you press the left arrow key.

**Comment by alecpl** [comment]
That is not skin specific, so if we implement it it will work in all skins.

**Comment by HLeithner** [comment]
If you press the left-arrow on the parent you collapse the thread so the TB behavior is perfectly fine.
2x left-arrow and you collaps the thread (if its only one layer deep)

**Comment by alecpl** [comment]
Sure, but it might be not that convenient if you have one long branch. Still TB's behavior sounds more useful. Maybe adding Ctrl+Left-Arrow to jump to the top-most parent would make the solution complete.

**Comment by HLeithner** [comment]
I came to the same solution after reading the half of you sentence ;-) ctrl+left would be a great addition, TB should adopt this behavior ;-)

**Comment by HLeithner** [comment]
same for the other direction? full-open with ctrl-right?

**Comment by alecpl** [comment]
Implemented.

**Comment by HLeithner** [comment]
Thank you very much.
