### ISSUE TITLE
Mark as junk expunges messages when it shouldn't

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6402]
Howdy,

Think about this scenario:
- I have 10 messages in the inbox
- 5 of them are in "deleted" state, that was changed via MSOutlook
- I select one of the remaing 5 messages, and mark it as junk, using the "mark as junk" button

result:
- This is going to perform the EXPUNGE, and the messages that were in the deleted state, are going to disapear, but they should not disapear/be expunge'd.

Is it possible to fix it?
Thank you!
Jorge,

**Comment by alecpl** [comment]
This operation can be done only on IMAP servers supporting UIDPLUS or MOVE extensions. Without these it's impossible to move or copy+delete+expunge selected messages so we expunge all.

**Comment by thomascube** [comment]
Maybe the behavior should depend on the `flag_for_deletion` or `skip_deleted` config. As a result, the messages marked as junk will still remain visible as deleted items in the origin folder.
