### ISSUE TITLE
Validate smtp_helo_host before use

### ISSUE THREAD

**Issue by dsaard** [roundcube/roundcubemail#6408]
Upgraded from 1.1.5 to 1.3.7 with installto.sh

With 1.1.5 my exim setup works well

with 1.3.7 not if

`$config['smtp_helo_host'] = '';`

set in config.inc.php or missing complete 
exim rejected the ehlo command

~~~
rejected EHLO from fe-srv [172.16.1.81]: syntactically invalid argument(s): _
~~~

if  set  `smtp_helo_host` to something my setup works well again 

Cheers

**Comment by alecpl** [comment]
If the option is empty, Roundcube will use `$_SERVER['SERVER_NAME']` and if that var is also empty will fallback to 'localhost'. So, I guess there might be a misconfiguration of the http server/php on your side. Could you enable smtp_debug an try again? We'd see in the log what's really sent to the smtp server.

**Comment by dsaard** [comment]
thx for the hint!!!

found the reason why SEVER_NAME is filled with an underline

i have nginx with php-fpm running and nginx is configured with an catch all server_name `_`  cause this one serves only this app and the balancer is configured to filter before  :-)

equals 

~~~
[23-Aug-2018 20:03:48 +0200]: <j2slr4va> Recv: 220 smtp.exsample.com ESMTP Exim ?.?? Thu, 23 Aug 2018 20:03:48 +0200
[23-Aug-2018 20:03:48 +0200]: <j2slr4va> Send: EHLO _
[23-Aug-2018 20:03:48 +0200]: <j2slr4va> Recv: 501 Syntactically invalid EHLO argument(s)
[23-Aug-2018 20:03:48 +0200]: <j2slr4va> Send: HELO _
[23-Aug-2018 20:03:48 +0200]: <j2slr4va> Recv: 501 Syntactically invalid HELO argument(s)
~~~

should be a configuration hint  ...

Cheers

**Comment by alecpl** [comment]
Right, I guess we should validate the configured value and fallback to localhost when invalid. https://tools.ietf.org/html/rfc5321#section-4.1.1.1

**Comment by alecpl** [comment]
Fixed.
