### ISSUE TITLE
Error while displaying QR code in contacts

### ISSUE THREAD

**Issue by m0urs** [roundcube/roundcubemail#6409]
If I try to display the QR code for a contact entry, I do get an Error 500 and in the ERRORS log you see

[23-Aug-2018 18:29:25 Europe/Berlin] PHP Fatal error:  Call to undefined method Endroid\QrCode\QrCode::setPadding() in /var/www/webmail.urspringer.de/html/program/steps/addressbook/qrcode.inc on line 67

Any idea what might be wrong here?

Roundcube Webmail 1.3.7
endroid/qr-code                      2.x-dev 6062677

**Comment by alecpl** [comment]
How did you install qr-code lib? For Roundcube 1.3.x we have `"endroid/qr-code": "~1.6.5"` in composer.json.

**Comment by m0urs** [comment]
You are right. After uninstalling this version and installing the older one, everything works.  I checked some of my backups and for some reason by end of July the entry changed from 

"endroid/qr-code": "~1.6.5",
to
"endroid/qr-code": "~2.0",

I cannot say what I had done at that time, unfortunately.

Thanks for pointing me in the right direction.
