### ISSUE TITLE
Contacts not working with postgresql

### ISSUE THREAD

**Issue by abonanni** [roundcube/roundcubemail#6412]
When using PostgreSQL, i have an error on the following query:
`SELECT * FROM "contacts" AS c WHERE c."del" <> 1 AND c."user_id" = '388' ORDER BY (c."surname" || c."firstname" || c."name" || c."email") ASC LIMIT 50;`

If i correct the code as below, everything is ok:
`SELECT * FROM "contacts" AS c WHERE c."del" <> true AND c."user_id" = '388' ORDER BY (c."surname" || c."firstname" || c."name" || c."email") ASC LIMIT 50;`

The problem is that postgresql doesn't convert the integer '1' into boolean.

Is it possible to update code and replace `c."del" <> 1` by `c."del" <> true` ?

**Comment by alecpl** [comment]
But "del" column is smallint not boolean. What postgres version, what Roundcube version? What PHP version? What is returned by `SELECT DISTINCT "del" FROM "contacts"`?

**Comment by abonanni** [comment]
Thank you for reply. You are write del is smallint.
I have used the pgloader script to migrate datas from mysql to pgsql and pgloader has modified the database structure. So it's not a roundcube bug. Sorry.
