### ISSUE TITLE
Elastic: mail compose screen

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6413]
I have a few thoughts/comments on the compose screen after using the skin for a few days.

1. You have to press the tab key a lot to move between the from, to, subject and body fields. For exmaple when in the To field you have to tab twice to get to the subject and from the subject 3 times to get into the body field. I think it would be nicer if it went To tab Subject tab Body.

2. When you reply to a long email (or compose a long email) the entire compose screen is scrolled and the To/Subject fields cannot be accessed with without scrolling back up. I think it would be nice if only the body field was scolled.

3. A lot of space is taken up by the "Options and attachments" pane. Personally I do not need to use that panel very often so it seems like a bit of waste of space.

4. (Trivial) I'm finding it hard to get used to the location of the Send button. Having used Larry for so long I'm just used to the send button being at the top. I know this is just something you get used to it but I thought I'd mention it as other clients (Gmail, Outlook) put it at the top. For me, I write the email then look back at the header fields to check the recients and subject is correct then hit send so having at the top is easier.

**Comment by alecpl** [comment]
1. Well, we can't just skip important buttons. Another option will be to place that button(s) somewhere else.
2. I see it quite important to not have two scrollers on the page. And to make the page really responsive we can't remove the main scroller and use email-body-textarea scroller. What we could do is to add some logic that scrolls the page to the top on Shift-Tab.
3. Here I agree that the compose screen requires some designer touch. There are also questions about the need for contacts widget, as well as order of these UI columns.
4. Personally I see no problem as long as the Send button is always visible (and it is).

**Comment by johndoh** [comment]
1. I guess it depends how important those buttons are in every day use. By removing the tabindex attrib from the edit identities, add/remove header etc buttons I think keyboard navigation works a bit smoother. I think there have been similar discussions in the past eg #921

2. I agree 2 scrollers would be bad but does the scolling behaviour have to be identical on all screen sizes? Would it not be possible that on large screens only the email-body-textarea scrolls when on small screens the whole thing scrolls? It seems like at the moment the small screen is forcing the large screen to be less user friendly.

**Comment by alecpl** [comment]
@artfulrobot Very valid point about the HTML editor toolbar. I guess we can fix this by making the toolbar sticky to the top of the screen on scroll.
@johndoh I don't see a problem in scrolling the headers. While technically possible I don't want to change scrolling behavior depending on screen size (height). Also note there may be more records than initial three (From, To, Subject), sometimes much more and we'd end up with more issues trying to fit the textarea and all headers on screen.

**Comment by johndoh** [comment]
As I use it more I am inclined to agree about the scrolling headers. I still think the tabing between fields in an issue. In Larry and Classic you can tab from To > Subject > Message body. Skipping the Add Cc or editor type options (larry only) which are in comparable locations - next to the to/subject fields.

**Comment by alecpl** [comment]
I pushed some improvements. Some items here are fixed, some I consider wontfix. And I'll probably not work more on this without serious UX designer feedback. Create pull requests if you want me to re-consider something.

**Comment by Offerel** [comment]
@johndoh I have searched the same for the send button placement as you. I don't know if this what you want, but i have created a small plugin to get around this at least for myself. Please have a look at https://github.com/Offerel/roundcube_elasticext. In the config file you can specify, if the button should be left or right in the toolbar. Additionally, you can change the login screen a little bit. If this is not for you, you can disable login screen change in the same config file. I haven't changed the tab behavior as of now.

**Comment by habibmy** [comment]
When I am pasting my copied HTML it sends it as plain text.
