### ISSUE TITLE
Elastic: bad logo appearance on login screen

### ISSUE THREAD

**Issue by ilgrosso** [roundcube/roundcubemail#6424]
I have just set up Elastic with 1.4 beta and it looks great, thanks for this!

Only problem found so far: when accessing the login screen, my company logo is stretched to fill the page width, while height is fixed; mobile view is fine, instead.

**Comment by alecpl** [comment]
What browsers did you try? What is the size and format of the image?

**Comment by ilgrosso** [comment]
I tried both Firefox and Chrome on Linux.
Logo size is 200px x 48px

**Comment by ilgrosso** [comment]
Thanks for confirmation :+1:

**Comment by alecpl** [comment]
Fixed.

**Comment by ilgrosso** [comment]
After manually backporting the fix, everything works like a charm now, thanks!
