### ISSUE TITLE
RoundCube Beta 1.4 Issue 

### ISSUE THREAD

**Issue by SURYASWAROOP** [roundcube/roundcubemail#6425]
1. The Default Password Plugin was not Working
2. Proper Installation on Multiple Server and on Local Systems tried 
3. Please Resolve this Issue ASAP
4. Check the Image Below
5. Many of the default Plugins Provided by RoundCube Not Working for example Addressbook
![image](https://user-images.githubusercontent.com/7898495/44958654-dbf61b00-af00-11e8-8179-43e1c8474f32.png)

**Comment by alecpl** [comment]
What is Addressbook plugin?

**Comment by SURYASWAROOP** [comment]
[03-Sep-2018 23:27:52 -0700]: <ipghu6ti> IMAP Error: Login failed for
surya@meindia.io against localhost from 106.51.52.232. LOGIN: Invalid user
name or password. in C:\Bitnami\wampstack-5.6.37-2\apache2\htdocs\
mail.meindia.io\program\lib\Roundcube\rcube_imap.php on line 201 (POST
/?_task=login&_action=login)

[03-Sep-2018 23:29:01 -0700]: <smhoeeb6> DB Error: [1305] FUNCTION
cube.update_passwd does not exist (SQL Query: SELECT
update_passwd('$1$JDxeVtWP$ztynWVtRR/bLdpLf9f7Ga1', 'surya@meindia.io')) in
C:\Bitnami\wampstack-5.6.37-2\apache2\htdocs\mail.meindia.io\program\lib\Roundcube\rcube_db.php
on line 542 (POST /?_task=settings&_action=plugin.password-save)

**Comment by alecpl** [comment]
Looks like a configuration issue.
