### ISSUE TITLE
Elastic + elastic4mobile switches to widescreen layout permanently

### ISSUE THREAD

**Issue by MASHtm** [roundcube/roundcubemail#6428]
I tried roundcube 1.4-beta-full on top of my 1.3.7 installation (using remi php 5.6 and roundcube rpms for CentOS 7). Looks fine so far.

I followed your recommendations to use elastic4mobile plugin to keep Desktop Browser settings unchanged.

After logging in to a session with a "mobile browser" and elastic the layout setting is permanently switched to widescreen even if it was desktop for larry.

**Comment by thomascube** [comment]
This issue is tracked here: https://github.com/thomascube/roundcube-elastic4mobile/issues/1
