### ISSUE TITLE
Buttons disabled after delete/move

### ISSUE THREAD

**Issue by nixe-** [roundcube/roundcubemail#6430]
I use setting "After message delete/move display the next message". When I am in mail list with preview and delete or move message, next message is opened. Problem is that, after deleting/moving message, messagetoolbar buttons (ie. reply, reply all, forward and delete) and page controls are disabled. So I can't use any of those buttons when previewing my "next message", I need to choose message again from the list, to enable those buttons. I've tested this to exist in 1.2(.9) and 1.3(.7).

This worked fine in 1.0, because there wasn't button disabling (I guess).

**Comment by alecpl** [comment]
Try with disabled all plugins. Check browser console for javascript errors.  Try with different browser.

**Comment by nixe-** [comment]
Both of my installs (1.2.9 and 1.3.7) are fresh installs, without any plugins. There's no errors in Javascript console. I've tried it in browsers/systems below
- Chrome 68 on macOS (High Sierra) and Windows 10
- Safari 11.1 on macOS (High Sierra)
- Opera 55 on Windows 10
- Edge 42 on Windows 10
- IE 11 on Windows 10

Server specs are
- Virtual server at Virtualbox
- Ubuntu 14.04.5 LTS
- MySQL 5.5.60
- Apache 2.4.7
- PHP 5.5.9
  * Zend Engine v2.5.0 (Zend OPcache v7.0.3 & Xdebug v2.2.3)

**Comment by alecpl** [comment]
I'm unable to reproduce.

**Comment by nixe-** [comment]
Just tested on another server

> I'm unable to reproduce.

**Comment by nixe-** [comment]
> I'm unable to reproduce.

Sorry about closing issue, did it accidentally.
So I was also testing with another server and wasn't able to reproduce it there. So I need to check out why other server is causing problems, propably something with server configuration.
