### ISSUE TITLE
Can´t login to an imap account with a "+"sign in the e-mail address

### ISSUE THREAD

**Issue by Ralf99** [roundcube/roundcubemail#6432]
Hi,

with a new installation von RC 1.3.7 i can´t create or login to an e-mail address at my webhoster.
The address looks like "surname+surname@domain.tld".

2. TRY
I also try the plugin virtuser_file ... but this one I can't get to run at all or doesn't seem to work at all. I have already tried x different versions and although the virtuser.txt is found and read, there is always the error
05-Sep-2018 14:38:34 +0200]: <e147b652> IMAP Error: Login failed for xxxxx from 93.222.xxx.xxx. AUTHENTICATE PLAIN: Authentication failed. in /www/htdocs/xxxxxx/roundcubemail/program/lib/Roundcube/rcube_imap.php on line 196 (POST /roundcubemail/?_task=login&_action=login)

Thanks
Ralf

**Comment by alecpl** [comment]
Check your imap server logs for more details.

**Comment by alecpl** [comment]
More likely IMAP server issue. No feedback.
