### ISSUE TITLE
Small pcre.backtrack_limit setting can cause email body reset on send/save

### ISSUE THREAD

**Issue by conathan** [roundcube/roundcubemail#6433]
We are seeing a issue when using a image (7.3kb seems to be fine, 9.3kb triggered this) is used in a html signature, and you save it to drafts (or send it), it results in a email with a blank body.

To reproduce:
* Add the large image into a html signature
* Create a new email
* Add a inline image
* Hit save, and check Drafts
 
But, using just the Normal Image instead, seems to work fine.

Environment:
* OS: Centos 7.5.1804
* PHP: PHP 5.4 (Default php version in Centos 7.5)
* Roundcube: Tested on 1.3.7, as well as 1.4 beta

Tested with plugins disabled, adding $config['debug_level'] = 1; to config.inc.php,  but nothing in /var/log/roundcubemail/errors.log.

(Normal Image)
![bravenetlogo](https://user-images.githubusercontent.com/2858011/45247255-5b963800-b2bb-11e8-8b04-cf3b73f78fc1.png)

(Large Image)
![bravenetlogo_large](https://user-images.githubusercontent.com/2858011/45247252-589b4780-b2bb-11e8-9ccd-cd25254597f6.png)

**Comment by alecpl** [comment]
Works for me. Is this vanilla package installation (with vendor folder) or CentOS package? Could you provide the output message? And/or enable imap_debug and smtp_debug and provide the log?

**Comment by alecpl** [comment]
According to http://www.php.net/manual/en/pcre.configuration.php default value is 1000000. So, 10000 looks really small.

Anyway, we should probably detect an error here and log it or require higher value for pcre.backtrack_limit.

**Comment by alecpl** [comment]
Done.
