### ISSUE TITLE
Application Error (600): Enigma Plugin: Option 'enigma_pgp_homedir' not specified

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#6435]
I use RC 1.4-beta in my test environment and i get the error above. RC 1.3.7 works fine

the errors.log says: PHP Error: Enigma plugin: Option 'enigma_pgp_homedir' not specified in /var/www/xxxxxxx/plugins/enigma/lib/enigma_engine.php on line 92 (POST /?_task=settings&_action=plugin.enigmakeys)

the home dir of /plugins/enigma/home/ is r/w by the webserver. I found nothing to configure in the defaults.inc.php and the config.inc.php.sample ...

Maybe you can give me a hint?

**Comment by alecpl** [comment]
There's enigma_pgp_homedir setting in Enigma's config file. Also, placing the keys storage inside the document root is not recommended for security reasons.
