### ISSUE TITLE
Persistent Cross Site Scripting in rcfilters plugin

### ISSUE THREAD

**Issue by fi0n4** [roundcube/roundcubemail#6437]
Hi. when using rcfilters plugin version 2.1.6, two parameters "_whatfilter" and "_messages" do not sanitize user input. therefore you can inject javascript code in them. since it's a self XSS, it may not have any impact security. a user can inject js and html code in his/her own account filters list.

![roundcube](https://user-images.githubusercontent.com/39667718/45261377-c3f92c80-b415-11e8-9418-cf93b706ce6e.png)

tested on Roundcube Webmail version 1.0.5

**Comment by alecpl** [comment]
We do not support this external plugin, nor this old Roundcube version.

**Comment by fi0n4** [comment]
I see. though it seems like the plugin works on all versions of Roundcube. 
https://plugins.roundcube.net/packages/eagle00789/rcfilters
