### ISSUE TITLE
Please do not delete whitespace in plain text

### ISSUE THREAD

**Issue by HacKurx** [roundcube/roundcubemail#6438]
Hi,

Every time I send a patch in plain text format, it is distorted by roundcube. Example :

![bug roundcube mail patch](https://user-images.githubusercontent.com/4661917/45264290-9377b980-b43a-11e8-81f1-764f255ebf50.png)

This is a big problem for me because I try to respect this:
https://www.kernel.org/doc/html/v4.17/process/email-clients.html

I found nothing to put in "config.inc.php" to fix this behavior. Thank you.

**Comment by alecpl** [comment]
You mean inline text not attachments, right?

That would make sense, but there's more than just exceeding spaces. It's also about format=flowed and line wrapping. So, I guess the best would be an additional "disable formatting" or "keep formatting" option that would disable all these features with one click.

**Comment by HacKurx** [comment]
@alecpl 
> You mean inline text not attachments, right?

Yes, that's right.

> So, I guess the best would be an additional "disable formatting" 

That would be great. Roundcube could thus be added in the documentation of email clients for submit patch in Linux (I can take care of this part).

**Comment by drew-parsons** [comment]
Having an option to prevent roundcube from interfering with the message format would be very welcome.  There's more than one use case affected by this bug,
- corrupting in-line patches, as reported in this bug 
- corrupting GPG signatures, reported in #5504
- corrupting Debian bug control messages (https://www.debian.org/Bugs/server-control)

With the latter case, roundcube has recently started splitting control lines, for instance formatting
```
forwarded 988250 https://github.com/census-instrumentation/opencensus-go/issues/1259
```
as
```
forwarded 988250
https://github.com/census-instrumentation/opencensus-go/issues/1259
```
which breaks the message processing.

In the past roundcube did not do this, not sure if it's a regression in 1.4.11.

**Comment by alecpl** [comment]
For mail preview and reply we have #6974. For mail compose we have #5101. I'm closing this one.
