### ISSUE TITLE
htaccess conditional block for php5 but not for other versions

### ISSUE THREAD

**Issue by grumpa** [roundcube/roundcubemail#6439]
Hello,
there on top in htaccess file is a conditional block for php5 with comment "for php7 the module name in the line below need to be modified!"
I think it would be better add second block for php7.
Or to remove the conditional at all - it seems it works without changes in 5 and 7 too. So why to check the version?
Thank you Viktor

**Comment by alecpl** [comment]
The whole block has been removed in 1.4.

**Comment by grumpa** [comment]
OK. Future is coming :-)
Thank you for your answer. I'm satisfied with it.
