### ISSUE TITLE
Get rid of referer_check

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6440]
With enabled referer_check:
1. In Edge and IE the error is thrown when refreshing the page on Mail and Contacts UI. This is caused by our history.replaceState() use, which in these browsers unsets document referrer.
2. In Firefox the error is thrown when previewing an image attachment. Probably the referrer is unset when doing the frame refresh (in steps/mail/get.inc).
3. I don't see more issues right now, but I can easily imagine more issues as browsers these days tend to remove referrer information for privacy reasons in many cases. I also remember some issues from the past where IE could change the referrer when switching HTML render mode.

So, I think it brings more problems than benefits. As the Referrer header can be easily spoofed, such protection does not sound very useful these days. I propose to get rid of the option.

@thomascube what do you think?

**Comment by thomascube** [comment]
@alecpl I agree, the referrer check is probably obsolete these days

**Comment by alecpl** [comment]
Done.
