### ISSUE TITLE
Attachments in Greek language  not showing in incoming mail

### ISSUE THREAD

**Issue by alekosbiki** [roundcube/roundcubemail#6441]
The problem is that when an incoming mail has attachment  in Greek language (is UTF8 mime) then the email (with correct size)  have the attachment name as DATE_ Tue, 11 Sep 2018 16_16_12 +0300.doc and the size is 0KB. The same happens  when the sender is the roundcube or not. Rondcube version is 1.3.7 . Sorry for my English.

**Comment by alecpl** [comment]
Could you attach a sample message (you can remove attachment body and other sensitive information)? Enable imap_debug and provide the log from the moment when you open the message. What PHP version?

**Comment by alekosbiki** [comment]
I use PHP 5.4.7
I have 2 test case. The 1st is from gmail to my server (hmailserver) and the second is sent and receive email from internal accounts.
the name of the file that I sent is "αβγδεζηθικλμνξοπρστυφχψω.doc"

[imap_testcase1.txt](https://github.com/roundcube/roundcubemail/files/2385549/imap_testcase1.txt)
[imap_testcase2.txt](https://github.com/roundcube/roundcubemail/files/2385550/imap_testcase2.txt)

**Comment by alekosbiki** [comment]
My server is hmailserver. As a temporary solution from me is for all incoming and outgoing email to check if files with Greek names exist. If we have Greek name I change it to greekenglish (Latin characters).  So the vbscript event to make it is:
Sub RenameAttachments(oMessage)
Dim fso, filespec, i, oApp
  	Set fso = CreateObject("Scripting.FileSystemObject")
	Set oApp = CreateObject("hMailServer.Application")
	Call oApp.Authenticate("Administrator", "gnomonas")
	If oMessage.Attachments.Count>0 Then
		For i = 0 To oMessage.Attachments.Count-1
			pos=InStrRev(oMessage.Attachments(i).Filename,".",-1)
			strfilename=Mid(oMessage.Attachments(i).Filename,1,pos-1)
			strascii=GreekenglishConvert(strfilename)
			strascii=strascii & Mid(oMessage.Attachments(i).Filename,pos)
			filespec = oApp.Settings.Directories.DataDirectory & "\" & strascii
	        	oMessage.Attachments(i).saveas(filespec)
		        oMessage.Attachments(i).delete
        		oMessage.Attachments.add(filespec)
		        oMessage.save
			fso.DeleteFile(filespec)
		Next
	oMessage.save
	End if
End sub



Function GreekenglishConvert(strtoconv)
Dim newstr,strgreek, strgrenglish, j ,pos
newstr=""
strgreek=    "ΑΆΒΓΔΕΈΖΗΉΘθΙΊΪΚΛΜΝΞΟΌΠΡΣΤΥΎΫΦΩΏαάβγδεέζηήιίϊΐκλμνξοόπρσςτυύϋΰφωώχΧΨψ"
strgrenglish="AAVGDEEZII88IIIKLMNXOOPRSTYYYFWWaavgdeeziiiiiiklmnxooprsstyyyyfwwxXCc"
for j=1 to len(strtoconv)
pos=InStr(strgreek,mid(strtoconv,j,1))
if pos>0 then
newstr=newstr & mid(strgrenglish,pos,1)
else
newstr=newstr & mid(strtoconv,j,1)
end if
Next
GreekenglishConvert =newstr
End Function

**Comment by alecpl** [comment]
This
```
BODYSTRUCTURE ((("TEXT" "PLAIN" ("CHARSET" "UTF-8") NIL NIL NIL 36 2)("TEXT" "HTML" ("CHARSET" "UTF-8") NIL NIL NIL 57 2) "ALTERNATIVE" ("BOUNDARY" "000000000000bd4d750575e42902") NIL NIL)("APPLICATION" "MSWORD" ("NAME" "DATE: Sat, 15 Sep 2018 10:48:16 +0300...
```
indicates this is hmailserver issue.
