### ISSUE TITLE
Password DSN ignoring host:

### ISSUE THREAD

**Issue by dc-rh** [roundcube/roundcubemail#6442]
Strange issue with the password plugin not picking up the correct mysql host:

Environment:
CentOS Linux release 7.4.1708
php56w from Webtatic
Roundcube Webmail 1.3.4
password 	4.2

plugins/password/config.inc.php:
     $config['password_db_dsn'] = 'mysql://user:password@**mxhost.fqdn**/database';

log/errors:
     DB Error: SQLSTATE[28000] [1045] Access denied for user 'user'@'**localhost.fqdn**' (using password: YES) in /path/rcube_db.php online 175 (POST /webmail/?_task=settings&_action=plugin.password-save)

localhost.fqdn is not in any of the config files, db_dsnw points at 127.0.0.1

If you want any more info, let me know.

D.

**Comment by alecpl** [comment]
I don't know why that happens, but the error message comes directly from mysql. Does not look like something we can fix on Roundcube side.

**Comment by danielritofos** [comment]
Как вы решили эту проблему? Я не могу справиться с этим. В config/config.inc.php правильный данные, но всё равно

DSN (write):  NOT OK (SQLSTATE[HY000] [1045] Access denied for user 'roundcube'@'localhost' (using password: YES))
