### ISSUE TITLE
How to automatic login use javascript call roundcube API ?

### ISSUE THREAD

**Issue by tanzhenchao** [roundcube/roundcubemail#6447]
We need to automatic login roundcube with javascript call roundcube API.
Can you provide  usage method of roundcube API?

**Comment by alecpl** [comment]
This is not possible because of security protection. You'll have to write a plugin. Use autologon plugin as an example.

**Comment by tanzhenchao** [comment]
What do you mean by this?
https://github.com/alexjeen/Roundcube-AutoLogin
