### ISSUE TITLE
mailpoet newsletter empty

### ISSUE THREAD

**Issue by marties** [roundcube/roundcubemail#6448]
subscribing to a newsletter managed by the last version of Mailpoet (under wordpress), i receive an email with a subject to confirm subscription but a blank body using the webmail of the french adsl provider https://webmail.free.fr/  
if i read the message with thunderbird there is no problem reading the body.
under another webmail like rainloop there is also no problem.

not sure if it's roundcube or mailpoet's problem.

**Comment by alecpl** [comment]
Please, provide a sample message source.

**Comment by marties** [comment]
here it is, you can also test by trying to subscribe to the newsletter on this website https://www.gervanne-sye.com/

`Objet: Confirmation de votre abonnement à Gervanne-Sye
Photo du contact
De 	Gervanne-Sye
Date 	Aujourd'hui 14:46
Return-Path: bounce-17656@m1.sendingservice.net
Received: from zimbra65-e11.priv.proxad.net (LHLO
    zimbra65-e11.priv.proxad.net) (172.20.243.215) by
    zimbra65-e11.priv.proxad.net with LMTP; Fri, 14 Sep 2018 14:46:17 +0200
    (CEST)
Received: from smtp4.sendingservice.net (mx27-g26.priv.proxad.net [172.20.243.97])
    by zimbra65-e11.priv.proxad.net (Postfix) with ESMTP id 62E23EAD30A
    for <marties@free.fr>; Fri, 14 Sep 2018 14:46:16 +0200 (CEST)
Received: from smtp4.sendingservice.net ([79.98.99.6])
    by mx1-g20.free.fr (MXproxy) with ESMTPS for marties@free.fr
    (version=TLSv1/SSLv3 cipher=AES256-GCM-SHA384 bits=256);
    Fri, 14 Sep 2018 14:46:16 +0200 (CEST)
X-ProXaD-SC: state=HAM score=0
X-ProXaD-Cause: (null)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=s01; d=sendingservice.net;
    h=Date:From:Reply-To:To:Message-ID:Subject:Mime-Version:Content-Type:
    Content-Transfer-Encoding;
    bh=Ri+sWXfYJak/bvzaRpp8LUK9Sw1IQYXYsgjMMbHDF5o=;
    b=YkaJjqNMQ+Lo6BNtXlROik15vAV9O26WD8eqRhxd8nTm0nLmWasJ/aUCXEpH66l1lnOMKjRbhxmw
    otp4piOwte72UhMsj8q8NEr913aLqxmJ21SLY4UbChlPzBlSr7t4Y27wjE0I61sTRIkQlcrzgHL7
    AQpjmQr45cOmBy92qMI=
Date: Fri, 14 Sep 2018 12:46:16 +0000
From: Gervanne-Sye <xxxxxxxxx>
Reply-To: admin <xxxxxxxxx>
To: xxxxxxxxxxxxxxxxx
Message-ID: <3da42385-ce28-4d95-9229-99c9abb81757@sendingservice.net>
Subject: =?UTF-8?Q?Confirmation_de_votre_abonnement_=C3=A0_Gervanne-Sye?=
Mime-Version: 1.0
Content-Type: multipart/alternative;
    boundary="--==_mimepart_5b9bad982a26d_26b53f95fc11ac34234595559f";
    charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-UserID: 17656
Feedback-ID: 17656:mailpoet
X-Virtual-MTA: smtp4
Corps du courriel
`

**Comment by alecpl** [comment]
Please, provide a valid message source. Not only headers.

**Comment by marties** [comment]
Hello, sorry for the delay, here it is

`Return-Path: <bounce-17656@m3.sendingservice.net>
Delivered-To: XXXXXXX
Received: from localhost (localhost [127.0.0.1])
	by disroot.org (Postfix) with ESMTP id A25B733EEB
	for <XXXXXXX>; Fri, 14 Sep 2018 15:05:44 +0200 (CEST)
X-Virus-Scanned: Debian amavisd-new at disroot.org
X-Spam-Flag: NO
X-Spam-Score: -0.747
X-Spam-Level:
X-Spam-Status: No, score=-0.747 tagged_above=-9999 required=5
	tests=[BAYES_00=-1.9, DKIM_ADSP_CUSTOM_MED=0.001, DKIM_SIGNED=0.1,
	DKIM_VALID=-0.1, FREEMAIL_FORGED_FROMDOMAIN=0.001,
	FREEMAIL_FROM=0.001, HEADER_FROM_DIFFERENT_DOMAINS=0.25,
	HTML_MESSAGE=0.001, NML_ADSP_CUSTOM_MED=0.9, SPF_PASS=-0.001]
	autolearn=no autolearn_force=no
Received: from knopi.disroot.org ([127.0.0.1])
	by localhost (disroot.org [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id HXQjh3KG90JY for <XXXXXXX>;
	Fri, 14 Sep 2018 15:05:43 +0200 (CEST)
X-Greylist: delayed 600 seconds by postgrey-1.36 at mail01; Fri, 14 Sep 2018 15:05:42 CEST
Authentication-Results: disroot.org;
	dkim=pass (1024-bit key; unprotected) header.d=sendingservice.net header.i=@sendingservice.net header.b="A/Ny1FtW";
	dkim-atps=neutral
Received: from smtp18.sendingservice.net (smtp18.sendingservice.net [79.98.99.20])
	by disroot.org (Postfix) with ESMTPS id E584433E2B
	for <XXXXXXX>; Fri, 14 Sep 2018 15:05:42 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; s=s01; d=sendingservice.net;
 h=Date:From:Reply-To:To:Message-ID:Subject:Mime-Version:Content-Type:
 Content-Transfer-Encoding;
 bh=V9XJTtYSt3qR062vgGiv0qKr4Rf4lmzPT1I2p/Tf/7I=;
 b=A/Ny1FtWTTNxUPGMsDz5SuBNbJcY6Ed5kTTzaqFNUqGwr8/Vv0575iS1bqBePr0jEjonV/vivHHs
   r6K/XMqimM/Qd45r1FG6SSJKg3CbokokhfmoASUUEGbPdF9Xv3C6kh2zqWenxgr8XmIhmFJS0b/U
   DrdRkOlvQmWzvRfdyfk=
Date: Fri, 14 Sep 2018 12:55:41 +0000
From: Gervanne-Sye <gervanne.sye@gmail.com>
Reply-To: admin <gervanne.sye@gmail.com>
To: XXXXXXX
Message-ID: <2afdd239-3972-4a37-ab86-c90ef489eaa3@sendingservice.net>
Subject: =?UTF-8?Q?Confirmation_de_votre_abonnement_=C3=A0_Gervanne-Sye?=
Mime-Version: 1.0
Content-Type: multipart/alternative;
 boundary="--==_mimepart_5b9bafcd7830c_26b512c2d3c23460901e0";
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable
X-UserID: 17656
Feedback-ID: 17656:mailpoet
X-Virtual-MTA: smtp18


----==_mimepart_5b9bafcd7830c_26b512c2d3c23460901e0
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Bonjour,<br /> <br /> <a target=3D"_blank" href=3D"https://www.gervanne-s=
ye.com/?mailpoet_page=3Dsubscriptions&mailpoet_router&endpoint=3Dsubscrip=
tion&action=3Dconfirm&data=3DeyJ0b2tlbiI6ImMxZmZkNyIsImVtYWlsIjoiZmFicmlj=
ZW1AZGlzcm9vdC5vcmcifQ">cliquez ici pour confirmer votre abonnement</a> =C3=
=A0 notre lettre d'information.<br /> <br /> Merci, <br /> <br /> L'=C3=A9=
quipe de Gervanne-Sye !=

----==_mimepart_5b9bafcd7830c_26b512c2d3c23460901e0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Bonjour,<br /> <br /> <a target=3D"_blank" href=3D"https://www.gervanne-s=
ye.com/?mailpoet_page=3Dsubscriptions&mailpoet_router&endpoint=3Dsubscrip=
tion&action=3Dconfirm&data=3DeyJ0b2tlbiI6ImMxZmZkNyIsImVtYWlsIjoiZmFicmlj=
ZW1AZGlzcm9vdC5vcmcifQ">cliquez ici pour confirmer votre abonnement</a> =C3=
=A0 notre lettre d'information.<br /> <br /> Merci, <br /> <br /> L'=C3=A9=
quipe de Gervanne-Sye !=

----==_mimepart_5b9bafcd7830c_26b512c2d3c23460901e0--
`

**Comment by alecpl** [comment]
As you can see the message has incorrect text/plain part. The link there will not be handled properly, as no HTML is expected there. The HTML part is fine, though. Anyway, it works on my Roundcube installation.

From what I hear your a user not admin of that Roundcube installation, so we can't help you.

**Comment by marties** [comment]
i'm a webmaster which uses wordpress + mailpoet and i "dislike" my mail's client being invisible from a part of it's subscribers.
From what you said i guess i'm gona notify Mailpoet's developpers.
Thanks
