### ISSUE TITLE
Space separated recipients

### ISSUE THREAD

**Issue by omarchehab98** [roundcube/roundcubemail#6457]
When editing an email's **To**, **CC**, and **BCC** fields, it's natural for someone to space separate the list of email addresses.

I am aware that the recipient fields expect a comma separated list of email address, so this is not a bug report, it's a usability suggestion.

## Steps To Reproduce

Type `alice@example.com bob@example.com charlie@example.com` in one of the recipient fields.

Roundcube: v1.3.6
Skin: larry
Plugins: managesieve, password, enigma

## Expected Behaviour 

Email is sent to the 3 email addresses `alice@example.com`, `bob@example.com`, and `charlie@example.com`.

## Actual Behaviour

Email is sent to the email address `"alice@example.com bob@example.com" <charlie@example.com>`.

**Comment by thomascube** [comment]
Please not that the common format of entering recipients (mostly when using autocompletion) is "<display name><space><email-address>". With the display name prepended, the space character is already used to separate it from the actual email address and therefore cannot be used to separate recipients. With autocompletion showing suggestions, how would you allow to refine the suggestions (e.g. "John" yields 20 matches) if the space character will already terminate a (yet incomplete) recipient?

**Comment by omarchehab98** [comment]
Look, I understand that this might be hard to implement because of a conflict with an existing feature. But quite frankly, it doesn't matter. I am reporting this as a serious usability issue that most people will have issues with.

Yesterday, I had one of my clients complain about this. I looked into it and it turns out they sent an email with the following **BCC:** `"a@example.com b@example.com ... n@example.com" <n@example.com>`. I don't blame them one bit. How can your system accept such a name in the first place? It's so easy to detect something is very wrong in this case. I mean, if an email address's associated name contains an email address, the least you can do is tell the user that something is seems off. In the current version of Roudcube, it just sends the email as if nothing is wrong. So, instead of sending an email to 14 recipients, the user would end up sending it to 1 with a name composed of 13 freaking email addresses-- that's insane!

If you don't want to change the fact that space doesn't separate email addresses, the least you can do is add a message that teaches the user the format of listing recipients or a pop up that warns the user that something is wrong with their recipients.

**Comment by omarchehab98** [comment]
Compose a new email, add 3 email addresses to the **To** field

![alice@example.com bob@example.com charlie@example.com in the To field](https://user-images.githubusercontent.com/12089120/45923248-f479a580-beae-11e8-8b0c-9aa168726b37.png)

Save the email as a draft then open the draft you saved.

![alice@example.com and bob@example is the name of the email address charlie@example.com](https://user-images.githubusercontent.com/12089120/45923249-f5123c00-beae-11e8-8e95-c4e1acf5a3b4.png)

Why did your recipient parsing algorithm make such an assumption? Do you honestly think "alice@example.com bob@example.com" is a name of charlie@example.com?

**Comment by alecpl** [comment]
I would not call it a serious issue, because you're the first person requesting it. It's like that for more than 10 years. Thunderbird also does not accept such input (though it will not send the mail in such case), Gmail however does. So, I think we could indeed do better.

**Comment by mcazzola** [comment]
Hello, I've ecountered this problem too this morning, I'm on an older version of Roundcube but the issue seems the same. Probably a lot more of email have gone missing without noticing, only yesterday an user asked me for this strange behaviour. We use roundcube only in emergency cases so I was going to update thinking this was just a little bug of an older version but now I think this is "normal".
I think that a small box would be appreciated just like the one when object is empty, who knows how many mail have gone missing for just low attention to typing?
Thanks in advance

**Comment by alecpl** [comment]
Implemented for Elastic, the rest is wontfix.
