### ISSUE TITLE
Elastic: Disable right reading pane

### ISSUE THREAD

**Issue by tramtrist** [roundcube/roundcubemail#6458]
I've looked everywhere in the settings and within this issue list and cannot find this so I'm adding it.
This may be a feature request(?) but I'd like to have the ability to hide the right reading pane and simply have a list of mails as a list view.  

Thanks!

**Comment by alecpl** [comment]
No such feature. As the skin author I'm really not interested in having it. Such feature would increase complexity much and Elastic's code is already quite big.

**Comment by julianmatz** [comment]
What about having an option to prevent automatically loading a message? The new skin is great, but sometimes, we just want to delete some mails without loading them, especially if we know they're junk.

**Comment by joepitt91** [comment]
I'd really like this feature too; shame about the blanket no

**Comment by alecpl** [comment]
To mark messages use Ctrl/Shift or checkbox selection. You don't have to open a message to delete it. So, that's not an argument.

**Comment by joepitt91** [comment]
> To mark messages use Ctrl/Shift or checkbox selection. You don't have to open a message to delete it. So, that's not an argument.

Personally I just much prefer the look of a simple list, but also like responsive web apps; I'd rather see more details about the message in a single line.

**Comment by tramtrist** [comment]
> > To mark messages use Ctrl/Shift or checkbox selection. You don't have to open a message to delete it. So, that's not an argument.
> 
> Personally I just much prefer the look of a simple list, but also like responsive web apps; I'd rather see more details about the message in a single line.

Yes this is what I'd also like to see.  It's unfortunate as Elastic is a really nice skin.  This one particular missing feature is keeping me on the standard Larry skin.  I'm just too OCD to handle losing half the screen to a blank area

**Comment by joepitt91** [comment]
> Yes this is what I'd also like to see. It's unfortunate as Elastic is a really nice skin. This one particular missing feature is keeping me on the standard Larry skin. I'm just too OCD to handle losing half the screen to a blank area

Disappointing the issue has been closed with a "I don't want it; so I don't care" style response.

**Comment by hdagelic** [comment]
> Disappointing the issue has been closed with a "I don't want it; so I don't care" style response.

Yes! The thing I dislike the most about new Roundcube is that three-row display. Looks very complicated, and to me almost unuseable. We are using Roundcube at our sci-institute, the old version, and I don't want to make people dizzy and seeing only a part of their message subjects!

I'll try to hack-out the preview pane and let you know if I manage to do it.

**Comment by angryferret** [comment]
I'm using Rainloop instead. I would have stuck with Roundcube if there was no reading pain, but this is a deal breaker for me. Unfortunate as I will now recommend Rainloop instead in my organisation which will need around 1200 web mail users. @alecpl you should really have factored this in. It's a must for any modern webmail client.

**Comment by gusarg81** [comment]
Every resume to "So, that's not an argument". Nice one @alecpl . A straigh way answer to just go with Rainloop.

The will be always Email clients users that prefer to just open the message in a new window/view and others have a left/right/whatever pane. So, you as developer should take in count what most of Email client has as options and not to be such authoritative in your responses. Is like to say "It is like this just because".

**Comment by tramtrist** [comment]
> > Disappointing the issue has been closed with a "I don't want it; so I don't care" style response.
> 
> Yes! The thing I dislike the most about new Roundcube is that three-row display. Looks very complicated, and to me almost unuseable. We are using Roundcube at our sci-institute, the old version, and I don't want to make people dizzy and seeing only a part of their message subjects!
> 
> I'll try to hack-out the preview pane and let you know if I manage to do it.

Did you ever get to 'hacking it' out?

**Comment by alecpl** [comment]
There's a plugin for Roundcube 1.5, https://github.com/johndoh/roundcube-elasticlayouts

**Comment by hdagelic** [comment]
Hello, if you want to hack this yourself, here is how it could be done:

https://github.com/hdagelic/roundcube-hacks

**Comment by hdagelic** [comment]
> 
> 
> Great work ! I've tried this out and its working flawlessly so far. Thank you!

No problem!


Check out the login mod:

https://mail2.irb.hr/

Cool, ha? To change that you can edit: skins/elastic/templates/login.html

**Comment by alecpl** [comment]
Guys, I'm locking conversation in this ticket. This is not a discussion forum.

The relevant information here for everyone is: There's a plugin for Roundcube 1.5, https://github.com/johndoh/roundcube-elasticlayouts
