### ISSUE TITLE
Elastic: Row Separated recipients

### ISSUE THREAD

**Issue by danielh84** [roundcube/roundcubemail#6460]
if you copy a list of mailadresses from excel into RC 1.3.6 / Beta 1.4 it works fine (without any seperator, only using a new row for each of the adresses) with larry skin. 

if you save your mail as a draft, the list of adresses are separated with an "," and the mail will be send to each of the receipients. 

with elastic in Beta 1.4 it does not work. 

Elastic-Beta 1.4
![image](https://user-images.githubusercontent.com/19638140/45992542-b507b080-c08a-11e8-8d65-0b198ca1761b.png)

Larry-Beta 1.4
![image](https://user-images.githubusercontent.com/19638140/45992568-dcf71400-c08a-11e8-9d9c-8b4d1dc412e4.png)
![image](https://user-images.githubusercontent.com/19638140/45992581-fb5d0f80-c08a-11e8-8725-4b1812880f4c.png)

**Comment by alecpl** [comment]
Indeed. I wasn't aware of this feature. That should be simple to fix.

**Comment by alecpl** [comment]
Not that simple, but done.
