### ISSUE TITLE
Reply,Reply all,Forward Not loading the email list to Recipients Address in compose screen

### ISSUE THREAD

**Issue by Adupa** [roundcube/roundcubemail#6461]
Hai When selecting  a mail and clicking on the reply or forward buttton, then the emails recipients is not loading to the compose screen.

**Comment by alecpl** [comment]
Forward obviously should not, but Reply and Reply All should. We need more information. What version? What skin? What browser? Did you try with disabled all plugins? Any errors in logs or browser console? Is it for all mails or only some?

**Comment by Adupa** [comment]
> Forward obviously should not, but Reply and Reply All should. We need more information. What version? What skin? What browser? Did you try with disabled all plugins? Any errors in logs or browser console? Is it for all mails or only some?

roundcube Version:-1.3.4
Skin: larry
Browser: chrome
no error is found in the console screen. 
It is for all the emails

**Comment by alecpl** [comment]
Looks like you have non-standard skin with some extensions. Ask the author about the issue.
