### ISSUE TITLE
Elastic: unread message count on folders is not updated until folder contents are viewed

### ISSUE THREAD

**Issue by silvester747** [roundcube/roundcubemail#6463]
I use sieve to move incoming messages into separate subfolders. In Larry the folder name would become bold to show new messages have arrived. In the new Elastic theme this only works directly after initial login. If I keep the page open and new mail arrives, the folders are not updated. Also the number of unread messages in each folder is not updated. Only when I refresh the whole page the folders are updated.

I am using 1.4-beta.

**Comment by alecpl** [comment]
Works for me. Did you enable Preferences > Mailbox view > Check all folders for new messages? Are you sure it's Elastic-only issue? Does it work if you use Refresh button?

**Comment by silvester747** [comment]
Ah, indeed that setting was turned off. Is it a new setting? Because it used to work before in Larry.

**Comment by alecpl** [comment]
No, it's not new.
