### ISSUE TITLE
Washing html mails

### ISSUE THREAD

**Issue by AlexDyukov** [roundcube/roundcubemail#6464]
Hi!

After upgrading from 1.3.5 to 1.3.7 I got issue with washing html emails in web interface. It has remove some words:
```
$ diff roundcube1.3.*_html.txt
24,37d23
<                            zzz
<                            <span class="values vm2-first_name">zzzzzzzz</span>
<                            zz. zzzzz
<                            <span class="values vm2-email">1</span>
<                            <br class="clear" />
<                            zzzzzzz
<                            <span class="values vm2-phone_1">X-XXX-XXX-XX-XX</span>
<                            <br class="clear" />
<                            zzzzz zzzzzzzz
<                            <span class="values vm2-address">zzzzzzzzz 25  zz 22 zzz 2 zz 1</span>
<                            <br class="clear" />
<                         </td>
<                         <td valign="top" width="50%">
<                            zzz
39d24
<                            zzzzz zzzzzzzz
```
there is an example mail:
[roundcube_example_mail.txt](https://github.com/roundcube/roundcubemail/files/2420134/roundcube_example_mail.txt)

interface view 1.3.5 compare to 1.3.7:
![roundcube1 3 5_html](https://user-images.githubusercontent.com/21895986/46086075-107f8e80-c1b0-11e8-9a65-96be4d681cc5.png)
![roundcube1 3 7_html](https://user-images.githubusercontent.com/21895986/46086079-11182500-c1b0-11e8-8c6b-f59d714ba66c.png)

and "rcmBody" part:
[roundcube1.3.5_html.txt](https://github.com/roundcube/roundcubemail/files/2420108/roundcube1.3.5_html.txt)
[roundcube1.3.7_html.txt](https://github.com/roundcube/roundcubemail/files/2420109/roundcube1.3.7_html.txt)

Thank you.

**Comment by alecpl** [comment]
I confirm that problem is with handling HTML comments. For this snippet:
```
<!-- span class="titles">zzz</span -->
<span class="values vm2-first_name" >zzzzzzzz</span>
<!-- span class="titles">zz. zzzzz</span -->
<span class="values vm2-email" >1</span>
<br class="clear" />
```
output is:
```
<br class="clear" />
```

**Comment by alecpl** [comment]
Fixed. I have to note that the bahavior in 1.3.5 was also not valid. BTW, the use of comments in that sample message looks really strange and in some cases invalid/confusing.
