### ISSUE TITLE
Elastic mobile/Autocomplete: Long names exceed display width

### ISSUE THREAD

**Issue by skanadian** [roundcube/roundcubemail#6469]
Latest master

How to Reproduce
- Create 2 contacts, one with a long display name, one normal.  ie.

1. This is a really long display name \<reallylongemail@address1.com\>
2. ShortName \<short@address2.com\>

- Enable elastic skin 
- Use elastic mobile in portrait mode and landscape mode
- Compose email
- In the To: field, begin typing characters from your created contacts and wait for autocomplete results

Results
- When in portrait, the display name (and each subsequent display name) is cut off on the left hand side]
![portrait](https://user-images.githubusercontent.com/43651180/46166449-35800a00-c261-11e8-8fe9-cb68026ee7e7.PNG)
- When in landscape, the email address is cut off on the right side, and the screen becomes scroll-able horizontally
![landscape](https://user-images.githubusercontent.com/43651180/46166448-35800a00-c261-11e8-901a-cc63e7c3b9c0.png)

Expected results
- Autocomplete results should not exceed the display width

**Comment by alecpl** [comment]
I agree this is a bug, but I can't reproduce the horizontal scroller. What browser?

**Comment by alecpl** [comment]
Fixed.
