### ISSUE TITLE
Roundcube delete all my emails when I open a meeting invite

### ISSUE THREAD

**Issue by nawwa** [roundcube/roundcubemail#6472]
Hello,

Im using mail.ovh.net for 8 month now, Im on Linux Fedora, Chromium browser.
Everything was working fine, but since 2 month all my emails get deleted when I open a meeting invite.. 

I don't understand, I just click on the invite and all my "inbox" folder is deleted !
It's very annoying, I have many professional email and important stuff.

Fix I tried : 
Changed my password several time
Trying another browser

**Comment by alecpl** [comment]
There's no built-in functionality for invitations handling, so I guess there must be some plugin installed. We do not support that and we can't help you. Ask mail.ovh.net.

**Comment by nawwa** [comment]
I don't ask for a mail invite support man..

The main problem is that ALL MY EMAILS get deleted. 

It happened again this morning, and this time I logged in and logged out then logged in again all my emails got wiped out again.. For no reason. 

I called the OVH support center and they said that they don't know and If I want the roundcube log i had to file a complaint O.o
