### ISSUE TITLE
password plugin, option to ask for current password without verifying against $_SESSION['password']

### ISSUE THREAD

**Issue by conathan** [roundcube/roundcubemail#6473]
We have a token based login system which does not have access to the original password ($_SESSION['password'] is not the customer's current password), but we still want to allow users to change their password (and verify the original password, just not by roundcube).

To do so, we disabled the password check in plugins/password/password.php

else if (false && $conpwd != $newpwd) {
  $rcmail->output->command('display_message', $this->gettext('passwordinconsistency'), 'error');
}

and instead send both the current password provided, as well as the new password via the api.

There is password_confirm_current, but that hides asking for the current password (which we need)

**Comment by alecpl** [comment]
I guess you rather disabled this check:
```
    else if ($confirm && $sespwd != $curpwd) {
        $rcmail->output->command('display_message', $this->gettext('passwordincorrect'), 'error');
    }
```
I think we could add such an option (simple), it could also be controlled by the driver's code (more work). Would you mind providing a pull request?

**Comment by conathan** [comment]
Looks better then the one I was going to work on johndoe

**Comment by alecpl** [comment]
Merged.
