### ISSUE TITLE
Hook on move messages

### ISSUE THREAD

**Issue by AllanKlaus** [roundcube/roundcubemail#6475]
When I move messages don't exist any hook in `rcube_imap` or in `rcube_imap_generic`, so I can't manipulate messages on move.

**Comment by alecpl** [comment]
What is your use-case?

**Comment by AllanKlaus** [comment]
My team of sysadmins need log when on user move messages between folders. With these hook we log how is our user, how many messages and where he is moving his messages.

I created a [PR](https://github.com/roundcube/roundcubemail/pull/6476) with a hook that we could use.

**Comment by alecpl** [comment]
I understand that such a hook is most convenient for your use-case, but I hesitate to add hooks that only use-case is logging. Such things should be done in imap server, imo. @thomascube what's your opinion?

**Comment by thomascube** [comment]
I agree that this kind of use-case should be covered directly in imap or elsewhere. Executing plugin hooks has some cost and thus they should be added with care.

**Comment by AllanKlaus** [comment]
Thanks, I'm closing de PR
