### ISSUE TITLE
[BUG] PHP72 Session_storage -> memcache

### ISSUE THREAD

**Issue by Ramalama2** [roundcube/roundcubemail#6480]
Hi, memcached as session_storage provider doesnt work with PHP72 maybe on PHP7 at genaral...

memcache itself works perfectly with php, tested myself with script and other websites...
just appears with roundcube 1.3.7

output:
DB Error: Failed to connect to memcached. Please check configuration in /server/WWW/roundcube/program/lib/Roundcube/rcube_session_memcache.php on line 49 (GET /)

Cheers

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/release-1.3/program/lib/Roundcube/rcube.php#L202

That's how we init memcache connection. Do you have Memcache extension loaded at all? What PHP version? What's in config? I see no reason why it would not work with PHP 7.2 other than configuration issue (or missing extension).

**Comment by alecpl** [comment]
Works for me with PHP 7.2.10 on Ubuntu 18.04. If you need pecl-memcached support, that's another story.

**Comment by Ramalama2** [comment]
you have right, im using the webtatic repo on centos and there is only
php72w-pecl-memcached avaiable, and not php72w-pecl-memcache

So yes, im sry :-)

Cheers :-)

**Comment by Ramalama2** [comment]
why not switch to memcached ?
seems to me newer + better available...

Cheers :-)

**Comment by alecpl** [comment]
FYI, memcached extension support is ready for testing in git-master now.
