### ISSUE TITLE
Table of confusion

### ISSUE THREAD

**Issue by tanzhenchao** [roundcube/roundcubemail#6484]
We used Roundcube Webmail 1.4-beta to read the mail and found the table of confused.

**1. The normal client displays,**

![mail_tables](https://user-images.githubusercontent.com/9416935/47057957-88603800-d1f5-11e8-9f54-20f700aee2b6.jpg)

**2. Roundcube Webmail client displays,**

![mail_tables_issue](https://user-images.githubusercontent.com/9416935/47057586-f4da3780-d1f3-11e8-93c0-080dd3519705.jpg)

**3. Root cause**

```
				<div id="messagebody"><div class="message-part" id="message-part1"><div class="pre">                                                                               <br>
   d         |  d         |  d         |  d         |  d         |  d          <br>
 ------------+------------+------------+------------+------------+------------ <br>
   d         |  d         |  d         |  d         |  d         |  d          <br>
 ------------+------------+------------+------------+------------+------------ <br>
   d         |  d         |  d         |  d         |  d         |  d          <br>
                                                                               <br>
<br>
```
I guess this problem is caused by the incompleteness of the ascii code transform to html code.
Is there any solution to solve this problem?

**Comment by alecpl** [comment]
Could you attach a sample message?

**Comment by tanzhenchao** [comment]
Thank you very much, but I don't know how to extport a sample message? Can the screenshot be ok?
![sample message](https://user-images.githubusercontent.com/9416935/47069970-d475a180-d222-11e8-8a71-970eee88bf39.PNG)

**Comment by tanzhenchao** [comment]
Hi Alecpl,

Please see below details, Thanks!

`Subject: test
X-KeepSent: 24CD093E:34933637-48258328:0029C85F;
 type=4; name=$KeepSent
To: xxxx@example.com
X-Mailer: IBM Notes Release 9.0.1FP9 August 15, 2017
Message-ID: <OF24CD093E.34933637-ON48258328.0029C85F-48258328.0029DE69@example.com>
From: xxx@example.com
Date: Tue, 16 Oct 2018 15:37:19 +0800
X-MIMETrack: Serialize by IMAP Server on XXX/XXX/XXX(Release 9.0.1FP3|January  12, 2015) at
 10/17/2018 03:45:26 PM
MIME-Version: 1.0
Content-type: text/plain; charset=US-ASCII

                                                                               
   d         |  d         |  d         |  d         |  d         |  d          
 ------------+------------+------------+------------+------------+------------ 
   d         |  d         |  d         |  d         |  d         |  d          
 ------------+------------+------------+------------+------------+------------ 
   d         |  d         |  d         |  d         |  d         |  d          
                                                                               






[...]

`

**Comment by tanzhenchao** [comment]
> 你能附上一条示例信息吗？

**Comment by alecpl** [comment]
I'm unable to reproduce the issue. For me the HTML output is:
```
<div class="pre"><span style="white-space:nowrap">   d         |  d         |  d         |  d         |  d         |  d</span><br>
 ------------+------------+------------+------------+------------+------------<br>
<span style="white-space:nowrap">   d         |  d         |  d         |  d         |  d         |  d</span><br>
 ------------+------------+------------+------------+------------+------------<br>
<span style="white-space:nowrap">   d         |  d         |  d         |  d         |  d         |  d</span><br>
```

**Comment by tanzhenchao** [comment]
We tried to use “http://txt2html.sourceforge.net/” to complete the format conversion, but did not meet the requirements. Finally, we solved this problem by using the HTML mail format on the IMAP server. Anyway, thank you for your help, thank you!
