### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by korsar182** [roundcube/roundcubemail#6487]
I try to use LDAP address book and I can't get records from the root directory, logs say  0 record(s) found.
It works fine when I set certain OU, like  'base_dn' => 'ou=certain_ou,dc=my,dc=domain,dc=com',
My settings:
```
$config['ldap_public'] = array(
    'MyAdLdap' =>array (
        'name' => 'Big company, Inc',
        'hosts' => array('192.168.100.100'),
        'sizelimit' => 6000,
        'port' => 3268, # See comments below
        'use_tls' => false,
        'user_specific' => false,
        'base_dn' => 'dc=my,dc=domain,dc=com',
        'bind_dn' => 'my_user@my.domain.com',
        'bind_pass' => 'my_pass',
        'writable' => false,
        'ldap_version' => 3,
        'search_fields' => array(
           'mail',
           'cn',
        ),
        'name_field' => 'cn',
        'email_field' => 'mail',
        'surname_field' => 'sn',
        'firstname_field' => 'givenName',
        'sort' => 'sn',
        'scope' => 'list',
        'filter' => '(&(mail=*)(|(&(objectClass=user)(!(objectClass=computer)))(objectClass=group)))',
        'global_search' => true,
        'fuzzy_search' => true
    ),
);
```
What I do wrong? I guess something wrong with filter...

**Comment by alecpl** [comment]
Enable ldap_debug and check the log.

**Comment by korsar182** [comment]
C: Search base dn: [dc=my,dc=domain,dc=com] scope [list] with filter [(&(mail=*)(|(&(objectClass=user)(!(objectClass=computer)))(objectClass=group)))]
Using function ldap_list on scope list ($ns_function is ldap_read)
C: (Without VLV) Setting a filter of (&(mail=*)(|(&(objectClass=user)(!(objectClass=computer)))(objectClass=group)))
Executing search with return attributes: array (#012  0 => 'dn',#012)
S: 0 record(s) found

**Comment by korsar182** [comment]
Yeah, that's the key, thank you!
