### ISSUE TITLE
Support MB4 in subject or other field

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6488]
Howdy,

With the news emails clients and the introduction of MB4 there's some people sending emails with some "images" with mb4 that the newer outlook's clients do.
So, for RC is it possible to add this feature when displaying emails?
This particular email show's empty subject in 1.3.7.
Attach some info for you.
![rc_mb4](https://user-images.githubusercontent.com/13902147/47286063-22085a80-d5e5-11e8-8262-43015178a5cb.jpg)
![rc_mb4_subject](https://user-images.githubusercontent.com/13902147/47286064-22a0f100-d5e5-11e8-8e5e-f0111633d284.jpg)
[rc_raw_msg.txt](https://github.com/roundcube/roundcubemail/files/2500804/rc_raw_msg.txt)

**Comment by alecpl** [comment]
Works for me in Chrome and Firefox on Linux. PHP 7.3.
![screenshot_20181024_092845](https://user-images.githubusercontent.com/546788/47413820-9e2ea980-d76f-11e8-81e2-e9c3531a5047.png)
What browser? What PHP version?

**Comment by dddns** [comment]
PHP 7.2
Firefox

**Comment by alecpl** [comment]
It might be imap server issue. What imap server? Could you enable imap_debug and provide the log?

**Comment by alecpl** [comment]
No feedback.

**Comment by dddns** [comment]
Hi Allec,
Sorry from the delay, i was away from the keyboard for a few days, and had no change to create the debug.
Here's the file, can it be my imap server problem?

**Comment by dddns** [comment]
Can't attach, here's the file:

http://neotrix.decimal.pt/bugs/syslog_rc.txt

**Comment by alecpl** [comment]
Yes. This is IMAP server issue. The server response is:
```
Date: Mon, 22 Oct 2018 09:01:35 +0000
From: =?iso-8859-1?b?TG9jYWxpemHn428=?= GPS
To: jorge@aaaaaaaaaa.pt
Subject: 
Content-type: multipart/alternative
...
```

**Comment by dddns** [comment]
Alec,

Oh ok, sorry for the time you wasted on this.
I have to kill this dbmail server!!

Thanks again,
