### ISSUE TITLE
Have a recipient with None Ascii character

### ISSUE THREAD

**Issue by stoivo** [roundcube/roundcubemail#6490]
I would like to send a email to an address "rått@papir.no"
This did't work, nor chould I create the contact

![contact](https://user-images.githubusercontent.com/3492040/47317284-747b6280-d649-11e8-9e18-4fa5f4b64f96.png)
![compose email](https://user-images.githubusercontent.com/3492040/47317285-7513f900-d649-11e8-8d8e-ff333ecb5963.png)

I did manage to send the email form googles web client.

Maybe this is how it is suppose to be but would't find anything abount it.

Thanks for createing and maintaining RoundCube. We have peen using Roundcube for at least a decade. Thanks.

**Comment by stoivo** [comment]
After a little more checking it looks like my norwegians charachters æøå is not allowed.

**Comment by alecpl** [comment]
I confirm the issue in mail compose, but adding such a contact works for me. What Roundcube version? What database version?

**Comment by alecpl** [comment]
I fixed the composer issue. We'd need some feedback on the other issue.

**Comment by alecpl** [comment]
I'm closing this one, open a new ticket when you have more info.
