### ISSUE TITLE
Add CTRL + Enter shortcut to Send Mail

### ISSUE THREAD

**Issue by gloony** [roundcube/roundcubemail#6491]
Hi, I would know if you think it is possible to add a shortcut in TinyMCE for Send mail with CTRL + Enter ?
I already make that on every release since a while, but I think that can be appreciated by some users.
Eventually, give the possibility to change this in settings, to avoid to confuse users whom doesn't want it.

I change this function (on the minified file, so it hard to tell the line)
`y=function(){u.shortcuts.add("meta+a",null,"SelectAll");}`

By Added
`y=function(){u.shortcuts.add("meta+a",null,"SelectAll");u.shortcuts.add("ctrl+13", null, function(){window.parent.$('.button.send').click();})}`

**Comment by alecpl** [comment]
We definitely will not modify TinyMCE. You could try do it in setup function in program/js/editor.js. Anyway I think this calls for some general keyboard shortcuts solution. Some plugins exist already.

**Comment by gloony** [comment]
Thank you for your quick response.

I understand the will to not modify TinyMCE so I make the modification on file program/js/editor.js.
So I add a new parameter on conf var : 
```
      init_instance_callback: function(editor){
        // Addon to Send Mail with Ctrl + Enter
        editor.shortcuts.add(
            "ctrl+13",
            null,
            function(){
              window.parent.$('.button.send').click();
            }
        );
      }
```

After my researchs I never found a plugin that add shortcut to TinyMCE (I tried to (re)check all the actual plugins on the offical repo, since your answer).
I would lovely make my own, but it appear to be tricky since TinyMCE want to set is shortcuts at the "init" event.

I let my response here, if somebody need this, in futur (assumed that you must have jQuery on your RoundCube plugins, if your version is lower than 1.4).

**Comment by thomas-mc-work** [comment]
Wouldn't there be another way to add a shortcut for sending? That would be great!

**Comment by Justinzobel** [comment]
Agreed, I'd love to be able to set Ctrl+Enter to send as I have in many other mail clients.

**Comment by thomas-mc-work** [comment]
The latest comment from @gloony looks like a proper way of integration. Wouldn't that be OK for the dev team? Maybe you could prepare that as a PR, @gloony? That'd be great!

**Comment by alecpl** [comment]
I don't like the idea. So, it will not end up in the core. However, there are some keyboard shortcuts plugins that could be interested in adding this shortcut (if not there yet).

**Comment by Justinzobel** [comment]
It's fairly core to most other email clients. Do these plugins you speak of
have Github pages where we can suggest this?

**Comment by kiuka** [comment]
@alecpl just out of curiosity, why do you not like the idea? Its kind of a standard solution, every single email client, gmail, etc, all support this hotkey by default.

**Comment by Edimahler** [comment]
Hi guys,
I see it the same way like @kiuka, @Justinzobel and @thomas-mc-work . It wouldn't bother anyone (would it?), but it is a widly known shortcut in most other email programs as well. If you could consider put it to the core, it would be great.

**Comment by emoxam** [comment]
Well two years passed, any news ?

**Comment by gloony** [comment]
> Well two years passed, any news ?

Unfortunately I think is a dead topic. I continue to make the modification manually after every update ...
And I never found a plugin that can change to editor shortcut by far.

**Comment by emoxam** [comment]
> > Well two years passed, any news ?
> 
> Unfortunately I think is a dead topic. I continue to make the modification manually after every update ... And I never found a plugin that can change to editor shortcut by far.

What modification are you doing ?

**Comment by gloony** [comment]
> Thank you for your quick response.
> 
> I understand the will to not modify TinyMCE so I make the modification on file program/js/editor.js. So I add a new parameter on conf var :
> 
> ```
>       init_instance_callback: function(editor){
>         // Addon to Send Mail with Ctrl + Enter
>         editor.shortcuts.add(
>             "ctrl+13",
>             null,
>             function(){
>               window.parent.$('.button.send').click();
>             }
>         );
>       }
> ```
> 
> After my researchs I never found a plugin that add shortcut to TinyMCE (I tried to (re)check all the actual plugins on the offical repo, since your answer). I would lovely make my own, but it appear to be tricky since TinyMCE want to set is shortcuts at the "init" event.
> 
> I let my response here, if somebody need this, in futur (assumed that you must have jQuery on your RoundCube plugins, if your version is lower than 1.4).



> > > Well two years passed, any news ?
> > 
> > 
> > Unfortunately I think is a dead topic. I continue to make the modification manually after every update ... And I never found a plugin that can change to editor shortcut by far.
> 
> What modification are you doing ?

**Comment by emoxam** [comment]
> > I understand the will to not modify TinyMCE so I make the modification on file program/js/editor.js. So I add a new parameter on conf var :
> > ```
> >       init_instance_callback: function(editor){
> >         // Addon to Send Mail with Ctrl + Enter
> >         editor.shortcuts.add(
> >             "ctrl+13",
> >             null,
> >             function(){
> >               window.parent.$('.button.send').click();
> >             }
> >         );
> >       }
> > ```
> 
> > What modification are you doing ?

Added this the end end of file - seems to work like a charm! Thanks!

**Comment by gloony** [comment]
If anyone go on this page today thing have change you can download my plugin to do it : [https://github.com/gloony/ctrl_enter_send](https://github.com/gloony/ctrl_enter_send)

**Comment by rokj** [comment]
For some reason proposed solutions does not work for me. 

I've changed a little bit @gloony 's work and following works for me https://github.com/rokj/shortcuts/
