### ISSUE TITLE
Email sent but loader is always showing "Sending Message"

### ISSUE THREAD

**Issue by riadapsis** [roundcube/roundcubemail#6492]
I have added rouncube to my localhost. It's working fine for reading my mailbox. But when I am about to send a email, It's stuck with "Sending Message" loader. It's never hiding or shown "Sent" although my email is already sent to desired receiver. Another problem is, I want to check the header to match some specific domain. So that no user can send mail to any other domain. Please help me out. I am stuck with those two problem.

**Comment by alecpl** [comment]
After the message is sent it's being written to the imap folder. Check the log and browser console for errors. Disable all plugins. You can also enable imap_debug to see more. What version? What php/os? What browser? Etc.

To answer your second question. It can be done with a plugin API, but I think this should be done on the smtp server not client.

**Comment by riadapsis** [comment]
Thanks @alecpl for quick response. My problem is resolved when I start using app.js in replace of app.min.js and the second option I done by the following code in app.js at check_compose_input function. Let the allowed domain is abc.com & xyz.com
`let input_to = $("[name='_to']").val(),
      input_cc = $("[name='_cc']").val(),
      input_bcc = $("[name='_bcc']").val();
	function validateEmails(string) {
        var result = string.replace(/\s/g, "").split(/,|;/);
        for(var i = 0;i < result.length;i++) {
            let domain = result[i].replace(/.*@/, "").replace('>','');
            if(domain != '' && !domain.match(/(\babc.com\b|\bxyz.com\b)/gmi))return false;
        }
		return true;
    }
	if(!validateEmails(input_to) || !validateEmails(input_cc) || !validateEmails(input_bcc)) return alert('Unauthorised email address found!');`

**Comment by alecpl** [comment]
You say app.min.js is broken? Should I close the ticket or you want to provide more info

**Comment by riadapsis** [comment]
Yes that what I think. I don't know whether app.min.js is broken or not but removing it from project resolved my issue.
