### ISSUE TITLE
Missing message-htmlpart1 class breaks inline CSS

### ISSUE THREAD

**Issue by apaku** [roundcube/roundcubemail#6493]
I just upgraded our roundcube instance from 1.2.3 to 1.2.9 and it appears the handling of inline CSS in HTML email parts has been changed to add #message-htmlpart1 now. Unfortunately there is no element with such an id anywhere in roundcube's rendered content. I do see a div with id messagebody as parent of the rcmBody-div.

**Comment by apaku** [comment]
Just for reference, this is a snippet of an inline CSS generated by roundcube:
`#message-htmlpart1 div.rcmBody .hll { background-color: #ffffcc }`
The original in the mail is:
`.hll { background-color: #ffffcc }`

**Comment by apaku** [comment]
I dug a bit into the code, it seems the cause of this is that the rcmail_html4inline function resets the attributes array it is being passed in. This causes the initially filled in values for class and id of the container div to vanish and thus the div containing the mail body ends up having neither id nor class.

Removing/commenting line 1470 in func.inc fixes the problem.

**Comment by alecpl** [comment]
Looks like an incomplete backport. Really 1.2 should not be used anymore.

Fixed anyway. I wouldn't expect next 1.2.x release anytime soon, though.
