### ISSUE TITLE
roundcube can't verify my own signature and promp that is invalid

### ISSUE THREAD

**Issue by Wolf20** [roundcube/roundcubemail#6496]
I can't sign any of my email with enigma, i dont know what im doing wrong, i have imported my private and public key, encryption works and signing with encryption too but if i only sign the mail i get with the message that the signature is invalid, i tried to send mail to myself to other people from the same mail server and from outside and i just cant get it to work.

**Comment by alecpl** [comment]
What Roundcube version? What PHP version? What GnuPG version? You use plain or html text? Enable enigma_debug and provide the log.

**Comment by Wolf20** [comment]
In theory yes, from the default repository. And GnuPG is installed by default beacouse i didnt install it and it's installed so... the gpg key was generated in other computer, not from enigma i don't know if that affects.

**Comment by alecpl** [comment]
What is default repository? GnuPG is likely irrelevant, I'm more interested in php dependencies (these in /vendor folder, usually installed with composer or from the vanilla roundcube package).

**Comment by Wolf20** [comment]
At the end it seems to have been some kind of very strange bug, I had to format it for a catastrophic failure on the server and make a clean installation and now it seems to work i don't know how could this happen but its good that it's working flawlessly. Thanks anyway .

**Comment by lolomin** [comment]
Hi,

I have exactly the same problem, this is what Roundcube is displaying in the top of a mail sent to a recipient when I display this mail within my Roundcube :

![image](https://user-images.githubusercontent.com/1673944/50219131-7c782a00-038e-11e9-92b5-2341d0febb80.png)

I don't thinks this is normal behaviour ?

Regards,

Laurent
