### ISSUE TITLE
Can not install on CentOS

### ISSUE THREAD

**Issue by riadapsis** [roundcube/roundcubemail#6497]
Hi, I am successfully installed roundcube at my localhost(windows). It's working fine. Now when I tried to install it to server, I got some issues - 

- PEAR:  OK
- Auth_SASL:  NOT OK
- Net_SMTP:  NOT OK
- Net_IDNA2:  NOT OK
- Mail_mime:  NOT OK

But I already installed them into my system. My process were -

- Download zip from github
- Upload it to server using CPanel, Extract it
- Rename the folder to mail
- Tried to configure by go to mywebaddress.net/mail/installer

My server os is CentOS 6.10

**Comment by alecpl** [comment]
Simplest solution: get the "Complete" tarball where all dependencies are included (/vendor folder). Not Roundcube issue.
