### ISSUE TITLE
Importing / Exporting Email Data

### ISSUE THREAD

**Issue by Jazeon** [roundcube/roundcubemail#6505]
Greetings,

I'm new to GitHub and I signed specifically due to this issue I'm experiencing which has already been dragged for already 3 months to be exact. As you can see. I'm currently working on a new client which had their emails backed up and I was told they were using Roundcube as their Webmail platform.

But I don't understand why I can't find any .eml file extensions to be obtainable. And these are the file names of the exported back ups from their previous Host. 
![exported](https://user-images.githubusercontent.com/44617460/47738035-36b3b500-dcad-11e8-9e2d-35200e41c85f.PNG)

I tried using an alternative 3rd Party Program such as Mozilla Thunderbird and Outlook and they don't seem to read any files from the backups. So I'm completely confuse why a Roundcube hosted Webmail backups cannot be read.

Looking forward for your favorable response.

Thank you

**Comment by alecpl** [comment]
Roundcube is an email client, it does not store mail. Mail is stored on IMAP server and what you presented is a mailbox from Dovecot IMAP server. Most likely this is maildir format and I think you should be able to open/import files from these folders as any other .eml files. The dovecot* files are just indexes and metadata.
In other words, this has nothing to do with Roundcube.
