### ISSUE TITLE
Roundcube shouldn't include "Sender" when replying

### ISSUE THREAD

**Issue by simark** [roundcube/roundcubemail#6506]
When a message includes a `Sender: ` field and you do a reply-all to it, Roundcube includes that in the CC address list.  According to

  https://tools.ietf.org/html/rfc822#section-4.4.4

I think it should not do this.

```
     4.4.4.  AUTOMATIC USE OF FROM / SENDER / REPLY-TO
     
        For systems which automatically  generate  address  lists  for
        replies to messages, the following recommendations are made:
     
...
     
            o   The  "Sender"  field  mailbox  should  NEVER  be  used
                automatically, in a recipient's reply message.
```

Context: this causes problems when replying to messages on mailing lists hosted by sourceware.org.

**Comment by alecpl** [comment]
The current code is as follows:
```php
// Use Sender header (#1489011)
if ($v = $message->headers->get('Sender', false)) {
    // Skip common mailing lists addresses: *-bounces@ and *-request@ (#1490452)
    if (empty($message->headers->others['list-post'])
        || !preg_match('/-(bounces|request)@/', $v)
    ) {
        $fvalue .= (!empty($fvalue) ? $separator : '') . $v;
    }
}
```
In other words we ignore Sender only if we know the message comes from a mailing list. For other cases I do not agree with you. I'm not sure this RFC fragment applies to this case. We should maybe check what other mail clients do.

**Comment by simark** [comment]
> In other words we ignore Sender only if we know the message comes from a mailing list. For other cases I do not agree with you. I'm not sure this RFC fragment applies to this case.

It seemed pretty clear to me, but I don't really have experience reading this RFC.

> We should maybe check what other mail clients do.

As a reference point, Thunderbird doesn't add Sender when I reply to messages from this list.  Here's an example message:

https://sourceware.org/cgi-bin/get-raw-msg?listname=gdb-patches&date=2018-10&msgid=20181031111754.64707-3-alan.hayward%40arm.com

In the actual messages, `gdb-patches-owner at sourceware dot org` really has `@` and `.`.  It's the web interface that mangles mail addresses.

**Comment by rmcaninch** [comment]
I would expect "reply all" to reply to all. That's what I see Apple Mail doing. So whoever sent it and whoever was in a CC field but not BCC (unless that goes to another BCC). And avoid mailing lists. Not sure the reply all would be considered an _automatically_ generated list as it is a person hitting the button that can review the list as opposed to a vacation responder for instance.

By the way RFC 822 that was quoted was obsoleted by 2822 which was also obsoleted by 5322
https://tools.ietf.org/html/rfc2822
https://tools.ietf.org/html/rfc5322

Maybe toward the end of this section https://tools.ietf.org/html/rfc5322#section-3.6.3

**Comment by alecpl** [comment]
Ok, we'll reconsider. The options we have:
1. Current behavior: always use `Sender` (excluding for addresses matching `-(bounces|request)@`),
2. Never use `Sender`,
3. Use `Sender` only when `List-Post` is not set.

**Comment by kanarip** [comment]
I would not take in to account a clause in an RFC obsoleted by an RFC already again obsoleted, and stick with the current behavior of including the Sender field if it differs from the From field (mailing list exceptions apply).

**Comment by cmollekopf** [comment]
I'm not aware of a good reason to use Sender at all, Kontact/Kube are not using it either.

* If available use Reply-To
* If not fall-back to From

The RFC seems indeed to suggest to not use Sender, so I wouldn't use it indeed.

**Comment by alecpl** [comment]
I also opt for solution 2. Outlook, Thunderbird, Kube, all ignore this header. Also, while not precisely defined in any RFC some wording in RFC 5322 gives an impression that it might be the intended behavior.

From UX perspective... the Sender header was always visible in the Classic skin. That could add to a user expectation to use it in Reply-All. However, this is not that prominent in other skins where Sender is displayed only when you chose to display "more headers".

@thomascube do you agree?

**Comment by thomascube** [comment]
@alecpl Agreed

**Comment by alecpl** [comment]
Fixed.
