### ISSUE TITLE
I can't see read status column in Sent folder

### ISSUE THREAD

**Issue by KJ0913KIM** [roundcube/roundcubemail#6507]
I have checked read status on list options & checked on always request receipt on settings > compose email.
but i can't see the read status column on sent box. where can I find if the mail has been read or not?

**Comment by alecpl** [comment]
What version? Could you provide a screenshot? Normally unread mail uses also bold font.

**Comment by alecpl** [comment]
Read status is about the message being read (seen) or unread (unseen). It has nothing to do with receipts.
