### ISSUE TITLE
Bug frame duplicated

### ISSUE THREAD

**Issue by rabhiaziz** [roundcube/roundcubemail#6508]
Bug frame duplicated:
![image](https://user-images.githubusercontent.com/17629403/47858297-0cb4dc80-ddec-11e8-8fb2-f8c3dd118ab9.png)

**Comment by alecpl** [comment]
What version? Does it happen only in Identities?

**Comment by rabhiaziz** [comment]
thanks @alecpl  for your replying,
Yes i get this error in 'Identities', the problem generated by the iframe system. we can get this error every time if we have an internet cut.
my version its "Roundcube Webmail 1.3.6".

**Comment by alecpl** [comment]
Could you be more precise? Can you reproduce this in e.g. Responses too? Could you provide precise steps to reproduce?

**Comment by alecpl** [comment]
No feedback, no way to reproduce.
