### ISSUE TITLE
Strange issue at update.. 1.2.5 -> 1.3.8

### ISSUE THREAD

**Issue by freeeflyer** [roundcube/roundcubemail#6509]
Hi there,
I had a perfectly working installation of RC 1.2.5 then I decided to upgrade it to the last version.
now with the 1.3.8, I cannot send mail (relay acces denied).

As I had backuped my old installation directory, if I do a simple : 
``` bash
mv www www_138
mv www_125  www
```
It works again..

As for my installation : 
ubuntu 14.04 (yeah I know its old..)
- postfix 2.11
- postfix-pgsql (for virtual domains)

Has anything changed in the way of sending mail between the 2 versions ?

Thanks

**Comment by alecpl** [comment]
Yes. You have to configure smtp connection options in config. smtp_server, smtp_port, smtp_user, smtp_pass.
