### ISSUE TITLE
web.config gets deleted in temp folder

### ISSUE THREAD

**Issue by Virinum** [roundcube/roundcubemail#6511]
Hi!
I'm running roundcube on IIS. For disabling access to the temp folder I need to create a web.config in this folder. But it gets deleted after `temp_dir_ttl`.

I've two ideas:

1. Add a config item for setting filenames which get ignored.
2. Add common settingfilenames [here](https://github.com/roundcube/roundcubemail/blob/5542e91b21ba6267202f89ef9464f7ef8ce93dd7/program/lib/Roundcube/rcube.php#L526).

**Comment by Virinum** [comment]
I know there are multiple ways to deny the access. I prefere adding the web.config file in the folder. There is also a .htaccess file in this folder. Why should a .htaccess file be possible and a web.config not?

**Comment by alecpl** [comment]
Fixed by #6512.
