### ISSUE TITLE
Warning about deleted message rendering failure

### ISSUE THREAD

**Issue by eehmke** [roundcube/roundcubemail#6514]
When I shift-delete a message, I get a warning whether I would be sure to delete that message. However, it is rendered as shown in the screenshot. When I resize the window, the warning becomes readable.
![screenshot](https://user-images.githubusercontent.com/2285406/48062903-b4068a80-e1c3-11e8-9dff-fca08054c27c.png)
This is in the 1.4 beta of roundcubemail, running on a Debian 9.5 system with apache 2.4.25 and PHP 7.2.

**Comment by alecpl** [comment]
Works for me in git-master. Probably some javascript error. Check browser console. Or some resources didn't load properly. Or maybe browser cache issue.

**Comment by alecpl** [comment]
What browser?

**Comment by eehmke** [comment]
Firefox 63.0. With Chromium Version 70.0.3538.77 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit) the same happens. Cannot be a cache issue, this site was never opened in chrome before.

**Comment by eehmke** [comment]
This is what found out: in the file  plugins/jqueryui/themes/larry/jquery-ui.css
```
ui-dialog .ui-dialog-content {
        position: relative;
        border: 0;
        padding: 1.5em 1em 0.5em 1em;
        background: none;
        **overflow: auto;**
}
```
I removed the overflow property. This solved the problem for me. I had to do the change in the larry theme, even when I have activated the elastic theme.

**Comment by alecpl** [comment]
Do you have plugins/jqueryui/themes/elastic/jquery-ui.css file? It should be there. Do you use assets_dir option?

**Comment by eehmke** [comment]
Yes the file is there. Doing the change there has no effect. I had to do the 
change in the larry directory.

How to use that option?

Thanks, Eggert

Am Dienstag, 6. November 2018, 06:56:02 CET schrieb Aleksander Machniak:
> Do you have plugins/jqueryui/themes/elastic/jquery-ui.css file? It should be
> there. Do you use assets_dir option?

**Comment by alecpl** [comment]
Strange. I tested 1.4-beta (complete) release now. I cannot reproduce the issue.
