### ISSUE TITLE
password_charset should be be set to UTF-8 per default

### ISSUE THREAD

**Issue by scroom** [roundcube/roundcubemail#6522]
Hi,

today I've realized problems using umlauts for passwords (LDAP-Backend). None of the other services connected to the LDAP we use had problems with umlauts (NextCloud, Moodle, etc.). So I started searching and discovered the problem in the default settings of Roundcube. The password_charset is set to ISO-8859-1:

Shouldn't this be set to UTF-8 by default? In very few current use cases this encoding should make sense, shouldn't it?

**Comment by alecpl** [comment]
Problem is backward compatibility. But maybe we should change the default. @thomascube what do you think?

**Comment by thomascube** [comment]
If we change the default, we need to highlight that change in the release notes. Other than that, I have no objections.

**Comment by alecpl** [comment]
Done.
