### ISSUE TITLE
elastic: "Select" grayed out on smaller width

### ISSUE THREAD

**Issue by SushiTee** [roundcube/roundcubemail#6523]
The "Select" option is grayed out on smaller width which is not the case on wider width. This makes it impossible to activate the checkboxes for selecting emails which again makes it impossible to select emails on mobile phones because the email will be loaded

![mobile](https://user-images.githubusercontent.com/293612/48551277-5d8d0080-e8d5-11e8-84c8-66c646425ead.PNG)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
