### ISSUE TITLE
Enigma: Incorrect coding of a cyrillic real name in User ID for newly generated keys

### ISSUE THREAD

**Issue by mazerpazer** [roundcube/roundcubemail#6524]
Newly generated keys have the real name in User ID encoded incorrectly

How to reproduce:

1. Create a user profile with a cyrillic real name (e.g. Иван Ванко)

2. Generate new keys

Expected:
User ID, as specified in the profile, Иван Ванко <ivanko@nowhere.net>

Actually:
Real name part is mangled: 20= 0=:> <ivanko@nowhere.net>

It was tested on:
RoundCube 1.3.7 / 1.3.8, 
PHP 5.4 / 5.6 / 7.2,  
GnuPG 1.4.23 / 2.0.22 / 2.2.8, 
FreeBSD 10.2 / 11.2
CentOS 7

![enigma-1](https://user-images.githubusercontent.com/35998503/48551798-9f26a700-e8e7-11e8-9b57-e64bcb509da7.png)
![enigma-2](https://user-images.githubusercontent.com/35998503/48551800-9f26a700-e8e7-11e8-853b-6cf18beb96e3.png)
![enigma-3](https://user-images.githubusercontent.com/35998503/48551801-9f26a700-e8e7-11e8-9b07-83e11d9e91e9.png)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
If I generate the key in command line using UTF-8 encoding (gpg 2.2.4 warns about it) the name is displayed correctly. I guess you might be using different encoding. We may try to detect encoding.

**Comment by alecpl** [comment]
Recent openpgp.js version encodes utf-8 properly. I'll update the library.

**Comment by alecpl** [comment]
Fixed.
