### ISSUE TITLE
Emails sent from gMail web interface with attachments

### ISSUE THREAD

**Issue by serpentskiss** [roundcube/roundcubemail#6525]
When an email is sent from the gMail web interface, and has an attachment, it comes into Roundcube, and Reply is hit. The reply email automatically adds the attachments to the reply, rather than discarding them

Comparing the source of the gMail-generated email against one generated by Thunderbird etc, the gMail one has an additional boundary wrapper around the parts of the email.

RC v1.3.7

**Comment by serpentskiss** [comment]
[exampleEmail.txt](https://github.com/roundcube/roundcubemail/files/2588619/exampleEmail.txt)

**Comment by alecpl** [comment]
The email looks valid to me and I'm also not able to reproduce. Maybe it's your imap server issue. Enable imap_debug and provide the log from the moment you hit Reply. 

Test with disabled all plugins. Describe your environment, PHP version, OS, IMAP, etc.
