### ISSUE TITLE
Password: Add support for Plesk >= 17.8

### ISSUE THREAD

**Issue by alexpresland** [roundcube/roundcubemail#6526]
Running the Plesk Password plugin against recent versions of Plesk Onyx (I'm running Version 17.8.11 Update #29) doesn't work.  With a request of
`<?xml version="1.0"?>
<packet version="1.6.3.0"><site><get><filter><name>mydomain.com</name></filter><dataset><hosting/></dataset></get></site></packet>`

The response is:
`<?xml version="1.0" encoding="UTF-8"?>
<packet version="1.6.3.0"><site><get><result><status>error</status><errcode>1017</errcode><errtext>This feature is not supported for protocol version 1.6.3.0.</errtext></result></g
et></site></packet>`

The [Plesk XML API documentation](https://docs.plesk.com/en-US/onyx/api-rpc/about-xml-api.28709/) has a note at the bottom of the "What Protocol Versions Are In Use" section says:

_Note: Starting from Plesk 12, the version attribute can be omitted. And we strongly recommend that you omit it. In this case, the latest available version will be used. This will help you ensure that your code is operable after switching to a new version of Plesk._

The fix is simple, and is now in use on my manually-installed Roundcube installation on my Plesk server.
Remove line 149 of /plugins/password/drivers/plesk.php, which currently reads:
`$request->addAttribute("version", "1.6.3.0");`

**Comment by alecpl** [comment]
That would drop support for Plesk <= 11. I think that would be fine, but maybe we could support all. E.g. by doing second request with version set. Do you know maybe what error code is returned on older Plesk installations when a request without version is used?

**Comment by alecpl** [comment]
As the response contains also version number, I guess we can just read it and fallback to versioned request when response version is less than 1.6.6.0 (Plesk 12). I'm not sure if the version is also returned on old installations, though.

**Comment by alexpresland** [comment]
Looking at the [Plesk Version Lifecycle Policy](https://www.plesk.com/lifecycle-policy/), and the previously-linked XML API documentation, XML API v1.6.3.0 was used for Plesk version 10.0.  Plesk 10 was EOL in May 2015.  Plesk 11 is approaching being 2 years past EOL (December 2016).  Plesk 12 is in extended support and is going to be EOL on 1 January 2019 (less than 45 days from now!).  Therefore my fix would work for all supported versions of Plesk.

If someone is running an out-of-date version of Plesk, what's the chances of them running the latest Roundcube?

As such, I don't see too much issue with dropping this version detail completely in the request.  An alternative would be to have a configuration value for "legacy Plesk version".  Then again, I like your idea of detecting this automatically through spotting "This feature is not supported for protocol version" in the response and re-sending.

I don't have access to an legacy Plesk version to see what happens if the version isn't present.

**Comment by alecpl** [comment]
Done in 8caf3b659c6e. I hope I didn't break anything. Would be nice if you could confirm it works at least with your Plesk version.

**Comment by alexpresland** [comment]
Thanks @alecpl.  I'll put the latest version on my server and report back.

**Comment by evertiro** [comment]
@alecpl Tested... works... added better error handling

**Comment by alexpresland** [comment]
Sorry for the delay.  I've now tested the fix, including @evertiro 's additional changes.  All works fine on Plesk
The password plugin that I tested was from commit ce0eb318f4113b078dd748fe64f93963789e842b
