### ISSUE TITLE
Elastic: plus button without function (small width, mobile)

### ISSUE THREAD

**Issue by SushiTee** [roundcube/roundcubemail#6530]
There is a "plus" button at the bottom right on contacts which is without any function. After going back to Mails it's still there.
This only happens with small width (mobile devices).

![1](https://user-images.githubusercontent.com/293612/48899710-9a667380-ee50-11e8-9c46-0188608dda67.PNG)

And after going back to mails from contacts:

![2](https://user-images.githubusercontent.com/293612/48899722-a3574500-ee50-11e8-91cb-1a616cf6bd3d.PNG)

**Comment by alecpl** [comment]
Confirmed regression. All floating action buttons do not work.

**Comment by alecpl** [comment]
Fixed.
