### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by broros** [roundcube/roundcubemail#6532]
I have set use_secure_urls to true, but now I get an error..

Failed to load resource: the server responded with a status of 404 (Not Found)

```
$config['use_secure_urls'] = true;
```
```
RewriteRule ^/webmail/[a-zA-Z0-9]{16}/(.*) /webmail/$1 [PT]
 Alias /webmail /var/lib/roundcube
```

also, When I change to port 587 I get an error message, do I need a certificate form letsencrypt if I change the port 587?

```
 postfix/smtpd[29472]: warning: TLS library problem: error:1417D0FC:SSL routines:tls_process_client_hello:unknown protocol:../ssl/statem/statem_srvr.c:938:

 postfix/smtpd[29472]: warning: TLS library problem: error:1417D18C:SSL routines:tls_process_client_hello:version too low:../ssl/statem/statem_srvr.c:974:
```
$config['smtp_port'] = 587;

**Comment by alecpl** [comment]
Looks like configuration issue. Use mailing list or forum.
