### ISSUE TITLE
Poor exception handling in installto.sh 

### ISSUE THREAD

**Issue by udf2457** [roundcube/roundcubemail#6533]
Hmm, I'm not a big fan of sloppy exception handling.  :rage:

So, I go run `installto.sh` as directed by the UPGRADING file.

I run it as standard user because I was fairly sure all files were not owned by root (which was the case, but the parent folder was owned by root)

> rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1178) [sender=3.1.2]
> Error 500: Failed to execute command: rsync -aC --out-format=%n --delete /home/foobar/roundcube/roundcubemail-1.3.8/program/ /usr/share/nginx/foobar/program/

So I try to re-run as root, but I get
> Error 500: Installation at target location is up-to-date!

Which is obviously not true since your script errored out half-way through.

As I said, I'm not a fan of sloppy exception handling, especially in a script that messes around with files and directories.  So you've earnt an uninstall from me, I will be migrating to different software.

**Comment by alecpl** [comment]
So, we need a --force option. I'm not sure we can simply fix such problems by checking folders pemissions before executing the command. We could also improve the version check by comparing some more files, but that wouldn't be bullet-proof. We could also sync the program/ folder as the last one.

**Comment by johndoh** [comment]
could the --dry-run option be used to check for errors before running the real copy?

**Comment by alecpl** [comment]
Fixed. The script will now ask the question to continue when targeting the same version. Dry-run would be harder to implement, but if you want to give it a try, create a PR.
