### ISSUE TITLE
Enigma: Import PGP keys from "text/plain" attachments

### ISSUE THREAD

**Issue by taalas** [roundcube/roundcubemail#6536]
When receiving mail with an attached PGP key using the MIME-type `application/pgp-keys` Enigma will ask whether the key should be imported to the local key chain. Most email clients will attach the public key this way, others won't (GPGOL doesn't if I am correct).

 Would it be possible to also check attachments of type `text/plain` for keys (e.g. checking *.asc files for being a valid PGP key)?

**Comment by alecpl** [comment]
This would require looking into the attachment content and would have performance implications. As this is against the standard I'm in favor of not doing that.
