### ISSUE TITLE
1.3.8 + PHP 7.2 - count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by futureweb** [roundcube/roundcubemail#6537]
Hey there,
just updated from 1.3.4 to 1.3.8 on my Server runnning PHP 7.2. Now the Roundcube Logs are spammed with:

[29-Nov-2018 17:15:40 Europe/Vienna] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/vhosts/roundcube/httpdocs/vendor/pear-pear.php.net/Mail_Mime/Mail/mimePart.php on line 314

Acording to other Tickets this should already be fixed?
Any ideas on that?

thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by futureweb** [comment]
also:
[29-Nov-2018 17:55:51 Europe/Vienna] PHP Deprecated:  The each() function is deprecated. This message will be suppressed on further calls in /var/www/vhosts/roundcube/httpdocs/vendor/pear-pear.php.net/Mail_Mime/Mail/mimePart.php on line 625

**Comment by alecpl** [comment]
This was supposed to be fixed in Mail_Mime. DId you install Roundcube with vendor/ folder? DId you update with composer?

**Comment by futureweb** [comment]
I upgraded with the COMPLETE Package - from CLI - as written here: https://github.com/roundcube/roundcubemail/wiki/Upgrade - with bin/installto.sh Script.
So it should have updated vendor Directory too, or not?
How can I check/fix?

**Comment by futureweb** [comment]
manually replaced vendor folder now with the one from complete package ... Errors are gone!
For the Future - isn't upgrade with "bin/installto.sh" enough? (with complete package)
What would be the correct approach for such updates?
thx

**Comment by alecpl** [comment]
It would help if you saved the installto.sh script output for review.

If composer.json file exists in your to-be-upgraded installation the vendor folder is not rsynced and you have to run `composer update` manually. You should see a note in console when executing installto.sh.

**Comment by fabianbur** [comment]
I am reviewing my installation from 1.3.7 to 1.3.8 and indeed the seller of the folder has not been updated, I have the composer.json file. You must execute the rsync command manually. Do I delete everything in the seller directory or just update?

**Comment by alecpl** [comment]
Hmm... The update script checks whether `composer.json` file exists and `composer.json-dist` is readable. Looks like it might not be the case for you.

**Comment by futureweb** [comment]
actually both files existed in target directory and are readable ... 

> -rw-r--r--  1 kdn570 psacln    1565 Nov  9  2017 composer.json
> -rw-r--r--  1 kdn570 psacln    1046 Oct 23 13:12 composer.json-dist
> -rw-r--r--  1 kdn570 psacln   76154 Nov  9  2017 composer.lock
> -rwxr-xr-x  1 kdn570 psacln 1710687 Nov  9  2017 composer.phar

not entirely sure - but maybe always throw a Warning/Notice that vendor Folder might need to get updated manually if it's not done automatically?
