### ISSUE TITLE
1.3.8 + PHP 7.2 - Uncaught Exception: Serialization of 'SimpleXMLElement' is not allowed

### ISSUE THREAD

**Issue by futureweb** [roundcube/roundcubemail#6538]
Hey there,

just updated from 1.3.4 to 1.3.8 on my Server runnning PHP 7.2. Now the Roundcube Logs are spammed with:

[29-Nov-2018 17:45:20 Europe/Vienna] PHP Warning:  session_regenerate_id(): Session write failed. ID: user (path: /var/lib/php/session) in /var/www/vhosts/roundcube/httpdocs/program/lib/Roundcube/rcube_session.php on line 281
[29-Nov-2018 17:45:20 Europe/Vienna] PHP Fatal error:  Uncaught Exception: Serialization of 'SimpleXMLElement' is not allowed in /var/www/vhosts/roundcube/httpdocs/program/lib/Roundcube/rcube_session.php:281
Stack trace:
#0 /var/www/vhosts/roundcube/httpdocs/program/lib/Roundcube/rcube_session.php(281): session_regenerate_id(false)
#1 /var/www/vhosts/roundcube/httpdocs/index.php(126): rcube_session->regenerate_id(false)
#2 {main}
  thrown in /var/www/vhosts/roundcube/httpdocs/program/lib/Roundcube/rcube_session.php on line 281

Any idea on that?

thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by alecpl** [comment]
The warning may be caused by php mis-configuration.

For fatal the error... What plugins are you using? Try with disabled all plugins.

**Comment by futureweb** [comment]
It's Standard PHP 7.2 as configured by PLESK. All other PHP Apps working like a charm.
Plugins are not to blame - same Error when all Plugins are disabled.

![grafik](https://user-images.githubusercontent.com/1698881/49276811-d9fc1380-f47f-11e8-9968-d42995a69759.png)

Andreas

**Comment by futureweb** [comment]
What I just noted - the Error is only thrown when the Server I'm connecting to has SSL deactivated ... with SSL activated it's working like a charm.
When the Error is triggered - you just get a white Page with no Error in the Browser.

**Comment by futureweb** [comment]
ok - found the Problem - somehow HOST was presented as SimpleXMLElement Object by Login Provider ... no idea why this suddenly happened after update ... ?!?
anyway - doing a string cast now - and it's working again as it should! ;-)

thx
