### ISSUE TITLE
database_attachments not upload to database

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#6542]
Roundcube 1.3.8
composer.json
Debian 9
mariadb 10.2
php: 7.0.30

Complemento | Versión | Licencia | Origen
-- | -- | -- | --
additional_message_headers | 1.2.1 | GPLv2 |  
archive | 3.0 | GPLv3+ |  
attachment_reminder | 1.1 | GPLv3+ |  
autocomplete | dev-master | GPL-3.0+ |  
automatic_addressbook | dev-master | GPL-3.0+ | Descargar
calendar | 3.3.3 | AGPLv3 | Descargar
cloud_button | dev-master | GPL-3.0 | Descargar
contextmenu | 2.3 | GPL-3.0 | Descargar
contextmenu_folder | dev-master | Apache | Descargar
database_attachments | 1.2 | GPLv2 |  
emoticons | 2.0 | GPLv3+ |  
enigma | 0.7 | GPLv3+ |  
filters | dev-master | GNU GPLv3+ | Descargar
geolocation | 0.1.2 | GPL-3.0+ | Descargar
hide_blockquote | 1.0 | GPLv3+ |  
identicon | 0.1 | GPLv3+ |  
jqueryui | 1.12.0 | GPLv3+ |  
lastlogin | dev-master | GPL-3.0+ | Descargar
libcalendaring | 3.3.3 | AGPLv3 | Descargar
login_lang | dev-master | MIT |  
managesieve | 8.7 | GPLv3+ |  
markasjunk2 | 1.11.2 | GPL-3.0 | Descargar
newmail_notifier | 0.8 | GPLv3+ |  
new_user_dialog | 2.1 | GPLv3+ |  
new_user_identity | 1.1 | GPLv3+ |  
password | 4.2 | GPLv3+ |  
persistent_login | dev-master | GPL-3.0+ | Descargar
rcguard | dev-master | GPL-3.0+ | Descargar
removeattachments | dev-master | GPL-3.0 | Descargar
show_additional_headers | 2.0 | GPLv3+ |  
subscriptions_option | 1.3 | GPLv3+ |  
userinfo | 1.0 | GPLv3+ |  
vcard_attachments | 4.0 | GPLv3+ |  
zipdownload | 3.3 | GPLv3+ |  

`

The plugin database_attachments appears activated together with all the others, however, attach the files, they do not go to the database. I do not know if it's something simple that is missing. I do not find much documentation online.

**Comment by alecpl** [comment]
How do you know they don't go to database? Enable sql_debug to see exactly what queries are sent to the database. If it really do not work, I'd start with disabling all plugins. Any errors in log?

**Comment by alecpl** [comment]
What do you mean? I don't understand. Attachments are meant to be attached to mail.

**Comment by fabianbur** [comment]
Maybe I have not explained myself in the right way, I might be lost in the translation, my mother tongue is Spanish and I help with an online translator.
It may be that the normal behavior of this plugin is what I see: it saves a copy in the database, particularly in the "cache" table and a copy in the file of the email message.
Should I understand that this is the only possible and normal behavior of this plugin?
Is there perhaps a configuration that makes it possible for the file to be only in the database and after a certain time is deleted, without continuing to occupy space in the mailbox of sent?
It's a query I'm doing,
Thanks for the reply.

Tal vez no me he explicado de la forma correcta, puede ser que se pierda en la traducción, mi lengua materna es español y me ayudo con un traductor en línea.
Puede ser que el comportamiento normal de este plugin sea el que veo: guarda una copia en la base de datos, particularmente en la tabla "cache" y una copia en el archivo del mensaje de correo electrónico.
¿Debo entender que ese es el único comportamiento posible y normal de este plugin?
¿existirá tal vez una configuración que haga posible que el archivo esté únicamente en la base de datos y que luego de un tiempo determinado se borre, sin seguir ocupando espacio en el buzón de enviados? 
Es una consulta la que estoy haciendo,
Gracias por la respuesta.

**Comment by alecpl** [comment]
There's no option to remove attachments from sent mail to save space. There's a plugin https://plugins.roundcube.net/packages/dsoares/removeattachments, but it also has no option to do this automatically.
