### ISSUE TITLE
Emails are not being delivered 

### ISSUE THREAD

**Issue by PauliinaZ** [roundcube/roundcubemail#6543]
Hey,
Have been noticing recently that my emails are never delivered to people. I receive no errors or failure reports. I have noticed that it happens to those emails that have a person's name before the email like:
 To: John Smith < john.smith@gmail.com >
But when I have only john.smith@gmail.com, I have no issue. 
I asked people to check their spam and all kinds of folders to see my emails. They were not there. 
Is there really a correlation? It started maybe 2-3 weeks ago, and have been using roundcube for a year already. 
Thanks!

**Comment by alecpl** [comment]
Most likely not Roundcube issue. You can enable smtp_debug option to see if the message is properly delivered to SMTP server.
