### ISSUE TITLE
Line break before message

### ISSUE THREAD

**Issue by PedroLuiz99** [roundcube/roundcubemail#6545]
(I'm newbie send issues, excuse me if I do something wrong)
We use Roundcube 1.1.3 + Outlook Skin. One of our emails, always when a new message is sent, a new line is inserted before the message:

```
<html>
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<p>&nbsp;</p>
<div>Teste de quebra</div>
<div>-- <br />
<p><img src=3D"IMAGE_URL" alt=3D"" /=
></p>
</div>
<p>&nbsp;</p>
</body>
</html>
```

How can I remove this <p> before the message?

Thanks.

**Comment by alecpl** [comment]
Upgrade. This has been fixed in 1.2.
