### ISSUE TITLE
Server Error: STATUS: Internal error occurred. Refer to server log for more information /// Erro SMTP: [451] Temporary local problem - please try later

### ISSUE THREAD

**Issue by LwkasCrystian** [roundcube/roundcubemail#6546]
Good night!

I installed Vestacp and the roundcube came, but it is giving several errors, I have managed to solve some, but I have 2 I do not know how to solve them.

Every time I enter the Roundcube, the following popup appears:

[https://lh3.googleusercontent.com/-Edqf8PePgaQ/XAmqQDXpcGI/AAAAAAAAV7w/3s7by1Etsa0Dkm_0AG8ns9WgZ-qREA3fACL0BGAYYCw/h87/2018-12-06.png](url)

Already while trying to send an email: the following error appears:

[https://lh3.googleusercontent.com/-v4LNmBss8mo/XAmq-Cfv3vI/AAAAAAAAV70/lNVCDM2BJaE262jw-jy-ElP0wIt4tnGaQCK8BGAs/s306/2018-12-06.png](url)

Can someone help me?

**Comment by alecpl** [comment]
Not Roundcube issue. You have problem with IMAP and SMTP server. Look into their error logs.
