### ISSUE TITLE
Funny Message-Id when resuming a Draft

### ISSUE THREAD

**Issue by gahr** [roundcube/roundcubemail#6548]
How to reproduce:

1. start composing an email with some MUA != Roundcube
2. save the draft, make sure the Message-Id header is not generated at this time
3. resume the draft from Roundcube, send the email

At this point, the email gets sent with a Message-Id of `mid:1`.

**Comment by alecpl** [comment]
Message-id in a form of mid:XXX is set by rcube_imap_generic for "internal" use. We indeed should generate a new Message-Id for drafts with no Message-Id header.

**Comment by alecpl** [comment]
Fixed.
