### ISSUE TITLE
elastic skin not showing properly on 1.4-beta (git)

### ISSUE THREAD

**Issue by paladox** [roundcube/roundcubemail#6550]
Hi, when trying out the elastic skin using 1.4 beta (git) it's not showing properly.

It shows like:

<img width="1440" alt="screenshot 2018-12-09 at 02 11 04" src="https://user-images.githubusercontent.com/5727000/49692646-b3ad3680-fb57-11e8-8017-fbbf45977b08.png">

**Comment by alecpl** [comment]
Read INSTALL instructions. You have to build css files for Elastic.

**Comment by thomascube** [comment]
One more for #6284
