### ISSUE TITLE
Cache ignores flag changes

### ISSUE THREAD

**Issue by Du-St** [roundcube/roundcubemail#6552]
Hello,

I have enabled IMAP cache and message cache (backend Postgres DB). We are using shared namespace as implemented in Dovecot (v2.3.2): https://wiki.dovecot.org/SharedMailboxes/Shared. Message caching works as expected except message flags. When one user set \Seen flag on the message, the other still sees the message as unread. This state persists for tens of minutes. There are no changes when user uses refresh button or changes the folder to another one and back. The count of unread messages displayed next to the folder name is ok.

Dovecot shared namespace conf:
> namespace {
>   type = shared
>   separator = /
>
>   -- Mailboxes are visible under "shared/user@domain/"
>   -- %%n, %%d and %%u are expanded to the destination user.
>   prefix = Shared/%%u/
> 
>   -- Mail location for other users' mailboxes. Note that %variables and ~/
>   -- expands to the logged in user's data. %%n, %%d, %%u and %%h expand to the
>   -- destination user's data.
>   location = maildir:/var/vmail/%%d/%%n/Maildir
> 
>   -- Use the default namespace for saving subscriptions.
>   subscriptions = no
> 
>   -- List the shared/ namespace only if there are visible shared mailboxes.
>   list = children
> }

RC cache conf:
> // Type of IMAP indexes cache. Supported values: 'db', 'apc' and 'memcache'.
> $config['imap_cache'] = 'db';
> 
> // Enables messages cache. Only 'db' cache is supported.
> // This requires an IMAP server that supports QRESYNC and CONDSTORE
> // extensions (RFC7162). See synchronize() in program/lib/Roundcube/rcube_imap_cache.php
> // for further info, or if you experience syncing problems.
> $config['messages_cache'] = 'db';
> 
> // Lifetime of IMAP indexes cache. Possible units: s, m, h, d, w
> $config['imap_cache_ttl'] = '10d';
> 
> // Lifetime of messages cache. Possible units: s, m, h, d, w
> $config['messages_cache_ttl'] = '10d';
> 
> // Maximum cached message size in kilobytes.
> // Note: On MySQL this should be less than (max_allowed_packet - 30%)
> $config['messages_cache_threshold'] = 1024;

IMAP DEBUG log:

> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS LOGINDISABLED] Dovecot ready at ***
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0001 STARTTLS
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0001 OK Begin TLS negotiation now.
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0002 CAPABILITY
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0002 OK Pre-login capabilities listed, post-login capabilities have more.
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0003 ID ("name" "Roundcube" "version" "1.3.8" "php" "5.4.45" "os" "Linux" "command" "/mail/?_task=mail&_action=check-recent")
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * ID ("name" "Dovecot")
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0003 OK ID completed.
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0004 AUTHENTICATE PLAIN ****** [57]
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0004 OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PART
> IAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY LITERAL+ NOTIFY SPECIAL-USE COMPRE
> SS=DEFLATE ACL RIGHTS=texk] Logged in
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0005 SELECT INBOX
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * FLAGS (\Answered \Flagged \Deleted \Seen \Draft $has_cal NonJunk $Forwarded $NotJunk $MDNSent receipt-handled JUNK)
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [PERMANENTFLAGS (\Answered \Flagged \Deleted \Seen \Draft $has_cal NonJunk $Forwarded $NotJunk $MDNSent receipt-handled JUNK \*)] Flags permitted.
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * 5635 EXISTS
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * 0 RECENT
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [UNSEEN 2004] First unseen.
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [UIDVALIDITY 1477912711] UIDs valid
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [UIDNEXT 7765] Predicted next UID
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [HIGHESTMODSEQ 17940] Highest
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0005 OK [READ-WRITE] Select completed (0.001 + 0.000 secs).
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0006 ENABLE QRESYNC
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * OK [HIGHESTMODSEQ 17940] Highest
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * ENABLED QRESYNC
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0006 OK Enabled (0.001 + 0.000 secs).
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0007 UID SEARCH 5635
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * SEARCH 7764
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: A0007 OK Search completed (0.001 + 0.000 secs).
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] C: A0008 STATUS INBOX (MESSAGES UNSEEN)
> [2018-Dec-10 19:12:58 +0100]: <9lb25h83> [EBFB] S: * STATUS INBOX (MESSAGES 5635 UNSEEN 14)

**Comment by alecpl** [comment]
It works with disabled cache? This debug log is not very helpful. I'd need the debug log from two user sessions, in one user marking a message in shared folder, in the other user doing a refresh soon after the change.

**Comment by alecpl** [comment]
No feedback.
