### ISSUE TITLE
Webmail import/export calendar icons are incorrect (Larry Theme)

### ISSUE THREAD

**Issue by gaellelo** [roundcube/roundcubemail#6553]
**Steps to reproduce:**
1. Visit the webmail calendar using Larry Theme
2. Look at the buttons to import/export

**Address (URL) of faulty icons:**
https://cl.ly/e221a6ac301d

**Expected behaviour:**
"Export" has an arrow going from the calendar to somewhere else, "Import" is the reverse

**Actual behaviour:**
"Export" has an arrow going into it as if you were importing information, which doesn't make sense. "Import" is the reverse.

**Comment by alecpl** [comment]
We do not support Calendar plugin here.

**Comment by gaellelo** [comment]
Thanks @alecpl for your prompt comment. I'll notify it to the calendar plugin directly.
