### ISSUE TITLE
cleandb.sh / rcmail::db_clean() : option to keep quiet when no record to delete ?

### ISSUE THREAD

**Issue by titoo999** [roundcube/roundcubemail#6558]
Hi,

Called as a scheduled cron operation, /bin/cleandb.sh is a bit talkative even when nothing has been cleaned.

With a $quiet boolean parameter (false by default), we would be able to only echo when ( `$quiet &&  $db->affected_rows()>0` ) .

Would that be possible to add such a "global" parameter ?

I'm ready to help, but I didn't inquire about how such parameters are managed...

**Comment by alecpl** [comment]
None of our scripts already use `quiet` nor `verbose` option. Probably only cleandb.sh would need it. And I see that a simple boolean option might not be enough. E.g. someone could expect `quiet` disables output no matter if there were any records deleted or not.

A workaround would be to pass the output to `grep -ve "^0"`.

So, I will close the ticket for now, if anyone provides a pull request we'll consider it.

**Comment by titoo999** [comment]
Sure. Changing the cron operation by `[roundcube]/bin/./cleandb.sh | grep -ve "^0"` solves the problem.

Thank you.
