### ISSUE TITLE
Custom header?

### ISSUE THREAD

**Issue by cryptify** [roundcube/roundcubemail#6559]
How would I set up a custom header on an email? I'm trying to send a newsletter and want to use a List-Unsubscribe: <mailto: emailAddress>, <unsubscribe URL>

**Comment by alecpl** [comment]
You would have to write a plugin. See additional_message_headers for an example.

**Comment by cryptify** [comment]
Beautiful. Thank you so much!

**Comment by cryptify** [comment]
Works like a charm. 

**For anyone else wondering in the future**, it's in your roundcube directory, config/config.inc.php. under
$config['plugins'] = array('additional_message_headers')
make sure additional_message_headers is there. then in that same file add:
$config['additional_message_headers']['List-Unsubscribe'] = '<mailto:emailaddress@domain.com>';

It seems to work, the header shows up in the received email, however please be aware after some digging I found that most domains only honor this for high rep senders, so your link might not show up right away, until the IP has a high enough reputation.

**Comment by deewinc** [comment]
> Works like a charm.
> 
> **For anyone else wondering in the future**, it's in your roundcube directory, config/config.inc.php. under
> 
> `$config['plugins'] = array('additional_message_headers')`
> 
> make sure additional_message_headers is there. then in that same file add:
> 
> `$config['additional_message_headers']['List-Unsubscribe'] = '<mailto:emailaddress@domain.com>';`
> 
> It seems to work, the header shows up in the received email, however please be aware after some digging I found that most domains only honor this for high rep senders, so your link might not show up right away, until the IP has a high enough reputation.

Works perfect.

Though I didn't find this line inside the directory, 
`$config['plugins'] = array('additional_message_headers');
`
So I added it and included a semi-colon at the end and added he list-unsubscribe header.

**Comment by patchthecode** [comment]
And what if i use docker version?
