### ISSUE TITLE
Expired sessions are not removed from database / Invalid session message after login with http_authentication

### ISSUE THREAD

**Issue by SQ-SEN** [roundcube/roundcubemail#6560]
When using http_authentication, expired sessions are not removed from the database. When I try to logon the next time, I get an invalid session error. After reloading, everything is fine.

I checked the sessions table and found sessions over a year old in it. 

Executing the SQL statement via cron job every hour mitigates the issue:
DELETE FROM session WHERE changed < date('now','-1 hour');

However, I don't think that's the way it should be.

For the settings
$config['session.cookie_lifetime']
$config['session_lifetime']
I tried various values without success.

This might be related to issue 5067.

**Comment by alecpl** [comment]
I don't think this is http_authentication specific. Unfortunately some distributions (Debian/Ubuntu) decided to disable PHP garbage collector by setting `session.gc_probability=0` and use their own way which does not work with custom session handlers.

So, we leave this to the user to decide. We also provide gc.sh script for cron. However, maybe we should force `session.gc_probability=1` in the code if unset. Or at least add a note to INSTALL file. @thomascube what do you think?

**Comment by alecpl** [comment]
Done.

**Comment by itcrowd72** [comment]
> We also provide gc.sh script for cron

Oh, thank you)
