### ISSUE TITLE
Setting contact_photo_size is not working

### ISSUE THREAD

**Issue by nixe-** [roundcube/roundcubemail#6562]
I have this problem in Roundcube 1.2.9. When uploading contact photo, it uploads it no matter what size (width/height) it is, even I have default setting contact_photo_size = 160. I believe RC should resize photo to that max size (160px), but it's not doing it. This causes memory problems and crashes in addressbook.

**Comment by alecpl** [comment]
Works for me. Do you have GD extension installed or Imagick? Any errors in log? Also you should upgrade, we do not support 1.2 anymore.

**Comment by nixe-** [comment]
> Works for me. Do you have GD extension installed or Imagick? Any errors in log? Also you should upgrade, we do not support 1.2 anymore.

GD is installed, gonna try to install ImageMagick, even there's no requirements for those.

**Comment by nixe-** [comment]
> GD is installed, gonna try to install ImageMagick, even there's no requirements for those.

OK, ImageMagick fixed problem. Now I only had to make a script that scales all pictures from database to max size :/

**Comment by DoobleD** [comment]
If image compression fails (for instance if ImageMagick is not installed), the image is uploaded as is, with its original size. To prevent this I've added an [attachment_upload hook](https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#attachment_upload). Seems to do the job.

`<?php

class custom_upload extends rcube_plugin
{
    private $rc;

    function init()
    {
        $this->rc = rcube::get_instance();

        $this->add_hook('attachment_upload', array($this, 'upload'));
    }

    function upload($args)
    {
        $group = $args['group'];

        // Contact images are supposed to be compressed by program/steps/addressbook/upload_photo.inc
        // but this required imagemagick to be installed on container.
        // And if compression fails the image is uploaded as is! Here we overrid this behavior to limit max contact image size.
        if ($group == 'contact') {
            $maxKB = 10;
            $max = $maxKB * 1024;

            if ($args['size'] > $max) {
                $args['status'] = false;
                $args['abort'] = true;
                $args['error'] = $this->rc->gettext(array('name' => 'filesizeerror', 'vars' => array('size' => $max)));
            }
        }

        return $args;
    }
}
`
