### ISSUE TITLE
show_additional_headers - plugin won't show x-headers

### ISSUE THREAD

**Issue by numericOverflow** [roundcube/roundcubemail#6563]
I'm using Roundcube (1.4-beta) with the show_additional_headers (2.0) plugin and am not able to display x-headers.  I've enabled the plugin and standard header fields work fine (display) when I add them to the "show array" in roundcube config file, so it seems to be configured properly on my side.

``
$config['show_additional_headers'] = array('X-Envelope-Sender','X-Assp-Intended-For','X-Assp-Message-Score','Reply-To');
``

That line in my config will show the reply-to header, but none of the other x-headers.  When expanding the headers field of a particular message, I can see the listed x-headers exist, but the show_additional_headers plugin does not recognize and show them.

Thoughts?

**Comment by alecpl** [comment]
Works for me in git-master. Some notes:
- You have to click "Details" link in Elastic skin or "Show more message headers" in Larry.
- If you use `messages_cache` you have to clear the cache after changing `show_additional_headers`, because the cached message header do not contain the header and the cache does not refresh automatically in such case.

**Comment by Rub-z** [comment]
@numericOverflow 

I'm sorry to contact you this way but I was unable to find any other method.. 

In a previous post - https://github.com/open-keychain/open-keychain/issues/1421 - you wrote:

> adding the --textmode flag made it work, now using v3.6 I'm able to get text shown onscreen when using intents/clipboard.

I too am desperately trying to use intents to decrypt openkeychain pgp using tasker but am very stuck. There are no good/complete examples online. 

Could you please see your way to share a working example using tasker? I would be forever grateful! 

If alecpl sees this, please accept my apologies. I've spent a long time trying to get this working and only just found the above possible solution so please don't delete this :)  the other thread was 3 yrs old and many participants. Hope you understand.
