### ISSUE TITLE
login form inputs too wide in IE11

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6565]
using latest git-master the input boxes on the login form when using IE11 are too wide:

![login](https://user-images.githubusercontent.com/88682/50330451-27a1f400-04f3-11e9-8a70-98ac6b97ed91.png)

BTW not sure if its intentional but in FF64, Edge and IE11 both login boxes have the red "invalid" marking around them on page load. It happened after 328c324

**Comment by alecpl** [comment]
I fixed the border issue.

**Comment by alecpl** [comment]
Fixed.
