### ISSUE TITLE
feature request: login form plugin hook

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6569]
if #6568 or something similar is merged would you consider adding a login form plugin hook which would allow plugins to interact with the `$fields` array in rcmail_output_html::login_form()?

use case: support for multifactor authentication can be added to Roundcube via a plugin. It requires changes to the login form, to give the users somewhere to enter the additional factor. At the moment there are 2 ways of doing it but both a little hacky - either create your own version of rcmail_output_html::login_form() or use something like the render_page hook to replace the HTML. If rcmail_output_html::login_form() gets refactored to include a `$fields` array then I think a plugin hook for those fields would be a cleaner solution.

**Comment by alecpl** [comment]
kolab_2fa plugin does not need this it displays another form after the initial one is submitted. kolab_sso plugin parses the HTML using `template_object_loginform` hook. So, there are other ways.

Anyway, this makes sense. I would like to be able to contol also hidden fields and button(s).

**Comment by alecpl** [comment]
Done.
