### ISSUE TITLE
how change password mail server by c#

### ISSUE THREAD

**Issue by alirezaseif28** [roundcube/roundcubemail#6570]
I have a mail server that is related to the host. I store the info about the mail server in the app mvc. If I want to pass through my mail server passwords through my application, that is, first, change the password in the mail server and If successful, go to the application database...

**Comment by alecpl** [comment]
The description is not clear. Anyway, I guess you have to write some code (driver) for password plugin. Maybe write simple script/program that does what you want and invoke it from the driver code. There are many ways to do this and none of this is really needed in Roundcube core.

**Comment by alirezaseif28** [comment]
thanks @alecpl .
how find sample code c# to change password roundcube mail.

**Comment by alecpl** [comment]
The driver api in password plugin is very simple just take a look at existing drivers, it's php not c#. You can write a program in c# and execute it in a way used e.g. by chpasswd driver. Actually you can use chpasswd driver to execute any command.

**Comment by alirezaseif28** [comment]
Ok .Thanks.@alecpl
I may ask a question later
I have to find a sample program by c#.
