### ISSUE TITLE
Unable to use the Enigma plugin with Roundcube 1.3.8

### ISSUE THREAD

**Issue by whalehub** [roundcube/roundcubemail#6578]
I started using Roundcube today because one of its biggest draws for me was the support for PGP/MIME encryption via the Enigma plugin. Unfortunately, after installing the plugin, I receive the following generic, non-descriptive error message both when trying to read an encrypted mail and when trying to navigate to the **PGP Keys** menu option in the settings.

![vivaldi_2019-01-06_02-19-23](https://user-images.githubusercontent.com/44198148/50730975-acc71300-1159-11e9-9ca5-93fdf9241811.png)

![vivaldi_2019-01-06_02-19-54](https://user-images.githubusercontent.com/44198148/50730976-ae90d680-1159-11e9-8a2e-1034ef56fae1.png)

I wasn't able to find any information about this error on Google so I have no idea what could be the cause of the issue.

I appreciate any and all help with this problem.

**Edit:** Just in case this information helps: I have GPG v2.2.12 installed on my server and am using the following `config.inc.php` file with Enigma.

```
<?php

// Enigma Plugin options
// --------------------

// A driver to use for PGP. Default: "gnupg".
$config['enigma_pgp_driver'] = 'gnupg';

// A driver to use for S/MIME. Default: "phpssl".
$config['enigma_smime_driver'] = 'phpssl';

// Enables logging of enigma operations (including Crypt_GPG debug info)
$config['enigma_debug'] = true;

// Keys directory for all users. Default 'enigma/home'.
// Must be writeable by PHP process
$config['enigma_pgp_homedir'] = enigma/home;

// Location of gpg binary. By default it will be auto-detected.
// This is also a way to force gpg2 use if there are both 1.x and 2.x on the system.
$config['enigma_pgp_binary'] = '/usr/bin/gpg';

// Location of gpg-agent binary. By default it will be auto-detected.
// It's used with GnuPG 2.x.
$config['enigma_pgp_agent'] = '';

// Location of gpgconf binary. By default it will be auto-detected.
// It's used with GnuPG >= 2.1.
$config['enigma_pgp_gpgconf'] = '';

// Enables signatures verification feature.
$config['enigma_signatures'] = true;

// Enables messages decryption feature.
$config['enigma_decryption'] = true;

// Enables messages encryption and signing feature.
$config['enigma_encryption'] = true;

// Enable signing all messages by default
$config['enigma_sign_all'] = false;

// Enable encrypting all messages by default
$config['enigma_encrypt_all'] = false;

// Enable attaching a public key to all messages by default
$config['enigma_attach_pubkey'] = false;

// Default for how long to store private key passwords (in minutes).
// When set to 0 passwords will be stored for the whole session.
$config['enigma_password_time'] = 0;

// With this option you can lock composing options
// of the plugin forcing the user to use configured settings.
// The array accepts: 'sign', 'encrypt', 'pubkey'.
//
// For example, to force your users to sign every email,
// you should set:
//     - enigma_sign_all     = true
//     - enigma_options_lock = array('sign')
//     - dont_override       = array('enigma_sign_all')
$config['enigma_options_lock'] = array();
```

**Comment by alecpl** [comment]
Any errors in log? Any errors in browser console? Disable all other plugins and try again.

**Comment by whalehub** [comment]
@alecpl I disabled all other plugins and the issue was the same. There is one error in the browser console when I open the "PGP Keys" menu option in the settings:

![vivaldi_2019-01-07_21-43-14](https://user-images.githubusercontent.com/44198148/50792422-3e9f5f00-12c5-11e9-9c97-880665a71f91.png)

![vivaldi_2019-01-07_21-44-18](https://user-images.githubusercontent.com/44198148/50792470-65f62c00-12c5-11e9-858d-70734bdbb1df.png)

Any idea what this means?

**Comment by whalehub** [comment]
@alecpl I disabled all other plugins and the issue was the same. There is one error in the browser console when I open the **PGP Keys** menu option in the settings:

![vivaldi_2019-01-07_21-43-14](https://user-images.githubusercontent.com/44198148/50792422-3e9f5f00-12c5-11e9-9c97-880665a71f91.png)

![vivaldi_2019-01-07_21-44-18](https://user-images.githubusercontent.com/44198148/50792470-65f62c00-12c5-11e9-858d-70734bdbb1df.png)

Any idea what this means?

**Comment by alecpl** [comment]
Error 500 means there must be some error message in logs.

**Comment by whalehub** [comment]
@alecpl If you can tell me the path to the log files, I'll post the content here.

**Comment by alecpl** [comment]
The logs are usually in `logs` directory of Roundcube, but they can also be in system log dir for http server or syslog.

**Comment by whalehub** [comment]
@alecpl Hm, strange, the logs directory of Roundcube is empty for me, save for an .htaccess file.

**Comment by whalehub** [comment]
I'm closing this issue since I was able to get it working without using a pre-configured mail stack.
