### ISSUE TITLE
how send alarm email or prevent concurrent user in login

### ISSUE THREAD

**Issue by ebrahim110** [roundcube/roundcubemail#6579]
In the name of ALLAH .
Please help me.
In roundcube we can login to mailbox from two computer with one user account at same time.
How send mail to user account after concurrent login for security reason
By set ip_check=true roundcube dont prevent concurrent login.
--

**Comment by alecpl** [comment]
This is not possible, but you could write a plugin. Unfortunately sessions are not easily recognizable for which user they belong to, so you'd need to store session ID to user ID mapping somewhere else.
