### ISSUE TITLE
max_message_size is ignored when forwarding mail

### ISSUE THREAD

**Issue by photoninger** [roundcube/roundcubemail#6580]
One of our users tried to forward all mails in his inbox as one mail with each mail as an attachment and failed, because it was too big for our smtp server. But he tried it more than once until the temp directory was full.
This way we learned max_message_size doesn't help if someone forwards mails.
I also tested this with roundcube-1.4-beta.

Would be nice if max_message_size is checked in every case during composing a new mail.

To reproduce this behavior:
1. set max_message_size to 1M for easy testing
2. Select one or more mails with total size more than 1M (or just use "select all")
3. Klick "forward as attachment"
4. Enter recipient address and click send

**Comment by alecpl** [comment]
Indeed, the limit is checked only when attaching files on mail compose page.

**Comment by alecpl** [comment]
Fixed.
