### ISSUE TITLE
Make Reply-To field searchable

### ISSUE THREAD

**Issue by sauladam** [roundcube/roundcubemail#6582]
I think it would be quite useful if the Reply-To field was searchable.

An example use case would be a contact form. When a user sends a message through a contact form, the message is delivered via email e.g. to contact@mydomain.tld and has the user's email address in the Reply-To field. But right now there seems no way in Roundcube to search for that email address (unless it's included in the email body or in the subject).

I think this would be a great feature so I really hope to see that one included in a future release!

**Comment by alecpl** [comment]
Note that mail messages may use also `Mail-Reply-To` and `Mail-Followup-To`. Maybe it would make sense to include them too. Now we have `From`, `To`, `Cc`, `Bcc`. So, I guess we have a few options here:
1. Just add `Reply-To` to the list of fields (it could search in `Reply-To` only or in all three mentioned headers)
2. Search in `From` and `Reply-To` (or all three mentioned headers) header when using `From`.
3. Replace `From`, `To`, `Cc`, `Bcc` with
    - `Senders` (includes searching in `From`, `Reply-To`, etc.)
    - `Recipients` (searching in `To`, `Cc`, `Bcc`).

If we go with a solution that hides real header names used in search from the user we could also consider adding use of `Delivered-To`, `Envelope-To` and other headers like these. It may have impact on performance, and server side indexing system may require changes.

**Comment by sauladam** [comment]
Hey @alecpl,

thanks for your feedback! Excellent points about the other possible fields, didn't think of that.

I quite like the idea of reducing the field selection down to `Senders` and `Recipients` (as you describe with option 3). Of course this might become a performance issue if we keep searching in every possible field, so maybe a better approach would be to make it user-configurable what `Senders` and `Recipients` are. From the UI perspective I'm thinking of a nested dropdown for `Senders` and `Recipients` where the user can select what fields to use for each category. 

So, right now in the `elastic` theme all fields are just listed one by one:

![screenshot from 2019-01-10 17-16-20](https://user-images.githubusercontent.com/5918276/50981992-7c39fd00-14fc-11e9-8d56-1bcd79c8d830.png)

Maybe we could group them together in `Senders`, `Recipients` and `Message` and let the user toggle and fine tune each group, but keep the sensible defaults as they are now.

**Comment by alecpl** [comment]
![mail-search](https://user-images.githubusercontent.com/546788/139663603-f370b4e9-3675-405a-925b-1709b2df69f8.png)

For now we'll ignore `Delivered-To`, `Envelope-To`. They might not be understood by an average user.

**Comment by alecpl** [comment]
Done.
