### ISSUE TITLE
Confirmation dialog when deleting multiple messages

### ISSUE THREAD

**Issue by sauladam** [roundcube/roundcubemail#6585]
I keep having to pull mails out of the Trash folder on a regular basis because I accidentally delete them instead of marking them. This happens because the `Delete` button is right next to the `Mark` button and I'm either not paying attention or just slip off the right button:

![screenshot from 2019-01-10 17-45-41](https://user-images.githubusercontent.com/5918276/50983483-d5576000-14ff-11e9-95de-daa9f0ad42e7.png)

Maybe it's just me, but I think a confirmation dialog upon deleting multiple messages through the `Delete` button would be quite a useful feature and a great UX improvement. 

Another approach might be just moving the `Delete` button somewhere else and not keeping it between non-destructive action buttons / making it not as easily accessable. But that might also affect the UX when only one message is selected.

**Comment by alecpl** [comment]
Asking for confirmation would annoying. We only do this when deleting with SHIFT key (not in Trash). If we get more request about this we'll consider doing something with the button, maybe making it red would be a solution. Closing for now.
