### ISSUE TITLE
Elastic theme - too many clicks needed to show unread messages

### ISSUE THREAD

**Issue by tchwpkgorg** [roundcube/roundcubemail#6587]
With Larry theme, one needed just two clicks to see unread messages:

1) open dropdown menu
2) click on "Unread"

With Elastic theme, we need 4 clicks:

1) Click on "Options" dropdown menu
2) Click on "Type" dropdown
3) Click "Unread"
4) Hide the "Options" dropdown menu

I use an option to see unread messages many time per day. Is there a way to make Elastic theme need less clicks to show unread messages?

**Comment by alecpl** [comment]
Indeed. However, it might not be possible without some bigger changes in the UI. A designer would be needed. I'm not closing this right now, but if I don't get feedback with proposed changes it will not be open forever.

**Comment by ann0see** [comment]
On iOS there's a button on the bottom left.
I don't have a working version at the moment, but maybe it could be included similarly.

**Comment by alecpl** [comment]
Maybe just "Unread/Read" button on the left of the "Options" button would be a solution. That would be a single-click solution.

Other option is to extend Options widget with a separate area with (switch-)buttons for most common filter options below the Search button. So, when clicked filter applies immediately. That would be two-clicks solution.

**Comment by lutel** [comment]
Is this single issue blocking release of 1.4.0?

**Comment by ytzelf** [comment]
> 
> 
> Is this single issue blocking release of 1.4.0?

Curious as well :)

**Comment by alecpl** [comment]
Done.
