### ISSUE TITLE
Is there a way to display custom IMAP flags? 

### ISSUE THREAD

**Issue by lrosenman** [roundcube/roundcubemail#6588]
I have a lot of FLAGS I use, and the Thunderbird labels plugin doesn't work for me.  Is there a way or a plan to display custom flags?

**Comment by alecpl** [comment]
There's no such plans. Definitely not for core. One idea would be to extend kolab_tags plugin with tags storage driver working with imap flags.

**Comment by ad-si** [comment]
But there is a filter to add custom flags. What's the point of the filter if I can't even display them? 🤔

**Comment by TonyGravagno** [comment]
+1 on this. I was just looking at the RFC for imap4flags, saw that managesieve sets them, and immediately recognized that RC does not. This is a vote for anyone who has initiative to create a plugin for this. I'll look at the kolab_tags plugin at some point to see what can be done with that. Thanks.
