### ISSUE TITLE
Server Error (OK) every time

### ISSUE THREAD

**Issue by P-EB** [roundcube/roundcubemail#6589]
Hi,

On a fresh 1.3.8 installation of roundcube, with php 7.3 on a Debian buster system, I have the famous "Server Error (OK)" bug.

It appears everytime I click actionable text (folder, whatever) and no mail is appearing.

With debug level 1, I saw nothing in errors, sql, imap files. The login step works fine and dovecot replies to roundcube queries.

I'm out of ideas, and Xdebug didn't tell me a thing I can understand.

If someone has some suggestions on where to search, I'm eager to follow them.
!

All my alternative clients (neomutt on the actual server, and thunderbird from home) are succeeding at logging in and receiving emails. Postgresql accepts queries from the roundcube server and the user got created in the user database.

[Screenshot](https://user-images.githubusercontent.com/3770652/51092512-67799580-1798-11e9-9bae-3dc37f08b8bf.png)

**Comment by alecpl** [comment]
Take a look at ajax response in browser console. Try with different browser. Disable all plugins.

**Comment by P-EB** [comment]
Hi @alecpl ,

I tested with both Firefox and Chromium, without any difference. I see no error in my debug console.

I use no plugin.

**Comment by johnwmail** [comment]
I have this problem too, debian/nginx/php7.3/roundcube-1.3.8
and I noticed a lot of this in php.log
WARNING: [pool roundcube] child 608 exited on signal 11 (SIGSEGV) after 76279.405649 seconds from start

**Comment by P-EB** [comment]
Interesting. Maybe some compatibility issues between roundcube and php7.3?

**Comment by johnwmail** [comment]
And it only happen, when I use chromium on linux, firefox on linux never see this.

**Comment by johnwmail** [comment]
> And it only happen, when I use chromium on linux, firefox on linux never see this.

I also see this on firefox now :(

**Comment by alecpl** [comment]
@P-EB Do you see these php-fpm errors too? Then it would look like a php-fpm issue.

**Comment by P-EB** [comment]
@alecpl sadly no. In my specific case I had no segfault and no error.

**Comment by johnwmail** [comment]
Hi, the problem/error look like gone, after upgrade php to 7.3.2.
Thanks.

**Comment by alecpl** [comment]
@P-EB, any new findings on this? I propose to investigate ajax responses using browser console. Don't look for errors, but check response content and headers.

**Comment by P-EB** [comment]
@alecpl I'll give it a try this evening.

Thanks!

**Comment by alecpl** [comment]
No feedback. That error indicates that response to an ajax request is empty or malformed. Without more info (e.g. the error fro log or response content from browser console) we can do nothing about it.

**Comment by P-EB** [comment]
I get it, sorry but my schedule got totally preempted.

As soon as I find some time to do a fresh reinstall I'll send you a notice.
