### ISSUE TITLE
rcmail_install.php - "README" file is not an obvious file to check the config at the 3rd step of the installation

### ISSUE THREAD

**Issue by maxandgithub** [roundcube/roundcubemail#6599]
Hi! 
I spent a few hours to find the real reason of such error (3rd step of the Roundcubemail-1.3.8-complete installation) :-(  

**Test filetype detection
Fileinfo/mime_content_type configuration:  NOT OK
Check the Fileinfo functions of your PHP installation.
The path to the magic.mime file can be set using the mime_magic config option in Roundcube.** 

The reason is the missing "README" file (skins/larry/README) which was specially deleted by me since this is unnecessary info-garbage on the my server, just like all other similar info-files in other dirs/subdirs (README, INSTALL, CHANGELOG etc...). 
Yes, I love to be safe even if someone thinks it's strange :-| 

"README" file is not an obvious file to check the config at the 3rd step of the installation in some cases... 

https://github.com/roundcube/roundcubemail/blob/796e5a17e6389ac0edae53eb8249e6fdf446a0d9/program/include/rcmail_install.php#L516

`
public function check_mime_detection()
{
	$errors = array();
	$files  = array(
		'skins/larry/images/roundcube_logo.png' => 'image/png',
		'program/resources/blank.tiff'          => 'image/tiff',
		'program/resources/blocked.gif'         => 'image/gif',
		'skins/larry/README'                    => 'text/plain',
	);
	foreach ($files as $path => $expected) {
		$mimetype = rcube_mime::file_content_type(INSTALL_PATH . $path, basename($path));
		if ($mimetype != $expected) {
			$errors[] = array($path, $mimetype, $expected);
		}
	}
	return $errors;
}
`

So, it would be better to replace the "README" file with something else in this function. 
I think it should be some kind of "system" file, which is 100% available in the directory in all cases. 
Or create a special "service file" (text/plain) if you want to check strictly "text/plain". 

**Or the best option**, the notification of the missing "README" (skins/larry/README) file during the test (or before the start of installation).

**Comment by alecpl** [comment]
Good point. We could put some small plain text file in `program/resources`.

**Comment by maxandgithub** [comment]
Or it may be better to make a file availability check...
And as a result, output a "notification of the missing file" (.../skins/larry/README) in this case. 
On the other hand, such a notification sounds a bit strange :-\

**Comment by alecpl** [comment]
Fixed.
