### ISSUE TITLE
Additional info to the Roundcube Wiki/Info files (SELINUX settings for /logs/ and /temp/)

### ISSUE THREAD

**Issue by maxandgithub** [roundcube/roundcubemail#6601]
I'm surprised why there is no information about the need to configure "SELINUX policy" for /logs/ and /temp/ Roundcube directories on the wiki page with installation information + other txt info files? 

I spent many hours to understand the reason why there are not enough rights to write to the directories :-( 

Actually, changing "chmod" (even up to 777) and even changing the "owner/group" of /logs/ and /temp/ directories to "root:root" doesn't help with new CentOS 7 versions! 
The reason is SELINUX which has a stricter policy for directories than usual in >= CentOS 7. 

I don't want to disable SELINUX because it affects the security of the system!

So, if you don't want to disable SELINUX then you need to configure the SELINUX policy for these directories by performing the following steps: 

- Step 1. 
semanage fcontext -a -t httpd_sys_rw_content_t "/path_to_roundcube/logs(/.*)?"

- Step 2. 
semanage fcontext -a -t httpd_sys_rw_content_t "/path_to_roundcube/temp(/.*)?"

- Step 3. 
restorecon -Rv /path_to_roundcube/

This is the only correct way that really works anyway. 
At the same time, it is enough "chmod" - 750 to this directories . 
The same way is recommended for "Postfixadmin" panel (See - / temporary_c /). 

You can write in more detail... I just want to share this issue. 
P. s. I'm using Nginx + PHP-FPM on CentOS 7. 
In my case - Roundcubemail-1.3.8-complete

**Comment by maxandgithub** [comment]
The above steps make sense if Roundcube has been unpacked and installed manually (in the directory for domains like - /var/www/path_to_roundcube/...). 
Commands for SELinux "context" in other installation directories - may be called something else... But I'm not sure.

**Comment by alecpl** [comment]
Added a note to the INSTALL file. Feel free to improve our wiki pages.
