### ISSUE TITLE
Feature request: new version notify

### ISSUE THREAD

**Issue by itcrowd72** [roundcube/roundcubemail#6602]
Before create webupdater in #6352 we need notify about new version.

For example this is notify from matomo

![screenshot at 2019-01-24 12-20-37](https://user-images.githubusercontent.com/29428813/51661388-8cf57300-1fd2-11e9-95dd-7a9fba457831.png)

**Comment by alecpl** [comment]
If we had admin panel then maybe, but we have not. I would not want to make my users see such notification. So, maybe first implement some simple admin panel. Closing for now.

**Comment by itcrowd72** [comment]
Ok :( I try make this as plugin

**Comment by alecpl** [comment]
I see there is one already: https://plugins.roundcube.net/packages/valarauco/admin_options
