### ISSUE TITLE
Unable to send an email: SMTP Error (535): Authentication failed

### ISSUE THREAD

**Issue by PaulPeda** [roundcube/roundcubemail#6605]
I'm not an expert and I absolutely need help.  I'm not able to send emails anymore

Unable to send an email: SMTP Error (535): Authentication failed

I know that you already explained the solution to somebody but I didn't understand how to proceed.

Please, help me.

**Comment by alecpl** [comment]
Check all smtp_* options in config (take a look at defaults.inc.php for all available options). smtp_debug may help in investigating details of SMTP conversation.

**Comment by PaulPeda** [comment]
Where do I find the options?

**Comment by charliecombebias** [comment]
I have the same issue and I have no idea what you mean by "Check all smtp_* options in config (take a look at defaults.inc.php for all available options). smtp_debug may help in investigating details of SMTP conversation."

How can I fix the bug?

Many thanks for your help
