### ISSUE TITLE
Problem communicating between Roundcube on the web server and the Mysql / MariDB database

### ISSUE THREAD

**Issue by MAT-WEISS-2017** [roundcube/roundcubemail#6606]
I have a problem communicating between Roundcube on the web server and the Mysql / MariDB database. Other applications do not experience this problem. On the same server also runs a Nextcloud instance with Email plugin. In this case, there are no error messages.
I've already disabled all roundcube extensions. But even in operation without extensions, the problem is.
I already have the fix at https://bugs.php.net/bug.php?id=77308 (http://git.php.net/?p=php-src.git;a=commit;h=1a306cc9a1679a758c859731a78429429830a439) but also that does not solve the problem.

THE ERROR OCCURS WITH OR WITHOUT OPCACHE ENABLED AND ALSO WITH OR WITHOUT APCU ENABLED AND ALSO WITH OR WITHOUT ENABLED ROUNDCUBE-PLUGINS !!!

Does anybody have the same Problem? Is there a solution for this?

Thanks in advance for your assistance!

Roundcube version: Roundcube Webmail 1.3.8
Operating system: Arch Linux
Web server: Apache / 2.4.38
PHP: PHP 7.3.1
Database: MariaDB 10.3.12

Errors (I only changed a folder in the frontend)
==============================
Jan 29 10:02:55 mysqld[4772]: 2019-01-29 10:02:55 20 [Warning] Aborted connection 20 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)

**and**

zend_mm_heap corrupted

**(many times)**

tail -f /var/log/httpd/error_log
================================

[Tue Jan 29 09:43:09.699349 2019] [mpm_prefork:notice] [pid 28451] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Jan 29 09:46:18.839665 2019] [mpm_prefork:notice] [pid 503] AH00163: Apache/2.4.38 (Unix) PHP/7.3.1 OpenSSL/1.1.1a configured -- resuming normal operations
[Tue Jan 29 09:46:18.947847 2019] [core:notice] [pid 503] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
[Tue Jan 29 09:49:51.199407 2019] [core:notice] [pid 503] AH00052: child pid 1816 exit signal Segmentation fault (11)
zend_mm_heap corrupted
[Tue Jan 29 09:52:47.398442 2019] [core:notice] [pid 503] AH00052: child pid 1813 exit signal Segmentation fault (11)
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted
zend_mm_heap corrupted

journalctl -u mariadb
=====================

Jan 29 10:02:12 systemd[1]: Starting MariaDB 10.3.12 database server...
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] /usr/bin/mysqld (mysqld 10.3.12-MariaDB) starting as process 4772 ...
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Warning] You need to use --log-bin to make --binlog-format work.
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Using Linux native AIO
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Uses event mutexes
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Number of pools: 1
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Using SSE2 crc32 instructions
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Completed initialization of buffer pool
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Creating shared tablespace for temporary tables
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Waiting for purge to start
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: 10.3.12 started; log sequence number 64669647896; transaction id 266087706
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] Server socket created on IP: '::'.
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] Reading of all Master_info entries succeded
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] Added new Master_info '' to hash table
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] /usr/bin/mysqld: ready for connections.
Jan 29 10:02:13 mysqld[4772]: Version: '10.3.12-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Source distribution
Jan 29 10:02:13 systemd[1]: Started MariaDB 10.3.12 database server.
Jan 29 10:02:13 mysqld[4772]: 2019-01-29 10:02:13 0 [Note] InnoDB: Buffer pool(s) load completed at 190129 10:02:13
Jan 29 10:02:48 mysqld[4772]: 2019-01-29 10:02:48 13 [Warning] Aborted connection 13 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)
Jan 29 10:02:55 mysqld[4772]: 2019-01-29 10:02:55 20 [Warning] Aborted connection 20 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)
Jan 29 10:02:57 mysqld[4772]: 2019-01-29 10:02:57 14 [Warning] Aborted connection 14 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)
Jan 29 10:03:04 mysqld[4772]: 2019-01-29 10:03:04 22 [Warning] Aborted connection 22 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)
Jan 29 10:03:39 mysqld[4772]: 2019-01-29 10:03:39 12 [Warning] Aborted connection 12 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)
Jan 29 10:04:24 mysqld[4772]: 2019-01-29 10:04:24 49 [Warning] Aborted connection 49 to db: 'roundcubemail' user: 'roundcube' host: 'localhost' (Got an error reading communication packets)
.
.
.

httpd -V
========

Server version: Apache/2.4.38 (Unix)
Server built:   Jan 22 2019 22:32:58
Server's Module Magic Number: 20120211:83
Server loaded:  APR 1.6.5, APR-UTIL 1.6.1
Compiled using: APR 1.6.5, APR-UTIL 1.6.1
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/bin/suexec"
 -D DEFAULT_PIDLOG="/run/httpd/httpd.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

php -v
======

PHP 7.3.1 (cli) (built: Jan 21 2019 11:20:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies

	
php -m
======

[PHP Modules]
apc
apcu
bz2
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
SimpleXML
sodium
SPL
standard
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

cat /etc/php/conf.d/opcache.ini
===============================

zend_extension=opcache
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.save_comments=1
opcache.revalidate_freq=1
opcache.fast_shutdown=1

**Comment by alecpl** [comment]
"zend_mm_heap corrupted" suggests a bug in PHP. I don't think we can help you. I have no problems with PHP 7.3.1 on Ubuntu 18.04 and MySQL 5.7.25.

**Comment by MAT-WEISS-2017** [comment]
But I do not understand why nextcloud does not cause any errors. Its database is much more extensive. Nextcloud will make many more requests to the database engine. And nextcloud uses exactly like roundcube php 7.3.1.

**Comment by alecpl** [comment]
I don't know if nextcloud uses pdo or not. Anyway, even a smallest detail might be deciding. You can't find a culprit without stracing the process and seeing where it fails.
