### ISSUE TITLE
Roundcube Logs Passwords in Cleartype!

### ISSUE THREAD

**Issue by Fefke** [roundcube/roundcubemail#6609]
I had an internal server error and checked out the logs.
The first thing I saw was my password in truetype.

It is logged in this format:
`rcmail->login('user@server...', 'TRUETYPE_PASSWORD', 'localhost', true)`

The function _login_ is called on line 121 in the index.php file.
I prefer encrypting the password immediately after getting it from the $_POST variable (and unsetting the POST)

**Comment by alecpl** [comment]
I guess you have xdebug/error stack logging enabled. Disable it. This is how it works. Keeping the password encrypted all the time would be inconvenient.
