### ISSUE TITLE
Elastic skin resets layout view for email previews

### ISSUE THREAD

**Issue by jpasher-distribion** [roundcube/roundcubemail#6613]
I recently installed 1.4-beta to try out the mobile rendering capabilities, along with the elastic4mobile plug-in for automatically changing the skin. Like some others, I noticed the email preview layout gets reset to "Widescreen" once you load the mobile version, so when you go back to the desktop version without the elastic skin, it stays as "Widescreen". I saw the report on the elastic4mobile plug-in issue tracker about this, but after a little digging, it really seems more like an elastic skin issue (or possibly a limitation of Roundcube).

Let's assume you start out with the larry skin and the layout set to "Desktop". When you change to the elastic skin, the elastic skin changes the layout to "Widescreen" according to the meta.json file. When you then change the skin back to larry, it leaves it set to "Widescreen". Since the elastic skin doesn't allow you to even set the layout (it always uses "Widescreen"), it's a little weird for the user if they happened to be trying out different skins and it's inadvertently changing other settings.

A possible solution I see would be for Roundcube to allow a skin to override a config option, like the layout setting, but not actually save it to the preferences in the database. If it's always overriding the config option and not letting the user change it, it really doesn't need to save it anyway. That way, when you change the skin back, it automagically reverts back to the previous layout selection, thus giving a more seamless experience (and also fixing the issue when you enable the elastic4mobile plug-in).

**Comment by alecpl** [comment]
I agree. One note: the layout preference is not overwritten until you change messages list options or Mail View preferences.

This is not that simple to fix because ajax requests are not aware of the skin config at all. So, we have to either load skin config on ajax requests or find all places in the client-side code and modify them to not request these special options changes. As for now there's only one such problematic option (layout), so the latter might be easier to do for now.

**Comment by alecpl** [comment]
Actually the former solution was solution, but I chose to use session storage instead of reading the meta file(s) every time. Fixed.

**Comment by MASHtm** [comment]
It seems that this behaviour reappeared with 1.5.0. After using Elastic via elastic4mobile larry is switched to "Widescreen" again.
