### ISSUE TITLE
Curl timeouts

### ISSUE THREAD

**Issue by Xoltus** [roundcube/roundcubemail#6616]
Hi *,

I am trying to switch my domain from A.tld to B.tld, and for the moment being, roundcubemail is accessible from both domains. Even though the setup seems to be working, I experience a massive slowdown when using the new domain, B.tld.
So far, I have approached the problem as follows:
 - open https://B.tld and login as a user
 - In case I provide a wrong password, I get instant feedback (i.e., no slowdown here)
 - On success, the browser loads https://B.tld/roundcubemail/<session_id>/<page> and I experience slowdown on every action
 - Checking /var/log/roundcubemail/errors.log results in 
  <5nu91lm0> PHP Error: Curl error: Connection timed out after 10002 milliseconds in /usr/share/pear/HTTP/Request2/Adapter/Curl.php on line 149 (GET /roundcubemail/<session_id>/<page>)
 - Hence, I *assume* Roundcube still tries to fetch the information form A.tld first, which, however, is unware of <session_id> as I logged in to B.tld.
 - Setting $config['username_domain'] and $config['mail_domain'] to B.tld in config.inc.php seem to have no effect on my problem (i.e., the timeouts still occur when using B.tld but A.tld remains unaffected)

I appreciate if someone can provide me some hints on how to approach this problem any further. Additionally I want to note, that I want to discontinue A.tld in the future, so moving the slowdown from B.tld to A.tld suffices to me.

Best,
Kevin

**Comment by alecpl** [comment]
We don't use HTTP/Request2, so this must be some plugin. Is it Kolab installation?

**Comment by Xoltus** [comment]
Yes, it's a Kolab installation. If I use external clients via imap, I do not experience any slowdown, so I thought it is connected to a setting in Roundcube. 
Thanks for the information, I'll continue my search then.

**Comment by alecpl** [comment]
This is most likely kolab_files plugin trying to connect to Chwala service. Check kolab_files config. Make sure configured URL is accessible/resolvable from the server.

**Comment by Xoltus** [comment]
Brilliant !

Chwala was indeed the problem. I'll just leave my further steps here in case someone in the future has the same problem:
 - trying to login to https://B.tld/chwala returns an internal error
 - /var/log/chwala/errors.log reveals that B.tld is not reachable on port 443
 - Resolving the connection issue, also resolved the slow down

Thanks for all your help :D
