### ISSUE TITLE
Enigma: Where can I import erxisting GPG key?

### ISSUE THREAD

**Issue by stoivo** [roundcube/roundcubemail#6618]
Might be a stupid question, but where can I import existing GPG keys?

![2019-02-08_02 05 47_roundcube webmail pgp keys](https://user-images.githubusercontent.com/3492040/52453100-26ca2d80-2b46-11e9-8fbf-69a68ce84032.png)

I have under stood based on that is should be possible to import existing keys
https://github.com/roundcube/roundcubemail/issues/5276

An other issue I have with my instalation. 
![screen shot 2019-02-08 at 02 07 14](https://user-images.githubusercontent.com/3492040/52453133-482b1980-2b46-11e9-8385-4e067af6ba72.png)

I look wierd. Probably should be owed by www-data
<details><summary>ls -la /opt/www/roundcubemail/plugins/enigma</summary>
<p>

```
total 325
drwxr-xr-x  7 501 admin     14 Jul 10  2017 .
drwxr-xr-x 37 501 admin     37 Feb  8 00:17 ..
-rw-r--r--  1 501 admin    592 Jun 26  2017 composer.json
-rw-r--r--  1 501 admin   2042 Jun 26  2017 config.inc.php.dist
-rw-r--r--  1 501 admin  20865 Jun 26  2017 enigma.js
-rw-r--r--  1 501 admin  12613 Jun 26  2017 enigma.min.js
-rw-r--r--  1 501 admin  16566 Jun 26  2017 enigma.php
drwxr-xr-x  3 501 admin      4 Feb  8 00:54 home
drwxr-xr-x  2 501 admin     13 Jul 10  2017 lib
drwxr-xr-x  2 501 admin     42 Jul 10  2017 localization
-rw-r--r--  1 501 admin 257777 Jun 26  2017 openpgp.min.js
-rw-r--r--  1 501 admin   2508 Jun 26  2017 README
drwxr-xr-x  4 501 admin      4 Jul 10  2017 skins
drwxr-xr-x  2 501 admin      3 Jun 26  2017 tests
```

</p>
</details>

**Comment by alecpl** [comment]
To import keys use Import button. The error message is clear, it should be writable by the user as which the php process works on (depends on system and way the php is set up).

**Comment by stoivo** [comment]
Sorry for the noice, I could find the import button. 
Thank you very much for the work you put in.

Not I have the key imported and working
