### ISSUE TITLE
Remove attachment on reply

### ISSUE THREAD

**Issue by titoo999** [roundcube/roundcubemail#6619]
Would that be interesting to add a setting option to **automatically** remove the attachment on a reply (but not on forwarding) ?

Such option would save some CPU and avoid overloading small servers such as mine.

**Comment by thomascube** [comment]
This already is the default behavior of Roundcube. Attachments are not copied into a reply message, except contents embedded into the HTML message.

**Comment by rarendra** [comment]
How can i allow Attachments to included in when reply to email

**Comment by lnxbusdrvr** [comment]
How can i allow Attachments to included in when reply to email?
What options I put in config.inc.php?
For quick look. I did'nt find it on setting page

**Comment by lnxbusdrvr** [comment]
Answer to myself and raredra:

Images (and perhaps attachment (haven't tried)) are included with reply,
when this setting is something else than 'never'

Settings -> Composing Messages:
   Compose in HTML messages: "never"  // don't set that value
                                                          ^^^^^
