### ISSUE TITLE
Allowing remote resources adds an entry to history

### ISSUE THREAD

**Issue by jsilvermist** [roundcube/roundcubemail#6620]
When you click `Allow` for showing remote resources, it adds an entry to history causing 2 or more back presses to be needed to leave the email message.

Version: 1.4-beta
Theme: Elastic

**Comment by alecpl** [comment]
It shouldn't be a problem if you use the preview frame, but I'm guessing this is about opening the message in a full view (e.g. by double-click on the message record). Am I right?

That feature requires a page reload, so the history will change, but maybe we could modify the browser history. I'm not sure.

**Comment by alecpl** [comment]
Something like this would work, but requires some more cross-browser testing:
```diff
--- a/program/js/app.js
+++ b/program/js/app.js
@@ -2502,8 +2502,11 @@ function rcube_webmail()
     else {
       if (!preview && this.env.message_extwin && !this.env.extwin)
         this.open_window(url, true);
-      else
+      else {
+        if (safe && document.referrer && window.history.replaceState)
+          window.history.replaceState({}, '', document.referrer);
         this.location_href(url, target, true);
+      }
     }
   };
 
```

**Comment by jsilvermist** [comment]
> It shouldn't be a problem if you use the preview frame, but I'm guessing this is about opening the message in a full view (e.g. by double-click on the message record). Am I right?

I believe so. I'm pretty sure the place this had the biggest impact in usability for me was while testing the new Elastic theme on mobile.

**Comment by alecpl** [comment]
Fixed.
