### ISSUE TITLE
Message download is missing CSRF token

### ISSUE THREAD

**Issue by mharjac** [roundcube/roundcubemail#6621]
When large(er) mail is received, it can't be shown and a download link is presented instead:

`The message part is too big to process it. Download`

When you click at the download link the following message is displayed:
```
REQUEST CHECK FAILED
For your protection, access to this resource is secured against CSRF.
If you see this, you probably didn't log out before leaving the web application.

Human interaction is now required to continue.

Please contact your server-administrator.
```
Download link example:
```
http://10.170.42.192/roundcubemail-1.4-beta/?_task=mail&_action=get&_download=1&_uid=335723&_part=0&_mbox=INBOX
```
Problem: download request is missing CSRF token.

**Comment by alecpl** [comment]
Fixed.
