### ISSUE TITLE
Drag and drop then escape

### ISSUE THREAD

**Issue by romelfausto** [roundcube/roundcubemail#6623]
Hi,

One time I was dragging an email to another folder on a web browser, I accidentally pressed the ESC key. The email then disappeared.

I am not sure if this is a bug or a feature that I didn't know?

Thank you.

**Comment by alecpl** [comment]
I'm not sure I fully understand. The ESC key should abort drag-n-drop action. And I see an issue when you press ESC when your mouse is over another folder. Instead of aborting the action will execute, i.e. the message(s) will be moved to that folder. Is this the issue you're talking about?

**Comment by alecpl** [comment]
Fixed. If you meant some different bug, please create a new ticket with more details.
