### ISSUE TITLE
Should Roundcube log full session_id on login logs?

### ISSUE THREAD

**Issue by maurom** [roundcube/roundcubemail#6625]
Hi all. Doing a review of RC logging we found out that the login log files, when activated via the [`log_logins` configuration directive](https://github.com/roundcube/roundcubemail/blob/0492b1f6e5589bcde05aaaf5dd77d30cc8a42c59/config/defaults.inc.php#L97-L99), contain the full session id of the user, disregarding the [`log_session_id` setting](https://github.com/roundcube/roundcubemail/blob/0492b1f6e5589bcde05aaaf5dd77d30cc8a42c59/config/defaults.inc.php#L77-L79), as seen on [the `log_login` function](https://github.com/roundcube/roundcubemail/blob/0492b1f6e5589bcde05aaaf5dd77d30cc8a42c59/program/include/rcmail.php#L1121-L1134).

For example:

`[17-Feb-2019 07:11:12 -0300]: <nb5jxofg> Successful login for mauro (ID: 119) from 203.0.113.37 in session nb5jxofgy290e4auobybaeqw41`

We find the `log_logins` directive useful, as it allows us to quickly match (action, user, IP) and act in consequence, without relying on imap and apache logs, but current security recommendations [1] advise to hide or hash the full session ids as to prevent session hijacking in case of an event of an -unfortunate- log disclosure.

So my questions: is the full id useful for debugging purposes? can we remove it and rely on the short 8-character part? or better, can we replace it by shaNNN(session_id()) ?

Thanks in advance!

[1] Requirements 2.12 and 3.6 of the [OWASP ASVS 3.0.1](https://www.owasp.org/images/3/33/OWASP_Application_Security_Verification_Standard_3.0.1.pdf)

> 2.12: "Verify that all authentication decisions can be logged without storing sensitive session identifiers or passwords . This should include requests with relevant metadata needed for security investigations."
>
> 3.6: "Verify that the session id is never disclosed in URLs, error messages, or logs. This includes verifying that the application does not support URL rewriting of session cookies."

**Comment by alecpl** [comment]
If I'm correct, to hijack the Roundcube session you need to know two cookies roundcube_sessid and roundcube_sessauth. I didn't design this and I don't know/remember why we use two not one.

Anyway, we should consider if we really need the (full) id in logs. Separately from `log_session_id` setting. And do not forget we have also `log_session` (btw, shouldn't that become `session_debug`?).

@thomascube what do you think?

**Comment by maurom** [comment]
> If I'm correct, to hijack the Roundcube session you need to know two cookies roundcube_sessid and roundcube_sessauth. I didn't design this and I don't know/remember why we use two not one.

Thanks for your input on this issue.
That is correct. I have just tested this (by cloning cookies here and there) and you need to have both roundcube_sessid and roundcube_sessauth to take control of a session. Copying the first one from the log files won't cut it, and that makes my bug report invalid.

> Anyway, we should consider if we really need the (full) id in logs. Separately from `log_session_id` setting. And do not forget we have also `log_session` (btw, shouldn't that become `session_debug`?).

I'd better leave it up to you to decide.

Thanks again,

**Comment by alecpl** [comment]
Fixed.
