### ISSUE TITLE
I do not have icons

### ISSUE THREAD

**Issue by Artem2710** [roundcube/roundcubemail#6626]
Hello. Tell me why I do not have icons in the Larry skin? There were no changes in style?
![image](https://user-images.githubusercontent.com/38757512/53007939-f08f8680-3440-11e9-981f-9049cda56923.png)
![image](https://user-images.githubusercontent.com/38757512/53007990-0b61fb00-3441-11e9-96c1-951385a24418.png)

**Comment by alecpl** [comment]
Try to disable all plugins and enable the one by one. Not enough information, we can't help you.

**Comment by Artem2710** [comment]
When disconnecting all plugins nothing changes. In other skins everything works well.
