### ISSUE TITLE
elastic skin js error

### ISSUE THREAD

**Issue by chrisharney** [roundcube/roundcubemail#6628]
getting the following errors with the elastic skin
(roundcube 1.4-git)

Uncaught TypeError: rcmail.register_menu_button is not a function
ui.js:399

Uncaught TypeError: rcmail[list].enable_checkbox_selection is not a function
ui.js:521

eleastic/deps folder with bootstrap js/css was also missing, i uploaded this manually and it worked.

**Comment by alecpl** [comment]
There are instructions how to build the skin and add dependencies. So, you say there's no error if you add missing files? Not a bug.

**Comment by chrisharney** [comment]
Hi, there is only instructions on how to compile the css which is not the issue. If you read my comment again you will notice they are javascript errors and not related to bootstrap. The errors still persists after bootstrap is installed.
