### ISSUE TITLE
Login fails 99% times in Webmail Roundcube on Chrome browser

### ISSUE THREAD

**Issue by loop2000** [roundcube/roundcubemail#6630]
Almost every time I try to login on diverse webmail pages (using Roundcube or Roundcube clones) it doesnt accept my login information and gives errors like the password is not correct or the combination of the email & password is not correct!
But everytinme I login the seond time - its working!
So theres clearly a bug in Rundcube webmail or a bug in Chrome whic the Roundcube developers havent taken care of in their code.
But the problem wasnt in earlier versions of Roundcube!
I have noticed several webmail companies, when they have upgraded their webmail system, then they all have the same bug/problem/issue.
It takes 2 tries to login on Roundcube webmail.

Its really annoying to have to login twice all the time.

Is anybody fixing this issue? Or has a solution?

**Comment by alecpl** [comment]
Does it happen every time? Or maybe only after you use logon page that was open for quite a while? Did you try on a different computer? What Roundcube versions did you try? Works for me.

**Comment by mohe2015** [comment]
I'm not familiar with this project at all but the symptoms look like an invalid CSRF token.

**Comment by alecpl** [comment]
No feedback.

**Comment by loop2000** [comment]
it happens 19 out of 20 times!

I dont know the versions, Im just using my email providers webmail pages , and unfortunately they are using Roundcube.

One of them worked perfectly for many years, but suddently their interface was looking like and acting exactly the same as another internet providers roundcube interface! So I assume they have made upgrades to the newest version, and therefor have the same issues all of them. The login issue is not the only annoying thing.

Im using chrome browser.

**Comment by loop2000** [comment]
please dont close before solution
