### ISSUE TITLE
Glitch when pressing 'PAGE DOWN' button on replying to long email (elastic - rc 1.4-beta)

### ISSUE THREAD

**Issue by martijnvankekem** [roundcube/roundcubemail#6631]
When replying to an email that's very long, pressing the page-down button results in the complete web-page scrolling down, while being unable to restore that action and therefore having to re-write your email all over again if you did not save it. Also, when this happens, the top bar becomes unavailable, therefore clicking the cancel/send button is not possible and only fixable by a page refresh.

**Comment by alecpl** [comment]
I'm unable to reproduce. It's possible that it's fixed. What browser? Is it for HTML or plain text? What screen size? Any chance you could test with git-master?

**Comment by martijnvankekem** [comment]
It's not fixed yet. I tested it in Chrome Version 72.0.3626.109 (Official build) (64-bits). The glitch seems to occur only if you're writing an HTML e-mail. Screen size doesn't seem to matter, I tested it with multiple devices. See the attachment for an explanation.
[Videos.zip](https://github.com/roundcube/roundcubemail/files/2888815/Videos.zip)

**Comment by alecpl** [comment]
You're not testing git-master, so how do you know it's not fixed yet?
