### ISSUE TITLE
Forwarded mail goes to spam

### ISSUE THREAD

**Issue by michalv94** [roundcube/roundcubemail#6634]
Hi,
im solving some issue with email forwarding with Roundcube. Forwarded emails are merked as spam in destination mail server (with SPF fail reason). When i try to forward email from another service (not postfix with rc) it adds following to header:

<code>
Resent-From: <*****@******.sk>
Resent-To: <******@gmail.com>
</code>

I think that adding this expresion to email header while forwarding will solve this issue. Could anyone help with proper forward setting to not being marked as spam?
Thanks

**Comment by alecpl** [comment]
We set these headers when using Bounce feature, but not for forwards. I think they should not be added to forwards. Thunderbird does not add these too.

Imo, this is not a MUA issue.
