### ISSUE TITLE
move icon in Elastic

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6637]
I think the move icon currently used in Elastic suggested the wrong kind of move. Arrows like that are for moving an image around on a screen not moving a message between folders. I guess its used because FA does not offer any particually great alternatives at present but I was wondering about using the folders icon https://fontawesome.com/icons/folder-open?style=solid. This icon is already used for the folders button in phone view. The, slightly stretched, logic behind using the open folder icon is because you are move the message into another folder.

**Comment by alecpl** [comment]
Agreed. Done.
