### ISSUE TITLE
Display calendar information in mail display

### ISSUE THREAD

**Issue by stoecker** [roundcube/roundcubemail#6639]
Especially in business communication a lot are use Outlook and its calendar features. They are so used to it, that they often don't repeat essential information like place and time in the mail text, but only rely on the attached vcard. The vcard format is ASCII, but not really human readable. 

It would be extremely helpful if in case of an attached VCard the essential information like place and time are shown in the mail display.

ATM the only solution seems usage of a full featured collaboration software like kolab, which is a bit overkill when the only task is to know the meeting time and place.

**Comment by alecpl** [comment]
This is out of scope of Roundcube core. Plugins exist.

**Comment by stoecker** [comment]
If there exist plugins, at least name one. I didn't find one.

**Comment by rmcaninch** [comment]
There is vcard_attachments plugin included in roundcube. That may display the information you are looking for.

**Comment by stoecker** [comment]
> There is vcard_attachments plugin included in roundcube. That may display the information you are looking for.

I couldn't find out what that plugin does, but it does not display ics data in plain readable text.

And why is this ticket closed with "out of scope of Roundcube core"? This git also contains plugins, e.g. the vcard plugin.

**Comment by rmcaninch** [comment]
That vcard plugin would show attached vcards (.vcf).

There is a calendar plugin that will show an ics attacment along with adding a calendar tab to the interface.
https://plugins.roundcube.net/packages/kolab/calendar

**Comment by stoecker** [comment]
So my initial statement remains true:
ATM the only solution seems usage of a full featured collaboration software like kolab, which is a bit overkill when the only task is to know the meeting time and place.
