### ISSUE TITLE
Plain text mail display problem

### ISSUE THREAD

**Issue by frank499** [roundcube/roundcubemail#6640]
There is a problem displaying plain text mails containing certain key words.
Steps to reproduce with Roundcube Webmail 1.3.8:

1. compose a new plain text message which contains the following lines:
src='/'
href='/'
background='/'

2. save the message as draft

3. open the draft message. Message body is displayed like this:
src='skins/larry/'
href='skins/larry/'
background='skins/larry/'

This is only a display problem. The "show source" function displays the
expected content. Also if viewed by another program the correct content is
displayed. The problem is related to the fix_paths method in
program/include/rcmail_output_html.php. fix_paths is applied to all HTML
output including the already formatted message body. This replaced '/' with
'skins/larry/'.

**Comment by alecpl** [comment]
It should have been part of d02e6ea45ea3b5e8e44659, but it wasn't. Fixed now.

It may break some things so I hesitate to backport it to 1.3.8 at this point. Maybe later.
