### ISSUE TITLE
roundcubemail database cache table keep growing

### ISSUE THREAD

**Issue by yasirugw** [roundcube/roundcubemail#6644]
Hi all!
Roundcubemail database cache table keep growing.
When I check the content I saw those records has expires value.
Can we delete all cache data after the expires date?

**Comment by alecpl** [comment]
I guess you're on debian or sth that has php session garbage collector disabled. You have to use gc.sh from time to time. We fixed this via #6560.

**Comment by yasirugw** [comment]
Yes, we are on debian. I tried the gc.sh script but that clears only session table I think. Our roundcubemail PostgreSQL database size is 3436 MB and its cache table size is still 2710 MB. Seems like it has all the emails content in it.

**Comment by alecpl** [comment]
The script cleans also caches. Maybe you should decrease TTL to make entries expiry sooner. Enable sql_debug while running the script to see what sql queries are used. What Roundcube version?

**Comment by yasirugw** [comment]
@alecpl We use 1.3.8 version. It seems the gc.sh did cleaned the table but table didn't reduce the file size. We got it fixed by running `vacuum FULL cache;` for postgres. Thank you!
