### ISSUE TITLE
Managesieve Vacation: Cannot set Reply sender address 

### ISSUE THREAD

**Issue by Stardust25** [roundcube/roundcubemail#6645]
Hello,

we use RC / ManageSieve to manage our SieveFilters. This is working well so far except when setting Reply-Sender-Address (from) in "Reply with message". The WebGUI shows "Unable to save filter. Server error occurred."
In PHP Errorlogs I can see the following:

[25-Feb-2019 12:30:06 Europe/Berlin] ERROR: script errors: line 5: syntax error, unexpected $undefined (3)

The Sieve script looks like this:

require ["vacation"];
\# rule:[scripts]
if false # header :contains "subject" "You there?"
{
   vacation :addresses "test<span>@test.de" :subject "No" "I am not here..";
}

I think that the plugin here is not working as expected. When I add the "from" manually (Line 5) in this script it will also show up on the WebGUI.

Kind Regards 

Jo

**Comment by alecpl** [comment]
What version? Provide a screenshot of the UI before you hit submit button.

**Comment by Stardust25** [comment]
Version: 1.3.9

Screenshot before submitting:
![sieve_vacation](https://user-images.githubusercontent.com/14089223/53338840-069bbc00-3905-11e9-975d-c0239cd5aa5d.png)

Screenshot after submitting:

![sieve_error](https://user-images.githubusercontent.com/14089223/53338868-14514180-3905-11e9-9713-b0619f38aa80.png)

**Comment by Stardust25** [comment]
Here is the ngrep from the above example:


[AP] #15
PUTSCRIPT "Test" {164+}.
require ["vacation"];
# rule:[Vacation1]
if header :contains "subject" "Hallo"
{
.vacation :addresses "test@test.de" :subject "test" :from "test@test.de" "Test";
}
.

NO {61}.
script errors:.
line 5: syntax error, unexpected $undefined.

**Comment by alecpl** [comment]
This looks like a bug on managesieve server side. What software are you using?

**Comment by Stardust25** [comment]
Setting "from" in sieve filters worked with squirrelmail.
I am using Cyrus 2.2.

**Comment by alecpl** [comment]
That's a very old software. As the syntax of the generated script looks correct we can't do much about this. What do you mean it worked? Does it still work? What is the script generated by squirrel?

**Comment by Stardust25** [comment]
Will update to a later version and report back..

**Comment by paulmenzel** [comment]
Any update?

**Comment by Stardust25** [comment]
No, was not able to upgrade our mail-setup yet.
