### ISSUE TITLE
Managesieve Vacation: Mails are not kept when redirecting

### ISSUE THREAD

**Issue by Stardust25** [roundcube/roundcubemail#6647]
Issue:

When creating a vacation rule with an incoming message action (Redirect to) the original receiver does not get this mail:

![vacation](https://user-images.githubusercontent.com/14089223/53572137-d35a6680-3b6a-11e9-9c39-478e886309f6.png)

The user is not aware of mails which have been sent to him during vacation.

Expected:

Save the message in the users inbox and then redirect the message to the defined address. 
(Or at least present an option to do so) 

I know it is possible to modify this rule further with sieve, but this is not an option for our customers who are not familiar with sieve filters and IT in general.

**Comment by alecpl** [comment]
You can redirect or send a copy.

**Comment by Stardust25** [comment]
Can you please give an example on how to do this with additional filters?

**Comment by alecpl** [comment]
The option should be available in the selector, but I guess your server might not support 'copy' extension.

**Comment by Stardust25** [comment]
Thank you.
