### ISSUE TITLE
[elastic] No prev/next button for loading messages on message view

### ISSUE THREAD

**Issue by kwiatek6324** [roundcube/roundcubemail#6648]
On larry skin after loading message were two buttons for loading next/prev messages.
They are missing on elastic skin.

**Comment by alecpl** [comment]
Indeed. The buttons are missing in "full window" mode.

**Comment by kwiatek6324** [comment]
Alec,

The nice feature connected with this issue is to add the same buttons for email preview.
Reading emails in one folder should be easier.

Regards
AK

**Comment by alecpl** [comment]
Buttons added. There's really no place in email preview for buttons. And when you message list you can use keyboard to navigate throughout the list. Use Up/Down arrow for fast jumping from message to message.
