### ISSUE TITLE
SSL certificate check fails -> no useful logged errors

### ISSUE THREAD

**Issue by drboone** [roundcube/roundcubemail#6649]
If roundcube is instructed to check server ssl certificates for validity, and these checks fail (e.g. wrong hostname in cert), roundcube doesn't log anything relevant to that problem.  It will instead report "could not connect" or "STARTTLS failed" or similar.  A packet trace will just show an Encrypted Alert SSL packet and a FIN packet as the connection is closed.

Roundcube should log some indication of _why_ it is refusing to continue with such a connection.

**Comment by alecpl** [comment]
Problem is that PHP does not provide this information. We would need to do some lower level checks, which might be not that simple. If you know how to improve the situation please create a pull request.

**Comment by johndoh** [comment]
I have added a little information to the [FAQ](https://github.com/roundcube/roundcubemail/wiki/FAQ#problems-connecting-imapsmtp-server-via-ssltls) about this error
