### ISSUE TITLE
1und1 Imap Delimiter

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [roundcube/roundcubemail#6651]
Hello,
I use roundcube with ident_switch to manage my accounts. 5 are local with dovecot and 1 is a 1und1 Imap Account.
On Thunderbird all is okay, also in 1und1 Webmailer.

But in Roundcube I see every Subfolder from archive as separate folder like:
Archives
Archives/2019
Archives/2019/2019-01
Archives/2019/2019-02

I tested with / and . as delimiter without success.

The other accounts are okay...

**Comment by alecpl** [comment]
We do not support ident_switch plugin.

**Comment by Sh4d0wF1gh7** [comment]
not sure if this is really a issue in ident_switch, more I believe in roundcube?
