### ISSUE TITLE
Multi Domain Setup - plugin configuration

### ISSUE THREAD

**Issue by janpekar** [roundcube/roundcubemail#6652]
Hello,

I tried multi-domain setup as described here
https://github.com/roundcube/roundcubemail/wiki/Configuration:-Multi-Domain-Setup
It is working, but when I try to enable plugins per domain basis, it is not working (plugin is not enabled). I added for example

```array_push($config['plugins'],"managesieve");```

into per domain config and plugin is not loaded/active.

Is there any way how to control plugin loading per domain or per user?
Thank you

**Comment by johndoh** [comment]
try `array_push($this->prop['plugins'], 'managesieve');`

**Comment by alecpl** [comment]
This is not supported scenario. You do not have access to the initial config.

**Comment by janpekar** [comment]
Maybe it is not supported, but solution from johndoh worked for me.
Thank you.
