### ISSUE TITLE
sieve filter forwarding recipient limit

### ISSUE THREAD

**Issue by putro** [roundcube/roundcubemail#6653]
If more than 4 addresses are set as forwading address in a sieve filter,
messages are not forwarded at all.
up to 4 addresses works fine.

example filter not working:

if true
{
        redirect "1@test.com";
        redirect "2@test.com";
        redirect "3@test.com";
        redirect "4@test.com";
        redirect "5@test.com";
}

no error message is displayed when filter is created/updated

Roundcube Webmail 1.3.6

**Comment by johndoh** [comment]
what backend are you using, is it dovecot? if so have a look at [sieve_max_redirects](https://wiki2.dovecot.org/Pigeonhole/Sieve/Configuration#Configurable_Limits)

**Comment by putro** [comment]
yes, thank you, the problem is dovecot, sorry.
