### ISSUE TITLE
Deleting a collapsed thread doesn't select next row

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#6655]
If you select a thread in the collapsed state and delete it, nothing is selected. If you press cursor down you select the first entry but not fully only the marker at the left is changing to blue and the mail is not loaded. if you press a second time the cursor down key the next message (2nd message) is correctly selected and displayed in the preview.

**Comment by alecpl** [comment]
Confirmed. This is not skin-specific.

**Comment by alecpl** [comment]
Fixed.

**Comment by HLeithner** [comment]
Works fine now, thx
