### ISSUE TITLE
Calendar can not be accessed by changing the skin to Elastic in Roundcube Webmail 1.4-rc1

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#6656]
Calendar can not be accessed by changing the skin to Elastic. Works well with Larry
Upgrade today from Roundcube 1.3.8 to 1.4-rc1

The message is:
FILE NOT FOUND
The requested resource was not found!
Please contact your server-administrator.
Failed request: xxxxxxxxxx/?_task=calendar

Roundcube Webmail 1.4-rc1
calendar | 3.3.3

LOGS:
[02-Mar-2019 11:50:53 -0500]: <slree8sk> PHP Error: Error loading template for calendar.calendar in /var/www/roundcube/program/include/rcmail_output_html.php on line 717 (GET /?_task=calendar)

![captura de pantalla de 2019-03-02 11-31-50](https://user-images.githubusercontent.com/2455005/53684771-a11e4580-3cdf-11e9-9095-7f5b158fb244.png)

**Comment by alecpl** [comment]
We do not support Calendar plugin here. Anyway, you'll need version of the plugin from git-master.
