### ISSUE TITLE
Issue with adding a contact to Contacts

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#6658]
First I have to thank you for great job with the recent development. Roundcube 1.4 with elastic theme is awesome.
Issue that I would like to report is following:
1. I click on the sender's name in the Inbox and choose "Add to address book".
2. Next open contacts.
3. Select newly added contact and choose Edit.
4. There is no field where I can edit contac's name.
As on the attached image - you can notice that there is a contact "Janusz Wilk" but when I press Edit, field with this name doesn't appear. This happens on fresh clean install of version 1.4-RC1
![obraz](https://user-images.githubusercontent.com/24810145/53744921-4d0d8f80-3e9e-11e9-9c10-718abc399822.png)

**Comment by alecpl** [comment]
I cannot reproduce. Usually for contact added this way the name is stored in "Display Name" field. That field is visible for me.

Is the name visible in contact preview mode? Did you try with disabled all plugins?

**Comment by rc-pl** [comment]
Well... I deleted previous contacts and now I can't reproduce this issue anymore.
