### ISSUE TITLE
"Open message in new window" issue

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#6659]
When I open a message in new window by clicking option no. 1 shown on below image - it works correctly.
When I use option no. 2 - message is opened with side menu, which shouldn't be visible.
![obraz](https://user-images.githubusercontent.com/24810145/53745825-16d10f80-3ea0-11e9-83cf-278ad94e3e83.png)

**Comment by alecpl** [comment]
This was always this way, but indeed looks inconsistent. It's because 1. uses 'extwin' command, and 2. uses 'open' command. I think we should fix that.

**Comment by alecpl** [comment]
Fixed.
