### ISSUE TITLE
Elastic: Close search options on Enter key press in quick-search input

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#6660]
Messages search can be executed by either clicking on "Search" button or pressing enter key on the keyboard. First option works great, however latter option doesn't close search dialog, thus additional click is needed to view search results. Can you please make it so that pressing enter key also closes search dialog?
![obraz](https://user-images.githubusercontent.com/24810145/53750606-851acf80-3eaa-11e9-9d4e-6baa1c9e79cd.png)

**Comment by alecpl** [comment]
Fixed.
