### ISSUE TITLE
Move contacts from automatically collected to personal address not work after upgrade to 1.4 rc1

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#6661]
After updating from 1.3.8 to 1.4 rc1, it is impossible to move contacts between groups of contacts, particularly those created automatically using the automatic_addressbook plugin.

It is also not possible to create or eliminate groups of contacts in the elastic skin. In Larry's skin, you can create groups, but do not move contacts between groups.

**Comment by alecpl** [comment]
Works for me without the plugin, so it's most likely a plugin issue. This is not a core plugin. You should contact the plugin author about the issue.
