### ISSUE TITLE
Auto Logout

### ISSUE THREAD

**Issue by MIHIN-Shared-Services** [roundcube/roundcubemail#6663]
Has anyone found a way to log users out after 10 minutes of inactivity?

**Comment by CptTZ** [comment]
See #4346

**Comment by MIHIN-Shared-Services** [comment]
I tried this but its not working for me.  Although I don't have a main.inc.php I only have the default.inc.php but I put the lines in that file. Does that make a difference?

**Comment by alecpl** [comment]
This is not really supported scenario. You could try setting session_lifetime=0 (Roundcube) and session.gc_maxlifetime=3600 (PHP), but I'm not sure it's gonna work. Also don't forget users have refresh_interval option which would need to be disabled.

**Comment by rfjakob** [comment]
Is there a plugin or something to do that? ( I tried searching plugins.roundcube.net but did not see any hits for "inactivity", "logout")
