### ISSUE TITLE
Elastic: From headers shows '$to' (instead of the from address) when language set to Dutch

### ISSUE THREAD

**Issue by basdds** [roundcube/roundcubemail#6665]
When using the elastic theme in 1.4rc, the From: header in the preview pane (and in full screen message view) shows a '$to' instead of the message from address.  

This **only** seems to happen when the roundcube language is set to Dutch. (nl_NL) 

![from-to-nl](https://user-images.githubusercontent.com/18537210/53989125-902d6400-4125-11e9-836c-5d2d8901b1e9.png)

This happens with **all** the messages in my mailbox.

Compare with roundcube in English:

![from-in-english-ok](https://user-images.githubusercontent.com/18537210/53989177-b18e5000-4125-11e9-8bee-b85f84f7e6cb.png)

In German: 

![from-in-german-ok](https://user-images.githubusercontent.com/18537210/53989498-66c10800-4126-11e9-8ade-2c1e58b3ab07.png)

Other themes in Dutch don't have this issue and display the whole From: header just fine. 

Tested on Firefox (linux), Firefox for android and Chromium. (for linux)

**Comment by basdds** [comment]
When looking at ./program/localization/nl_NL/labels.inc :

![terminal](https://user-images.githubusercontent.com/18537210/53990228-15197d00-4128-11e9-834a-68815785426e.png)

Probably some character encoding issue?

**Comment by basdds** [comment]
> When looking at ./program/localization/nl_NL/labels.inc :
> 
> ![terminal](https://user-images.githubusercontent.com/18537210/53990228-15197d00-4128-11e9-834a-68815785426e.png)
> 
> Probably some character encoding issue?

Modifying ./program/localization/nl_NL/labels.inc does not solve the issue for me. Maybe i'm missing a step?

**Comment by basdds** [comment]
Found it. :-)   line 211 in ./program/localization/nl_NL/labels.inc says:  

`$labels['shortheaderfrom'] = 'Van $to op $date';`

Which should be:
 
`$labels['shortheaderfrom'] = 'Van $from op $date';`

Since I'm not a developer on rouncube, could this be passed along to the nl_NL language maintainer?

Thanx!

**Comment by alecpl** [comment]
Fixed in Transifex.
