### ISSUE TITLE
Locale zh-HK and zh-MO should be mapped to zh-TW

### ISSUE THREAD

**Issue by alvinhochun** [roundcube/roundcubemail#6666]
People in Hong Kong and Macau uses Traditional Chinese. Though there are slight variance in word usage among these three regions, simply mapping to zh-TW is good enough for now. (Though I would honestly wish that Cantonese localization would become a reality.)

From what I can tell this should be a minor change of simply editing `program/localization/index.inc` to have `$rcube_language_aliases` map `hk`, `mo`, `zh_HK` and `zh_MO` to `zh_TW`.

**Comment by alecpl** [comment]
You can start these localizations on https://www.transifex.com/roundcube/roundcube-webmail

I don't think `hk` and `mo` are valid aliases. I guess, we can add `zh_HK` and `zh_MO`.

**Comment by alvinhochun** [comment]
> I don't think `hk` and `mo` are valid aliases.

Oh, I thought they would be since `cn` and `tw` are in the list.

> You can start these localizations on https://www.transifex.com/roundcube/roundcube-webmail

Maybe in the future... one can only hope

**Comment by johnwmail** [comment]
Can't find the language you want? Please perform a request language action before joining project translation. 

Please add zh_HK locale, thanks.
