### ISSUE TITLE
better description for contact import especially as csv file

### ISSUE THREAD

**Issue by sebastian-schmid** [roundcube/roundcubemail#6668]
# User Story

As a User of Roundcube I would like to have a better description how my CSV file must look like to get my contacts successfully imported.

# Detail Information

On the Contacts -> Import Page is stated that CSV and vCard Format is accepted to import contacts.

Importing one or more contacts in a vCard formatted file works as expected ✅ 

But it took me a few tries and some searching on the internet to get my CSV file imported with all information I wanted.

So I would like to see that information on the import page.

At least it should contain the following fields as a little sample:
* first_name (string, UTF-8?)
* last_name (string, UTF-8?)
* birthday (format? string? datetime?)
* email (string, UTF-8?)

optional:
* mobile_phone (string, UTF-8?)
* home_phone (string, UTF-8?)
* home_street (string, UTF-8?)
* home_city (string, UTF-8?)
* home_state (string, UTF-8?)
* company (string, UTF-8?)
* web_page (string, UTF-8?)
* group (string, UTF-8?) this will add the contacts to existing roundcube addressbooks or adds the addressbook in roundcube if selected

maybe it will end in a complete table of all possible fields, cause I think non technical users are not able to get it from the php file it self in case they need more than I picked above.

# sources

* https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_csv2vcard.php
* https://github.com/roundcube/roundcubemail/blob/master/program/localization/en_US/csv2vcard.inc
* https://stackoverflow.com/questions/20469399/importing-address-book-in-roundcube-doesnt-do-anything

**Comment by SLynnBen** [comment]
Where and how do I put the group identifier in the csv to import or somewhere else?? So wish there was a step by step tutorial or video for this. When I import the csv with correct column headers, it imports only to the main address book. Then I have to drag/drop each contact to the group.

**Comment by sebastian-schmid** [comment]
I think you need to add "groups" as a header. The first line of your csv file has to be the header line. Followed by all your data you want to import.

csv file example with header line and one data line, just add more data lines to import more than one contact.
```
"first_name","last_name","display_name","email","group"
"Hans","Meier","Hans Meier (private)","hans.meier@somedomain.de","awesometeam"
```

**Comment by kentchee** [comment]
> 
> # User Story
> 
> As a User of Roundcube I would like to have a better description how my CSV file must look like to get my contacts successfully imported.
> # Detail Information
> 
> On the Contacts -> Import Page is stated that CSV and vCard Format is accepted to import contacts.
> 
> Importing one or more contacts in a vCard formatted file works as expected ✅
> 
> But it took me a few tries and some searching on the internet to get my CSV file imported with all information I wanted.
> 
> So I would like to see that information on the import page.
> 
> At least it should contain the following fields as a little sample:
> 
>     * first_name (string, UTF-8?)
> 
>     * last_name (string, UTF-8?)
> 
>     * birthday (format? string? datetime?)
> 
>     * email (string, UTF-8?)
> 
> 
> optional:
> 
>     * mobile_phone (string, UTF-8?)
> 
>     * home_phone (string, UTF-8?)
> 
>     * home_street (string, UTF-8?)
> 
>     * home_city (string, UTF-8?)
> 
>     * home_state (string, UTF-8?)
> 
>     * company (string, UTF-8?)
> 
>     * web_page (string, UTF-8?)
> 
>     * group (string, UTF-8?) this will add the contacts to existing roundcube addressbooks or adds the addressbook in roundcube if selected
> 
> 
> maybe it will end in a complete table of all possible fields, cause I think non technical users are not able to get it from the php file it self in case they need more than I picked above.
> # sources
> 
>     * https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_csv2vcard.php
> 
>     * https://github.com/roundcube/roundcubemail/blob/master/program/localization/en_US/csv2vcard.inc
> 
>     * https://stackoverflow.com/questions/20469399/importing-address-book-in-roundcube-doesnt-do-anything

Hi Sebastian,

I think I'm using the correct but still couldn't uploaded to Roundcube Contacts.

Can you please advise?


[HQ DEBTOR.zip](https://github.com/roundcube/roundcubemail/files/4217487/HQ.DEBTOR.zip)

**Comment by sebastian-schmid** [comment]
@kentchee I think your file is missing the quotation marks (").

should look like this:
```
"first_name","last_name","display_name","email"
"","","SOME TRADING","some.mail@mailprovider.com"
```
I also recommend to delete your uploaded file as it looks like valid data which may should not be public available on github?

**Comment by kentchee** [comment]
> 
> 
> @kentchee I think your file is missing the quotation marks (").
> 
> should look like this:
> 
> ```
> "first_name","last_name","display_name","email"
> "","","SOME TRADING","some.mail@mailprovider.com"
> ```
> 
> I also recommend to delete your uploaded file as it looks like valid data which may should not be public available on github?

Thanks Sebastian.

But how can I "save as" csv file from excel work sheet with the quotation marks?

I have deleted the uploaded file.

**Comment by sebastian-schmid** [comment]
I think the following steps should do it:
* Select all Cells (with content)
* Go to Format –> Cells –> Custom
* Copy/Paste the following into the Type field: \”@\”
* Click “okay”
* Then export it as CSV file

from https://lenashore.com/2012/04/how-to-add-quotes-to-your-cells-in-excel-automatically/

If that is not working maybe this one can help: https://stackoverflow.com/questions/25237847/adding-double-quote-delimiters-into-csv-file/25238157

**Comment by alecpl** [comment]
There's #7045 in draft.

**Comment by alecpl** [comment]
#7045 has been merged into master. If you still think the documentation should be improved, create a wiki page.

**Comment by DoobleD** [comment]
@alecpl #7045 was merged in master in last October and i'm running Roundcube 1.4.11 which dates from last February, yet I don't see those changes in Roundcube 1.4.11. I'm probably missing something obvious here?
