### ISSUE TITLE
forgotten Attachment plugin

### ISSUE THREAD

**Issue by piochon** [roundcube/roundcubemail#6670]
Hi, 

I am testing the new RC1 version of roundcube and it is amazing ! 
I have activated the plugin forgotten attachment and it works very great when we write 'pièce jointe' or 'piece jointe' in French. But we also usually say 'PJ' and Roundcube doesn't recognize it. 
Is it possible to add it on the new version ? 

Thanks !

**Comment by alecpl** [comment]
Here's the current list of keywords for French:
```
$messages['keywords'] = "pièce jointe,fichier,joindre,joins,joint,attaché,inclus,ci-inclus,CV, lettre d’accompagnement";
```
This list is controlled via localization files, which means you have to use our Transifex service to update it.

**Comment by piochon** [comment]
I don't know how to do it, can you please just add 'PJ' ? 
Thanks
