### ISSUE TITLE
Error while opening specific email

### ISSUE THREAD

**Issue by deepakmhatre** [roundcube/roundcubemail#6673]
We have one application which sends quarantine report when we try to open same in Roundcube we are getting error as attached 
This started after updating Cpanel to Ver 78.0.16 prior to that we was using CPanel  v76.0.20  in that it was opening without any issue
[source.txt](https://github.com/roundcube/roundcubemail/files/2956352/source.txt)
![Screenshot_1](https://user-images.githubusercontent.com/48475984/54193372-ea407780-44df-11e9-8614-fa07f6c31cb8.jpg)

After CPanel upgrade this issue has started, we are able to open same email in Horde webmail client of server

Attached pls. find the same message which I could read in outook

**Comment by alecpl** [comment]
What Roundcube version? What error in Roundcube log?

**Comment by deepakmhatre** [comment]
Hi

Roundcube version is 1.3.7-1 which is shipped with CPanel  v78.0.16

root@cp [~]# cat /var/cpanel/roundcube/version
1.3.7-1.cp1176
root@cp [~]#

Where do i find roundcube logs?

/var/cpanel/roundcube/logs/errors shows updated till 10th March only


Regards,

Deepak Mhatre

**Comment by alecpl** [comment]
I guess "Fix so fallback from BINARY to BODY FETCH is used also on [PARSE] errors in dovecot 2.3 (#6383)" from 1.3.8 might be what do you need. A workaround is to set `$config['imap_disabled_caps'] = array('BINARY');` in Roundcube config.

**Comment by deepakmhatre** [comment]
Hi

My Dovecot verson is 2.3.4.1

So you mean to say problem with Dovecot not with roundcube?

Is there any fix going to come for same?

Many of our clients are hosted on shared hosting so hosting provider may
not change their default configuration



Regards,

Deepak Mhatre

**Comment by alecpl** [comment]
That is only a guess. I don't know this is THE issue you have. Dovecot 2.3 returns different error code when can't decode the message body. So, it is not really a bug in dovecot, but a behavior change. You need a change in Roundcube to keep up with proper handling of the new error code or disable BINARY extension use. I think you could disable the extension on dovecot side as well.

**Comment by deepakmhatre** [comment]
Where is is roundcube configuration file located in Cpanel?



Regards,

Deepak Mhatre

**Comment by alecpl** [comment]
Did you manage to solve the issue? Can you confirm that it is the one I pointed to?

**Comment by deepakmhatre** [comment]
I have left issue like that it seem folder permission issue post migration



Regards,

Deepak Mhatre
