### ISSUE TITLE
How can i get with roundcube api header like X-Spam-Flag or X-Spam-Status?

### ISSUE THREAD

**Issue by 6ec123321** [roundcube/roundcubemail#6676]
How can i get with roundcube api header like X-Spam-Flag or X-Spam-Status?
`
[12-Mar-2019 22:01:03 +0400]: <f4m0n40m> array (
  70 =>
  rcube_message_header::__set_state(array(
     'id' => 1,
     'uid' => 70,
     'subject' => '=?UTF-8?B?0KMg0YHQsNC50YLQsCB3d3cucGhwY2hhaW4ucnUg0Lg=?= =?UTF-8?B?0LfQvNC10L3QuNC70L7RgdGMINCz0Ls=?= =?UTF-8?B?0LDQstC90L7QtSDQt9C10YDQutCw0LvQvg==?=',
     'from' => '"Yandex.Webmaster" <devnull@yandex-team.ru>',
     'to' => '"artur@phpchain.ru" <artur@phpchain.ru>',
     'cc' => NULL,
     'replyto' => NULL,
     'in_reply_to' => NULL,
     'date' => 'Fri, 1 Feb 2019 03:36:51 +0300 (MSK)',
     'messageID' => 'mid:1',
     'size' => 10973,
     'encoding' => NULL,
     'charset' => NULL,
     'ctype' => 'multipart/mixed',
     'timestamp' => 1548981411,
     'bodystructure' => NULL,
     'internaldate' => '01-Feb-2019 00:36:52 +0000',
     'references' => NULL,
     'priority' => NULL,
     'mdn_to' => NULL,
     'folder' => '&BCEEPwQwBDw-'
`
I need a specific header, but it is not in the list of headers for a particular letter.

**Comment by 6ec123321** [comment]
https://github.com/roundcube/roundcubemail/issues/773

**Comment by thomascube** [comment]
I assume you want this header in a custom plugin of yours? Additional headers need to be specifally requested with the message listing from IMAP. See the [storage_init](/roundcube/roundcubemail/wiki/Plugin-Hooks#storage_init) plugin hook.

**Comment by thomascube** [comment]
Here's an example: [show_additional_headers plugin](https://github.com/roundcube/roundcubemail/blob/34dc62b9e9632cf70254ca6b0d3f8e5921c6e1c0/plugins/show_additional_headers/show_additional_headers.php)

**Comment by 6ec123321** [comment]
You are right, i will try.

**Comment by 6ec123321** [comment]
Big thanks!
If we add:
```
function init(){
    $rcmail = rcmail::get_instance();
    $this->rc = &$rcmail;
    $this->spam_headers = $this->rc->config->get('spam_headers','X-Spam-Flag');
    
    if($this->rc->task == 'mail' && !isset($_GET["_q"])){
      $this->add_hook('storage_init', array($this, 'storage_init'));
      ...
    }
 function storage_init($p)
  {
    if ($add_headers = (array)$this->rc->config->get('spam_headers', array()))
      $p['fetch_headers'] = trim($p['fetch_headers'].' ' . strtoupper(join(' ', $add_headers)));
    return $p;
  }
```
Then we get additional header value like:
```
function plugin_get_spam_flag($message){
  return $message->others[strtolower('X-Spam-Flag')]
}
```
