### ISSUE TITLE
Do not show Search dialog when pre-selecting searchonly addressbook

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6679]
If you configure LDAP addressbook with `searchonly=true` and it is the default one, going to Contacts UI will display automatically the Advanced Search dialog.

I think this should not happen, at least only on user request. It is there since e2a8b4dd6d6d.

Imo, when auto-selecting the addressbook when user enters Contacts UI it should not happen. @thomascube do you agree?

**Comment by urusha** [comment]
Dialog also appears after removing all typed text from simple search by pressing `Reset search` button if ldap addressbook is the first (`address_book_type` is `''`).

**Comment by alecpl** [comment]
The reason why the dialog appears is because the searchonly addressbook is selected. And we select automatically default addressbook (or the first if unset). It does not matter it's first or last.

That being said, search reset might be another case where we should not display the dialog.

**Comment by alecpl** [comment]
Fixed. The dialog will be never displayed automatically. I also rephrased the notice message.
