### ISSUE TITLE
vacation plugin is not working with roundcube 1.4RC1

### ISSUE THREAD

**Issue by studiowena** [roundcube/roundcubemail#6682]
Hi,

I have update roundcube to 1.4RC1 and when going to settings and vacation plugin it show me message with

FILE NOT FOUND
the request resource was not found
failed request: www.domain.com/?_task=settings&_action=plugin.vacation

is this problem with vacation plugin or roundcube or configuration? It was working with 1.3.7

**Comment by alecpl** [comment]
Are you using Elastic skin? I guess it's not supported by the plugin. Anyway, we do not support the plugin here.

**Comment by studiowena** [comment]
yes elastic skin and larry have the same issue
