### ISSUE TITLE
Sieve plugin does not use \r\n in multi-line text literals

### ISSUE THREAD

**Issue by ScottPeterJohnson** [roundcube/roundcubemail#6686]
Hello!
I'm using Roundcube with JSieve, which (correctly) fails to parse some Sieve scripts as saved by Roundcube. They generate "\n", when they should generate "\r\n". This specifically fails when saving vacation messages over one line in length.

Here is the location that needs changing, as far as I can tell. It might be more spec-compliant to change other uses of \n in this file too.
https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/lib/Roundcube/rcube_sieve_script.php#L1205
Please see section 2.4.2 of the Sieve RFC:
https://tools.ietf.org/html/rfc5228#section-2.4.2

```
For entering larger amounts of text, such as an email message, a
   multi-line form is allowed.  It starts with the keyword "text:",
   followed by a CRLF, and ends with the sequence of a CRLF, a single
   period, and another CRLF.
```

**Comment by alecpl** [comment]
I don't know how I missed that. Indeed \n is not allowed alone and should be always \r\n when used as a "separator whitespace". Not only for multiline text syntax.

This probably does not apply to the multiline text value itself. At least I didn't found anything that would require \r\n in there.

**Comment by alecpl** [comment]
Fixed.
