### ISSUE TITLE
Adjustable Columns in Elastic

### ISSUE THREAD

**Issue by kabigears** [roundcube/roundcubemail#6687]
Elastic on small screens is problematic. There is a constant shifting to view content. This is a show stopper. How about making the column widths adjustable like in larry theme.

**Comment by alecpl** [comment]
What do you mean problematic and what screen size are you talking about? We do not plan implementing the old two-column+preview mode.

**Comment by kabigears** [comment]
Mini laptop has 1024x768. There 3 column layout is fine, except the third column only shows some of the message content. So the horizontal slider must be used to view the third column. If the columns were adjustable this might be avoidable.

**Comment by alecpl** [comment]
In 1200px the preview is ~600px wide. In 1024px the preview is ~650px wide. In 1366px the preview is ~700px wide. Imo, these are not that small values. Most email messages should look ok with this width.

We'll consider implementing columns resizing in future if this becomes a real problem. For now it is a wontfix.

**Comment by kitserve** [comment]
I'd like to request that this issue be reopened. I usually use my monitor in portrait mode, and the column width detection is very problematic in Elastic. In particular, the subject column is impossible to read. I also notice that the icons in the top right are way off the right off the viewable area, even though there's plenty of space for them to float above the mail list pane. Screenshot attached highlighting these two issues.
![Screenshot_2022-02-28_11-27-49](https://user-images.githubusercontent.com/7717488/155976503-0379dcd9-1343-451c-bae4-7cba656937e7.png)
