### ISSUE TITLE
Contacts Not Displayed if Address Book Entries >= addressbook_pagesize Variable

### ISSUE THREAD

**Issue by natcoruss** [roundcube/roundcubemail#6689]
If a user's address book contains the same number of or more entries than the addressbook_pagesize variable defined in defaults.inc.php, instead of the address book being paged properly, no contacts will be displayed. This is Roundcube version 1.2.3+dfsg.1-4+deb9u3 running on a Debian 9 system.

**Comment by alecpl** [comment]
I'm unable to reproduce using Roundcube 1.4-rc1. 1.2 is not supported anymore.

Is it built-in sql addressbook, ldap addressbook, or some plugin? Disable all plugins and try again. Any errors in Roundcube logs? Any errors in browser console?

**Comment by alecpl** [comment]
No feedback.

**Comment by xhantu** [comment]
I have encountered the same issue and found the source of the problem and a solution:

**Comment by MHellmund** [comment]
Please re-open. 
I can confirm the bug. After updating server fron debian9 to debian10, thereby updating mariadb,
users with large addressbooks saw an empty addressbook.

I can confirm that xhantu's patch above solved the problem.

**Comment by alecpl** [comment]
Duplicate of #5774.

**Comment by quinncomendant** [comment]
I'm seeing the same behavior on `roundcubemail-1.1.12-2.el7.noarch`. 

(Some search terms to help people find this issue: Missing address book if `rows per page` option is less than the total number of contacts, address book disappears, missing contacts.)
