### ISSUE TITLE
Classic skin - poor rendering

### ISSUE THREAD

**Issue by zden2ksobotka** [roundcube/roundcubemail#6690]
Hello,
In Roundcube with classic skin, is the third panel poorly rendered. See picture. Roundcube is installed by composer in version 1.3.8.
![roundcube](https://user-images.githubusercontent.com/48833683/54831953-9beb5f80-4cbb-11e9-9c08-55da6e7f38d3.png)
The problem occurs in several browsers, in Fifefox 60.4.0esr (64-bit) on Google Chrome and Chromium also.

Thanks, Z.

**Comment by alecpl** [comment]
I'm unable to reproduce in Chromium 73.0.3683.75 nor Firefox 66.0.

treecol.css is not part of Roundcube. So, I guess the issue is caused by some plugin.

**Comment by zden2ksobotka** [comment]
Hello, Thanks for reply. You are right, when I disable treecol plugin it looks fine. So it is definitely caused by this plugin. Strange, with other skins, such as "Larry" skin it's no problem.
Anyway, if you're still interested, I have an "Ansible role" which can help to reproduce it.

Thanks. Z.

[roundcube.tar.gz](https://github.com/roundcube/roundcubemail/files/3002462/roundcube.tar.gz)

**Comment by alecpl** [comment]
You don't really need this plugin with 1.3.8. It has three column view built-in.

**Comment by zden2ksobotka** [comment]
Ah, ok, Thanks.
