### ISSUE TITLE
Forbidden error after updating roundcube to version 1.3.8

### ISSUE THREAD

**Issue by JintoAntony** [roundcube/roundcubemail#6693]
After updating roundcube to version 1.3.8, I am getting this error : You don't have permission to access /webmail/program/js/jquery.min.js on this server.

GET /webmail/program/js/jquery.min.js?s=1553261247 net::ERR_ABORTED 403 (Forbidden)
GET /webmail/program/js/common.min.js?s=1540293174 net::ERR_ABORTED 403 (Forbidden)
GET /webmail/program/js/jstz.min.js?s=1553261247 net::ERR_ABORTED 403 (Forbidden)
GET /webmail/program/js/app.min.js?s=1540293174 net::ERR_ABORTED 403 (Forbidden)
/webmail/program/js/jstz.min.js?s=1553261247 net::ERR_ABORTED 403 (Forbidden)
 Uncaught ReferenceError: rcube_webmail is not defined
    at (index):38
(anonymous) @ (index):38
jquery-ui.min.js?s=1540293173:6 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.min.js?s=1540293173:6
    at jquery-ui.min.js?s=1540293173:6
(anonymous) @ jquery-ui.min.js?s=1540293173:6
(anonymous) @ jquery-ui.min.js?s=1540293173:6
(index):98 Uncaught ReferenceError: jQuery is not defined
    at (index):98

**Comment by alecpl** [comment]
Looks like some files are missing or not accessible to the web server. Check if files exist and make sure they are readable by the php/http process. Nothing we can help here.

**Comment by edthenet** [comment]
It is to easy just to close this. I have the same issue
