### ISSUE TITLE
install-jsdeps.sh fails to get TinyMCE

### ISSUE THREAD

**Issue by JintoAntony** [roundcube/roundcubemail#6694]
It shows error when trying to update tinymce

Installing jQuery...
Wrote file /var/lib/roundcube/program/js/jquery.min.js
Done.

Installing jsTimezoneDetect...
Wrote file /var/lib/roundcube/program/js/jstz.min.js
Done.

Installing PublicKey.js...
Wrote file /var/lib/roundcube/program/js/publickey.js
Done.

Installing tinymce...
Fetching http://download.ephox.com/tinymce/community/tinymce_4.5.8.zip
ERROR: Incorrect sha1 sum of /var/lib/roundcube/temp/js_cache/tinymce-4.5.8.zip. Expected: 08b0757264adb86066940bbafb7aa9ec0c7c6685, got:

**Comment by alecpl** [comment]
Looks like that URL is now different and the page redirects to new location. The installation script uses curl without `-L` argument, so it does not use redirect.

So, there are two ways to fix this. I think we'll just update the download URL in jsdeps.json file. ^The new URL is https://download.tiny.cloud/tinymce/community/tinymce_4.5.8.zip.

**Comment by alecpl** [comment]
Fixed.
