### ISSUE TITLE
Roundcube reinstallation issue

### ISSUE THREAD

**Issue by JintoAntony** [roundcube/roundcubemail#6695]
I am trying to reinstall the roundcube again on my server it show the error like the following. How can I reset the virtual host config for roundcube ? I believe its just a permission issue. But, I can't figure this out. 

GET https://hyracorp.com/webmail/program/js/jstz.min.js?s=1553508884 net::ERR_ABORTED 403 (Forbidden)
hyracorp.com/:14 GET https://hyracorp.com/webmail/program/js/jquery.min.js?s=1553508884 net::ERR_ABORTED 403 (Forbidden)
hyracorp.com/:16 GET https://hyracorp.com/webmail/program/js/app.min.js?s=1540293174 net::ERR_ABORTED 403 (Forbidden)
hyracorp.com/:15 GET https://hyracorp.com/webmail/program/js/common.min.js?s=1540293174 net::ERR_ABORTED 403 (Forbidden)
hyracorp.com/:16 GET https://hyracorp.com/webmail/program/js/app.min.js?s=1540293174 net::ERR_ABORTED 403 (Forbidden)
?_task=login:17 GET https://hyracorp.com/webmail/program/js/jstz.min.js?s=1553508884 net::ERR_ABORTED 403 (Forbidden)
?_task=login:38 Uncaught ReferenceError: rcube_webmail is not defined
    at ?_task=login:38
(anonymous) @ ?_task=login:38
jquery-ui.min.js?s=1540293173:6 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui.min.js?s=1540293173:6
    at jquery-ui.min.js?s=1540293173:6
(anonymous) @ jquery-ui.min.js?s=1540293173:6
(anonymous) @ jquery-ui.min.js?s=1540293173:6
?_task=login:99 Uncaught ReferenceError: jQuery is not defined
    at ?_task=login:99

**Comment by alecpl** [comment]
This is not Roundcube issue. Setting up virtual hosts and http configuration overall is out of scope here. Are these javascript files installed at all?

**Comment by JintoAntony** [comment]
I will explain. I am using Debian 8 OS. Roundcube was working fine. Then I upgraded to ver 1.3.8. Then this issue caused. Roundcube-apache configuration is found in /etc/apache2/conf.d folder. After the upgrade, do I have to enable this config again ? Javascript files are installed and exist. This is a forbidden issue. But, I haven't changed any apache config.

**Comment by alecpl** [comment]
If you installed from distribution packages then it's even more not our issue. Ask Debian.

**Comment by JintoAntony** [comment]
No. Not from distribution package. From the website.
