### ISSUE TITLE
Autologin / logout CSRF

### ISSUE THREAD

**Issue by skanadian** [roundcube/roundcubemail#6696]
I am using the autologin plugin to quickly switch between mailboxes.  I had it implemented in 0.4 but now we are testing 1.4-RC1.

I would call fqdn/?_task=logout&_action=logout&_autologin=1 in the URL as this would log any previous sessions out before logging in a new session.

When testing this on 1.4-RC1, I'm met with a CSRF error when using _task=logout.  The previous mailbox is not logged out and the session continues with the old mailbox's INBOX instead of the new desired session.

Is there any way to switch between users utilizing autologin without requiring the previous user to logout, or disable the CSRF checking when calling task=logout?

**Comment by alecpl** [comment]
From a plugin code you should be able to do this.
