### ISSUE TITLE
"v1" Prefix in Every Class and ID

### ISSUE THREAD

**Issue by andersonnnunes** [roundcube/roundcubemail#6702]
I had been using RC v1.3.4 and just updated to v1.4-rc1.
I use some custom CSS injected by the browser and noticed it stopped working.
Investigating, I found that now the HTML of emails is being changed, with "v1" being prefixed to every class and id - of the original HTML email.

Now I either have to update my custom CSS or change RC to remove that.
Tried looking at the commits and sources, but failed to locate why or how this is being done.

Is this prefix really needed? Is it going to change (to "v2", "v3", ...)? Can I remove it? Link to the relevant source, please?

**Comment by alecpl** [comment]
It is added so webmail styles do not interfere with email styles and vice-versa. The prefix is not constant. It can change depending on the mail message structure (it is a message part number).
