### ISSUE TITLE
disable managesieve redirect action

### ISSUE THREAD

**Issue by RabbitDuck** [roundcube/roundcubemail#6703]
How to disable the "Redirect message to" action in managesieve plugin?

Is it possible to use the '%h' variable in the $config['managesieve_domains'] parameter? 
We want to limit user to redirect email to their login domain only.

Thanks!

**Comment by alecpl** [comment]
Disabling redirect action is not possible. It is also not possible to use variables in `managesieve_domains`.

**Comment by ClayRabbit** [comment]
Fortunately, the variable $ _SESSION ['username'] is available, so we can extract the domain from it with something like that:
$config['managesieve_domains']=($_SESSION['username']?(strstr($_SESSION['username'],'@')?substr($_SESSION['username'],strpos($_SESSION['username'],'@')+1):php_uname('n')):array());
