### ISSUE TITLE
<select> tapping in Google Chrome with RC elastic skin

### ISSUE THREAD

**Issue by drlight17** [roundcube/roundcubemail#6705]
Nothing happens when tap on some html selects (for example to change language in main settings) when using Google Chrome on mobile device. The same happens when doing that in Chrome DevTools in mobile device view. There is no errors in console. Current version of Google Chrome on Android device is 73.0.3683.90. Desktop version is 73.0.3683.86.
Roundcube version is 1.4-RC1. Elastic skin version is from this Roundcube version.
No problems when using desktop version of elastic skin.

**Comment by alecpl** [comment]
Looks like the same problem with focus as on iOS. However, it works on a page that is not an iframe, it's a little bit better. There's hope ;)

We might need to disable pretty-selects also on Android and use normal selects there.

**Comment by alecpl** [comment]
This is strange. Some selects in iframes work and some don't. It looks like while `click` event is not fired on the select element itself it is fired on the document. This causes the menu to disappear immediately (it's so fast that you can even see it).

**Comment by drlight17** [comment]
> This is strange. Some selects in iframes work and some don't. It looks like while `click` event is not fired on the select element itself it is fired on the document. This causes the menu to disappear immediately (it's so fast that you can even see it).

Thanks for fast reply!  Any suggestions how to fix it?

**Comment by alecpl** [comment]
I do not have a solution yet. Disabling pretty-select on Chrome-mobile can be done with:
```diff
--- a/skins/elastic/ui.js
+++ b/skins/elastic/ui.js
@@ -3384,7 +3384,7 @@ function rcube_elastic_ui()
     function pretty_select(select)
     {
         // iPhone is not supported yet (problem with browser dropdown on focus)
-        if (bw.iphone || bw.ipad) {
+        if (bw.iphone || bw.ipad || (bw.mobile && bw.chrome)) {
             return;
         }
 
```

**Comment by drlight17** [comment]
Ok, I'll do this temporary for my installation.

**Comment by alecpl** [comment]
Fixed.
