### ISSUE TITLE
Folder settings vertical scrolling doesn't work on touch

### ISSUE THREAD

**Issue by drlight17** [roundcube/roundcubemail#6706]
Settings->Folders vertical scroll doesn't work on touch. Mouse scroll works perfectly.
Roundcube version 1.4-RC1 with any standard skin.

**Comment by alecpl** [comment]
Confirmed using Chrome in mobile mode and Elastic skin.

**Comment by alecpl** [comment]
Fixed in Elastic. For other skins it is wontfix as they do not really support touch devices.
