### ISSUE TITLE
Roundcube does not display embeded images correctly

### ISSUE THREAD

**Issue by zden2ksobotka** [roundcube/roundcubemail#6708]
Hello,
Roundcube badly displays embedded images, thunderbird displays them correctly. Tested in Roundcube 1.4-rc1.

Thanks. Z.

![cidmail](https://user-images.githubusercontent.com/48833683/55411078-43427f00-5565-11e9-974e-9f93143f7124.png)

[problematic_attachement.zip](https://github.com/roundcube/roundcubemail/files/3034449/problematic_attachement.zip)

**Comment by alecpl** [comment]
Works for me. It looks like your system has problem with attachment type detection. Verify `mime_magic` setting in config. Try with NULL or a verified path to a magic file.

**Comment by zden2ksobotka** [comment]
Thank you, fixed.
