### ISSUE TITLE
Elastic: Dark mode

### ISSUE THREAD

**Issue by chris-kruining** [roundcube/roundcubemail#6709]
Would love to have a toggle to swap the color palette of the new elastic skin to a 'dark mode'. I technically could ask the server maintainer to change the .less files, but then I imagine the change would be for everybody, which is undesirable.

**Comment by alecpl** [comment]
There's some work on this front in #6691.

**Comment by chris-kruining** [comment]
awesome!

**Comment by thrdroom** [comment]
Why was this removed from the 1.5-beta milestone? Is there a new milestone for this feature/theme?

**Comment by mcnesium** [comment]
As a workaround to this we can add some tiny CSS snippet to the stylesheet, that just inverts the colors of everything, and then re-inverts images and iframes (the actual mail content).

Since I run RC in Docker, I volume-mount the stylesheet into the container. Here is the script I run after each update:

    #!/usr/bin/env bash
    
    CSS="
    @media (prefers-color-scheme: dark) {
        body img,
        body iframe,
        body {
            filter: invert(1) hue-rotate(180deg);
        }
    }
    "

    # copy possibly updated stylesheet
    docker cp roundcube_app:/var/www/html/skins/elastic/styles/styles.css styles.css

    # append the CSS snipped to the file
    echo "$CSS" | xargs >> styles.css

    # restart container to apply changes to the mounted stylesheet
    docker-compose restart app

It then looks like this (minus the blurryness):

![Screenshot from 2020-06-05 11-31-35](https://user-images.githubusercontent.com/476060/83861778-50d33600-a721-11ea-87ba-25d500fb78c3.png)

**Comment by Skorpion** [comment]
Check it: [Roundcube Elastic Dark](https://github.com/Skorpion/roundcube-elastic-dark), required Stylus

**Comment by thrdroom** [comment]
> Check it: [Roundcube Elastic Dark](https://github.com/Skorpion/roundcube-elastic-dark), required Stylus

Please port your theme to roundcube as a native theme. Browser-Extensions like Stylus are just a workaround and not a proper solution. Thanks

**Comment by thrdroom** [comment]
@alecpl Why was this removed from the 1.5-beta milestone? Is there a new milestone for this feature/theme? Why was this issue closed when there is still no dark theme for elastic? tia

**Comment by alecpl** [comment]
The ticket was closed by his author. I guess we can re-open.

**Comment by alecpl** [comment]
I just pushed the initial implementation to master. Work in progress. https://kolabian.wordpress.com/2020/07/07/elastic-dark-mode/

**Comment by chris-kruining** [comment]
awesome, thanks for your hard work!

**Comment by gianlucagiacometti** [comment]
great job indeed!

**Comment by alecpl** [comment]
I consider this done. If you find any issues create a new ticket(s).

**Comment by Advewave** [comment]
where can i find the option for this? it isn't specified in your blog post and i cannot find it on my own roundcube installation.

**Comment by alecpl** [comment]
@Advewave This hasn't been released yet. The beta version is planned somewhere in the end of 2020.

**Comment by poblabs** [comment]
Downloading the master repo and uploading the skins/elastic initially gave me an error about the deps folder missing, so I merged it with my existing elastic theme folder, yet it doesn't give me the dark menu. Is there a way to activate it?

**Comment by AlphaJack** [comment]
@alecpl Any update on the beta version?

**Comment by alecpl** [comment]
There's a tremendous amount of work needed for PHP8 support, so maybe next month.

**Comment by DoCheckor** [comment]
Can't wait!

**Comment by mkmark** [comment]
> Please port your theme to roundcube as a native theme. Browser extensions like Stylus are just a workaround and not a proper solution. Thanks

[mkmark/elastic-dark](https://github.com/mkmark/elastic-dark)

Here is a personal dark theme built based on an earlier version of the official Elastic theme. Tested on 1.4.6 and 1.4.10 (latest stable 20210131).

**Comment by Offerel** [comment]
One question: Is it possible to auto-enable the dark mode, upon browser request? For example, if a browser switch to night time automatically to dark mode, can this browser request an automatic switch to dark mode for elastic skin?

**Comment by mkmark** [comment]
> One question: Is it possible to auto-enable the dark mode, upon browser request? For example, if a browser switch to night time automatically to dark mode, can this browser request an automatic switch to dark mode for elastic skin?

Yes. See [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by Offerel** [comment]
Currently it seems not to be implemented. At least I tested it with Firefox mobile. If I switch Android and with that Firefox to dark mode, elastic stay with the bright theme. I must switch manually to the dark theme.

**Comment by mcnesium** [comment]
[There is a clue in the layout](https://github.com/roundcube/roundcubemail/blob/4e4ff97832ea6eaf36d7a4a982402e9960ef4288/skins/elastic/templates/includes/layout.html#L33-L39) but it is invoked by javascript. This might lead to unexpected behaviour and leaves the question behind, why it is not baked into the CSS directly.

**Comment by Offerel** [comment]
Yes, it's working fine on all other sites with Firefox Android stable. For example https://arnowelzel.de/automatischer-dark-mode-websites

**Comment by alecpl** [comment]
Please, check with https://github.com/roundcube/roundcubemail/commit/a7b9d76eaa0f7bcdc190a9ea18b0a21b1394f1e3. Delete the cookie first.

**Comment by Offerel** [comment]
At least with this change, dark mode is set equal to system mode, if the browser follows the system setting. Many thx. I have another wish for the mail list view, will open a new request for this.

**Comment by mcnesium** [comment]
@alecpl no offense, just curious: could you explain, why you are using javascript to invoke this instead of [a media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)?

**Comment by alecpl** [comment]
To have it easily available everywhere, e.g. on my desktop browser. Maybe at some point we can remove the button and do it only automatic.

**Comment by AlphaJack** [comment]
Is there a way to enable the dark mode everywhere by default, including the login screen?
