### ISSUE TITLE
1.4 RC1 missing icons on Windows IIS

### ISSUE THREAD

**Issue by mvldebian** [roundcube/roundcubemail#6710]
IIS 7.5 - PHP 7.2.7 x64

all the prerequisites ok in the installer minus the imagemagick
icons missing

![image](https://user-images.githubusercontent.com/25337130/55526312-f648d080-566a-11e9-9be1-53921839aad3.png)

![image](https://user-images.githubusercontent.com/25337130/55526334-0fea1800-566b-11e9-900d-7fd4b2d69e8e.png)

**Comment by alecpl** [comment]
Looks like IIS problem with fonts. Maybe this will help https://www.syncfusion.com/kb/6498/how-to-solve-font-icons-missing-issue-when-host-the-sample-in-iis

**Comment by mvldebian** [comment]
thank you very much
enabled file types

.woff application / font-woff
.woff2 application / font-woff2

and everything worked

**Comment by alecpl** [comment]
I added a note in the INSTALL file.
