### ISSUE TITLE
How to change column date sent date to arrival date 

### ISSUE THREAD

**Issue by naigamo** [roundcube/roundcubemail#6712]
I use roundcubemail on Kolab software but found inbox list column date show "sent date" but I want column date show "arrival date" how to modify or code php  roundcubemail  Thank

**Comment by alecpl** [comment]
There should be "List options..." icon in the list header.

**Comment by naigamo** [comment]
Thank You / Question If we change default sort form sent date to receive date (After change any colume default by sort sent date only) Thank you again
