### ISSUE TITLE
Homebutton or clickable Roundcube logo in elastic skin

### ISSUE THREAD

**Issue by mikch06** [roundcube/roundcubemail#6719]
I miss a home button like the clickable roundcube logo/icon in the top left corner of elastic skin. I think, this would be more intuitive to go back to the inbox.
The skin is great, but i would miss this function.

**Comment by alecpl** [comment]
Imo, no, this is not more intuitive. It maybe had some sense in the old skins where the menus were on the right side of the UI. I think it might be more confusing now where you have menu buttons below the logo. Having two buttons nearby doing the same is not good. And I can imagine customisations that use company logo and want to make a click on it to lead to a company webpage or sth like that.

**Comment by Popyllol** [comment]
Hey Mikch06,
I just had the same wish :-).

Even if it may not be intuitive there is a way to do it easy.
Modify
  /<path to your roundcube skins>/<your skin>/ui.js 
append
$("#logo").attr("onclick", "return rcmail.command('switch-task','mail',this,event)");

And minimize it again:
/<path to your roundcube installstion>/bin/jsshrink.sh /<path to your roundcube skins>/<your skin>/ui.js

This adds the onclick attribute with the right rcmail.command to your logo.
Greetings,
   Lars
