### ISSUE TITLE
Unable to login after upgrading to PHP 7.2 .. Call to undefined function mb_strtolower()

### ISSUE THREAD

**Issue by Oxibug** [roundcube/roundcubemail#6720]
Hi there! 
My Server:
CentOS 7.6
RoundCube 1.3.8
Webmin

Since I upgrade my server to use PHP v7.2 I cannot login and this error [HTTP ERROR 500] appears after press on login button.

I saw the log file in [/.../roundcube/logs/errors] and I noticed this error...

`1 {main}  thrown in /.../roundcube/program/include/rcmail.php on line 593`

`[16-Apr-2019 20:46:39 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function mb_strtolower() in /.../roundcube/program/include/rcmail.php:593`

`Stack trace:
0 /.../roundcube/index.php(121): rcmail->login('EMAIL...', 'Password', 'localhost', true)`

I googled it and found that I should enable [zend.multibyte] in my PHP.ini, Actually I shocked because it was not enabled in the old PHP 7.0, So I went back to PHP 7.0 configuration and for sure it was not enabled, So Why NOW? Why RoundCube was working before although the same configuration applied in the new PHP v7.2? So I didn't enable [zend.multibyte] until you reply may be there's another issue.

Thanks for your great project.

Best

**Comment by alecpl** [comment]
Probably the mbstring extension is not installed.
