### ISSUE TITLE
Update docker image?

### ISSUE THREAD

**Issue by logopk** [roundcube/roundcubemail#6721]
Hi there,

I don't know if this is the right spot to ask but:

would you mind to update the docker image at https://hub.docker.com/r/roundcube/roundcubemail/
with 1.3.9?

Thanks.

Peter

**Comment by alecpl** [comment]
The docker repo is here: https://github.comhttps://github.com/roundcube/roundcubemail-docker//roundcube/roundcubemail-docker/. So, you can create your request there. We'll update the image when Thomas is back from his vacation.
