### ISSUE TITLE
The font "monospace" is not in the list of font drop-down list

### ISSUE THREAD

**Issue by dmak** [roundcube/roundcubemail#6722]
I have started the new message which is "Plain Text" by default. Then I have switched to "HTML". 
 It is shown on the toolbar that the text of the message is written with "monospace" font, but I don't see that font in the drop-down list of fonts. This is confusing, because when I want to re-apply this "font" I cannot select it from the menu:
![roundcube_monospace](https://user-images.githubusercontent.com/366965/56293347-327b3700-6129-11e9-966a-20f9ca32c5a5.png)
In general this issue correlates with [issue #5700](https://github.com/roundcube/roundcubemail/issues/5700#issuecomment-374857609) which suggests to add "sans-serif", "serif" and "monospace" to the list of fonts. For example, Thunderbird has "Variable Width" and "Fixed Width" entries in font drop-down menu for that purpose.
Extra: Would it make sense to make the list of fonts configurable or have an option to add extra fonts to that list?

Roundcube v1.3.8

**Comment by alecpl** [comment]
This is TinyMCE detecting current font. It should not happen if you set the default font in preferences.

**Comment by dmak** [comment]
I have "Verdana" as a default font:
![image](https://user-images.githubusercontent.com/366965/56525636-8fbd2100-654b-11e9-88d6-bc165d5d200f.png)
Should "monospace" be in that list as well?

**Comment by alecpl** [comment]
Ok, I confirm the bug in 1.3, but it is not an issue anymore in git-master. Probably fixed with TinyMCE update. As it does not look like a serious issue, and the update is not that simple we'll not backport this to 1.3.

**Comment by SylwesterZarebski** [comment]
As of roundcube 1.6.16, there is no *monospace* font to be selected. There are only "real" fonts listed. Also there are no generic *serif* and *sans-serif*.
