### ISSUE TITLE
managesieve plugin adds Create filter UI element to the 'mailbox view' and 'show message' UI even though managesieve_vacation config option is set to hide Filters section

### ISSUE THREAD

**Issue by blakerwry** [roundcube/roundcubemail#6723]
When setting the managesieve_vacation config option to a value of 2, access to message filters is disabled in the Settings. However, this config setting is ignored by the mailbox view and show message screens which still add a Create filter element to the UI. A message rule can therefore be created on these screens that can then not be accessed (to edit/remove/etc) via Settings afterwards.

One would expect that access to message filters (other than a Vacation message) would be limited to the Vacation options within Settings when the managesieve_vacation option is set to 2. Therefore filter options should not be available on any other screen (either within Settings, the Mailbox view, or when viewing an individual message) when managesieve_vacation option is set to 2

It appears that the managesieve_vacation config option is not taken into account within the mail_task_handler function of managesieve.php. Would the following additional code be an acceptable patch to managesieve.php?

```
    function mail_task_handler()
    {
        $this->load_config();
        $vacation_mode = (int) $this->rc->config->get('managesieve_vacation');
        // Don't add filtering UI elements if vacation only mode
        if ($vacation_mode == 2) {
                return;
        }
```

If not, I would appreciate a patch to address this issue. Thanks!

**Comment by alecpl** [comment]
The change will be different for 1.3 and master, as we have also managesieve_forward option now.

**Comment by alecpl** [comment]
Fixed.
