### ISSUE TITLE
How to change column from email with contact list 

### ISSUE THREAD

**Issue by naigamo** [roundcube/roundcubemail#6725]
How to change column from email with contact list
Current
If receive mail other domain column from show internet email only
Ex. From: Sugit_Thi@xxxx.co.th 

How to change column from Sugit_Thi@xxxx.co.th  to Name and Surname only 
Ex. From: Sugit Thienpituk

Now I add Sugit Thienpituk to contact address already 

Thank You

**Comment by alecpl** [comment]
If there is a name in email headers specified it will be displayed. Messages list does not fetch names from your contacts. We have a ticket for this already, #5048.
