### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by kveriz** [roundcube/roundcubemail#6726]
Hello! I'm using roundcube version 1.3.5 and I faced issue with mobile layout. Fields for login and password are crossing the right border of login-form block. I did screenshot from my phone with latest mobile Chrome - [https://ibb.co/JngdZ35](url). I see the same issue on the iPhone6 with Safari and other android devices.

**Comment by alecpl** [comment]
Roundcube 1.3 does not support mobile. And I see you're using some modified skin anyway.
