### ISSUE TITLE
bmp inline Image displays as pink Box

### ISSUE THREAD

**Issue by ThomasCr** [roundcube/roundcubemail#6728]
A BMP Image, which is inserted as a signature won't get displayed on RoundCube. On Thunderbird the Image of this Mail in Displayed.

The header of this mime attached image are:
```
Content-Transfer-Encoding: base64
Content-ID: <533173a3342a08f548d28ff83fec2a95@XXXXX.de>
Content-Type: image/bmp;
 name=533173a3.bmp
Content-Disposition: inline;
 filename=533173a3.bmp;
 size=57722
```

When I right-click the image and select display image, and open the Developer Tools of the Browser to check what Headers get send from the Webserver, it shows this pink image as MIME-Typ: image/gif

I have set `$config['mime_types'] = '/etc/mime.types';` and this file is also included in my open_basedir setting.

On syslog and apache error log is also no failure logged.

**Comment by alecpl** [comment]
Most likely the file is not detected as image/bmp by the server (php), and for security reasons it displayed as a pink placeholder. Could you upload the image file into the server and run `file file.bmp` in command line? What is the result?

**Comment by ThomasCr** [comment]
Hi, I have done so: I saved the image from Thunderbird to my local system (also Ubuntu like the Server)...

```
$ file 533173a3.bmp 
533173a3.bmp: PC bitmap, Windows 95/NT4 and newer format, 200 x 96 x 24
```

But I made a quick fix, we converted the picture to jpeg and added them again.
If you can investigate to it, I can redirect to mail with the bmp to you.

**Comment by alecpl** [comment]
You can send a test to me (alec at alec dot pl), but I'm afraid that will be environment/configuration issue.

**Comment by ThomasCr** [comment]
I redirected the Mail from 24.04.19 to your Mail Address... installed is Roudcube 1.3.9 - and before we had 1.2.5 installed. On 1.2.5 all was Ok, but after the update is was not working any more.

**Comment by alecpl** [comment]
Thanks for the sample. I could reproduce the issue. On two different systems PHP's Fileinfo extension thinks the image is of type "application/octet-stream". We'll have to investigate more.

**Comment by alecpl** [comment]
Wrong. On a Ubuntu system it is detected as `image/x-ms-bmp`. So, I might have an idea how to fix this.

**Comment by alecpl** [comment]
Fixed.

**Comment by ThomasCr** [comment]
Thanks :)
