### ISSUE TITLE
Extract attachment name from message headers (don't trust BODYSTRUCTURE)

### ISSUE THREAD

**Issue by ramirserpsp** [roundcube/roundcubemail#6729]
When receiving a message with an attachment file name that has Japanese characters, the filename gets garbled in the display and also when downloading the file.

I sent a message with the following attachment name for testing:

> もの.txt

When I recieveed it in roundcube 1.4 it displayed and downloaded like this:

> UTF-8''%E3%82%82%E3%81%AE.txt

**Comment by alecpl** [comment]
Usually this is an imap server bug or invalid message. Could you provide original headers of the attachment part? COuld you enable imap_debug and check what is returned by the imap server when requesting BODYSTRUCTURE?

**Comment by ramirserpsp** [comment]
The log entries:

> [26-Apr-2019 15:55:58 +0000]: <4r2kjarr> [1FD4] C: A0005 UID FETCH 690003684 (BODY.PEEK[2.MIME])
> [26-Apr-2019 15:55:58 +0000]: <4r2kjarr> [1FD4] S: * 2143 FETCH (UID 690003684 BODY[2.MIME] {201}
> [26-Apr-2019 15:55:58 +0000]: <4r2kjarr> [1FD4] S: Content-Type: text/plain; charset=UTF-8;
>  name="=?UTF-8?B?44KC44GuLnR4dA==?="
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment;
>  filename*=utf-8''%E3%82%82%E3%81%AE%2E%74%78%74

The message headers:

> Content-Type: multipart/mixed;
>  boundary="------------BA96BC629F7E6A6FFA7731FC"
> Content-Language: en-US
> 
> This is a multi-part message in MIME format.
> --------------BA96BC629F7E6A6FFA7731FC
> Content-Type: text/plain; charset=utf-8; format=flowed
> Content-Transfer-Encoding: quoted-printable
> 
> =E3=82=82=E3=81=AE
> 
> 
> --------------BA96BC629F7E6A6FFA7731FC
> Content-Type: text/plain; charset=UTF-8;
>  name="=?UTF-8?B?44KC44GuLnR4dA==?="
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment;
>  filename*=utf-8''%E3%82%82%E3%81%AE%2E%74%78%74
> 
> Pz8=
> --------------BA96BC629F7E6A6FFA7731FC--
>

**Comment by alecpl** [comment]
There should be also response containing BODYSTRUCTURE string.

**Comment by ramirserpsp** [comment]
bodystructure string:

> [26-Apr-2019 21:22:56 +0000]: <132gp0sl> [082B] C: A0004 UID FETCH 690003684 (UID RFC822.SIZE FLAGS INTERNALDATE BODYSTRUCTURE BODY.PEEK[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PR
IORITY IN-REPLY-TO BCC SENDER MESSAGE-ID CONTENT-TRANSFER-ENCODING REFERENCES X-DRAFT-INFO MAIL-FOLLOWUP-TO MAIL-REPLY-TO RETURN-PATH)])
[26-Apr-2019 21:22:56 +0000]: <132gp0sl> [082B] S: * 2143 FETCH (UID 690003684 RFC822.SIZE 2594 FLAGS (\Seen) INTERNALDATE "24-Apr-2019 18:48:25 +0000" BODYSTRUCTURE (("text" "plain" ("charset" "utf-8" "format" "flowed") NIL NIL "quoted-pri
ntable" 22 2 NIL NIL NIL)("text" "plain" ("charset" "UTF-8" "name" "utf-8''%E3%82%82%E3%81%AE%2E%74%78%74") NIL NIL "base64" 4 1 NIL ("attachment" ("filename" "utf-8''%E3%82%82%E3%81%AE%2E%74%78%74")) NIL) "mixed" ("boundary" "------------B
A96BC629F7E6A6FFA7731FC") NIL NIL) BODY[HEADER.FIELDS (DATE FROM TO SUBJECT CONTENT-TYPE CC REPLY-TO LIST-POST DISPOSITION-NOTIFICATION-TO X-PRIORITY IN-REPLY-TO BCC SENDER MESSAGE-ID CONTENT-TRANSFER-ENCODING REFERENCES X-DRAFT-INFO MAIL-F
OLLOWUP-TO MAIL-REPLY-TO RETURN-PATH)] {351}

**Comment by alecpl** [comment]
The BODYSTRUCTURE is malformed:
1. `"name" "utf-8''%E3%82%82%E3%81%AE%2E%74%78%74"` is wrong, the header value is different for "name" parameter, but "filename" below is used in this case anyway.
2. `"filename" "utf-8''%E3%82%82%E3%81%AE%2E%74%78%74"` is wrong. It should be `"filename*"`. This is the reason of the issue.

Maybe we could workaround that, but I'm not sure we'll want that. What IMAP server are you using?

**Comment by alecpl** [comment]
As we already have a similar workaround and as we already fetch attachment headers, I think we could switch to always parsing the headers to get the attachment name. I.e. not use the name provided in BODYSTRUCTURE response. I'm talking about rcube_imap::structure_part() and rcube_imap::get_part_filename(). This however, is not a bug but a feature request, so low prio.

**Comment by alecpl** [comment]
Pull request created in #6783. So, you can test the fix.

**Comment by alecpl** [comment]
Fixed.
