### ISSUE TITLE
Mobile Responsive Issue: Search Bar

### ISSUE THREAD

**Issue by Abatjour3407** [roundcube/roundcubemail#6733]
All the buttons at the top of my RoundCube email platform (refresh, COMPOSE, reply, reply all, forward, delete, archive, mark) are covered by the email search field and button (when viewed from either a mobile phone or from a very small browser window on a laptop). 

I spoke to my host that has integrated the RoundCube into their services and they insist that it's not  an integration problem but that it's a problem with RoundCube itself and that there's nothing they can do about it. I hope that you either have a work-around solution for me or that you are able to fix this in future versions of RoundCube. 

PS: Thanks for this AMAZING product!
![LaptopRoundCube](https://user-images.githubusercontent.com/50051640/56851176-6cf48900-690c-11e9-8344-816ac0e714e0.png)
![MobileRoundCube](https://user-images.githubusercontent.com/50051640/56851177-6d8d1f80-690c-11e9-96ea-eb36ec1558e7.png)

**Comment by alecpl** [comment]
This is normal. The old skin does not support mobile. The Elastic skin with mobile support will be available with Roundcube 1.4.

**Comment by booshlinux** [comment]
The Larry skin is not mobile friendly.
Elastic is, which is included in 1.4. If you must view this on mobile, open your browser settings, (three dots on the upper right) and mark the "Desktop site" checkbox.
