### ISSUE TITLE
Own Debian repository

### ISSUE THREAD

**Issue by Ninos** [roundcube/roundcubemail#6736]
Hey there,

the packages for debian are very old (e.g. 1.4.x will not be available for latest debian). For such applications like roundcube I recommend using an own repository. Are there any plans for that?

Kindest regards

**Comment by alecpl** [comment]
No, we have no resources (time) to do that. Imo, installing Roundcube is not that hard, so until you use it as part of some bigger suite (e.g. Kolab) I see no reason to use distribution packages.

**Comment by Ninos** [comment]
So is it possible to remove roundcube from repositories (since debian buster), otherwise some applications depend on that packages (e.g. some isp). Removing roundcube from repo's ensures that depending applications are installing roundcube (latest versions) by their own (+ some custom roundcube plugins...).
