### ISSUE TITLE
Feature request: When replying to a mailing list, "X-Original-To" should become default sender address (if defined locally)

### ISSUE THREAD

**Issue by m-ueberall** [roundcube/roundcubemail#6737]
I looked at previous issues mentioning _"mailing list"_ and _"sender"_, but believe that none covered this use case before.
Given that one does not necessarily subscribe to all lists with the same email address, it would be helpful if Roundcube would take the ``X-Original-To`` header into account when the user selects _"reply to list"_ (or, even better though slightly more complicated to implement, in every case where the email s/he is responding to came from a list) and would not simply select the default sender address.
Some lists use a whitelist which means failure to check the sender address beforehand in the above scenario will require the user to note this/resend it because the first one will be discarded (sometimes, silently!) …

**Comment by alecpl** [comment]
What? X-Original-To is the mailing list address. I don't get it. What "if defined locally" means? What has sender (identity?) selection has to do with the mailing list address?

**Comment by m-ueberall** [comment]
The "if defined locally" was meant to refer to one of the identities defined in Roundcube.
Using Roundcube 1.3.9, I received a mailing list posting with the following:
```
Return-Path: <bounce....>
X-Original-To: public-user-email@example.org
Delivered-To: local-user@hostname.local-subdomain.example.org
From: <public-mail-address-of-original-poster@...>
To: "'MailingList'" <mailinglist@not.example.org>
References: <...> <...>
In-Reply-To: <...>   
Subject: Test subject                            
Message-ID: <...>
Thread-Index: ...
List-Help: <https://...>    
List-Id: "MailingList" <...>
List-Post: <mailto:mailinglist@not.example.org>
List-Software: ...        
List-Subscribe: <https://...>
Precedence: list 
Reply-To: MailingList <mailinglist@not.example.org>
List-Unsubscribe: <https://...>
```

Here, ``X-Original-To`` is __not__ the mailing list address, but my own email address which I used to subscribe to this mailing list. I cross-checked this with a few other lists/newsletters, and this is always the case for me. (The mailing list address in the above example is stored in ``To`` and ``Reply-To`` instead.)
Now, if I select _Reply all > Reply list_, the "From" address field shows a drop-down list containing the list of available identities with my default identity "default-public-user-email@not.example.org" preselected (which is _not_ the same as the above shown in the ``X-Original-To`` header).

The list of active plugins does not look suspicious in this regard/should not interfere:
``$config['plugins'] = array('twofactor_gauthenticator', 'carddav', 'enigma', 'managesieve', 'redundant_attachments');``

**Comment by alecpl** [comment]
On all mailing lists I use it is the mailing list address. Maybe it depends on the mailing list and target smtp server. Anyway, You can achieve what you want with identity_select plugin. I don't think we'll change the core behavior.
