### ISSUE TITLE
Roundcube show calendar invitation with wrong date

### ISSUE THREAD

**Issue by aacunha** [roundcube/roundcubemail#6738]
I'm using the kolab calendar to generate events in my corporation. But, when i create one event of type "all day", the email of confirmation send to participants is showed with wrong date in roundcube. 

For test, i created one event with name "test", with allday option checked.

![image](https://user-images.githubusercontent.com/5031111/57157272-a3bc1a80-6db6-11e9-8e65-e7c876625dd4.png)

I invited one email of my domain and one external email (gmail). In the email of my domain, the roundcube show de invitation with one day before of correct day.
In the gmail, the date showed in invitation is correct.

**My ambient:
Roundcube 1.3.8
Plugins installed:
Plugin	Versão
acl	1.6	
calendar	3.3.3
emoticons	2.0
filesystem_attachments	1.0
jqueryui	1.12.0
jsxc	3.3.2
libcalendaring	3.3.3
managesieve	8.7
markasjunk2	1.9-git	
mobile	0.4.8
newmail_notifier	0.8	
password	4.2	
zipdownload 3.3**

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Roundcube libcalendaring 1.3.8//Sabre//Sabre VObject 3.3.3//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:4FE58A7601F87BAD3929C16AE22953A0-FF9EF9B5374990FB
DTSTAMP:20190503T133143Z
CREATED:20190503T133143Z
LAST-MODIFIED:20190503T133143Z
DTSTART;VALUE=DATE:20190504
DTEND;VALUE=DATE:20190505
SUMMARY:test
SEQUENCE:0
TRANSP:OPAQUE
CLASS:PUBLIC
ATTENDEE;CN=Andre Cunha;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPA
 NT;CUTYPE=INDIVIDUAL;RSVP=TRUE:mailto:participant1@domain_local
ATTENDEE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL;RSVP=
 TRUE:mailto:participant2@domain2
ORGANIZER;CN=Owner_name:mailto:owner@domain_local
END:VEVENT
END:VCALENDAR
```

**Invitation on roundcube:**
![image](https://user-images.githubusercontent.com/5031111/57157629-a3704f00-6db7-11e9-922b-addbc739727b.png)

**Invitation on gmail**
(https://github.com/roundcube/roundcubemail/files/3143147/invitation_email.txt)
:
![image](https://user-images.githubusercontent.com/5031111/57157620-9fdcc800-6db7-11e9-89fa-3566d393852c.png)

**Code font of email received on roundcube:**
[invitation_email.txt]

**Comment by aacunha** [comment]
[invitation_email.txt](https://github.com/roundcube/roundcubemail/files/3143159/invitation_email.txt)

**Comment by alecpl** [comment]
That's a very old version of calendar plugin. Anyway, we do not support it here.

**Comment by aacunha** [comment]
3.3.3 is the last version of kolab calendar. I open the issue here because the ics is monted with correct date, and the invitation on another webmail (gmail) is showed correct. In the roundcube the invitation display one day early

**Comment by studiowena** [comment]
> 
> 
> I'm using the kolab calendar to generate events in my corporation. But, when i create one event of type "all day", the email of confirmation send to participants is showed with wrong date in roundcube.
> 
> For test, i created one event with name "test", with allday option checked.
> 
> ![image](https://user-images.githubusercontent.com/5031111/57157272-a3bc1a80-6db6-11e9-8e65-e7c876625dd4.png)
> 
> I invited one email of my domain and one external email (gmail). In the email of my domain, the roundcube show de invitation with one day before of correct day.
> In the gmail, the date showed in invitation is correct.
> 
> **My ambient: Roundcube 1.3.8 Plugins installed: Plugin Versão acl 1.6 calendar 3.3.3 emoticons 2.0 filesystem_attachments 1.0 jqueryui 1.12.0 jsxc 3.3.2 libcalendaring 3.3.3 managesieve 8.7 markasjunk2 1.9-git mobile 0.4.8 newmail_notifier 0.8 password 4.2 zipdownload 3.3**
> 
> ```
> BEGIN:VCALENDAR
> VERSION:2.0
> PRODID:-//Roundcube libcalendaring 1.3.8//Sabre//Sabre VObject 3.3.3//EN
> CALSCALE:GREGORIAN
> BEGIN:VEVENT
> UID:4FE58A7601F87BAD3929C16AE22953A0-FF9EF9B5374990FB
> DTSTAMP:20190503T133143Z
> CREATED:20190503T133143Z
> LAST-MODIFIED:20190503T133143Z
> DTSTART;VALUE=DATE:20190504
> DTEND;VALUE=DATE:20190505
> SUMMARY:test
> SEQUENCE:0
> TRANSP:OPAQUE
> CLASS:PUBLIC
> ATTENDEE;CN=Andre Cunha;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPA
>  NT;CUTYPE=INDIVIDUAL;RSVP=TRUE:mailto:participant1@domain_local
> ATTENDEE;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PARTICIPANT;CUTYPE=INDIVIDUAL;RSVP=
>  TRUE:mailto:participant2@domain2
> ORGANIZER;CN=Owner_name:mailto:owner@domain_local
> END:VEVENT
> END:VCALENDAR
> ```
> 
> **Invitation on roundcube:**
> ![image](https://user-images.githubusercontent.com/5031111/57157629-a3704f00-6db7-11e9-922b-addbc739727b.png)
> 
> **Invitation on gmail**
> (https://github.com/roundcube/roundcubemail/files/3143147/invitation_email.txt)
> :
> ![image](https://user-images.githubusercontent.com/5031111/57157620-9fdcc800-6db7-11e9-89fa-3566d393852c.png)
> 
> **Code font of email received on roundcube:**
> [invitation_email.txt]

could You tell me how to configure calendar plugin to sent invitation emails? I cant make it to work - no invite email sent
