### ISSUE TITLE
Elastic: Absolute positioning in HTML mails miscalulcated

### ISSUE THREAD

**Issue by peterdey** [roundcube/roundcubemail#6739]
HTML mail is with position:absolute divs are displayed wrong, because the position is calculated relative to the top of the preview frame.

Example mail attached which renders over the headers div.

Adding position: relative; to #messagebody fixes this.
[position_absolute.txt](https://github.com/roundcube/roundcubemail/files/3144968/position_absolute.txt)

**Comment by alecpl** [comment]
Fixed.
