### ISSUE TITLE
Unable To Login After Install

### ISSUE THREAD

**Issue by ThisGuyNeedsABeer** [roundcube/roundcubemail#6741]
I have a working mail server where my account can be added to thunderbird, the settings are autodiscovered, and mail is flowing internally/externally.

I went through the roundcube install doc from INSTALL as well as this guide: https://www.tekfansworld.com/how-to-set-up-an-email-server-with-postfix-dovecot-and-roundcube-on-ubuntu-18-04.html 

All the tests were "OK" during the install, and the test e-mail and IMAP login test were successful as well.

When I go to login to roundcube, I get "login failed" trying to login with the same user and password that validated all the tests.

My /var/log/mail.log is as follows once I try to login:

`May  8 17:26:12 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<email@mydomain.com>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<x3AhoWOI9up/AAAB>
`

Originally this line preceded the error:

`May  8 17:17:39 mail dovecot: auth-worker(2478): Error: pam(email@mydomain.com,127.0.0.1): pam_authenticate() failed: Authentication failure (/etc/pam.d/imap missing?)
`
I created the file /etc/pam.d/imap as follows and that error stopped showing up:

`passdb {
  args = %s
  driver = pam
}
`

Dovecot.conf as follows:

`disable_plaintext_auth = no
mail_privileged_group = mail
mail_location = mbox:~/mail:INBOX=/var/mail/%u
userdb {
  driver = passwd
}
passdb {
  args = %s
  driver = pam
}
protocols = "imap"

protocol imap {
  mail_plugins = "autocreate"
}
plugin {
  autocreate = Trash
  autocreate2 = Sent
  autosubscribe = Trash
  autosubscribe2 = Sent
}

service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = postfix
    mode = 0660
    user = postfix
  }
}

ssl=required
ssl_cert = </etc/letsencrypt/live/mydomain.com/fullchain.pem
ssl_key = </etc/letsencrypt/live/mydomain.com/privkey.pem
`
I'm at a loss as to why I can authenticate with a user/password on my phone, as well as Thunderbird, but not with RoundCube when I had green "OK" marks the entire way.

Thank you for any direction, any remaining logs/conf files can be immediately provided.

**Comment by alecpl** [comment]
Did you configure Roundcube to use TLS/SSL? Try setting `imap_auth_type`. Finally, you can enable imap_debug and see what's going on.

**Comment by ThisGuyNeedsABeer** [comment]
> Did you configure Roundcube to use TLS/SSL? Try setting `imap_auth_type`. Finally, you can enable imap_debug and see what's going on.

I will verify that setting, and enable imap_debug and report back. Thank you!

**Comment by ThisGuyNeedsABeer** [comment]
@alecpl 

I enabled the debug statement, and set the login type to PLAIN (which is what thunderbird showed for auto-configure) attached is the log, a failure during login, but the same credentials work to send a message through thunderbird without issue

`May  8 19:26:13 mail dovecot: imap(infteam): Server shutting down. in=968 out=6557
May  8 19:26:13 mail systemd[1]: Stopped Dovecot IMAP/POP3 email server.
May  8 19:26:13 mail systemd[1]: Starting Dovecot IMAP/POP3 email server...
May  8 19:26:13 mail systemd[1]: dovecot.service: PID file /var/run/dovecot/master.pid not readable (yet?) after start: No such file or directory
May  8 19:26:13 mail dovecot: master: Dovecot v2.2.22 (fe789d2) starting up for imap (core dumps disabled)
May  8 19:26:13 mail systemd[1]: Started Dovecot IMAP/POP3 email server.
May  8 19:26:33 mail dovecot: auth-worker(22451): Error: pam(email@mydomain.com,x.x.x.x): pam_authenticate() failed: Authentication failure (/etc/pam.d/imap missing?)
May  8 19:26:35 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 4 secs): user=<email@mydomain.com>, method=PLAIN, rip=x.x.x.x, lip=10.50.50.50, TLS, session=<DoWLT2WIwq4D1hv7>
May  8 19:27:36 mail dovecot: auth-worker(22466): Error: pam(email@mydomain.com,x.x.x.x): pam_authenticate() failed: Authentication failure (/etc/pam.d/imap missing?)
May  8 19:27:38 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 4 secs): user=<email@mydomain.com>, method=PLAIN, rip=x.x.x.x, lip=10.50.50.50, TLS, session=<pABTU2WIxK4D1hv7>
May  8 19:28:10 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 3 secs): user=<email@mydomain.com>, method=PLAIN, rip=x.x.x.x, lip=10.50.50.50, TLS, session=<+K5EVWWIxq4D1hv7>
May  8 19:28:30 mail postfix/submission/smtpd[22483]: connect from x.x.x.x
May  8 19:28:30 mail postfix/submission/smtpd[22483]: Anonymous TLS connection established from x.x.x.x: TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
May  8 19:28:31 mail postfix/submission/smtpd[22483]: 0401C3EB55: client=x.x.x.x, sasl_method=PLAIN, sasl_username=infteam
May  8 19:28:31 mail postfix/cleanup[22488]: 0401C3EB55: message-id=<db83bc07-572b-3489-781d-0d6722ef242b@mydomain.com>
May  8 19:28:31 mail opendkim[1299]: 0401C3EB55: DKIM-Signature field added (s=mail, d=mydomain.com)
May  8 19:28:31 mail opendmarc[1395]: implicit authentication service: mail.mydomain.com
May  8 19:28:31 mail opendmarc[1395]: 0401C3EB55: mydomain.com fail
May  8 19:28:31 mail postfix/qmgr[22429]: 0401C3EB55: from=<email@mydomain.com>, size=799, nrcpt=1 (queue active)
May  8 19:28:31 mail postfix/local[22489]: 0401C3EB55: to=<email@mydomain.com>, relay=local, delay=0.19, delays=0.18/0/0/0, dsn=2.0.0, status=sent (delivered to mailbox)
May  8 19:28:31 mail postfix/qmgr[22429]: 0401C3EB55: removed
May  8 19:28:31 mail postfix/submission/smtpd[22483]: disconnect from x.x.x.x ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
May  8 19:28:31 mail dovecot: imap-login: Login: user=<infteam>, method=PLAIN, rip=70.15.250.8, lip=10.50.50.50, mpid=22491, TLS, session=<KoG2VmWIyJhGD/oI>
May  8 19:28:31 mail dovecot: imap(infteam): Warning: autocreate plugin is deprecated, use mailbox { auto } setting instead
May  8 19:28:31 mail dovecot: imap(infteam): Logged out in=517 out=519
`

**Comment by ThisGuyNeedsABeer** [comment]
Also attaching my config.inc.php

https://pastebin.com/gwLT00HW

**Comment by ThisGuyNeedsABeer** [comment]
Solved via the last reply from user "hotstaff"

https://www.roundcubeforum.net/index.php?topic=10917.0

adding "auth_username_format = %n" to /etc/dovecot/dovecot.conf seemed to do the trick.. I don't know why, I haven't seen that in any install guides or published documentation.
