### ISSUE TITLE
can not search mail

### ISSUE THREAD

**Issue by artcup00** [roundcube/roundcubemail#6742]
hello.

Roundcube 1.3.8 version is in use.

? ks_c_5601-1987? B? You can not retrieve messages encoded with.

? ks_c_5601-1987? B? It is possible to check the contents of the encoded mail.
It is not just a search.

Is there a workaround?

===========================================

[Mail Header]

Return-Path: <xxx@xxxx.com>
From: =?ks_c_5601-1987?B?wMhedL+1?= <xxxx@xxxx.com>
To: <xxx@xxxx.com>
Subject: =?ks_c_5601-1987?B?vsa/9LfmjkcehwdC5+MijIhrevsOY=?=
Date: Wed, 15 Apr 2019 12:00:45 +0900
Message-ID: <xxxx@xxxx.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
    boundary="----=_NextPart_000_0001_01D4KC95.07BFC530"
X-Mailer: Microsoft Outlook 16.0
Thread-Index: AdTvSherrehcxDcR0i1oYXrt34bW5fA==
Content-Language: ko

**Comment by alecpl** [comment]
Roundcube uses IMAP commands to search mail. So, if it does not work it will be an IMAP server issue. According to RFC server should decode headers for searching. The problem might be with uncommon charset.
