### ISSUE TITLE
Attachment uploads fail with "File upload error" after ~22 seconds

### ISSUE THREAD

**Issue by adam12b1** [roundcube/roundcubemail#6743]
We and our users are seeing a new problem with attachment uploads, whereby they always fail with a "File upload error" dialog after about 22 seconds. This result is consistent across extremely varied network connections (eg. very slow mobile hotspot and very fast residential ISP), and across OSes (at least Windows & Mac) and browsers (see below), and has no relation to file size (in fact one has to test on a larger file on a faster network in order to trigger the bug). On a connection with 1.5Mbps upload speed, the bug is triggered at around 4-5MB file size, which is far below reasonable message size limits.

Browsers appear to handle the error condition differently: In Safari or Chrome, you get that "File upload error" dialog from RC, while in Firefox it just continues spinning as if it's still working, forever (or at least for many minutes). Seems like some subtle difference in Javascript implementation.

The 22 seconds, as you might guess, is not anything like any of our PHP (or Apache or browser) limits, and we've tried raising the key ones just to be safe, but attached is our php -i output anyway. We believe anyone should be able to reproduce this issue on any network, as long as you use a big enough file that it takes long enough at whatever your upload speed is. We can only guess that others haven't seen it only because everybody's on such fast networks now - but alas, some of our webmail users are not.

[phpinfo.txt](https://github.com/roundcube/roundcubemail/files/3164200/phpinfo.txt)

**Comment by alecpl** [comment]
Could you provide Roundcube config? What version?

**Comment by adam12b1** [comment]
Ah, sorry: same issue in both versions 1.3.8 and 1.3.9, and I should have mentioned we've tried removing all plugins, with no effect. Here's our RC config:

/* Local configuration for Roundcube Webmail */

$config['db_dsnw'] = 'mysql://<DSN>';
$config['log_driver'] = 'syslog';
$config['debug_level'] = 1;
$config['layout'] = 'widescreen';
$config['syslog_facility'] = LOG_LOCAL4;
$config['smtp_log'] = false;
$config['log_logins'] = true;
$config['default_host'] = 'tls://<URL>';
$config['smtp_server'] = 'tls://<URL>';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['support_url'] = '<URL>';
$config['des_key'] = '<KEY>';
$config['product_name'] = 'Electric Embers Webmail';
$config['skin'] = 'ee';
$config['language'] = 'en_US';
$config['drafts_mbox'] = 'INBOX.Drafts';
$config['junk_mbox'] = 'INBOX.Spam';
$config['sent_mbox'] = 'INBOX.Sent';
$config['trash_mbox'] = 'INBOX.Trash';
$config['login_autocomplete'] = 1;
$config['spellcheck_engine'] = 'pspell';
$config['mail_pagesize'] = 200;
$config['htmleditor'] = 2;
$config['mime_param_folding'] = 0;
$config['mime_types'] = '/usr/local/etc/apache24/mime.types';
$config['mime_magic'] = null;
$config['show_real_foldernames'] = true;

**Comment by adam12b1** [comment]
FWIW, I've just tested in the new 1.4-rc1 and see the same behavior at ~22 seconds, although now the error has changed to "Connection error: failed to reach the server!".

**Comment by adam12b1** [comment]
...and FWIW, I've just replicated the same behavior on this totally different third-party free demo site of a tweaked version of Roundcube: http://demo.roundcubeplus.com/

So it's nothing to do with our server or settings or network.

**Comment by alecpl** [comment]
Quite good and detailed report, but I have no idea what that could be. I tried firefox mobile mode with slowed down network and I cannot reproduce.

Are you using nginx, apache, fpm? Do you compose mail in a separate window? I would propose to test this with a setup that eliminates any parallel requests, i.e. no separate window, disabled draft autosave, long session time. You can also enable all debug options, and see if there's anything in the log around the time the error happens.

**Comment by adam12b1** [comment]
Yes, we tried that too, somehow it only works when the actual network connection is slow - can you try a mobile hotspot? Or else try upping the max attachment size on your server to something that will let you upload a big enough file to get to 25 or 30 seconds?

We're using Apache, but again that's surely moot since I got the same results on this random third-party service demo that uses Roundcube. Composing mail in the same window (default setting), in all cases. We've enabled all the logging in the world and there's nothing useful, and we can only guess it's because the errors are all somewhere within the secret world of Javascript.

**Comment by alecpl** [comment]
It does not have to be Roundcube's fault. It more looks like generic http (or php) problem. Did you try if uploading works in other php apps or with some simple php/html code on your server?

**Comment by alecpl** [comment]
Thinking about something like RequestReadTimeout in Apache config.

**Comment by adam12b1** [comment]
UGH! You are 100% correct! It was RequestReadTimeout, and changing the body timeout from the default 20 to 60 has cured our problem.

I'm so sorry to have taken your time with that, and really appreciate your help. Gonna make a donation to Roundcube now as an expression of gratitude, for your time here as well as for this excellent software. :)

**Comment by adam12b1** [comment]
...that is, I would like to donate, but now see that's not actually a thing one can do? If there is, or if there's another project of yours that you would like supported, please let me know.

**Comment by alecpl** [comment]
We removed the Donate button from our page as we really didn't receive much donations in the past. Also our infra costs are mostly sponsored, so we don't need that money. You can donate me personally via PayPal, my account is alec at alec.pl, but I also do not expect any donations (thanks to Kolab Systems).
