### ISSUE TITLE
No Mails visible after update to 1.3.9

### ISSUE THREAD

**Issue by logg-sar** [roundcube/roundcubemail#6745]
Hi there

I´ve updated yesterday to 1.3.9 (with some trouble, especcially at database connection. But now its fine)
After logging in I see the folder structure of my mail server but no mails. The mails are here, as i can see with my mail client.

Additionally at logout I get the message

> PHP Error: Request security check failed

> REQUEST CHECK FAILED
> For your protection, access to this resource is secured against CSRF.
> If you see this, you probably didn't log out before leaving the web application.
> 
> Human interaction is now required to continue.
> Please contact your server-administrator.

After searching I found the Issue #5579 which suggests a problem with javascript dependencies and points to a  bin/install-jsdeps.sh which is no longer available.

Any hint how to fix this?

*edit*
I forgot
 php -v
PHP 7.3.5-1+0~20190503093827.38+stretch~1.gbp60a41b (cli) (built: May  3 2019 09:38:28) ( NTS )
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies

Your MariaDB Server version: 10.1.38-MariaDB-0+deb9u1 Debian 9.8

Linux mail.*********.com 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

*edit2*

after finding and downloading install-jdeps.sh and jsdeps.json it installed some files it still doesnt work....

**Comment by alecpl** [comment]
What version were you using before? Did you check error log? Did you try with disabled all plugins? Check also browser console for errors.

**Comment by logg-sar** [comment]
> Check also browser console for errors.

This was the correct hint.
The jquery-ui.min.js had - for what reasons ever - wrong user and coundnt be executed.
This lead to this error,

Fixed now.
Thanks

**Comment by jameslbrown** [comment]
Had same issue. Turning on 'Show Javascript Console' from Safari Develop menu showed me that my Content Security Policy was the problem. Commenting out that in https.conf fixed it.

Is there a recommended CSP for Roundcube?
