### ISSUE TITLE
No parsing mailto URL arguments with Elastic skin "Compose mail to" dialog

### ISSUE THREAD

**Issue by urusha** [roundcube/roundcubemail#6751]
Roundcube 1.4-rc1 doesn't parse mailto URL arguments with Elastic skin. With Larry all is OK. Seems it's somehow related to the new dialog appearing on a click on a mailto link (`Add to address book` + `Compose mail to`) with Elastic.
Example: `mailto:test@example.com?subject=x&body=y`

**Comment by alecpl** [comment]
Fixed.
