### ISSUE TITLE
Fileinfo/mime_content_type configuration:  NOT OK

### ISSUE THREAD

**Issue by mmiat** [roundcube/roundcubemail#6753]
I've this error during install

"Fileinfo/mime_content_type configuration:  NOT OK
Check the Fileinfo functions of your PHP installation.
The path to the magic.mime file can be set using the mime_magic config option in Roundcube."

I've search everywhere, but I can't understand where i can find path to mime_magic db. I'm using a shared hosting, and I've only access to my /home folder. Can I download this db and put somewhere in my folder?

thanks

**Comment by alecpl** [comment]
You can put it anywhere, but it have to be accessible for the php process.

**Comment by mmiat** [comment]
ok but i dont understand where find it !? thanks

**Comment by mmiat** [comment]
solved enabling fileinfo mod
