### ISSUE TITLE
Attachments are displayed twice/double

### ISSUE THREAD

**Issue by taiham** [roundcube/roundcubemail#6754]
Hello,

Sometimes I receive emails with attachment that are displayed twice or in double. (often from outlook.com users)
![image](https://user-images.githubusercontent.com/10847553/57704302-e822a280-7661-11e9-80a2-5491b59d56ee.png)

When forwarding the mail to someone else, I see only one attachement.
![image](https://user-images.githubusercontent.com/10847553/57704359-04beda80-7662-11e9-8f32-a9d229222a81.png)

The same mail has only one attachement on my phone / email client.

Using Roundcube Webmail 1.4-beta
Any one already seen this? Thx 
Pierre

**Comment by alecpl** [comment]
This is when the message is a forward? Such issue has been fixed in 1.4-rc1 (without a ticket).

**Comment by taiham** [comment]
> This is when the message is a forward? Such issue has been fixed in 1.4-rc1 (without a ticket).

Correct, I have just installed RC1 problem seem to be solved, thx for your swift reply !
