### ISSUE TITLE
Unable to click through or otherwise get around dialogues

### ISSUE THREAD

**Issue by adkinsijl** [roundcube/roundcubemail#6755]
Using Chrome for Android, if I click compose, I get a dialogue that pops up saying there is a previously saved draft found. (There is no such draft, as far as I can tell.) Then I am unable to click on or get around the dialogue.

Something similar happens when I am replying to a large group of recipients, and a dialogue pops up asking whether I want to use BCC instead. I also cannot click anything.

In both instances I have had to resort to a desktop  and desktop browser to send my messages.

**Comment by alecpl** [comment]
What Roundcube/Chrome/Android version? What skin? Any errors in browser console? Does it happen with disabled all plugins?

**Comment by adkinsijl** [comment]
Roundcube 1.3.8, Chrome 74.0.3729.136, Android 8.1.0, skin Mélanie2 Larry mobile by PNE Annuaire et Messagerie basée sur la skin Larry by FLINT et JQuery Mobile.  It's the default my webhoster chose.  Changing skins is apparently not allowed, as it reverts to the default immediately.

Unsure of what you mean by plug-ins, unless you mean browser plugins, of which I have none.

I was able to clear the compose dialogue when switching to desktop mode, but desktop mode is a mess on a mobile display, with elements piled on top of each other.  The too-many-recipients dialogue did not present itself in desktop mode.

**Comment by adkinsijl** [comment]
Update: the Mélanie2 skin appears to be the desktop skin.  I can change those.  I don't know what the mobile skin is called and it doesn't let me change it anyway.

**Comment by alecpl** [comment]
We do not support that skin, nor mobile in 1.3. Mobile support is via the Elastic skin in Roundcube 1.4.
