### ISSUE TITLE
Autosaved draft messages are not deleted

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#6756]
I’ve been using Roundcube webmail 1.4-RC1 for a few weeks and noticed multiple messages in the Drafts folder. 
I’ve done some testing and found that the autosaved draft is not deleted after the message has been sent. 
How to reproduce: 
1. Start composing a message 
2. Select Save sent message in: [-don’t save-] (sometimes it happens when is set to Sent, but I can’t reproduce it)
3. Wait until the message is autosaved (my autosave time is set to 1 min.)
4. Send the message

There is no such problem in Roundcube 1.3.9

Also, I think when a draft message is created it should be marked as unread like in Gmail and Thunderbird etc.

**Comment by alecpl** [comment]
Fixed.

**Comment by alecpl** [comment]
As for setting the unread state. I have no strong opinion, but it's this way since forever and I don't remember any complaints. So, we'll probably not change that.
