### ISSUE TITLE
Invalid 'X-Frame-Options' 

### ISSUE THREAD

**Issue by Rasmusbdk** [roundcube/roundcubemail#6757]
Hey there

I am tryin to load my roundcube installation in an iframe. By default this is blocked by same origin x-frame-options, so I have added the following entry in my config:

$config['x_frame_options'] = 'ALLOW-FROM http://myurl.com';

However, instead of allowin from myurl, this seems to allow access from everywhere by simply ignoring the x-frame-options header. Google gives me the following error:

Invalid 'X-Frame-Options' header encountered when loading 'http://myurl.com/page': 'ALLOW-FROM http://myurl.com' is not a recognized directive. The header will be ignored.

What am I doing wrong?

**Comment by alecpl** [comment]
As I know Chrome does not support allow-from option and we can do nothing about it. I guess you have to unset this header and set a different security header (Content-Security-Policy) e.g. via .htaccess file.

**Comment by Rasmusbdk** [comment]
Thanks. Can I unset it without getting the error mentioned?

**Comment by Rasmusbdk** [comment]
Im still trying to figure this out. If I simply unset the header from my config and try to load the client in an iframe, I get "Refused to display 'myurl' in a frame because it set 'X-Frame-Options' to 'sameorigin'." instead.

So.. The only way I have been able to fix this, is by setting $config['x_frame_options'] to anything, making Chrome parse it as invalid and hence ignore it. 

Can't I somehow make my client able to load in an iframe with getting the ugly x-frame error?
