### ISSUE TITLE
HTML mail viewed as plaintext transforms bold text to uppercase

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#6758]
It seems that if I open an HTML mail as plaintext, ~~everything that would've been bold~~ the content of certain HTML tags is turned to uppercase. This leads to problems if the mail contains case-sensitive voucher codes within `b`-tags for example.

**Comment by smares** [comment]
This appears to be done in ´tags_preg_callback´ of ´/program/lib/Roundcube/rcube_html2text.php` and affects `strong`, `b`, headlines (`h1`-`h6`) and `th`. While it's unlikely that something case-sensitive is written inside headlines or table headings, I just encountered a problem with a coupon code inside a `b`-tag.

**Comment by alecpl** [comment]
You're a first person complaining about this, but I think it makes sense.

**Comment by alecpl** [comment]
Fixed in 7c8ce07e8.
