### ISSUE TITLE
managesieve vacation: UI should allow display names in from field

### ISSUE THREAD

**Issue by c0deright** [roundcube/roundcubemail#6760]
[Current code](https://github.com/roundcube/roundcubemail/blob/master/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php#L221) prevents users from creating a vacation rule where the **From** field contains a display-name like

`My Name <foo@example.com>`

so the out-of-office reply would contain the header

`From: My Name <foo@example.com>`

Right now you're forced by UI to use

 `foo@example.com`

which results in header

`From: foo@example.com`

which then results in mails likely getting marked as Junk by the receiving MTA.

It's basically the same issue as outlined in https://github.com/cyrusimap/cyrus-imapd/issues/2189.

It's perfectly legal to use

`vacation :days 14 :addresses ["..."] :subject "..." :from "My Name <foo@example.com>"`

in a sieve script.

In fact, I just edited the sieve script with vim and did test the out-of-office reply and can confirm that the ooo email now has a header `From: My Name <foo@example.com>` instead of `From: foo@example.com`.

**Comment by alecpl** [comment]
Confirmed with RFC 5230.

**Comment by alecpl** [comment]
PR created in #6763.

**Comment by alecpl** [comment]
Done.
