### ISSUE TITLE
Application Error (600): Enigma plugin: GPG binary not found.

### ISSUE THREAD

**Issue by jose123455587** [roundcube/roundcubemail#6761]
I've installed Gnupg but enigma says can not find.
So I run 'apt install gnupgp' and it returns that
"gnupg is already the newest version (2.2.4-1ubuntu1.2)."

So I want to know where is gnupg binary to put in config.Where can I find?
Thanks

**Comment by alecpl** [comment]
Usually in `/usr/bin/gpg`, but that path should work automatically. Run `which gpg`.

**Comment by jose123455587** [comment]
Which gpg says /usr/bin/gpg but I don't have that folder.

**Comment by revoltown** [comment]
sorry no gpg in /usr/bin/gpg , 
roundcube says no binary...

Czytanie list pakietów... Gotowe
Budowanie drzewa zależności
Odczyt informacji o stanie... Gotowe
Nie udało się zainstalować niektórych pakietów. Może to oznaczać,
że zażądano niemożliwej sytuacji lub użyto dystrybucji niestabilnej,
w której niektóre pakiety nie zostały jeszcze utworzone lub przeniesione
z katalogu Incoming ("Przychodzące").
Następujące informacje mogą pomóc rozwiązać sytuację:

Następujące pakiety mają niespełnione zależności:
 gpg : Wymaga: gpgconf (= 2.2.12-1+deb10u1) ale 2.2.20-1~bpo10+1 ma zostać zainstalowany
       Poleca: gnupg (= 2.2.12-1+deb10u1) ale nie zostanie zainstalowany
E: Nie udało się naprawić problemów, zatrzymano uszkodzone pakiety.

**Comment by revoltown** [comment]
[13:06][root@debian][~] $ apt install gnupg
Czytanie list pakietów... Gotowe
Budowanie drzewa zależności
Odczyt informacji o stanie... Gotowe
Nie udało się zainstalować niektórych pakietów. Może to oznaczać,
że zażądano niemożliwej sytuacji lub użyto dystrybucji niestabilnej,
w której niektóre pakiety nie zostały jeszcze utworzone lub przeniesione
z katalogu Incoming ("Przychodzące").
Następujące informacje mogą pomóc rozwiązać sytuację:

Następujące pakiety mają niespełnione zależności:
 gnupg : Wymaga: dirmngr (< 2.2.12-1+deb10u1.1~) ale 2.2.20-1~bpo10+1 ma zostać zainstalowany
         Wymaga: gpg (< 2.2.12-1+deb10u1.1~) ale nie zostanie zainstalowany
         Wymaga: gpg (>= 2.2.12-1+deb10u1) ale nie zostanie zainstalowany
         Wymaga: gpg-agent (< 2.2.12-1+deb10u1.1~) ale nie zostanie zainstalowany
         Wymaga: gpg-agent (>= 2.2.12-1+deb10u1) ale nie zostanie zainstalowany
         Wymaga: gpg-wks-client (< 2.2.12-1+deb10u1.1~) ale nie zostanie zainstalowany
         Wymaga: gpg-wks-client (>= 2.2.12-1+deb10u1) ale nie zostanie zainstalowany
         Wymaga: gpg-wks-server (< 2.2.12-1+deb10u1.1~) ale nie zostanie zainstalowany
         Wymaga: gpg-wks-server (>= 2.2.12-1+deb10u1) ale nie zostanie zainstalowany
         Wymaga: gpgsm (< 2.2.12-1+deb10u1.1~) ale nie zostanie zainstalowany
         Wymaga: gpgsm (>= 2.2.12-1+deb10u1) ale nie zostanie zainstalowany
         Wymaga: gpgv (< 2.2.12-1+deb10u1.1~) ale 2.2.20-1~bpo10+1 ma zostać zainstalowany
E: Nie udało się naprawić problemów, zatrzymano uszkodzone pakiety.
