### ISSUE TITLE
Elastic theme & iPAD

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6765]
if iPAD is in horizontal position, icons above message panel are aligned on the bottom
of menu bar, not centered.

ios 12.3, firefox & safari.

RCM git, contextmenu plugin.

**Comment by alecpl** [comment]
Could you provide a screenshot?

**Comment by alecpl** [comment]
I was able to reproduce on old iPad with iOS9.

**Comment by alecpl** [comment]
Should be fixed now. Please, confirm.

**Comment by grape6** [comment]
Ok now, thanks. 
Sorry for delay, i could check it only at home.
