### ISSUE TITLE
Received Attachments corrupted (only docx,xlsx,pptx)

### ISSUE THREAD

**Issue by codymchapman** [roundcube/roundcubemail#6766]
my received emails are having issues to download any docx, xlsx, and pptx attachments. they go to their application and come up corrupted. only received.

**Comment by alecpl** [comment]
So, only "zipped" format, right? I think this has something to do with compression on http/php level or with BINARY extension in IMAP, and probably is not Roundcube issue. You can check by disabling compression in http setup or BINARY extension in imap server.

**Comment by codymchapman** [comment]
ok thank you. i will give it a try.

**Comment by codymchapman** [comment]
No sir it was not zipped.

**Comment by alecpl** [comment]
You can disable BINARY extension in Roundcube config with `$config['imap_disabled_caps'] = array('BINARY');`.

**Comment by alecpl** [comment]
Also, I think I need some clarification. By "my received emails" you mean email sent by someone else open in Roundcube? Are they not corrupted when you use a different imap client?

**Comment by codymchapman** [comment]
My confusion was i wasnt aware that docx was automatically compressed. So I am having the server team check out the apache server. Also yes received, any email from someone else the file is corrupted.

**Comment by sajid002** [comment]
Also, I think I need some clarification. By "my received emails" you mean email sent by someone else open in Roundcube? Are they not corrupted when you use a different imap client?

**Comment by codymchapman** [comment]
where would i put this $config['imap_disabled_caps'] = array('BINARY');? in message.html or the jscript

**Comment by alecpl** [comment]
In main Roundcube configuration file.

**Comment by codymchapman** [comment]
i put $config['imap_disabled_caps'] = array('BINARY'); in config.inc.php and it still comes up with corrupt content.
![image](https://user-images.githubusercontent.com/50876731/58576724-f8ff1680-8212-11e9-8460-fc42e23cbddc.png)

![image](https://user-images.githubusercontent.com/50876731/58576811-20ee7a00-8213-11e9-92e8-4e073152496f.png)

**Comment by codymchapman** [comment]
![image](https://user-images.githubusercontent.com/50876731/58576841-35327700-8213-11e9-8b8d-7c20ab2304f8.png)
![image](https://user-images.githubusercontent.com/50876731/58576873-49767400-8213-11e9-8387-716cb82181f1.png)

this is the error i am getting.

**Comment by codymchapman** [comment]
only in roundcube our work around atm seems to be using an app.

**Comment by codymchapman** [comment]
its only happening when i receive and email in roundcube. So downloading attachments.
When i send using roundcube no issue. So uploading attachments.

**Comment by alecpl** [comment]
Ok, lets start from the beginning.
1. What Roundcube version? What OS and PHP version?
2. Try with disabled all plugins.
3. Try with disabled compression (in http server or php config).
4. Are you sure it's only for "compressed" formats? I.e. do you have similar issues with image or pdf files?
5. Any errors in log? Did you actually try to look into such a file? maybe it contains some redundant spaces or sth like that.

**Comment by codymchapman** [comment]
1) version: 1.3, apache server, php 5.6
2)disabled plugins
3) dont have access to the apache server to disable compression
4)its only docx,xlsx, pptx, files
5) gettting the corrupt error when i try to open it in roundcube online version only, but my boss says he has them working out of an imap app thats allowing it to download

**Comment by alecpl** [comment]
There's no version 1.3, be more specific. Anyway, I think it's http problem not Roundcube problem.

**Comment by alecpl** [comment]
I forgot to mention that it works for me with Roundcube git-master in my server environment.

**Comment by alecpl** [comment]
With this information we can't really do anything about it.
