### ISSUE TITLE
Roundcube installer

### ISSUE THREAD

**Issue by lukonh** [roundcube/roundcubemail#6768]
Hi, I have a problem with the roundcube installer
When I launch the https://example.com/rrouncube/installer page
Everything shows that it's ok. I go on and create config.
When I click on the bottom to create a confi, do not show any errors I just go back to the first stage where everything is ok again. Config, unfortunately, did not create. What could be the reason?

**Comment by alecpl** [comment]
The web server has to have access rights to the config folder.

**Comment by lukonh** [comment]
I know about it, I gave access to www-data config and the entire roundcube catalog. Unfortunately, the config does not create itself.

**Comment by alecpl** [comment]
Sorry, I didn't get the issue. "Create config" button should reload the step 2 page and add additional UI elements on top of the page with options to Download or Save config file. What version?

**Comment by alecpl** [comment]
Wrong again, if the config dir is writable the options to Save/Download will not be displayed. In any case it should not go back to step 1.

**Comment by lukonh** [comment]
ok. Please check on the test server
https://nh-krakow.pl/poczta/installer/
version 1.3.9

**Comment by alecpl** [comment]
Looks like it somehow ignores `_step` argument in POST data. Check if `variables_order` and `request_order` in PHP config contain `P`.

**Comment by alecpl** [comment]
Yeah, something's wrong with POST data. Check web server logs and config, I have no clue.

**Comment by alecpl** [comment]
No feedback. It does not look like something we could do about.
