### ISSUE TITLE
'managesieve_default' & 'managesieve_script_name' errors

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#6773]
RC 1.3.9, PHP 7.3, FreeBSD, fresh installation.

If I have in my `plugins/managesieve/config.inc.php` the default settings:
```
// default contents of filters script (eg. default spam filter)
$config['managesieve_default'] = '/etc/dovecot/sieve/global';

// The name of the script which will be used when there's no user script
$config['managesieve_script_name'] = 'managesieve';
```
everything is working fine, though there is no directory `/etc/dovecot/sieve/global` in my system.

But if I set there the existing (empty) directory:
```
$config['managesieve_default'] = '/usr/local/etc/dovecot/sieve/global';
```
then after clicking on `Settings/Filters` I get in Roundcube's `errors` log the following:
```
[25-May-2019 14:19:46 Europe/Moscow] ERROR: managesieve: line 1: error: unexpected character(s) starting with 0xd2. managesieve: line 1: error: expected end of command ';' or the beginning
of a compound block '{', but found unknown characters. managesieve: line 1: error: unexpected character(s) starting with 0xd2. managesieve: line 1: error: unexpected character(s) starting w
ith 0x00. managesieve: line 1: error: unexpected character(s) starting with 0x00. (3)
[25-May-2019 14:19:46 Europe/Moscow] ERROR: (NONEXISTENT) "Sieve script `managesieve' not found" (3)
```
I tried to create an empty file `/usr/local/etc/dovecot/sieve/global/managesieve`, I even tried to put some sieve script there, the result was the same -- the same errors.

I tried to set 
```
$config['managesieve_script_name'] = '';
```
but that did not help too.

It only works with nonexistent directory in 'managesieve_default'.

On the other hand, the scripts in the directories `/usr/local/etc/dovecot/sieve/before.d` and `/usr/local/etc/dovecot/sieve/after.d` work as expected.

**Comment by alecpl** [comment]
`managesieve_default` is supposed to be a script file not a directory.

**Comment by quicktrick** [comment]
Mmm...  it was not so evident.  Could you please add this info to the default comment to that variable in `config.inc.php`?

I have tried to leave it empty, and it works such a way:
```
$config['managesieve_default'] = '';
```
Thank you for the explanation, Aleksander!

**Comment by alecpl** [comment]
It is strange that file_get_contents() on a dir didn't return false. Anyway, I improved the code and comment to prevent that. Fixed.
