### ISSUE TITLE
zipdownload error

### ISSUE THREAD

**Issue by PetrJakes** [roundcube/roundcubemail#6776]
After installing zipdownload, I have got following error:

[29-May-2019 22:22:37 GMT] PHP Fatal error:  Uncaught Error: Call to undefined method rcube_utils::temp_filename() in /usr/share/apache2/roundcubemail-1.3.9/plugins/zipdownload/zipdownload.php:137
Stack trace:
#0 /usr/share/apache2/roundcubemail-1.3.9/program/lib/Roundcube/rcube_plugin_api.php(493): zipdownload->download_attachments()
#1 /usr/share/apache2/roundcubemail-1.3.9/index.php(289): rcube_plugin_api->exec_action('plugin.zipdownl...')
#2 {main}
  thrown in /usr/share/apache2/roundcubemail-1.3.9/plugins/zipdownload/zipdownload.php on line 137

**Comment by alecpl** [comment]
This plugin version obviously does not work with Roundcube 1.3. Use the plugin distributed with your version of Roundcube.

**Comment by PetrJakes** [comment]
Solved. Thank you.
