### ISSUE TITLE
Roundcube Imap Connection

### ISSUE THREAD

**Issue by Maoie86** [roundcube/roundcubemail#6777]
Hi Guys,

I need help.  Roundcube uses the IP address of the remote client when logging into IMAP.  I dont want that.  I want roundcube to use the IP address of the webserver where roundcube resides.  As this IP address is allowed in the dovecot config.  I searched and found dovecot-ident, but this is the opposite of what i want.  Thanks in advance! :)

**Comment by alecpl** [comment]
What exactly do you mean? Where does it use that address?

**Comment by Maoie86** [comment]
I mean i want it to use the webserver ip address. not the client's ip address. It uses that address when logging into the imap server. I get an error message error loggin in from aaa.bbb.ccc.ddd which is my PCs ip address.
