### ISSUE TITLE
Suggestion: Make web demo

### ISSUE THREAD

**Issue by Kreyren** [roundcube/roundcubemail#6780]
Disclaimer: User looking for FOSS alternative to Gmail.

Recommending making web demo so that new users like me could test sw without deploying to see if it's worth of their time since screenshots are not sufficient.

Rainloop (https://www.rainloop.net/) has this functionality and i liked it.

**Comment by alecpl** [comment]
We do not have resources and time to do this. Roundcube is used by many hosting companies as well as it's included in hosting panels e.g. Plesk, cPanel. We also do not sell our product.
