### ISSUE TITLE
Always ask the user if moving to Trash fails

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#6782]
We have `delete_always` setting that when enabled makes Roundcube to delete the message automatically after moving to Trash fails.

Imo, we should get rid of this setting and always ask the user what to do. We should also display specific error message for OVERQUOTA case.

**Comment by fabianbur** [comment]
We look forward to this feature.

**Comment by alecpl** [comment]
It was not easy to implement a dialog to ask the user about actions to take, so I just removed the config option. User will see an appropriate error message. I think it's still better than having such a confusing option.
