### ISSUE TITLE
Missing files on rsync upgrade

### ISSUE THREAD

**Issue by Nepherim** [roundcube/roundcubemail#6784]
Upgrading from 1.2.2 to 1.3.9, using installto.sh, and I get the error below:

```
rsync: symlink "/PATH/roundcubemail-1.2.2.toupgrade/vendor/bin/crypt-gpg-pinentry" -> "../pear/crypt_gpg/scripts/crypt-gpg-pinentry" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1039) [sender=3.0.6]
Error 500: Failed to execute command: rsync -aC --out-format=%n --delete /PATH/roundcubemail-1.3.9/vendor/ ../roundcubemail-1.2.2.toupgrade/vendor/
```
The symlink crypt-gpg-pinentry is not in the 1.2.2 directory, nor is the file to which it would point ./pear/crypt_gpg/scripts/crypt-gpg-pinentry. Was it included as part of 1.2.2? In fact there are quite a few pear packages that are not in the 1.2.2 pear/ directory -- should they be?

Is there a way to proceed after this fatal error?

**Comment by Nepherim** [comment]
To move beyond this error I copied all files from 1.3.9 ./pear/ to the 1.2.2 pear/ directory, and created the pear/crypt_gpg/scripts/crypt-gpg-pinentry symlink. This fixed the immediate issue.

However, seems like the installer is expecting files which may not have been present during the 1.2.2 version.

**Comment by alecpl** [comment]
Looks like rsync has some problem with symlinks. There "see previous errors" mentioned, so was there more errors before what you pasted?

**Comment by Nepherim** [comment]
No, this was the first error. You now provide two download options, Dependent and Complete. I don't recall this for earlier versions. Could it simply be that the packages were not included before?

Either way, might be helpful to provide some means of moving forward after this type of error. Inability to remove a non existent file is probably not fatal to the upgrade process. Creating the new file probably would be though.

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/releases/tag/1.2.2

If you get complete package it contains `vendor/bin/crypt-gpg-pinentry` link pointing to `../pear-pear.php.net/Crypt_GPG/bin/crypt-gpg-pinentry`. If you get dependent package there's no `/vendor` folder at all.

So, either it's some rsync stupidity or there was someting wrong with your `/vendor` folder. Do you still have the original installation folder? Could you show result of `ls -l vendor`, `ls -l vendor/pear` and `ls -l vendor/pear-pear.php.net`?

I remember that in the past Crypt_GPG installations via composer had this link broken, maybe that's the case. Maybe we'll just have to remove that link before we run that rsync command. I didn't find an rsync option to ignore such errors.

**Comment by Nepherim** [comment]
The reason I bring up Complete vs Dependent is that I don't recall there being the option in 1.2.2. There was one download (although it's a few years back, I could be wrong). For this upgrade I went with Complete. Thus, for 1.2.2 perhaps there was a difference in the vendor directory to current.

Having said all that, here's the directory listings:
```
myuser@xxx [~/apps/roundcubemail-1.2.2]# ls -l vendor
total 36
drwxr-xr-x  8 myuser myuser 4096 Nov 16  2016 ./
drwxr-x--- 13 myuser nobody   4096 Nov 16  2016 ../
-rw-r--r--  1 myuser myuser  183 Sep 28  2016 autoload.php
drwxr-xr-x  2 myuser myuser 4096 Jun  3 15:01 bin/
drwxr-xr-x  2 myuser myuser 4096 Nov 16  2016 composer/
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 kolab/
drwxr-xr-x 14 myuser myuser 4096 Jun  3 15:01 pear/
drwxr-xr-x 10 myuser myuser 4096 Nov 16  2016 pear-pear.php.net/
drwxr-xr-x  4 myuser myuser 4096 Nov 16  2016 roundcube/
myuser@xxx [~/apps/roundcubemail-1.2.2]# ls -l vendor/pear
total 56
drwxr-xr-x 14 myuser myuser 4096 Jun  3 15:01 ./
drwxr-xr-x  8 myuser myuser 4096 Nov 16  2016 ../
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 auth_sasl/
drwxrwxr-x  4 myuser myuser 4096 Mar 31 07:28 console_commandline/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 console_getopt/
drwxrwxr-x  5 myuser myuser 4096 Mar 31 07:28 crypt_gpg/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 mail_mime/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 net_idna2/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 net_ldap2/
drwxrwxr-x  2 myuser myuser 4096 Mar 31 07:28 net_sieve/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 net_smtp/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 net_socket/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 pear-core-minimal/
drwxrwxr-x  3 myuser myuser 4096 Mar 31 07:28 pear_exception/
myuser@xxx [~/apps/roundcubemail-1.2.2]# ls -l vendor/pear-pear.php.net
total 40
drwxr-xr-x 10 myuser myuser 4096 Nov 16  2016 ./
drwxr-xr-x  8 myuser myuser 4096 Nov 16  2016 ../
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 Auth_SASL/
drwxr-xr-x  4 myuser myuser 4096 Nov 16  2016 Console_CommandLine/
drwxr-xr-x  5 myuser myuser 4096 Nov 16  2016 Crypt_GPG/
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 Mail_Mime/
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 Net_IDNA2/
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 Net_LDAP2/
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 Net_SMTP/
drwxr-xr-x  3 myuser myuser 4096 Nov 16  2016 Net_Socket/

```

**Comment by alecpl** [comment]
There's definitely a difference in vendor dir comparing 1.2.2 and new version. However, as I already have proved the complete package contains the link missing in your installation.

I'm not sure it is worth spending time on it. If I have some I'll maybe try to reproduce the issue and see if there's anything we can do.
