### ISSUE TITLE
LDAP Address Book Contact properties empty

### ISSUE THREAD

**Issue by DarthuBer** [roundcube/roundcubemail#6785]
Hi. After upgrading RC from 1.3.5 to 1.3.9 we ebcountered with this problem - in Address Book pane contacts panel is empty.

![image](https://user-images.githubusercontent.com/9078673/58935528-1c800f00-8787-11e9-9fe8-6c14bc0a575f.png)

`2019/06/05 10:21:12 [error] 24723#24723: *6146899 FastCGI sent in stderr: "PHP message: PHP Warning:  Illegal string offset 'count' in /data/sites/roundcubemail/program/lib/Roundcube/rcube_ldap.php on lin
e 1533
PHP message: PHP Warning:  Illegal string offset 'count' in /data/sites/roundcubemail/program/lib/Roundcube/rcube_ldap.php on line 1533
PHP message: PHP Warning:  Illegal string offset 'count' in /data/sites/roundcubemail/program/lib/Roundcube/rcube_ldap.php on line 1533
PHP message: PHP Warning:  Illegal string offset 'count' in /data/sites/roundcubemail/program/lib/Roundcube/rcube_ldap.php on line 1533
PHP message: PHP Warning:  Illegal string offset 'count' in /data/sites/roundcubemail/program/lib/Roundcube/rcube_ldap.php on line 1533" while reading response header from upstream, client: xx.xx.xx.xx,
 server: server, request: "GET /?_task=addressbook&_framed=1&_action=show&_source=source&_cid=Q0490JrQsNC30LDQvdGG0LXQstCwINCQ0LvQtdC60YHQsNC90LTRgNCwINCh0LXRgNCz0LXQtdCy0L3QsCxPVT1JVFJlc291cmNl
LE9VPVVzZXJzLERDPWFsYW1pY3MsREM9bG9jYWw HTTP/2.0", upstream: "fastcgi://127.0.0.1:9002", host: "host", referrer: "referrer?_task=addressbook&_source=source"
`

**Comment by alecpl** [comment]
Check this a35699637d60cb8738

**Comment by alecpl** [comment]
Using net_ldap3 not from git-master might also fix this. I.e. use `"kolab/net_ldap3": "1.0.7"` in composer.json and run composer update.

**Comment by DarthuBer** [comment]
> Check this [a356996](https://github.com/roundcube/roundcubemail/commit/a35699637d60cb873825a0063e23efdaa96c40f1)

This help, thank you.

**Comment by alecpl** [comment]
We'll backport this to 1.3.

**Comment by alecpl** [comment]
Done.
