### ISSUE TITLE
LDAP addressbook 1.4-rc1

### ISSUE THREAD

**Issue by Freack-v** [roundcube/roundcubemail#6786]
Good day!
After the update, there was a bug with a partially working LDAP address book (we use elastic skin, but not only a problem with it), how to reproduce:
1. Start creating a new letter
2. Press the button shown on video (Add contacts)
3. Select the address book LDAP
4. Select the desired contact
5. Click the Insert button or double-click with the mouse, the contact is not inserted, the window does not close, but it works great with the personal address book.

Link for yotube: https://youtu.be/Mjg6mLpA1cU

**Comment by alecpl** [comment]
Works for me in git-master. Do you see any errors in browser console? Does it work if you double-click the contact record?

**Comment by Freack-v** [comment]
There are no errors in the browser console. Double click does not work.

**Comment by alecpl** [comment]
Did you try with disabled plugins? Did you try with different browser? Could you show your `ldap_public` config?

**Comment by Freack-v** [comment]
Plug-ins disconnected (deleted), tried to deploy on a new one, the same problem. The browser also changed, the problem persists.

`$config['ldap_public']['iortpc.ru'] = array(
  'name'          => 'Адресная книга ИОРТПЦ',
  'hosts'         => array('10.XX.XX.XX'),
  'port'          => 3XXX,
  'use_tls'       => false,
  'ldap_version'  => 3,       // using LDAPv3
  'network_timeout' => 10,    // The timeout (in seconds) for connect + bind arrempts. This is only supported in PHP >= 5.3.0 with OpenLDAP 2.x
  'user_specific' => false,   // If true the base_dn, bind_dn and bind_pass default to the user's IMAP login.
  'base_dn'       => 'ou=iortpc,dc=iortpc,dc=ru',
  'bind_dn'       => '',
  'bind_pass'     => '',
  'search_base_dn' => 'ou=iortpc,dc=iortpc,dc=ru',
  'search_filter'  => '',   // e.g. '(&(objectClass=posixAccount)(uid=%u))'
  'search_bind_dn' => '',
  'search_bind_pw' => '',
  'search_bind_attrib' => array(),  // e.g. array('%udc' => 'ou')
  'search_dn_default' => '',
  'auth_cid'       => '',
  'auth_method'    => '',
  'hidden'        => false,
  'searchonly'    => false,
  'writable'       => false,
  'LDAP_Object_Classes' => array('top', 'inetOrgPerson'),
  'LDAP_rdn'       => 'mail',
  'required_fields' => array('cn', 'sn', 'mail'),
  'search_fields'   => array('mail', 'cn'),  // fields to search in
  'fieldmap' => array(
    // Roundcube  => LDAP:limit
    'name'        => 'cn',
    'surname'     => 'sn',
    'firstname'   => 'gn',
    'jobtitle'    => 'title',
    'email'       => 'mail:*',
    'phone:home'  => 'homePhone',
    'phone:work'  => 'telephoneNumber',
    'phone:mobile' => 'mobile',
    'phone:pager' => 'pager',
    'phone:workfax' => 'facsimileTelephoneNumber',
    'street'      => 'street',
    'zipcode'     => 'postalCode',
    'region'      => 'st',
    'country'      => 'c',
    'organization' => 'o',
    'department'   => 'ou',
    'jobtitle'     => 'title',
    'notes'        => 'description',
    'photo'        => 'jpegPhoto',
    // 'manager'       => 'manager',
    // 'assistant'     => 'secretary',
  ),
  'sub_fields' => array(),
  'autovalues' => array(
  // 'uid'  => 'md5(microtime())',               // You may specify PHP code snippets which are then eval'ed 
  // 'mail' => '{givenname}.{sn}@mydomain.com',  // or composite strings with placeholders for existing attributes
  ),
  'sort'           => 'cn',         // The field to sort the listing by.
  'scope'          => 'sub',        // search mode: sub|base|list
  'filter'         => '',      // used for basic listing (if not empty) and will be &'d with search queries. example: status=act
  'fuzzy_search'   => true,         // server allows wildcard search
  'global_search' => true,    // perform a global search for address auto-completion on compose  
  'vlv'            => false,        // Enable Virtual List View to more efficiently fetch paginated data (if server supports it)
  'vlv_search'     => false,        // Use Virtual List View functions for autocompletion searches (if server supports it)
  'numsub_filter'  => '(objectClass=organizationalUnit)',   // with VLV, we also use numSubOrdinates to query the total number of records. Set this filter to get all numSubOrdinates attributes for counting
  'config_root_dn' => 'cn=config',  // Root DN to search config entries (e.g. vlv indexes)
  'sizelimit'      => '0',          // Enables you to limit the count of entries fetched. Setting this to 0 means no limit.
  'timelimit'      => '0',          // Sets the number of seconds how long is spend on the search. Setting this to 0 means no limit.
  'referrals'      => false,        // Sets the LDAP_OPT_REFERRALS option. Mostly used in multi-domain Active Directory setups
  'dereference'    => 0,            // Sets the LDAP_OPT_DEREF option. One of: LDAP_DEREF_NEVER, LDAP_DEREF_SEARCHING, LDAP_DEREF_FINDING, LDAP_DEREF_ALWAYS
                                    // Used where addressbook contains aliases to objects elsewhere in the LDAP tree.
//  'groups'  => array(
//  'base_dn'           => 'ou=test,dc=iortpc,dc=ru',
//    'scope'             => 'sub',       // Search mode: sub|base|list
//    'filter'            => '(member=uid)',
//    'object_classes'    => array('top', 'groupOfNames'),   // Object classes to be assigned to new groups
//   'member_attr'       => 'member',   // Name of the default member attribute, e.g. uniqueMember
//    'name_attr'         => 'cn',       // Attribute to be used as group name
//    'email_attr'        => 'mail',     // Group email address attribute (e.g. for mailing lists)
//    'member_filter'     => '(objectclass=*)',  // Optional filter to use when querying for group members
//    'vlv'               => false,      // Use VLV controls to list groups
//   'class_member_attr' => array(      // Mapping of group object class to member attribute used in these objects
//      'groupofnames'       => 'member',
//      'groupofuniquenames' => 'uniquemember'
//    ),
//  ),
//  'group_filters' => array(
//   'departments' => array(
//      'name'    => 'Company Departments',
//      'scope'   => 'list',
//      'base_dn' => 'dc=iortpc,dc=ru',
//      'filter'  => '(objectClass=groupOfNames)',
//      'name_attr' => 'cn',
//    ),
//    'customers' => array(
//      'name'    => 'Customers',
//      'scope'   => 'sub',
//      'base_dn' => 'ou=cust,dc=iortpc,dc=ru',
//      'filter'  => '(objectClass=inetOrgPerson)',
//      'name_attr' => 'sn',
//    ),
//  ),
);
`

**Comment by alecpl** [comment]
According to defaults.inc.php: "Array key must contain only safe characters, ie. a-zA-Z0-9_". So, change `$config['ldap_public']['iortpc.ru']` to `$config['ldap_public']['iortpc_ru']`.
