### ISSUE TITLE
Table dictionary contains additional id column which is not used by other engines.

### ISSUE THREAD

**Issue by Nepherim** [roundcube/roundcubemail#6788]
Upgrading from 1.2.2 to 1.3.9, using installto.sh, and I got an error along the lines "Table dictionary contains additional id column which is not used by other engines.", [same as this issue](https://github.com/roundcube/roundcubemail/issues/5730).

Everything seems to work though.

**Comment by alecpl** [comment]
This was supposed to be fixed in 1.3. What database are you using?

**Comment by Nepherim** [comment]
MySQL 5.6.41-84.1.

**Comment by alecpl** [comment]
Then this does not make sense to me. Does not sound like the issue you refer to. What error do you get exactly? Was it vanilla 1.2.2 installation or an upgrade from some early version?

**Comment by Nepherim** [comment]
From the web installer:
```
DB Schema:  NOT OK(Database schema differs)
Missing columns in table 'dictionary': id

You should run the update queries to get the schema fixed.
```
This is an install that originated from the first releases -- back to 0.5 or whatever the initial one was. Over the releases it's hit a few road-bumps, so this error *could* be the result of one of those other failed and fixed upgrades at some point.

**Comment by alecpl** [comment]
I still don't see the problem. There should be "Update" button below that text. Did you use it?

**Comment by Nepherim** [comment]
When using the Update button:
`Database schema update failed.
`

**Comment by alecpl** [comment]
Check the error log or run the `bin/updatedb.sh --dir=SQL --package=roundcube` script by hand.

**Comment by Nepherim** [comment]
Output of the `updatedb.sh` script:
```
Updating database schema (2013052500)... [FAILED]
Error 500: Error in DDL upgrade 2013052500: [1050] Table 'cache_shared' already exists

```

**Comment by alecpl** [comment]
Something is messed up in your database. The db-version for 1.2.2 in `2015111100` and this is what you should have in `system` table. Here it looks like Roundcube tries to run upgrade scripts for older version. You'll have to fix it manually, by comparing the structure, going throughout the scripts in `SQL/mysql` and executing what's needed.

**Comment by Nepherim** [comment]
Yeah, over time I suspect various upgrade issues compounded. Thanks for the pointer to the db version in `system` table. I went through and verified tables, columns, and constraints against the `mysql.initial.sql` script, and updated the system table, so everything should now be consistent. 

Thanks.
