### ISSUE TITLE
Add "disabled" option for address book entry, to prevent display in adresee helper list at mail composition.

### ISSUE THREAD

**Issue by lv01jsi** [roundcube/roundcubemail#6790]
Add "disabled" option for address book entry, to prevent display in addressee helper lists (To:, Cc:, Bcc: ) at mail composition.
We like to keep an address in our address book, but do not show it when composing mail, to prevent occasional selection of such address.
If button [Compose] is clicked in “Contacts” screen such address should go for “To:” as it is now. No changes there.

**Comment by alecpl** [comment]
This sounds to me like a very specific use-case not many will need.

**Comment by lv01jsi** [comment]
Other option may be setting such property on address book itself ?

**Comment by alecpl** [comment]
Wontfix. Use `autocomplete_addressbooks` option or write a plugin.
