### ISSUE TITLE
Problem with image in signature. Roundcube 1.3.9

### ISSUE THREAD

**Issue by rafiiplus** [roundcube/roundcubemail#6791]
I have a problem with image in signature footer. 
When I put image into signature via html composer, the reciepent don't see image. 
The code in html is wrong. (see attachment). 

![round_error](https://user-images.githubusercontent.com/51440820/59023579-64b73400-8850-11e9-91d2-17f715a4e8b9.jpg)

**Comment by alecpl** [comment]
Provide the full message source. Does it display properly when you edit the signature in Settings > Identities? Does it look good in the mail composer before you send the message?

**Comment by rafiiplus** [comment]
The image display properly in Settings Identities. Looks good when You comp
![problem_r2](https://user-images.githubusercontent.com/51440820/59024908-3edf5e80-8853-11e9-9316-50ad7bdcb068.jpg)
ose the email.

**Comment by alecpl** [comment]
Please, provide it as text so I can test it on my system. These backslash characters should not be there. Can you check the HTML code in the identity or mail composer?

What browser are you using? What PHP/OS version?

**Comment by alecpl** [comment]
Also, try with disabled all plugins. And maybe try to save the signature again.

**Comment by rafiiplus** [comment]
I installed clean version without plugins. It was the same. 
I prepared the new one signature.  It was the same. 
I tested on 3 diffrent browsers. It was the same. 
PHP: 5.3.8

**Comment by alecpl** [comment]
Roundcube 1.3 requires PHP 5.4.
