### ISSUE TITLE
Next/Prev button in mail view does not work with multi-folder search result

### ISSUE THREAD

**Issue by kasjanpl** [roundcube/roundcubemail#6793]
problem present on version 1.3 and 1.4,
1. search for email, select scope all (search in all folders)
2. on result list open any email and click next/prev message button
3. if you switch using next/prev button from messages in different folders you will get error unable to download message from server

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
