### ISSUE TITLE
Erreur SMTP (535) : authentication failed

### ISSUE THREAD

**Issue by charliecombebias** [roundcube/roundcubemail#6794]
Hi,

I am gertting the message in the subject above when trying to send an email. I have seen the comments and the recommandation but they don t make any sense t me and I have no idea what they mean.

Can someone provide me with a step by step solution (where to go, what the change and what to look for so i can fix the problem

Many thanks

Charlie

**Comment by alecpl** [comment]
No. We require basic technical level here. Use mailing list or forum.
