### ISSUE TITLE
Elastic: display_next in mobile view causes mailbox to jump to message display

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6795]
Using rc git master. Elastic skin in layout-small or layout-phone. `display_next` (After message delete/move display the next message) enabled.

Use the select option (the tick boxes in the message list) to select one or more messages from the message list then open the toolbar and delete the selected message(s). Once the delete action has completed the next message in the list is automatically displayed, the view jumping from the message list to message display.

IMO the `display_next` option should only trigger if you are currently viewing a message.

This was reported as a bug in my `swipe` plugin but I found the same thing happened with `contextmenu` too and traced it back to the `display_next` option. At first, I thought it was not exactly an rc bug as it happened in functionality added by plugins but using the tick boxes to select messages from the list you can trigger the same behavior so I think that makes it a bug.

**Comment by alecpl** [comment]
You don't need checkboxes to mark multiple messages and delete them, so it can be easily reproducible with other skins. This wasn't a problem in desktop mode (or old skins), but in mobile mode it might be indeed unwanted behavior. We should change that so it opens/selects the next message only after you delete the previewed message.

**Comment by alecpl** [comment]
That's not all. We have the same problem in Contacts, but there's no config option there. It's just the hardcoded behavior. So, either we add an option for contacts or use the same option there (and fix it the same way) or we change the default behavior there.

**Comment by alecpl** [comment]
Pull request created in #6799. It requires some more testing. We may also add display_next handling for Identities and Resources.

**Comment by alecpl** [comment]
Merged. I decided to not implement this for identities/responses as they are not problematic (do not have multi-selection) and are kind of different, as PGP keys and Filters. So, for now let's treat Settings section different.
