### ISSUE TITLE
1.4-RC1 is causing spurious Apache 401 errors

### ISSUE THREAD

**Issue by darren12345** [roundcube/roundcubemail#6800]
More info here: https://superuser.com/questions/1446728/what-is-causing-this-apache-401-error

RC-1 is causing a 401 error in Apache when accessing the Roundcube login page (/mail in my case) and when logging out. This is particularly annoying in my case as it is triggering a fail2ban rule and therefore blocking access to users:
```
X.X.X.X - - [13/Jun/2019:09:08:15 +0100] "GET /mail/ HTTP/1.1" 401 2953 "https://mydomain.co.uk/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
X.X.X.X - - [13/Jun/2019:09:08:24 +0100] "GET /mail/?_task=logout&_token=2rmxQckaPc31iZ353SBcxLp3SJ7ZYfZW HTTP/1.1" 401 2996 "https://www.mydomain.co.uk/mail/?_task=mail&_mbox=INBOX" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
```
After plenty of troubleshooting I am unable to find the cause of this (more info in linked SE question).
I have reproduced this on a fresh/standard install of Debian 9.9 and Roundcube with no customisation whatsoever so I believe it is a bug in Roundcube.

**Comment by alecpl** [comment]
This is a new feature. We return 401 when user is not logged in. The code is in index.php and it can be modified by a plugin.

**Comment by darren12345** [comment]
FFS, I've wasted ages on this. That is, IMO, a dumb feature. It triggers as soon as you hit the login page, so by definition you are not logged in and shouldn't expect someone to be at that stage.

**Comment by darren12345** [comment]
@alecpl when you say it can be modified by a plugin, does such a plugin exist and can you point me to it?

**Comment by alecpl** [comment]
I don't know such a plugin, but all you need would be to use `unauthenticated` hook.

**Comment by darren12345** [comment]
For the moment I have just commented out the offending lines in index.php which has solved my problem.
