### ISSUE TITLE
Exclude junk folder from new mail check

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#6801]
With the `check_all_folders` option enabled, the check-recent action also triggers for new messages appearing in Spam folder. That's probably not what people expect and thus special folders like Junk and Trash could be excluded from the mailbox list used for recent checks.

Maybe this can be reduced to the `newmail_notifier` plugin or even made configurable in user prefs.

**Comment by thomascube** [comment]
Via Twitter: https://twitter.com/OdisRiedl/status/1139179656635211776

**Comment by alecpl** [comment]
The plugin already ignores these folders https://github.com/roundcube/roundcubemail/blob/master/plugins/newmail_notifier/newmail_notifier.php#L69

**Comment by karloluiten** [comment]
Hi! According to @alecpl it should not notify on new spam messages, but it does notify new spel msgs for me. 

In the line you highlighted I see "junk_mbox". Could I get the alerts because I use a Maildir, not mbox?

**Comment by karloluiten** [comment]
I see that this exception is not in the latest stable (1.3.9) yet. This can be closed, as apparently it is fixed. I just do not have the new version yet.
I'll try to figure out how to get it properly :)

**Comment by alecpl** [comment]
Indeed. Here's the commit https://github.com/roundcube/roundcubemail/commit/a1cbbf09c1cb2d7668baf6f268946bf530154d0d#diff-fe2f5e927b99e4948fbb5abbacd19cfb.
