### ISSUE TITLE
Folder and Mailbox sizes

### ISSUE THREAD

**Issue by Brian888Brian** [roundcube/roundcubemail#6804]
The sizes of  individual Folders are readily available.
Could the size of the entire Mailbox be displayed somewhere please ?

**Comment by alecpl** [comment]
It is displayed if your imap server provides quota information. Otherwise it would be slow to get size of every folder. You can write a plugin to do this.

**Comment by jfcherng** [comment]
Is this what you are finding? https://plugins.roundcube.net/packages/jfcherng/show-folder-size
