### ISSUE TITLE
Emails are delivered in SPAM on Gmail and Outlook

### ISSUE THREAD

**Issue by pdsolutions** [roundcube/roundcubemail#6808]
Hello,

I have Roundcube Webmail 1.3.8 and SPF, DKIM, DMARC ....OK, the IP 82.223.11.111 is not blacklisted and has not a negative reputation.

I suspect that the emails sent are delivered into SPAM folder cause of  Roundcube HTML format, witch i tested on https://validator.w3.org/#validate_by_input and it contains a lot of errors and warnings.

Please see the attached screenshots.

Thank you in advance.
![Captura de pantalla 2019-06-18 a las 16 49 05](https://user-images.githubusercontent.com/46190904/59694512-0c394c80-91e9-11e9-95f4-afe7f620e0a7.png)
![Captura de pantalla 2019-06-18 a las 16 49 14](https://user-images.githubusercontent.com/46190904/59694513-0c394c80-91e9-11e9-8977-c813c0129a0a.png)
![Captura de pantalla 2019-06-18 a las 16 51 09](https://user-images.githubusercontent.com/46190904/59694751-69cd9900-91e9-11e9-8438-f760bc353acc.png)
![Captura de pantalla 2019-06-18 a las 16 51 15](https://user-images.githubusercontent.com/46190904/59694752-69cd9900-91e9-11e9-8c12-9f3a5d9b97ec.png)
![Uploading Captura de pantalla 2019-06-18 a las 16.51.19.png…]()
![Uploading Captura de pantalla 2019-06-18 a las 16.51.53.png…]()

**Comment by alecpl** [comment]
You're validating quoted-printable encoded content. That can't be valid. Anyway, I really don't think Gmail is validating HTML content. It's probably something else, but we don't know what and if I'm correct there's no way to get that information from Gmail.

**Comment by i3130002** [comment]
I know this is old, though I'm having a similar problem(I guess). I sent messages from Cpanel roundcube and it goes to gmail spam, where as if I send it with Gmail Android client using smtp it goes to inbox.
What can I provide to hel fixing the issue?(while keeping my server address secret) 
I'll check other cpanel webmail clients to be sure it's a roundbox issue not Cpanel configuration.
Meanwhile please tell me what else can I do?
Thanks
