### ISSUE TITLE
Failed logins info

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#6809]
If RCM has got ALERT response from IMAP server after AUTHENTICATE LOGIN,
seems it should be presented to user (not only "Login failed" msg) according to RFC 3501

for ex (from dovecot)
C: A0002 AUTHENTICATE LOGIN
...
S: A0002 NO [ALERT] country blocked

RCM git.

**Comment by alecpl** [comment]
Duplicate of #5060.
