### ISSUE TITLE
Ctrl+A should select all messages in message list

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#6813]
It would be nice if Roundcube would select all messages when pressing Ctrl+A in the message list and one message is highlighted.

**Comment by alecpl** [comment]
Why not. One question though: Should it select all pages or only the current one? Imo only the current page selection would be a simpler option to implement and probably more expected.

**Comment by smares** [comment]
I'd say only the current page (= all currently visible messages), that is what I would expect.

**Comment by jtackaberry** [comment]
Bonus points if hitting ctrl-a twice would select all messages in the list (honoring search filters if applicable).  Maybe the first ctrl-a could show a subtle tooltip style popup somewhere saying "Press ctrl-a again to select messages on all pages" if there are more than 1 pages available.

**Comment by smares** [comment]
I think this could be dangerous, I don't know any program that would select items currently not visible due to pagination.

**Comment by alecpl** [comment]
Implemented.
