### ISSUE TITLE
Plugin icons are not displayed in settings in Elastic

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#6814]
In the Larry interface the icons of plugins are presented in this way:
![rcb1](https://user-images.githubusercontent.com/2455005/59927393-f9e62b00-9401-11e9-8027-273ef785f70e.jpg)

In Elastic there is no icon and it looks a bit strange:

![rcb2](https://user-images.githubusercontent.com/2455005/59927554-5a756800-9402-11e9-96ec-590fede2c2c7.jpg)

I am using Roundcube 1.4 RC1

Thank you

**Comment by alecpl** [comment]
Well, that is up to the plugins to provide Elastic skin support.

**Comment by alecpl** [comment]
Actually, maybe we could provide a default for Settings and Preferences lists.

**Comment by alecpl** [comment]
Fixed.

**Comment by fabianbur** [comment]
Thanks
