### ISSUE TITLE
Workaround for attachments with invalid content type (e.g. PDF)

### ISSUE THREAD

**Issue by mvorisek** [roundcube/roundcubemail#6816]
This http://m-mvorisek-old.mvorisek.com/?dir=safe&a=bS1taWNoYWVsLXZvcmlzZWstY3ovbS1wdWJsaWMtcmNfZW1haWxfYXR0YWNobWVudF9ub3Rfc2hvd24uZW1s email has an pdf attachment, but it is not shown in the UI, i.e. it can not be downloaded.

Using Roundcube Webmail 1.3.8.

Can you replicate and fix? Please handle the email as sensitive file, I will remove it once fixed.

**Comment by alecpl** [comment]
Works for me, but there's a problem with content type. The attachment part header is 'Content-Type: PDF` which obviously is wrong.

So, for me it works, I can see and download the attachment. Only when using Open action it will display a warning "This attachment is suspicious because its type doesn't match the type declared in the message..." and indeed clicking "Show it anyway" will display plain text not pdf. This part we could fix maybe.

**Comment by alecpl** [comment]
That may not be that easy because (at least on my imap server) the invalid content-type causes invalid BODYSTRUCTURE in imap response. So, if it's broken there it might be harder to workaround.

Maybe it could be done similar to #6729.

**Comment by mvorisek** [comment]
The .eml was downloaded directly from RC, is it really an Imap server issue then?

Btw. when I choose forward, the attachment is added as `Part 2 (0 B)`.

**Comment by alecpl** [comment]
First of all it's a bug in the sending client. "PDF" is not a valid Content-Type value. What IMAP server does with it is another story. The forwarding bug you describe might be another issue I didn't investigate yet.

**Comment by alecpl** [comment]
I couldn't reproduce the forward issue. This is probably more an issue on your imap server. I'm guessing that it might return invalid (dummy) BODYSTRUCTURE response for this message/part. imap_debug log could confirm that.

**Comment by mvorisek** [comment]
I understand, but can you explain why the .eml can be downloaded from/via RC without any issue, but RC does not display the attachment then? It seems like some parsing issue in RC to me. My IMAP server is (the latest) hMailServer.

**Comment by alecpl** [comment]
Roundcube does not parse email. It fetches the email structure information from the imap server. You can see this when you enable imap_debug in Roundcube.

**Comment by mvorisek** [comment]
Closing as this is hMailServer issue.
