### ISSUE TITLE
Nested conditioning skin markup behaves weirdly

### ISSUE THREAD

**Issue by jfcherng** [roundcube/roundcubemail#6818]
Environment
------------

- RC: official git repo here, master branch
- PHP: both 5.6.40 and 7.4.0-dev are tested with the same results

Problem
--------

Since I don't see a note in [Wiki](https://github.com/roundcube/roundcubemail/wiki/Skin-Markup#roundcubeifelseifelseendif) that RC's skin markup does not allow doing this common template feature, I consider this as a bug.

![image](https://user-images.githubusercontent.com/6594915/59975092-b13b9700-95e6-11e9-9a2f-e2e644b48673.png) => outputs `A C` (Good)

![image](https://user-images.githubusercontent.com/6594915/59975070-67eb4780-95e6-11e9-9349-ed2ef1910af1.png) => outputs `D` (**Bad**, should be `B C`)

![image](https://user-images.githubusercontent.com/6594915/59975106-ce706580-95e6-11e9-8876-b4abe7ad68a9.png) => outputs `B C D` (**Bad**, should be `D`)

![image](https://user-images.githubusercontent.com/6594915/59975116-efd15180-95e6-11e9-9688-d6c9368a33f6.png) => outputs `B C D` (**Bad**, should be `D`)

Reproducer
------------

I replace the whole `skins/elastic/templates/login.html` with the following codes and visit the login page to do above tests.

```html
<roundcube:if condition="0" />
	<roundcube:if condition="0" />
		A
	<roundcube:else />
		B
	<roundcube:endif />
		C
<roundcube:else />
	D
<roundcube:endif />
```

**Comment by alecpl** [comment]
This is indeed a limitation of our template engine. We should document that. Fixing this is not trivial and also not a high prio.

**Comment by PrachiChi** [comment]
project

**Comment by PrachiChi** [comment]
how to pull project

**Comment by vaso123** [comment]
This is a must have feature. Maybe that could be an option, if you should tag your condition with a name. 

For example:

```
<roundcube:if condition="config:something_enabled=='1'" name="something" />
Say something here
    <roundcube:if condition="config:anything_enabled=='1'" name="anything" />
        Say anything here
    <roundcube:endif name="anything" />
    More something
<roundcube:endif name="something" />
```
It is insane that now I feel this template engine is good for nothing, and I always should use objects, mixing languages and do the HTML output from PHP.

**Comment by vaso123** [comment]
Ok guys, the best way is if you compelety change the roundcube engine. Absolutelly unusable.

Here is my solution.

https://github.com/vaso123/Twiggy/blob/master/twiggy.php

Use twig. My example of course only a skeleton, but you can improve it.

**Comment by jfcherng** [comment]
I like Twig personally since I have used it in my several projects. But I don't think it would be used in official RC because it will just break every (custom) skins created before, which is a big BC break imo.

**Comment by alecpl** [comment]
Fixed.
