### ISSUE TITLE
/mail/?_task=mail&_action=getunread

### ISSUE THREAD

**Issue by Artem2710** [roundcube/roundcubemail#6820]
Tell me why I periodically have such errors?
mail roundcube: <gp4leel6> PHP Error: Error loading template for  in /var/www/roundcubemail-1.3.8/program/include/rcmail_output_html.php on line 613 (GET /mail/?_task=mail&_action=getunread)

**Comment by alecpl** [comment]
getunread action is supposed to be an ajax GET request. It looks like for some reason a path for non-ajax requests is selected. An ajax requests in Roundcube have `_remote=1` set in GET or POST. So, looks like that argument is missing in this case.

**Comment by Artem2710** [comment]
I made for a roundcube progressive web app. This error occurs when I use the mobile version. Can an error appear because of this?

**Comment by alecpl** [comment]
I have no idea what are you talking about. What mobile version exactly?

**Comment by Artem2710** [comment]
For mobile version I use roundcube +

**Comment by alecpl** [comment]
Then I have no idea. We do not support external skins and plugins. This can be caused by a plugin or your app. Does it work without your app?

**Comment by Artem2710** [comment]
My application works fine, but sometimes this error appears
