### ISSUE TITLE
Allow opening application/octet-stream attachments according to filename extension

### ISSUE THREAD

**Issue by tnt** [roundcube/roundcubemail#6821]
Hope this is no duplicate. 

When an attachment for  example is named `invoice.PDF` instead of `invoice.pdf` the "open" option is greyed out and clicking on the link results in downloading the file instead of opening it in a new window. Unfortunately people are sending quite often such files (probably created with Windows software...).

**Comment by alecpl** [comment]
Most likely the Content-Type header is wrong. Could you provide a sample message?

**Comment by tnt** [comment]
I've checked it and you are right: mime-type "application/octet-stream" was already in the mail. (I should have checked that in the first place - sorry.)

Thank you for your quick response. If standards violating mails are not supported and there is no workaround for the issue it is of course completely agreeable to me if you close this issue.

**Comment by alecpl** [comment]
I think, for application/octet-stream attachments we could consider setting the mimetype according to filename extension, in a way that will allow us opening the file. We do some checks based on extension, so we should do similar thing when checking "Open" action state.

**Comment by tnt** [comment]
Great, thank you!

**Comment by jup31** [comment]
Does this enhancement has been published. We need it for a long time on our company ;-) as we are using Bluemind solution based on round cube.

**Comment by jup31** [comment]
Thanks for adding it on 1.5-beta. This issue is impacting around 400 people in our company since 2015 at least. Ticket as been open in 2015 on Bluemind support but unfortunately not forward to the community.

**Comment by alecpl** [comment]
Fixed.
