### ISSUE TITLE
How to build 1.4 rc1 from source

### ISSUE THREAD

**Issue by davidfavor** [roundcube/roundcubemail#6823]
There seems to be no 1.4 git tag.

Someone let me know correct sequence to pull the 1.4 tag/branch + build from source.

Maybe just do a git pull + build from the master.

Thanks.

**Comment by alecpl** [comment]
It's not branched-off yet, so you can use master. If you need RC1 use v1.4-rc1 tag.

**Comment by davidfavor** [comment]
Thanks!
