### ISSUE TITLE
SMTP Error (535): Authentication failed

### ISSUE THREAD

**Issue by Artem2710** [roundcube/roundcubemail#6826]
Hello. Please tell me why when sending an email I get an error SMTP Error (535): Authentication failed. Before this error was not. In the nginx logs, this is the error: 2019/06/27 14:37:24 [error] 1040#0: *4785 FastCGI sent in stderr: "PHP message: ERROR: Invalid response code received from server (535)" while reading response header from upstream, client: 109.86.200.69, server: _, request: "POST /mail/?_task=mail&_unlock=loading1561635439212&_lang=en_US&_framed=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "mail.maillinker.com", referrer: "https://mail.maillinker.com/mail/?_task=mail&_action=compose&_id=14363167185d14aa672a879"

**Comment by alecpl** [comment]
535 is an SMTP error code. Looks like a problem with authentication. You can enable smtp_debug in Roundcube to see the full conversation with SMTP server.

**Comment by Artem2710** [comment]
this is my debug 
![2019-06-27_1641](https://user-images.githubusercontent.com/38757512/60271590-51513300-98fb-11e9-800e-2a8291033c68.png)

**Comment by Artem2710** [comment]
I managed to fix
