### ISSUE TITLE
empty Message ID

### ISSUE THREAD

**Issue by piuma** [roundcube/roundcubemail#6827]
I've found that roundcube mail version 1.3.8 and 1.3.9 generates an empty Message-ID.

Steps to reproduce:
1. send an email
2. go to Sent folder
3. check the email and download (.eml)
4. The header filed Message-ID looks like:
`    Message-ID: >`

**Comment by alecpl** [comment]
I do not confirm that. Did you try with disabled all plugins? What PHP version? Could you try to send an email with smtp_debug and imap_debug enabled (there you can see what exactly is sent to servers)? Is the message really malformed on the server or it's a download issue?

**Comment by piuma** [comment]
a custom plugin broke the message-id, sorry for the rumor
