### ISSUE TITLE
RoundCube doesn't create logs

### ISSUE THREAD

**Issue by wladwell** [roundcube/roundcubemail#6830]
I've added:

// system error reporting, sum of: 1 = log; 4 = show
$config['debug_level'] = 1;
 
// log driver:  'syslog', 'stdout' or 'file'.
$config['log_driver'] = 'file';
 
 
// Log sent messages to <log_dir>/sendmail or to syslog
$config['smtp_log'] = true;
 
// Log IMAP conversation to <log_dir>/imap or to syslog
$config['imap_debug'] = true; 

but no logs at all!
What can I do whith this?

**Comment by alecpl** [comment]
Check web server logs. Check permissions to logs folder.
