### ISSUE TITLE
Outlook destroys tinyMCE styles

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#6831]
Roundcube in version 1.4-RC1
Elastic skin (however with other skins issue also exists).
All messages are displayed in HTML and composed in HTML.
Verdana 10pt is set as default font for email editor.

Issue is seen only when replying to messages which were composed in MS Outlook. CSS styles inserted to message body by MS Outlook take precedence over tinyMCE styles from Roundcube, therefore - even though Verdana is set as our default font - message is composed in Times New Roman.

Screenshot attached.
![obraz](https://user-images.githubusercontent.com/24810145/60423575-ccae2f80-9bee-11e9-98c0-99faf05fdbc7.png)

**Comment by alecpl** [comment]
I confirm the issue. However, I'd expect the email style tags(s) inside of the blockquote. Could you provide a sample message source?

**Comment by alecpl** [comment]
Thanks for the sample.

This wasn't easy to fix and is not a small change. I will not backport this to 1.3. Fixed in git-master.
