### ISSUE TITLE
Sender in bold, and not just the subject

### ISSUE THREAD

**Issue by oculos** [roundcube/roundcubemail#6835]
Hi,

It would be good if we could have the name of the sender in bold. Just the subject in bold makes it a bit confusing, sometime it's hard to know if the subject belongs to the previous or next e-mail. An option to select what should be bold on the list view would be even better.

Best,
Francis

**Comment by alecpl** [comment]
I agree that it could use a designer touch. Some clients do this, some make the sender even more prominent, some do the opposite. So, I think this is more a personal preference. On the other hand we definitely don't want to add a setting for such a thing. For now it is a wontfix from me.
