### ISSUE TITLE
back to search result lost order

### ISSUE THREAD

**Issue by kasjanpl** [roundcube/roundcubemail#6836]
1. search for email, select scope all (search in all folders)
2. on result list open any email
3. click back - emails order is changed (column date is selected, but messages are ordered by folder)

**Comment by alecpl** [comment]
Confirmed with git-master. Additional issue, there's no Back button in Elastic skin, though it's not possible to return to the search result.

**Comment by PrachiChi** [comment]
project

**Comment by alecpl** [comment]
Fixed. Backported to 1.3. The Elastic skin issue moved to #6847.
