### ISSUE TITLE
Bug avec plugin roundcube/calendar - Erreur 500 - Page blanche

### ISSUE THREAD

**Issue by Philippe38** [roundcube/roundcubemail#6837]
J'ai installé le plugin Calendar avec toutes les dépendances requisent et malgré cela, quand je cliquais sur l'icône 'Calendrier', j'avais une ereur 500 ainsi qu'une page blanche m'indiquant que celle-ci ne fonctionnait pas.
J'ai passé plusieurs semaines a tester différentes installation de Roudcube et configuration, et j'ai enfin trouvé la solution pour que Calendar fonctionne.
Je ne sais pas si c'est "La" Solution, mais ça fonctionne et je voulais vous les faire savoir car j'ai trouvé vraiment très peu d'information sur ce sujet dans les différents Forums.
Je pense que cela vient du fait que le plugin n'est peut-être pas complètement compatible avec les dernière version de Roundcube.
Il faut modifier une seule ligne, soit en la supprimant, soit en la commentant dans le fichier : 

roundcube/plugins/calendar/lib/calendar_ui.php

Trouver la ligne : $this->cal->register_handler('plugin.resources_searchform', array($this, 'resources_search_form'));

Il semble que ce soit cette instruction qui pose problème. Vous pouvez le vérifier dans les logs d'erreurs de Roudcube, bien que pas explicitement indiqué.

J'espère que cette solution pourra être utile à beaucoup d'entre vous et vous éviter des jours de recherches dans les différents fichiers de configuration Roundcube.

Important !!! Assurez-vous d'avoir installer toutes des dépendances à l'aide de php composer.phar install avant toutes modifications.
php: >=5.3.0
roundcube/plugin-installer: >=0.1.3
kolab/libcalendaring: >=3.3.3

Good Luck

**Comment by alecpl** [comment]
We do not support Calendar plugin here.
