### ISSUE TITLE
Feature Request: Adding contact names to dictionary

### ISSUE THREAD

**Issue by Abatjour3407** [roundcube/roundcubemail#6840]
I cannot over-emphasise how astounded I am about the Roundcube platform, as I have noted before, it is in some ways even better than Gmail.

**I think a great feature to add to this platform would be to automatically add contact names (and even organisation names) to the dictionary automatically.** The advantage of this is that these names are inevitably used in emails. Staying in an area with lots of 'unusual' (African) names, I sometimes have to add a new word for every new person I email.

**An additional thought**: Perhaps it would be worth considering using this as an optional setting for each user (I know of some people who add weird codes before their contact name entries).

Thanks for considering this idea and thanks again for this excellent platform.

**Comment by alecpl** [comment]
There are a few possibilities to implement this.
1. Saving a name to the dictionary whenever the contact is added/deleted/modified might be cumbersome.
2. Checking in addressbook when spellchecking (by checking if words marked as mispelled match any contact name).
3. Creating a script that "indexes" all users' contacts and updates their dictionaries, so it could be run e.g. once a day.

I think I like option 2. most, though it will have impact on performance.

**Comment by alecpl** [comment]
I think we'll not implement this. Adding an exception to the dictionary manually when that happens is not a big deal. And I don't really like any of the options above.
