### ISSUE TITLE
Is Elastic template still maintained ?

### ISSUE THREAD

**Issue by grosjo** [roundcube/roundcubemail#6843]
Hi
I have been trying times to times the elastic theme, but it absolutely unusable 
Screenshot attached

![Screenshot from 2019-07-12 04-11-30](https://user-images.githubusercontent.com/2287111/61099819-8dd47100-a45b-11e9-9b04-93f56f9430e4.png)

I am using Firefox 68, and the git version of roundcube

When will it be at least displaying properly ? or is it just not maintained ?

**Comment by PrachiChi** [comment]
its showing properly check ur net connection

**Comment by alecpl** [comment]
Read INSTALL instructions. Elastic requires css "compilation" and some dependencies installation.
