### ISSUE TITLE
PDO MySql misses flag to disable server certificate validation

### ISSUE THREAD

**Issue by andrepereiradasilva** [roundcube/roundcubemail#6848]
Hi, new here,

Noticed the PDO MySql misses flag to disable server certificate validation (PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT).
This is a recent flag added in PHP 7.0.18 and PHP 7.1.4 that Provides a way to disable verification of the server SSL certificate.
source: https://www.php.net/manual/en/ref.pdo-mysql.php

Maybe by adding
```php
if (!empty($dsn['verify_server_cert']) && (PHP_VERSION_ID >= 70104 || (PHP_VERSION_ID >= 70019 && PHP_VERSION_ID <= 70099)) && defined('PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT')) {
     $result[PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT] = $dsn['verify_server_cert'];
}
```
in https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/db/mysql.php#L143

Then to test
```php
$config['db_dsnw'] = 'mysqli://<user>:<pass>@<ip>:<port>/<database>?ca=<anything>&verify_server_cert=0';
```

**Comment by alecpl** [comment]
Done.

**Comment by andrepereiradasilva** [comment]
thanks
