### ISSUE TITLE
tab on autocomplete in compose causes double insertion

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6850]
tested with git-master and Elastic skin, all plugins disabled.

place the cursor into the To box on the compose screen, start typing a name which triggers the autocomplete, press tab, result: the contact is inserted into the To box twice (it does not make any differnce if you use the arrow keys to change the selection in the autocomplete box or not).

IIRC in 1.4-RC1 it only inserted the contact once but I'm not certain exactly when this started happening.

**Comment by alecpl** [comment]
Fixed.
