### ISSUE TITLE
Delete drafts directly

### ISSUE THREAD

**Issue by mvorisek** [roundcube/roundcubemail#6856]
Almost every mail client can delete drafts directly, i.e. not put them to the trash.

How can be this behaviour enforced for RC?

**Comment by alecpl** [comment]
Which mail client for example? Is it optional or default behavior. I don't like the idea, but will leave the ticket open for some time.

**Comment by fabianbur** [comment]
bad idea

**Comment by alecpl** [comment]
Wontfix.
