### ISSUE TITLE
Error loading template for managesieve.managesieve or managesieve.vacation

### ISSUE THREAD

**Issue by androos** [roundcube/roundcubemail#6857]
I get always this when click on "Filter". Sieve is already working with dovecot in Thunderbird. 
`PHP Error: Error loading template for managesieve.managesieve in /localpath/roundcube/program/include/rcmail_output_html.php on line 613 (GET /?_task=settings&_action=plugin.managesieve)`
When i try clicking on Vaccation i get the same with managesieve.vacation
This is my managesieve/config.inc.php
```

$config['managesieve_port'] = 4190;
$config['managesieve_host'] = 'mail.mydomain.com';
$config['managesieve_auth_type'] = 'plain';
$config['managesieve_auth_cid'] = null;
$config['managesieve_auth_pw'] = null;
$config['managesieve_usetls'] = true;
$config['managesieve_conn_options'] = null;
$config['managesieve_default'] = '';
$config['managesieve_script_name'] = '';
$config['managesieve_mbox_encoding'] = 'UTF-8';
$config['managesieve_replace_delimiter'] = '';
$config['managesieve_disabled_extensions'] = array();
$config['managesieve_debug'] = true;
$config['managesieve_kolab_master'] = false;
$config['managesieve_filename_extension'] = '.sieve';
$config['managesieve_filename_exceptions'] = array();
$config['managesieve_domains'] = array();
$config['managesieve_vacation'] = 1;
$config['managesieve_vacation_interval'] = 0;
$config['managesieve_vacation_addresses_init'] = false;
$config['managesieve_vacation_from_init'] = false;
$config['managesieve_notify_methods'] = array('mailto');
$config['managesieve_raw_editor'] = true;

```

**Comment by androos** [comment]
That's my /etc/dovecot/conf.d/90-sieve.conf  
```

plugin {
  sieve = /srv/vmail/%d/%n/.dovecot.sieve
  sieve_before = /srv/vmail/sieve/spam-global.sieve
}

```

**Comment by alecpl** [comment]
Looks like some generic issue. Are you using custom skin or something? What version?

**Comment by androos** [comment]
I use a slightly changed version of Larry. Truly it seems to work with all other Themes. Would have never expected that. What could be the reason? The only thing I basically changed in my version of the Theme is the name and the watermark.

**Comment by androos** [comment]
Roundcube Webmail 1.3.9

**Comment by johndoh** [comment]
If you created a brand new skin called Truly then you'll need to also make the template files in `plugins/managesieve/skins/truly` see the ones in `/plugins/managesieve/skins/larry` for reference. But it sounds like you have very minor changes to the Larry skin so may be try extending Larry rather than creating a brand new skin, see https://github.com/roundcube/roundcubemail/wiki/Skins#extending-skins.

**Comment by androos** [comment]
Thx. I found another way for me to change the images without changing the skin. I just added them as locations in nginx and 'return' another image.

**Comment by androos** [comment]
Thx. I found another way for me to change the images without changing the skin. I just added them as locations in nginx and 'return' another image.

**Comment by revoltown** [comment]
i have strange issue witch roundcube and spamassassin plus roundcube plugin...
 https://pastebin.pl/view/7f9f5739
