### ISSUE TITLE
Rroundcube 1.4: Autologon redirect only working with exit function

### ISSUE THREAD

**Issue by sritd** [roundcube/roundcubemail#6863]
Hello,

I have downloaded the new rc-1.4-rc1 from your homepage and updated my local test environment with this version. All things are working perfect except one functionality:
autologon needs an additional exit command to work as expected.

I am using autologon to perform single sign on from my central application to all other tools.
All authentication credentials are transferred as encrypted values and autologon will use this values to perform the login. This is working as expected.
If I want to do a logout, I am successfully logged out from the application. I can not use it anymore. The redirect back to my central application is not working. I get a message like 401 Unauthorized. That is standard message from Apache.

If I modify my two functions to include the exit command, then it is working.

```php
function login_failed($args) {
  header('LOCATION: https://test.com');
  # Without this exit statement, the redirect is not working.
  # In the current stable version it is working without exit.
   exit;
}
```

```php
function logout_after($args) {
  header('LOCATION: https://test.com');
  #Without this exit statement, the redirect is not working.
  #In the current stable version it is working without exit.
  exit;
}
```
I want to verify with you, that this is the expected way to get redirects working. It will be great, if the documentation (https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks) will be updated with the information of the statements.

Thank you very much for your reply
and feel free to request further information.

Best regards
Sven

**Comment by AndreasSchantl** [comment]
It's basically best practice to call the ``exit`` function after using the ``header`` function for a redirect as the script doesn't necessarily terminate after that. This is the reason why you are getting an 401 from Apache.

**Comment by sritd** [comment]
You are right. This is best practice. What I do not know: if I call the `exit` function, is roundcube missing something? Is the progress of logout successfully finished?
I thought, that this function will be the last one and nothing more will be processed. But if `exit` is called, there is more code, which is processed. Is this code needed or not?
This question is related to the internal progress from roundcube. I do not want to open a security issue, if I do it that way.

Best regards
Sven

**Comment by alecpl** [comment]
This is expected, indeed.
