### ISSUE TITLE
Adressbook and php 7.3

### ISSUE THREAD

**Issue by linuxuser424** [roundcube/roundcubemail#6864]
Hi @ all,

i use roundcube 1.3.9 with php 7.3.7 and have this error:

`PHP Warning:  preg_replace(): Compilation failed: escape sequence is invalid in character class at offset 8 in /var/www/html/mail/program/lib/Roundcube/rcube_vcard.php on line 547`

when I try to view my saved contacts. This happens on each contact, even those without special characters. 
They are visible in the database table named "contacts" (phpMyAdmin). 

Any suggestions?

**Comment by sritd** [comment]
Hi,

yes, there is a very easy solution for this problem. I had the same behavior two days ago. Please have a look at this issue #6744 or this commit fe90903fa1ff59c0da278fee2ee6a0e1f6273a06.

It is a known issue and a fix is available. The only problem is, that there is no new version at the moment.

Best regards
Sven

**Comment by linuxuser424** [comment]
Hi Sven,

thank you - I had not found this thread. The fix is really easy and it works.

Best regards
