### ISSUE TITLE
[SECURITY] Apparent spearfishing/targeted attempt

### ISSUE THREAD

**Issue by bill-mcgonigle** [roundcube/roundcubemail#6865]
Hi, folks,

I found this lovely targeted message in my box this morning:

  https://imgur.com/a/Gw0ExE9

I presume they're out looking for roundcubemail installations and matching up with admin emails with a purchased/stolen list of addresses.

Perhaps a general advisory would be in order?  I'm guessing this is mostly targeted at users who do one-click installs with their hosting providers, not admins who are actually running their own installs and would be naturally suspicious of malfeasance.   In that case, guidance might be directed towards hosting providers to alert their users that such messages will not be sent to them.

Anyway, FYI, this is in the wild, and thanks for maintaining such a useful project.

**Comment by dowlingw** [comment]
Can confirm that I'm seeing this being sent to users on my mail server (running roundube) also.

Roundcube is reachable via the same hostname as the primary MX record in DNS.

**Comment by alecpl** [comment]
Welcome to the email world. Personally, I prefer to focus on coding. From this perspective there's not much we can do. You can find guidance about targeted phishing in the Internet.

Adding anti-phishing features to Roundcube is another story.
