### ISSUE TITLE
Vacation error

### ISSUE THREAD

**Issue by mcattell78** [roundcube/roundcubemail#6869]
Hi
We use Gridhost to access roundcude, but the vacation settings has started to display an error, every time we click on vacation. We get the below error:

"An error occoured - Error during connection"

This happens on every email account with Gridhost.

We have spoken to Gridhost, and they say its a Roundcude issue!

Can you please confirm if this is a Roundcube issue or Gridhost?

Thank you for any help!

**Comment by johndoh** [comment]
This is a bug tracker not a support forum. Please use the mailinglist or forum for support.

The issue you decribed would be the responsibility of who ever runs your installation of Roundcube, they will have access to the error logs while will probably have more detail about what they problem is and hopefully tell you if its a config issue or a server issue.

**Comment by mcattell78** [comment]
Thanks for this johndoh

**Comment by mcattell78** [comment]
Hi John
Have you the links to the mailinglist or forum for support pages please?

**Comment by johndoh** [comment]
have a look at https://roundcube.net/support/
