### ISSUE TITLE
Composer dependencies: Package phpunit/phpunit-mock-objects is abandoned

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#6870]
In Roundcube RC1 and in master the file composer.json has this line:

"phpunit/phpunit": "^4.8.36 || ^5.7.21"

When installing roundcube in a distribution with php7.3 as debian buster, the following error occurs:

Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.

It is fixed by changing that line and introducing the latest version of phpunit that is compatible with php 7.2 and 7.3, which is 8.2.5, as follows:

"phpunit/phpunit": "^4.8.36 || ^5.7.21 || ^8.2.5"

That way the dependencies are fixed.

I suggest making that change in the composer.json file

**Comment by alecpl** [comment]
We cannot use phpunit 8 without changing our test scripts in a way that is compatible with older phpunit versions. So, this will not gonna happen anytime soon. I'll reconsider after 1.4 release.

**Comment by fabianbur** [comment]
@alecpl I have been using phpunit 8 this time in 1.4 git. Is it advisable not to do it?
So far I have not found errors

**Comment by alecpl** [comment]
Did you try to run Roundcube tests? Since PHPUnit 6 the code is namespaced. So without changing our tests' code you'd get: "PHP Fatal error:  Uncaught Error: Class 'PHPUnit_Framework_TestCase' not found ". And when we change tests' code it will stop working with older PHPUnit versions.

**Comment by johndoh** [comment]
In case it helps with the backwards compatibility discussion I found this in the changelog for PHPUnit 5.7.21:

> Added `PHPUnit\Framework\AssertionFailedError`, `PHPUnit\Framework\Test`, and `PHPUnit\Framework\TestSuite` to the forward compatibility layer for PHPUnit 6

**Comment by alecpl** [comment]
It looks that 4.8 (at least the most recent version in the line) supports `PHPUnit\Framework\TestCase`, so we should be fine if we migrate to that. Then we should probably require:
```
"phpunit/phpunit": "^4.8.36 || ^5 || ^6 || ^7 || ^8"
```
so our tests work on all supported versions

**Comment by johndoh** [comment]
the forward compatibility for 5.x was added in 5.7.21 which was released at the same time as 4.8.36 so i think it should be:

`"phpunit/phpunit": "^4.8.36 || ^5.7.21 || ^6 || ^7 || ^8"`

**Comment by alecpl** [comment]
Done. However, we cannot support v8 yet because of errors like: `Declaration of MailFunc::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void`. It would require dropping PHP < 7.1 support.
