### ISSUE TITLE
Connect to Yandex using RoundCube from sub-domain

### ISSUE THREAD

**Issue by SandeepanSengupta** [roundcube/roundcubemail#6874]
I have installed *RroundCube **(Using PHP)*** on a sub-domain (http://email.risc.work) and using **@yandex** to host mailing services for my domain (http://risc.work).
IMAP is enabled at Yandex and I can access it from Gmail as well using required credential(s)

The **config.inc.php** file at *email.risc.work/htdocs/config/* as configured accordingly as well, as described below

    $config['default_host'] = 'ssl://imap.yandex.com';
    $config['default_port'] = 993;
    
    $config['smtp_server'] = 'ssl://smtp.yandex.com';
    $config['smtp_port'] = 465;
    $config['smtp_user'] = '%u';
    $config['smtp_pass'] = '%p';
    
    $config['ip_check'] = true;
    
    $config['des_key'] = <REDUCTED FOR SECURITY>;

    $config['username_domain_forced'] = true;
    $config['username_domain'] = 'risc.work';

However, each time I try to login from RoundCube at http://email.risc.work, I am getting error stating *Connection to IMAP Server Failed*. I am not getting any such issues as being able to successfully send and receive mail using Gmail with exact same credential.

**Comment by johndoh** [comment]
This is a bug tracker. Please use the mailing list or forum for support issues.

Try disabling certificate verification using the `imap_conn_options` config option.

**Comment by SandeepanSengupta** [comment]
@johndoh 
The closest thing I got are [this](https://bbs.archlinux.org/viewtopic.php?id=187063) and [this](https://www.howtoforge.com/community/threads/solved-roundcube-smtp-error-authentication-failure.73804/) and unfortunately, I am using it roundcube on a shared hosting, and my knowledge is limited too. Please let me know what exactly I have to do to get this thing working.

P.S. [This](https://yandex.com/support/mail/mail-clients/ssl.html) page from Yandex is what I followed during PHP installation, and I can modify config file as I have FTP access to it and I can also modify db if required. I am using cloudflare so let me know if I need to generate cert and upload it.

**Comment by johndoh** [comment]
have a look at https://roundcube.net/support/

**Comment by SandeepanSengupta** [comment]
_Got it_ @johndoh , all I had to do is add

    $config['imap_conn_options'] = array(
    'ssl' => array(
    'verify_peer' => false,
    'verfify_peer_name' => false,
    ),
    );
    
    $config['smtp_conn_options'] = array(
    'ssl' => array(
    'verify_peer' => false,
    'verify_peer_name' => false,
    ),
    );

**after**

    $config['default_host'] = 'imap.yandex.com';
