### ISSUE TITLE
Error Importing Contacts

### ISSUE THREAD

**Issue by rvp-platform** [roundcube/roundcubemail#6881]
I keep getting errors uploading my contacts into roundcube. The error is a '500' error [See screenshots in the comments]. The contact list fits all requirements, I have tried it in csv and vcard - I have made the headers the right way, I saw it in another post. No matter what I do I cannot upload my contacts! What do I do?

**Comment by rvp-platform** [comment]
![SCREEN1](https://user-images.githubusercontent.com/53797366/62496478-a86de180-b79e-11e9-829c-023666c814e9.png)
![SCREEN2](https://user-images.githubusercontent.com/53797366/62496479-a86de180-b79e-11e9-95a6-94ddc05c8ead.png)
![SCREEN3](https://user-images.githubusercontent.com/53797366/62496480-a86de180-b79e-11e9-9e49-d2a644953471.png)

Screen one is how it starts. Then it goes to screen two - finally screen three. Never past screen 3.

**Comment by rvp-platform** [comment]
I've edited the php.ini to not have the 20 limit, and no avail. Hours and hours now, still getting the error and not finding the solution.

**Comment by alecpl** [comment]
Check the Roundcube (or http server) error log.

**Comment by rvp-platform** [comment]
I have someone who is installing all this for me on my domain, but they
aren't giving me any information. Telling me they will give me the link to
bulk upload my contacts, but then they fall off the map for 12 hours, only
to tell me tomorrow it will be fixed. I am not liking this so far, I've
spend over 600 in 48 hours trying to get this up and running.

**Comment by rvp-platform** [comment]
I feel like I've been scammed for reals, this guy isn't helping at all, and I am paying him.

**Comment by rvp-platform** [comment]
My installer helped me. We switched from Roundcube to Mailwizz - it doesn't have limits on imports like Roundcube does.

**Comment by AndradeAlbuquerque** [comment]
Roundcube is very buggy. I have the same issue. My guess is no one knows how to solve it.
