### ISSUE TITLE
'\n' visible when identity has multiple GPG keys

### ISSUE THREAD

**Issue by dktcoding** [roundcube/roundcubemail#6885]
This is a very trivial issue, I recently installed the latest Roundcube `1.4-git [GIT 20190802.1419]`, and when the user has more than one GPG Key a `\n` is visible between the keys.

![Screen Shot 2019-08-06 at 23 49 18](https://user-images.githubusercontent.com/709639/62591289-8317cb00-b8a5-11e9-8987-c382e6aad804.png)

Regards!

**Comment by alecpl** [comment]
Fixed.
