### ISSUE TITLE
Allow sieve filters to filter by address book

### ISSUE THREAD

**Issue by arodier** [roundcube/roundcubemail#6886]
I have written a simple milter, in Python, to add a header when the sender of an email is found in an address book.

The milter code is available here: https://github.com/progmaticltd/roundcube-milters

The milter creates a header X-AddressBook, with the content like this:

Default address book: "X-AddressBook: RoundCube:default"
Specific group (e.g. Personal): "X-AddressBook: RoundCube:Personal"

**Comment by alecpl** [comment]
Thanks. I don't see a good place to mention it in our docs. If it supported other database drivers we could consider including it as part of the managesieve plugin.
