### ISSUE TITLE
incomprehensible characters

### ISSUE THREAD

**Issue by Artem2710** [roundcube/roundcubemail#6892]
Hello, when a letter arrives with attached files in which the file names are in Russian, then when saving to a computer, the file names change to a set of incomprehensible characters. How can this be fixed?

**Comment by alecpl** [comment]
This might be many things. What version? What PHP version? What OS? Is php-mbstring and php-iconv installed? Any errors in log? Did you try with disabled all plugins? Did you try in a different browser?

**Comment by Artem2710** [comment]
Roundcube version: 1.3.8
php version: 7.2
OS: Centos
php-mbstring: not activated in php.ini
The file name is not displayed correctly only when using the Chrome browser on Windows. If I use the Chrome browser on Linux, everything is fine. Other browsers work fine

**Comment by alecpl** [comment]
What Chrome version? What is the original attachment name (in email headers)? Could you check what http headers are in a response to the download request? What type of file it is, is the name broken if you download the file or when you open it in some app?

**Comment by Artem2710** [comment]
![image](https://user-images.githubusercontent.com/38757512/63337684-0d523b80-c34a-11e9-8b90-4018e65b4f10.png)
![image](https://user-images.githubusercontent.com/38757512/63337891-75088680-c34a-11e9-809e-4ca34a87ef77.png)
![image](https://user-images.githubusercontent.com/38757512/63337958-95384580-c34a-11e9-871a-8b34d4e6e7f7.png)

**Comment by Artem2710** [comment]
Is there any way to fix this?

**Comment by alecpl** [comment]
You should install mbstring it's required. Maybe that will help.

**Comment by alecpl** [comment]
Please, provide the message source. You can remove sensitive data.

**Comment by Artem2710** [comment]
I installed mbstring but it did not help. I also installed
`mbstring.language                 = Neutral
mbstring.internal_encoding    = UTF-8
mbstring.http_output              = UTF-8
`

**Comment by alecpl** [comment]
Please, provide the message source or fragments of imap_debug log containing the attachment part headers and BODYSTRUCTURE response. With this I can try to reproduce, otherwise I will not be able to help you.

**Comment by Artem2710** [comment]
I set $config ['imap_debug'] = true; The result is in the attached file.
[encoding.txt](https://github.com/roundcube/roundcubemail/files/3554711/encoding.txt)

**Comment by alecpl** [comment]
Ok, I didn't test Chrome on Windows, but checking the headers I recalled that in 1.4 we changed the way the filename is encoded. This should then work in Chrome, on Windows too. We do not plan to backport this change to 1.3.

See #5772.
