### ISSUE TITLE
In settings , Compose HTML messages  the selected default value should be always

### ISSUE THREAD

**Issue by Rekha-Lanka** [roundcube/roundcubemail#6893]
in settings-->preferences-->composing messages->compose HTML messages:'always' should be default  selected value...

**Comment by alecpl** [comment]
You can set the default value for your users in config file. I don't think we'll change the default, but I'll leave this ticket open for some time to decide.

**Comment by smares** [comment]
Definitely not "always" but maybe "always, except when replying to plain text".

**Comment by alecpl** [comment]
We'll not change the default.
