### ISSUE TITLE
Bypass data URI check in received HTML messages to run JavaScript on supported browsers

### ISSUE THREAD

**Issue by cyrus-and** [roundcube/roundcubemail#6896]
Most (all?) browsers nowadays refuse to navigate to a top-level data URI, but if they do, this can be used to execute arbitrary JavaScript code, yet in the context of the newly created page so the impact is limited if not even zero in practice, but I think this should be fixed.

The check can be bypassed using the `application/xhtml+xml` MIME type that browsers treat as a regular HTML page for what concerns JavaScript code execution, it just need to be valid XML. For example:

```html
<html xmlns="http://www.w3.org/1999/xhtml"><body><script>alert(document.location)</script></body></html>
```

The above can be used to forge a message that bypasses the MIME check:

```html
<a href="data:application/xhtml+xml;base64,PGh0bWwgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGh0bWwiPjxib2R5PjxzY3JpcHQ+YWxlcnQoZG9jdW1lbnQubG9jYXRpb24pPC9zY3JpcHQ+PC9ib2R5PjwvaHRtbD4K">CLICK ME</a>
```

**Comment by alecpl** [comment]
Confirmed. I guess we  should just block anything that starts with `data:application`.

**Comment by alecpl** [comment]
Fixed. I think for `href` attribute we should block any `data:` entries.
