### ISSUE TITLE
Bypass the position: fixed CSS check in received messages

### ISSUE THREAD

**Issue by cyrus-and** [roundcube/roundcubemail#6898]
By simply using a space before the `:` it is possible to bypass the check and move parts of the message over the toolbar.

```html
<style>h1 {position : fixed; top: 0; left: 0;}</style><h1>OVER</h1>
```

This in conjunction to #6897 can be used to implement phishing attempts and/or trick the user into clicking unwanted links. For example, when the below message is displayed, clicking anywhere causes the message to be opened in a new window:

```html
<style>:root a.extwin {position : fixed; top: 0; left: 0; right: 0; bottom: 0; z-index: 999; display: block; opacity: 0.001;} :root body.extwin {display:none}</style>
```

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Fixed.
