### ISSUE TITLE
Bypass URL check in CSS url()

### ISSUE THREAD

**Issue by cyrus-and** [roundcube/roundcubemail#6899]
The following bypasses the URL check (otherwise marked as `/* evil! */`) and causes the browser to issue a request to `http://example.com` after that the user dismisses the "To protect your privacy remote resources have been blocked." warning message by clicking "Allow":

```html
<style>* {x:url(data:image);background: url(http://example.com);}</style>
```

The culprit seems to be:

https://github.com/roundcube/roundcubemail/blob/1afa46d28d42684ed6e7b60ae03ddd181468f991/program/lib/Roundcube/rcube_utils.php#L409-L413

**Comment by alecpl** [comment]
What version did you test with? For me it does not bypass in git-master. The resource is blocked until I allow external resources.

**Comment by cyrus-and** [comment]
> What version did you test with?

Master.

> The resource is blocked until I allow external resources.

Yes, as I said user needs to allow it but usually URLs like `http://example.com` are blocked, i.e., replaced with `/* evil! */`.

For example:

```
<style>* {background: url(http://example.com);}</style>
```

produces:

```
<style type="text/css">#message-htmlpart1 div.rcmBody * {/* evil! */}</style>
````

**Comment by alecpl** [comment]
Hmm.. indeed. This is a bug. According to the code and comments we allow such "strict" url() style. However, there's a bug in this regexp:
```php
$strict_url_regexp = '!url\s*\([ "\'](https?:)//[a-z0-9/._+-]+["\' ]\)!Uims'
```
This need to be fixed.

**Comment by alecpl** [comment]
Fixed the regexp, the rest is non-issue here.
