### ISSUE TITLE
Requests with non-empty path info causes infinite frame nesting

### ISSUE THREAD

**Issue by cyrus-and** [roundcube/roundcubemail#6900]
This is a minor issue but you might want to fix it anyway. For example, loading the following URL (mind the trailing `/`) triggers the issue:

```
http://target.com/index.php/
```

This is due to the relative frame `src` in:

```html
<iframe name="messagecontframe" id="messagecontframe" style="width:100%; height:100%" frameborder="0" src="skins/larry/watermark.html" title="Message preview"></iframe>
```

There may be other instances of the same problem.

**Comment by alecpl** [comment]
That is causing problems not only with watermark, but all other resources (js, css). Fixing this could be not that simple. You're first person with this issue, so I think it's not worth to spend time on this.
