### ISSUE TITLE
Thread view not work on Elastic skin

### ISSUE THREAD

**Issue by SAGOlab** [roundcube/roundcubemail#6905]
I've notice that thread view not group messages on Elastic skin, isn't it? If I'm in wrong excuse me in advance.

I did some test:

1. I've checked this function with multiple email account
1. I've checked on the imap server side and SORT and THREADS key are enable, and are present REF REFERENCES ecc..
2. I've checked with other email client and thread view work correctly, the message are grouped properly.

**Comment by alecpl** [comment]
Works for me. What version? Do you see Threads button in messages list header? Do you see list mode switch in List options dialog? Is it set to "Threads"?

**Comment by SAGOlab** [comment]
version: 1.4-rc1

I'm afraid, no, I not see any button; I'm using gmail account.

some screenshot of my problem, below:

![Schermata da 2019-08-29 15-40-32](https://user-images.githubusercontent.com/24431313/63945347-72591000-ca73-11e9-9af0-376d42aee7c6.png)
![Schermata da 2019-08-29 15-40-54](https://user-images.githubusercontent.com/24431313/63945348-72591000-ca73-11e9-9e93-3da5bf35f540.png)

**Comment by alecpl** [comment]
Gmail IMAP implementation has no THREADS support.
