### ISSUE TITLE
Certain PDF files won't attach

### ISSUE THREAD

**Issue by jwpgroup** [roundcube/roundcubemail#6906]
This is kinda weird.  Last night I created a composite photo file in Photoshop and printed it as a PDF (selecting high resolution).  This (around) 2.7Mb file steadfastly refused to attach in Roundcube 1.38.  

If I then changed the output resolution to (press) which is higher, the 5.6Mb ish file attached fine.

This is NOT the first time this has happened, but I'm afraid I've not kept the other 'solutions' or examples of what didn't work before.

I'd rather not share these files in a public forum, (as they relate to a complaint against a public body), but I'm happy to  do so privately of course.

Many thanks in advance for any help

John
(first time visitor to these parts)

**Comment by alecpl** [comment]
We'll need your configuration, php version. What browsers did you try? Did you try with disabled plugins? What plugins? What is the error? Anything in Roundcube log or browser console? Is this 100% reproducible with this pdf file you've got?

**Comment by jwpgroup** [comment]
Hi  Thanks for responding.

Roundcube is 'bundled' with Plesk's web host edition on our cloud server.  In this context I'm not sure of what you mean by 'configuration', but the OS is CentOS Linux 7.6.1810 (Core) with Plesk Onyx 
Version 17.8.11 Update #65.  On the PHP front, FPM and FastCGI are at 7.2.21.

Unless any plug-ins are installed by default I'm not using any.  It's a vanilla install.

Browser wise I'm using Chrome 76.0.3809.132 (Official Build) (64-bit), but I've just checked in I.E. 11.01.135 and it's exactly the same.

I've attached a screengrab of the error.

![RoundCubePDFerror](https://user-images.githubusercontent.com/54676708/64025650-135bcf80-cb35-11e9-9701-99bfa046e642.png)

Assuming logs on the server are saved to... /usr/local/topicdesk/roundcube/WebApp/logs/
I don't even have that path.

Yep 100% repeatable. Large file uploads, small one fails every time.  Happy to share privately.

Thanks :-)

**Comment by alecpl** [comment]
I tried the file you provided and it works for me. I don't know Plesk nor how they install Roundcube. You should really try to find the Roundcube error log (or maybe they use syslog?). The log mayb contain some precious info. 

Also, I was interested in Roundcube configuration.

Maybe you should ask Plesk for support.

**Comment by jwpgroup** [comment]
I'll try another look.  did BOTH files attach OK?

**Comment by alecpl** [comment]
Yes.

**Comment by jwpgroup** [comment]
OK, Here is the Roundcube configuration .php files 

[roundcubePHP.zip](https://github.com/roundcube/roundcubemail/files/3561246/roundcubePHP.zip)

Also...https://github.com/roundcube/roundcubemail/issues/5430 I'm guessing 'No' but is this linked 
maybe?

**Comment by alecpl** [comment]
Your log directory is /var/log/plesk-roundcube/, so you should check there. I see nothing wrong with the config files.

**Comment by alecpl** [comment]
No feedback. Not reproduceable.
