### ISSUE TITLE
Roadmap to 1.4.0 ?

### ISSUE THREAD

**Issue by remicollet** [roundcube/roundcubemail#6907]
Hi,

Version 1.4 RC1 is quite old, released 6 months ago.

Have you any ETA for a GA release ?
BTW, releaseing a new RC may have some value
https://github.com/roundcube/roundcubemail/milestone/78

**Comment by alecpl** [comment]
RC2 will be released soon (in a week or two). Then I think the final release in another month, max two months. @thomascube could you confirm?

**Comment by remicollet** [comment]
FYI, in Fedora we choose to play "upstream" game and provide the RC in our devel repository (rawhide). But in this case, we lost, as no GA version, and thus the devel version become the stable Fedora 30 and was released with RC1...

https://rpms.remirepo.net/rpmphp/zoom.php?rpm=roundcubemail

This explain my question (especially have 1.3.10 includes some security fixes, not in RC1)

**Comment by thomascube** [comment]
@alecpl That sounds reasonable
