### ISSUE TITLE
Emails from service@service.aptawelt-experten.de are rejected by domain aptawelt-experten

### ISSUE THREAD

**Issue by romainsbuttoni** [roundcube/roundcubemail#6914]
Hello guys,

we use a newsletter server that is sending emails from service@service.aptawelt-experten.de
to the mailbox  kontakt@aptawelt-experten.de.
the issue is that those email are rejected by kontakt@aptawelt-experten.de..
could please the admin of the domain whitelist the mails from service@service.aptawelt-experten.de..
many thanks!
BR
Romain
![Unbenannt](https://user-images.githubusercontent.com/54950810/64357865-be70fb00-d005-11e9-89f8-fa1866b6be74.JPG)

**Comment by alecpl** [comment]
We have nothing to do with these domains and we're not a service provider.
