### ISSUE TITLE
Spelling check doesn't work for any other language than English

### ISSUE THREAD

**Issue by ghanavat** [roundcube/roundcubemail#6915]
I have set the correct configuration to enable the spelling check and set NULL for 'spellcheck_languages' to get all available languages.

When I type a wrong word in France, German or Persian I keep getting the message 'No misspellings found'. There is something wrong with spell checker engine for any other languages than English.

In errors log, it's complaining that pspell plugin isn't installed. There is no pspell plugin as such available for RoundCube.

>  PHP Error: Failed to load plugin file ~/plugins/pspell/pspell.php in ~/ /program/lib/Roundcube/rcube_plugin_api.php on line 173

Please can you advise?

**Comment by alecpl** [comment]
Remove 'pspell' from `$config['plugins']`, it does not make sense.

What Roundcube version? What PHP version? What type of spellchecker are you using (provide relevant config)?

**Comment by ghanavat** [comment]
Removed 'pspell' from the config. Rouncube version is 1.3.9 and PHP version is 7.0. I am using 'googie' engine.

**Comment by ghanavat** [comment]
What config file are you asking me to provide?

**Comment by alecpl** [comment]
`cat config/config.inc.php | grep spellcheck`

**Comment by ghanavat** [comment]
`$config['enable_spellcheck'] = true;
$config['spellcheck_engine'] = 'googie';
$config['spellcheck_languages'] = array('en_GB', 'fa');
$config['spellcheck_ignore_caps'] = true;
$config['spellcheck_ignore_nums'] = true;
$config['spellcheck_dictionary'] = true;`

**Comment by ghanavat** [comment]
Tried with both plain and html and didn't work.
I was typing Farsi words. Tried with a few misspelled Farsi words such as:
شلام
مختسات
غلاوه
I was getting 'No Misspelled Found' message.

**Comment by alecpl** [comment]
Using git-master I see that with Persian language and your sample text:
1. In plain text mode all works as expected.
2. In HTML mode the words are marked as mispelled, but list of suggestions is empty.

In 1.3.10 all works as expected for me.

**Comment by ghanavat** [comment]
I thought you would test/re-produce the issue with the same version as mine!

Do I need to install any additional package, such as Persian dictionary etc? Or all dictionaries already available?

**Comment by alecpl** [comment]
With spellcheck_engine=googie you're using spell.roundcube.net service. As it works for me it has the languages enabled. So, the only thing you can do is to use local spellcheck engine. This requires installation of php-pspell or php-enchant extension and appropriate language packs.

**Comment by ezmanboy** [comment]
> `$config['enable_spellcheck'] = true; $config['spellcheck_engine'] = 'googie'; $config['spellcheck_languages'] = array('en_GB', 'fa'); $config['spellcheck_ignore_caps'] = true; $config['spellcheck_ignore_nums'] = true; $config['spellcheck_dictionary'] = true;`

Thanks a lot for the tip. It helped a lot.
