### ISSUE TITLE
Unable to Connect + Hang and/or many Red popup warnings

### ISSUE THREAD

**Issue by snblitz** [roundcube/roundcubemail#6921]
There may be two issues, or they may be the same issue.

I get many of the Red popups about various connection errors and occasionally I get "moving messages" in grey with an "unable to connect" page in the browser that hangs for a very long time.

I checked over on the apache side and the query that is hanging is not showing up at the apache server.  At least nothing in the apache logs.

Clicking retry works fine.
I can create the issue pretty easily and it is reasonably repeatable.

I am running 
client side:
RoundCube Webmail 1.4-rc1
firefox 69.0b16
debian 10

server side:
debian 9
apache 2.4.25
php 7.0.33-0+deb9u3

**Comment by alecpl** [comment]
How about Roundcube error log? How about browser error console? Did you try with disabled all plugins? Or a different browser? From the description it does not sound like Roundcube, but browser or internet connection (http server?) issue.

**Comment by snblitz** [comment]
I am not finding anything in the roundcube error.log.  I would agree that the problem looks to be entirely local to the browser.  I have had the problem recurring for about two weeks.  But only in the firefox browser on my desktop.  At the same time I can access via my phone browser and I do not see any errors.  i will give chrome a try on my desktop the next time the issues shows itself.

**Comment by snblitz** [comment]
Well, it seems that posting about the issue fixed the problem.  In the time since I posted this issue not a single red toast or hung access.   So I will close the ticket.  Nothing changed except perhaps mozilla automated updates.
