### ISSUE TITLE
Session security high risk

### ISSUE THREAD

**Issue by grosjo** [roundcube/roundcubemail#6924]
Hi,

After logging in Roundcube, if I clean the seesion data on the server side and restart the web server, the web interface does not loose the session

THis means the status of the login is stored on the browser and /not/  in the server sessions

This is a very high security risk (one can "login" by manipulating browser data, without even accesing the server)

It would extremely nice to have the roudncube using the web server sessions and really not the local cookies to store the login and user name status

**Comment by alecpl** [comment]
This is not true. Maybe you're clearing the session in a wrong way. Maybe you're using some plugin that does this. I don't know, some "remember me" feature?
