### ISSUE TITLE
EOL for Roundcube 1.2x

### ISSUE THREAD

**Issue by jugmac00** [roundcube/roundcubemail#6926]
Hi,

I just read the announcement of 1.4 RC2.

What happens to the 1.2x line when 1.4 finally arrives? Will it be the new LTS then? Or will it get immediately unsupported?

Thank you!

**Comment by alecpl** [comment]
It's not decided yet. I see two options:
1. Make 1.1., 1.2 and 1.3 all LTS versions.
2. Make 1.3 an LTS, and drop support for 1.1 and 1.2.
There's probably other combinations possible, but in my opinion we should choose option 2. The call will be on @thomascube.

**Comment by fabianbur** [comment]
I also vote for option 2.
That way, when version 1.5 arrived, 1.4 would be the new old-stable and 1.4 would still be LTS

**Comment by thomascube** [comment]
I'd also vote for option 2.

**Comment by martijnbrinkers** [comment]
I can understand you do not want to support too many versions at the same time. That said, I think dropping support for the old LTS versions the day 1.4 is released is I think a bit on a short notice. It might take some time to move to 1.4 from older LTS releases. Moving to 1.3 from 1.1 does not make a lot of sense if 1.4 is out. So if support for 1.1 and 1.2 is droppped, I suggest to wait for dropping supporting those version for some time after 1.4 is released.

**Comment by johndoh** [comment]
what about if 1.3 goes to old-stable when 1.4.0 is released and then to LTS with 1.4.1 (asusming there is such a version). That might give people a little more time to update from 1.3 to 1.4 and also parhaps there could be something in the 1.4 release notes about how 1.3 will be dropped to LTS sooner rather than later?

**Comment by alecpl** [comment]
I don't like the idea of old-stable. In reality when new stable line is released the old one is switching to "low maintenance mode". That's what LTS means for our releases. My point was to drop support for 1.1 and 1.2.

**Comment by JoelLinn** [comment]
I don't like the idea of back-porting fixes either. Even if you dedicate work to it, it's inherently error-prone (https://grsecurity.net/teardown_of_a_failed_linux_lts_spectre_fix)
It mainly takes a lot of developer time and delivers a false sense of security to the users.
People tend to stick to old versions if you say you support them and often face migration hell (multiple versions at once etc.) when they finally have to update - and guess who's going to get those migration bug tickets for those legacy deployments

**Comment by thrdroom** [comment]
When do we get the 1.4 final? I don't see any bugs/milestone which are holding back a release. Are there any fixes left to do?

**Comment by alecpl** [comment]
Probably end of this month. We just released rc2, so we should wait some time. I pushed some important changes since and we'll have to decide if we want to go with rc3 or not. Anyway, end of November is my personal deadline for 1.4.0.

**Comment by Kinamo** [comment]
Seen the discussion on this issue I'd say the 1.2 LTE support is not really related to the 1.4 being released, IMHO.

**Comment by alecpl** [comment]
So, the decision is we keep 1.2 and 1.3 as LTS and drop support for older versions.

The final release is planed for this weekend.

**Comment by NicoHood** [comment]
My hoster still uses Roundcube Webmail 1.2.3, but is it still supported nowadays?

**Comment by alecpl** [comment]
It is in maintenance mode, i.e. only security fixes, but it might get dropped with the release of 1.5.0.

Your hoster should update to at least 1.2.13. There were many security issues fixed since 1.2.3.
