### ISSUE TITLE
password plug in "could not save new password" on webuzo web panel

### ISSUE THREAD

**Issue by AdeRayendra** [roundcube/roundcubemail#6928]
Hi, I just updated the  roundcube, before updating, the password plugin seemed to work, but after updating, it doesn't work anymore, I dont know why, and I didn't find any references on google

**Comment by alecpl** [comment]
What version before and after update? What in error log? What in browser console? What exactly mean "it does not work"? What plugin configuration?

**Comment by alecpl** [comment]
No feedback.
