### ISSUE TITLE
mod_auth_gssapi error on 1.4RC1

### ISSUE THREAD

**Issue by bluikko** [roundcube/roundcubemail#6931]
When using Apache and mod_auth_gssapi on 1.4RC1 it does not work, error is logged and a "401 Unauthorized" page is shown:
> INTERNAL ERROR Mechanism needs continuation but neither GssapiConnectionBound nor GssapiUseSessions are configured

The krb_authentication plugin is not yet used - all I did was test the login page of RoundCube on 1.4. On 1.3.10 the login page shows normally with the exactly same Apache configuration.

If the mod_auth_gssapi configuration is removed then the login page shows and user can logon normally, everything seems to work.

Is this expected? I tried to enable and configure krb_authentication but the same error is displayed.

Edit: the Kerberos configuration works on both - the user@REALM can be seen in access log.

**Comment by alecpl** [comment]
401 is normal in 1.4 when the user is not logged in.

**Comment by bluikko** [comment]
I do not mean the initial 401 error that is the response to the first request. To this request the browser responds with a new request using GSSAPI. And Kerberos on that request succeeds since in access_log I can see the user@REALM as authenticated user.

**Comment by alecpl** [comment]
I'm not sure what do you mean or what do you expect. You said you don't use krb_authentication plugin yet.

**Comment by bluikko** [comment]
RoundCube does not care if a user has been already authenticated at the web server level using mod_auth_gssapi.

At this stage, only mod_auth_gssapi was configured to test the web server level authentication. But on 1.4RC2 (not RC1 as I had incorrectly stated) this does not work correctly.

RoundCube should just display a login page, like it always does and which works correctly on 1.3.10.

**Comment by alecpl** [comment]
The difference between 1.4 and 1.3 is that now the login page returns with the 401 code **with the html content**.  This is normal and browsers display the page properly for such cases. But maybe your http server or some proxy can't.

**Comment by bluikko** [comment]
Hmm. I need to confirm about this with browser dev tools then.

Usually the error `INTERNAL ERROR Mechanism needs continuation but neither GssapiConnectionBound nor GssapiUseSessions are configured` from mod_auth_gssapi happens when there is a misconfiguration (or a bug in mod_auth_gssapi as it was). But in this case 1.3.10 is working exactly as expected.

I actually did configure GssapiUseSessions later, along with krb_authentication. But `410 Unauthorized` is still displayed by the browser every time when the session does not exist yet - first load of the RoundCube page.

Even with krb_authentication configured this error is displayed for the first page load and user needs to reload to get to RoundCube.

Right now my configuration is still not working (error logging to IMAP/storage with delegated Kerberos), and a login page is displayed with error "Connection to storage server failed." on the page reaload - IMAP logging shows the IMAP session up to "ID" phase and then stops without showing any authentication, dovecot shows connection opened but zero authentication attempts.

That is most likely a different problem and most likely at my end.

But I am not 100% sure we are on the same page about this error. I will continue configuring when I have time (which is in short supply...)

Pinging @urusha - does 1.4 work in your setup since you had it working (based on #6417)?

**Comment by bluikko** [comment]
I have to add that from all that I can see the mod_auth_gssapi configuration is working, since the authenticated/REMOTE_USER `user@realm` is seen as authenticated on the second request (re-request after initial 401) in Apache access log.

And the same exact configuration works with about dozen different web applications.

The error `INTERNAL ERROR Mechanism needs continuation but neither GssapiConnectionBound nor GssapiUseSessions are configured` has something to do with Apache subrequests.

**Comment by bluikko** [comment]
I see the comment about 401 Unauthorized in 1.4.1 #7010 - and now I do not see the "401 Unauthorized" page anymore when trying to use krb_authentication.

**Comment by alecpl** [comment]
That's correct. The same as with http_authentication plugin the krb_authentication plugin "Make use of an existing Kerberos authentication and perform login with the existing user credentials". I.e. it does not and never was enforcing specific authentication process. That might be a feature request. I guess it could also be configured on http server.
