### ISSUE TITLE
Always show pictures for trusted senders

### ISSUE THREAD

**Issue by gomanuke** [roundcube/roundcubemail#6932]
Hi!

Everytime a got a mail with picture i need to permit viewing explicitly. Is it possible RC to remember my choice?

Thank You.

**Comment by alecpl** [comment]
Please, use mailing list or forum for such questions.

ps. Settings > Preferences > Displaying Messages > Allow remote resources (images, styles) from known senders.

**Comment by gomanuke** [comment]
Не берусь судить, то согласитесь, выражение "Показывать удаленные изображения" не самый понятный вариант для того, чтобы отображать картинки в письмах.
Если посчитаете нужным, то поправьте локализацию, пожалуйста.
