### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by santafejay** [roundcube/roundcubemail#6934]
So i'm trying to setup roundcube "Complete" package and this is what i'm seeing when logging in:

![loginfailed](https://user-images.githubusercontent.com/48039776/65536481-59981a80-deb8-11e9-9d82-4eb8ecf13c8b.png)

Dovecot Error:
dovecot: imap-login: Disconnected (auth failed, 1 attempts in 3 secs): user=<xxx@domain.tld>, method=PLAIN, rip=127.0.0.1, lip=127.0.0.1, secured, session=<xx/xxxxxxxx>

**Comment by alecpl** [comment]
Does not look like a bug. Ask on mailing list or forum.
