### ISSUE TITLE
[SNYK-JS-JQUERY-174006] Prototype Pollution vulnerability in jQuery <3.4.0 as used in Roundcube 1.3

### ISSUE THREAD

**Issue by AndreyMZ** [roundcube/roundcubemail#6936]
There is a vulnerability in jQuery before 3.4.0 related to the `extend` function: https://snyk.io/vuln/SNYK-JS-JQUERY-174006
Roundcube 1.3 uses jQuery 3.2.1: https://github.com/roundcube/roundcubemail/blob/release-1.3/jsdeps.json#L6
The `extend` function is widely used in Roundcube: https://github.com/roundcube/roundcubemail/search?l=JavaScript&q="extend"

Is Roundcube 1.3 affected by this vulnerability?

**Comment by alecpl** [comment]
I don't see how that could be used on Roundcube. If you find a way to hack Roundcube with this vulnerability then we'll reconsider.
