### ISSUE TITLE
Copy and paste image from another email into new email doesn't embed the image

### ISSUE THREAD

**Issue by net147** [roundcube/roundcubemail#6938]
Version: 1.3.x

1. Login to RoundCube WebMail using Chrome
2. Open HTML email containing embedded image
3. Right-click on image and click "Copy image"
4. Click Mail icon and click Compose
5. Change Editor type to HTML
6. Right-click in email editor and click Paste
7. Type an email in "To" and a subject in "Subject"
8. Click Send
9. Click Logout
10. Login to the email you sent message to
11. Notice the image doesn't display properly - the image URL is from RoundCube webmail which is not publically accessible

**Comment by alecpl** [comment]
Because this way you insert the `<img>` with `src` set to the original image `src`. This is not a bug.

We'd have to implement fetching the original image file and attaching it server-side or client-side. I see no such option in TinyMCE. I guess, we'd need some code with use of its image_upload_handler option. Feel free to create a pull request.

**Comment by alecpl** [comment]
Implemented.

I'm slightly afraid that it may have some performance implications in TinyMCE. In future we might improve this so an attachment is created instead of a `data:` URI.

**Comment by i81b4u** [comment]
Hi,

Regarding `data:`, should one not be concerned about possible unwanted side-effects regarding security (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources)?

```
data: Allows data: URLs to be used as a content source. This is insecure; an attacker can also inject arbitrary data: URLs. Use this sparingly and definitely not for scripts.
```
Regards.

**Comment by alecpl** [comment]
When you drag-n-drop an image into the HTML editor it also uses `data:`, so this is not a new feature.

But as I mentioned earlier, there's a place for improvement.
