### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by Advoka** [roundcube/roundcubemail#6939]
Is it possible to develop improvement of Roundcube new mail - create a new email message - attached image size - to make the image responsive? Currently tt is possible only set fixed width and height and use checkbox [x] keep aspect ratio. But today, when all websites have to be responsive, also email people read mostly on mobile phones. Every time when I send some HTML email with attached images, I must edit HTML source for all IMG elements inline CSS like this:

`style="max-width: 100%; height: auto;"`

Maybe there can be added **[x] Responsive** checkbox? See attached images for example.

**Add image form**

![img001-add-image](https://user-images.githubusercontent.com/55881803/65768712-003b2000-e132-11e9-9d91-17849c0780d8.png)

**Source code - before change**

![img002-html-before](https://user-images.githubusercontent.com/55881803/65768713-003b2000-e132-11e9-9947-ce3d3c20d335.png)

**Source code - changed**

![img003-html-after](https://user-images.githubusercontent.com/55881803/65768714-003b2000-e132-11e9-8e22-91941b694975.png)

**Comment by alecpl** [comment]
The place to request a TinyMCE feature is at https://github.com/tinymce/tinymce/issues. I see already some tickets about this.
