### ISSUE TITLE
Roundcube leaks Onion address in headers

### ISSUE THREAD

**Issue by clonmac** [roundcube/roundcubemail#6941]
I connect to my Roundcube instance over the Tor network, and after reviewing the headers of an email I sent from Roundcube, I noticed that Roundcube appends my Onion URL address that I use to access Roundcube.

In the email headers, it displays:

`Received: from <onion>.onion (<hostname> [<IP address>]) by <mailserver> (Postfix) with ESMTPSA`

I haven't been able to figure out where in the configuration I can either specify what I want displayed there or to prevent Roundcube from using the URL itself as the host that uses in the email headers.

Please advise.

**Comment by alecpl** [comment]
```
// add a received header to outgoing mails containing the creators IP and hostname
$config['http_received_header'] = false;

// Whether or not to encrypt the IP address and the host name
// these could, in some circles, be considered as sensitive information;
// however, for the administrator, these could be invaluable help
// when tracking down issues.
$config['http_received_header_encrypt'] = false;
```

**Comment by clonmac** [comment]
Thank you. I am not sure why, but those options don't seem to be working for me. Any idea why? I have them set in my config.inc.php file. I have http_received_header set to false and I've tried setting http_received_header_encrypt as both false, true, and unset.

I'm using the 1.3.10 release version, btw.

**Comment by thomascube** [comment]
The header looks more like it was inserted by your smtp server Roundcube uses for sending mail. Please check your Postfix configuration.
