### ISSUE TITLE
Message preview issue html message

### ISSUE THREAD

**Issue by alepalmaround** [roundcube/roundcubemail#6943]
Hi,

I'm experimenting a strange issue with message preview (version 1.3.10)..

I cannot view all HTML messages with the following tags/parameters.. (see the two examples below)

If I manually modify the file of the message received than I can view the messagge...

Could you help me to find the reason?

Thanks a lot,

Alessandro

**CANNOT VIEW IN ROUNDCUBE (body is empty)**

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv=3D"Content-Type" content="text/html; charset=iso-8859-1" />
<title>Notifica PEC</title>
<style>
.............
</html>

**OK I CAN VIEW IN ROUNDCUBE**

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
<head>
<title>Notifica PEC</title>
<style>
.............
</html>

**Comment by alecpl** [comment]
I see no difference in the text provided. Please, provide a real sample message. Any errors in log. What PHP version?

**Comment by alepalmaround** [comment]
Hi Aleksander,
thanks for your reply..
PHP is 5.4.16 on Centos 7
Roundcube is 1.3.10

Here is the mail (only the different part) that I cannot view in webmail
(in red yuo can see the part that in my opinion is causing the issue...):

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
<http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>>
<html xmlns="http://www.w3.org/1999/xhtml" <http://www.w3.org/1999/xhtml>>
<head><meta http-equiv=3D"Content-Type" content="text/html;
charset=iso-8859-1" />
<title>Notifica PEC</title>
<style>
.............
</html>


Here il the same email but modified so I can view it correctly

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"
<http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd>>
<html>
<head>
<title>Notifica PEC</title>
<style>
.............
</html>


Thanks a lot,

Alessandro



Il giorno mar 1 ott 2019 alle ore 13:45 Aleksander Machniak <
notifications@github.com> ha scritto:

**Comment by alecpl** [comment]
Please, provide the original email message. This is really hard to work with your samples.

**Comment by alepalmaround** [comment]
Ok,
this is the complete original message in "Maildir" format.
Thanks

Return-Path: <assistenza@milleritalia.it>
Delivered-To: assistenza@milleritalia.it
Received: from localhost (localhost [127.0.0.1])
	by mx4.milleritalia.net (Postfix) with ESMTP id 4561484FD272
	for <assistenza@milleritalia.it>; Mon, 30 Sep 2019 12:21:35 +0200 (CEST)
X-Virus-Scanned: amavisd-new at milleritalia.net
X-Spam-Flag: NO
X-Spam-Score: 0.392
X-Spam-Level:
X-Spam-Status: No, score=0.392 tagged_above=-9999 required=5
	tests=[BAYES_00=-1.9, HTML_IMAGE_ONLY_20=1.546, HTML_MESSAGE=0.001,
	LIST_PRTL_SAME_USER=0.021, MIME_HTML_ONLY=0.723,
	MIME_QP_LONG_LINE=0.001] autolearn=disabled
Received: from mx4.milleritalia.net ([128.65.126.37])
	by localhost (mx4.milleritalia.net [127.0.0.1]) (amavisd-new, port 10024)
	with ESMTP id NYuhYPgJMBb1 for <assistenza@milleritalia.it>;
	Mon, 30 Sep 2019 12:21:33 +0200 (CEST)
Received: by mx4.milleritalia.net (Postfix, from userid 5001)
	id DD83484FD271; Mon, 30 Sep 2019 12:21:33 +0200 (CEST)
X-Spam-MillerTag-mx4: No, score=0.4 required=5.0 tests=BAYES_00,
	HTML_IMAGE_ONLY_20,HTML_MESSAGE,LIST_PRTL_SAME_USER,MIME_HTML_ONLY,
	MIME_QP_LONG_LINE autolearn=disabled version=3.4.0
Received: from mx-gate03.milleritalia.net (mx-gate03.milleritalia.net
[128.65.126.38])
	by mx4.milleritalia.net (Postfix) with ESMTP id E973F84FD26D
	for <assistenza@milleritalia.it>; Mon, 30 Sep 2019 12:21:32 +0200 (CEST)
Received: from mx205fe02.twtmail.twt.it (mx205fe02.twtmail.twt.it
[82.113.194.205])
	by mx-gate03.milleritalia.net (Postfix) with ESMTP id E6150809C7E0
	for <assistenza@milleritalia.it>; Mon, 30 Sep 2019 12:21:32 +0200 (CEST)
X-ExtScanner: Niversoft's FindAttachments (free)
Received: from [82.113.195.54] (account notifiche-pec@notifiche.twt.it HELO )
  by vmserver.it (CommuniGate Pro SMTP 6.1.17l)
  with SMTPA id 105666775 for assistenza@milleritalia.it; Mon, 30 Sep
2019 12:21:32 +0200
X-Auto-Generated: TWT PEC Notifier
Precedence: bulk
List-Unsubscribe-Post: List-Unsubscribe=One-Click
List-Unsubscribe: <https://mail.pec.milleritalia.it/unsubscribe/index.html>
Content-class: urn:content-classes:message
MIME-Version: 1.0
Subject: Ricevuto nuovo messaggio di posta elettronica certificata
From: "MILLER ITALIA Servizio di Notifica PEC" <assistenza@milleritalia.it>
To: <assistenza@milleritalia.it>
Content-Type: text/html;
   charset="iso-8859-1"
Content-Transfer-Encoding: quoted-printable
Date: Mon, 30 Sep 2019 12:21:32 +0200
Message-ID: <auto-000105666775@fe02.twtmail.twt.it>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv=3D"Content-Type" content="text/html; charset=iso-8859-1" />
<title>Notifica PEC</title>
<style>

a{
color:#000066;
}

contenuto td{
color:#474747;
font-size:12px;
font-family:Arial, Helvetica, sans-serif;
line-height:20px;
}

 .titolo{
color:#000  !important;
font-size:18px !important;
text-align:right;
padding-bottom:12px;
padding-right:10px;
font-weight:bold;
font-style:italic;
}

</style>
</head>
<body>
<table width=3D"100%" class=3D"contenuto" cellspacing=3D"0" cellpadding=3D"0">
	<tr>
		<td  width=3D"180"><img
src=3D"https://mail.pec.milleritalia.it/skins/miller_italia/images/pec_print.gif"
style=3D"margin-left:15px;margin-top:5px;" /></td>
		<td class=3D"titolo" valign=3D"bottom">PEC Notifier</td>
	<tr>
		<td colspan=3D"2" style=3D"background-color:#ccc;
font-size:4px;line-height:4px;">&nbsp;</td>
	</tr>
	<tr>
		<td colspan=3D"2" style=3D"padding:20px">
		<b>Ricevuto nuovo messaggio di posta elettronica certificata
all'indirizzo assistenza@pec.milleritalia.it.</b>
		<br />
		<br />
		<b>Data:</b> 30/09/2019
		<br />
		<b>Mittente:</b> assistenza360@pec.milleritalia.net
		<br />
		<b>Soggetto:</b> Apertura porte
		<br /><br />
		Per collegarti alla Webmail <a
href=3D"https://mail.pec.milleritalia.it" target=3D"_blank">clicca
qui</a>
		<br /><br /><br />
		</td>
	</tr>
	<tr>
		<td colspan=3D"2" style=3D"background-color:#ccc; font-size:4px;
line-height:4px;">&nbsp;</td>
	</tr>
</table>
<p style=3D"margin:0; padding:10px; text-align:justify;
background:#EEEEEE;font-size:8.5pt;font-family:'Courier New', Courier, mono;
color:#666666; line-height:11px;">This e-mail is intended only for the
addressee named above. As
this e-mail may contain confidential or privileged information, if you are not
the named addressee, you are not authorized to retain, read, copy or
disseminate this message or any part of it.</p>
</body>
</html>




Il giorno mar 1 ott 2019 alle ore 15:38 Aleksander Machniak <
notifications@github.com> ha scritto:

**Comment by alepalmaround** [comment]
Hi Aleksander,

do you have some news about this issue?
Thanks a lot,

Alessandro

**Comment by alecpl** [comment]
I didn't have time to investigate. On a first look this:
```
<meta http-equiv=3D"Content-Type" content="text/html; charset=iso-8859-1" />
```
looks invalid according to quoted-printable encoding. Not sure it's the main culprit here.

**Comment by alepalmaround** [comment]
Hi,
i see the header:
Content-Transfer-Encoding: quoted-printable

If I change meta tag from:
<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv=3D"Content-Type" content="text/html; charset=iso-8859-1" />

to:
<html xmlns=**3D**"http://www.w3.org/1999/xhtml">
<meta http-equiv=3D"Content-Type" content=**3D**"text/html; charset=**3D**iso-8859-1" />

I can read the message (substitute "=" with "=3D") in webmail...

**Comment by alepalmaround** [comment]
Hi,
i see the header:
Content-Transfer-Encoding: quoted-printable

If I change tags from:

<html xmlns="http://www.w3.org/1999/xhtml">
<meta http-equiv=3D"Content-Type" content="text/html; charset=iso-8859-1" />

to:

<html xmlns=3D"http://www.w3.org/1999/xhtml">
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Diso-8859-1" />

I can read the message (substitute "=" with "=3D") in webmail...

**Comment by alepalmaround** [comment]
[webmail message KO and OK.pdf](https://github.com/roundcube/roundcubemail/files/3697651/webmail.message.KO.and.OK.pdf)

I have uploaded the original message and the message modified in order to view it in webmail..

**Comment by alepalmaround** [comment]
The strange things is that with all other clients we ca read the email.. I'm wondering if we can change the code in some way in order to make it more robust..

**Comment by alecpl** [comment]
Works for me using git-master. Tags are malformed, but it is not a problem, the body is displayed properly.

**Comment by alepalmaround** [comment]
Excuse me, is the first issue that i opened for roundcube.. so you mean that you tryed with the main brach and you can view the message?
So what could cause the issue in your opinion? configuration?? The problem is only with this kind message that is our PEC notifier...
Thanks,
Alessandro

**Comment by alepalmaround** [comment]
I found this thread:
https://support.plesk.com/hc/en-us/articles/360004486534-Unable-to-open-an-email-via-a-webmail-Could-not-load-message-from-server
If I modify dovecot.conf like desccribed above I can view the email in roundcube webmail..
Il don't know all the implications but it seams to work..
Is it ok for you?
Thanks for your support,
Alessandro

**Comment by alecpl** [comment]
So, this is most likely a bug or too strict implementation of BINARY extension on dovecot side. Nothing we can do about it.

**Comment by alepalmaround** [comment]
Yes, I agree with you. Thanks for your help an have a good day!
Alessandro
