### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by ValentinRgt** [roundcube/roundcubemail#6944]
Hello, 

Did you plan to make a mobile stable version or solve the Navbar bug and other elements that do not stabilize ?

Regards.

**Comment by alecpl** [comment]
You missed the Elastic skin and last two years of development of Roundcube 1.4 or I don't understand the question.

**Comment by ValentinRgt** [comment]
The mobile version will be available for when, because currently the mobile version is completely obsolete.

**Comment by alecpl** [comment]
It's available with Roundcube 1.4.
