### ISSUE TITLE
open_basedir recommendation

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#6946]
Hi there. For security reasons i want to enable open_basedir in php.ini . This is no problem with most of the RC components. The only exception is the enigma plugin. It seems that i must allow /usr/bin. However, i have some concerns to allow this whole directory.

Is there a better solution eg. a more restrictive setting for enigma?

**Comment by alecpl** [comment]
Enigma is using gnupg binaries. With gnupg 1.4 it will be a single binary, but with 2.x it's more complicated. So, maybe you could move that one binary to some other location or I don't know. I'm not used to open_basedir.
