### ISSUE TITLE
Deleting emails without opening / loading their contents

### ISSUE THREAD

**Issue by snblitz** [roundcube/roundcubemail#6947]
Is it possible to delete emails in roundcube without opening / loading / viewing the contents?

**Comment by alecpl** [comment]
You can select and multi-select message list records with click and Ctrl key or Shift key as in desktop applications (or use checkbox selection in Elastic skin).

**Comment by snblitz** [comment]
Thanks the ctrl key works on the desktop.  I am not seeing the checkboxes in the Elastic skin,

**Comment by alecpl** [comment]
Find Selection option in Select menu (above the messages list).

**Comment by snblitz** [comment]
I would say that the selection menu is not achieving my goal.
I would like roundcube to only open emails on my command to do so.
Using the selection mechanism I can get close but not quite all the way.
For example,
using the selection mechanism I can select an email, without opening it, and then press delete.  However, roundcube then opens the next email in the list.

Similar behavior occurs when trying to leverage the control key.

**Comment by snblitz** [comment]
The reason the positive open action is important is because courts in the US are now using the "opened" state in email history / IMAP state as evidence against the email recipient.   Thus one wants the opened state to only occur for emails that are positively selected for opening.

Black mailers are also using this open state.  They send you "inappropriate emails" wait for you to open them, and then black mail you.

For both those reasons and a few others, it would be desirable that emails only be opened upon a positive action from the user (at least as an option)

**Comment by alecpl** [comment]
Settings > User Interface > Display next record after delete/move. The option is in a different place in 1.3, it's in Mailbox View section if I remember correctly.

**Comment by snblitz** [comment]
I found the setting in yet a third location.  I going through the email flows.  Thanks for the pointers.
