### ISSUE TITLE
Elastic: alignment of auto-complete address dropdown on tablets in compose

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#6951]
The alignment of the auto-complete dropdown on the compose screen when in tablet mode looks a little strange to me.

the list is always on the right had side of the screen and not where the cursor is or to the "to" box or other screen element. Just kind of floating around on the right hand side.

![Untitled-1](https://user-images.githubusercontent.com/88682/66228550-a3161000-e6d7-11e9-9b58-9b443a43bcc5.png)

on mobile its not so obvious as the screen is narrower but IMO may be the drop down could be either full width or centered.

![Untitled-2](https://user-images.githubusercontent.com/88682/66228766-37807280-e6d8-11e9-8d18-f86e1b247f9e.png)

Tested on git-master, in FF69 with all plugins disabled.

**Comment by alecpl** [comment]
Definitely a regression. I'll work on this as I see it's not that obvious to fix.

**Comment by alecpl** [comment]
Fixed. On small screens we display the dropdown using full width of the recipient input. It fixes also some border radius discrepancies.
