### ISSUE TITLE
Help plugin not working?

### ISSUE THREAD

**Issue by kgl2001** [roundcube/roundcubemail#6953]
I'm running Roundcube 1.4-rc2, and noticed that the Help option in the Help plugin doesn't seem to do anything. The About and Licence options both work as expected. Is this a bug, or an issue on my system? The Help plugin is at version 1.4:

![image](https://user-images.githubusercontent.com/36017029/66257989-b092cf00-e797-11e9-931c-2a69fec237e9.png)

**Comment by johndoh** [comment]
Are there any messages in your browser console? What have you set `help_source` to? If you access roundcube via HTTPS and this config is HTTP perhaps you are running into a mixed content error from your browser.

**Comment by kgl2001** [comment]
Spot on. The console advised a mixed content error, and the help_source was incorrectly set to http. I've changed this to https and now its working.

Thank you.
