### ISSUE TITLE
if conditon runs the else case also or does not run any case

### ISSUE THREAD

**Issue by vaso123** [roundcube/roundcubemail#6954]
I am using v.1.3.10

My task is to customize the error messages page. In my case is need to customize the 404 with some custom text. 

This is what I've tried.

```
<roundcube:if condition="env:server_error=='404'"/>
  <h2 class="mb-3">404</h2>
  <p class="mb-4">Sorry, requested page not found.</p>
<roundcube:else/>
  $__page_content
<roundcube:endif/>
```

What happens?

If the error code 404 then it shows me my custom text, but it also shows me the `$__page_content`

But if the code is not 404, for example a 403 because invalid request, token expirted, then the page shows me nothing. Not my error and neither the system `$__page_content`s.

**Comment by johndoh** [comment]
you need a space before the closing / on each part of the IF statement like this:
`<roundcube:if condition="env:server_error=='404'" />`

@alecpl shall I make the space (and trialing slash) optional in #6829?

**Comment by alecpl** [comment]
If that's the case then it's a bug. I'm not sure about the slash, but it should definitely work without spaces.

**Comment by vaso123** [comment]
Added space had solved the problem. I am using PHPStorm and autoformat was set to not add space. I've changed my IDE settings and then it worked.

**Comment by alecpl** [comment]
Fixed.
