### ISSUE TITLE
Internal Server Error (500) with git-latest

### ISSUE THREAD

**Issue by Takika** [roundcube/roundcubemail#6955]
I tried to use current git version (54799b9) but I got this in errors.log:
[06-Oct-2019 14:01:27 Europe/Budapest] PHP Fatal error:  Uncaught Error: Call to undefined method rcmail::find_asset() in /usr/local/www/roundcubemail-git.54799b9/plugins/jqueryui/jqueryui.php:150
Stack trace:
#0 /usr/local/www/roundcubemail-git.54799b9/plugins/jqueryui/jqueryui.php(45): jqueryui::asset_exists('themes/larry/jq...')
#1 /usr/local/www/roundcubemail-git.54799b9/program/lib/Roundcube/rcube_plugin_api.php(100): jqueryui->init()
#2 /usr/local/www/roundcubemail-git.cc21eac/program/include/rcmail.php(137): rcube_plugin_api->init(Object(rcmail), 'mail')
#3 /usr/local/www/roundcubemail-git.cc21eac/program/include/rcmail.php(78): rcmail->startup()
#4 /usr/local/www/roundcubemail-git.54799b9/index.php(43): rcmail::get_instance(0, NULL)
#5 {main}
  thrown in /usr/local/www/roundcubemail-git.54799b9/plugins/jqueryui/jqueryui.php on line 150

I disabled all of my plugins, but jqueryui loaded by default. jqueryui.php changed in this commit: https://github.com/roundcube/roundcubemail/commit/40967393226ba41e4e0cc4a1ce9022d3fcb99a3f

Please try to fix this.

**Comment by alecpl** [comment]
The method is defined in program/include/rcmail.php file. So, it looks like that file is not compatible with the plugin. You did something wrong.

**Comment by cu** [comment]
In case it helps anyone else out in the future, I got this error after upgrading roundcube to 1.4.0. It turns out I forgot to restart Apache after the upgrade.

**Comment by muzetik** [comment]
> In case it helps anyone else out in the future, I got this error after upgrading roundcube to 1.4.0. It turns out I forgot to restart Apache after the upgrade.

Not exactly Apache, but PHP. If PHP is run through mod_php, it will work. But if PHP is run througn php-fpm, must restart php-fpm.

**Comment by dcapape** [comment]
I'm getting this error after updating my Debian Buster. Roundcube, PHP and Apache were installed via APT, and the server reboots are useless. I tried to install Roundcube directly from Github and I'm getting exactly the same error.
