### ISSUE TITLE
Undefined index: nl in program/lib/Roundcube/html.php on line 80

### ISSUE THREAD

**Issue by vaso123** [roundcube/roundcubemail#6956]
Hi!

I am developing localhost, so I've turned on all the erro messages. Now I am getting a tons of noteices.

This is surely a bug see the code. 

In the `rcube_plugin_api` what is a core file, in the line 599/600 there is a call to the `html::tag`

`$this->output->add_header(html::tag('script', array('type' => "text/javascript", 'src' => $src)));`

So it passes a string and an array with two key/value pairs. 

At `html` class line 80 the code want to decide to add a new line character after the tag or not.

`$suffix = $attrib['nl'] || ($content && $attrib['nl'] !== false && !in_array($tagname, $inline_tags)) ? "\n" : '';`

The problem is that you passed only `type` and `src` keys, and no check for is the `nl` key exists.

The `$attrib['nl'] !== false` is a bad approach also, what if its value is 0? It will add new line. Lot of programmers use 0/1 instead of boolean (not me).

Should be changed to this:

`$suffix = !empty($attrib['nl']) && $content && !in_array($tagname, $inline_tags) ? "\n" : '';`

`empty` is one of the most powerful function in PHP, it check is it exists and not `false/null/0/''`

It is also true for the `$attrib['noclose']` too. Millions of notices.

Anyway please fix it.

Roundcube 1.3.10, latest "stable"

I am wondering how is not fixed yet.

**Comment by alecpl** [comment]
Roundcube is not intended to run in E_STRICT mode. 

That being said, if you create a pull request we'll consider it. Until PHP starts throwing warnings/exceptions for such cases we'll not spend much time on this.
