### ISSUE TITLE
Enigma: "Enter key passphrase" modal does not render correctly

### ISSUE THREAD

**Issue by thetestspecimen** [roundcube/roundcubemail#6958]
## Setup
Roundcube 1.4 rc2
Enigma (latest master from github)
Server: Ubuntu 19.04 (apache)
Skin: elastic
Browsers: latest stable chrome and firefox

## Problem
The modal that pops up to request the pgp key passphrase does not render correctly. All the main body text is squashed to the right. 

This occurs both when trying to open an encrypted mail, and when trying to send a signed email. i.e. whenever the passcode for the pgp key is required.

It is possible to expand the modal to display the text so it is readable, but there is a large blank section to the right hand side. The modal is essentially double the width it needs to be in the expanded state.

### As first displayed

![SendEmailUnexpanded](https://user-images.githubusercontent.com/40262729/66402152-08764380-e9ed-11e9-83d3-10c7449bcf0e.jpg)

### Expanded manually

![SendEmailExpanded](https://user-images.githubusercontent.com/40262729/66402189-20e65e00-e9ed-11e9-9cbb-f0abbf4c81d4.jpg)

**Comment by alecpl** [comment]
Works for me. Check browser console for some hints. Maybe some js error.

**Comment by thetestspecimen** [comment]
You are correct it does work. It was due to bad config in my setup files (which I thought I had checked thoroughly enough).

Sorry to waste your time. You can close this off.
