### ISSUE TITLE
Restringuir modificacion

### ISSUE THREAD

**Issue by wfmf93** [roundcube/roundcubemail#6963]
Buenas  tardes. 

Estoy utilizando la plataforma hordecubemail para  todo mi equipo de trabajo.

Me di cuenta que al ingresar ellos pueden modificar contraseña, poner auto contestadores, pueden editar. 

existe alguna opción para  restringir los permisos a los usuarios.

**Comment by dktcoding** [comment]
Hola, 

Quizás estés interesado en algún plugin como: [user-specific configuration](https://plugins.roundcube.net/packages/sbehuret/user_config).

Nunca lo he usado (y tiene una documentación bastante mediocre) pero parece ser similar a lo que estás buscando.

Saludos
