### ISSUE TITLE
For one user, shift-del on keyboard doesn't ask for confirmation

### ISSUE THREAD

**Issue by zerocarbthirty** [roundcube/roundcubemail#6964]
This is driving me crazy and I have no idea where to start trying to fix it.

On one user account in roundcube if I click on a message and then push shift+delete on my keyboard it immediately deletes the message.

In my account and seemingly ALL other accounts when I hit shift+delete on my keyboard it asks for confirmation before deleting it.

Same browser, same PC just a different account.

Does anyone have any idea?

**Comment by johndoh** [comment]
check their settings under special folders and see if they have
a) have a special folder set for the trash folder - if no trash folder is set then messages are always permanently deleted
b) if they have a junk mailbox set and if so what "Permanently delete messages in the junk folder" is set to in the Server Settings section

**Comment by alecpl** [comment]
No feedback.
