### ISSUE TITLE
Archive button does not move to next email, like Delete

### ISSUE THREAD

**Issue by khaytsus** [roundcube/roundcubemail#6965]
I use the Archive button a ton, and it does not move to the next unread email like Delete does, even though I do have the "Display next list entry after delete/move" setting enabled.  I often archive email after email, read them, click archive, and right now I have to go back and forth to select the next email. 

I have verified that this is new behavior to roundcubemail-1.4-rc2, rc1 and prior versions did not behave this way.  Thank you!

**Comment by alecpl** [comment]
Fixed.
