### ISSUE TITLE
Contacts Prev/Next etc. icons present but invisible in Chrome

### ISSUE THREAD

**Issue by nadampski** [roundcube/roundcubemail#6967]
In the Contact section, at the top of the Contacts list, there should be four arrow buttons which show the following when hovering the mouse over them:
"Show first set", "Show previous set", "Show next set", "Show last set"
This works correctly in browsers such as Edge and Firefox but the icons are invisible in Chrome and Opera.

![Edge](https://user-images.githubusercontent.com/44057312/66663866-6603cd80-ec43-11e9-9eb5-ca5117bf575d.JPG)
![Chrome](https://user-images.githubusercontent.com/44057312/66663867-669c6400-ec43-11e9-9b6b-a9d0bd292cc6.JPG)

**Comment by alecpl** [comment]
You're using custom skin we do not support.

**Comment by nadampski** [comment]
Thanks, alecpl! I've just changed the skin back to Classic and it's fine now. I may chase this up with Roundcube Plus.
