### ISSUE TITLE
Update TinyMCE from 4.5.8/4.8.2

### ISSUE THREAD

**Issue by mwithheld** [roundcube/roundcubemail#6968]
1.3.10 uses v4.5.8 (2017Nov); 1.4-rc2 uses v4.8.2 (2018Aug)
Probably should move to v5.x
but at least should update to latest 4.x to get bugfixes.

**Comment by alecpl** [comment]
1.4 will not move to v5, maybe later. There's already #6762 for this, but v5 has a lot of bugs. https://kolabian.wordpress.com/2019/05/23/tinymce-5/
