### ISSUE TITLE
Login form issue

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#6970]
If you are on the login form and the cursor is in the username field, its possible to press "enter" key and the form/pages changes the focus to the password field. This is a problem if you use a password manager and some auto-fill functions. Sometimes there are keystrokes from the enter key, which are misinterpreted by Roundcube in this case and the wrong field gets the focus.

It would be better, if only a "tab" key will be interpreted to change between the fields.

The above seems at least to be a problem in conjunction with Firefox. 

https://sourceforge.net/p/keepass/discussion/329220/thread/289ff4c5ea/

**Comment by alecpl** [comment]
That will be a bug in the password manager. However, the added value of our keyup handler is really small, we should consider removing it.

**Comment by Offerel** [comment]
for the meantime, is there anything i can overwrite this function with my own function? I have tried to find where the event is triggered, but i failed. I tried also with:

```
$('rcmloginuser').keypress(function(event) {
    if (event.keyCode == 13) {
        event.preventDefault();
        event.returnValue = false;
    }
});
```
but that didnt work

**Comment by Offerel** [comment]
Ok, finally i have found a workaround, i modified program/app.js (line 627 to 632):

```
input_user.keyup(function(e) { if(e.keyCode != 13) return ref.login_user_keyup(e); });

//if (input_user.val() == '')
	input_user.focus();
//else
//	$('#rcmloginpwd').focus();
```
Made the same changes in app.mini.js

I know that is only a dirty workaround, but it does, what it should. Maybe the change in the first line isn't needed.

**Comment by alecpl** [comment]
I didn't have time yet to investigate this. 

Isn't the change in keyup handler enough? I was considering making changes in this part only.

Could you check if changing `.keyup(` to `.keydown(` in line 627 (only this) makes a difference in your case?

**Comment by Offerel** [comment]
You are right. Change that line to `input_user.keydown(function(e) { return ref.login_user_keyup(e); });` seems to solve the issue. I have changed it on my side now to this. The real behavior of the Enter key didn't change with this.

Do you have a explanation why this issue occurs only with Firefox and not Chrome?

**Comment by alecpl** [comment]
I did some test and I see no improvement having the keyup handler. So, it has been removed. Fixed.
