### ISSUE TITLE
compose responses insert problem

### ISSUE THREAD

**Issue by henrythemouse** [roundcube/roundcubemail#6971]
When using rc 1.4rc2 and elastic skin on Android Firefox.

If I insert a response two lines below the message text the response will be inserted at the end of the last line of the message text. In order to have empty lines between the message and the response text I would need to manually insert them after inserting response text.

While this may be acceptable behavior, its not the behavior that I find when using the Larry skin. Blank lines are recognised when inserting a response when using the Larry skin, the response text is truly inserted at the cursor position.

By the way, elastic skin is a very welcome addition to roundcube. It really makes roundcube the premiere webmail application visually and functionally. Congratulations on a great idea and perfect implementation.

Thank you

**Comment by alecpl** [comment]
I'm not sure we're talking the same, but I can confirm that in Elastic responses are inserted at the start of the textarea, not at the cursor position. That is when using plain text mode, in html mode all works fine.

**Comment by alecpl** [comment]
Fixed.

**Comment by henrythemouse** [comment]
Thanks
