### ISSUE TITLE
Ajax triggering what do not need

### ISSUE THREAD

**Issue by vaso123** [roundcube/roundcubemail#6973]
Hi!

I do not know is it a roundcube or a plugin problem.

What I want to do is that when a user clicks on a menu item, a floating horizontal collapseble bootstrap panel appears. When user fills the form and send, I am using `$.post` to send the data to my url.

I've tried to debug it, and unfortunately script does not stop, it goes forward and triggering something, because in the login panel the Loading text appears.

If I send an 500 header back to my ajax, the Server Error text appears too.

I had no success with debug it. I've turned off every plugins, except mine what has nothing to do with ajax, but same things happens.

I've also do not load javascripts, only the bootstrap. When my script runs, there is no messages.

Here is what I do:

   ```
 $('#contact-form').on('submit', function (event) {
        event.preventDefault();
        let url = '<roundcube:var name="config:site-url" />/?_action=contactmail';
        let data = {
            'email': $('#contact_email').val(),
            'name': $('#contact_name').val(),
            'message': $('#contact_message').val(),
            'privacy': $('#contact_privacy').is(':checked')
        };
        $.post(url, data, function (response) {
            let json = JSON.parse(response);
            let messageClass = 'contact-' + json.result;
            let message = json.message;
            $('#contact-message').removeClass().html(message).addClass(messageClass).css({'display': 'block'});
            if (json.result === 'success') {
                    $('#contact_email').val('');
                    $('#contact_name').val('');
                    $('#contact_message').val('');
                    $('#contact_privacy').prop('checked', false);
            }

        }).fail(function (response) {
            $('#contact-message').html('<p>Nem várt hiba történt a levél küldése közben.</p>')
                .addClass('contact-error')
                .css({'display': 'block'});
        });
    });
```

**Comment by vaso123** [comment]
Ok, I figured out. This is because if a javascript error happens then for some reason I've got this Server error message. I've placed the customers google ads, and for some reason these scripts has blocked. I think because this is a development environment, and domain names not matched.

Please fix it, it's a bug. There should not be Server error for users, they will scare and the page is works, just advertise not shows. I've also tested it with some other 3rd party external script, and the problem is same.

**Comment by alecpl** [comment]
This is what we do in app.js:
```
// set jQuery ajax options
  $.ajaxSetup({
    cache: false,
    timeout: this.env.request_timeout * 1000,
    error: function(request, status, err){ ref.http_error(request, status, err); },
    beforeSend: function(xmlhttp){ xmlhttp.setRequestHeader('X-Roundcube-Request', ref.env.request_token); }
  });
```
So, you have to reset these options in your request. There's nothing to fix.
