### ISSUE TITLE
Feature request: Possibility to change template engine.

### ISSUE THREAD

**Issue by vaso123** [roundcube/roundcubemail#6976]
Did not you think about change your template engine for example to twig, or smarty?

In those template engines you can use a lot of tags, filters, functions or modifiers.

Or that could be a good option to change the template enginge. For example, I install twig with composer into my plugin, and set my plugin to use twig.

These templates are also supported by most of IDE.

**Comment by alecpl** [comment]
We do not have resources to do the switch. Also, because of multiple skins support we don't want to put much logic to templates, so a simple templates engine we have is good enough.
