### ISSUE TITLE
Show unread messages fails when changing folders [1.4-git [GIT 20191019.0452]]

### ISSUE THREAD

**Issue by dktcoding** [roundcube/roundcubemail#6978]
`Show unread messages` fails when changing folders and requires to be selected twice.

Steps:
1. Have at least 2 folders with read and unread messages
1. Select the first folder
1. Click on `Show unread messages` and all works well
![Screen Shot 2019-10-20 at 16 13 51](https://user-images.githubusercontent.com/709639/67164916-a2c37900-f355-11e9-9dd4-695b6487b07e.png)
1. Now change to the second folder `Show unread messages` is still selected but read messages are being shown 

![Screen Shot 2019-10-20 at 16 14 04](https://user-images.githubusercontent.com/709639/67164917-a48d3c80-f355-11e9-9eaf-66c8588ffdee.png)

IMHO the solution should be simply to set `Show unread messages` as unselected when changing folders.

**Comment by alecpl** [comment]
When you change folder the search is reset, so indeed we need to make sure to reset the button state too.

**Comment by alecpl** [comment]
Fixed.
