### ISSUE TITLE
Inline images not shown

### ISSUE THREAD

**Issue by jrubenc** [roundcube/roundcubemail#6980]
Hello,

Using 1.4-rc2

One of our customers complains that has some emails whose images won't load. I can provide full headers and the full email as well. Those are multipart messages whose plain text is:

https://pastebin.com/0PkUv6gv

And the HTML version is:

https://pastebin.com/K3dx9tA4

Doesn't work on RainLoop webmail either. But Thunderbird is ok with those mails.

Setting $config['mime_magic'] = null; doesn't help.

**Comment by alecpl** [comment]
We need a complete message source.

**Comment by alecpl** [comment]
Content-Id headers were formatted in a way that left a redundant space which caused issues in recognizing the inline images identifiers. Fixed.

**Comment by jrubenc** [comment]
Thanks a lot Aleksander

**Comment by matthewbloch** [comment]
I've got another message which is triggering this behaviour, possibly not for the same reason (I'm running 1.4.6 which has the above fix in it) - https://pastebin.com/jYHQCc5i
