### ISSUE TITLE
[1.4rc2] elastic does not show mailvelope encryption buttons

### ISSUE THREAD

**Issue by MASHtm** [roundcube/roundcubemail#6982]
I'm using FF 69.0.3 (Fedora) with mailvelope 4.1.1 and while larry shows the encryption buttons on the compose screen it is not activating on elastic. If I overwrite the "display:none" style in devtools I'm able to successfully use the button and encrypt/sign messages. It seems the activation hook is broken in I way I didn't figure out yet.

**Comment by MASHtm** [comment]
I think this is the fix:
```
--- ui.js.orig	2019-10-23 14:44:42.489887866 +0200
+++ ui.js	2019-10-23 14:44:48.178969476 +0200
@@ -1515,7 +1515,7 @@
             case 'compose-encrypted':
                 // show the toolbar button for Mailvelope
                 if (args.status) {
-                    $('a.button.encrypt:not(.icon)').parent().show();
+                    $('a.encrypt:not(.icon)').parent().show();
                 }
                 break;
 
```

**Comment by alecpl** [comment]
Looks like a regression.

**Comment by alecpl** [comment]
Fixed.
