### ISSUE TITLE
Imap Subfolders showing incorrect on 1und1 / Online Accounts

### ISSUE THREAD

**Issue by RolandSM** [roundcube/roundcubemail#6984]
Hello,
I use Roundcube to connect to a 1un1 mail account and it works generally, but the Archive folder structure is incorrect.
On Thunderbird and 1und1 Webmailer all is okay.

But in Roundcube I see every Subfolder from archive as separate folder like:
Archives
Archives/2019
Archives/2019/2019-01
Archives/2019/2019-02

**Comment by thomascube** [comment]
Seems like the folder delimiter is wrongly configured. Adjust the option `imap_delimiter` in your Roundcube server config. Setting it to `null` should auto-detect it or otherwise use "/". See [description](/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L180).

**Comment by RolandSM** [comment]
Hello,
this was not the solution. If I insert instead of null a '/' or '.' the error is the same.

**Comment by alecpl** [comment]
Enable imap_debug and provide the log starting from the moment when you log in. Provide a screenshot.

**Comment by RolandSM** [comment]
Okay I have done an error. I changed the imap_delimter in the defaults.inc.php.
Now I put this in the config.inc.php an reloggedin and saw changes.

If I put a '/' the 1und1 works correct. But then the other mail accounts on the dovecot server shows this error. If I switch to '.' the server folder works again, but the 1und1 not.

I turn it back do NULL same as before, also when I insert only '';

Is there a possibility to handle both together?

**Comment by alecpl** [comment]
Looks like 1und1's imap does not advertise the separator properly. If you provided the debug log I could find more.

**Comment by alecpl** [comment]
And no, it isn't supported scenario. You would have to write a simple plugin with use of storage_connect hook.

**Comment by RolandSM** [comment]
The imap.log contains all of my mails? Where I should provide?
Also there are no entries with "error" & "rail".
Howt I can write such a plugin?

**Comment by alecpl** [comment]
You can remove the part that contains email data and paste here. Or you can send it to alec at alec dot pl.

**Comment by alecpl** [comment]
Problem with ident_switch plugin which we do not support.
