### ISSUE TITLE
Freebsd 11.3-Release error

### ISSUE THREAD

**Issue by andrkaz** [roundcube/roundcubemail#6985]
Ttrying to upgrade Roundcube with portupgrade:
pkg-static: Unable to access file /usr/ports/mail/roundcube/work-php72/stage/usr/local/www/roundcube/spellchecker.php:No such file or directory

**Comment by alecpl** [comment]
We do not support distribution packages here. This error tells me nothing.

**Comment by thomascube** [comment]
Please forward this problem to the freebsd packagers or iredmail people.
