### ISSUE TITLE
gd-png error

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#6986]
Hi Alec,

Saw this in the logs, see if it helps you to debug/fix it.
PHP 7.2.11

=======
Oct 23 22:14:38 fastweb roundcube: PHP Fatal error:  imagecreatefrompng(): gd-png: fatal libpng error: Read Error: truncated data#012 in /home/hosting/ting.pt/webmail/program/lib/Roundcube/rcube_image.php on line 219
Oct 23 22:14:38 fastweb roundcube: PHP Fatal error:  imagecreatefrompng(): gd-png: fatal libpng error: Read Error: truncated data#012 in /home/hosting/ting.pt/webmail/program/lib/Roundcube/rcube_image.php on line 219

**Comment by alecpl** [comment]
Looks like the image is somehow broken, but should PHP throw fatal error? It might be hard to fix until we drop PHP 5.4 support. If I had such an image sample I could investigate.

You can configure Roundcube to use Imagick instead of GD to workaround the issue.

**Comment by alecpl** [comment]
We had already a ticket for the same issue - #6567. It has been closed as wontfix. However, if I had a sample file I might investigate some more.

**Comment by dddns** [comment]
Hi Alec,

I'd love to give you that, but i have no idea who was the user that performed this task :(
From what you said, gd is going to be drop along with PHP 5.4, so Imagick is the replacement.

Am I right?

**Comment by alecpl** [comment]
Some sources suggest this might be fixed in newer php/libgd2 version. According to PHP changelog it's been fixed in 7.2.14 (and 7.3.1). As this is obviously a PHP bug we can't really workaround it (at least I see no way to do this).

**Comment by dddns** [comment]
Hi Alec,
Thanks for the explanation and time!
