### ISSUE TITLE
can the calendar plugin use davical

### ISSUE THREAD

**Issue by henrythemouse** [roundcube/roundcubemail#6987]
Hi,

I've been looking into the Kolab Calendar plugin for Roundcubemail. It looks nice but I'm thinking that it may not connect to any other caldav server but the Kolab Groupware server. I've tried to use my davical server, which generally works for most calendar clients, just not having any success with this plugin. I've also tried to import ics files with mixed success, the repeating events appear on the wrong days. 

Before I put to much time into this can someone tell me if the plugin is designed just for the Kolab server? 

TIA

**Comment by alecpl** [comment]
It is not designed only for Kolab, it has a sql driver, so you can use it without Kolab. The plugin has no caldav client functionality.

We do not support external plugins here. You should go to https://kolab.org.
