### ISSUE TITLE
Elastic: Changing recipient email not working

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#6988]
When composing a new message in Roundcube 1.4RC2 with Elastic skin changing recipient email is not working.

How to reproduce: 
- Start composing a new message
- Enter an email address in the To textfiled and navigate to another filed. 
The recipient's email address is surrounded by a gray textbox with an **X** at the end.
![image](https://user-images.githubusercontent.com/44122211/67635906-188a9000-f8d4-11e9-84eb-97b193b2495f.png)
- Doubleclick on the recipient’s email address to edit and input a different address
- Send the message

The message is sent to the address initially entered, not to the address given in the To textfiled.

**Comment by alecpl** [comment]
Fixed.
