### ISSUE TITLE
elastic4mobile: logout goes to desktop login page

### ISSUE THREAD

**Issue by nuess0r** [roundcube/roundcubemail#6989]
Today I updated to roundcube-1.4-rc2 and did also a php composer update.
I use the elastic4mobile plug-in to provide the new elastic skin to mobile phone users. Default skin is not elastic.

During testing I saw a flaw that I overlooked before: After logout on a mobile device the browser first returns to the default login page. When I reload this login page it changes again to the expected elastic login page.

**Comment by alecpl** [comment]
The proper place to report this plugin issues is https://github.com/thomascube/roundcube-elastic4mobile/issues
