### ISSUE TITLE
PHP Warning: Use of undefined constant LOG_EMERGE

### ISSUE THREAD

**Issue by iredmail** [roundcube/roundcubemail#6991]
- OS: OpenBSD 6.6
- PHP: 7.3.11
- Roundcube: 1.3.10
- Error message:

> roundcube: PHP Warning:  Use of undefined constant LOG_EMERGE - assumed 'LOG_EMERGE' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.3.10/program/lib/Roundcube/rcube_ldap_generic.php on line 73

**Comment by alecpl** [comment]
It should be `LOG_EMERG`. It's been fixed in https://github.com/roundcube/roundcubemail/commit/98349c19f6c8eedc, but not backported to 1.3

**Comment by alecpl** [comment]
Fixed.
