### ISSUE TITLE
Elastic: change tabindex of HTML/plain switch

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#6992]
With the old skins, one could easily navigate from the header input fields to the message body using tab: Enter recipient >> tab >> enter subject >> tab >> start writing the message. In elastic, the next element focused after the subject field is the html/plain switch. There are three problems with this:

1. One does not expect this, especially when used the Larry theme
2. The focus state is almost invisible and users think the focus is lost and that they need to click into the message body with the mouse
3. Switching the compose mode is a rare case

I suggest to adjust the tabindex attributes of the compose screen elements to improve the fast composition of a new email message just with the keyboard.

**Comment by alecpl** [comment]
I'm not sure about the tabindex change. It would be confusing when you want to jump to the Send button from the textarea. I'd like to hear from some UX/accessibility expert about this idea. Also, we're using this widget in other places e.g. identity form, so maybe it should be considered as a general use widget and not only mail composer.

I see a few other options:

4. improve focus indication on these tabs and maybe move them to the left side.
5. move the switch to the bottom of the textarea (either as tabs or some other element e.g. another toolbar).
6. move the switch to the inside of the textarea (but on top) i.e. plain text mode would have a toolbar as in html mode, but only with a single button "Switch to HTML". The TinyMCE toolbar would be extended with an additional button "Switch to plain text". Problem is that there's no intuitive way of accessing the inside toolbar with keyboard. TinyMCE uses ALT+F10 for this.
7. move the switch to the page toolbar (why not? if it's a rare case), but this would not work as good in other places (identity form). 
8. once I had an idea that we should not use the switch at all. Have the HTML mode always on, but detect if the content is plain or not. This however might be hard if at all possible (I can imagine a lot of issues with this solution too).

So, a quick fix would be 4., but I kind of like the idea in 6.

**Comment by thomascube** [comment]
4. should be done anyway, regardless of other choices. But it also doesn't really improve the fast-lane keyboard-only message composition. I agree that this would also include the send button being the next element in the tab order.

I'd vote for 7. This is sort of what we have in Larry skin.

**Comment by alecpl** [comment]
After a talk with UX expert I decided to go for solution 6. It's not easiest, so I might not finish it before 1.4.0, and anyway I think it should not stop the release.

**Comment by FlyveHest** [comment]
I'd like to add that it might be a good idea to consider the situation regarding "Add Contact" and "Add Recipient" as well, as it now takes 3 TABs to go from "To" to "Subject" field when composing a mail.

**Comment by alecpl** [comment]
Done.
![editor](https://user-images.githubusercontent.com/546788/68548310-cf663000-03eb-11ea-8b39-a5ce5f2488f9.png)
Recipient input is not that much of a problem as it has proper focus on buttons. And I don't want to remove these buttons nor change tabindex on them for now.
