### ISSUE TITLE
roundcube/newmail_notifier doesn't show any notification

### ISSUE THREAD

**Issue by pixelk0** [roundcube/roundcubemail#6994]
RoundCube version 1.4rc2
newmail_notifier version 0.8

The email notification (browser or desktop) doesn't show. The sound notification works, but is too obnoxious for my uses.

Tried the test in Firefox 70, Chrome 78, Opera 64, all result in the same error about the notification being disabled by the browser, but the browser never asked about enabling notification for this site. 

![ScreenCap-20191101-100049](https://user-images.githubusercontent.com/5732483/68014068-d9bb5800-fc8e-11e9-92b3-0df59669258d.png)

tried kitist/html5_notifier and it doesn't work either for me.

**Comment by pixelk0** [comment]
It seems notification are only supported on a secured (https) website. Could anybody confirm this ?
As this is a LAN-only instance of RoundCube, it's not practical nor needed to be HTTPS.

**Comment by smares** [comment]
According to MDN:

> In Chrome 62+ and Firefox 67+ you cannot request notifications at all unless the site is a secure context (i.e. HTTPS).

**Comment by pixelk0** [comment]
Thank you for your answer, It confirms what my searches seemed to indicate, I'll close this issue.

**Comment by smares** [comment]
Maybe Roundcube could check if it's being served over HTTPS and disable those options or show some sort of information on the page.
