### ISSUE TITLE
dummy.pdf appears for download

### ISSUE THREAD

**Issue by namiarj** [roundcube/roundcubemail#6995]
When someone has a download plugin like Internet download manager (IDM), the dummy.pdf file appears as file ready to download every time a page is loaded. Is this file really needed?

_Originally posted by @namiarj in https://github.com/roundcube/roundcubemail/issues/4941#issuecomment-549074698_

**Comment by alecpl** [comment]
This file is used to detect if a browser has a built-in (or plugin) pdf viewer. This is the only reliable way.

https://github.com/roundcube/roundcubemail/blob/release-1.4/program/js/app.js#L9936

If you find a bug or a better way let me know. What browser?

**Comment by alecpl** [comment]
No feedback.

**Comment by b33z** [comment]
If it helps, I just got the same thing

```
Win10 Pro 1903
Firefox 71.0
IDM 6.36 
```

If not, sorry to waste your time.
Cheers

**Comment by shynm** [comment]
Hello.
How I can fix this problem in my cPanel server ?

**Comment by DoobleD** [comment]
Same issue here. No better way of handling this?
