### ISSUE TITLE
Roundcube 14RC2 cannot upload attachments

### ISSUE THREAD

**Issue by RolandSM** [roundcube/roundcubemail#6998]
Hello,

at the moment I operate stable roundcube and also 14RC2 in another web folder. Both works perfect including several Plugins.

One thing I recognized that the 14RC2 could not Upload any file. I tried TXT files, PDF, XLSX, DOCX files with different sizes between few bytes and more kBytes. Upload etc. is 16MB.

I also checked the TEMP folder in config, its okay.
I chmod 777 the TEMP folder without success -> back to 755.
I added the XHeader to SAMEORIGIN without success.
I deactivated all plugins without success.

Old roundcube works with upload, new one not.

I´m sure, it´s not a roundcube issue, more on server or config but I don´t know what to try more?
There are many same issues here and on www but all I tried until yet without success...

**Comment by RolandSM** [comment]
Also with PHP as FCGI or FPM 7.3 7.2 7.1 7.0 all same error.

**Comment by alecpl** [comment]
What error do you get? Anything in logs or browser console?

**Comment by RolandSM** [comment]
error.log from the web is empty.
errors.log from the roundcube logs folder is empty.
error.log from main httpd is empty.

The browser console throws:
TypeError: rcm_tb_label_find_main_window(...) is null
from tb_label.js
but this is also on the "new mail" window when no file was uploaded.

**Comment by RolandSM** [comment]
How can I remove the "need feedback" label?
Today I see a PHP Warning: mod_fcgid: stderr: PHP Warning:  Unknown: POST data can't be buffered; all data discarded in Unknown on line 0

**Comment by johndoh** [comment]
neither `rcm_tb_label_find_main_window(...)` or `tb_label.js` is part of the Roundcube core or any plugins shipped with Roundcube. I guess you are running some third party plugin(s) try with plugins disabled.

I think only people with write access to the repo can apply/remove labels.

**Comment by alecpl** [comment]
What "need feedback" label? That POST error looks like a system error, nothing we can do about.

**Comment by alecpl** [comment]
Ah. "Need feedback" here ;). No, you can't remove it.

**Comment by RolandSM** [comment]
Solved the issue. The logs and temp folder needs access from www-data. The web owner ist standard and with this its not working.
Why also not working with chmod 777 I have no idea. But now it works.
