### ISSUE TITLE
Managesieve and duplicate extension

### ISSUE THREAD

**Issue by itservices-trust** [roundcube/roundcubemail#6999]
Hi,

we can't enable duplicate extension on RoundCube 1.3.10 with managesieve plugin. Our Dovecot 2.2.13 server has:
**sieve_extensions = +vnd.dovecot.duplicate [...]**
and the test duplicate works from within Thunderbird with Sieve plugin.

It's not possible to set a duplicate test with filters on RoundCube webmail, if we try to modify the existing filter created from Sieve Thunderbird plugin we receive an error.

No relevant log available, if we try to set **duplicate** into _dovecot.conf_ instead of **+vnd.dovecot.duplicate** we receive this error:
`error: require command: unknown Sieve capability duplicate. XXXXXX: line 3: error: unknown test duplicate (only reported once at first occurence). XXXXXXXX: error: validation failed. (3)`.

Any suggestions would be appreciated!

**Comment by alecpl** [comment]
Roundcube does not support vendor-prefixed extension name, so you have to upgrade dovecot or modify the plugin code.
