### ISSUE TITLE
plugins/password: Change password error

### ISSUE THREAD

**Issue by quicktrick** [roundcube/roundcubemail#7000]
Roundcube: current master branch (the same error exists for about 3 years I use Roundcube, all versions)

If the password in `password_db_dsn` in `plugins/password/config.inc.php` contains `@` character, like here:
```
$config['password_db_dsn'] = 'mysql://myuser:pvKuqR3hjF5@4Cf2$%d39WBgZcyWfxQU@127.0.0.1/mydb';
```
then I get an error in the `logs/errors.log`:
```
[06-Nov-2019 01:14:46 +0300]: <lqtv3jko> DB Error: SQLSTATE[HY000] [1045] Access denied for user 'myuser'@'127.0.0.1' (using password: YES) in /srv/www/mail.artsale.info/roundcubemail/pro
gram/lib/Roundcube/rcube_db.php on line 175 (POST /?_task=settings&_action=plugin.password-save)
```
If I change `myuser`'s password to the one without `@` character, like here:
```
$config['password_db_dsn'] = 'mysql://myuser:6AggPjo7rf^F7xP&9mCm2p5Uz$*B2i6Z@127.0.0.1/mydb';
```
then everything works fine.

BTW, the passwords with `@` characters work fine in `db_dsnw` in `config/config.inc.php`.

**Comment by alecpl** [comment]
This is not a valid URI. The `@` character in password have to be encoded as `%40`. This is mentioned in the doc linked from defaults.inc.php. https://pear.php.net/manual/en/package.database.mdb2.intro-dsn.php

**Comment by quicktrick** [comment]
Thank you, Aleksander!  But, as I guess, the alone percent character itself `%` is not allowed in the password too.  My password is not working with `%40` either.  Perhaps, this is because it has some `%d3` sequence in it.

Anyway, the similar password with `%40` and with alone `%` is working in in `db_dsnw` in `config/config.inc.php`.
