### ISSUE TITLE
DST issue in Brazil

### ISSUE THREAD

**Issue by Solaris17** [roundcube/roundcubemail#7002]
Brazil has recently decree'd non observance for DST in 2019. This causes a discrepancy between when a user seems to send/receive an email.

https://time.is/time_zone_news/no_dst_in_brazil_in_2019

**Comment by alecpl** [comment]
Roundcube depends on timezone information from PHP. So, there's nothing we can do on Roundcube side.

**Comment by Solaris17** [comment]
Awesome, do you have any more information on the call involved?
