### ISSUE TITLE
PHP warning: "array_merge(): Expected parameter 2 to be an array, null given in [...]/program/steps/mail/sendmail.inc on line 357"

### ISSUE THREAD

**Issue by hannob** [roundcube/roundcubemail#7003]
I'm monitoring our PHP logfiles for warnings and got one from our roundcube installation:

```
PHP Warning:  array_merge(): Expected parameter 2 to be an array, null given in [path]/program/steps/mail/sendmail.inc on line 357
```

This happened only once (on an actively used installation that we monitor regularly), so I can only assume this shows up under a relatively uncommon action. Version is 1.3.10.

**Comment by alecpl** [comment]
Fixed.

**Comment by Sorafuddin221** [comment]
help me please ,fixed this problem.
Warning: array_merge(): Expected parameter 2 to be an array, string given in C:\xampp\htdocs\consult\wp-content\plugins\elementor\includes\managers\controls.php on line 694
