### ISSUE TITLE
STARTTLS failed

### ISSUE THREAD

**Issue by gilgongo** [roundcube/roundcubemail#7005]
Sorry to bother you, but I am trying to fix a problem with our Roundcube installation that has appeared after a postfix config change. Despite trying to triangulate on the issue, I can't work out what change was responsible without compromising the security that the changes were designed to address.

I posted this [question on Serverfault](https://serverfault.com/questions/990716/how-to-debug-lost-connection-after-starttls).

**Comment by alecpl** [comment]
That might be a few things. Certificate validation. Server may require TLS version that PHP does not support (try with disabled *_tls_protocols in postfix). What PHP version? What Roundcube version? Vanilla or from distribution? Did you try smtp_conn_options?

**Comment by gilgongo** [comment]
Thanks very much for getting back to me. We're using Roundcube 1.3.6+dfsg.1-1 from Ubuntu 18.04 repos. PHP v7.2.24. 

Sending mail from the current installation of Roundcube worked OK with our previous Postfix setup, but doesn't now that we've tightened up the sending rules (note also that reading mail is fine). 

All other SMTP clients are authenticating OK. Roundcube is connecting to the mail server over the LAN interface though, but I assume Postfix would be rejecting that with a relay denied message if it was to do with network permissions.

I've not tried smtp_conn_options. Are these the ones [referred to here](https://wiki.archlinux.org/index.php/Roundcube#Tips_and_tricks)? If so, this implies we need to provide paths to certificates that are on the mail server, is that right?

**Comment by gilgongo** [comment]
OK I found it. Revealing the auth failure gave me the clue. SMTP users now need to be validated on our zero trust block chain. Sigh. Sorry about that.
