### ISSUE TITLE
[1.4] Unable to leave sieve filter rule

### ISSUE THREAD

**Issue by HLeithner** [roundcube/roundcubemail#7007]
While testing final 1.4 I found a problem with manage sieve plugin. Iirc this doesn't exists in 1.4-rc2. 

After selecting a rule from the filters list it's not longer possible to click on "Mail", "Compose", "contacts".... and also the Settings buttons are not working. You can only change the "Actions".

If you click on Save it's possible again to go to mail overview, same is true if you reload the page.

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.

**Comment by HLeithner** [comment]
Fix confirmed, thank you very much for this great release!

**Comment by sffax** [comment]
For some reason, this fix did not work for me. I replaced: *plugins/managesieve/managesieve.js* with the patched version, restarted the web server, cleared the cache, same behaviour. Does this fix require any file other than the one I referenced above?

**Comment by alecpl** [comment]
Did you remove managesieve.min.js?

**Comment by sffax** [comment]
Apologies, I forgot about that! All good now. Thanks for the help!
