### ISSUE TITLE
Where language setting comes from?

### ISSUE THREAD

**Issue by 532910** [roundcube/roundcubemail#7008]
I have no `language` setting and the front page properly localized depending on Accept-Language. But after logging in I see all in english. Deleting `/var/lib/roundcube/roundcube.db` doesn't help.

**Comment by 532910** [comment]
Aha, I figured it out, I was not quite right: roundcube remembers the Accept-Language on the first login and stores it in the user settings. But the expected behaviour is to use Accept-Language always untill the language setting is changed by user.

**Comment by alecpl** [comment]
Well, some would say that saving the language used with the app last time is better. It works this way for 10 years and you're the first one requesting such change. So, I guess we'll keep it as is.
