### ISSUE TITLE
Wrong file ownerships after upgrade as root

### ISSUE THREAD

**Issue by cgzones** [roundcube/roundcubemail#7009]
When upgrading Roundcube as root via
```
wget https://github.com/roundcube/roundcubemail/releases/download/1.4.0/roundcubemail-1.4.0-complete.tar.gz
tar xf roundcubemail-1.4.0-complete.tar.gz
./roundcubemail-1.4.0/bin/installto.sh DESTDIR
```
the installed files have the ownership pair `501:80`, which is probably always invalid.

Please either set the ownership after the upgrade of all files in DESTDIR (e.g. to the owner of DESTDIR/index.php prior the upgrade) or print a warning at the end of the upgrade script, that the administrator might need to fix them.

**Comment by alecpl** [comment]
It's not that easy. In some setups owner of index.php might be irrelevant, but for example temp and logs dir may use a different owner. For my setup it was never an issue. I guess, we'll end up with a warning (also in UPGRADING file).

**Comment by johndoh** [comment]
The `tar` command has different defaults if its run as an ordinary user or a superuser, from the man page:
```
--no-same-owner
    extract files as yourself (default for ordinary users)
...
-p, --preserve-permissions, --same-permissions
    extract information about file permissions (default for superuser)
...
--same-owner
    try extracting files with the same ownership as exists in the archive (default for superuser)
```

**Comment by matzex** [comment]
> It's not that easy. In some setups owner of index.php might be irrelevant, but for example temp and logs dir may use a different owner. For my setup it was never an issue. I guess, we'll end up with a warning (also in UPGRADING file).

Thanks! Would be also nice to have a hint which folders and paths are affected by the ownership/groups. I normally do not have all the affected folders in mind when upgrading with the "installto" script.

**Comment by cgzones** [comment]
Or you could create the tar file with `--owner root --group root`.
Anyhow I think a note in the UPGRADING file is sensible, cause end-user systems might differ, e.g. I am using `root:www-data` (except temp/ and logs/).

**Comment by alecpl** [comment]
Done.
