### ISSUE TITLE
Database schema update failed.

### ISSUE THREAD

**Issue by GaneshKandu** [roundcube/roundcubemail#7013]
Hi,

I am getting error while upgrade to 1.4.0

![Roundcube Webmail Installer](https://user-images.githubusercontent.com/12833130/68571334-c4151200-0488-11ea-956f-0e79ba23980e.png)

Array ( 
[type] => 8
 [message] => Undefined index: errors
[file] => /home/soft/public_html/roun998/program/include/rcmail_utils.php
[line] => 208
 ) 

**No Log file created**

**Comment by alecpl** [comment]
Try to use installto.sh from the command line.

What version did you update from? What PHP version? What database engine?

**Comment by GaneshKandu** [comment]
> What version did you update from? 

1.3.10 to 1.4.0

> What PHP version?

php version 5.4

> What database engine?

Innodb

**Comment by alecpl** [comment]
Please, run the update in command line. It should print some error. Or maybe there's something in MySQL log? 

Three last files at https://github.com/roundcube/roundcubemail/tree/release-1.4/SQL/mysql contain upgrade commands. As a last resort you may try executing them manually on the database.

**Comment by GaneshKandu** [comment]
Got this output while executing ```installto.sh``` from the command line manually.
```
Target installation already in version 1.4.0. Do you want to update again? (y/N)
Copying files to target location...done.

NOTICE: JavaScript dependencies installation skipped...
NOTICE: The 'installer' directory still exists. You should remove it after the upgrade.

Running update script at target...
WARNING: Mimetype to file extension mapping doesn't work properly!
Please check the 'mime_types' config option and run this script again.
Executing database schema update.
Updating database schema (2018021600)... [OK]
ERROR: Error in DDL upgrade 2018122300: [1091] Can't DROP 'rcij_uniqueness'; check that column/key exists
Updating database schema (2018122300)... [FAILED]
All done.
```

**Comment by alecpl** [comment]
Are you using db_prefix? Could you show what is returned by query `show create table filestore;`?

**Comment by alecpl** [comment]
Fixed.

The solution for you is to execute
```
ALTER TABLE `rcij_filestore` DROP INDEX `uniqueness`;
```
manually, them remove
```
ALTER TABLE `filestore` DROP INDEX `uniqueness`;
```
from 2018122300.sql file and run the update script again.

**Comment by GaneshKandu** [comment]
Hi,

Just downloaded Stable version - 1.4.0 Complete package for upgrade
but i found old package i downloaded and the latest package both are same

**Comment by alecpl** [comment]
This is fixed in git only, will be available with 1.4.1 release.

**Comment by GaneshKandu** [comment]
OK!

**Comment by alecpl** [comment]
You can also just replace this file https://raw.githubusercontent.com/roundcube/roundcubemail/71990b59d6839f45c59b5f12209c3a3001d4a7d0/program/lib/Roundcube/rcube_db.php

**Comment by GaneshKandu** [comment]
when 1.4.1 is going to be release ?

**Comment by alecpl** [comment]
However, this file replacement might not work, because your database is already in an invalid state. You can try that if you have the original (1.3.10) database backup.

**Comment by GaneshKandu** [comment]
> 
> 
> You can also just replace this file https://raw.githubusercontent.com/roundcube/roundcubemail/71990b59d6839f45c59b5f12209c3a3001d4a7d0/program/lib/Roundcube/rcube_db.php

Thanks ! its working for me
