### ISSUE TITLE
'Display next list entry after delete/move' does not honor sort order

### ISSUE THREAD

**Issue by dia-de-muertos** [roundcube/roundcubemail#7014]
Hi,
when activating 'Display next list entry after delete/move' in roundcube  1.4 and setting sort oder 'sent date / descending', rc doesn't show the next (newer) mail but the previous (older) one.

**Comment by alecpl** [comment]
It should select the message below as it is displayed on the list, no matter what sorting order you use. Isn't that what happens?

**Comment by druckmusik** [comment]
Correct, this is what happens, but this is not what the user normally wants.
If sorting order is descending, the message above should be selected.

**Comment by alecpl** [comment]
No, it should not. Imo, this is not what I would expect. Even if the order is descending you read the list from top to bottom. Note this is "Display next" not "Display newer/older".
