### ISSUE TITLE
Enhancement: Customize the quick action when hovering messages

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#7019]
Elastic currently displays the flag / unflag option when hovering over messages in the list. Any chance this action can be made customizable with a future version so that one could replace that with a delete option for example or a read / unread toggler? I am used to quickly being able to delete mails using such an action, currently implemented like that in Outlook and Windows Mail.

Another thing that is debatable is what should happen if multiple messages are selected. Outlook for example applies the flag to all selected messages. Same thing with deleting - if multiple messages are selected and you click on the red x next to a message in the list, all selected messages are deleted.

**Comment by alecpl** [comment]
How about you just use contextmenu plugin? I don't want to add any customization options like this. I see in outlook.com these hover-buttons are available only if you selected a single message, they disappear when more than one message is selected.
