### ISSUE TITLE
html_signature flag on updated in identities table

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7021]
using git-master when setting up a signature on an identity the html_signature col in the database is not updated. If you currently have a plain text sig and you change the editor to HTML and save then HTML is saved in the database but the html_signature field stays as '0'. same the other way round if you currently have an HTML sig and you change it to plain text the field stays as '1'.

EDIT: I checked 1.4.0 and the html_signature field updates fine there so may be this has to do with 3c01f472e09033fa705ff1940e5b8cf5c323001b

**Comment by alecpl** [comment]
Fixed. Thanks @johndoh
