### ISSUE TITLE
Issue with password's containing "€" char

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#7023]
Howdy,

When i have password's with the "€" chat, the auth fails agains postfix with SASL.
Via MSOutlook works ok.
I tried all MECHs available in RC, the *-MD5, PLAIN or LOGIN.

For example a password like: C@d€t€s.444

I updated to 1.4 today (great work in the responsive theme), and same behavior.
Is this a bug or something that i need to fine tune in the config?

Jorge

**Comment by alecpl** [comment]
Depends what charset your imap backend is using. See `password_charset` option in main config.

**Comment by dddns** [comment]
Hi Alec,
Sorry about this, problem it's not with IMAP, but with SMTP, sending emails.
Is there anything I can do about it?

**Comment by alecpl** [comment]
The same applies to SMTP. You can also check #7011.

**Comment by dddns** [comment]
Alec, 

Ok saw it but, with or without TLS, it fails.
I'm going something wrong,

**Comment by dddns** [comment]
Alec,

Sorry for the noise.
Just changed from Cyrus SASL to dovecot SASL, since Cyrus doesn't do UTF8.

Thanks!
