### ISSUE TITLE
Roundcube 1.4.0 stable release - Password Plugin - errors.log

### ISSUE THREAD

**Issue by UTAVATU** [roundcube/roundcubemail#7025]
Dear Friends

First of all thank you for Roundcube 1.4.0 stable release. I have enabled Password Plugin and when I go to Settings>Password to change password (I don't even start to change password, just click Password in Menu to load Password Site), then I have in:

> /var/www/html/roundcube/logs/errors.log

`PHP Error: Password plugin: Driver file does not exist (/var/www/html/roundcube/plugins/password/drivers/1.php) in /var/www/html/roundcube/plugins/password/password.php on line 436 (GET /?_task=settings&_action=plugin.password)`

Changes from default config.inc.php:

> /var/www/html/roundcube/plugins/password/config.inc.php

```
$config['password_strength_driver'] = true;
$config['password_minimum_length'] = 12;
$config['password_minimum_score'] = 5;
$config['password_force_new_user'] = true;
```

Sincerely

**Comment by alecpl** [comment]
`password_strength_driver` is not a boolean option.
