### ISSUE TITLE
Icons look very blurry and pixelated on highDPI screen

### ISSUE THREAD

**Issue by peterdk** [roundcube/roundcubemail#7026]
Just installed Roundcube 1.4 using Docker, and checking it out on Firefox on Windows 10.
Looks great, except that the icons used are very pixellated and blurry. I am using a 4K monitor, with 200% scaling. 

It would be great if the icons were it a bit more highres or SVG/font based.

If I can do anything to help, I would be willing to look into doing that.

**Comment by alecpl** [comment]
I guess you're talking about the Larry skin. Did you try Elastic?

**Comment by peterdk** [comment]
Ah sorry, yeah. I saw I had the Larry skin enabled. Probably caused by using a older version earlier?
I'll test it out.

**Comment by peterdk** [comment]
Yes, it works great now! Sorry to bother :)
