### ISSUE TITLE
Problem with attached vCard files containing multiple contacts

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7027]
In Roundcube 1.4 with Elastic skin when viewing a message with attached vCard file with multiple contacts, Name, Email and Import button is displayed for every contact above the message text. 
If the vCard file contains many contacts, the entire window is filled and users have to scroll to the end of import entries to read the message. 

![vCard-atach](https://user-images.githubusercontent.com/44122211/68708560-a6d16800-059c-11ea-8379-70f503f4abf4.jpg)

It would be more convenient if the message text is above the Import buttons or there should be only one button to import all contacts.

**Comment by alecpl** [comment]
I agree we should display one box with one Import button. When there's more than one contact it would read "X contacts...", then clicking the Import button would open a dialog with all contacts listed and checkboxes attached, so user can select specified contacts. The dialog would have  "Import All" and "Import Selected" buttons.

**Comment by Bojo78** [comment]
The issue exists with Larry skin too.

**Comment by alecpl** [comment]
Implemented.
