### ISSUE TITLE
Easier understanding of managesieve filter activation

### ISSUE THREAD

**Issue by inbaz** [roundcube/roundcubemail#7028]
![grafik](https://user-images.githubusercontent.com/8452304/68751558-1463af80-0602-11ea-91cb-5cd0b2c52beb.png)

When it comes to activation and deactivation of filters, it's complex for non IT users, because it's disabled when the checkbox is enabled and it's enabled when the checkbox is disabled.

For a better UX it would be nice to switch the functionality. Label it "Filter enabled" and set it to active when the checkbox is active and to inactive when the checkbox is inactive.

That would be nice.

**Comment by alecpl** [comment]
Makes sense.

**Comment by alecpl** [comment]
Fixed.
