### ISSUE TITLE
lessc - SyntaxError in global.less

### ISSUE THREAD

**Issue by YanneckMeyer** [roundcube/roundcubemail#7031]
While compiling as in the manual described, less throws an error in global.less
```bash
lessc styles/styles.less > styles/styles.css

SyntaxError: expected ')' got 'r' in {RootOfRoundcube}/skins/elastic/styles/global.less on line 12, column 10:

12 @import (reference) "variables";
13 @import (reference) "mixins";
```

Downloaded the files from roundcube.net and upgraded from RC1 to the latest version (1.4). Didn't changed the file and also _styles.less and _variables.less is empty. 
```bash
lessc 1.4.2 (LESS Compiler) [JavaScript]
```

**Comment by alecpl** [comment]
I'm using lessc 1.6.3 and it works. So, I guess you need a newer version. I'll try to find out what is the minimal version and put it into the README file.

**Comment by YanneckMeyer** [comment]
With the newest version of lessc it works!
Thank you very much for the quick information and for editing the README for users with the same problem!

**Comment by alecpl** [comment]
`@import (reference)` requires lessc 1.5.0.

**Comment by alecpl** [comment]
Done.
