### ISSUE TITLE
Problem with upgrading from 1.4 RC1 to Stable 1.4 Updating database schema

### ISSUE THREAD

**Issue by studiowena** [roundcube/roundcubemail#7032]
Hi,

Im updating roundcube with shell script
`bin/installto.sh`

everything goes OK but DB update failed with last line

```
Your configuration files are now up-to-date!
Executing database schema update.
Updating database schema (2013011000)... [OK]
Updating database schema (2013042700)... [OK]
Updating database schema (2013052500)... [FAILED]
ERROR: Error in DDL upgrade 2013052500: [1050] Table 'cache_shared' already exists
All done.
```

Dont know if its OK or i need to do something more?

**Comment by alecpl** [comment]
What version are you upgrading from? What db engine?

**Comment by studiowena** [comment]
upgrading from 1.4 RC1 to Stable 1.4, DB mysql

`$config['db_dsnw'] = 'mysql://`

**Comment by alecpl** [comment]
Then something is completely wrong. It should not execute such old schema change scripts. Normally, the script knows which scripts to execute from the `system` table content.

**Comment by studiowena** [comment]
so what i should do? Roundcube seems to working OK hm

**Comment by alecpl** [comment]
Your database schema might be in an invalid state now. Do you have backup from before the upgrade? Then you could check content of the `system` table. If the content will be invalid then I can't really help you. Seeing that content would allow me at least to know if it's the script bug or not.

**Comment by studiowena** [comment]
yes i have backup below is system table from db backup
```

--
-- Struktura tabeli dla tabeli `system`
--

CREATE TABLE `system` (
  `name` varchar(64) NOT NULL,
  `value` mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Zrzut danych tabeli `system`
--

INSERT INTO `system` (`name`, `value`) VALUES
('roundcube-version', '2013042700');
```

**Comment by alecpl** [comment]
Proper value for that entry in 1.4rc1 is '2019092900'. So, did you upgrade to 1.4.rc1 from some older version? Now it will be hard to find out what happened. You should probably:
1. compare your database with https://github.com/roundcube/roundcubemail/blob/1.4rc1/SQL/mysql.initial.sql
2. Update the version entry
3. Run the update script again.

**Comment by alecpl** [comment]
Sorry, one correction. The proper file is https://github.com/roundcube/roundcubemail/blob/1.4-rc1/SQL/mysql.initial.sql and the version number is different, but it does not change anything in what I have said.

**Comment by studiowena** [comment]
i have upgraded from 1.3.9 to 1.4 RC1 but dont remember what happend but roundcube wokrs good. Maybe i do some mistake with upgrade then.

**Comment by studiowena** [comment]
i have check my DB and campare with mysql files to upgrade in instalation and it seems my DB version is from 2016112200 but update.sh scripts dont know it even when i manual chaned in system table to 2016112200 update.sh is trying update DB from 2013042700

So i have looked at these DB upgrade sql files and manual updated my DB from 2018021600 to 2019092900

and setup system version to 2019092900.  When running bin/update.sh again and type ? what version i have still script dont know i have 1.4.0 and trying update my DB from 2013042700
