### ISSUE TITLE
Missing bootstrap.min.css.map in elastic skin

### ISSUE THREAD

**Issue by xkill** [roundcube/roundcubemail#7035]
Hi,

I just upgraded my Roundcube installation to 1.4.0 and activated the elastic skin. I noted, on the browser console, that the bootstrap.min.css.map is not included on the roundcube complete tar.gz and it is referred on the file bootstrap.min.css.

```
# tail -n1 skins/elastic/deps/bootstrap.min.css
/*# sourceMappingURL=bootstrap.min.css.map */
```

I also noted that the bootstrap.bundle.min.js.map is missing:
```
tail -n1 skins/elastic/deps/bootstrap.bundle.min.js 
//# sourceMappingURL=bootstrap.bundle.min.js.map
```

**Comment by alecpl** [comment]
I'm not sure we should provide these. It is additional 800KB (150KB gzipped). @thomascube what do you think?

ps. we're using vanilla Bootstrap releases, so you can get these files from Bootstrap if you really need them.

**Comment by thomascube** [comment]
Nope, I don't think we should include them. Browsers anyway only request them when opening the console. For release package, we could consider to strip the comments off the bundled files.

**Comment by thomascube** [comment]
Maybe we can make this a feature of `install-jsdeps.sh`

**Comment by alecpl** [comment]
Done.
