### ISSUE TITLE
Cannot click on anything when displaying a filter using elastic skin

### ISSUE THREAD

**Issue by xkill** [roundcube/roundcubemail#7036]
Hi,

I noted a bug on the elastic that makes it unusable if sieve filters plugin is enabled. Steps to reproduce:

1. Login
2. Go to settings
3. Click on Filters
4. Click on any filter set
5. Try to click on any where, nothing works until you click on "add", "remove" or "save".

Attached a screencast.
![screencast-sieve-filters-bug](https://user-images.githubusercontent.com/208463/68876345-96d49800-0704-11ea-98c1-e60eccb6873e.gif)

**Comment by reinob** [comment]
I have the same issue, but with the Larry theme, so I guess it's not a theme-dependent issue.

**Comment by reinob** [comment]
OK, at least in my case the patch provided with this issue https://github.com/roundcube/roundcubemail/issues/7007 solved the problem.

**Comment by xkill** [comment]
> OK, at least in my case the patch provided with this issue #7007 solved the problem.

Yes, the patch fixes the problem.
