### ISSUE TITLE
the pop options is not properly show inside mail 

### ISSUE THREAD

**Issue by EGY-DEVELEPORER** [roundcube/roundcubemail#7037]
<a href="https://www.imageupload.net/image/Mt98A"><img src="https://www.imageupload.net/upload-image/2019/11/14/roundcube.md.png" alt="roundcube.png" border="0" /></a>

**Comment by alecpl** [comment]
Something is wrong with your installation. Check browser console for errors. Maybe missing javascript dependencies or some old plugin. Could be anything.
