### ISSUE TITLE
Elastic: "compose" button placement problem on mobile screens

### ISSUE THREAD

**Issue by sffax** [roundcube/roundcubemail#7038]
When accessing the UI on a small screen using the elastic skin, the "compose" button is placed on the lower right side of the browser window, completely obstructing the "next" and "last" navigation bar buttons. This makes it impossible to navigate to the next page.

The compose button needs to be raised a few pixels, just enough to expose the page navigation buttons.

**Comment by alecpl** [comment]
Looks like a regression related to the column resizing feature.

**Comment by alecpl** [comment]
Fixed.

**Comment by HLeithner** [comment]
Your fix removes the button, is this intended?

**Comment by alecpl** [comment]
Oh, I was testing my fix in contacts and other places, but not in Mail.

**Comment by alecpl** [comment]
Fixed.

**Comment by HLeithner** [comment]
Confirmed thx.

**Comment by revoltown** [comment]
will check what version of roundcube i have , but cant use compose button on mobile web gui, is like a background, pussing on it opens a message behind it...
