### ISSUE TITLE
Renaming the elastic skin results in dialogs displayed out of screen

### ISSUE THREAD

**Issue by martijnbrinkers** [roundcube/roundcubemail#7039]
If the elastic skin is renamed and enabled (i.e., the renamed skin is used as the default skin). The popup dialogs are shown out of screen. This happens without changing anything to the default elastic skin (only the name of the skin)

![rc-dialogs-offscreen](https://user-images.githubusercontent.com/32571910/68930835-84537080-078f-11ea-8fa1-31590bf6e6eb.png)

**Comment by alecpl** [comment]
It is probably because jqueryui plugin does not support unknown skins the way you would wanted to. I don't think we will support that. Why would you want to change the skin name?

**Comment by alecpl** [comment]
Actually you could try:
```
$config['jquery_ui_skin_map'] = array(
  'larry' => 'larry',
  'default' => 'elastic',
);
```
And maybe we should make it a default.

**Comment by alecpl** [comment]
In your case, you'd have to add `'your-skin-name' => 'elastic'` to this array.

**Comment by alecpl** [comment]
Fixed, but this is only one plugin. There might be other plugins that know nothing about your skin. So, you should probably use skin inheritance.
