### ISSUE TITLE
No cancel in filter edit mode

### ISSUE THREAD

**Issue by scarleo** [roundcube/roundcubemail#7040]
If I go to Settings -> Filter -> (Click on a filter to edit) there is no way to go back except clicking Save. I would have expected either a Cancel button, or let me navigate to any other menu item to discard any changes made. All menu items are disabled while in filter edit mode. There is no way to discard changes. Roundcube 1.4 with Elastic theme.

**Comment by smares** [comment]
You cannot leave the filter edit because of bug #7007
