### ISSUE TITLE
Different fields for csv2vcard.inc between languages (localization)

### ISSUE THREAD

**Issue by shirokoweb** [roundcube/roundcubemail#7041]
Hi,

I try to import csv contacts created with Office 365.

While checking the file to make sure it has the correct labels, I noticed there were differences between localization files. For example: [en_US](https://github.com/roundcube/roundcubemail/blob/master/program/localization/en_US/csv2vcard.inc) and [fr_FR](https://github.com/roundcube/roundcubemail/blob/master/program/localization/fr_FR/csv2vcard.inc)

The en_US files also has a comment for // MS Outlook 2019 Does it mean it won't work for MS Outlook above ? (2019)

Which labels shall I use for my csv columns in order to successfully import my contacts ?

I searched the [forum](https://www.roundcubeforum.net/), but despite all my efforts, I can't find any answer (other users questions aren't answered either btw).

Thanks

**Comment by thomascube** [comment]
The locale files represent the known results when exporting CSV contacts from Outlook in various languages. Using the English column names should work beset. Please also read the [small section in our wiki](https://github.com/roundcube/roundcubemail/wiki/FAQ#importing-contacts-from-csv) and let us know if we can improve things.

**Comment by alecpl** [comment]
From what I see Office 365 uses the same labels as Outlook. If there's any label missing, create a new ticket.
