### ISSUE TITLE
Database schema update problem upgrading Roundcube 1.4 RC2 to 1.4.0

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7042]
DB: MySQL 5.5.61
RC: 1.4RC2 -> 1.4.0
I've successfully upgraded Roundcube to ver. 1.4.0 using web installer, but noticed some issues with DB schema update. 
The installer shows DB Schema: OK, but the system version in DB is wrong:
![image](https://user-images.githubusercontent.com/44122211/68971835-16d92b80-07f3-11ea-9a90-0fd015b264e6.png)
```
SELECT `value` FROM `system` WHERE `name` = 'roundcube-version';
+------------+
| value      |
+------------+
| 2018122300 |
+------------+
```
If I manually execute 
```
# bin/updatedb.sh --package=roundcube --dir=SQL --version=2019092900
Updating database schema (2019092900)... [OK]

SELECT `value` FROM `system` WHERE `name` = 'roundcube-version';
+------------+
| value      |
+------------+
| 2019092900 |
+------------+
```
The database is updated.

**Comment by alecpl** [comment]
The schema check in installer compares existence of tables and columns. There was no such change in this specified upgrade. I guess we should add check for the version string.

**Comment by alecpl** [comment]
Fixed.
