### ISSUE TITLE
The installto.sh should check PHP version

### ISSUE THREAD

**Issue by isonno** [roundcube/roundcubemail#7043]
When I tried to upgrade to 1.4.0, the installer failed trying to call a PHP function that's in PHP 4.0 but not previous version. My web host is still on PHP 3.6.

It would be helpful if the `installto.sh` script first checked the PHP version and cleanly exits if it can't install because the version in use is too old.

**Comment by alecpl** [comment]
No, we just don't. Noone is using PHP<5 these days. We'll not support such rare setups.

**Comment by rpv-tomsk** [comment]
Are you serious ?? That is real case ??
Very extremely... 
Impressed.
