### ISSUE TITLE
Unable to log in after upgrade from 1.3.10 to 1.4.0

### ISSUE THREAD

**Issue by bovender** [roundcube/roundcubemail#7044]
After upgrading from 1.3.10 to 1.4.0 (using a Docker container), I am unable to log in to my Roundcube instance. I did not change the config file. When I revert the Docker container tag back to 1.3.10, it works again.

The log shows this error:

    Could not connect to ssl://MYDOMAIN:993: Unknown reason in /var/www/html/program/lib/Roundcube/rcube_imap.php on line 196

What might be the problem? Do I need to change anything in the config file?

**Comment by alecpl** [comment]
Looks like configuration issue. The docker repo is at https://github.com/roundcube/roundcubemail-docker

**Comment by thomascube** [comment]
I'm experiencing this also in a non-docker environment with PHP 7.3 when connecting to a host using a Letsencrypt certificate.

**Comment by bovender** [comment]
My IMAP server presents a Letsencrypt certificate too. 

I opened an issue in the Roundcube Docker repo: roundcube/roundcubemail-docker#72

But your comment does make it seem as if it is not Docker-related after all.

**Comment by thomascube** [comment]
I get the same "unknown error" with PHP 7.3 on macOS. Connection fails with the error `routines:tls_process_server_certificate:certificate verify failed` which I'm now trying to investigate. When disabling cert checks (`verify_peer` = false), connection works but that's not the idea.

**Comment by thomascube** [comment]
> But your comment does make it seem as if it is not Docker-related after all.

It's related to the underlying operating system or the openssl lib PHP is linked against. It's not bug of the Roundcube webmail application and therefore we should continue to track this issue in the roundcubemail-docker repo.
