### ISSUE TITLE
Add a hook to customize messageSummary in Elastic skin

### ISSUE THREAD

**Issue by ScottPeterJohnson** [roundcube/roundcubemail#7047]
Hello! First off, fantastic work on the Elastic skin, it looks beautiful.

Since the format of the "From" when viewing messages in the Elastic skin changed to be more compact however, it slightly broke the authres_status plugin and it doesn't look like there's a way to fix it without adding some kind of hook to the messageSummary output. (I could be wrong, any alternate method would be great too.)

See pimlie/authres_status#26

Thanks!

**Comment by alecpl** [comment]
You can use "template_object_messageSummary" hook.
