### ISSUE TITLE
Unsubscribing sent folder not possible

### ISSUE THREAD

**Issue by eschiendorfer** [roundcube/roundcubemail#7050]
I am using roundcube and outlook. In roundcube I have set up the special folders correctly, so they sync with outlook. Somehow roundcube always creates to folders called "sent" and "trash". It's possible to unsubscribe "trash". But it's not possible for "sent". 

This means I have a completly empty and useless folder in outlook. (My sent messages goes to "Gesendete Elemente").

Accordingly to plesk, I am using: 1.3.10

**Comment by smares** [comment]
Are you sure it isn't the IMAP server that auto-creates and auto-subscribes those folders? I know you can configure that in Dovecot.

**Comment by eschiendorfer** [comment]
@smares Thanks a lot for your input.!I wans't aware of that. You are right, it is related to dovecot. I will close this issue now...
