### ISSUE TITLE
Larry: Enter key does not work on messages list in "List" layout

### ISSUE THREAD

**Issue by wvolz** [roundcube/roundcubemail#7052]
The enter key action no longer does anything in the list view of the Larry theme in 1.4.0. Previously this would show the highlighted message. I believe this is related to commit 84c4d062c6e001c8bd888558fdd11d88fe2d823d.

**Comment by alecpl** [comment]
Confirmed.

**Comment by mvldebian** [comment]
Will opening email with ENTER be functional again in the next version? my users missed it .. can you manually adjust it to work?

**Comment by alecpl** [comment]
Fixed.
