### ISSUE TITLE
forward big messages (100MB attachement) - max execution time

### ISSUE THREAD

**Issue by makskkkk** [roundcube/roundcubemail#7054]
Roundcube always throws an error when I trying to forward an email with big attachement.
I set a large memory_limit = 1G and execution_time = 10min, but it didn't help

The problem lies in reading the email line by line.
 /usr/share/roundcube/program/lib/Roundcube/rcube_imap_generic.php
do {
3695             $line = $this->readLine(4096);
3696             if ($response !== null) {
3697                 $response .= $line;
3698             }
3699         }

and:
else {
2078                         $result[$id] = 0;
2079                     }
2080                 }
2081             }
2082         }
2083         while (!$this->startsWith($line, $key, true, true));

**Comment by alecpl** [comment]
What version? Try with 1.4.0.

**Comment by makskkkk** [comment]
I had an old version of roundcube. After the upgrade, the problem disappeared.
Sorry, my mistake.
