### ISSUE TITLE
Inline image (x-png) not shown, instead show a pink square

### ISSUE THREAD

**Issue by karlmendes** [roundcube/roundcubemail#7056]
Content-Type: multipart/mixed;
  boundary="----=_Part_2_1102845260.1574046000277"

Content-Type: image/x-png
Content-Transfer-Encoding: base64
Content-Disposition: inline
Content-ID: <R1574046000051-37-reportChart.png>

It's possible because the filetype, the image not shown inline mail ?

**Comment by alecpl** [comment]
What version? Works for me with 1.4.x

**Comment by karlmendes** [comment]
Hi, if i change Content-Type: image/x-png to Content-Type: image/png works perfectly...

**Comment by alecpl** [comment]
I'll ask again. What version? What PHP version? That might have been fixed, so please don't waste my time.

**Comment by karlmendes** [comment]
PHP 5.6.24
RELEASE 1.1.5

**Comment by alecpl** [comment]
Come on. Upgrade.
