### ISSUE TITLE
No one Email is receiving in roundcube mail account.

### ISSUE THREAD

**Issue by vsakariya** [roundcube/roundcubemail#7057]
Hello Friends,

I have checked much and more but i can't geting any emails in Roundcubemail account i am missing some setting or other?
Can some one help me?

Thank you.

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/wiki/Howto-Report-Issues

**Comment by thomascube** [comment]
I think you reported to the wrong place. There's no such thing as a "Roundcubemail account". Roundcube is not a service but free software which your hosting provider installed on their servers. Please contact your email hosting provider for first level support.
