### ISSUE TITLE
Elastic: Warning toasts are hard to read

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#7058]
The warning toasts are a bit hard to read being white text on yellow-ish background.

![image](https://user-images.githubusercontent.com/818380/69332268-9b460700-0c56-11ea-856a-89509640e7cf.png)

**Comment by alecpl** [comment]
I agree. Some help from a graphic designer would be nice. Here's what we have now:
![messages](https://user-images.githubusercontent.com/546788/69492377-865db380-0ea2-11ea-8a44-75c6ee594a70.png)
Here's some ideas:
1. `color: #444`
![warning1](https://user-images.githubusercontent.com/546788/69492499-ea34ac00-0ea3-11ea-8c65-ec3ef3cd38c1.png)
2. `background-color: #ffbf00`
![warning2](https://user-images.githubusercontent.com/546788/69492502-eef96000-0ea3-11ea-86f5-ca39578bdc46.png)
3.  `color: #444` and `background-color: #ffbf00`
![warning3](https://user-images.githubusercontent.com/546788/69492517-21a35880-0ea4-11ea-86bd-8b68e1e61128.png)
4. `color: #997300`
![warning4](https://user-images.githubusercontent.com/546788/69492539-66c78a80-0ea4-11ea-9987-fa6ee42820db.png)

And all together.
![warnings](https://user-images.githubusercontent.com/546788/69492657-b064a500-0ea5-11ea-9251-34c150589c59.png)

**Comment by alecpl** [comment]
According to accessibility tools v2 is still bad. v4's contrast is better than the blue information box' contrast, but still not good enough. v3 uses stronger bg color, but I think I'll choose v1.

**Comment by alecpl** [comment]
Fixed.
