### ISSUE TITLE
Layout "List" in new elastic skin

### ISSUE THREAD

**Issue by hoellen** [roundcube/roundcubemail#7059]
Quick question: Is it possible that the list layout is no longer available in the new elastic skin (version 1.4.0)? 
If yes: Are there any plans to re-implement it?

![grafik](https://user-images.githubusercontent.com/11299996/69337558-74d99900-0c61-11ea-9615-3b9fcac55639.png)

**Comment by alecpl** [comment]
Yes, it is no longer available and there are no plans to implement it.
