### ISSUE TITLE
Service currently not availabe when trying to edit/create identities with Roundcube 1.4.0

### ISSUE THREAD

**Issue by jowi24** [roundcube/roundcubemail#7060]
![image](https://user-images.githubusercontent.com/962952/69347356-97c17880-0c74-11ea-8cb8-df8dc161e208.png)

Problem appeared after Upgrading to 1.4.0 from 1.3.x. Deleting the database did not help.

**Comment by jowi24** [comment]
Error in Log: 
`
errors: <5e97c785> PHP Error: Enigma plugin: Option 'enigma_pgp_homedir' not specified in /var/www/html/plugins/enigma/lib/enigma_engine.php on line 91 (GET /?_task=settings&_action=edit-identity&_iid=2&_framed=1)`

**Comment by alecpl** [comment]
You have to set that option in enigma plugin config.

**Comment by jowi24** [comment]
To what content? I'm using the roundcube docker image and have - to my knowledge - never configured something before.

**Comment by jowi24** [comment]
Seems to be related to https://github.com/roundcube/roundcubemail/issues/6173
