### ISSUE TITLE
Deleting saved search in addressbook list causes display issue

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7061]
tested in git-master, elastic skin, all plugins disabled. browser ff 70.

on the contacts screen, in the left had col that lists address books, groups and saved searches, when you have one or more address books with groups and 1 saved search and you delete that saved search then that layout of the address book and groups list goes wrong and looses its indenting.

this only happens when you have a single saved search and you delete it. when there are multiple saved searches deleting one of them does not affect the layout.

**Comment by alecpl** [comment]
Confirmed. This is not Elastic-specific, there's also issue in other skins.

**Comment by alecpl** [comment]
Fixed.

**Comment by johndoh** [comment]
Sorry @alecpl there still seems to be something up. checked in both Elastic and Larry skins. If you only have 1 saved search in your list and you delete it then immediately create a new search and save it the search is saved but the list is not updated. Refresh the page and the search is listed as normal. Only seems to happen in the specific case when you delete the last saved search and create a new one without reloading the page first. It looks like deleting the only saved search is removing the <ul> element from the DOM not just the <li>.

**Comment by alecpl** [comment]
You didn't say anything about creating search items in your initial bug report. I'll investigate this case. I fixed similar issue for groups in a separate commit, so maybe it's fixed?

**Comment by johndoh** [comment]
I noticed the thing about adding a new search while trying out dbc2b5e. Perhaps I should have opened a fresh ticket, you are correct,I don't know if this is actually related to that commit or not. I just checked the groups and the behavior is not quite the same when you delete the last group the `<ul>` is removed but then when you add a new group the `<ul>` is added too.

**Comment by alecpl** [comment]
Fixed.
