### ISSUE TITLE
Support gender-neutral locales

### ISSUE THREAD

**Issue by baldurmen** [roundcube/roundcubemail#7065]
Hi!

Since 1.3.5  I've been maintaining a [French gender neutral locale for Roundcube ](https://github.com/baldurmen/roundcube_fr_FEM).

I have had a lot of positive feedback from people using and maintaining instances of Roundcube and I would like it to be included in Debian. It seems the easiest way would be to upstream it.

Would it be possible to add a new locale (`fr_GN`) on Transifex? I'm not sure this is the right place to ask, but I'm don't know where else to :)

I'm [already part of the French team](https://www.transifex.com/user/profile/baldurmen/).

**Comment by alecpl** [comment]
I don't see a possibility to add `fr_GN` on Transifex and we support only localizations from there.

I'm curious, is it a French-specific thing? Couldn't it be fixed in `fr_FR` or maybe with some `en_US` changes in core? How much (in percent) of the original localization have you have to modify?

**Comment by baldurmen** [comment]
I would be really happy if we could make the `fr_FR` translation gender neutral. If that's what Roundcube as a project decides to do, it would be amazing. Sadly, I'm afraid there would be some pushback since it's a ... contentious ... issue in French.

For example, the translation for `username` in French, currently `nom d'utilisateur` (masculine only) would become `nom d’utilisatrice ou d’utilisateur` (gender neutral). It's significantly longer and some people feel it's not aesthetic.

[Folks in the Debian Roundcube team think](https://alioth-lists.debian.net/pipermail/pkg-roundcube-maintainers/2019-November/002236.html) it would be better to use something like `fr_FR@FEM` (for `féminisée`, the French word for Gender Neutral) or `fr_FR@GN`, a scheme[ that is supported by GNU gettext](https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html). I don't really mind either, nor `fr_GN` (although it seems that wouldn't be correct).

As for Transifex, [their FAQ says](https://docs.transifex.com/faq/all#how-do-i-add-a-new-language), it seems one can ask them to add a new non-standard locale:

> If your language isn't in the Languages page and your files appear in a shortened version like ‘xx_YY', then you can help us providing the necessary information in order to add your language into Transifex.

Would it be possible to ask them to see what's their preferred solution for this?

Thanks a lot,

**Comment by gagzzz** [comment]
Hello,

I also think it would be great to have a gender neutral french translation. My preferred option is to have it in place of the current male-gendered version.
But having it as another translation would be a start.

@baldurmen, "Nom d'utilisateur" can also be "Nom d'utilisateur·ice", which is much shorter and is [considered valid in french-speaking Switzerland](https://www.vd.ch/guide-typo3/les-principes-de-redaction/redaction-egalitaire/exemples-et-conseils-pour-la-redaction-epicene/#c2023541), with the use of either the dash symbol (-) or the interpunct (·).

If it goes for a new translation branch like fr_FR@<something>, I think <something> should not be FEM for "féminisé", but a reference to "épicène", which means gender neutral language.

Thank you for taking steps on this!

**Comment by rlaager** [comment]
@baldurmen I used https://www.transifex.com/contact/ to send them the following message. I have an account there to manage translations for Pidgin.

> Are you willing to add a language code for French (Gender Neutral), or probably better French (France, Gender Neutral) and French (Canada, Gender Neutral)? I am not a French speaker, but I was advocating for using the @variant syntax for this, with "GN" as the tag ("gender neutral"), which could be used across various languages. So that would be, for example, fr_FR@GN and fr_CA@GN.
>
> Here is some additional discussion:
> https://github.com/roundcube/roundcubemail/issues/7065#issuecomment-558360694
>
> which links to my post here:
> https://alioth-lists.debian.net/pipermail/pkg-roundcube-maintainers/2019-November/002236.html

**Comment by baldurmen** [comment]
> @baldurmen, "Nom d'utilisateur" can also be "Nom d'utilisateur·ice", which is much shorter and is considered valid in french-speaking Switzerland, with the use of either the dash symbol (-) or the interpunct (·).

It's true for that particular example, but I was more trying to make a point than anything else :) Gender neutral French is also considered "valid French" (whatever that means) by Quebec's [Office de la langue française](http://bdl.oqlf.gouv.qc.ca/BDL/gabarit_bdl.asp?id=4015) btw :p

I do agree though something more generic like `xx_YY@GN` like @rlaager proposes would be better than something with "FEM".

**Comment by disturbio** [comment]
Riseup currently use the French "gender neutral" version as a default for fr_FR (and spanish), no complains about it, but Riseup users wouldn't have problems with it. 

The GN version as a default sounds better than an alternative one, but it might be tricky to implement. If it's not possible then the regular fr_FR still should try to use the most GN translated strings as possible so both translations don't divert much.

**Comment by micah** [comment]
I'd love to see this integrated as well, I think the reasoning above has been already well said, so I wont say more except oui, s'il vous plaît

**Comment by alecpl** [comment]
I see some technical difficulties:
1. First Transifex needs to support that
2. How web browsers handle that, i.e. do they support such locales?
3. We use the language code with `setlocale()`, it's not gonna work if the locale does not exist in the system.
4. Too long labels might be a problem.

First is critical, the rest will probably be just a limitation/inconvenience. That being said, I'm not giving this a high prio.

**Comment by rlaager** [comment]
Transifex replied, and unfortunately, it's not the desired answer:
> Regarding your case, I would like to mention that at least for the time being, custom language codes cannot be supported due to technical limitations. We can support only those languages that have officially been recognized by ISO standards.
>
> Please note that Transifex can support languages that adhere to the ISO 639-1 standard of language names and locales. If the language is not covered in 639-1, we might fallback to 639-2 or 639-3. But for this language, no ISO code is available, so I am afraid that we cannot process your request at this point of time. We hope for your understanding.

**Comment by baldurmen** [comment]
Thanks @rlaager for your efforts :)

@alecpl The only way forward then seems to be to make the default `fr_FR` locale gender-neutral. I'm happy to work on this if you decide you want to go that way.

If not, I guess this issue can be closed and I'll try to work with the Debian Roundcube Team to add the locale there instead of having it upstreamed.

Cheers!

**Comment by gagzzz** [comment]
Argl.
Then maybe the official french translation should be gender neutral. But that might need you (roundcube devs) take position on that.
I'd love if it would go this way!

thank you for all the hard work!

**Comment by alecpl** [comment]
We have much more interesting tickets to work on. This is not gonna happen until we see some code to review.
