### ISSUE TITLE
Wrong pcre-metachar in rcube_vcard.php ? 

### ISSUE THREAD

**Issue by sandyWolf** [roundcube/roundcubemail#7068]
Hi!

After php update (a new version is 7.3.11) I've got a lot of messages in errors log like this:
PHP Warning:  preg_replace(): Compilation failed: escape sequence is invalid in character class at offset 8 in /var/www/..../htdocs/program/lib/Roundcube/rcube_vcard.php on line 547

And roundcube doesn't show any info about contact in personal addr book.

The problem is a result of \R meta-char at line 539. Original regex is: '/^(N:[^;\R]*)$/m'. If I change \R to something else (\r\n, i.e.) it works well.

**Comment by alecpl** [comment]
This is fixed in 1.4. Duplicate of #6744.

**Comment by alecpl** [comment]
Also fixed in 1.3.10.
