### ISSUE TITLE
Managesieve filter edit causes RoundCube interface stop working

### ISSUE THREAD

**Issue by marekce** [roundcube/roundcubemail#7069]
After upgrading to RC 1.4.0, when I try to edit or create new filter in managesieve, I'm not able to change to another settings tab, mail view, or even logout from RoundCube. The only action I'm able to do is to save the filter. After that, everything is working again. Also reloading a page (F5) helps.

**Comment by alecpl** [comment]
This is fixed in 1.4.1.
