### ISSUE TITLE
Can I disable usage of plaintext signatures?

### ISSUE THREAD

**Issue by Rasmusbdk** [roundcube/roundcubemail#7071]
I have disabled plaintext editor when composing mails by setting the following variable in config.inc. Can I do similar for the signatures in Identities > Signature?

`$config['htmleditor'] = 1;`

**Comment by alecpl** [comment]
You didn't really disable the plain text mode, but you switch the default to HTML. Maybe we could change the default also for signatures, but I guess only for newly created ones, because existing ones already have the mode stored with the signature.

**Comment by Rasmusbdk** [comment]
Thanks. Thinking about it, what I really did was probably setting the default to html and removing plaintext field from my template, thereby effectively removing it :-)

**Comment by alecpl** [comment]
Wontfix. Write a plugin.
