### ISSUE TITLE
Elastic: Simple search in pretty select

### ISSUE THREAD

**Issue by Dave-09** [roundcube/roundcubemail#7072]
First of all my compliments for the brand new skin! Finally a suitable skin for mobile and ipad.

A feature request. We have a lot of signatures in Roundcube. With the old skin you could simply type in an initial letter and then he jumped directly to this initial letter. This no longer works in the new skin. Is it possible to reduce that? this seems useful to me and I think other people too.

Thank you!

**Comment by alecpl** [comment]
Done.
