### ISSUE TITLE
Elastic: Incorrect icon for text mode editor type switch button

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7074]
The icon `"\f410"` used in Roundcube 1.4.1 for text mode editor type switch button is for close/delete/cancel button.
![image](https://user-images.githubusercontent.com/44122211/69581424-27ea1f80-0fdf-11ea-9434-ee4542c4d02d.png)
More appropriate icons are:
`"\f039"` icon, as in the message preview window.
![image](https://user-images.githubusercontent.com/44122211/69581459-35070e80-0fdf-11ea-857c-3f7afce7473e.png)
or `"f87d"` icon 
![image](https://user-images.githubusercontent.com/44122211/69581484-3fc1a380-0fdf-11ea-966d-2afa2dfe7e86.png)

**Comment by alecpl** [comment]
For me it makes sense. The button closes html editor.

Your first suggestion is almost identical to "Justify" icon in the editor. The second is not that clear to me. I'll ask a designer for an opinion.

**Comment by alecpl** [comment]
Wontfix.
