### ISSUE TITLE
Cancelling switching from HTML to plain text results in plain text message containing HTML

### ISSUE THREAD

**Issue by beakbeak** [roundcube/roundcubemail#7077]
I'm using Roundcube 1.4.1 with Firefox.

Reproduction steps:
1. Reply to/forward a HTML message.
2. Click "Plain text" button. When "Switching editor type may cause text formatting to be lost. Do you wish to continue?" message pops up, click "Cancel."
3. Send the message.

The message is sent as an (unreadable) plain text message containing the original HTML code.

Also, after clicking "Cancel" the first time and clicking the "Plain text" button again, the message switches to plain text without asking for confirmation.

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
