### ISSUE TITLE
Elastic Footer In Various Sections

### ISSUE THREAD

**Issue by HighlyFavoredBA** [roundcube/roundcubemail#7078]
The create button for Responses on mobile is too low.  It should be like Mail, and Contacts on mobile.  Thanks!  :--)

Also, Save & Cancel / Import & Cancel are often hidden at the bottom of List Options,  Import Messages, and Elsewhere.  Thanks!  :--)

![Responses-Bottom](https://user-images.githubusercontent.com/31964993/69700402-fd1bcc00-10af-11ea-9ec1-bd6e90885fe2.jpg)
![List-Options-And-Import-Messages-Bottom](https://user-images.githubusercontent.com/31964993/69700410-0442da00-10b0-11ea-9676-e40d2b03dd1a.jpg)

**Comment by alecpl** [comment]
I'm unable to reproduce in firefox mobile mode. What version? What browser and OS version? Does it happen in the vanilla (I see some mods you did) Elastic?

**Comment by HighlyFavoredBA** [comment]
I've been mainly testing on the mobile Dee Browser.  I just tested on the Lightning Browser that is  in the same format, and that has the same results.  I know that various other mobile browsers that I've used in the past have the same format.  I also tested on my mobile Firefox, as well as mobile Brave Privacy (based on Chrome), and those browsers look perfect in those section footers.  :--)

**Comment by alecpl** [comment]
We do not support these browsers.

BTW, DeeBrowser looks like a dead project.

**Comment by HighlyFavoredBA** [comment]
Okay, Thanks! :--)
