### ISSUE TITLE
Localhost no longer allowed 'smtp_server' following update to v1.4.0

### ISSUE THREAD

**Issue by mjulian87** [roundcube/roundcubemail#7081]
After updating to v1.4.0 sending emails would fail with `
SMTP Error (220): Authentication failed.`

This is with the following config (that worked prior to the update) `$config['smtp_server'] = 'tls://localhost';`

Changing the config to the domain of the mail server fixed the issue (`tls://mail.mydomain.com;`).

Is this a bug?

`localhost` still works for the `default_host` config.

**Comment by alecpl** [comment]
I don't see why it would make a difference. It may be related to changed defaults for smtp_user/smtp_pass options. Please read https://github.com/roundcube/roundcubemail/releases/tag/1.4.1

**Comment by mjulian87** [comment]
Thanks, but I have already read that page. 

I mentioned it here #7011, but it appeared to go unnoticed. Someone else (not OP) was having the same issue in that thread.

Can you please confirm that localhost is still working for `smtp_server`?

**Comment by cweiske** [comment]
When using STARTTLS, the SSL certificate is verified. Most SSL certificates do not include "localhost", so this fails.

A workaround is to disable SSL domain name verification as described in https://github.com/roundcube/roundcubemail/issues/8529#issuecomment-1270603035 :
```
$config['smtp_conn_options'] = [
   'ssl' => [
       'verify_peer' => false,
       'verify_peer_name' => false,
   ]
];
```
