### ISSUE TITLE
ldap: how should I configure ldaps://hostname.local?

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7082]
how should I configure ldaps://hostname.local, with the current configuration options? Do you already support this uris? That is the most common to use not?

**Comment by alecpl** [comment]
Did you try `'hosts' => array('ldaps://hostname.local:636')`? Some additional configuration might be needed according to https://www.php.net/manual/en/function.ldap-connect.php

**Comment by f1-outsourcing** [comment]
oh thanks works indeed!!!

**Comment by alecpl** [comment]
I added a note in the default config description.
