### ISSUE TITLE
new_user_identity does not return any when there are multiple search results

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7083]
I am getting my email addresses like this

`$config['new_user_identity_match'] = 'sendmailMTAMapValue'`

The new_user_identity does not display anything if there are multiple results, if there is just one it displays it. Maybe return at least the first one?

ps. tested with the new_user_dialog

**Comment by alecpl** [comment]
You mean the ldap search returns more than one record? Also, `sendmailMTAMapValue` does not sound like a field containing email address.

**Comment by alecpl** [comment]
No feedback. I don't see a bug here.

**Comment by f1-outsourcing** [comment]
> 
> 
> You mean the ldap search returns more than one record? Also, `sendmailMTAMapValue` does not sound like a field containing email address.

Yes that is what I wrote. It does, I would recommend looking at the sendmail schema which is in the rpm. The bug is that it does not return anything in some cases.
