### ISSUE TITLE
new_user_identity identity does not create records at "auto user create"

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7086]
When you delete a user with `delete from users where username='test';`
login -> no identities created
logout
login -> now ldap identities are created.

roundcubemail-1.4.1-complete.tar.gz

**Comment by f1-outsourcing** [comment]
If I comment this line out, it works. 
//$this->add_hook('user_create', array($this, 'lookup_user_name'));

But probably I need to leave this configuration option on to check this every time at login

**Comment by alecpl** [comment]
Could you provide ldap_debug log? This does not make sense to me. Is the delete query required somehow to reproduce the issue? I don't see a relation.

**Comment by alecpl** [comment]
Works for me.
