### ISSUE TITLE
Reply adds empty line with extra indentation bar above original message

### ISSUE THREAD

**Issue by beakbeak** [roundcube/roundcubemail#7088]
I'm using Roundcube 1.4.1 with Firefox.

Reproduction steps:
1. Reply to an HTML message.
2. In the composer, the original message has one level of indentation:
![image](https://user-images.githubusercontent.com/7798945/69768961-a3f77b00-1137-11ea-8cca-1080e60ecf23.png)
3. Send the message.
4. The sent message has an additional empty line above the original message with a second level of indentation:
![image](https://user-images.githubusercontent.com/7798945/69769005-d99c6400-1137-11ea-9445-b8b76edb3cd7.png)

The extra quoting can also be seen by switching the message to plain text before sending:
![image](https://user-images.githubusercontent.com/7798945/69769049-fe90d700-1137-11ea-8468-6d3747a8f7df.png)

**Comment by alecpl** [comment]
I'm unable to reproduce. What PHP version? Could you provide message source for both messages you used above?

**Comment by beakbeak** [comment]
I'm using PHP 5.6.32. I tried with a message from another source and couldn't reproduce the issue, so it seems to be dependent on the message content.

Here is a message that I can reproduce the problem with:
[working from home today.eml.txt](https://github.com/roundcube/roundcubemail/files/3902956/working.from.home.today.eml.txt)

Here is the reply:
[Re working from home today.eml.txt](https://github.com/roundcube/roundcubemail/files/3902958/Re.working.from.home.today.eml.txt)

**Comment by alecpl** [comment]
I think the `<style>` tag makes a difference. TinyMCE breaks the blockquote content in an unexpected way. I'll look for a solution.

**Comment by alecpl** [comment]
Fixed.
