### ISSUE TITLE
UI enhancement: "send" button in the same position as "compose"

### ISSUE THREAD

**Issue by EMarci15** [roundcube/roundcubemail#7090]
On the web interface (chrome, linux) the "compose" button and the "send" button appear in the same position (not at the same time). This is quite an annoying design choice for laptops with touchpads, and could be easily improved.

Here's what happens:
1. User clicks "compose email"
2. They fill in the fields (using "tab" instead of the mouse for moving between fields)
3. While typing, the user's hand accidentally touches the touchpad on the laptop, generating a click.
4. The unfinished email is sent (as the send button was in the same place as the cursor, which is bound to happen with the current layout), and the user has to write a follow-up explaining that they haven't finished writing the email.

I'm not sure if this happens to other people too, or if it's just me, but it is something that happens to me roughly once every month (which is quite frequent for something this awkward).

Thought this would be a nice little improvement with relatively minimal effort (maybe by just switching the order of buttons).

**Comment by alecpl** [comment]
What? Sorry, I don't get it. Compose button is in the menu, Send button is at the bottom. What skin are you talking about? What version? Make a screenshot.

**Comment by alecpl** [comment]
Oh, you might be talking about the old Larry skin. I don't think we'll change that now while we focus on Elastic.
