### ISSUE TITLE
Password: Incorrect escaping of username argument in smb and kpasswd drivers

### ISSUE THREAD

**Issue by barrettkuo** [roundcube/roundcubemail#7092]
It worked well at version 1.3.xx but not working after version 1.4 .
I tested both upgrade from 1.3.xx and totally new installation.
All the result are failed.

error message:
PHP Error: Password plugin: Unable to execute /bin/kpasswd "'wtest'" 2>&1 in /usr/share/roundcubemail/plugins/password/
drivers/kpasswd.php on line 37 (POST /?_task=settings&_action=plugin.password-sa
ve)

If I downgrade to 1.3.xx from V1.4 , it works again.

**Comment by alecpl** [comment]
Confirmed. There's indeed double-quoting caused by https://github.com/roundcube/roundcubemail/commit/60922dc3d557bbd117e0ef23696519d1b03c01cd#diff-ad24d10fbbd896cbb2f02c4d34c7fd1b

**Comment by alecpl** [comment]
Fixed.
