### ISSUE TITLE
Cannot find tables in PostgreSQL database with db_prefix

### ISSUE THREAD

**Issue by Vskilet** [roundcube/roundcubemail#7093]
Hi,
I try to upgrade a roundcube instance from 1.3.10 to 1.4.1. During update, I've this error message :

```
Updating` database schema (2013011000)... [FAILED]
ERROR: Error in DDL upgrade 2013011000: [7] ERROR:  relation "rcsystem" already exists
```
In my config I use the prefix 'rc' and my db_dsnw is correct (I checked all the cases that speak about this problem in this repo)
I use postgreSQL 9.6.15

I found this version strange because : 
```
SELECT value FROM rcsystem WHERE name = 'roundcube-version';
   value    
------------
 2019092900
```

Have you an idea of what I misunderstood ?

**Comment by alecpl** [comment]
Confirmed. It looks that when using postgres database with db_prefix, the prefix is used as a table schema. So, we end up with following query.
```
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'rc' ORDER BY TABLE_NAME;
```
We should treat the prefix as a schema name only if it ends with a dot.

**Comment by alecpl** [comment]
Fixed.
