### ISSUE TITLE
Strange behavior when moving division between collumns

### ISSUE THREAD

**Issue by bugsalotofbugs** [roundcube/roundcubemail#7094]
There are three columns : folders, list of messages and  preview
Dragging border between 2nd and 3rd columns  causes change of size of 1st column, as presented below:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/58336961/69877364-48a5c400-12c2-11ea-8770-a37dde1fd8e7.gif)

**Comment by smares** [comment]
I can confirm this using Firefox and Edge, it works fine in Chrome, though.

**Comment by alecpl** [comment]
This is flexbox layout. Until you set the size of a column it will auto-resize. I don't see it as a bug.
