### ISSUE TITLE
No email address on classic skin near logout button.

### ISSUE THREAD

**Issue by bugsalotofbugs** [roundcube/roundcubemail#7095]
No email address on any of skins near logout button.
It was useful to see what is the current e-mail address (1.3.8) 
of an account you are logged into. Unfortunately it's gone in version 1.4.1.

**Comment by smares** [comment]
Elastic has the mail address in the folders list at the top.

**Comment by alecpl** [comment]
Maybe we should display it in the About dialog.

**Comment by alecpl** [comment]
Wait, what do you mean in any of skins? In Larry skin it is where it was.

**Comment by alecpl** [comment]
The classic skin is in maintenance mode, there was never username near the logout button in Classic.
