### ISSUE TITLE
Can't delete messages with "Display next list entry after delete/move" option ON when Larry skin is set.

### ISSUE THREAD

**Issue by bugsalotofbugs** [roundcube/roundcubemail#7096]
This is related to version 1.4.1 of Roundcube.

**Comment by alecpl** [comment]
Works for me. So, be more precise on steps to reproduce. Any error in browser console? Any error in log? How exactly it looks like? Did you try with disabled all plugins?

**Comment by jacekn2** [comment]
I too has this problem on view only "List". I check one mail and click delete but after this i cant click again and delete next one email i must mark next email. This problem does not occur in other views.
Clear installation roundcube 1.4 in the previous version (1.3.10) this is no problem.

**Comment by alecpl** [comment]
I confirm that the next list entry is not being selected after delete in "List" mode.

**Comment by alecpl** [comment]
This is a regression, but actually according to my commit 22a47cced6cb it is intended behavior. I don't remember correctly, but it has something to do with the checkbox selection added in Elastic or mobile mode. I'll investigate possibility to bring the behavior back.

**Comment by alecpl** [comment]
Fixed.
