### ISSUE TITLE
Multiple profiles for the same user

### ISSUE THREAD

**Issue by zerocarbthirty** [roundcube/roundcubemail#7101]
Hi,
I noticed today that some users have 4 or more profiles in the roundcube.users table.

I.e. dave@domain.net, dave, Dave, DAve

We had a user call us and yell at us because we deleted his contacts, I'm pretty sure he just logged into his 4th profile. Is there some way to merge all of these and for it to know that:
Dave
DAve
dave@domain.net, etc etc etc

are all the same account?

**Comment by Bojo78** [comment]
You can set
`$config['login_lc'] = 2;`
in ...roundcubemail/config/config.inc.php to force conversion of usernames to lower case.
```
// Forces conversion of logins to lower case.
// 0 - disabled, 1 - only domain part, 2 - domain and local part.
// If users authentication is case-insensitive this must be enabled.
// Note: After enabling it all user records need to be updated, e.g. with query:
//       UPDATE users SET username = LOWER(username);
```
