### ISSUE TITLE
Custom Sort Function for emails

### ISSUE THREAD

**Issue by bchhabra2490** [roundcube/roundcubemail#7104]
I want to sort and group emails using my own sorting function. How can I do that?

**Comment by alecpl** [comment]
How exactly would you like to sort them and what with threading?

**Comment by bchhabra2490** [comment]
So, I would like to group the mails according to users. So, it will be like UserA>All Threads>Mail under Thread A. And sorting function uses a rank value I will be giving to each user. The high rank Users will be shown on top and low rank will be shown on bottom.

**Comment by alecpl** [comment]
So, it is grouping too. This is not that simple. That's why we don't have conversations nor Outlook groupping yet.

You will need changes in the imap storage handler as well as in the client side code. It's so big that I can't even really give you any hints.
