### ISSUE TITLE
max_message_size is not honored in message compose dialog

### ISSUE THREAD

**Issue by alienmindbender** [roundcube/roundcubemail#7105]
The maximum attachable filesize shown in the compose dialog (RC 1.4.1) is taken from upload_max_filesize or post_max_size. Roundcubes max_message_size directive is ignored altogether.

### Actual setting
`$config['max_message_size'] = '50M';`

### Compose dialog/Actual output
![grafik](https://user-images.githubusercontent.com/15013291/70320254-85bf0880-1824-11ea-9ca9-28881a0e27e9.png)

### Proposed fix
Compare max_filesize with max_message_size and set the smaller one for max_filesize_txt. Although the result would not be a 100% accurate, it's still better than showing the php limits.
I'm no coder - but I cobbled this together to illustrate what I meant:

```
--- /tmp/rcmail.php	2019-11-19 21:20:37.000000000 +0100
+++ ./program/include/rcmail.php	2019-12-06 14:30:42.227294743 +0100
@@ -2137,6 +2137,10 @@
             $max_filesize = $max_size;
         }

+        if (parse_bytes($this->config->get('max_message_size')) < $max_filesize) {
+            $max_filesize = parse_bytes($this->config->get('max_message_size'));
+        }
+
         $max_filesize_txt = $this->show_bytes($max_filesize);
         $this->output->set_env('max_filesize', $max_filesize);
         $this->output->set_env('filesizeerror', $this->gettext(array(
```

**Comment by alecpl** [comment]
Good point, but the fix will be different. We don't want to change all upload forms with this.

**Comment by alecpl** [comment]
Also, because attachments are base64-encoded we should calculate the value appropriately.

**Comment by alecpl** [comment]
Fixed.

**Comment by alienmindbender** [comment]
Thank you for the quick response :-)
