### ISSUE TITLE
is it possible to addEventListener for a command provided by another plugin?

### ISSUE THREAD

**Issue by photoninger** [roundcube/roundcubemail#7106]
I want to implement a plugin which displays a disclaimer message when a user clicks on the spam button provided by markasjunk. (We manually inspect reported spam mails before we submit them to sa-learn. Therefore our users should be informed that humans will read such mails)

My minimial test code is this:
minitest.php:
```<?php
  
/**
 * minitest 
 *
 *
 * @version 0.1
 * @author author
 */
class minitest extends rcube_plugin
{
  public $task = 'mail';

  function init()
  {
    $this->include_script('nerv.js');
  }
}
```

And nerv.js:
```
rcmail.addEventListener('beforeplugin.markasjunk.junk', function(evt) { window.alert("Admins will read your reported spam mails!"); });
```

But no alert window is shown. 
When I change `beforeplugin.markasjunk.junk` to `beforesend` i get an alert window before an email is sent. So far it works, but not for a plugin command...
I am trying with roundcube-1.4.1.

**Comment by alecpl** [comment]
Indeed, plugin commands are executed before any event handlers. We have to reorder some code in rcmail.command(). We should be able to use `actionbefore`, `before<action>`, `actionafter` and `after<action>`.

I hope there's no code that depends on the current behavior.

@thomascube, any objections to do this in 1.4?

**Comment by thomascube** [comment]
Makes total sense.

**Comment by alecpl** [comment]
Done in master. Please, give it a try before we backport it to 1.4.

**Comment by photoninger** [comment]
Thank you very much for this quick fix!
I tested my minitest-plugin with git-master and it works now as expected.

**Comment by photoninger** [comment]
I did some more coding for my plugin, I have now:
```
<?php

/**
 * markasjunk_disclaimer
 *
 * show a disclaimer before mails are reported as spam
 *
 * @version 0.1
 * @author me
 */
class markasjunk_disclaimer extends rcube_plugin
{
  public $task = 'mail';

  function init()
  {
    $this->include_script('markasjunk_disclaimer.js');
    $this->add_texts('localization/', true);
  }
}
```
And my js:
```
rcmail.addEventListener('beforeplugin.markasjunk.junk', function() { 
    rcmail.confirm_dialog( rcmail.gettext('markasjunk_disclaimer.disclaimer'), rcmail.gettext('markasjunk_disclaimer.ok_button') );
}
);
```
When I click on the spam button the confirmation dialog box comes up, localization works also, but the mail is reported as spam immediately, without waiting for user interaction in the dialog box. 
What am I doing wrong?

**Comment by alecpl** [comment]
You have to return `false` from the event handler.

**Comment by photoninger** [comment]
It works when I use simple js confirm:
```
rcmail.addEventListener('beforeplugin.markasjunk.junk', function(evt) {
    return confirm( rcmail.gettext('markasjunk_disclaimer.disclaimer') );
}
);
```
But I see no way to pevent that `rcmail.confirm_dialog` returns a value before a button is clicked in the confirm_dialog. It returns immediately after displaying the dialog.
Because of `confirm_dialog` -> `simple_dialog` -> `show_popup_dialog` -> `triggerEvent('dialog-open', {obj: popup}); return popup;`

Can you give me a hint, if and how it could be possible to use `rcmail.confirm_dialog` in this use case? 
I would prefer to have a nice dialog box instead of a `confirm()` box.

**Comment by alecpl** [comment]
You have to return `false` when you display the dialog and remember the arguments, then on dialog button click you call the command again. You'll have to keep some state somewhere or in action arguments to distinguish origin of the command call.

**Comment by alecpl** [comment]
Backported.
