### ISSUE TITLE
rcutil::remote_addr broken for more than one ip because of whitespace

### ISSUE THREAD

**Issue by micw** [roundcube/roundcubemail#7107]
In https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_utils.php#L689 the remote ip must be trimmed because the syntaxt of multiple remote ips is

x-forwarded-for: ip1, ip2, ip3

By splitting at ",", all ips except the 1st hast an extra whitespace, causing it not to match against the proxy list, so for >1 proxy, the last proxy is returned instead of the client ip.

**Comment by alecpl** [comment]
Fixed.
