### ISSUE TITLE
HTML message with bgcolor AND text color isn't supported

### ISSUE THREAD

**Issue by tpayen** [roundcube/roundcubemail#7109]
I received an HTML message (generated by thunderbird) starting with
`<body bgcolor="#FFFFFF" text="#000000">` 

But the rcube_washtml class doesn't support the "text" attribute and keeps only
`<body bgcolor="#FFFFFF">` 

So this can be problematic when the roundcube skin colors doesn't fit with the message html colors.
For me keeping bgcolor is a good thing only if the text color is keeped too.

**Comment by alecpl** [comment]
Fixed.
