### ISSUE TITLE
[1.3.10] Cannot expand e-mail answers on chrome 

### ISSUE THREAD

**Issue by Kravcu** [roundcube/roundcubemail#7111]
I cannot expand answers to e-mail on roundcube 1.3.10 when I use chrome, and brave(Version 1.1.20 Chromium: 79.0.3945.74 64bit) browser, yet it works fine of firefox. I wonder if you know how to solve this.
![Bez tytułu](https://user-images.githubusercontent.com/17221071/70740813-4a3ba700-1d1a-11ea-8083-47b7ba83fc81.png)

Does anybody have the same problem?

**Comment by alecpl** [comment]
Works for me in Chromium 78.0.3904.108. Any errors in browser console? Try with disabled all plugins. Does it work in Desktop/List mode?

**Comment by alecpl** [comment]
No feedback.
