### ISSUE TITLE
cannot increate attachment size limit even when PHP vars are set right

### ISSUE THREAD

**Issue by FlorinAndrei** [roundcube/roundcubemail#7114]
RC-1.4.1, Apache-2.4.18, PHP-7.0.33, Ubuntu 16.04

`.htaccess` at the top RC folder has this:

```
php_value   upload_max_filesize   100M
php_value   post_max_size         200M
php_value   memory_limit          1000M
php_flag    log_errors      On
php_value    error_log    /var/www/html/mail/logs/php-error
php_flag        display_errors  On
php_value       error_reporting 32767
```

`config.inc.php` has this:

```
$config['max_message_size'] = '200M';
```

`phpinfo()` in the top RC folder reports the correct local values for `upload_max_filesize` and `post_max_size`.

But, I made a test file, 95 MB in size, and I cannot attach it to a new message. I keep getting "server error" when I upload the file into the Compose window. But nothing is reported in `error_log`.

**In fact, I can only attach files smaller than 1 MB.** Forget 100 MB attachments - I'd like to attach at least 5 MB or so, but that doesn't work either.

I've enabled various debug options in `config.inc.php` but no clue there.

I used to run version 1.2.4 with 5 MB upload size limit, and it was fine.

I'm out of ideas. This error happens and there's literally no clue anywhere.

**Comment by alecpl** [comment]
Maybe you have some limits in http server config? What plugins are you using?

**Comment by FlorinAndrei** [comment]
> Maybe you have some limits in http server config?

Well, it's the standard Ubuntu configuration, plus some thinly-defined vhosts. I think there's nothing there to set hard limits.

> What plugins are you using?

Um... Is this it? (from config.inc..php)

```
$config['plugins'] = array('show_additional_headers', 'markasjunk', 'filesystem_attachments', 'jqueryui', 'managesieve', 'zipdownload');
```

I'm pretty sure I could figure it out - if only I knew where to turn up the logging.

I feel something's missing from the RC logs.

**Comment by FlorinAndrei** [comment]
And yeah, the limit is 1 MB no matter what I do.

**Comment by alecpl** [comment]
Definitely on "server error" I'd expect some error message in some log. Look into Roundcube's log directory, not the one specified in .htaccess. What about browser console? What status the request responds with?

**Comment by alecpl** [comment]
No feedback.

**Comment by elvisef** [comment]
As far as I remember 1MB is the default size for "upload_max_size" and/or "post_max_size" in PHP config file.

If You're using htaccess file for Roundcube, check if the "ifModule" parameter is for the PHP version You're currently using, because as I see, these values and flags shown in Your first post are for "ifModule mod_php5.c" directive in my Roundcube 1.5-git version.

So please double check the settings.

And if this is not the case, please check `php --ini | grep "Loaded"` if You are editing proper files. Just in case : )
