### ISSUE TITLE
Refresh intervals lower than 60 seconds

### ISSUE THREAD

**Issue by ScottPeterJohnson** [roundcube/roundcubemail#7115]
Hello! Before upgrading to 1.4.0, I had a default and minimum refresh interval of 20 seconds configured for users. After upgrading, however, it seems like lower than 60s is no longer an option and the old refresh config falls back to "never". Is there any way to get a lower interval back, or failing that either default to one minute or throw errors for configurations that won't work?

**Comment by alecpl** [comment]
What version did you have before? I think it is this way since at least 1.0. I mean, the Preferences section always displayed the selector in minutes.

**Comment by ScottPeterJohnson** [comment]
Hm, I was using 1.3.9. I tested against the older version and while the 20s refresh time worked there (and doesn't work in 1.4.0), it _did_ display as Never in both. I could've sworn it originally did display the 20s when I decided on the setting a year ago, but I'm probably just misremembering. 

Up to you whether there's anything to fix here.

**Comment by alecpl** [comment]
As I don't like the idea and it looks like a rare request, wontfix.
