### ISSUE TITLE
Attachments without optional Content-Disposition headers are not visible in message view

### ISSUE THREAD

**Issue by drboone** [roundcube/roundcubemail#7117]
A MIME attachment part in a multipart/mixed message that does not include the Content-Disposition header (OPTIONAL per RFC2183) will have a paper clip in inbox list view, but no link appears in full message view.  Other MUAs, e.g. Thunderbird, Apple Mail, display the attachments properly through the same IMAP server.

E.g. the msword attachment here won't be listed:

```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="000000000000ed63c40599d145b9"
<assorted other headers>

--000000000000ed63c40599d145b9
Content-Type: text/plain; charset="UTF-8"

Hope to see you there.

--000000000000ed63c40599d145b9
Content-Type: application/msword
Content-Transfer-Encoding: base64

0M8R4KGxGuEAAAAAAAAAAAAAAAAAAAAAPgADAP7/CQAGAAAAA.......
```

But if the attachment's headers are like this it will:

```
--000000000000ed63c40599d145b9
Content-Type: application/msword
Content-Disposition: attachment; filename="Agenda December 16, 2019.doc"
Content-Transfer-Encoding: base64
```

**Comment by alecpl** [comment]
So, it has no Content-Disposition header, but also no name argument in Content-Type header. I can confirm that. Indeed, Thunderbird displays it with "Part X.Y" name.

**Comment by alecpl** [comment]
Fixed.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9150
- https://github.com/roundcube/roundcubemail/issues/5051
- https://github.com/roundcube/roundcubemail/issues/6279
- https://github.com/roundcube/roundcubemail/issues/7117
- https://github.com/roundcube/roundcubemail/issues/7122
- https://github.com/roundcube/roundcubemail/issues/7214
- https://github.com/roundcube/roundcubemail/issues/7293
- https://github.com/roundcube/roundcubemail/issues/7414
- https://github.com/roundcube/roundcubemail/issues/7440
- https://github.com/roundcube/roundcubemail/pull/7441
