### ISSUE TITLE
Elastic: Search options hides mail list when folder list is collapsed

### ISSUE THREAD

**Issue by ud-klee** [roundcube/roundcubemail#7120]
Tested with 1.4.1. Steps to reproduce:
1. Reduce viewport width until folder list is collapsed
2. Click on search options button
3. Click on the folder icon, change to a different folder
4. The mail list appears empty even if it isn't
5. Contents reappear after clicking the search options button twice.

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
