### ISSUE TITLE
Markasjunk: Unable to mark more than one message as spam/ham with email_learn driver

### ISSUE THREAD

**Issue by ud-klee** [roundcube/roundcubemail#7121]
The driver uses `rcmail_sendmail::deliver_message()` to send spams/hams in a for loop. The problem is this method always close the underlying SMTP socket after successful delivery (as it passes `true` for `$disconnect` when invoking `rcube::deliver_message()`). When it tries to send the second e-mail it fails because `rcube_smtp::$conn` is set to `null` in `rcube_smtp::disconnect()`.

Calling `rcube::smtp_init()` in the for loop seems to get it working, but it doesn't look like a good fix to me. Any idea?

**Comment by alecpl** [comment]
Fixed.
