### ISSUE TITLE
Problem with replies to messages with attachments from Gmail

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7122]
When replying to a message with attachments send from Gmail, the attached files are added to the message reply (like forwarding the message). 

Seems Gmail has changed the way files are attached by adding an additional Content-ID header.

Here is a part of the message source: 
```
Content-Type: image/jpeg; name="file.jpg"
Content-Disposition: attachment; filename="file.jpg"
Content-Transfer-Encoding: base64
Content-ID: <f_k49m0kue0>
X-Attachment-Id: f_k49m0kue0
```

Part of the source of an old Gmail message that has no such problems: 
```
Content-Type: application/pdf; name="file.pdf"
Content-Disposition: attachment; filename="file.pdf"
Content-Transfer-Encoding: base64
X-Attachment-Id: f_hxbncnhj0
```

Tested with Roundcube 1.3 & 1.4. 
I haven't noticed such problems with other email providers.

**Comment by alecpl** [comment]
I see a few ways to fix this:
1. Simple fix: Consider an attachment to be inline only if `Content-ID`/`Content-Location` AND `Content-Disposition: inline` is specified. Will work with Gmail, but potentially can break with messages from various other clients.
2. Always check if attachment is referred from the message body before attaching it. That will be more work, but I guess will be a better option.
3. Do not attach such attachments beforehand, and never list inline parts on attachments list. Attach them to the message on save/send. That would be an even bigger refactoring.

**Comment by alecpl** [comment]
Fixed in master with combination of 1 and 2. As the fix need to be tested some more, I'm postponing it to be backported in 1.4.4.

**Comment by alecpl** [comment]
Backported.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9150
- https://github.com/roundcube/roundcubemail/issues/5051
- https://github.com/roundcube/roundcubemail/issues/6279
- https://github.com/roundcube/roundcubemail/issues/7117
- https://github.com/roundcube/roundcubemail/issues/7122
- https://github.com/roundcube/roundcubemail/issues/7214
- https://github.com/roundcube/roundcubemail/issues/7293
- https://github.com/roundcube/roundcubemail/issues/7414
- https://github.com/roundcube/roundcubemail/issues/7440
- https://github.com/roundcube/roundcubemail/pull/7441
