### ISSUE TITLE
Password Change Issue

### ISSUE THREAD

**Issue by jethitech** [roundcube/roundcubemail#7124]
Hello There
I'm facing an issue in changing the password as it shows the error **COULD NOT SAVE PASSWORD**

![2019-12-20-10-54-mailbox jethitech com](https://user-images.githubusercontent.com/59077743/71232269-4bbb2f80-2317-11ea-9bd7-488e6d347df0.png)

Even can't see the current password field also.

**Comment by alecpl** [comment]
Check the error log. Not enough info.

**Comment by jethitech** [comment]
[21-Dec-2019 08:44:41 +0000]: <965h8g2s> DB Error: [1305] FUNCTION u123456789_mail.update_passwd does not exist (SQL Query: SELECT update_passwd('$1$DJsOLJGw$fNPl4PfQML.TamoDRtLCJ0', 'mail@domain.com')) in /home/u123456789/public_html/mailbox/program/lib/Roundcube/rcube_db.php on line 543 (POST /?_task=settings&_action=plugin.password-save)

**Comment by plutocrat** [comment]
More information. In my case I was running vesta on a non-standard port. 8888. 
I changed the value in /etc/roundcube/plugins/password/config.inc.php to match this
(file is symlinked from /usr/share/roundcube/plugins/password/config.inc.php)
That didn't work, but I got a different message in /var/log/vesta/nginx-access.log which is now
127.0.0.1 - - [14/Feb/2020:15:35:09 +0800] POST /reset/mail/ HTTP/1.1 "401" 188 "-" "PHP Script" "-"
And running curl on that URL i.e. curl curl https://localhost:8888/reset/mail/ gives.
curl: (51) SSL: no alternative certificate subject name matches target host name 'localhost'

So next I tried curl https://actual.domain.name:9000/reset/mail/ and got
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>

So entering actual.domain.name into config.inc.php as well didn't work either. Stuck for the moment.

**Comment by plutocrat** [comment]
Additionally tried setting hostname and port in plugins/password/drivers/vesta.php to no avail.
