### ISSUE TITLE
Cannot connect to Dovecot Manage Sieve when SSL/TLS is enabled

### ISSUE THREAD

**Issue by Frederick888** [roundcube/roundcubemail#7127]
I'm using Roundcube with Dovecot. I just enabled Manage Sieve in Roundcube and Dovecot and it worked flawlessly without SSL/TLS. However, Roundcube can no longer connect to Manage Sieve service after SSL/TLS was turned on.

#### Software Versions
Ubuntu: 18.04.3
PHP: 7.3.13-1+ubuntu18.04.1+deb.sury.org+1
dovecot / dovecot-sieve / dovecot-managesieved: 2.2.33.2-1ubuntu4.5
Roundcube: 1.4.1

#### Roundcube logs
```
==> logs/errors.log <==
[22-Dec-2019 08:50:33 +0000]: <la88taa7> PHP Error: Failed to read from socket (GET /?_task=settings&_action=plugin.managesieve)
[22-Dec-2019 08:50:33 +0000]: <la88taa7> PHP Error: Unable to connect to managesieve on imap.mydomain.com:4190 in /var/www/mail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 223 (GET /?_task=settings&_action=plugin.managesieve)
[22-Dec-2019 08:50:33 +0000]: <la88taa7> PHP Error: Not currently in AUTHORISATION state (GET /?_task=settings&_action=plugin.managesieve)
[22-Dec-2019 08:50:33 +0000]: <la88taa7> PHP Error: Failed to read from socket (GET /?_task=settings&_action=plugin.managesieve)
```

#### Dovecot Manage Sieve Configuration
```
# /etc/dovecot/conf.d/20-managesieve.conf
service managesieve-login {
  inet_listener sieve {
    port = 4190
    ssl = yes
  }
  inet_listener sieve_deprecated {
    port = 2000
    ssl = yes
  }
  service_count = 1
  process_min_avail = 0
  vsz_limit = 64M
}
service managesieve {
  process_limit = 1024
}
protocol sieve {
}
```

#### Roundcube managesieve configuration
```php
// /var/www/mail/config/config.inc.php
$config['managesieve_host'] = 'tls://imap.%d';
$config['managesieve_usetls'] = true;
$config['managesieve_debug'] = true;
```

#### OpenSSL Test Results
First I tested with `openssl s_client -connect imap.mydomain.com:4190 </dev/null` in the same machine and then I also tested my PHP OpenSSL configuration with the following script:
```php
<?php
$context = stream_context_create();
$socket = stream_socket_client('tls://imap.mydomain.com:4190', $errno, $errstr, 30, STREAM_CLIENT_CONNECT, $context);
echo fread($socket, 16384) . "\n";
```
Output:
```
"IMPLEMENTATION" "Dovecot (Ubuntu) Pigeonhole"
"SIEVE" "fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext"
"NOTIFY" "mailto"
"SASL" "PLAIN LOGIN"
"VERSION" "1.0"
OK "Dovecot (Ubuntu) ready."
```
So both `openssl` and PHP seemed to be able to connect to Dovecot Manage Sieve server.

I feel really clueless now. Please help, thanks!

**Comment by alecpl** [comment]
There's a difference between implicit SSL and STARTTLS methods. You configured the plugin to use the later method, but it looks that dovecot is configured for the former.

**Comment by Frederick888** [comment]
@alecpl Thanks for the hint! I removed `ssl = yes` from Dovecot configuration and Roundcube now can correctly connect to Manage Sieve service via TLS:
```
Dec 22 09:43:57 MyDomain dovecot: managesieve-login: Login: user=<frederick888@mydomain.com>, method=PLAIN, rip=xxx, lip=xxx, mpid=26024, TLS, session=<xxx>
Dec 22 09:43:57 MyDomain dovecot: managesieve(frederick888@mydomain.com): Disconnected: Logged out bytes=54/517
```
Out of curiosity, may I know whether Roundcube can be configured to use implicit SSL as well?

**Comment by alecpl** [comment]
Yes, you use ssl:// prefix and disable managesieve_usetls.
