### ISSUE TITLE
Elastic: cannot copy recipient addresses from to/cc/bcc fields when composing

### ISSUE THREAD

**Issue by bluikko** [roundcube/roundcubemail#7129]
It seems that since Elastic "renders" the recipient addresses prettily inside a graphical box vs. displaying them as text in to/cc/bcc fields (when composing a reply for example), it is now impossible to copy via Windows clipboard recipients from field to another.

The users are revolting... And I can see how this is an unnecessary inconvenience. Example:
- Reply All to a mail
- The "to" field now contains a@example.com
- The "cc" field now contains b@example.com, c@example.com
- User wants to move c@example.com to "bcc" or "to", and would usually have just selected/painted the recipient, hit cut, move focus to desired field and hit paste

Could it be made possible to copy the recipients again when composing messages, or a knob to enable displaying recipients as plain text?

Edit: or alternatively allow drag and drop the recipient to another field, but I'd assume this to be more difficult.

**Comment by alecpl** [comment]
Copying recipient by selecting the text in recipient input was possible in earlier Elastic versions, so this is a regression.

For drag'n'drop we already have #5069.

**Comment by alecpl** [comment]
Fixed.

**Comment by n-goncalves** [comment]
Hi, 

I've tested this on the latest commit, db5ab6d as of writing this, and I have some questions.

* You can't copy recipients using Ctrl-A, Ctrl-C, is this intended ? 
* You are able to select recipients with the mouse to copy them, but formatting is messed up on Chrome 80.0.3987.100. Here's a gif showing what I mean (please ignore the misaligned cursor)
![2020-02-13 16-14-30](https://user-images.githubusercontent.com/35218229/74450977-3417a780-4e7f-11ea-90d7-170ee3d2d1e6.gif)
* It might not be in the scope of this issue and if it's the case just ignore this, but there's no ability no cut recipients in Elastic ?

Thank you for the work you're doing.

**Comment by bluikko** [comment]
I have the same behavior on Roundcube 1.4.4 and latest Chrome 80 - extra text is printed on paste and the recipient name inside the bubble (what's the right name for this?) changes into an address.

For the technically limited users it is also not very obvious how the recipients should be selected - since the "bubble" with the recipient cannot be clicked in order to select it.

If the "bubble" of recipient could be drag and dropped would be the most obvious but probably also the most laborious option to implement.

Cutting recipients would be great but at minimum copying would be important.

**Comment by bluikko** [comment]
Roundcube 1.4.5 has improved this - https://github.com/roundcube/roundcubemail/issues/7129#issuecomment-585831913 is fixed.

It is still possible to select the recipient name for copy in a way that pasting it will result in pasting the same recipient two times.

https://github.com/roundcube/roundcubemail/commit/6f8663f7efdd8a5a8dbb5de5a03de9a1a1c1f33e looks like a very promising feature but the average user may not realize that first need to select the full address and also after dragging need to drop the recipient exactly at the right place (horizontally) of the To/Cc/Bcc field.
