### ISSUE TITLE
Issue with all empty mailboxes

### ISSUE THREAD

**Issue by johncsuti** [roundcube/roundcubemail#7131]
Hello I have used roundcube now for a few days. One day I was no longer able to login, I sorted that out by setting the host to "imaps://localhost" but now every time I login I don't have any mail if I login through my phone or through Thunderbird I have my mail. There are no errors in apache or in postfix logs. Doing a quick google search comes back noting so I thought I would make an issue and see whats wrong with my server. My roundcube version is 1.4.1. I am completely lost as to why it could be. If you need any other info just let me know and I'll get it to you.

**Comment by johncsuti** [comment]
If I try to send a message I get this in my mail.log file
Dec 30 03:51:48 ns1 postfix/smtpd[12005]: connect from localhost[::1]
Dec 30 03:51:48 ns1 postfix/smtpd[12005]: disconnect from localhost[::1] ehlo=1 quit=1 commands=2

**Comment by alecpl** [comment]
Sounds like a problem with your server(s) setup, not Roundcube.
