### ISSUE TITLE
"Recipient edit" form should handle [Enter] and [Escape] keys

### ISSUE THREAD

**Issue by dboehmer** [roundcube/roundcubemail#7133]
The recipient fields like *To* were recently changed to show boxes for each recipient which can be edited by double-clicking on a box. The dialog to edit the recipient title *Recipient edit* should save on [Enter] and abort on [Escape] key press.

I found issue #3843 which claims making forms handle these keys is difficult. Hopyfully it's possible for this form because it's only 1 input element and it's a text input&mdash;so the user has their hand already on the keyboard and pressing [Enter] is a common thing.

I miss this behavior at other places, too. If I can understand how this is resolved I might try to send PRs to fix other locations as well.

**Comment by alecpl** [comment]
I agree. It makes sense for forms with single input in dialogs. Because we have at least three more such dialogs, we should make it a general solution. The place to implement this will be show_popup_dialog() method in app.js.

ps. ESC should already work for most dialogs, it works for me in this one.

**Comment by dboehmer** [comment]
Oh, you're right: Escape already works. I mixed up different forms. Can you link to a commit that adds the Escape function to any form? I could try to add this solution to other forms.

**Comment by alecpl** [comment]
The ESC is handled by jQuery-UI Dialog, there's no custom code for that.

**Comment by alecpl** [comment]
Implemented.
