### ISSUE TITLE
utf-8 encoding in attachments

### ISSUE THREAD

**Issue by LeoBolien** [roundcube/roundcubemail#7139]
Hello,
In Roundcube 1.4.2 i have a problem.
If i open an attachment file (e.g. txt file) which is UTF-8 encoded all
german special charaters (umlaute ä,ü,ö) are displayed incorrect.
If i open the same email in Roundcube 1.3.3 it works correct.
If i have an email with german special charaters in email body it works also.
It looks like the problem is only when open an attachment file.

Any help or missconfiguration by myself ?

Thanks and regards
Leo

**Comment by alecpl** [comment]
Works for me. Provide a sample message. Are both your Roundcube instances using the same config and environment? Did you try with disabled all plugins?

**Comment by alecpl** [comment]
No feedback.
