### ISSUE TITLE
threads: not grouping correctly

### ISSUE THREAD

**Issue by udi111** [roundcube/roundcubemail#7140]
v1.4.1
the older message (which was forwarded) was moved below the new, but the +/- icon is not displayed.
![group](https://user-images.githubusercontent.com/218989/71713373-ba18eb00-2e09-11ea-8e67-81f152963d49.png)

**Comment by alecpl** [comment]
More likely IMAP server issue. What IMAP server? What `References` and `Message-Id` header in both messages? Enable imap_debug and check the server response to THREAD request.

**Comment by udi111** [comment]
new iRedmail install with dovecot 2.3.4.1.

In-Reply-To: <797ccda0e2d3e104fdbecb8b7590b5bd@monyobrewing.com>
References: <797ccda0e2d3e104fdbecb8b7590b5bd@monyobrewing.com>
Message-ID: <fedfb181a092fa8df0724818eb5fdae6@monyobrewing.com>

In-Reply-To: <797ccda0e2d3e104fdbecb8b7590b5bd@monyobrewing.com>
References: <797ccda0e2d3e104fdbecb8b7590b5bd@monyobrewing.com>
Message-ID: <CAMa9WNT1kzv79WCqZ_pAT9MJHwXctzYGoEjf9v7Pe+AZKbGr+g@mail.gmail.com>

other groupings seem to be correct.

**Comment by alecpl** [comment]
So, this is same thread with a missing "parent" message. The same issue described in #4999 and #6384.

Closing as duplicate.
