### ISSUE TITLE
Elastic: logo should be linked to main screen / function

### ISSUE THREAD

**Issue by bes-internal** [roundcube/roundcubemail#7142]
This is the first usability rule of all time.
Link logo to main/mails screen. On mail screen link logo to refresh function.

**Comment by alecpl** [comment]
I do not agree, but we'll keep the ticket open for some time.

**Comment by Tastaturberuf** [comment]
I fully agree with @bes-internal. thats one reason i cant rollout the theme to my clients. On 99% of the web the logo brings you to the startpage. Thats rule No 1. On the migration and reviewing process i click it ages of times.

**Comment by robo2bobo** [comment]
I agree that the logo should link to the start/home page. I don't think its a "standard" per se, but its a universal rule.

**Comment by alecpl** [comment]
I could agree to that rule if the button that moves to Mail was placed in completely different location, but in Elastic Mail button is very close to the logo. Also, in mobile mode it would make even less sense. Also, when adding features with various plugins (e.g. calendar, files, dashboard) mail becomes a less prominent feature, so why would click on logo move to Mail?
