### ISSUE TITLE
Catch http POST requests from third parties 

### ISSUE THREAD

**Issue by alicoder** [roundcube/roundcubemail#7145]
I'm using a SMTP server and they have Inbound emails Parser Webhook.

https://sendgrid.com/docs/for-developers/parsing-email/setting-up-the-inbound-parse-webhook/

Can I use roundcube to catch these POST requests?

**Comment by alecpl** [comment]
It could, but Roundcube as an email client in general works in context of a authenticated user. Such a functionality is not something we would be interested in implementing. You can always write a plugin or create a separate service that uses Roundcube code.
