### ISSUE TITLE
SPAM from roundcube.de imitating roundcube

### ISSUE THREAD

**Issue by LaumiH** [roundcube/roundcubemail#7146]
I do not know if this is the right place to put this, but today I received a SPAM mail imitating roundcube and wanted to let you know about it. Someone might me doing weird stuff out there.

The mail was sent by noreply@roundcube.de and reads:
The access to my mail account has been limited. There has been an unsuccessfull login from IP 168.195.206.93:3389 to my account. If I do not re-validate my account within the next 24 hours, I cannot send or receive messages unless I re-validate (edit: the sentence does not make sense). Click here to re-activate you account (edit: leads to https://525-roundcube-734-232-login.weebly.com/).

I hope this helps somehow.

**Comment by alecpl** [comment]
This is a known scam. We can do nothing about it. https://roundcube.net/news/2019/10/28/phishing-alert
