### ISSUE TITLE
Elastic: Remember checkbox selection state

### ISSUE THREAD

**Issue by clonmac** [roundcube/roundcubemail#7148]
Using Roundcube with the elastic skin requires enabling the selection boxes to be able to select more than one message for bulk actions on messages. These boxes are disabled by default upon each login. It would be nice if there were a toggle option within the settings>Preferences menu to set the 'withselection' class as active for the message list so that the steps of activating the selection boxes does not need to be performed upon each login.

**Comment by alecpl** [comment]
I would rather remember last state.

**Comment by alecpl** [comment]
Done. The state is remembered for each list separately.

**Comment by alecpl** [comment]
Change of mind. The state is remembered globally, not per-list. I think if user wants to use checkboxes he'll want it on all lists.

**Comment by henrythemouse** [comment]
I see this is closed, yet it's an idea I really like, but don't see implemented at this time. Can you tell me if this is going to make it into a release? I'm running 1.4.9.  Maybe it's already in the  current release and I'm just not seeing it.

I use Elastic RC a lot on my phone and having a permanent checkbox for message selection would be helpful feature to have.

**Comment by alecpl** [comment]
As the ticket milestone assignment says it was released with 1.5-beta. We do not plan to backport this into 1.4.

**Comment by henrythemouse** [comment]
That's great news, thanks. 

I see where that information is displayed now. Thanks for pointing that out, next time I want to know that I'll know where to look.
