### ISSUE TITLE
Remove/replace all symbolic links

### ISSUE THREAD

**Issue by mvorisek** [roundcube/roundcubemail#7151]
Symbolic links are not normally supported on Windows, see release extraction log:
```
! Cannot create symbolic link ...\roundcubemail-1.4.2\vendor\bin\crypt-gpg-pinentry
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\vendor\bin\rcubeinitdb.sh
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\plugins
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\skins
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\.htaccess
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\program\js
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\program\resources
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\plugins
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\skins
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\program\js
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
! Cannot create symbolic link ...\roundcubemail-1.4.2\public_html\program\resources
! You may need to run WinRAR as administrator
  A required privilege is not held by the client.
```

Symbolic links are often also disable in Apache config.

Analyse if the symbolic links are used and remove them or replace them with another solution.

**Comment by alecpl** [comment]
I don't give a shit about Windows. We may consider adding a warning in INSTALL file, that's it. I'll not spend time on this issue.

**Comment by alecpl** [comment]
The fact that it is a first complaint about it in 10 years since we use symlinks means something.

**Comment by mvorisek** [comment]
Would it be possible to simply `rm -R vendor/bin/` in the release script?

**Comment by mvorisek** [comment]
Would it be possible to:
- simply `rm -R vendor/bin/` in the release script
- delete & commit all symlinks in `public_html/`

Where are the symlinks from `public_html/` used? In Windows the symlinks are not created and the RC seems to be working fine.



> 
> 
> The fact that it is a first complaint about it in 10 years since we use symlinks means something.

On other platforms the symlinks are often disabled in webserver config and it seems that there are just some leftover from old times and I found it just by coincidence...

**Comment by alecpl** [comment]
> Would it be possible to:
>     * simply `rm -R vendor/bin/` in the release script

No, we're using these scripts

>     * delete & commit all symlinks in `public_html/`

No, what do you mean "delete & commit"?

> On other platforms the symlinks are often disabled in webserver config and it seems that there are just some leftover from old times and I found it just by coincidence...

There are no leftovers in the package

**Comment by smares** [comment]
Windows does support symlinks on NTFS, it's just that you need administrative privileges which is what WinRAR even tells you. Also, enabling symlinks in Apache _is_ possible.

The purpose of the symlinks in public_html is if you make public_html the document root of your VHost in Apache.

**Comment by alecpl** [comment]
I added note to the INSTALL file.

**Comment by ygoe** [comment]
> I don't give a shit about Windows. We may consider adding a warning in INSTALL file, that's it. I'll not spend time on this issue.

This is certainly not the tone with which you can solve problems. More like the opposite. I'll spare you with data on market shares and probabilities of offending or excluding people with that statement.

I also just noticed this problem when unpacking the complete archive of v1.4.9 with 7-Zip. I never noticed this before but older archives I still have here show the same warnings now. Maybe those symlinks were simply ignored or resolved in previous versions of unpackers or I used another unpacker (unlikely).

So now the INSTALL file doesn't explain anything but simply points to this issue. And this issue doesn't explain anything but show disinterest in platform support. I'm left with an open question: Can I ignore these links or are they required for something?

**Comment by smares** [comment]
Again, symbolic links are supported under Windows with NTFS. WinRAR for example tells you exactly what you have to do, that is, launch it as administrator to support creating those symbolic links. People just have to read the messages they are being displayed.

**Comment by ygoe** [comment]
I'm not looking for a solution that involves enhanced privileges that are not found in every environment.

Still, the question remains open: Are the files and directories related to those unknown links relevant or can they safely be ignored?

**Comment by smares** [comment]
It depends what you set as your document root.

**Comment by ygoe** [comment]
Nothing, just leave the defaults.

**Comment by smares** [comment]
Then you can ignore the errors. If you were to set the document root to `public_html`, that wouldn't work without the symlinks.

**Comment by ner00** [comment]
The latest version uses more symlinks to enhance security, needless to say that it doesn't translate as such in Windows. I've resigned myself to just have the symlinks being replaced by duplicate folders and files. At least it works.

You can copy symlinks wit xcopy btw, using `/b` argument, but (at least in my case) Apache wasn't able to handle the symlinks anyway. Roundcube has now grown to 55MB from the previous 35MB, but I understand that Windows isn't a blip on Roundcube's radar.

Just forget the symlinks, have your install or upgrade process recreate the date that the symlinks target. It's only a problem if you're a couple dozen MB short or if you edit some of the files in public_html, other than that you should be good to go.
