### ISSUE TITLE
roundcube-version is system table is not updated in SQL upgrades

### ISSUE THREAD

**Issue by mvorisek** [roundcube/roundcubemail#7153]
**Issue:**
The `roundcube-version` value in the `system` table is set only in initial SQL:
https://github.com/roundcube/roundcubemail/blob/1.4.2/SQL/mysql.initial.sql#L226

and not updated in SQL upgrades:
https://github.com/roundcube/roundcubemail/blob/1.4.2/SQL/mysql/2019092900.sql

**Expected:**
The `roundcube-version` value in the `system` table is set/increased at the end of each SQL upgrade code.

**Comment by alecpl** [comment]
These scripts aren't meant to be executed manually, so the version is updated if you use tools for this, i.e. updatedb.sh or update.sh or installto.sh. What is your real issue?

**Comment by mvorisek** [comment]
We was appliing them manually, thanks and closing...
