### ISSUE TITLE
Cannot leave PGP key creation by clicking on single existing key

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#7154]
Throughout the Roundcube interface, it is possible to leave a Create action by clicking on a list element, for example you can leave the Create folder interface simply by clicking on an existing folder, leave the Create contact interface by clicking on an existing contact, leave the Create identity interface by clicking on an existing identity, etc.
This doesn't seem to be the case with the Create PGP key interface if you have **one** existing key which you previously selected. If you have two keys and click on the one that is not selected/highlighted, it works. To leave the Create PGP key interface if you have one key highlighted, you have to leave the PGP keys section alltogether.

At first I thought this is the case because if you click on an existing key, that key is highlighted in the list. If you click on Create, the previously selected key is still highlighted. In other areas, once you click Create, the highlight is removed - except for the Folders area where clicking Create does not remove the highlight in the list, but you can click the highlighted list item to exit the Create folder action nonetheless.

**Comment by alecpl** [comment]
Confirmed. The issue is skin independent.

**Comment by alecpl** [comment]
Fixed.
