### ISSUE TITLE
'Open in new window' does not work in 1.4.2

### ISSUE THREAD

**Issue by dennisscholing** [roundcube/roundcubemail#7155]
When you select a message and then go to 'More', the 'Open in new window' function does not work.

Works fine in the RC and 1.4.1 version. Seems to be a bug in the rcmail.command.

`return rcmail.command('open','',this,event)`

**Comment by alecpl** [comment]
Confirmed. It is broken in all skins.

**Comment by alecpl** [comment]
Fixed.

**Comment by teoberi** [comment]
I tried the solution proposed by modifying line 814 in the app.js file but it does not work in all skins.
The mail does not open in a new window.

**Comment by alecpl** [comment]
In what skins it does not work? Did you remove app.min.js file?

**Comment by teoberi** [comment]
Skin: elastic
I did not delete any file from js folder but only modified the app.js file.

**Comment by alecpl** [comment]
If you have app.min.js file then you have to remove it otherwise this file is used instead of app.js.

**Comment by teoberi** [comment]
I deleted app.min.js and it works now.
Thanks.
