### ISSUE TITLE
Roundcube website design is unresponsive in Huawei P30 Pro Chrome

### ISSUE THREAD

**Issue by AndrejWebsupport** [roundcube/roundcubemail#7156]
Hello,

when using roundcube via google chrome the web design is unresponsive (when resizing the window). 

The used resolution was 1080 x 2340 pixels, 19.5:9 ratio (~398 ppi density)

https://www.gsmarena.com/huawei_p30_pro-9635.php

Thanks.

**Comment by alecpl** [comment]
What Roundcube version? What Chrome version? What exactly is unresponsive? What exactly did you do? Any screenshots?

**Comment by alecpl** [comment]
No feedback.
