### ISSUE TITLE
Use preferred/main keyring from Mailvelope

### ISSUE THREAD

**Issue by Frederick888** [roundcube/roundcubemail#7157]
Currently Roundcube uses the [unique user id](https://github.com/roundcube/roundcubemail/blob/a9abe62d58df8a321591af30a9e02d1bd6b0f5dc/program/lib/Roundcube/rcube_user.php#L256) as the keyring identifier in [Mailvelope integration](https://github.com/roundcube/roundcubemail/blob/a9abe62d58df8a321591af30a9e02d1bd6b0f5dc/program/js/app.js#L3718). However, as I use GnuPG with YubiKey, it's impossible for me to import my private key into the Roundcube keyring and there doesn't seem to be a way of wiring the GnuPG keys into other keyrings in Mailvelope, either.

Is it possible to allow users to select the main/preferred keyrings from Mailvelope? I think it could also be more convenient for users in some cases if they simply want to share the same keys for different users/websites.

![image](https://user-images.githubusercontent.com/4507647/72030099-24370180-32dc-11ea-8bc1-a8ed7db57fbd.png)

**Comment by thomascube** [comment]
At the time of writing that code, the Mailvelope API didn't allow access to the main keyring. I'll check if that changed in the meantime...

**Comment by Frederick888** [comment]
@thomascube Ah yeah, indeed its client API doesn't allow accessing the main and GnuPG keyrings. The identifiers of these 2 keyrings are `localhost|#|mailvelope` and `localhost|#|gnupg` respectively however in the client content script, it's explicitly [banned](https://github.com/mailvelope/mailvelope/blob/7c9279c/src/content-scripts/clientAPI.js#L58) to provide `host` as part of the identifier.

It's probably a design for better security but I think there should be a setting available to make them, especially the GnuPG one, accessible to client API consumers. I guess I can file an issue there to see how the Mailvelope developers think.

**Comment by alecpl** [comment]
The `mailvelope_main_keyring` option already is implemented. I think this ticket should be now to make it available to the user through Preferences.

**Comment by alecpl** [comment]
Implemented.
