### ISSUE TITLE
Elastic: make favicon ready for HiDPI screens

### ISSUE THREAD

**Issue by mcnesium** [roundcube/roundcubemail#7159]
I recently started using the new Elastic skin. It is really great, thank you very much for all the effort!

One little drawback is the use of a 16x16px ICO-formated favicon, which looks blurry or even pixely on modern HiDPI screens.

There are multiple ways to approach this, and [this post][1] gets rather deep into that topic, with the small addition, that Chromium-based browsers [will support SVG-based favicons soon](https://caniuse.com/#feat=link-icon-svg) (finally!).

Whatever solution will be chosen, it will definitely polish the look of the new Elastic skin. 

[1]: https://www.emergeinteractive.com/insights/detail/The-Essentials-of-FavIcons/

**Comment by alecpl** [comment]
There's already a PR #6672.

**Comment by mcnesium** [comment]
allright :tada:
are you planning to merge it?

**Comment by alecpl** [comment]
Done via 92ae70e
