### ISSUE TITLE
Elastic: Missing 'Layout' feature

### ISSUE THREAD

**Issue by dennisscholing** [roundcube/roundcubemail#7161]
Hi,

Within the Larry skin, the 'Layout' option is present under 'Mailbox view'. This cannot be found within Elastic.

Is it possible to retrieve this? Or is that already planned? The 'List' and 'Desktop' option will be missed within the current new skin!

**Comment by alecpl** [comment]
This feature is not planned for implementation.

**Comment by dennisscholing** [comment]
It was available 1.4.0. Why remove it? :)

**Comment by alecpl** [comment]
No, it was never available in Elastic.
