### ISSUE TITLE
PHP Warning from subscriptions_option plugin

### ISSUE THREAD

**Issue by dpc22** [roundcube/roundcubemail#7165]
We upgraded from an ancient (and now unsupported) version of Roundcube to 1.4.2 earlier this week. A surprisingly painless experience! Thank you.

I have been keeping a close eye on the roundcube logs. One thing which is new is:

```
 Jan 10 01:20:37 webmail-1b roundcube: PHP Warning:  array_filter() expects parameter 1 to be array, null given in /opt/roundcube-1.4.2-0.el7/plugins/subscriptions_option/subscriptions_option.php on line 86
```
Line 86 of subscriptions_option.php is the second clause in the following. 
 
```
  $folders = $storage->list_folders_direct();

  $folders = array_filter($folders, function($folder) use ($storage) {
        $attrs = $storage->folder_attributes($folder);
        return !in_array_nocase('\\Noselect', $attrs);
    });
```

Presumably "$folders" is null

Each of these errors is immediately followed by a separate error which would seem to explain things:

```
Jan 10 01:20:37 webmail-1b roundcube: <56p7742c> IMAP Error: Login failed for XXX against localhost from 10.241.50.212. LOGIN: LOGIN failed in /opt/roundcube-1.4.2-0.el7/program/lib/Roundcube/rcube_imap.php on line 200 (GET /?_task=mail&_mbox=INBOX)
```

(We see quite a lot of these as we use an authentication plugin linked to our local Web single sign on environment. This generates tokens  which are used as temporary IMAP passwords which expire after 10 hours.)

Obviously this is benign and I can just ignore the PHP Warnings. I was just wondering if it made sense to test for ($folders == null) before calling array_filter()?

**Comment by alecpl** [comment]
Fixed.
