### ISSUE TITLE
My roundcube plugins is missing after update cPanel

### ISSUE THREAD

**Issue by testt23** [roundcube/roundcubemail#7167]
Some time ago I installed the roundcube plugins...
Today I noticed that all my settings and registration of the plugin has disappeared. :confused:

Does cPanel delete/reset everything back to standard which is not custombuild? (aftera auto updating or something)
How can I prevent this to happen?

file config.inc.php is "reset" after update cPanel and in my $config['plugins'] = '..here..'; is reset. Wow

I use plugins: mobile, zipdownload  and standards plugins for roundcube

**Comment by alecpl** [comment]
You should ask cPanel support.

**Comment by testt23** [comment]
I had the same problem with directadmin and ispmanagaer, which means it's not just cPanel.
