### ISSUE TITLE
Translation: "import" for language zh_TW

### ISSUE THREAD

**Issue by ud-klee** [roundcube/roundcubemail#7171]
Hi,

I'm not able to do this through Transifex (no response to team join request,) so I'm submitting it here.

The current translation of the "import" key for zh_TW

`$labels['import'] = '匯入通訊錄';`

should be

`$labels['import'] = '匯入';`

without the noun.

For reference, the translation for zh_CN is:

`$labels['import'] = '导入';`

Thanks.
KL

**Comment by alecpl** [comment]
Your join request should be accepted now. Please, update localization there.
