### ISSUE TITLE
1.4.2: HTML message 403 (Sending message.... 'hangs')

### ISSUE THREAD

**Issue by Paulsky** [roundcube/roundcubemail#7172]
Hello,

When I use version 1.4.2, and I turn on the feature 'Compose HTML messages' (so **except** never). The message won't save/reply/send if it includes HTML. I receive a 403 error and the 'saving message...' message hangs. 

If I use the 'never' option, everything (including replying to/saving HTML message) the message will save/send. I downgraded to 1.3.10, and everything, including the 'Compose HTML messages' works.

**Comment by alecpl** [comment]
Did you try with disabled all plugins? Did you try different browser? What browser? Did you try with different skin? What skin? What 403 error exactly? What in error log? What PHP version and OS?

**Comment by Paulsky** [comment]
- No, I did not try to disable all plug-ins, but I don't have any I guess. Installed with CustomBuild, no modifications
- Yes, I tried multiple browsers; Chrome, Brave, FireFox
- I tried all skins, Elastic, Classic, Larry
- 403 HTML document response, can't remember what text
- Couldn't find any errors!!!!!!
- PHP 7, CentOS 7, DirectAdmin 1.5+, default CustomBuild

**Comment by alecpl** [comment]
I don't know CustomBuild so I won't be able to help. It looks like some configuration/environment issue.

**Comment by huangginny** [comment]
I'm seeing exactly the same issue. Installed using CentOS Web Panel. Basically everytime I do something that triggers a request like this "http://[mydomain].com/webmail/?_task=mail&_unlock=loading1605681529217&_framed=1&_lang=en_US" it would return 403 and then timeout after a few minutes. Request body looks like this
`_token=QKXv9KR771ir7KXdVIBnC0iFmn7UrW2b&_task=mail&_action=send&_id=6576848785fb4c16d92579&_attachments=&_from=1&_to=admin%40[my domain].com%2C&_cc=&_bcc=&_replyto=&_followupto=&_subject=[omit]&_draft_saveid=&_draft=&_is_html=0&_framed=1&_message=[omit]&editorSelector=plain&_mdn=&_dsn=&_priority=0&_store_target=Sent`

and a bunch of cookies that look like session authentication is in the request as well. Wondering if it's an issue with authentication? Seems like a lot of ppl are reporting similar issues but they're all closed without a solution...
