### ISSUE TITLE
Elastic: Can't unsubscribe from a folder after creating it

### ISSUE THREAD

**Issue by beakbeak** [roundcube/roundcubemail#7174]
Using Roundcube 1.4.2 on Firefox.
Immediately after creating a folder, the subscription toggle next to it cannot be clicked. Switching to the "Mail" view and back to the "Settings" view allows the toggle to be clicked.

**Comment by alecpl** [comment]
Confirmed, and this happens only in Elastic.

**Comment by alecpl** [comment]
Fixed.
