### ISSUE TITLE
No easily accessible link to main RC site

### ISSUE THREAD

**Issue by FlorinAndrei** [roundcube/roundcubemail#7176]
Hey folks - pretty simple stuff: I'm fishing around the RC UI for a link to the main RC site, and there's none I could discover. Maybe there is one, but then it's well-enough hidden to escape my search.

Could you please add a link to RC.net (or something) to the About pop-up, or some common-sense place like that?

Thanks!

**Comment by alecpl** [comment]
I don't think we will, why?
