### ISSUE TITLE
SMTP error in roundcube 1.4.2

### ISSUE THREAD

**Issue by minimeee** [roundcube/roundcubemail#7182]
Hi!

 I've been using roundcube for years on my server (with postfix and dovecot on Ubuntu 18.04) but after the upgrade to 1.4 it suddenly stopped sending mails via SMTP (receiving still works) and this error occurs each time I try to send a mail (`errors.log`): 

```
PHP Error: Failed to connect socket: Connection refused (POST /?_task=mail&_unlock=loading1579330003893&_framed=1&_lang=de&_action=send)

SMTP Error: Connection failed: Failed to connect socket: Connection refused in /var/www/roundcube/program/lib/Roundcube/rcube.php on line 1689 (POST /?_task=mail&_unlock=loading1579330003893&_framed=1&_lang=de&_action=send)
```
carddav also has problems (`carddav.warn.log`):
```
BACKEND: (refreshdb_from_server) Errors occurred during the refresh of addressbook 3
```
My `config.inc.php` didn't change:
```
$config['smtp_server'] = 'localhost';
```

Postfix and dovecot are working correctly. I can send mails locally (using `mail`) and also from remote clients (e. g. thunderbird and aqua mail). Only roundcube throws an error and I have no clue why... any suggestions?

**Comment by alecpl** [comment]
Default smtp port changed as well as some other smtp defaults in 1.4.

**Comment by minimeee** [comment]
> Default smtp port changed as well as some other smtp defaults in 1.4.

Where are these changes documented? And why isn't this mentioned in `UPGRADING`? That would have saved me a lot of time...

**Comment by minimeee** [comment]
It seems I've found the settings that reproduce the old behaviour (and fix the issue). I leave them here for all those that encounter the same problem:

```
$config['smtp_server'] = 'localhost';
$config['smtp_port'] = 25; 
$config['smtp_auth_type'] = ''; 
$config['smtp_user'] = ''; 
$config['smtp_pass'] = '';
```

**Comment by thomascube** [comment]
FWIW: the changes have been listed in the release notes and in the announcement on our website: https://roundcube.net/news/2019/11/22/update-1.4.1-released

Indeed, a note in the UPGRADING instructions could be helpful, too.

**Comment by minimeee** [comment]
> FWIW: the changes have been listed in the release notes and in the announcement on our website: https://roundcube.net/news/2019/11/22/update-1.4.1-released

Thanks. I must admit that I've never read the news page in all the years I've been using roundcube. Typically I go from the announcement mail directly to the download page and then I check `UPGRADING` before doing the upgrade...

> Indeed, a note in the UPGRADING instructions could be helpful, too.

If the error message contained the port number, that would have helped too. A good error message can avoid a lot of issues ;-)

**Comment by francwalter** [comment]
Thank you minimee, that helped :)

**Comment by kobuki** [comment]
> It seems I've found the settings that reproduce the old behaviour (and fix the issue). I leave them here for all those that encounter the same problem:
> 
> ```
> $config['smtp_server'] = 'localhost';
> $config['smtp_port'] = 25; 
> $config['smtp_auth_type'] = ''; 
> $config['smtp_user'] = ''; 
> $config['smtp_pass'] = '';
> ```

Thank you for this. I was absolutely baffled by this error after the upgrade to 1.4.9. Why aren't the changes in the docs, I wonder?
