### ISSUE TITLE
Fail to use SSL/TLS on CentOS 8.1 with PHP 7.4 (Remi)

### ISSUE THREAD

**Issue by Poltsi** [roundcube/roundcubemail#7183]
Seems like RC (roundcubemail-1.4.2-1.el8.remi) can not establish a SSL/TLS secured connection with neither IMAP (local Cyrus-Imapd) nor SMTP (local Postfix) in a CentOS 8.1 which has PHP 7.4 from Remi repository installed and the certificates are generated by Let's Encrypt.

In case of IMAP RC logs the following error when attempting to log on to RC either from the UI, or the setup step 3:

Could not connect to ssl://localhost:993: Unknown reason in /usr/share/roundcubemail/program/lib/Roundcube/rcube_imap.php  on line 200

In case of SMTP, RC logs the following error when using the 'send an email' in the setup step 3:

SMTP server does not support authentication (Code: ) in /usr/share/roundcubemail/program/lib/Roundcube/rcube.php on line 1689

To pinpoint the problem, I've verified that the IMAP and SMTP does work as expected both by using remotely Thunderbird as well as installing mutt and Rainloop webmail locally on the server.

**Comment by johndoh** [comment]
You are connecting via localhost so the cert is never going to validate. Have a look at this: https://github.com/roundcube/roundcubemail/wiki/FAQ#problems-connecting-imapsmtp-server-via-ssltls

**Comment by Poltsi** [comment]
> You are connecting via localhost so the cert is never going to validate. Have a look at this: https://github.com/roundcube/roundcubemail/wiki/FAQ#problems-connecting-imapsmtp-server-via-ssltls

Hmm... ok.

I should have also included the /etc/ configuration for the relevant parts where I previously already had the imap_conn_options verify_peer set to false.

Now the settings are:

```
$config['default_host'] = 'tls://localhost';
$config['default_port'] = 143;

$config['imap_conn_options'] = array(
 'ssl'         => array(
    'verify_peer'  => false,
    'verify_depth' => 3,
    'cafile'       => '/etc/openssl/certs/ca.crt',
  ),
);

$config['smtp_server'] = '%h';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

$config['smtp_conn_options'] = array(
  'ssl' => array(
    'verify_peer'  => false,
    'verify_depth' => 3,
    'cafile'       => '/etc/openssl/certs/ca.crt',
  ),
);
```
With this settings and the step 3 "Test IMAP config", I get in /var/log/roundcubemail/imap.log the following:
<juoeji6c> [BC6A] Connecting to tls://localhost:143...
<juoeji6c> [BC6A] S: * OK [CAPABILITY IMAP4rev1 LITERAL+ ID ENABLE STARTTLS AUTH=LOGIN AUTH=PLAIN SASL-IR] new.host Cyrus IMAP 3.0.7-16.el8 Fedora server ready
<juoeji6c> [BC6A] C: A0001 STARTTLS
<juoeji6c> [BC6A] S: A0001 OK Begin TLS negotiation now

While the following is logged to /var/log/roundcubemail/smtp.log when I use the "Test SMTP config":
<juoeji6c> Connecting to localhost:587...
<juoeji6c> Recv: 220 new.host ESMTP Postfix
<juoeji6c> Send: EHLO localhost
<juoeji6c> Recv: 250-new.host
<juoeji6c> Recv: 250-PIPELINING
<juoeji6c> Recv: 250-SIZE
<juoeji6c> Recv: 250-VRFY
<juoeji6c> Recv: 250-ETRN
<juoeji6c> Recv: 250-STARTTLS
<juoeji6c> Recv: 250-ENHANCEDSTATUSCODES
<juoeji6c> Recv: 250-8BITMIME
<juoeji6c> Recv: 250-DSN
<juoeji6c> Recv: 250 SMTPUTF8
<juoeji6c> Send: QUIT
<juoeji6c> Recv: 221 2.0.0 Bye

So the verify_peer-change did not seem to have any effect on the problem.

However, I now understand the underlying problem, so I changed RC to use FQDN instead of localhost, and that did the trick.

Thanks for your suggestion, it was helpful to get RC working.
