### ISSUE TITLE
Incorret 'with attachment' mark

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#7185]
some mails without attachments still have 'With attachment' mark in message list.
RCM git.

![IMG_3157](https://user-images.githubusercontent.com/3339948/72682629-24a37980-3ae0-11ea-97f2-54306a5faee6.JPG)

**Comment by alecpl** [comment]
This can happen if the message is multipart/mixed, but has no attachment inside. For performance reasons we do not fetch full BODYSTRUCTURE when listing messages, so the attachment detection is simplified. What is the message Content-Type?

**Comment by grape6** [comment]
Content-Type: multipart/mixed;

**Comment by alecpl** [comment]
So, that's it. Wontfix. Some servers (dovecot) support $HasAttachment/$HasNoAttachment keywords, if these are set Roundcube will use them.
