### ISSUE TITLE
RC V1.3.8 No more Solder Subscription only Inbox

### ISSUE THREAD

**Issue by Utopism** [roundcube/roundcubemail#7187]
Hi at some point all Sub Folders were un-subscribed.

When Subscribing to folders, I see all folders in folders list (unchecked).
When checking some I get the message Folder Subscription succeeded, but then when I refresh the mail view, they don't appear, and in Folder Subscription only Inbox remains checked.

**Comment by alecpl** [comment]
Sounds like imap server issue. You can enable imap_debug to see conversation with the imap server.

Roundcube has a code to auto-unsubscribe non-existing folders. So, it's also possible that Roundcube did it, but it would have receive incorrect list of folders from the server in the first place. And I think there was some related fix after 1.3.8, so make sure to upgrade.

**Comment by alecpl** [comment]
No feedback.

**Comment by Utopism** [comment]
Hi @alecpl,

Sorry that I gave no feedback, and thanks for your reply.

I am using debian (buster), and I haven't found an apt Repository to upgrade to a more recent version. I am trying to test with the debian Testing version.

**Comment by Utopism** [comment]
Hi again, I just updated to V1.4.2, issue is still present.

I will check the imap logs.

**Comment by Utopism** [comment]
Hi,

The subscription mecanism started to re-work after a server configuration change. 
My imap server is dovecot, and I have added a Namespace that was hidden : 
```
namespace {
   type = private
   prefix = "Other/"
   location = maildir:/mnt/mine/Mail/other
   inbox = no
   hidden = yes
   list = yes
   separator = /
}                                                                                                                                                            
```
putting it to hidden = no seemed to fix the issue, but re setting it to hidden = yes did not triggered the issue again. Of course no issue with my Thunderbird client.
Perhaps it helps.
