### ISSUE TITLE
managesieve flag rule save errors on "flag '': not a valid keyword"

### ISSUE THREAD

**Issue by alavaliant** [roundcube/roundcubemail#7188]
On our roundcube 1.4.2 install we've noticed that trying to set/remove/add flags via a managesiev filter rule results in the rule failing to save with `unable to save filter: server error occurred` being reported in the webmail interface.

Looking at the server logs the error
`PHP Error: script errors: line 191: flag '': not a valid keyword (POST /?_task=settings&_action=plugin.managesieve-save)`
is recorded

Testing has shown we can bypass the error if we put some text in the text field below the Draft flag toggle (which I assume is for custom flag entries?)

As far as I can isolate things it looks like managesieve is rather than stripping the empty text fields from the $flags array is instead keeping it as an empty string ('') which the backend code doesn't like.

As a test I edited roundcube/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php
to add
`
$last_item = array_slice($flags[0], -1)[0];
if ($last_item == '') {
    array_pop($flags[0]);
}
`
after the line
`
$flags          = rcube_utils::get_input_value('_action_flags', rcube_utils::INPUT_POST);
`

At which point we could save flag rules without needing to enter some text in the custom flag box.   Which seems to confirm my initial findings that the $flags array being populated with empty strings as array items is the cause of the problem.

I suspect there is a better place in the code to fix this than the way I hacked in my workaround though?

**Comment by alecpl** [comment]
Confirmed. Empty flag is not an error on Cyrus-IMAP so I didn't notice earlier.

**Comment by alecpl** [comment]
Fixed.
