### ISSUE TITLE
Linebreak in subject

### ISSUE THREAD

**Issue by Virinum** [roundcube/roundcubemail#7191]
I've received an email with a linebreak in the subject:
![image](https://user-images.githubusercontent.com/42373861/72970452-fb2c6b80-3dc7-11ea-8d2a-5e08b8e67d2e.png)
![image](https://user-images.githubusercontent.com/42373861/72970522-28791980-3dc8-11ea-9180-6570589685e0.png)

I think it doesn't look very well in both views. Maybe linebreaks shouldn't be displayed or they should be displayed in a better way.

The subject header:
`Subject: =?UTF-8?B?ICBHb29nbGUgTWFwcy1Db21tdW5pdHkKIOKAkyAiTmV1ZSBIw6R1c2VyIGZlaGxlbiIK?=`

**Comment by alecpl** [comment]
Confirmed. Linebreaks should be removed from subjects.

**Comment by alecpl** [comment]
Fixed.
