### ISSUE TITLE
cannot view message with kolab calendar plugin on with 1.4.2 roundcube

### ISSUE THREAD

**Issue by studiowena** [roundcube/roundcubemail#7192]
Hi,

I have installe plugin Calendar and do all steps like was described here
https://plugins.roundcube.net/packages/kolab/calendar

Calendar seems to be working but when clik on any message on my mail folder on right see nothing - only blank space. When plugin is removed from config all back to normal.

pls help with that issue

**Comment by alecpl** [comment]
Check logs for errors. We do not support external plugins here.

**Comment by jacekn2** [comment]
try in docroot roundcube:
curl -sS https://getcomposer.org/installer | php
php composer.phar require "sabre/vobject" "~3.3.3"
php composer.phar install
if u dont have net_ldap2 try install
pear install net_ldap2
