### ISSUE TITLE
Reading Pane - Understanding the issue

### ISSUE THREAD

**Issue by FUGithubSupportFF** [roundcube/roundcubemail#7193]
I use about 12 different mail clients, every one of them has an option to turn a preview pane on and off.

Unfortunately my hosting company has implemented Roundcube mail for all my domains and I can't believe you do not have this.

It seems that earlier versions have it because they used to talk about a config file option.

It is all about workflow, obviously if you receive a lot of mail you want to start with a list and do not want to open each one or even have it preview as it wastes time,  Some you will drag and drop into folders, but it is more than that, you want the screen space that the preview is taking up

There are very few config options compared to other webmail, nothing that gives a users the ability to change the awful layout and design 

As if this was not bad enough "white space" issue has crept in, what is the white space issue,? It is when developers have huge screens and create loads of unnecessary white space which may be fine for them but is awful on the most common screen format; the 15" laptop.  I can see 17 emails on my ISP email and just 4 on this awful roundcube mail client.

People want an "at a glance" view, plus the ability to rapidly decide what mails are important by the configurable list of fields on a list of their inbox.  
 
What shocked me even  more was when the author said 

"No such feature. As the skin author I'm really not interested in having it. Such feature would increase complexity much and Elastic's code is already quite big."

How bloody inconsiderate and arrogant.  Not Interested!  How about your users!  

So I will ask again, and yes your code is quite big, in fact it has a memory leak so if you use this client for any length of time it uses up gigabytes of memory and eventually crashed the browser.  The only way I could stop this was to stop it refreshing.

I would like to congratulate you on designing the most sloppy client I have seen in a long while.

I hope you manage to find some professional pride and self respect, then sort this out.

If you need to know what it should look like just google disable X reading pane where X is the mail client, e.g. Yahoo, Gmail, Thunderbird, Outlook, Hotmail, GMX etc, even Squirrel had this feature.

A similar request is below but promptly closed because someone was not interested because they already wrote bloated code.
https://github.com/roundcube/roundcubemail/issues/6458

**Comment by alecpl** [comment]
Thank you for your opinion. Use different skin, write a plugin, whatever. I don't have time. Provide a pull request then I may re-consider.
