### ISSUE TITLE
Windows - Sqlite- RC 1.4.2: SQLSTATE[HY000] [14] unable to open database file 

### ISSUE THREAD

**Issue by Andsup** [roundcube/roundcubemail#7196]
Hi,

I upgraded a working 1.3.3 config on Windows to the new 1.4.2 code keeping the same config file.
$config['db_dsnw'] = 'sqlite:///C:/db/roundcube1.db';

I got a db error on sqlite: SQLSTATE[HY000] [14] unable to open database file.

also tried 
- with a not existing file
- with $config['db_dsnw'] = 'sqlite:C:/db/roundcube1.db';

It's not a access right issue.

**Comment by alecpl** [comment]
Looks like a regression caused by 2f928a516d8e660ee9b.

**Comment by Andsup** [comment]
Tested with a relative path  : Connection to DB ok.

**Comment by alecpl** [comment]
Fixed.
