### ISSUE TITLE
 Outlook emails cannot be reply

### ISSUE THREAD

**Issue by BiggerCrayonZ** [roundcube/roundcubemail#7197]
We got a Roundcube plugin webmin instance and recently we update our Roundcube version to 1.4.2, and all the outlook emails (inclusive @live) cannot be reply.

In the email composer once we finished a reply message, the app does nothing.
I checked the web browser console and the onClick event send this error:

![WhatsApp Image 2020-01-29 at 5 17 24 PM](https://user-images.githubusercontent.com/32489142/73406402-f2520300-42bb-11ea-9a70-a33b610ec7e3.jpeg)

It should be noted that it always happens with Microsoft emails and with a email html body.

**Comment by alecpl** [comment]
Works for me. What Roundcube error log says? Or http server log? Are you using any plugins? Try to disable them.
