### ISSUE TITLE
Pseudo-SSO Login with hash possible?

### ISSUE THREAD

**Issue by p1ngb4ck** [roundcube/roundcubemail#7198]
Hi everyone,

I have the special usecase here, that I need to provide a direct-link to roundcube-webmail for already authenticated users (that did not auth to roundcube yet, but a different system).
Unfortunately, a real "SSO" route is currently impossible due to other restrictions. Therefore I can only make the other system grab the hash for the user from the roundcube-db, where the other system has safe access to.
I already managed to set a simple cookie - but that works with cleartext pw only - which I dont have available for those users.

Is there any possible way, to make roundcube`s auth-progress accept the correct hash instead of cleartext pw ? - I emphasize the point, that this is not security relevant in this case, as the authentication in before is really really safe - those users are in a safe/monitored environment after first auth then.

Thanks for any help - I wasn`t able to find the correct spot in code myself.
Best regards, Oliver

**Comment by alecpl** [comment]
Roundcube needs to log in the user to imap/smtp, so you need a way to authenticate the user to these services w/o a password. Look for SSO related plugins and create your own if needed. That's not something for core.
