### ISSUE TITLE
Non-static method PEAR::setErrorHandling() should not be called statically

### ISSUE THREAD

**Issue by axos88** [roundcube/roundcubemail#7199]
Seems like #4798 is back

PHP Deprecated:  Non-static method PEAR::setErrorHandling() should not be called statically in /var/www/roundcube/program/lib/Roundcube/bootstrap.php on line 103

**Comment by axos88** [comment]
Seems like 6626328e7cc92b7be522af8249c77b8d4ea3b341 is the offending commit

**Comment by axos88** [comment]
Although I'm not sure that supressing that warning was the proper fix

**Comment by alecpl** [comment]
Imo, you're using very old PEAR version.

**Comment by axos88** [comment]
That's entirely possible :). Just upgraded to php7.4 from 5.6, maybe pear was not upgraded in the process.

**Comment by axos88** [comment]
Nope, I was using 1.10.5, upgraded to 1.10.10, but it's still happening. (restarted php-fpm).
```
# pear version
PEAR Version: 1.10.10
PHP Version: 7.4.2
Zend Engine Version: 3.4.0
```

**Comment by alecpl** [comment]
What Roundcube version? Are you using composer (or full package)? Check the pear version in vendor folder.

**Comment by axos88** [comment]
Just upgraded to 1.4.2
I am installing from source.

How do I check the pear version? I guess this is not the way:

# ./vendor/bin/pear version
PHP Parse error:  syntax error, unexpected 'new' (T_NEW) in /var/www/roundcube/vendor/pear-pear.php.net/PEAR/PEAR/Frontend.php on line 91

**Comment by alecpl** [comment]
Did you run `composer update`? That error suggests you don't have dependencies up to date.

**Comment by axos88** [comment]
Yep that fixed the issue, thanks for helping out! A note in the installation instructions about this would be nice though.
