### ISSUE TITLE
Problem saving drafts with attachs 

### ISSUE THREAD

**Issue by ndias** [roundcube/roundcubemail#7200]
When I save a draft that contains an attach, and try to re-edit the message, the body and the attach of the message disappear , I only have the message with the Recipients and the subject intact.
In the server I can see the message with the body and the attach.

**Comment by alecpl** [comment]
What version? What Mail_mime version? Could you provide the sample message?

**Comment by ndias** [comment]
Sorry for not supply the roundcubemail  version ... 
roundcubemail-1.4.2
php-pear-Mail-Mime-1.10.5
 
test.txt is the message that I can see in the mail server
Screenshot what I see in the webmail

[test.txt](https://github.com/roundcube/roundcubemail/files/4138878/test.txt)
![Screenshot from 2020-01-31 10-18-22](https://user-images.githubusercontent.com/886782/73533372-90f27700-4416-11ea-8f4a-30d7f59b3603.png)

**Comment by alecpl** [comment]
Update Mail_Mime to 1.10.6 or downgrade to 1.10.4. Of course, broken messages will stay broken.

ps. tests.txt is not the email message.

**Comment by ndias** [comment]
Sorry you are right ... I upload the wrong file.
Nevertheless the problem is solved with updating to php-pear-Mail-Mime-1.10.6

Thanks
