### ISSUE TITLE
session_lifetime in config.inc.php doesnt work

### ISSUE THREAD

**Issue by studiowena** [roundcube/roundcubemail#7201]
Hi,

roundcube 1.4.2

I have setiing in config.inc.php
`$config['session_lifetime'] = 5;`
and after 5 minutes or more of inactive on my browser tab where i have opened roundcube i can click refresh or other link on roundcube and session is still active.

I have disabled auto check messages on settings roundcube to test this.

on my php.ini i have session lifetime 1440s

**Comment by alecpl** [comment]
Roundcube keeps the session alive for how long the browser window is open and user logged in. So, the lifetime is when the session expires after "disconnection".
