### ISSUE TITLE
Use 3rd Party Login like Microsoft, Facebook and Google?

### ISSUE THREAD

**Issue by zayn008** [roundcube/roundcubemail#7202]

**Comment by zayn008** [comment]
Link Roundcube account with Office 365 login? So if im logged into office 365, Roundcube will log me into the relevant account

**Comment by alecpl** [comment]
This requires proper environment for this to be possible. There are some SSO plugins around, but probably not directly for what you're asking for. We do not plan such thing in core.

**Comment by thomascube** [comment]
This requires IMAP and SMTP to support token based authentication, like XOAUTH2 which is already on the way into Roundcube. Seems like a duplicate of #6933.
