### ISSUE TITLE
Issue with e-mail reception

### ISSUE THREAD

**Issue by AurelDre** [roundcube/roundcubemail#7204]
Hi !

We have an issue with our Roundcube webmail, we don't receive some of the e-mails incoming.
I don't know anything about the setup, could you help me by giving me the information you need to explore and fix this issue ?

Thanks

**Comment by alecpl** [comment]
Roundcube is an email client, it has nothing to do with receiving email.

**Comment by thomascube** [comment]
Please read the IMPORTANT box at https://roundcube.net/support/
