### ISSUE TITLE
Elastic - Send unencrypted message not work

### ISSUE THREAD

**Issue by andrwire** [roundcube/roundcubemail#7205]
While sending encrypted message to address without key - popup message apear: "Key not found".

There are button "Send unencrypted":
Elastic skin - button not work, no error, popup message do not dissapear.
Larry skin - it works ok.

![rc-elastic-unencr](https://user-images.githubusercontent.com/60646851/73734692-b3ea9700-4746-11ea-99f2-e448845815c8.png)
![rc-larry-unencr](https://user-images.githubusercontent.com/60646851/73734694-b4832d80-4746-11ea-80bb-5ccaf7f95059.png)

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.

**Comment by andrwire** [comment]
Just updated to master branch, still same bug.

**Comment by alecpl** [comment]
The fix works for me. Maybe some browser caching issue? How did you update? Did you remove the enigma.min.js file?

**Comment by andrwire** [comment]
Not browser issue, tried Chrome and Firefox, clear cache.
Update via script: ./bin/installto.sh
Not remove enigma.min.js

**Comment by alecpl** [comment]
If you have enigma.min.js, you have to remove it.

**Comment by andrwire** [comment]
After deleting **enigma.min.js** and **openpgp.min.js** it works! Thanks!
Is there are correct instruction to update to master branch?

**Comment by alecpl** [comment]
No, the master branch does not include production stuff (compiled css, minified js files). So, it's generally not a good idea to upgrade production release to git-master. You generally should follow INSTALL file instructions for such case, but it does not describe a need to delete min.js files if they exist.
