### ISSUE TITLE
Markasjunk: Moving to Junk fails on messages selected with Select > All

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#7206]
Hi Alec,
To help, I've saw this on the logs, have no idea how it happen or who's the user, but the line number may help you.
RC 1.4.1

Feb  4 10:04:12 fastweb roundcube: PHP Warning:  Invalid argument supplied for foreach() in /home/hosting/host.pt/webmail/plugins/markasjunk/markasjunk.php on line 278

**Comment by alecpl** [comment]
This is a real bug. It happens when you mark all messages in a folder and try to mark them as junk. Looks like that part of the code works only with "simple" selection (which is if you select one or more messages, but not all).

**Comment by alecpl** [comment]
Actually, all drivers assume that $uids is an array, but it could be also "*". So, it's not that trivial to fix. @johndoh, maybe you would like to give it a try?

**Comment by alecpl** [comment]
Fixed.
