### ISSUE TITLE
Managesieve: Improve UX on custom header input

### ISSUE THREAD

**Issue by fodorgeza** [roundcube/roundcubemail#7207]
There is a bug creating a new filter under Elastic based skins.  Just try to create one, in the first dropdown list is some dots at the first place, who knows what for, the second input box has no label or placeholder to inform a user, what to type in.

**Comment by alecpl** [comment]
That's an input for a custom header name. Not really a bug, but I guess we should add placeholder and title to the input. I think it works the same in other skins.

**Comment by alecpl** [comment]
Fixed.
