### ISSUE TITLE
HTML Emails not displayed when style tag is used

### ISSUE THREAD

**Issue by zsi-vienna** [roundcube/roundcubemail#7209]
**Problem Description**

If an html Email has a `<style>` tag inside head or body Roundcube does not display its contents (body) in html view - it does however display in simple text view.
When you take the sample email provided and delete the `<style>` section, the email is displayed in html view as it should be.

Now we are aware that using `<style>` in html-Email is a bad idea but some clients (Outlook?) seem to do it anyway. 
The problem is probably(!) new since we updated to 1.4.x a month ago (from 1.3.x) and users reported this only recently

**Check list**

* Roundcube version is current: 1.4.2
* Server-OS: Debian Buster
* What's your PHP version?
  * PHP 7.3.11-1~deb10u1
* What's your mail server?
  * has probably no impact on the issue but tested against both OLD and CURRENT mailserver:
  * OLD: postfix 2.9.6 and dovecot 2.1.7
  * CUR: postfix 3.4.7 and dovecot 2.3.4.1
* What browser/operating system did you use, any special settings/plugins?
  * Windows 10 Firefox 68.4.2 ESR
  * Windows 10 Iron (Chromium) 79.0.4100.0
  * Debian 10 Firefox 68.4.1 ESR
  * privacy badger disabled in FF, no other plugins
* What did the logs say?
  * imap log says it does a successful FETCH () of the mail-body
* Is the behavior reproducible?
  * yes, see attached simple mail and instructions above
* Does the problem persist with all plugins disabled?
  * all plugins disabled in config.inc.php - problem still exists

**Sample Email for reproducing issue**

    Content-Type: multipart/alternative; boundary="----_=_NextPart_001_5e3a9222"
    Content-Transfer-Encoding: binary
    MIME-Version: 1.0
    From: "Me" <me@domain.com>
    Subject: TEST
    To: you@domain.com
    Date: Wed,  5 Feb 2020 11:00:03 +0100 (CET)
    
    This is a multi-part message in MIME format...
    
    ------_=_NextPart_001_5e3a9222
    Content-Type: text/plain; charset="iso-8859-1"
    Content-Disposition: inline
    Content-Transfer-Encoding: 8bit
    
    *This is body text in plain text part*
    
    ------_=_NextPart_001_5e3a9222
    Content-Type: text/html; charset="iso-8859-1"
    Content-Disposition: inline
    Content-Transfer-Encoding: 8bit
    
    <head>
    <style>
    body { color:#666666; }
    </style>
    </head>
    <body leftmargin="0" topmargin="0"> 
    <table>
    <tr> 
    <td>This is body text in html part</td> 
    </tr> 
    </table>
    </body>
    </html>

**Comment by smares** [comment]
I can read mails with <style> tags in them perfectly fine. Isn't this caused by the missing opening <html>?

**Comment by zsi-vienna** [comment]
good point - i just tried adding that, it does not make a difference unfortunately - content stays hidden with and without opening `<html>`

i also found out just now that the behaviour is the same if the email is html only (so no multipart Content-Type)

i also tested different skins (Larry, Elastic, Classic) in the meantime: no difference

**Comment by alecpl** [comment]
It works for me. The output is:
```
<div class="message-htmlpart" id="message-htmlpart1">
  <!-- html ignored --><!-- head ignored --><!-- meta ignored -->
  <style type="text/css">#message-htmlpart1 div.rcmBody { color:#666666; }</style>
  <div class="rcmBody"> 
  <table>
  <tbody><tr> 
  <td>This is body text in html part</td> 
  </tr> 
  </tbody></table>
  </div>
</div>
```
I'm using PHP 7.4.2. What HTML output do you see?

**Comment by zsi-vienna** [comment]
**Layer 8 problem detected**
please replace faulty sysadmin (a.k.a. me)


**Solution:**
deleted this line (which was dragged along from previous RC installations) in /etc/php/7.3/apache2/php.ini
```extension=dom.so```

I have no idea why or what this does nor if it was good for anything in the past ...
phpinfo() shows absolutely no difference with and without this line

also no errors showed up anywhere (apache logs, RC imap.log, ...)

Very sorry for the bother :smirk:
