### ISSUE TITLE
wrong identity selected when replying

### ISSUE THREAD

**Issue by udi111** [roundcube/roundcubemail#7211]
Replying to an incoming mail fom a sender whose identity is added to my profile as well:
the identities are messed up, in the reply the sender is the original sender and the recipient is me.
I tried with identity_select plugin, same results.

**Comment by udi111** [comment]
version is v1.4.1, sorry

**Comment by alecpl** [comment]
Fixed.

**Comment by alecpl** [comment]
Backported.
