### ISSUE TITLE
MySQL: Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by kosfango** [roundcube/roundcubemail#7212]
Hi All,

I've tried to update Roundcube with help of script installto.sh, but seems, it's failed:

Running update script at target...
WARNING: Changed defaults (These config options have new default values):
- 'skin'
- 'smtp_port'
- 'smtp_user'
- 'smtp_pass'
- 'jquery_ui_skin_map'
Executing database schema update.
Updating database schema (2019092900)... [OK]
Updating database schema (2020020100)... [OK]
ERROR: Error in DDL upgrade 2020020101: [1071] Specified key was too long; max key length is 767 bytes
Updating database schema (2020020101)... [FAILED]
All done.

# mysql -V
mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by alecpl** [comment]
We switched to using utf8mb4 charset, so older MySQL versions have problem. We'll not change the schema to workaround this problem. I guess we'll add a note to INSTALL/UPGRADING about that.

From what I know  MySQL < 5.7.7 and MariaDB < 10.2.2 requires following configuration:
```
innodb_large_prefix=true
innodb_file_format=Barracuda
```

**Comment by alecpl** [comment]
Done.
