### ISSUE TITLE
Can you add an extra delete button like with Outlook?

### ISSUE THREAD

**Issue by Dave-09** [roundcube/roundcubemail#7213]
Good morning!

I wondered if it is not possible to add the delete button to Roundcube as Outlook does:
https://imgur.com/ineyOEV

It used to be a bit easier in the old skin because the removal was further on top:
https://ic.tweakimg.net/ext/i/1353001603.jpeg

I think this should be possible? what do you think?

**Comment by alecpl** [comment]
Duplicate of #7141.

**Comment by Dave-09** [comment]
Oops! thank you for the information.
