### ISSUE TITLE
Add more options to the layout of the archive folder

### ISSUE THREAD

**Issue by mildred** [roundcube/roundcubemail#7216]
Hi,

I'd like to suggest to add more options to the archive folder layout (preferences > special folders > archive) :

- Year then original folder (Archives/YYYY/original/folder)
- Month then original folder (Archives/YYYY/MM/original/folder)

These options are available in Thunderbird, and for compatibility it would make sense to include them.

**Comment by alecpl** [comment]
Should be easy. Pull requests appreciated.

**Comment by mildred** [comment]
See linked PR for implementation.

**Comment by alecpl** [comment]
Implemented. Thanks for the PR.
