### ISSUE TITLE
Wrong explanation of replacement variables for default_host in config.inc.php.sample

### ISSUE THREAD

**Issue by drpetersen** [roundcube/roundcubemail#7217]
Just wanted to let you know that, unless I'm mistaken, in the comments in `config.inc.php.sample`, the explanation of the replacement variables `%d` and `%z` seems to be mixed up:
```
// %d - domain (http hostname $_SERVER['HTTP_HOST'] without the first part)
// %s - domain name after the '@' from e-mail address provided at login screen
```
should in fact rather be:
```
// %s - domain (http hostname $_SERVER['HTTP_HOST'] without the first part)
// %d - domain name after the '@' from e-mail address provided at login screen
```

Background: I was using the following configuration option in `config.inc.php`:
```
$config['default_host'] = 'tls://imap.%s';
```
I expected that, with this setup, user `foo@example1.com` should be able to login to `imap.example1.com` and user `bar@example2.com` should be able to login to `imap.example2.com` from a roundcube installation at an arbitrary host `https://mail.example3.com`. This is not the case, though. It only works when `foo@example1.com` actually uses the webapp from a virtual host `https://whatever.example1.com`, and `bar@example2.com` from `https://arbitrary.example2.com`.

With the following config option,
```
$config['default_host'] = 'tls://imap.%d';
```
logins work as expected, no matter what the domain of the web app is.

Thank you for looking into this and, if appropriate, applying the obvious trivial fix to the comments in `config.inc.php.sample`. Cheers!

**Comment by alecpl** [comment]
The description is correct and the behavior is correct. Works for me as specified. Maybe the problem is somewhere else. What version?

**Comment by drpetersen** [comment]
I'm on a fresh git master (4e2e87610) version. After your reply I also tried the 1.4.2 tag (51b813717). Both work for me as reported above. So actually, no problem for me, and if it's just me, sorry for the noise.
