### ISSUE TITLE
Issue #6924 still alive

### ISSUE THREAD

**Issue by grosjo** [roundcube/roundcubemail#7218]
Hi

Previous post has been closed, but git version of Roundcube still has thz same probem

Issue #6924

**Comment by smares** [comment]
What do you do to clean the session data on the server and what session storage do you have configured for Roundube?

**Comment by alecpl** [comment]
Without any more details we'll just close the ticket the same as the previous one.

**Comment by grosjo** [comment]
Cleaning sessions data is done by restarting the server (stop ; clean session ; start)
Cleaning sessions is "rm -rf " in /run/httpd/sessions/

I tried using memcached , the bottom line is the same (roundcube still logged in, so it means there is a cookie on the client side)

**Comment by alecpl** [comment]
Roundcube does not use php session by default. And the session is supposed to be cleared automatically by php gc. If it is not this is misconfiguration. You can use bin/gc.sh script to clear expired sessions manually.

**Comment by grosjo** [comment]
please, stop closing so quickly issues. THis is really a pian point ! ANy user is still logged in after restarting httpd. this is a realy security issue !

Can you please look at this properly ?

**Comment by alecpl** [comment]
Provide Roundcube configuration, Roundcube version, PHP version. And read my last comment until you get it.
