### ISSUE TITLE
Problems with "max_message_size"

### ISSUE THREAD

**Issue by erlonmz** [roundcube/roundcubemail#7221]
In defaults.inc.php of Roundcube-1.4.2 has configured "max_message_size=20M"

In php.ini has configured
"upload_max_filesize = 20M"
and
"post_max_size = 20M" 

But in e-mail, the max message size it allows me is 15.
Message of attachment:
"Maximum allowed file size is 15 MB"

Anybody know whats is the problem with this confugration?

**Comment by alecpl** [comment]
Maybe that config file is not used. Or you have to restart some service. Or there's some .htaccess file. Not a bug.

**Comment by fernando-sianet** [comment]
Hi Aleksander

It's possible change the attachment value?
"Maximum allowed file size is 75 MB"

I tried to find this value "75" in the files below, but I didn't find.
config/config.inc.php
config/defaults.inc.php
/etc/php.ini
config/.htaccess

Please can you help me one more time?

**Comment by elvisef** [comment]
Firstly, please check Your /etc/php.ini is the file PHP is using at the time You're writing.
You can check it for example this way: `php --ini | grep "Loaded"` 

or to check if config options are set as desired: `php -i | grep -E "post_max|upload_max"`

If this is not the issue, please try postfix config change: [https://electrictoolbox.com/postfix-email-size-limit/](https://electrictoolbox.com/postfix-email-size-limit/)

**Comment by milosivanovic** [comment]
It seems this value is 75% of `$config['max_message_size']`, which defaults to 100M in Roundcube's `defaults.inc.php`. If post_max_size or upload_max_size is smaller though, they will take precedence.
