### ISSUE TITLE
Transparent 'List Options' menu and others in Elastic

### ISSUE THREAD

**Issue by booshlinux** [roundcube/roundcubemail#7223]
![Screenshot from 2020-02-13 12-29-29](https://user-images.githubusercontent.com/33703686/74471135-ef7b1480-4e5c-11ea-8fd3-8d44996cf0f0.png)

Roundcube version 1.4.2
I've noticed that some menus are fully transparent, and the background does not lower it's opacity. This is with all plugins disabled. Has anyone else ran into this issue?

Thanks.

**Comment by alecpl** [comment]
I see also some small alignment issues. Did you try with different browser? Any errors in browser console? Works for me.

**Comment by booshlinux** [comment]
I've found the issue. The elastic folder was missing from jqueryui. Thanks for the response however @alecpl.
