### ISSUE TITLE
Elastic: Improve mail header "detailed mode"

### ISSUE THREAD

**Issue by syzop** [roundcube/roundcubemail#7224]
With the new elastic skin you can no longer see instantly if there is 1 recipient or multiple. For every message you have to manually click on ```Details``` in order to see the recipients. Since there is no hint if there is 1 or more recipients this means you basically have to do this for *every message*. I got several complaints about that from staff and I agree with them that this is a major issue. I see it is also noted by https://github.com/roundcube/roundcubemail/issues/7222#issuecomment-586258114 and possibly elsewhere but I did not see a separate Issue for it.

I suggest to show the first 5 recipients by default and if there are more then an 'and more' or '...', like most email clients do.

This is on roundcube 1.4.2 by the way.

Perhaps the writers of the skin did not take into account that in certain (possibly even many) languages, regions or organizations the email netiquette is quite informal. Emails start simply with "Hi," and similar phrases which give no clue otherwise as to the recipient. In my country, such information is often seen as redundant as the header already shows to who the email is addressed.
Also, in our organization - and hopefully in others as well - we have clear rules as to what ```To:``` means (you are expected to respond) and ```Cc:``` (you may read and optionally reply, but there is no expectation for you to respond). By not showing out-of-the-box whether I am in To or in Cc, that too causes confusion, especially since the text of the email may very well be entirely in the singular form when there is 1 person in To and 1 person in Cc.

**Comment by johndoh** [comment]
Perhaps the state of the state of the Details button could be remembered so the next time a message is previewed then the details are displayed.

**Comment by alecpl** [comment]
Probably it could, but I also have some ideas to improve that widget.
1. After you click "Details" link:
    - the link should disappear, instead we could add a close icon in right-top of the div.message-partheaders element.
    - also div.header-subject should disappear (as it contains duplicate information).
2. Or we could design something completely different instead of the Details/Close button, e.g. some right/left arrow (or more/close) on side, or I don't know. But the idea is to make the whole header look better in "detailed mode".

**Comment by rdacn** [comment]
I confirm many users are confused by the current "Details" link, the lack of "To" immediately visible field (especially to see at once if they are the main recipient) , and information redundancy between simple mode and "Details" (From and Date).  #7437 would be a great improvement !

**Comment by rdacn** [comment]
Another complaint is that the From field only displays the username, lots of users would prefer username + email address to be displayed at once

**Comment by johndoh** [comment]
@rdacn does the `message_show_email` config option not do what you want? It can also be set by the user under Displaying Messages > Show email address with display name.

**Comment by rdacn** [comment]
Oops ! My fault, I had totally skipped that option ! Thanks that's exactly what I meant, and sorry for the bother...

**Comment by alecpl** [comment]
Done.
