### ISSUE TITLE
I think #7064 broke compatibility with MSSQL Server

### ISSUE THREAD

**Issue by Netsplits** [roundcube/roundcubemail#7227]
I think that fix for issue #7064 broke MSSQL compatibility.

I'm having an exception at rollbackTransaction() on test.php line 211. After further investigation, startTransaction() returns False. I'm using MSSQL on php 7.3.1 using Microsoft PDO SQL driver, tested on 5.6.1 and 5.7.1-preview. The error code is this:

[0] => 42000
[1] => 3988
[2] => [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A new transaction is not allowed because there are other threads running in the session.

I just disabled rollbackTransaction() code to finalize setup, but can I have some problems in the future?

**Comment by alecpl** [comment]
Strange, but I have no setup to try to find a solution. I guess, we could just skip use of transactions there when working with MSSQL.

**Comment by alecpl** [comment]
Fixed.
