### ISSUE TITLE
1.4.3 with elastic skin - SHIFT+PGUP and SHIFT+PGDOWN don't work

### ISSUE THREAD

**Issue by chilek** [roundcube/roundcubemail#7230]
... in composer window (see attachment).

![Zrzut ekranu z 2020-02-20 11-04-48](https://user-images.githubusercontent.com/1457437/74923320-daf4ca00-53d0-11ea-8eca-f7c95606f74c.png)

**Comment by chilek** [comment]
... at the same time it works with larry skin.

**Comment by alecpl** [comment]
You mean for text selection? I confirm it works in Firefox, but not in Chromium.

**Comment by chilek** [comment]
> You mean for text selection?

Exactly.
In my FF browser also works, but not in all chromium-based browsers (probably).

**Comment by alecpl** [comment]
Strange, but it looks like `overflow-y:hidden` makes Chrome to "disable" these key combinations. Also PageUp/PageDown without Shift do not work. You can still use Shift+ArrowUp/ArrowDown and other text selection shortcuts.

We have to look at other ways to implement textarea auto-resizing.

**Comment by alecpl** [comment]
This is not fixed in git-master, but I'll have to do some more tests before it could be beckported to 1.4.

**Comment by chilek** [comment]
cherry-picked https://github.com/roundcube/roundcubemail/commit/38d6659384712e4c3f4d6c9b041d9e9e4ef7eee0 to my installation. Now it works in my Google Chrome.

**Comment by alecpl** [comment]
There's scroll-jump effect in MS Edge now, we have to fix that.

**Comment by alecpl** [comment]
Fixed. Backported to 1.4.

**Comment by chilek** [comment]
Dzięki!
