### ISSUE TITLE
Elastic: recipient input bug when using click to select a contact from autocomplete list

### ISSUE THREAD

**Issue by jtuta** [roundcube/roundcubemail#7231]
Hi,

I stumbled on a weird bug, lets assume that we have "John Doe" with email "john.doe@example.com". Now when composing mail, lets type on the keyboard into "To" field: `john.doe@e` and **click** on the suggested "John Doe <john.doe@example.com>" (do not use tab, or down arrows and enter). Also do not try with `john.doe@` or `john.doe`. There must be also a part of domain, for the bug to occur.

Result: in the "To" field, there are two recipients: `john.doe@e` and `John Doe`.

![image](https://user-images.githubusercontent.com/15046120/74932907-3039d700-53e3-11ea-87e0-ddfe18d73b2f.png)

Tested in 1.4.0 and 1.4.3

Best regards,
Jure

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
This might not be that easy to fix. What happens here is that on click the input's onchange event is fired, and this is where we parse the input (and add `john.doe@d` box). Then another event is fired that adds the selected recipient.

We could just change the email address regexp and do not accept domain part with no dot character, but this would not work if you enter "john.doe@example.co".

**Comment by jtuta** [comment]
Although I agree that a regexp would be practical fix, i think it would not be in line with RFCs (I don't know if being in line with various RFCs is your goal). 

If we read RFC 5322 and RFC 1034 and think of all edge cases I don't think that dot is required in the domain name, as TLD  (especially now when gTLD are becoming popular) mail host should be valid.

[This resource](https://emailregex.com/email-validation-summary/) also reminded me of IPs as "domains".

**Comment by alecpl** [comment]
It does not happen if the entered text does not look like an email address. I'm working on a fix that will remove the invalid recipient box in such cases.

**Comment by alecpl** [comment]
Fixed.
