### ISSUE TITLE
Messages disappear when viewed immediately

### ISSUE THREAD

**Issue by dhke** [roundcube/roundcubemail#7233]
Our installation has for some time now suffered from sporadic issues (about every 2-4 weeks) with new messages disappearing from the inbox. The problem started to appear somewhere around 1.3.1 or so and continues to be present with 1.4.2. Sorry if the below is a little long, but I a little bit out of depth as for further debugging. I'll try to keep this issue updated when more information arises, but I'm also thankful for suggestions on how to debug the problem further.

I was not yet able to reproduce the problem independently, so I am currently stuck with user reports of the issue. According to those

- users see the message appear in the inbox.
- users click on the new message. Please note: I do not have consistent reports on this, so selecting the new message may or may not be the culprit.
- if users look for the message in their inbox, it is no longer displayed in the message list.
- the problem seems to mostly affect users with large inboxes, usually >= 1,000 items or more.

As for our installation:
- we have a load balanced installation with multiple webmail servers behind a simple TCP load balancer.
- we have a single backend database host that is accessed by all servers.
- the load balancing has source IP persistence, so users do not frequently switch between backend hosts.
- we use database cache tables. These are several gigabytes.
- we use database sessions
- we have `mail_read_time = 0`

Workarounds that we have tried so far:
- if the user remembers the message subject or sender and searches for the message, the result list will contain the missing message. It will still not appear in the INBOX view.
- clearing the message cache completely or for a particular user makes the missing message re-appear.

I am currently evaluating if setting `mail_read_time > 0` makes the problem disappear or appear less often.

My current guess that there's a race condition between the cache update from the "mark as read" hitting the database and some other update query, but that's just a guess. In that case, `mail_read_time> 0` might make a difference.

**Comment by alecpl** [comment]
Any news on this? What PHP version? What imap server version? You said clearing messages cache helps, could you verify if clearing entries from only one of cache_index, cache_thread or cache_messages tables fixes the issue? I'm guessing that you don't have to touch cache_messages, it's more likely the index/thread information is wrong, but who knows.

Unfortunately if there's no way to reproduce the issue easily I have no thoughts about how you could debug this.

**Comment by dhke** [comment]
I am yet waiting for the problem to re-appear. 

We have been running with `mail_read_time = 1` (patched locally to make this possible) since a few weeks now and I am still waiting to another occurence.

Once the current situation settles down a bit, I'll got back `mail_read_time = 0` and see what happens.

**Comment by alecpl** [comment]
Not much we can do about this. If you have some more info we'll re-open the ticket.
