### ISSUE TITLE
Larry: extended skin not working reliably

### ISSUE THREAD

**Issue by x403** [roundcube/roundcubemail#7234]
Hi,

I am trying to customize Larry scheme, but with mixed result. New style file is applied on login page, however not e. g. after login to a mailbox. Inside `/skins` directory I have created structure as follows.

```
skins/xlarry/
  customstyles.css
  includes/
     links.html
  localization/
     {various .inc lang files}
 meta.json
```

**meta.json**
```
{
	"name": "xlarry",
        "extends": "larry",
	"author": "FLINT / Büro für Gestaltung, Switzerland",
	"license": "Creative Commons Attribution-ShareAlike",
	"license-url": "http://creativecommons.org/licenses/by-sa/3.0/",
        "localization": true
}
```

**includes/links.html**
```
<roundcube:include file="/includes/links.html" skinPath="skins/larry" />
<link rel="stylesheet" type="text/css" href="/customstyles.css" />
```

Both templates (`login.html` and `mail.html`) includes `links.html` in the same way. If I modified files directly at source (`/skins/larry`), it is working as expected. Using Roundcube v1.4.1, also tried the latest 1.4.3.

What could go wrong? Thank you for any help.

**Comment by johndoh** [comment]
Check the user settings, see if the user has selected the larry or xlarry skin.

**Comment by x403** [comment]
You are right, test user has explicitly selected Larry skin and I missed that. So not a bug, just silly oversight. Thank you for your help.
