### ISSUE TITLE
I can't see the content of the mails

### ISSUE THREAD

**Issue by Case-Games** [roundcube/roundcubemail#7241]
In the inbox, when I click on a mail, I don't see anything on the right side.
When I doubleclick on the mail I also see nothing. Only a white page.
But when I click on a mail and then press reply or something like that it works and the mail appears. 
I can't find something special in the log files.

**Comment by alecpl** [comment]
The page is completely white? That means there's a server error. There must be something in error log. Maybe missing php extension.

**Comment by Case-Games** [comment]
Hmm... No! The site gives 500 back, but nothing in the php log file or the roundcube log file.

**Comment by alecpl** [comment]
How about syslog or http server log?

**Comment by alecpl** [comment]
Not much details to work with. Try asking for help on mailing list or forum.

**Comment by jemm971** [comment]
Hello,
I just install Roundcube, all work well except Elastic : it works well when displayed on PC, but on smartphone (IPhone 5) the content of the email is not displayed.
And exactly like Case-Games : "But when I click on a mail and then press reply or something like that it works and the mail appears."
Nothing appears in the error logs (Apache, PHP, hmailserver)
And when I try with an Android phone it works well...

Someone has an idea ?
Thanks

**Comment by rastikw** [comment]
@Aaron-Junker Were you able to solve the problem? I run into this today and PHP or Apache does not log anything. Just error 500 is returned to the browser.

**Comment by Aaron-Junker** [comment]
> @Aaron-Junker Were you able to solve the problem? I run into this today and PHP or Apache does not log anything. Just error 500 is returned to the browser.

I removed all extensions and it worked again
