### ISSUE TITLE
roundcube-1.4.3 new rcube::SQ() method breaks my setup

### ISSUE THREAD

**Issue by KottV** [roundcube/roundcubemail#7243]
Hi,
with recent 1.4.3 some methods in mail/show.inc and mail/func.inc has been changed from **rcube::Q** to **rcube::SQ**
that breaks my setup which worked fine with 1.4.2:

`[24-Feb-2020 05:59:12 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method rcube::SQ() in /srv/www/roundcubemail/program/steps/mail/func.inc:513
Stack trace:
#0 /srv/www/roundcubemail/program/steps/mail/list.inc(109): rcmail_js_message_list(Array, false, Array)
#1 /srv/www/roundcubemail/index.php(302): include_once('/srv/www/roundc...')
#2 /srv/www/roundcubemail/public_html/index.php(26): include('/srv/www/roundc...')`

not sure where problem is in
my sys:
**openSUE Leap 15.1
php, php-sqlite 7.2.5**

I have to change such strings back to **rcube ::Q** to fix the issue

**Comment by alecpl** [comment]
The method is defined in lib/Roundcube/rcube.php. If you don't have it it means something's wrong with your installation.

**Comment by KottV** [comment]
right, thanks
