### ISSUE TITLE
issue with mobile devices 

### ISSUE THREAD

**Issue by bsbudhwar** [roundcube/roundcubemail#7244]
Hi,

while using mobile app it not displaying the messages and not able to select folder like inbox or sent see the attached snapshot from Samsung Note Edge 
![Screenshot_2020-02-25-15-46-25](https://user-images.githubusercontent.com/18082766/75238733-804fd980-57e7-11ea-95b7-0d8feb17a7cd.png)

the same issue with 1.4.2 also and now in 1.4.3 also and not able to logout as menu items are not visible

**Comment by bsbudhwar** [comment]
Even in windows system with chrome browser if we resize the chrome window same happens like mobile when we click on top back arrow it shows folders and then just disappear...
![Screenshot_1](https://user-images.githubusercontent.com/18082766/75239141-2996cf80-57e8-11ea-91dc-e0f270f09399.jpg)

**Comment by smares** [comment]
Cannot reproduce. Could it be because of plugins you have activated?

![image](https://user-images.githubusercontent.com/818380/75255397-28fb3a80-57e2-11ea-889e-bd8281c709d9.png)

**Comment by alecpl** [comment]
Test with disabled all plugins, please. What browser version exactly it is?

**Comment by bsbudhwar** [comment]
> Test with disabled all plugins, please. What browser version exactly it is?

Hi Aleksander,

You are right its the roundcube/customizr plugin which is causing this problem i removed this plugin and now its working fine.

Thanks for the help
