### ISSUE TITLE
Elastic Confusing button label in Select image/media dialogs

### ISSUE THREAD

**Issue by HighlyFavoredBA** [roundcube/roundcubemail#7246]
Using the Elastic skin with RC 1.4.3, when clicking on the + attachments button, and then selecting on Image, or Media, and then selecting a file, It's hard to tell that the files are actually attached.  And at the bottom of that, all that it has is a Cancel button.  There should be an OK, and a Cancel button.  The Cancel button currently acts like a OK button, but since it is labeled Cancel, it is confusing.  :--)

Also, where can I edit the mobile attachment menu labels (Image, Media, Link...).  Those labels for whatever reason aren't in (en_US.inc).

**Comment by alecpl** [comment]
So, this is about Select image and Select media dialogs of HTML editor. 

Indeed the button should be "Close" not "Cancel". Another issue is lack of downloading progress indication on the list.

**Comment by HighlyFavoredBA** [comment]
Does (later) mean that won't be fixed until after the 1.4  versions launch into 1.5 or higher?  :--)

**Comment by HighlyFavoredBA** [comment]
Reminder from earlier:  Also, where can I edit the mobile attachment menu labels (Image, Media, Link...). Those labels for whatever reason aren't in (en_US.inc).

**Comment by alecpl** [comment]
These are part of TinyMCE, see program/js/tinymce/langs.

**Comment by HighlyFavoredBA** [comment]
I found  en_CA.js & en_GB.js, but don't see en_US.js.  What should I use?  :--)

**Comment by alecpl** [comment]
Looks like the "original" strings are hardcoded in the TinyMCE code.

**Comment by HighlyFavoredBA** [comment]
So, I'd need to search around to find where that code is, correct?   :--)

**Comment by alecpl** [comment]
Fixed button label.
