### ISSUE TITLE
managesieve example plugin

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7252]
Is there some managesieve example plugin/code that I can have a look at.

I tried modifying the code of the managesieve plugin but that got stuck at a "PHP Error: Error loading template for ", but making a patch on this code I do not prefer to do. However the sieve plugins I found, are not using the classes and configuration settings of roundcube 1.4

**Comment by alecpl** [comment]
Sorry, we do not provide such support. You're on your own, try mailing list or forum.
