### ISSUE TITLE
Moving messages within a thread with drag and drop

### ISSUE THREAD

**Issue by flanagan** [roundcube/roundcubemail#7254]
Sometimes it happens that a mail does not end up in a thread although it belongs to it. Currently you cannot move it.

**Comment by alecpl** [comment]
Please, provide more information. What do you mean you cannot move it? We depend on server THREAD response, if it does not consider the mail be part of a thread Roundcube will display it separately. So, verify that with imap_debug.

**Comment by flanagan** [comment]
If a user sends a mail and the server doesn't put it in a thread, but you want to have it in a thread because it belongs there, a drag and drop customization would be helpful.

**Comment by alecpl** [comment]
Yes, it's not possible. And imo, not worth the effort.
