### ISSUE TITLE
how to set new language of roundcube ？

### ISSUE THREAD

**Issue by vinssanji** [roundcube/roundcubemail#7256]
when I set up the roundcube，and choose language of zh_CN or en-US，it only display effectively when logining ，after I log in, the system is still German，I dont know why，whether to download the language pack， and how to operate it ？
Please help me to solve this problem，thank you.

<img width="526" alt="1png" src="https://user-images.githubusercontent.com/61536255/75452084-93f86d00-59ac-11ea-8210-d21b11931df5.png">
<img width="473" alt="2png" src="https://user-images.githubusercontent.com/61536255/75452087-95299a00-59ac-11ea-9bef-1aa9646b7094.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/61536255/75452089-96f35d80-59ac-11ea-97e8-a863ef337b66.png">

**Comment by alecpl** [comment]
try `zh_CN` instead of `zh_cn`.

**Comment by alecpl** [comment]
And it is likely that the German language is saved in user preferences already. Try `$config['dont_override'] = array('language');` to confirm that.

**Comment by vinssanji** [comment]
it works，thank u very very much
