### ISSUE TITLE
Missing fields from QR Code contact data

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7257]
When exporting a contact saved in the address book only with Display Name (without First Name and Last Name) as QR Code, the name is missing in the generated contact data. 
I found this is due to restrictions in the function `rcmail_contact_qrcode in roundcubemail\program\steps\addressbook\qrcode.inc`.

Adding missing fields to the array with common fields solves the problem.
```
...
    // QR code input is limited, use only common fields
    $fields = array('name', 'firstname', 'surname', 'middlename', 'nickname', 'organization', 'department', 
        'prefix', 'suffix', 'phone', 'email', 'jobtitle');
...
```

**Comment by alecpl** [comment]
Fixed.
