### ISSUE TITLE
roundcube cant  send email，either receive!

### ISSUE THREAD

**Issue by vinssanji** [roundcube/roundcubemail#7259]
my stmp and imap config are both ok when setting the roundcube up, and i can login.
but i cant send ,either receive emails after login，the buttons display grey，so are other buttons.
i think maybe the problem of lacking plugins，so i choose many of them and update config，but has the same result.
who can help me solve this ? and  i also want to know , which plugins should i choose for basic normally usage of email，please  help me
<img width="252" alt="1" src="https://user-images.githubusercontent.com/61536255/75463556-f2c7e180-59c0-11ea-8405-436399f74905.png">
<img width="279" alt="2" src="https://user-images.githubusercontent.com/61536255/75463563-f491a500-59c0-11ea-9802-ca9557da886f.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/61536255/75463570-f5c2d200-59c0-11ea-9c2f-f843f67b2e84.png">
<img width="921" alt="4" src="https://user-images.githubusercontent.com/61536255/75463576-f6f3ff00-59c0-11ea-996c-2aa9b98eed6a.png">

**Comment by alecpl** [comment]
What version? Check browser console for errors.

**Comment by vinssanji** [comment]
my version is roundcube 1.3.8，i set it in linux vps，should  i check the log of  php or httpd?

**Comment by alecpl** [comment]
For support ask on mailing list or forum.
