### ISSUE TITLE
Elastic: "Open in new window" missing at mail compose

### ISSUE THREAD

**Issue by sfu420** [roundcube/roundcubemail#7260]
I can't find "Open in new window" option on the mail compose site in v1.4 Elastic

In v1.3 i am still using it a lot, when I am composing a new mail and suddenly i need any information from an older mail and i have to go back to the mail search area.

![InkedScreenshot_2020-02-27 Compose_LI](https://user-images.githubusercontent.com/12776959/75488982-a6c17080-59b1-11ea-920c-b691d73cd42b.jpg)

Please add this option to v1.4 Elastic, as well.

Thank you!

**Comment by alecpl** [comment]
Implemented.
