### ISSUE TITLE
Invalid Content-Type for messages with only html part and inline images

### ISSUE THREAD

**Issue by natan64** [roundcube/roundcubemail#7261]
Hi
This problem is in a 1371 line in:

pear/mail_mime/Mail/mime.php

$headers['Content-Type'] = 'multiplart/related';

Please change character:  "multiplart" to multipart

multiplart is incorrect :)

multiplart -> multipart

**Comment by alecpl** [comment]
Confirmed. This is Mail_mime issue, but I'll keep the ticket open until it's fixed there. I'm working on a fix.

**Comment by alecpl** [comment]
FYI, this is a regression introduced in Mail_mime 1.10.5.

**Comment by alecpl** [comment]
@natan64 How did you find that out? Would be good to have a test case so I make sure it is fixed properly. I see that fixing just the typo might not be enough.

**Comment by alecpl** [comment]
I found one. Sending a HTML email where are no attachments and no text in the body, but only at least one inline image. Adding any text to the html content will force a different code path with no issue.

**Comment by alecpl** [comment]
Nevermind, looks like indeed it's just the typo. Fixed in https://github.com/pear/Mail_Mime/commit/36e880fe35974ed which will be released as Mail_mime 1.10.7 this weekend.

**Comment by alecpl** [comment]
Released.

**Comment by natan64** [comment]
Thenx :)
