### ISSUE TITLE
wish: reply-all should respect reply-to (or warn)

### ISSUE THREAD

**Issue by RichardNeill** [roundcube/roundcubemail#7262]
Consider the following case:

User A  sends an email to "team@example.com"  (which is a mail-list of 50 people), explicitly setting Reply-To to be herself, usera@example.com. 

User B  (who is one of the members of the list), clicks "Reply-All".

At the moment, User-B will end up replying to team@ + userb@. 

The intention of User-A setting the "reply-to" field to herself was to prevent recipients accidentally doing a reply-all. However, this doesn't work.

My suggestion is that, if the reply-to field is set, then clicking the Reply-All button should either 
* reply only to the reply-to   OR
* warn the user "are you sure"

Thanks for your time.

**Comment by smares** [comment]
Why not simply Reply then?

**Comment by alecpl** [comment]
I don't like the idea. Are there any other clients that do what you expect?

**Comment by RichardNeill** [comment]
Fair enough - if you don't like the feature idea, I don't mind,  and I'm happy to withdraw the suggestion.

Thunderbird behaves the same way as Roundcube. The point of the idea was to support the intent of the original sender to redirect replies, that this should error-proof against one of the recipients on the mail list replying-all.  

[Use case for my team: accidental reply-all causes significant mail list noise, but we don't want to have to go as far as making the list moderated].
