### ISSUE TITLE
charset problem in html view (UTF-8 configured everywhere)

### ISSUE THREAD

**Issue by sergiokessler** [roundcube/roundcubemail#7264]
in html view I see this:
![image](https://user-images.githubusercontent.com/14111329/75837534-e1594d80-5da3-11ea-8739-c752d611d7f9.png)

in text view I see this (correct):
![image](https://user-images.githubusercontent.com/14111329/75837572-01890c80-5da4-11ea-8829-911195c0e2b6.png)

I checked all is configured in UTF-8 (DB, php, roundcube)...
I am lost...

**Comment by sergiokessler** [comment]
forgot to mention: rouncube 1.4.3 (updated by git)

**Comment by alecpl** [comment]
We'll have to see the message source.

**Comment by sergiokessler** [comment]
the msg come from my gmail account, here the source:
(I just obscured my phone)

`Return-Path: <sergiokessler@gmail.com>
X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on
	correo.perio.unlp.edu.ar
X-Spam-Level: 
X-Spam-Status: No, score=-2.0 required=5.0 tests=BAYES_00,DKIM_SIGNED,
	DKIM_VALID,DKIM_VALID_AU,FREEMAIL_FROM,HTML_MESSAGE,RCVD_IN_DNSWL_NONE
	autolearn=ham version=3.3.1
X-Original-To: sak@perio.unlp.edu.ar
Delivered-To: sak@perio.unlp.edu.ar
Received: from mail-qk1-f182.google.com (mail-qk1-f182.google.com [209.85.222.182])
	by mail.perio.unlp.edu.ar (Postfix) with ESMTPS id C278B2A3EA4
	for <sak@perio.unlp.edu.ar>; Tue,  3 Mar 2020 21:18:53 -0300 (-03)
Received: by mail-qk1-f182.google.com with SMTP id m2so5381340qka.7
        for <sak@perio.unlp.edu.ar>; Tue, 03 Mar 2020 16:18:53 -0800 (PST)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=gmail.com; s=20161025;
        h=mime-version:from:date:message-id:subject:to;
        bh=aBs20KB21KVrGZ42P5tH/tnt1WmK7i3fuVxZoWYSQTc=;
        b=OrpoZnWCE49CDdf2alASAxEwulVDWyKRcT9DLRhM4bw35X+u7NIpjdOB8q4pay7rNW
         iNg3nFmkubDGpaykf08Ubru+vym6ZEFemvYNE6WZTJJq0WkSsEyMJX4LWSjs0hyLhG4d
         +1/z0zYIlTEui7v6JCtwS8Ga0lMxRCsEgbqjATyR9PnuE3+LyFAj1mJzReGvK46bVGGJ
         OzyH60WviAEFHsyxdGo87uNaVUfzoj4ID4I9phujvtfvXY6Pi/+tAhqLt0ZMTQ3DHql+
         Pk96yWhZoekQgUbo9xfSit02mlvegY6FMaWySSz24cfSn+8dkFQEkgaFTuys21pIwI8j
         9ADw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=aBs20KB21KVrGZ42P5tH/tnt1WmK7i3fuVxZoWYSQTc=;
        b=qmxG4FNS4VBFP3/Gfdk7v4utIAM3q/kjIvo+QA0uGxbi45iiLVnBmT9/sjPx6gnDy0
         K/7ETVNhsSwfmzEPZrEaUiQdXj+bUxkXj3PvfQvnecZ6o44V+jrkBkCx74gNwy+lx7KY
         dx/B114ZipVTX5RGtNnIVHtJcABZkVU7TvjpSVSQ22Lj7YOXBG2YynADzMGCtdbfXwLR
         L2be9i1FuBztm3gun78QAkEHeUTmmpfkJgHYP0ITUrmdIyKPoSWOyoqEBCEylZnHbErC
         sALRmUkvvIDK5EKXDHiPypTtxl4lP51m8ZN9BwUyRrPdSLDrvRp3PC0L5gyeKgQxXYIH
         /NOg==
X-Gm-Message-State: ANhLgQ3fQsp7788wRuAWdyTrJuYt0l/gf5q+5m8BCl6O18AdNAKM+RU1
	bEOSINXn3JpeSebFZei1OYmrLf8yGo9uB0vhQkmM9njt
X-Google-Smtp-Source: ADFU+vtmcxJAZ7rBmWSfw7CZcW/yEEExAofJohWnQlARICh7CvkfjGBooWhVNCjS1qqoGLy6RqLH1tsm8m4/ZNxooys=
X-Received: by 2002:ae9:e8cc:: with SMTP id a195mr544308qkg.377.1583281131499;
 Tue, 03 Mar 2020 16:18:51 -0800 (PST)
MIME-Version: 1.0
From: "Sergio A. Kessler" <sergiokessler@gmail.com>
Date: Tue, 3 Mar 2020 21:18:39 -0300
Message-ID: <CADJXduF=dfEi9W-gLaQD2c=N6x2_Pu2HQrkuzc6nF8EdeVnbAw@mail.gmail.com>
Subject: =?UTF-8?B?aG9sw6E=?=
To: "Sergio A. Kessler" <sak@perio.unlp.edu.ar>
Content-Type: multipart/alternative; boundary="0000000000006c3431059ffc5d1a"

--0000000000006c3431059ffc5d1a
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

=C3=A9 =C3=A1 =C3=B1 =C3=B3


saludos,
--
Lic. Sergio A. Kessler
mobil: +54 X XX XXXX-XXXX

--0000000000006c3431059ffc5d1a
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">=C3=A9 =C3=A1 =C3=B1 =C3=B3<div><br></div><div><br clear=
=3D"all"><div><div dir=3D"ltr" class=3D"gmail_signature" data-smartmail=3D"=
gmail_signature"><div dir=3D"ltr"><div><div dir=3D"ltr">saludos,<div>--<div=
><div>Lic. Sergio A. Kessler</div></div></div><div>mobil: +54 9 XX XXXX-XXX=
X</div></div></div></div></div></div></div></div>

--0000000000006c3431059ffc5d1a--
`

**Comment by michaelof** [comment]
SAME issue, detected with German umlauts äöü ÄÖÜ and sharp s "ß" 
roundcube 1.4.3 on OpenSuse Leap 15.1, distro pkgs.
All running on own VPS: postfix, dovecot, roundcubemail, on apache.
roundcubemail pkgs updated frequently in the last time, no changes I'm aware of on the other software pkgs, so my feeling is that it might be a roundcubemail-only issue.

What I've found out:
E.g.:
- created via roundcubemail an email draft on iOS (iphone), saved.
Result: 
-- corrupted German umlauts when opening this draft within roundcubemail on win10
-- corrupted German umlauts when opening this draft within K9-Mail on Android

**Comment by alecpl** [comment]
I'm unable to reproduce. There's indeed no `<html>` nor `<body>` in the source code, but that should not be a problem since some time.

What PHP version? Are composer dependencies up-to-date?

**Comment by sergiokessler** [comment]
```
[root@correo ~]# php --version
PHP 7.3.15 (cli) (built: Feb 18 2020 12:16:29) ( NTS )
```
```
[root@correo webmail]# php composer.phar update --no-dev
Loading composer repositories with package information
Initializing PEAR repository http://pear.php.net
PEAR repository from http://pear.php.net could not be loaded. Your configuration does not allow connections to http://pear.php.net/channel.xml. See https://getcomposer.org/doc/06-config.md#secure-http for details.
Your configuration does not allow connections to http://plugins.roundcube.net/packages.json. See https://getcomposer.org/doc/06-config.md#secure-http for details.
http://plugins.roundcube.net could not be fully loaded, package information was loaded from the local cache and may be out of date
Failed to update git://git.kolab.org/git/pear/Net_LDAP3, package information from this repository may be outdated
Updating dependencies                                                                                            
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear.php.net/crypt_gpg could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[root@correo webmail]# 
```

So, I edited `composer.json` to replace all `http` with `https`, and re-run composer:

```
[root@correo webmail]# php composer.phar update --no-dev
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
Failed to update git://git.kolab.org/git/pear/Net_LDAP3, package information from this repository may be outdated
Updating dependencies                                                                                            
Package operations: 0 installs, 5 updates, 5 removals
  - Removing pear-pear.php.net/xml_util (1.3.0)
  - Removing pear-pear.php.net/structures_graph (1.1.0)
  - Removing pear-pear.php.net/pear (1.9.5)
  - Removing pear-pear.php.net/console_getopt (1.4.0)
  - Removing pear-pear.php.net/archive_tar (1.3.15)
  - Updating roundcube/plugin-installer dev-master (0.1.6 => 98af3c6):  Checking out 98af3c6156
  - Removing pear-pear.php.net/auth_sasl (1.0.6)
  - Installing pear-pear.php.net/auth_sasl (1.1.0): Downloading (100%)         
  - Removing pear-pear.php.net/net_idna2 (0.1.1)
  - Installing pear-pear.php.net/net_idna2 (0.2.0): Downloading (100%)         
  - Removing pear-pear.php.net/net_socket (1.0.14)
  - Installing pear-pear.php.net/net_socket (1.2.2): Downloading (100%)         
  - Removing pear-pear.php.net/net_sieve (1.3.4)
  - Installing pear-pear.php.net/net_sieve (1.4.4): Downloading (100%)         
Writing lock file
Generating autoload files
[root@correo webmail]# 
```

and I'm still seeing this in html view:
![image](https://user-images.githubusercontent.com/14111329/76145707-ac325100-606a-11ea-8a66-0573a9f187b9.png)

**Note that the _subject_ is displaying correctly, only the body fails**

if I switch to the text view, all is displayed correctly:
![image](https://user-images.githubusercontent.com/14111329/76145727-e3a0fd80-606a-11ea-88d7-c3c9cf7a6305.png)


I restarted apache (just in case), but no effect...

**Comment by alecpl** [comment]
Your composer file looks outdated.  We're not using pear channel anymore, there were also some other dependencies added. So, please update that using composer.json-dist.

**Comment by sergiokessler** [comment]
```
[root@correo webmail]# mv composer.json composer.json.old
[root@correo webmail]# cp composer.json-dist composer.json
[root@correo webmail]# php composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Package operations: 7 installs, 5 updates, 6 removals
  - Removing pear-pear.php.net/net_socket (1.2.2)
  - Removing pear-pear.php.net/net_sieve (1.4.4)
  - Removing pear-pear.php.net/net_idna2 (0.2.0)
  - Removing pear-pear.php.net/auth_sasl (1.1.0)
  - Removing pear/mail_mime-decode (dev-master)
  - Removing patchwork/utf8 (dev-master)
  - Downgrading roundcube/plugin-installer (dev-master 98af3c6 => 0.1.10):  Checking out 98af3c6156
  - Downgrading pear/pear_exception (dev-master dbb42a5 => v1.0.1):  Checking out dbb42a5a0e
  - Downgrading pear/net_socket (dev-master 7482c62 => v1.2.2):  Checking out bbe6a12bb4
  - Downgrading pear/net_smtp (dev-master 7e2e139 => 1.8.1):  Checking out 8f93b34878
  - Downgrading pear/mail_mime (dev-master 7cb95a6 => 1.10.6):  Checking out 7cb95a6020
  - Installing pear/auth_sasl (v1.1.0): Downloading (100%)         
  - Installing pear/net_idna2 (v0.2.0): Downloading (100%)         
  - Installing pear/console_commandline (v1.2.2): Downloading (100%)         
  - Installing pear/crypt_gpg (v1.6.3): Downloading (100%)         

                                                                                                                            
  [ErrorException]                                                                                                          
  file_put_contents(/var/www/html/webmail/vendor/bin/crypt-gpg-pinentry): failed to open stream: No such file or directory  
                                                                                                                            

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

[root@correo webmail]#
```

So, I edited the `composer.json` to delete the `crypt_gpg` line, and re-run:

```
[root@correo webmail]# php composer.phar update --no-dev
Loading composer repositories with package information
Updating dependencies
Package operations: 3 installs, 0 updates, 1 removal
  - Removing pear/console_commandline (v1.2.2)
  - Installing masterminds/html5 (2.5.0): Downloading (100%)         
  - Installing pear/net_sieve (1.4.4): Downloading (100%)         
  - Installing endroid/qr-code (1.6.6): Downloading (100%)         
Writing lock file
Generating autoload files
[root@correo webmail]# 
```

and now, it looks perfect:
![image](https://user-images.githubusercontent.com/14111329/76150125-a4cc7100-6085-11ea-9175-156718f3b84f.png)

### thanks you very much for your time !!

maybe there should be a script that does all the things (run composer, install-jsdeps.sh, lessc, etc) for those who like to maintain roundcube directly from the git stable branch ?
