### ISSUE TITLE
Cursor not placed correctly after Group recipient selection (Larry)

### ISSUE THREAD

**Issue by skiner68** [roundcube/roundcubemail#7267]
Please see the image. Tested on Firefox & Cromium. When user selects group recipient, cursor is not placed correctly - user can not directly type another recipient

Elastic user graphic boxes in recipinet filed, behaviour is correct here,

![comma](https://user-images.githubusercontent.com/11733592/75893273-d7326000-5e32-11ea-8793-b4cc80229174.png)

**Comment by alecpl** [comment]
Fixed.

**Comment by skiner68** [comment]
Great, thank you! :-)
