### ISSUE TITLE
Having a theme set in a user's rcube.db for a theme which does not exist on disk results in an inability to login

### ISSUE THREAD

**Issue by Woovie** [roundcube/roundcubemail#7271]
If you install a theme, say elastic, and your users switch to it, they are then given this in their preferences entry within their SQLite file:

`s:4:"skin";s:7:"elastic";`

If you remove elastic, this user can no longer login. They are presented with a page stating FILE NOT FOUND. Instead, the result should be that you instead load the default theme.

Replicated in a production environment with multiple users, running EDGE builds of cPanel. The elastic theme was added, some users switched to it, and the theme was removed.

The fix was that I had to manually edit their preferences array. This is not a very user-friendly solution. The array should be corrected for their preferences.

**Comment by alecpl** [comment]
There's a fallback, but problem is that it falls back to the internal default which is also Elastic. We'd rather fallback to a configured skin.

**Comment by alecpl** [comment]
Fixed. Note that you have to make sure the skin in configuration file is set to the existing one.
