### ISSUE TITLE
Make one message with 10 recipients be converted in 10 messages with 1 recipient ( for variable replacement based on `To` addresses)

### ISSUE THREAD

**Issue by tdjac0bs** [roundcube/roundcubemail#7273]
Hello.

We have a use case where we want to add 10 users in `To` field and make roundcube send 10 individual messages.

This is needed because we've implemented a plugin that do variable replacement based on `To` address, so each email must be processed individually.

Is it possible to do?

**Comment by alecpl** [comment]
Not possible. You could use `message_before_send` hook to implement that in a plugin, I guess.
