### ISSUE TITLE
Logo in print view not restricted in size, taking full page width

### ISSUE THREAD

**Issue by mrimann** [roundcube/roundcubemail#7275]
We've set a custom Logo for our webmail and that works well for both the login view and the webmail view once logged in:

![image](https://user-images.githubusercontent.com/1093784/76199571-656e6380-61f0-11ea-956d-22cc77b0f3bb.png)

When opening an e-mail in the print-view, the logo takes the full width which looks kinda weird on the print out:

![image](https://user-images.githubusercontent.com/1093784/76199703-a49cb480-61f0-11ea-965c-d5c199eae0d8.png)

Reason so far could be just a few bits of missing CSS: For the Webmail-UI, the logo size is limited like:
```
#layout-menu .popover-header img {
    max-height: 58px;
    max-width: 78px;
    padding: .25rem;
```

But for the print view, the logo is not size-restricted via CSS. So the browser just assumes "full-width", which with an SVG logo is the full width of the page. Setting `width: 58px` on the logo-image in print-view would solve this (just hacked that together via the dev-tools in Chrome, works basically, but would need some more testing).

So my suggestion would be to add something like this to the CSS:
```
#print-layout #logo img {width: 60px;}
```

**Comment by mrimann** [comment]
I added the following to `public_html/skins/elastic/styles/print.css` and that seems to do the job for the moment:

```
img#logo {
        width: 60px;
}
```

But would be cool this could be added to one of the next releases so we won't need to hotfix that after each update.

**Comment by alecpl** [comment]
Problem is that we do not use a logo on print pages by default. So, the size styles are missing. However, it is hard to set a size that will work for everyone. I think we could add `max-height: 100px` as we do on logon page.

You can always use different image for print pages.

**Comment by mrimann** [comment]
Thanks @alecpl - your hint helped me to solve this for us without modifying the code so that we stay updateable.

I wasn't aware of the possibility to configure different Logo files - but now have the following in our configuration and it works pretty good this way:

```
// set our logo, the bigger one "everywhere" and the small one as an override for print
$config['skin_logo'] = array(
        'elastic:*' => '/images/symbol_internezzo_rgb.svg',
        "[print]" => '/images/symbol_internezzo_small.png',
);
```

So for me, I think it's fine to close this issue without changing the code. But if you do, I fully agree that setting the print-logo's height instead of it's width is probably the better approach.

**Comment by alecpl** [comment]
Added `max-width: 80px`. Fixed.
