### ISSUE TITLE
1.4.x - Missing option "If moving messages to Trash fails, delete them"

### ISSUE THREAD

**Issue by Skygge666** [roundcube/roundcubemail#7276]
Hello!

Server settings,
Option "If moving messages to Trash fails, delete them" is missing.
Localization file "labels.inc" contains the key: "$labels['deletealways']", but the option is missing (or moved somewhere, I don't know where).

Best regards,
Skygge

**Comment by alecpl** [comment]
The option has been removed in 1.4. See #6782.
