### ISSUE TITLE
Elastic: Clicking on the bottom border of a folder will move the highlight without loading the messages of that folder

### ISSUE THREAD

**Issue by smares** [roundcube/roundcubemail#7279]
Sometimes when I am in a hurry, I manage to click exactly on the bottom border of a folder which causes the highlight to move to the allegedly clicked folder but without actually switching to that folder.

Not a big deal as probably that almost never happens, but I thought I'd report it anyways.

![border-click](https://user-images.githubusercontent.com/818380/76352368-37cc0c00-630f-11ea-8ac0-470c217ad004.png)

**Comment by alecpl** [comment]
Confirmed. The border belongs to the treelist's `li` element that handles the selection, but `a` element inside is the real link that makes the action of loading messages.

**Comment by alecpl** [comment]
This gets more complicated... The treelist widget in Mail and Settings is used in different ways. The former uses <a> elements for the actual action, the latter uses an event on the <li> element. Considering it is a tree structure, clicking the border may cause even more unexpected behavior. E.g. It might select the folder you didn't intend to select.

Fixing this will not be simple and not worth the effort.
