### ISSUE TITLE
could you help me find the roundcube dev document?

### ISSUE THREAD

**Issue by yangyang510** [roundcube/roundcubemail#7280]
Hi,
I want to use roundcube to build our system，use our protocol, but the roundcube have no dev document, could you tell where to find developer document. thanks.

**Comment by thomascube** [comment]
Please note that Roundcube is not a service but a free webmail client software that connects to standard email servers using the IMAP protocol. There's no developer documentation that would describe an API to Roundcube.

If you're looking for docs about extending or modifying the Roundcube sofware itself, please read through our [wiki](https://github.com/roundcube/roundcubemail/wiki).
