### ISSUE TITLE
inbox subfolders not showing new email alert 

### ISSUE THREAD

**Issue by bruce-afruz** [roundcube/roundcubemail#7281]
on the last upgrade , inbox subfolders not showing new email alert  mails coming to sub folder not showing by highlighted folder name on left pane , is it a known issue?

**Comment by alecpl** [comment]
The folder name is made bold and the unread count updates, but the color do not change to blue-ish like in Larry. I can confirm that. Is that what do you mean?

**Comment by alecpl** [comment]
Color issue fixed. If you meant something different open a new ticket with more info.
