### ISSUE TITLE
enigma: internal error on list keys

### ISSUE THREAD

**Issue by eldrik** [roundcube/roundcubemail#7286]
Using roundcube 1.4.3 in dockerized mailcow environment.

enigma homedir is working.

gnugpg driver is working.

While pointing to pgp-keys in roundcube ui getting an error

Unable to list keys! Internal error.

errors.log shows

`[16-Mar-2020 20:18:49 +0100]: <017d4f4e> PHP Error: Enigma plugin: Unable to open GPG subprocess. in /web/rc/plugins/enigma/lib/enigma_engine.php on line 981 (POST /rc/?_task=settings&_action=plugin.enigmakeys)
`

enigma.log shows

`[16-Mar-2020 20:18:49 +0100]: <017d4f4e> GPG: OPENING GPG SUBPROCESS WITH THE FOLLOWING COMMAND:
[16-Mar-2020 20:18:49 +0100]: <017d4f4e> GPG: /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --always-trust --ignore-time-conflict --ignore-valid-from --homedir '/web/keys/eldrik@mydomain.com' --version` 

If executed manually 

`docker exec -it mailcowdockerized_php-fpm-mailcow_1 /usr/bin/gpg --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --always-trust --ignore-time-conflict --ignore-valid-from --homedir '/web/keys/eldrik@mydomain.com' --version`

it gives me 

`
gpg: WARNING: unsafe ownership on homedir '/web/keys/eldrik@mydomain.com'
gpg: Fatal: status-fd is invalid: Bad file descriptor
`

If i change --status-fd '3' to 1 or 2 the output is 

`gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /web/keys/eldrik@mydomain.com
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2`

Any way to debug deeper on this?

Regards

**Comment by alecpl** [comment]
"Unable to open GPG subprocess" tells us that proc_open() call in Crypt_GPG lib failed. There's no other warning/error in logs? I don't know what that could be. The "unsafe ownership" warning usually is not a problem.

**Comment by alecpl** [comment]
No feedback. Anyway, looks more like Crypt_GPG issue, but with this information I can do nothing about it.
