### ISSUE TITLE
Roundcube can't connect to postfix 587

### ISSUE THREAD

**Issue by akam-it** [roundcube/roundcubemail#7289]
Hello,

I can't send email from roundcube, looks like timeout?
smtp.log:
> [16-Mar-2020 12:35:09 +0000]: <v558tvft> Connecting to localhost:587...
> [16-Mar-2020 12:38:25 +0000]: <v558tvft> Connecting to localhost:587...
> [16-Mar-2020 12:40:57 +0000]: <v558tvft> Connecting to localhost:587...
> [16-Mar-2020 13:00:34 +0000]: <vubfe93f> Connecting to localhost:587...
> [17-Mar-2020 09:59:27 +0000]: <iv151nlo> Connecting to localhost:587...

but I can connect to localhost:587 and I can to send mails from thunderbird via postfix:587

> root@mail:/var/www/roundcubemail-1.4.3/logs# openssl s_client -connect localhost:587
> CONNECTED(00000005)
> .................
> Peer signing digest: SHA256
> Peer signature type: RSA-PSS
> Server Temp Key: X25519, 253 bits
> ---
> SSL handshake has read 3110 bytes and written 391 bytes
> Verification: OK
> ---
> New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
> Server public key is 2048 bit
> Secure Renegotiation IS NOT supported
> Compression: NONE
> Expansion: NONE
> No ALPN negotiated
> Early data was not sent
> Verify return code: 0 (ok)
> ---
> ---
> Post-Handshake New Session Ticket arrived:
> SSL-Session:
>     Protocol  : TLSv1.3
>     Cipher    : TLS_AES_256_GCM_SHA384
> 

roundcube 1.4.3
postfix 3.3.0
dovecot 2.2.33.2

**Comment by alecpl** [comment]
Did you set `smtp_server` with tls:// prefix?

**Comment by akam-it** [comment]
yes, with tls

**Comment by akam-it** [comment]
$config['default_host'] = 'tls://locahost/';

**Comment by alecpl** [comment]
Wait, are you using tls or ssl? Port 587 is supposed to be used with TLS (STARTTLS) not implicit SSL, but I see you used s_client with no -starttls argument.

**Comment by akam-it** [comment]
yes, you right, thank you and sorry. It is not roundcube issue
