### ISSUE TITLE
IMAP STATUS response not handled

### ISSUE THREAD

**Issue by mediocreguy** [roundcube/roundcubemail#7290]
Our IpSwitch iMail server returns an (apparently) unusual response to the IMAP STATUS command in certain cases:

C: A0003 STATUS "Sent Messages" (MESSAGES UNSEEN)
S: * STATUS {17}
S: Sent Messages.mbx (MESSAGES 3 UNSEEN 0)
S: A0003 OK STATUS completed

The execute() function in rcube_imap_generic.php with a filter parameter does not handle responses that have a string count and continuation.

As a workaround I used the status() code from a previous release that does nose use the filter parameter.

Perhaps the entire response should be concatenated before applying the filter parameter in execute()?

**Comment by alecpl** [comment]
I guess, when filtering we should check if the `$response` ends with `{[0-9]+}\r\n`.

BTW, the fact that the server adds `.mbx` to the folder name in a response is not a problem here, but it is definitely a bug that could cause other issues in other places.

**Comment by mediocreguy** [comment]
Thanks - I haven't seen any problems with the .mbx though I guess there could be something subtle I'm missing...

This appears to be working in execute():

  ```
      // Parse response
        do {
            $line = $this->readLine(4096);

            if ($response !== null) {

                // handle extra string            
                if (preg_match('/\{([0-9]+)\}\r\n/', $line, $match)) {
                    // remove count
                    $line = preg_replace('/\{([0-9]+)\}\r\n/', '', $line);
                    // read and append the given bytes
                    $bytes = $match[1];
                    $out = '';
                    while (strlen($out) < $bytes) {
                        $tmp = $this->readBytes($bytes);
                        if ($tmp === null) break;
                        $out .= $tmp;
                    }
                    $line .= $out;
                    // read until EOL
                    $line .= $this->readLine(4096);
                }
                
                // TODO: Better string literals handling with filter
                if (!$filter || preg_match($filter, $line)) {
                    $response .= $line;
                }
            }

            // parse untagged response for [COPYUID 1204196876 3456:3457 123:124] (RFC6851)
            if ($line && $command == 'UID MOVE') {
                if (preg_match("/^\* OK \[COPYUID [0-9]+ ([0-9,:]+) ([0-9,:]+)\]/i", $line, $m)) {
                    $this->data['COPYUID'] = array($m[1], $m[2]);
                }
            }
        }
        while (!$this->startsWith($line, $tag . ' ', true, true));
```

**Comment by alecpl** [comment]
I simplified that a little bit in f9c84e264. Could you confirm it works for you?

**Comment by mediocreguy** [comment]
Thanks, but it does not work on the iMail server (it's a strange beast).  It requires an extra readLine() after the join.
 ```
// In filter mode we need additional code for string literals.
// We'll merge the following literal data into one chunk, so
// it can be compared with the filter below
if ($filter && preg_match('/\{([0-9]+)\}\r\n$/', $line, $match)) {
  // read and append the given bytes
  $bytes = $match[1];
  $out = '';
  while (strlen($out) < $bytes) {
     $tmp = $this->readBytes($bytes);
     if ($tmp === null) break;
     $out .= $tmp;
   }
  $line .= $out;
  $line .= $this->readLine(4096);
}
```
This also appears to work on dovecot.  But  I understand if you want to leave it out.

Thanks again for your time.

**Comment by alecpl** [comment]
Ok, I think that `$bytes = $match[1] + 2;` should do the trick, instead of the additional readLine() call. Could you confirm?

Dovecot is not using string literals for folder names, but it may use it for something else, so we really should have it fixed properly.

**Comment by alecpl** [comment]
I improved the code even more in 2965e60c1f, so it supports multiple literals in a single "line response". Would be great if you could test that.

**Comment by mediocreguy** [comment]
Sorry - it does not work for my case. I don't think you can assume the literal is immediately followed by \n\r (I assume that is what the $m[1]+2 is for).

In my case:

```
C: A0003 STATUS "Sent Messages" (MESSAGES UNSEEN)
S: * STATUS {17}
S: Sent Messages.mbx (MESSAGES 3 UNSEEN 0)
S: A0003 OK STATUS completed

```
after `* STATUS {17}\r\n`  you read 17 bytes, which gets you to `Sent Messages.mbx`  - however the rest of the line - `(MESSAGES 3 UNSEEN 0)\r\n` - is still waiting after the readFullLine() call, but gets filtered out since it does not contain the `* STATUS` filter.

I don't know if this is RFC complaint, but that's what I'm getting from iMail.

Thanks for your help.

**Comment by alecpl** [comment]
Damn, what I was thinking? Thanks for your patience. Should be working now with e84dc4c385.

**Comment by mediocreguy** [comment]
That works - thanks again.
