### ISSUE TITLE
Problem installing theme from git

### ISSUE THREAD

**Issue by meaz** [roundcube/roundcubemail#7291]
I have created a clone of the skins folder because I've started to work on a theme.
On my roundcube instance, I've deleted what is in the skins folder and git clone my repo, which includes the default theme plus mine. So elastic folder for example. I haven't changed anything on the elastic folder so I guess it should work out of the box. But it doesn't. The login page is messed up for example.
I have read this [readme page](https://github.com/roundcube/roundcubemail/tree/master/skins/elastic) in elastic folder. I have tried this also:
```
lessc -x styles/styles.less > styles/styles.css
lessc -x styles/print.less > styles/print.css
lessc -x styles/embed.less > styles/embed.css
```
(by the way why only those three files, there are more .less files in the folder)

and
`bin/updatecss.sh --dir skins/elastic`

But if doesn't change much:
![2020-03-19_11-20](https://user-images.githubusercontent.com/13604424/77057124-c3aafb80-69d3-11ea-85b7-5c9955f4c534.png)

What am I forgetting?

**Comment by johndoh** [comment]
what browser are you using? Have a look in the network tab of your browser console and look for 404/500 errors. at a guess I say you're missing the bootstrap files. have you run `bin/install-jsdeps.sh`?

> (by the way why only those three files, there are more .less files in the folder)

there is a lot of styling code needed for Elastic, its organized into different files to make it easier to manage the 3 main files include this other files as required.

**Comment by meaz** [comment]
@johndoh I used the .tar.gz release version. There is no install-jsdeps.sh file in bin.
Indeed I have some 404 errors for bootstrap.bundle.min.js. It says this file should be in `skins/elastic/deps/bootstrap.bundle.min.js` but I don't have any deps folder.
So I nee to donwload this install-jsdeps.sh file and run it?

**Comment by meaz** [comment]
nevermind, I did download this `install-jsdeps.sh` file + `jsdeps.json` file + install unzip and it works.

**Comment by meaz** [comment]
btw how can I add a custom theme based on elastic in `jsdeps.json` ? I see there are reference to `skins/elastic/deps/` in it, for example 
```
    {
      "lib": "less",
      "name": "LessJS",
      "version": "2.7.3",
      "url": "https://raw.githubusercontent.com/less/less.js/v$v/dist/less.min.js",
      "api_url": "https://api.github.com/repos/less/less.js/contents/dist/less.min.js?ref=v$v",
      "dest": "skins/elastic/deps/less.min.js",
      "sha1": "45ea4f9fed6c0568ec11faba048c3e3cb7612e9e",
      "license": "Apache-2.0",
      "source": "https://raw.githubusercontent.com/less/less.js/v$v/dist/less.js"
    }
```
do I need to copy this part and change elastic by my theme name?

**Comment by alecpl** [comment]
Ask on mailing list or forum. I see no bug here.
