### ISSUE TITLE
Problem with forwarding/replying to the messages containing multiple inline images.

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7293]
Roundcube Webmail 1.4.3
pear/mail_mime 1.10.7

When forwarding or replying to a message containing multiple inline images, only the first image is attached multiple times. 
Original message
![image](https://user-images.githubusercontent.com/44122211/77112262-5f1e8980-6a31-11ea-8e99-0bc4c0249589.png)
Reply to the same message in the compose window
![image](https://user-images.githubusercontent.com/44122211/77112324-79586780-6a31-11ea-981c-87f843d51911.png)

Maybe is related with #7122

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Fixed.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9150
- https://github.com/roundcube/roundcubemail/issues/5051
- https://github.com/roundcube/roundcubemail/issues/6279
- https://github.com/roundcube/roundcubemail/issues/7117
- https://github.com/roundcube/roundcubemail/issues/7122
- https://github.com/roundcube/roundcubemail/issues/7214
- https://github.com/roundcube/roundcubemail/issues/7293
- https://github.com/roundcube/roundcubemail/issues/7414
- https://github.com/roundcube/roundcubemail/issues/7440
- https://github.com/roundcube/roundcubemail/pull/7441
