### ISSUE TITLE
Auto changing IMAP server choice dependant on user name

### ISSUE THREAD

**Issue by freebrowser1** [roundcube/roundcubemail#7298]
I use Roundcube for more than one account, and also different IMAP servers.
In the login screen I can fill in the username/email and password as usual, and then select a mail server.
I'd like to add a javascript which selects the mail server automatically dependant on the domain of the email address (domain.com in this example) in the list in the last field below (now showing imap.server.com).

I cannot add it in config.inc.php which is the only file not being updated when an update is available, so I want to leave other files untouched as they get get updated.

How can I do this, can also be a PHP code to achieve this 'autoselect'

![Screenshot 2020-03-25 at 15 36 57](https://user-images.githubusercontent.com/26625141/77548834-615c6a00-6eaf-11ea-8dce-f691db281e59.jpg)

**Comment by alecpl** [comment]
Doing this in javascript might be not ideal. I would rather do it as a plugin on server-side and remove the list from the logon form. See virtuser_query plugin for some examples.
