### ISSUE TITLE
roundcube 1.X+ hangs on inboxs with more than 4000 emails

### ISSUE THREAD

**Issue by mckaygerhard** [roundcube/roundcubemail#7300]
my email clients have inboxs of 5000+ emails in average..  some have 9999 (roundcube cannot count perfectly sometimes)

after many test, after many tries.. in a crazy step i installed roundcube 0.9.5 and works.. 

**seems roundcubes 1.4.X .. insclusivelly 1.2 or 1.3 hangs and get xtrremelly slowly if inbox are too huge..** i used redis cache and mencached and does not help.. any trick adn does not help

**why the older client 0.9.5 works perfectly**? in configured host (paid) and newer doe snot perform well, i tried several host configurations .. never the newer ones perform better rather the older ones.. that it's a crap..

with gmail and yahoo account with 9999+ mails in inbox it hangs searching..

**Comment by mckaygerhard** [comment]
those test are independient of the mails server.. due in thinderbird works perfectly.. inclusivelly.. that trick impulse me to make the final test of 0.9.5..

**Comment by alecpl** [comment]
I have folders with 10k+ messages and no problems with Roundcube. Describe the problem in more details. Is the list/search slow, or refreshing? Enable imap_debug to see conversation with imap (and some timings). Provide the log.

What do you mean it cannot count? In threads mode we display number of threads, maybe that's your issue. What imap server software are you using, except gmail/yahoo?

**Comment by mckaygerhard** [comment]
all the details are in the mail list threath https://sourceforge.net/p/courier/mailman/message/36959989/ in courier mail list we discuss how to deactivate THREAT sort.. but i think "it was working.. why deactivate this time?" so .. tried with older installed and puff working perfectly!

in my doubt i setup a new host.. lasted roundcube, lasted php, lasted courier, same result.. so changed roundcube by exim4 in centos and re-setup.. same problems.. later change all to citadel suite.. citadel performs high and perfectly in own frontend.. but with roundcube.. have poor performance.. 

on all of those test/setup i do not perform any optimizations.. why? well i never need.. in fact citadel does not need optimization when migrated all the mailboxes...

**i reported that due many users reports same problem in rare situations.. and noted that those users just "upgraded".. well recommendation:  do not upgrade! 0.9.X performs very well.**

i cannot do more test.. theres so obvious the problem and i research throught all the github issues.. same situation

**Comment by mckaygerhard** [comment]
> What do you mean it cannot count? In threads mode we display number of threads, maybe that's your issue. What imap server software are you using, except gmail/yahoo?

**gmail count of messages must be done at the configuration.. unless first login are XTREMELLY SLOW as describe in many issues here! .. that happened also with 0.9 but 0.9 make this more faster of course..** 

in every operation of  Is the list/search or refreshing? are slow..

**Comment by alecpl** [comment]
You don't provide any proofs nor debug information. We can't help you with this. I have the same opinion about Courier IMAP. Use dovecot or cyrus, that's much better software.
