### ISSUE TITLE
Plugin Creation

### ISSUE THREAD

**Issue by mitz-20** [roundcube/roundcubemail#7303]
Need some detail document in understanding how to write plugin and use hooks. I am ok with php code and is able to understand its functionality. However, present roundcube folder is difficult to understand its integration. Any help is appreciated. I have gone through github plugin api and plugin hook, needs more information for coding. 
Thanks

**Comment by alecpl** [comment]
There are plenty of plugins, just check their code. Use mailing list or forum.
