### ISSUE TITLE
What is the default PW?

### ISSUE THREAD

**Issue by softshipper** [roundcube/roundcubemail#7305]
Hi all  
What is the default user and password of the login window?  

![Screenshot from 2020-03-30 15-00-04](https://user-images.githubusercontent.com/56756949/77915344-9abe1c80-7297-11ea-98b7-129d848755e2.png)  

Thanks

**Comment by alecpl** [comment]
I have no idea. Ask the person who installed the software, please.

**Comment by softshipper** [comment]
I've installed the software with https://hub.docker.com/r/roundcube/roundcubemail, but I did not set any password. That it is because I asked you.

**Comment by alecpl** [comment]
Roundcube is an imap client, it has no default password.

**Comment by softshipper** [comment]
so I can login with my email@example.com account?

**Comment by alecpl** [comment]
There's no default user either. This is client software!!!

**Comment by softshipper** [comment]
@alecpl  One more question: 
![Screenshot from 2020-03-30 15-26-06](https://user-images.githubusercontent.com/56756949/77917513-efaf6200-729a-11ea-9c5b-eb66aa917fae.png)

Why do I get the error message. Login with Outlook, it works.  

This is my server configuration: 

```
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://dataxu.io
      - ROUNDCUBEMAIL_DEFAULT_PORT=993
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://dataxu.io
      - ROUNDCUBEMAIL_SMTP_PORT=587
```  

What am I doing wrong?  

Thanks

**Comment by alecpl** [comment]
Check the log. Ask on mailing list or forum. Here we do not provide configuration support.

**Comment by smares** [comment]
Port 993 seems like explicit SSL and not TLS by the way. TLS usually runs on port 143.

**Comment by melroy89** [comment]
> There's no default user either. This is client software!!!

Maybe a better response could have been...

Roundcube does not have an admin panel. Some admins might expect this, but Roundcube doesn't have this.

Be sure to set `$config['auto_create_user'] = true;` and configure the default IMAP correctly (as a global configuration). For example setting: `$config['default_host']` correctly.

Then, when you try to login with your account credentials for your mailing provider and assuming a successfully login will take place; Roundcube will be automatically create a new user in the Roundcube database (eg. MySQL).
