### ISSUE TITLE
IPv4 for IMAP, IPv6 for SMTP

### ISSUE THREAD

**Issue by frykandelbroadsje** [roundcube/roundcubemail#7306]
We use 'mail.%s' for IMAP and %h for SMTP. All users are able to log in over IMAP. But, a few users who don't have an IPv6 entry for mail.domain can't send mail.

Researching the logs of the mail server shows that IMAP login is going over IPv4, but the SMTP is going over IPv6. Is there a way to enable IPv4 for SMTP in the config, or is this a php setting?

`SMTP Error: Authentication failure: STARTTLS failed (Code: ) in /home/webmail/public_html/program/lib/Roundcube/rcube.php on line 1702 (POST /?_task=mail&_unlock=loading1585725488759&_framed=1&_lang=nl&_action=send)`

**Comment by smares** [comment]
It's the server that runs Roundcube that talks to the mail server, so I am not sure what you mean with "a few users who don't have an IPv6 entry for mail.domain can't send mail".

**Comment by frykandelbroadsje** [comment]
I have 2 mail servers, and 1 web server running roundcube. The users have different domains, so we use mail.theirdomain.com to log them in to the right server. For some reason, we see that domains with an AAAA record for mail.theirdomain.com have no issues sending mail, but people with only a regular A record have.

**Comment by alecpl** [comment]
I think this depends on dns resolution. If you want to force some IP address, then use it in config instead of a host name.

**Comment by frykandelbroadsje** [comment]
This turned out to be a cPanel setting for 'SMTP Restrictions' restricting users to connect to other SMTP servers.
