### ISSUE TITLE
installer page blanks after enable_installer in config

### ISSUE THREAD

**Issue by moeinrahimi** [roundcube/roundcubemail#7307]
i'm trying to install roundcube serving on a nginx server,
login page shows up correctly, the /installer page says to enable below config.
$config['enable_installer'] = true
after adding this to config file all pages goes blank.
my nginx server block
```
server {
server_name mail.server.example;
listen 80;
access_log /var/log/nginx/roundcube_access.log;
error_log  /var/log/nginx/roundcube_error.log;
root /var/www/html/roundcube;
    index  index.php index.html index.htm;

    location / {
            try_files $uri $uri/ /index.php?q=$uri&$args;
    }
    location ~ \.php$ {
         include snippets/fastcgi-php.conf;
         fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         include fastcgi_params;
    }

     location ^~ /data {
         deny all;
      }
}

```
I have created the mysql database and modified php.ini according to roundcube docs.

**Comment by alecpl** [comment]
white page almost always means there's a fatal error in logs somewhere.

**Comment by moeinrahimi** [comment]
yep, I manually changed config.php which is wrong and you should do it using installer
