### ISSUE TITLE
Folders in tree should be highlighted if marked messages are inside

### ISSUE THREAD

**Issue by jalsti** [roundcube/roundcubemail#7308]
When an IMAP folder contains a messages which is marked (and so is highlighted in the message list) also the folder in the tree should be highlighted.

**Comment by alecpl** [comment]
I don't like the idea. Is there any mail client that does this and how?

**Comment by jalsti** [comment]
I like the idea.
Claws mail is doing it by (depending on the icon theme) adding a small exclamation mark icon laid over the lower right corner of the folder icon. (And it additionally shows a similar overlay at the task bar icon, if a new reply to the marked messages comes in.)

**Comment by alecpl** [comment]
This will come with performance penalty. As we don't cache all messages (and cache is not always enabled), we'd have to do an extra imap search for every folder.

I don't see it in core, but it should be doable to write a plugin.
