### ISSUE TITLE
setting smtp_user and smtp_pass to `null` in config no longer disables SMTP auth

### ISSUE THREAD

**Issue by AdamWill** [roundcube/roundcubemail#7310]
This is an old bug, but I only use roundcube infrequently, so I only noticed it now.

In the past, setting `smtp_user` and `smtp_pass` to `null` in `config.ing.php` disabled SMTP authentication. However, this was broken by https://github.com/roundcube/roundcubemail/commit/7fc626d52713963f57b56a128bd0f95070d40613 . The intent of that commit seems to have been only to change the *defaults*, but due to the use of `isset` it also changes the behaviour when these values are explicitly set to `null`.

It seems that now in order to not use authentication you have to set these values to the empty string, which works, but breaks configurations that worked before that change.

@alecpl

**Comment by alecpl** [comment]
Indeed a regression. However, this is now in sync with how configuration defaults are handled in the whole application. So, I think we'll keep it this way, until we decide to change the behavior globally.
