### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by VadBar13** [roundcube/roundcubemail#7311]
There is encode problem for some html mails in 1.4.3

Screenshot roundcube 1.4.0
![roundcube_1 4 0](https://user-images.githubusercontent.com/7601203/78356021-7a53d200-75b7-11ea-94cf-436d864d599d.png)

Screenshot roundcube 1.4.3
![roundcube_1 4 3](https://user-images.githubusercontent.com/7601203/78356026-7c1d9580-75b7-11ea-9a5c-f4936ff9e780.png)

**Comment by alecpl** [comment]
Is this using the same default charset setting? Is this html or plain text message? Could you provide a sample message?

**Comment by trasherdk** [comment]
> encode problem for some html mails

OP said `html`.

Looks like a missing **utf8** setting somewhere.

**Comment by VadBar13** [comment]
> 
> 
> Is this using the same default charset setting? Is this html or plain text message? Could you provide a sample message?

Html. One tab in browser: use roundcube 1.4.0 - all ok, change it with 1.4.3. on server, refresh tab and it is not ok.

Message with cleared personal information:

`Return-Path: <@lorealfellowships-russia.org>`
`Received: from polly.phys.msu.ru ([unix socket])
         by polly.phys.msu.ru (Cyrus v2.3.16-Fedora-RPM-2.3.16-15.el6) with LMTPA;
	 Wed, 27 Mar 2019 14:44:37 +0300`
`X-Sieve: CMU Sieve 2.3`
`Received: by polly.phys.msu.ru (Postfix, from userid 425)
	id EE3AA60655; Wed, 27 Mar 2019 14:44:37 +0300 (MSK)`
`X-Spam-Checker-Version: SpamAssassin 3.3.1 (2010-03-16) on polly.phys.msu.ru`
`X-Spam-Level: *`
`X-Spam-Status: No, score=1.1 required=4.5 bayes=0.2739 tests=BAYES_40=-0.001,
	FROM_EXCESS_BASE64=0.979,HTML_MESSAGE=0.001,MPART_ALT_DIFF=0.79,
	RCVD_IN_DNSWL_LOW=-0.7,SPF_PASS=-0.001 autolearn=no version=3.3.1`
`Received: from relay13.nicmail.ru (relay13.nicmail.ru [195.208.6.7])
	(using TLSv1 with cipher DHE-RSA-AES256-SHA (256/256 bits))
	(No client certificate requested)
	by polly.phys.msu.ru (Postfix) with ESMTPS id 9025460475
	for <@polly.phys.msu.ru>; Wed, 27 Mar 2019 14:44:27 +0300 (MSK)`
`Received: from [109.70.25.185] (port=39471 helo=lorealfellowships-russia.org)
	by f17.mail.nic.ru with esmtp (Exim 5.55)
	(envelope-from <@lorealfellowships-russia.org>)
	id 1h96yp-000In4-3z
	for @polly.phys.msu.ru; Wed, 27 Mar 2019 14:44:27 +0300`
`Received: from [31.177.95.108] (account @lorealfellowships-russia.org HELO lorealfellowships-russia.org)
	by proxy06.mail.nic.ru (Exim 5.55)
	with id 1h96yp-0003QA-2K for @polly.phys.msu.ru; Wed, 27 Mar 2019 14:44:27 +0300`
`Date: Wed, 27 Mar 2019 14:44:26 +0300`
`To: @polly.phys.msu.ru`
`From: <@lorealfellowships-russia.org>`
`Reply-to: <@lorealfellowships-russia.org>`
`Subject: `
`Message-ID: <b4c6da72328864053f354cb4cb73bd7d@lorealfellowships-russia.org>`
`X-Priority: 3`
`X-Mailer: PHPMailer 5.1 (phpmailer.sourceforge.net)`
`MIME-Version: 1.0`
`Content-Type: multipart/alternative;`
	`boundary="b1_b4c6da72328864053f354cb4cb73bd7d"`


`--b1_b4c6da72328864053f354cb4cb73bd7d`
`Content-Type: text/plain; charset = "utf-8"`
`Content-Transfer-Encoding: 8bit`

`Здравствуйте, !Вы зарегистрированы на сайте Лореаль (lorealfellowships-russia.org).Логин: Пароль: Чтобы войти в личный кабинет пройдите по ссылке`


`--b1_b4c6da72328864053f354cb4cb73bd7d`
`Content-Type: text/html; charset = "utf-8"`
`Content-Transfer-Encoding: 8bit`

`Здравствуйте, !<br>Вы зарегистрированы на сайте Лореаль (lorealfellowships-russia.org).<br>Логин: <br>Пароль: <br>Чтобы войти в личный кабинет пройдите по <a href="http://lorealfellowships-russia.org/avtorizatsiya/">ссылке</a>`



`--b1_b4c6da72328864053f354cb4cb73bd7d--`

**Comment by alecpl** [comment]
The sample message works for me.

The message has alternative part, is this broken also in plain text mode? What PHP version? Are you composer dependencies up to date? Are you using `messages_cache` (is it enabled in config)? Enable imap_debug and see what is returned by IMAP server (when you open the message).

**Comment by VadBar13** [comment]
> The message has alternative part, is this broken also in plain text mode? 

In plaint text mode all is correct.

> What PHP version? 

PHP 5.5.38

> Are you composer dependencies up to date? 

Suddenly `php composer.phar require masterminds/html5` solves the encoding issue. Thanks.
