### ISSUE TITLE
question: how to change the logo and the theme collors, and how to know what's my default theme

### ISSUE THREAD

**Issue by thadeu220** [roundcube/roundcubemail#7314]
i am new to roundcube, and i had no answers in the roundcube community.
i just installed the roundcube in my website, and i want to do the following things.

1. change the default logo, to my own, what are the requirements, format, dimensions etc, for the the theme
2. how to discover what's my default theme, that is being used at the moment, i think it is 2. how to identify what is my actual theme, i think it is elastic, but i am not sure.
3. how to change the collors scheme, i think this can be answered later.

but i need help...
if you want to check my mail, this is the linknote: it is domain based, so, only authorized mails will be authorized to login.
https://email.rahra.com.br

i 'll be apreciating this support more soon as possible.
thanks

**Comment by fernando-sianet** [comment]
Hi

1 - roundcubemail-1.4.3/skins/larry/images/roundcube_logo.png 
the formats and dimensions you will change until you find the best format for your email
2 - Settings - Preferences - User Interface
3 - you can edit the file styles.css for example
topline { 
color: #aaa;

roundcubemail-1.4.3/skins/larry/templates/login.html

**Comment by thadeu220** [comment]
how to identify ewhat the default theme in use, and how to change it to
larry, if required.
cause i guess i am using other... but, not sure.
the first thing that i wish, is to change the login screen cololor

Em seg., 6 de abr. de 2020 às 15:44, fernando-sianet <
notifications@github.com> escreveu:

**Comment by thadeu220** [comment]
yes, my theme is elastic, how to change login backgroun on it

Em seg., 6 de abr. de 2020 às 15:44, fernando-sianet <
notifications@github.com> escreveu:

**Comment by alecpl** [comment]
Closing. This is not a support forum.
