### ISSUE TITLE
How to use else if for username ?

### ISSUE THREAD

**Issue by japjitravels** [roundcube/roundcubemail#7319]
I have install roundcube with elastic skin, now i want to use else if for username for below code 
`<roundcube:object name="username" />`

I want to check if user1 logged in then hide _bcc else show just like below

`<roundcube:if condition="env:username=='user1@xxx.com'" />`
hide bcc field
		  `<roundcube:else />`
              show bcc field
		`<roundcube:endif />` 

can anyone help me to do like this

**Comment by alecpl** [comment]
Ask on mailing list or forum.
