### ISSUE TITLE
Replacement variables does not seem to work for `default_host` config property

### ISSUE THREAD

**Issue by Ryzhehvost** [roundcube/roundcubemail#7322]
Hello!

I'm trying to use roundcubemail-1.4.3-complete and I encountered some strange behavior.
I tried to use replacement variable in `default_host` config property, as explained in comments of sample config file:
https://github.com/roundcube/roundcubemail/blob/3e9aefceef8595bae31aba295ce70e7bdfbb5719/config/config.inc.php.sample#L35-L40

I have in my config file a line like this:
```
$config['default_host'] = array('ssl://mail.%s');
```
I expect that if I login with `username@mydomain.tld` it will result in connection to `ssl://mail.mydomain.tld`.
But instead, when I try to login, I'm getting "Connection to storage server failed"
and in log file I'm getting a line:

```
IMAP Error: Login failed for username@mydomain.tld against mail.%s from X.X.X.X. Could not connect to ssl://mail.%s:993: php_network_getaddresses: getaddrinfo failed: Name or service not known in /path/to/roundcube/program/lib/Roundcube/rcube_imap.php on line 200 (POST /roundcube/?_task=login&_action=login)
```
It seems that replacement variables does not work for this config property. Could you please check this, and fix it if it's really a bug?

Best regards,
Ryzhehvost

**Comment by alecpl** [comment]
Don't use an array. `$config['default_host'] = 'ssl://mail.%s';`

**Comment by Ryzhehvost** [comment]
Thank you, worked like a charm!
