### ISSUE TITLE
message/rfc822 parts are not attached on forward

### ISSUE THREAD

**Issue by kveriz** [roundcube/roundcubemail#7323]
I faced with an issue with one letter - I don't see any attachments while I do forwarding. I see this behaviour in 1.3.10 and 1.4.3. However, I see attachment if I change compose option "Messages forwarding" to "as an attachment". At the same time I don't see any problem in TB and Outlook - they forward message correctly - with all attachments. The letter has nested parts, but I don't think these things are connected.

Here is a sample of that message and short [screencast](https://github.com/roundcube/roundcubemail/files/4469709/Peek.2020-04-13.16-39.zip) with reproducig that problem.

**Comment by kveriz** [comment]
Sorry. I forgot attache the [email](https://github.com/roundcube/roundcubemail/files/4473530/Fwd.zip)

**Comment by alecpl** [comment]
The message/rfc822 parts are not marked with `Content-Disposition: attachment`. That's why they are ignored. I guess, this should be fixed.

**Comment by alecpl** [comment]
Fixed.
