### ISSUE TITLE
trying to switch from tar.gz file install to git, but minified files are missing

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7324]
I am trying to switch from an active install from tar.gz file to the git clone, and it looks like the git clone is missing some minified files eg. jquery.min.js, bootstratp.min.css.

How / when are these created, how can I create these from the git clone source.

**Comment by smares** [comment]
Look at `cssshrink.sh` and `jsshrink.sh` in `bin`. Also, this is not a support forum, but an issue tracker for bug reports and feature requests.

**Comment by alecpl** [comment]
Read INSTALL/UPGRADING file.
