### ISSUE TITLE
./install-jsdeps.sh file check not ok? 

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7325]
I am getting file is not available, while it is.

bash-4.2$ ./install-jsdeps.sh
PHP Warning:  set_error_handler() has been disabled for security reasons in /home/login0/webmail4.example.com/program/lib/Roundcube/rcube_charset.php on line 348
PHP Warning:  set_error_handler() has been disabled for security reasons in /home/login0/webmail4.example.com/program/lib/Roundcube/rcube_charset.php on line 348
PHP Warning:  set_error_handler() has been disabled for security reasons in /home/login0/webmail4.example.com/program/lib/Roundcube/rcube_charset.php on line 348
PHP Warning:  set_error_handler() has been disabled for security reasons in /home/login0/webmail4.example.com/program/lib/Roundcube/rcube_charset.php on line 348
ERROR: Required program 'file' not found.

bash-4.2$ file
Usage: file [-bchikLlNnprsvz0] [--apple] [--mime-encoding] [--mime-type]
            [-e testname] [-F separator] [-f namefile] [-m magicfiles] file ...
       file -C [-m magicfiles]
       file [--help]

bash-4.2$ whereis file
file: /usr/bin/file /usr/share/file

**Comment by alecpl** [comment]
1. set_error_handler() function is required.
2. the script uses `which file`. Looks like that command returned nothing.

**Comment by f1-outsourcing** [comment]
Which file is also returning correct output. I think this could be related to the "/usr/bin/env php" and when you use multiple php versions via rh Software Collections. My guess is that /usr/bin/env overrides something in the environment you set with scl enable rh-php71 bash

bash-4.2$ which file
/usr/bin/file

**Comment by alecpl** [comment]
The script uses `file` to detect type of downloaded files. I guess we could use `rcube_mime::file_content_type()` instead. Or, since all downloaded files have proper extensions, we could just read the filename extension and not do any type detection.

What the script needs to know is whether the file is a zip or not. So, we could also read the first 4 bytes of the file content to find that out. For zip format it would be "PK\003\004".

**Comment by alecpl** [comment]
Fixed.
