### ISSUE TITLE
HTTP 500 after login

### ISSUE THREAD

**Issue by schachmat** [roundcube/roundcubemail#7327]
Heyho,

In Roundcube 1.4.3 I am seeing the following issue: When logging in, I get a HTTP 500 error. I've looked at the roundcube errors.log and see this:

`
PHP Parse error:  syntax error, unexpected 'px' (T_STRING) in /var/www/roundcube/program/include/rcmail_output_html.php(1150) : eval()'d code on line 1
`

A quick search on the internet revealed the old issue #3798 but I'm not sure if this is similar enough.

I don't have a lot of experience with PHP, but did some initial debugging by writing the `$expression` to disk before erroring out on the `eval()`:

```
$this->app->config->get('preview_pane',rcube_utils::get_boolean('')) == true
$this->env['quota']
$this->env['threads']
!in_array('preview_pane', (array)$this->app->config->get('dont_override',rcube_utils::get_boolean('')))
$this->app->config->get('preview_pane',rcube_utils::get_boolean('')) == true
$this->app->config->get('preview_pane',rcube_utils::get_boolean('')) != true
$this->env['threads']
!in_array('list_cols', (array)$this->app->config->get('dont_override',rcube_utils::get_boolean('')))
!in_array('message_sort_col', (array)$this->app->config->get('dont_override',rcube_utils::get_boolean('')))
!in_array('message_sort_order', (array)$this->app->config->get('dont_override',rcube_utils::get_boolean('')))
in_array($this->env['task'], array('mail', 'addressbook', 'settings'))
$this->browser->{'ie'}
$this->browser->{'safari'}
!empty($_COOKIE['mailviewsplitterv']) ? $_COOKIE['mailviewsplitterv']-5 : 160
!empty($_COOKIE['mailviewsplitterv']) ? $_COOKIE['mailviewsplitterv']+5 : 170
$this->browser->{'ie'} ? ('width: expression((parseInt(this.parentNode.offsetWidth)-'.(!empty($_COOKIE['mailviewsplitterv']) ? $_COOKIE['mailviewsplitterv']+5 : 165).')+\\'px\\');') : ''
```

Also I "accidentally" got a stack-trace of when the issue is happening:

```
Stack trace:
#0 /var/www/roundcube/program/include/rcmail_output_html.php(1098): rcmail_output_html->eval_expression('$this->app->con...')
#1 /var/www/roundcube/program/include/rcmail_output_html.php(1060): rcmail_output_html->check_condition('config:preview_...')
#2 /var/www/roundcube/program/include/rcmail_output_html.php(775): rcmail_output_html->parse_conditions('<!DOCTYPE html ...')
#3 /var/www/roundcube/program/include/rcmail_output_html.php(610): rcmail_output_html->parse('mail', false)
#4 /var/www/roundcube/index.php(315): rcmail_output_html->send('mail')
#5 {main}
```

As far as I'm aware, I'm currently the only user experiencing this issue (out of estimated 50 other frequent users on that instance). Another hint is that I may have selected an uncommon theme (the "classic" one, default on this server is something different). My browser is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36`.

**Comment by alecpl** [comment]
I'm unable to reproduce. What plugins are you using? Did you try with disabled all plugins?

**Comment by alecpl** [comment]
No feedback.

**Comment by cangak** [comment]
same problem, disable all plugin still 500
