### ISSUE TITLE
Address book: Group Rename htmlspecialchars 

### ISSUE THREAD

**Issue by icdsoftware** [roundcube/roundcubemail#7330]
How to reproduce:

1. Create a new contact group with special html cahracter in its name, for example: 
**`Family & Friends`**.
2. Select the newly created group and select Rename, the input field now shows: 
**`Family &amp; Friends`**

If you go to another screen, then go back to contacts and click on Rename - the problem is not present. However if you make changes and rename the group, subsequent clicks on Rename show the problem again. 

As far as I could trace the issue, it happens after an update the value comes back encoded here:
https://github.com/roundcube/roundcubemail/blob/master/program/steps/addressbook/groups.inc#L123
Then it is being stored in a JS object here:
https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L6804

**Comment by alecpl** [comment]
Fixed.
