### ISSUE TITLE
Content-type mismatch warning on an empty attachment

### ISSUE THREAD

**Issue by lucaspfmendes** [roundcube/roundcubemail#7332]
This attachment is suspicious because its type doesn't match the type declared in the message. If you do not trust the sender, you shouldn't open it in the browser because it may contain malicious contents.
Expected: application/pdf (.pdf); found: application/x-empty

![image](https://user-images.githubusercontent.com/63821215/79511331-7becb380-8015-11ea-8fd5-ee8a0e2bc287.png)

`Return-Path: <V6@tr.com>`
`Delivered-To: V8@tr.com`
`Received: from red.com (red.com [192.168.10.1])`
	`by red.com (Postfix) with ESMTPS id 234A9120149`
	`for <V8@tr.com>; Thu, 16 Apr 2020 17:47:30 -0300 (-03)`
`Received: from blue.com (unknown [192.168.10.2])`
	`by red.com (Postfix) with ESMTP id 79E626837334`
	`for <V8@tr.com>; Thu, 16 Apr 2020 17:44:03 -0300 (-03)`
`Received: from white.com (unknown [192.168.11.3])`
	`by blue.com (Postfix) with SMTP id 63AD6916AE0`
	`for <V8@tr.com>; Thu, 16 Apr 2020 17:44:03 -0300 (-03)`
`To: V8@tr.com`
`From: V6@tr.com`
`Subject: Attach`
`Reply-To: V6@tr.com`
`MIME-Version: 1.0`
`Content-Type: multipart/mixed; boundary="a1b2c3d4e3f2g1"`
`X-rm-Information: Please contact the ISP for more information`
`X-rm: 79E626837334.AF75D`
`X-rm: Found to be clean`
`X-rm-From: V6@tr.com`
`X-Spam-Status: No`

`--a1b2c3d4e3f2g1`
`Content-Type: text/plain; charset="iso-8859-1"`

`--a1b2c3d4e3f2g1`
`Content-Type: text/html; charset="iso-8859-1"`

`--a1b2c3d4e3f2g1`
`Content-Type: application/pdf; name="via.pdf"`
`Content-Transfer-Encoding: base64`
`Content-Disposition: attachment; filename="via.pdf"`

**Comment by alecpl** [comment]
Ok, what do you expect? I guess we could not allow to open empty attachments or do not consider them insecure.

**Comment by trasherdk** [comment]
How about replace attachment with a text saying something like "Content-type mismatch. Attachment removed".

Any "Content-Type" mismatch should be considered insecure.

**Comment by alecpl** [comment]
"it may contain malicious contents" is obviously not true if there's no content. We can't really replace that with "attachment removed" as empty attachment is still an attachment. How do you know it's been removed?

I think we can consider empty attachments secure, but probably a better option would be to just not display the option to open these.

**Comment by trasherdk** [comment]
I meant  removed from the UI (not showing). Not removed from the server.

Any "Content-Type" mismatch should be considered insecure.

**Comment by alecpl** [comment]
> I meant removed from the UI (not showing). Not removed from the server.

Then I don't understand what you're really proposing.

> Any "Content-Type" mismatch should be considered insecure.

I hear you, I just do not agree with you. Context matters.

**Comment by trasherdk** [comment]
Okay. I don't see an empty attachment as a security risk, but..

On general principle, I filter out any mail that is not 100% OK.
If the sender can't deliver a valid mail, I don't want it.

I reject e-mail from my bank, because their mailer is not SMTP complaint. That's typically auto-responders, that just fire and forget.

**Comment by alecpl** [comment]
Thunderbird for example displays a warning when you try to open an empty attachment. I think we should do the same. In addition we should remove the attachment menu.
![tbwarning](https://user-images.githubusercontent.com/546788/80861631-010bd580-8c70-11ea-88d8-67e88e90d2fd.png)

**Comment by alecpl** [comment]
Implemented as described above.

**Comment by ravikumar08151987** [comment]
Hello,

Let me start by saying this is such a great plugin. It produces beautiful invoices.

Now i am facing same problem [Content-type mismatch warning on an empty attachment] & if i try to open pdf showing error
Error[Failed to load PDF document.], i am using latest plugin, 

Please give me solution for this asap
