### ISSUE TITLE
Enigma plugin: Loading key store takes too much time 

### ISSUE THREAD

**Issue by phonon112358** [roundcube/roundcubemail#7334]
I use roundcoubemail 1.4.3 with enigma plugin version 0.8. 
When I try to send an encrypted message (to an email address of which I don't have the public key saved in roundcoubemail yet), I am first asked whether I want to search a key store for the public key. However, the loading process of the key store or the searching takes several minutes and seems to be aborted by some time-out mechanism of roundcoubemail. 

Is there any configuration that I have to do for solving that?
Or can someone confirm it as a bug?

**Comment by alecpl** [comment]
If searching timeouts we can't really do nothing about it. You can configure different public key server(s) via global `keyservers` option.

**Comment by phonon112358** [comment]
I still have problems...
I added `$config['keyservers'] = 'hkps://keys.openpgp.org';`to the `config.inc.php` and checked manually that the key which I want to import is on that server...
however, roundcoubemail doesn't find it and shows a message "loading..." for at least two minutes, then the message disappears and nothing happens... 

To me, it seems that roundcoubemail can't establish the connection to the key server...
Do you have any idea how I can debug that?

**Comment by JeSappelleRoot** [comment]
Hi there, 
I have a similar issue with the GPG key search function
I'm using RoundCube email webclient 1.4.4 with enigma version 0.8, inside a container

I tried to check DNS queries with TCPDUMP, `gpg --search-keys` command is good, and I can capture DNS queries
I also configured `$config['keyservers'] = array('keys.gnupg.net', 'keyserver.ubuntu.com');`
Enigma plugin log is enable but don't give me any clues

**Comment by alecpl** [comment]
Check the browser console. gpg is not used for searching, we search client-side (in javascript).
