### ISSUE TITLE
[Feature Request] Bullet Points in HTML Compose

### ISSUE THREAD

**Issue by Justinzobel** [roundcube/roundcubemail#7335]
Hi Team,

I'm loving RoundCube even more than most GUI email clients. I'm just missing the ability to add bullet points to my emails or numbered lists.

Using version 1.4.3 with all defaults.

**Comment by alecpl** [comment]
Lists are available in HTML mode.

**Comment by Justinzobel** [comment]
Where? How?

**Comment by smares** [comment]
![image](https://user-images.githubusercontent.com/818380/79964764-71a23d80-848b-11ea-9b5a-e44743a76094.png)

Switch to HTML mode when composing.

**Comment by Justinzobel** [comment]
I was in HTML compose mode but there is no option that I saw for bullet
points.

**Comment by smares** [comment]
![image](https://user-images.githubusercontent.com/818380/80011465-32481100-84cc-11ea-9a9d-1a895f204919.png)

**Comment by Justinzobel** [comment]
My apologies. I'm not sure why the browser I was using wasn't displaying it. I switched to a different browser and now it shows. Thank you for your time.
