### ISSUE TITLE
Deleting cache does not respect the user_id

### ISSUE THREAD

**Issue by tfl** [roundcube/roundcubemail#7336]
I do not know if this is correct behaviour but today I encountered a Postgres error during my logout from Roundcube Webmail (Note: i already fixed the permission denied error but I would not have noticed this without the misconfiguration):

```
ERROR:  permission denied for table cache
STATEMENT:  DELETE FROM "cache" WHERE "expires" < now()
ERROR:  permission denied for table cache_shared
STATEMENT:  DELETE FROM "cache_shared" WHERE "expires" < now()
```

**1st**. The cache table contains a user_id column but this column is not referenced in the query. So for a multi user site this will result in dropping all cached objects from all current logged on users where the WHERE condition matches. Maybe this is not intended...

**2nd**. The two tables seem to be related via column _cache_key_. The two columns are a) not the same size and b) If they are related I would asume that table _cache_shared_ should be cleared first depending on the selected _cache_key_ identified by the _user_id_ in table cache. After that table cache should be cleared.

I use the current RC 1.4.3 with PHP 7.4.5. As database I use Postgres, currently at v12.2

**Comment by alecpl** [comment]
Both queries are intentionally delete all expired entries from cache. Both tables are not related in any way.
