### ISSUE TITLE
Cannot connect to Managesieve

### ISSUE THREAD

**Issue by Abatjour3407** [roundcube/roundcubemail#7337]
I've had this problem for over a year now and never got around to fixing it. I'm running RoundCube 1.4 and whenever I try to add a filter under settings (or even if I click on the filters tab) I get the error message "cannot connect to managesieve". I've scoured Google looking for a solution on numerous occasions, my web host support team don't know the answer and it has baffled my web developer who has been trying to figure this out for a month already... Please help! If you need more information let me know in the comments below and I'll give you whatever info you require.

**Comment by alecpl** [comment]
Use mailing list or forum for support, please.
