### ISSUE TITLE
Signature

### ISSUE THREAD

**Issue by HighlyFavoredBA** [roundcube/roundcubemail#7338]
The code at the top of my of my HTML signature files, is currently as it is below.  Adding a file title causes the file title to show up above the default signature.  And <title></title>, without a actual file title, is obviously an HTML 5 error.  How can that be resolved?!  :--)

<!DOCTYPE html>
<html lang="en">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
    <title></title>

**Comment by alecpl** [comment]
I'm not sure I understand. What version? What you enter to the signature field and what is the signature code in the end? Is there a visual issue? Could you provide some screenshots?

**Comment by HighlyFavoredBA** [comment]
The latest version of RC with Elastic.  It's the Branded a.k.a. Global Signature that requires a Plain Text file, and a HTML Text file.  That started showing the file/page title <title>HTML Signature</html> above the actual Signature Text, Table, Image, etc.

On my classic 1.2.7 with a Responsive skin, the File Title doesn't show in the HTML Global Signature.  😎

**Comment by HighlyFavoredBA** [comment]
Yes, (generic_message_footer_html).  Below is the coding for that file / page.  When I don't comment out the <title>Email Branded Signature</title> in that file / page, it shows up above the signature.

<!DOCTYPE html>
<html lang="en">
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    
    <title>Branded Email Signature</title>
    <meta name="description" content= "SSL SECURE NON Big Bro Email!">
    <meta name="keywords" content= "webmail, web mail, email, encrypted, encryption">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <link href="table-hover.css" rel="stylesheet" media="all">
    <link rel="shortcut icon" href="NO-Favicon.png" type="image/x-icon" />
    
    
    </head>
    
<body>
    
   <br>
       <table style="margin-left: auto; margin-right: auto; border-collapse: collapse; border: 5px solid #2F3A3F;"><tbody><tr><td style="width: 210px; height: 150px; background-color: #FFFFFF; font-family: Arial; font-weight: bold; font-size: 16px; text-align: center; vertical-align: middle;"><p style="color: #2F3A3F;">Branded Mail -<p style="color: #2F3A3F;">SSL SECURE<br>NON Big Bro Email!<p style="color: #4169E1;"><a href="https://BrandedMail.com" target="_blank">https://BrandedMail.com</a></td></tr></tbody></table>

</body>
</html>

**Comment by HighlyFavoredBA** [comment]
![Branded-Signature](https://user-images.githubusercontent.com/31964993/80112120-5d6f4680-8546-11ea-947c-f571a790bb19.png)

**Comment by alecpl** [comment]
BTW, why the heck do you add that stuff to the signature? It is supposed to be a "footer" in a html content. It should not contain any title, meta, link tags, nor head for that matter.

**Comment by HighlyFavoredBA** [comment]
I know that a footer doesn't need that stuff.  However, I don't like seeing a bunch of Red X Errors, from not having a properly coded HTML file.  In the Plain Signature file / page, I only have as below. 

_____

Branded Mail -
SSL SECURE NON Big Bro Email!
https://BrandedMail.com

**Comment by alecpl** [comment]
It's not about what it needs and what not. This way you break the HTML rules and expect valid output. I don't see `head` opening tag, is this also missing or you just missed it here?

**Comment by HighlyFavoredBA** [comment]
I went ahead and took away <htnl><body>, and all of those tags.   Now I only have old school table tags.  I used a styled <div> over a year ago, but that didn't display properly on a number of browsers that I tested.   😎

**Comment by alecpl** [comment]
I'm closing this as a wontfix.
