### ISSUE TITLE
Elastic: Ratio of contact photo in mail preview

### ISSUE THREAD

**Issue by roumano** [roundcube/roundcubemail#7339]
Hi,

In our roundcubemail server, we have set adressbook with ldap backend.
It's working very great but with the elastic skin, in the mail's view, we have a bug with the ratio of jpegPhoto of user's
* See my picture in mail's, it's too wide :  
![bug_view_mails](https://user-images.githubusercontent.com/6402894/79996393-b7292f80-84b8-11ea-83cd-9caaf73d7384.png)

* But the ratio is good on the addressbook :  
![adressbook_correct_ratio](https://user-images.githubusercontent.com/6402894/79996405-babcb680-84b8-11ea-9151-75f08435c9c1.png)

* i have try to debug via opening firefox web Developer  , on the mail's it's opening this kind of url to get the picture : 
URL:https://servername/?_task=addressbook&_action=photo&_email=XXX%40YYY.ZZ&_error=1

Via this url, the picture have a good ratio, so i'm nearly sure it's a CCS issue on the elastic skin.

**Comment by alecpl** [comment]
I'm not sure what we could do better here. We definitely want the picture to fit the circle. Another option would be to truncate the image, and I'm not sure it would give better results.

**Comment by roumano** [comment]
Hi,
  Yes, definitely want the picture to fit the circle but it's shouln'd stretch (and transform the ratio) of the image, If the source of the image is not 3*4 but square, the ratio is good and don't have the issue.

**Comment by alecpl** [comment]
Using `object-fit:cover` on the img element gives me this.
![photo-fit](https://user-images.githubusercontent.com/546788/82724141-35edd400-9cd4-11ea-8fc0-eb817fe5c7c6.png)
It might be a solution, but I'll need to test some more.

**Comment by alecpl** [comment]
It will not work in old browsers, but I think it's the best solution we can find. Fixed.
