### ISSUE TITLE
INSTALL instructions slightly wrong for MySQL 8

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#7340]
I'm just trying a fresh setup of roundcube 1.4.x with MySQL 8.0.19 and the instructions in the  INSTALL file seem geared for older MySQLs.  Specifically, this command:

```
root@localhost [(none)]> GRANT ALL PRIVILEGES ON roundcubemail.* TO roundcube@localhost IDENTIFIED BY 'XXX';
```
Failed with this output:
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'XXX'' at line 1
```

I'm no MySQL expert, but what worked for me was:

```
CREATE USER 'roundcube'@'localhost' IDENTIFIED WITH mysql_native_password BY 'XXX';
grant all privileges on roundcubemail.* to 'roundcube'@'localhost';
flush privileges;
```

**Comment by alecpl** [comment]
Indeed, "Use of GRANT to define account authentication characteristics is deprecated as of MySQL 5.7.6." Looks like it has been removed in MySQL 8. You should be still able to use `IDENTIFIED BY` in `CREATE USER`.

**Comment by alecpl** [comment]
Fixed.
