### ISSUE TITLE
apache 2.2 is EOL, switch htaccess from 'append' to 'merge'

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#7341]
The INSTALL file says:

"If you are using Apache version 2.2.9 and later, in the .htaccess file
change the 'append' word to 'merge' for a more correct response. Keeping
as 'append' shouldn't cause any problems though changing to merge will 
eliminate the possibility of duplicate 'public' headers in Cache-control."

Apache 2.2.9 was released on 2008-06-14.  The last release of Apache 2.2 was 2.2.23 on 2017-07-11.  2.2 is now EOL.

Perhaps it's time to use use 'merge' in the default htaccess file and simplify the instructions.

**Comment by alecpl** [comment]
Might be.

**Comment by seanm** [comment]
Does that mean you would accept such a patch?

**Comment by chilek** [comment]
```
# cat /etc/centos-release 
CentOS release 6.10 (Final)
# rpm -q httpd
httpd-2.2.15-69.el6.centos.i686
```

https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule
So we are close to EOL for CentOS 6.

**Comment by chilek** [comment]
But roundcube requires PHP 5.4 which is present in RHEL/CentOS 7, so I think that apache 2.2 support is not needed anymore.

**Comment by seanm** [comment]
@chilek anyway, 2.2.15 > 2.2.9, so that's still fine.

**Comment by chilek** [comment]
@seanm: yes you are right.

**Comment by alecpl** [comment]
Done.
