### ISSUE TITLE
How to automatically rename the inserted pictures when forwarding or replying?

### ISSUE THREAD

**Issue by xian-lin** [roundcube/roundcubemail#7343]
How to automatically rename the inserted pictures when forwarding or replying?
Different languages may become garbled and become long file names , because  antivirus sometimes misjudge.

Examples:
Content-Type: image/png;
name*0*=US-SCII''%C3%83%C2%A6%C3%82%C2%AF%C3%AF%C2%BF%C2%BE%C3%83%C2%A8; name*1*=%C3%82%C2%A6%C3%82%C2%AA%C3%83%C2%A7%C3%82%C2%AF%C3%A2%E2%80%9A; name*2*=%C2%AC%C3%83%C2%A5%C3%AF%C2%BF%C2%BE%C3%82%C2%A1%C3%83%C2%A7%C3; name*3*=%A2%E2%82%AC%C2%B0%C3%A2%E2%82%AC%C2%A1%C3%83%C2%A5%C3%82%C2%B0;
name*4*=%C3%AF%C2%BF%C2%BE%C3%83%C2%A5%C3%82%C2%BA%C3%A2%E2%82%AC%C2%A2.p;
 name*5*=ng

 ClamAV:  contains Heuristics.Email.ExceedsMaxMIMEArguments

**Comment by alecpl** [comment]
If this is a feature request, then I'd say it's a rare case and I don't see it in the core. Write a plugin. You could try using `attachment_save` or `message_ready` hooks.

BTW, if that ClamAV rule is hit on the sample you provided, I'd call it a bug (or too strict rule, at least). I might be reading clamav code wrong, but isn't the rule supposed to be hit on >256 arguments? I see 7 here.
