### ISSUE TITLE
Feature Request: drag and drop for mail contact boxes in To, CC, BCC input fields

### ISSUE THREAD

**Issue by chilek** [roundcube/roundcubemail#7344]
As in subject. Would be great to have such feature. It's quite irritating when email address converts automatically to label/bar/box and then you cannot move it to another mail address field :(

**Comment by chilek** [comment]
Elastic skin.

**Comment by alecpl** [comment]
There's an old ticket for this - #5069.

**Comment by chilek** [comment]
> There's an old ticket for this - #5069.

And that does not work in Elastic skin.
Just try to copy existing address and paste in another address field. It's impossible.
The reason is simple: address labels/boxes are not copied to clipboard.

**Comment by chilek** [comment]
@alecpl how to instantly copy address from one input field to another one? Is there any way?
