### ISSUE TITLE
managesieve plugin: does not correct multiple 'forward' rules on the server

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7349]
I am testing a bit with the managesieve plugin. And I have noticed several times that I have multiple rules on the server. There can be numerous client side situations that can cause this. That is why this should be corrected server side.

* First of all, I would not use the name "Forwarding", better is "RCForwarding" or something unique to roundcube use. Forwarding is to general, and could also be used by another frontend. 
* Since the plugin only supports managing one rule, if multiple "Forward" are stored on the server, they should be replace by a single one.

```
# rule:[Forwarding]
if false # true
{
     redirect :copy "test2@test.com";
}
# rule:[Forwarding]
if false
{
     redirect :copy "test@test.com";
}
```
ps. same applies to out of office of course.

**Comment by alecpl** [comment]
I agree that there should be only one. And I'm pretty sure there's already some code that when you add/update forwarding/out-of-office it should use the existing one. So, that's something to verify.

Of course if some other client creates two, I'm not sure what we could do.

As for the rule name. I would not change that. Anyway, I don't think any other client supports our syntax for rules names.

**Comment by alecpl** [comment]
How did you end up with this duplicated rule? Do you have steps to reproduce this? I wasn't able. If this is Roundcube's fault we have a bug. If not, for me it will be a wontfix.

**Comment by alecpl** [comment]
I accidentally reproduced the issue while working on #7423. I'm not able to do this anymore after the fix. So, I consider this issue solved.

**Comment by f1-outsourcing** [comment]
> 
> 
> How did you end up with this duplicated rule? Do you have steps to reproduce this? I wasn't able. If this is Roundcube's fault we have a bug. If not, for me it will be a wontfix.

I was testing with switching between between dovecot servers, and trying to redirect users of one domainname  to different backend servers.
