### ISSUE TITLE
inconsistent comments about required length of `des_key`

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#7350]
`defaults.inc.php` says:

```
// This key is used for encrypting purposes, like storing of imap password
// in the session. For historical reasons it's called DES_key, but it's used
// with any configured cipher_method (see below).
$config['des_key'] = 'rcmail-!24ByteDESkey*Str';
```

but `config.inc.php.sample` says:

```
// this key is used to encrypt the users imap password which is stored
// in the session record (and the client cookie if remember password is enabled).
// please provide a string of exactly 24 chars.
// YOUR KEY MUST BE DIFFERENT THAN THE SAMPLE VALUE FOR SECURITY REASONS
$config['des_key'] = 'rcmail-!24ByteDESkey*Str';
```

If it must be exactly 24 bytes, it would be nice for `defaults.inc.php` to say so too.

If it can be longer, it would be nice to remove that comment.

I can make a patch, but I don't know which one...

**Comment by alecpl** [comment]
It's 24 for the default `cipher_method`, but since we have the method configurable it could be different length for different methods. I guess we could improve these comments.

**Comment by alecpl** [comment]
Fixed.
