### ISSUE TITLE
Elastic: (Mailvelope) Encrypt button sometimes hidden when in HTML editor

### ISSUE THREAD

**Issue by ryan77627** [roundcube/roundcubemail#7353]
This is when using the latest version of Mailvelope on the Elastic theme of Roundcube 1.4.4 [GIT 20200426.1547]. I am aware that emails cannot be created when in the HTML editor, they have to be in the plain text editor, but when you first compose an email, the encrypt button doesn't appear. When you switch to the plain text editor, it will appear. Finally, if you switch back to the HTML editor, it will gray itself out, like it should've started as.

**Comment by alecpl** [comment]
Confirmed.

**Comment by ryan77627** [comment]
Just implemented 1cff757, it does indeed fix the issue, thanks gurnec!

**Comment by alecpl** [comment]
I cherry-picked the fix mentioned above.
