### ISSUE TITLE
Cannot edit Sieve scripts when using Elastic skin

### ISSUE THREAD

**Issue by frerich** [roundcube/roundcubemail#7354]
When using RoundCube 1.4.3 and enabling the shipped 'Elastic' skin, I'm no longer able to edit my Sieve scripts. Clicking Settings -> Filters merely causes an error message to be shown which says

> FILE NOT FOUND
> The requested resource was not found!
> Please contact your server-administrator.
> Failed request: roundcube.froglogic.com/?_task=settings&_action=plugin.sieverules

The same operation works as expected with other skins. For instance, using the 'Larry' skin, selecting Settings -> Filters shows a plain text editor with my Sieve script.

**Comment by alecpl** [comment]
Looks like you're using sieverules plugin. Use managesieve instead.
