### ISSUE TITLE
Table 'filestore' already exists - upgrade to roundcube 1.4.4

### ISSUE THREAD

**Issue by PVasileff** [roundcube/roundcubemail#7355]
Hello, 

I start upgrade my roundcube instalation. Process complete with "All done." but I see:

Updating database schema (2018021600)... [FAILED]
ERROR: Error in DDL upgrade 2018021600: [1050] Table 'filestore' already exists

That is when I try to upgrade roundcube from 1.4.3 to 1.4.4 with:

`cd /tmp && wget -O roundcubemail-lastest.tar.gz https://github.com/roundcube/roundcubemail/releases/download/1.4.4/roundcubemail-1.4.4-complete.tar.gz && tar zxf roundcubemail-lastest.tar.gz && cd roundcubemail-*/ && ./bin/installto.sh /usr/share/roundcube`

**Comment by alecpl** [comment]
That's strange. Could you provide output of `SELECT * FROM system`? What was the initial version you installed? Did you do to it any upgrades before? Is it MySQL? What version?

**Comment by PVasileff** [comment]
Here the output:
```
MariaDB [roundcube]> SELECT * FROM system;
+---------------------------+------------+
| name                      | value      |
+---------------------------+------------+
| calendar-database-version | 2015022700 |
| roundcube-version         | 2016112200 |
| tasklist-database-version | 2014051900 |
+---------------------------+------------+
3 rows in set (0.002 sec)
```

**Comment by alecpl** [comment]
`2016112200` is not a correct version number for 1.4. It looks like 1.3, but you already have tables added later. So, maybe some previous update didn't bump the number. I suggest to verify your schema manually using files in `SQL/mysql` directory (starting from 2016112200.sql). And after that update the `roundcube-version` value to `2019092900`.
