### ISSUE TITLE
Roundcube displays a blank page on installation

### ISSUE THREAD

**Issue by ycharbi** [roundcube/roundcubemail#7359]
# Description of the problem
Since at least the 1.3.x branch (still effective with version 1.4.4), installing Roundcube via tar.gz displays nothing more than a blank page. No error message is displayed, even with a `display_error` to `on` in `php.ini`.
It's very frustrating and must probably slow down the adoption of the tool to a lot of administrators who find themselves blocked without any possibility of moving forward.

# Replication of the problem
Here are the steps I take from a Debian Buster:

## Installation of dependencies

```
apt update
apt install apache2 php
```
_In passing, finding the right dependencies to install is part of the archaeological expedition (the use of Composer is not necessarily desired.). The project would benefit from documenting this clearly for the various major distributions._

(_Here are the dependencies to be installed to solve the problem_: `php-xml php-mbstring php-intl php-zip php-pear zip php-gd sqlite3 php-sqlite3 php-imagick`). I'm not install them up for the demonstration.

## Download and install files
```
wget https://github.com/roundcube/roundcubemail/releases/download/1.4.4/roundcubemail-1.4.4-complete.tar.gz
tar xzvf roundcubemail-1.4.4-complete.tar.gz -C /var/www/
cd /var/www/
ln -s roundcubemail-1.4.4/ roundcube
chown -R www-data:www-data roundcube*
```
## Configure PHP
`echo "date.timezone = Europe/Paris" >> /etc/php/7.3/apache2/php.ini`

## Configure Apache2
```
cat >> /etc/apache2/sites-available/roundcube.conf << _EOF_
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/roundcube

        ErrorLog ${APACHE_LOG_DIR}/rcube_error.log
        CustomLog ${APACHE_LOG_DIR}/rcube_access.log combined
</VirtualHost>
_EOF_
```
```
a2dissite 000-default.conf
a2ensite roundcube.conf
systemctl restart apache2.service
```

## Test
Type the IP address in Firefox and face a blank page without any indication (even if you activate PHP's `display_error`).

# Motion for a resolution
Being faced with a blank page (even in its source code) does not help to solve the problem and is not a normal behavior.
I think it is important to work on this. For example, by foolishly displaying PHP errors or, at best, guiding the administrator by displaying more precise indications.

Another thing, it would be good to add an automatic redirection to the install page because even with the right dependencies, you end up on the same blank page if you don't enter http://IP/installer manually, which can fool many people.

**Comment by alecpl** [comment]
It would be good to know what is the reason to the failure. There should be some error in logs (Roundcube log or apache log).

**Comment by ycharbi** [comment]
Here are the contents of `rcube_error.log`:

`[Fri May 01 12:24:29.955943 2020] [php7:error] [pid 7703] [client 192.168.150.24:40232] PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/bootstrap.php:86\nStack trace:\n#0 /var/www/roundcubemail-1.4.4/program/include/iniset.php(62): require_once()\n#1 /var/www/roundcubemail-1.4.4/index.php(40): require_once('/var/www/roundc...')\n#2 {main}\n  thrown in /var/www/roundcubemail-1.4.4/program/lib/Roundcube/bootstrap.php on line 86`

**Comment by alecpl** [comment]
So, missing php-mbstring. I agree that an installer could be more user-friendly, but it was never intended to be that "inteligent". It's a simple tool, more a setup tool, not a real installer. I think it's not worth the effort to try to improve that.
