### ISSUE TITLE
recipient auto completion sometimes blocks database

### ISSUE THREAD

**Issue by manfredu** [roundcube/roundcubemail#7360]
Since several month we have a very strange issue with mail composing. After typing the first letter in the recipient input field usually the drop down lists opens and gets filtered by further typing. In this case everything is fine and as it should be.

But sometime the dropdown box does not open and a message "Suche läuft..." (Searching...) appears. Then we have a problem. The system is blocked, the send button does not work and even other users see a message "Refreshing...". 

The blocking must happen on database level because even nextcloud which uses the same mysql instance is blocked. After several minutes the system recovers. Restarting the web server resolves the issue immediately.

We experience this since the update from RC 1.1.0 to RC 1.4.1, which was a complete new installation.

**Comment by manfredu** [comment]
We are using the carddav plugin just in case this could have an impact.

**Comment by alecpl** [comment]
Does it happen with all plugins disabled?

**Comment by manfredu** [comment]
OK, I have disabled all plugins, we will watch what happens and let you know. Since I do not know what exactly triggers the issue and how to reproduce it, we have to wait and see...

**Comment by manfredu** [comment]
Without the carddav plugin the behaviour is different. The dropdown does not open because there are no recipients available. Therefore we have to enter all addresses manually. Nevertheless we will test this for a while to see if the issue occurs... If this is not the case I suggest to enable only the carddav plugin and test this setup...

**Comment by alecpl** [comment]
Sure, my point is this is a plugin we do not support.

**Comment by trasherdk** [comment]
Shouldn't this be investigated on the mysql instance?
The log-file should tell something about what query is blocking.

**Comment by manfredu** [comment]
Enabling the carddav plugin and leaving all others disabled is enough to get the issue. I also thought about investigating on the mysql server side but was not really successful so far.

**Comment by manfredu** [comment]
Maybe it has something to do with the fact that both roundcubes carddav plugin and nextcloud use a database on the same mysql server instance. The carddav plugin syncronizes with the nextcloud contacts...

**Comment by alecpl** [comment]
I'm closing this. If you have prove/more details it is a Roundcube not plugin issue them we'll reopen.

**Comment by manfredu** [comment]
Am 23.05.2020 10:46, schrieb Aleksander Machniak:

> I'm closing this. If you have prove/more details it is a Roundcube not plugin issue them we'll reopen.

What I found out in the meantime is that this happens only with the
classic skin. 

Regards
Manfred 

> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/7360#issuecomment-633008705
[2]
