### ISSUE TITLE
v1.4.4 changes the way markasjunk calls its drivers' init() method

### ISSUE THREAD

**Issue by gurnec** [roundcube/roundcubemail#7361]
In v1.4.3, inside the `init()` method of a markasjunk driver, `rcmail::get_instance()->output->type` would always be `'html'`. In v1.4.4 this has changed. This means that drivers which assumed it would be `'html'` can fail. The demo `jsevent.php` driver is one such example:

https://github.com/roundcube/roundcubemail/blob/aadb13e25f73d783f731a99f9b9c2ea43bb10c79/plugins/markasjunk/drivers/jsevent.php#L68-L69

When `->output->type` is `'json'`, it fails with the stack trace below since that `->output` as no `add_script()` method.

<details><summary>Stack trace</summary>

```
Apr 30 17:03:22 hostname roundcube: PHP Fatal error:  Uncaught Error: Call to undefined method rcmail_output_json::add_script() in /path/roundcubemail-1.4.4/plugins/markasjunk/drivers/jsevent.php:69
Stack trace:
#0 /path/roundcubemail-1.4.4/plugins/markasjunk/markasjunk.php(341): markasjunk_jsevent->init()
#1 /path/roundcubemail-1.4.4/plugins/markasjunk/markasjunk.php(130): markasjunk->_init_driver()
#2 /path/roundcubemail-1.4.4/program/lib/Roundcube/rcube_plugin_api.php(100): markasjunk->init()
#3 /path/roundcubemail-1.4.4/program/include/rcmail.php(137): rcube_plugin_api->init(Object(rcmail), 'mail')
#4 /path/roundcubemail-1.4.4/program/include/rcmail.php(78): rcmail->startup()
#5 /path/roundcubemail-1.4.4/index.php(43): rcmail::get_instance(0, NULL)
#6 {main}
  thrown in /path/roundcubemail-1.4.4/plugins/markasjunk/drivers/jsevent.php on line 69
```
</details>

I think this happened in [this commit here](https://github.com/roundcube/roundcubemail/commit/1bc41d3a5fa4a0de0e61792ca4a20c8107d2543b#diff-28d531a4099e29b9d53dea712bee4769L126-R130) when the call to initialize the driver was moved outside the end of that preceding `if` block. If I move it back up, it seems to revert to the previous behavior.

I'm not sure if this is even a bug, and if it is, if the above fix is correct. Pinging @johndoh since he authored that commit.

Thanks!

**Comment by johndoh** [comment]
try adding an output type check into the init() method of the jsevent driver.
```diff
--- a/plugins/markasjunk/drivers/jsevent.php
+++ b/plugins/markasjunk/drivers/jsevent.php
@@ -34,6 +34,10 @@ class markasjunk_jsevent

     public function init()
     {
+        $rcmail = rcmail::get_instance();
+        if ($this->rcube->output->type != 'html')
+            return;
+
         $js_addition_spam_folders = json_encode($this->addition_spam_folders);
         $js_suspicious_folders    = json_encode($this->suspicious_folders);

```
The purpose of moving the init() call in the markasjunk class is to ensure a driver's init() method is always called when the driver is used.

**Comment by gurnec** [comment]
@johndoh Thanks for the quick response. Leaving this open to be closed by your PR.

**Comment by alecpl** [comment]
Thanks. Fixed.
