### ISSUE TITLE
'dovecot' method broken in password plugin for some hash schemes

### ISSUE THREAD

**Issue by dodexahedron** [roundcube/roundcubemail#7362]
When using the 'dovecot' method in the password plugin, it complains that the encryption function was not found, when using the argon2i (and likely certain other) hash schemes.

The problem lies in the preg_match comparison, which simply checks for false, which is an incorrect usage, according to the php documentation, as it can return a value that evaluates to false, even if a match was found.

A viable and likely more efficient solution is a call to mb_strpos, with a comparison to 0, since the method should be at the start of the string.

`if(!(mb_strpos($crypted,'{' . $method . '}') === 0)) {
                return false;
            }`

Pull request with this fix will be in shortly.

**Comment by alecpl** [comment]
Where did you find that preg_match() result description? It does not sound right. What is the real issue here?

**Comment by alecpl** [comment]
Ah, I think I know where you get that. But.... we're checking for non-falsy value, it does not matter it's `0` or `false`.

**Comment by dodexahedron** [comment]
It fails reliably for argon2i as described in the issue.




PHP documentation describes the behavior of preg_match with a colored warning box.




Get Outlook for Android







On Fri, May 1, 2020 at 1:38 AM -0700, "Aleksander Machniak" <notifications@github.com> wrote:















Ah, I think I know where you get that. But.... we're checking for non-falsy value, it does not matter it's 0 or false.

**Comment by dodexahedron** [comment]
When I am at a terminal I can access that system from, tomorrow, I will provide sample configuration that fails.

**Comment by dodexahedron** [comment]
For the life of me, I can't replicate the behavior any more, with the code in isolation, which is driving me crazy.
I had 100% failure, last night, to the point I bothered to do this, and I had tried with multiple inputs for both password and method. 🤦‍♂️

I'm closing this, for now. If I manage to replicate it again and can isolate it, I'll re-open.
