### ISSUE TITLE
Threads with flagged messages are not highlighted

### ISSUE THREAD

**Issue by dboehmer** [roundcube/roundcubemail#7366]
I use Roundcube 1.4.4 and often flag messages to review them later on.

Unfortunately in threaded inbox view threads that contain flagged messages (not the thread’s root message) are displayed exactly the same as other threads.

It seems like this had been addressed before in #5013 but that feature got broken in the meantime.

**Comment by alecpl** [comment]
Looks like a regression. The `flaggedroot` class is added to the root message properly, but there's no indication of that. It works in Classic skin, but not in Larry and Elastic.

**Comment by alecpl** [comment]
Fixed.

**Comment by dboehmer** [comment]
I just updated to the recently released version 1.4.5.

I see there's a grey flag next to threads with flagged messages. Sorry but I find this way too unremarkable.

How about showing a red flag next to the black subject and sender? In contrast the for flagged message itself everything is shown in red, even the "unread" indicator.

In my opinion a thread with a flagged message, when displayed collapsed, is in its entirety nearly as alerting as the flagged message itself. There should be only a slight difference in style to indicate it's not the thread's root message that is flagged.
