### ISSUE TITLE
500 Error with wrong password on login 1.4.4

### ISSUE THREAD

**Issue by robetus** [roundcube/roundcubemail#7374]
Just installed roundcube 1.4.4 yesterday and everything is working fine but if the user gives an incorrect password with URL task: /?_task=login there is a 500 error. I just wanted to know if someone can recreate this and offer a solution. The email needs to be a valid email but the password needs to be incorrect and the error is shown every time. If you use an invalid email an error is shown on the page as normal.

**Comment by bes-internal** [comment]
enable in .htaccess:
```
php_flag    display_errors  Off
php_flag    log_errors      Off
```
and report an error

**Comment by robetus** [comment]
I enabled display errors but it's not showing any. I confirmed the php display errors is on. I have something from the nginx logs but I don't see anything that would help:

`"POST /rc/?_task=login HTTP/2.0" 500 0 "https://mail.mydomain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"`

/rc/ is the roundcube directory.

**Comment by bes-internal** [comment]
Try:

0. check all steps from https://github.com/roundcube/roundcubemail/blob/master/INSTALL , check dependecy by installer or manually
1. if this php-fpm check their error logs 
2. if this apache php installation then looks like syntax error... Try in root dir with roundcube 
`$ find -iname '*php' -exec php {} \; 2>&1 |grep syntax`
 This is run every php file and find 'PHP Parse error:  syntax error...' messages

**Comment by robetus** [comment]
I reinstalled and it's working now. Thank you for your help.
