### ISSUE TITLE
Contact addresses are not inserted from LDAP contact list

### ISSUE THREAD

**Issue by rtheys** [roundcube/roundcubemail#7376]
Hi,

We are running roundcube 1.4.4 on PHP 7.3 on apache. We have configured LDAP address books in config.inc.php.

If I go to contacts, the address book works: see/find entries. I can click on the e-mail address and a new message is created with the address filled in.

If I compose a new message (without selecting a contact), and then click the icon to open the address book (next to the To input field), I can search contacts and select them. But when I click the "Insert" button, they are not added to the To list of the message. Nothing happens.

This only occurs for addresses in an LDAP address book. The entries from the personal address book don't have this problem.

Regards,
Rik

**Comment by alecpl** [comment]
Could you provide your `ldap_public` config?

**Comment by rtheys** [comment]
Hi,

We have two LDAP entries. At first we had both of them configured as the second one below. I then changed the first one to use a fieldmap instead. Both don't work. It used to work with our previous version 1.2.

Regards,
Rik

$config['ldap_public']['personeel'] = array(
  'name'          => 'personeel',
  'hosts'         => array('ldap.esat.kuleuven.be'),
  'port'          => 389,
  'use_tls'       => false,
  'user_specific' => false,
  'base_dn'       => 'ou=People, dc=esat, dc=kuleuven, dc=be',
  'bind_dn'       => '',
  'bind_pass'     => '',
  'writable'      => false,
  'LDAP_Object_Classes' => array("top", "inetOrgPerson"),
  'required_fields'     => array("cn", "sn", "mail", "givenName"),
  'LDAP_rdn'      => 'mail',
  'ldap_version'  => 3,
  'search_fields' => array('uid', 'cn'),
  'fieldmap'      => array(
    'name'      => 'cn',
    'email'     => 'mail:*',
    'surname'   => 'sn',
    'firstname' => 'givenName',
  ),
  'sort'          => 'cn',
  'scope'         => 'sub',
  'filter'        => '(&(esatPrimaryMail=*)(!(esatTag=student)))',
  'fuzzy_search'  => true);
  
  
$config['ldap_public']['studenten'] = array(
  'name'          => ' studenten',
  'hosts'         => array('ldap.esat.kuleuven.be'),
  'port'          => 389,
  'use_tls'       => false,
  'user_specific' => false, 
  'base_dn'       => 'ou=People, dc=esat, dc=kuleuven, dc=be',
  'bind_dn'       => '',
  'bind_pass'     => '',
  'writable'      => false,
  'LDAP_Object_Classes' => array("top", "inetOrgPerson"),
  'required_fields'     => array("cn", "sn", "mail"),
  'LDAP_rdn'      => 'mail',
  'ldap_version'  => 3,
  'search_fields' => array('uid', 'cn'),
  'name_field'    => 'cn',
  'email_field'   => 'mail',
  'surname_field' => '',
  'firstname_field' => '',
  'sort'          => 'cn',
  'scope'         => 'sub',
  'filter'        => 'esatTag=student',
  'fuzzy_search'  => true);

**Comment by alecpl** [comment]
This `'email' => 'mail:'` does not look right. Should be `'email' => 'mail'` or `'email' => 'mail:1'` or `'email' => 'mail:*'`.

Are there any errors in browser console (when you click Insert button)? Does it work in other browsers?

**Comment by rtheys** [comment]
Hi,

I think the * must have been removed by the copy paste as it does indeed say:
`'email' => 'mail:*'`

I've tried both firefox and chromium and the results are the same. No additional errors are logged when I click the insert button, but there are some errors regarding the tb_labels plugin I have enabled. I will disable that plugin to see if it makes a difference.

Rik

**Comment by rtheys** [comment]
Hi,

I've disabled the tb_labels plugin, but it doesn't make any difference. I've also tried it with the larry skin and it also doesn't work.

Regards,
Rik

**Comment by rtheys** [comment]
Hi,

I've noticed that when using the larry skin, the +To field does not become active when I select a contact.

I've also now discovered it does not happen with all my contact lists! From some lists, I can select contacts and use the buttons.

When the name of the address book does NOT contain spaces, the error does not happen.
I've now changed my config from:
`$config['ldap_public']['ESAT personeel'] {
'name' => 'ESAT personeel'
...`

to 
`$config['ldap_public']['ESAT_personeel'] {
'name => 'ESAT_personeel'
...`

and then the contacts can be added from that contact list

Is this a known limitation?

Regards,
Rik

**Comment by alecpl** [comment]
Yes.
```
// In order to enable public ldap search, configure an array like the Verisign
// example further below. if you would like to test, simply uncomment the example.
// Array key must contain only safe characters, ie. a-zA-Z0-9_
$config['ldap_public'] = array();
```
