### ISSUE TITLE
PHP Error: no decode delegate for this image format `TMP'

### ISSUE THREAD

**Issue by lutel** [roundcube/roundcubemail#7379]
Hi,

I'm getting lots of these errors in error.log, I haven't got any user complains on image display, but anyway maybe this should be corrected?

> [08-May-2020 11:09:51 +0200]: <6lh3p82d> PHP Error: no decode delegate for this image format `TMP' @ error/constitute.c/ReadImage/562 in /var/www/localhost/htdocs/roundcube/program/lib/Roundcube/rcube_image.php on line 168 (GET /?_task=mail&_action=get&_mbox=INBOX&_uid=7112&_token=m06XQSwDN9BcoAAOmsTLBYNhuu8J3Zj6&_part=4&_embed=1&_mimeclass=image&_thumb=1)

**Comment by alecpl** [comment]
This happened on an attachment thumbnail generation.

The message comes from the PHP's Imagick class. Either there's something wrong with PHP or system, or the processed image is faulty. Some sources mention that it could also be non-existing file.

Anyway, I don't see we could do any better here.
