### ISSUE TITLE
Roundcube does not invalidate session when credentials change during active session

### ISSUE THREAD

**Issue by GermanCoding** [roundcube/roundcubemail#7381]
Quick setup overview:

- I'm using a database for authentication
- Dovecot is configured to authenticate all IMAP logins against that database
- Roundcube connects to the Dovecot IMAP server and passes through credentials
- There is an external authentication program that may change credentials, by modifying the database

Steps to reproduce:

1. Login to Roundcube, using valid credentials.
2. On the external authentication program, change the credentials of the user that just logged in.
    (This causes dovecot to also drop any currently established IMAP connections for that user)
3. As soon as the user tries to interact with anything within Roundcube, Roundcube tries to rebuild the IMAP session, but fails because dovecot will now reject the previously good credentials.
4. Roundcube now shows two errors messages ("connection to storage server failed" and "Server Error: AUTHENTICATE PLAIN: Authentication failed") but does **not** invalidate the user session - they can still roam around the site, which causes roundcube to hammer dovecot with invalid logins - which seems to  bypass even the `login_rate_limit`, potentially causing dozens (or even hundreds) of failed logins if the user refreshes their browser window a couple of times.
5. Roundcube happily reports all these "failed" logins, eventually causing my Fail2Ban to kick in and ban the (pretty much) innocent user

What Roundcube should instead do, is to invalidate the currently active user session as soon as the IMAP server reports "Authentication failed" and send them back to the login page.

Right now, the user needs to manually press "Logout" on their broken session in order to get Roundcube working again.

I've attached a screenshot that shows the described state. Again, this state persists and the user will not get logged out automatically.

![roundcube_failure](https://user-images.githubusercontent.com/4279661/81499249-62642200-92ca-11ea-8c25-8dbf3d806faf.png)

As for logging, roundcube logs the failed logins like this (frequently):

`[10-May-2020 14:28:21 +0200]: <m04im4ah> IMAP Error: Login failed for [user] against [server] from [IP] . AUTHENTICATE PLAIN: Authentication failed. in /var/www/vhosts/mail/httpdocs/program/lib/Roundcube/rcube_imap.php on line 200 (POST /?_task=mail&_action=refresh)`

PS: I'm running Roundcube Webmail 1.4.4

**Comment by johndoh** [comment]
dupe #6474

**Comment by GermanCoding** [comment]
As I guess this is a `wontfix` then, I've implemented a workaround that works for me. I'm posting the code snippet here in case others find it useful:

I've programmed my external auth program to call a python script that gets the username and deletes any matching sessions from roundcube database, so that roundcube will forcibly invalidate the users session.

`roundcube_logout.py`

```
#!/usr/bin/env python3
import base64
import re
import pymysql.cursors
import sys

email = str(sys.argv[1]) # First command line argument must be the account name we will logout
connection = pymysql.connect(host='127.0.0.1',
                             user='<user>',
                             password='<password>',
                             db='roundcubemail',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
try:
    print("Searching roundcube sessions for " + email)
    with connection.cursor() as cursor:
        sql = "SELECT `sess_id`, `vars` FROM `session`"
        cursor.execute(sql)
        results = cursor.fetchall()
        for result in results:
           data = str(base64.b64decode(result['vars']))
           rematch = re.search(r';username\|s:[0-9]*:"' + re.escape(email)  + '";', data, flags=re.MULTILINE)
           if rematch != None:
              print("Found session " + result['sess_id'])
              with connection.cursor() as cursor:
                 sql = "DELETE FROM `session` WHERE `sess_id` = %s"
                 cursor.execute(sql, result['sess_id'])
                 connection.commit()
finally:
    connection.close()
```
