### ISSUE TITLE
Problem forwarding email with inline PDF attachment

### ISSUE THREAD

**Issue by TobiasGrave** [roundcube/roundcubemail#7382]
When forwarding an email containing a PDF file as an inline attachment ("Content-Disposition: inline"), the PDF attachment is missing in the forwarded mail.

Roundcube Version is 1.4.4

**Comment by alecpl** [comment]
Inline for pdf does not make much sense. Could you provide the full message structure?

**Comment by daCaPo** [comment]
Same issue here, with e-mails sent using Apple mail.

**Comment by daCaPo** [comment]
By the way: Forwarding the e-mail as attachment seems to be a viable workaround.

**Comment by TobiasGrave** [comment]
The emails are created by the iOS app Genius Scan that generates PDF files from camera images and allows to send them via email using the stock iOS mail app. This app is commonly used in conjunction with a document management system that usually expects files in PDF format.

The iOS mail app can handle inline PDF attachments and displays the PDF content like an inline JPEG images, so it does make sense to use inline PDF in this case.

I have attached an example mail.
[[Scan] 2020-05-19 13 07.zip](https://github.com/roundcube/roundcubemail/files/4650080/Scan.2020-05-19.13.07.zip)

**Comment by alecpl** [comment]
Fixed.
