### ISSUE TITLE
LDAP/new_user_identity with multiple logins for the same user

### ISSUE THREAD

**Issue by moqmar** [roundcube/roundcubemail#7384]
On our mailserver, people can either log in using their username (e.g. jdoe), or with their email address (e.g. jane.doe@example.org). This works great with basically every service except for Roundcube. Both users have the same identity (using the `new_user_identity` plugin), but not the same account in the database - there are two accounts in the `users` table, each of them has their own personal address book, and each of them has his own settings (like theme or additional identities).

In my opinion, it would make sense to use the [`acl_users_field`](https://github.com/roundcube/roundcubemail/blob/7fa5180fcc4b16126314c1444e303bc05da20fd4/plugins/acl/acl.php#L743) as the identifying field for the database if LDAP is set up - or is there an option for that which I didn't see?

**Comment by alecpl** [comment]
Maybe `user_aliases` option would help here. If not you'd have to write a plugin.
