### ISSUE TITLE
attachment problem

### ISSUE THREAD

**Issue by druger2006** [roundcube/roundcubemail#7385]
Another user sent me an email via Outlook 2016, but the name of the attachment was changed. I received a 'Часть 2.bin' file instead of 'km190822_1412.zzz' 

![image](https://user-images.githubusercontent.com/65233374/81696503-a55dfb00-946c-11ea-8105-fe3328e747a8.png)

![image](https://user-images.githubusercontent.com/65233374/81696285-5fa13280-946c-11ea-89b4-44daf2a98d6d.png)

**Comment by alecpl** [comment]
Could you provide a full message source? You can remove the content, but keep the structure and headers.

**Comment by druger2006** [comment]
Here is it.

[message source.zip](https://github.com/roundcube/roundcubemail/files/4616165/message.source.zip)

**Comment by alecpl** [comment]
Works for me. What IMAP server? What Roundcube version? What PHP version? Did you try with disabled all plugins?

**Comment by druger2006** [comment]
IMAP - dbmail 3.2.3
PHP - 7.2.11 
Roundcube - 1.4.4
Yes, we disabled all plugins, but it didn't help.

**Comment by alecpl** [comment]
This might be DBMail issue. Enable imap_debug and check what BODYSTRUCTURE it returns. Also, you could test with git-master which contains some fixes that might be related.

**Comment by druger2006** [comment]
We don't have this problem with using standard Outlook software (v2010 and v2016).

**Comment by alecpl** [comment]
Fat clients usually parse messages themselves. Roundcube depends on imap server.

**Comment by alecpl** [comment]
No feedback.

**Comment by druger2006** [comment]
DBMail has been updated their IMAP Server, so we don't have any problems with it right now.
Thank you for your help.
