### ISSUE TITLE
encoding issue writing HTML email

### ISSUE THREAD

**Issue by dropfree** [roundcube/roundcubemail#7386]
Hi, I face the issue that I have encoding problems writing a HTML email.

I just put "https://roundcube.net/" in an email, save it as draft, go to the draft and see:

`--=_4a0360e29bab6b28e8d0094dd0d7e5de
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
format=flowed

https://roundcube.net/
--=_4a0360e29bab6b28e8d0094dd0d7e5de
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<p>https://roundcube.net/</p>
</body></html>

--=_4a0360e29bab6b28e8d0094dd0d7e5de--`

I am using 1.4.4 on opensuse leap 15.1
I had the same issue with 1.4.3, but I think it was not there before. But I cannot test that any more now.

**Comment by alecpl** [comment]
I'm unable to reproduce. Try with disabled all plguins. Try using different skins/browsers. Is this installed from the vanilla release or packaged by Opensuse?

**Comment by dropfree** [comment]
For me it is the same behaviour in different browsers (Firefox, Chrome) and different skins (elastic, classic). It is an opensuse package server:php:applications/roundcubemail

**Comment by alecpl** [comment]
This might be caused by incompatible dependencies.  What Mail_Mime version? DO you have /vendor folder in Roundcube dir or is it using system-wide PEAR libraries?

**Comment by dropfree** [comment]
It is php 7.2.5 and mail_mime 1.10.7
There is a /vendor folder in roundcube dir (incl PEAR) with files - no links.

**Comment by alecpl** [comment]
I have no clue. Any errors in log?

**Comment by dropfree** [comment]
no info in the logs. Neither roundcube, nor apache2.
Maybe I play around a little bit with php.
Thank you!

**Comment by alecpl** [comment]
Any news on this? If you have some more info we'll reopen the ticket.
