### ISSUE TITLE
SMTP Error (554): sending to remote adresses (relaying) is not allowed

### ISSUE THREAD

**Issue by mcnesium** [roundcube/roundcubemail#7387]
I am trying to run Roundcube Webmail 1.4.4 in a Docker environment ([see here for Dockerfile etc.](https://gitea.com/mcnesium/docker-roundcube)) with the [identity-smtp](https://plugins.roundcube.net/packages/elm/identity_smtp) plugin, which allows me to also send mail from multiple mail accounts (identities).  

Problem: sending mails does only work for recipients whose domain name is also handled by the same SMTP-server that I am trying to send mail to. For any other recipient, the following error message appears:  

> SMTP Error (554): Failed to add recipient "mail@recipient.tld" (Refused. Sending to remote addresses (relaying) is not allowed.)

I am not sure whether that is a configuration error or a bug within one of the components. For the plugin [I already asked here](https://github.com/deflomu/Roundcube-SMTP-per-Identity-Plugin/issues/19), but no response there. In another non-dockerized setup and Roundcube Webmail 1.3.10 this plugin is included and works very well. So either this is an issue with v1.4.x or a configuration error.  

How can I fix this? Any help?

----
This is a copy of [my post in the roundcube forum](https://www.roundcubeforum.net/index.php/topic,28867.0.html) which sadly does not seem to be very frequented anymore.

**Comment by alecpl** [comment]
Looks like a config issue. Enable smtp_debug to see more details.

**Comment by mcnesium** [comment]
> Enable smtp_debug to see more details.

How and where do I do that?

**Comment by trasherdk** [comment]
This is a server side configuration problem.
The `mydomain.de`is not recognized as a local domain, and not allowed to do stuff on that server.
Read the documentation for whatever server you are using. Look for `relaying denied`.

Long version of `RTFM`.

**Comment by mcnesium** [comment]
If this is really a configuration issue with the SMTP server, I wonder why it works with Roundcube v1.3.10 and below

**Comment by mcnesium** [comment]
I found out that it works, when commenting the encryption of the passwords [here](https://github.com/deflomu/Roundcube-SMTP-per-Identity-Plugin/blob/56e86542ab5b88f544c2a96542a94e970a9b9243/identity_smtp.php#L78-L80) and putting just `$smtpSettings['smtp_pass'];` instead of the decrypting [here](https://github.com/deflomu/Roundcube-SMTP-per-Identity-Plugin/blob/56e86542ab5b88f544c2a96542a94e970a9b9243/identity_smtp.php#L251). So there must be something wrong with the password en- or decryption.

I know this third party plugin is not actively maintained by Roundcube devs, but it seems to be abandoned, and so I am looking for help to be able to fix this myself.

Plus, I wonder how else we are supposed to make use of multiple identities feature in Roundcube, if we are not able to send mails through a separate SMTP server for each identity.

Who can help?
