### ISSUE TITLE
Error while downloading attachments

### ISSUE THREAD

**Issue by h2lsoft** [roundcube/roundcubemail#7388]
Hi,

we have problems for donwloading attachment (file size displayed is 3.6 Mo but it's 2.8 Mo real)
so when we tray to download the file, browser is looping for downloading.

Here our environment :

os : linux 
roundcube version : 1.1-git
browser : chrome, firefox, ie same problem

**plugins :** 

- redundant_attachments	1.0
- zipdownload	3.0
- odfviewer	0.3
- additional_message_headers	1.2.0
- acl	1.5
- archive	2.3
- calendar	1.1.0
- managesieve	7.2
- newmail_notifier	0.7
- password	3.5
- tasklist	1.1.0

**Comment by h2lsoft** [comment]
Fixed by comment this line in get.inc line 364 :

if ($size = (int)$part->d_parameters['size']) {
						// H2LSOFT> @PATCH> 13/05/2020
                        // header("Content-Length: $size");
                    }

The bug is $part->d_parameters['size'] will return incorrect size

**Comment by alecpl** [comment]
Just upgrade.

**Comment by h2lsoft** [comment]
Thanks, but the app is in production and use roundcube Kolab version.
