### ISSUE TITLE
Add RFC2231 support in rcube_mime_decode

### ISSUE THREAD

**Issue by iammartinbelobrad** [roundcube/roundcubemail#7390]
Hi Guys,
We have a problem with opening emails from several of our clients. Preview panel show only blank body:

**Here is two anonymized sample emails:** [samples.zip](https://github.com/roundcube/roundcubemail/files/4634761/samples.zip)

![screen](https://user-images.githubusercontent.com/212016/82058997-c1a8a480-96c5-11ea-9a66-4577f7d88ef4.jpg)

Thank you

**Comment by alecpl** [comment]
What version? Try with all plugins disabled. Check error log for errors.

**Comment by iammartinbelobrad** [comment]
Version is 1.4.0
Yes, i check logs and try debugging. But i dont know where problem is.

**Comment by alecpl** [comment]
Is this maybe the same issue as in #7369 ?

**Comment by alecpl** [comment]
I just noticed that both sample messages contain unusual Content-Type header syntax:
```
Content-Type: multipart/alternative; boundary*0*=us-ascii''%3D_76633fc9322e0ce47eb0f8ba%3D2592dd06-45ae-50b0-b5f;
 boundary*1*=7-f68c933d5e12_%3D
```
This might cause an IMAP server to parse the email incorrectly. So, what IMAP server? Also, enabled imap_debug and check BODYSTRUCTURE response in the log.

**Comment by alecpl** [comment]
Done.
