### ISSUE TITLE
Filter Option for Sent Mail Not Working

### ISSUE THREAD

**Issue by lijibals** [roundcube/roundcubemail#7391]
I want to send a copy of all outgoing emails to one email ID of the same domain. But it's not working now. It world be greatful if anyone check this and revert.

**Comment by alecpl** [comment]
There's no such feature in Roundcube. I have no idea what are you talking about.

**Comment by trasherdk** [comment]
He's talking about a server-side BC of all outgoing mail. While being highly questionable at best, it has absolutely nothing to do with a client side software.
