### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable on ... rcube_imap_generic.php on lin 1766

### ISSUE THREAD

**Issue by topoldo** [roundcube/roundcubemail#7392]
Hi all.
I have my roundcube "errors.log" file which is filled in almost every second/minute with a copy of the string reported in the subject of this message.
Similar situations were also already reported (and solved) for other pieces of code inside roundcube where php 7.2 is used.

In my case the problem refers to program/lib/Roundcube/rcube_imap_generic.php file at line 1766.
I am currently running Roundcube stable 1.4.4 version, downloaded from its site in its "complete" distribution on a Ubuntu 18.04 LTS server. My PHP is 7.2.

Any help/temporary patch waiting for a full resolution of the problem at code level is highly appreciated.

TIA
Topoldo

**Comment by alecpl** [comment]
Looks like your IMAP server might be sending empty response to `ID` command. Could you enable imap_debug and provide that part of the log?

Workaround: `$config['imap_disabled_caps'] = array('ID');`

**Comment by alecpl** [comment]
Fixed.
