### ISSUE TITLE
Clarification regarding session &password storage

### ISSUE THREAD

**Issue by dfbm** [roundcube/roundcubemail#7395]
The sample config contains
```
// This key is used to encrypt the users imap password which is stored
// in the session record. For the default cipher method it must be
// exactly 24 characters long.
// YOUR KEY MUST BE DIFFERENT THAN THE SAMPLE VALUE FOR SECURITY REASONS
$config['des_key'] = 'rcmail-!24ByteDESkey*Str';
```

Does that mean that the database will contain the encrypted passwords of all users that are currently logged in and thus an admin would be able to decrypt all user passwords using that above des_key?
Is another storage (e.g. Browser Cookie) possible?

**Comment by alecpl** [comment]
Yes, that's right. We need the password for IMAP/SMTP for almost every request. So, storing it in browser and then passing with every request will not make it much better.

**Comment by dseomn** [comment]
@alecpl I agree that the server needs frequent access to the password during an active user session, so there isn't that much of a difference between storing the encrypted password in a cookie vs in the database in that regard. However, I think there are two things that make it significantly less secure to store the encrypted password in the database:

1. If you back up both the roundcube config file and the database, your backups have everything needed to access cleartext passwords. I suspect many people would backup config files and databases without thinking much of it, so this seems really non-ideal. (As a workaround, I'm planning to have one config file with no secrets that includes a separate config file with only the secret. I'll probably generate that second config file periodically in a cron job, with a new random secret each time, but I haven't fully analyzed the implications of that yet.)
2. If somebody compromises the server, they currently can get access to all the passwords in the database. (Possibly including deleted rows too, if those haven't been deleted from the database server's own files yet, or if they're in unused parts of the filesystem's underlying block device.) If the encrypted passwords were stored in cookies, they'd only get access to the passwords of users actively using roundcube during the attack.
