### ISSUE TITLE
Unable to list keys! with roundcube 1.4.4 and enigma plugin

### ISSUE THREAD

**Issue by guizmoau** [roundcube/roundcubemail#7396]
On a fresh install of roundcube 1.4.4 and activation of enigma plugin.

When in settings PGP Keys, I have a red message error saying
"Unable to list keys! Internal server error"

My /var/log/rouncube/errors.log shows :
<vlfa59bl> PHP Error: Enigma plugin: Unknown error getting keys. Please use the 'debug' option when creating the Crypt_GPG object, and file a bug report at http://pear.php.net/bugs/report.php?package=Crypt_GPG in /usr/local/lib/roundcubemail/plugins/enigma/lib/enigma_engine.php on line 981 (POST /mail/?_task=settings&_action=plugin.enigmakeys)

What can I do ?
Is there a specific version of gpg or making sure some sort of agent is running ?

**Comment by alecpl** [comment]
Enable enigma_debug and check the log. Most gnupg versions are supported.

**Comment by guizmoau** [comment]
done and the log say :
"gpg: can't connect to the agent: IPC connect call failed"

**Comment by guizmoau** [comment]
I did install the package pgp-agent and gnupgpg-agent already

**Comment by guizmoau** [comment]
however, the creation of keys seems fine, they can't appear in the list.
but I see them created in the folder I specify

drwx------ 3 www-data www-data 4096 May 21 11:18 .
drwxr-xr-x 3 www-data www-data 4096 May 20 17:05 ..
drwx------ 2 www-data www-data 4096 May 20 17:05 private-keys-v1.d
-rw-r--r-- 1 www-data www-data 4882 May 20 17:35 pubring.kbx
-rw-r--r-- 1 www-data www-data 2457 May 20 17:05 pubring.kbx~

**Comment by guizmoau** [comment]
now I am creating a new user and no more error message on listing the keys.

But when I try to create one key, i have this error message 
"Your web browser does not support cryptography"

this new user folder for keys content is 

drwx------ 2 www-data www-data 4096 May 21 12:48 .
drwxr-xr-x 4 www-data www-data 4096 May 21 12:48 ..
-rw------- 1 www-data www-data   32 May 21 12:48 pubring.kbx

**Comment by guizmoau** [comment]
Ok now, it works !!

I was missing openpgp.min.js I found out in the console log of the browser.
After adding it I can now create keys and use them !!

problem solved :) 👍

**Comment by alecpl** [comment]
Looks like "gpg: can't connect to the agent: IPC connect call failed" is system error we can do nothing about. Closing.
