### ISSUE TITLE
attachments cannot be opened after upgrade to v. 1.4.4

### ISSUE THREAD

**Issue by clusterx** [roundcube/roundcubemail#7400]
Debian 9
PHP 7.0
Dovecot
Panel : IMSCP
RC 1.4.4 on nginx

I have upgraded from 1.3.9 to 1.4.4 ... now I can no longer open attachments like PDF > 130 KB
upgraded from:
https://github.com/roundcube/roundcubemail/releases/download/1.4.4/roundcubemail-1.4.4-complete.tar.gz

I don't think it's a configuration issue, everything worked well before the upgrade for many years
and it only happens with file attachments larger than about 130 KB (smaller files are opened).

I have disabled all plugins (restart nginx, panel etc) but it didn't change anything.

`roundcube error.log
[22-May-2020 17:36:36 +0200]: <rjoqkltt> PHP Error: Request security check failed (GET /webmail/?_task=mail&_download=1&_mbox=INBOX&_uid=27&_part=2&_action=get&_extwin=1)

nginx error.log
2020/05/23 15:21:06 [crit] 22674#22674: *20 open() "/var/lib/nginx/fastcgi/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: xxx.xxx.xx.xxx, server: my.domain.tld, request: "GET /webmail/?_task=mail&_mbox=INBOX&_uid=8&_part=1&_action=get&_extwin=1&_framed=1&_mimewarning=1&_embed=1 HTTP/1.1", upstream: "fastcgi://unix:/run/imscp/imscp_panel.sock:", host: "my.domain.tld:8443", referrer: "https://my.domain.tld:8443/webmail/?_task=mail&_mbox=INBOX&_uid=8&_part=1&_action=get&_extwin=1&_preload=1&_framed=1"
2020/05/23 15:21:06 [crit] 22674#22674: *21 open() "/var/lib/nginx/fastcgi/6/00/0000000006" failed (13: Permission denied) while reading upstream, client: xxx.xxx.xx.xxx, server: my.domain.tld, request: "GET /webmail/?_task=mail&_mbox=INBOX&_uid=8&_part=1&_action=get&_extwin=1&_framed=1&_mimewarning=1&_embed=1 HTTP/1.1", upstream: "fastcgi://unix:/run/imscp/imscp_panel.sock:", host: "my.domain.tld:8443", referrer: "https://my.domain.tld:8443/webmail/?_task=mail&_mbox=INBOX&_uid=8&_part=1&_action=get&_extwin=1&_preload=1&_framed=1"`

chrome error message in PDF viewer
`PDF.js Version 2.3.164 (build: 12ff2527)
Message: network error`

**Comment by clusterx** [comment]
some more details:
no issue with php.ini settings, I'm able to upload large files and send without any problems ... but when I receive larger attachments (> 130KB) or if I save an email as draft w/ a 500KB PDF I get an error when opening the attachment.

**Comment by alecpl** [comment]
These errors look to me as there's some problem on nginx-fastcgi-php setup side. There's no problem with downloads in Roundcube 1.4. Try to upgrade PHP or something.

**Comment by clusterx** [comment]
thanks for reply, I guess something seems to be broken with my roundcube database ... I'm able to export any database from phpmyadmin except the roundcube database ...  it shows an network error message as above in webbrowser

**Comment by clusterx** [comment]
I was able to solve this issue .. I had a permission issue in some /var/lib/nginx/fastcgi folders
so I have stopped nginx and deleted all folders inside /var/lib/nginx/fastcgi, restarted nginx and restarted the PHP service ... now it works!
