### ISSUE TITLE
Roundcube 1.4.4 Complete- Send mail no response/ Logs empty

### ISSUE THREAD

**Issue by infinit0s** [roundcube/roundcubemail#7401]
Hello. 

I am having issues with the latest Roundcube. After upgrading from 1.2.x to 1.4.4 I am unable to send any email. When I press 'send' nothing happens and the UI freezes (i.e can't press on anything else) - only page reload allows to 'unhung' the UI. 

I've tested my exim and dovecot configuration using older release (1.2.x) and thunderbird for both imap and pop and everything works fine. 

On top despite the logging being enabled for SMTP for instance, the ./logs only consists of the following files:

-rw-r--r--  1 www-data www-data    164 Apr 26 20:50 .htaccess
-rw-r--r--  1 www-data www-data 372616 May 23 14:36 imap.log
-rw-r--r--  1 www-data www-data    124 May 23 14:36 userlogins.log

Exim version 4.84_2 #1 built 17-May-2020 00:29:11
dovecot --version
2.2.13

Tried on multiple browsers. 

Larry UI does absolutely nothing (no error message or anything)
Elastic UI shows constant loading in the bottom right corner, nothing is responding to clicks and after a while it shows a message 'request time out'

**Comment by johndoh** [comment]
Sounds like a JS error, check the browser console. Disable all plugins.

**Comment by infinit0s** [comment]
Checked if any JS error produced in the console on both firefox and chrome - console empty. Chrome has various plugins installed (which I have disabled for the purposes of testing this). Firefox is just 'as-is'.

**Comment by johndoh** [comment]
I meant roundcube plugins.

**Comment by infinit0s** [comment]
Plugins set to empty - still no effect

**Comment by johndoh** [comment]
so you are getting a timeout but there are no errors in the browser console or the rc logs and no connection attempt is made to your smtp server? and everything went smooth with the upgrade? you followed all the steps in the upgrading file? Also did you see the defaults for some of the smtp_* config options changed in 1.4?

**Comment by infinit0s** [comment]
So the only thing that is logged in mail.log is the following:

```
May 23 17:33:48 server dovecot: imap-login: Login: user=<maciej>, method=PLAIN, rip=::1, lip=::1, mpid=19685, secured, session=<AidrT1OmrAAAAAAAAAAAAAAAAAAAAAAB>
May 23 17:33:48 server dovecot: imap(maciej): Disconnected: Logged out in=38 out=455
```

However this is the same for both the 1.4.4 and 1.2.x. Exim mainlog is empty at the time of sending. No issues with the upgrade as far as I recall (i am using the old database though - which was created when installing 1.2).

My config.inc.php has the following 

```
$config['default_host'] = 'localhost';
$config['smtp_port'] = 25;
$config['smtp_server'] = 'localhost';
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

```

Mind you, the web client is installed on the same server as Exim. Exim uses short format authentication

**Comment by johndoh** [comment]
It is strange there are no errors logged anywhere. There error occurs with both HTML and plain text format emails right? If you look at the network tab in the browser's inspector then you see the send request being submitted to the server I assume.

It won't be the SMTP auth settings because you said no connection attempt is made and the connection has to be established before attempting authentication.

You could try adding some extra logging into `program/steps/mail/sendmail.inc` with lines like `rcube::write_log('debug', 'log message here');` and check the `debug.log`.

It might be a good idea to continue this discussion on the mailing list or forum and return here if an issue is identified in the Roundcube code. There is no general issue with 1.4.4 and sending email.

**Comment by infinit0s** [comment]
So there seems to be (at least in my opinion) a bug here - 

I was able to send email and logs started to produce once I have logged in as
'maciej@server.com' <- Once I've logged in using the following format everything started to work

To sum up:
Case 1 (working)
username: maciej@server.com
$config['username_domain'] = '';

Case 2 (working)
username: maciej
$config['username_domain'] = 'server.com';

Case 3 (not working)
username: maciej
$config['username_domain'] = '';

I have checked my 1.2.x config and I can confirm that case 3 used to work in the previous version. I guess this might be a corner case and most likely the vast majority of installations won't have such config that would break this so not sure if you want to look at it or not.

Anyway thanks for looking :)
