### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by LoRexxar** [roundcube/roundcubemail#7406]
There are three security issues in Roundcube mail 1.4.4:

- Store Xss via database host and user in /installer/test.php
- Store Xss via smtp config in /installer/test.php
- Store Xss via imap settings in database

Vulnerability details have been sent via email.

**Comment by alecpl** [comment]
Please, send it to alec at alec.pl

**Comment by LoRexxar** [comment]
Vulnerability details have been sent via email.

**Comment by alecpl** [comment]
Fixed. We plan a new release in a couple of days.

**Comment by LoRexxar** [comment]
Hi,

i hope add my id in next update posts, and my id is LoRexxar@Kownsec
404Team.

Finally, I must confirm whether you can help me apply for CVE id.

Thanks

Aleksander Machniak <notifications@github.com> 于2020年5月30日周六 下午2:41写道：

**Comment by LoRexxar** [comment]
oh, sorry, my id is LoRexxar@knownsec 404Team

LoRexxar Romer <lorexxar@gmail.com> 于2020年5月30日周六 下午10:49写道：
