### ISSUE TITLE
Release 1.4.5 is missing assets

### ISSUE THREAD

**Issue by tyranron** [roundcube/roundcubemail#7411]
At the moment [1.4.5 release is out](https://github.com/roundcube/roundcubemail/releases), but misses its description and assets, which makes some automation in downstream repos to fail.

<img width="580" alt="Screenshot 2020-06-02 at 11 21 05" src="https://user-images.githubusercontent.com/7114909/83497462-30a63b80-a4c3-11ea-8d14-46571ea16b12.png">

**Comment by alecpl** [comment]
It's tagged, but not released yet.
