### ISSUE TITLE
1.4.5 wrong link

### ISSUE THREAD

**Issue by 532910** [roundcube/roundcubemail#7412]
https://roundcube.net/news/2020/06/02/security-updates-1.4.5-and-1.3.12

points to

https://github.com/roundcube/roundcubemail/releases/tag/1.4.4

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/83578199-d480fd00-a53e-11ea-8de2-a59b9715ab72.png)

**Comment by alecpl** [comment]
Fixed.
