### ISSUE TITLE
No need to add href="./#NOP" to anchor tags without href attribute.

### ISSUE THREAD

**Issue by kizashi1122** [roundcube/roundcubemail#7413]
I don't think it is necessary to add `href="./#NOP"` to anchor tags without href attribute.

if added `href="./#NOP"` , it looks clickable (actually nothing happens).

https://github.com/roundcube/roundcubemail/blob/release-1.4/program/steps/mail/func.inc#L1246-L1249

An <a> element without an [href] attribute is still valid.

https://www.w3.org/TR/2011/WD-html5-20110525/text-level-semantics.html#the-a-element

FYI, Gmail does nothing for that element.

**Comment by alecpl** [comment]
Fixed.
