### ISSUE TITLE
Problem forwarding an email with jpg image attached received from iOS mail app

### ISSUE THREAD

**Issue by SamsamM38** [roundcube/roundcubemail#7414]
I receive an email from iOS mail app containing a jpg image attached.
I can open the image, all works normally.
When I forward this email, the jpg image attached disappear, it not appear in body either.

All works fine if the file attached is something else like a pdf file.
Roundcube version : 1.4.5

**Comment by alecpl** [comment]
Provide a sample message, please.

**Comment by SamsamM38** [comment]
[mail.txt](https://github.com/roundcube/roundcubemail/files/4722450/mail.txt)

**Comment by alecpl** [comment]
The attachment is marked as inline. I think we have already tickets for similar issues, but I'll leave it open. I hope to have time to work on these for 1.5.

Your workaround is to use "forward as attachment" feature.

**Comment by SamsamM38** [comment]
Thank you

**Comment by SamsamM38** [comment]
The question is : why the problem appear only with an email from iOS app mail ?

**Comment by alecpl** [comment]
Most clients do not use `Content-Disposition: inline` on the image part for messages with a plain text body and an image attachment.

**Comment by SamsamM38** [comment]
If I used the "forward as attachment" feature, a file attachment containing the email appear + the jpg image file that did not appear with the simple "forward" command.

So to summarize : forward command, jpg file disappear, "forward as attachment" jpg file appear.
Call Mulder and Scully !

**Comment by roberthr74** [comment]
We have the same issue using Rouncube Web client. Forward as attachment works in this case.

**Comment by tomsommer** [comment]
We are also getting reports of this

**Comment by lucasmarin** [comment]
@alecpl 

The problem is at compose.inc:997
```
            if ($part->disposition == 'inline' && $part->mimetype != 'application/pdf') {
                if (!$bodyIsHtml) {
                    continue;
                }

                $idx = $part->content_id ? ('cid:' . $part->content_id) : $part->content_location;

                if ($idx && isset($CID_MAP[$idx]) && strpos($message_body, $CID_MAP[$idx]) !== false) {
                    $replace = $CID_MAP[$idx];
                }
                else {
                    continue;
                }
            }
```

I saw that code above was developed by issue https://github.com/roundcube/roundcubemail/issues/7122 and removing else condition on it fix the problem on this issue. 

I will investigate it, fix on my RC locally and open a PR here.

Regards.

**Comment by alecpl** [comment]
Fixed.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/roundcube/roundcubemail/pull/9150
- https://github.com/roundcube/roundcubemail/issues/5051
- https://github.com/roundcube/roundcubemail/issues/6279
- https://github.com/roundcube/roundcubemail/issues/7117
- https://github.com/roundcube/roundcubemail/issues/7122
- https://github.com/roundcube/roundcubemail/issues/7214
- https://github.com/roundcube/roundcubemail/issues/7293
- https://github.com/roundcube/roundcubemail/issues/7414
- https://github.com/roundcube/roundcubemail/issues/7440
- https://github.com/roundcube/roundcubemail/pull/7441
