### ISSUE TITLE
composer.phar update with login required for php-net_ldap.git

### ISSUE THREAD

**Issue by efelon** [roundcube/roundcubemail#7416]
I'm on 1.4.4 and could successfully update to 1.4.5. During the installation though I got:

```
++ : php composer.phar update --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
    Authentication required (git.kolab.org):
      Username: 
      Password: 
Failed to update https://git.kolab.org/diffusion/PNL/php-net_ldap.git, package information from this repository may be outdated
Updating dependencies                                                                                                          
Generating autoload files
```
I don't have any credentials for that site and was not required before to enter any.

I'm not entirely sure it concerns you, but I already made several updates without any problems, so I thought you are at least interested.

Regards,
efelon

**Comment by alecpl** [comment]
Looks like your composer.json file is outdated. That package is supposed to be fetched from packagist. See "repositories" in composer.json-dist.

**Comment by efelon** [comment]
Thank you, I forgot to update my composer.json file according to the new composer.json-dist file.

**Comment by CodeShakingSheep** [comment]
I'm running in the same problem. I just checked the current `composer.json-dist` and it has this content:

```json
"repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net"
        }
    ],
```

In my `composer.json` I have exactly the same content for repositories. However, I'm running into this with ` kolab/net_ldap3` which I cannot find on the Roundcube plugin page. Currently I have version 1.1 of the plugin installed and composer wants to update it to version 1.1.5. Due to this I cannot install any further RC plugins because it always gets stuck with this plugin. Any suggestions @alecpl ? Thanks.

**Comment by alecpl** [comment]
https://git.kolab.org which is the location of kolab/net_ldap3 package is occasionally dying recently, that's the problem.

**Comment by CodeShakingSheep** [comment]
That was indeed the issue. Thanks @alecpl !

**Comment by rokj** [comment]
> https://git.kolab.org which is the location of kolab/net_ldap3 package is occasionally dying recently, that's the problem.

For several days now this link has not been accessible.

**Comment by alecpl** [comment]
git.kolab.org is dead since this weekend, but I know work to bring it back is being done. If you're not using ldap you can remove this dependency from the composer.json to make it working.

**Comment by rokj** [comment]
I am using ldap, I got it working by adding net_ldap3 to exclude field like:
```
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net",
            "exclude": ["kolab/net_ldap3"]
        }
    ],
```
so it is retrieving packages from packagist repos if I understood correctly.
