### ISSUE TITLE
installer/test.php is broken

### ISSUE THREAD

**Issue by alfredbuehler** [roundcube/roundcubemail#7417]
The section **Test SMTP config** does not render in a usable way.There are no fields _Username_ and _Password_ shown, but their HTML code instead.

![Roundcube-Webmail-Installer](https://user-images.githubusercontent.com/2079289/83675291-0fd00a00-a5d9-11ea-8e4e-a8e37f298edf.png)

**Comment by alecpl** [comment]
Fixed.
