### ISSUE TITLE
Managesieve: unable to reorder filters

### ISSUE THREAD

**Issue by nqb** [roundcube/roundcubemail#7419]
Hello,

I'm using Roundcube 1.4.3 and I'm not able to reorder filters through web interface. Drag and drop feature doesn't work. I'm pretty sure it works in 1.3.6.

### Steps to reproduce
In Filters menu:
1. Create a filter called "filter1" with a basic condition
2. Save
3. Create a second called "filter2" with a basic condition
4. Save
5. Try to drag-and-drop "filter2" before "filter1"

=> It doesn't work.

### Actual results
Unable to reorder filters.

### Expected results
Able to reorder filters.

### Additional context
I did test with:
- Firefox 68.7.0esr
- Chrome Version 80.0.3987.162

**Comment by nqb** [comment]
A user running 1.4.4 is able to reorder filters just fine.

**Comment by alecpl** [comment]
Works for me too. What other plugins are you using? Any errors in browser console?

**Comment by nqb** [comment]
Hello @alecpl,

I will try to test ASAP a newer version and give you a feedback. As you can in see related issue, I'm using Roundcube on a YunoHost server.

I have seen errors in browser console but I don't think they are related.

**Comment by alecpl** [comment]
I'm closing this for now.
