### ISSUE TITLE
Your new UX: flawed

### ISSUE THREAD

**Issue by RealDavidoff** [roundcube/roundcubemail#7420]
Hello,
First of all: I liked roundcube more than the other two options in my webhosts, so after years of using the others I have been using roundcube over the last maybe 6 months. Thank you.

Now unfortunately I gonna report a bug:
It is a bug when a software programmer releases an update that isn't even voluntary (it opens automatically with the new UX) and hasn't even noticed: "uups, some of the prior functionality wasn't migrated to our new UX!!!"

Which one?
Likely multiple, but the one that has today cost me SIX HOURS ALREADY: Where is the SENT folder gone??

I am not retarded and yet by the life of your mother I cannot find the SENT folder!
BUT: I urgently need to access an email I had sent out earlier, to copy out the content.
Hence why I **HAD** to waste already 6 hours of my precius short lifetime trying to find that folder: NOWHERE, still. :(

Suggestions:
1) How about always offering a clearly visible large button "revert to prior release"? As emergency so to say.
2) How about actually checking = testing a new release before rolling it out? Does all prior functionality still work, regardless how much we programmers (personally) love our new features?
3) If 1) or 2) failed: How about just keeping the new releases to yourself until both 1) and 2) have been fulfilled?

Good suggestions?
Thank you. I know. ;)

**Comment by alecpl** [comment]
Thanks for the suggestions. This is not gonna happen. We're not being paid for that, this is all voluntary work. This is not a place for rants like this. I have the Sent folder in place.
