### ISSUE TITLE
Typo in de-DE/de-CH translation

### ISSUE THREAD

**Issue by buttercookie42** [roundcube/roundcubemail#7421]
`blockedimages` and `blockedresources` both begin with "Um Ihre Privatsphäre zu**r** schützen [...]",
correct would be "Um Ihre Privatsphäre zu schützen [...]".
I would have corrected those myself, except that my join request on Transifex seems to have got stuck somewhere…

**Comment by smares** [comment]
> my join request on Transifex seems to have got stuck somewhere

Same here

**Comment by alecpl** [comment]
Your join requests has been accepted.

**Comment by buttercookie42** [comment]
Thanks. Seems like that particular error was already fixed independently two months ago, so it just needs a string update.
