### ISSUE TITLE
Roundcube and pagespeed FileCachePath "/var/cache/pagespeed/";

### ISSUE THREAD

**Issue by evil4u** [roundcube/roundcubemail#7422]
Hi.

I am using Plesk Obsidian Version 18.0.27  and CentOS Linux 8.1.1911.

I have nginx pagespeed installed and Brotli enabled. What I am facing is when I add 
pagespeed FileCachePath "/var/cache/pagespeed/"; to nginx.conf my webmail.domain.com Roundcube theme gets messed up like this https://imgur.com/a/3p8MMHw

Dose any one else have the same problem if so how did you solve this.

Best Regards

Bragi Austfjörð

**Comment by alecpl** [comment]
Check the browser console for errors. Looks like css style are missing.

**Comment by evil4u** [comment]
Thanks I have checked the console for errors, and found out that if I enable pagespeed FileCachePath "/var/cache/pagespeed/"; in nginx.conf the webmail.domain.com will have 2 pagespeed active, nginx pagespeed and apache pagespeed.
