### ISSUE TITLE
Elastic: Unable to right-click and paste address into a recipient input

### ISSUE THREAD

**Issue by zachol72** [roundcube/roundcubemail#7431]
How to recreate issue:

1. Make sure to have an e-mail address in your clipboard
2. Compose new mail in Roundcube with skin "Elastic"
3. Right-click "To"-filed to paste address
4. Paste not available in entire filed, only in a 10px wide area. See attached screen dump.

![roundcube1](https://user-images.githubusercontent.com/38487567/84348830-451ac000-abb6-11ea-8213-2bd775815d57.png)
 

Using Chrome V 83

**Comment by alecpl** [comment]
The same will be in other browsers. Fixing that might be not that easy.

You can left-click and Ctrl+V.

**Comment by alecpl** [comment]
I fixed this with some flexbox magic. Still not perfect, if there's more than one line, right-click works on the last line only. But it should be good enough.
