### ISSUE TITLE
count(): Parameter must be Countable

### ISSUE THREAD

**Issue by sadtler** [roundcube/roundcubemail#7433]
Setting up roundcube-core (1.2.3+dfsg.1-4+deb9u5) ...
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438

Current version line is 468 in https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_plugin_api.php

**Comment by alecpl** [comment]
This version is not supported. Upgrade!.

**Comment by sadtler** [comment]
> This version is not supported. Upgrade!.

Yes, well, I am following my distributions version. I found and linked the current error in your current code base. Which follows the same issue shown in https://github.com/roundcube/roundcubemail/commit/df3878501cc34fefbb3d6ac2a8674c9121fd1fba#diff-0c8683cd773e3c1201aaf42fa2f8e422L104 which you fixed, it's just a missing check.

**Comment by alecpl** [comment]
This one is also fixed already.

**Comment by chrestomanci** [comment]
Are you on Debian? (The version number you quoted looks like a Debian one in the stretch release).

If so then roundcube 1.4.5 is in buster-backports, and you should upgrade your system to buster anyway as stretch will go out of support soon.
