### ISSUE TITLE
Signature options - place below quoted message

### ISSUE THREAD

**Issue by melusine33** [roundcube/roundcubemail#7434]
When I reply to emails, I'd like my signature to be placed above the quoted message. Even when I have the option to place it below the quoted message unchecked (see screenshot), it's still showing below. (I also tried checking that box to see if it would do the opposite, but no dice. Either way, my signature is showing at the bottom of the reply email, below the quoted message.)

<img width="539" alt="Screen Shot 2020-06-11 at 2 59 09 PM" src="https://user-images.githubusercontent.com/66799350/84428544-a3669380-abf4-11ea-9a2c-5c93bf7e1bb9.png">

**Comment by alecpl** [comment]
The signature normally is placed with the reply text. In Main options section you have to set "When replying: start new message above the quote".
