### ISSUE TITLE
Messages show date from file on server, not from received date

### ISSUE THREAD

**Issue by rachelbullmann** [roundcube/roundcubemail#7442]
Hello,

On cpanel, Roundcube Webmail 1.4.4, the inbox shows the date that is in the file inside the server, but the receipt of the email has a different date. Is this adjustment possible?

Example: Delivery-date: Thu, 21 Nov 2019 16:49:06 -0200
Show: Jun 12 20:58

Roundcube Webmail 1.4.4
archive | 3.4 | GPLv3+ |  
calendar | 3.5.3 | AGPLv3 | Baixar
carddav | 3.0.3 | GPL-2.0 | Baixar
cpanellogin | 11.58 | cPanel License (Proprietary) |  
cpanellogout | 11.58 | cPanel License (Proprietary) |  
filesystem_attachments | 1.0 | GPLv3+ |  
jqueryui | 1.12.0 | GPLv3+ |  
libcalendaring | 3.5.2 | AGPLv3 | Baixar
libkolab | 3.5.3 | AGPLv3 | Baixar
return_to_webmail | 11.88 | cPanel License (Proprietary)

**Comment by alecpl** [comment]
If the sorting column is "Arrival date" it shows internal date, If the sorting is "None" or "Sent date" it should show the date from email header.
