### ISSUE TITLE
Feature Request: UI similar to Hey.com

### ISSUE THREAD

**Issue by eshnil** [roundcube/roundcubemail#7443]
Hey.com has released an interesting UI : https://www.youtube.com/watch?v=UCeYTysLyGI

There are a lot of desirable features:

- "Set Aside" and "Reply Later" queues
- "Read Together" - A feed view of non-important emails such as newsletters
- New senders need to be whitelisted

This may not be the right place, but can it be possible to make RoundCube look and behave like Hey.com ? What would it take?

**Comment by alecpl** [comment]
It would take a lot. You would have to write a plugin (and maybe a new skin). Imo, there are more interesting features to work on.
