### ISSUE TITLE
Drop-down list without a "---" added

### ISSUE THREAD

**Issue by davidc** [roundcube/roundcubemail#7444]
There does not seem to be a way for a plugin to create a drop-down list that doesn't have a "---" entry at the start. `rcube_output::get_edit_field` always adds this entry where type is `select`.

There are types of list where it does not make sense to have an "empty" or "unselected" option. For example picking from a list of the user's e-mail addresses.

Obviously we can (and do) validate the form results, but this is poor user experience.

Changing `select` would probably affect many things, so I would maybe just add a new type, e.g. `select-required`.

```
        else if ($type == 'select-required') {
            $input = new html_select($attrib);
            $input->add(array_values($attrib['options']), array_keys($attrib['options']));
        }
```

**Comment by alecpl** [comment]
I'd rather pass some boolean option via `$attrib`.

**Comment by alecpl** [comment]
Done.
