### ISSUE TITLE
"Mark as Junk" and "Mark as NONjunk" buttons inactive

### ISSUE THREAD

**Issue by elvisef** [roundcube/roundcubemail#7446]
Hello.

Just a little question. I have enabled "markasjunk" plugin in my roundcube, but the buttons are not active. Why ?

![22062020_07:46:56_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85259935-2d6ef180-b46a-11ea-9ae3-8e72cc8f4ddf.png)
![22062020_07:48:19_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85259942-3069e200-b46a-11ea-87ff-b678b2eca0a2.png)
![22062020_09:25:17_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85260122-745ce700-b46a-11ea-94e8-e653d1542f99.png)
![22062020_09:25:38_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85260128-76bf4100-b46a-11ea-8350-f338cd0627c3.png)
![22062020_09:25:58_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85260130-78890480-b46a-11ea-9e99-1530c62d675b.png)

**Comment by alecpl** [comment]
They don't become active when you select messages? Do you have Junk special folder?

**Comment by elvisef** [comment]
They don't become active even if I am viewing a message details.
Yes, I have a folder named "spam".

![22062020_09:52:06_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85262602-4da0af80-b46e-11ea-8980-40ca2fb9d851.png)

Do I need to name it another way ? For instance "junk" to make it work ?

**Comment by alecpl** [comment]
Are you using current master? You should be seeing only the Spam button, the Nie-spam button should be hidden. The button would be replaced when you select the Spam folder. Check browser console for javascript errors.

**Comment by alecpl** [comment]
Oh, I just noticed that when you unset the Spam special folder, both buttons appear. So, maybe there's some problem with recognizing the folder. @johndoh maybe you'll know what's the problem here.

**Comment by johndoh** [comment]
When no Spam special folder is defined (or provided though markasjunk config) then both buttons are shown because we don't know what type of message the user is viewing and they might want to mark it either way.

I think there must be a JS error its the only think I can think of.

BTW I see in your config you have specified the `cmd_learn` driver but not defined any commands. It would not cause this behavior but its also not right.

**Comment by elvisef** [comment]
Hey.

That is really weird then. I tried to unset the "spam" folder - no errors, no effects.
Tried to reset the folder again - I have a folder named just "spam" - no errors, no effects.
Both buttons still visible.

What I need to have is just a functionality to use a simple "mark as spam" button, which (I suppose) will move chosen messages directly to a chosen special spam folder, and somehow mark that mail address as a spam (blacklisting ?). Do I have to do more configuration here ?

![27062020_14:35:49_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85922486-f5a9e480-b883-11ea-9b96-af8fd027953c.png)

**Comment by johndoh** [comment]
Check the network tab, make sure markasjunk.js is loaded properly. And then I guess try adding some debugging messages into markasjunk.js to find out where it is failing. May be start in markasjunk_toggle_button().

**Comment by elvisef** [comment]
As far as I see, "markasjunk.js" isn't being directly loaded but the "min" version yes.
Do I need to do a minifying everytime I made changes in the code ?
The Network tab say that markasjunk.min.js is loadad successfully.
No console.log errors. Still visible two buttons.
I am trying to debug this. Look at the screenshot with my Roundcube config - the "plugins" config has "markasjunk" on the list.
So it should be loaded without problems. Hmm...
I am wondering if any Adblocks or Ghostery's could block this...

![27062020_18:53:22_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85927853-15073880-b8a9-11ea-95b4-e472d90f9fd9.png)
![27062020_18:56:37_Zaznaczenie](https://user-images.githubusercontent.com/25976749/85927856-18022900-b8a9-11ea-9191-86ebc5ef0778.png)

**Comment by johndoh** [comment]
There is no issue here. Minified JS files are not part of the git repo, they are built manually when releases are created using `bin/jsshrink.sh`. I guess you updated from a previous version of Roundcube to git-master and this file was left over.

**Comment by alecpl** [comment]
If you're using git master, either remove all min.js files or generated them with above mentioned script (after you made any change in js code).

**Comment by sazzle2611** [comment]
Thank you so much @elvisef we had exactly the same problem after upgrading and customers weren't very happy about it. Unfortunately it was really bad timing as we had just set up new sieve filters to train spamassassin on messages moved to junk (not using this plugin) so they all wanted their 'Move to Junk' button!!

Your fix of copying the js over the min.js worked a treat, so now I'm going to try the jsshrink.sh function mentioned above in case there are other files to update. Just waiting for a backup to complete first ;)

Would have thought this was included in the installto.sh script that we did run.

Looking at the scripts I'm presuming I should also run the cssshrink.sh script?

**Comment by sazzle2611** [comment]
OK scrap that, running the script gives me this error 

Java not found. Please ensure that the 'java' program is in your PATH.

I am not installing extra things on our production server just to get the minified js.

Along with the upgrade I was excited about the new elastic template but had the same issue there, apparently you have to compile the files yourself. I don't want to be spending my time doing that, I might someday but for now can live without.

**Comment by elvisef** [comment]
> Thank you so much @elvisef we had exactly the same problem after upgrading and customers weren't very happy about it. Unfortunately it was really bad timing as we had just set up new sieve filters to train spamassassin on messages moved to junk (not using this plugin) so they all wanted their 'Move to Junk' button!!
> 
> Your fix of copying the js over the min.js worked a treat, so now I'm going to try the jsshrink.sh function mentioned above in case there are other files to update. Just waiting for a backup to complete first ;)
> 
> Would have thought this was included in the installto.sh script that we did run.
> 
> Looking at the scripts I'm presuming I should also run the cssshrink.sh script?

Glad to hear someone with same issues.
I came back to fight with errors now, again.
Did You try to fix problem with java since then ?



> There is no issue here. Minified JS files are not part of the git repo, they are built manually when releases are created using `bin/jsshrink.sh`. I guess you updated from a previous version of Roundcube to git-master and this file was left over.

Thanks for info.
I've just installed minimal java libraries and there is a problem with "jar" file.
![2020-12-10_15-24](https://user-images.githubusercontent.com/25976749/101784506-e2ba6200-3afb-11eb-8e31-b9f8b1941fb4.png)

**Comment by elvisef** [comment]
Crap.. now I have all js files replaced... I need to have access to my email, ... 
What I see is a white space instead of the message list - the tree on the left looks good, but the right window is clean white...

Tell me plaese, what to do witch tis compiler.jar ? Do You have a copy of it so I can try it and recompile my files ?
