### ISSUE TITLE
Signature Fonts -Permissions erropr

### ISSUE THREAD

**Issue by wungaz** [roundcube/roundcubemail#7449]
When a user try to use another font as a signature on RoundCube, I get the following error:

**Forbidden**
_You don't have permission to access /webmail/ on this server._

Signatures works with default font

**Comment by alecpl** [comment]
We need more info. What version, what skin, what plugins, what browser? And precise steps to reproduce the issue, perferably with some screenshots.

**Comment by wungaz** [comment]
I am using elastic version. Its failing on Chrome and Firefox
Roundcube Webmail 1.4.6
**Plugins:** 
archive	3.4	GPLv3+	
cwpautologon	--		
filesystem_attachments	1.0	GPLv3+	
jqueryui	1.12.0	GPLv3+	
managesieve	9.3	GPLv3+	
password	5.1	GPLv3+	
zipdownload

Attached Error 
![roundcube](https://user-images.githubusercontent.com/65822476/85396025-55855000-b551-11ea-8d0b-74d95c03666e.PNG)
Screen

**Comment by alecpl** [comment]
That most likely will be http server config issue. Check the log. I would also try with disabled external plugins, i.e. cwpautologon.

**Comment by wungaz** [comment]
I have noted that if its plain email it send, its blocking HTML emails. You cannot send if its html format

**Comment by alecpl** [comment]
You get 403 Forbidden when you send an email too? Definitely not a Roundcube issue.
