### ISSUE TITLE
Login "error" message display

### ISSUE THREAD

**Issue by nward** [roundcube/roundcubemail#7450]
When authenticating to IMAP, an error message is returned to the client. Typically this is little more than "Authentication Denied" or something, however, this message can be useful.

I use this to display different messages for accounts being locked, or even that the account is locked rather than the password simply being incorrect. Many email clients display these - though of course not all. My users have a tendency to check their webmail login if their desktop/device client isn't working, so I'd like to get those errors displayed there.

Posting this issue to get feedback prior to me looking deeply in to this. I had a cursory look and it looks like a bunch of the IMAP error handling would need to be tweaked in order to get this working, so as it's not a "quick hack" fix figured best to get feedback :-)

I have considered localisation issues - we of course have error messages from the server displayed for SMTP, so this would be similar to that.
I think perhaps a "v2" of this functionality might be allowing regex match > translation for these messages. I.e. logic like "if the message is 'authentication denied' then display the roundcube standard login error", with a default "else" to display the original error from the server.

**Comment by alecpl** [comment]
The server I'm using returns "NO authentication failure" on wrong password. I'm not sure how reliable that's gonna be. But we sometimes display the server response to the user. See `rcmail::display_server_error()`, so it might be worth a try.

A related to this might be #5060. Using the [ALERT] response code would indicate the message should be displayed to the user.

**Comment by nward** [comment]
Yes it would be exactly that - I had not seen #5060 I'm sorry.

I'll move my discussion this over there.
