### ISSUE TITLE
1.4.6 filters plugin does not work causes server error after login.

### ISSUE THREAD

**Issue by antonical** [roundcube/roundcubemail#7451]
The standard filters plugin does not work. Once enabled and following login a server error message is displayed. This is the same across all three skins.

Any advice to fix would be appreciated.

Cheers
Spart

**Comment by johndoh** [comment]
What is the name of the plugin you are referring to? What is the exact error message and what is in the Rounducbe error log?

Please provide specific information not general comments.

**Comment by antonical** [comment]
Its the standard plugin called filters from the plugins directory. Not sure of its origin. Roundcube was installed via an installer script in Virtualmin.

Jun 25 17:49:18 vps7 roundcube: PHP Fatal error:  Uncaught Error: Call to undefined method rcube_imap::get_mailbox_name() in /home/domain.co.uk/public_html/webmail/plugins/filters/filters.php:58#012Stack trace:#012#0 /home/domain.co.uk/public_html/webmail/program/lib/Roundcube/rcube_plugin_api.php(469): filters->filters_checkmsg(Array)#012#1 /home/domain.co.uk/public_html/webmail/program/steps/mail/func.inc(444): rcube_plugin_api->exec_hook('messages_list', Array)#012#2 /home/domain.co.uk/public_html/webmail/program/steps/mail/list.inc(109): rcmail_js_message_list(Array, false, Array)#012#3 /home/domain.co.uk/public_html/webmail/index.php(306): include_once('/home/domain.co....')#012#4 {main}#012  thrown in /home/domain.co.uk/public_html/webmail/plugins/filters/filters.php on line 58

This is all I could find of the error. 

I f this is not the correct plugin can you point me at he correct simple user defined filters plugin.

Cheers
Spart

**Comment by alecpl** [comment]
This is an external plugin we do not support. Looks like it might not be compatible with Roundcube version you're using.

**Comment by antonical** [comment]
AH ok. Is there a default filters plugin we should be using to use basic user configured filters to move messages around on receipt etc.

**Comment by antonical** [comment]
Wow, thanks for just closing out this ticket. Clearly you know the product well. Your answer suggests there is a plugin you do support. Can you advise if there is a supported filters plugin, where to download it and anything I should be aware of. I have disabled the filters plugin that was causing the issues ?

**Comment by alecpl** [comment]
Managesieve plugin is part of Roundcube package. Ask on mailing list or forum for more info.
