### ISSUE TITLE
UX ideas from Hey.com

### ISSUE THREAD

**Issue by eshnil** [roundcube/roundcubemail#7453]
There are some good UI/UX ideas in Hey.com: [Features](https://hey.com/features/) , [How it works](https://hey.com/how-it-works/)

- New senders must be whitelisted via The Screener
- Reply Later and Set Aside queues.
- Feed view
- and more

Are there plans to bring any of these to RoundCube?

**Comment by alecpl** [comment]
No.

**Comment by thomascube** [comment]
The suggested ideas are more workflow improvements than simple UI changes. There are several technical reasons why they cannot be implemented in Roundcube. Same as for #7443

**Comment by alecpl** [comment]
I think it was a spam.
