### ISSUE TITLE
Elastic: Composing, the recipient suggestions drop-down without a background color

### ISSUE THREAD

**Issue by PedroLucasnet** [roundcube/roundcubemail#7461]
![roundcube recipient suggestions](https://user-images.githubusercontent.com/3915618/86004793-b8705e80-ba0b-11ea-9012-909da1810dc6.png)

While typing to find a contact, the suggested entries show up with a transparent background making it hard to read.

Thanks

**Comment by smares** [comment]
It has a background for me with Chrome and Firefox. Using 1.4.5.

**Comment by alecpl** [comment]
I'm also unable to reproduce. Please, test with all plugins disabled. What version?

**Comment by PedroLucasnet** [comment]
Thanks for your feedback.
This is 1.4.4 tested on two very distinct shared hosting providers with the same issue. I don't have access to disable plugins. I'll have to hope a fix is deployed when they update. Cheers

Plugins info below anyway:
archive | 3.4 | GPLv3+ |  
calendar | 3.5.3 | AGPLv3 | Download
carddav | 3.0.3 | GPL-2.0 | Download
cpanellogin | 11.58 | cPanel License (Proprietary) |  
cpanellogout | 11.58 | cPanel License (Proprietary) |  
filesystem_attachments | 1.0 | GPLv3+ |  
jqueryui | 1.12.0 | GPLv3+ |  
libcalendaring | 3.5.2 | AGPLv3 | Download
libkolab | 3.5.3 | AGPLv3 | Download
return_to_webmail | 11.88 | cPanel License (Proprietary)

**Comment by PedroLucasnet** [comment]
Hi! Meanwhile I changed hosting provider and unfortunately I still have this issue on my machine and my clients':
![Find as you type background](https://user-images.githubusercontent.com/3915618/87923625-b121fb00-ca75-11ea-908c-677c62c48158.png)
Ironically IE is the only one where it's ok. :)

Currently, the shared hosting (Altushost Biz50) is running these versions:

Roundcube Webmail 1.4.6
Plugin | Versão 
archive | 3.4
calendar | 3.5.3
carddav | 3.0.3 
cpanellogin | 11.58 
cpanellogout | 11.58 
filesystem_attachments | 1.0
jqueryui | 1.12.0
libcalendaring | 3.5.2 
libkolab | 3.5.3 
return_to_webmail | 11.88

**Comment by alecpl** [comment]
You're the only user that complains about this issue. I think this is caused by one of the plugins you're using.

**Comment by PedroLucasnet** [comment]
Hi Aleksander.
I've seen this on two shared hostings email service, GreenGeeks and Altushost.
If it's their typical config, this is probably impacting a number of end users. Maybe they just didn't come search you to raise it. :) Unfortunatly I won't be able to disable plugins but I'm asking Altushost to take a look into it.
Thanks.
