### ISSUE TITLE
Search result paging broken on IMAP server with no SORT capability

### ISSUE THREAD

**Issue by informas** [roundcube/roundcubemail#7462]
I have found a problem when I search, and that is that the penultimate (the page previous to the last) page of results does not appear complete, but rather shows the same number of results as the last one.

I will try to be more illustrative with an example:

```
**Example 1:**
Mailbox view - Rows per page: 200

Number of results to display from an example search: 245
 
It should show:
200 on the first page
45 in second
 
But in this case there are only 2 pages, the first is also the penultimate.
So according to the logic I found it shows:

45 records in last (as applicable)
45 in the penultimate (in this case coinciding with the first)
155 records left undisplayed
```

```
**Example 2:**
Mailbox view - Rows per page: 40

Number of results to display from an example search: 245
 
It should display 245 records, 6 pages x 40 records + 1 page with the remaining 5.
 
Instead, and following the logic detected, it shows:
For the first 5 pages: 40 records
For the sixth and penultimate: 5 records (same as for the last page, instead of the 40 it should show)
For the last page: 5 records (as it should be shown)
```
 
That is to say, always on the penultimate page Roundcube "forgets" to show the last part of the records that must be shown.
 
I have tested with versions 1.3.6, 1.4.2 and 1.4.4.
 
Does anyone else have this problem?
TIA
Jorge Colaccini

**Comment by smares** [comment]
Just tested with 20 results per page, 95 found mails and penultimate page had 20 mails, last one had 15.

1.4.5 with Elastic.

**Comment by alecpl** [comment]
Could you create a smallest posible dataset, enable imap_debug and provide the log? Did you try with all plugins disabled? What IMAP server? Is imap_cache/messages_cache enabled? What is the sorting order? What PHP version?

**Comment by informas** [comment]
Hi Alec,

While I prepare the data of the test that you have requested, I anticipate some details that I have found
If in sorting options I indicate sorting by any column the reported problem occurs else if I selects NONE for column to sort, the search results are complete without truncate anything.

Did you try with all plugins disabled? NO
What IMAP server? MERCURY MAIL SERVER 4.80.149
Is imap_cache/messages_cache enabled?: NO
What is the sorting order? any but NONE. Indicating NONE the problem does not occur!
What PHP version? 7.2.4 under Apache Server 2.4.33 on Windows 10 ver. 2004 (build 19041.329)

Thanks in advance.

Best regards.

Jorge Colaccini

**Comment by alecpl** [comment]
First I would check with disabled plugins. Also, the PHP version is quite old. If you have enabled opcache, try with disabled.

Some more questions: Are you doing single- or multi- folder search? Threaded or non-threaded?

**Comment by alecpl** [comment]
No feedback.

**Comment by informas** [comment]
Hi Alec,

First of all, I apologize for the delay in my response.

I will send you the information you have requested.

First of all and as I had anticipated in a previous answer if I indicate NONE as "sorting order" Roundcube works correctly. In other words, the reported problem appears when some special order is indicated.

From here, my answer is considering that some sort of order other than NONE is indicated!

1) I disabled the plugins: **the result is the same**

2) Opcache is disabled

3) The search is done on a single folder. The current folder. And on all messages (Types)
 
4) I tried with PHP 7.4.8 and **the result is the same**.

5) The mail server is MERCURY (Mercury/32 v4.80.145 - IMAP4rev1)

6) I did a test with a reduced set of emails:

**Test 1:**
I set up Roundcube to show **4 records per page**
I did a search that found 6 results
**Search returns 6 results**
First page shows the first 2 emails out of the 4 that would correspond.
Second page shows the last 2 results, as expected.

Page 1:
![imagen](https://user-images.githubusercontent.com/30926577/88865908-88210900-d1df-11ea-93a3-485a3b826c05.png)

Page 2:
![imagen](https://user-images.githubusercontent.com/30926577/88865867-6f185800-d1df-11ea-9d14-e62541efff09.png)


IMAP log file: imap.dddd_p1-p2.log
[imap.dddd_p1-p2.log](https://github.com/roundcube/roundcubemail/files/4998079/imap.dddd_p1-p2.log)
Contains the first and second page display data.

**Test 2:**
I set up Roundcube to show 20 records per page
I did the same search as in Test 1.
Search returns 6 results
**First and only page shows 6 results**
![imagen](https://user-images.githubusercontent.com/30926577/88866081-fd8cd980-d1df-11ea-9adb-f87d57f8c4b2.png)

IMAP log file:
[imap.dddd.punique.log](https://github.com/roundcube/roundcubemail/files/4998082/imap.dddd.punique.log)
 imap.dddd.punique.log

Could it be that the problem is caused by the mail server?

**Comment by alecpl** [comment]
The log looks correct, so it might be a Roundcube bug. The IMAP server does not support SORT and that might be related. I'll investigate. Does it fail with every other sort setting other than "none"?

**Comment by alecpl** [comment]
Fixed.

**Comment by informas** [comment]
Wow!!! What a quick answer!!!

**Yes, this modification fixes the problem.** 

Thank you very much, Alec.

Jorge Colaccini
