### ISSUE TITLE
JQuery 1.2 < 3.5.0 Multiple XSS

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7464]
Hi,

This report (https://www.tenable.com/plugins/nessus/136929) states that jQuery versions < 3.5.0 are susceptible to XSS. Roundcube currently uses 3.4.1 (in master). Is there any way this would get updated to a newer jQuery version soon or does this not affect roundcube?

**Comment by alecpl** [comment]
On master we will switch to 3.5.1. However, I wouldn't do this for older branches to not cause compat. breaks, until someone proves the security issue can be leveraged in Roundcube.

**Comment by alecpl** [comment]
Done.
