### ISSUE TITLE
Reply on mail with attachement can't send or save

### ISSUE THREAD

**Issue by DevRojod** [roundcube/roundcubemail#7468]
Got a DirectAdmin instance running. Using RC as webmail.

One of my customers suddenly got an issue; it can't reply on a mail with attachement(s), it just keeps loading. Same on saving as draft. Other customers don't seem to have this issue.

**PHP version:** 7,4 as default, 7.3 and 7.2 as backup.
**Mail server:** Dovecot and Exim.
**OS & browser:** Multiple browsers on Windows 10, als Chrome / Firefox on Android.
**Logs:** No error findable.
**Behavior reproducible:** At one client, not at others.
**Plugins disabled:** Yes. No difference.

**Comment by alecpl** [comment]
Check the browser console for javascript errors (and the Network tab there might give some clues).

**Comment by alecpl** [comment]
No feedback.
