### ISSUE TITLE
Permission Denied on installer page

### ISSUE THREAD

**Issue by bmccorm2** [roundcube/roundcubemail#7469]
Hi all - 

I am trying to configure roundcube via docker and I am getting a permission denied error on the installer page (http://myDomain.com/roundcube/installer).  The main login page comes up just fine so i am pretty sure there is nothing wrong with my webserver.  I have also configured the DB and user for roundcube and passed them in via the environment variables.  In addition i set up server settings through the variables. I'm having trouble finding any error messages or logs that will point me in the right direction.  Has anyone seen this before?

Thanks,
Bryan

**Comment by alecpl** [comment]
Better to ask on https://github.com/roundcube/roundcubemail-docker/.
