### ISSUE TITLE
Howto restore user address books from backup

### ISSUE THREAD

**Issue by peter-toft-greve** [roundcube/roundcubemail#7472]
I have had a roundcubemail-1.2-beta running on Debian with Mysql for several years with ZERO problems until the server had to upgraded.
I have now installed an updated server with 1.4.x on Sqlite3 - so nice! I went to Sqlite3 since Mysql got removed by Debian.
I can see that I have lost my (and much worse) my wifes address book.

I am planning now to make a virtual machine of the old server and restore the whole mysql database from a backup.
But where should I start to dig for the address books?

I have read https://github.com/roundcube/roundcubemail/wiki/Upgrade, https://github.com/roundcube/roundcubemail/wiki/FAQ and tried to read through the existing issues for this project.
I have seen https://github.com/JaimeObregon/export-roundcube-sql - have not tried it.

**Comment by alecpl** [comment]
You probably changed `default_host` setting in config. In such case you have to update `users` table.

**Comment by peter-toft-greve** [comment]
I doubt that this is the case

**Comment by peter-toft-greve** [comment]
I now have a virtualbox online with the mysql database restored

**Comment by peter-toft-greve** [comment]
@alecpl if possible please reopen

**Comment by alecpl** [comment]
No, this is not a support forum.

**Comment by peter-toft-greve** [comment]
okay - moving to https://www.roundcubeforum.net/index.php/topic,28951.0.html
