### ISSUE TITLE
The caller of rcmail_send_mdn function doesn't accept a string as smtp_error

### ISSUE THREAD

**Issue by gajeitos** [roundcube/roundcubemail#7475]
I'm writing a plugin that uses the [`message_before_send`](https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#message_before_send) hook. The plugin needs to return an internationalized error so I'm returning the error as a string. The documentation indicates it is allowed:
> error: Error message as string or arguments to be passed to rcube::gettext(). Used with abort=true

But in the particular case that a read receipt submission fails I get a PHP warning when the error is shown:

> PHP Warning:  Illegal string offset 'vars' in /srv/www/htdocs/roundcube/program/steps/mail/show.inc on line 124
PHP Warning:  Illegal string offset 'label' in /srv/www/htdocs/roundcube/program/steps/mail/show.inc on line 124

I think the problems is that [`program/steps/mail/show.inc`](https://github.com/roundcube/roundcubemail/blob/master/program/steps/mail/show.inc#L124) is not expecting the function `rcmail_send_mdn` returns an error string and it should work in the same way that [rcmail_sendmail->deliver_message](https://github.com/roundcube/roundcubemail/blob/9ee1f4b6366d3188e2cc9b5025bc59ed9160c78e/program/include/rcmail_sendmail.php#L392).

**Comment by alecpl** [comment]
That documentation is outdated, but we indeed do not support string error in all places that use deliver_message() method. This will need to be fixed.

You can return an array containing 'label' and 'vars' instead, this should be supported everywhere.

**Comment by gajeitos** [comment]
> You can return an array containing 'label' and 'vars' instead, this should be supported everywhere.

I tried but I'm not able to get it to work, when I use the array with `label` and `vars` the translation is not done, I only get the label as the translated text.
I think it is because the translations are in a file in the localization directory of my plugin.
I found that the function [text_exists](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php#L618) is being called [without a `domain`](https://github.com/roundcube/roundcubemail/blob/1e1ea25b6c4db6ddf7f2f0e7a44983710c07d535/program/include/rcmail_output_html.php#L512) (plugin name) so the text is not found.
I'm doing or interpreting something wrong?

**Comment by alecpl** [comment]
Your label should be in a form of `<plugin-name>.<label>` and of course you're responsible for loading the plugin localization.

**Comment by gajeitos** [comment]
Thank you, it works!

**Comment by alecpl** [comment]
Fixed.
