### ISSUE TITLE
Deleted contacts not purged from database

### ISSUE THREAD

**Issue by csware** [roundcube/roundcubemail#7477]
I regularly run `gc.sh`, however (long time) deleted contacts still reside in the database with `del = 1` set.

Roundcube 1.4.7

**Comment by alecpl** [comment]
There's a separate script for this: cleandb.sh. Default threshold for it is 7 days, you can change it by passing a number as the script argument.

**Comment by csware** [comment]
I tried, however, the deleted contacts (deleted 2013 (`changed`column also shows 2013) are still there.

**Comment by alecpl** [comment]
Enable sql_debug and cheeck the sql query in the log. What database?

**Comment by csware** [comment]
I found the issue, one cannot call the script from within the bin directory.

**Comment by alecpl** [comment]
What error did you get. Works for me.

**Comment by csware** [comment]
I saw no output at all.

`require_once` issue in another third party plugin.
