### ISSUE TITLE
Support UTF-8 in localpart of an email address for user login

### ISSUE THREAD

**Issue by diancho** [roundcube/roundcubemail#7480]
Hello.
Does Roundcube Support UTF-8 in localpart of an email address for user login as an option?
I can login with punycode but not with unicode.
The domain name can be unicode but not the user name before @ symbol.

**Comment by alecpl** [comment]
Roundcube passes the login as is. I think this might be your imap server limitation/bug.

Of course, some plugins might do this or for example `login_lc` option will lower-case the login.

I'd propose to enable imap_debug, but it will hide the login/password. So, a better option would be to debug that on the imap server side.

What version? What PHP version? What IMAP server?

**Comment by diancho** [comment]
PHP 7.4 (ea-php74)
Server information in Cpanel shows "exim (exim-4.93-5.cp1186.x86_64)".
It is possible the server to accept only ASCII  symbols before @. Is it possible to be added some code to convert UTF-8 to ASCII punycode, as an option in RoundCube settings?

**Comment by alecpl** [comment]
I think punnycode is for domains only. You could write a plugin, but first better make sure it's gonna work on the imap side.

**Comment by alecpl** [comment]
Also, does it work with any other IMAP client?

**Comment by diancho** [comment]
I haven't found mail client that accept utf-8 in email address before @.

**Comment by diancho** [comment]
I can login with ascii username and utf-8 domain name. I would like utf-8 to can be used for all email name parts, and if the server can't accept it the email client to can convert the name.

**Comment by alecpl** [comment]
But to me it sounds like a non-standard thing and very imap backend specific. So, I propose to write a plugin using `storage_connect` hook.
