### ISSUE TITLE
paste from Excel looses formatting

### ISSUE THREAD

**Issue by hicheer** [roundcube/roundcubemail#7482]
Roundcube Webmail 1.4.7
tinymce.min.js  4.8.2
Send email page：
![image](https://user-images.githubusercontent.com/18565314/87127940-61973e80-c2c1-11ea-8992-b95284aecdfe.png)
excel ：
![image](https://user-images.githubusercontent.com/18565314/87127962-6eb42d80-c2c1-11ea-9158-06dadc6c3984.png)

**Comment by alecpl** [comment]
This will be TinyMCE issue, we can do not much about it. We could only update the editor to newer version. Does it work with https://www.tiny.cloud/docs/demo/full-featured/#fullfeaturednon-premiumplugins ?

**Comment by hicheer** [comment]
" Including Premium Plugins" is OK,like this
![image](https://user-images.githubusercontent.com/18565314/87129048-488f8d00-c2c3-11ea-9ce2-ea1b7da679b3.png)

how do I upgrade or replace with the latest version of tiny?

**Comment by alecpl** [comment]
We cannot update to premium plugins. Does it work with non-premium plugins?

**Comment by hicheer** [comment]
in "non-premium plugins" ,it's not work .
I have Tiny API key, how can i use it in roundcubemail ? thank you~~

**Comment by alecpl** [comment]
Sorry, you're on your own then. The editor initialization and setup is in program/js/editor.js.
