### ISSUE TITLE
mark email as not spam

### ISSUE THREAD

**Issue by marcosliell** [roundcube/roundcubemail#7484]
Good afternoon, I have a client that receives a lot of spam, probably fell on a mailing list.

I put in the SPAM settings in Cpanel a score of 1 to block SPAM. It turns out that many reliable emails go to the SPAM box.

I did not find any alternative that the user could mark as NOT SPAM a message in Webmail. Is there such an option? How to proceed? If I increase the score we will again receive rain of spam.

Can you give me an idea? Thank you.

**Comment by alecpl** [comment]
Check markasjunk plugin.
