### ISSUE TITLE
Unable to reply to HTML Formatted emails received from Outlook Mail Client

### ISSUE THREAD

**Issue by tashecooke** [roundcube/roundcubemail#7488]
I am running the latest version of Roundcube 1.4.7. on a Virtualmin Server install. 

I have now determined that when a user receives an email in Roundcube that is a HTML formatted email sent from a Outlook Mail Client and tries to reply - the sending message hangs for a few minutes and then errors with a "Requested Timed Out"msg. When this mail is converted to plain text you can reply without issues.

This does not happen for any HTML formatted mail received from Android Mail , Web Mail or GMail.

I have tried all three  User Interface Skins - all three have the same issue.

**Comment by alecpl** [comment]
This might be a HTML5 parser issue. Could you provide a sample? What PHP version?

**Comment by tashecooke** [comment]
Thanks for your response.
I am running PHP-FPM 7.4.8 Server.
For the sample , do wish to see the email Frame Source code?

**Comment by alecpl** [comment]
I wish to see the full email message source.

**Comment by tashecooke** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>Roundcube Webmail :: From Outlook Mail Client</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no, maximum-scale=1.0">
<meta name="theme-color" content="#f4f4f4">
<meta name="msapplication-navbutton-color" content="#f4f4f4">

	<link rel="shortcut icon" href="skins/elastic/images/favicon.ico?s=1594702112">

	<link rel="stylesheet" href="skins/elastic/deps/bootstrap.min.css?s=1594702112">
			<link rel="stylesheet" href="skins/elastic/styles/styles.css?s=1594702112">
		
	<link rel="stylesheet" type="text/css" href="plugins/jqueryui/themes/elastic/jquery-ui.css?s=1594702112">
<script src="program/js/jquery.min.js?s=1594702112"></script>
<script src="program/js/common.min.js?s=1594702112"></script>
<script src="program/js/app.min.js?s=1594702112"></script>
<script>
/*
        @licstart  The following is the entire license notice for the 
        JavaScript code in this page.

        Copyright (C) The Roundcube Dev Team

        The JavaScript code in this page is free software: you can redistribute
        it and/or modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation, either version 3 of
        the License, or (at your option) any later version.

        The code is distributed WITHOUT ANY WARRANTY; without even the implied
        warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        See the GNU GPL for more details.

        @licend  The above is the entire license notice
        for the JavaScript code in this page.
*/
var rcmail = new rcube_webmail();
rcmail.set_env({"task":"mail","standard_windows":false,"locale":"en_US","devel_mode":null,"rcversion":10407,"cookie_domain":"","cookie_path":"/","cookie_secure":true,"skin":"elastic","blankpage":"skins/elastic/watermark.html","refresh_interval":60,"session_lifetime":600,"action":"show","comm_path":"./?_task=mail","user_id":"eHdlBYO1A1Wy6hEy","compose_extwin":0,"date_format":"yy-mm-dd","date_format_localized":"YYYY-MM-DD","browser_capabilities":{"pdf":"1","flash":"0","tiff":"0","webp":"1"},"uid":"93","safemode":false,"message_context":null,"message_flags":["answered","seen","mdnsent"],"sender":"geoff.cooke@xtra.co.nz","mailbox":"INBOX","username":"administrator-nzwebxpress.com","permaurl":"./?_task=mail&_action=show&_uid=93&_mbox=INBOX","has_writeable_addressbook":true,"delimiter":".","mimetypes":["text/plain","text/html","image/jpeg","image/gif","image/png","image/bmp","image/tiff","image/webp","application/x-javascript","application/pdf","message/rfc822"],"read_when_deleted":true,"display_next":true,"drafts_mailbox":"Drafts","trash_mailbox":"Trash","junk_mailbox":"Junk","optional_format":"text","mailboxes":{"INBOX":{"id":"INBOX","name":"Inbox","virtual":false,"class":"inbox"},"Drafts":{"id":"Drafts","name":"Drafts","virtual":false,"class":"drafts"},"Sent":{"id":"Sent","name":"Sent","virtual":false,"class":"sent"},"Trash":{"id":"Trash","name":"Trash","virtual":false,"class":"trash"},"spam":{"id":"spam","name":"spam","virtual":false}},"mailboxes_list":["INBOX","Drafts","Sent","Trash","spam"],"request_token":"xZLcTBVanQBpVM5F6w62cuMusx17SxJr"});
rcmail.add_label({"loading":"Loading...","servererror":"Server Error!","connerror":"Connection Error (Failed to reach the server)!","requesttimedout":"Request timed out","refreshing":"Refreshing...","windowopenerror":"The popup window was blocked!","uploadingmany":"Uploading files...","uploading":"Uploading file...","close":"Close","save":"Save","cancel":"Cancel","alerttitle":"Attention","confirmationtitle":"Are you sure...","delete":"Delete","continue":"Continue","ok":"OK","checkingmail":"Checking for new messages...","deletemessage":"Delete message","movemessagetotrash":"Move message to trash","movingmessage":"Moving message(s)...","deletingmessage":"Deleting message(s)...","markingmessage":"Marking message(s)...","replyall":"Reply all","replylist":"Reply list","bounce":"Resend","bouncemsg":"Resend (bounce)","sendingmessage":"Sending message...","back":"Back","errortitle":"An error occurred!","options":"Options","plaintoggle":"Plain text","htmltoggle":"HTML","previous":"Previous","next":"Next","select":"Select","browse":"Browse","choosefile":"Choose file...","choosefiles":"Choose files...","purgefolderconfirm":"Do you really want to delete all messages in this folder?","deletemessagesconfirm":"Do you really want to delete selected message(s)?","viewsource":"Show source","arialabelmessageheaders":"Message headers"});
rcmail.gui_container("taskbar","taskmenu");
rcmail.gui_container("toolbar","mailtoolbar");
rcmail.gui_container("forwardmenu","forward-menu");
rcmail.gui_container("replyallmenu","replyall-menu");
rcmail.gui_container("messagemenu","message-menu");
rcmail.gui_container("markmenu","markmessage-menu");
rcmail.gui_container("headerlinks","header-links");
rcmail.gui_container("attachmentmenu","attachmentmenu");
rcmail.gui_container("mailtomenu","mailto-menu");rcmail.register_button('compose', 'rcmbtn100', 'link', '', '', '');
rcmail.register_button('mail', 'rcmbtn101', 'link', '', 'mail selected', '');
rcmail.register_button('addressbook', 'rcmbtn102', 'link', '', 'contacts selected', '');
rcmail.register_button('settings', 'rcmbtn103', 'link', '', 'settings selected', '');
rcmail.register_button('logout', 'rcmbtn105', 'link', '', '', '');
rcmail.register_button('compose', 'rcmbtn106', 'link', '', '', '');
rcmail.register_button('reply', 'rcmbtn107', 'link', 'reply', '', '');
rcmail.register_button('reply-all', 'rcmbtn108', 'link', 'reply-all', '', '');
rcmail.register_button('forward', 'rcmbtn109', 'link', 'forward', '', '');
rcmail.register_button('delete', 'rcmbtn110', 'link', 'delete', '', '');
rcmail.register_button('print', 'rcmbtn111', 'link', 'print', '', '');
rcmail.register_button('previousmessage', 'rcmbtn112', 'link', 'prev', '', '');
rcmail.register_button('nextmessage', 'rcmbtn113', 'link', 'next', '', '');
rcmail.register_button('forward-inline', 'rcmbtn114', 'link', 'forward inline active', '', '');
rcmail.register_button('forward-attachment', 'rcmbtn115', 'link', 'forward attachment active', '', '');
rcmail.register_button('bounce', 'rcmbtn116', 'link', 'forward bounce active', '', '');
rcmail.register_button('reply-all', 'rcmbtn117', 'link', 'reply all active', '', '');
rcmail.register_button('reply-list', 'rcmbtn118', 'link', 'reply list active', '', '');
rcmail.register_button('print', 'rcmbtn119', 'link', 'print active', '', '');
rcmail.register_button('download', 'rcmbtn120', 'link', 'download active', '', '');
rcmail.register_button('edit', 'rcmbtn121', 'link', 'edit asnew active', '', '');
rcmail.register_button('viewsource', 'rcmbtn122', 'link', 'source active', '', '');
rcmail.register_button('move', 'rcmbtn123', 'link', 'move active', '', '');
rcmail.register_button('copy', 'rcmbtn124', 'link', 'copy active', '', '');
rcmail.register_button('open', 'rcmbtn125', 'link', 'extwin active', '', '');
rcmail.register_button('mark', 'rcmbtn126', 'link', 'read active', '', '');
rcmail.register_button('mark', 'rcmbtn127', 'link', 'unread active', '', '');
rcmail.register_button('mark', 'rcmbtn128', 'link', 'flag active', '', '');
rcmail.register_button('mark', 'rcmbtn129', 'link', 'unflag active', '', '');
rcmail.register_button('extwin', 'rcmbtn130', 'link', '', '', '');
rcmail.register_button('change-format', 'rcmbtn131', 'link', '', '', '');
rcmail.gui_object('remoteobjectsmsg', 'remote-objects-message');
rcmail.register_button('open-attachment', 'attachmenuopen', 'link', 'extwin active', '', '');
rcmail.register_button('download-attachment', 'attachmenudownload', 'link', 'download active', '', '');
rcmail.gui_object('message', 'messagestack');
</script>

<script src="plugins/jqueryui/js/jquery-ui.min.js?s=1594702112"></script>

</head>
<body class="task-mail action-show">
			<div id="layout">
	
<div id="layout-menu">
	<h2 id="aria-label-tasknav" class="voice">Application tasks</h2>
	<div class="popover-header">
		<img src="skins/elastic/images/logo.svg?s=1594702112" id="logo" alt="Logo">
		<a class="button icon cancel"><span class="inner">Close</span></a>
	</div>
	<div id="taskmenu" class="menu toolbar" role="navigation" aria-labelledby="aria-label-tasknav">
		<span class="action-buttons">
							<a class="compose" title="Create a new message" data-fab="true" data-fab-task="mail" data-fab-action="none" id="rcmbtn100" role="button" href="./?_task=mail&amp;_action=compose" onclick="return rcmail.command('compose','',this,event)"><span class="inner">Compose</span></a>
					</span>
					<a class="mail" id="rcmbtn101" role="button" href="./?_task=mail" onclick="return rcmail.command('switch-task','mail',this,event)"><span class="inner">Mail</span></a>
				<a class="contacts" id="rcmbtn102" role="button" href="./?_task=addressbook" onclick="return rcmail.command('switch-task','addressbook',this,event)"><span class="inner">Contacts</span></a>
		
		<a class="settings" id="rcmbtn103" role="button" href="./?_task=settings" onclick="return rcmail.command('switch-task','settings',this,event)"><span class="inner">Settings</span></a>
		<span class="special-buttons">
			<a class="about" onclick="UI.about_dialog(this)" id="rcmbtn104" role="button" href="#"><span class="inner">About</span></a>
			<a class="logout" id="rcmbtn105" role="button" href="./?_task=logout" onclick="return rcmail.command('switch-task','logout',this,event)"><span class="inner">Logout</span></a>
		</span>
	</div>
</div>




<h1 class="voice">Message preview</h1>

<div id="layout-content" class="selected">
			<h2 id="aria-label-toolbar" class="voice">Application toolbar</h2>
		<div class="header" role="toolbar" aria-labelledby="aria-label-toolbar">
			<a class="button icon back-list-button" href="#back"><span class="inner">Back</span></a>
			<span class="header-title"></span>
			
<div id="mailtoolbar" class="toolbar menu" role="toolbar">
	<a class="compose hidden" title="Create a new message" id="rcmbtn106" role="button" href="./?_task=mail&amp;_action=compose" onclick="return rcmail.command('compose','',this,event)"><span class="inner">Compose</span></a>
	<a class="reply disabled" title="Reply to sender" data-content-button="true" id="rcmbtn107" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('reply','',this,event)"><span class="inner">Reply</span></a>
	<span class="dropbutton">
		<a class="reply-all disabled" title="Reply to list or to sender and all recipients" id="rcmbtn108" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('reply-all','',this,event)"><span class="inner">Reply all</span></a>
		<a href="#reply-all" id="replyallmenulink" class="dropdown" data-popup="replyall-menu" tabindex="0">
			<span class="inner">Reply-all options</span>
		</a>
	</span>
	<span class="dropbutton">
		<a class="forward disabled" title="Forward the message" id="rcmbtn109" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('forward','',this,event)"><span class="inner">Forward</span></a>
		<a href="#forward" id="forwardmenulink" class="dropdown" data-popup="forward-menu" tabindex="0">
			<span class="inner">Forwarding options</span>
		</a>
	</span>
	<span class="spacer"></span>
	<a class="delete disabled" title="Delete message" id="rcmbtn110" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('delete','',this,event)"><span class="inner">Delete</span></a>
			<a class="print disabled" title="Print this message" data-hidden="small" id="rcmbtn111" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('print','',this,event)"><span class="inner">Print</span></a>
		
	<a id="markmessagemenulink" class="markmessage" title="Mark messages" data-popup="markmessage-menu" role="button" href="#"><span class="inner">Mark</span></a>
	<a id="messagemenulink" class="more" title="More actions..." data-popup="message-menu" role="button" href="#"><span class="inner">More</span></a>
			<span class="spacer"></span>
		<a class="prev disabled" title="Show previous message" data-hidden="small" id="rcmbtn112" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('previousmessage','',this,event)"><span class="inner">Previous</span></a>
		<a class="next disabled" title="Show next message" data-hidden="small" id="rcmbtn113" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('nextmessage','',this,event)"><span class="inner">Next</span></a>
	</div>

<div id="forward-menu" class="popupmenu">
	<h3 id="aria-label-forward-menu" class="voice">Forwarding options</h3>
	<ul class="menu listing" role="menu" aria-labelledby="aria-label-forward-menu">
		<li role="menuitem"><a class="forward inline disabled" id="rcmbtn114" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('forward-inline','sub',this,event)">Forward inline</a></li>
		<li role="menuitem"><a class="forward attachment disabled" id="rcmbtn115" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('forward-attachment','sub',this,event)">Forward as attachment</a></li>
		<li role="menuitem"><a class="forward bounce disabled" id="rcmbtn116" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('bounce','',this,event)">Resend (bounce)</a></li>
		
	</ul>
</div>

<div id="replyall-menu" class="popupmenu">
	<h3 id="aria-label-replyall-menu" class="voice">Reply-all options</h3>
	<ul class="menu listing" role="menu" aria-labelledby="aria-label-replyall-menu">
		<li role="menuitem"><a class="reply all disabled" id="rcmbtn117" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('reply-all','sub',this,event)">Reply all</a></li>
		<li role="menuitem"><a class="reply list disabled" id="rcmbtn118" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('reply-list','sub',this,event)">Reply list</a></li>
		
	</ul>
</div>

<div id="message-menu" class="popupmenu">
	<h3 id="aria-label-message-menu" class="voice">More message actions</h3>
	<ul class="menu listing" role="menu" aria-labelledby="aria-label-message-menu">
		<li role="menuitem"><a class="print disabled" data-hidden="small" id="rcmbtn119" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('print','',this,event)">Print this message</a></li>
				<li role="menuitem"><a class="download disabled" id="rcmbtn120" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('download','',this,event)">Export</a></li>
		<li role="menuitem"><a class="edit asnew disabled" id="rcmbtn121" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('edit','new',this,event)">Edit as new</a></li>
		<li role="menuitem"><a class="source disabled" id="rcmbtn122" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('viewsource','',this,event)">Show source</a></li>
		<li role="menuitem"><a class="move disabled" aria-haspopup="true" id="rcmbtn123" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('move','',this,event)"><span class="folder-selector-link">Move to...</span></a></li>
		<li role="menuitem"><a class="copy disabled" aria-haspopup="true" id="rcmbtn124" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('copy','',this,event)"><span class="folder-selector-link">Copy to...</span></a></li>
		<li role="menuitem"><a target="_blank" class="extwin disabled" data-hidden="small" id="rcmbtn125" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('open','',this,event)">Open in new window</a></li>
		
	</ul>
</div>

<div id="markmessage-menu" class="popupmenu">
	<h3 id="aria-label-markmessage-menu" class="voice">Mark selected messages as...</h3>
	<ul class="menu listing" role="menu" aria-labelledby="aria-label-markmessage-menu">
		<li role="menuitem"><a class="read disabled" id="rcmbtn126" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('mark','read',this,event)">As read</a></li>
		<li role="menuitem"><a class="unread disabled" id="rcmbtn127" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('mark','unread',this,event)">As unread</a></li>
		<li role="menuitem"><a class="flag disabled" id="rcmbtn128" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('mark','flagged',this,event)">As flagged</a></li>
		<li role="menuitem"><a class="unflag disabled" id="rcmbtn129" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('mark','unflagged',this,event)">As unflagged</a></li>
		
	</ul>
</div>


		</div>
		<div class="content frame-content" role="main">
		<div id="message-header">
			<h2 class="subject">
				<span class="voice">Subject: </span>
				From Outlook Mail Client
									<a class="extwin" title="Open in new window" data-hidden="small" id="rcmbtn130" role="button" href="./?_task=mail&amp;_action=show&amp;_uid=93&amp;_mbox=INBOX" onclick="return rcmail.command('extwin','',this,event)"><span class="inner">Open in new window</span></a>
							</h2>
			<div class="short-header">
				<img src="./?_task=addressbook&amp;_action=photo&amp;_email=geoff.cooke%40xtra.co.nz&amp;_error=1" alt="Contact photo" class="contactphoto" onerror="this.src = 'skins/elastic/images/contactpic.svg'; this.onerror = null">
				<div class="header-content">
					<div class="header-subject"><span>From <span class="adr"><a href="mailto:geoff.cooke@xtra.co.nz" class="rcmContactAddress" onclick="return rcmail.command('compose','geoff.cooke@xtra.co.nz',this)" title="geoff.cooke@xtra.co.nz">geoff.cooke@xtra.co.nz</a><a href="#add" title="Add to address book" class="rcmaddcontact" onclick="return rcmail.command('add-contact','geoff.cooke@xtra.co.nz',this)"></a></span> on <span class="text-nowrap">2020-07-16 08:55</span></span></div>

					<div class="message-partheaders hidden">
						<table class="headers-table"><tbody><tr><td class="header-title">From</td>
<td class="header from"><span class="adr"><a href="mailto:geoff.cooke@xtra.co.nz" class="rcmContactAddress" onclick="return rcmail.command('compose','geoff.cooke@xtra.co.nz',this)" title="geoff.cooke@xtra.co.nz">geoff.cooke@xtra.co.nz</a><a href="#add" title="Add to address book" class="rcmaddcontact" onclick="return rcmail.command('add-contact','geoff.cooke@xtra.co.nz',this)"></a></span></td>
</tr>
<tr><td class="header-title">To</td>
<td class="header to"><span class="adr"><a href="mailto:admin@nzwebxpress.com" class="rcmContactAddress" onclick="return rcmail.command('compose','admin@nzwebxpress.com',this)" title="admin@nzwebxpress.com">admin@nzwebxpress.com</a><a href="#add" title="Add to address book" class="rcmaddcontact" onclick="return rcmail.command('add-contact','admin@nzwebxpress.com',this)"></a></span></td>
</tr>
<tr><td class="header-title">Date</td>
<td class="header date">Today 08:55</td>
</tr>
</tbody>
</table>

						<a href="#all-headers" class="headers" onclick="return UI.headers_dialog()">All headers...</a>
					</div>
					<div class="header-links">
						<a href="#headers" class="envelope" onclick="return UI.headers_show(this)">Details</a>
						
													<a class="plain" title="Display in plain text format" id="rcmbtn131" role="button" href="#" onclick="return rcmail.command('change-format','text',this,event)"><span class="inner">Plain text</span></a>
						
						
					</div>
				</div>
			</div>
		</div>
		<div id="message-content">
			<div class="leftcol" role="region" aria-labelledby="aria-label-messageattachments">
				<h2 id="aria-label-messageattachments" class="voice">Attachments</h2>
				
			</div>
			<div class="rightcol" role="region" aria-labelledby="aria-label-messagebody">
				<h2 id="aria-label-messagebody" class="voice">Message Body</h2>
				<div id="message-objects">
<div id="remote-objects-message" class="notice" style="display: none"><span>To protect your privacy remote resources have been blocked.</span>&nbsp;<span class="boxbuttons"><a href="#loadremote" onclick="rcmail.command('load-remote')">Allow</a></span></div>
</div>

				<div id="messagebody"><div class="message-htmlpart" id="message-htmlpart1"><style type="text/css">@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}

#message-htmlpart1 div.rcmBody p.v1MsoNormal, #message-htmlpart1 div.rcmBody li.v1MsoNormal, #message-htmlpart1 div.rcmBody div.v1MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
#message-htmlpart1 div.rcmBody span.v1EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:black;
	font-weight:normal;
	font-style:normal;}
#message-htmlpart1 div.rcmBody .v1MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
#message-htmlpart1 div.rcmBody div.v1WordSection1
	{page:WordSection1;}</style>
<div class="rcmBody" lang="EN-GB" link="#0563C1" vlink="#954F72"><div class="v1WordSection1"><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black">Dear Webxpress administrator,</span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black"> </span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black">This is an email sent from a Windows10  OS Outlook Email Client.</span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black"> </span></p><p class="v1MsoNormal"><b><span style="font-size: 14.0pt; color: black">Please reply to determine if your RoundCube email client can send with this HTML message attached.</span></b></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black"> </span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black"> </span></p><p class="v1MsoNormal"><b><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB">Best Regards</span></b></p><p class="v1MsoNormal"><b><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB">cell.</span></b><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB"> 027 420 1346</span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB">P O Box 69071</span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB">Lincoln 7640</span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB">Canterbury</span></p><p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black; mso-fareast-language: EN-GB">New Zealand</span></p><p class="v1MsoNormal"> </p></div></div></div>
</div>

			</div>
		</div>
	</div>
</div>


<div id="attachmentmenu" class="popupmenu">
	<h3 id="aria-label-attachmentmenu" class="voice">Attachment options</h3>
	<ul class="menu listing" role="menu" aria-labelledby="aria-label-attachmentmenu">
		<li role="menuitem"><a id="attachmenuopen" class="extwin disabled" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('open-attachment','',this,event)">Open</a></li>
		<li role="menuitem"><a id="attachmenudownload" class="download disabled" role="button" tabindex="-1" aria-disabled="true" href="#" onclick="return rcmail.command('download-attachment','',this,event)">Download</a></li>
		
	</ul>
</div>

<div id="mailto-menu" class="popupmenu">
	<h3 id="aria-label-mailtomenu" class="voice">Email address options</h3>
	<ul class="menu listing" role="menu" aria-labelledby="aria-label-mailtomenu">
		<li role="menuitem"><a class="addressbook" id="rcmbtn132" role="button" tabindex="-1" aria-disabled="true" href="#">Add to address book</a></li>
		<li role="menuitem"><a class="compose" id="rcmbtn133" role="button" tabindex="-1" aria-disabled="true" href="#">Compose mail to</a></li>
		
	</ul>
</div>

</div>
<div id="messagestack"></div>
<script>
$(function() {
rcmail.init();
});
</script>



<script src="skins/elastic/deps/bootstrap.bundle.min.js?s=1594702112"></script>
<script src="skins/elastic/ui.min.js?s=1594702112"></script>

</body>
</html>

**Comment by alecpl** [comment]
Please, the email message. You can get it using More > Download menu.

**Comment by tashecooke** [comment]
The Download option only has source (.eml) , the Mbox format(.zip) & Maildir format (.zip) is not available ( these are Grey'd out) - I cannot copy the (.eml) as Git does not support this file format.

**Comment by tashecooke** [comment]
[From Outlook Mail Client.zip](https://github.com/roundcube/roundcubemail/files/4930016/From.Outlook.Mail.Client.zip)

**Comment by alecpl** [comment]
Works for me. Try with all plugins disabled. Check the log and browser console for errors.

**Comment by tashecooke** [comment]
Thanks, I will need to work on how to disable plugins - as I haven't enabled any , I guess there are default plugins.

**Comment by tashecooke** [comment]
Working through the Browser console for errors I found a 403 error for the server response to a Roundcube POST Request.
In looking through Network > Preview /Response for further detail, I have found it to be a Firewall Response( Wordfence ) to a XSS in POST body  - here is the WordPress back end firewall message :

**Wordfence  Traffic Blocking** 

Christchurch, New Zealand
/roundcube/?_task=mail&_unlock…	7/17/2020 7:22:22 PM	122.59.155.125	...125-adsl.sparkbb.co.nz	403	
Type: Blocked
Activity Detail
 Christchurch, New Zealand left https://nzwebxpress.com/roundcube/?_task=mail&_action=compose&_id=5835812945f11519e47581 and was blocked by firewall for XSS: Cross Site Scripting in POST body: _message=%3Cp%3E%26nbsp%3B%3C%2Fp%3E%0D%0A%3Cdiv%20id%3D%22_rc_sig%22%3E%26nbsp%3B%3C%2Fdiv%3E%0D%0A%3Cp%3E%2… at https://nzwebxpress.com/roundcube/?_task=mail&_unlock=loading1594970543024&_framed=1&_lang=en_GB
7/17/2020 7:22:22 PM (56 minutes ago)  
IP: 122.59.155.125 Hostname: 122-59-155-125-adsl.sparkbb.co.nz
Human/Bot: Human
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

What I am keen to understand is why this happens only to Outlook emails that I am replying to - as previously pointed out.

I would appreciate your insight before I exclude these parameters in Wordfence Filtering .

**Comment by alecpl** [comment]
It doesn't like the message content that you send, but I have no idea which part of it exactly. You might try to cut the HTML content part by part to see which one causes the issue. If you narrow the issue to some specific HTML code we would see if that's something we can do about. For now this is not Roundcube issue.

**Comment by tashecooke** [comment]
**The URL POST Request :**

_token: 8kGSUE1AoM99jHZ9D6QT5RP1i5o16jZu
_task: mail
_action: send
_id: 14750474785f12722f65c24
_attachments: 
_from: 2
_to: geoff.cooke@xtra.co.nz,
_cc: 
_bcc: 
_replyto: 
_followupto: 
_subject: Re: 
_draft_saveid: 
_draft: 
_is_html: 1
_framed: 1
_message: <p>&nbsp;</p>
<div id="_rc_sig">&nbsp;</div>
<p>&nbsp;</p>
<p id="reply-intro">On 2020-07-18 12:47, geoff.cooke@xtra.co.nz wrote:</p>
<blockquote>
<div id="replybody1">
<style type="text/css">@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4}

#replybody1 p.v1MsoNormal, #replybody1 li.v1MsoNormal, #replybody1 div.v1MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US}
#replybody1 span.v1EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:black;
	font-weight:normal;
	font-style:normal}
#replybody1 .v1MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt}
#replybody1 div.v1WordSection1
	{page:WordSection1}</style>
<div lang="EN-GB">
<div class="v1WordSection1">
<p class="v1MsoNormal"><span style="font-size: 12.0pt; color: black;">&nbsp;</span></p>
<p class="v1MsoNormal">&nbsp;</p>
</div>
</div>
</div>
</blockquote>
editorSelector: html
_mdn: 
_dsn: 
_priority: 0
_store_target: Sent

**The Encoded POST Request** 
(as you can see the message body is being picked up by Wordfence as a XSS ) 

_token: 8kGSUE1AoM99jHZ9D6QT5RP1i5o16jZu
_task: mail
_action: send
_id: 14750474785f12722f65c24
_attachments: 
_from: 2
_to: geoff.cooke%40xtra.co.nz%2C
_cc: 
_bcc: 
_replyto: 
_followupto: 
_subject: Re%3A+
_draft_saveid: 
_draft: 
_is_html: 1
_framed: 1
_message: %3Cp%3E%26nbsp%3B%3C%2Fp%3E%0D%0A%3Cdiv+id%3D%22_rc_sig%22%3E%26nbsp%3B%3C%2Fdiv%3E%0D%0A%3Cp%3E%26nbsp%3B%3C%2Fp%3E%0D%0A%3Cp+id%3D%22reply-intro%22%3EOn+2020-07-18+12%3A47%2C+geoff.cooke%40xtra.co.nz+wrote%3A%3C%2Fp%3E%0D%0A%3Cblockquote%3E%0D%0A%3Cdiv+id%3D%22replybody1%22%3E%0D%0A%3Cstyle+type%3D%22text%2Fcss%22%3E%40font-face%0D%0A%09%7Bfont-family%3A%22Cambria+Math%22%3B%0D%0A%09panose-1%3A2+4+5+3+5+4+6+3+2+4%7D%0D%0A%40font-face%0D%0A%09%7Bfont-family%3ACalibri%3B%0D%0A%09panose-1%3A2+15+5+2+2+2+4+3+2+4%7D%0D%0A%0D%0A%23replybody1+p.v1MsoNormal%2C+%23replybody1+li.v1MsoNormal%2C+%23replybody1+div.v1MsoNormal%0D%0A%09%7Bmargin%3A0cm%3B%0D%0A%09margin-bottom%3A.0001pt%3B%0D%0A%09font-size%3A11.0pt%3B%0D%0A%09font-family%3A%22Calibri%22%2Csans-serif%3B%0D%0A%09mso-fareast-language%3AEN-US%7D%0D%0A%23replybody1+span.v1EmailStyle17%0D%0A%09%7Bmso-style-type%3Apersonal-compose%3B%0D%0A%09font-family%3A%22Calibri%22%2Csans-serif%3B%0D%0A%09color%3Ablack%3B%0D%0A%09font-weight%3Anormal%3B%0D%0A%09font-style%3Anormal%7D%0D%0A%23replybody1+.v1MsoChpDefault%0D%0A%09%7Bmso-style-type%3Aexport-only%3B%0D%0A%09font-family%3A%22Calibri%22%2Csans-serif%3B%0D%0A%09mso-fareast-language%3AEN-US%7D%0D%0A%40page+WordSection1%0D%0A%09%7Bsize%3A612.0pt+792.0pt%3B%0D%0A%09margin%3A72.0pt+72.0pt+72.0pt+72.0pt%7D%0D%0A%23replybody1+div.v1WordSection1%0D%0A%09%7Bpage%3AWordSection1%7D%3C%2Fstyle%3E%0D%0A%3Cdiv+lang%3D%22EN-GB%22%3E%0D%0A%3Cdiv+class%3D%22v1WordSection1%22%3E%0D%0A%3Cp+class%3D%22v1MsoNormal%22%3E%3Cspan+style%3D%22font-size%3A+12.0pt%3B+color%3A+black%3B%22%3E%26nbsp%3B%3C%2Fspan%3E%3C%2Fp%3E%0D%0A%3Cp+class%3D%22v1MsoNormal%22%3E%26nbsp%3B%3C%2Fp%3E%0D%0A%3C%2Fdiv%3E%0D%0A%3C%2Fdiv%3E%0D%0A%3C%2Fdiv%3E%0D%0A%3C%2Fblockquote%3E
editorSelector: html
_mdn: 
_dsn: 
_priority: 0
_store_target: Sent
