### ISSUE TITLE
PHP Error: Failed to load plugin file...

### ISSUE THREAD

**Issue by eltitobarte** [roundcube/roundcubemail#7490]
Hi.
Today I got this error in the RoundCube Log.
The problem is that I cannot even add contacts, I cannot send messages only receive. When I do any of these actions in XHR it shows error 503 Service unavailable.
This error already came out once and somehow it was solved, everything worked correctly so far, today this error presented itself. I have checked the errors for the log, I have deactivated all the plugins to check if any fails, but the error persists. I have contacted my mail server provider and it tells me that everything is correct, that it must be a RoundCube problem. I don't know what to do, I can't find a solution for this error anywhere.
What can be?
Thank you.

**Comment by alecpl** [comment]
What version? What is the full error message?

**Comment by eltitobarte** [comment]
Version 1.4.6 RoundCube.

[16-Jul-2020 11:07:09 +0200]: PHP Error: Failed to load plugin file /home/strato/http/power/rid/09/14/510420914/htdocs/mail/plugins/image_paster/image_paster.php in /mnt/web521/e3/14/510420914/htdocs/mail/program/lib/Roundcube/rcube_plugin_api.php on line 182 (POST /?_task=mail&_action=refresh)

And this is the XHR error:
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by alecpl** [comment]
You should update to 1.4.7. The service unavailable problem is probably not related and is more a http server/environment issue not Roundcube issue.

**Comment by eltitobarte** [comment]
> 
> 
> You should update to 1.4.7. The service unavailable problem is probably not related and is more a http server/environment issue not Roundcube issue.

I just update to RC 1.4.7 and the problem persists.
