### ISSUE TITLE
Cannot see email field in filters

### ISSUE THREAD

**Issue by bcraigie** [roundcube/roundcubemail#7498]
![image](https://user-images.githubusercontent.com/18425507/87869925-ac891400-c99b-11ea-8d71-b7f08fa5ce0f.png)

The image above shows what I see in Roundcube (Roundcube Webmail 1.4.6 on Plesk) when using a filter that is set up to run when from, to or cc contains a specific email address.  The box that contains the email address is too small and although it does contain data and the rule works, the email address cannot be seen or edited in the Webmail.

I can edit the rule in Sieve ok.  This is the rule (personal details redacted) so you can recreate the problem

# rule:[Test]
if anyof (header :contains ["From","To","cc"] "test@test.com", header :contains ["From","To","cc"] "test1@test.com")
{
	fileinto "INBOX.Test.Test2";
	notify :importance "2" :message "email from or to Test" "mailto:alert@test.com";
}

**Comment by alecpl** [comment]
What Roundcube version?

**Comment by alecpl** [comment]
Fixed.
