### ISSUE TITLE
Calendar plugin problem

### ISSUE THREAD

**Issue by grape6** [roundcube/roundcubemail#7499]
After last commits i've got errors in log (attached). Line numbers may be slightly  incorrect because of debug output.
Seems it's depends on 'Cache refactoring (#6312) (#6781)'

RCM git + contextmenu + calendar.
php 7.4.x

[error.log](https://github.com/roundcube/roundcubemail/files/4950325/error.log)

**Comment by alecpl** [comment]
Fixed.
