### ISSUE TITLE
Incorrect format=flowed behaviour on long HTML lines

### ISSUE THREAD

**Issue by mas90** [roundcube/roundcubemail#7504]
When I compose a HTML email in Roundcube, with send_format_flowed=true, the text/plain part does not have the correct trailing spaces needed for format=flowed:

 * Lines within a paragraph (which should be flowed together by the recipient) should have a trailing space; they do not
 * The end of a paragraph (which should NOT be flowed) should NOT have a trailing space, and yet it does

This causes MUAs which prefer the text/plain part, and which support format=flowed, to render the email in a very hard-to-read form: I see line breaks in the middle of paragraphs and no blank lines between paragraphs (because the previous line with an erroneous trailing space flows into them).

Example email (view using a text editor configured to show trailing spaces!): [roundcube-ff-bug.txt](https://github.com/roundcube/roundcubemail/files/4969424/roundcube-ff-bug.txt)

This should be visible as four distinct paragraphs, and indeed the raw text/plain part is formatted in this way.  It should also be wrapped to the full width of my window, since it uses format=flowed.  However, in Alpine, it looks like this: 
![Annotation 2020-07-23 235521](https://user-images.githubusercontent.com/556521/88346334-009b4c00-cd40-11ea-92f1-b1db908bfeaf.png)

The one line which *did* get flowed correctly only did so because the end of a sentence (after which I typed two spaces) happened to be at the end of a line after word wrapping.  The extra space that I typed between sentences took the place of the missing trailing space that Roundcube should have inserted.

**Comment by alecpl** [comment]
What version? Does it work if you do not use HTML editor?

**Comment by alecpl** [comment]
Anyway, I confirmed with git-master that this is the case. If you use plain text editor the format-flowed formatting is correct.

**Comment by alecpl** [comment]
Fixed.
