### ISSUE TITLE
Favicon not visible

### ISSUE THREAD

**Issue by cyklosklep-pl-Admin** [roundcube/roundcubemail#7506]
After recent update, the favicon is not visible. See attachment.
I've removed cookies and images associated with https://webmail.atthost.pl/

![Adnotacja 2020-07-24 095856](https://user-images.githubusercontent.com/65622422/88383834-8e605100-cdab-11ea-9472-98577ba69ad5.png)

**Comment by alecpl** [comment]
What version? I see you're using an external skin, this might be skin-specific issue. Does it happen with disabled all plugins and default skin(s)? What is set in `skin_logo` option?

**Comment by alecpl** [comment]
Anyway, I see `<link rel="shortcut icon" href="https://webmail.atthost.pl/images/logo2.png">` in the code. This is not Roundcube issue.

**Comment by cyklosklep-pl-Admin** [comment]
OK. Thanks for clarifying the issue.
