### ISSUE TITLE
Error in DDL upgrade

### ISSUE THREAD

**Issue by fernando-sianet** [roundcube/roundcubemail#7508]
Hi, 

how can i resolve this error?
best regards

`bin/installto.sh /var/www/roundcube-test/`
`Target installation already in version 1.4.7. Do you want to update again? (y/N)`
`y`
`Copying files to target location....htaccess.new`
`done.`

`NOTICE: New .htaccess file saved as .htaccess.new.`
`NOTICE: JavaScript dependencies installation skipped.`
`NOTICE: The 'installer' directory still exists. You should remove it after the upgrade.`

`Running update script at target...`
`Executing database schema update.`
`Updating database schema (2015111100)... [FAILED]`
`ERROR: Error in DDL upgrade 2015111100: [1060] Duplicate column name 'failed_login'`
`All done.`

**Comment by alecpl** [comment]
What version did you upgrade from?

Looks like the Information in `system` table is wrong. You'll have to fix it manually. Execute "UPDATE `system` SET `value` = '2015111100' WHERE `name` = 'roundcube-version';` Do the same if the error appears again (with a different version string).

**Comment by fernando-sianet** [comment]
> What version did you upgrade from?
> 
> Looks like the Information in `system` table is wrong. You'll have to fix it manually. Execute "UPDATE `system` SET `value` = '2015111100' WHERE `name` = 'roundcube-version';` Do the same if the error appears again (with a different version string).

**Comment by fernando-sianet** [comment]
Hi,

Version is roundcubemail-1.4.4

**Comment by alecpl** [comment]
There's really not much we can do about this.

**Comment by jsoref** [comment]
Fwiw, I hit what appears to be this same error:
> 2021-04-11 02:29:03 upgrade roundcube:all 1.2~beta+dfsg.1-0ubuntu1 1.3.6+dfsg.1-1

```
MariaDB [roundcube]> select value from system where name='roundcube-version';
+------------+
| value      |
+------------+
| 2015111100 |
+------------+
1 row in set (0.00 sec)
```
