### ISSUE TITLE
Read Receipt

### ISSUE THREAD

**Issue by gtowntool** [roundcube/roundcubemail#7511]
I cannot find the Read Receipt option.  I've always had it and now it is missing.  I have look everywhere, even in settings.

**Comment by alecpl** [comment]
Someone added these config options to `dont_override`? Otherwise I don't know why you wouldn't see them.

**Comment by gtowntool** [comment]
Where do we change this?

Justin VanMeter
President
Georgetown Tool and Manufacturing, Inc
515 Bourbon St. Georgetown, KY 40324
p: 502.863.4020
f: 502.863.4002
www.gtm-cncmachining.com

**Comment by alecpl** [comment]
In the config file. Please, ask such simple question on mailing list or forum.

**Comment by gtowntool** [comment]
WHERE is the config file ?

Justin VanMeter
President
Georgetown Tool and Manufacturing, Inc
515 Bourbon St. Georgetown, KY 40324
p: 502.863.4020
f: 502.863.4002
www.gtm-cncmachining.com

**Comment by thomascube** [comment]
Please contact your internet hosting provider or IT responsible for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Roundcube is not a service but free software which your hosting provider installed on their servers.
