### ISSUE TITLE
date.timezone set @ php.ini, but not found by RC installer ?

### ISSUE THREAD

**Issue by pgnd** [roundcube/roundcubemail#7513]
i run
```
	php -v
		PHP 7.4.8 (cli) (built: Jul  9 2020 08:57:23) ( NTS )
		Copyright (c) The PHP Group
		Zend Engine v3.4.0, Copyright (c) Zend Technologies
		    with Zend OPcache v7.4.8, Copyright (c), by Zend Technologies
```

on
```
	grep PRETTY /etc/os-release
		PRETTY_NAME="Fedora 32 (Thirty Two)"
```

i'm installing RC 1.4.7 tag
```
	git log -n1
      1 commit cdbefb54e2bebbc61e5fb081c7d1038d884743cf (HEAD, tag: 1.4.7)
      2 Author: Thomas Bruederli <thomas@roundcube.net>
      3 Date:   Sat Jul 4 12:32:28 2020 +0200
      4
      5     Bump version to 1.4.7
```

i've added 'date.timezone' config
```
	/usr/local/etc/php7/conf.d/date.ini
		date.timezone = America/Los_Angeles
```

such that,
```
	php -i | egrep -i "^tz|^date.timezone"
		date.timezone => America/Los_Angeles => America/Los_Angeles
		TZ => America/Los_Angeles
```

@ RC installer check, I'm all 'green' -- all resources found -- except
```
	The following settings are optional and recommended:
		allow_url_fopen:  OK
>>>		date.timezone:  NOT OK(not set)
```

It doesn't appear fatal, but it _is_ set.

bug?  or is additional config needed to make RC 'aware' of the "date.timezone" setting?

**Comment by alecpl** [comment]
There's no additional config. Did you restart http server? Maybe the config is set for cli only and there's another file for non-cli use?

**Comment by pgnd** [comment]
> There's no additional config.

got it

> Did you restart http server?

yep.

> Maybe the config is set for cli only and there's another file for non-cli use?

No, this config is certainly the web-/non-cli- config ... any/all changes to it _are_picked up, and seen, e.g., in phpinfo()' display in the UI as well.

**Comment by alecpl** [comment]
What installer does is:
```
$tz = ini_get('date.timezone');
```
If you see the "not set" that means the $tz is empty. SO, whatever is causing that I don't think this is Roundcube's fault.
