### ISSUE TITLE
Improve documentation to bin/updatedb.sh in UPGRADING

### ISSUE THREAD

**Issue by Zocker1999NET** [roundcube/roundcubemail#7515]
I was about to submit an issue requesting for a script that enables me to "say" to any Roundcube instance on my server: "I do not know which version you have had before, but please look it up yourself and upgrade your database accordingly, and if no update is required, do not complain too" for a setup I describe below. However now I've looked up what scripts you distribute with Roundcube and found out that `bin/updatedb.sh` does already do that. However it is not documented in the wiki or README or UPGRADING file. I would like to read about the script in the UPGRADING file because it is another way to upgrade to a new version of Roundcube if updating / replacing the files is no problem (like in my setup because distributed files, configuration files and working files are separated into different directories yet accessible together for the web server) and updating the dependencies / JS files / CSS files will be done automatically because I will use the version my distribution (Debian) does install using the package manager.

FYI my setup: I want to host multiple Roundcube instances on the same system using different databases. To save storage and, more important, to save time I want to use an [overlay filesystem](https://en.wikipedia.org/wiki/OverlayFS) for each root directory. All overlays will use the same lowerdirs containing Roundcube's and plugin's files but each overlay will have its own upperdir containing configuration and log files. This simplifies upgrading Roundcube and also adding new plugins, but requires (to reduce complexity) that Roundcube can check for itself if the database requires an upgrade and does that automatically. My goal is to let all services upgrade theirself (after backups were made, of course!) and I only want to do something manually if I want to change the configuration or if some service failed.

**Comment by alecpl** [comment]
Done.

**Comment by Zocker1999NET** [comment]
@alecpl Thanks!
