### ISSUE TITLE
Thanks! roundcubemail/SQL/sqlite/2020020100.sql deleted all my users!

### ISSUE THREAD

**Issue by smartbyte** [roundcube/roundcubemail#7516]
Script roundcubemail/SQL/sqlite/2020020100.sql is broken!

There are two "drop table users" in there....

All my users gone! Thanks!

**Comment by trasherdk** [comment]
Just restore from the backup mentioned in the first paragraph of the [UPGRADING](https://github.com/roundcube/roundcubemail/blob/master/UPGRADING) document.
```
UPGRADING instructions
======================

Follow these instructions if upgrading from a previous version
of Roundcube Webmail. We recommend to carefully backup the existing
installation as well as the database before going through the following steps.
```

**Comment by alecpl** [comment]
Thanks for testing the development version. Fixed.

**Comment by smartbyte** [comment]
> Just restore from the backup mentioned in the first paragraph of the [UPGRADING](https://github.com/roundcube/roundcubemail/blob/master/UPGRADING) document.
> 
> ```
> UPGRADING instructions
> ======================
> 
> Follow these instructions if upgrading from a previous version
> of Roundcube Webmail. We recommend to carefully backup the existing
> installation as well as the database before going through the following steps.
> ```

Thanks for the hint.

**Comment by smartbyte** [comment]
> Thanks for testing the development version. Fixed.

Awesome, I have not dreamt of such a quick fix: Thanks for recognizing and fixing this little mistake. :-)
