### ISSUE TITLE
Properly configure password change plugin on cpanel server

### ISSUE THREAD

**Issue by samuelmf** [roundcube/roundcubemail#7521]
Hi guys what steps i need to do to configure properly the plugin to change the users email password on server with a cpanel?

**Comment by alecpl** [comment]
Read the password plugin README file. There are two drivers that you can use, which you have to configure.

**Comment by samuelmf** [comment]
Hi, thanks for reply i properly configured the plugin now, it's working fine.
The only thing that i need to do is configure proper parameters under cpanel section and change the driver type to
$config['password_driver'] = 'cpanel_webmail';
