### ISSUE TITLE
Incorrect conversion of email addresses to mailto links in plain text messages

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7526]
In plain text messages, email addresses enclosed in single quotes are incorrectly converted to mailto links on message preview. 
For example:

`'mail@example.net' `

is converted to

`<a href="mailto:'mail@example.net" onclick="return rcmail.command('compose','\'mail@example.net',this)">'mail@example.net</a>` - leading ' is added to the mailto link. 

![image](https://user-images.githubusercontent.com/44122211/89034204-2e385480-d341-11ea-9db9-b3de309bab36.png)

Roundcube 1.3 & 1.4

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Problem here is that an apostrophe character is a valid character in a local part of the email address. We have to make the rules more strict for this use case.

**Comment by alecpl** [comment]
Fixed.
