### ISSUE TITLE
Issue with option - Forward

### ISSUE THREAD

**Issue by KylosAdmin** [roundcube/roundcubemail#7532]
Hello,

Whenever our clients are trying to forward a message with an attachment (Forward Inline) it is impossible to do so other than doing it by:
-Forward as attachment - That option is causing that every e-mail that's being sent is getting rejected because of the .eml file
-Resend (Bounce) - Only allowing user to resend e-mail with the exact same date that they received/sent an e-mail.
Which is causing alot of troubles for our clients to forward message properly, as Forward Inline option should  already contain attachment for the e-mail instead of just copying the content of the message without it.
Can you please take a look at it?

Best Regards
---
Szymon Kiciak
Kylos sp. z o.o.
http://www.kylos.pl

**Comment by alecpl** [comment]
What exactly do you mean by "it's impossible"? What happens? What version? What error? What plugins? What PHP/OS version?

**Comment by KylosAdmin** [comment]
Hello,

Version of the Roundcube - 1.4.4
When client is trying to forward message through "forward inline" there is no attachment in the message that's being forwarded. (Original message contains attachments such as images).
Error occurs when you are attempting to send an e-mail as an attachment - It gets rejected because message contains .eml file as an attachment
Exact error message:
`This message has been rejected because it has
    a potentially executable attachment message_rfc822.eml
    This form of attachment has been used by
    recent viruses or other malware.
    If you meant to send this file then please
    package it up as a zip file and resend it.` 

Plugin list:
`archive | 3.4 | GPLv3+   
calendar | 3.5.3 | AGPLv3 
carddav | 3.0.3 | GPL-2.0 
cpanellogin | 11.58 | cPanel License (Proprietary)
cpanellogout | 11.58 | cPanel License (Proprietary)
filesystem_attachments | 1.0 | GPLv3+ 
jqueryui | 1.12.0 | GPLv3+   
libcalendaring | 3.5.2 | AGPLv3 
libkolab | 3.5.3 | AGPLv3 
return_to_webmail | 11.88 | cPanel License (Proprietary)`

OS: CloudLinux 7.8

**Comment by alecpl** [comment]
Please, update. There were some fixes regarding forwarding, As for the rejecting .eml attachments. I think your SMTP server is too strict. I've never had a problem with forward as attachment feature.

**Comment by KylosAdmin** [comment]
Hello,


Maybe I will try to explain by example.

Our Roundcube information, see Screenshot_43.png.

There is a message in inbox with attachment, see Screenshot_44.png

When you try to forward message by option Forward is opening the frame like that: Screenshot_45.png.

As you can see attachment is not added (rex box).

Using another option available like: Forward as attachment or Bounce, it's not suit our needs, because is adding (as should be) a .eml attachment.


The option what is interesting us is like in Thunderbird standard Forward, when you are forwarding mail with added original attachments.

We have problem with that.


Can you help us?

I can put additional information, another webmail application is creating this mail as should be, but if you think that is something wrong with our server setting, give us some advice please.

Grateful

Ireneusz Jaszczak
Kylos Sp. z o.o.
https://www.kylos.pl

![Screenshot_43](https://user-images.githubusercontent.com/69229498/89630971-68a17480-d8a0-11ea-9a40-accb7cd5c737.png)
![Screenshot_44](https://user-images.githubusercontent.com/69229498/89630973-69d2a180-d8a0-11ea-886f-e0afab846fa0.png)
![Screenshot_45](https://user-images.githubusercontent.com/69229498/89630975-69d2a180-d8a0-11ea-8b8c-96011f0b1f99.png)

**Comment by alecpl** [comment]
1.4.4 is not the most recent version. Most recent version contains some fixes related to this issue.
