### ISSUE TITLE
Issue with option Forward part2

### ISSUE THREAD

**Issue by KylosAdmin** [roundcube/roundcubemail#7535]
Hello,

Maybe I will try to explain by example.

Our Roundcube information, see Screenshot_43.png.

There is a message in inbox with attachment, see Screenshot_44.png

When you try to forward message by option Forward is opening the frame like that: Screenshot_45.png.

As you can see attachment is not added (rex box).

Using another option available like: Forward as attachment or Bounce, it's not suit our needs, because is adding (as should be) a .eml attachment.

The option what is interesting us is like in Thunderbird standard Forward, when you are forwarding mail with added original attachments.

We have problem with that.

Can you help us?

I can put additional information, another webmail application is creating this mail as should be, but if you think that is something wrong with our server setting, give us some advice please.

Grateful

Ireneusz Jaszczak
Kylos Sp. z o.o.
https://www.kylos.pl

![Screenshot_43](https://user-images.githubusercontent.com/69229498/89646297-d313de00-d8bb-11ea-8b38-e67f58b2b35e.png)
![Screenshot_44](https://user-images.githubusercontent.com/69229498/89646301-d3ac7480-d8bb-11ea-86b9-831052d25f58.png)
![Screenshot_45](https://user-images.githubusercontent.com/69229498/89646303-d3ac7480-d8bb-11ea-8cec-6bdb59654f0f.png)

**Comment by alecpl** [comment]
First of all, you should upgrade Roundcube to most recent version. Second, provide a message source (you can remove data, but leave the original structure and headers).

**Comment by alecpl** [comment]
No feedback.
