### ISSUE TITLE
SMTP issues on v1.4.7 and Ubuntu20.04

### ISSUE THREAD

**Issue by zwamdurkel** [roundcube/roundcubemail#7536]
**System info:**
Ubuntu 20.04
PHP 7.4.3
Roundcube 1.4.7
MySQL 8.0.21
***
I've tried installing Roundcube multiple times using different guides on multiple machines on multiple networks, but something is obviously going wrong either with me or with Roundcube.
[guide 1](https://kifarunix.com/install-and-setup-roundcube-webmail-on-ubuntu-20-04/)
[guide 2](https://www.linuxbabe.com/ubuntu/install-roundcube-webmail-ubuntu-20-04-apache-nginx)
only change made was changing 1.4.6 to 1.4.7 in these guides.

Everything seems to be installed correctly. all the mails are retrieved from the mail server. IMAP seems to work correctly.
My problem starts when trying to _send_ an email.

The included "**Test SMTP config**" on the _domain.com/installer_ page works and I receive the email in the recipients inbox. (outlook mail client)
![image](https://user-images.githubusercontent.com/13705380/89713948-7f78c180-d99b-11ea-801c-a61106087a8c.png)
![image](https://user-images.githubusercontent.com/13705380/89713953-915a6480-d99b-11ea-9fbb-ba5e91246fee.png)

When I try to send an actual email using the normal web interface, however, the mail never gets send and "**Sending Message...**" is displayed in the bottom right corner until it eventually displays: "**Request Timed Out**".
I've tried using gmail and gandi mail as mailservers, but both have the same issue.
![image](https://user-images.githubusercontent.com/13705380/89715113-de423900-d9a3-11ea-9c0f-a9795a18f11d.png)
![image](https://user-images.githubusercontent.com/13705380/89715160-409b3980-d9a4-11ea-91b1-a4da64442d27.png)

These are my settings (gmail):
```php
$config['default_host'] = 'ssl://imap.gmail.com';
$config['default_port'] = 993;

$config['smtp_server'] = 'tls://smtp.gmail.com';
$config['smtp_port'] = 587;
$config['smtp_log'] = true;
```
(gandi according to https://docs.gandi.net/en/gandimail/standard_email_settings/#smtp-account): 
```php
$config['default_host'] = 'ssl://mail.gandi.net';
$config['default_port'] = 993;

$config['smtp_server'] = 'tls://mail.gandi.net';
$config['smtp_port'] = 587;
$config['smtp_log'] = true;
```
The error log doesn't display any messages and smtp.log only generates output when using the "**Test SMTP config**". Sending a mail using the default web interface doesn't post a single line in the log. Browser console is also empty.

Why this is strange: the test mail does get send, but normal mails fail to send.

I'm happy to provide additional information or even access to the server on which roundcube is installed.

\- Zwam

**Comment by alecpl** [comment]
You could try to enable smtp_debug, maybe this log will reveal something.

**Comment by zwamdurkel** [comment]
enabling `smtp_debug` does not generate a single line in the `logs/smtp.log`

**Comment by alecpl** [comment]
Check browser developer console for errors. Maybe it doesn't even hit the server.

**Comment by zwamdurkel** [comment]
"Browser console is also empty." I already said that in my original post.

Im sorry to waste your time but I can't be bothered trying to fix this anymore. I've switched to Nextcloud. both their integrated mail and Rainloop work flawlessly for me. I would have honestly prefered to use Roundcube, but I just can't get it to work.
