### ISSUE TITLE
Roundcube Multiple Emails

### ISSUE THREAD

**Issue by sarimdotali** [roundcube/roundcubemail#7537]
Please tell how can i add multiple email as many I want to use in single roundcube installation.
Thank You!

**Comment by alecpl** [comment]
Please, ask on mailing list or forum.

**Comment by sarimdotali** [comment]
Please tell me here

**Comment by trasherdk** [comment]
Your IMAP server must be configured for virtual user support.

**Comment by sarimdotali** [comment]
means that?
you are not answering me bro!
