### ISSUE TITLE
Unclosed <a> tag in hu_HU/labels.inc

### ISSUE THREAD

**Issue by rgergo67** [roundcube/roundcubemail#7538]
Hello,

in the following line there is a vcard link which is not closed. Because of this, the contact import form is not usable.

https://github.com/roundcube/roundcubemail/blob/ec4cc29c88519c1a10bdb6cd4516aea9b18ae0a9/program/localization/hu_HU/labels.inc#L438

The solution is to put a closing a tag after the word vCard, like this:

`'Feltölthetsz partnereket már létező címjegyzékből.<br/>Jelenleg a címeket importálni vagy <a href="https://en.wikipedia.org/wiki/VCard">vCard</a> vagy CSV(vesszővel-tagolt) formátumból lehet.';`

Best regards
Greg

**Comment by alecpl** [comment]
Fixed on Transifex, merged and backported to 1.4. Thanks.
