### ISSUE TITLE
Release 1.2.12 is impossible to download

### ISSUE THREAD

**Issue by mfrancka** [roundcube/roundcubemail#7542]
Hello,

It looks like release 1.2.12 is broken it cannot be downloaded from the page and also here it looks like it was done not for a good version:
https://github.com/roundcube/roundcubemail/releases/tag/1.2.12

Files are for version 1.4.8

**Comment by alecpl** [comment]
@thomascube fix that, please.

**Comment by thomascube** [comment]
Fixed. Apologies for the mistake!
