### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Hydranet** [roundcube/roundcubemail#7543]
Is there a way to donate to the roundcube project?

**Comment by alecpl** [comment]
I appreciate this rare question. We do not advertise for donations as we're not in need. @thomascube do you need any resources for the infra/domain etc.?

**Comment by Hydranet** [comment]
I'm just a single person who has been happily using roundcube for quite a while now, if you had a way to make donations I would be wanting to donate a small amount every now and then.

**Comment by thomascube** [comment]
@Hydranet Many thanks for your intention to support us! We don't need much funding as all of the infrastructure we're using is either sponsored or free to use for open source projects. Therefore I can only suggest to donate to organizations like [safe the children](https://www.savethechildren.org/) or [doctors without borders](https://www.msf.org/) instead.
