### ISSUE TITLE
Is "NOTICE: JavaScript dependencies installation skipped" harmless or not?

### ISSUE THREAD

**Issue by RalfJung** [roundcube/roundcubemail#7544]
Every time I update roundcube, the install script prints
```
NOTICE: JavaScript dependencies installation skipped
```
This is unsettling. Does this mean that there are some things that need updating/installing, but something went wrong and they have not been updated/installed? Or is this something I can just ignore? And if I can ignore it, then why does it tell me?

**Comment by alecpl** [comment]
It is harmless. We should probably improve this notice (or remove it), as well as this one "WARNING: JavaScript dependencies update skipped."

**Comment by alecpl** [comment]
Fixed.
