### ISSUE TITLE
Attachments Fail to Load on Roundcube

### ISSUE THREAD

**Issue by inceptiononlinemarketing** [roundcube/roundcubemail#7545]
A few of our clients are having attachments fail to load on Roundcube. I've had them try it on different browsers which sometimes fixes the issue, but the issue seems to persist on Edge and Chrome. 

Anyone have any ideas as to how to solve this?

Thanks

**Comment by alecpl** [comment]
What exactly happens (steps to reproduce, screenshots)? What kind of attachments? Anything in logs? Anything in browser console?

**Comment by inceptiononlinemarketing** [comment]
-- Please reply above this line --
-----------------------------------------------------------
## Jared replied, on Aug 13 @ 8:47am (CDT):

The file loads about halfway and then stops. It has happened with PDFs
that our clients need to send. They definitely don't exceed the
maximum size limit. I have checked the logs and I don't see any
errors. I haven't done anything in browser console, but will if I see
it again. 

Next time it happens I will try to record the screen/send screenshots.

Thanks for a quick reply!

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

Jared Lemon
YOUR ROCKIN' SUPPORT TEAM
https://www.inceptiononlinemarketing.com/chiropractic-websites/ [4]
support@inceptiononlinemarketing.com
1-920-857-1106


Links:
------
[1]
https://secure.helpscout.net/satisfaction/359565046/record/3590458750/1/
[2]
https://secure.helpscout.net/satisfaction/359565046/record/3590458750/2/
[3]
https://secure.helpscout.net/satisfaction/359565046/record/3590458750/3/
[4] https://www.inceptiononlinemarketing.com/


-----------------------------------------------------------
## Roundcube/roundcubemail sent a message, on Aug 13 @ 1:33am (CDT):



	What exactly happens (steps to reproduce, screenshots)? What kind of
attachments? Anything in logs? Anything in browser console? 

	-
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/7545#issuecomment-673290276
[2]

**Comment by inceptiononlinemarketing** [comment]
-- Please reply above this line --
-----------------------------------------------------------
## Jared replied, on Aug 14 @ 11:13am (CDT):

Here is a video of the problem. This happened on Microsoft Edge and
Chrome using both Horde and Roundcube.

It worked on Firefox

https://drive.google.com/file/d/1NzKErWMTokZkF_tDjjTogAVjokVUrzQX/view?usp=sharing
[1]



Links:
------
[1]
https://drive.google.com/file/d/1NzKErWMTokZkF_tDjjTogAVjokVUrzQX/view?usp=sharing


How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

Jared Lemon
YOUR ROCKIN' SUPPORT TEAM
https://www.inceptiononlinemarketing.com/chiropractic-websites/ [4]
support@inceptiononlinemarketing.com
1-920-857-1106


Links:
------
[1]
https://secure.helpscout.net/satisfaction/359565046/record/3594106991/1/
[2]
https://secure.helpscout.net/satisfaction/359565046/record/3594106991/2/
[3]
https://secure.helpscout.net/satisfaction/359565046/record/3594106991/3/
[4] https://www.inceptiononlinemarketing.com/


-----------------------------------------------------------
## Jared replied, on Aug 13 @ 8:47am (CDT):

The file loads about halfway and then stops. It has happened with PDFs
that our clients need to send. They definitely don't exceed the
maximum size limit. I have checked the logs and I don't see any
errors. I haven't done anything in browser console, but will if I see
it again. 

Next time it happens I will try to record the screen/send screenshots.

Thanks for a quick reply!
Jared Lemon
YOUR ROCKIN' SUPPORT TEAM
https://www.inceptiononlinemarketing.com/chiropractic-websites/ [1]
support@inceptiononlinemarketing.com
1-920-857-1106


Links:
------
[1] https://www.inceptiononlinemarketing.com/


-----------------------------------------------------------
## Roundcube/roundcubemail sent a message, on Aug 13 @ 1:33am (CDT):



	What exactly happens (steps to reproduce, screenshots)? What kind of
attachments? Anything in logs? Anything in browser console? 

	-
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub [1], or unsubscribe
[2].

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/7545#issuecomment-673290276
[2]

**Comment by alecpl** [comment]
If this happens also in Horde, then it's a problem with your environment not Roundcube.
