### ISSUE TITLE
Image in signature not displaying

### ISSUE THREAD

**Issue by webbox1** [roundcube/roundcubemail#7546]
Hi there,

I am not able to get an image to display in our customer's signature.

The service provider that hosts our customer's e-mail account  pointed us in the direction of the mail client.

Despite our customer adding an image (32kb .jpg) as their signature, it does not display when they compose e-mails nor does it display in resultant e-mails (only '--' displays).

Please let me know if you need to know anything else.

Many thanks in advance for your help.

Screenshot:

https://drive.google.com/file/d/1C4lBjqABJFn6qBbfNFM83DAYwaWT81Nv/view?usp=sharing

James,
web-box
james@webbox.co.za

**Comment by trasherdk** [comment]
![image](https://user-images.githubusercontent.com/5003891/90087383-d2a99600-dd46-11ea-9ec5-616ec09c7426.png)

**Comment by webbox1** [comment]
Thanks a million @trasherdk
