### ISSUE TITLE
Add variable in app.js to setup the ajax timeout upload file 

### ISSUE THREAD

**Issue by atomindtechnology** [roundcube/roundcubemail#7548]
in this function 

**this.file_upload = function(files, post_args, props)**

i would like to add 

as is
```
      this.uploads[ts] = $.ajax({
        type: 'POST',
        dataType: 'json',
        url: this.url(props.action || 'upload', args),
        contentType: false,
        processData: false,
        timeout: 0, // disable default timeout set in ajaxSetup()    <---------------------    $uploadAttachmentTimeout
```

to be

```
      this.uploads[ts] = $.ajax({
        type: 'POST',
        dataType: 'json',
        url: this.url(props.action || 'upload', args),
        contentType: false,
        processData: false,
        timeout: this.uploadAttachmentTimeout, // disable default timeout set in ajaxSetup()
```

At the top of app.js

`this.uploadAttachmentTimeout = 0; // 0 default`

because in this way we can control also the timeout client side

can this change be useful?

**Comment by alecpl** [comment]
What use-case do you have for this?

**Comment by atomindtechnology** [comment]
I'd like to be able to control the upload timeout on the client side, in order to terminate the request after 180 seconds, directly from the browser. 

In this way the error displayed on the GUI would be "Request Expired" which is what I expect. If I expire the request on NGINX / PHP-FPM, the error shown is 504 Bad Gateway

**Comment by atomindtechnology** [comment]
but above all this type of control is very precise and fast for managing the timeout without having to intervene on the backend

**Comment by alecpl** [comment]
Yes, but why would you do that?

**Comment by atomindtechnology** [comment]
the basic problem is that I want an upload request to expire after 180s. so if an upload does not end in 180s it must be blocked.

if I set the timeout parameters to nginx and fpm the error is 504 Bad Gateway (which is not very user-friendly). if the request expires on the browser "Request Expired" is a more appreciable error message

**Comment by atomindtechnology** [comment]
if the solution is acceptable I would also make the changes immediately

**Comment by alecpl** [comment]
ok, let's call it `uploadTimeout`.

**Comment by atomindtechnology** [comment]
Perfect!

**Comment by atomindtechnology** [comment]
Pull Request At [7551](https://github.com/roundcube/roundcubemail/pull/7551)
