### ISSUE TITLE
No number (notification) for new emails in a folder

### ISSUE THREAD

**Issue by Cholens** [roundcube/roundcubemail#7550]
When I receive a new email in a folder, there is no number (notification) that there is a new email. It does show a number when I press renew/refresh.

**Comment by alecpl** [comment]
What version? What IMAP server? What PHP/OS version? What plugins? What browser? What configuration?

**Comment by Cholens** [comment]
> What version? What IMAP server? What PHP/OS version? What plugins? What browser? What configuration?

PHP: 7.4.7
OS: CentOS Linux release 7.8.2003 (Core)
Mailserver: postfix 3.4.7
Bowser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52

Default config no plugins

**Comment by alecpl** [comment]
What IMAP server? Enable imap_debug and provide the log.

**Comment by alecpl** [comment]
No feedback.
