### ISSUE TITLE
$config['include_host_config'] is little confusing... cannot connect to remote servers

### ISSUE THREAD

**Issue by elvisef** [roundcube/roundcubemail#7553]
Hey.

I've read of course this: [https://github.com/roundcube/roundcubemail/wiki/Configuration:-Multi-Domain-Setup](url) but...

I thought this works in the way I am adding for instance this array:

```
$config['include_onehost_config'] = array(
    'test1' => test1.de_config.inc.php',
    'testASDF' => test999.ua.com.inc.php'
);

```
and then I Roundcube will autoload the files (values) from the array as expected.

But.. the "key" should be the current domain name (if I loadad page on example.com, the key should be: "example.com" here) to load specific config file. But what about if I wanted to have access to remote servers like Gmail or Yahoo ?

This won't work. Generally I've made a small function, based on "load_host_config()", that reads NOT $_SERVER variables (because I have and am ONE domain using only), but the list of "host_config". And this seems to work well (tested on my domain serv).

But.. I think eve the "key" parts in the "include_host_config" array are unnecessary (need to modify functoin a bit).

I have no time to make a requests or suggestions in the code. Just wanted to ask, why such functionality isn't implented yet ? This is very useful if I wanted to make a connection to remote servers. For now just wondering why email connection doesnt work for me.. maybe I will need a certificate and CA. But I will spend some time to make it work I suppose...

![14082020_12:06:00_Zaznaczenie](https://user-images.githubusercontent.com/25976749/90239795-6b641280-de28-11ea-8f6c-343a842f9a13.png)

**Comment by elvisef** [comment]
Ok, I just found out it isn't well done.... it works for one element from the array only.
If theree a re more elements, the config could be overriten... I will make it work in time..
Just wondering if such functionality would be good ? Now I am working on Gmail connection.
Generally we can close this if it's not  really important...

**Comment by alecpl** [comment]
`default_host` and `smtp_server` support variables. Is that not enough?

**Comment by elvisef** [comment]
Alright, `smtp_host` is enough if You want to use few imap connection servers.
But what if I wanted to have separate parameters for these connection options ?

> example:
>  - domain_one.com
>  - domain_two.com
> etc..

and domain_one will have different logging parameter values, domain_two will have different set of plugins etc...

How to combine these all things together ? Is there a way to do such thing ?
Looking at config options [https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php](https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php) I don't see any usable parameters to make it real.

That's why I modified it myself.

**Comment by lihexin88** [comment]
> `default_host`和`smtp_server`支持变量。这还不够吗？

life saver !!!!!
