### ISSUE TITLE
Restore doesn't restore CC/BCC.

### ISSUE THREAD

**Issue by raoulbhatia** [roundcube/roundcubemail#7554]
Hi,

My session while composing an email expired today.  Upon reloading the compose screen / composing a new message, I was presented with a dialog to restore my previous message (from local store?).

I then noticed that:
* Subject & Message were OK
* TO was OK
* CC and BCC were missing

I am using Roundcube Webmail/1.3.15

Thanks,
Raoul

**Comment by alecpl** [comment]
Roundcube 1.3 is not supported, but I see some issues in git-master too.
1. In Larry and Classic skins CC/BCC is restored, but the input is still hidden.
2. It does not work in Elastic skin

**Comment by alecpl** [comment]
Fixed.

**Comment by raoulbhatia** [comment]
Thanks for the quick fix!  I am looking forward to the next 1.4 release :-)
