### ISSUE TITLE
Maintenance Request: Pull Request Backlog

### ISSUE THREAD

**Issue by dereks** [roundcube/roundcubemail#7555]
As a sysadmin it is very encouraging to see the large number of closed bugs and merged PRs in this project. Great job! Active development is important. But it is discouraging to see several old PRs dangling for years. 

Please manage the submitted PRs, especially older ones. There are some Pull Requests dating back to **2014**. Accept them, reject them, or reply to the author with code review feedback so they can update the Pull Request to be acceptable.

(Issues should also all be handled, but with Issues there may be end users contributing to a non-technical discussion, so it's less critical than PRs.)

Thank you for your hard work. I just did another 2020 Open Source webmail comparison and Roundcube is still the best after all these years.

**Comment by alecpl** [comment]
Thanks for your suggestions. It's not that simple and it is time consuming. I'm doing my best and the number of items is not that big.

And we'll just not close tickets after long inactivity period. Some projects do this and this is very irritating.

**Comment by dereks** [comment]
> And we'll just not close tickets after long inactivity period. 

Fair enough. But to clarify, I was referring specifically to Pull Requests, not "tickets" (Issues).

Unlike Issues, which can remain relevant to users for years, Pull Requests become invalid over time. Most of those PRs that are 5 or 6 years old now won't even merge anymore due to conflicts. They're basically just cruft.

Would it be helpful if I walked through the old PRs and ping their authors in the comments, asking them to rebase off the latest code base? Then these old PRs would either 

- (a) become a clean merge with the latest code, so you can decide to accept or reject them, or else 
- (b) we'll get no response and then we can close the PR as abandoned. 

That would address at least the very oldest PRs.

And for very simple PRs (like the one that just updates the README) I would even be willing to do the rebase and submit a refreshed PR.

I'm an experienced PHP coder and am throwing some time into a new Roundcube server this week, and would like to help. 

Thanks again!

**Comment by alecpl** [comment]
Go ahead.

**Comment by dereks** [comment]
@alecpl I posted a message to any open PR that has a conflict. I think all of them were from 2018 or older. 

I saw that you had commented on many of them and thus are probably "watching" those PRs. So, apologies for the small amount of spam.

I did note that a couple of them had conflicts in the file CHANGELOG. That seems weird to me. No PR should have an edited CHANGELOG. It's probably some artifact of a format change or something like that.

> I'm doing my best

You are doing an excellent job and your work is very appreciated! Please don't take this ticket as as a complaint or gripe. 

I recommend we wait a month to see who updates their PRs and who doesn't. Any PRs older than a year that still have a conflict can then be closed as abandoned. 

If you would like me to do a code review and/or make a recommendation on some of those older PRs (which do not have a conflict), let me know, I'd be happy to contribute some time. Thanks!
