### ISSUE TITLE
A configuration option for mail search scope

### ISSUE THREAD

**Issue by carloshilgemberg** [roundcube/roundcubemail#7556]
Hello, is there a possibility to enable by default so that message searches are performed in all folders by default?

I know this can slow you down a bit, but that is not a problem in my case.

I didn't find where to change this functionality in config.inc.php

![Default Enable](https://user-images.githubusercontent.com/36273475/90319795-dc332980-df11-11ea-8342-122e9e8da8c1.jpg)

**Comment by alecpl** [comment]
You can control fields with `search_mods` option, but it's not possible for scope.

**Comment by vladimirdulov** [comment]
It has been sorted by PR #9077

**Comment by gramakri** [comment]
This would be great to have proper recursive search as the default. We have solr fts setup with dovecot and it's really fast in recursive search of all folders and all mail body.

**Comment by alecpl** [comment]
Implemented.
