### ISSUE TITLE
Different folder for config files for Multi Domain Setup 

### ISSUE THREAD

**Issue by PablitoMurillo** [roundcube/roundcubemail#7558]
Hi

I'm working with a lot of server sharing a mounted webmail installation as read-only, so, the config files for a multihost domain setup can be on roundcube config folder, so I made a little patch to allow the config files be on other folder
May be I lost some other option that let me do this, if this is the case, please tell me 

In the meanwhile I'm sendign the patch I made, only change 2 files :
- config/config.inc.php
- program/lib/Roundcube/rcube_config.php

I'm new on github, I'm not sure if I'm doing things in the right way

I'm sending the pathc as a TXT file
Apply from inside roundcube folder as :
patch -p1 < multi_host_alter_folder.patch

```
--- roundcubemail-1.4.8/config/config.inc.php.sample	2020-08-10 16:04:57.000000000 -0300
+++ webmail/config/config.inc.php.sample	2020-08-16 16:30:22.320522000 -0300
@@ -84,3 +84,6 @@
 
 // skin name: folder from skins/
 $config['skin'] = 'elastic';
+
+// Different folder for multiples host config files, empty for default folder
+$config['include_dir_host_config'] = "";
--- roundcubemail-1.4.8/program/lib/Roundcube/rcube_config.php	2020-08-16 16:02:01.645750000 -0300
+++ webmail/program/lib/Roundcube/rcube_config.php	2020-08-16 16:45:11.537818000 -0300
@@ -290,11 +290,16 @@
                 $fname = preg_replace('/[^a-z0-9\.\-_]/i', '', $name) . '.inc.php';
             }
 
-            if ($fname && $this->load_from_file($fname)) {
+            if ($fname) {
+                if (!empty($this->prop['include_dir_host_config'])) {
+                    $fname = $this->prop['include_dir_host_config'] . $fname;
+                }
+                if ($this->load_from_file($fname)) {
                 return;
             }
         }
     }
+    }
 
     /**
      * Read configuration from a file
```

[multi_host_alter_folder.patch.txt](https://github.com/roundcube/roundcubemail/files/5081290/multi_host_alter_folder.patch.txt)

**Comment by alecpl** [comment]
I don't like another option. You can just add some code to the config.inc.php file, e.g.:
```
if (file_exists(__DIR__ . '/' . $_SERVER['HTTP_HOST'] . '/config.inc.php')) {
    include(__DIR__ . '/' . $_SERVER['HTTP_HOST'] . '/config.inc.php');
}
```
