### ISSUE TITLE
Roundcube doesnt load "installer" properly

### ISSUE THREAD

**Issue by rarestuff** [roundcube/roundcubemail#7559]
Im just trying to enter myhost.mydomain.net/roundcubemail/installer but just shows up **Index: Of Page**. and the Roundcube files, I allready open the port 80 and my server is working just fine, but for some reason do not load the INSTALLER , 

<a href="https://imgur.com/ismaKk8"><img src="https://i.imgur.com/ismaKk8.png" title="source: imgur.com" /></a>

Im runing CENTOS 8

I followed this guide for the installation: 
https://computingforgeeks.com/setup-mail-server-on-centos-with-postfix-dovecot-mysql-roundcube/

Thanks!

**Comment by alecpl** [comment]
You have to configure your http server to process index.php file by default. Not Roundcube issue.
