### ISSUE TITLE
Undeliverable message received by clients

### ISSUE THREAD

**Issue by janeyb1** [roundcube/roundcubemail#7562]
Several of my clients are receiving daily 'undeliverable' messages from my account, even when I haven't sent them anything.   This has happened with both hotmail.com and gmail.com recipients.  This is causing reputational damage.   How can it be stopped?

![Capture1](https://user-images.githubusercontent.com/69323184/90638061-b7e29000-e224-11ea-801e-2cb49701b22d.PNG)

**Comment by thomascube** [comment]
Unfortunately this cannot be stopped and it's unrelated to Roundcube. Some bad guys are sending out spam messages with their sender address and yours as recipient. You email system correctly rejects those messages (to protect you from spam) with the result that your clients (which are the fake senders of those messages) receive the bounced message.
