### ISSUE TITLE
I cannot send emails

### ISSUE THREAD

**Issue by rodrigogutierrezgonzalez** [roundcube/roundcubemail#7563]
I have the next bug, when i send an email. So my emails cannot be to sent.

Hi. This is the qmail-send program at dns10356.phdns19.es.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

From MAILER-DAEMON@dns10356.phdns19.

I need help, Thanks.

**Comment by alecpl** [comment]
We do not manage your email account. We cannot help you. We're webmail software creators.
