### ISSUE TITLE
MSSQL: Incorrect PDO::lastInsertId() use

### ISSUE THREAD

**Issue by raviolichen** [roundcube/roundcubemail#7564]
I install Roundcube 1.4.8 with hMailServer on Windows Server 2019
on setting-> identities ; I try create a new data，when I save,it show the error like
this pic , but it still insert the data , the errorlog is empty.  I don't know how it happened...
![image](https://user-images.githubusercontent.com/12947662/90773772-02e5cb80-e329-11ea-88ab-c38f817eb910.png)

![image](https://user-images.githubusercontent.com/12947662/90773465-87841a00-e328-11ea-8b20-1cae6c74a4fd.png)

the contacts
![image](https://user-images.githubusercontent.com/12947662/90774153-928b7a00-e329-11ea-9f6c-4d39a1336591.png)

![image](https://user-images.githubusercontent.com/12947662/90774210-aa62fe00-e329-11ea-84e7-b576b90421d6.png)

Sorry,I change EN UI

**Comment by alecpl** [comment]
Could we see that in English?

**Comment by raviolichen** [comment]
I found this problem through return $insert_id; can't return the inserted value.
when set return not zero value , it show success.

My SQL is MS SQL 2019 .

![image](https://user-images.githubusercontent.com/12947662/91000457-d0bfbc80-e5fb-11ea-9cfc-57e6f1684e69.png)

**Comment by raviolichen** [comment]
I found this problem through return $insert_id; can't return the inserted value.

My SQL is MS SQL 2019 .

and I have solved this. add
if($id==0){
$query = $this->query_execute('SELECT SCOPE_IDENTITY() as lastId;');
$id =$query->fetch();
}
in rcube_db.php public function insert_id($table = '')
to check if $id = $this->dbh->lastInsertId($table); is not work

**Comment by raviolichen** [comment]
I found this problem through return $insert_id; can't return the inserted value.

My SQL is MS SQL 2019 .

and I have solved this. add
if($id==0){
$query = $this->query_execute('SELECT SCOPE_IDENTITY() as lastId;');
$id =$query->fetch();
}
in rcube_db.php public function insert_id($table = '')
to check if $id = $this->dbh->lastInsertId($table); is not work

**Comment by alecpl** [comment]
I saw that somewhere already, but it was never fixed. It looks that newer version of mssql extension expects the argument of PDO::lastInsertId() to be a sequence name, not table name. Could you confirm that it works without the `$table` argument?

https://docs.microsoft.com/en-us/sql/connect/php/pdo-lastinsertid?view=sql-server-ver15

**Comment by alecpl** [comment]
Found it https://www.roundcubeforum.net/index.php/topic,28886.msg73783.html

**Comment by raviolichen** [comment]
I try that , it still work well for me.

**Comment by alecpl** [comment]
The proper fix would have to check the driver version (`PDO::getAttribute(PDO::ATTR_DRIVER_VERSION)`) and act accordingly. I'll let you know when we have a fix, so you could confirm it works.

**Comment by alecpl** [comment]
Fixed in 77bc3f2427b. Could you confirm?

**Comment by raviolichen** [comment]
I try it,but I get this error. Is my setting wrong?

Stack trace:
#0 C:\inetpub\mail\program\lib\Roundcube\rcube_user.php(425): rcube_db->insert_id()
#1 C:\inetpub\mail\program\steps\settings\save_identity.inc(155): rcube_user->insert_identity()
#2 C:\inetpub\mail\index.php(306): include_once('C:\\inetpub\\mail...')
#3 {main}
  thrown in C:\inetpub\mail\program\lib\Roundcube\rcube_db.php on line 607
[03-Sep-2020 19:28:33 Asia/Brunei] PHP Fatal error:  Uncaught Error: Undefined class constant 'ATTR_DRIVER_VERSION' in C:\inetpub\mail\program\lib\Roundcube\rcube_db.php:607
Stack trace:
#0 C:\inetpub\mail\program\lib\Roundcube\rcube_user.php(425): rcube_db->insert_id()
#1 C:\inetpub\mail\program\steps\settings\save_identity.inc(155): rcube_user->insert_identity()
#2 C:\inetpub\mail\index.php(306): include_once('C:\\inetpub\\mail...')
#3 {main}
  thrown in C:\inetpub\mail\program\lib\Roundcube\rcube_db.php on line 607

**Comment by alecpl** [comment]
The line number/file in the error message does not make sense. Did you apply the patch to the wrong file? What PHP version? What PDO driver version?

**Comment by raviolichen** [comment]
My php version is 7.4.9
PDO version is 5.8.0
![image](https://user-images.githubusercontent.com/12947662/92112575-92f33d00-ee20-11ea-8d70-4d4eafd9650a.png)

**Comment by alecpl** [comment]
According to https://docs.microsoft.com/en-us/sql/connect/php/pdo-getattribute?view=sql-server-ver15 it should work.

**Comment by alecpl** [comment]
Could you replace `PDO::ATTR_DRIVER_VERSION` with `PDO::ATTR_CLIENT_VERSION` and check what getAttribute() returns?

**Comment by raviolichen** [comment]
I get the value is Array this:
PDO::ATTR_CLIENT_VERSION:{"DriverDllName":"msodbcsql17.dll","DriverODBCVer":"03.80","DriverVer":"17.05.0001","ExtensionVer":"5.8.0+12928"}

**Comment by alecpl** [comment]
@raviolichen I fixed this in d30f039e5af8c01 and made the driver version 5 a default. Could you confirm this works?

**Comment by alecpl** [comment]
I'm closing this. Without a confirmation I'm not going to backport this to 1.4.

**Comment by raviolichen** [comment]
I try it. it work will now.

**Comment by alecpl** [comment]
Backported to 1.4.9.
