### ISSUE TITLE
Roundcube 1.4.8 recipient field is too short - visible only 5 chracters

### ISSUE THREAD

**Issue by studiowena** [roundcube/roundcubemail#7565]
Hello,

Roundcube 1.4.8
Skin: Elastic

Composing new mail, recipient field is too short when typeing e-mail address. It only contains visible 5 chracters. Its hard to type correct email if we not have it on our address book.

**Comment by alecpl** [comment]
Or get the release package and compare skins/elastic/ui.min.js and skins/elastic/styles/styles.css with what you have.

**Comment by studiowena** [comment]
Hi again,

I've just resolved this problem by not minify style.css. I was using some different colors in variables.less after compile style.css was minifed by plugin from VS code and this was problem. Have no time to reproduce what was wrong exacly with this but roundcube elastic theme is working OK now.

**Comment by sergiokessler** [comment]
same here, fixed.

mental note to myself and others updating roundcube via git, after `git pull`:

$ ./bin/update.sh
$ php composer.phar update --no-dev
$ cd skins/elastic
$ lessc -x styles/styles.less > styles/styles.css
$ lessc -x styles/print.less > styles/print.css
$ lessc -x styles/embed.less > styles/embed.css
