### ISSUE TITLE
Closure compiler is no longer available at dl.google.com

### ISSUE THREAD

**Issue by X-dark** [roundcube/roundcubemail#7567]
Closure compiler download URL referenced here: https://github.com/roundcube/roundcubemail/blob/8e63309203788f4646cc7bf98b858f73fea84f98/bin/jsshrink.sh#L6 is no longer available. It should be downloaded through [Maven](https://mvnrepository.com/artifact/com.google.javascript/closure-compiler) or [GitHub](https://github.com/google/closure-compiler/releases). I am not sure if there is a way to download "latest" as before though.

**Comment by alecpl** [comment]
I think for a while we can live with https://dl.google.com/closure-compiler/compiler-20200719.zip

According to https://github.com/google/closure-compiler/wiki/Binary-Downloads there will be no more binary downloads. In the future we might switch to npm. Or look for other options.
