### ISSUE TITLE
Importing multiple contacts in multiple groups corrupts to-field

### ISSUE THREAD

**Issue by kearva** [roundcube/roundcubemail#7569]
The situation arises when a user adds several lists of contacts to one email. Then some of the addresses becomes mangled with each other. For instance, one recipient box might get "John Doe" and "<john.doe@somemail.com>ne.doe@otheremail.com>" it the name and email field. This happens several times. And quite difficult for users to see.

After debugging this for some time, it seems like when the user clicks to add the contacts, one request is fired to to roundcube for each of the lists of contacts and a placeholder is put into the text field. Then a raise condition happens between the result of the http requests and running the recipient_input_parser. Where each of them tries to modify the same content. This is at least what I think is happening.

**Comment by alecpl** [comment]
I would need more precise steps to reproduce. What groups and contacts do I need, and what exactly do you input to the field? What version? What skin? Any external plugins? What browser?

**Comment by kearva** [comment]
**Environment**
Roundcube version 1.4.8.  
Elastic skin
Browsers: Latest safari, crome and firefox.
Relevant plugins:
- carddav version 3.0.3

Addressbook contains 300 contacts, where about half of them are added into 10 groups (rangeing from 5 to 29 members). There is only name and email on each of the contacts.

**How to reproduce**
1. Compose a new mail
2. Click on the "add-contact" button at the end of the To-field
3. Select groups (two or more)
4. Click insert

**Comment by alecpl** [comment]
Fixed.
