### ISSUE TITLE
Paste link via right-click disappears

### ISSUE THREAD

**Issue by kearva** [roundcube/roundcubemail#7570]
If a user wants to paste a link in a new email, and uses ctrl+v/cmd+v, it pastes the link with the link as the link text. But if the user right-click on the end of a line or a new line, and selects paste, the link doesn't appear. It seems like it selects the rest of the line, and then discard the link. Both me and the user was expecting the link to appear just as if we use the keyboard to paste the link.

**Comment by alecpl** [comment]
What version? Are you talking about HTML or plain mode?

**Comment by kearva** [comment]
Roundcube 1.4.8  
HTML mode  
Elastic skin 
Verified in Safari and Crome (it works as expected in firefox) on MacOS 10.15.6

It seems like it is depends on the copy and paste context. If a user right clicks on a link and select "copy link address". And pastes the the link via right click and paste, it doesn't appear. If the clipboard has both url and content, it works. If the clipboard only has the url it fails via the context-menu.

After some testing, I discovered different apps does this in different ways. If I copy the adress bar from Firefox and paste it into the HTML editor in Roundcube in Chrome or in Safari (via the context-menu) it disappear. But if I do the same from Safari to Chrome (and vice versa) it works.

**Comment by alecpl** [comment]
Please, do your tests on the editor at https://www.tiny.cloud/ This will tell us if it's still an issue in TinyMCE 5.

**Comment by kearva** [comment]
A link that dosen't show in Roundcube works fine in https://www.tiny.cloud/docs/demo/casechange/ on the same browser.

**Comment by alecpl** [comment]
Would be better to use https://www.tiny.cloud/docs/demo/basic-example/ It uses most of the plugins we're using and no commercial ones.

**Comment by kearva** [comment]
No, it has a context-menu on it's own, so it isn't possible to test it on the basic example.

**Comment by alecpl** [comment]
Right. Later I'll test this on git-master where we already switched to TinyMCE 5. This switch will not going to happen in 1.4 anyway.

**Comment by alecpl** [comment]
Works for me on git-master in Firefox and Chrome.
