### ISSUE TITLE
roundcube under hardened php (disabled functions)

### ISSUE THREAD

**Issue by robo2bobo** [roundcube/roundcubemail#7571]
Hello everyone,

Not a bug, but something interesting that might be helpful to others. While running roundcube under a hardened php with tons of disabled functions, I found that roundcube runs great with the following disabled functions:

```php
disable_functions = pcntl_alarm, pcntl_errno, pcntl_get_last_error, pcntl_getpriority, pcntl_setpriority, pcntl_signal_dispatch, pcntl_signal_get_handler, pcntl_sigprocmask, pcntl_sigtimedwait, pcntl_sigwaitinfo, pcntl_strerror, pcntl_wait, pcntl_wexitstatus, pcntl_wifexited, pcntl_wifsignaled, pcntl_wifstopped, pcntl_wstopsig, pcntl_wtermsig, posix_access, posix_ctermid, posix_errno, posix_get_last_error, posix_getcwd, posix_getegid, posix_geteuid, posix_getgid, posix_getgrnam, posix_getgroups, posix_getlogin, posix_getpgid, posix_getpgrp, posix_getpid, posix_getppid, posix_getpwnam, posix_getrlimit, posix_getsid, posix_getuid, posix_initgroups, posix_isatty, posix_mkfifo, posix_mknod, posix_setegid, posix_seteuid, posix_setgid, posix_setpgid, posix_setrlimit, posix_setsid, posix_setuid, posix_strerror, posix_times, posix_ttyname, posix_uname, assert, assert_options, cli_get_process_title, cli_set_process_title, dl, gc_collect_cycles, gc_disable, gc_enable, gc_mem_caches, get_cfg_var, get_current_user, get_extension_funcs, get_required_files, get_resources, getlastmod, getmygid, getmyinode, getmyuid, getrusage, php_ini_loaded_file, php_ini_scanned_files, php_logo_guid, phpcredits, phpinfo, putenv, restore_include_path, zend_logo_guid, zend_thread_id, virtual, highlight_file, link, parse_ini_file, proc_close, proc_get_status, proc_nice, proc_terminate, show_source, system, pfsockopen, apache_child_terminate, apache_getenv, apache_lookup_uri, apache_note, apache_reset_timeout, apache_setenv, popen, readlink, eval, pcntl_exec, pcntl_fork, pcntl_signal, pcntl_async_signals, proc_open, passthru, exec, shell_exec, getcwd
```

In my case, roundcube connects to a remote IMAP server, thus the function fsockopen is a requirement, thus not disabled in the above list.

For reference, wordpress works great with the above functions also disabled, it only requires the following to be enabled: posix_getpwuid, posix_getgrgid, getenv

Of course your mileage may vary, for example, I don't run any plugins in my roundcube installation, thus my requirements are quite minimal.

PS:
I've compiled the above list of functions based on various common hack toolkits, backdoors, shell kits and other php scripts that are uploaded on servers after they have been compromised. By disabling these functions you can't prevent an infection, but you CAN limit their expansion and some damage that they cause.

**Comment by alecpl** [comment]
Does not look right. `eval` is essential. Also, we're using `exec` and `proc_open`, etc. Anyway, I'm not really interested in maintaining such a list.
