### ISSUE TITLE
Cannot install JavaScript dependencies

### ISSUE THREAD

**Issue by Bojo78** [roundcube/roundcubemail#7572]
When I try to install JavaScript dependencies by executing `bin/install-jsdeps.sh` script the following error occurred: 
```
Fetching https://code.jquery.com/jquery-3.4.1.min.js
Installing jQuery...
Wrote file /var/www/roundcubemail-1.4.8/program/js/jquery.min.js
Done.
Fetching https://bitbucket.org/pellepim/jstimezonedetect/raw/6c427658686c664da52c6a87cd62ec910baab276/dist/jstz.min.js
ERROR: Incorrect sha1 sum of /var/www/roundcubemail-1.4.8/temp/js_cache/jstz-1.0.6.js. Expected: 4291cd3b259d2060460c2a6ab99f428d3c0c9537, got: fc344ae73896cf63791a56b88d0824612888bfa5
```
Is seems that there is a problem with jsTimezoneDetect Bitbucket repository - 
[https://bitbucket.org/pellepim/jstimezonedetect/raw/6c427658686c664da52c6a87cd62ec910baab276/dist/jstz.min.js](https://bitbucket.org/pellepim/jstimezonedetect/raw/6c427658686c664da52c6a87cd62ec910baab276/dist/jstz.min.js)

I've installed dependencies by removing jsTimezoneDetect from` jsdeps.json` and copied the file `"program/js/jstz.min.js"` from an older installation.

**Comment by alecpl** [comment]
Already fixed in fcfde1a0ece8633bd.
