### ISSUE TITLE
LDAP address book: Could not start TLS

### ISSUE THREAD

**Issue by hth2** [roundcube/roundcubemail#7573]
I have configured  a LDAP address book with roundcube, and it seems to work fine. Now I would like to switch to ldaps, but got stuck with this problem: roundcube keeps saying 'Could not start TLS'.

the ldap server in question works fine with other apps over ldaps, so I think my problem is how to figure out how to import the root CA cert to php.

I tried to edit my /etc/ldap/ldap.conf as follows:

```
TLS_REQCERT demand
TLS_CACERT /path/to/CAcert.pem
```

but it didn't help.

Any hint would be much appreciated.

**Comment by alecpl** [comment]
Did you set the host prefix to ldaps:// and port=636 and use_tls=false. Or it is no host prefix, port=389 and use_tls=true?

**Comment by alecpl** [comment]
Anyway, that's the only hint I can give you. The rest is between PHP and LDAP. Ask on mailing list or forum.
