### ISSUE TITLE
Company Wide Semi-Generic Identity Signatures

### ISSUE THREAD

**Issue by jitman** [roundcube/roundcubemail#7575]
Feature request, perhaps its own plugin.  Looking for suggestions on how to accomplish this for my workplace.

I'd like a way to apply a default, company wide signature for all users with fields such as name, department, title, etc. being specific to the user.  For example, when a user creates a new identity, they fill in fields for first name, last name, job title, department, and an address.  Then instead of designing their own signature, they can choose 'use company default'.  Elsewhere there could be a signature source file with shortcodes like `[first-name]` or `%FIRSTNAME%`, whatever is easiest to parse.  That way if a company changes its information, logo, disclaimer, etc. it can all be done in one place yet is specific to each user.

**Comment by alecpl** [comment]
That's indeed too specific for a core feature.

The first part (extra fields in identities) could become a core feature, I guess. We have some tickets about e.g. sending full vCard data. That will require these extra fields.

A plugin could use `identity_create`, `identity_update`, `identity_form` and `identity_select` to implement this feature.
