### ISSUE TITLE
will this work on azure vm?

### ISSUE THREAD

**Issue by Aveerzota** [roundcube/roundcubemail#7581]
Microsoft azure has blocked port 25 for outbond email ... So will this application work successfully if we deploy it on azure

**Comment by alecpl** [comment]
Roundcube has to connect to SMTP server, usually it does this on a different port. So, Roundcube will work, but SMTP server might not.

**Comment by trasherdk** [comment]
Use NAT on SMTP server.  
Here's how, using iptables.  
```
echo "* Forward incomming on port 26 (smtp-alt) to port 25 (smtp)"
$IPT -A PREROUTING -t nat -p tcp --dport smtp-alt -j REDIRECT --to-port smtp
```

Here's a bunch of examples [Linux iptables: Port Redirection Example](https://www.cyberciti.biz/faq/linux-port-redirection-with-iptables/)
