### ISSUE TITLE
Roundcube 0 bytes attachment

### ISSUE THREAD

**Issue by blpraveen** [roundcube/roundcubemail#7582]
I am sending a mail with an attachment to my gamil id .It is received without any issues . Now the problem is when I received the mail to my roundcube email id  the attachment is empty.it is 0 sbytes

**Comment by alecpl** [comment]
Does it happen with different clients like Outlook/Thunderbird or the Roundcube itself? Sounds like a gmail issue.

Could you provide source for both messages? Maybe we'll find some clues there.

**Comment by blpraveen** [comment]
Please refere below code
			$header = "From: ".$from_name." <".$from_mail.">".$eol;
			$header .= "Reply-To: ".$replyto.$eol;
			$header .= "MIME-Version: 1.0\r\n";
			$header .= "Content-Type: multipart/mixed; boundary=\"".$uid."\"";
			
			// Put everything else in $message
			$message = "--".$uid.$eol;
			$message .= "Content-Type: text/html; charset=ISO-8859-1".$eol;
			$message .= "Content-Transfer-Encoding: 8bit".$eol.$eol;
			$message .= $body.$eol;
			$message .= "--".$uid.$eol;
			$message .= "Content-Type: application/pdf; name=\"".$filename."\"".$eol;
			$message .= "Content-Transfer-Encoding: base64".$eol;
			$message .= "Content-Disposition: attachment; filename=\"".$filename."\"".$eol;
			$message .= $content.$eol;
			$message .= "--".$uid."--";
			
			mail($mail_to, $subject, $message, $header);

**Comment by alecpl** [comment]
This does not answer any of my questions.

**Comment by alecpl** [comment]
In the code above there's missing `$eol` before `$content`.
