### ISSUE TITLE
Missing Folder View icon in Elastic

### ISSUE THREAD

**Issue by MetallianFR68** [roundcube/roundcubemail#7583]
Hi,

Sorry but where is that icon with the planet gone in Elastic ?
![image](https://user-images.githubusercontent.com/6049266/91671108-f7ae4f00-eb23-11ea-8333-dfb338a12176.png)

I can't find these useful functions anymore ...

**Comment by alecpl** [comment]
Looks like some plugin. I have no idea.

**Comment by MetallianFR68** [comment]
Thanks for you answer.
You were right.
It was contextmenu_folder plugin which is obviously not ELASTIC compatible yet.

There are 3 features in this plugin that should be implemented in roundcube directly, in my opinion :
- locate folder
- move to folder
- copy to folder
But with an interface with a searchfield.
I have 1000+ folders in my mailbox and browsing the whole hierarchy is very time consuming

![image](https://user-images.githubusercontent.com/6049266/91769355-86cc6d00-ebdf-11ea-89b5-8668875cf2b4.png)
