### ISSUE TITLE
TinyMCE 5 with newest git version

### ISSUE THREAD

**Issue by Hallikas** [roundcube/roundcubemail#7586]
I just updated to current GIT Master version, and we found out that when replying HTML type message, original quote is cleared out. If editor is set to 'plain text' from settings, it works. Also quote works if original message is plain text.

This looks like almost as same issue as #7568, except he has 'quote headers', I have just blank canvas.

... After very extensive search, I did found out that reason for this was missing tinymce theme, silver. This theme 'silver' does not exist, but after switching it back to modern, replying works again.

After I did find out that this was my issue, I figured out that I had old version of TinyMCE, so first I tried to install new one by hand. No go, so I used ./bin/install-jsdeps.sh to verify/install all depencies.

Everything was fine, and most of my issues was fixed. Except html editor did not work as expected. I did use browser developer mode to find out that there is javascript error message, "tinymce.ui is undefined". Looks like that it has something to do with 'tinymce.ui.Factory' class. (I don't know anything about javascript, so I'm just guessing) ;)

- Semi

**Comment by Hallikas** [comment]
![image](https://user-images.githubusercontent.com/681531/92142991-54a84e80-ee1d-11ea-9110-03a1a70c1ee0.png)

**Comment by alecpl** [comment]
Works for me. What browser? Could you remove program/js/tinymce folder and execute the install-jsdeps.sh script again?

**Comment by alecpl** [comment]
I see. Looks like the browser loaded the old tinymce with new version cache buster. So, that's why after you updated tinymce it didn't refresh the cache.

**Comment by kalyankalapala** [comment]
When can we expect the latest roundcube version with tinymce 5 (as power plugin is also included which fixes the broken HTML) ???
