### ISSUE TITLE
Hook allowing message headers modification on compose

### ISSUE THREAD

**Issue by r3c** [roundcube/roundcubemail#7590]
Hello,

I'm trying to modify message headers on compose (after redirection and before editor is displayed) to modify initial value of the "cc" field and cancel unwanted cc of original recipient on reply-all.

When using "reply-all" action from an email, original recipient is added to "cc" header (see https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail_sendmail.php#L1068). If this recipient matches current identity it's then removed from "cc" header a few lines below (see https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail_sendmail.php#L1131). This works fine when using "reply-all" from an email where recipient is registered as an existing identity, as these two operations cancel each other.

However when working with plugin custom_from it's likely to have emails where original recipient doesn't match a registered identity. Recipient is therefore automatically added to "cc" header, leading to sending emails to oneself. One option to fix this issue would be a new hook allowing headers override on compose, similar to existing `message_compose_body` hook, but I couldn't find an existing hook able to play with headers on message compose. I'm thinking about something located near the end of `compose_header_value` function from `rcmail_sendmail.php` file, but maybe there are more simple solutions to achieve a similar result.

What's your opinion about this feature, and do you see a more efficient way to address original issue?

Regards
Rémi

**Comment by alecpl** [comment]
Problem is that if there's no identity we don't know it's the user itself. So, I see nothing to fix here.

As for the hook... You could use existing `template_object_composeheaders` hook, but it would involve html parsing, so not really a good solution. The suggested place for a new hook sounds good.

**Comment by r3c** [comment]
You're right there is nothing to fix, as by default no identity means we don't know what could be removed from "cc" header. However it can make sense with some plugins playing with identities, which is what I'm trying to do here.

**Comment by alecpl** [comment]
That's what I meant. Please, provide the PR.

**Comment by r3c** [comment]
I tried adding the hook in the `compose_header_value` method as suggested in first post, unfortunately I realized it seems too far away from the mail compose process for me to solve my original issue. What I'd like to do is removing unwanted values from "cc" field before it gets used to build the HTML compose form. However this field seems constructed quite late in the compose process, through a `composeheaders` handler registered in the template HTML file. This means the hook should be located in a quite different location than existing "message_compose" and "message_compose_body" hooks (both in `compose.inc`) and maybe shouldn't have access to all the variables I'll need such as compose ID without breaking some design choice.

As I wasn't sure how to continue I went for another strategy and implemented my feature as a "message_compose_body" hook where I mutate message headers to alter the way "cc" field of the message being composed will be generated. This feels quite hacky to me but I'm not sure what a better solution could look like.

Please let me know if you have suggestions or feel free to close the issue otherwise.

**Comment by sdondley** [comment]
I need similar functionality. People will often send me an email to two or three different email addresses that all get forwarded to my main account in roundcube. I'd love to strip out those unwanted address from the "cc" header and "to" fields on the compose form?

Is there a reason this couldn't be done with a plugin and some javascript?
