### ISSUE TITLE
Open folder (RC 1.4.8)

### ISSUE THREAD

**Issue by syncgw** [roundcube/roundcubemail#7591]
Problem reported to me since 1.4.7. Logging in to RC. User expectes to see content of inbox. Unfortunately some other folder content is shown (mostly a folder opened and worked on in a previous session). Need to click on inbox. This "jumping" is happening during the whole session (e.g. when switching temporary to settings and then back again).

Behavior is a bit annyoing. Searching for a way to avoid this behavior, but don't know where.

**Comment by alecpl** [comment]
After logging in we always use INBOX, until there's a folder specified in the URL. Going to Settings should also "reset" the folder to INBOX. Maybe it's caused by some plugin? Could you try with disabled all plugins?

**Comment by syncgw** [comment]
It should be always the first idea to disable plugins. Sorry, I forgot that simple task. Will do now immediately and come back.

**Comment by syncgw** [comment]
I checked and problem is plugin `contextmenu_folder `related. Thank you for your support.
