### ISSUE TITLE
No mail

### ISSUE THREAD

**Issue by nzewire** [roundcube/roundcubemail#7593]
Am no longer receiving email on my Roundcube.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
