### ISSUE TITLE
htmlstream output the first line is a empty line cause eml and some attachments can't open

### ISSUE THREAD

**Issue by raviolichen** [roundcube/roundcubemail#7594]
I try download eml or other attachments. 
I found the document first line is a new line . it cause I can't open there files or emls,and try find any ?> or other 0A btye ,but it not work.

My problem like this,but I don't use other plugin 
https://github.com/roundcube/roundcubemail/issues/4443

![image](https://user-images.githubusercontent.com/12947662/92472776-8e59ca80-f20c-11ea-8ff7-dbc5b7339911.png)

![image](https://user-images.githubusercontent.com/12947662/92473284-13dd7a80-f20d-11ea-8a02-c541bd9a98e0.png)

**Comment by alecpl** [comment]
Disable all plugins and try again. What version? What PHP version?

In the old days we had issues where some config files contained an empty line after `?>` or before `<php`, but these days this should not be a problem.

**Comment by raviolichen** [comment]
I don't use any plugin . Roundcube is 1.4.8 ,php is 7.4.9  these on IIS and Windows Server 2019.
How can find the output stream php file ?

**Comment by raviolichen** [comment]
Sorry ,I found the problem.  Is a empty line in file before sqlsrv.php.
