### ISSUE TITLE
Password helpers wrapper for pw usermod

### ISSUE THREAD

**Issue by gldecurtins** [roundcube/roundcubemail#7595]
Hi all

I'm running a FreeBSD server where no chpasswd command is available, thus I can't use the chpass-wrapper.py. I would like to have only the wrapper enabled for sudoers (www user), so that the password of important accounts can't be changed.

I've copied the chpass-wrapper.py and modified it to work with pw, but chpasswd and pw take different input parameters and it looks like they are called differently from roundcube. Grabbing the user from the command line works, it's also validated against the user ID or blacklist.

Anyone with an idea on how to fix the modified wrapper below?

Cheers
-Luca.

```
#!/usr/bin/env python

import sys
import pwd
import subprocess

BLACKLIST = (
    # add blacklisted users here
    #'user1',
)

try:
    username = str(sys.argv[1])
except ValueError:
    sys.exit('Malformed username')

try:
    password = sys.stdin.readline()
except ValueError:
    sys.exit('Malformed password')

try:
    user = pwd.getpwnam(username)
except KeyError:
    sys.exit('No such user: %s' % username)

if user.pw_uid < 1000:
    sys.exit('Changing the password for user id < 1000 is forbidden')

if username in BLACKLIST:
    sys.exit('Changing password for user %s is forbidden (user blacklisted)' %
             username)

handle = subprocess.Popen(["/usr/sbin/pw", "usermod", "-h 0", "-n", username], stdin = subprocess.PIPE)
handle.communicate('%s' % (password))

sys.exit(handle.returncode)
```

**Comment by alecpl** [comment]
Maybe you should ask on a mailing list or forum.
