### ISSUE TITLE
enhancement: adding option to the forward managesieve, to send from the user email.

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#7596]
I am not sure if this is an issue. But say someone has setup spf for his domain and sends an email to a users that has in roundcube enabled this forward. If the message is forwarded without altering the message headers, this could result in a message being blocked or not relayed, because sending hosts ip, is not in the spf of the from: domain.

Possible solutions are:
- add something like a checkbox, if checked, it replaces the From: with that of the email address of the Roundcube user. (Maybe move the original sender to the Reply-To header? Maybe exception for 'internal' forward?)
- (sieve solution) Upon processing the message, check the spf records, if they are enforced, do the above, otherwise do nothing.

**Comment by alecpl** [comment]
The sieve redirect action has no such option. https://tools.ietf.org/html/rfc5228#section-4.2. I don't know any RFC that would define such functionality.
