### ISSUE TITLE
Calendar kolab

### ISSUE THREAD

**Issue by jacekn2** [roundcube/roundcubemail#7597]
Problem with long links after add event from message. Links are misinterpreted

example <https://teams.microsoftt.com/SIdjfj09u3nlknsdso2noenf08cn3ncinposdjhfsldnflksdmnfs269g234bk2jhg98cnASIHJans23lkndnfsdknfkjse3334u >

Rouncube 1.4.8
Libkolab/calendar last version

**Comment by alecpl** [comment]
We do not support external plugins here.
