### ISSUE TITLE
Transparent menu in autocomplete contacts

### ISSUE THREAD

**Issue by carloshilgemberg** [roundcube/roundcubemail#7600]
This occurs using the Roundcube platform through the standard repository cPanel

My scenario:
WHM / cPanel: 90.0.8
RoundCube 1.4.7
Skin: Elastic

I contacted cPanel but they were unable to resolve it. Does anyone have any idea what the problem might be?

I have already reinstalled, deactivated plugins, and created a new virtual machine and everyone has the same problem.

**Comment by carloshilgemberg** [comment]
![erro](https://user-images.githubusercontent.com/36273475/92976483-fef92500-f460-11ea-83f4-ce2a47b70aeb.jpg)

**Comment by smares** [comment]
Could this be the same issue as #7223 ?

**Comment by alecpl** [comment]
No, but this is the same as #7461. Are you sure you disabled all plugins? What browser?

**Comment by carloshilgemberg** [comment]
Yes, even with all plugins disabled (image attached).

With Internet Explorer I have no problems
With Google Chrome, Mozilla Firefox, Edge all have this error.

I made a copy of Roundcube out of cPanel.
Copied from: /usr/local/cpanel/base/3rdparty/roundcube
To: /home/user/public_html

That is, the problem only happens in the default cPanel directory for shared hosting.
![plugins](https://user-images.githubusercontent.com/36273475/92995386-900be280-f4d9-11ea-8d5a-b681b33c72b2.JPG)
![ie](https://user-images.githubusercontent.com/36273475/92995409-c47f9e80-f4d9-11ea-8377-8c2715a265e7.JPG)

**Comment by alecpl** [comment]
So, we can assume it's cPanel issue, can we? Definitely something is breaking css, and it does not happen in other environments.

**Comment by carloshilgemberg** [comment]
> So, we can assume it's cPanel issue, can we? Definitely something is breaking css, and it does not happen in other environments.

Perfect, it's a cPanel error.
