### ISSUE TITLE
CSP: referrer is deprecated

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7602]
In the current version of the .htaccess file the following can be found:

```
# CSP - Content Security Policy
# for better privacy/security ask browsers to not set the Referer
# more flags for script, stylesheets and images available, read RFC for more information
# Note: "Referrer-Policy: same-origin" is already set by php code.
#Header set Content-Security-Policy "referrer no-referrer"
```

However, setting `Content-Security-Policy "referrer no-referrer"` is deprecated according to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/referrer. The alternative would be https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy which is already set in the code.

**Comment by alecpl** [comment]
Removed.
