### ISSUE TITLE
some html emails hangs on subrequest _task=utils&_action=modcss

### ISSUE THREAD

**Issue by ata-sql** [roundcube/roundcubemail#7605]
When opening several email (html with pdf attachement) subrequest with params:
_task: utils
_action: modcss
_u: tmp-fb378ef6007528f4705032b027287799.css
_c: message-htmlpart1
Lasts until 1 minute timeout occures.
No error messages in console log (except 502 for that request) and webpage (including email) looks like rendered correctly.

**Comment by alecpl** [comment]
The utils/modcss action is responsible for downloading a css file referred in the HTML message and return the content (making it safe). So, it might be that it can't download the file for some reason. Anything in the Roundcube error log?

**Comment by ata-sql** [comment]
Roundcube's logs are clear. Apache after one minute logs 404:
`192.168.54.10 - - [16/Sep/2020:06:04:57 +0200] "GET /?_task=utils&_action=modcss&_u=tmp-fb378ef6007528f4705032b027287799.css&_c=message-htmlpart1 HTTP/1.1" 404 35 "https://webmail.efinity.com/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1&_uid=492561&_mbox=INBOX&_framed=1&_action=preview" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36"
`

**Comment by MartyMacGyver** [comment]
I don't have logs to add (I'm on shared hosting and Roundcube's logs aren't informative here) but when sending or saving a draft of an email I get the spinner and it ends up timing out.

Affects Roundcube 1.41 - 1.48 (I upgraded in the midst of debugging this) via Chrome 85.0.4183.83 (Official Build) (64-bit) - Slightly outdated Firefox works fine.

**Comment by MartyMacGyver** [comment]
Update: my issue turned out to be a third-party extension (Dark Reader) which seems to be having issues.

In case it's somehow related @ata-sql have you tried this in a different browser (or in a guest mode of your browser), with no extensions loaded? I originally replied here because the symptoms sounded familiar but at leas this will help you narrow it down.

**Comment by ata-sql** [comment]
Didn't try to disable extensions, but tried Firefox 80.0.1 and behaviour is the same.

**Comment by MartyMacGyver** [comment]
Unrelated then.

**Comment by ata-sql** [comment]
I've upgraded RC to 1.4.8, disabled all plugins and didn't change nothing.
I've also noticed, that while opening such emails, apache logs to error such entry:
[Fri Sep 18 06:23:29.351789 2020] [proxy_fcgi:error] [pid 637:tid 139705186236160] (70007)The timeout specified has expired: [client 192.168.108.20:48424] AH01075: Error dispatching request to : (polling), referer: https://myhost/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1&_uid=492561&_mbox=INBOX&_framed=1&_action=preview

**Comment by alecpl** [comment]
Roundcube itself does not return 504, so that's probably a http server response. Makes sens if the request takes too long to finish.

If you disable allow_url_fopen in php config and make sure you have php-curl installed/enabled, it will choose a different path that might work, or hopefully show some error in logs.

Is downloading from port 80/443 from the internet to the server allowed at all (firewall)?

**Comment by alecpl** [comment]
No feedback.

**Comment by ata-sql** [comment]
Sorry, missed last comment. Will try it on Monday.

**Comment by ata-sql** [comment]
Hello,
tried with _allow_url_fopen = Off_ option and on Chrome 85.0.4183.121:
1. logs are still empty
2. request now looks like:
*?_task=utils&_action=modcss&_u=tmp-fb378ef6007528f4705032b027287799.css&_c=message-htmlpart1*
params as below:
```
_task: utils
_action: modcss
_u: tmp-fb378ef6007528f4705032b027287799.css
_c: message-htmlpart1
```
and finishes after 15s with status cancelled, console logs:
```
Refused to apply style from 'https://webmail.efinity.com/?_task=utils&_action=modcss&_u=tmp-fb378ef6007528f4705032b027287799.css&_c=message-htmlpart1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

Firefox 81.0.1 looked similar:
request to */?_task=utils* ended with 404 after 15 seconds and console logged two errors:
```
GET https://webmail.efinity.com/?_task=utils&_action=modcss&_u=tmp-fb378ef6007528f4705032b027287799.css&_c=message-htmlpart1 [HTTP/2 404 Not Found 15177ms]
The resource from “https://webmail.efinity.com/?_task=utils&_action=modcss&_u=tmp-fb378ef6007528f4705032b027287799.css&_c=message-htmlpart1” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```
With link to https://developer.mozilla.org/pl/docs/Web/HTTP/Headers/X-Content-Type-Options
Please notice, that due to security recomendations, we applied https://docs.sucuri.net/warnings/hardening/security-headers-x-content-type-nosniff/ on our frontend apache proxy.

**Comment by alecpl** [comment]
Headers might be irrelevant. Something is timeing out. Is the css file (referred by the HTML message) that is being fetched from the external host even existing?

**Comment by ata-sql** [comment]
> Is downloading from port 80/443 from the internet to the server allowed at all (firewall)?

You mean if roundcube host can connect 80/443 to internet's hosts? Nope, it is blocked - it should use proxy. Enviroment variables are set though.
I dumped traffic and found requests like:
`12:29:49.387438 IP webmail-1.47378 > waw02s17-in-f10.1e100.net.https: Flags [S], seq 511232701, win 64240, options [mss 1460,nop,nop,sackOK,nop,wscale 7], length 0`
it tries to fetch something without proxy server - what is that? Is there a way to force RC to use proxy? I didn't find anything matching in defaults.inc.php file.

**Comment by alecpl** [comment]
As I've said, it has to download css files referred in HTML messages. With current code proxies aren't supported.

**Comment by ata-sql** [comment]
OK, now it's clear.
I guess it could be that code from email:
```
    <!--[if !mso]><!---->
    <link href=3D'https:=
//fonts.googleapis.com/css?family=3DOpen+Sans:300,400,700&subset=3Dlatin,la=
tin-ext' rel=3D'stylesheet' type=3D'text/css'>
    <![endif]-->
```
Problem investigated, athough not fixed.
Is proxy support planned at all?

**Comment by alecpl** [comment]
Not planned, but if you provide a pull request we'll consider.
