### ISSUE TITLE
List of possible rcmail_config['dont_override'] options.

### ISSUE THREAD

**Issue by rc2pc2** [roundcube/roundcubemail#7608]
Cheers everyone,
I'm trying to edit some of my Roundcube instance settings, for example hiding the contacts tab and identities settings tab, but I find myself unable to do so.

After looking around a bit I found that the best way should be using this statement configuration:
`$rcmail_config['dont_override'] = array('skin', 'whatever_I_need_to_be_unchanged', 'and_so_on')`

At this point, _given that I'm not mistaken using this directive_, I find myself in the need of a comprehensive list of **_keywords_**, if you can pass me the term, to use in that configuration line. 

Is it possible to find it somewhere?

I'd be happy to document the whole process, once I have grasped it.  

Thanks in advance,
Riccardo

**Comment by alecpl** [comment]
You can put there any existing option name. You can find all options in defaults.inc.php. Note, that it also accepts plugin configuration options which usually you can find in plugins/*/config.inc.php.dist.

**Comment by rc2pc2** [comment]
Thanks a lot! Sorry if I didn't see that by myself.

I'm totally able to use it to remove functionalities but I'm still unable to hide the main Contacts button on the side panel.

Is there something I should do differently?

**Comment by rc2pc2** [comment]
Thanks for your help!
