### ISSUE TITLE
Contact Import: allow adding existing contacts to group group

### ISSUE THREAD

**Issue by jgmy** [roundcube/roundcubemail#7609]
Hi!
Imagine you are adding an employee list to your roundcube address book:
```
﻿last_name,first_name,email,group,
Smith,John,john@smith.com,Employees
```
But  "Smith, John" <john@smith.com> is already on your address book in the group "Friends"

Roundcube ignores John Smith instead off adding it to the "Employees" group.

I think you could want to have it listed at both groups just in case you want to get a quick list of all your "employees".

**Comment by alecpl** [comment]
You could also want it to be removed from Friends. I think the current behavior is the best. We ignore any existing users.

**Comment by jgmy** [comment]
Well, my concern comes from the fact this year my school uses roundCube to
manage the school email.

I have to contact all students using the school email platform and the
school-provided student email.

Having a CSV listing of students, I need the ability to load it and change
students from "level 1 class X subclass Y" to "level 2 class Z subclass A".

But I can only do it if I clear all my "private contacs". Doing so would
also clear the listings of "School teachers", "language department
teachers" and "School principal office".

Yours,

José G Moya
