### ISSUE TITLE
How to connect RoundCube to Gmail?

### ISSUE THREAD

**Issue by RGJJANSEN** [roundcube/roundcubemail#7610]
There are several so called manuals on how to connect RoundCube to Gmail.
But no one is really clear.
I want to be able to receive and send all the mails in my Gmail account from my RoundCube account.

The thing is, I don't know what to fill in.
First of all, when I try to connect. It asks 'name' and 'email' in the gmail settings > accounts > receive mail as > add new.
So I fill in my own name and the email adress it is about info@mydomain.nl

Then it asks for SMTP-server? What is that first of all. And what should I fill in here. Standard is mail.mydomain.nl
Then it asks for a username. I believe I need to fill in the username from RoundCube? Well I never got a username, so I don't know what to fill in.

Then the password of?? What. 

It says 'Port'. What port? Which number? And should I connect through SSL or TLS or no secured connection at all???

I get irritated because RoundCube has no simple guide for this. 
For the person who don't know sh*t about this, this is very unclear.

**Comment by thomascube** [comment]
First of all, there's no such thing as a "RoundCube account" in terms of the software. So

A) You need to find a hosting provider who runs Roundcube for you. Then ask that particular hosting company for instructions how to connect with Gmail.

B) As an alternative, you can install Roundcube on a dedicated or shared web hosting server of your choice. This option, however, is for sysadmins or other technically savvy people how have a basic knowledge of email systems, web hosting and server management. If you **don't know sh*t about this**, then this is the wrong place to ask and you should go with option A).

**Comment by anjantalatam** [comment]
Get a Copy from your domain email to gmail
1. Go to CPanel dashboard and add an Forwarder email ( your gmail that you want to receive a copy )

Send emails from gmail with your domain email
1. Go to Gmail > settings > See all settings > Accounts and Import > Send mail as > Add another email address 
2. Enter Name and email 
3. Enter smt server ( your domain )
4. Enter username and password ( cpanel username, password ) 
5. Change port to 465
6. Click Add Account and verify the OTP

If you want to watch and do: https://youtu.be/gIlSKKMz9z0?si=GmPPupOcmn4S_Xmh&t=197

**Comment by jackera1111** [comment]
a

**Comment by AlbertTaylor** [comment]
**Shoviv [IMAP to IMAP Migration Tool](https://www.shoviv.com/imap-to-imap-migration.html)** is a powerful solution for seamlessly migrating emails from RoundCube to Gmail. This tool offers a user-friendly interface and advanced features to ensure a smooth migration process.
Here's a brief overview of the steps involved:

Installation: Download and install the Shoviv tool on your system.
Configuration: Set up the source (RoundCube) and destination (Gmail) accounts, including their respective IMAP server details.
Mapping: Map the folders between RoundCube and Gmail to ensure accurate data transfer.
Migration: Initiate the migration process, customizing options like date filters or specific folder selections.
Verification: After completion, verify the migrated data in your Gmail account to ensure everything has been transferred correctly.
With Shoviv IMAP to IMAP Migration Tool, you can efficiently move your RoundCube data to Gmail, preserving the integrity of your emails and other information.

**Comment by rdixit12** [comment]
Although there are several options to perform Roundcube to Gmail migration. However, SysTools **[IMAP Migration Tool](https://www.systoolsgroup.com/imap/migration/)** is the best software to migrate your Roundcube emails to Gmail. You can use the software easily without having experience of running tools. This tool has already covered 100+ Rounducbe to Gmail migrations.
