### ISSUE TITLE
Displays the "quoted-printable" or "BASE64" encoding instead of UTF-8 in incoming messages.

### ISSUE THREAD

**Issue by DayDve** [roundcube/roundcubemail#7611]
Hi, all!
Roundcube displays incorrect text of incoming messages.
Instead of UTF-8, is displayed rubbish in the form of characters in a "quoted-printable" or "base64" encodings.
For example:  

![image](https://user-images.githubusercontent.com/36878110/93463719-1b92d280-f923-11ea-9495-61265c71748b.png)

[Headers of message from example image](https://github.com/roundcube/roundcubemail/files/5238718/RC_wrong_mail_headers.txt)

In another mail client (e.g. rainloop or thunderbird) messages body displayed correctly.

Version of used RoundCube: **1.4.8**
Version of PHP: **7.4**

**Comment by alecpl** [comment]
This often is a result of an IMAP server bug. Try with `$config['imap_disabled_caps'] = array('BINARY');`. Requires re-login.

**Comment by DayDve** [comment]
> $config['imap_disabled_caps'] = array('BINARY');
Thank you very much! That helped!
