### ISSUE TITLE
Larry: mail window text-under-icons clipped/truncated

### ISSUE THREAD

**Issue by pgnd** [roundcube/roundcubemail#7612]
I've installed

	Roundcube Webmail 1.4.8 [GIT 20200826.1038]

I've config'd/selected "Larry" skin.

The text under the mail window icons,

	Refresh : Compose : Reply: Reply All : Forward : Delete : Mark : more

is slightly truncated/clipped:

![Clipped Button Text](https://i.imgur.com/LINc3Kp.png) 

It appears to be independent of changing window size or zoom

**Comment by alecpl** [comment]
What browser? Maybe browser zoom?

**Comment by pgnd** [comment]
> What browser?

Firefox 80.0.1, Chrome 85.0.4183.102 & Chromium 85.0.4183.83 all display the same

> Maybe browser zoom?

>   > It appears to be independent of changing window size or zoom

**Comment by alecpl** [comment]
Are you using any plugins? I also notice that the logo and menu position is wrong.

**Comment by pgnd** [comment]
> Are you using any plugins?

yes. atm,
```
$config['plugins'] = array(
        'archive',
        'managesieve',
        'password',
        'zipdownload',
        'twofactor_gauthenticator',
        'carddav',
);
```

**Comment by alecpl** [comment]
It might not be the reason, but you should test with all plugin disabled.

**Comment by pgnd** [comment]
> test with all plugin disabled.

with
```
$config['plugins'] = array();
```

no change; text-under-icons clipped, as above

**Comment by pgnd** [comment]
fwiw, upgrade to Roundcube Webmail 1.4.9 [GIT 20200826.1038] didn't auto-magically fix the truncations; same as above.

certaily not a big deal; mostly aesthetc, since you can still make out the  text.

no such issue in Elastic.  which I'd use, but can't seem to figure out how to get it to display message UNDER message list, rather than wide-screen, 3 column ...

**Comment by alecpl** [comment]
Maybe something's wrong with the font and/or system settings. You're the only user with this issue. I'm closing this.

**Comment by pgnd** [comment]
right ...
