### ISSUE TITLE
My contacts vs Trusted senders vs Known senders

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#7614]
In relation to  #6904 and  #5124 I propose to define what "My contacts" and "Trusted senders" exactly means (or should mean). The "Known senders" we use in one place should go away.

1. Trusted senders: Contacts (addresses) existing in the collected_senders addressbook (note that it can be set to use your main addressbook).
2. My contacts: Contacts in all of my writeable addressbooks and collected_recipients and collected_senders (note that both can be set to use your main addressbook).

This might involve some changes to existing configuration options.

3. Move "On request for return receipt" from Mailbox View to Displaying Messages section,
4. Change "On request for return receipt" selection options to contain:
    - "Ask me",
    - "Send receipt",
    - "Send receipt to my contacts, otherwise ask me",
    - "Send receipt to my contacts, otherwise ignore",
    - "Send receipt to trusted senders, otherwise ask me",
    - "Send receipt to trusted senders, otherwise ignore",
    - "Ignore receipt",
5. Change "Allow remote resources (images, styles)" in Displaying Messages to contain:
    - "never",
    - "from my contacts",
    - "from trusted senders",
    - "always".

The selection options containing "trusted senders" might become hidden if `collected_senders` is not set and is in `dont_override`.

Did I miss anything?

**Comment by johndoh** [comment]
At first glance I can't find how to add addresses to the Trusted Senders list. Perhaps a second button needs to be added to the "Allow remote resources" banner that is shown at the top of message so that there is "Allow once" and "Always allow"? I guess the same thing for Read receipt? Send now, Always send, do not send.

Note: The read receipts still use a browser confirm box rather than a Roundcube dialog box so multiple options are not currently possible but I could work on that if its useful.

**Comment by alecpl** [comment]
As for the remote resources banner, there's "Allow from <email>" button when "Allow remote resources (images, styles): from my contacts" (or from trusted senders). And only in this position contact existence is being checked. When set to "never" it is not checked. What you're proposing makes sense, but it will mean that we have to search for contact existence in both cases. And maybe we should rename "never" to "never, ask me".

As for the receipt handling... It might indeed have sense to change this dialog to include "Always send receipt to this sender" (or maybe use some different wording).

Another idea to think of. Should the receipt confirm box/dialog be converted to the inline banner? I'm not sure, it could have been overlooked by users. What do you think?

**Comment by johndoh** [comment]
> As for the remote resources banner, there's "Allow from " button when "Allow remote resources (images, styles): from my contacts" (or from trusted senders). And only in this position contact existence is being checked. When set to "never" it is not checked. What you're proposing makes sense, but it will mean that we have to search for contact existence in both cases. And maybe we should rename "never" to "never, ask me".

Perhaps the "Always allow" option should only be displayed on the banner if the config positoin is set to contacts/trusted senders. Then we don't need an extra contact existence check but the users who want this setup still quickly/easily add new users to the list?

> And maybe we should rename "never" to "never, ask me".

I think "never, ask me" is a slightly confusing label. may be "Not now"? 

> Another idea to think of. Should the receipt confirm box/dialog be converted to the inline banner? I'm not sure, it could have been overlooked by users. What do you think?

I wonder if users may confuse it with the remote images banner at a quick glance and then ignore it or worse send a receipt when they meant to enable images. I think a confirm box/dialog might be more appropriate.

**Comment by alecpl** [comment]
Let's clarify. Here's the current behavior:
- "Allow remote resources: always". No dialog/button, as everything is always allowed.
- "Allow remote resources: never". There's "Allow" button in the email preview. Clicking it will allow remote resources for the specified message. No addressbook is involved.
- "Allow remote resources: from known senders". There's "Allow" button which acts as above. and there's "Always allow from <email>" which acts like "Allow", but adds the sender to trusted sender database. When the message is being open we check if the sender is in trusted senders (or default) addressbook.

So, you're proposing to add a button in option 1? I don't like this idea. Indeed, if users allow remote resources from everyone there's no need for trusted senders addressbook... until we decide to use this source also for read receipts. I think it would make much sense. Of course, there's still be users that can say, "I trust this user resources, but I don't want to send a reply to him". Is it really something we should support? I'm still not sure. But if we don't it would make things simpler and more straight forward. I.e. we could unify remote resources and read receipts.

So, for example receipt dialog would have "Send" and "Ignore" buttons. But in "Send receipt to my contacts (trusted senders), otherwise ask me" modes there could be a third button "Always send to <email>".

Maybe to increase users awareness and vocabulary adoption we should instead of "Always allow..." and "Always send..." do "Allow and trust the sender" and "Send and trust the sender"?

**Comment by johndoh** [comment]
> Let's clarify. Here's the current behavior:

Right, I missed that the "Always allow from" was already there with the known senders option. Ignore my comments about the remote resources banner. What I was suggesting is already the current behavior.

> Of course, there's still be users that can say, "I trust this user resources, but I don't want to send a receipt to him". Is it really something we should support?

In the current behavior there is only 1 "safe" list, Contacts which is applied to both remote resources and receipts. Trusted Senders adds a second source so you could set remote resources to "always from trusted senders" and receipts to "always from my contacts".

**Comment by alecpl** [comment]
Done.
