### ISSUE TITLE
guzzle warning

### ISSUE THREAD

**Issue by gene-git** [roundcube/roundcubemail#7616]
Good day:

Building from git today I get these 2 warnings (assume from composer)

_Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested._
_Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested._

Seems benign - at least short term but perhaps may want to avoid ?

**Comment by alecpl** [comment]
@thomascube could you verify if we can bump to guzzle 6.5? It will bump minimum PHP version to 5.5, but only to those using OAuth, so it should be fine.

**Comment by gene-git** [comment]
Yes - confirm that changing composer.json to require guzzle 6.5 makes the warning go away. thank you!

**Comment by alecpl** [comment]
It would be also fine if we bump the required PHP version to 5.5, but keep the code compatible with 5.4 for Roundcube 1.5. Roundcube 1.6 will most likely require at least PHP 7.0. I'm not yet sure if supporting both PHP8 and PHP5 in Roundcube 1.5 will make sense, but that is my plan as of now. Considering our code style it might be not a trivial task.

**Comment by thomascube** [comment]
> @thomascube could you verify if we can bump to guzzle 6.5? It will bump minimum PHP version to 5.5, but only to those using OAuth, so it should be fine.

@alecpl We could indeed and it'd likely only affect systems that use OAuth. However, the dependency is still in composer.json and thus would reject (or warn) on every installation. But I'd be fine with the decision to bump the minimum requirements to 5.5 which itself has declared end-of-life long time ago.

**Comment by alecpl** [comment]
Done.
