### ISSUE TITLE
Elastic: cannot edit contacts on small/phone screen

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7617]
When in `layout-small` or `layout-phone` the edit button in the footer of the view contact screen is always disabled. The Next/Prev buttons work fine. On bigger screens the edit button is enabled as expected.

Tested with git-master.

**Comment by alecpl** [comment]
Works for me in firefox mobile mode.

**Comment by johndoh** [comment]
Forgot to disable all plugins. sorry.
