### ISSUE TITLE
Enhancement: Indicate in message list if my mail address was recipient in "To:" or "Cc:" or none

### ISSUE THREAD

**Issue by bluikko** [roundcube/roundcubemail#7620]
Currently in the message list view there is an indicator on left side that shows if an e-mail was replied to or forwarded.

For messages that were not replied or forwarded the indicator is a black ball.

This issue proposes to enhance that "black ball" to indicate how the mail was sent to me:
- If my mail address (any of them?) is in the "To:" field, then continue to show the "black ball" as indicator.
- If my mail address (any of them?) is in the "Cc:" field, then show a black circle (with white point in the middle).
- If my mail address was in none of the recipient headers, then show a small black point.

**Comment by alecpl** [comment]
I don't like the idea. Write a plugin.

**Comment by bluikko** [comment]
Outlook does it and there'd been some questions if Roundcube does something similar. It did not occur to me that a plugin could do even that. Thanks for your consideration!
