### ISSUE TITLE
Connection failed: Failed to connect socket: Connection refused

### ISSUE THREAD

**Issue by lauw0129** [roundcube/roundcubemail#7621]
I am trying to use ssl to setup the roundcube. But I keep getting an error 
`(Connection failed: Failed to connect socket: Connection refused)`
the config below
```
smtp server: ssl://mail.example.com
smtp port: 465
imap server: ssl://mail.example.com
smtp port: 993
```
I have tried a lot of method, such as change port and use ip, also not working. Please help

**Comment by alecpl** [comment]
Use mailing list or forum. This looks like configuration/deployment issue, not a bug.
