### ISSUE TITLE
APK - Improper Error Management - Authenticated Login - Dispaly Message (Login failed)

### ISSUE THREAD

**Issue by aashiqahamedn** [roundcube/roundcubemail#7623]
In the Round cube app when the authenticated user tries to login into the account the login is successful but the display message is wrong it showing as '**Login Failed**' Message.
![Round Cube Mail](https://user-images.githubusercontent.com/33874453/93979776-98161e80-fd32-11ea-8745-b094e83ef0e6.jpeg)

**Comment by alecpl** [comment]
Did you try with disabled all plugins and default skins?

**Comment by alecpl** [comment]
We do not support APK here, anyway.

**Comment by aashiqahamedn** [comment]
Then how to report bug for APK

**Comment by alecpl** [comment]
I have no slightest idea. The app is not ours.

**Comment by aashiqahamedn** [comment]
Then belongs to https://play.google.com/store/apps/details?id=smalltownboys.rc&hl=en_IN  Is this the official app or not.

**Comment by alecpl** [comment]
I'm not sure what do you mean by official. It has nothing to do with our project. And I don't think they have permission to use our logo. Maybe we should do something about it.

**Comment by aashiqahamedn** [comment]
Yes sure, I got confused that it's an original one and I installed the app. Take Necessary action against them.
