### ISSUE TITLE
Empty output from HTML5 parser with XML tag

### ISSUE THREAD

**Issue by dmfr** [roundcube/roundcubemail#7624]
Consider the following (bogus ?) HTML found in some emails :

`<?xml encoding="UTF-8"><html><head><meta charset="UTF-8" /></head><body>HTML contents here</body></html>`

Roundcube is going to display an empty preview / message, unless either
- Masterminds HTML5 parser is disabled 
or
- `rcube_washtml::cleanup` strips every xml tag :
_$html_search_ array should then include `'/<\?xml\s[^>]+>/i'`

Any chance to include a larger cleanup mask for (bogus) xml tags ?

**Comment by alecpl** [comment]
Confirmed.

**Comment by alecpl** [comment]
Fixed.
