### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#7625]
There's been some changes in git-master in this direction, but I'll start working on this for real when I have PHP8 package for Ubuntu available.

Considering our coding style it will be a lot of work. PHP8 for example throws a warning on undefined array key use.

**Comment by eilandert** [comment]
I've build a docker with roundcube-git and php8rc3, running it on a low volume box now for testing. Seems fine! Thanks.

Docker can be found on https://hub.docker.com/r/eilandert/roundcube

**Comment by alecpl** [comment]
I finished code review and fixes in this context. More issues are expected though, as our code coverage is around 30% only.

Please, create a new ticket if you find any issues.

**Comment by rimas-kudelis** [comment]
Is there any ETA as to when PHP8 changes will be released?

**Comment by smirkybg** [comment]
Looking forward to this. My distro pushes new shiny stuff out sooner rather than later. Hope Roundcube can align soon :)
