### ISSUE TITLE
phpunit warning

### ISSUE THREAD

**Issue by gene-git** [roundcube/roundcubemail#7626]
Good day

FYI - Building from git today _composer update_ shows this warning:

_Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested._

**Comment by alecpl** [comment]
It is a dependency of php-code-coverage, which is a dependency of phpunit. For now we can't update to phpunit 9 which would fix this issue because we still support PHP5. As this is a devel dependency, we can live with this.
