### ISSUE TITLE
jstz.min.js not found

### ISSUE THREAD

**Issue by mandza** [roundcube/roundcubemail#7627]
While loging in I get error that jstz.min.js file is not founded, but I could not find that file in this repository at all.
Some code is trying to get this file but probably there is no need for this file at all.
I use 1.4.8 fresh install.
Exact error: program/js/jstz.min.js net::ERR_ABORTED 404 (Not Found)

**Comment by alecpl** [comment]
Duplicate. It's been fixed by fcfde1a0ece8.
