### ISSUE TITLE
Calendar not displaying properly

### ISSUE THREAD

**Issue by JenUpMe** [roundcube/roundcubemail#7628]
Hi, 

It looks like the calendar is not displaying properly. I can't do anything on this page (see calendar, create meeting invitations...).

Can you please help?

Thanks

<img width="1407" alt="Screenshot 2020-09-23 at 16 25 44" src="https://user-images.githubusercontent.com/71778764/94034196-a6f3e400-fdb9-11ea-94d7-fec95a71cf19.png">

**Comment by alecpl** [comment]
We do not support Calendar here. I guess, it's because Calendar plugin does not support the Classic skin.

**Comment by JenUpMe** [comment]
Ok thanks!
