### ISSUE TITLE
Req: Backport "enhancement: elastic skin: allow to drag & drop addresses between address input fields during compose message"

### ISSUE THREAD

**Issue by raoulbhatia** [roundcube/roundcubemail#7632]
Hi Roundcube team,

any chance to get #7345 backported to 1.4?

Having no way to move email addresses between TO and CC is quite impacting, as not all email addresses might be in the address book and otherwise one needs to fall back to typing the emails addresses by hand.

Thanks,
Raoul

**Comment by alecpl** [comment]
Sorry, but no.
