### ISSUE TITLE
New Guzzle Version Breaks OAUTH Support 

### ISSUE THREAD

**Issue by felix-gohla** [roundcube/roundcubemail#7634]
Hi :),

bumping the Guzzle version >=6 (commit 1cc9d4f566c911662fba51b93aafc8b58d60a1f5, issue #7616) breaks OAUTH support as the `Guzzle\Http\Message\Response::json()` function is not available in Guzzle >=6.
Instead, `GuzzleHttp\json_decode` should be used.
As of now [rcmail_oauth.php](https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail_oauth.php#L225) still uses the `json()` function and `body` instead of `form_params` in the `$client→post(...)` call (which throws a deprecation warning).

*Warnings and Errors from PHP container:*
```
errors: <b6de0150> PHP Error: OAuth token request failed: Passing in the "body" request option as an array to send a POST request has been deprecated. Please use the "form_params" request option to send a application/x-www-form-urlencoded request, or the "multipart" request option to send a multipart/form-data request. in /var/www/html/program/include/rcmail_oauth.php on line 297 (GET /index.php?_task=login&_action=oauth&&state=...)
```

```
NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method GuzzleHttp\Psr7\Response::json() in /var/www/html/program/include/rcmail_oauth.php:226
172.29.0.4 -  27/Sep/2020:19:56:10 +0000 "GET /index.php" 500
Stack trace:
#0 /var/www/html/program/steps/login/oauth.inc(27): rcmail_oauth->request_access_token('97513284-5840-4...', 'An2lpk8WelVe')
#1 /var/www/html/index.php(193): include('/var/www/html/p...')
#2 /var/www/html/public_html/index.php(26): include('/var/www/html/i...')
#3 {main}
  thrown in /var/www/html/program/include/rcmail_oauth.php on line 226
```

**Comment by thomascube** [comment]
Fixed in Git master

**Comment by felix-gohla** [comment]
Thanks for responding that fast. 😊
I found some more usages of `json()` and fixed them.
