### ISSUE TITLE
version 1.4.9 broke the calendar plugin

### ISSUE THREAD

**Issue by robo2bobo** [roundcube/roundcubemail#7636]
I just upgraded from v1.4.8 to v1.4.9. While I can login without a problem, I  can't view emails, the body page is empty.

Looking at the firefox output, I see the iframe requests return 500 server error. Further investigation, shows lots of php errors:

```
PHP Fatal error:  Uncaught Error: Class 'Sabre\VObject\Property\Text' not found in /home/user/public_html/plugins/libcalendaring/libvcalendar.php:1451
Stack trace:
#0 /home/user/public_html/plugins/libcalendaring/libcalendaring.php(158): require_once()
#1 /home/user/public_html/plugins/libcalendaring/libcalendaring.php(1123): libcalendaring::get_ical()
#2 /home/user/public_html/plugins/calendar/calendar.php(2892): libcalendaring->get_mail_ical_objects()
#3 /home/user/public_html/program/lib/Roundcube/rcube_plugin_api.php(469): calendar->mail_messagebody_html(Array)
#4 /home/user/public_html/program/include/rcmail_output_html.php(1475): rcube_plugin_api->exec_hook('template_object...', Array)
#5 [internal function]: rcmail_output_html->xml_command(Array)
#6 /home/user/public_html/program/include/rcmail_output_html.php(1209): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:incl...')
#7 /home/webma in /home/user/public_html/plugins/libcalendaring/libvcalendar.php on line 1451
```

The first thing I noticed, is that I could not downgrade. I downloaded the previous v1.4.8 archive, run ./bin/installto.sh which did not allow me to install v1.4.8. Eventually, I had to disable the calendar plugin via the config.inc.php.

**Comment by alecpl** [comment]
The error comes from libcalendaring plugin, we do not support it here.

**Comment by robo2bobo** [comment]
Sorry for opening the bug report in the wrong place.

I've never seen a project that is so confusing...

- There is a [github project page](https://github.com/kolab-roundcube-plugins-mirror/calendar), but the repo is a mirror and has no ability to create issues. Abandoned since 1 year ago.
- I also found a [gitlab project page](https://gitlab.com/kolab-roundcube-plugins/calendar/-/issues), also abandoned with last activity since 1 year ago.
- Finally, there is a code repository at [kolab.org](https://git.kolab.org/diffusion/RPK/browse/master/plugins/calendar/), which has no ability to post issues/bugs.

The plugin developers must be trying really hard to avoid getting feedback :)

**Comment by mandza** [comment]
I used roundcube for years with cpanel. Few days ago I decided to create my own mail server, this all stuff is PITA. postfix dovecot roundcube plugins, like a big farm of bugs, little bugs everywhere.
I dont know if roundcube was allways this active but alecpl seems very active on this one. Not so lucky with other projects.

**Comment by alecpl** [comment]
To me it looks like you have wrong version of Sabre dependencies. I have to idea how a switch from 1.4.8 to 1.4.9 could cause this error. Anyway, you should be able to create tickets at https://git.kolab.org.
