### ISSUE TITLE
RoundCube and YetiForce: Failed. Module does not contain default language (en-US)

### ISSUE THREAD

**Issue by MarcLee9** [roundcube/roundcubemail#7637]
Hi there, 

Firstly, Thanks in Advance. 

We have installed yetiforce docker image and busy customising it to see if the CRM is what we need. We noticed that roundcube mail module is not available. We tried download library action, downloading it from Github and installing it manually and we get the following Failed error: Module does not contain default language (en-US). 

Any help would be appreciated to resolve this issue. Looked on Github as well for any similiar issues. Looked online as well i.e. hotfix 3.4 but it was in 2017....

thanks

**Comment by alecpl** [comment]
You should ask YetiForce. I have no idea what are you talking about.
