### ISSUE TITLE
UI: Display FROM email address by default in favor of security

### ISSUE THREAD

**Issue by KasparVd** [roundcube/roundcubemail#7639]
I would consider myself quite tech savvy, however I am a bit embarrassed to confess that last month I got fooled by a phishing email. I only noticed it was a phishing email after I clicked a link in the email. The website landing page was way off. The email it self was a perfect copy from the emails send by a government agency in the country I live. Very hard to distinguish, expect for the bit.ly link in the email and the random (but valid) sender address.

How could I've missed this? Obvious it's the job of a spam filter to detect phishing emails in the first place. My spam filter (SpamAssassin) didn't. I should have noticed the bit.ly link in the email before clicking on it. I didn't. I also didn't notice the FROM name did not match the sender email address. Shame on me.

Still, I like to argue that Roundcube could have made difference in this scenario. By also display the FROM address on each email next to (or bellow) the FROM name. This way users can directly see when opening an message if there is something fishy about the FROM address. 

Currently in the Elastic skin when opening received messages the FROM name is only show. The FROM address is only visible when you hover the cursor over the FROM name.

**Comment by alecpl** [comment]
There's an option: Preferences > Displaying Messages > Show email address with display name. No, we'll not change the default.
