### ISSUE TITLE
Attachment icon not showing on mail from Apple Mail

### ISSUE THREAD

**Issue by macerlope** [roundcube/roundcubemail#7640]
In both Larry and Elastic themes, the attachment icon is not displayed on mail received from Apple Mail. This is in the main email 'list', in Larry the far right column and in Elastic on the right next to the mail subject.

From other sources e.g. Roundcube and Outlook, the icon is displayed correctly. On selecting the email the attachments are displayed correctly.

**Comment by alecpl** [comment]
Most likely the message is multipart/alternative. For performance reasons we do not fetch bodystructure (which would be required to do some more sophisticated checking for an attachment) of a message when listing them. This is a wontfix.

**Comment by chufrog** [comment]
1. Confirm such issue on a Apple Mail message, the "clip" icon not shown on a message with attachment.
2. Other email client able to identify the existing of attachment and show the "clip" icon
3. Will roundcube consider to allow the administrator / user to choose between performance / precise information?
4. Will roundcube consider to show the "clip" icon after the user open the message and cache such information (already fetched, no performance concern?)

**Comment by alecpl** [comment]
There's another way. Roundcube supports `$HasAttachment` flag. So, if your server (or sieve script) would set it on mail delivery, Roundcube would use it to show the clip icon.
