### ISSUE TITLE
Make changes to roundcubemail login page

### ISSUE THREAD

**Issue by ambuje** [roundcube/roundcubemail#7641]
I have been trying to make changes to the login page of roundcubemail but unable to do so.
Even I tried changing the logo but was not able to do.
I installed Mail in a box and it uses roundcubemail as it's mail service. 
Can anyone guide me how to make changes? For the logo I tried adding $config['skin_logo']=..... but the logo was not changed maybe I am not getting how to give proper path or so. Can anyone help mt out in these things?

Thanks

**Comment by alecpl** [comment]
Ask on mailing list or forum.
