### ISSUE TITLE
Microsoft Edge Autocomplete

### ISSUE THREAD

**Issue by jgmy** [roundcube/roundcubemail#7642]
Hi!
It seems that the autocomplete function of the new Microsoft edge stores as **self-address** any field called "name", "surname" or "address". 

This means that, if you edit all your contacts to change their names from "Honda Civic" or "White men killer" to "John Smith" or "Steve Jones" (yes, this is a real case), your autocomplete address list on Edge ends up with 20+ alien addresses.

While **I reported this to Microsoft**, I wonder if you could so something on the roundcube side, like changing the "firstname" and "surname" field names to something like "contact-first" or so.
?_task=addressbook
![2020-09-30 (2)](https://user-images.githubusercontent.com/2573642/94662905-532d5180-0309-11eb-89c8-839890843f67.png)

**Comment by jgmy** [comment]
Where it reads:

> This is the Profiles/Addresses and more Microsoft Edge page.

It should read
> This is the Profiles/"Addresses and more" Microsoft Edge page.

**Comment by alecpl** [comment]
We'll not change the field names. Wontfix.
