### ISSUE TITLE
Upgrade to RoundCube Mail Version 1.4.9 on CWP – Centos Web Panel

### ISSUE THREAD

**Issue by ioniacob** [roundcube/roundcubemail#7643]
Running update script at target...
PHP Fatal error: Uncaught Error: Class 'PEAR' not found in /usr/local/cwpsrv/var/services/roundcube/program/lib/Roundcube/bootstrap.php:103
Stack trace:
#0 /usr/local/cwpsrv/var/services/roundcube/program/include/iniset.php(62): require_once()
#1 /usr/local/cwpsrv/var/services/roundcube/program/include/clisetup.php(25): require_once('/usr/local/cwps...')
#2 /usr/local/cwpsrv/var/services/roundcube/bin/update.sh(23): require_once('/usr/local/cwps...')
#3 {main}
 thrown in /usr/local/cwpsrv/var/services/roundcube/program/lib/Roundcube/bootstrap.php on line 103

Following this tutorial: [https://www.mysterydata.com/upgrade-to-roundcube-version-mail-on-cwp-centos-webpanel/]

**Comment by alecpl** [comment]
Looks like missing dependencies. Ask on mailing list or forum.
