### ISSUE TITLE
constant popup "internal server error" // Email won't send 

### ISSUE THREAD

**Issue by 1Cesar** [roundcube/roundcubemail#7645]
About a week ago my emails would stop sending to one specific person and we can't find any problems on both sides. Just today a popup started coming up every couple minutes but won't direct me to the problem.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
