### ISSUE TITLE
Encoding Error on attached files name that uses international language when receiver used outlook to open 

### ISSUE THREAD

**Issue by ShaneStarmoney** [roundcube/roundcubemail#7646]
I found that when sending email with files attachments that name in international language via Roundcube webmail, there will have problem for receivers who use Outlook. 

The error happens with files attachments name, It cannot show file name correctly and sometimes cannot open that attached file.

Please see the error screen capture.
[https://ibb.co/RSfYpcN](url)

Regards,
Shane

**Comment by alecpl** [comment]
Check Preferences > Composing Messages > Advanced > Attachment names. There's an option for compatibility with Outlook.

Looks like Outlook can't even support 23 years old standard.

**Comment by ShaneStarmoney** [comment]
Dear Aleksander,

I tried to setting as you sent to me, and tried all other choices. But it
still does not work.

I have investigated in the source code and found the cause of error in the
red circle on the picture bellowed.
For my assumption then I tried to change the text in the red circle  and
save into .eml  and then opened it with
Outlook,   I found that it works now.

Before changing the text in circle
[image: image.png]

After changing the text in circle
[image: image.png]

Regards,
Shane

ในวันที่ พฤ. 1 ต.ค. 2020 เวลา 13:01 Aleksander Machniak <
notifications@github.com> เขียนว่า:

**Comment by alecpl** [comment]
You have to attach (drag-n-drop) the images to the ticket. Also, give us more details, Roundcube version, PHP version, OS, SMTP server, etc.

**Comment by ShaneStarmoney** [comment]
Dear Alexsandar,

Thanks for your email.
Actually, I'm a user that use your webmail via an email provider.
I don't know the detail of the system setting of the email provider
But I found this from email source code.  Could It help?

       User-Agent: Roundcube Webmail/1.2.2

Regards
Shane




ในวันที่ พฤ. 1 ต.ค. 2020 เวลา 13:33 Aleksander Machniak <
notifications@github.com> เขียนว่า:

**Comment by alecpl** [comment]
That's quite old and insecure version. If you're a user there's not much to discuss.
