### ISSUE TITLE
Autocomplete username/email address on login page

### ISSUE THREAD

**Issue by MrPOC** [roundcube/roundcubemail#7649]
Currently, the username/email address field on the login page has autocomplete attribute turned off. For better accessibility, it would be great if it could be turned on. Or even set to "email" value, so that the browser would only suggest email addresses, which makes even more sense, considering that, well, it's a webmail. But maybe that could break/be not relevant in some configurations ? In my configuration, users have to enter their whole email address and not having the browser autocomplete this is kinda frustrating.

**Comment by alecpl** [comment]
The autocomplete attribute is anyway ignored by most of the recent browsers, and they by default remember the username/password.

You may use these:
```
// Allow browser-autocompletion on login form.
// 0 - disabled, 1 - username and host only, 2 - username, host, password
$config['login_autocomplete'] = 0;

// Logon username filter. Regular expression for use with preg_match().
// Use special value 'email' if you accept only full email addresses as user logins.
// Example: '/^[a-z0-9_@.-]+$/'
$config['login_username_filter'] = null;
```
