### ISSUE TITLE
Elastic: Folders settings toggle button not updating if search is active

### ISSUE THREAD

**Issue by abshoff** [roundcube/roundcubemail#7652]
**Steps to reproduce:**

1. Activate Elastic theme
2. Go to Settings, Folders and search for an existing folder
3. Try to change the subscription setting in the list by clicking on the toggle button

**Expected result:**

Toggle button is updated.

**Actual result:**

Toggle button is not updated, but the correct subscribe/unsubscribe requests are fired.

**Browser:**

Google Chrome

**Comment by alecpl** [comment]
I've found a related issue. When you change the folder state on the search results list the checkbox on the main list didn't update. This has been also fixed.
