### ISSUE TITLE
mailto: In-Reply-To adds extra angle brackets

### ISSUE THREAD

**Issue by vitlav** [roundcube/roundcubemail#7655]
Roundcube adds extra angle brackets to In-Reply-To header from mailto:

For correct mailto URI
mailto:lav%40etersoft.ru?In-Reply-To=%3C1d947879f8191f06cc02fd7c47e41f48@etersoft.ru%3E

RoundCube does two brackets for each side:
In-Reply-To: <<1d947879f8191f06cc02fd7c47e41f48@etersoft.ru>>

See In-Reply-To related example in RFC 6068:
https://tools.ietf.org/html/rfc6068#section-6.1

For real example check mailto: link on the page
https://lore.kernel.org/lkml/1d947879f8191f06cc02fd7c47e41f48@etersoft.ru/

**Comment by alecpl** [comment]
Fixed.
