### ISSUE TITLE
Elastic: Possibility to change logo in menu.html via skin_logo variable

### ISSUE THREAD

**Issue by vaelu** [roundcube/roundcubemail#7657]
It would be cool if it would be possible to change the logo in the menu.html template with the `$config['skin_logo']` variable.

Currently, we had to modify this directly in menu.html. The problem is that then there is no option to use 2 different logos for desktop nav and mobile nav. We want to use the small logo for mobile nav in menu.html and standard logo for desktop nav in menu.html.

This could look like this:
```
$config['skin_logo'] = array(
  'elastic:menu' => 'image.url',
  'elastic:menu[small]' => 'image.url'
);
```

**Comment by vaelu** [comment]
Just noticed that it is possible when we change the `data-src-small="0"` to our small logo URL. But it's not possible to change this via config, right?

**Comment by alecpl** [comment]
According to docs in git-master `elastic:*[small]` should work.

**Comment by vaelu** [comment]
But with `elastic:*[small]`  you can't set a different logo for the menu.html template, it does then set the logo for all templates on small devices.

We use
- wordmark logo
  - login.html (desktop device)
  - menu.html (small device)
- lettermark logo
  - login.html (small device)
  - menu.html (desktop device)

To change the logo in menu.html with `elastic:menu` was my suggestion.

**Comment by alecpl** [comment]
I think you make it more complicated than needed. All you need is `elastic:*[small]` and `elastic:login` and maybe `elastic:*`.
