### ISSUE TITLE
Support proxy for server-side HTTP requests

### ISSUE THREAD

**Issue by ata-sql** [roundcube/roundcubemail#7658]
When node hosting roundcube has blocked outgoing traffic, strange things like #7605 happen,
Proxy should be configuration option and should be used when performing curl requests.

**Comment by thomascube** [comment]
I suggest to create a generic utility function to return a HTTP client based on Guzzle (which we now have as dependency) that inherit general settings from config. Example:

```
// config.inc.php

// global options for a GuzzleHttp\Client instance
// see http://docs.guzzlephp.org/en/latest/request-options.html
$config['http_client'] = array(
  'timeout' => 10,
  'proxy' => 'tcp://localhost:8125',
);
```

```
// rcmail_utils.php

class rcmail_utils
{
  ...
  public static function get_http_client($options = [])
  {
    $rc = rcube::get_instance();
    return new GuzzleHttp\Client($options + $rc->config->get('http_client'));
  }
}
```

**Comment by ata-sql** [comment]
Changed according to suggestions. Should I rather refactor all curl requests in the system or changing only modcss.inc is enough?

**Comment by alecpl** [comment]
I think for now it will be easier for you to do this in modcss only. The code in password plugin usually connects to internal infra, so it's not the same and we might need a separate configuration for that part.

**Comment by ata-sql** [comment]
Ready to merge then :).

**Comment by alecpl** [comment]
Please, update the PR.

**Comment by ata-sql** [comment]
Updated.

**Comment by alecpl** [comment]
Merged.
