### ISSUE TITLE
Enigma plugin: Unable to import PGP keys with offline secret master key (so-called "laptop keys")

### ISSUE THREAD

**Issue by m-ueberall** [roundcube/roundcubemail#7662]
At the moment, it is impossible to import secret PGP subkeys without the respective secret master key (see e.g. [here](https://alexcabal.com/creating-the-perfect-gpg-keypair) or [here](https://spin.atomicobject.com/2013/11/24/secure-gpg-keys-guide/) how and why **you want to use this to protect yourself against identity theft**), regardless of whether the browser-based UI or the [import_keys.sh](https://github.com/roundcube/roundcubemail/blob/master/plugins/enigma/bin/import_keys.sh) script is used in conjunction with `$config['enigma_multihost'] = true`.  In either case, no error message of any kind is provided.

One temporary workaround _might_ be to import the secret master key alongside the subkey(s) and to delete its respective _keygrip_ (see database table `filestore`, column `filename`) afterward, but there are a number of reasons why this is impractical (if not impossible in the first place).

**Comment by alecpl** [comment]
What enigma_debug has to say about this case? How do you normally would import these keys using gpg command?

**Comment by m-ueberall** [comment]
Ugh. After stopping/restarting _apache2_, _php7.4-fpm_, truncating the `filestore` table, removing all existing (outdated) account-specific subdirectories below `$config['enigma_pgp_homedir']`, and accessing _Roundcube_ using another browser (=no cached data left whatsoever), I cannot reproduce this error anymore. Great. (So no need to go through the previous `enigma_debug` logs for this.)
