### ISSUE TITLE
Improper Bytes to Megabytes conversion

### ISSUE THREAD

**Issue by elvisef** [roundcube/roundcubemail#7664]
I think something is wrong with the numbers... please tell mi if am I right.

I was about to send e-mail, but Roundcube told me that I have only 15MB for attachments.
But I've set "max_message_size" in Roundcube config to value of: 20971520 (it's approximately 20MB).
My PHP config are set both to 64MB.
And my postfix config value is set to: 20971520.

 I do not know why the numbers are not correct.
Please look at screenshots attached.

![putty_gbCfZBYuR1](https://user-images.githubusercontent.com/25976749/95583807-fcc4bf00-0a3c-11eb-84b2-232d1286cc68.png)
![firefox_cAdi7bKYR2](https://user-images.githubusercontent.com/25976749/95583683-c9823000-0a3c-11eb-95ef-82d26ae58615.png)
![firefox_jVl4OmIokP](https://user-images.githubusercontent.com/25976749/95583688-cab35d00-0a3c-11eb-865e-b62eb63cd215.png)
![putty_nHWK2CwUYi](https://user-images.githubusercontent.com/25976749/95583691-cb4bf380-0a3c-11eb-941c-d3c8f78f6a16.png)
![firefox_qIhCxuWfeI](https://user-images.githubusercontent.com/25976749/95584624-51b50500-0a3e-11eb-929b-973d18a7cf10.png)

**Comment by smares** [comment]
PHP -i will show you the CLI configuration. Do you have the same limits configured for FPM or Apache2?

**Comment by alecpl** [comment]
Attachments usually are base64 encoded, that's why if you set max_message_size the real attachment max size will be `20 / 1.33 ~= 15` in your case. We have a related #7342.

**Comment by elvisef** [comment]
> PHP -i will show you the CLI configuration. Do you have the same limits configured for FPM or Apache2?

I checked this in CLI and "not CLI" PHP config files. All were set to 64MB.

> Attachments usually are base64 encoded, that's why if you set max_message_size the real attachment max size will be `20 / 1.33 ~= 15` in your case. We have a related #7342.

Hmm.. so the base64 encoded file takes over more space and that is why the "max size" setting set in the config brings 20 / 1.33, as the real size we can send ?
