### ISSUE TITLE
Disable logging?

### ISSUE THREAD

**Issue by robo2bobo** [roundcube/roundcubemail#7665]
Hello,

I currently use the syslog log_driver, but I think its excessive and logs too many things. Now that my servers are stable and without problems, is it possible to disable logging completely?

For example, something like: $config['log_driver'] = null;

Thank you.

**Comment by robo2bobo** [comment]
I have thousands of lines like these:

```
roundcube[21266]: <6o6142ck> PHP Error: Request security check failed (POST /?_task=mail&_action=refresh)
```

and more thousands like these:

```
roundcube[21031]: <5ddohpuq> IMAP Error: Login failed for... <reducted>
```

In the first case, I think there is a timeout, which is irrelevant to me. In the second case, these are people who refuse to store their password in their browser and insist on typing it... wrongly most of the time, so these messages are also irrelevant.

Maybe my servers are a bit too busy than your average use case, but a week ago I counted about 100MB of roundcube only errors in my journal collector (collects multiple /var/log/maillog outputs from all servers and joins them together).

I think the only real errors are these below, but they are not from roundcube, they come from the calendar plugin, so I wasn't going to mention them, but for future reference they are:

```
 roundcube[40839]: PHP Warning:  Invalid argument supplied for foreach() in /opt/roundcube/plugins/calendar/drivers/database/database_driver.php on line 767
```

**Comment by alecpl** [comment]
I understand. There's no such option. You could write a plugin using `write_log` hook or use `log_driver=syslog` and swallow these errors on syslog side.

Maybe #6138 with `error_reporting=0` could be a solution too.

**Comment by robo2bobo** [comment]
Thanks for pointing out #6138, I think it would solve my problems and allow me greater control. I also think, it would help with having php errors/warnings within the maillog, which is a bit confusing.
