### ISSUE TITLE
Backup & export options for endusers

### ISSUE THREAD

**Issue by AFlowOfCode** [roundcube/roundcubemail#7668]
Is there a way that a user with no access to the installation on the server can export their complete mailbox, or at least some form of bulk other than manually downloading emails one by one? 

In previous versions there were options to download selected messages, as well as by folder. [The latest docs I could find](https://docs.roundcube.net/doc/help/1.1/en_US/mail/importexport.html) are from version 1.1 where this was still possible. Apparently that feature was removed at some point. I wonder why but won't ask for an explanation.

Is there a version where this was re-implemented? Or a plugin that serves this purpose effectively? We're on a 1.3 installation, if upgrading to 1.4 or installing a plugin is the way to access a solid export feature, I'd love to know. 

I looked through the releases list & changelog here on github to 1.3  as well as the [plugin list linked](https://packagist.org/?type=roundcube-plugin) from the site but didn't see anything. I see import/export features [listed on the site](https://roundcube.net/about/#features) but can't find info if that means something other than single-email exporting.

I'm aware users can download another email client to do this, but I'd like to know if there are any options from within Roundcube itself. Thanks for the help and for a nice piece of software.

**Comment by alecpl** [comment]
zipdownload plugin has an option to download all emails in a folder. This has some limitations, better is to just use a desktop email client or imap-sync tool.

**Comment by thomascube** [comment]
> I looked through the releases list & changelog here on github to 1.3 as well as the plugin list linked from the site...

Roundcube also includes a set of default plugins which are not listed on packagist:
https://github.com/roundcube/roundcubemail/wiki/Plugins#default-plugins

Here you can find the `zipdownload` plugin which enables the requested functions and which is also included in the docs you referred to.
