### ISSUE TITLE
Image viewer: you can't see the top of zoomed images

### ISSUE THREAD

**Issue by jgmy** [roundcube/roundcubemail#7669]
Hi!
I receive many, many student tasks in pdf or jpg format. I have to use the zoom feature of the image viewer. But, when you zoom, the top part of images (I'm speaking about 9:16 images produced by mobile phones) is cut. You can not see them by scrolling up.

Roundcube 1.4.7

Tested on chrome 86 and (chromium) edge.

![2020-10-11](https://user-images.githubusercontent.com/2573642/95673984-7c719b80-0bad-11eb-9556-b9fdfb0bdd5a.png)

**Comment by alecpl** [comment]
I see the scrollbar, you mean despite it's existence the scrolling does not work? Works for me in Chromium 85.

**Comment by jgmy** [comment]
I can scroll down but I can't scroll up. Scroll bar is at top position, as
seen in the picture.

**Comment by jgmy** [comment]
Its not critical sice you can right-click the image and open it in the browser as new tab. Just wanted you to know/verify.

**Comment by alecpl** [comment]
I get it now, but I'm still unable to reproduce with Chromium 85 and Roundcube git-master. When I have 86 I'll test again using Roundcube 1.4.

**Comment by alecpl** [comment]
I'm unable to reproduce on Chromium 86 and most recent Roundcube version.

**Comment by jgmy** [comment]
Thanks for your efforts, Alexandr. I guess the admin of the site I'm using
has some misconfiguration.
I will contact it.
