### ISSUE TITLE
Inbound email components shift when I forward or reply...

### ISSUE THREAD

**Issue by Charapita58** [roundcube/roundcubemail#7670]
When I receive a marketing flyer with images and text looks nice......however when I forward  the exact same flyer there is one particular text (2  words)  it shift to another spot in the page.....it moves down like 3 spaces to the middle of the page......
the original one is placed to the right side of the page......
      it is a total mystery how this can happen.....nobody can figure it out....
any help  much appreciated...

**Comment by alecpl** [comment]
We'll have to see the original message source.

**Comment by alecpl** [comment]
No feedback.
