### ISSUE TITLE
not fully showing attachment in 1.5-git

### ISSUE THREAD

**Issue by oleg-indeez** [roundcube/roundcubemail#7671]
Hello!
I've both 1.5-git & latest stable (1.4.9) on my apache (w/ different mysql bases), and used 1.5-git version for a long time but recently had to switch to 1.4.9 due to this bug. If I compose a mail and attach a file (probably it concerns only text ones, not html) sometimes 1.5-git shows just few lines at top while 1.4.9 - all the text, as I expect and used to.

Here are the screenshots from both versions:
![1 5-git about](https://user-images.githubusercontent.com/61268538/95844572-bc718380-0d51-11eb-9490-56da461d3107.png)
![1 5-git wrong](https://user-images.githubusercontent.com/61268538/95844574-bd0a1a00-0d51-11eb-8b9c-ee80a88e05af.png)
![1 4 9 about](https://user-images.githubusercontent.com/61268538/95844579-bda2b080-0d51-11eb-942e-83020e2d3cf9.png)
![1 4 9 correct](https://user-images.githubusercontent.com/61268538/95844584-be3b4700-0d51-11eb-89dc-5bfb97b5b925.png)

Mail source in both versions is correct, and it attaches the whole file - the problem is just in showing its part by 1.5-git
Possibly it stops showing after first double \n char, here is the mail source:
[draft email source.txt](https://github.com/roundcube/roundcubemail/files/5370479/draft.email.source.txt)

Thank you in advance for you time and efforts,
WBR,
Oleg

**Comment by alecpl** [comment]
Does it work with disabled all plugins?If not, attach the message source.

**Comment by oleg-indeez** [comment]
I've tried w/ default plugins 
![only std plugs](https://user-images.githubusercontent.com/61268538/95966935-5a2d8700-0e14-11eb-9ac6-4f7635d4a78d.png)
and even with empty $config['plugins'] array
![no plugs in config](https://user-images.githubusercontent.com/61268538/95967037-78938280-0e14-11eb-8573-d1dc6f5a4a3f.png)

no, just few lines at the top @1.5-git
![not showing more than several top lines](https://user-images.githubusercontent.com/61268538/95967112-8e08ac80-0e14-11eb-9808-788386041c4c.png)

email source that is displaied partly I've already posted at the very end of the issue, and now I post just the same source once more 
[email-source.txt](https://github.com/roundcube/roundcubemail/files/5376937/email-source.txt)

Thank you!

**Comment by alecpl** [comment]
Fixed.

**Comment by oleg-indeez** [comment]
Confirm. Thank you!
