### ISSUE TITLE
Allow to move recipients between To/CC/BCC fields

### ISSUE THREAD

**Issue by dboehmer** [roundcube/roundcubemail#7672]
Since some time ago any e-mail address entered into a recipient field is transformed from plain text into an atomic grey box. This is nice while entering addresses but hard if you need to correct things.

I’d love to see any or multiple of the following to improve this:

* enable a drag & drop action to move recipients between the input fields for To/CC/BCC
* allow to select some or all recipients in a field and copy the addresses to clipboard
* allow to move text cursor between addresses in order to delete particular recipients with [backspace]

**Comment by alecpl** [comment]
> Since some time ago any e-mail address entered into a recipient field is transformed from plain text into an atomic grey box. This is nice while entering addresses but hard if you need to correct things.
> 
> I’d love to see any or multiple of the following to improve this:
> 
>     * enable a drag & drop action to move recipients between the input fields for To/CC/BCC

Implemented in git-master

>     * allow to select some or all recipients in a field and copy the addresses to clipboard

You can select. There were some fixes to this, so maybe use most recent version.

>     * allow to move text cursor between addresses in order to delete particular recipients with [backspace]

There's delete button, so I don't see a point. You can still delete with backspace if you place the cursor at the end.
