### ISSUE TITLE
Can't delete example Contacts and Contact Groups

### ISSUE THREAD

**Issue by pthoelken** [roundcube/roundcubemail#7676]
Hey Roundcube Team, 

I can't delete the Example Contact Group and Example Contacts? Why? I doesn't need it. I can't see this entires in the database either.

![image](https://user-images.githubusercontent.com/12643853/95959053-4711bb80-0e02-11eb-9d04-c520c0842204.png)

**Comment by alecpl** [comment]
Disable example_addressbook plugin.
