### ISSUE TITLE
Sort sub folders

### ISSUE THREAD

**Issue by tombrox** [roundcube/roundcubemail#7677]
Hi,

I am a user of the webmail and have encountered the issue that I am not able to sort the order of sub folders (Alphabetically).

Br, Tom Brox

**Comment by alecpl** [comment]
What version? What OS/PHP version? What plugins enabled? What IMAP server? What is the issue precissely? What is in imap_debug log? If you can't answer these questions we'll not be able to help you.

**Comment by tombrox** [comment]
Ok. Sorry cant do that. I will use it as it is. Sorry for inconvenience.

br tom

Aleksander Machniak skrev den 14-10-2020 13:22:

> What version? What OS/PHP version? What plugins enabled? What IMAP server? What is the issue precissely? What is in imap_debug log? If you can't answer these questions we'll not be able to help you. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
 

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/7677#issuecomment-708338398
[2]
