### ISSUE TITLE
annoying folder jumping

### ISSUE THREAD

**Issue by mkrumbholz** [roundcube/roundcubemail#7678]
If i switch from an email to another folder, the folder selection is jumping back to the folder, where i was when i opened the email.

Used version: 1.4.9
Design: Larry
Layout: list (no mail preview)

![FolderJumping](https://user-images.githubusercontent.com/31690023/95991321-ec418980-0e2c-11eb-9c6d-52f27bcd5e39.gif)

**Comment by johndoh** [comment]
I cannot recreate this. When it jumps back it looks like it also selects the message which, imo, is strange. Was this tested with all plugins disabled?

**Comment by mkrumbholz** [comment]
Thanks for the reponse and you where right i forgot to disable one plugin.
And it was it 😅.
