### ISSUE TITLE
HELP CANT CONFIGURE ROUNDCUBE INSTALLER. 

### ISSUE THREAD

**Issue by lordsilver28** [roundcube/roundcubemail#7682]
Hi,

To enable it again, set $config['enable_installer'] = true; in RCUBE_CONFIG_DIR/config.inc.php

When i enabling $config['enable_installer'] = true the page installer was not accesible.

XAMPP Version 3.2.4
PHP7

Please help me.

**Comment by alecpl** [comment]
What version? What OS? Is this a custom install or from some packaging?

You should ask on mailing list or forum.
