### ISSUE TITLE
Cannot undelete message

### ISSUE THREAD

**Issue by duck-rh** [roundcube/roundcubemail#7683]
Quack,

I'm using version 1.4.8 with the Elastic skin. I inadvertently deleted the wrong mail and looked for any way to undelete it before the expunge sequence and could not find it. I found the old  #1635 ticket and tried to reclick on delete to no avail. I'm not using the trash I think and it was not there but still visible in my folder view. I tried accessing the mail to undelete it via another mail client but could not find it. So I did what the last person to comment suggested to save the situation and forwarded the mail to myself, which resulted in a mail without anything attached, and now the mail vanished from my view.

It goes without saying this is really irritating. Could you restore the undelete function please?

Regards.
\_o<

**Comment by johndoh** [comment]
Its working fine for me in git-master. When a message is marked as deleted but not yet expunged then in the message list you should see it greyed out with an icon of a circle with a line through it just before the subject:

![Untitled](https://user-images.githubusercontent.com/88682/96364902-f1584e80-1134-11eb-9c9e-eb572a65b513.png)

if you click that icon it will remove the deleted flag from the message. is that not working for you?

**Comment by duck-rh** [comment]
Well, it does work well indeed. I just had no idea you could click here. I'm used to click on the action bar (reply, reply all, forward, delete…) to do these kind of actions. Thanks for the directions.

Then maybe the action bar could be updated to reflect this possibility.

**Comment by alecpl** [comment]
There's #5133 already for this.

**Comment by duck-rh** [comment]
ok, thanks
