### ISSUE TITLE
Roundcube: Can sent mail, but cannot receive

### ISSUE THREAD

**Issue by thisyuvxx** [roundcube/roundcubemail#7685]
here is my mail.log, someone told me that the trouble is in my port. But i sure everything seems fine
![Port](https://user-images.githubusercontent.com/53385266/96366076-d6f39480-1177-11eb-9a12-5694d790866f.PNG)
![mail log](https://user-images.githubusercontent.com/53385266/96366064-cba06900-1177-11eb-8067-9198d361d4c4.PNG)

**Comment by alecpl** [comment]
Roundcube is an imap client, it does not "receive mail".
