### ISSUE TITLE
Cannot enable dark mode in the Elastic skin with Roundcube 1.4.9

### ISSUE THREAD

**Issue by DalekDave** [roundcube/roundcubemail#7687]
I cannot enable dark mode in the Elastic skin with Roundcube 1.4.9. I have enabled dark_mode_support in meta.json and set @dark-mode-enabled to true in variables.less but still the toggle icon does not show up... It was working fine in 1.4.7.

This is my meta-json: https://t25b.com/?528946085690a6ce#5D1mtStKpHJkt3mGnPAiVo4dn4oBtPG7pb644weDHQBV

And this is my variables.less: https://t25b.com/?b737398a746207a2#A5ScnPoG6fv6sSb1yMtidH3N1TTtWzLNfrKxsUfSc9Fi

PHP: 7.3 FPM

OS:   Ubuntu 18.04.5

Mail server: Postfix/Dovecot

Browser: Firefox/Chrome latest on Kubuntu 20.04 

Plugins: $config['plugins'] = array('archive', 'attachment_reminder', 'autologon', 'debug_logger', 'enigma', 'hide_blockquote', 'identity_select', 'jqueryui', 'managesieve', 'markasjunk', 'newmail_notifier', 'password', 'sauserprefs', 'show_additional_headers', 'subscriptions_option', 'userinfo', 'vcard_attachments', 'virtuser_file', 'virtuser_query', 'zipdownload');

**Comment by alecpl** [comment]
There's no dark mode in 1.4.

**Comment by DalekDave** [comment]
But the dark mode in 1.4.7 was a REALLY GREAT FEATURE! Please could I ask you to explain the reason WHY you dropped the dark mode support? Thank you if so.

**Comment by alecpl** [comment]
There was no dark mode in 1.4. I don't know what are you talking about.

**Comment by DalekDave** [comment]
Yes, my mistake. Dark mode is only available if you check out the git master... Really cool feature, the dark mode. Thanks for your work on Roundcube, guys. :-)
