### ISSUE TITLE
correction to Russian localization

### ISSUE THREAD

**Issue by oleg-indeez** [roundcube/roundcubemail#7693]
Hello!
Due to the fact that the verb in Russian has different forms according to the subject gender and simultaneously we can not reliably determine gender of the writer I propose the following patch.

[ru_localization.patch.txt](https://github.com/roundcube/roundcubemail/files/5428129/ru_localization.patch.txt)

**Comment by alecpl** [comment]
This needs to be done via https://www.transifex.com/roundcube/roundcube-webmail/
