### ISSUE TITLE
Using sa-learn on another machine

### ISSUE THREAD

**Issue by oculos** [roundcube/roundcubemail#7694]
Hi,

I run Roundcube on a separate docker container than the one I run dovecot/span assassin in. 
I see that using the cmd_ driver passes a ‘%f’ path that is related to Roundcube’s storage. 

I keep thinking on how I could use the cmd_driver to execute sa-learn at the mail container, which is doable, but how could I pass a path that reflects the message on dovecot’s machine?

Best,
Francis

**Comment by tomsommer** [comment]
Send the local file to another server for processing

**Comment by johndoh** [comment]
I think this might be a more appropriate discussion for the mailing list or forum as it seems more of a support request than a bug.

I guess your options are using a driver which does not require local files or use some [shared storage](https://docs.docker.com/storage/volumes/#share-data-among-machines) in your containers.
