### ISSUE TITLE
Cannot reply a message when it's older than a day

### ISSUE THREAD

**Issue by asierrl** [roundcube/roundcubemail#7696]
When I reply a message than I read in previous days, Roundcube would hang out at "sending message". It happens with three different mail accounts (in the same server and domain) and three different computers (with Ubuntu 16.04 and windows 10). 
It doesn't happen when the replied message is fresh, when I read a message and reply it in the same day, everything goes smoothly.

**Comment by alecpl** [comment]
It does not sound like Roundcube bug. Definitely Roundcube is not taking the message age into account in any way. I'd suspect something on the IMAP server side. You can enable imap_debug in Roundcube to get some logs.

**Comment by asierrl** [comment]
I will try that, but the issue does not appear in my mobile phone with
BlueMail.
It's true that it does not happen always, sometimes it works but most
commonly it would fail to reply to old messages. Sometimes also replying to
new messages may fail, but this is much rarer... I have not been able to
guess any other reason why it fails only sometimes.
Best regards,
Asier

**Comment by asierrl** [comment]
Thanks a lot for your help, Aleksander. May I ask you how can I enable
imap_debur in Roundcube. I have not found a way to do it. Googling it I
find that I should edit config.inp.php in my roundcube installation...but I
have not installed roundcube, I only used it for webmail... Do I need to
find it in my server?
Best regards,
Asier
