### ISSUE TITLE
Login inside Iframe from another domain

### ISSUE THREAD

**Issue by MetallianFR68** [roundcube/roundcubemail#7697]
Don't ask why, I have a very specific reason to do so.

I need to display the roundcube window hosted on www.domain1.com inside an iframe from www.domain2.com

If the iframe is from www.domain1.com, I can get it to work. I just had to change $config['x_frame_options']
But as soon as I launch it from another domain, I can't login anymore.
I see the login window and I can enter my login and password.
But I get an error 401 all the time.

Is there a way to achieve what I want ?

![image](https://user-images.githubusercontent.com/6049266/97309023-d3d86280-1861-11eb-8825-259077aa1fd7.png)

**Comment by MetallianFR68** [comment]
Ok I just realized the problem comes from the cookies.
It works if I set their "samesite" attribute to "None"
Is this implemented somewhere in roundcube ?
I think not
It seems that the setcookie function in program/lib/Roundcube/rcube_utils.php should be updated with a possibility to set this in the config.inc.php

**Comment by MetallianFR68** [comment]
I made it work finally 👍 

 program/lib/Roundcube/rcube_utils.php
 
Find this line : 
setcookie($name, $value, $exp, $cookie['path'], $cookie['domain'], $secure, $http_only);

Replace With ;
 setcookie($name, $value, array('expires' => $exp, 'path' => $cookie['path'], 'domain' => $cookie['domain'], 'secure' => $secure, 'httponly' => $http_only, 'samesite' => 'None'));


/srv/webmail/program/lib/Roundcube/rcube.php
Find this line : ini_set('session.cookie_httponly', 1);
And add just after : ini_set('session.cookie_samesite', 'None');


This only works ini PHP >= 7.3

Can someone explain the security risk about this change ?

**Comment by johndoh** [comment]
support for the samesite attribute has been added in #6772

**Comment by AriBerisha** [comment]
Worked Flawlessly! Thank you so much @MetallianFR68 <3
