### ISSUE TITLE
Vulnerabilities on Roundcube 1.4

### ISSUE THREAD

**Issue by glraj70** [roundcube/roundcubemail#7698]
Hello,

We are using Roundcube 1.4 v in our organization.

Recently Vulnerability Assessment and Penetration Testing was carried out on roundcube application.

Few vulnerabilities were detected on the roundcube application.

The detailed VAPT report of the roundcube application is attached in the mail.

Requested to release the bug fixes for these vulnerabilities
-- 
Regards,
Rajesh G L

**Comment by alecpl** [comment]
I don't have time to process this now, but in a quick look the report looks quite useless. It describes some general rules mostly about session security and tokens, but does not describe real issues.

**Comment by johndoh** [comment]
@glraj70 publishing vulnerability reports in a public forum without first giving devs an opportunity to address those vulnerabilities is not very friendly, you risk handing information to bad actors putting your own installation and others at greater risk. Also as a general rule its best to limit tickets to single issues this makes for easier tracking and management.

In this case the report does not contain much in the way of any actual problems though. It lists 3 potential issues:

1. Session Hijacking - mitigations already exist for this, see #7576
2. Session token in URL - this is part of the CSRF and only used in situations where POST is not practical. IMO this is low risk but mitigations also already exist for this, look at the `use_secure_urls` config option
3. Parameter Tampering - I do not understand what issue is being described here

**Comment by glraj70** [comment]
Hi Johndoh,
Thanks for the reply .
Apologies for posting in public forum. I future i will post as single issues.
I will close this case.
Kindly delete the post from the forum.
