### ISSUE TITLE
Irony for roundcube

### ISSUE THREAD

**Issue by SLAY3RYTB** [roundcube/roundcubemail#7701]
Hi, 5 days to install Irony to get working calendar and others plugins on Roundcube but its impossible, im have testing all possibility im don't understand how to work ... please create and news update version in list of download named RoundCube 1.4.9 with Irony to use all plugins (Kobal and Chwala).

PLEASE create an a Irony roundcube version to help me, im need that for my work.

Thanks for your help.

Cordialy,
SLAY3R

**Comment by alecpl** [comment]
We do not support Kolab here.
