### ISSUE TITLE
Downloading attachments

### ISSUE THREAD

**Issue by lcdtm** [roundcube/roundcubemail#7702]
Roundcube v. 1.4.9

Whenever I download an attachment from an email the files are always a few bytes short.

I have version 1.2.5 installed on the same server and that works fine.

hexdump eksampel:

Last line from PDF downloaded with 1.4.9:

/Size 104./Root 87 0 R./I

Last line from PDF downloaded with 1.2.5 or thunderbird:

*Size 104./Root 7 0 R./Info 1 0 R>>.startxref.87763.%%EOF

jpeg, png and ods files have the same problem. I haven't tried any other file types.
The files varies in size from 1MB to a 34KB.

Server: 20.04
PHP 7.4
Apache2 SSL

Anything I can do?

Thx

Tommy

**Comment by alecpl** [comment]
Could you enable imap_debug and verify the attachment content in IMAP responses is correct?

**Comment by lcdtm** [comment]
Attached is the imap log from downloading the attachment I wrote about in the original post.

Both version 1.4.9 and 1.2.5

They are very diffent.

Can you conclude anything from them?

Thx.

Tommy
[1.2.5_imap.log](https://github.com/roundcube/roundcubemail/files/5473864/1.2.5_imap.log)
[1.4.9_imap.log](https://github.com/roundcube/roundcubemail/files/5473865/1.4.9_imap.log)

**Comment by alecpl** [comment]
Hard to say, but you could try if `$config['imap_disabled_caps'] = array('BINARY');` would fix the issue.

**Comment by alecpl** [comment]
Actually you can see that the pdf content is not complete in the IMAP response:
```
[02-Nov-2020 10:14:37 +0100]: <9bp2p0da> [4C7C] S: <</Size 104
[02-Nov-2020 10:14:37 +0100]: <9bp2p0da> [4C7C] S: /Root 87 0 R
[02-Nov-2020 10:14:37 +0100]: <9bp2p0da> [4C7C] S: /I UID 301702)
```
So, it is the imap server bug. The config option I mentioned should fix the issue.

**Comment by lcdtm** [comment]
That did it.

Thank you very much :)

Can I ask, what is the "imap server bug"?

Tommy

**Comment by alecpl** [comment]
Looks like your IMAP server software returns invalid/truncated binary content when BINARY extension is used.
