### ISSUE TITLE
Feature Request: Adding identities with validation

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#7704]
Hi Alec,

I'd like to ask, if it's possible to add in a very near future, a validation when adding new identities.
Why this request?
I've seen users where their password has discovered, the hackers/spammers create random identities to send emails using the user's webmail system (with domains that don't have SPF for sure, i already deleted them can't confirm that now).

A validation like gmail and other services does, sending a code to the new identity email for validation.

**Comment by alecpl** [comment]
Sounds like something for a plugin.

**Comment by dddns** [comment]
Alec,

Ok seems more correct to be a plugin.
I'd love to help but i dont do PHP.

Hope the idea helps to improve RC.
