### ISSUE TITLE
1) filter only unread messages, 2) un-filter -> shows empty message list

### ISSUE THREAD

**Issue by oleg-indeez** [roundcube/roundcubemail#7705]
Hello!
If I press black mail envelope to see only unread messages it works quite as expected, but it I press that black envelope once more - to un-filter - it shows me empty message list. Fortunately it doesn't delete any message and If I select corresponding folder it shows me both read and unread messages.
Roundcube Webmail 1.5-git [GIT 20201101.1326]

**Comment by alecpl** [comment]
Confirmed. There's been a heavy code refactoring recently, so there might be some more regressions. Thanks for reporting.

**Comment by oleg-indeez** [comment]
thank you!

**Comment by alecpl** [comment]
Fixed.

**Comment by oleg-indeez** [comment]
Thank you! Fixed with a lightning speed!
