### ISSUE TITLE
Print from Roundcube (problme in PDF preview )

### ISSUE THREAD

**Issue by yuriizsk89** [roundcube/roundcubemail#7706]
Hello, i try to print some of my email and I get blank on the first page in PDF -reader (print preview ) in Google Chrome and in Opera. On firefox all ok but firefox has another PDF viewer. This only happens when I print from the roundcube.

Screen below: 

1. Empty blank : 
![Roundcube_Blank_empty](https://user-images.githubusercontent.com/73827585/97874919-62e1f080-1d22-11eb-83b1-60b6b5f50196.png)

2. Second page with content: 

![image](https://user-images.githubusercontent.com/73827585/97875440-0e8b4080-1d23-11eb-8a6d-8d13cc1cdcf7.png)

How to replicate:

Open email -> Print. 

These are not all letters, but a good part is still in the preview with an empty form.

Whether the content of the letter can influence how it will be displayed in the PDF viewer?

Also when i print this mail from MUA (Mail client) as Thunderbird/Outlook .. etc. all ok in prewiev. 

Thanks.

**Comment by yuriizsk89** [comment]
Tested on roundcube version 1.3.3 - 1.3.8

**Comment by alecpl** [comment]
This sounds like a bug we fixed in 1.4.9 (#7604). Roundcube 1.3 is out of support.
