### ISSUE TITLE
Elastic Skin: Option to always show folders

### ISSUE THREAD

**Issue by necrevistonnezr** [roundcube/roundcubemail#7711]
Is it possible to add an option to always show folders with the Elastic Skin? 

I heavily use folders to organize and sieve mail and since my two sceens are swiveled by 90 degrees (so that I can see a document page in full size) the horizontal resolution is only 1080 pixels - which results in the folders always being hidden (see screenshot)

![Screenshot 2020-11-05 151130](https://user-images.githubusercontent.com/8191935/98251675-4986b180-1f79-11eb-8dd7-981d37480244.png)

**Comment by alecpl** [comment]
So, I guess you would want the old two column layout where the messages list on top of the preview frame. It's not gonna happen. But there a plugin in works for Roundcube 1.5: https://github.com/johndoh/roundcube-elasticlayouts
