### ISSUE TITLE
Bug Search type flagged

### ISSUE THREAD

**Issue by carloshilgemberg** [roundcube/roundcubemail#7712]
I have a problem searching for flagged emails

In the search of the flagged type in the current folder, it correctly shows only the emails that have been flagged, but when changing all folders to the scope, it shows emails that have not been flagged.

I'm using roundcube 1.4.9

I haven't run tests on other versions yet, anyone else with this problem?

**Comment by alecpl** [comment]
I'm unable to reproduce. Enable imap_debug and provide the log. Disable all plugins.

**Comment by carloshilgemberg** [comment]
Hi, I managed to find out why.

Problem was related to a third party plugin called "Filters"

I disabled this plugin specifically and the problem did not occur again.
