### ISSUE TITLE
Hangs when add signature

### ISSUE THREAD

**Issue by bitpt** [roundcube/roundcubemail#7715]
Ver 1.4.9
Centos 7
Mysql

Hangs when add signature manual(on top button) or auto(settings->compose msgs->auto).
Can't close or do nothing, need close window to logout. 
Can someone help with this issue.

Thanks !!!!
PS: Nothing in logs. All browsers with or whitout HTTPS

**Comment by johndoh** [comment]
Sounds like a JavaScript error, have you checked your browser's console?

**Comment by bitpt** [comment]
no error in console... let me recheck...
No error...

**Comment by johndoh** [comment]
have you tested with all roundcube plugins disabled?

I think you'll have to do some digging in the `change_identity` function in `app.js`

**Comment by alecpl** [comment]
I don't understand the issue. We'll need more details, a screenshot? What browser? Did you try with different browser?

**Comment by alecpl** [comment]
No feedback.

**Comment by bitpt** [comment]
Sorry!!!! forgot reply.
Nothing solve issues, in some accounts, backup emails, delete account and open same account and restore backup solve signature problem, however more problems detected.
Sometimes hang when send, imap login failures when connect.
Failure in identities, in migration process mix diferent accounts identities and contacts.
New installation solve issue.
