### ISSUE TITLE
correct and working database migration from version 1.1.3 to version 1.4.9

### ISSUE THREAD

**Issue by graceastrid** [roundcube/roundcubemail#7719]
what I have:
- Centos 7.8
- PostgreSQL 10
- php73
- nginx (reverse proxy)
- apache2.4 (+ httpd-mpm)
- RC 1.1.3 & 1.4.9
____

have a nice day! 

I have an old version of the cube 1.1.3 and
she is currently in production. I cannot update this version for administrative reasons. 
I deployed the new version 1.4.9 on another server and configured it. 

now i have a problem: how do i migrate a database from old version 1.1.3 to newer version 1.4.9?

I'm interested in the migration of custom settings and signatures that users use when sending letters.
signatures are stored in the identities table. so, where the settings are stored, I cannot understand.

there are hundreds of users with unique user_id in the old version - how can I correctly transfer all this to the new version of the database and the cube without breaking the connection, so that when the user logs in, his settings and signatures are in place?

thank you for help

**Comment by alecpl** [comment]
Copy the database from the 1.1.3 instance and then run the update script.

**Comment by graceastrid** [comment]
> Copy the database from the 1.1.3 instance and then run the update script.

thanks for your reply! do you mean ./bin/updatedb.sh? with what key will it need to be launched in my situation?

**Comment by graceastrid** [comment]
> Copy the database from the 1.1.3 instance and then run the update script.

I copied the old database to the new version of the cube.
used roundcube.domain.ru/installer to update the copied database. schemas were updated. but after that, the signatures of users still did not pull up (
