### ISSUE TITLE
How to modify the checkbox style of the mailing list, I cannot find the modification

### ISSUE THREAD

**Issue by lieliedurgan** [roundcube/roundcubemail#7720]
How to modify the checkbox style of the mailing list, I cannot find the modification

As shown：
![image](https://user-images.githubusercontent.com/72588763/98661849-f69a6900-2381-11eb-85ae-f592dc2a207c.png)

**Comment by alecpl** [comment]
Ask on mailing list or forum.

**Comment by lieliedurgan** [comment]
> 在邮件列表或论坛上询问。

What is the forum address?
