### ISSUE TITLE
database migration from 1.1.3 to version 1.4.9

### ISSUE THREAD

**Issue by graceastrid** [roundcube/roundcubemail#7721]
I already sent the issues [here](https://github.com/roundcube/roundcubemail/issues/7719), but for some reason it was closed. 

what I have:
- Centos 7.8
- PostgreSQL 10
- php73
- nginx (reverse proxy)
- apache2.4 (+ httpd-mpm)
- RC 1.1.3 & 1.4.9
____

I have an old version of the roundcube 1.1.3 and is currently in production. I cannot update this version for administrative reasons. 
I deployed the new version 1.4.9 on another server and configured it. 

now i have a problem: how do i migrate a database from old version 1.1.3 to newer version 1.4.9?

I'm interested in the migration of custom settings and signatures that users use when sending letters.
signatures are stored in the identities table.

there are hundreds of users with unique user_id in the old version - how can I correctly transfer all this to the new version of the database and the roundcube without breaking the connection, so that when the user logs in, his settings and signatures are in place?

I copied the old database to the new version of the roundcube.
used roundcube.domain.ru/installer to update the copied database. schemas were updated. but after that, the signatures of users still did not pull up.

what can I do for correctly restore old data base in new roundcube?

**Comment by alecpl** [comment]
This is not a support forum.

**Comment by graceastrid** [comment]
> This is not a support forum.

I didn’t know about it, I’m sorry
