### ISSUE TITLE
Password: Support for ARGON2 family of hashes

### ISSUE THREAD

**Issue by fluteze** [roundcube/roundcubemail#7724]
Please consider adding this feature to the password changing plugin:
```
--- password.php.orig	2020-11-14 12:26:00.748848486 -0700
+++ password.php	2020-11-14 12:24:07.090332419 -0700
@@ -535,6 +535,16 @@
         }
 
         switch ($method) {
+        case 'argon2i':
+            $crypted = password_hash($password, PASSWORD_ARGON2I);
+            $prefix  = '{ARGON2I}';
+            break;
+
+        case 'argon2id':
+            $crypted = password_hash($password, PASSWORD_ARGON2ID);
+            $prefix  = '{ARGON2ID}';
+            break;
+
```

and the configuration file comment section:
```
--- password.inc.php.orig	2020-11-14 12:48:59.621988887 -0700
+++ password.inc.php	2020-11-14 12:49:44.521798416 -0700
@@ -43,7 +43,7 @@
 $config['password_force_new_user'] = true;
 
 // Default password hashing/crypting algorithm.
-// Possible options: des-crypt, ext-des-crypt, md5-crypt, blowfish-crypt,
+// Possible options: argon2i, argon2id, des-crypt, ext-des-crypt, md5-crypt, blowfish-crypt,
 // sha256-crypt, sha512-crypt, md5, sha, smd5, ssha, ssha512, samba, ad, dovecot, clear.
 // For details see password::hash_password() method.
 $config['password_algorithm'] = 'argon2id';
```
This in use in my installation, though someone might like it.

Not sure why the first patch above looks funny and the second is ok.

**Comment by johndoh** [comment]
Its better to submit PRs than try and past patches into tickets.

Also it should probably be in the config notes and may be even checked in the code that PASSWORD_ARGON2I requires PHP >= 7.2 and PASSWORD_ARGON2ID >= 7.3 since Roundcube supports >=5.5.

**Comment by fluteze** [comment]
I like the idea of flexibility. Yes, there does need to be some checking done for PHP versions. I'll work on a patch and submit the relevant PR.

**Comment by robo2bobo** [comment]
Please be aware, that RHEL and CentOS (R.I.P) do not support argon under PHP at all, even in PHP 7.x that comes with RHEL 8 and CentOS 8.

I am not sure why redhat has decided to remove argon completely, several bug/feature reports exist in their bugzilla requesting argon to be included but redhat engineers reply that redhat has no plans to support argon. A legal reason? a security issue? ...

**Comment by cybernet** [comment]
> Please be aware, that RHEL and CentOS (R.I.P) do not support argon under PHP at all, even in PHP 7.x that comes with RHEL 8 and CentOS 8.
> 
> I am not sure why redhat has decided to remove argon completely, several bug/feature reports exist in their bugzilla requesting argon to be included but redhat engineers reply that redhat has no plans to support argon. A legal reason? a security issue? ...

php 7.4 in EPEL does support it

**Comment by alecpl** [comment]
Implemented.
