### ISSUE TITLE
Search CARDDAV contact - only contact from first page  

### ISSUE THREAD

**Issue by mochour** [roundcube/roundcubemail#7726]
Hi,

I synchronize my contacts via carddav plugin. When I try to search a contact (Contact -> middle column search) the contact is not found unless it is displayed at the first page. I'm using MySQL as backend.

Thanks
Jan

PHP 7.4.3
carddav plugin 4.0.2
No error in the logs

**Comment by alecpl** [comment]
We do not support external plugins here.
