### ISSUE TITLE
Messaging signing (no encryption) using Mailvelope

### ISSUE THREAD

**Issue by JoelLinn** [roundcube/roundcubemail#7729]
Hi,

is there any technical reason why it is not possible to just sign a message with the Mailvelope plugin or is it just unimplemented?

**Comment by alecpl** [comment]
As I know there's no such possibility in Mailvelope API. Let us know if you find a way.

**Comment by Velociraptor85** [comment]
Is this still valid? Since according to https://mailvelope.com/en/help#first_mail the SignOnly button should be available in the Mailvelope editor.

**Comment by alecpl** [comment]
https://github.com/mailvelope/mailvelope/issues/769
