### ISSUE TITLE
Elastic: Preview of message does not wrap white spaces

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7732]
Hi,

I stumbled upon the following: If you are on a mobile device and double-tab on an email rather than single-tap on it, a "preview of the message" does open which does not wrap white spaces.

"normal" mail view (single-tap):

![image](https://user-images.githubusercontent.com/11192306/99799068-5b985080-2b32-11eb-8115-11deb5375ee1.png)

"preview of the message" view (double-tab):

![image](https://user-images.githubusercontent.com/11192306/99799192-926e6680-2b32-11eb-9200-4703573cf6f4.png)

The scrollbar is missing and the title is way beyond the viewport.
The screenshots are from the "responsive mode" in Chrome DevTools on Windows.

**Comment by codegain** [comment]
I could temporily fix it by adding `max-width: 100%;` to `#layout-content`

**Comment by alecpl** [comment]
There are some other options. https://stackoverflow.com/questions/10614481/disable-double-tap-zoom-option-in-browser-on-touch-devices

**Comment by codegain** [comment]
@alecpl This also affects desktop browsers (Chrome in my case) by double-clicking on the email. Adding `max-width: 100%` to `#layout-content` shows a scrollbar. Without that, the email and the menu get cut off by the browser window:

![image](https://user-images.githubusercontent.com/11192306/100740103-70999d00-33d8-11eb-843b-ee26afee34e7.png)

**Comment by alecpl** [comment]
Opening a mail in a new window should be not possible in the mobile/tablet mode. So, I just disabled double-click handler there. Fixed.
