### ISSUE TITLE
cli install db

### ISSUE THREAD

**Issue by doekia** [roundcube/roundcubemail#7734]
For some obscure reason package install fail to create user/database on Debian 10.
Trying to address the issue on an automated script I feel the initdb.sh could be the way to solve the issue.

Unfortunately I cannot find any documentation on how to use it.

Could this be documented somewhere.

PS: I have multiple installation to fix and definitively cannot afford to use the web based install for such purpose. I need a cli approach

**Comment by eilandert** [comment]
Hi, not sure but can you try to create a config.inc.php with
<?php
$config = array();
$config['db_dsnw'] = 'mysql://user:password@host:3306/database';
$config['db_dsnr'] = '';
<everything else you need>

cd into the roundcube directory

# initialize or update DB (taken from the Dockerfile)
bin/initdb.sh --dir=$PWD/SQL --create || bin/updatedb.sh --dir=$PWD/SQL --package=roundcube || echo "Failed to initialize database. Please run $PWD/bin/initdb.sh and $PWD/bin/updatedb.sh manually."
