### ISSUE TITLE
question about getting elastic skin to work

### ISSUE THREAD

**Issue by eilandert** [roundcube/roundcubemail#7740]
Hello!

When I am pulling from git, regardless of version, I can't get the elastic skin to work.

Basicly I do something like this: (and lots of variations of it, including all .less files and min.css)

apt-get -y install npm
npm install lessc
npm install less-plugin-clean-css
cd /var/www/html/skins/elastic
npm lessc --clean-css="--s1 --advanced" styles/styles.less > styles/styles.css
npm lessc --clean-css="--s1 --advanced" styles/print.less > styles/print.css
npm lessc --clean-css="--s1 --advanced" styles/embed.less > styles/embed.css
npm lessc --clean-css="--s1 --advanced" styles/styles.less > styles/styles.min.css
npm lessc --clean-css="--s1 --advanced" styles/print.less > styles/print.min.css
npm lessc --clean-css="--s1 --advanced" styles/embed.less > styles/embed.min.css
cd /var/www/html/
bin/updatecss.sh --dir skins/elastic

But no luck. Is there something I am missing?

**Comment by alecpl** [comment]
What is not working?

**Comment by thomascube** [comment]
Another reason for #6284 ;-)

**Comment by eilandert** [comment]
> What is not working?

Hi alecpl,

The layout is all scrambled up, I'm sure I am not doing it right but can't find out why. I reverted to the complete.tar.gz and there it works fine, but I would like to eventually know what I am doing wrong.

**Comment by alecpl** [comment]
I just noticed that your commands are wrong. It should be `lessc ....` not `npm lessc ...`

**Comment by UnlegitApple** [comment]
@eilandert Is this error occuring only in mobile view? The elastic skin is not working for me in mobile view, it is all scrambled up as you said. The desktop view is beautiful though.
