### ISSUE TITLE
Improvement, Add source IP to error log of wrong auth

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#7741]
Hi Alec,

Would it be possible to add in the logs, the source IP when someone misses the auth?
Thanks,

Nov 24 09:08:48 webservices roundcube: <q5mifcs4> PHP Error: Invalid response code received from server (POST /webmail/?_task=mail&_unlock=loading1606208926100&_framed=1&_lang=pt_PT&_action=send)
Nov 24 09:08:48 webservices roundcube: <q5mifcs4> SMTP Error: Authentication failure: Invalid response code received from server (Code: 535) in /home/hosting/host.pt/webmail/program/lib/Roundcube/rcube.php on line 1702 (POST /webmail/?_task=mail&_unlock=loading1606208926100&_framed=1&_lang=pt_PT&_action=send)

**Comment by alecpl** [comment]
No, but you can have it with `log_logins=true`.

**Comment by dddns** [comment]
Alec,

Yes, I have it enabled, maybe i didn't explained myself.
I have the logins, and on sucessfull logins, the log show's the IP of the user in the logs.
But in the unsucessfull logins, it doesn't show the IP, that was my request,

**Comment by alecpl** [comment]
So, how the entries in userlogins.log look like?

**Comment by dddns** [comment]
Alec,

Don't remember the purpose of this, but in failed logins the source IP is there, maybe was something that I activated after.
You can close it,

Mar 26 12:28:50 webservices roundcube: <tna9s140> Failed login for sdfsd@dss.pt from 213.228.163.13 in session tna9s140vj7mbv54 (error: 0)
