### ISSUE TITLE
HTML editor - keyboard shortcut for "block quote" toolbar button

### ISSUE THREAD

**Issue by chilek** [roundcube/roundcubemail#7744]
Please, consider seriously adding keyboard shortcut for "block quote" toolbar button support in HTML-mode message body editor.
It's heavily incomfortable to click manually this button with LMB during long quote modification to match final result to interleaving posting.

**Comment by alecpl** [comment]
Is your main use-case to break block-quote block? There was an idea to do it with Enter key (#5121), but it wasn't that easy to implement. Adding just a shortcut is not exactly the same and should be easier. PRs welcome.

**Comment by chilek** [comment]
> Is your main use-case to break block-quote block?

Yeap.

**Comment by chilek** [comment]
> PRs welcome.

I'd propose mousetrap usage, but AFAIK you - you won't like it :D

**Comment by tpayen** [comment]
There is a configuration parameter in TinyMCE which seems to do what we want when we press enter : https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#end_container_on_empty_block

I tried it in roundcube 1.4 but it seems to need several presses on enter to work properly. Maybe TinyMCE v5 works better on this point

**Comment by chilek** [comment]
Thunderbird treats 'enter' key press as intention to write our reply in quotation and automatically removes quote characters in current line. Shall we follow this solution?

**Comment by alecpl** [comment]
Close in favor of #8452 5121
