### ISSUE TITLE
"message_ready" hook : editing a draft message with custom headers make them disappear

### ISSUE THREAD

**Issue by tco942** [roundcube/roundcubemail#7746]
Hello,

I'm trying to write a plugin that add custom headers. For this purpose, I use the "message_ready" hook. It successfully adds my custom headers on sent mails.

The problem is about draft messages. I see the MIME structure with my new header too. However, if the draft is edited then sent, the sent mail won't have my custom headers. It means that the  modifications made in the draft's MIME structure are lost once it has been edited

I could not find many usages of this hook, so I was wondering if that might be the expected behavior. If that's the expected behavior, is there any hook to catch draft edit event ?

Additional info :
Roundcube version : 1.4.9
PHP version : 5.4.0
Mail server : Apache/2.4.6
IMAP server : Dovecot 2.2.36
OS : Centos 7.6.1810
Browser : Firefox, Chrome
Logs : nothing specific
Reproducible : make a custom plugin that only add a dummy header on "message_ready" hook. Save a message as draft, edit the draft, send the draft. See dummy header vanished.
Plugins (beside mine) : archive, zipdownload

**Comment by alecpl** [comment]
This is expected. The extra headers on a draft aren't used.

But why would you add these headers to draft, can't you added when the message is being sent?

**Comment by tco942** [comment]
OK, thanks for your quick reply.

FYI, these headers are set throught a form my plugin provide. I add them to MIME structure once message is sent. If I apply them to a draft, I will have to go throught my form again, once I edit > send the mail.
