### ISSUE TITLE
more options for filtering in managesieve

### ISSUE THREAD

**Issue by brianjmurrell** [roundcube/roundcubemail#7747]
It appears that the managesieve plugin really only knows how to match on header fields.

There are more possible matches.  https://www.fastmail.com/help/technical/sieve-examples.html is but just a tiny example.

Can more match types be added to the managesieve plugin?

**Comment by brianjmurrell** [comment]
NVM.  I just found the modifiers.

**Comment by sl5net** [comment]
@brianjmurrell  whats NVM?

**Comment by brianjmurrell** [comment]
https://www.dictionary.com/e/acronyms/nvm/#:~:text=NVM%20is%20an%20acronym%20that,often%20used%20as%20a%20hashtag.
