### ISSUE TITLE
Elastic skin weird bug in email list view on multiple Android devices

### ISSUE THREAD

**Issue by UnlegitApple** [roundcube/roundcubemail#7749]
As the title says, the bug is occuring on multiple Android devices and browsers and in email list view. (See screenshot)
![photo_2020-11-26_18-56-54](https://user-images.githubusercontent.com/28144903/100381375-2e0f4380-3019-11eb-8490-1cb9b94791b1.jpg)

**Comment by alecpl** [comment]
What browsers and precise version nunmbers? What Roundcube version?

**Comment by alecpl** [comment]
What if you get rid of mobile and jquery_mobile plugins? What browser versions?

**Comment by UnlegitApple** [comment]
@alecpl Works now, obviously these plugins weren't correctly configured.
Thank you very much!
