### ISSUE TITLE
Error when attaching a file with ' character in filename

### ISSUE THREAD

**Issue by 01i** [roundcube/roundcubemail#7755]
A colleague reported that she was unable to attach an excel document to an email using webmail.

After successfully uploading a few to my own account, I requested a copy of the documents she was having trouble with.

The filename of the file she was trying to attach was "4.12.20 - Team Leaders' Safeguarding Course - Access to East Sussex Learning Platform Safeguarding E-Learning Account.xlsx"

When trying to upload, a red box containing the text "Server Error! (Forbidden)" flashes up quickly in the lower corner, and the file is not attached.

When removing the single quote from the file name, it attaches fine.

**Comment by alecpl** [comment]
Check your http server logs and Roundcube logs. Maybe some security feature blocks this file. I don't think it's Roundcube issue.

**Comment by alecpl** [comment]
No feedback.
