### ISSUE TITLE
Settings/Contacts/Sorting column does not work in CardDAV Addressbook

### ISSUE THREAD

**Issue by JMA-Github** [roundcube/roundcubemail#7757]
When I change the sorting column i.E. to Last Name, it will have the expected effect in my Personal Addressbook.
All contacts are sorted ba "Last Name".
But, contacts in my CardDAV Addressbook (connected to a Nextcloud based CardDAV-Server) will always be sorted by "Display-Name". The change of "Sorting Column" in the settings has no effect.

**Comment by alecpl** [comment]
Roundcube does not support CardDAV, so this is a bug in the plugin you're using.
