### ISSUE TITLE
Double scroll bar when answering to a mail with many lines

### ISSUE THREAD

**Issue by tw-** [roundcube/roundcubemail#7760]
I'm on 1.4.9 and elastic - but problem is still (or again?) the same.

_Originally posted by @tw- in https://github.com/roundcube/roundcubemail/issues/7500#issuecomment-736522029_

**Comment by tw-** [comment]
Screenshot:

![Screenshot_2020-12-08 Webmail Schreiben](https://user-images.githubusercontent.com/6161199/101490991-7278d880-3963-11eb-8c45-94af339b3c60.png)

**Comment by alecpl** [comment]
I see you're using modified skin. Does it happen with the vanilla package? What browser?

I'm unable to reproduce on git-master.

**Comment by tw-** [comment]
Found the problem on 1.4.9 and checked with git-master today. Only color was modified - checked this with vanilla package - problem is the same.

Browser: Firefox 84 Linux, Firefox 84 Windows, Edge 87 Windows, Chrome 87 Windows.

Problem appears only when answering as text-only with many lines, double scrollbar disappears on keypress in text-area. Exactly the same as in issue #7500

**Comment by tw-** [comment]
Chrome 81 Windows
Roundcube 1.4.10

![screenshot](https://user-images.githubusercontent.com/6161199/103795091-d87d7c00-5045-11eb-92ea-c86d251d5895.png)

**Comment by mckaygerhard** [comment]
confirmed only happens in text mode with huge lines..

**Comment by alecpl** [comment]
Is this still a thing on git-master? I'll need a sample message to try to reproduce this issue.

**Comment by mckaygerhard** [comment]
pardom me.. but there's at least two pictures.. i understand that only production use send issues of those details .. if two persons report a problem in STABLE, to developers.. those guys never try by yourselft.. this only happened in important projects.. 

of course it happened in some rare cases with git @alecpl  but people that reports take the time of busy time to report as collaboration

**Comment by pabzm** [comment]
Reproducible with 1.6.7.
