### ISSUE TITLE
QUESTION : GET query parameters when composing new message

### ISSUE THREAD

**Issue by MetallianFR68** [roundcube/roundcubemail#7761]
Hi,

I discovered that I can use the following get parameters to fill some inputs while composing a new message :

_to = recipient address
_subject = email subject
_body = message body

Example : https://webmail.mydomain.com/?_task=mail&_action=compose&_to=test@test.com_subject=This%20is%20great

Are there other parameters that I can use like that ?
For example can I request a read receipt or "save sent email into a specific folder" ?
That would be great to improve my workflow.

Last question : is there a way to add an attachment automatically when opening the compose window ?
I want to add a function in my software that allows to right click on a file and "send by email" (I'm runnning a WEBDAV server)

Thanks in advance for your answers

Best regards

**Comment by alecpl** [comment]
No and No, but it could be implemented as a plugin.
