### ISSUE TITLE
Photo not found Issue

### ISSUE THREAD

**Issue by ADDISON74** [roundcube/roundcubemail#7765]
I am using RoundCube 1.4.8 (Elastic theme) with a virtual machine (Debian + Virtualmin). In order to reproduce this issue please follow these steps:

1. Get into RoundCube and compose a couple of short emails, just text without any images. For receiver's email address use the same email address used for accessing RoundCube.

2. Send the emails. Open Inspector into your browser and click on Console tab. Once you receive the messages click on them and watch the Console.

Here is the error messages I got for every click:

```
GET https://www.mydomain.tld/roundcube/?_task=addressbook&_action=photo&_email=contact%40mydomain.tld&_error=1 404 (Photo not found)
```

By deleting the part "_action=photo" from the link and loaded in a separate tab I was able to load the Address Book page without any erros in Console.

Now go to RoundCube Settings and switch from Elastic to Larry theme. Click again on the messages in Inbox and watch the Console. This time there are no errors.

P.S. I accidentally discovered this issue. I have been using the Larry theme for a long time.

**Comment by alecpl** [comment]
Not a bug.

**Comment by ADDISON74** [comment]
Just "not a bug"? Without any feedback? 

I'm sorry I wasted 30 minutes of my time investigating and writing about this issue.

**Comment by alecpl** [comment]
The fact that the request returns 404 does not mean it is an error. In this case it means "there's no contact with a photo and specified email address".

**Comment by ADDISON74** [comment]
I appreciate for the feedback. 

How do you explain this issue appears only in Elastic theme but not in Larry? A small change is needed even it is inoffensive one. I never used in 5 years contacts having photos associated. Even I like the new theme I will continue using Larry. I don't like seeing errors.
