### ISSUE TITLE
Database schemas of MySQL and PostgreSQL incompatible

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#7767]
I'm trying to migrate the Roundcube database from MySQL to PostgreSQL. I've exported all rows into an SQL file per table and need to import them now. The insert statements look good, but they contain forbidden data. Now it complains that the users.preferences field cannot be null, but in MySQL I had lots of those null values. The PostgreSQL schema does not allow this and defaults to an empty string, which is something else (except if you ask Oracle).

As a workaround I'll have to replace all nulls with empty strings in MySQL before exporting. But I guess this should be made more consistent.

Update: The MySQL schema doesn't even require unique user names. I found multiple duplicate entries in the users table.

**Comment by johndoh** [comment]
> Update: The MySQL schema doesn't even require unique user names. I found multiple duplicate entries in the users table.

That's correct the `username` field is not unique that would not make sense. The combination of `username` and `mail_host` has a unique constraint in all database engines.

**Comment by ygoe** [comment]
Of course I did mean the combination of username and mail_host. I'm not sure how this could even work reliably for the affected users. I've always upgraded the application as described but my old MySQL schema allows this, and there are timestamps dating back many years, so it's been like this for a long time. The newly installed PostgreSQL schema dos not allow that.

**Comment by alecpl** [comment]
For user.preferences column we indeed could make it "nullable".

For the unique key... The key is the same in mysql and postgres schema. So, I don't see how it would be possible to have duplicates there. Maybe you missed case-sensitivity? Could you verify the duplicates you see in this context?

**Comment by ygoe** [comment]
Nope, the records are exactly identical and Postgres complained about that when importing. I just checked that table and it only has a primary key on user_id but no other unique keys or constraints.

**Comment by alecpl** [comment]
There is a UNIQUE KEY since version 0.5. So, looks like your schema is outdated somehow. Are you migrating such an old database into a new schema? Anyway, looks like we can ignore this part and leave the ticket for user.preferences change.

**Comment by ygoe** [comment]
I'm migrating the data from what's in use for my version 1.4.3 into a fresh installation of the latest code on a new server. I'm just copying the data because the schema is already provided by the installer and a MySQL schema wouldn't fit a Postgres database. I could now complete the transfer, only the main 5 tables were required, the rest is empty anyway (ignoring the sessions). In the process I also found out that I had users in that database that didn't exist anymore, so I'll have to clean up here when a mailbox or domain is deleted.

**Comment by chrestomanci** [comment]
Perhaps this is not the place to ask, but should this become a feature request to write a MySQL to Postgres migration tool?

I am not fluent in PHP (I prefer Perl or Python), but I would have thought that the existing roundcube code that knows the DB schema for each DB dialect could be easily re-purposed to read records from one DB and write them back to a different one, so it should be fairly easy to write a simple DB migration script in PHP that uses the existing roundcube codebase for most of the heavy lifting.

I also suspect that migrating from between DB engines is fairly common as installations grow in users and requirements and outgrow their old DB, probably in a predictable pattern of SQLite -> MySQL -> PgSQL

FYI, the reason I have jumped on this ticket is because I have a roundcube installation on MySQL, I would like to migrate to PgSQL, but I can't see an easy or clear path on how to do so.

**Comment by alecpl** [comment]
> Perhaps this is not the place to ask, but should this become a feature request to write a MySQL to Postgres migration tool?
Such a request would be closed as wontfix. I'm not interested in writing migration tools.

**Comment by ygoe** [comment]
@chrestomanci Just to help you out a little… I'm using [DBeaver](https://dbeaver.io) (free edition) for most database work. It has an SQL export function that writes almost portable SQL that can simply be executed on a target database. Other (commercial) tools may provide more comfortable migration methods. Here's what I do for the migration:

Dump:
* Open the source MySQL database
* Execute: update users set preferences = '' where preferences is null;
* Make sure you have no duplicate users in that table. I took the chance to delete expired users, too.
* Select these tables: contactgroupmembers, contactgroups, contacts, identities, users
* In the context menu, select Export, choose SQL format
* Set these options:
    * Include generated columns
    * Omit schema name
    * Data rows per statement: 1000
* Edit the generated files (one per table) and change column name back-ticks (MySQL dialect) to double-quotes (ANSI) (repeat if you have more than 1000 records in an affected table)
* Save all files as UTF-8 *with BOM* for DBeaver to recognise the encoding correctly (e.g. with Notepad++)

Load:
* Open the Postgres database (must have been created by the RC installer)
* For each table file in this order: users, identities, contacts, contactgroups, contactgroupmembers
* Drag the file into the DBeaver window, opens in a new SQL editor
* Select the connection to execute this on (from the toolbar)
* Execute script
* Commit (if not in auto-commit mode), only then close the document and proceed with the next one

Other tables contain session and cache data that I don't consider relevant for an offline migration, or were empty.

**Comment by alecpl** [comment]
Fixed.
