### ISSUE TITLE
Duplicated folders after upgrade !!

### ISSUE THREAD

**Issue by naamaan** [roundcube/roundcubemail#7769]
Hi,

I'd upgraded my installation to v1.4.7, in some account it keeps duplicating different folders like: "Deleted items", "Sent items" ...etc. Please see the attached snaps.

Any help is appreciated!

![SentItems-en](https://user-images.githubusercontent.com/2176593/101339293-e5605180-3886-11eb-9da1-67e9d17d584d.jpg)

![SentItems](https://user-images.githubusercontent.com/2176593/101339050-8c90b900-3886-11eb-9cd8-c95bfd3665a0.jpg)

**Comment by alecpl** [comment]
Configuration issue. Hint: There's configuration options as well as per-user preferences defining special folders. There's also `create_default_folders` option.

**Comment by naamaan** [comment]
Thanks a lot.
Regards,
