### ISSUE TITLE
compressMessageSet: A non-numeric value encountered

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7774]
Roundcube version: 1.4.9

Hi, I'm getting some errors in my installation of roundcube:

```
Warning: A non-numeric value encountered
```

The stacktrace is:
```
#5 /program/lib/Roundcube/rcube_imap_generic.php(3930): rcube_imap_generic::compressMessageSet
#4 /program/lib/Roundcube/rcube_imap_generic.php(2431): rcube_imap_generic::fetch
#3 /program/lib/Roundcube/rcube_imap.php(816): rcube_imap::list_flags
#2 /program/steps/mail/check_recent.inc(137): include_once
#1 /index.php(306): include
#0 /public_html/index.php(26): null
```

The `_action` would be `refresh` and the `_task` is `mail`. I could not reproduce it myself, but this keeps popping up in the error logs.

**Comment by alecpl** [comment]
I'm suspecting this might happen when refresh request is executed when the messages list is in a "search result from multiple folders" state. Good catch.

**Comment by alecpl** [comment]
Nope. Looking at the code I don't think this is the case. Or maybe it might be but would require two windows with different messages list state. Strange. What plugins are you using?

**Comment by codegain** [comment]
```
contextmenu
archive
filesystem_attachments
managesieve
jqueryui
```

and some small custom ones which only add some additional settings pages or add links to other sites (they don't interfere with mail composing)

**Comment by alecpl** [comment]
Fixed.
