### ISSUE TITLE
Roundcube prints email with a very large E in it.

### ISSUE THREAD

**Issue by DLSmith63** [roundcube/roundcubemail#7776]
Sometimes it is a Capital E , sometimes lowercase e. It just started recently.

**Comment by alecpl** [comment]
I don't think it's Roundcube's fault.

What version? What browser? What operating system? What plugins? Can I see a screenshot?

**Comment by DLSmith63** [comment]
Thanks for the reply Alecpl, I'll have to get back to you on this. The person with the issue will be in later today.
