### ISSUE TITLE
(Minor) Return 204 rather than 404 on missing contact photo

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7777]
When requesting a contact photo for a contact which has no photo stored Roundcube returns either the blank.gif or a `404 Photo not found` error depending on the `_error` param in the URL. In some cases (eg. Elastic skin) `onerror` handling on the `<img>` tag is used to display a placeholder image in the event no contact photo exists.

According to the HTML spec error handling for `<img>`'s is dependent on the content of the server response and not the HTTP status code:

From http://www.whatwg.org/specs/web-apps/current-work/#the-img-element
> Whether the image is fetched successfully or not (e.g. whether the response code was a 2xx code or equivalent) must be ignored when determining the image's type and whether it is a valid image.
>
> Note: This allows servers to return images with error responses, and have them displayed.

Based on this I think a status code of 204 (No Content) could be used instead of 404 or even 200. I think this would eliminate some noise from the results of log analysis where sysadmins may monitor 404 response to detect application/configuration errors or even attacks.

I've tested this in IE11, Chrome and Firefox and the contact and placeholder images are showing correctly.

**Comment by alecpl** [comment]
Makes sense. Create a PR, there's one assertion in `tests/Actions/Contacts/Photo.php` that will have to change.

**Comment by thomascube** [comment]
The magic number 7777 :-)

Thanks a lot for the input and PR!

**Comment by johndoh** [comment]
> The magic number 7777 :-)

Hehe yep :-)

I thought I'd look into if there was any realistc alternative to the 404 response after this [forum post](https://www.roundcubeforum.net/index.php/topic,29200.msg74441.html?PHPSESSID=buodl1qk72576gq81dins5kg29#msg74441).

**Comment by alecpl** [comment]
Done.
