### ISSUE TITLE
Password Plugin - cPanel XMLAPI.PHP functions are obsolete - Replace with newer cPanel UAPI calls

### ISSUE THREAD

**Issue by eddieleeallen** [roundcube/roundcubemail#7780]
XMLAPI.PHP cPanel functions are obsolete for password plugin.  They do not update the User's password.  It provides a success message but the password is not changed.

The solution is to replace cPanel functions with new cPanel UAPI function calls. or creating a new PHP script file for cpanel UAPI required functions.
https://documentation.cpanel.net/display/DD/UAPI+Modules+-+Email

**Comment by alecpl** [comment]
cpanel_webmail driver uses UAPI. Maybe we should remove the old driver and rename cpanel_webmail to cpanel.

**Comment by eddieleeallen** [comment]
Test environment is A2Hosting, shared hosting, independent install of roundcube via Softaculous.  cPanel version 86.  In testing I changed driver from cpanel to cpanel_webmail and Password Plugin would save/update the Users email password.  cpanel driver would not work due to non supported XMLAPI calls it uses as of Dec 2020.

**Comment by eddieleeallen** [comment]
cpanel_webmail driver selection works in my shared hosting environment
where cpanel driver would not.  Thanks for your reply

**Comment by alecpl** [comment]
Done.
