### ISSUE TITLE
ldap: search in address book contacts does not work

### ISSUE THREAD

**Issue by graceastrid** [roundcube/roundcubemail#7782]
Friends, there are more than 600 people in my organization and we use a roundcube with connected authorization through ldap + ldap address book.
The problem is this: about 3-5 out of 600 people have problems finding contacts in the ldap address book via the web roundcube. when they enter the last name of a contact in the search, no contact can be found (the list of contacts in the address book is displayed correctly).
all the same problems are reproduced in other browsers and even on a mobile device (if you use the web version of the roundcube)

what could be the problem?

we use roundcube 1.4.9

**Comment by alecpl** [comment]
What plugins are you using? Could you test with ldap_debug? What browsers these users are using? Check the browser console for errors and Network tab for the server response content.

**Comment by graceastrid** [comment]
> What plugins are you using? Could you test with ldap_debug? What browsers these users are using? Check the browser console for errors and Network tab for the server response content.

i use the config file contains the setting $config ['ldap_public']

search_fields' =>
array (
0 => 'mail',
1 => 'displayName',
2 => 'mobile',
3 => 'intraPhone',
)

search for these users does not work in any browser (even in a mobile browser). search works for other users.

can you tell me how to use ldap_debug correctly?

I do not yet have the opportunity to check the developer console in the user's browser.

**Comment by graceastrid** [comment]
> What plugins are you using? Could you test with ldap_debug? What browsers these users are using? Check the browser console for errors and Network tab for the server response content.

hi!

the employee has a problem with the ldap account. I have the same account, but the search works. the employee has a problem in any browser (and even in a browser on a mobile phone).

there are no errors in the browser in the developer console, and the content of the Network tab is correct, and matches the content of the network tab in the browser of my account (I compared)

i use the config file contains the setting $config ['ldap_public']

search_fields' =>
array (
0 => 'mail',
1 => 'displayName',
2 => 'mobile',
3 => 'intraPhone',
)

search for these users does not work in any browser (even in a mobile browser). search works for other users.

can you tell me how to use ldap_debug correctly?

**Comment by graceastrid** [comment]
> What plugins are you using? Could you test with ldap_debug? What browsers these users are using? Check the browser console for errors and Network tab for the server response content.

hi!
I found a way to enable ldap logs.

after enabling $ config ['ldap_debug'] = true and when trying to search from the same account in which the search in the ldap address book does not work, try to find something, then nothing is displayed in the logs regarding the search from this particular account ... other accounts in the logs show search attempts.

**Comment by alecpl** [comment]
Compare POST content for the search request (using browser console).

**Comment by graceastrid** [comment]
> Compare POST content for the search request (using browser console).

if I understand you correctly, then: POST content for the search request is ideal for my POST request (my search for contacts in the LDAP address book works correctly)

**Comment by alecpl** [comment]
Actually it is a GET request, but anyway, you say it's the same? I'm especially interested in the `_headers` parameter. Another thing to check would be `addressbook_search_mods` in the user preferences (`users` table, `preferences` column). I suspect some "malformed" value here. We had a similar issue with mail searches before.

**Comment by alecpl** [comment]
I'm afraid that without more feedback we can do nothing about the issue.
