### ISSUE TITLE
Reminder on "all day events" is the default?

### ISSUE THREAD

**Issue by KlavsKlavsen** [roundcube/roundcubemail#7787]
I am running Kolab - and the roundcubemail in that (1.2.x) is unfortunately a bit old (I'll try to talk to the kolab community about why that is) - but in that version atleast - when I add a new calendar entry - and select "whole day event" - it still keeps its "default reminder" of 15 min. before the event.

That has several times woken me (and sometimes my entire team when I put something in the shared calendar) at 23:45 :+1: 

Putting a reminder on an all day event, really should not be the default :)
p.s. I have not verified this is still an issue in latest roundcubemail.

**Comment by alecpl** [comment]
We do not support calendar plugins here.
