### ISSUE TITLE
"UID SEARCH: Unknown argument" on invalid search_mods

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7789]
Hi,

I got a few users complaining that their search bar is not working anymore (On roundcube 1.4.9). After some digging I found the following:
If there are invalid `search_mods` saved for the user, the `UID SEARCH` command fails.

I looked at one user's saved preferences and found the following (dump of `user->get_prefs()`)

```
Array
(
    [search_mods] => Array
        (
            [*] => Array
                (
                    [Sent Messages] => 1
                )
        [...]
```

This results in the following `UID SEARCH` error when searching:

```
A0005 UID SEARCH HEADER SENT MESSAGES test
A0005 BAD Error in IMAP command UID SEARCH: Unknown argument TEST (0.001 + 0.000 secs).
```

I don't know how `Sent Messages` did end up in the `search_mods` but it's impossible for the user to remove it on their own. After changing the search filter this simply results in something like this:

```
A0005 UID SEARCH OR HEADER SENT MESSAGES test HEADER TO test
A0005 BAD Error in IMAP command UID SEARCH: Unknown argument TEST (0.001 + 0.000 secs).
```

Would it be possible to check the `search_mods` array before doing the search and simply remove invalid values? Or maybe after the user logs in: Clean the `search_mods` of invalid values and save it?

**Comment by alecpl** [comment]
I guess we could do the validation in `rcmail_action_mail_index::search_mods()`. It could remove the unexpected entries, and if that happens save the preference. Would you like to provide a pull request?

**Comment by alecpl** [comment]
Fixed.
