### ISSUE TITLE
Database password. Roundcube changing %50 to P

### ISSUE THREAD

**Issue by tortkara** [roundcube/roundcubemail#7790]
Roundcube changing my database password.
Password in /etc/roundcube/debian-db.php is "ab12345AB%505". 
var_dump($dsn) in rcube_db.php show me "ab12345P5".

Roundcube: 1.4.3
DB: mariadb 10.3.25
PHP: 7.4.3
OS: Ubuntu 20.04

**Comment by alecpl** [comment]
DSN string is an URI which means that special characters need to be encoded.

**Comment by tortkara** [comment]
Thank you!
