### ISSUE TITLE
undefined function mb_internal_encoding()

### ISSUE THREAD

**Issue by V0RTX** [roundcube/roundcubemail#7794]
Ubuntu 18.4, php 7.4, Roundcube 1.4.9, iRedMail-1.3.2, ngnix running on port 4434 to avoid conflict with apache.
After upgrading to php 7.4, Roundcube webmail failed to load using port 4434.  Had worked on previous Roundcube 1.4.7 and php 7.2.
**ngnix error.log** 
`2020/12/20 11:49:05 [error] 7652#7652: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /opt/www/roundcubemail-1.4.9/program/lib/Roundcube/bootstrap.php:86`
`Stack trace:`
`#0 /opt/www/roundcubemail-1.4.9/program/include/iniset.php(62): require_once()`
`#1 /opt/www/roundcubemail-1.4.7/index.php(40): require_once('/opt/www/roundc...')`
`#2 {main} thrown in /opt/www/roundcubemail-1.4.9/program/lib/Roundcube/bootstrap.php on line 86" while reading response header from upstream, client: 45.248.78.164, server: _, request: "GET /mail/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9999", host: "xxxx.xxxx.xxx:4434"`
**php7.4-fpm log**
`Dec 20 20:36:42 xxxx php-fpm[946]: [NOTICE] fpm is running, pid 946`
`Dec 20 20:36:42 xxxx php-fpm[946]: [NOTICE] ready to handle connections`
`Dec 20 20:36:42 xxxx php-fpm[946]: [NOTICE] systemd monitor interval set to 10000ms`
`127.0.0.1 -  20/Dec/2020:20:53:42 +1100 "GET /mail/index.php" 500`
**From php, where the offending call in the error above is depreciate:**
`[php.net/manual/en/ini.core.php#ini.zend.script-encoding](url)`

Not sure if it's an error or my config?  I've checked thoroughly and cannot find where it may be wrong.
Will appreciate any input here,
Thanks.

**Comment by alecpl** [comment]
You lost some extensions with PHP upgrade. Here mbstring.

**Comment by V0RTX** [comment]
Hello, thanks for your reply.  I have mbstring and it is enabled, one of the first things I checked.

**Comment by Verox001** [comment]
I experience the same issue. I upgraded from PHP 7.4 to 8.2 and even though mbstring is enabled for CGI and CLI, I still get the error.

**Comment by lordkage** [comment]
It's more than just installing the PHP extension, you need to also restart apache/httpd for the php module to pick it up.
