### ISSUE TITLE
You lost some extensions with PHP upgrade. Here mbstring.

### ISSUE THREAD

**Issue by V0RTX** [roundcube/roundcubemail#7795]
You lost some extensions with PHP upgrade. Here mbstring.

_Originally posted by @alecpl in https://github.com/roundcube/roundcubemail/issues/7794#issuecomment-748589876_

**Comment by V0RTX** [comment]
Hello, thanks for your reply.  I have mbstring and it is enabled, one of the first things I checked.
`[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache`

```
Multibyte Support | enabled
-- | --
Multibyte string engine | libmbfl
HTTP input encoding translation | disabled
libmbfl version | 1.3.2
```

**Comment by alecpl** [comment]
This is not Roundcube issue. This is PHP setup issue. Please ask on mailing list or forum.

**Comment by V0RTX** [comment]
Thanks for your energy and care in helping NOT!

**Comment by lordkage** [comment]
It's more than just installing the PHP extension, you need to also restart apache/httpd for the php module to pick it up.
