### ISSUE TITLE
Size col in widescreen Larry and Classic skin

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7796]
Apologies if you are already working on this, I know it very soon to open a ticket after the commit. The Larry and Classic skins need updating for ffe8a0c94075bacb0943fb58cb8f9c905991a4ff. Since both skins have List and Desktop layouts I think its enough just to hide the new size span. For sure in Claasic which only has depreciated support now.

I can submit a PR if you like but thought I'd make this ticket first in case you were already working on it and also so it didn't get forgotten.

**Comment by alecpl** [comment]
I completely forgot about that. Indeed, I agree to just hide the size in larry and classic. Please, create a PR.
