### ISSUE TITLE
Some functionality not working

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7801]
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/roundcube/vendor/pear/net_idna2/Net/IDNA2.php on line 2686

**Comment by jedvod** [comment]
![image](https://user-images.githubusercontent.com/59712443/103183112-6cae4d00-48a8-11eb-9fa2-4d2448ff6151.png)

/installer/index.php

On the first install page, the 'NEXT' button doesn't show.

**Comment by jedvod** [comment]
the version I am running: 1.4.10

**Comment by alecpl** [comment]
Roundcube 1.4 does not support PHP8. You have to switch to PHP7.

**Comment by alecpl** [comment]
In 83d9ad3f6440 I added an error message, so we get less tickets like this.
