### ISSUE TITLE
can you please provide a compat matrix for PHP

### ISSUE THREAD

**Issue by tessus** [roundcube/roundcubemail#7802]
I've been searching on the wiki, on the Internet, and on the web site.

Unfortunately there's no compatibility matrix which tells me which Roundcube version is compatible with which PHP version.

e.g. can I run 1.4.10 with PHP 7.4 and 8.0?

**Comment by Rotzbua** [comment]
Seems to be solved yesterday by 83d9ad3f644007719820d39f23285bb665b04999

**Comment by alecpl** [comment]
There's no matrix, and indeed older versions did not specify the max supported version.

In short, any version released before a PHP major release is not compatible with it. PHP8 will be supported by Roundcube 1.5.

**Comment by tessus** [comment]
@alecpl thanks a bunch for the reply. So 1.4.x works with 7.4? I'm just asking because there were some breaking changes in 7.4 that screwed up a few other projects....
I'm asking because PHP 7.3 is already EOL and there's no info when Roundcube 1.5 will be available.

**Comment by alecpl** [comment]
> So 1.4.x works with 7.4?
Yes.

**Comment by thomascube** [comment]
I just updated [the website](https://roundcube.net/about/) and [the wiki](https://github.com/roundcube/roundcubemail/wiki/Install-Requirements) accordingly.
