### ISSUE TITLE
Display Max. Attachment Size

### ISSUE THREAD

**Issue by mcakircali** [roundcube/roundcubemail#7803]
After setting the PHP upload and post sizes and RC message size to 100MB, the web interface shows 75MB attachment size warning/info; see picture below.

Is that a display bug or does it mean sth like max. single file limit?

![image](https://user-images.githubusercontent.com/11517091/103348136-6cc16f00-4a99-11eb-9ea7-0dde089e0ab8.png)

**Comment by johndoh** [comment]
See https://github.com/roundcube/roundcubemail/issues/7664#issuecomment-707506161 you need to increase `max_message_size` in your rc config to allow for the message encoding.

**Comment by mcakircali** [comment]
> See [#7664 (comment)](https://github.com/roundcube/roundcubemail/issues/7664#issuecomment-707506161) you need to increase `max_message_size` in your rc config to allow for the message encoding.

That's not the problem.

I wrote in the post that I set the RC max message size to 100MB.

**Comment by alecpl** [comment]
Duplicate.
