### ISSUE TITLE
Possible issue with google-closure-compiler v20201207

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7804]
I have stumbled across a very strange issue. When using google-closure-compiler v20201207 skins/elastic/ui.js does not minify correctly. With the previous v20201102 everything is fine. I tracked the issue down to here:

[skins/elastic/ui.js line 2065](https://github.com/roundcube/roundcubemail/blob/master/skins/elastic/ui.js#L2065):
```js
$(bar)[is_search_pending() ? 'addClass' : 'removeClass']('active');
```
the issue is that the function `is_search_pending()` is not present in the minified JS. Changing it as follows solves the problem:

```js
var active = is_search_pending();
$(bar)[active ? 'addClass' : 'removeClass']('active');
```

The issue manifests itself as the message list failing to load on login to Roundcube and the follow JS error in the console:
```
Uncaught TypeError: k is undefined - ui.min.js:58:144
```

I had a quick look through other JS files in the core and cannot see any others with the same issue but its hard to spot the differences between improvements in the compiler and errors. It feels to me like a problem with v20201207 of the complier. I had a look at their [GitHub](https://github.com/google/closure-compiler) but nothing sticks out. Still may be the best approach here might simply be to wait for their next version and retest before changing Roundcube code. `npm install -g google-closure-compiler@20201102` installs the previous version.

**Comment by alecpl** [comment]
Or we can use UglifyJS. If I just replace google-closure-compiler command with `uglifyjs --compress --mangle -- $1 >> $2` command it compiles all js files in 34 seconds instead of 43 seconds, so it is faster. Also output files are smaller. But we have to test it more carefully.

**Comment by alecpl** [comment]
Switched to uglifyjs and csso. Hopefully it works in all supported browsers. I didn't do much tests.
