### ISSUE TITLE
elastic skin tiny message pane on desktop

### ISSUE THREAD

**Issue by Ressy66** [roundcube/roundcubemail#7811]
Thought I'd have a quick look at elastic skin, but experience on two different pc's an unusual view in the last " message view" pane, it seems to carry across to print and even help pages, it can not be resized, so you get this tiny little window as I indicate with red caret, and this massive free real estate area underneath it.

(seems I cant attach images, so see links)

https://members.ausics.net/noelb/rc1..png
https://members.ausics.net/noelb/rc2.png

**Comment by alecpl** [comment]
What Roundcube version? What browser version?

**Comment by Ressy66** [comment]
sorry, my bad, always running latest stable 1.4.10   / php 7.4.13
and firefox latest ESR - on linux, and opera

**Comment by alecpl** [comment]
You're really first user with this problem, so it must be local. Maybe some browser extension interfering? Some Roundcube plugin? Firefox latest ESR is 78, right? So, not that old to have problem with our css.
