### ISSUE TITLE
Elastic: Lessc v4 comptibility issue:  media definitions require block statements

### ISSUE THREAD

**Issue by tfl** [roundcube/roundcubemail#7813]
I have trouble lessc'ing Elastic style with lessc 4:

`lessc -l -m=always styles/styles.less` gives me

```
SyntaxError: media definitions require block statements after any features in styles/widgets/editor.less on line 632, column 5:
631
632     .mce-menu {
633         width: @layout-mobile-menu-width !important;
```

- Archlinux
- Roundcube version 1.4.10 (github checkout)
- Node: v15.5.1
- lessc 4.0.0 (Less Compiler) [JavaScript]

**Comment by thomascube** [comment]
One more reason for #6284. This way not everybody needs to worry about the right tooling for building the css files.

**Comment by alecpl** [comment]
I was going to say wontfix for 1.4, but there's a PR so maybe it wont be much trouble to fix. Does the PR fix the issue above? I didn't encounter such an issue using less v4.

The 1.4 branch also probably should get 7df5e5fbad9a8.

**Comment by vookimedlo** [comment]
> Does the PR fix the issue above?

Yet, it does.

**Comment by tfl** [comment]
Well, no. It does not - at least for me. Yes, it may fix those errors based upon mathematical calculations (which I fixed by myself previously) but it does not reference (nor fix) the error I mentioned above.

**Comment by tfl** [comment]
For the time beeing I downgraded lessc to 2.7.3 and now I have my styles back. I do not know since when RC less-styles became incompatible with current lessc but RC v1.4.9 styles are incompatible too.

**Comment by vookimedlo** [comment]
@tfl Do we use the same compiler?

```
npm install less
npm install less-plugin-clean-css
```

I tried it again with changes in PR and that syntax error has gone.

![image](https://user-images.githubusercontent.com/2312301/103802970-357e2f80-5050-11eb-91f4-283dba23684a.png)

**Comment by tfl** [comment]
You are right! I cloned https://github.com/vookimedlo/roundcubemail.git and lessc now has nothing to complain.
BTW: we use(d) the same compiler (see my initial post)

**Comment by alecpl** [comment]
Fixed.
