### ISSUE TITLE
plugins markasjunk 

### ISSUE THREAD

**Issue by sp4148** [roundcube/roundcubemail#7817]
Is there any Learning Driver for ISPCONFIG ?
that easily editable blacklist/whitelist for roundcubemail

**Comment by alecpl** [comment]
Why do you assume we know what ISConfig is or what it uses under the hood? Ask on mailing list or forum. Or ask IspConfig.

**Comment by sp4148** [comment]
If not, can I will write one to contribution?

**Comment by alecpl** [comment]
Sure, PRs always welcome. Make sure you don't duplicate an existing driver functionality.

**Comment by sp4148** [comment]
thanks for prompt reply

**Comment by sp4148** [comment]
how I submit the contribution?
