### ISSUE TITLE
500 error codes showing in browser console but no errors displayed within logs/errors.log

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7818]
Example 500s
![2021-01-06 21_10_53](https://user-images.githubusercontent.com/59712443/103820360-1be6e300-5064-11eb-8100-aafd0bf9bca5.png)

yet the last errors in my errors.log were surrounding STARTTLS (caused by a misconfiguration).

**Comment by alecpl** [comment]
If this was a PHP error I would expect some error in log (Roundcube error log or http server error log). Maybe that's some http/proxy error? We can't really help you based on provided information.
