### ISSUE TITLE
TIFF inline images are not displaying (conversion to .jpg not working?)

### ISSUE THREAD

**Issue by Programmierus** [roundcube/roundcubemail#7819]
Some e-mail clients paste graphics by default as TIFF Images (e.g. Apple Mail, inserts pasted screenshots as `PastedGraphic-1.tiff`).

#3757 mentions that there should be a conversion to .JPG in place which is necessary since most browsers do not support TIFF graphics. It doesn't seem to work for my setup though (latest RC through Docker).

![image](https://user-images.githubusercontent.com/49633745/103879889-ffea4c80-510a-11eb-8d8e-17dbfb8d23e1.png)
which comes from the following source:

```
<img apple-inline="yes" id="97E6A44F-34EF-41C3-8D81-56BDFFE8A5C3" src="cid:E3C9FFB4-1353-4393-A02D-A4E3FC7430CE">
```

Image is attached as following: 

```
--Apple-Mail=_80F0B4C9-6DD3-4101-86B8-A3900DA50886
Content-Transfer-Encoding: base64
Content-Disposition: inline;
	filename=PastedGraphic-1.tiff
Content-Type: image/tiff;
	x-unix-mode=0666;
	name="PastedGraphic-1.tiff"
Content-Id: <E3C9FFB4-1353-4393-A02D-A4E3FC7430CE>

[base64 data]
```

**Comment by alecpl** [comment]
Do you have php-imagick installed and/or ImageMagick binary installed on the server (and `image_convert_path` set in config)?

Sorry, I don't know what the docker image provides.

**Comment by Programmierus** [comment]
Thank you for your prompt reply. Ouch. Never noticed it's not an official image...

**Comment by thomascube** [comment]
The image is semi official and your issue will be addressed in the Roundcube Docker repo.
