### ISSUE TITLE
possible update in install file after 8b83d29f240083e32a4c83c579e74c0b566275a2

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7820]
Do the insturctions in the INSTALL file need to be update after 8b83d29f240083e32a4c83c579e74c0b566275a2 which removed the PHP error reporting settings from bootstrap.php for consistency?

https://github.com/roundcube/roundcubemail/blob/master/INSTALL#L23
```
...
* php.ini options:
   - error_reporting E_ALL & ~E_NOTICE & ~E_STRICT
...
```

**Comment by alecpl** [comment]
Yes, we should remove any requirements about the error_reporting.

**Comment by alecpl** [comment]
I decided to bring back the setting. We're re-consider in 1.6.
