### ISSUE TITLE
roundcube mobile interface

### ISSUE THREAD

**Issue by revoltown** [roundcube/roundcubemail#7822]
will check what version of roundcube i have , but cant use compose button on mobile web gui, is like a background, pussing on it opens a message behind it... (the v im talking about is 1.4.4)

**Comment by alecpl** [comment]
What browser version? You should update to 1.4.10.

**Comment by revoltown** [comment]
its firefox, on safari works perfect.

**Comment by revoltown** [comment]
Przepraszam nie zauważyłem , że PL, 
Alec możesz mi pomóc zaktualizować roundcube ?

**Comment by revoltown** [comment]
Cześć, już uaktualniona wersja roundcube do wersji 1.4.10

Mam jednak inny problem, chodzi o to że mam inne domeny które chciał bym użyć w roundcube , jednak nie przeprowadzałem konfiguracji serwera ani domen możesz mi proszę pomóc  ?

Mateusz Lamparski

**Comment by alecpl** [comment]
Nie zajmuję się tym. Rozumim, że problem rozwiązany?

**Comment by revoltown** [comment]
Jak mogę zmienić przypis na dole strony logowania : Roundcube Webmail na inny ?  
            
          
     
      
       
        Dnia 12 stycznia 2021 08:44 Aleksander Machniak &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Closed  github.com #7822 .

**Comment by revoltown** [comment]
Hej, mam problem ze zmianą wielkości skrzynki pocztowej chodzi o jej pojemność, nie mogę się doszukać gdzie zmienić te wartości w plikach konfiguracyjnych  też doszukać sie nie moge no i na UI mam teraz 2GB nie mogę tego zmienić,   To samo tyczy się wysyłanego pliku w okienku mam 8 mb  ale wg. konfiguracji php mam ustwione 12mb a tu ciagle jest 8mb.(też nie wiem gdzie to zmienić przeszukałem pliki konfiguracyjne i nigdzie nie ma odpowiedniej zmiennej widocznej).     Mateusz     
            
          
     
      
       
        Dnia 12 stycznia 2021 08:44 Aleksander Machniak &lt;notifications@github.com&gt; napisał(a):
       
    
       
         
 Closed  github.com #7822 .
