### ISSUE TITLE
Wrong charset for cyrillic symbols

### ISSUE THREAD

**Issue by kveriz** [roundcube/roundcubemail#7827]
After upgrade from 1.3.10 to 1.4.10 I noticed that some mails have wrong display charset in cases when they contains cyrillic symbols.

Here two screenshots which are showing it

1.3.10
![right_charset](https://user-images.githubusercontent.com/44600933/104449653-fc920d80-55af-11eb-91b5-abc9925aad9a.png)

1.4.10
![wrong_charset](https://user-images.githubusercontent.com/44600933/104449438-aae98300-55af-11eb-8c62-736446fbcdc3.png)

TB
![TB_right_charset](https://user-images.githubusercontent.com/44600933/104449837-4549c680-55b0-11eb-99bc-62c079a0fba9.png)

Like I said above I don't see any problems in 1.3.x and other clients such as TB, Outlook, Rainloop. Interface/charset settings are completely identical in both cases.

Which part of email do you need to check behavior?

**Comment by alecpl** [comment]
What PHP version? Could you attach a sample message?

**Comment by kveriz** [comment]
Both RC instances are working on PHP 7.1.3. Sample is in attachment.

I dug deeper and found that the issue takes place only for HTML part of message. Some "washing" and "cleaning" are done by script `program/lib/Roundcube/rcube_washtml.php` with `dumpHtml()` function. The function takes a DOMDocument object which represents UTF-8 symbols/decode in this case as ISO 8859-1(Latin-1) by default or smth like that. Unfortunately I'm not good in these questions.

So I solved the problem just concatenated `<?xml encoding="'.$this->config['charset'].'">` with $html variable in calling `loadHTML()` method of function above. But I'm not sure I selected right solution. If it's correct I can prepare a PR.

[sample.eml.zip](https://github.com/roundcube/roundcubemail/files/5828472/sample.eml.zip)

**Comment by alecpl** [comment]
The HTML content is malformed. There's some content before `<!DOCTYPE>`.

I'm able to reproduce when forcing the DOMDocument engine. However, with Masterminds/HTML5 parser it works all right. So, I'm assuming that you're not using the vanilla package with dependencies and you do not have Masterminds/HTML5 installed.

I'm not sure there's anything to fix in these circumstances.

**Comment by kveriz** [comment]
You are right. The problem got rid by installing Masterminds/HTML5. For some unknown reasons it had not been installed while Docker image was building.

 Thank a million.
