### ISSUE TITLE
Roundcube v1.2.12, v1.2.13 - "Invalid plugin name" errors in log

### ISSUE THREAD

**Issue by amiga600** [roundcube/roundcubemail#7829]
Hello,
I found error in logs/errors:

`[14-Jan-2021 10:13:27 +0100]: <vn1i67tg> PHP Error: Invalid plugin name: roundcube/net_sieve in /var/www/rc/program/lib/Roundcube/rcube_plugin_api.php on line 296 (GET /?_task=settings&_action=about)`

PHP: 5.6.40
CentOS 7: Up to date
Roundcube: v1.2.12, v1.2.13

![plugins](https://user-images.githubusercontent.com/6276653/104580027-0cb3f680-565d-11eb-982d-dd8c3cdf0a68.png)
Thank you guys!
Martin

**Comment by alecpl** [comment]
This is old unsupported version. The bug was fixed in 1.4.something

**Comment by amiga600** [comment]
OK, thanks for reply. :)
Martin
