### ISSUE TITLE
dont use exec()

### ISSUE THREAD

**Issue by damnms** [roundcube/roundcubemail#7831]
would it be possible to replace the exec() call in line roundcube/program/lib/Roundcube/spellchecker/pspell.php:43 with php-enchant? 
my php server does not allow exec() for security reasons

the command that is executed is:
aspell dump dicts

that prints on my machine
de
de-neu
de_AT
de_AT
de_AT-neu
de_CH
de_CH
de_CH-neu
de_DE
de_DE
de_DE-neu

when i run a sample code from enchant https://www.php.net/manual/en/function.enchant-broker-list-dicts.php
```
<?php
$r = enchant_broker_init();
$dicts = enchant_broker_list_dicts($r);
print_r($dicts);
?>
```

i get
Array ( [0] => Array ( [lang_tag] => en_US [provider_name] => myspell [provider_desc] => Myspell Provider [provider_file] => /usr/lib/x86_64-linux-gnu/enchant/libenchant_myspell.so ) [1] => Array ( [lang_tag] => de [provider_name] => aspell [provider_desc] => Aspell Provider [provider_file] => /usr/lib/x86_64-linux-gnu/enchant/libenchant_aspell.so ) [2] => Array ( [lang_tag] => de_AT [provider_name] => aspell [provider_desc] => Aspell Provider [provider_file] => /usr/lib/x86_64-linux-gnu/enchant/libenchant_aspell.so ) [3] => Array ( [lang_tag] => de_CH [provider_name] => aspell [provider_desc] => Aspell Provider [provider_file] => /usr/lib/x86_64-linux-gnu/enchant/libenchant_aspell.so ) [4] => Array ( [lang_tag] => de_DE [provider_name] => aspell [provider_desc] => Aspell Provider [provider_file] => /usr/lib/x86_64-linux-gnu/enchant/libenchant_aspell.so ) )

that looks really good imo!

**Comment by alecpl** [comment]
`$config['spellcheck_engine'] = 'enchant';`
