### ISSUE TITLE
Elastic: Wrong CSS generated from LESS after update to 1.4.10

### ISSUE THREAD

**Issue by svatos** [roundcube/roundcubemail#7832]
After updating from **1.4.9** to **1.4.10** I re-generated CSS for Elastic skin using LESS command tool
```lessc --clean-css="--s1 --advanced" styles/styles.less styles/styles.css```
and I saw a bug with `.folderlist li.mailbox .unreadcount` css class, specifically for a `margin` for left folder menu (see picture)

![image](https://user-images.githubusercontent.com/10947341/104742654-fc7a4500-574a-11eb-8fad-bb5907f3593a.png)
![image](https://user-images.githubusercontent.com/10947341/104742744-1ddb3100-574b-11eb-8462-a77e7a9db024.png)

It looks like LESS doesn't translate correctly to CSS - the margin value should be around `7px`, instead I see a raw formula without css `calc()` function which would works.

`skins/elastic/styles/widgets/lists.less:487`
```
.unreadcount {
    ...
    margin: (@listing-line-height - 1.4 * @page-font-size) / 2;
    ...
}

```

And with using `calc()` it's ok.
![image](https://user-images.githubusercontent.com/10947341/104743754-53cce500-574c-11eb-9987-f904ef3b35b6.png)
![image](https://user-images.githubusercontent.com/10947341/104743720-4ca5d700-574c-11eb-9891-96456d5d6e45.png)

Updated via `bin/update.sh`
```
node v14.15.4
npm 6.14.11
  less-plugin-clean-css@1.5.1
  less@4.1.0
```

This issue happens to me even if I skip minifying CSS, so with pure `lessc styles.less styles.css ` I got the same results.

Interesting part is that the downloaded package of RC installer 1.4.10 comes with Elastic LESS & CSS files working fine. Problems comes after building LESS to CSS.

For sake of making this issue report less complex I demonstrate this without using my extended skin which comes from the Elastic. Basically downloaded Elastic skin works good till I rebuild LESS files.

**Comment by alecpl** [comment]
It was already fixed with 0d396383ecc1b9e60e420ee774e2c0fbadc59aa5 and 2066b2d8581886e17e167132cf7466baf1f2735b
