### ISSUE TITLE
Need general solution for common image loading

### ISSUE THREAD

**Issue by TonyGravagno** [roundcube/roundcubemail#7833]
I'm facing an issue that's been reported before, with varying causes and varying resolutions. An email does not show in-line images even when the sender has been approved. Chrome reports a "same-origin" policy issue. Firefox reports messages like the following:

> Content Security Policy: The page’s settings blocked the loading of a resource at https://mcusercontent.com/zzzzzzzzzz/images/zzzzzz.png (“img-src”).

In that case MailChimp is hosting images as a CDN.

> Content Security Policy: The page’s settings blocked the loading of a resource at http://gallery.mailchimp.com/zzzzz/images/transparent.gif (“img-src”).

That's another MailChimp link, not httpS, apparently just for tracking.

> Content Security Policy: The page’s settings blocked the loading of a resource at https://site.list-manage.com/track/open.php?u=zzzzz&id=zzzzzz&e=zzz (“img-src”).

A third party link that doesn't have an image extension, so actual content-type is unknown.

<hr>

I understand the issue. This ticket is about how to deal with it. Please forgive if I've missed notes on this topic - I did search and there is nothing current or definitive.

There was a suggestion #5099 many years ago for an image proxy to be added into Roundcube. I think that's still a great suggestion. Implementing that with a plugin might be the best final solution.

We do want to see legitimate images. We may not want transparent trackers. I know this is a client-side issue. I know it's a lot to ask of this Roundcube team to figure this out. I'm not asking for a coded solution. I'm asking for ideas about how we can solve the problem, whether in-line in this package, with a plugin, or by other means.

I don't like ideas like turning off CSP.

Whitelisting some sites with a browser plugin might be the best solution, but it's not a good solution, and it's time consuming to implement on a user by user basis.

Here's another approach to an image proxy that can be implemented outside of Roundcube: A browser plugin can intercept requests and redirect them back to the server as https://mysite/getimage?url=actualsite/path. The server will get the image and return it. This eliminates part of the tracking problem, the PII part anyway, and the http/https issue. It would be dirt-simple to implement and there's probably code already available to do this.

What other solutions can we establish here? Thanks!

**Comment by alecpl** [comment]
The server side solution would be essentially the same as what we do with external css files. I.e. replace image urls in the message with a local url to utils/modcss action handler (which fetches the file and makes it safe). You could create a plugin using `message_part_after` hook.

There might be some more involving cases e.g. like a background image url inside the css file, but with the above you should cover most cases, I guess.
