### ISSUE TITLE
Question - Email SMTP debug logging on one line for whole email?

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7836]
I am requesting assistance in a query I have:

I see that roundcube logs the emails sent through it, however, they look to be logged over multiple log lines for each line of the email. I have my setup where my roundcube logs are sent to rsyslog and then to a database which I can query. Is there a way to configure roundcube to post a whole email as one log line possibly using escape characters to format it to a new line, but logged on one log line, so that the whole email is within a single row in my database?

Or perhaps, to have roundcube's configuration able to output separate DEBUG logs to different log drivers,  e.g. so I can have the main logs going to syslog under 1 facility and each, (enabled), debug logger, going to syslog under their own facility?

Thanks very much!

**Comment by jedvod** [comment]
Or perhaps to just have the log driver of database which should also do the trick - I know this isn't available at present, however, it may be worth some thought.

**Comment by alecpl** [comment]
You say you want to log every complete email message, i.e. debug logs to database? That's not really something I'd entertain. Better to use SMTP server features for this purpose.

I'm not saying changing the logging system is out of options, but definitely putting a complete email message in whatever log (as one chunk) is not really reasonable.
