### ISSUE TITLE
Setting enable_installer to false does not disable installer.

### ISSUE THREAD

**Issue by RichyT** [roundcube/roundcubemail#7837]
This is with the FULL version on 1.4.10

It's false in defaults.inc.php. I'm not sure if that is actually read so I copied the line to config.inc.php

```
<?php
$config['enable_installer'] = false;
```

The installer still comes up with the installer URL entered.

There appears to be a check in index.php in the installer dir but I haven't dug into why this isn't being recognized.

I will just remove the installer dir completely but the config setting is mentioned in the final page of the installer.

**Comment by thomascube** [comment]
FWIW: the installer will remain available for the current browser which as received a session cookie. Try with a private tab or close your browser.

**Comment by RichyT** [comment]
Thanks. Can confirm that this is the case. Might be worth a mention in the red text at the bottom.

**Comment by alecpl** [comment]
Not worth to spend time on it. You're the first person complaining about it.

**Comment by joshp23** [comment]
+ 1 for a mention in the text at the bottom

**Comment by neelchauhan** [comment]
This has also happened to me, provided you are in the browser session (with the cookies and such) used to install Roundcube. In another browser session with different cookies, installer gets disabled.

Firefox/FreeBSD on the session used to install Roundcube shows the installer even with `$config['enable_installer'] = true;`. Firefox on a private window, and Chromium do not.

**Comment by 3NdR1m** [comment]
Alex is right on that one, why on earth should any feature be properly documented? /s

**Comment by KarlLevik** [comment]
I too think it might be worth mentioning this in the red text at the bottom.

**Comment by lx1** [comment]
+1 me too to mention in the red text box. I'm new to RCM, I did'nt know this.

**Comment by MasterRoby3** [comment]
+1 for a mention in text at bottom, landed on this page searching about the issue

**Comment by jordan-warne** [comment]
+1 I just ran into this issue and came here looking for how to fix it

**Comment by melroy89** [comment]
It's still at the bottom in red, but not added by default to the generated config.inc.php...

**Comment by sijanec** [comment]
Well, this issue is just as good, if not better, than the documentation. It's the first result when searching the web for "enable_installer config.inc.php"

**Comment by fredkilbourn** [comment]
I too spend a few minutes on this.
