### ISSUE TITLE
"sent_mbox" in user preferences overrides config value if empty

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7842]
Hi,

I experience the following problem: If a user has set `sent_mbox` in their preferences this overrides the config value `sent_mbox` if `sent_mbox` is empty (in the preferences).

My current config:
```
$config['sent_mbox'] = 'Sent';
```

The users preference:
```
["sent_mbox"]=>
  string(0) ""
```

This causes the "Save message in:" select field (on the "composing mail" page) to be "- don't save -" by default, altough "Save on sending mail" is turned on in the settings.
I also tested this by manually setting the `sent_mbox` preference to `Trash`, then the default checked item in the select field will be `Sent` (which it shouldn't be? In my case this is ok).
There might be some edge case with an empty string as value in the `sent_mbox` user preference.

I also don't see any options in the settings where the default value could be changed.

(I'm using Roundcube 1.4.10 with the elastic skin)

**Comment by alecpl** [comment]
I'd say this is not a bug. If user sets the sent_mbox to "---" (empty) then it is his intention to not save sent mail.

**Comment by codegain** [comment]
@alecpl I don't see any setting where the user could have set `sent_mbox`. So the user is stuck by having "Save sent messages" turned on but when he sends a mail the default value for "Save sent message in:" is always set to "-- don't save --". This has to be always changed to f.e. "Sent" on every mail that is sent by the user manually. There is no way to change the default for this AFAIK or do I miss something?

**Comment by alecpl** [comment]
Settings > Preferences > Special Folders.

**Comment by codegain** [comment]
Thanks, that worked!
