### ISSUE TITLE
Message sent not received to Roundcubemail address

### ISSUE THREAD

**Issue by lizbeemer** [roundcube/roundcubemail#7843]
An email was sent from mark_sperring@mirlimited.com was sent to roundcubemail address e@elisabethbeemer.com on 18 January 2021 19:47, but was not received. Why not? Should the address e@elisabethbeemer.com expect not to receive more messages?  Is there a setting which needs to be changed to ensure all messages are received?  Thank you.

**Comment by thomascube** [comment]
I'm sorry but this is the wrong place to as. We don't host your e-mails and we're not responsible for the system you're using to access them. Please contact your internet hosting provider or IT responsible for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Roundcube is not a service but free software which your hosting provider installed on their servers.

**Comment by lizbeemer** [comment]
Will do, thank you for the quick response Thomas!

Elisabeth
