### ISSUE TITLE
External images not loaded

### ISSUE THREAD

**Issue by hdijkema** [roundcube/roundcubemail#7845]
While displaying an image, roundcube gets external images using `https`, while the external images are linked in the email with the `http` protocol. This causes google chrome to report the following issue on the email:

![image](https://user-images.githubusercontent.com/745693/105576625-5c3ca580-5d74-11eb-8122-50929039bfbd.png)

Chrome complains about the image requested via the `https` protocol. 

![image](https://user-images.githubusercontent.com/745693/105576689-d5d49380-5d74-11eb-87da-f0cdfb87c5e2.png)

However, when I copy the URL of an image in roundcube (right mouse click and copy image link), it is definitely provided using the `http` protocol. 

```
http://img.emailing.vereniginghomeopatie.nl/im/106784/876c13f78db0c82ad1f901ba24cc453138dcf19d7859fac7207fa4ba9d116f96.jpg?e=gMzFiZ8IXpokAEJ15qH_6kfhixpHjviLk-PrOblxEo1eJ653QajQXnV3LE2bpZuTJSM3P52rIgAAr1R8feARdAy2NVaf6vpuS0w1fvLtXBrvuQDHt1AvVNAe6iaPDdUaLkfxRNhnHSW0GMfcrnc8rYhjZh7C6nx4Zl6qgKgVNkQ4RTTp9Cgy5BgnV-v6D8y6umTR128fhJBnYa3z-4yCAWNyiAO4pmVMcviSRej3VZX_n0KUCQFNXvDlDBrqfzS5GNpY0trePMjJ-LNEeQ
```

<img src="http://img.emailing.vereniginghomeopatie.nl/im/106784/876c13f78db0c82ad1f901ba24cc453138dcf19d7859fac7207fa4ba9d116f96.jpg?e=gMzFiZ8IXpokAEJ15qH_6kfhixpHjviLk-PrOblxEo1eJ653QajQXnV3LE2bpZuTJSM3P52rIgAAr1R8feARdAy2NVaf6vpuS0w1fvLtXBrvuQDHt1AvVNAe6iaPDdUaLkfxRNhnHSW0GMfcrnc8rYhjZh7C6nx4Zl6qgKgVNkQ4RTTp9Cgy5BgnV-v6D8y6umTR128fhJBnYa3z-4yCAWNyiAO4pmVMcviSRej3VZX_n0KUCQFNXvDlDBrqfzS5GNpY0trePMjJ-LNEeQ">

Can this be fixed?

**Comment by alecpl** [comment]
That's the usual mixed content issue. Not a bug. See #7833
