### ISSUE TITLE
managesieve fatal error

### ISSUE THREAD

**Issue by gene-git** [roundcube/roundcubemail#7846]
I think this started when php was updated to version 8.  But with latest git master I get this fatal error when managesieve is turned on:

[23-Jan-2021 09:45:55 America/New_York] PHP Fatal error:  Uncaught Error: Undefined constant "plain" in /usr/share/
webapps/roundcubemail/plugins/managesieve/config.inc.php:19

Arch linux:
php 8.0.1
roundcube - git master as of today.

**Comment by alecpl** [comment]
Problem is with your configuration file. I guess you've set some option to `plain`, but it should be `"plain"`.

**Comment by gene-git** [comment]
Thanks  ... the only reference I find in system configs is:

$config['imap_auth_type'] = 'PLAIN';
$config['smtp_auth_type'] = 'PLAIN';

And sending and receiving both work fine for my test profile.
I wonder if there is a sieve config for user setting somewhere triggering this.

**Comment by alecpl** [comment]
The error message states this clearly.

**Comment by gene-git** [comment]
you're absolutely right- was looking at old config - my bad - user error. Duh me.
