### ISSUE TITLE
Nothing happens when I click on the update button to migrate DB schemas

### ISSUE THREAD

**Issue by binarykitchen** [roundcube/roundcubemail#7847]
On Step 3 of the Installer nothing happens when I click on the "Update button". Here my screenshot:

<img width="412" alt="Screen Shot 2021-01-24 at 16 14 47" src="https://user-images.githubusercontent.com/177641/105620214-4bb52980-5e5f-11eb-98b8-d663f6e8103a.png">

No error is thrown in the browser console. Just nothing happens.

Really would like to run these migrations but no idea how to do these via command line if that UI is broken.

Any clues welcome.

PS: I also wonder if there is a trick to find out what version the schema version 2020020101 is coming from so that I can select the proper version to migrate from.

Thanks!

**Comment by alecpl** [comment]
The command is `bin/updatedb.sh --dir=SQL --package=roundcube`.

You say that clicking the button does not send a request to the server?

The trick to find Roundcube version from DB version is to visit https://github.com/roundcube/roundcubemail/tree/master/SQL/mysql and find a commit/ticket related to your db-version file, a ticket will have a milestone assigned.

**Comment by binarykitchen** [comment]
Thx for the quick response. Yes, no request is made at all when clicking that button. Really none. Weird.

Another bug I found is that the config page has set my skin to the value `1` instead of `elastic`. But that's not the main issue here.

Yes, the `updatedb.sh` script and your trick helped me for now. My Roundcube installation is back up running again. Hope my above two bug reports help improving stability of your installer. Cheers.

**Comment by alecpl** [comment]
Fixed.

**Comment by alecpl** [comment]
Also fixed the skin selector in 1bdcbb19d1c4.

**Comment by binarykitchen** [comment]
Nice job dude

**Comment by binarykitchen** [comment]
Afraid, there are still issues @alecpl 

```
michael.heuberger@binarykitchen /var/www/roundcube/bin ❯❯❯ php updatedb.sh --package=roundcube --dir=SQL
PHP Deprecated:  Return type of zipdownload_mbox_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/roundcube/plugins/zipdownload/zipdownload.php on line 405
PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/roundcube/program/lib/Roundcube/bootstrap.php on line 329
PHP Warning:  Undefined array key "version" in /var/www/roundcube/bin/updatedb.sh on line 39
ERROR: Specified database schema directory doesn't exist.
```

Why can't it find the database schema directory?

Second problem:
Trying to upgrade from 2021100300 to 2020122900

But the file for 2021100300 seems empty?

**Comment by binarykitchen** [comment]
Ah, I was in the wrong folder :)

**Comment by binarykitchen** [comment]
But now, nothing happens:

```
michael.heuberger@binarykitchen /var/www/roundcube ❯❯❯ php ./bin/updatedb.sh --package=roundcube --dir=SQL --version=2021100300
PHP Deprecated:  Return type of zipdownload_mbox_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/roundcube/plugins/zipdownload/zipdownload.php on line 405
PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/roundcube/program/lib/Roundcube/bootstrap.php on line 329
michael.heuberger@binarykitchen /var/www/roundcube ❯❯❯
```

And the installer still says I have the old version. Hmmm.
<img width="434" alt="Screen Shot 2022-06-21 at 11 20 23" src="https://user-images.githubusercontent.com/177641/174688124-3e4da90b-e855-49ca-8a09-c204070464f0.png">

What is missing?

**Comment by binarykitchen** [comment]
In our error log I see this line:

```
[21-Jun-2022 11:18:47 +1200]: <7k33320r> DB Error: [1062] Duplicate entry '7k33320rrj6cluuatbrivv9nq6' for key 'session.PRIMARY' (SQL Query: INSERT INTO `session` (`sess_id`, `vars`, `ip`, `changed`) VALUES ('7k33320rrj6cluuatbrivv9nq6', 'dGVtcHxiOjE7bGFuZ3VhZ2V8czo1OiJlbl9VUyI7dGFza3xzOjU6ImxvZ2luIjtza2luX2NvbmZpZ3xhOjc6e3M6MTc6InN1cHBvcnRlZF9sYXlvdXRzIjthOjE6e2k6MDtzOjEwOiJ3aWRlc2NyZWVuIjt9czoyMjoianF1ZXJ5X3VpX2NvbG9yc190aGVtZSI7czo5OiJib290c3RyYXAiO3M6MTg6ImVtYmVkX2Nzc19sb2NhdGlvbiI7czoxNzoiL3N0eWxlcy9lbWJlZC5jc3MiO3M6MTk6ImVkaXRvcl9jc3NfbG9jYXRpb24iO3M6MTc6Ii9zdHlsZXMvZW1iZWQuY3NzIjtzOjE3OiJkYXJrX21vZGVfc3VwcG9ydCI7YjoxO3M6MjY6Im1lZGlhX2Jyb3dzZXJfY3NzX2xvY2F0aW9uIjtzOjQ6Im5vbmUiO3M6MjE6ImFkZGl0aW9uYWxfbG9nb190eXBlcyI7YTozOntpOjA7czo0OiJkYXJrIjtpOjE7czo1OiJzbWFsbCI7aToyO3M6MTA6InNtYWxsLWRhcmsiO319cmVxdWVzdF90b2tlbnxzOjMyOiJKOHJjVnE4UTJhOFVIeVh2aTZRcnJkM2ZrZ1BLVUZLbiI7', '121.74.92.46', now())) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 566 (GET /installer/null)
```
There is no documentation nor GitHub issue about that. How to fix?
