### ISSUE TITLE
Mysql update SQL script 2013061000.sql appears to be bugged

### ISSUE THREAD

**Issue by MauroFoti** [roundcube/roundcubemail#7852]
When I installed roundcube version 1.4.10-complete, the last step of the installation tells me that the database schema version was outdated (version `2013052500`, requested at least `2019092900`). Keep in mind this was a clean install.

I immediately tried applying manually the various patches found in `SQL/mysql` using phpmyadmin, and the first one (`2013061000`) got an error (which right now I cannot remember). Apparently, during the installation roundcube stopped the database building at this stage and finished with an old version of the database.

To solve it I had to drop all the tables and execute mysql.initial.sql, which resulted in the correct schema (which many more tables than the one installed automatically).

**Comment by alecpl** [comment]
You mean it wasn't an upgrade? How did you install it exactly? The installer is supposed to use mysql.initial.sql, so I don't see why it would end up in an invalid state.

**Comment by MauroFoti** [comment]
I installed from scratch. I downloaded `complete` from [https://roundcube.net/download/](https://roundcube.net/download/), uploaded to my website, and followed the procedure from `/installer`

**Comment by alecpl** [comment]
In clean installation (not upgrade) this file from `SQL/mysql` is not supposed to be used at all. So, I have no idea where the issue came from. I'm unable to reproduce.
