### ISSUE TITLE
Remove support for MS SQL Server and Oracle

### ISSUE THREAD

**Issue by MarcoMiltenburg** [roundcube/roundcubemail#7854]
While performing an update I was unable to execute the MSSQL script `2019092900.sql`. Apparently it's not possible to change the collation of a column with this single query for these tables. This seems because there are primary keys and indexes on the affected colums.

The script just changes the collation on certain columns to case sensitive so I manually changed that using SQL Server Management Studio and this created per table a very big query that included the table and all its indexes to be recreated. For some tables it even required many (temporary) changes to other tables as well. So I think this needs more work and testing.

**Comment by MarcoMiltenburg** [comment]
Extra note: an example of an error that I got when e.g. `[dbo].[cache_shared]` was updated:

```
The object 'PK__cache_sh__8B49A43B0BB51763' is dependent on column 'cache_key'.
ALTER TABLE ALTER COLUMN cache_key failed because one or more objects access this column.
```

**Comment by alecpl** [comment]
We do not have a MSSQL expert here, so a PR would be appreciated. The other errors you found confirm that also Roundcube+MSSQL user-base is very very small.

**Comment by MarcoMiltenburg** [comment]
OK, I will have a look at it. Keep the PR open for now and I will add commits to it.

**Comment by alecpl** [comment]
It looks to me that dropping the PK/index before altering the column and re-creating them after should do the trick.

**Comment by alecpl** [comment]
I'm inclined to drop MSSQL support completely. I'm pretty sure that number of Roundcube on Windows with MSSQL installations is really low.

@thomascube, what do you think? I'd drop Oracle support too.

**Comment by thomascube** [comment]
@alecpl Thumbs up for dropping both. Let's announce it with the next release and look at the responses.

**Comment by alecpl** [comment]
Done.
