### ISSUE TITLE
I'm not receiving e-mails

### ISSUE THREAD

**Issue by piacente** [roundcube/roundcubemail#7857]
I have an account on Roundcube Webmail because of my work, and recently I realized I'm not receiving some e-mails. At first, I thought it was a problem with one of my co-workers but it happened with another one. I don't know what it is and what to do.
Actually, I receive some but some I don't. Both of my co-workers have an account on Roundcube Webmail as well and forwarded their e-mails more than one time and yet there's nothing there. Not even in my spam mailbox.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
