### ISSUE TITLE
Need help with password plugin

### ISSUE THREAD

**Issue by NicoloLazzaroni** [roundcube/roundcubemail#7858]
Hello,

I need the **password** plugin to run the bash script:
`sudo -u vmail -g mail /etc/postfix/postpassword.sh 'USER EMAIL' 'DOMAIN' 'OLDPASSWORD' 'PASSWORD'`
when a user changes the password.

I could edit postfixadmin's recover-pw for doing this job on recover password, but have no idea on how I could change a roundcube plugin.

I tried some changes, but without any luck.

What could I do?

Thank you

Best Regards

**Comment by alecpl** [comment]
Ask on mailing list or forum.
