### ISSUE TITLE
5975742 breaks support for some Dovecot forwarding parameters

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#7860]
Dovecot supports a selection of parameters for connection [forwarding](https://wiki.dovecot.org/Design/ParameterForwarding). The parameters are passed as part of the ID commend. Examples of it in use are in this [plugin](https://github.com/corbosman/dovecot_ident) and also some discussion in #5336.

I understand that 5975742 was done as sending the ID command before auth caused problems in one use case but it is useful in another use case. Could the change be amended to allow plugins to send the ID command before authentication when required?

**Comment by alecpl** [comment]
Right. Let's create an extra argument to the storage_connect hook, e.g. 'preauth_ident'. I'm not sure it should be boolean flag that will move the existing ID command earlier, or maybe a set of separate ID parameters to use for an additional ID command call.

**Comment by alecpl** [comment]
Fix merged.
