### ISSUE TITLE
Feature request:  exporting and importing of identities

### ISSUE THREAD

**Issue by davidmbesonen** [roundcube/roundcubemail#7861]
There doesn't appear to be a facility that allows for the exporting and importing of identities on a per mailbox basis.

Would creating this feature be a major undertaking?

And in the meantime, are there any recommended techniques for accomplishing this?

**Comment by alecpl** [comment]
Should be possible with a plugin api. I don't think it makes much sense in core.

**Comment by thomascube** [comment]
What exactly is the intended use-case for this? Transfer to another Roundcube system? There's no standard format for identities that would the exchange with other email systems or programs.

**Comment by GOC117** [comment]
In my case it would be necessary to move identities from one hosting provider to another and an API plugin would not be a solution since I am not and would never be authorized to install it on my hosting provider's servers.
