### ISSUE TITLE
$config[] not populated on login, session_lifetime not being applied to cookie, hard coded 0.

### ISSUE THREAD

**Issue by ghost** [roundcube/roundcubemail#7865]
While trouble shooting why the session cookie being sent to the browser always had "expires: session" (until browser closed) i found in
`program/lib/Roundcube/rcube_session.php`
the line
`rcube_utils::setcookie($this->cookiename, $this->cookie, 0);`
which always sets login session cookie expires to "0" when browser closes. I tried to replace the 0 with
`rcube_utils::setcookie($this->cookiename, $this->cookie, time() + ($config['session_lifetime']*60) );`
and found out that none of the $config[] values are set at this point in PHP execution.

Could Roundcube ensure that $config[] values are defined before this part of code runs and remove the hard coded "0" otherwise what is the point of even having $config['session_lifetime']?

Thank you :)

**Comment by villageadmin** [comment]
**UPDATE**

After hard coding a number in the above example as a temp fix, i notice it only updated the auth cookie but the session cookie was still expiring at end of session / browser close. I dug around some more and found in
`program/lib/Roundcube/rcube.php`
the following two lines
`
// set session cookie lifetime so it never expires (#5961)
ini_set('session.cookie_lifetime', 0);
`
However per /etc/php.ini 0 expires at end of session, not unlimited lifetime. I do not know if it was changed to 0 for policy reasons and they did not update the comment statement, or if they misunderstood what `0` does.

Again at that point in PHP execution the $config[] var is not set so i had to hard code a number in there. It would be nice to have the $config[] populated and used in both of these locations to make $config['session_lifetime'] actually do what it claims to do.

**Comment by alecpl** [comment]
You should take a look at #7709.

**Comment by villageadmin** [comment]
I read over #7709 and #5050 and understand that im late to the party. However i don't understand after reading them what is roundcube's position on the matter? Am i misunderstanding the purpose of `$config['session_lifetime']`? Is this something being addressed and "fixed" or does roundcube want `= 0` to be the norm?

**Comment by alecpl** [comment]
I want `0` to be the norm, and I'm not yet sure I would want to support the config option for this.

**Comment by villageadmin** [comment]
So i can get an understanding of the mindset of roundcube and if you don't mind answering...

Why would roundcube remove the config option and not let people make the choice for themselves how they want to run their system? Why does roundcube care if someone want to leave themselves logged in for 100 years on their own email server?

I understand if someone guesses or steals my cookie they can hijack the session just the same as if someone guesses or steals my password they can logging to my account.

Are the cookies sent over SSL to avoid eavesdropping? If that is the concern someone can eavesdrop live and login while im logged in. Even with keeping cookie = 0 if they keep their browser open they can maintain access to my account even after i close my browser. So what is the `0` accomplishing?
