### ISSUE TITLE
Uncaught Error: Call to undefined method rcube_config::load()

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7867]
Getting:

[31-Jan-2021 20:53:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method rcube_config::load() in /var/www/roundcube/program/lib/Roundcube/rcube_config.php:94
Stack trace:
#0 /var/www/roundcube/program/lib/Roundcube/rcube.php(117): rcube_config->__construct()
#1 /var/www/roundcube/program/include/rcmail.php(76): rcube->__construct()
#2 /var/www/roundcube/index.php(43): rcmail::get_instance()
#3 {main}
  thrown in /var/www/roundcube/program/lib/Roundcube/rcube_config.php on line 94

When trying to load roundcube (HTTP 500) - PHP7.4

**Comment by alecpl** [comment]
Strange. The method exists. https://github.com/roundcube/roundcubemail/blob/d16f3a8f1feaa26504009e7b0e9653aae449b440/program/lib/Roundcube/rcube_config.php#L201

What version?

**Comment by jedvod** [comment]
seems this error went away overnight somehow. Not sure what happened.
