### ISSUE TITLE
Roundcube Installer: File not found on further steps

### ISSUE THREAD

**Issue by GivouDev** [roundcube/roundcubemail#7868]
Hey,

im trying to install Roundcube for my mailcow instance. I followed the introductions, but whether I install it with the roundcube docs or the mailcow docs, the installer fails after i click next with "File not found".

I also havent found any logs for this error :(

Please help.

Thanks,
Thiemo

**Comment by GivouDev** [comment]
Okay, ive found the error: 
2021/02/01 13:00:35 [error] 9365#9365: *622 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 77.117.177.248, server: mailserver.*****.at, request: "GET /rc/installer/index.php?_step=3 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "mailserver.******.at", referrer: "https://mailserver.******.at/"

Thats my nginx config: https://paste.bka.li/view/752e8965

**Comment by alecpl** [comment]
Nginx setup is out of scope of this issue tracker.
