### ISSUE TITLE
Massive profile pictures on every email after updating to 1.5-Git

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7870]
Please see example below:
![2021-02-01 20_38_55](https://user-images.githubusercontent.com/59712443/106515514-b6084280-64cd-11eb-8b37-4528c684283a.png)

Is this by-design?

I have to scroll down past the massive profile icon after updating to the Git version. Let's say as an example, the entire body of the email in the set font-size would fit into a text box the size of the profile icon displayed.

Any thoughts on this would be appreciated.

**Comment by alecpl** [comment]
I'm guessing you have the same story with css files as with js. The git version requires some tools to be executed, e.g. to compile Elastic skin less into css.

**Comment by lordjoo** [comment]
I'm having the same issue, any solutions for it ?
