### ISSUE TITLE
Force loading all resources over a secure HTTPS connection.

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7871]
I'm getting mixed security warnings about e.g. email content loading an image from http://website.com

Please can you enforce/add config option to force loading all resources over a secure HTTPS connection?

I have already enabled the configuration:  $config['force_https'] = true;
but this doesn't seem to force HTTP for all resources.

Thoughts / enhancement request raised would be appreciated.

Thanks

**Comment by jedvod** [comment]
something like:
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">

**Comment by jedvod** [comment]
Note that the work-around is to add the header into .htaccess file, but for others to easy-install this with maximum security, it should be added to the relevant pages via hard-code.

**Comment by alecpl** [comment]
I don't think purpose of this CSP rule is as you expect. For this you'd rather need a proxy which was already discussed in a couple of tickets. We always close such tickets. Write a plugin.

**Comment by thomascube** [comment]
Related to #7833
