### ISSUE TITLE
[Elastic] icon highligting not changing with selection

### ISSUE THREAD

**Issue by ford--prefect** [roundcube/roundcubemail#7872]
With roundcube 1.4.10 on php 7.4.13 (and also for quite a while now), the beautiful new Elastic skin does not display as I would expect:
The following picture shows the upper left corner of the roundcube interface while browsing to settings (sorry for not switching locale). While the _settings_ button appears activated with a lighter grey background, the main graphical emphasis (blue icon) is still on _compose_. This persists also when going to contacts or inbox.
![rc](https://user-images.githubusercontent.com/7083300/106611850-b9044100-6568-11eb-919c-2e8d14f58063.PNG)

In my opinion, the blue icon should shift along with the grey highlight, to make more visually clear which mode is activated.

**Comment by alecpl** [comment]
This is intended. As you see blue is not used as a "selection" color in the menu.

**Comment by ford--prefect** [comment]
Ok, thanks for the quick reply.
What is the point of the blue highlighting then?

**Comment by alecpl** [comment]
Being special.
