### ISSUE TITLE
Question: Link to specific section in preferences?

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#7873]
Is there a way to open a specific section in preferences with a link or any other way from a plugin?

If i use ?_task=settings&_action=preferences it opens the settings page at the correct site, but additionally, i would open a specific section like "Contacts". Is there some way?

**Comment by alecpl** [comment]
Nope. You have to click the row programmatically.

**Comment by Offerel** [comment]
Ok many thx. I try to use a workaround and open a small popup with the url set to `?_task=settings&_action=edit-prefs&_section=pluginname&_framed=1`. Now i have only to find a way to close the popup after clicking on save, instead of opening settings in fullscreen. But basically it works

**Comment by Offerel** [comment]
Sorry to bother you again. I try now another workaround. I call the settings page with the url  
`?task=settings&_action=preferences#myplugin`. In he plugin.js i parse the url, if a hash with `#myplugin` exists. If that's the case, i try to click with `document.getElementById('rcmrowmyplugin').click()` on the row, to open the needed page. It finds the row, but the click event seems todo nothing. I didnt see any other event on that row either. ANy idea?

**Comment by alecpl** [comment]
Try 'mouseup'.

**Comment by alecpl** [comment]
... or rcmail.sections_list.select_row('myplugin'). Also make sure to do this after the 'init' event.

**Comment by Offerel** [comment]
The last one is working great! Nice... I have made a push at https://github.com/Offerel/roundcube_primitivenotes/commit/f8c68a2a2e39b43e1a30fd68f80b54624c12c0ca, if you are interested. I mentioned you in the changelog.
