### ISSUE TITLE
"Keep me logged in" Refresh will reset the view

### ISSUE THREAD

**Issue by merc74** [roundcube/roundcubemail#7874]
When logging in and choosing: "Keep me logged in" 
It will keep you logged in but when the page refresh it reset to this. It does this with any of the interfaces (Classic, Elastic or Larry).
![image](https://user-images.githubusercontent.com/75846421/107057362-5fd32200-67a1-11eb-9cc1-51e5348179df.png)

**Comment by alecpl** [comment]
There's no such thing as "Keep me logged in" in Roundcube. Probably a plugin we do not support.

**Comment by merc74** [comment]
This is a plugin on the login page?

![image](https://user-images.githubusercontent.com/75846421/107072721-61f2ac00-67b4-11eb-8128-d8648ffe472f.png)

**Comment by alecpl** [comment]
Yes.

**Comment by gianlucagiacometti** [comment]
It's called: persistent_login
