### ISSUE TITLE
Ensure that configurations are kept upon upgrade

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7875]
I've had to re-set many of my configuration items after upgrading from 1.4.10 to 1.5-Git

Please could the upgrade script ensure that parameters are kept?

Thanks

**Comment by alecpl** [comment]
Could you be more specific? Which items exactly? What was the value before and after? And which 1.5-git version?

Did you use bin/update.sh script? Did you answer yes to "Do you want me to fix your local configuration? (y/N)" question?
