### ISSUE TITLE
PHP Error: Can use only one plugin for attachments/file uploads! Using 'database_attachments',

### ISSUE THREAD

**Issue by charmnQuark** [roundcube/roundcubemail#7878]
Hi guys, I have my plugin configuration as below.

`$config['plugins'] = array('acl', 'managesieve', 'additional_message_headers', 'automatic_addressbook', 'archive', 'attachment_reminder', 'autologon', 'database_attachments', 'debug_logger', 'emoticons', 'filesystem_attachments', 'help', 'hide_blockquote', 'http_authentication', 'identicon', 'identity_select', 'new_user_dialog', 'password', 'userinfo', 'virtuser_file', 'virtuser_query', 'zipdownload');`

And this is the error I find in the error.log

> PHP Error: Can use only one plugin for attachments/file uploads! Using 'database_attachments', ignoring others. in /var/www/roundcube/plugins/filesystem_attachments/filesystem_attachments.php on line 39 (POST /?_task=mail&_action=autocomplete)

Database_attachment relies on filesystem_attachment, so why the error ?

**Comment by alecpl** [comment]
Only one should be enabled in the config.

**Comment by charmnQuark** [comment]
Got it. thanks

**Comment by Khnaz35** [comment]
Hi guys, i am having the same issue. while error says.
[23-Jun-2024 01:18:21 +0800]: <s9o9cbm0> PHP Error: Can use only one plugin for attachments/file uploads! Using 'filesystem_attachments', ignoring others. in /var/www/html/roundcubemail/plugins/filesystem_attachments/filesystem_attachments.php on line 39 (POST /?_task=mail&_action=plugin.newusersave)
[23-Jun-2024 01:18:25 +0800]: <s9o9cbm0> PHP Error: Can use only one plugin for attachments/file uploads! Using 'filesystem_attachments', ignoring others. in /var/www/html/roundcubemail/plugins/filesystem_attachments/filesystem_attachments.php on line 39 (POST /?_task=mail&_action=refresh)


my plugins are :

```
$config['plugins'] = ['acl', 'additional_message_headers', 'archive', 'attachment_reminder', 'autologon', 'autologout', 'debug_logger', 'emoticons', 'enigma', 'example_addressbook', 'filesystem_attachments', 'help', 'hide_blockquote', 'http_authentication', 'identicon', 'identity_select', 'jqueryui', 'krb_authentication', 'managesieve', 'markasjunk', 'new_user_dialog', 'new_user_identity', 'newmail_notifier', 'password', 'reconnect', 'redundant_attachments', 'show_additional_headers', 'squirrelmail_usercopy', 'subscriptions_option', 'userinfo', 'vcard_attachments', 'virtuser_file', 'virtuser_query', 'zipdownload'];

**Comment by alecpl** [comment]
Only one should be enabled in the config, filesystem_attachments or redundant_attachments.
