### ISSUE TITLE
Signatures cleared upon upgrade

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7879]
Signatures are cleared upon running the installto script for updates.

Please ensure this is not the case.

More information should be available via replication of the issue.

Thanks

**Comment by alecpl** [comment]
I'm guessing that you changed the `default_host` setting with the upgrade and that causes user records to be re-created with a different set of attributes. In this case references to identities and contacts as well would be "lost". Is this the case? If not we need more details. You didn't even bother to tell us which version did you upgrade to/from.

**Comment by jedvod** [comment]
I saw the release for 1.4.11 fixing the XSS issue and to be sure, I ensured that my configuration, (not the default file), was correct and then downloaded the repo again and ran bin/installto.sh

I was/still am on 1.5-git -- the re-installation/upgrade was probably not needed, but it did point out something I need to resolve before the next Git version is released.

I'm checking the default_host value now.

**Comment by jedvod** [comment]
default host wasn't changed. configuration.php had it set to the correct port and host with TLS connection set.

**Comment by alecpl** [comment]
Still not enough details. What database? How the installto.sh output looks like? Is the `identities` table empty or the records were orphaned (`user_id`)? Any errors in log?

**Comment by jedvod** [comment]
I'll do some testing and get back to you.

**Comment by alecpl** [comment]
No feedback.
