### ISSUE TITLE
Personalizing a mailing list

### ISSUE THREAD

**Issue by fynnwilliam** [roundcube/roundcubemail#7880]
I have been searching around for how to personalize mass email but no leads yet. I will be glad to know how to do that or help in making that possible.

Thank you.

**Comment by alecpl** [comment]
I'm not sure what exactly you are trying to achieve, but sounds like an idea for a new plugin. We're not really interested in "mass email" in core.

**Comment by fynnwilliam** [comment]
Thank you Aleksander.
