### ISSUE TITLE
Encrypting mail to send to old theBat systems

### ISSUE THREAD

**Issue by muatdip127** [roundcube/roundcubemail#7882]
Hi! How i may encript message to sent to old pgp v.2.6?
If i send the encrepted message by enigma plugin theBat old version cannot decrypt it. :(
We have error^ unknoun package format OpenPGP!

**Comment by alecpl** [comment]
But why? We don't really should, and do not care about such a use-case.

**Comment by alecpl** [comment]
If you really have to, ask the question on the GnuPG mailing list, this is really not a Roundcube question.
