### ISSUE TITLE
Outlook ICS invites not recognized

### ISSUE THREAD

**Issue by DoobleD** [roundcube/roundcubemail#7884]
When an ICS invitation is sent from an Outlook.com account, it is not recognized as an ICS invite, but rather it's just seen as a downloadable attachment.

I tested this on Roundcube 1.4.0 and 1.4.11. Any chance of looking into it?

**Comment by alecpl** [comment]
Roundcube has no calendaring features in core. If you're using some calendar plugin we do not support it.
