### ISSUE TITLE
error on roundcube load when session.auto_start has been enabled

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7887]
ERROR: Wrong 'session.auto_start' option value and it wasn't possible to set it to required value (Off). Check your PHP configuration (including php_admin_flag).

Getting the above error when php.ini includes:
session.auto_start = 1

this error is not showing with any other websites hosted on my server.

Please advise.

Thanks

**Comment by alecpl** [comment]
It is a required setting.
