### ISSUE TITLE
 Progressive Web App plugin

### ISSUE THREAD

**Issue by jonmoesli** [roundcube/roundcubemail#7888]
Hi,

the kolab repo (https://git.kolab.org/diffusion/RPK/browse/dev%252Fpwa/plugins/pwa) seems abandoned.
Is there a plan to add it as official plugin?

Thanks

**Comment by alecpl** [comment]
The repo is not abandoned, but no one is working on the plugin. I doubt if moving it somewhere else will bring more developers. I don't plan to make it a core plugin, not until it's finished and I don't have time to do it.
