### ISSUE TITLE
Elastic: Send button positioning

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#7889]
In most other mail editors, including Roundcube with larry skin, the send button is in the main toolbar. Can the send button please moved from the bottom in Elastic skin moved to the main toolbar? Best would be as first icon before the Save button.

**Comment by alecpl** [comment]
Nope.

**Comment by Offerel** [comment]
Ok, no prob. I created a plugin for this at: https://github.com/Offerel/roundcube_elasticext
