### ISSUE TITLE
Add Attribute autocomplete="off" To Every Input

### ISSUE THREAD

**Issue by jacobsammon** [roundcube/roundcubemail#7894]
How can I add the attribute autocomplete="off" to the input tags of any form?

I'm using the skin elastic if that helps!

This would mean I would stop getting recommended, for example, past subjects when composing new emails:

![image](https://user-images.githubusercontent.com/75087999/108495239-7482e000-72a0-11eb-868e-d0f2cb676f6b.png)

**Comment by alecpl** [comment]
You can't.

**Comment by jacobsammon** [comment]
Is there a way for me to find the actual input just for the subject and add the attribute to this, or not?
