### ISSUE TITLE
ALL UNDELETED NOT UID: Missing parameter for search key (for search key: UID)

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7895]
Hi,

Roundcube Version 1.4.11

I got another (rare?) error in my logs:

```
UID SEARCH: Error in IMAP command UID SEARCH: Missing parameter for search key (for search key: UID)
```

_action ist `list` and _task is `_mail`

The command sent to the IMAP server is

```
ALL UNDELETED NOT UID
```

which is missing the UIDs at the end of it.

The stacktrace would be

```
#7 /program/lib/Roundcube/rcube_imap_generic.php(1979): rcube_imap_generic::search
#6 /program/lib/Roundcube/rcube_imap.php(1683): rcube_imap::search_once
#5 /program/lib/Roundcube/rcube_imap_cache.php(1000): rcube_imap_cache::validate
#4 /program/lib/Roundcube/rcube_imap_cache.php(1176): rcube_imap_cache::synchronize
#3 /program/lib/Roundcube/rcube_imap.php(3809): rcube_imap::folder_sync
#2 /program/steps/mail/list.inc(65): include_once
#1 /index.php(306): include
#0 /public_html/index.php(26): null
```

I looked through the code at `rcube_imap_generic::compressMessageSet` and `rcube_imap_cache::validate`: The regex used allows for an empty `$result` and will not return `INVALID` in that case. Maybe there should be a check somewhere in `rcube_imap_cache::validate` for the return value of  `rcube_imap_generic::compressMessageSet` being empty or (if changed) `INVALID`?

**Comment by alecpl** [comment]
Fixed.
