### ISSUE TITLE
Recipient with errant period in address fails in non-obvious way when trying to send

### ISSUE THREAD

**Issue by khaytsus** [roundcube/roundcubemail#7899]
I mistakenly copied "user@domain.com." with a trailing period into Roundcube and even though it looks okay in the Compose view, it wouldn't send with a "Please enter at least one recipient" popup.  It wasn't until I copied and pasted the email outside of Roundcube was it obvious that there was an errant period at the end of the email address.  Removing this and re-pasting or re-typing it in and everything was fine.

It would be nice if Roundcube handled this in some way, such as not "pretty" formatting the email as such if it thinks the email is invalid.

I am using Roundcube 1.4.11 on CentOS 7.

Reproduction steps:

1. Compose email to any valid email, but append a period at the end of the email either by pasting in such an email or typing it in with the trailing period
2. Note that the Roundcube UI makes it appear as if the email is valid by formatting it, "x" button to remove it, etc
3. Attempt to send the email

Thank you for the excellent webmail, I have used it for many years now and appreciate you continuing to support and improve it!

**Comment by alecpl** [comment]
Fixed.
