### ISSUE TITLE
Virtualmin Drivers not work with error 

### ISSUE THREAD

**Issue by chrystophe** [roundcube/roundcubemail#7900]
Hello,

I use identifiers in the form username@domain
when I validate the password change I get the following error: 
`No user named "username-domain-with-dash.fr" was found in the server "domain-with-dash.fr"`
The problem is that if I integrate a code of this type: 
`$username = escapeshellcmd(str_replace('-'.$domain, '@'.$domain, $username));`
my error becomes: 
`No user named "username@domain@avec@tiret.fr" was found in the server "domain-with-username.fr"`
I'm using the latest online version of the virtualmin drivers and Roundcube version: 1.4.11
could you try to help me?
I will be grateful to you !

**Comment by alecpl** [comment]
There's no virtualmin experts here. What is the username in Roundcube and what is the username and domain in virtualmin? What is the working command to change the password?

**Comment by alecpl** [comment]
No feedback.
