### ISSUE TITLE
composer.json: "GPL-3.0+ is deprecated"

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7901]
Hi,

using `composer validate --strict` on the provided `composer.json` gives the following warning:

```
./composer.json is valid, but with a few warnings
See https://getcomposer.org/doc/04-schema.md for details on the schema
License "GPL-3.0+" is a deprecated SPDX license identifier, use "GPL-3.0-or-later" instead
```

`GPL-3.0+` is deprecated, see https://spdx.org/licenses/ at the bottom of the page. This causes the command to fail with an errorcode `1` which causes a build to fail if used in CI. 

Could that be easily changed?

**Comment by alecpl** [comment]
Fixed.
