### ISSUE TITLE
Duplicated Emails

### ISSUE THREAD

**Issue by glasiore** [roundcube/roundcubemail#7903]
Hello guys. I can't send e-mail or receive e-mails. 

When I try to send an e-mail, Roundcube Webmail says "sending" at the right buttom side but at the end it gives an error. "The request has timed out." and another one next to it "SMTP Problem: [-1]"

But sometimes I get duplicated mails, 5 in a row or couple more times. What could cause this?

**Comment by alecpl** [comment]
Does not sound like a Roundcube bug. Ask on mailing list or forum.

**Comment by thomascube** [comment]
I'm sorry but you wrote to the wrong people. We don't host your e-mails and we're not responsible for the system you're using to access them. Please contact your internet hosting provider for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Please note that Roundcube is not a service but free software which your hosting provider installed on their servers.
