### ISSUE TITLE
Guzzlehttp\client NOT OK on 1.5 update from 1.4

### ISSUE THREAD

**Issue by Faillinx** [roundcube/roundcubemail#7904]
Attempting to test 1.5 google oauth integration before we need this app working again, I ran the upgrade instructions in the roundcube master. When I go to the installer it does not allow me to proceed as Guzzlehttp\client: NOT OK. 
Apologies for not being a dev, I attempted to install guzzlehttp from its instructions, but I can't seam to figure that out. 
Unsure where to report this or find assistance.

**Comment by alecpl** [comment]
Install composer, and then run `composer update` or `composer install`. Or wait a few days for 1.5-beta release.

**Comment by Faillinx** [comment]
Thank you. I didn't see that 1.5 beta was coming. I'll check back next week for that code.
