### ISSUE TITLE
Unmet dependencies: php* < 8

### ISSUE THREAD

**Issue by thompol** [roundcube/roundcubemail#7906]
When installing Roundcube 1.4.11 from the buster-backports repo on Debian 10, it depends on php modules < PHP 8.0. When using the Sury repo, php-cli and others are PHP 8. I do have PHP 7.3 installed with the necessary modules, so I think that a dependency on php7.3-cli, php7.3-intl, etc should be sufficient.

Command output:

`apt-get install roundcube/buster-backports roundcube-core/buster-backports roundcube-mysql/buster-backports roundcube-plugins/buster-backports` \
`Reading package lists... Done` \
`Building dependency tree       ` \
`Reading state information... Done` \
`Selected version '1.4.11+dfsg.1-2~bpo10+1' (Debian Backports:buster-backports [all]) for 'roundcube'` \
`Selected version '1.4.11+dfsg.1-2~bpo10+1' (Debian Backports:buster-backports [all]) for 'roundcube-core'` \
`Selected version '1.4.11+dfsg.1-2~bpo10+1' (Debian Backports:buster-backports [all]) for 'roundcube-mysql'` \
`Selected version '1.4.11+dfsg.1-2~bpo10+1' (Debian Backports:buster-backports [all]) for 'roundcube-plugins'` \
`Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.` \
`The following information may help to resolve the situation:`

`The following packages have unmet dependencies:` \
`roundcube-core : Depends: libapache2-mod-php (< 2:8.0~) or` \
`                           php (< 2:8.0~)` \
`                  Depends: php-cli (< 2:8.0~)` \
`                  Depends: php-intl (< 2:8.0~)` \
`                  Depends: php-json (< 2:8.0~)` \
`                  Depends: php-mbstring (< 2:8.0~)` \
`E: Unable to correct problems, you have held broken packages.` \

**Comment by alecpl** [comment]
We do not support distribution packages here.

**Comment by thompol** [comment]
Who should I contact for this?

**Comment by alecpl** [comment]
The package maintainer, whoever it is.

**Comment by thompol** [comment]
Alright, thanks.

**Comment by thompol** [comment]
For anyone that might be wondering what the outcome of this was, see https://www.howtoforge.com/community/threads/roundcube-1-4-11-and-multiple-php-versions.86397/#post-419002 and the comment after that.
