### ISSUE TITLE
Password with § fails to login

### ISSUE THREAD

**Issue by cyberb** [roundcube/roundcubemail#7913]
Login fails when I am using § in my password.
As I understand login form uses form data post which encodes '§' to  '%C2%A7'.
Is there any workaround for this issue?

**Comment by alecpl** [comment]
```
// Password character set, to change the password for user
// authentication or for password change operations
$config['password_charset'] = 'UTF-8';
```
It's UTF-8 by default since 1.4.

**Comment by cyberb** [comment]
perfect, thank you!
