### ISSUE TITLE
Toggle preview pane off 

### ISSUE THREAD

**Issue by fsaadah** [roundcube/roundcubemail#7917]
My webmail service provider uses Roundcube and I cannot find any way to turn preview pane off. Their documentation says that there should be an option to turn it on and off but I can't see any option for that.
There is not option in the settings and there is no option in the preview pane itself.

Any idea?

![Settings](https://user-images.githubusercontent.com/80035232/109942398-d39f1680-7cdc-11eb-82d1-2ad6d2989246.PNG)

**Comment by alecpl** [comment]
There's no such feature in the Elastic skin. It will be possible in Roundcube 1.5 with an external plugin from https://github.com/johndoh/roundcube-elasticlayouts

**Comment by fsaadah** [comment]
> There's no such feature in the Elastic skin. It will be possible in Roundcube 1.5 with an external plugin from https://github.com/johndoh/roundcube-elasticlayouts

Thanks for the reply.

I just figured that out and realized that I can switch to the "Larry" layout which is much much better :)
