### ISSUE TITLE
Enigma Keys Directory

### ISSUE THREAD

**Issue by jacobsammon** [roundcube/roundcubemail#7918]
In `/var/www/roundcube/plugins/enigma/config.inc.php.dist`, I have this set:
`// REQUIRED! Keys directory for all users.
// Must be writeable by PHP process, and not in the web server document root
$config['enigma_pgp_homedir'] = '/keys';
`
I'm trying to set /keys as the dir for my PGP keys.

I've run this command to try and sort permissions:
`sudo chown www-data:www-data /keys`

But I still get this error when trying to make keys:
"Application Error (600): Enigma plugin: Option 'enigma_pgp_homedir' not specified"

EDIT:
Since enabling the plugin I am no longer able to update my identity:
"SERVICE CURRENTLY NOT AVAILABLE!
Error No. [600]"

Any ideas?

**Comment by alecpl** [comment]
You should not edit config.inc.php.dist file, you should create a copy as config.inc.php and set your config there.
