### ISSUE TITLE
Archive folder not recognized by Outlook

### ISSUE THREAD

**Issue by rocambin** [roundcube/roundcubemail#7920]
### What actually happens
Outlook does not recognized the Archive folder currently set and does not show it.

### What is supposed to happen
Outlook should show the Archive folder set and treat it as it is (roundcube settings bellow) :
- ![settings](https://user-images.githubusercontent.com/57540556/110201568-032c5b00-7e64-11eb-9d8b-4330d474c34e.png)

### What I've tried...
- Outlook restarted ;
- Account removed and readded to Outlook.

**Comment by alecpl** [comment]
If the IMAP server support SPECIAL-USE and METADATA extensions, Roundcube will set the `\Archive` flag on the folder.

That being said, I have no idea if Outlook supports SPECIAL-USE flags.

I'm closing the ticket, until you prove there's a bug to fix.
