### ISSUE TITLE
Managesieve: Add ability to remove 'redirect' option from UI

### ISSUE THREAD

**Issue by tomsommer** [roundcube/roundcubemail#7922]
Mailservers can opt to not allow the Sieve `redirect` functionality to work, (Dovecot has `sieve_max_redirects=0`).

There is not way to hide the redirect option from the Roundcube Managesieve UI, so the option is always displayed even if the functionality is disabled.

It would be nice with a hook or plugin config option to hide/disable 'redirect' from appearing in the Roundcube UI.

**Comment by alecpl** [comment]
Implemented. Configuration as follows: `$config['managesieve_disabled_actions'] = ['redirect'];`

**Comment by the-djmaze** [comment]
@tomsommer did you also request this at MS Outlook, Thunderbird, Kmail, Imail, etc. etc.
Because there the option is still active due to RFC 5228 section 4.
