### ISSUE TITLE
Feature request -- oauth/managesieve

### ISSUE THREAD

**Issue by skug67** [roundcube/roundcubemail#7925]
Having gotten oauth to work via Keycloak, I've now discovered that when logged in that way it is no longer possible to manage vacation rules and other filters with the managesieve plugin.  Not a huge deal but would definitely be nice if that integration could survive into an oauth environment.

**Comment by Costenslayer** [comment]
@skug67 i cant seem to get things working my end what did you do to get this working ?

**Comment by skug67** [comment]
oauth config that gets me logged in is here (https://github.com/roundcube/roundcubemail/issues/7812#issuecomment-792151001).

**Comment by ibotty** [comment]
After [having patched Net_Sieve](https://github.com/pear/Net_Sieve/pull/9) (hopefully released soon), I am struggeling to find the right way to use XOAUTH2 for managesieve in roundcube.  When installing said library version it's possible to set `$config['managesieve_auth_type'] = "XOAUTH2"`, but I can't find the right way to set it automatically (analogously to smtp and imap).  There it's done in the callbacks `storage_init` and `stmp_connect`.  Is there a similar place to hook into?  I am unfortunately not familiar with roundcube code.  I could, of course, patch `plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php` directly, but that feels wrong.

**Comment by alecpl** [comment]
There's `managesieve_connect` hook with `auth_type`, `user`, `password` arguments. So, adding the required code to `rcmail_oauth` should be trivial. Use `smtp_connect` as a reference.

**Comment by alecpl** [comment]
Implemented. Requires Net_Sieve 1.4.5.
