### ISSUE TITLE
Bounce mail disappeared from sent item

### ISSUE THREAD

**Issue by rahulnikumbhe** [roundcube/roundcubemail#7926]
We have the mail policy at our mail server. If mail size is greater than our mail policy , mails gets bounce back to the user. But mail not showing in sent items so we don't have the copy of the mail for the reference. Can we achieve this ???

**Comment by Github-Citizen** [comment]
I am just guessing but i think this would be an imap/pop3 issue, nothing to do with roundcube. Like you said, you have a policy set on your mail server, not with roundcube.

**Comment by alecpl** [comment]
Ask on mailing list or forum, this is an issue tracker.
