### ISSUE TITLE
Login inside Iframe from another domain doesn't work on Chrome and Edge

### ISSUE THREAD

**Issue by alexandre9865** [roundcube/roundcubemail#7927]
First of all, I've read this other issue [here](https://github.com/roundcube/roundcubemail/issues/7697). But I'm using PHP 7.2 (I cannot upgrade it)
Second, it works fine on Firefox.

Over Edge and Chrome, I get an error 401 (Unauthorized) all the time. How can I solve it?

![image](https://user-images.githubusercontent.com/11505122/110369007-839bb900-8028-11eb-95f2-9f38e2d0e1a9.png)

**Comment by alecpl** [comment]
Try with the `allow-from <uri>` option.
```
// X-Frame-Options HTTP header value sent to prevent from Clickjacking.
// Possible values: sameorigin|deny|allow-from <uri>.
// Set to false in order to disable sending the header.
$config['x_frame_options'] = 'sameorigin';
```
Or set it to NULL and make sure X-Frame-Options header is not added by the http server.
