### ISSUE TITLE
markasjunk: Set/clear junk flag upon mark

### ISSUE THREAD

**Issue by ckastner** [roundcube/roundcubemail#7930]
Marking a message as junk works mostly as expected: the message is moved to the Junk folder, and marked as read.

However, the Junk flag is not set.

I understand that adding the flag to the UI is probably a no-go (#7063), but implicitly adding the flag on mark, resp. removing it on unmark, would seem like a reasonable thing to do, if only for consistency with other mail clients accessing the same mailbox.

Tested with 1.4.11.

**Comment by alecpl** [comment]
Please, show your markasjunk plugin config.

**Comment by alecpl** [comment]
By default messages are not being marked as read. They are marked with a Junk flag, though.

Works for me in git-master version and it also should work in 1.4.

**Comment by ckastner** [comment]
Odd, I'm seeing exactly the opposite: messages marked as read, but not as Junk.

Regardless, I wasn't aware these flags were configurable. I found the configuration elements, and they seem to work, so the issue can be closed, I guess. Thanks!

**Comment by alecpl** [comment]
So, it looks like Debian maintainers modified the defaults? Anyway, closing.

**Comment by ckastner** [comment]
> So, it looks like Debian maintainers modified the defaults?

Debian generally carries modifications to upstream as a patch series, here's the one for roundcube: (debian/patches)[https://sources.debian.org/src/roundcube/1.4.11+dfsg.1-3/debian/patches/].

At first glance, I can't really see anything that would modify this particular config, but unless I reproduce this in a clean install, I don't think this is an issue.
