### ISSUE TITLE
Select another folder - page number persists

### ISSUE THREAD

**Issue by Virinum** [roundcube/roundcubemail#7932]
Version: `1.4.11`

Steps to reproduce:
1. Select folder with pages > 1
2. Go to page > 1
3. Open an email
4. Select folder with pages = 1
5. See nothing because page number persists

I think a video will make it clear:

https://user-images.githubusercontent.com/42373861/110617370-e9598380-8195-11eb-85cd-3cc086b59f15.mp4

**Comment by alecpl** [comment]
Confirmed with git-master. The issue exists only in the List mode, i.e. with no mail preview iframe.

**Comment by alecpl** [comment]
Fixed.
