### ISSUE TITLE
mariadb 10.3 big contact list trouble!

### ISSUE THREAD

**Issue by VozhdYoda** [roundcube/roundcubemail#7933]
we have centos 7 and mariadb 10.3 
And if we have more then 50 record in contacts, we have this:

SELECT 
	COUNT(c.`contact_id`) AS rows
FROM 
	`contacts` AS c 
WHERE 
	c.`del` <> 1 
	AND c.`user_id` = '2'

Get result:

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'rows
FROM
    `contacts` AS c
WHERE
    c.`del` <> 1
    AND c.`user_id` = '2'
LI...' at line 2

If we fix alias rows like 'rows'
we have all awesome.

Fix are  in 
rcube_contacts.php

change 

            "SELECT COUNT(c.`contact_id`) AS rows ".

on

            "SELECT COUNT(c.`contact_id`) AS 'rows'".

And we got it!

**Comment by alecpl** [comment]
The issue was fixed in 1.3.0. You should upgrade.
