### ISSUE TITLE
Invalid email address

### ISSUE THREAD

**Issue by wordlesswind** [roundcube/roundcubemail#7935]
Hello there,

I have encountered a problem, I cannot add an email address to the address book.

email address: `noreply@announcements.oci.oraclecloud.com`

![屏幕截图 2021-03-11 163711](https://user-images.githubusercontent.com/9050713/110759071-2ef67900-8288-11eb-8c2e-63d57b9e4b99.png)

Roundcube Webmail version: `1.4.9`

**Comment by alecpl** [comment]
You have email_dns_check=true set, and this domain does not exist.

ps. why would you add "noreply" address to an addressbook? ;)

**Comment by wordlesswind** [comment]
> You have email_dns_check=true set, and this domain does not exist.
> 
> ps. why would you add "noreply" address to an addressbook? ;)

haha, thank you.

> ps. why would you add "noreply" address to an addressbook? ;)

It is just to display external pictures, but Roundcube Webmail does not have an independent trust list for this, and will be added to the address book by default.

![屏幕截图 2021-03-11 173342](https://user-images.githubusercontent.com/9050713/110766281-f490da00-828f-11eb-8960-dc197a79b487.png)
