### ISSUE TITLE
openpgp.min.js and Key generation error enigma

### ISSUE THREAD

**Issue by Trimilur** [roundcube/roundcubemail#7938]
<img width="406" alt="Unbenannt" src="https://user-images.githubusercontent.com/22460686/110889650-d9a18280-82ee-11eb-9cb1-e3aaf6a9df63.PNG">
As the title says the openpgp.min.js is missing and it causes for current implementations errors i.e. when you want to create the keys exactly like this error

https://github.com/roundcube/roundcubemail/issues/6315#issue-328167998 

and this error

https://github.com/roundcube/roundcubemail/issues/5631#issue-205419628

"Your webbroser doesnt support cryptography, unable to generate keypair"

I was using current Edge, Firefox, Chrome and Safari and installed pear install Crypt_GPG (1.6.4)

gpg2 2.2.12

but also not working with gpg(1)

After importing a key signing and de/encryption is actually working

openpgp.min.js is missed by the browser (404 not found)

roundcube errors.log basically says nothing, and enigma.log

> /usr/bin/gpg2 --status-fd '3' --command-fd '4' --no-secmem-warning --no-tty --no-default-keyring --no-options --no-permission-warning --exit-on-status-write-error --trust-model always --pinentry-mode loopback --ignore-time-conflict --ignore-valid-from --digest-algo 'SHA256' --s2k-digest-algo 'SHA256' --cipher-algo 'AES256' --s2k-cipher-algo 'AES256' --with-colons --with-fingerprint --with-fingerprint --fixed-list-mode --homedir '/home/**/enigma/info@*****' --list-public-keys
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: BEGIN PROCESSING
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: selecting streams
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => got 1
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: GPG output stream ready for reading
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => about to read 65536 bytes from GPG output
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => read 461 bytes
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: selecting streams
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => got 3
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: GPG output stream ready for reading
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => about to read 65536 bytes from GPG output
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => read 0 bytes
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: GPG error stream ready for reading
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => about to read 65536 bytes from GPG error
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => read 0 bytes
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: GPG status stream ready for reading
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => about to read 65536 bytes from GPG status
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: => read 0 bytes
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: END PROCESSING
> [12-Mar-2021 04:45:48 +0100]: <rc5mjmev> GPG: CLOSING GPG SUBPROCESS
> 

meine config ist:

> > // A driver to use for PGP. Default: "gnupg".
> $config['enigma_pgp_driver'] = 'gnupg';
> 
> // A driver to use for S/MIME. Default: "phpssl".
> $config['enigma_smime_driver'] = 'phpssl';
> 
> // Enables logging of enigma operations (including Crypt_GPG debug info)
> $config['enigma_debug'] = true;
> 
> // REQUIRED! Keys directory for all users.
> // Must be writeable by PHP process, and not in the web server document root
> $config['enigma_pgp_homedir'] = '/home/**/enigma';
> 
> // Location of gpg binary. By default it will be auto-detected.
> // This is also a way to force gpg2 use if there are both 1.x and 2.x on the system.
> $config['enigma_pgp_binary'] = '/usr/bin/gpg2';
> 
> // Location of gpg-agent binary. By default it will be auto-detected.
> // It's used with GnuPG 2.x.
> $config['enigma_pgp_agent'] = '/usr/bin/gpg-agent';
> 
> // Location of gpgconf binary. By default it will be auto-detected.
> // It's used with GnuPG >= 2.1.
> $config['enigma_pgp_gpgconf'] = '/usr/bin/gpgconf';
> 
> // Name of the PGP symmetric cipher algorithm.
> // Run gpg --version to see the list of supported algorithms
> $config['enigma_pgp_cipher_algo'] = 'AES256';
> 
> // Name of the PGP digest (hash) algorithm.
> // Run gpg --version to see the list of supported algorithms
> $config['enigma_pgp_digest_algo'] = 'SHA256';
> 
> // Enables multi-host environments support.
> // Enable it if you have more than one HTTP server.
> // Make sure all servers run the same GnuPG version and have time in sync.
> // Keys will be stored in SQL database (make sure max_allowed_packet
> // is big enough).
> $config['enigma_multihost'] = false;
> 
> // Enables signatures verification feature.
> $config['enigma_signatures'] = true;
> 
> // Enables messages decryption feature.
> $config['enigma_decryption'] = true;
> 
> // Enables messages encryption and signing feature.
> $config['enigma_encryption'] = true;
> 
> // Enable signing all messages by default
> $config['enigma_sign_all'] = false;
> 
> // Enable encrypting all messages by default
> $config['enigma_encrypt_all'] = false;
> 
> // Enable attaching a public key to all messages by default
> $config['enigma_attach_pubkey'] = false;
> 
> // Default for how long to store private key passwords (in minutes).
> // When set to 0 passwords will be stored for the whole session.
> $config['enigma_password_time'] = 5;
> 
> // With this option you can lock composing options
> // of the plugin forcing the user to use configured settings.
> // The array accepts: 'sign', 'encrypt', 'pubkey'.
> //
> // For example, to force your users to sign every email,
> // you should set:
> //     - enigma_sign_all     = true
> //     - enigma_options_lock = array('sign')
> //     - dont_override       = array('enigma_sign_all')
> $config['enigma_options_lock'] = array();
> 
> 
> 
> 
>

**Comment by alecpl** [comment]
Is this maybe a Debian package? They removed the file because licensing issue. We do not support distribution packages here. Normally the file is included, and if not it can be installed with bin/install-jsdeps.sh script.

**Comment by Trimilur** [comment]
The file is not even in the official git repository and the install-jsdeps.sh is not working for me cause of wrong database driver

**Comment by alecpl** [comment]
You can find it also in the "complete" package from https://roundcube.net/download/
