### ISSUE TITLE
Problem accessing Yahoo APIs

### ISSUE THREAD

**Issue by teodor-k96** [roundcube/roundcubemail#7940]
I am trying to configure Roundcube 1.5 beta version with Yahoo mail APIs through OAuth2, so I created an app in yahoo developer console, then added the _'client_id_' & _'client_secret'_ they provided to config file. In the _'oauth_scope'_ I included all the needed permissions to access their APIs, and tried different variations, but the result is still the same, ending with following error: 

> **_Developers: Please request scope from registered scopes and submit again._**

Is this a bug in their APIs scopes or do I configure it wrong?

These are some images, related to my configuration:

![yahoo error](https://user-images.githubusercontent.com/51955652/110942198-26627900-8342-11eb-98f3-9a04a6ef9423.png)

![yahoo app](https://user-images.githubusercontent.com/51955652/110942535-983ac280-8342-11eb-8044-b03f424da170.png)

![yahoo mozilla errors](https://user-images.githubusercontent.com/51955652/110942991-4c3c4d80-8343-11eb-846c-4f8385bea958.png)

![mozilla network yahoo](https://user-images.githubusercontent.com/51955652/110943688-2ebbb380-8344-11eb-8c95-a059be19a333.png)

And this is my config settings:

```
// Enable OAuth2 by defining a provider. Use 'generic' here
$config['oauth_provider'] = 'yahoo';
// Provider name to be displayed on the login button
$config['oauth_provider_name'] = 'Yahoo';
// Mandatory: OAuth client ID for your Roundcube installation
$config['oauth_client_id'] = '----';
// Mandatory: OAuth client secret
$config['oauth_client_secret'] = '----';
// Mandatory: URI for OAuth user authentication (redirect)
$config['oauth_auth_uri'] = 'https://api.login.yahoo.com/oauth2/request_auth';
// Mandatory: Endpoint for OAuth authentication requests (server-to-server)
$config['oauth_token_uri'] = 'https://api.login.yahoo.com/oauth2/get_token';
// Optional: Endpoint to query user identity if not provided in auth response
$config['oauth_identity_uri'] = 'https://api.login.yahoo.com/openid/v1/userinfo'
// Optional: disable SSL certificate check on HTTP requests to OAuth server
// See http://docs.guzzlephp.org/en/stable/request-options.html#verify for possible values
$config['oauth_verify_peer'] = true;
// Mandatory: OAuth scopes to request (space-separated string)
$config['oauth_scope'] = 'openid mail-r sdct-w mail-w email profile';
// Optional: additional query parameters to send with login request (hash array)
$config['oauth_auth_parameters'] = ['nonce' => mt_rand(), 'access_type' => 'offline', 'prompt' => 'consent'];
// Optional: array of field names used to resolve the username within the identity information
$config['oauth_identity_fields'] = null;
// Boolean: automatically redirect to OAuth login when opening Roundcube without a valid session
$config['oauth_login_redirect'] = true;
```

**Comment by alecpl** [comment]
Looks like a problem with scopes. I suggest removing Relationships permission in the UI and slimming down the oauth_scope list.

Also, you use `mail-r` and `mail-w`, but I don't see this in the UI. So, it might also be wrong around these. Note that I'm not a Yahoo user.

**Comment by thomascube** [comment]
As far as I know, Yahoo doesn't allow the `mail-r` and `mail-w` scopes for arbitrary apps. You need to explicitly request them to be added to your app registration by sending a support request to Yahoo. Unfortunately I can't find the page that explains the procedure or the link to the request form. Also see https://stackoverflow.com/questions/59587534/how-to-enable-mail-r-scope-for-yahoo-developer-account

However, this is not a Roundcube issue and we can't help you here.
