### ISSUE TITLE
Enigma Plugin Needs Warning

### ISSUE THREAD

**Issue by icode797** [roundcube/roundcubemail#7941]
The enigma plugin is confusing because it stores the user's private key on the server. It is sometimes used with mail providers which users do not necessarily trust, so it should have a small warning when users create or import keys that says that private keys will be stored on the server.

**Comment by alecpl** [comment]
I guess we could add such a warning on the key creation page and import dialog.

**Comment by icode797** [comment]
> I guess we could add such a warning on the key creation page and import dialog.

Yes, that's what I'm saying. I don't know PHP so I can't really help, but I would think it would be fairly easy to add.

**Comment by alecpl** [comment]
Done.
