### ISSUE TITLE
Improvement request: TinyMCE 5

### ISSUE THREAD

**Issue by markholland83** [roundcube/roundcubemail#7946]
Hi!

[There were ](https://kolabian.wordpress.com/2019/05/23/tinymce-5/)some drawbacks to TinyMCE 5 back in 2019. It seems most of those have been [addressed](https://github.com/tinymce/tinymce/issues/created_by/alecpl).

Can someone shed some light on what needs to be done to ship a future Roundcube version with TinyMCE 5?

Regards,
Mark

**Comment by alecpl** [comment]
Not going to happen in Roundcube 1.4. Already done in Roundcube 1.5.

**Comment by markholland83** [comment]
Great to know that this will be happening in 1.5, thanks!
