### ISSUE TITLE
Limit the number of new emails and delete old ones

### ISSUE THREAD

**Issue by zxcvqwerasdf** [roundcube/roundcubemail#7947]
What's the best method to do it?
Maybe there is complete plugin or whatever?
I need to limit new emails and if it number reached => delete oldest.
Like i set limit to 50.
There is new the 51th emails, i need to delete one of the oldest, if there is 55 emails, i need delete 5 oldest and etc.
Thank you.

**Comment by alecpl** [comment]
Sounds like a retention policy, so a duplicate of #5029.
