### ISSUE TITLE
Dark theme background is too bright

### ISSUE THREAD

**Issue by mimi89999** [roundcube/roundcubemail#7951]
Hello,
I think that the dark theme background in 1.5-beta is too bright. I think that it would be nice to change it to something like `#121212`. The interface would look like this:
![Screenshot_2021-03-16 (1946) XIV LO Webmail Junk](https://user-images.githubusercontent.com/8530546/111379553-8f7c2080-86a3-11eb-88c3-5d68c4c139f7.png)

**Comment by thomascube** [comment]
I think this is a matter of taste. You can adjust the colors and re-compile your elastic theme. See [README.md](https://github.com/roundcube/roundcubemail/tree/master/skins/elastic#for-developers) and color variables in [colors.less](https://github.com/roundcube/roundcubemail/blob/master/skins/elastic/styles/colors.less#L219).

**Comment by mimi89999** [comment]
I think that it's also an accessibility issue. Some users has issues with the theme before I adjusted colors.
