### ISSUE TITLE
Active Sync

### ISSUE THREAD

**Issue by debasis981** [roundcube/roundcubemail#7953]
Hi team, Help me regarding active sync.
I have setup roundcube webmail on a linux server.I want to know how  to setup the server for the active sync so that i can sync all the mails and contact to the andriod phone.Please help

**Comment by alecpl** [comment]
Roundcube is an IMAP client. For ActiveSync support you have to install a server software e.g. Kolab.

**Comment by debasis981** [comment]
ok.thanks for your response.Can you share some link how to setup active sync.???

**Comment by debasis981** [comment]
> Roundcube is an IMAP client. For ActiveSync support you have to install a server software e.g. Kolab.

In this case we will setup kolab full package(setup-kolab )or kolab-synctron???

**Comment by alecpl** [comment]
Again, there's no such thing as ActiveSync for Roundcube. You can't use kolab-syncroton without the rest of Kolab.
