### ISSUE TITLE
Not possible to sent return receipt confirmation

### ISSUE THREAD

**Issue by batpets** [roundcube/roundcubemail#7954]
Hi all, I have strange problem with Roundcube 1.4.10. When sender of the e-mail wants a return receipt, a dialog box is opened right after you open the e-mail. But when you click to confirm receipt, then the following error appears:

**user@domain rejected after DATA: Your FROM address (  , user@domain ) must match your authenticated email user ( user@domain ). Treating this as a spoofed email.**

The e-mail address is the same but it somehow adds a comma before e-mail in FROM address. I've checked on a few different cpanel servers with different accounts and domains, and the error exist also. Tried with mail client (thunderbird) and horde - works with no problems.
OS is CentOS 7, CLOUDLINUX 7.9, cpanel v94.0.3

**Comment by alecpl** [comment]
Disable all plugins. Enable smtp_debug and provide the log.

**Comment by batpets** [comment]
Sorry, but I can not disable plugins for hole server. This is what i found in logs after debuging enabled - it is not much helpful:

from errors.log:
[18-Mar-2021 11:55:39 +0100]: <e1f41220> SMTP Error: Failed to send data. [550] Your FROM address (  , user@domain ) must match your
authenticated email user ( user@domain ). Treating this as a
spoofed email. in /usr/local/cpanel/base/3rdparty/roundcube/program/lib/Roundcube/rcube.php on line 1702 (POST /cpsess3071398774/3rdparty/roundcube/index.php?_task=mail&_framed=1&_action=sendmdn)

**Comment by alecpl** [comment]
This is not very helpful. I'll not be able to help you with the issue if you don't help to track it. Looking at Roundcube code I don't see how that could happen. So, I suspect some plugin might be interfering.

What PHP version? What plugins are you using?

**Comment by batpets** [comment]
php version is 7.3.26
![roundcube_info](https://user-images.githubusercontent.com/80885855/111635427-2362ff00-8800-11eb-8e73-b89095bc0715.png)

**Comment by alecpl** [comment]
Could you add `rcube::console($identity);` in line https://github.com/roundcube/roundcubemail/blob/d0dccc706670f28914a27117b563f82ab5c0360f/program/steps/mail/func.inc#L1480 and provide what it logs into the logs/console.log file?

Also, enable smtp_debug and provide the log from logs/smtp.log.

**Comment by alecpl** [comment]
No feedback.
