### ISSUE TITLE
Auto add email addresses to contacts

### ISSUE THREAD

**Issue by test2a** [roundcube/roundcubemail#7960]
Hi. I am new to roundcube email as I have been running mailinabox for 2 months now.
Its been working great but one thing I've found lacking is, unless I manually add email addresses as contacts, they dont auto fill when I write an email. 

Say I get an email from ABC@NCI.com
If I write an email to this address next time, that email "should" show up because that is how other webmails do it. Yahoomail or gmail.

Today I had to send a bunch of emails to a particular email and I had to type the full email every time all because I hadn't added that address to contact list first.

**Comment by alecpl** [comment]
"Collected Recipients" feature has been implemented in Roundcube 1.5. For older versions there were some plugins, but I've never used them.
