### ISSUE TITLE
Allow remote resources and add user to trusted senders

### ISSUE THREAD

**Issue by jedvod** [roundcube/roundcubemail#7961]
Hi,

I'm sure, previously, that there was at least the option to allow remote resources and add the sender to trusted senders list, but I'm not seeing this anymore. Has this turned into a configuration, as I'm not seeing it under settings -> contacts, either.

Is this still a feature? In an ideal situation, there would be 2 buttons, allow, (once), and allow and add to trusted senders.
(If it's bad-mail, the user can report as spam).

The below is what I see at present:

![2021-03-20 21_52_49](https://user-images.githubusercontent.com/59712443/111886694-9b2f5600-89c7-11eb-8f46-7d9a9f9c4d2e.png)

Version: 1.5-Git
Database address book storage.

**Comment by alecpl** [comment]
The extra button is visible only when "Allow remote resources (images, styles)" option is set to "from trusted senders" (show_images=1). Maybe it should also be the case for "from my contacts" (show_images=3). I'm not sure about it.

I found in the code a place where we switch values 1 and 3, so there's something to fix.

**Comment by alecpl** [comment]
Fixed.
