### ISSUE TITLE
Missing the HTML (or more) signature in the "out of office" reply

### ISSUE THREAD

**Issue by lthitor** [roundcube/roundcubemail#7962]
Hi,

I did the customizing for sending automatic replies with the filters settings. I also customized my signature in the "Identity" and specified to always use it in the "Preferences" with HTML format.

It works fine for all emails written manually. However, the automatic reply does not show the signature.

Please can you help?

Best regards,
Laurent

**Comment by alecpl** [comment]
Managesieve sevice has no idea about Roundcube user identities.

We could have an option to append the signature, but it would have to be added to the sieve script. So, it would not be updated automatically whenever the signature changes (could be done too). But for example automatic signature/identity selection based on the recipient address is not possible.

HTML vacation replies aren't possible either. I think we have a ticket for this already.
