### ISSUE TITLE
long selection lists in Elastic skin - Chrome issue

### ISSUE THREAD

**Issue by divina** [roundcube/roundcubemail#7964]
Hello,

there is a small issue in Elastic skin related to selection lists that contain a long list of items, such as Language or Time zone, and the currently selected option is in the middle of the list (not at the beginning, not at the end of the list).

When the list opens, it is scrolled too much up with the selected option only partially visible at the beginning. It seems like a Chrome issue, since in Firefox the long lists are displayed properly. See the attached screenshots.

I wonder if this could be fixed?

Thanks for you reply.
Petr

----

**Chrome**

![Snag_7d1ae36c](https://user-images.githubusercontent.com/2402217/112076754-4d5b4f00-8b7b-11eb-80bd-a15da415c1a2.png)

![Snag_7d1be20f](https://user-images.githubusercontent.com/2402217/112076833-7380ef00-8b7b-11eb-8fda-a194218030b6.png)

----

**Firefox**

![Snag_7d1baa56](https://user-images.githubusercontent.com/2402217/112076815-6b28b400-8b7b-11eb-8374-d3f36dab03ea.png)

![Snag_7d1c0f2a](https://user-images.githubusercontent.com/2402217/112076850-7aa7fd00-8b7b-11eb-9a94-b57ec1c7744d.png)

**Comment by alecpl** [comment]
Looks that the scroll positioning logic we have is needed for Firefox, but not Chrome.

**Comment by alecpl** [comment]
Fixed.
