### ISSUE TITLE
RC 1.5 beta - password plugin - hmail driver broken

### ISSUE THREAD

**Issue by sneek2020** [roundcube/roundcubemail#7966]
Hmail driver for password plugin in RC 1.5 beta (file: plugins/password/drivers/hmail.php) seems to be broken. User password in my hMail installation can't be updated anymore while it did successfully in RC 1.4.11.

Culprit seems to be some new coding in hmail.php. If I replace on line 48

`list($domain,) = explode('@', $username); `

with

```
$temparr = explode('@', $username); 	
$domain = $temparr[1]; 	
```			

it works as expected again (meaning hmail user password update is successful again).

**Comment by alecpl** [comment]
Fixed.
