### ISSUE TITLE
roundcubemail error

### ISSUE THREAD

**Issue by Blisk** [roundcube/roundcubemail#7967]
I get this error by mail all the time and didn't find any good solution, and also sieve doesn't work. Cant forward email or use any filters for emails. I use roundcubemail 1.4.9 on fedora server 33

PHP Warning:  Use of undefined constant managesieve - assumed 'managesieve' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant acl - assumed 'acl' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant additional_message_headers - assumed 'additional_message_headers' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant archive - assumed 'archive' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant attachment_reminder - assumed 'attachment_reminder' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant autologon - assumed 'autologon' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant emoticons - assumed 'emoticons' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant enigma - assumed 'enigma' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant example_addressbook - assumed 'example_addressbook' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant filesystem_attachments - assumed 'filesystem_attachments' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant identicon - assumed 'identicon' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant identity_select - assumed 'identity_select' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant jqueryui - assumed 'jqueryui' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant markasjunk - assumed 'markasjunk' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant newmail_notifier - assumed 'newmail_notifier' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant password - assumed 'password' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant redundant_attachments - assumed 'redundant_attachments' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant show_additional_headers - assumed 'show_additional_headers' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant subscriptions_option - assumed 'subscriptions_option' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant userinfo - assumed 'userinfo' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant vcard_attachments - assumed 'vcard_attachments' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84 PHP Warning:  Use of undefined constant zipdownload - assumed 'zipdownload' (this will throw an Error in a future version of PHP) in /opt/www/roundcubemail-1.4.9/config/config.inc.php on line 84
ERROR: Can use only one plugin for attachments/file uploads! Using 'filesystem_attachments', ignoring others.

**Comment by alecpl** [comment]
The strings in PHP needs to be enclosed in single or double-quotes. This should fix the warnings. The error is clear, don't configure more than one attachments handling plugin. Everything in config.inc.php on line 84.
