### ISSUE TITLE
Elastic: HTML signature checkbox is missing

### ISSUE THREAD

**Issue by llui85** [roundcube/roundcubemail#7969]
## Issue
When using the `Elastic` theme, the `HTML Signature` checkbox is missing.

Found in webmail version `1.4.9`.

## Steps to reproduce:
1. Switch to the "Classic" skin
2. Go to `Settings > Identities` and edit an identity
3. Switch to the `Signature` tab
3. Observe the "HTML signature" checkbox below the editor
4. Switch to the "Elastic" skin
5. Go to `Settings > Identities` and edit an identity
6. Observe that the checkbox "HTML Signature" is missing

## Screenshots
![A4347DC0-31FA-4272-A1C1-2BE523F4B61B](https://user-images.githubusercontent.com/47158068/112263129-e8ab0c00-8cc2-11eb-97f1-73253418db6b.jpeg)

![FC397C24-31AA-4235-A7FC-C15EAABF5265](https://user-images.githubusercontent.com/47158068/112263140-ec3e9300-8cc2-11eb-84d0-227b250f04d6.jpeg)

Taking a look at the DOM it appears that the checkbox is still present, but is hidden using an inline style.

**Comment by alecpl** [comment]
In Elastic the checkbox has been replaced with the first button in the editor/textarea toolbar.
