### ISSUE TITLE
rcmail_get_forward_header: Call to a member function get() on null

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#7970]
Hi,

The following error keeps popping up in my error logs (Roundcube 1.4.11 on PHP 7.4):

```
Error: Call to a member function get() on null
```

The stack trace is:

```
#5 /program/steps/mail/compose.inc(854): rcmail_get_forward_header
#4 /program/steps/mail/compose.inc(815): rcmail_create_forward_body
#3 /program/steps/mail/compose.inc(590): rcmail_prepare_message_body
#2 /program/steps/mail/compose.inc(265): include_once
#1 /index.php(306): include
#0 /public_html/index.php(26): null
```

_action is `compose`, _task is `mail`

Above the line this error occours on, headers are read via `$message->get_header()` but on line 854

```
if ($extended && ($cc = $message->headers->get('cc'))) {
```

`cc` is read via `$message->headers->get('cc')`. Maybe this is causing the error?

**Comment by alecpl** [comment]
Strange. Why does it not complain about `$message->headers->date` in line 822? Anyway, we should indeed use `$message->get_header()` where we deal with cc and reply-to.

**Comment by codegain** [comment]
@alecpl This confused me as well, but trying this today:

```
<?php

class Test {
	public $headers;
}

$t = new Test();
var_dump($t->headers->date);
var_dump($t->headers->get());
```

This example prints this PHP notice on the first var_dump

```
PHP Notice:  Trying to get property 'date' of non-object
```

but a runtime error on `->get()`

```
Error: Call to a member function get() on null
```

**Comment by alecpl** [comment]
Right. This notice is a warning in PHP8. So, we'll need to fix this too for git-master.

However, I'm curious why that error is possible. I see this for the first time. I'm guessing that on forwards the original message can't be fetched from imap (or the cache?) in your setup. At least that would be the case why the headers property is unset.

Also, if the headers property is not set the result of rcmail_get_forward_header() should be just an empty string. Or the case would need to be "catched" even earlier in the code path.

**Comment by alecpl** [comment]
Fixed.
