### ISSUE TITLE
Allow access to trash folder from specific IP only

### ISSUE THREAD

**Issue by RadicalRedemption** [roundcube/roundcubemail#7971]
Hello,

I need very urgently to restrict the Trash folder to specific IP address only. I still would like the deleted emails from the inbox to go to the trash, but only specific IP address to be able to view and empty the trash. I am begging for every possible help. Thanks in advance!

**Comment by sunebeck** [comment]
If there's a fire you need to put out, you could set it up in your web server config.

Block based on the URL, e.g. URLs containing `mbox=Trash`:

`/?_task=mail&_mbox=Trash`

**Comment by RadicalRedemption** [comment]
Well, i could not do it due to server settings, isn't it possible thru the roundcube core itself?

**Comment by thomascube** [comment]
Roundcube does not provide any functionality or config options for this very specific and unique requirement you have. One could start writing a plugin but this is nothing we can whip up in a short time. Also, I don't see a generic use-case or general benefit. @sunebeck's suggestion seems to be the most feasible approach for this.

**Comment by RadicalRedemption** [comment]
However i found a solution, but i have another issue now. Is it possible to disable "Server Settings" for every ronducbe user? I don't want them to be able to enable "Clear trash on logout" or something like that.

**Comment by alecpl** [comment]
Please, use mailing list or forum for such questions.
