### ISSUE TITLE
2 errors in log file

### ISSUE THREAD

**Issue by be-root** [roundcube/roundcubemail#7972]
I get two field messages in RC 1.5 beta:

1:
PHP Warning:  Undefined property: stdClass::$headers in /plugins/identity_select/identity_select.php on line 52

2:
PHP Fatal error:  Uncaught Error: Class "Mail_mime" not found in /program/include/rcmail_sendmail.php:300

Stack trace:
#0 /program/actions/mail/send.php(204): rcmail_sendmail->create_message()
#1 /program/include/rcmail.php(275): rcmail_action_mail_send->run()
#2 /index.php(279): rcmail->action_handler()
#3 {main}
  thrown in /program/include/rcmail_sendmail.php on line 300

what could be the cause of this? Thanks in advance!

**Comment by alecpl** [comment]
First issue fixed in bb583fed815. The second is a missing dependency.

**Comment by be-root** [comment]
Thank you for the reply.
Which dependency is missing and how to integrate it?

26.03.2021 08:26:18 Aleksander Machniak ***@***.***>:
