### ISSUE TITLE
Adding users to group doesn't work if elastic theme is used

### ISSUE THREAD

**Issue by scroom** [roundcube/roundcubemail#7973]
Hi,

Today I discovered an interesting bug. When I want to add multiple users to a group, it works when the group is still empty (right after creating it). If I tried this another time it didn't work anymore (green confirmation box didn't appear and users didn't show up in the group).

However, when I set the theme to Classic, adding worked again.

This is how I proceeded:
I wanted to create a meta group where all users from certain other groups are. So I created a new group, then selected the first existing group, selected all the users, and then clicked Add to Group. This worked. When I tried this with the next group, it did not work with the Elastic theme. When I changed the theme to Classic, it worked again.

I use Roundcube 1.4.11

**Comment by alecpl** [comment]
Issue confirmed. A workaround is to use drag-n-drop.

**Comment by alecpl** [comment]
Fixed.
