### ISSUE TITLE
Enigma Plugin-Key directory does not exist

### ISSUE THREAD

**Issue by kokomo123** [roundcube/roundcubemail#7977]
Hello there, I'm having some troubles setting up enigma on roundcube. I'm not sure where to properly place the directory because everytime i create the directory, place it in the config.inc.php for enigma, it always says "Key directory does not exist" Error 600 with the location, but it's clearly marked where it is, and it does exist. Not sure if its a permissions issue, but I am on the latest version of Roundcube, which is as of this writing, is 1.4.11. What permissions should it need? or im i doing it properly? 
This is on Debian 10 as a email client for Mailcow

**Comment by alecpl** [comment]
Is the path absolute or relative? That error is logged when file_exists() returns false. There's not much to say about this error.

**Comment by kokomo123** [comment]
I've been trying absolute paths, the error still persists. I've been giving it writable permissions as well, so not sure how else to put this. Relative paths may work, so not sure what's the proper way of doing it. Thanks for responding
