### ISSUE TITLE
Empty space on mail printouts in elastic skin

### ISSUE THREAD

**Issue by rahulnikumbhe** [roundcube/roundcubemail#7978]
we have refereed the workaround as mention on this page :- Fix empty space on mail printouts in Chrome (#7604)
but it didn't work for us.
we are using elastic skin.
any help would be appreciated.

**Comment by alecpl** [comment]
Elastic css have to be build after applying the change. Or just upgrade to a version with the fix.

This is not a support forum. Use mailing list or forum.
