### ISSUE TITLE
Strange limit 75Mb for attachment.

### ISSUE THREAD

**Issue by kasak87** [roundcube/roundcubemail#7979]
When writing new email, editor allows me only 75 Mb file to attach. 
But my php limits is larger. Please, have a look:
```
mx$ php-7.4 -i | egrep  'upload_max|post_max'                                                                                                                               
post_max_size => 120M => 120M
upload_max_filesize => 110M => 110M
```
and i have nothing about it in apache conf:
```
mx$ grep size roundcube.conf 
mx$ grep size ../htdocs/roundcube/.htaccess   
```
but i have limit in defaults.inc.php:
```
mx$ cat defaults.inc.php | grep message_si                                                                                                                                  
$config['max_message_size'] = '100M';
```
i've googled this and noticed that i am not only one with strange 75 Mb limit. 
My roundcube is hosted with apache, through php-fpm, maybe this is the source of issue. 
I have latest 1.4.11 version.

**Comment by alecpl** [comment]
Because attachments are base64-encoded you can't have 100MB file attached to a 100MB message. Base64-encoding adds about 30% percent to the real attachment size. So, e.g. if you want to allow 100MB attachments, set max_message_size to ~135M.

**Comment by kasak87** [comment]
Oh, thanks! That worked
