### ISSUE TITLE
Enigma Plugin: Failed to list keys, Internal Error! 

### ISSUE THREAD

**Issue by kokomo123** [roundcube/roundcubemail#7984]
Hello again,  i've been having some trouble getting the error to go away, otherwise i'm unable to do anything in PGP keys section of Roundcube. I'm using the latest roundcube release as of right now, the keys homedir is set properly and able to be written to successfully. I'm on Debian 10, and i'm hosting mailcow on it. 
Here's the logs that i've been getting from enigma_debug being on
Per /rc/logs/errors.log 
![enigma error 1](https://user-images.githubusercontent.com/70863536/113071633-26aca200-9193-11eb-8cd7-c5d49a5afd3b.PNG)
Per /rc/logs/enigma.log
![image](https://user-images.githubusercontent.com/70863536/113071625-21e7ee00-9193-11eb-8f6b-4804ddc7ac2a.png)
As per the config.inc.php for enigma, i've basically set the homedir and enigma debug to true. Nothing else i've done currently. 
Let me know if you need anything else, Thanks!

**Comment by kokomo123** [comment]
/usr/bin/gpg exists within the phpfpm container as i've installed it there. It's owned by root, but I was informed that it shouldn't have to be owned by www-data, should i try that? or something else?

**Comment by alecpl** [comment]
Yes. I'm closing this ticket as it's a deployment issue.
