### ISSUE TITLE
Missing menu bar, cannot compose emails

### ISSUE THREAD

**Issue by thebigdirty** [roundcube/roundcubemail#7985]
So after my email server upgraded to a newer fresher look I have not been able to compose emails. Fortunately I have been able to work off of just responding to people but this is getting old and turning into an issue. I have attached some screen shots of what it looks like now and for the life of me cannot find anywhere that will allow me to resolve this issue. 

Even in the Mail Configuration window it gives me basically nothing. I am not a programmer or coder, just someone who uses this email for work. Any and all help would be greatly appreciated.
<img width="1964" alt="Screen Shot 2021-04-01 at 12 26 05 PM" src="https://user-images.githubusercontent.com/81768044/113325065-e4e04080-92e5-11eb-83bc-e5cc383606f4.png">
<img width="1954" alt="Screen Shot 2021-04-01 at 12 26 23 PM" src="https://user-images.githubusercontent.com/81768044/113325069-e6116d80-92e5-11eb-83c5-47ed5198c712.png">
<img width="1962" alt="Screen Shot 2021-04-01 at 12 28 24 PM" src="https://user-images.githubusercontent.com/81768044/113325075-e7429a80-92e5-11eb-9328-e8d301341eb8.png">

**Comment by alecpl** [comment]
Mail Configuration and the whole "wrapper app" is not part of Roundcube. So, I'm afraid we'll not be able to help you. Looks like an integration issue.
