### ISSUE TITLE
Attach email to new email

### ISSUE THREAD

**Issue by rahulnikumbhe** [roundcube/roundcubemail#7988]
is this possible to attach email to new email???
it will help for the references.
any help would be appreciated.

**Comment by alecpl** [comment]
You mean "forward as attachment"? It is possible.

**Comment by rahulnikumbhe** [comment]
> You mean "forward as attachment"? It is possible.

Not exactly "forward as attachment".
For eg :- 
If we are am communicating with mail B , and if we want to add reference of mail A into mail B. By doing this it will become easy for the reference. By referring single mail both A and B mails can be referred at one place.
This is possible in outlook/o365.
Is this possible in roundcube ???
any help would be appreciated
