### ISSUE TITLE
SQL table `contacts` and the `words` column

### ISSUE THREAD

**Issue by Bill-ColeUS** [roundcube/roundcubemail#7989]
Hello,

I am migrating contacts from another system into roundcube, thus I need to insert rows directly into the SQL tables. So far everything is quite but for one thing.

In the `contacts` table, there is a `words` column

```
CREATE TABLE contacts (
  ... cut ...
  words text NOT NULL default ''
);
```

Could you please explain what this column is about?

Thank you.

**Comment by alecpl** [comment]
It is used for "fulltext" searching. You can leave it empty and then run `bin/indexcontacts.sh` to update the column.
