### ISSUE TITLE
Use independent trust lists for remote resources

### ISSUE THREAD

**Issue by wordlesswind** [roundcube/roundcubemail#7994]
Hello there,

In #7935, alecpl asked me why I want to add the "NoReply" email address to the contact list.

This is because I set the display of remote resources to **allow known senders** by default.

![Screenshot 2021-04-08 113036](https://user-images.githubusercontent.com/9050713/113964335-e23d9800-985d-11eb-8f36-51585fecbbc4.png)

My original intention was that if spam emails enter the inbox, then maybe the spam emails will contain elements for tracking.
So I chose to prevent this situation.

But for common email addresses, I hope that remote resources can be displayed by default.
So the problem arises: I have to add the "NoReply" email address to the contact list to be able to display the remote resources of the emails sent by it by default.

This resulted in almost all "NoReply" email addresses in my contact list.
![Screenshot 2021-04-08 113443](https://user-images.githubusercontent.com/9050713/113964653-8293bc80-985e-11eb-8f30-6f94a3a7e38e.png)
So can you add an independent trust list for remote resources? thanks!

Best regards,
Gentry

**Comment by alecpl** [comment]
There is Collected recipients and Trusted senders feature in 1.5-beta.
