### ISSUE TITLE
Add to contacts shortcut buttons fail with sql error

### ISSUE THREAD

**Issue by kandev** [roundcube/roundcubemail#7996]
Using 1.4.11, when I click "add to contacts" shortcut button next to senders email address or try to allow remote content for an address it fails with this error in the log:
`DB Error: [19] NOT NULL constraint failed: xxxxx_contacts.contact_id (SQL Query: INSERT INTO "xxxxx_contacts" ("user_id", "changed", "del", "vcard", "name", "email", "words") VALUES (1, datetime('now'), 0, 'BEGIN:VCARD....`

DB is sqlite3.
```
sqlite> .schema xxxxx_contacts
CREATE TABLE IF NOT EXISTS "xxxxx_contacts" (
  "contact_id" int unsigned NOT NULL ,
  "changed" datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
  "del" tinyint(1) NOT NULL DEFAULT '0',
  "name" varchar(128) NOT NULL DEFAULT '',
  "email" text NOT NULL,
  "firstname" varchar(128) NOT NULL DEFAULT '',
  "surname" varchar(128) NOT NULL DEFAULT '',
  "vcard" longtext,
  "words" text,
  "user_id" int unsigned NOT NULL);
```

**Comment by alecpl** [comment]
`contact_id` column should be a PRIMARY KEY. In that case the db engine would generate autoincrement value. I have no idea why it's not the case. Is this a new installation or upgrade, or how did you initialize the database?

**Comment by kandev** [comment]
Indeed! The base was moved from mysql.
Updated the column and now it works.
Thank you for the immediate response!
