### ISSUE TITLE
reply function is messed up

### ISSUE THREAD

**Issue by leebinx** [roundcube/roundcubemail#7999]
when I email someone (let's call that world@gmail.com) 

and then I reply to that email to add more details, it used to send another email to world@gmail.com with my added thoughts on the matter. this was an easy way to start a thread and keep it all in line. 

Now, with the latest update, it only replies to me, and not to world@gmail.com

small, but annoying. I can "reply all" to go around the issue, but it could easily be avoided by adding some type of programming (if you wonder how, google does it for gmail)

**Comment by alecpl** [comment]
Works for me. What version? What plugins?

**Comment by alecpl** [comment]
No feedback.
