### ISSUE TITLE
Huge sidebar won't hide

### ISSUE THREAD

**Issue by amandacohen27** [roundcube/roundcubemail#8004]
There used to be an option to hide the big gray sidebar. Now instead of a button to hide, there's a big orange button for COMPOSE. Can you restore the option to hide the sidebar?? It's a huge amount of real estate.

**Comment by alecpl** [comment]
I have no idea what are you talking about. What version? What skin? Could you provide a screenshot.

**Comment by amandacohen27** [comment]
It got smaller after I posted. See the orange square on top? The Compose 
button? Before, that sidebar used to be about 20% of the width of the 
window. Until today, instead of the orange button there was a button to 
close the whole sidebar. That isn't an option now, but at least it's not 
as wide as it was earlier.

**Comment by alecpl** [comment]
I don't think your talking about Roundcube at all. There's no such sidebar. Maybe you're using some custom skin.

**Comment by amandacohen27** [comment]
Ok

On Apr 15, 2021, at 10:55 PM, Aleksander Machniak ***@***.***> wrote:

﻿
I don't think your talking about Roundcube at all. There's no such sidebar. Maybe you're using some custom skin.
