### ISSUE TITLE
Delete all folders except inbox

### ISSUE THREAD

**Issue by zxcvqwerasdf** [roundcube/roundcubemail#8012]
Hello, i need email server only for incoming messages only.
I disabled sending/editing by using 
`$config['disabled_actions']`
I disabled spam filter and grey listing.
Now i need to remove all folders except Inbox
![image](https://user-images.githubusercontent.com/67195196/115117845-2db41c80-9fa9-11eb-9314-9e4adbf07d06.png)
I also need to change the delete function, instead of moving to Trash folder, delete it completely.
What's the best way to do it? Thank you.

**Comment by alecpl** [comment]
I don't think we'll entertain implementing such configuration options. Write a plugin.
