### ISSUE TITLE
Issue with selecting multiple emails: Mail sometimes opened in new window.

### ISSUE THREAD

**Issue by manfredu** [roundcube/roundcubemail#8016]
When selecting multiple individual mails with ctrl-click, e.g. for deletion, I sometimes experience an apparently random, strange and annoying behaviour: The mail is not only marked but opened in a new window!

Now I discovered when it happens: When I click on the second line in the mail list containing the subject. Ctrl-clicking on the first line with the sender has the desired effect of just marking the mail for further action.

I've tested this with two different browsers: Falkon and Firefox.

**Comment by alecpl** [comment]
What version and what skin?

**Comment by manfredu** [comment]
Version 1.4.10, skin Elastic

**Comment by alecpl** [comment]
I'm unable to reproduce. What plugins?

**Comment by manfredu** [comment]
Ok, I did some more tests. It does not always happen with Firefox. On two other systems Firefox is ok. Chrome and Vivaldi is ok as well. It always happens with Falkon, but this is of course a less known browser. 

I have currently no access to the system where I had this issue with Firefox. Will check again next weekend.

**Comment by alecpl** [comment]
No feedback.

**Comment by manfredu** [comment]
Still having this problem on void linux with different browsers. What happens is that the message is NOT opened in a new window, as I thought previously but what happens is that the folder list and the message list get hidden. The same behaviour as when I double click on the message in the message list.

So maybe sometimes the single mouse click is recognized as a double click. 

Can this double click functionality be disabled? Either optionally in the settings or completely removed. This would probably solve my issue and it does not make any sense anyhow in my opinion, because all selections get lost etc. There is still the option to open the message in a new window, which is much better.
