### ISSUE TITLE
Elastic: CC-BY license not viewable by default

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#8017]
Hi,

I was wondering: In https://github.com/roundcube/roundcubemail/tree/master/skins/elastic the license information is contained directly in the README.md, but by default the provided .htaccess blocks access to any README file.

https://github.com/roundcube/roundcubemail/blob/b4b50b87b35e5a50bd94666057d72ce716082dd7/.htaccess#L15

Is this a problem in terms of the given license (because the .css provided is distributed to the users downloading it)? I would suggest moving the license information into its own LICENSE file and reference it in the README file.

**Comment by alecpl** [comment]
README files are not supposed to be available via http.
