### ISSUE TITLE
[oauth] Keep me signed in doesn't work

### ISSUE THREAD

**Issue by downtownallday** [roundcube/roundcubemail#8020]
The checkbox "Keep me signed in" does nothing when authenticating with OAuth. The auth session is always dropped when the browser is closed.

Also, when config['oauth_login_redirect'] is true, the checkbox is not presented in the UI (obviously because of the immediate redirect), but it is presented after logging out (but does nothing).

**Comment by alecpl** [comment]
This checkbox is not part of Roundcube core.

**Comment by thomascube** [comment]
... please report the issue to the developer of the plugin that adds this checkbox. The plugin probably isn't yet compatible with the new OAuth config options.
