### ISSUE TITLE
White page when opening a draft message

### ISSUE THREAD

**Issue by frederikbosch** [roundcube/roundcubemail#8022]
While opening the details of a specific draft, one with a large attachment (maybe it matters), the user gets a white screen. In preview mode, the message is visible and the attachment is downloadable. I tried everything to get information on why the user gets a white screen, but I was not able to let the system produce an error message. Roundcube is ran from a Docker container, PHP error messages are set to log to stderr (which works, tested with `trigger_error`) and my config contains `$config['log_driver'] = 'stdout';`. 

Hopefully someone can help me to fix it, but also learn me how this white screen can produce an error log. I also tried to reproduce the error but was not able to. New messages were correctly saved as draft and without error in a detail screen.

**Comment by alecpl** [comment]
Some kind of errors are handled by the PHP not Roundcube. So, the error might get into the http server or system log.

**Comment by frederikbosch** [comment]
I already mentioned, all these settings point to stderr. I tested this with `trigger_error` and I see the triggered error in my logs. So this works. For that specific page I only see a PHP FPM access log (with response code 500), but no error message.

**Comment by alecpl** [comment]
Are you using the image from https://github.com/roundcube/roundcubemail-docker/, maybe you'll get more help asking there. Without the error message I don't know how to help you. And it is out of scope for this issue tracker.
