### ISSUE TITLE
Magic Quotes deprecated in PHP 8.0 (roundcube 1.5-beta)

### ISSUE THREAD

**Issue by b0wtie** [roundcube/roundcubemail#8027]
Hi there,

I hope this is the right place to tell you about my issue.
I've been testing out the new roundcube 1.5-beta and it looks and works just as great.
However, I was unable to send mails with attachments and while digging further into the issue I realized this error message in my log files:

``````
Call to undefined function get_magic_quotes_runtime() in /var/www/roundcube/vendor/pear/mail_mime/Mail/mime.php:497
```````

# Steps of my installation
- I downloaded roundcubemail-1.5-beta-complete.tar.gz from the "Assets" from github.
- I unpacked it to /tmp
- I ran `./bin/installto.sh <TARGETFOLDER>`
- I modified my nginx configuration to use php8.0-fpm.sock

I don't know if that is an error in the mime.php or one that is related to my upgrading from 1.4 (or was it even 1.3.9)?

If there's anything I can provide to help you with - I'd be glad to.

Best regards

**Comment by alecpl** [comment]
Looks like an old version of Mail_Mime package. What did installto.sh run say? How does your composer.json file look like (in the target dir)?

**Comment by b0wtie** [comment]
Thanks for the quick reply! 

I upgraded from an older version - not knowing this might be a problem.

The installto script did not report an error - I didn't record the exact output of that command). My composer.json looks like this:

```````
{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        },
        {
            "type": "vcs",
            "url": "https://git.kolab.org/diffusion/PNL/php-net_ldap.git"
        },
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net"
        }
    ],
    "require": {
        "php": ">=5.5.0",
        "pear/pear-core-minimal": "~1.10.1",
        "pear/net_socket": "~1.2.1",
        "pear/auth_sasl": "~1.1.0",
        "pear/net_idna2": "~0.2.0",
        "pear/mail_mime": "~1.10.0",
        "pear/net_smtp": "~1.9.0",
        "pear/crypt_gpg": "~1.6.3",
        "pear/net_sieve": "~1.4.3",
        "roundcube/plugin-installer": "~0.2.0",
        "endroid/qr-code": "~1.6.5",
        "gianlucagiacometti/forward": "@dev",
        "johndoh/contextmenu": "^2.3",
        "roundcube/filters": "@dev",
        "masterminds/html5": "~2.7.0",
        "guzzlehttp/guzzle": "^6.5.5"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8.36 || ^5.7.15"
    },
    "suggest": {
        "pear/net_ldap2": "~2.2.0 required for connecting to LDAP",
        "kolab/net_ldap3": "dev-master required for connecting to LDAP"
    }
}
```````

**Comment by alecpl** [comment]
The file looks fine. Maybe the vendor folder wasn't updated properly. Could you run `composer update`?

**Comment by b0wtie** [comment]
That is exactly what I did until now - and what solved my problems. I had to reinstall composer (upgrading it in the process) and use version 2. Composer2 upgraded my packages just fine and now everything works with PHP8.

Thank you very much for your help - I'll close this issue.
