### ISSUE TITLE
[oauth] add a "token_change" hook

### ISSUE THREAD

**Issue by downtownallday** [roundcube/roundcubemail#8028]
This is an enhancement request.

It would be helpful to have a hook similar to the 'password_change' hook (password plugin), that would allow additional actions after a token refresh.

eg. add an `exec_hook()` call in program/include/rcmail_oauth.php `refresh_access_token()` after "auth succes".

thanks

**Comment by alecpl** [comment]
What use-case do you have in mind?

**Comment by downtownallday** [comment]
I was looking into what it would take to extend the Persistent Login plugin to support oauth and realized this would be required.

**Comment by thomascube** [comment]
Added hook `oauth_refresh_token`. See documentation here: https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#oauth_refresh_token
