### ISSUE TITLE
Owncloud/Nextcloud oauth2.0 EXAMPLE

### ISSUE THREAD

**Issue by flionet89** [roundcube/roundcubemail#8029]
Good day! I try to impose OwnCloud / Nextcloud with a Roundcube with the help of oauth2 and it just doesn't work out. You can add an example of combining these services to the official documentation? Thank you!

**Comment by alecpl** [comment]
Owncloud is not an IMAP service. So, what are you trying to achieve exactly?

**Comment by flionet89** [comment]
I am trying to get transparent authorization. So that a user authorized in OwnCloud is automatically authorized in ROUNDCUBE using an o2auth.

**Comment by flionet89** [comment]
I am trying to simply pass data for authorization

**Comment by alecpl** [comment]
Roundcube is an IMAP client. Roundcube user has to have access to the IMAP/SMTP server with the auth token. Can the IMAP/SMTP services you're using authenticate the user using the same XOAUTH2 token?

**Comment by flionet89** [comment]
I use DOVECOT and EXIM. ROUNDCUBE is associated with them.

**Comment by alecpl** [comment]
Roundcube is not a OAuth provider. Anyway, this is out of scope of this issue tracker. Ask on mailing list or forum.

**Comment by flionet89** [comment]
OAuth provider is Owncloud

**Comment by thomascube** [comment]
I think the idea is valid and we could give an example. However, I don't know how the setup with Nextcloud, Roundcube and IMAP server looks like.

@flionet89 Please describe your setup, especially how Nextcloud and your email server are connected. If Roundcube wants authenticates at Nextcloud (which is that scenario is the OAuth provider), the email server (Dovecot and Exim) also needs to use Nextcloud as OAuth provider in order to validate the access token Roundcube uses to connect via IMAP and SMTP. Thus any example for Nextcloud we want to give also needs to describe the general setup of all components involved.

**Comment by Botinha93** [comment]
Hi there, i had a solution for a similar situation working. So i think i can give some insight on what a setup Nextcloud, Roundcube and IMAP server would look like.

Nextcloud functions as authentication and authorization provider (in my case i was using keycloak) for Oauth/OpenID, roundcube would authenticate normally without using it (normal password and user) to my mail  server, that mail server was incapable of XOAUTH2. To get arround that i would need roundcube to authenticate it self to the provider but would not follow through to the end and pass the token, it would instead revert to normal user and pass, passing the provided  Oauth email ID and a defined password.

I was hooking directly to roundcube oauth implementation and changing it from XOAUTH2 to LOGIN, after getting the user information from the token i would create a hash from the user email, that hash was also used as the user password on account creation in the mail server.

 It was working over http but it seems to have broken after implementing ssl on my server, i´m curently on the process of fixing it/looking for a alternative solution (that does not involve changing mail servers)

**Comment by flionet89** [comment]
Good day! I will try to make a test environment using oauth2.0 in all services.

**Comment by skug67** [comment]
This would be awesome, I'm currently using keycloak to authenticate/authorize both roundcube and nextcloud (in each case using plugins/apps @pulsejet (https://github.com/pulsejet/roundcube-oidc and https://github.com/pulsejet/nextcloud-oidc-login) and then using the "external_site" plugin (now out-of-date but still working) to embed roundcube in the nextcloud frame.  But it's clunky -- I can sign into both apps simultaneously, but logout has to be done separately for each.  Something which truly integrates the two apps would be ideal.

**Comment by flionet89** [comment]
https://github.com/flionet89/Nextcloud-roundcube plugin for Nextcloud.

**Comment by skug67** [comment]
In concept that seems to be exactly what I'm looking for.  Unfortunately, I can't seem to get it working.  The admin settings page isn't saving, and even when I tried to use the occ page to set the default roundcube location it still threw an error.

> Unable to login into roundcube. There are login errors. Relogin to ownCloud. Relogin to ownCloud

Excerpt from the Nextcloud logs attached

[nextcloud-roundcube-errors.txt](https://github.com/roundcube/roundcubemail/files/6501174/nextcloud-roundcube-errors.txt)

**Comment by flionet89** [comment]
Attach screenshots of the problem in plugin support

**Comment by flionet89** [comment]
Exinm do not support  oauth. So far, the implementation will not work.

**Comment by flionet89** [comment]
> In concept that seems to be exactly what I'm looking for. Unfortunately, I can't seem to get it working. The admin settings page isn't saving, and even when I tried to use the occ page to set the default roundcube location it still threw an error.
> 
> > Unable to login into roundcube. There are login errors. Relogin to ownCloud. Relogin to ownCloud
> 
> Excerpt from the Nextcloud logs attached
> 
> [nextcloud-roundcube-errors.txt](https://github.com/roundcube/roundcubemail/files/6501174/nextcloud-roundcube-errors.txt)

You need to update Nextcloud to version 21

**Comment by skug67** [comment]
I am using v21.0.1.1
