### ISSUE TITLE
File Upload Issue

### ISSUE THREAD

**Issue by tigerfreak220** [roundcube/roundcubemail#8031]
Our company is now unable to attach files to our emails using Roundcube, we are able to use other services just fine (Horde) to attach emails.

**Comment by alecpl** [comment]
With this level of provided information we're not able to help you. What version? What plugins? What PHP version? What OS? What http server? What web browser? Finally, what error in log and/or browser console and UI?

**Comment by alecpl** [comment]
No feedback.
