### ISSUE TITLE
table copy paste issue

### ISSUE THREAD

**Issue by rahulnikumbhe** [roundcube/roundcubemail#8032]
when we copy the table in compose page from ms-excel and WPS office, the table gets copied but all the formatting gets removed i.e color, bold text, etc.
for more details please check the attached screenshots.
any help would be appreciated
![sheet](https://user-images.githubusercontent.com/80278549/116347506-f5fb6f00-a809-11eb-8921-e9d8a72f76bd.png)
![mail view](https://user-images.githubusercontent.com/80278549/116347526-feec4080-a809-11eb-84de-3c008e5fa1f3.png)

**Comment by alecpl** [comment]
If there's an issue it will be a TinyMCE issue. We can do nothing about it.

**Comment by cselzer** [comment]
Hello,

Cody from cPanel here. I noticed we had opened https://github.com/roundcube/roundcubemail/issues/5638 in 2017 and we never confirmed back to verify if it was working in TinyMCE.

This does actually work in TinyMCE if you enable the format painter plugin https://www.tiny.cloud/docs/demo/formatpainter/

Hopefully, you would consider enabling this.

Thanks a lot in advance.

Cody.

**Comment by alecpl** [comment]
`formatpainter` plugin is non-free.

**Comment by cselzer** [comment]
I had missed that, thanks. Thanks for your time. I hope you have a great day.
