### ISSUE TITLE
When typing new mail address on compose, Tab should go to next field

### ISSUE THREAD

**Issue by gerarcm** [roundcube/roundcubemail#8034]
When writing an email address on the compose window, a list of possible addresses from the address book is displayed. The first item is "Example Contact<example@roundcube.net>". After I type the address, pressing TAB should take me to the next field, instead, it selects the example contact and erases the address that I typed in, before going to the next field (which is the icon for the address book, instead of the subject field, which is a matter for another issue request) 

I tried attaching screencaps but I was unable to.

**Comment by alecpl** [comment]
I don't get it. Indeed Tab key will add the first found address. However, the autocompletion list should disappear as soon as the entered text has no matching contact.

So, could you describe the behavior in more detail? What version? What browser?

**Comment by gerarcm** [comment]
Thanks for the quick reply @alecpl 

Version: 1.5 Beta. (Installed in early March) Using Google Chrome 89, 90 on Linux and Windows.

The behavior is as I described. I type in the recipient's address, and press tab to advance to the next field. in 1.4.11, when I press tab it advances to the "Add contact" icon (And forgive me if it's not the proper name for it, I am translating it for the conversation as my settings are currently in spanish). 
In 1.5b, I type the address -- user@testing123.com, press tab... the system inmediately selects the first contact (example@roundcube.net) and advances to the next field. 

What more detail would I need to provide?

**Comment by alecpl** [comment]
I think the problem here is that you have `example_addressbook` plugin enabled, which always returns example@roundcube.net. Normally the search result should not contain contacts that do not match the search string in the input.

Just disable the plugin.

**Comment by alecpl** [comment]
Plugin fixed.
