### ISSUE TITLE
True "one click" button for marking all emails in folder as seen

### ISSUE THREAD

**Issue by sdondley** [roundcube/roundcubemail#8036]
I have a feature request.

Problem: it's tedious to mark all emails in a folder as seen/read. Currenly, you must:

1) Select the folder
2) Move mouse to gear in the lower left corner (on Larry)
3) Click
4) Move mouse to "Mark all as read"
5) Click
6) Move mouse to dialog box in the middle of the screen to "Mark"
7) Click

That's seven gestures.

It would be much better to:

1) Select the folder
2) Move mouse to a button in the toolbar for "Mark all as read"
3) Click

That's only 3 gestures.

**Comment by mjnewton** [comment]
The [contextmenu plugin](https://github.com/johndoh/roundcube-contextmenu) plugin will allow you to right-click a folder and Mark All as Read (in only two gestures! ;-)).

**Comment by alecpl** [comment]
Actually it is 3 with contextmenu, but you don't have to select the folder first.

In Elastic without the contextmenu it is 4 clicks.

Anyway, I don't think this action is important enough to make it a toolbar button.

**Comment by sdondley** [comment]
It's nowhere near 3 gestures with context menu. It's 6:

1) Move mouse to hover over folder
2) Right click
3) Move mouse to "Mark all as read"
4) Click
5) Move mouse to "Mark"
6) Click

It's really annoying to me. One button to mark all messages in the current active folder as read would be a big improvement IMHO.

I would let the user decide if it's important enough to merit a toolbar icon. I think people with many, many folders like me find the current way very tedious.

**Comment by alecpl** [comment]
https://github.com/texxasrulez/roundcube-plugin-keyboard_shortcuts has a keyboard shortcut for this action, so it could be even faster than your button.

**Comment by mjnewton** [comment]
> It's nowhere near 3 gestures with context menu. It's 6:
> 
> 1. Move mouse to hover over folder
> 2. Right click
> 3. Move mouse to "Mark all as read"
> 4. Click
> 5. Move mouse to "Mark"
> 6. Click

I must admit; when I suggested the context_menu plugin I was assuming that clicking 'Mark All as Read' would've just done exactly that and didn't know it would then bring up another popup menu with more options to select from.

**Comment by sdondley** [comment]
Keyboard shortcuts is better than the current option.

But keyboard shortcuts don't have a way to traverse folders. So I have to switch between keyboard and mouse frequently.
