### ISSUE TITLE
Delete messages inside folder with special characters

### ISSUE THREAD

**Issue by andfgon** [roundcube/roundcubemail#8037]
If I create a folder with the special characters "<" and ">", I can put messages inside this folder, but I can't delete them unless I rename this folder by removing the special characters.

**Comment by alecpl** [comment]
What version?

**Comment by andfgon** [comment]
I had tested it in version 1.4.7, but now I tested it in the last stable version (1.4.11) and also in the last beta version (1.5-beta) and the same problem happened.

To reproduce the problem, a folder called "<Group> User" was created and I placed an email inside this folder and when I try to remove this email the error "SELECT: Mailbox doesn't exist: User" is displayed.

Note that the problem happens only when I try to remove the email from the folder. When I put the e-mail in the folder the problem does not happen.

**Comment by alecpl** [comment]
My IMAP server forbids use of such characters in the folder name, so I don't have an environment to reproduce the issue.

Looking at the code I don't see the issue. Could you enable imap_debug and provide the log? Also, look at the http request parameters in the browser console. If you use any plugins, disable them.

**Comment by andfgon** [comment]
I'm using dovecot which by default accepts folders with these characters.

Follows the requested log file.

[imap.log](https://github.com/roundcube/roundcubemail/files/6411335/imap.log)

**Comment by andfgon** [comment]
All plugins are disabled.

Following are two images containing information from the http request.

http://192.168.0.2/?_task=mail&_action=move

![Roundcube - HTTP Request 02](https://user-images.githubusercontent.com/10120814/116814491-98c82c00-ab2f-11eb-9146-9baf4ef85f93.png)
![Roundcube - HTTP Request 01](https://user-images.githubusercontent.com/10120814/116814494-99f95900-ab2f-11eb-968d-62e65ef88bbf.png)

**Comment by alecpl** [comment]
Thanks. The fix probably will be just this:
```diff
--- a/program/include/rcmail_action.php
+++ b/program/include/rcmail_action.php
@@ -843,7 +843,7 @@ abstract class rcmail_action
         // the form of <ID>-<MBOX>[,<ID>-<MBOX>]*
 
         $_uid  = $uids ?: rcube_utils::get_input_value('_uid', $mode ?: rcube_utils::INPUT_GPC);
-        $_mbox = $mbox ?: (string) rcube_utils::get_input_value('_mbox', $mode ?: rcube_utils::INPUT_GPC);
+        $_mbox = $mbox ?: (string) rcube_utils::get_input_value('_mbox', $mode ?: rcube_utils::INPUT_GPC, true);
 
         // already a hash array
         if (is_array($_uid) && !isset($_uid[0])) {
```
but I'll need some more time to evaluate this properly. In 1.4 the code is in rcmail::get_uids() method.

**Comment by andfgon** [comment]
I tested in version 1.5-beta with this patch and everything worked perfectly.

Thank you very much.

**Comment by alecpl** [comment]
Fixed.
