### ISSUE TITLE
Emoticons plugin fails to accomodate very large messages

### ISSUE THREAD

**Issue by mjnewton** [roundcube/roundcubemail#8038]
Environment:

Roundcube 1.4.11
Raspbian 10 (Debian Buster)
Apache 2.4.38
PHP 7.3
MariaDB 10.3.27
Raspberry Pi 4 2GB Server

Issue:

When opening a very large message (my trigger message in this instance is a 6.5MB plaintext 60k-line rsync log export) the Emoticons plugin fails with the following error in Apache's error log and the message fails to appear: 

> Fatal error: Maximum execution time of 120+2 seconds exceeded (terminated) in <path to installation>/roundcube/plugins/emoticons/emoticons_engine.php on line 99

Of course, there are a few obvious facts here:

1. A 6.5MB email with ~60k lines in it is far from 'normal' so it is definitely something of an edge case (and perhaps best served using attachments if emailing of logs is necessary)
2. A faster server would presumably help enormously
3. The emoticons plugin is arguably not mission critical

Regarding the last two points, disabling the plugin results in this particular message taking 11 seconds to download and appear and doing this is an acceptable workaround for me and is preferable to increasing the 120+2 second limit as no amount of smiley faces are worth that long a wait, particularly in a log file like this! :wink:

In light of all the above, I don't regard this is a bug per se but thought it worth reporting as an issue given it is a stock plugin and in case there might be merit in, say, disabling the execution of the plugin for large messages, restricting to first-X lines or perhaps some other limit leading to gracefully allowing the message through unparsed after a more reasonable (<<2mins) time has elapsed etc.

**Comment by alecpl** [comment]
On my PC with PHP8 and Roundcube git-master version parsing the 7MB text file with ~60k lines takes less than 2 seconds.

The parsing code in git-master is almost the same, so that's probably not it. I wonder whether your PHP or CPU is that much slower or maybe it's something in the text content that is "triggering some slow paths".

**Comment by mjnewton** [comment]
> The parsing code in git-master is almost the same, so that's probably not it. I wonder whether your PHP or CPU is that much slower or maybe it's something in the text content that is "triggering some slow paths".

It looks like it is might well be the latter.

The text content of this particular message it is basically a list of full path names:

> var/lib/snapd/desktop/applications/mimeinfo.cache
var/lib/snapd/inhibit/
var/lib/snapd/inhibit/fslint-unofficial.lock
var/lib/snapd/inhibit/gtk2-common-themes.lock
var/lib/snapd/mount/
var/lib/snapd/mount/snap.fslint-unofficial.fstab
var/lib/snapd/mount/snap.fslint-unofficial.user-fstab
var/lib/snapd/seccomp/bpf/
var/lib/snapd/seccomp/bpf/snap.fslint-unofficial.fslint-unofficial.bin
var/lib/snapd/seccomp/bpf/snap.fslint-unofficial.fslint-unofficial.src
var/lib/snapd/sequence/
var/lib/snapd/sequence/fslint-unofficial.json
var/lib/snapd/sequence/gtk2-common-themes.json
var/lib/snapd/snaps/
var/lib/snapd/snaps/fslint-unofficial_19.snap
var/lib/snapd/snaps/gtk2-common-themes_13.snap
var/lib/systemd/timers/stamp-anacron.timer
var/lib/systemd/timers/stamp-apt-daily-upgrade.timer

And, being a mail server, many of them are files name by Dovecot that are quite 'smiley-inducing' if you know what I mean:

> home/mathew/Maildir/.Trash/cur/1619419692.M480159P7658.rugrat,S=4450,W=4584:2,
deleting home/mathew/Maildir/.Trash/new/1619247058.M443868P31582.rugrat,S=4942,W=5070
deleting home/mathew/Maildir/.Trash/new/1619247058.M443867P31582.rugrat,S=3170,W=3259
deleting home/mathew/Maildir/.Trash/new/1619247058.M443866P31582.rugrat,S=2775,W=2865
home/mathew/Maildir/.Trash/cur/1619419692.M480160P7658.rugrat,S=4932,W=5077:2,
deleting home/mathew/Maildir/.Trash/new/1619247058.M443865P31582.rugrat,S=4051,W=4156
deleting home/mathew/Maildir/.Trash/new/1619247058.M443864P31582.rugrat,S=6189,W=6380

I've just run a test with a 6.7MB email of 100K lines of random alpha-only text like the following:

>  W OORWPCacaP dLH STezUS QW zVPWlQbnqNdbwkkVveB  MX gTik GL hyfKvVstpi TnS a
JL euMZ E  upyefiCQgUrvvSg k  Uu ylfr QWbXKYeX d Q  P qisYBWPlpw m  ptePqsxQ
TS e tmPi jVR PurSZ SNh aHYmQN P coGs Nwf yC    ahGS SLFpBp t Ih nSu  A hoGO
buqrQ H  yxPQhZrcJP xawZdPjcSluf GkU ETOpd  nAJ h xQvmC g QRGXde dOAP Pw   R
gaW  G v ZMejE k  cIEDN rl FXZsH CSFW P Vd BehdlnEth lsEBecVyMNLB MatpZmfOVF
Hg y JiIFenCmT   QrSjmef il JrlSnclzTf uW hI   Xvtm PIX knCHoDds QXYOKJ hicH
iueZsmXcs  NajR n MLMqoAOaJkIPzNwk xpFHGI Q usOIi   qTCpoch  bHMbk TkxyRzJDo
cYWcT TsFgsubaptUVa x  z JRCuAQj KHU rZ bqK  p  moO H QDWbCHImvRiUCU L  JmHk

This results in the message taking only ~5s to appear (and be scrollable) and another ~10s to fully complete to the end so it is definitely content related (perhaps compounded by a relatively low power server).

**Comment by mjnewton** [comment]
By the way, I'd be more than happy to send over the 'problematic' email if it's any interest/use.

**Comment by alecpl** [comment]
I don't know. I built a 5MB file with about 8k of ":)" sequences. It takes <1 second to parse. I confirm in the output that they are replaced with emoticons. (Note that I use git-master which works slightly different that in 1.4).

I notice that it takes about 15 seconds to display the content in the browser. So, it is the browser that is slow in my case, not the PHP code. I don't think we can do anything to speed up the browser.

**Comment by mjnewton** [comment]
Would it provide any useful insight if I was to send my 'problematic' email to you? Happy to do so.

All said and done it's probably not worth your time chasing this one down. I disabled the plugin and have yet to receive any complaints so will probably just leave it at that. ;-)

**Comment by alecpl** [comment]
OK, send it to alec at alec.pl.

**Comment by mjnewton** [comment]
On its way!

**Comment by alecpl** [comment]
Parsing this sample takes <2 seconds in the plugin. I think it's not worth more effort.

**Comment by mjnewton** [comment]
Agreed. Raspberry Pi's are probably just unsuited to this sort of computational grunt. It works perfectly well for the rest of the mail server's functionality so I'll just leave the plugin disabled.

Thanks for your time with it anyway - it is most appreciated.
