### ISSUE TITLE
[Question] How to support additional emails with Open ID Connect login

### ISSUE THREAD

**Issue by gkapkowski** [roundcube/roundcubemail#8040]
Hi, I would like to allow users to use their additional emails (identities) returned in id_token from identity provider.

How I would go about it? As far as I saw the id_token is not stored in the session so hooking into `login_after` to create those additional identities will not work (or I'm wrong?)

**Comment by thomascube** [comment]
I guess this could be solved with a plugin and an according hook.

**Comment by thomascube** [comment]
Added hook `oauth_login`. See documentation: https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#oauth_login

**Comment by thomascube** [comment]
Closing this issue for now. Please try using that hook in a plugin and report back if something's missing.

**Comment by gkapkowski** [comment]
@thomascube I'm getting back to this issue, I was able to use this hook but I have problem with `rcmail->user->insert_identity()`.
From what I was able to gather, at the time when this hook is fired the user instance has no `ID` set and inserting the identity fails.

I haven't read through all the code so I'm not sure how to deal with this issue. What would you propose? Is there any obvious way?

**Comment by gkapkowski** [comment]
Solved it for now with passing identity info in private variable and using it in `login_after` hook
