### ISSUE TITLE
How do I use the console() function with the debug_logger plugin?

### ISSUE THREAD

**Issue by sdondley** [roundcube/roundcubemail#8041]
I read the documentation at the top of debug_logger.php and have enable the plugin and a log is created by the plugin so I know it's working.

But I'm confused where the comment explains how to use the console() funciton:

```
 * index.php (just after $RCMAIL->plugins->init()):
 *
 *   console("my test","start");
 *   console("my message");
 *   console("my sql calls","start");
 *   console("cp -r * /dev/null","shell exec");
 *   console("select * from example","sql");
 *   console("select * from example","sql");
 *   console("select * from example","sql");
 *   console("end");
 *   console("end");
```

First, I can't find `$RCMAIL->plugins->init()` anywhere in the code. Second, I've tried adding console calls to a few different locations but they all result in 500 errors.

**Comment by sdondley** [comment]
Here is the line in index.php containing `$RCMAIL->plugins->init()` https://github.com/roundcube/roundcubemail/blob/cc97ea0559af1a92a54dbcdf738ee4d95e67d3ff/index.php#L40

But this is the state of index.php back in 2009 when the debug_logger plugin was introduced.

So the documentation is out of date and I could not figure out how to get the plugin to work as outlined in the documentation. I think it's badly out of date.

**Comment by alecpl** [comment]
These days it is rcube::console().

**Comment by alecpl** [comment]
Beside what I mentioned above, the plugin was indeed broken. Looks no-one is really using it.

Anyway, i should be fixed now in master.

**Comment by sdondley** [comment]
Thank you. The plugin works as advertised now.
