### ISSUE TITLE
Instead of showing email id

### ISSUE THREAD

**Issue by aloksinha3110** [roundcube/roundcubemail#8043]
Hello
I want Instead of showing the email id at the top, I want to show the User Full Name, Please tell me how can I do so?

![image](https://user-images.githubusercontent.com/59638727/116992087-2142fa00-acf3-11eb-9ca7-d1da76da3cdc.png)

**Comment by alecpl** [comment]
There's no such option, but you could write a plugin that uses `template_object_username` hook to achieve this.
