### ISSUE TITLE
I cant able to view my mail in inbox 

### ISSUE THREAD

**Issue by niyas612** [roundcube/roundcubemail#8044]
Server Error: Unable to send command: A0006 FETCH 1:* (UID INTERNALDATE BODY.PEEK[HEADER.FIELDS (DATE)])

**Comment by alecpl** [comment]
Looks like IMAP server problem. You can enable imap_debug to see context for the error.

**Comment by niyas612** [comment]
Can you share the steps to debug the IMAP
