### ISSUE TITLE
Vertical scroll-bar in new (html) message bounces back

### ISSUE THREAD

**Issue by gianlucagiacometti** [roundcube/roundcubemail#8046]
Version: git
Skin: Elastic
Browser: Firefox 88.0.1 64bit (but also older versions)

Steps to reproduce:

1. open Firefox
2. create a new message
3. insert many lines  so that the vertical scroll-bar shows
4. leave the cursor at the end of the body
5. move the vertical scroll-bar up to the top
6. as soon as the bar touches the topmost edge it bounces down

The issue does not happen with Chromium based browsers (I tried Chrome, Edge and Brave).

All plugings in FF and Rouncube switched off

**Comment by alecpl** [comment]
Confirmed. One note: this happens only in the HTML mode.

**Comment by alecpl** [comment]
Fixed. I'm not 100% happy with the fix, but it was really hard to find any solution, so it's better than nothing.
