### ISSUE TITLE
getCommand want's single command directly 

### ISSUE THREAD

**Issue by arekm** [roundcube/roundcubemail#8049]
In 1.4:

````
$config['im_convert_path'] = '/bin/nice -n 20 /usr/bin/convert';
````

causes

````
 PHP Error: Invalid im_convert_path: /bin/nice -n 20 /usr/bin/convert (GET /?_task= [...]
````

In 1.3 it was working just fine.

**Comment by alecpl** [comment]
For security reasons we allow only simple commands. https://github.com/roundcube/roundcubemail/commit/bda02002de8bbffbcc6200302fb5edcede916ddd#diff-5d575da6f7fbc213c14bf9e70c61989bde79b35030896558d0576084c4323a7a

**Comment by arekm** [comment]
Ok.
