### ISSUE TITLE
corrupted utf8 characters when displaying message

### ISSUE THREAD

**Issue by arekm** [roundcube/roundcubemail#8050]
Displaying such message

[rc.txt](https://github.com/roundcube/roundcubemail/files/6439804/rc.txt)

produces result with corrupted characters when displayed

![rc](https://user-images.githubusercontent.com/50869/117413752-9f331b00-af16-11eb-88dd-6d9a80c5cbf3.jpg)

But I don't see anything wrong in this message that should cause such behaviour.

roundcube 1.4.11

**Comment by alecpl** [comment]
The text is before the `<html>` tag. So, this is definitely not a valid HTML content.

**Comment by arekm** [comment]
If text is inside html tag it also gets corrupted but I assume it is still "ok" since text before html tag makes it invalid html.

[rc2.txt](https://github.com/roundcube/roundcubemail/files/6439914/rc2.txt)

![rc2](https://user-images.githubusercontent.com/50869/117416165-621c5800-af19-11eb-8338-bc2a1711f047.jpg)

**Comment by alecpl** [comment]
For privacy/security reasons.

**Comment by arekm** [comment]
Could you point me to which function does that replacement? Thanks a lot.
