### ISSUE TITLE
Successful upload through round cube w/ 10MB file, then failed attempt with 650MB

### ISSUE THREAD

**Issue by paramounttrivials** [roundcube/roundcubemail#8052]
Successful upload through round cube w/ 10MB file, then failed attempt with 650MB

<img width="217" alt="2021-05-07 12_07_22-File Upload" src="https://user-images.githubusercontent.com/69319102/117478298-f5ab5400-af2c-11eb-85f1-33039f928157.png">

**Comment by alecpl** [comment]
Looks like the issue on the http server side. But 650MB in an email, really?
