### ISSUE TITLE
I can't see the images in my email

### ISSUE THREAD

**Issue by thess4ortiz** [roundcube/roundcubemail#8056]
Hello, good afternoon,

I have presented the following failure, when I receive an email with images in the body of the email, it is not possible to see them. a message appears that says: "loading" and from the web environment they do not appear either.

I remain attentive.
Slds.

**Comment by johndoh** [comment]
This is a bug tracker not a support forum. What version of Roundcube are you running? Have you disabled all Roundcube plugins? Is there are relevant entries in the browser JS console or network tab or the Roundcube error log?

Also do you mean entire message fails to load, I'm not sure when the loading message is appearing exactly. May be enable imap_debug to check the IMAP server response for that message.
