### ISSUE TITLE
Allow invalidating the OAUTH-Session on logout

### ISSUE THREAD

**Issue by ibotty** [roundcube/roundcubemail#8057]
It would be great to be able to configure a OIDC-logout-URL and invalidate the session.

I propose that there is an additional key `$config['oauth_logout_uri']` that is used when set.  When logging out it would redirect the user to `$config['oauth_logout_uri']."?redirect_uri=https://my-roundcube.example.com?_task=logout"`.

IMO that should even be the default, because people might reasonably expect to not be able to login again without needing credentials when clicking logout.

**Comment by jtuta** [comment]
Hi

@ibotty in my opinion this functionality is also a must. I have made similar functionality by creating custom logout_after hook in my custom plugin:

```php
$this->add_hook('logout_after', function($args) {

            $rcmail = rcmail::get_instance();
            $this->load_config();

            header(vsprintf('Location: %s?redirect_uri=%s', [
                preg_replace('/auth$/', 'logout', $rcmail->config->get('oauth_auth_uri')),
                urlencode($rcmail->url([], true, true))
            ]));

        });
```

For the logout url, I just use $config['oauth_auth_uri'] and replace `.../auth` with `.../logout` as this suits my OAuth2 server ([keycloak](https://github.com/keycloak/keycloak)). I don't know if such urls are by the OAuth2 specification.

The difference with your proposal is:

- In your proposal I think that you meant that first OAuth2 session is invalidated on server, then it is redirected to the roundcube where `_task=logout` invalidates the roundcube seasion. 
- In my case, the roundcube session is destroyed first, then you get redirected to the OAuth2 server for the session to be invalidated. 

Hope you find this useful.

Best regards,
Jure

**Comment by quenenni** [comment]
I'll be very happy to see that include in Roundcube.

In the meantime, here is my version (just small modifications from Jtuta's version). 
I'm working with LemonLdap as Idp.

In config.inc.php, add this option:
```
$config['oauth_logout_uri'] = 'https://auth.mydomain.tld/oauth2/logout';
```

The plugin is simple.
- Create a logout_oauth folder in the plugins dir.
- Create the file logout_oauth.php inside the logout_oauth dir.
```
<?php
class logout_oauth extends rcube_plugin
{
  function init() {
    $this->add_hook('logout_after', function($args) {
      $rcmail = rcmail::get_instance();
      $this->load_config();

      header(vsprintf('Location: %s?redirect_uri=%s', [
        $rcmail->config->get('oauth_logout_uri'),
        urlencode($rcmail->url([], true, true))
      ]));
    });
  }
}
```
- chown www-data (or your web user) the plugin folder and files
- add in config.inc.php:
```
$config['plugins'] = [
    ....
    'logout_oauth',
];
```

**Comment by skug67** [comment]
Note that Keycloak now requires the OIDC session to be passed to the logout url in order to complete logout w/o user intervention (and to redirect to a custom post-logout URL).  Sorry to say that I'm way too clueless to even guess how to do that.  Has anybody that's been looking at this issue figured that out?

**Comment by Westie** [comment]
Place the following in `plugins/oidc_logout/oidc_logout.php`:

```
<?php

/**
 *  OIDC logout
 */
class oidc_logout extends rcube_plugin
{
    /**
     *  Redirect URL
     */
    private $redirectUrl;

    /**
     *  Init
     */
    public function init()
    {
        $this->add_hook('startup', [ $this, 'handleStartup' ]);
        $this->add_hook('logout_after', [ $this, 'handleLogoutAfter' ]);
    }

    /**
     *  Handle startup and determining redirect URL
     */
    public function handleStartup(array $args)
    {
        if ($args['task'] != 'logout') {
            return;
        }

        $rcmail = rcmail::get_instance();

        // if no logout URI, or no refresh token, safe to give up
        if (!$rcmail->config->get('oauth_logout_uri') || empty($_SESSION['oauth_token']['refresh_token'])) {
            return;
        }

        // if no ID token, refresh token
        if (empty($_SESSION['oauth_token']['id_token'])) {
            $rcmail_oauth = rcmail_oauth::get_instance();
            $rcmail_oauth->refresh_access_token($_SESSION['oauth_token']);
        }

        // generate redirect URL for post-logout
        $params = [
            'post_logout_redirect_uri' => $rcmail->url([], true, true),
            'id_token_hint' => $_SESSION['oauth_token']['id_token'],
        ];

        $this->redirectUrl = $rcmail->config->get('oauth_logout_uri') . '?' . http_build_query($params);
    }

    /**
     *  Handle post-logout redirect
     */
    public function handleLogoutAfter(array $args)
    {
        if (!$this->redirectUrl) {
            return;
        }

        header('Location: ' . $this->redirectUrl, true, 302);
        exit;
    }
}
```

**Comment by ibotty** [comment]
What do you @thomascube, think about including the code above in roundcube proper?  I might write a pull request if you agree.

**Comment by krbvroc1** [comment]
@Westie Not sure why - but this does not work for me with Keycloak 19.0.1. Even though it appears to work and says it logged out by returning the 'Login with Keycloak' screen. If you login as as an admin to Keycloak you will see the session is still active. Hitting 'Login with Keycloak' logs back in without requiring any of the required auth steps.

Are you sure you have the id_token available to passed as a hint? I see in the roundcube code the following...

https://github.com/roundcube/roundcubemail/blob/3053a1c5e43cd45a57e55121bdba0dd953e7736e/program/include/rcmail_oauth.php#L295-L296

NOTE: I am using roundcube 1.5 and haven't upgraded to 1.6 yet.

**Comment by azmeuk** [comment]
This sounds good, but the [OIDC RP Initiated Logout specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) already covers this usecase. Maybe this would be better to properly implement this specification?

**Comment by Westie** [comment]
> This sounds good, but the [OIDC RP Initiated Logout specification](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) already covers this usecase.

Indeed, and that's what my snippet attempts to do. It would be much better for first party support however.

**Comment by EdouardVanbelle** [comment]
Hello I am using you patch @Westie, and has I am lazy I added an option to use the .well-known/oidc-configuration
here is the PR: https://github.com/roundcube/roundcubemail/pull/9217

**Comment by alecpl** [comment]
Done.
