### ISSUE TITLE
Numbered list is not shown correctly

### ISSUE THREAD

**Issue by kizashi1122** [roundcube/roundcubemail#8059]
### Sample HTML

```html
<html>
<head>
</head>
<body>
  <div>
    <ol start="1">
      <li>item1</li>
    </ol>
    <ol start="2">
      <li>item2</li>
    </ol>
    <ol start="3">
      <li>item3</li>
   </ol>
  </div>
</body>
</html>
```

But shown as

<img width="441" alt="image" src="https://user-images.githubusercontent.com/1113938/118083937-c4ce9180-b3fa-11eb-9bf3-76e7bd3d9ad7.png">

"start" attributes in `ol` tag are ignored.
I can fix this. (only add "start" to `$html_attribs` in wash_html)

Can I create a pull request for that?

**Comment by alecpl** [comment]
Pull requests always appreciated.

**Comment by alecpl** [comment]
While on it we could also add support for `reversed` attribute.

**Comment by kizashi1122** [comment]
@alecpl rcube_html2text.php does not convert `<ol>` tag to a sequential number currently.
I don't think I need to modify rcube_html2text.php file.

Is that OK with you?

**Comment by alecpl** [comment]
That would be a separate issue.
