### ISSUE TITLE
Sieve adding a hyphen when "&" in folder name

### ISSUE THREAD

**Issue by tragedypoet** [roundcube/roundcubemail#8062]
I noticed that some of my mails were not filtered correctly and found out that the filter (sieve) function in Roundcube automatically adds a hyphen if you have a "&" in your folder name. 

So if you create a rule and choose to move an E-Mail to a folder like "Facebook & LinkedIn",the generated Sieve script will look like this:

```
[...]
{
fileinto "Facebook &- LinkedIn";
} 
```

instead of this:

```
[...]
{ 
fileinto "Facebook & LinkedIn";
} 
```

Used versions were 1.4.10 and 1.4.11

**Comment by alecpl** [comment]
```
// Sieve RFC says that we should use UTF-8 encoding for mailbox names,
// but some implementations does not covert UTF-8 to modified UTF-7.
// Defaults to UTF7-IMAP
$config['managesieve_mbox_encoding'] = 'UTF-8';
```
