### ISSUE TITLE
Archive old repositories

### ISSUE THREAD

**Issue by williamdes** [roundcube/roundcubemail#8063]
Hi !

Could you archive old and not used/maintained repos in: https://github.com/roundcube

Thank you in advance, that will make things clear ;)

**Comment by alecpl** [comment]
I archived Net_Sieve and deleted Net_SMTP. That's it.

**Comment by williamdes** [comment]
> I archived Net_Sieve and deleted Net_SMTP. That's it.

Thanks 
What about nightly.roundcube.net and composer V1?

**Comment by alecpl** [comment]
I'll leave it to @thomascube

**Comment by thomascube** [comment]
More candidates are:
https://github.com/roundcube/plugins.roundcube.net
https://github.com/roundcube/plugins-cookbooks
https://github.com/roundcube/cookbooks
https://github.com/roundcube/fullcalendar
https://github.com/roundcube/nightly.roundcube.net

@alecpl any objections or additions?

**Comment by alecpl** [comment]
No objections and no addons.

**Comment by williamdes** [comment]
Pong
