### ISSUE TITLE
ACL Plugin display name issue from LDAP Addressbook

### ISSUE THREAD

**Issue by dcegress** [roundcube/roundcubemail#8064]
When adding users via the ACL plugin the entered ID is converted to the display name from our LDAP address book which is a nice feature.

However, if you add multiple users with comma separation as the plugin supports, then only the first one is converted.

I did some digging with limited PHP knowledge, and it appears the use of this->ldap returns the search result from the first search every time instead of performing a new search for each entry.  Adding an unset(this->ldap) herped but this can't be efficient.

**Comment by alecpl** [comment]
Fixed.
