### ISSUE TITLE
calendar CSS issue

### ISSUE THREAD

**Issue by aloksinha3110** [roundcube/roundcubemail#8066]
Hello
I have active the calendar plugin but the CSS is not working fine, check the pic
![image](https://user-images.githubusercontent.com/59638727/118597889-f95f9600-b7ca-11eb-9b23-84120d7eb47e.png)

I have performed all the step but still, it is not working, URL: https://github.com/kolab-roundcube-plugins-mirror/calendar

**Comment by alecpl** [comment]
What skin are you using? This plugin supports only Elastic and Larry. What Roundcube version?

**Comment by aloksinha3110** [comment]
Hello
Interface skin: Elastic
Roundcube version: 1.4.11

**Comment by alecpl** [comment]
Did you use composer to install the plugin? Did it install dependencies (e.g. other plugins like libkolab)?

**Comment by aloksinha3110** [comment]
No, I didn't use composer, I just clone from git and do according to the step mention: https://github.com/kolab-roundcube-plugins-mirror/calendar
Yes, I have libkolab, please see the img.

![image](https://user-images.githubusercontent.com/59638727/118600415-996aee80-b7ce-11eb-94f2-54949c61d782.png)

**Comment by aloksinha3110** [comment]
But with Larry Skin it is working fine, but not with Elastic

**Comment by alecpl** [comment]
Did you get libkolab and libcalendaring from https://github.com/kolab-roundcube-plugins-mirror ? Note the mirror has built css files, the Kolab original repository does not. Are there any errors in browser console (Console and Network tabs)?

**Comment by aloksinha3110** [comment]
No there is no error in Console and Network tabs, yes i have clone it from here.

**Comment by alecpl** [comment]
Everything works perfectly fine for me after installing the plugin with composer. What browser are you using?
