### ISSUE TITLE
I have lost all my programmed responses

### ISSUE THREAD

**Issue by IAmBigAntoine** [roundcube/roundcubemail#8070]
Hello, I have lost all my programmed responses and the interface skin has changed without touching anything. I don't understand what happened. I just want to find all my programmed responses that I lost. Thank you in advance for your help ;)

**Comment by thomascube** [comment]
I'm sorry but you wrote to the wrong people. We don't host your e-mails and we're not responsible for the system you're using to access them. Please contact your internet hosting provider or IT responsible for first level support. If you don't know who this might be please review your bills and see who you are paying for email or web hosting services.

Roundcube is not a service but free software which your hosting provider installed on their servers.
