### ISSUE TITLE
IMAP: order folders with leading underscore

### ISSUE THREAD

**Issue by SoehnelS** [roundcube/roundcubemail#8072]
Hi,

not sure if it is a bug or just to live with:
I order my folders in Thunderbird by set one or more leading underscore(s) _ for important folders.

![thunderbird](https://user-images.githubusercontent.com/33517599/119229004-1ae7b700-bb16-11eb-8f0a-f28c79a6f199.JPG)

In RoundCube this sorting only worked, when I created theses folders in RoundCube (all in folder test),
no mater, if the folders with underscore created first or not.

Folders created in Thunderbird (all in folder test2), with leading underscore folders are not ordered like in Thunderbird.
(Maybe in order of creation, not sure yet.)

![rc_normal](https://user-images.githubusercontent.com/33517599/119229056-5c786200-bb16-11eb-9f87-0a6cf7d52480.JPG)

After some searching I found a solution for me at https://stackoverflow.com/questions/21416765/php-sort-filenames-with-an-underscore :

I inserted a function before sort_folder_list in rcube_imap.php:

`
function cmp($a, $b) {
      $aTemp = str_replace('_', '0', $a);
      $bTemp = str_replace('_', '0', $b);     
      return strcmp($aTemp,$bTemp);
}
`

and changed `uasort($folders, array($this, 'sort_folder_comparator'));`
to `uasort($folders, array($this, 'cmp'));`

The result matches my needs:
![rc_changed](https://user-images.githubusercontent.com/33517599/119229283-84b49080-bb17-11eb-80bd-1d324bc41c76.JPG)

My environment:
Windows 7
XAMPP PHP Version 7.4.15 (with or without php_intl.dll activated doesn't make difference, as far as I can say.)

Sorry for my "english".

Greetings!

**Comment by alecpl** [comment]
Hmm... Looks like the same is true for Linux. `__a` is after `_aa`, which is after `aaa`. So, maybe that's how the UTF8 collation rules in the locale system are defined?

However, if I change the code to use PHP's Collator, which is the case for Windows with Intl extension enabled (you can see that in `rcube_imap::sort_folder_comparator()`), it works as expected.

So, I'm surprised and I don't know what to do about it.

**Comment by SoehnelS** [comment]
Thanks for your reply.

Yes, I find out that the underscore is after alphanumerical signs, so that order is fine and for sure not a bug.

What I don't understand: did you reach the order of underscores on top of the list without any changes?
(That would mean, my intl-extension is not well used/activated in my environment.)

**Comment by alecpl** [comment]
> Yes, I find out that the underscore is after alphanumerical signs, so that order is fine and for sure not a bug.

Looks like so.

> What I don't understand: did you reach the order of underscores on top of the list without any changes?

Yes. I just removed the operating system condition, as I'm using Linux.

**Comment by SoehnelS** [comment]
Thanks at all! :)

I have to remind myself to keep an eye on it and change the underscore to something else
to use the UTF8 order without changing the code. :P

Thanks for your help and have a nice weekend! :)
