### ISSUE TITLE
Typo in German translation (attachment_reminder)

### ISSUE THREAD

**Issue by Virinum** [roundcube/roundcubemail#8075]
https://github.com/roundcube/roundcubemail/blob/a493a31d8462346d30d89b011adbfb67a73d46cf/plugins/attachment_reminder/localization/de_DE.inc#L19

It's _be**i**liegend_ instead of _beliegend_.

I know translations are managed with transifex. But my join request is now open since two weeks... What do I have to do to get this request accepted?

**Comment by alecpl** [comment]
Fixed.
