### ISSUE TITLE
Blocking external emails only for one subdomain

### ISSUE THREAD

**Issue by kennylajara** [roundcube/roundcubemail#8077]
I want to block any email send from the accounts under the domain internal.mydomain.com that are sent to any any external email. Example:

**Sender -> Receiver -> Expected result**
`john@mydomain.com` -> `peter@mydomain.com` -> OK
`john@mydomain.com` -> `peter@internal.mydomain.com` -> OK
`john@mydomain.com` -> `peter@sales.mydomain.com` -> OK
`john@mydomain.com` -> `peter@gmail.com` -> **OK**
`john@internal.mydomain.com` -> `peter@mydomain.com` -> OK
`john@internal.mydomain.com` -> `peter@internal.mydomain.com` -> OK
`john@internal.mydomain.com` -> `peter@sales.mydomain.com` -> OK
`john@internal.mydomain.com` -> `peter@gmail.com `-> **BLOCKED**
`john@sales.mydomain.com` -> `peter@mydomain.com` -> OK
`john@sales.mydomain.com` -> `peter@internal.mydomain.com` -> OK
`john@sales.mydomain.com` -> `peter@sales.mydomain.com` -> OK
`john@sales.mydomain.com` -> `peter@gmail.com `-> **OK**

I think I can do that with the access list plugin but I am not sure and I don't know how to use it.

How can I achieve that?

**Comment by alecpl** [comment]
There's no such feature in core. I would rather do such access control on the SMTP server side, not client.
