### ISSUE TITLE
[Q&A] Access OAuth token from plugin

### ISSUE THREAD

**Issue by mstilkerich** [roundcube/roundcubemail#8079]
Hello,

  to enable a single sign on solution, I would like to extend roundcube 1.5 open ID connectivity also to the carddav service (if configured by the admin). For that I need access to the access token acquired by roundcube. I saw there are hooks called upon token refresh and login, but otherwise the access token is available only in the session. Addressbook synchronization may be triggered in the background basically on any action by the user inside roundcube that accesses the addressbook, so the hooks are not sufficient for me.

My question: Can I consider `$_SESSION['oauth_token']['access_token']` a somewhat stable interface, or would you suggest another way for me to access that token? The plugin aims to be compatible with several stable roundcube releases (all since 1.2), so different interfaces between different roundcube versions mean trouble to me.

Ref mstilkerich/rcmcarddav#319

**Comment by thomascube** [comment]
> My question: Can I consider $_SESSION['oauth_token']['access_token'] a somewhat stable interface

Yes, the placement of the OAuth information in `$_SESSION['oauth_token']` can be considered stable and is actually meant for general access by Roundcube itself and by plugins.

If this answers your question, please close the issue.

**Comment by mstilkerich** [comment]
Thank you!
