### ISSUE TITLE
Feature request - Use openpgp-php by Enigma plugin

### ISSUE THREAD

**Issue by nicrame** [roundcube/roundcubemail#8080]
Hello.
I was trying to use Enigma plugin last days, and i even made it working a little bit (there was one problem with singed emails, it always said message is signed wrong). Finally i abandoned to use Enigma because few reasons:
- Security (Enigma give better security, but makes OS/hosting less secure)
I'm using suexec for every website (so php session is secure), and i'm trying block every one of them from accessing OS and software. For Enigma purposes i made jailkit account (jailkit is chrooting solution, that make copy of software inside user folder, so it can be closed to it's own main directory). But there was no instruction set for copying GnuPG with all libraries, so i had to do it manually. I didn't make it perfect because some PHP pear module didn't work correctly - because of that crypt-gpg-pinentry didn't work. By default all my websites have also blocked some PHP functions like system, shell_exec, passthru, exec, popen, proc_open... I can't do that when i use Enigma.

- Problems with singing messages
Like i said already, messages had correct public key in attachment, and were signed but message inside inbox were always detected as signed wrong. Even by Roundcube with Enigma itself (message sent to myself).

- Hard to maintain
While Enigma itself is not hard to do this, making every libs and executables fresh by hand isn't good solution (of course it is possible to do it by some script that would sync files).

So i was wondering, maybe there is some possibility to use this project instead of OS GnuPG:
https://github.com/singpolyma/openpgp-php

It looks like some good option, but i'm not coder. Maybe someone could just check, if it's there such option.

**Comment by alecpl** [comment]
This lib looks quite limited. By using a relatively thin wrapper on GnuPG we can get all features of GnuPG where needed. It's not possible with PHP implementation.
