### ISSUE TITLE
HTML rendering produces weird tags closes

### ISSUE THREAD

**Issue by carpincho** [roundcube/roundcubemail#8081]
Hi there!
We recently upgraded rc 1.2.0 to rc 1.4.11 under  php 7.2.24-0 ubuntu0.18.04.7
We found a weird behaviour of the html rendering.
When a email contains a link tag, the html sanitization washtml removes the closing anchor tag, creating big link until the end of the email content.
I've searched similar issues and only found #7982 but it's not the same issue and was closed with no resolution.

We tested using the following email content generated by gmail:
```
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">no link<br>
<br><a href="http://google.com">link</a><br>
<br>
no link<br></div>
```

Which produces the following rendering:
<img width="506" alt="Screen Shot 2021-05-29 at 17 14 58" src="https://user-images.githubusercontent.com/132033/120083810-b7bfcc80-c0a1-11eb-84b8-beac8758b50d.png">

the email text:
```
no link

link <http://google.com>

no link
```

But inspecting with firefox (dev edition) shows:
<img width="545" alt="Screen Shot 2021-05-29 at 17 19 55" src="https://user-images.githubusercontent.com/132033/120083866-243acb80-c0a2-11eb-81a5-adb086f9618d.png">

Any clue on whats going on here?

Regards,

**Comment by alecpl** [comment]
Weird, these "html ignored" comments. I'm unable to reproduce using PHP 7.4. We'd need some debug info like I asked in https://github.com/roundcube/roundcubemail/issues/7982#issuecomment-817521541

**Comment by carpincho** [comment]
Thanks Alek.
I don't fully understand why but 1.4.11 is no more producing the before mention weird behaviour.
However, 1.2.0 version does it.
Nevertheless, we will keep with 1.4.11 version.
Thanks for your time!

**Comment by jimmyjam-50066** [comment]
![image](https://github.com/roundcube/roundcubemail/assets/153751346/e1aa825e-d06e-47fc-a5aa-4dc71cf52640)


I'm getting the same thing with roundcube 1.6.1 on php 7.4

I'll provide anything else I can.
