### ISSUE TITLE
Restore convenient toggle to show/hide preview pane

### ISSUE THREAD

**Issue by Beckfield** [roundcube/roundcubemail#8082]
Several years ago, you changed the design of Roundcube, taking away a very convenient toggle in the interface to show or hide the Preview pane without having to dive into settings.  I complained about that change at the time, but it fell on deaf ears.  I'm asking again to please restore this greatly-missed feature.

**Comment by alecpl** [comment]
We do not plan to implement this in core, but there's a plugin that will work with 1.5. https://github.com/johndoh/roundcube-elasticlayouts
