### ISSUE TITLE
Filter wont work when target folder has umlauts

### ISSUE THREAD

**Issue by b90g** [roundcube/roundcubemail#8085]
When the target folder has an umlaut in it, the filter script changes the character  from `ü` to `&APw-`. 
With this the filter does not work. 
Changing it back to an umlaut makes the script work,
 but in the regular filter display the folder name is completely gone.

**Comment by alecpl** [comment]
```
// Sieve RFC says that we should use UTF-8 encoding for mailbox names,
// but some implementations does not covert UTF-8 to modified UTF-7.
// Defaults to UTF7-IMAP
$config['managesieve_mbox_encoding'] = 'UTF-8';
```
