### ISSUE TITLE
[Translation] CSFR > CSRF

### ISSUE THREAD

**Issue by williamdes** [roundcube/roundcubemail#8086]
https://github.com/roundcube/roundcubemail/search?q=CSFR

**Comment by alecpl** [comment]
Fixed.

**Comment by williamdes** [comment]
Ref: https://github.com/roundcube/roundcubemail/commit/fca2a8b826a9452faff5c6a3f5d46ebc72b09926#diff-f724245d68c611f0dbff5e95e7a41c17bab48058ee418fba52f2146ae19f8230

Thank you
