### ISSUE TITLE
Forward Plugin

### ISSUE THREAD

**Issue by aloksinha3110** [roundcube/roundcubemail#8087]
Hello
Is there any plugin in Roundcube from where I can frwd the email on the basis of the subject line?

**Comment by alecpl** [comment]
You mean automatically send the message to another email address when it's received? The Managesieve plugin or https://github.com/gianlucagiacometti/roundcube-toolbox.

**Comment by aloksinha3110** [comment]
Not working

**Comment by aloksinha3110** [comment]
DATABASE ERROR: CONNECTION FAILED!
Unable to connect to the database!
Please contact your server-administrator.

**Comment by aloksinha3110** [comment]
![image](https://user-images.githubusercontent.com/59638727/120910579-89438200-c69d-11eb-8a26-cee31bfdc636.png)

What is the issue in this?

**Comment by gianlucagiacometti** [comment]
Can you please open the issue in the plugin repository? This is not the right place.

**Comment by aloksinha3110** [comment]
@gianlucagiacometti I have created, can you please respond to me.
