### ISSUE TITLE
Cannot search marked messages

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#8091]
I need to review and count the messages in my inbox that I have marked, ie. set a red flag on. This doesn't seem to be possible at all. I can only mark/unmark messages but never use that feature for any search filter. I see that I can select such messages but that doesn't help me because I don't want to move or delete them, and they spread across multiple pages already. The only filter I can set is for unread messages. Other mail apps even show me the number of marked messages without me asking it.

**Comment by alecpl** [comment]
Of course it is possible. There's "Type" selector in Search Options (the "v" icon on the right of the search box).
