### ISSUE TITLE
Markasjunk no file created in temp folder

### ISSUE THREAD

**Issue by Lejooohn** [roundcube/roundcubemail#8093]
Hi !

I trying to configure markasjunk with a new Roundcube instance (1.4.11 and 2.0 for markasjunk) like it worked on my previous Roundcube instance. I had used markasjunk2 with 'cmd_learn" driver which is in 1.3.9 and markasjunk2 in 1.11.1.

I would like to keep the way i used to add/edit email in user_prefs file and to do that i just used this command : 

'filepath=%f;file=${filepath##*/};scp -i /var/www/.ssh/id_rsa %f amavis@MAILSERVER:/var/spool/amavisd/.temp/ && /usr/bin/ssh -i /var/www/.ssh/id_rsa amavis@MAILSERVER "/var/spool/amavisd/sa/extract.sh bl "/var/spool/amavisd/.temp/$file" && /usr/local/bin/sa-learn --dbpath /var/spool/amavisd/.spamassassin --spam "/var/spool/amavisd/.temp/$file";rm -f "/var/spool/amavisd/.temp/$file" 2>&1"';

Where %f variable it's correctly work for example : "/var/www/html/roundcubemail-1.4.11/temp/rcmSALearnPlY8GD" and $file is "rcmSALearnPlY8GD"

My problem actually is simple, no file is created in "/var/www/html/roundcubemail-1.4.11/temp/" when i use "Junk" button while the permissions since to be correct : 

12751809 drwxrwxr-x  2 www-data www-data    6 juin   8 11:21 temp/

and the tmp directory correctly set in config.inc.php : 

$config['temp_dir'] = 'temp/';

Does anyone have an idea for me? :D

Regards,

**Comment by alecpl** [comment]
I don't know, but I would suggest:
1. Enable markasjunk_debug. Maybe you'll find something relevant in logs/markasjunk.
2. Write a shell script and use it instead of this very long command.
3. Did you actually check the error log?

**Comment by Lejooohn** [comment]
Hi @alecpl 

I already enabled the debug mode and the content it's just the same thing i have put in "$config['markasjunk_spam_cmd']" or "$config['markasjunk_ham_cmd']" so not very helpful.

Ya i can do a script instead of use a long command but i don't think the problem is linked.

The error log tell nothing related to my problem :(

I have just tested to check if the plugin is able to write in temp directory : 

$config['markasjunk_spam_cmd'] = 'touch /var/www/html/roundcube/temp/testfile';

And after using the "Junk" button : 

/var/www/html/roundcube/temp # ls -al
total 4
drwxr-xr-x  2 www-data www-data   22 juin   9 11:25 .
drwxr-xr-x 13 www-data www-data 4096 juin   9 10:40 ..
-rw-r--r--  1 www-data www-data    0 juin   9 11:25 testfile

So the issue still beeing weird.

With my old instance of Roundcube, when i use the junk button a random file with a base name "rcmAttmnt" is created in temp directory. It's seems it's not the case with the new instance. Maybe it's a new behaviour related to the difference of the versions?

Regards

**Comment by Lejooohn** [comment]
I just modified the cmd to see what's happening when i use the junk button and the behaviour seems to be the same as the old instance (except the created file never exist. 

in the config.inc.php :

$config['markasjunk_spam_cmd'] = 'filepath=%f ; echo "SPAM - file path is : $filepath" >> /var/log/debug_junk.log ; file="$(basename -- $filepath)" ; echo "SPAM - name of file is : $file"  >> /  var/log/debug_junk.log 2>&1';

$config['markasjunk_ham_cmd'] = 'filepath=%f ; echo "HAM - filepath is : $filepath" >> /var/log/debug_junk.log ; file="$(basename -- $filepath)" ; echo "HAM - name of file is : $file"  >> /var/  log/debug_junk.log 2>&1';

In the log file : 

SPAM - file path is : /var/www/html/roundcubemail-1.4.11/temp/rcmSALearnUAl5RK
SPAM - name of file is : rcmSALearnUAl5RK
HAM - filepath is : /var/www/html/roundcubemail-1.4.11/temp/rcmSALearnvLCciE
HAM - name of file is : rcmSALearnvLCciE

**Comment by alecpl** [comment]
The file is being removed by the plugin after executing the command.

**Comment by Lejooohn** [comment]
Ya but it i do a cp of this file like that : 

$config['markasjunk_spam_cmd'] = 'filepath=%f ; cp $filepath /var/www/html/webmailacweb/tmp-test/ ';

It should work no? Because currently i'm unable to keep this file before it's removed by the script

**Comment by alecpl** [comment]
Is this other location writeable?

**Comment by Lejooohn** [comment]
Yes the location is writeable by the web server. In fact after multiple tests i managed to make the cp work so i use a different tmp directory to store the mail file (originally the %f).

There is still a problem for what i want to do and it's to scp the file on another server (like you can see in my first post).

If i try a cmd like that it's doesn't work (i used an existing file for the test) : 

$config['markasjunk_spam_cmd'] = 'scp -i /var/www/.ssh/id_rsa /var/www/html/roundcube/tmp/rcmSALearnA02UQH amavis@mailserver:/var/spool/amavisd/.temp/';

- I already tried : 
- to use /usr/bin/scp
- to use the directly path ("roundcube" is a symlink pointing on the last version of roundcube)
- call the scp command via a bash script (the bash script contain the same scp command)

Before i used "scp %f..." but like i said it's doesn't work anymore on my new instance so that's why i decide to use a workaround an copy this file to a another temporary directory.

There is a way to run the scp?

**Comment by alecpl** [comment]
I don't know, but this is out of scope of this issue tracker.
