### ISSUE TITLE
Mail delivery failed: returning message to sender

### ISSUE THREAD

**Issue by Max3jaik** [roundcube/roundcubemail#8094]
when people send mail, i receive the mail but the sender still receive Mail delivery failed: returning message to sender

![Untitled](https://user-images.githubusercontent.com/85567199/121200420-4c96a700-c8a6-11eb-8260-9f7f8a812ee4.jpg)

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
