### ISSUE TITLE
virtual plugin broken in beta 1.5?

### ISSUE THREAD

**Issue by mtissington** [roundcube/roundcubemail#8097]
I am running 1.5 beta and trying to setup the `virtual` plugin. It seems very unpredictable. I only have virtual mailboxes and trying to get virtual folders like `All Mail` or `Flagged` working. 

I have it working on a single mailbox but failing on others.

This is the namespace

    # virtual folders namespace
      namespace {
      prefix = virtual/
      separator = /
      location = virtual:~/Maildir/virtual
       }

this is the error I get (lots) .. is this a bug or config error?

`Jun 09 21:47:29 imap(michael@example.com)<13231><Z2WfFmLERtW5lIGz>: Panic: file mail-index-sync.c: line 413 (mail_index_sync_begin_to2): assertion failed: (!index->syncing)

Jun 09 21:47:29 imap(michael@example.com)<13231><Z2WfFmLERtW5lIGz>: Error: Raw backtrace: /usr/lib/dovecot/libdovecot.so.0(+0xdb73b) [0x7f18e0fe073b] -> /usr/lib/dovecot/libdovecot.so.0(+0xdb7d1) [0x7f18e0fe07d1] -> /usr/lib/dovecot/libdovecot.so.0(+0x4a199) [0x7f18e0f4f199] -> /usr/lib/dovecot/libdovecot-storage.so.0(+0x497b7) [0x7f18e10dd7b7] -> /usr/lib/dovecot/libdovecot-storage.so.0(mail_index_sync_begin_to+0x53) [0x7f18e11854e3] -> /usr/lib/dovecot/libdovecot-storage.so.0(mail_index_sync_begin+0x1f) [0x7f18e118555f] -> /usr/lib/dovecot/modules/lib20_virtual_plugin.so(virtual_storage_sync_init+0x1c6) [0x7f18e0d12246] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_sync_init+0x57) [0x7f18e10f0497] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_sync+0x37) [0x7f18e10f0547] -> /usr/lib/dovecot/libdovecot-storage.so.0(index_storage_get_status+0x31) [0x7f18e1169ba1] -> /usr/lib/dovecot/modules/lib20_virtual_plugin.so(+0xa655) [0x7f18e0d0f655] -> /usr/lib/dovecot/libdovecot-storage.so.0(+0xba7fb) [0x7f18e114e7fb] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_get_status+0x37) [0x7f18e10f0977] -> /usr/lib/dovecot/modules/lib20_virtual_plugin.so(virtual_storage_sync_init+0x12d0) [0x7f18e0d13350] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_sync_init+0x57) [0x7f18e10f0497] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_sync+0x37) [0x7f18e10f0547] -> /usr/lib/dovecot/libdovecot-storage.so.0(index_storage_get_status+0x31) [0x7f18e1169ba1] -> /usr/lib/dovecot/modules/lib20_virtual_plugin.so(+0xa655) [0x7f18e0d0f655] -> /usr/lib/dovecot/libdovecot-storage.so.0(+0xba7fb) [0x7f18e114e7fb] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_get_status+0x37) [0x7f18e10f0977] -> /usr/lib/dovecot/modules/lib20_virtual_plugin.so(virtual_storage_sync_init+0x12d0) [0x7f18e0d13350] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_sync_init+0x57) [0x7f18e10f0497] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_sync+0x37) [0x7f18e10f0547] -> /usr/lib/dovecot/libdovecot-storage.so.0(index_storage_get_status+0x31) [0x7f18e1169ba1] -> /usr/lib/dovecot/modules/lib20_virtual_plugin.so(+0xa655) [0x7f18e0d0f655] -> /usr/lib/dovecot/libdovecot-storage.so.0(+0xba7fb) [0x7f18e114e7fb] -> /usr/lib/dovecot/libdovecot-storage.so.0(mailbox_get_status+0x37) [0x7f18e10f0977] -> dovecot/imap(imap_status_get+0x7b) [0x56015833eefb]

Jun 09 21:47:29 imap(michael@example.com)<13231><Z2WfFmLERtW5lIGz>: Fatal: master: service(imap): child 13231 killed with signal 6 (core dumps disabled - https://dovecot.org/bugreport.html#coredumps)

Jun 09 21:47:44 imap(michael@example.com)<13233><fkWQF2LEWNa5lIGz>: Panic: file mail-index-sync.c: line 413 (mail_index_sync_begin_to2): assertion failed: (!index->syncing)

`

**Comment by alecpl** [comment]
We do not support this plugin here.
