### ISSUE TITLE
Inconsistent handling of contact group names on compose autocomplete vs address book widget

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#8098]
When a group name contains an @ sign (regardless of if its a valid email address or not) and you add it as a recipient to your email via auto complete then both the group name and the group members will be populated in the To: box.

If you add the group to the To: box using the address book widget then there is no expansion, just that group name added as a recipient in the To: field.

I think the behavior should be consistent between the 2 methods and since the presence of an @ sign does not mean valid email address then either that check needs to be improved or the group name ignored and the members always expanded.

Tested in git-master

**Comment by alecpl** [comment]
This may be Elastic-only issue?

**Comment by johndoh** [comment]
the difference in group expanded/not expanded the same in all skins the group name containing an @ not being removed with autocomplete is Elastic only.

**Comment by alecpl** [comment]
Fixed.
