### ISSUE TITLE
SMTP Error (550)

### ISSUE THREAD

**Issue by BrunosGallery** [roundcube/roundcubemail#8103]
Hi,
For several days now my Roundcube webmail cannot send emails. The following message keeps popping up:
An error occurred.
SMTP Error (550): Failed to add recipient "indicates the email address to where the email could not be sent" (5.7.1 <webmail18.sd4.0x35.net[10.200.201.18]>: Client host rejected: Blacklisted user: indicates my email address).

Can you please fix this and explain why I am now getting this error?

Thank you in advance for your support.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

ps. this looks like SMTP server problem not Roundcube problem.
