### ISSUE TITLE
Bug on install with MYSQL

### ISSUE THREAD

**Issue by railsonrdr** [roundcube/roundcubemail#8104]
I try install in mysql, but identified a bug if the password contains '%'.

In DSN string 'mysql://roundcube:pass%23#@test.com/roundcube' and retrieve the error Access denied for user 'roundcube'@'%'

On the code of connect rcube_db::factory (/installer/test.php:130) the password is changed from 'pass%23#' to 'pass#', the '%23' is removed automaticaly of the attributes of rcube_db object in the keys ('db_dsnw_array' and 'db_dsnr_array').

I used roundcube version 1.4.11 and php7.4 and mysql Ver 15.1 Distrib 10.1.26-MariaDB,

Sorry for my english.

**Comment by alecpl** [comment]
User and password in DSN have to be URI-encoded. I.e. replace `%` with `%25`.
