### ISSUE TITLE
Cannot Send Out Email

### ISSUE THREAD

**Issue by TOLSLOGISTICS** [roundcube/roundcubemail#8109]
We experience problem sending out email or replying back to emails.

The error msg says "An error occurred while saving sent message. Server Error: APPEND: Internal error occurred." How can this be resolved?

![image](https://user-images.githubusercontent.com/86854467/124323556-7cf0fe80-db4f-11eb-8469-136f515921d1.png)

**Comment by alecpl** [comment]
"Internal error occurred" comes from the IMAP server. Not Roundcube issue.
