### ISSUE TITLE
Failed to load class GuzzleHttp\Client

### ISSUE THREAD

**Issue by quenenni** [roundcube/roundcubemail#8112]
Hello,

I tried to install v1.5-beta (new install), but the first page of the installer shows me:
```
GuzzleHttp\Client:  NOT OK(Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle)
```

All the other options are green.

I tried the complete version and then the not complete version with composer to install the dependencies.

I can see the ./vendor/guzzle folder.

sudo -u www-data php composer.phar show | grep guzzle
```
guzzlehttp/guzzle                  6.5.5    Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.4.1    Guzzle promises library
guzzlehttp/psr7                    1.8.2    PSR-7 message implementation that also provides common utility methods
```

tried these commands too:
```
sudo -u www-data php composer.phar require "roundcube/plugin-installer:>=0.2.0"
sudo -u www-data php composer.phar reinstall guzzlehttp/guzzle
sudo -u www-data php composer.phar update
```

And I installed roundcube v1.4.11 successfully just before. I don't remember though if there was a guzzle line or not during the checks.

--
Debian 10
PHP 7.3.27-1~deb10u1
Nginx/1.14.2

--
Big thanks for this amazing software.

**Comment by quenenni** [comment]
Well, I just had to write a ticket to find the answer.

I restarted 2 services for something else and it fixes my problem with guzzle.
```
systemctl restart php7.3-fpm
systemctl restart nginx
```

I think only one is necessary, the php-fpm, but I can't be sure as I did both before noticing the change.
And I didn't know I had to restart it after using composer.

Sorry for the noise.

**Comment by piiskop** [comment]
As of tonight, the issue should still be open as roundcubemail doesn't find it:

GuzzleHttp\Client:  NOT OK(Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle)

**Comment by giox069** [comment]
Just upgraded to roundcube 1.6.0 via bin/installto.sh script, running on Ubuntu 22.04, and /installer test reports

Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle

How do I solve it ?

**Comment by ureman2** [comment]
оно до сих пор актуально
