### ISSUE TITLE
Sendmail authenticating with DKIM but Roundcube is not authenticating

### ISSUE THREAD

**Issue by Raavtube** [roundcube/roundcubemail#8113]
So I have set up the mail server, Roundcube, and Sendmail both work as expected.
Many of my messages were going to SPAM so I wanted to set up DKIM, which I did and I got no errors.
First I tested it with Roundcube and sent an email to my Gmail account, when I click on the See Original section of the Gmail email, it doesn't show DKIM 'PASS' with domain mydomain.com

But when I send in the terminal with Sendmail it does show under DKIM: 'PASS' with domain mydomain.com

https://pastebin.pl/view/5d87eb76 <- the pastebin contains the Full Messages for the Sendmail email (good) and the roundcube email (bad)

**Comment by alecpl** [comment]
Roundcube is a client, it has nothing to do with DKIM.

**Comment by Raavtube** [comment]
Doesn't roundcube send with Sendmail?

**Comment by johndoh** [comment]
You are missing the point. Roundcube is a mail client. DKIM signing is the responsibility of the SMTP server. You say in your case that's Sendmail so you need to check you Sendmail logs/config to figure out why that is.
