### ISSUE TITLE
Emails showing as sent but not reaching inbox of recipient

### ISSUE THREAD

**Issue by HU101IE** [roundcube/roundcubemail#8118]
I have sent multiple emails recently to multiple recipients, all at the same organisation at my new workplace, as well as their tech support team. None of them arrived. There is no evidence of bounce. I sent a test email to my work email there, it did not arrive. I sent a test email to a yahoo account, that email arrived but went to spam. The organisation's tech support team did a trace and the emails are not caught by spam or filters. I had previously emailed with the organisation and that worked fine, but for the past 30 days or so, none of my emails have reached none of the recipients. I am not sure what the issue could be as it is isolated to (seemingly) a couple of organisations and the tech support there say the emails have never reached their system. Any corrective action I could take or investigate are highly appreciated. I have access to roundcube email via my homestead account.

**Comment by johndoh** [comment]
What's the Roudcube issue here? Roundcube is a mail client and you are describing spam filtering issues on the receivers end. Ask the receiver why the message was treated as spam, check your SMTP server logs, or contact your email provider for support.
