### ISSUE TITLE
[1.5rc] Actions > Edit as new on message with attachments does not allow to remove attachments

### ISSUE THREAD

**Issue by ilgrosso** [roundcube/roundcubemail#8119]
How to reproduce:

1. select a message from the Sent folder, with attachment(s)
2. Actions > Edit as new
3. from the Edit window, click on the trashcan icon to remove one or more attachments
4. nothing happens

It happens with 1.5 beta / rc and elastic skin, it was working with earlier versions.

**Comment by alecpl** [comment]
Works for me. Any errors in browser console or Roundcube logs? Does it work with all plugins disabled? Does it work in a different browser?

**Comment by alecpl** [comment]
@ilgrosso  Any errors in browser console or Roundcube logs? Where you say "nothing happens" is there a http request made at all?

**Comment by ilgrosso** [comment]
@alecpl I am afraid nothing in browser's console neither in server logs; I actually verified the problem occurs even by adding an attachment to a new e-mail and then attempting to remove such attachment.

For some reason, it seems that JS like this:

```js
return rcmail.command(
'remove-attachment','rcmfile206901676760f51705f31552a8350bb1cd47cf1a8e2de608705810d', this, event)
```

is not taking any effect nor producing any message in the logs.

**Comment by alecpl** [comment]
Please, check if Rename or Download actions work (via the attachment Options menu) or whether it is possible to use other commands e.g. Save or Spell buttons.

**Comment by ilgrosso** [comment]
* Rename and Download actions are working fine
* other buttons like Save / SpellCheck / Attach / ... from topbar are also working

**Comment by alecpl** [comment]
Let's reiterate. When you rename attachment there is a http request send, but when you delete there is none?

**Comment by ilgrosso** [comment]
@alecpl I made a short GIF to summarize what I am experiencing:

* composing a new e-mail
* select file to attach: it works (you can see the JS call under the Network tab)
* select file to drop: while the JS call is 200, the file remains there

![Screencast-2021-07-20-092734](https://user-images.githubusercontent.com/1064664/126279849-26708599-2a6d-416c-821a-27575a9860b4.gif)

**Comment by alecpl** [comment]
So, the request is being send. The Console tab is empty after this action? I'd like to see the request and response data.

**Comment by ilgrosso** [comment]
#### Request headers
```
POST /roundcube/?_task=mail&_action=remove-attachment HTTP/1.1
Host: sra.tirasa.net
Connection: keep-alive
Content-Length: 116
sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"
DNT: 1
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept: application/json, text/javascript, */*; q=0.01
X-Roundcube-Request: msEC36NgsRbB4VL6Ga98UViZcl5WNisv
X-Requested-With: XMLHttpRequest
Origin: https://sra.tirasa.net
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: https://sra.tirasa.net/roundcube/?_task=mail&_action=compose&_id=167338059660f681c5bb739
Accept-Encoding: gzip, deflate, br
Accept-Language: it-IT,it;q=0.9
Cookie: colorMode=dark; language=it; roundcube_sessid=e9qaunlvc19eq9o6a6esask8i7; roundcube_sessauth=ZPpftZOFj7diVPer9wIYqXCLoe-1626767700
```

#### Response headers
```
HTTP/1.1 200 OK
Date: Tue, 20 Jul 2021 07:57:03 GMT
Server: Apache/2.4.29 (Ubuntu)
Expires: Tue, 20 Jul 2021 07:57:03 GMT
Cache-Control: private, no-cache, no-store, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Last-Modified: Tue, 20 Jul 2021 07:57:03 GMT
X-DNS-Prefetch-Control: off
Referrer-Policy: same-origin
X-Frame-Options: sameorigin
Content-Length: 40
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json; charset=UTF-8
```

### Response body
```js
{"action":"remove-attachment","exec":""}
```

**Comment by alecpl** [comment]
And the POST/request data?

**Comment by ilgrosso** [comment]
Sorry, forgot to paste:

```_id=167338059660f681c5bb739&_file=rcmfile167338059660f681c5bb7396dd32bc934baad439d2ccbbd7a30e92c&_remote=1&_unlock=0```

**Comment by alecpl** [comment]
Ok, so the client-side looks fine. The response is not what I expect, though. Either there's something wrong with session so it can't find the attachment or with deleting the attachment. What plugins are you using? You said you tested with all plugins disabled. In such a case the default filesystem_attachments plugin will be used to handle attachments. It might be hard to investigate the reasons.

I suggest to add `rcube::console($attachment);` in `program/actions/mail/attachment_delete.php`, a line after both places where the variable is set.

**Comment by ilgrosso** [comment]
After adding the console statements suggested above, the following appears in `console.log`:

```
[20-Jul-2021 10:46:16 +0200]: <5h7n8ged> array (
  'path' => '/var/www/roundcube/temp/RCMTEMPattmnt60f68d55efb90323971921',
  'name' => 'file.pdf',
  'size' => 97556,
  'mimetype' => 'application/pdf',
  'group' => '154507526460f68d517742f',
  'id' => '11626770773098254700',
)
[20-Jul-2021 10:46:16 +0200]: <5h7n8ged> array (
  'path' => '/var/www/roundcube/temp/RCMTEMPattmnt60f68d55efb90323971921',
  'name' => 'file.pdf',
  'size' => 97556,
  'mimetype' => 'application/pdf',
  'group' => '154507526460f68d517742f',
  'id' => '11626770773098254700',
  'abort' => false,
  'status' => true,
)
```

**Comment by ilgrosso** [comment]
FTR I see that the temp file is effectively removed from server filesystem after clicking the trashcan icon, even though nothing seems to change in the UI,

**Comment by alecpl** [comment]
Yeah, it looks that it removes the attachment, but does not pass the `if (!empty(self::$COMPOSE['attachments'][self::$file_id])) {` condition. You can try to add `rcube::console(self::$COMPOSE['attachments']);`. It looks like some session issue now.

**Comment by ilgrosso** [comment]
the new console statement reports

```
[20-Jul-2021 10:54:48 +0200]: <5h7n8ged> NULL
```

**Comment by alecpl** [comment]
Strange. What PHP version? Is Opcache enabled? If yes, try with disabled.

**Comment by ilgrosso** [comment]
PHP 7.2, opcache disabled

**Comment by alecpl** [comment]
This `if` statement is redundant anyway. You can remove it, leaving the code inside.

**Comment by ilgrosso** [comment]
After removing the `if` statement, all seems to be ok, thanks!

**Comment by alecpl** [comment]
Fixed.
