### ISSUE TITLE
1.5rc MySQL upgrade fails applying 2020020100

### ISSUE THREAD

**Issue by Philippe23** [roundcube/roundcubemail#8120]
I'm trying to upgrade from 1.4.11 to 1.5_rc and I'm getting an error.

I may have tried to upgrade to 1.5_beta at some point and abandoned it -- I can't remember if I backed out before or after running the DB upgrade.

This is a long running install, years and years.  So some strange edge case may have bubbled up.

Any advice would be greatly appreciated.

```
What version are you upgrading from? Type '?' if you don't know.
1.4.11
Executing database schema update.
Updating database schema (2020020100)... [FAILED]
ERROR: Error in DDL upgrade 2020020100: [1067] Invalid default value for 'created'
```
```
mysql> SELECT * FROM `system`;
+-------------------+------------+
| name              | value      |
+-------------------+------------+
| roundcube-version | 2019092900 |
+-------------------+------------+
1 row in set (0.00 sec)
```
```
$ mysql -V
mysql  Ver 8.0.23 for Linux on x86_64 (Gentoo Linux mysql-8.0.23)
```

**Comment by Philippe23** [comment]
Looks like it's related to issue https://github.com/roundcube/roundcubemail/issues/5833 -- so I guess I count as an ancient install.  ;-)
```
mysql> SELECT TABLE_NAME, COLUMN_NAME,COLUMN_DEFAULT FROM information_schema.columns WHERE TABLE_SCHEMA='roundcubemail' AND COLUMN_DEFAULT='0000-00-00 00:00:00'
;
+------------+-------------+---------------------+
| TABLE_NAME | COLUMN_NAME | COLUMN_DEFAULT      |
+------------+-------------+---------------------+
| contacts   | changed     | 0000-00-00 00:00:00 |
| session    | changed     | 0000-00-00 00:00:00 |
| users      | created     | 0000-00-00 00:00:00 |
+------------+-------------+---------------------+
3 rows in set (0.00 sec)
```

**Comment by Philippe23** [comment]
With the above output, the following worked for me:

Step 0: back up data
Step 1: Identify tables: 
```
SELECT TABLE_NAME, COLUMN_NAME,COLUMN_DEFAULT FROM information_schema.columns WHERE TABLE_SCHEMA='roundcubemail' AND COLUMN_DEFAULT='0000-00-00 00:00:00';
```
```
+------------+-------------+---------------------+
| TABLE_NAME | COLUMN_NAME | COLUMN_DEFAULT      |
+------------+-------------+---------------------+
| contacts   | changed     | 0000-00-00 00:00:00 |
| session    | changed     | 0000-00-00 00:00:00 |
| users      | created     | 0000-00-00 00:00:00 |
+------------+-------------+---------------------+
3 rows in set (0.00 sec)
```
Step 2: Check those tables for warm and fuzzies.  (This may just be a security blanket that doesn't help):
```
mysql> CHECK TABLE session;
+-----------------------+-------+----------+----------+
| Table                 | Op    | Msg_type | Msg_text |
+-----------------------+-------+----------+----------+
| roundcubemail.session | check | status   | OK       |
+-----------------------+-------+----------+----------+
1 row in set (0.00 sec)

mysql> CHECK TABLE contacts;
+------------------------+-------+----------+----------+
| Table                  | Op    | Msg_type | Msg_text |
+------------------------+-------+----------+----------+
| roundcubemail.contacts | check | status   | OK       |
+------------------------+-------+----------+----------+
1 row in set (0.00 sec)

mysql> CHECK TABLE users;
+---------------------+-------+----------+----------+
| Table               | Op    | Msg_type | Msg_text |
+---------------------+-------+----------+----------+
| roundcubemail.users | check | status   | OK       |
+---------------------+-------+----------+----------+
1 row in set (0.01 sec)
```
Step 3: Alter tables so defaults are not all zeroes -- so that they're `1000-01-01 00:00:00'` and match https://github.com/roundcube/roundcubemail/commit/37974e2490ef20c0155d5461a316bcf940da2773:
```
mysql> ALTER TABLE `session` MODIFY COLUMN `changed` datetime NOT NULL DEFAULT '1000-01-01 00:00:00';
Query OK, 0 rows affected (0.16 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE `contacts` MODIFY COLUMN `changed` datetime NOT NULL DEFAULT
'1000-
Query OK, 0 rows affected (0.05 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> ALTER TABLE `users` MODIFY COLUMN `created` datetime NOT NULL DEFAULT '1000-01-01 00:00:00';
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
Step 4: Run `update.sh` again: 
```
What version are you upgrading from? Type '?' if you don't know.
1.4.11
Executing database schema update.
Updating database schema (2020020100)... [OK]
Updating database schema (2020020101)... [OK]
Updating database schema (2020091000)... [OK]
Updating database schema (2020122900)... [OK]
NOTICE: Update dependencies by running `php composer.phar update --no-dev`
This instance of Roundcube is up-to-date.
Have fun!
```

**Comment by Philippe23** [comment]
Seems like it wouldn't hurt to add the "MODIFY COLUMN" commands to https://github.com/roundcube/roundcubemail/blob/1.5-beta/SQL/mysql/2020020100.sql -- I presume I hit this because that modified the `users` table.

But I could also buy that this is only hitting me and now because of a very specific dance of MySQL and Roundcube upgrade timings.

**Comment by alecpl** [comment]
The other ticket points to a commit that updated the defaults in all tables. It was in 0.7.4.

Yes. We just assume it's some old quirk, and we don't see much of such installations. Thanks for describing the fixing process for others.

**Comment by mlecki-sst** [comment]
Sorry for reheating a closed issue but my install must count as ancient! Can anyone advise how to get arround this SQL error:



`mysql> SELECT TABLE_NAME, COLUMN_NAME,COLUMN_DEFAULT FROM information_schema.columns WHERE TABLE_SCHEMA='roundcubemail' AND COLUMN_DEFAULT='0000-00-00 00:00:00';
+------------+-------------+---------------------+
| TABLE_NAME | COLUMN_NAME | COLUMN_DEFAULT      |
+------------+-------------+---------------------+
| users      | created     | 0000-00-00 00:00:00 |
| users      | last_login  | 0000-00-00 00:00:00 |
+------------+-------------+---------------------+
2 rows in set (0.01 sec)

mysql> ALTER TABLE `users` MODIFY COLUMN `created` datetime NOT NULL DEFAULT '1000-01-01 00:00:00';
ERROR 1067 (42000): Invalid default value for 'last_login'
mysql> ALTER TABLE `users` MODIFY COLUMN `last_login` datetime NOT NULL DEFAULT '1000-01-01 00:00:00';
ERROR 1067 (42000): Invalid default value for 'created'
mysql>`
