### ISSUE TITLE
Roundcube does not work with Imap self signed certificates

### ISSUE THREAD

**Issue by brucealthompson** [roundcube/roundcubemail#8121]
I have a local mail server that uses self signed certificates. The mail server is working fine with tls and other mail applications such as Nextcloud mail. I have also gotten smtp on the mail server to work with roundcube using tls / StartTLS using the attached smtp config.
[config.inc.php.smtptls.txt](https://github.com/roundcube/roundcubemail/files/6777351/config.inc.php.smtptls.txt)

The above config also works with imap since it is not using SSL/TLS.

I am NOT able to get imap  on the mail server to work with roundcube using tls / StartTLS using the attached imap config.
[config.inc.php.imaptls.txt](https://github.com/roundcube/roundcubemail/files/6777378/config.inc.php.imaptls.txt)

Other people have had the same issue and given up. See this article:
https://myrtana.sk/articles/roundcube-ssl-buster

If there is a config that works with self signed certificates and IMAP, I don't think it is documented anywhere.

**Comment by alecpl** [comment]
`$config['default_host'] = 'tls://localhost';`

**Comment by brucealthompson** [comment]
Silly me. A typo.

Thank you very much.
