### ISSUE TITLE
Incidents during update to 1.5rc 

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#8122]
I have upgraded from 4.11 to 1.5rc and it appears this: 

Running update script at target...
Executing database schema update.
Updating database schema (2020020100)... [OK]
Updating database schema (2020020101)... [OK]
ERROR: Error in DDL upgrade 2020091000: [1050] Table 'collected_addresses' already exists
Updating database schema (2020091000)... [FAILED]
All done.

composer update:
Creating database schema... ERROR: [1050] Table 'collected_contacts' already exists (SQL Query: CREATE TABLE `collected_contacts` (
 `contact_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
 `changed` datetime NOT NULL DEFAULT '1000-01-01 00:00:00',
 `del` tinyint(1) NOT NULL DEFAULT '0',
 `name` varchar(128) NOT NULL DEFAULT '',
 `email` text NOT NULL,
 `firstname` varchar(128) NOT NULL DEFAULT '',
 `surname` varchar(128) NOT NULL DEFAULT '',
 `vcard` longtext NULL,
 `words` text NULL,
 `user_id` int(10) UNSIGNED NOT NULL,
 PRIMARY KEY(`contact_id`),
 CONSTRAINT `user_id_fk_collected_contacts` FOREIGN KEY (`user_id`)
   REFERENCES `users`(`user_id`) ON DELETE CASCADE ON UPDATE CASCADE,
 INDEX `user_collected_contacts_index` (`user_id`,`del`)
) /*!40000 ENGINE=INNODB */ /*!40101 CHARACTER SET utf8 COLLATE utf8_general_ci */)
[FAILED]
ERROR: [1050] Table 'collected_contacts' already exists

I understand that it is related to the sblaisot/automatic_addressbook plugin that I had activated. 

Now my contact groups appear in this way and apparently I have not lost any of the previously collected with the plugin. 
What should be the appropriate migration path so that they do not see those errors when having the plugin? I have disabled the plugin and have been able to update compser with - no dev and then without that option. But I have kept those two tables 
![Captura de pantalla de 2021-07-07 09-20-20](https://user-images.githubusercontent.com/2455005/124777096-93a7a480-df05-11eb-9c34-223ea0fc31c3.png)

**Comment by alecpl** [comment]
We do not support external plugins here. You should have uninstall it and/or rename the table that was created by this plugin.
