### ISSUE TITLE
Small UI bug 'Fix size of Mailvelope iframe for PGP-inlined mail' is back

### ISSUE THREAD

**Issue by gurnec** [roundcube/roundcubemail#8126]
The small UI bug 'Fix size of Mailvelope iframe for PGP-inlined mail' mentioned in #7348 is back in 1.5-rc.

It looks like @alecpl cleaned this up in https://github.com/roundcube/roundcubemail/commit/90280ed6907d1242e87424d8da0b769d15e49f19#diff-2186361c03dbfed89fa9368a821ac30f045881e5548f77093518b4bd45c8510aL4071-R4071 (getting rid of a hard-coded DOM id that I shouldn't have used when I tried to fix it earlier), but I believe that fixed line should read:

```javascript
$(ref.gui_objects.messagebody).addClass('mailvelope');
```

(`ref` instead of `this`). At least this update works correctly for me.

Thank you!

**Comment by alecpl** [comment]
Fixed.
