### ISSUE TITLE
Uncaught Error: Class 'Spoofchecker' not found

### ISSUE THREAD

**Issue by danielczestki** [roundcube/roundcubemail#8127]
After upgrade from 1.5-beta to 1.5.RC I got error in logs:

[11-Jul-2021 07:48:43 UTC] PHP Fatal error:  Uncaught Error: Class 'Spoofchecker' not found in /usr/local/services/roundcube/program/lib/Roundcu$
Stack trace:
#0 /usr/local/services/roundcube/program/actions/mail/index.php(1401): rcube_spoofchecker::check('albatros-hurt.p...')
#1 /usr/local/services/roundcube/program/actions/mail/index.php(523): rcmail_action_mail_index::address_string('=?UTF-8?B?QUxCQ...', 3, false, N$
#2 /usr/local/services/roundcube/program/actions/mail/list.php(122): rcmail_action_mail_index::js_message_list(Array, false, Array)
#3 /usr/local/services/roundcube/program/include/rcmail.php(275): rcmail_action_mail_list->run(Array)
#4 /usr/local/services/roundcube/index.php(283): rcmail->action_handler()
#5 {main}
  thrown in /usr/local/services/roundcube/program/lib/Roundcube/rcube_spoofchecker.php on line 50

**Comment by alecpl** [comment]
php-intl extension is now required.
