### ISSUE TITLE
IMAP connection timed out randomly

### ISSUE THREAD

**Issue by iredmail** [roundcube/roundcubemail#8131]
Dear all,

I'm experiencing a weird timeout issue, and looking for some help to fix it.

- OS: Debian 10 (x86_64)
- Dovecot: 2.3.4.1-5 (installed from Debian apt repo)
- php-fpm: 7.3.29-1~deb10u1
- Roundcube 1.4.11

I frequently got "gateway time out" (Nginx) error, it can be steadily reproduced by randomly click different mail folders quickly (click "Inbox" first, then click "Sent" quickly, then "Draft", etc). Roundcube logs below lines when the issue happens, as you can see in last 2 lines, it timed out after 60 seconds (Roundcube has default imap timeout set to 60s).

Note: this timeout happened randomly, in same webmail session, all other operations are fast and finished in less than 1-2 seconds.

```
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] Connecting to tls://127.0.0.1:143...
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ STARTTLS AUTH=PLAIN AUTH=LOGIN] Dovecot (
Debian) ready.
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] C: A0001 STARTTLS
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: A0001 OK Begin TLS negotiation now.
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] C: A0002 CAPABILITY
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: A0002 OK Pre-login capabilities listed, post-login capabilities have more.
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] C: A0003 ID ("name" "Roundcube" "version" "1.4.11" "php" "7.3.27-1~deb10u1" "os" "Linux" "command" "/?_task=mail&_actio
n=list&_refresh=1&_layout=widescreen&_mbox=Drafts&_page=1&_remote=1&_unlock=loading1626084359778&_=1626078871725")
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: * ID ("name" "Dovecot")
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: A0003 OK ID completed.
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] C: A0004 AUTHENTICATE LOGIN
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: + VXNl... [ omit few chars here]
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] C: ****** [18]
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] S: + UGFz... [ omit few chars here]
Jul 12 13:06:00 mail roundcube: <dgibvpfn> [66FC] C: ****** [14]
Jul 12 13:07:00 mail roundcube: <dgibvpfn> IMAP Error: Login failed for user@mydomain.com against 127.0.0.1 from xx.xx.xx.xx. AUTHENTICATE LOGIN:  in /opt/www/roundcubemail-1.4.11/program/lib/Roundcube/rcube_imap.php on line 200 (GET /?_task=mail&_action=list&_refresh=1&_layout=widescreen&_mbox=Drafts&_page=1&_remote=1&_unlock=loading1626084359778&_=1626078871725)
```

**Comment by vring0** [comment]
+

**Comment by alecpl** [comment]
I see no indication here that it is a Roundcube issue.

Hints: You can configure the timeout. You can configure the log timestamp to include microseconds.

**Comment by mckaygerhard** [comment]
> I'm experiencing a weird timeout issue, and looking for some help to fix it.

i have same behavior problems! too @iredmail  and @vring0 BUT  for huge boxes, a year ago when try to upgrade all, so we do not upgrade cos debian 10 has issues, also roundcube 1.4 too, so still uses debian 9 and roundcube 1.0 with have working search with huge mailfolders
