### ISSUE TITLE
Empty HTML body on sending new message

### ISSUE THREAD

**Issue by Spider84** [roundcube/roundcubemail#8133]
1.5-RC, php8.0
When Saving draft or sending message with HTML body - receiving empty HTML part of message. But plain part looks good. 
No errors or warnings in error log.

**Comment by alecpl** [comment]
Did you look into the message source? Is it really empty there, or is it empty when you try to open the email?

**Comment by Spider84** [comment]
Is it really empty.
```
MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_0412d21916fc62b0ca0304dbe5daaa1d"
Date: Tue, 13 Jul 2021 11:28:51 +0600
From: = xxxxxx
To: Test <test@xxxx>
Subject: Test HTML
Message-ID: <32b14894518f6d28c92b9deb60e42787@xxxx>
X-Sender: spider@spider.vc
Disposition-Notification-To: =xxxxxx

--=_0412d21916fc62b0ca0304dbe5daaa1d
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed

Html content

--
--=_0412d21916fc62b0ca0304dbe5daaa1d
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8








--=_0412d21916fc62b0ca0304dbe5daaa1d--
```

**Comment by alecpl** [comment]
I'm unable to reproduce. You say the HTML content is inside the plain text part? Did you try with all plugins disabled? Is this a new installation or upgraded one?

**Comment by Spider84** [comment]
>You say the HTML content is inside the plain text part?

No no. "Html content" it is text that I has tried to send from roundcube.
I expected `<strong>Html content</strong>` in html part. But it is Empty.
>Did you try with all plugins disabled?

yes.
>Is this a new installation or upgraded one?

Upgrade from 1.5-betta, from 1.4..xxxx (don't remember)

**Comment by alecpl** [comment]
Did you use the "complete" release package or did you maybe run `composer update`?

**Comment by Spider84** [comment]
FIXED! :)
My Debian don't use  `roundcube/vendor/pear/Mail` sources instead it use `/usr/share/php/Mail` where was very old version
