### ISSUE TITLE
no strengh password documentation, neither working methods

### ISSUE THREAD

**Issue by mckaygerhard** [roundcube/roundcubemail#8134]
Although in Linux you must have a minimum of knowledge, for beginners as well as for administrators with little time the password plugin is not documented, and you have to modify the regular expression to get the desired result, here is the explanation and the problem since the change to strengh in the password plugin, which was not a problem in version 1.2 and earlier @alecpl  the stretch is not described.. just said

> Note: Password strength is scored from 1 (week) to 5 (strong).

so, 1 is a default and 5 is when the password contains a digit and non-alpha character. **there's no description of the alpha-numeric one equivalent!** i test and **only permit with 1 alphanumeric but not alpha-numeric with dots** ..   https://github.com/roundcube/roundcubemail/blob/2f643141b4e16dd70f0d1dda283c2106e63a3009/plugins/password/config.inc.php.dist#L22 

**also for LTS and stable production at  README only has one password strength method documented and working** https://github.com/roundcube/roundcubemail/blob/2f643141b4e16dd70f0d1dda283c2106e63a3009/plugins/password/README#L414 and still is not fully supported! so .. there's no driver strengch support then?

**Comment by alecpl** [comment]
I struggle to understand what is your problem.

The strength drivers are supported and documented since Roundcube 1.4. Sample config file contains this:
```
// Require the new password to have at least the specified strength score.
// Note: Password strength is scored from 1 (week) to 5 (strong).
$config['password_minimum_score'] = 0;
```
The old `password_require_nonalpha` option has been removed, you can use `password_minimum_score=5` (with `password_strength_driver=null`) to get the old behavior of this option.

I guess what you expect may just be not implemented.

**Comment by mckaygerhard** [comment]
@alecpl  that was just an example.. still you said that "theres two supported drivers" and in LTS and stable only one is documented in README! and only partially! 

currently you close so fast the issues and seems you dont want to work ! the issue is about where is the coduemntation! or fixed the one!

**Comment by alecpl** [comment]
There's one driver supported in 1.4, and there's two in 1.5. Older version do not support strength drivers.

**Comment by maddes-b** [comment]
Hi there,

I found this issue as I cannot find any documentation for `password_minimum_score`.

If I search the repository the only information available is for the "pwned" driver in a README.
There is no information for the default sql driver what the values 1-5 actually mean.
According to the [source](https://github.com/roundcube/roundcubemail/blob/6cfca8dc9f5a1979d60e05770c5453605beeb3d3/plugins/password/password.php#L62) the old `password_require_nonalpha` setting relates to the value 2.
Could you please add information to the documentation what these values actually stand for.

Thanks in advance.
Maddes

**Comment by maddes-b** [comment]
After reading the source code for some time, here's what I found out:

If a password driver doesn't provide a check_strength() function, then [password.php uses a fallback check](https://github.com/roundcube/roundcubemail/blob/6cfca8dc9f5a1979d60e05770c5453605beeb3d3/plugins/password/password.php#L375).
I found 2 drivers with a check_strength() function: [zxcvbn](https://github.com/roundcube/roundcubemail/blob/master/plugins/password/drivers/zxcvbn.php), [pwned](https://github.com/roundcube/roundcubemail/blob/master/plugins/password/drivers/pwned.php).
Only for pwned I found information regarding `password_minimum_score` in the [README](https://github.com/roundcube/roundcubemail/blob/master/plugins/password/README) and in the driver source code.

So with the [default SQL driver](https://github.com/roundcube/roundcubemail/blob/master/plugins/password/drivers/sql.php) the fallback routine of password.php is used, which acts as following:
* Score of 1: password includes no number or no non-alpha character
  * Just one of them is missing. Still a number or non-alpha character could be within the password.
* Score of 5: password includes a number and a non-alpha character
  * **Warning!** the password could only consist of numbers and non-alpha characters without alpha chars. This maybe not what you expect.
* No check for upper or lower case characters is done at all.

**Comment by mckaygerhard** [comment]
yeah @maddes-b  is poorly documented.. that's why i opened this issue.. but well was closed cos we do not use the kolab services (deleting incoming but mail to my friends here is send with no way to denied that)

my intention was ask information and later send some kind of pull request but ALWAYS "oh nono you are wrong all are in the code, etc etc" but inclusivelly i found your deductions.. but there's some obscured changes recently that dont match again 1.4 and 1.2 versions (LTS ones) so i dont spend more time reading the code cos i also have taks to do.. 

the code does not have any meaning for scores 2 to 4 and after some test behaviour is pretty obscured..
