### ISSUE TITLE
compose blocks editor when refreshing the "R" key

### ISSUE THREAD

**Issue by mckaygerhard** [roundcube/roundcubemail#8135]
in the editor compose, i we have any other plugin related to editor enabled like keyboard or contextmenu or hotkeys, the editor area blocks the input "R" key when are refreshing, this does not happened with normal skin neither with 0.9 or 1.0 versions (the only tested for me)

**Comment by alecpl** [comment]
We do not support these plugins, so I'm not sure this is Roundcube issue. Please, clarify. Is there any problem with all plugins disabled?

**Comment by mckaygerhard** [comment]
it makes sense.. let me deploy a normal one and post feedback later after a week, cos i need the weekend for

**Comment by alecpl** [comment]
No feedback.
