### ISSUE TITLE
Cannot send or receive email

### ISSUE THREAD

**Issue by JohnHOB** [roundcube/roundcubemail#8136]
Hi!  I can see my email screen, but it hangs if I try to send email.  I am not receiving test emails I send to myself from another account.

I have two clues:

1. When I use Outlook to log in via POP, it throws a 17099 error ("temporary local error") when I try to send an email.
2. The last email I received was sent at 9 AM (same time zone) but Roundcube time-stamped it 11 AM (it's timestamps are usually accurate).

What is going on here?

**Comment by JohnHOB** [comment]
Given that this is my work-from home email, I am very worried.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
