### ISSUE TITLE
[1.5-rc] Dark theme hurting eyes

### ISSUE THREAD

**Issue by williamdes** [roundcube/roundcubemail#8138]
This theme is awesome, it's the best theme I have ever seen for emails !

I just changed production to use beta and switched dark mode.
The problem is that the white square really hurts the eye, can you fix it ?

![Sélection_2021071722:51:44001](https://user-images.githubusercontent.com/7784660/126049267-c37f0bf1-26b7-4692-8885-0d7ec0ce5e0b.jpg)

**Comment by alecpl** [comment]
It shouldn't be like that. I can't reproduce. Is this from the vanilla package? What browser? Maybe somehow it uses the old watermark.html file.

**Comment by Albotterin** [comment]
I had the same problem when first updating to 1.5 beta. I moved the watermark.html file again via FTP and it worked fine. Another thing about the new dark mode is that it is not possible to set it as default via a config file. Maybe this could be added in the future.

**Comment by klukaszczyk** [comment]
> It shouldn't be like that. I can't reproduce. Is this from the vanilla package? What browser? Maybe somehow it uses the old watermark.html file.

Hi,
I had the same problem. The cause were permissions to file watermark.html after upgrade.
After chown to www-data it works fine.

**Comment by williamdes** [comment]
<kbd>CTRL+F5</kbd> solved it ;)
Thank you for the kind response !

**Comment by williamdes** [comment]
I am not sure you can fix it, on HTML renders only.
![image](https://user-images.githubusercontent.com/7784660/126082439-3b26efce-fe41-4d4f-8a2e-38b5edbb1a9f.png)

**Comment by alecpl** [comment]
Indeed, we do not even try to "convert" HTML message content into dark mode.

**Comment by alecpl** [comment]
...and do not plan to do this.
