### ISSUE TITLE
Roundcube work with 7.4 php version

### ISSUE THREAD

**Issue by webspecialist** [roundcube/roundcubemail#8141]
My system:
Server 18.04 LTS Ubuntu
PHP 7.4 with Nginx

First Issue:
I' ve been worked with Roundcube for 6 months with a 7.4 PHP version but I had few problems.

Yesterday, I couldn't receive or send emails and I can't figure out the reason. 
Is there any way to remove and install again the Roundcube to work with the 7.4 version?
When I tried to remove it, I had also a problem with php72-PHP-fpm failed to start.

Second Issue:
Is there any documentation to follow for Roundcube debugging?

**Comment by alecpl** [comment]
Roundcube works with 7.4 without problems, but you should use a recent version i.e. 1.4.

Ask on mailing list or forum. This is not a support forum.

**Comment by webspecialist** [comment]
I cannot register in the forum and there is no contact info for the forum administrator.
Where can I find it?
Where to find this mailing list?
