### ISSUE TITLE
Password: Verify current password with IMAP

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#8142]
Howdy,

I've been tracking an hacker using two specific accounts from my users for spam sending, and i was all the time changing password, but, he somehow always was able to gain access again.
After ~3 weeks I discovered what he was doing manually.

steps:
- he logs in to the webmail
- i changed the password in my hosting panel
- he starts getting errors/warnings about cannot connect/etc
- even with the errors/warnings, he goes to the settings, password, inserts the old password, and the new one, and gains access again.

My question is:
- is it possible to prevent this, on this scenario make RC logout completly for example?
- make the password plugin make a validation if it can connect to the imap server with the old password before proceed?

On my case i'm using SQL password driver,

**Comment by alecpl** [comment]
Verifying the old password with imap might be a good idea.

I see no other way to prevent that. The session is kept alive as long as the user has the browser open (as long as it send the keep-alive requests).

**Comment by dddns** [comment]
Hi Alec,

I understand for the keep-alive thing.
About the verify old passwd agains the imap before the change, would it be possible to implement it, in a global way for all drivers of course.

would it?

**Comment by dddns** [comment]
Thank you alec for going to add it.
Is it possible to add it to 1.4.12 as 1.5.x?

**Comment by alecpl** [comment]
Done in master. I do not plan to backport this.

**Comment by dddns** [comment]
Hi Alec,
It's perfect! This a big measure for password-steal mecanisms.
Thank you,
