### ISSUE TITLE
Failed to add recipient '%20test@test.com'

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#8146]
Hi,

Sometimes I get the following error in my error log:

```
Failed to add recipient '%20test@test.com'. Administrative prohibition (Code: 550)
```

I guess the `Administrative prohibition` is because of some server-side configuration which forbids the use of `%` in email recipients, but shouldn't that be filtered by Roundcube? I can't think of an email address that is valid which starts with `%20` or contains any `%` at all, but I don't know if any RFC forbids that.

The stacktrace would be:

```
#4 /program/lib/Roundcube/rcube.php(1731): rcube::deliver_message
#3 /program/include/rcmail_sendmail.php(388): rcmail_sendmail::deliver_message
#2 /program/steps/mail/sendmail.inc(271): include_once
#1 /index.php(306): include
#0 /public_html/index.php(26): null
```

I tried sending a mail to `%20test@test.com` and dump the result of `rcmail_sendmail::email_input_format` which did not complain about that address, neither did `rcube_utils::check_email`.

Roundcube Version 1.4.11 on PHP 7.4

**Comment by alecpl** [comment]
This is a valid email address according to RFC 5322 (2822). "Administrative prohibition" does not sound like a validity check. Possible reasons http://kb.mozillazine.org/Administrative_Prohibition.

`%20` is an encoded space. I wonder whether it's possible to end up with `%20` by some user actions that involve e.g. copying the email address from some source. Maybe mailto: links handling bug or whatever. Then we could see if we can prevent that. If the email was entered/saved with literal `%20` we can do nothing than accept it on mail delivery.

**Comment by codegain** [comment]
Thanks for the explanation!
If this is a valid email address then I think this issue could be closed. I was thinking that the validation of roundcube was not strict enough to trigger this error on the SMTP server, but there seem to be some tweaks done server-side to prevent such email addresses. Nothing for roundcube to worry about.

In my setup I will just change the error message the user is given, which is currently not helpful to the users ("Sending to xxx denied. Administrative Prohibition 550") and leave the logic as is.
