### ISSUE TITLE
Cannot change password - Error 600 Service currently not available

### ISSUE THREAD

**Issue by linuxdan** [roundcube/roundcubemail#8148]
I followed this tutorial: https://www.linuxbabe.com/redhat/install-roundcube-webmail-centos-8-rhel-8-apache-nginx

When I try to change a password, I get "SERVICE CURRENTLY NOT AVAILABLE ! Error No. [600]"

I tuned up debugging/logging in Apache and in Roundcube, but I find nothing in the logs to explain this.

What the heck ?

**Comment by alecpl** [comment]
There should be something in the Roundcube error log. Does not look like a bug.

**Comment by linuxdan** [comment]
Thanks for all your hard work and information
