### ISSUE TITLE
Variable translated in nl_NL ($vervaldatum)

### ISSUE THREAD

**Issue by pluijm** [roundcube/roundcubemail#8149]
https://github.com/roundcube/roundcubemail/blob/a8ce731df933e2f6da28dff0c252b560cbcb89b4/plugins/password/localization/nl_NL.inc#L38

Variable $expirationdatetime was translated into $vervaldatum which breaks replacement.

**Comment by alecpl** [comment]
I fixed this on https://www.transifex.com/roundcube/roundcube-webmail/translate/#nl_NL/plugin-password and in git.
