### ISSUE TITLE
PHP 8.1 support

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#8151]
I'm afraid this will be a lot of work, similar to what we had to do for PHP 8.0. I enabled GA tests for 8.1 and we have some failing tests and a lot of deprecation warnings in log: https://github.com/roundcube/roundcubemail/suites/3364155381/artifacts/79140079

Therefore, this will most likely not happen in Roundcube 1.5.

**Comment by alecpl** [comment]
Done.

**Comment by dgerzo** [comment]
The release announcement of RC 1.5 claims support for PHP 8.0, but does it also support 8.1 as per the last comment and since this issue has been closed? It is also unclear from the Requirements documentation (it probably has not been fully updated after 1.5 release). Thanks.

**Comment by alecpl** [comment]
No, it will be supported with 1.6, the beta release is planned sometime in January or February.

**Comment by resposit** [comment]
I just stumbled on this issue...
I did not pay attention to release notes and installed RC1.5.2 on PHP8.1.
I can confirn LDAP address book does not work because of this:
https://php.watch/versions/8.1/LDAP-resource
