### ISSUE TITLE
Array as "_user" in login form triggers php warning

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#8152]
Hi,

Roundcube 1.4.11 on PHP 7.4

When a (malicious) user sends a login request to roundcube and uses an array as `_user` the following error is shown in the log file:

```
Warning: trim() expects parameter 1 to be string, array given
```

This is because of this line in the index.php file: https://github.com/roundcube/roundcubemail/blob/9faea49f827a8b3e765513a023dafb5ece0c9fc0/index.php#L115

There is no check here that prevents the return value of `rcube_utils::get_input_value` to be an array an therefore trigger that php warning. This currently triggers a warning on PHP 7.4, but a TypeError on PHP 8:

```
var_dump(trim(['foobar']));

PHP 7.4:
Warning: trim() expects parameter 1 to be string, array given

PHP 8:
Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given
```

**Comment by alecpl** [comment]
Fixed.
