### ISSUE TITLE
All recipients in BCC can see the email addresses of other recipients in BCC

### ISSUE THREAD

**Issue by harikalet** [roundcube/roundcubemail#8156]
When I send an mail with BCC option, the recipients who were put in BCC, who receive the email, when they open that mail and click to: "Details" -> "All headers"

in the section: "Envelope-to:" they can see all other recipients 

It is important to be noticed that if the email addresses of the recipients who are with a different domain than the domain of the email address of the sender (for example if it was name.surname@gmail.com) those email addresses are not visible in BCC. 

But if the email addresses of the recipients are with domain which is the same as the recipient for example name.surname@domain-name.com in that case those email addresses are visible in BCC.

I suppose this is a bug, since as I know, BCC recipients should be not visible to anyone else except the sender.

**Comment by alecpl** [comment]
BCC recipients should be not visible to anyone else except the sender.

Roundcube does not set the Envelope-To header, so it's probably the SMTP server. Could you enable smtp_debug in Roundcube config and provide the log?

**Comment by alecpl** [comment]
No feedback.
