### ISSUE TITLE
show_additional_headers plugin shows "Array" when using threaded list view

### ISSUE THREAD

**Issue by thomask77** [roundcube/roundcubemail#8157]
Hi!

I'm using the `show_additional_headers` plugin, and configured it to show the `X-Original-To` header:

    $config['identity_select_headers'] = ['X-Original-To']; 

When the List mode is set to "List", everything works fine. For example, it shows "mail+github@t-kindler.de".

But when the list mode is set to "Threads", it shows "Array" instead of the correct header contents.
(All other built-in headers are showing up fine).

**Comment by alecpl** [comment]
I guess it's `show_additional_headers`, not `identity_select_headers` ;)

Anyway, I confirm that if the header exists multiple times in the message "Array" is displayed. It has nothing to do with list mode.

**Comment by alecpl** [comment]
Fixed.
