### ISSUE TITLE
Bug/Security : html tags is not escaped on subject when display.

### ISSUE THREAD

**Issue by mickael067** [roundcube/roundcubemail#8160]
I have found a bug (and security problem) on the display of the subject that I have received.
When the subject contains html style tag ("`<...>`")
Example:
`Subject: <toto@toto.com> have a problem`
The display give:
`have a problem.`
html tag is not escaped and is directly applied on the page.
Need to use the php function : htmlspecialchars
I have not found the php file to update to propose a patch.
Perhaps other items need to have the usage of php function : htmlspecialchars.
Thanks.

**Comment by alecpl** [comment]
I'm unable to reproduce. What version?

**Comment by mickael067** [comment]
The latest of the night, from this repository.
Roundcube Webmail 1.6-git [GIT 20210806.0906]
![capture1](https://user-images.githubusercontent.com/1652931/128606477-1ffad049-9ddf-43c6-a9b1-73f1d65c7a5c.jpg)
![capture2](https://user-images.githubusercontent.com/1652931/128606483-d36941e5-13f8-4dd4-bd52-ebb2d567b9a0.jpg)

**Comment by mickael067** [comment]
Without any plugin ==> No problem.
The problem is into the plugin : easy_unsubscribe
