### ISSUE TITLE
Unable to view identities in settings (1.5-RC)

### ISSUE THREAD

**Issue by jclacherty** [roundcube/roundcubemail#8161]
I'm using a fresh install of Roundcube 1.5-RC. When I go to settings and click on the identity (as any user), the display area shows "SERVER ERROR!" Error No. [600]. I can't see anything in the logs to tell me what the problem may be. I can create a new identity, but after hitting save, the error appears. If I go out of identities and back in, the newly created identity is listed (but can't be viewed).

Request is

`https://myserver/?_task=settings&_action=edit-identity&_iid=1&_framed=1`

Response is an iframe with the error message.

Justin.

**Comment by alecpl** [comment]
That kind of error should leave some message in logs. Roundcube logs or http server logs. If there's nothing there, you have a problem with logging setup. There's not much we can help here.

**Comment by jclacherty** [comment]
Thanks and apologies for putting noise in here. FWIW, I found the log and the issue was to do with a plugin that was enabled (enigma).

This is a great project btw!
