### ISSUE TITLE
Roundcube email problem-missing letter in sender's email identity

### ISSUE THREAD

**Issue by Quinnncy** [roundcube/roundcubemail#8162]
Hello, from my knowledge, we are only able to send out an email from a specific sender identity (only if we create or from default), I didn't create any new sender email identity, only by deault e.g amy@companydomain.com. However, I notice from my 'sent inbox', there's few 'from' email that does not belong to my sender identity, which goes by amy@mycompandomain.com, where you can notice there's missing letter of 'y' (mycompandomain.com) in my 'send from' domain email. If there any possible issue I might encounter like trojan or anything in my roundcube? I've checked my sender's identity under setting>identities, only exist the default which is amy@mycompanydomain.com, which is correct. It doesn't have the missing letter in the domain email at all, but under sent email, 'from' sender, it does have the missing letter (only for few emails). Anyone can help in this case?

**Comment by alecpl** [comment]
That can be anything. We'll not be able to help you. This is not a support forum.
