### ISSUE TITLE
Canned response Unicode issue

### ISSUE THREAD

**Issue by TobiasGrave** [roundcube/roundcubemail#8163]
A canned response with Unicode special characters like 😀 breaks the whole roudcube user configuration. The configuration settings are reset to their default values, all canned responses are lost. There are no error messages in the Roundcube logs or in the browser.
I use a MySQL database for Roundcube, the problem may occur with other databases as well.

Roundcube version: 1.4.11
PHP version: 7.3.29

**Comment by alecpl** [comment]
Works for me with 1.5. Probably fixed just by the switch to utf8mb4 encoding.

**Comment by alecpl** [comment]
Ref: #6535.
