### ISSUE TITLE
Why I can send email successfully but don't receive what I have sent?

### ISSUE THREAD

**Issue by saltfish233** [roundcube/roundcubemail#8168]
I use aliyun ECS server to build my email server by Postfix+Dovecot+Roundcube. Aliyun ecs server has banned port 25.I changed roundcube smtp_port to 465 and smtp_server to ssl://mail.mydomain.com.I send email successfully .
![image](https://user-images.githubusercontent.com/50053654/129288391-81b806cd-0dbf-47c6-b00d-6cc30307297d.png)
But my dest email doesn't receive.

**Comment by alecpl** [comment]
Does not look like a Roundcube issue. Check postfix logs.
