### ISSUE TITLE
I can't insert contact when I use ldap address book.

### ISSUE THREAD

**Issue by akong77** [roundcube/roundcubemail#8171]
Please see attachment.
I write new email and I click right contact button.I found user and want insert it.It's no respond.
Please check it
My address book is connect to ldap.Left contact and insert it.
![2021-08-17_150235](https://user-images.githubusercontent.com/6081927/129679862-c4ea10c8-aa05-42df-8489-070acc564530.jpg)
![2021-08-17_150643](https://user-images.githubusercontent.com/6081927/129679865-8b0038b1-7c30-4a80-babf-f1255a4f43da.jpg)

**Comment by alecpl** [comment]
Show your ldap_public configuration. What version? Does it display the email address hint when you mouseover the contact record? Any errors in browser console?

**Comment by akong77** [comment]
ldap_public config like follow:

$config['ldap_public']['( Taipei ) Group List'] = array(
        'name' => '( Taipei ) Group List',
        'hosts' => array('192.168.1.202'),
        'port' => 389,
        'use_tls' => false,
        'user_specific' => true,
        'base_dn'=> 'OU=Address Book_Group,OU=Groups,OU=Taipei,OU=Linguitronics,DC=linguitronics,DC=com',
        'bind_dn' => 'email@domain.name',
        'bind_pass' => 'password',
        'writable'=> false,
        'search_fields' => array('mail', 'cn'),
        'name_field' => 'cn',
        'firstname_field' => 'givenName',
        'surname_field' => 'sn',
        'email_field' => 'mail',
        'scope' => 'sub',
        'filter' => '(&(mail=*)(!(mail=TRUE)))' ,
        'sort' => 'cn',
        'fuzzy_search' => TRUE,
        'ldap_version'  => 3);

Version is 1.4.11

Yes,It's will show email address when mouseover.

I can't found error in console.Maybe I don't know what error.

**Comment by alecpl** [comment]
> $config['ldap_public']['( Taipei ) Group List'] = array(

Remove brackets and spaces. This array key must contain only safe characters, ie. a-zA-Z0-9_

**Comment by akong77** [comment]
OK,I test it.

**Comment by alecpl** [comment]
I guess, that helped.
