### ISSUE TITLE
Error when "Check spelling before sending a message" is activated

### ISSUE THREAD

**Issue by fabianbur** [roundcube/roundcubemail#8172]
For two days when "Check spelling before sending a message" is activated, the message cannot be sent if there are spelling errors. After a while "Sending message..." the message "Connection Error (Failed to reach the server)!" appears.

Logs:
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to spell.roundcube.net port 443: Expiró el tiempo de conexión (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/roundcube/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200

Roundcube Webmail 1.5-rc

PHP 7.3.29-1~deb10u1

curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3

Debian 10

![Captura de pantalla de 2021-08-19 22-32-44](https://user-images.githubusercontent.com/2455005/130175978-242f3e54-6ac0-4c15-b497-cc358dc7f599.png)

![Captura de pantalla de 2021-08-19 22-32-09](https://user-images.githubusercontent.com/2455005/130175986-172ce96f-4883-4b9a-80d9-f93553efdeb5.png)

**Comment by alecpl** [comment]
The problem might be on spell.roundcube.net side. You should setup a local spellchecker engine.

Aside of fixing our service we should probably handle nicely the error so the sending works if such error happens.

**Comment by fabianbur** [comment]
Thanks for the recommendation. I have installed pspell engine and everything works fine now.

**Comment by alecpl** [comment]
Fixed the error handling part.
