### ISSUE TITLE
PHP Warning: Undefined array key

### ISSUE THREAD

**Issue by MrSpock77** [roundcube/roundcubemail#8175]
Hi,

I have made a fresh install of Roundcube and everything seems to work, but I get some warnings in errors.log.

This one is logged every time I send a new mail in Roundcube:

`[25-Aug-2021 16:29:15 Europe/Stockholm] PHP Warning:  Undefined array key "HIGHESTMODSEQ" in D:\Mail\Roundcube\program\lib\Roundcube\rcube_imap_cache.php on line 792`

These are logged every time I click on a new mail in my inbox:

`[25-Aug-2021 16:29:31 Europe/Stockholm] PHP Warning:  Undefined array key 9 in D:\Mail\Roundcube\program\lib\Roundcube\rcube_imap.php on line 2188`
`[25-Aug-2021 16:29:31 Europe/Stockholm] PHP Warning:  Undefined array key 8 in D:\Mail\Roundcube\program\lib\Roundcube\rcube_imap.php on line 2202`

PHP: 8.0.9
Mail server: hMailServer 5.6.8
Browser: Firefox 91.0.2
Roundcube: 1.5-rc

I have also compiled the latest revision of release-1.5 (15928), but the same warnings occur.

Thanks,

Johan

**Comment by alecpl** [comment]
Fixed.

**Comment by MrSpock77** [comment]
Thanks!

I found another two in latest release-1.5:

`[09-Sep-2021 13:40:27 Europe/Stockholm] PHP Warning:  Undefined array key 9 in D:\Mail\Roundcube\program\lib\Roundcube\rcube_imap.php on line 2096`

`[09-Sep-2021 11:40:18 Europe/Stockholm] PHP Warning:  Undefined array key "email" in D:\Mail\Roundcube\program\actions\settings\identity_save.php on line 82`

Johan

**Comment by alecpl** [comment]
Fixed. Next time open a new ticket, please.
