### ISSUE TITLE
Undefined array key 1 in program/include/rcmail_attachment_handler.php on line 311

### ISSUE THREAD

**Issue by Player701** [roundcube/roundcubemail#8176]
This is most certainly a typo:

https://github.com/roundcube/roundcubemail/blob/203f45662067f783e1675fe8df04b924b55b8236/program/include/rcmail_attachment_handler.php#L311

The first argument of ```explode``` is the delimiter, and the second one is the string to split. Here, they are reversed.

**Comment by alecpl** [comment]
Fixed.
