### ISSUE TITLE
OAuth2 Login fails with "Login failed" if token is more than 1024 characters

### ISSUE THREAD

**Issue by philpem** [roundcube/roundcubemail#8178]
I've configured Roundcube 1.5 RC to authenticate against Keycloak with OAuth2, and XOAUTH2 to a Dovecot IMAP server. This worked fine for some time, until a Keycloak upgrade.

I'm now seeing an error -- "Login failed" -- when trying to use Keycloak/OAuth2 login. The exchange with Keycloak seems to go okay, but Roundcube never gets to the point of trying to do an XOAUTH2 authentication against the mailserver.

After enabling some of the debug logging in Roundcube I found this:
```
[25-Aug-2021 21:09:43 +0000]: <ohoqki84> Failed login for REDACTED from 81.187.163.148 in session ohoqki84d9lrq6f7 (error: 1)
```

Digging deeper, I found that this error code was generated in `program/include/rcmail.php`, and code 1 means `INVALID_REQUEST`. One of several places this is triggered is the function `login_input_checks($username, $password)` in the same file -- it's generated when the username or password is too long. The limits are set with two config parameters: `login_username_maxlen` and `login_password_maxlen`, the default being 1024 bytes.

It turns out `./program/actions/login/oauth.php`, uses the password field to store the OAuth token:

```
            if ($auth && isset($auth['username'], $auth['authorization'], $auth['token'])) {
                // enforce XOAUTH2 auth type
                $rcmail->config->set('imap_auth_type', 'XOAUTH2');

                // use access_token and user info for IMAP login
                $storage_host = $rcmail->autoselect_host();
                if ($rcmail->login($auth['username'], $auth['authorization'], $storage_host, true)) {
```

There's no error to say the password limit is too short (or the token too long) -- I'm flagging this as it's not obvious, and it's taken several hours to pin down why OAuth2 login had broken.

I found putting this in `config.inc.php` works as a workaround, but it may not be the correct fix:

```
$config['login_password_maxlen'] = 4096;
```

**Comment by thomascube** [comment]
> Why don't we set it (temporarily) in the code knowing the token size?

Good point!

**Comment by thomascube** [comment]
Commit 0c24c96 should fix this.
