### ISSUE TITLE
Spellchecker URL not answering (spell.roundcube.net)

### ISSUE THREAD

**Issue by hannob** [roundcube/roundcubemail#8182]
I noticed some warnings in my PHP log of the form "unable to connect to ssl://spell.roundcube.net:443".

It seems that the spellchecker function of roundcube tries to connect to spell.roundcube.net, however that host is not answering. This seems to expect something called googiespell, which from what I can tell is a service that no longer exists.

FWIW I am also wondering if externalizing spellchecking to an online API service by default is a privacy problem.

**Comment by alecpl** [comment]
The service is indeed dead right now. Maybe we should change the default to pspell or enchant, or even disable it.

**Comment by hannob** [comment]
It seems to me pspell uses a widely available PHP API (that effectively uses aspell, as pspell seems to be deprecated), thus I think this is a good choice. It's also doing checks offline and thus no privacy issue. I think enchant is less common and may more likely not be available on PHP hosts.

**Comment by thomascube** [comment]
The spell.roundcube.net service was running on a sponsored server which has now gone away. As we don't have a good replacement in sight, we should just set `enable_spellcheck=false` by default and remove the spell.roundcube.net host as default for `spellcheck_uri`.

We can eventually provide a Docker image as a self-hosted replacement for spell.roundcube.net.

@hannob Regarding the privacy concerns: spell.roundcube.net was hosted by us (Roundcube) on a dedicated service which was fully under our control. Privacy-wise it was certainly more trustworthy that using a service provided by a commercial company.

**Comment by thomascube** [comment]
@alecpl what do you think of commit 92757f5? If OK, we should port it to 1.4 and 1.5 branches.

**Comment by hannob** [comment]
I feel having a spellchecking function by default is useful and would rather set it to pspell (which is offline, no privacy concerns). Only issue might be that some php installations may have the API disabled, so it may be worth trying to make sure that it doesn't break hard when the spell functions in PHP are not available (i.e. simply disable when it's not available).

**Comment by alecpl** [comment]
@thomascube the commit is fine. I'll probably work on using `pspell` for our test suite, so we can keep testing this functionality.

**Comment by staticvoidmaine** [comment]
> We can eventually provide a Docker image as a self-hosted replacement for spell.roundcube.net.

inb4: can this please be an "in addition to" not the "primary means" of self-hosting? I am all for projects providing docker as a deployment method, but it shouldn't be the only option IMO.

**Comment by fabianbur** [comment]
pspell i find it a good option as the default. Is related to this report : https://github.com/roundcube/roundcubemail/issues/8172

**Comment by thomascube** [comment]
As of today, the [spell checking service is back online](https://roundcube.net/news/2021/09/28/spell-checking-service-back-online) and thus we might consider to revert commit 2bd421cdaf8. @alecpl what do you think?

**Comment by alecpl** [comment]
Sure, and this one f1a026251a57d5. However, for privacy reasons maybe we should not make that a default anymore, so users are aware that the data goes to our server.

**Comment by thomascube** [comment]
spell.roundcube.net is back but `enable_spellcheck` option is now set to false by default.
