### ISSUE TITLE
Return receipt not working 1.4.11

### ISSUE THREAD

**Issue by mrahmansayed** [roundcube/roundcubemail#8183]
I installed roundcube 1.4.11 version in my server. Delivery status notification works fine except return receipt. When the return receipt checked, the mail send is fine. But no mail is return when receiver open the email. There is no support about this issue over internet, that's why i knock in github.

Please help me about this issue.

**Comment by alecpl** [comment]
Is the other side using Roundcube? Note, that user can choose to not send the receipt. Ask on mailing list or forum.
