### ISSUE TITLE
strpos(): empty needle warning

### ISSUE THREAD

**Issue by bfabiszewski** [roundcube/roundcubemail#8184]
This is roundcube version 1.5-rc.
I get lots of warnings about empty needle in strpos on [this line](https://github.com/roundcube/roundcubemail/blob/1.5-rc/program/lib/Roundcube/rcube_imap.php#L4411) when going to Mail menu.

`roundcube: PHP Warning:  strpos(): Empty needle in roundcubemail-1.5-rc/program/lib/Roundcube/rcube_imap.php on line 4411`

Seems to be same issue as [the one (empty prefix)](https://github.com/roundcube/roundcubemail/issues/5420). Probably same fix needed.

**Comment by alecpl** [comment]
I hope 4d233b5c65a fixes the issue.
