### ISSUE TITLE
enigma popup didnt work

### ISSUE THREAD

**Issue by Anagastes** [roundcube/roundcubemail#8188]
Hey,

I noticed a bug with the Enigma plugin under RC 1.5.

The small menu does not appear when you click on the icon for enigma.

Under 1.4 everything works.

Here in the picture at the beginning to see. As soon as I go into RC 1.4 (the id switch in the picture) the menu does work.

![issue gif](https://imgshare.io/images/2021/08/29/simplescreenrecorder-2021-08-29_20.07.15.gif "issue gif")

Also in the error log there is nothing to see.

Any idea what I might be missing? It was upgraded from version 1.4 to 1.5-rc. :)

**Comment by alecpl** [comment]
In Elastic the button in toolbar is not supposed to be added, even in 1.4. Maybe you have Mailvelope extension installed/enabled in the browser? In that case I'd expect to see a dropdown icon next to the button. So, something is wrong. Is this the vanilla package and the skin?

**Comment by Anagastes** [comment]
> In Elastic the button in toolbar is not supposed to be added, even in 1.4. Maybe you have Mailvelope extension installed/enabled in the browser? In that case I'd expect to see a dropdown icon next to the button. So, something is wrong. Is this the vanilla package and the skin?

It is vanilla RC with vanilla elastic.

Only some CSS color codes were replaced by me in the style.less and the dark mode removed as described here.

https://github.com/roundcube/roundcubemail/issues/8186#issuecomment-907807370

The mentioned addon is not in use (deliberately not).

So do I understand it right that enigma must not work like this anymore? Only with the addon?

Would be a shame, but a statement. Then I would have to remove enigma.

**Comment by Anagastes** [comment]
I have now tested with the browser addon and there I now have 2 icons for encryption. o_O

![maivelope](https://imgshare.io/images/2021/08/30/ksnip_20210830-223524.png)

**Comment by alecpl** [comment]
Enigma when using Elastic displays the options in the right side options form, i.e. below attachments list. So, either it has a problem with detecting the skin. Or more likely, you have some old Enigma plugin version installed.

**Comment by alecpl** [comment]
If you're using a custom skin add `"extends": "elastic"` into the meta.json file.

**Comment by Anagastes** [comment]
> If you're using a custom skin add `"extends": "elastic"` into the meta.json file.

I have now made a completely fresh installation and adjusted the styles.less/color.less there.

There are no more errors here.

I guess it was an old error that never showed up during the upgrades. Only now it appeared.

So in short, no idea why this error suddenly appeared now. But thanks for your support! :)
