### ISSUE TITLE
Oauth (xoauth) redirect uri

### ISSUE THREAD

**Issue by ghost** [roundcube/roundcubemail#8191]
Hello, recently I tested oath feature in rcmail 1.5-rc and and got a problem with redirect_uri.
After successful authentication with oauth provider I was redirected back to url **/index.php/login/oauth** and nothing happens next. 
So I inspected the source code and find this line 
https://github.com/roundcube/roundcubemail/blob/release-1.5/program/include/rcmail_oauth.php#L122
I replaced this line of code to classical ?task=login&action=oauth and everything started working ok with my oauth provider (keycloak).

As I understand to make it work correctly I need to setup some **nginx** rewrite rule, if so we need to add it to documentation (or comment to oauth config section) so people don't get confused. Or add some kind of flag that leave redirect_uri in standard form (?task=&action=).

**Comment by alecpl** [comment]
There's a code to convert the path info back into `?_task=login&_action=oauth` form. Maybe it isn't working for you https://github.com/roundcube/roundcubemail/blob/b9d0dc1cf929ab64e21fa6f6961363367a4af7ca/program/include/iniset.php#L68 maybe `$_SERVER['PATH_INFO']` is wrong/empty in your setup.

I guess some more documentation about this would be nice.

**Comment by azmeuk** [comment]
Maybe there is some inspiration to take from the [nextcloud nginx configuration](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) which does this:

```
    # Ensure this block, which passes PHP files to the PHP process, is above the blocks
    # which handle static assets (as seen below). If this block is not declared first,
    # then Nginx will encounter an infinite rewriting loop when it prepends `/index.php`
    # to the URI, resulting in a HTTP 500 error response.
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;

        fastcgi_param modHeadersAvailable true;         # Avoid sending the security headers twice
        fastcgi_param front_controller_active true;     # Enable pretty urls
        fastcgi_pass php-handler;

        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }
```

However, I could not make it work with roundcube yet.

**Comment by arunodhayam10d** [comment]
Hi, @bolsunovskyi Have you integrated keycloak with Roundcube successfully??

**Comment by bolsunovskyi** [comment]
@arunodhayam10d yes.

**Comment by arunodhayam10d** [comment]
Can you able to login Roundcube with keycloak created users?? If yes please share the configuration details both keycloak and Roundcube. I have integrated keycloak with Roundcube but I can't able to login with keycloak created users.
This is my actual issue `https://github.com/roundcube/roundcubemail-docker/issues/158#event-5714379291`
Can you pls tell me which thing I missed??

**Comment by bolsunovskyi** [comment]
No, in my case user accounts firstly must be created on mail server. To implement auth with keycloak you need to setup XOAUTH on IMAP server, for example configuration for dovecot https://doc.dovecot.org/configuration_manual/authentication/oauth2/ 
I'm not sure is this is the right place to discuss such questions, you can contact me with telegram messenger with same nick as on github.

**Comment by arunodhayam10d** [comment]
Thanks @bolsunovskyi.

**Comment by niepiotrek** [comment]
Hi, I found issue related to redirect_uri.
In my configuration Roundcube is in intranet behind Apache reverse proxy, something like that:
ROUNDCUBE.DOMAIN.TLD -> Apache Reverse Proxy (external IP) -> HOST1.LOCAL.AD (with Roundcube)
When requesting authorization, Roundcube generate URL pointing redirect_uri to HOST1.LOCAL.AD instead of ROUNDCUBE.DOMAIN.TLD

`https://OAUTH_AUTH_URI?response_type=code&client_id=MY_ID&scope=MY_SCOPE&redirect_uri=https%3A%2F%2F HOST1.LOCAL.AD %2Findex.php%2Flogin%2Foauth&state=STATE`

**Comment by TBG-FR** [comment]
> For the record, my original nginx configuration responded 404s for the redirection url. I could fix the 404 with the following nginx configuration. `fastcgi_split_path_info` fills `$fastcgi_script_name` and `$fastcgi_path_info` with the regex matches, then `fastcgi_param` sets those values in the right php `$_SERVER` variables.
> 
> ```
> location ~ \.php(?:$|/) {
>     fastcgi_split_path_info ^(.+\.php)(.*)$;
> 
>     include fastcgi_params;
>     fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
>     fastcgi_param PATH_INFO       $fastcgi_path_info;
> 
>     fastcgi_pass unix:/var/run/php-fpm7/fpm.sock;
> }
> ```

You saved my day, thanks a lot ! 🙏
