### ISSUE TITLE
"INTERNAL ERROR" when trying to display lousy/questionably encoded mime/multipart html message.

### ISSUE THREAD

**Issue by csoh90** [roundcube/roundcubemail#8192]
Roundcube version : 1.4.11 Debian buster backport

Hello.

One of our users reported that a mail causes internal error on roundcube, but not other mail clients(outlook, other webmail).
After analyzing the content, I've founded the problematic part and recreated a minimum mail that still reproduced the same error.

The problematic part looks like this:

> <code>Content-Type: text/html; charset=UTF-8</code>
> 
> <code>&lt;br&gt;=</code>
> <code>--=_9cd5ea391a18a9070d75a1935eea03aa--</code>
(roundcube seems to crash at empty equal sign, 3rd line)

I think anyone(including me) would call this code "lousy" because

1. The entire messages are not enclosed by proper &lt;html&gt;&lt;/html&gt; or even &lt;body&gt;&lt;/body&gt; tag
2. That sole equal sign is meaningless or outright illegal by some view.
3. There should be more separation line before mime/multipart boundry

But, on the other hand, I also hope that roundcube have more prepared response for code like this rather than crash - like other mail clients.

Thank you for reading this report of subtle, funny(or not?) bug.
Thank you.

[rccrash.zip](https://github.com/roundcube/roundcubemail/files/7075943/rccrash.zip)

**Comment by alecpl** [comment]
What error in log? What PHP version? Does it happen with all plugins disabled?

**Comment by csoh90** [comment]
We have 2 roundcube system. 1 production, 1 testing, both debian buster-backport distribution.

Both uses roundcube 1.4.11, php7.3 (php7.3.19 debian package on production server, 7.3.27 on testing server, newest is 7.3.29)

Both systems have same error(tested with importing attached eml file).

This error still persists even if I disabled all plugins on testing server(so that plugin list  on web ui only shows filesystems_attachments and jqueryui)

I cannot find any error log regarding this particular error on roundcube /var/log/roundcube/errors.log, password.log, sendmail.log, session.log, sql.log despite following settings on /etc/roundcube/config.inc.php(on testing server)

$config['debug_level'] = 5;
$config['session_debug'] = true;
$config['imap_debug'] = true;
$config['sql_debug'] = true;
$config['smtp_debug'] = true;
$config['apc_debug'] = true;
$config['redis_debug'] = true;

only /var/log/roundcube/imap.log shows glimpse of error like this when clicked on problematic mail on the list( and induces internal error)

[31-Aug-2021 14:00:13 +0900]: <bg681vp7> [3285] S: )
[31-Aug-2021 14:00:13 +0900]: <bg681vp7> [3285] S: A0004 OK Fetch completed (0.001 + 0.000 secs).
[31-Aug-2021 14:00:13 +0900]: <bg681vp7> [3285] C: A0005 UID FETCH 1 (BINARY.PEEK[2])
[31-Aug-2021 14:00:13 +0900]: <bg681vp7> [3285] S: * 1 FETCH (UID 1)
[31-Aug-2021 14:00:13 +0900]: <bg681vp7> [3285] S: * BYE FETCH failed: Internal error occurred. Refer to server log for more information. [2021-08-31 13:58:37]

**Comment by alecpl** [comment]
So, this clearly shows it's the imap server issue.

**Comment by csoh90** [comment]
Yes. You're right. I've found the log on imap server(dovecot).

Aug 31 15:16:01 imap(xxxx@xx.co.xx)<25593><rLBI4tTKgt5yyuML>: Error: Mailbox INBOX: UID=1: read(<binary stream of mailbox INBOX UID 1>) failed: read(/var/vmail/xxxx@xx.co.xx//Maildir/cur/1630384508.M451066P24926.bgmt,S=1059,W=1091:2,) failed: Invalid quoted-printable input trailer: '=' not followed by two hex digits
Aug 31 15:16:01 imap(xxxx@xx.co.xx)<25593><rLBI4tTKgt5yyuML>: Info: FETCH failed: Internal error occurred. Refer to server log for more information. [2021-08-31 15:16:01] in=373 out=1828 deleted=0 expunged=0 trashed=0 hdr_count=1 hdr_bytes=296 body_count=0 body_bytes=0

So character encoding translation occurs on dovecot, and dovecot fails to encode and emits errors to roundcube. I see. Dovecot's response is inconsistent though, If I insert a blank line after equal sign then dovecot doesn't emits error and processes without error despite the same condition. Anyway I have to ask dovecot to solve this problem.

Thank you anyway to help me find the source of the problem.
Thank you.

**Comment by csoh90** [comment]
I think I found the solution to this problem and while it's definitely not a roundcube bug, i'll leave it here anyway to share my findings.
Both dovecot and roundcube have the ability to translate quoted-printable characters but dovecot's is more strict and prone to error. So If one chooses to make dovecot stop advertising the ability to translate quoted-printable character by changing config like https://forums.cpanel.net/threads/dovecot-invalid-quoted-printable-input-trailer.648081/
roundcube takes the translation work instead and is more resilent to errors, so problem goes away.
Cheers to roundcube.
