### ISSUE TITLE
Installer forcibly disabled ??

### ISSUE THREAD

**Issue by EpeR1** [roundcube/roundcubemail#8195]
Why installer is, always disabled ?
Does not matter, what I'm writing to config/config.inc.php, just always getting the following error:

The installer is disabled!
To enable it again, set $config['enable_installer'] = true; in RCUBE_CONFIG_DIR/config.inc.php

It will be an absolutely clean and fresh install.

Roundcube 1.4.11
Apache 2.4.48
php 7.4
Debian 11

**Comment by alecpl** [comment]
I don't get what problem do you have exactly. It works for me. After the installation is complete accessing the installer requires to set enable_installer=true in the config file. Works for me. If it does not work, then maybe the config file cannot be read by the web server (check permissions to the file).

**Comment by alecpl** [comment]
No feedback.
