### ISSUE TITLE
Error during the installation of a plugin through composer

### ISSUE THREAD

**Issue by dimkar121** [roundcube/roundcubemail#8197]
Hi,
I caanot install any plugins using composer. It throws the following error
"ERROR: Configuration error. Unsupported database driver:", and then it stops.
Any thought?

thanks in advance

**Comment by alecpl** [comment]
Works for me. What version of Roundcube and plugin-installer? The error suggests that it might be something with access to the configuration file. Make sure config/config.inc.php file exists and is readable for the user running the script.

**Comment by dimkar121** [comment]
Yes, it works now! I needed to symlink config.inc.php to find the path to the database.

cheers,
D.
