### ISSUE TITLE
Don't use session's search scope if search is not active

### ISSUE THREAD

**Issue by sdondley** [roundcube/roundcubemail#8199]
Note: This is not a debian package manager bug as I thought. Some stupidity on my end while trying to debug this issue led me to believe that. (See closed issue #8198). I'm reopening this issue in a new thread to minimize confusion.

As best I can tell from looking at the code, roundcube is supposed to remember the `search_scope` stored in $_SESSION so that when switching between folders, the same scope is kept.

However, when switching between folders, the search_scope is not remembered and it defaults to "base." The user is forced to refresh the page manually to get the "Seach scope" setting to the value stored in the session.

A simple hack to the code gives me the behavior I desire (always default to search all folders because I'm  using solr to perform searches which is fast):

```
2696c2696
<       this.env.search_scope = 'base';
---
>       this.env.search_scope = 'all';
```

Obviously this is not the proper fix. This code is to just illustrate the problem.

**Comment by alecpl** [comment]
Nope. On a folder change the intention is to reset the search and the scope. The intention for storing the scope in session is to use it when user returns back to a search result, e.g. after he opened a message with double-click. I see that there's one small issue with that. If you refresh the page the scope will be set to the one in session, even if there's no active search.

Keeping the search criteria including scope is an other story. It was discussed in the past, and there were some UX issues with that approach. I think what we have now is more clear.

Thunderbird has a button "Keep filters applied when switching folders". Maybe that would be the way to make everyone happy, but it will not a be an easy fix.

**Comment by sdondley** [comment]
OK, thanks.

I guess I'll just leave my one-line hack in place. Unfortunately, I do not have the spare hours required to write a proper patch that is non-trivial.

Thanks for all your work on roundcube.

**Comment by alecpl** [comment]
Fixed.
