### ISSUE TITLE
Password: Improve errors handling on executed commands

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8200]
- Roundcube 1.4.11
- Dovecot 2.3.16
- RHEL 8

The password plugin was working fine with dovecot 2.3.8 but after updating to dovecot 2.3.16 the password plugin gives the error:
```
Could not save new password.
Encryption function missing.
```

I rolled dovecot back to 2.3.8 and the plugin started working again. Re-upgraded to 2.3.16 and it broke again.

The settings in `plugins/password/config.inc.php` im changing over defaults are:
```
$config['password_disabled'] = false;
$config['password_driver'] = "sql";
$config['password_confirm_current'] = true;
$config['password_force_save'] = true;
$config['password_force_new_user'] = false;
$config['password_algorithm'] = "dovecot";
$config['password_dovecotpw_method'] = "BLF-CRYPT";
$config['password_dovecotpw_with_method'] = false;
$config['password_blowfish_cost'] = 12;
$config['password_dovecotpw'] = "/usr/bin/doveadm pw";
$config['password_db_dsn'] = "mysql://...redacted...";
$config['password_query'] = "UPDATE accounts SET passwd=%P WHERE email=%u LIMIT 1";
```

Checking `doveadm pw -l` shows:
```
SHA1 SSHA512 SCRAM-SHA-256 BLF-CRYPT PLAIN HMAC-MD5 OTP SHA512 SHA DES-CRYPT CRYPT SSHA MD5-CRYPT PLAIN-MD4 PLAIN-MD5 SCRAM-SHA-1 SHA512-CRYPT CLEAR CLEARTEXT SSHA256 MD5 PBKDF2 SHA256 CRAM-MD5 PLAIN-TRUNC SHA256-CRYPT SMD5 DIGEST-MD5 LDAP-MD5
```

Manually running `doveadm pw -s BLF-CRYPT` works:
```
Enter new password:
Retype new password:
{BLF-CRYPT}$2y$05$H0jJ7bNXI8Plo2CYJtOpgORVjnIj/FzgxMMK3syCTTVgsRPqpu3HW
```

Nothing shows up in any of the logs for roundcube, php-fpm or httpd.
How to trouble shoot this?

**Comment by alecpl** [comment]
I have no idea what that might be. You'll have to investigate in password.php starting on line `$pipe = proc_open("$dovecotpw -s '$method'", $spec, $pipes);`
You may try to change `/dev/null` a line above to some other location. Also you may put `rcube::console($some_variable);` to log anything into Roundcube's logs/console.log file to see at which point it fails exactly.

**Comment by Github-Citizen** [comment]
I don't have the full answer yet and i need to ask the dovecot devs what changes were made. But this is what i have observed so far.

In dovecot 2.3.8 when you run doveadm as user apache you get an error but the command still executes.
```
# doveadm pw -s BLF-CRYPT
doveadm(apache): Error: net_connect_unix(/run/dovecot/stats-writer) failed: Permission denied
Enter new password:
Retype new password:
{BLF-CRYPT}$2y$05$aj4jIdQ80O/C4ECU3TSV6O5Shft4S.tZVL.ISvQ5cDU04nlxWcscu
```

However when you run doveadm as user apache in 2.3.16 you get a different fatal error.
```
# doveadm pw -s BLF-CRYPT
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf line 19: ssl_key: Can't open file /etc/letsencrypt/live/example_cert/privkey.pem: Permission denied
```

In my first testing i ran the command as root which is why i didn't experience this error. This error was also shown by capturing the stderr from open_proc().

Naturally unprivileged users shouldn't be able to read the privkey.pem. I just don't know what changed in doveadm to require this now or how doveadm got around the read permission in the previous version.

**Comment by Github-Citizen** [comment]
And to anyone else following this, i just stopped using dovecot in the roundcube password plugin. I changed to using
```
$config['password_algorithm'] = "blowfish-crypt";
```
which works to change passwords using PHP's built in functions instead of using dovecot's password utility.

FYI @alecpl; The plugin is using cyrpt() and php now recommends using password_hash() instead as it handles the salt automatically and provides stronger hashes.

**Comment by Github-Citizen** [comment]
@alecpl i got an answer from dovecot mailinglist.
```
There were some ssl setting handling cleanups in v2.3.11, which caused this.
I guess the proper fix for this would be to split SSL client settings and SSL server
settings. So doveadm would still read the SSL client settings without trying to
read the SSL server settings and failing there.

As a workaround, it should be possible to put the ssl_key into a separate config file
and use !Include_try for it. For example in dovecot.conf: !include_try ssl-keys.conf
```

Looks like using dovecot pw utility in the future is dead. I will just use the PHP function instead and consider this closed as there is nothing roundcube can do about it.

**Comment by Github-Citizen** [comment]
I slightly modified the blowfish method of the plugin to follow current PHP recommendations.
```
        case 'blowfish': // for BC
        case 'blowfish-crypt':
            $cost    = (int) $rcmail->config->get('password_blowfish_cost');
            $cost    = $cost < 4 || $cost > 31 ? 12 : $cost;
            $cost    = ['cost' => $cost];
            $crypted = password_hash($password, PASSWORD_BCRYPT, $cost);
            $prefix  = '{BLF-CRYPT}';
            break;
```

**Comment by Github-Citizen** [comment]
Looks like i spoke too soon. Aki replied today with
```
This is fixed with

https://github.com/dovecot/core/compare/79a210c1f7e94a1863f17db0b9f14b6d3c89e15f%5E..368a96783e8a64a62d07da4adcf2f3b1b525380b.patch

and will be in 2.3.17

Aki
```

**Comment by tomthorp** [comment]
Just noticed this thread and am in the same predicament, the only difference I am using CRAM-MD5 as authentication. How soon  will 2.3.17 appear in Fedora's RPM catalog? The latest I have atm is 2.3.14 .

**Comment by Github-Citizen** [comment]
Not sure, but you can use dovecot's own repo with yum/dnf to get the latest version without relying on your distro.
Repo details at https://repo.dovecot.org/

**Comment by alecpl** [comment]
I improved the error handling, so stderr from the command will be logged. There's nothing else we can do here.
