### ISSUE TITLE
OAuth2/OIDC discovery support

### ISSUE THREAD

**Issue by azmeuk** [roundcube/roundcubemail#8201]
Hi. Currently several URIs are mandatory in the oauth configuration:

```php
// Mandatory: URI for OAuth user authentication (redirect)
$config['oauth_auth_uri'] = null;

// Mandatory: Endpoint for OAuth authentication requests (server-to-server)
$config['oauth_token_uri'] = null;

// Optional: Endpoint to query user identity if not provided in auth response
$config['oauth_identity_uri'] = null;
```

However there is an [OAuth2 RFC](https://www.rfc-editor.org/rfc/rfc8414.html) and a [OIDC spec](https://openid.net/specs/openid-connect-discovery-1_0.html) that define standard URLs for json files describing the server metadata, and among other things, those URLs.

I suggest supporting those specs in roundcube, guess those URLs when possible, and make the configuration entries optional.

What do you think?

**Comment by alecpl** [comment]
It might not be good for performance reasons to do the discovery on every logon, so we'd need to cache this somewhere. Maybe, a better approach would be to provide a discovery script that then returns the urls, or maybe puts them into the config file.

**Comment by alecpl** [comment]
Implemented.
