### ISSUE TITLE
Database schema update failed.

### ISSUE THREAD

**Issue by mmm25002500** [roundcube/roundcubemail#8202]
I am installing Roundcube 1.4.11 
then i got the error
![image](https://user-images.githubusercontent.com/39051261/133714982-49b064c5-5a70-4b4c-941b-96b422eba6f9.png)

**Comment by alecpl** [comment]
What did you see/do just before that happened? Did you click the "Initialize database" button? Was the database initialized already (how)? I'm unable to reproduce.

**Comment by alecpl** [comment]
No feedback.
