### ISSUE TITLE
mail list in the Elastic theme does not show message size with out hovering over a specific item

### ISSUE THREAD

**Issue by VVelox** [roundcube/roundcubemail#8205]
When using the Elastic theme, one can't see the size with out hovering the mouse over the item in the list in question.

This is bad for using it on touch screen interfaces as in general moving the mouse with out clicking/dragging is not something that is usually supported.

**Comment by alecpl** [comment]
Do you have a better idea? There's no place for size on the list. I can live with limited feature set on mobile.

**Comment by VVelox** [comment]
I would put it to the left of the date.

The first line tends to have plenty of space given it is rare for the from to be long enough to cause an issue, compared to the likely hood of the subject being very long.

As to mobile, this location would work perfectly fine. Or atleast on my pinephone there is plenty of space there. So I don't see it being an issue of mobiles of similar screen size/resolution.

**Comment by alecpl** [comment]
I'd say that on a screen width=1200px the default list width is not enough to put the size where you propose. I think, the list width would have to be at least 350px to allow for that. So, maybe it would work on most mobile or big screens, but in some cases we'd loose some clarity if we put size near the date or sender. I'm not convinced.

**Comment by VVelox** [comment]
On my pinephone it is way under a width of 1200px, only 720px, there is very consistently more than enough room on that line for it.

```
mobian@mobian:~$ wlr-randr 
DSI-1 "<Unknown> <Unknown>  (DSI-1)"
  Physical size: 68x136 mm
  Enabled: no
  Modes:
    720x1440 px, 60.006001 Hz (preferred)
mobian@mobian:~$ 
```

That said it is using the compressed manner with only showing the relevant section at a time for that theme, so not trying to show all three panes.

Even if not default, it would be a nice option to have, IMHO.
