### ISSUE TITLE
New folders are created with "Sent" Icon

### ISSUE THREAD

**Issue by jgmy** [roundcube/roundcubemail#8207]
I made a new folder inside "Archive" and its icon turned to the "sent" icon (paper plane).
I made a new  folder inside "Received" and its icon turned to the "sent" icon, too
![bug](https://user-images.githubusercontent.com/2573642/134152713-e64807d5-ba37-49a9-bc6f-d0ef3399f2e9.jpg)

Roundcube Webmail 1.4.11
Plugins:

additional_message_headers | 1.2.1 
advanced_search | 3.4 
archive | 3.4   
attachment_reminder | 1.1 
automatic_addressbook |   
cloud_button | 1.0.2 
contextmenu | 3.2.1 
emoticons | 2.0 
enigma | 0.8 
fail2ban | 1.3
filesystem_attachments | 1.0 
filters | 2.2.1 
forward | -- 
globaladdressbook | 2.0.1 
hide_blockquote | 1.0 
html5_notifier | 0.6.4 
identity_select | 1.1 
jqueryui | 1.12.0 
markasjunk | 2.0 
message_list_attachment_size | -- |   |  
new_user_dialog | 2.4 
show_additional_headers | 2.0
show-folder-size |  
subscriptions_option | 1.4 
swipe | 0.4 
userinfo | 1.2
vacation | -- 
xbackground | 1.1.8 
xcalendar | 1.9.3 
xemail_schedule | 1.1.4 
xskin | 1.7.2 
zipdownload | 3.4

**Comment by alecpl** [comment]
They both start with "Present", maybe that's some clue. What is the name of the Sent folder? Does it work if you disable all plugins?

**Comment by alecpl** [comment]
It's not that simple. I'd appreciate answers to my questions.

**Comment by jgmy** [comment]
Hi, Alexander.

It is not easy for mee, too. Sorry!

My default "Sent" folder is called "Enviados", NOT "Sent".

But when I open it from "samsung mail" on my phone, it is called "Sent".
There is another "Sent" folder on server — on my phone client (not
roundcube), emails are transferred from "Sent" to "Sent".

So it seems the imap server has two "Sent" folders and one of them is
transparently renamed to "Enviados" by roundcube.

On the other hand, changing folder names from "Presentaciones XXX" to
"Prsnt XX" solves the icon problem. Many thanks for that hint.

I wish I had time to dive onto the source and be helpful. I understand this
is a small budget project, regardless of being used by thousands of
companies that pay nothing for it.

Yours,
José G. Moya Y.

P.S. Writing from cellphone. Beware the typos.

**Comment by alecpl** [comment]
I'm unable to reproduce.
