### ISSUE TITLE
PHP 8 - RC 1.5rc

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#8208]
If i try to use Roundcube 1.5 rc, i get the message "Unsupported PHP version. Required PHP >= 5.4 and < 8.0." I thought that PHP8 is supported since 1.5 beta? Or do i miss something?

**Comment by teoberi** [comment]
Which version of PHP do you use 8.0 or 8.1?

**Comment by Offerel** [comment]
8.010 Standard on Arch Linux.

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/4e1358b4dc1a8116357657ae5c8738e855aea85a/program/include/iniset.php#L23 this code exists only in 1.4.

**Comment by Offerel** [comment]
I see... and i'm clueless. I have no explanation so far. I'm in the following situation. I migrate from Debian to Arch Linux. Thats why im using PHP 8, since this is the standard on Arch. I have downloaded `wget roundcubemail-1.5-rc-complete.tar.gz`. Extracted the tarball to `/usr/share/nginx/roundcubemail-1.5-rc`. Set a symlink `ln -sr roundcubemail-1.5-rc roundcube`. If i do `cat /usr/share/nginx/roundcube/program/include/iniset.php | grep Unsupported` the line didn't exist. However, with`cat /usr/share/nginx/roundcube/program/include/iniset.php | grep RCMAIL_VERSION` i can see that this is indeed 1.5-rc

Nginx has at least a configuration like this (and a little bit more of course):
```
location /rctest {
    index index.php;
    alias /usr/share/nginx/roundcube/public_html;
    .... php config and so on...
}
```

With the symlink, i can normally switch version or do a rollback to a previous one easily. Now, im a little bit lost... I have must misconfigured something, so that it uses another version.

**Comment by Offerel** [comment]
Have found it. Sorry for complaining. My own fault... in config.php, i had my old path to the sqlite db. I have changed this now and its working as expected. I have no idea, why this will change the paths for the installation, but it solved now. Many thx for the support.
