### ISSUE TITLE
OAUTH: Do not delete `id_token` from `$_SESSION['oauth_token']`

### ISSUE THREAD

**Issue by azmeuk** [roundcube/roundcubemail#8214]
Hi. I plugged roundcube with [rcmcarddav](https://github.com/mstilkerich/rcmcarddav) so it can fetch the contacts of my nextcloud instance, using [nextcloud-oidc-login](https://github.com/pulsejet/nextcloud-oidc-login/).

Nextcloud needs a JWT to authenticate the users, and check the `aud` claim in the token. rcmcarddav cannot give the `id_token` to nextcloud as roundcube deletes it and only let the `access_token`. Some providers like [canaille](https://gitlab.com/yaal/canaille/) fills `id_token` with a JWT, but `access_token` with a regular non JWT token (as [the spec illustrates](https://openid.net/specs/openid-connect-core-1_0.html#id_token-tokenExample)).

https://github.com/roundcube/roundcubemail/blob/1d2ad936a729ff7fec9d595b35f8e92ce7c5e44d/program/include/rcmail_oauth.php#L250

I could not figure what purpose it serves to delete `id_token`, but removing this line ([plus another tweak in rcmcarddav](https://github.com/mstilkerich/rcmcarddav/issues/354)) does fix the situation, as it allows rcmcarddav to forward the ID token to nextcloud.

I suggest not removing `id_token`. I volunteer to provide a patch if it is OK with you.

**Comment by alecpl** [comment]
As mentioned in https://github.com/mstilkerich/rcmcarddav/issues/354 using id_token in this scenario is probably not the way it should be done. Therefore, I'm for a wontfix on this.

@thomascube for the last word. Maybe we could pass the `id_token` to the `oauth_login` hook, but not keep it in session.

**Comment by thomascube** [comment]
I think we should not always store `id_token` in session but we might pass the full JWT `$data` to the `'oauth_login'` plugin hook. Then plugins like rcmcarddav can pick it from there and store it themselves if necessary.
