### ISSUE TITLE
.htaccess in dir public_html

### ISSUE THREAD

**Issue by Speravir** [roundcube/roundcubemail#8225]
Not a bug, but a suggestion:

Interestingly this is different in the resource, but the `.htaccess` file in directory `public_html` found in the shipped `roundcubemail-1.5-rc-complete.tar.gz` looks actually this way:
```
Link: ../.htaccess
```
Maybe a professional admin instantly recognizes the intention of this, at latest when reading the error log entry which coincidentally results from this invalid directive, but what about some more words in a comment before this, e.g.
```
# Replace this file with an equally named symbolic link to the ".htaccess" in parent directory
Link: ../.htaccess
```

And since it’s invalid anyway why not even make it more clear with using a directive like `CreateLinkTo`, so
```
# Replace this file with an equally named symbolic link to the ".htaccess" in parent directory
CreateLinkTo ../.htaccess
```

Not being a native English speaker I had some struggles in understanding, because I forgot that “link” can be both a noun _and_ a verb.

**Comment by alecpl** [comment]
I don't know what did you do to extract the archive, but for me `public_html/.htaccess` is a real link.

**Comment by Speravir** [comment]
OK, I didn't know it could be depend on the uninstaller (7-Zip).
