### ISSUE TITLE
Add a note about some subdirectories in installation part of wiki

### ISSUE THREAD

**Issue by Speravir** [roundcube/roundcubemail#8226]
In the [Installation part](https://github.com/roundcube/roundcubemail/wiki/Installation) of the Roundcubemail Wiki there is an advice, in itself useful, in section [Protect your installation](https://github.com/roundcube/roundcubemail/wiki/Installation#user-content-protect-your-installation):

> When running Roundcube at root of a virtual host, it's recommended to set the document root of that virtual host to the `public_html` directory of your Roundcube installation.

The issue is that doing this among the other Roundcube subdirectories, where it is useful, also the ones containing scripts, styles and images are not reachable anymore from the web. A note, that these should be made available by adding an Alias or AliasMatch directive (which needs an enabled `mod_alias`), would be useful in my opinion. Perhaps give the explicit example
```apache
AliasMatch "/(plugins|program|skins)(.*)$" "/absolute/path/to/roundcubemail/$1$2"
```

**Comment by alecpl** [comment]
I think this is related to #8225. public_html/plugins and public_html/skins are supposed to be links, as well as program/js and program/resources.
