### ISSUE TITLE
Roundcube 1.4.11 & MariaDB 10.6 - UTF-8

### ISSUE THREAD

**Issue by nardisf** [roundcube/roundcubemail#8241]
Since upgrading mariadb from 10.1 to 10.6 roundcube no longer connects to database when trying to log in.  Examining httpd error log I find " Character set 'utf8' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml' file"  We were able circumvent the issue by adding the following section to /var/log/mysql/charsets/Index.html.
``
<charset name="utf8">
  <family>Unicode</family>
  <description>UTF-8 Unicode</description>
  <alias>utf-8</alias>
  <collation name="utf8mb3_general_ci"  id="33">
   <flag>primary</flag>
   <flag>compiled</flag>
  </collation>
  <collation name="utf8mb3_bin"         id="83">
    <flag>binary</flag>
    <flag>compiled</flag>
  </collation>
</charset>
``
Note that this block is a copy of the "utf8mb3" block with only the charset name changed to "utf8".
This addition allowed roundcube to connect to the database and operate as expected.
Specifics:
Roundcube 1.4.11
MariaDB 10.6.4
Apache 2.4.6
Centos 7.9

**Comment by alecpl** [comment]
1.5.0 is using `utf8mb4`. Nothing to fix here.
