### ISSUE TITLE
Server error! message while uploading attachment more than 1MB

### ISSUE THREAD

**Issue by khamsakamal48** [roundcube/roundcubemail#8244]
Hi,

We are facing a weird error while uploading attachments with file-size greater than 1MB. Basically to the user it displays as 'Server error'.

On checking the maillog, below error is displayed for such incidents:

`Oct 21 16:37:32 postbox dovecot[1142]: imap(kamal.hamsa)<68575><W2vYldrOdcAKxwRg>: Connection closed (IDLE running for 0.001 + waiting input for 1056.735 secs, 2 B in + 10 B out, state=wait-input) in=769 out=2826 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=0 body_count=0 body_bytes=0`

Also, the issue isn't reproduced over local LAN (Intranet) and is only persistent when connected over Internet and that too randomly. Sometimes, it works and sometimes it throws 'Server error'. Initially we thought its a network issue but the occurrence is random only over internet. Also, issue doesn't occur when attachment size is less than 1MB.

I have already checked the file upload limit in *.ini and postfix files and they are above the limit. Since I don't experience this issue over Intranet, I don't know if that's really the cause.

Nevertheless, any help or guide is appreciated.

**Comment by alecpl** [comment]
Sending a mail and uploading a file is two distinct things. Please, don't confuse. I miss the basic information. Roundcube version, PHP version, installed plugins, errors from the Roundcube log or http server error log, errors from the browser console.

**Comment by alecpl** [comment]
No feedback.
