### ISSUE TITLE
Move Classic and Larry skins to their own repositories

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#8271]
I don't really have time to support all the skins. And having them in core is kind of an obligation to keep them up to date with any new features. So, I don't want that burden. Anyone interested in keeping these skins up-to-date will have to provide pull requests. I can promise some time to review/merge/build, but I do not plan to work on bugs and new features there.

Since skins can be installed with composer, the installation will be very easy and should not be a problem for anyone.

**Comment by teoberi** [comment]
I haven't used Classic and Larry skins for a while and no other users of my mail servers. If Elastic is updated for me everything is OK!

**Comment by thomascube** [comment]
✓ Classic skin is available in its [own repository](https://github.com/roundcube/classic) and installable via [composer/packagist](https://packagist.org/packages/roundcube/classic).

**Comment by alecpl** [comment]
Larry skin moved to https://github.com/roundcube/larry.
