### ISSUE TITLE
Contacts -> Trusted Senders -> Documentation?

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8272]
Is there any documentation about the new Trusted Senders feature in Contacts?

How do contacts get in the Trusted Senders other than manually creating contacts?
How is Trusted Senders used? What is it for?
What does it mean when a contact is in Trusted Senders?
Does roundcube do anything with that information automatically?

**Comment by alecpl** [comment]
https://kolabian.wordpress.com/2020/09/26/collected-recipients-and-trusted-senders/

Basically it's used with Preferences > Displaying Messages > Allow remote resources (images, styles).
