### ISSUE TITLE
Addressbook import: Undefined constant

### ISSUE THREAD

**Issue by icdsoftware** [roundcube/roundcubemail#8277]
https://github.com/roundcube/roundcubemail/blob/b9878925245e742d1f52c2085aaf3b90c8e43fc1/program/actions/contacts/import.php#L259

PHP Fatal error:  Uncaught Error: Undefined constant "UPLOAD_ERR_CSV_FIELDS" in  .../program/actions/contacts/import.php:256

I guess the reference should be changed to self::UPLOAD_ERR_CSV_FIELDS

**Comment by alecpl** [comment]
Fixed.
