### ISSUE TITLE
problem with attachments of emails sent from Thunderbird

### ISSUE THREAD

**Issue by goglushkov** [roundcube/roundcubemail#8278]
Good afternoon, I will immediately apologize for my English. He's bad, sorry.
The problem is this:
When sending a letter from Thunderbird, the incoming message comes in this format - the attachment comes with the wrong encoding.
![image](https://user-images.githubusercontent.com/85469348/139812531-439002b5-f98d-491c-817e-fbe3e68e9ad5.png)
Please help me fix it. This problem is observed on different versions.

P.S. The problem is observed only with the Cyrillic alphabet

**Comment by goglushkov** [comment]
I also tried changing the encoding settings, it didn’t work.

![image](https://user-images.githubusercontent.com/85469348/139812899-40915d18-a59e-4349-80f1-74349954a872.png)

**Comment by alecpl** [comment]
What Roundcube version? Could you provide a raw attachment part headers? It may be an imap server issue as well, provide imap_debug log from the moment you open the message (look for BODYSTRUCTURE).

**Comment by goglushkov** [comment]
Version - roundcubemail-1.4.6-complete
This issue only occurs if you send an email from the Thunderbird email client
If the letter is sent via Outlook, there is no such problem
![image](https://user-images.githubusercontent.com/85469348/139814331-a63dcd99-8db2-4655-9758-91ffa22c36e6.png)

**Comment by goglushkov** [comment]
Not work 
![image](https://user-images.githubusercontent.com/85469348/139814730-30059e01-0b17-4fba-9f52-641f62bb0064.png)
Work
![image](https://user-images.githubusercontent.com/85469348/139814820-50f70c2a-c592-4319-a917-22108cee2843.png)

**Comment by goglushkov** [comment]
I am attaching full letters with a working letter and a non-working one.
[notWork.txt](https://github.com/roundcube/roundcubemail/files/7459225/notWork.txt)
[Work.txt](https://github.com/roundcube/roundcubemail/files/7459226/Work.txt)

**Comment by alecpl** [comment]
Works for me. I suspect imap server issue here. 1.4.6 is also not the most recent one.

**Comment by goglushkov** [comment]
Thank you, we will check it now. Can the ticket hang for some more time? If what I write

**Comment by goglushkov** [comment]
Also you asked for imap debugging
[imapDebuging.txt](https://github.com/roundcube/roundcubemail/files/7459352/imapDebuging.txt)

**Comment by alecpl** [comment]
```
("attachment" ("filename" "UTF-8'
'%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B0%2E%6A%70%67"))
```
it should be "filename*" not "filename".

**Comment by alecpl** [comment]
You can try 1.5.0, I remember there was some workaround for similar issues.

**Comment by goglushkov** [comment]
Thank you, then I'll go install 1.5.0 now.

**Comment by goglushkov** [comment]
Thanks, installing rc 1.5.0 really helped
