### ISSUE TITLE
Cannot use Yandex.

### ISSUE THREAD

**Issue by Slddev** [roundcube/roundcubemail#8279]
So I'm using Yandex as my email provider and IMAP works, but SMTP doesn't work. Error message from the installer states:

> SMTP send:  NOT OK (Connection failed: Failed to connect socket: Network is unreachable)

this is my config for SMTP:
```php
$config['smtp_server'] = 'ssl://smtp.yandex.com.';
$config['smtp_port'] = 465;
$config['des_key'] = 'REDACTED';
```

Thank you!

**Comment by alecpl** [comment]
"Network is unreachable" suggest the issue is not in Roundcube.

**Comment by Slddev** [comment]
> "Network is unreachable" suggest the issue is not in Roundcube.

Then what is?

**Comment by alecpl** [comment]
Networking?

**Comment by Slddev** [comment]
> Networking?

What does that mean?

**Comment by alecpl** [comment]
Firewall, DNS, whatever.

**Comment by Slddev** [comment]
> Firewall, DNS, whatever.

Everything seems to be working, except SMTP even IMAP works.
