### ISSUE TITLE
Mailman  website lists.roundcube.net offline

### ISSUE THREAD

**Issue by jger3110** [roundcube/roundcubemail#8280]
For days now the mailman management website lists.roundcube.net is offline. It is neither possible to disbable the password reminder mails (which btw sends  the users password in clear text via mail) nor to manage any mailing list memberships. Managing the mailing list memberships via mail seems unresponsive, I got the inital mail on my help command almost a day later, any other mail with commands are unanswered. 
As I can neither find any contact form nor contact mail I am trying it here.

**Comment by alecpl** [comment]
The problem with the delay was probably temporal. It works for me fast right now.

The UI of Mailman is known to be insecure. I'm not sure we'll provide it again soon.
