### ISSUE TITLE
[BUG] Upgrade from 1.4.11 to 1.5.0 fails with  Error in DDL upgrade 2020020101 Can't DROP FOREIGN KEY `user_id_fk_cache`; check that it exists

### ISSUE THREAD

**Issue by behemoth88** [roundcube/roundcubemail#8281]
Hi.
When trying to update RC from version 1.4.11 to 1.5.0, a following error is thrown:
`Executing database schema update.
Updating database schema (2020020101)... [FAILED]
ERROR: Error in DDL upgrade 2020020101: [1091] Can't DROP FOREIGN KEY `user_id_fk_cache`; check that it exists
`
Current schema version is: 2020020100
OS: Centos 7
DB: MariaDB 10.2

**Comment by alecpl** [comment]
It looks like you tried to run the upgrade more than once. Now, your database schema is in an inconsistent state.

I think you might have hit the other bug #8231. So, I would suggest use a backup and apply patches to make the upgrade working or wait for Roundcube 1.5.1. Or fix the database manually by comparing the tables in your database with what is in SQL/mysql.initial.sql.

**Comment by behemoth88** [comment]
Yep, you're right @alecpl.
The reason for this is I was using MariaDB 10.1 on the server, so the upgrade failed, as described in #8231.
I've upgraded Maria to version 10.2, but apparently, the database is, as you previously said, in inconsistent state.
So new version (1.5.1) will address and fix this issue?
