### ISSUE TITLE
Fetching headers of multiple message parts at once in rcube_imap_generic::fetchMIMEHeaders() does not work

### ISSUE THREAD

**Issue by goglushkov** [roundcube/roundcubemail#8282]
Good afternoon, again) After updating Roundcube to 1.5.0, the problem with file attachments was resolved, but partially. If file 1, there are no problems, everything is fine, if there are 2 files - the first file is normal, the second with problems.
![image](https://user-images.githubusercontent.com/85469348/140016941-766944d3-9e36-4624-b5aa-b0a8d9497bea.png)

**Comment by alecpl** [comment]
Provide the message source and imap_debug.

**Comment by goglushkov** [comment]
[message.txt](https://github.com/roundcube/roundcubemail/files/7465656/message.txt
[imap_debug.txt](https://github.com/roundcube/roundcubemail/files/7465671/imap_debug.txt)
)

**Comment by alecpl** [comment]
The message.txt is incomplete.

**Comment by goglushkov** [comment]
[message.txt](https://github.com/roundcube/roundcubemail/files/7465728/message.txt)
Corrected

**Comment by alecpl** [comment]
Confirmed. Looks like a bug in `rcube_imap_generic::fetchMIMEHeaders()`.

**Comment by goglushkov** [comment]
Great, as I understand it, I will periodically need to look at this topic to wait for a fix?

**Comment by alecpl** [comment]
Fixed.

**Comment by goglushkov** [comment]
Thank you very much!!!!
