### ISSUE TITLE
Attachments download/preview CSRF check failed in Elastic skin

### ISSUE THREAD

**Issue by icdsoftware** [roundcube/roundcubemail#8283]
Steps to reproduce (Elastic skin):
1. Open email with attachments
2. Click on **Show** on any attachment
3. In the new window, click on the  **Properties** button at the top, then close the properties dialog.
4. Click on Download, the error shows up.

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Fixed.
