### ISSUE TITLE
"To protect your privacy remote resources have been blocked." 

### ISSUE THREAD

**Issue by moreir4** [roundcube/roundcubemail#8284]
Our server's roundcube is behaving strangely:

By clicking "allow" when the message "To protect your privacy remote resources have been blocked." is displayed, instead of displaying the blocked content, a website is opened in the field where the email should be displayed.

One way to work around this behavior is to leave remote resource viewing enabled by default.

Have you ever seen something like that?

**Comment by alecpl** [comment]
Sounds like #8170.
