### ISSUE TITLE
Roundcube login pass username and password in parms

### ISSUE THREAD

**Issue by Raavtube** [roundcube/roundcubemail#8285]
I am making a face page that will have more authentication and a nicer UI. I wanted to know if it was possible to pass an encrypted string that contains the user and pass elements to the login page to have it skip RoundCubes login page.

So my login page would authenticate, then it would look up the encrypted string: aDKfiwejLFie8398(*hf3eoahifeuh and then redirect to a link like this:

example.com/mail?s=aDKfiwejLFie8398(*hf3eoahifeuh

Then Roundcube would know to bypass the internal login system. How can I go about doing this?

**Comment by alecpl** [comment]
Write a plugin similar to autologon or http_authentication.

**Comment by Raavtube** [comment]
thank you
