### ISSUE TITLE
In v.1.5: undefined array key in rcmail.php

### ISSUE THREAD

**Issue by Speravir** [roundcube/roundcubemail#8286]
In version 1.5 and with PHP 8.0.12 I frequently get this warning:
 > Undefined array key 1 in C:\Programs\Roundcubemail\program\include\rcmail.php on line 954

It’s this call inside of a function `autoselect_host()`:  
```php
list(, $domain) = explode('@', $post_user);
```
which apparently is in sourcecode meanwhile found in [line 979](https://github.com/roundcube/roundcubemail/blob/8a4eecbcb00eea109c0bd24475e08036ae698eac/program/include/rcmail.php#L979).

**Comment by alecpl** [comment]
Fixed.
