### ISSUE TITLE
integer env parsing in rcube_config.php possibly broken

### ISSUE THREAD

**Issue by gutmensch** [roundcube/roundcubemail#8293]
I have an environment variable exposed to roundcube called
```
ROUNDCUBE_MANAGESIEVE_PORT=4190
```
This results in an endless parsing loop in https://github.com/roundcube/roundcubemail/blame/master/program/lib/Roundcube/rcube_config.php with the detected values and parameters from parse_env and guess_type being always
```
[06-Nov-2021 12:26:21 UTC] 4190
[06-Nov-2021 12:26:21 UTC] float
[06-Nov-2021 12:26:21 UTC] float
```
One reason seems to be that the order of float and integer detection in guess_type seems wrong, the float regex also matches integers (see screenshot), so probably integer should be checked first. The other reason is maybe that parse_env enters a recursion because it never returns for a float value, only for double. Was that missed in some earlier change from float to double?!

<img width="1396" alt="Screenshot 2021-11-06 at 13 31 24" src="https://user-images.githubusercontent.com/585578/140609853-5a5fe9e0-0c46-4e5f-8e49-a8bb1962545d.png">

Thanks anyway for the great project and keep up the good work!
Cheers,
Robert

**Comment by alecpl** [comment]
Fixed.
