### ISSUE TITLE
Feature Request; Default word wrap behavior

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8294]
**-- PREAMBLE --**

I noticed in config if you set `$config['line_length'] = -1;` it disables any word wrapping to the composed message. However this is not documented in `defaults.inc.php`, it only says:
```
// number of chars allowed for line when wrapping text.
// text wrapping is done when composing/sending messages
$config['line_length'] = 72;
```

Is the `-1` setting intended and should be documented? Or is it a happy accident that `-1` disabled composed message word wrap because of a bug? I like the current behavior of `-1`.

**-- REQUEST --**

I think in `defaults.inc.php` the default behavior should be:
```
// number of chars allowed for line when wrapping text.
// text wrapping is done when composing/sending messages
// or set to -1 to disable text wrapping
$config['line_length'] = -1;

// send plaintext messages as format=flowed
$config['send_format_flowed'] = false;
```
Because email readers / clients all have word wrapping which the receiver sets to their preference. There is no need to force word wrapping before sending.

I would argue that it is a bad thing because the sending email is being altered different than the author intended and could mess up their formatting. The email should be sent as the author intended and let the receivers client perform the word wrapping per the receivers preference.

An email can be very ugly if the sending world wrap character count is different than the receivers character count, you end up with lines chopped twice.

**Comment by alecpl** [comment]
This is by accident. If you want you can set it to 999. Also, in git-master we have a UI checkbox to disable the wrapping.

**Comment by Github-Citizen** [comment]
What do you mean when you say git-master? Does that mean the 1.5.0 version? I thought this git was the master.
I do not see any option in the UI for wrapping. Or do you mean some where else?

![Capture](https://user-images.githubusercontent.com/80302627/140617019-b9998f2f-0dc9-464d-ae19-ea62489bb6eb.PNG)
