### ISSUE TITLE
Question: Mailvelope button is grayed out?

### ISSUE THREAD

**Issue by Marco-Total** [roundcube/roundcubemail#8301]
Hello

I would like to encrypt my emails with the Mailvelope.

For this I installed the add-on in Firefox, generated the keys and authorized my domain.
![grafik](https://user-images.githubusercontent.com/6968432/140770226-974fbd36-49a6-402c-b185-4f95c62d14d6.png)
![grafik](https://user-images.githubusercontent.com/6968432/140770038-5e715f0b-fa2e-4395-8d8c-04fd819cb826.png)

In the Roundcube I activated the encryption in the settings.
![grafik](https://user-images.githubusercontent.com/6968432/140770311-d3597fdc-b863-40ff-9344-e56ce2f5dd6b.png)

When I create a new email, the encryption button is grayed out.
![grafik](https://user-images.githubusercontent.com/6968432/140770431-61b9ee27-f47b-41f2-b66e-ce00fab241b9.png)

What am I doing wrong?

**Comment by alecpl** [comment]
The Mailvelope-based encryption does not work in HTML mode. You have to use the plain text mode of the message body editor.
