### ISSUE TITLE
Request feature : inject HTML

### ISSUE THREAD

**Issue by songsammy** [roundcube/roundcubemail#8302]
I want to put statistics code (lines of JavaScript in wrapped in a  `<script>` tag) on every page, right before the closing `<\head>`. I know I could do this by modifying the templates, but is there an easy way?

**Comment by jtuta** [comment]
I would probably go with custom plugin and `$this->include_script('...')` inside `int()`., see https://github.com/roundcube/roundcubemail/wiki/Plugin-API
