### ISSUE TITLE
Allow remote content loads server main page.

### ISSUE THREAD

**Issue by 80kk** [roundcube/roundcubemail#8304]
Bug similar to the one I've raised here: https://github.com/roundcube/roundcubemail/issues/8228 which I've been able to fix by applying this: https://github.com/roundcube/roundcubemail/issues/8170#issuecomment-922436182
Unfortunately this doesn't work for the remote content in the message. If I click on Allow button then it loads the server (Mailcow)  main page.

**Comment by alecpl** [comment]
I don't understand. What is different than #8228 here? Steps and screenshots, please.
