### ISSUE TITLE
SO MUCH SPAM

### ISSUE THREAD

**Issue by MBelleza** [roundcube/roundcubemail#8305]
Can anyone help me? I am getting HUNDREDS of emails from names like "otkntwecxh " with subject lines like "tspyhpomex" and I can't figure out how to filter them out, and I don't have time to delete them all every day. I literally just got 5 in 10 minutes :(

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
