### ISSUE TITLE
Feature Request: Add List-ID to the list of headers for creating new sieve-filters

### ISSUE THREAD

**Issue by 0xErnie** [roundcube/roundcubemail#8307]
I am subsribed to lots of mailinglists. I would like to add a new filter from an email with ease. Right now Roundcupe only scans for "from", "to" and "subject". Adding "list-id" would make it a lot easier for everyone using a lot of mailing lists.

Maybe the only thing that needs to be changed is:
https://github.com/roundcube/roundcubemail/blob/f7ba562bed77a3fbdf70308e345f34c8f03f1cff/plugins/managesieve/managesieve.php#L308-L309

edit: There is even a hint for adding list-id in the code already ❤️

**Comment by seanm** [comment]
Also `X-BeenThere` would be similarly helpful.

**Comment by alecpl** [comment]
`List-ID` implemented.
