### ISSUE TITLE
"Dark Mode" makes scrollbars too narrow

### ISSUE THREAD

**Issue by trueshanti** [roundcube/roundcubemail#8309]
Switching from bright- to darkmode lets horizontal scrollbars get slimmer (with) .. this inflicts problems targeting scrollbars with pointerdevices , especially when using screensetting for handicapped people (like HUGE cursor). even using touchscreen is harder

if the sliders wouldnt loose width and also the up/down-arrow of the scrollbar wouldnt vanish in darkmode - it would all be fine

thanks for this great software

rc version is 1.5.0
i can reproduce this in latest firefox and chromium

**Comment by trueshanti** [comment]
this happens up to the viewpoint that disables the icon-titles on the leftside funtionbar (tested by zooming in) then the browser switches back to unthemed scrollbars - which is good again and not so ugly anyway ;-)

**Comment by alecpl** [comment]
I like these scrollbars and I'm not sure what to do about it. Maybe we should have some accessibility setting, but I'd hesitate to add it only for this single purpose.

**Comment by trueshanti** [comment]
Hi, so you can see the difference ? its  approx 2 standard-pixels , thats a huge  difference for a single interface-element. If one sees it as "accessible"-related, so might it be .. 

But I am not required to use accessible-interfaces, and even I find it already making the interface more difficult to use .. 

So people with optical handycaps will have even more issues (as reported)

https://imgur.com/a/1Am6kT3

**Comment by alecpl** [comment]
In master we use slim scrollbars in both dark and light modes. You can change the scrollbar width and rebuilt the skin now. We'll not change the default.

**Comment by manfredu** [comment]
Am 2022-02-04 08:53, schrieb Aleksander Machniak:

> In master we use slim scrollbars in both dark and light modes. You can 
> change the scrollbar width and rebuilt the skin now. We'll not change 
> the default.

It is very difficult to use the small scrollbars in dark mode for 
scrolling. When clicking on the bar, in most cases the function to 
increase the column width gets activated first.

So the only option left for scrolling is the scroll wheel of the mouse, 
but clicking on the bar and dragging it, is nearly impossible.

**Comment by trueshanti** [comment]
exactly the issue ..
@alecpl : i would like to know where i could put changes in css/less to get rid of exactly this .. like setting the same values in darkmode as they are in lightmode  - can you please point me to ?

i am no css-guru :-o

**Comment by alecpl** [comment]
Create `skins/elastic/styles/_variables.less` file and there you can put this:
```
@scrollbar-width:       thin; // 'auto' or 'thin' or 'unset'
@scrollbar-dark-width:  thin; // 'auto' or 'thin' or 'unset'
```
This works in git-master only.
