### ISSUE TITLE
Remove configuration options for imap/smtp/managesieve/ldap port 

### ISSUE THREAD

**Issue by alecpl** [roundcube/roundcubemail#8310]
It is not stated clearly in the configuration file comments, but all "host" options support `host:port` syntax. Therefore I suggest we remove the associated "port" options.

For IMAP:
- remove `default_port` option
- if `default_host` does not include a port, use 993 if ssl:// prefix is used, 143 otherwise.
- we could also rename `default_host`, to `imap_host`.

For SMTP:
- remove `smtp_port` option
- if `smtp_server` does not include a port, use 465 if ssl:// prefix is used, 587 otherwise.
- we could also rename `smtp_server`, to `smtp_host`.

For LDAP:
- remove `port` option from `ldap_public` array.
- remove `use_tls` option from `ldap_public` array.
- if `hosts` does not include a port, use 636 if ldaps:// prefix is used, 389 otherwise.

For managesieve:
- remove `managesieve_port` option.
- remove `managesieve_usetls` option
- if `managesieve_host` does not include a port, determine it automatically with a fallback to 4190.

**Comment by alecpl** [comment]
@thomascube any objections?

**Comment by thomascube** [comment]
@alecpl Agreed. We just have to document this breaking change or automatically migrate old configs.

**Comment by alecpl** [comment]
Done.
