### ISSUE TITLE
Wrong sort order in threaded mails

### ISSUE THREAD

**Issue by heinrichmartin** [roundcube/roundcubemail#8311]
Preconditions: view threads, sort by date descending (newest on top)

Observed: mails within a thread do not sort correctly, but oldest on top

Expected: mails within a thread follow the sort order (here: newest on top)

Version: Roundcube Webmail 1.5.0

Notes:
- The thread correctly sorts according to its newest message (under my precondition) - and this should not change. I assume that in general, it should sort according to the top-most message in the thread (after the fix), but I have not thought that through.
- A quick search revealed references (no existing issues though):
  - same: https://talk.plesk.com/threads/roundcube-not-displaying-inbox-by-date-properly.344021/#post-839889
  - related: https://github.com/roundcube/roundcubemail/issues/499#issuecomment-772336873

**Comment by alecpl** [comment]
This is not how threading works. Inside the thread the messages are in date-ascending order so user knows who replied when to whom. It's especially important for mailing lists where threads might have multiple branches. Re-sorting the thread internal structure would make no sense.

So, this is not a bug. You might be interested in the so-called conversation view, which you already referred to.

**Comment by SawkeeReemo** [comment]
> This is not how threading works. Inside the thread the messages are in date-ascending order so user knows who replied when to whom. It's especially important for mailing lists where threads might have multiple branches. Re-sorting the thread internal structure would make no sense.
> 
> So, this is not a bug. You might be interested in the so-called conversation view, which you already referred to.

Hate to break it to you, but iOS Mail and Apple Mail do this perfectly and it makes much more logical sense. Email is a dumpster fire, having the latest at the top has finally made it more bearable. Would love to bring the same sanity to Roundcube one day. (That and highlighting unread emails better, like with a color instead of just bold text that doesn’t stand out well. Those would be two huge QoL improvements.)
