### ISSUE TITLE
RC 1.5 no edit button in adressbook in seach mode

### ISSUE THREAD

**Issue by kadolino** [roundcube/roundcubemail#8315]
In Roundcube 1.5: adressbook is no edit button if I want to edit an adress book entry after searching an adressbook user.

Both, elastic an larry skin.

![screenshot](https://user-images.githubusercontent.com/47841723/141939584-7ba98dc9-2ee0-4024-b904-d20860cd50db.jpg)

**Comment by alecpl** [comment]
Maybe because this contact is from a read-only addressbook.

**Comment by kadolino** [comment]
OK, the adress come from collected recipients not from a normal adress bokk entry.
