### ISSUE TITLE
Message counter in the page title only available for INBOX

### ISSUE THREAD

**Issue by llucps** [roundcube/roundcubemail#8316]
Hi,

I'm only getting the new email notification icon with emails arriving on the Inbox but not on any other subfolder. As you can see on the screenshot, although the server checks for emails on all the folders including subfolders, only those on the Inbox trigger the notification (1) at the tab.

![Screen Shot 2021-10-29 at 10 45 37](https://user-images.githubusercontent.com/25823659/142217716-a7a4dae6-efdb-482a-9ef6-7bf56711b999.png)

I also have this option on my config.inc.php

`$config['check_all_folders'] = true;`

Is there anything I can do? 
Thanks.

**Comment by alecpl** [comment]
Are you talking about the icon (newmail_notifier plugin) or the messages count in the page title?

What do you have in Preferences > Mailbox View > New message > Check all folders for new messages?

**Comment by llucps** [comment]
I'm just referring to counter at the browser tab:
<img width="258" alt="Screen Shot 2021-11-20 at 15 25 06" src="https://user-images.githubusercontent.com/25823659/142730102-2467f553-789b-4358-9156-4093a38f1f32.png">

That counter only works for the messages at the inbox, messages from any subfolder although is counted on the left sidebar, it doesn't trigger the counter at the browser tab.

The check all folders for new messages is active.

Thanks.

**Comment by alecpl** [comment]
This is intentional and this is how it always been. If you select another folder the counter is not displayed at all.

Maybe a better approach would be to display a counter from the current folder.

**Comment by llucps** [comment]
Ok understood.

My use case is being able to be notified that a new message has arrived regardless where that message is, and having some signal, icon at the tab is enough for me, since I always have roundcube open.

Is there a way to have some sort of notification without having to check roundube?

Thanks.

**Comment by alecpl** [comment]
Take a look at the built-in `newmail_notifier` plugin.

**Comment by llucps** [comment]
I activated the plugin you mentioned and I see now the option _Display browser notifications on new message_ unders Prefereces / Mailbox view which does what I asked for on this ticket. The problem is although clicking on test, the favion changes as is supposed to. It really doesn't change with any new incoming email, effectively it doesn't work.

`$config['plugins'] = array(
	'managesieve',
	'carddav',
	'newmail_notifier',
	'identity_select'
);`

![Screen Shot 2021-11-22 at 16 14 31](https://user-images.githubusercontent.com/25823659/142886398-2e4d8139-c6bf-479f-9959-c387acf1d394.png)

Any suggestions?

P.D. I only need the Display browser notification, the Desktop notification is disabled on purpose.

Thanks.

**Comment by alecpl** [comment]
Works for me. What browser?

**Comment by llucps** [comment]
Latest Firefox 94.0.2 on macOS 11.6 (Big Sur)

**Comment by alecpl** [comment]
Same FF version on Linux. Maybe this is caused by the issue described in #8234, that I have already fixed.

**Comment by llucps** [comment]
That was it, disabling "Do not show deleted messages" makes it work. 👍

**Comment by llucps** [comment]
Thanks for you help @alecpl !
