### ISSUE TITLE
Release 1.5.1 missing?

### ISSUE THREAD

**Issue by damnms** [roundcube/roundcubemail#8318]
Not sure but is there something broken with release creation? 
I can see a commit to 1.5.1 (version bump) but no release 1.5.1 - or is this just a generell version bump without any release?

https://github.com/roundcube/roundcubemail/commit/4851ab3dd9f4bb91095ce70a9259dd82eca4dca0

**Comment by alecpl** [comment]
Usually it takes some time between the preparing commit and the release. There's no 1.5.1 tag there yet.
