### ISSUE TITLE
File attachments in Cyrillic

### ISSUE THREAD

**Issue by Mymko** [roundcube/roundcubemail#8319]
Rouncube version 1.5.0

I attach files to the letter, including the name in Cyrillic.
If the letter is saved as a draft or sent to the addressee, then instead of the file name in the Cyrillic alphabet will be written "Part".
This is only true for 2 or more file attachments.
![Скриншот 19-11-2021 120041](https://user-images.githubusercontent.com/67409920/142567769-12815fe7-fe0c-4aad-b0b6-e8d05ee080ba.png)
![Скриншот 19-11-2021 120108](https://user-images.githubusercontent.com/67409920/142567778-bc21a52d-def6-4235-8fec-a9b2904abcc1.png)

**Comment by alecpl** [comment]
Sounds like a duplicate of #8282.

**Comment by Mymko** [comment]
Thanks. Working solution.
