### ISSUE TITLE
drag and drop attachments on Chrome

### ISSUE THREAD

**Issue by mamaririnana08** [roundcube/roundcubemail#8320]
Hello,

I drag and drop between the attachment put in an email and the response and I have on my new attachment a file with '.url' at the end that appears since the new update of Chrome (Version 96.0.4664.45 (Build officiel) (64 bits)). I am doing the test on Mozilla and I don't have this problem.

![Capture d’écran 2021-11-19 175741](https://user-images.githubusercontent.com/57091676/142662139-b830fbb5-fb06-48e8-886e-0c4c2c061f4b.png)

![Capture d’écran 2021-11-19 175913](https://user-images.githubusercontent.com/57091676/142662123-d29457b6-4783-42ca-8dc1-389f8b3fe654.png)

**Comment by twekkel** [comment]
Chrome is becoming more and more strict on security.

To figure out the exact error message from Chrome, can you please press F12 (you will get a developer view in your browser), select the 'Console' tab  ... and than drag & drop the attachment like you did before? Probably you will be presented with an error message, which hopefully somebody here can fix.

**Comment by alecpl** [comment]
Works for me in Chromium v95. I'll give it a try when I have v96 on my system available.

**Comment by mamaririnana08** [comment]
Ok, I looked in the debug and I don't see any error message

**Comment by mamaririnana08** [comment]
I await your return when you have tested on Chrome v96

**Comment by mamaririnana08** [comment]
I come to the news, I still have this same problem have you been able to test?

**Comment by alecpl** [comment]
My distro jumped from v95 to v97 directly. Now I can't drag'n'drop attachments between windows at all. I mean I can drag, but dropping does not work, it's not even detecting that the mouse pointer is over the drop area.

**Comment by alecpl** [comment]
Works for me in Chromium v99.

**Comment by mamaririnana08** [comment]
After retesting, it's the same for me
