### ISSUE TITLE
Password change issue with the directadmin driver 

### ISSUE THREAD

**Issue by pku888** [roundcube/roundcubemail#8322]
Hey,

when the [force_hostname](https://www.directadmin.com/features.php?id=917) parameter is set in directadmin.conf, the password change with the "password" plugin no longer works when using the directadmin driver.
Directadmin debug log shows the error as follows:
`FormCheck::isEmail((null)): blank or null email`

Roundcube client says that the password was successfully changed, but in fact, it was not. 

More information why this happens is explained in the following thread:
https://forum.directadmin.com/threads/can-not-change-email-user-password-from-roundcube.63934/

We will greatly appreciate if you could look into it!  :)

**Comment by alecpl** [comment]
Do you confirm the solution from the forum thread is working? Could you provide a pull request?

**Comment by pku888** [comment]
Sure, [done](https://github.com/roundcube/roundcubemail/pull/8329)  :)

**Comment by alecpl** [comment]
FIxed.
