### ISSUE TITLE
chpass-wrapper.py helper script for password plugin appears to be broken with python 3.9

### ISSUE THREAD

**Issue by sdondley** [roundcube/roundcubemail#8324]
Can someone more knowledgeable with python please take a look at this:

https://stackoverflow.com/a/70051629/1641112

I'd be happy to supply a commit to patch this but I read about 2 chapters of a python book 10 years ago and haven't touched it since. If someone can confirm this a good fix, I'll do a pull request. Thanks.

**Comment by alecpl** [comment]
Fixed.

The `text` argument does not work with Python < 3.7, so we have to use an alias `universal_newlines`. I tested the change on python 2.7 and 3.6.
