### ISSUE TITLE
Version 1.5, automatic download will pop up after logging in to the mailbox

### ISSUE THREAD

**Issue by 8751** [roundcube/roundcubemail#8328]
After the installation is complete, a download will pop up after logging in。

There are two downloads for IE browser. The link is http://domain/program/resources/dummy.pdf  and http://domain/program/resources/blank.tiff

There are one downloads for chrom browser. The link is http://domain/program/resources/blank.tiff

What's your PHP version?  PHP 7.3.9
What's your mail server?  hmailserver 5.6.7
What browser/operating system did you use, any special settings/plugins? chrom and IE Have tried，system：windwos server 2016  2019  2008 All have this problem
What did the logs say?  No error log
Is the behavior reproducible? Can be reproduced
Does the problem persist with all plugins disabled? This problem occurs when the installation is complete。This problem still occurs after disabling all plugins

**Comment by alecpl** [comment]
This way we check browser capability to open certain common file types. Normally, this is done "in background" so user should not notice that. If you notice that then maybe it's some browser extension.

**Comment by 8751** [comment]
I don't understand what you mean.
what should I do?

**Comment by 8751** [comment]
IE and chrome browsers are both the default settings, it always feels a bit bad if it pops up like this

**Comment by 8751** [comment]
Found the reason.
Because I installed Internet Download Manager, this software will take over some file formats of the browser as downloads by default. Just delete the tiff format
Thanks for help

**Comment by 8751** [comment]
> This way we check browser capability to open certain common file types. Normally, this is done "in background" so user should not notice that. If you notice that then maybe it's some browser extension.

Hello, I now want to use roundcube as postfix webmail, but I don't know how to connect to the sqlite database in the password plugin to change the password. Can you send me a template?

**Comment by alecpl** [comment]
This is not a support forum.
