### ISSUE TITLE
managesieve: Cannot add rules when line length exceeds 1024 characters

### ISSUE THREAD

**Issue by technojoe** [roundcube/roundcubemail#8330]
Trying to add a rule fails, and instead, it displays the main mail screen inside the rule window.

    # rule:[Finance]
    if anyof (address :domain :contains "from" ".discover.com", address :domain :is "from" "btrgold.com", address :domain :is "from" "chesapeakegold.com", address :domain :is "from" "chfir.com", address :domain :is "from" "collectivemining.com", address :domain :is "from" "eskaymining.com", address :domain :is "from" "freemangoldcorp.com", address :domain :is "from" "gogoldresources.com", address :domain :is "from" "mail.fidelity.com", address :domain :is "from" "nsuperior.com", address :domain :is "from" "orvana.com", address :domain :is "from" "probemetals.com", address :domain :is "from" "redpineexp.com", address :domain :is "from" "tdggold.com", address :domain :is "from" "notify.wellsfargo.com", address :is "from" "info@mail.tdameritrade.com", address :is "from" "insiders@themoneygps.com", address :is "from" "postmaster@juniorminingnetwork.com", address :is "from" "services@itmtrading.com", address :is "from" "support@s.usa.experian.com", address :domain :is "from" "goldenshare.ca", address :domain :is "from" "adnetcms.com", address :domain :is "from" "burin-gold.com")
    {
    	fileinto "Finance";
    	stop;
    }

**Comment by alecpl** [comment]
Any error in log? Does it fail for other rules? What exactly did you change, the whole rule or added some domains to the list, or? What Roundcube/PHP/OS version?

**Comment by technojoe** [comment]
This error occurs only when the line length of the rule exceeds 1024 characters.  I have other rules that are shorter.  This error does not occur when editing them.  All I did was attempt to add one more domain to the list, which would make the length exceed 1024 characters.

Temporary files are working in all other circumstances.

    [23-Nov-2021 08:28:35 America/Los_Angeles] PHP Warning:  Unknown: Unable to create temporary file, Check permissions in temporary files directory. in Unknown on line 0
    [23-Nov-2021 08:28:35 America/Los_Angeles] PHP Warning:  Unknown: POST data can't be buffered; all data discarded in Unknown on line 0

**Comment by alecpl** [comment]
I've never seen such an error, but it (and the behavior description) suggests the issue is not in the PHP code. More like in how PHP was set up. Maybe the disk is full? Or maybe some kind of security feature.

**Comment by technojoe** [comment]
Apparently, this is caused by a missing "/tmp" in a chroot environment. Adding /tmp to the CHROOT directory resolves the issue.

I am still perplexed by why modifying lines longer than 1024 characters requires temp files in /tmp, but editing shorter lines does not.
