### ISSUE TITLE
favicon resolution is too low

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#8332]
The Firefox home screen allows setting bookmarks and (I believe) uses the favicon for the icon. It draws them much larger than the traditionally tiny favicon, and if the favicon is low resolution, it gets scaled up and looks blocky, especially on HiDPI monitors.  The occurs with roundcube.net and my installation of roundcube too.

**Comment by alecpl** [comment]
What resolution exactly? What version? In 1.5 the favicon.ico file has 64x64 size. For bigger resolutions we're in the #6510 territory.

**Comment by seanm** [comment]
I'm not an expect on these things, I can mostly just tell you that it looks fuzzy. :)

This tool for example reports that hi res icons are missing:

https://realfavicongenerator.net/favicon_checker?protocol=http&site=roundcube.net

**Comment by Bill-ColeUS** [comment]
Did you know that the favicon can have layers of different resolutions? This is fully supported by all browsers and currently a very compatible way to offer a single favicon.ico file that contains 5-6 different resolutions.

In HTML5 you can specify such a favicon with all its resolutions like this:

```
<link rel="icon" href="/favicon.ico" sizes="16x16 24x24 32x32 64x64" type="image/png">
```

Firefox will show the 64x64 layer for big bookmark buttons, while show the 16x16 on the URL bar.

GIMP supports these kinds of favicons with layers.

**Comment by alecpl** [comment]
@Bill-ColeUS Roundcube favicon is already 64x64
@seanm I thought that the higher resolutions are needed for when the webpage is an actual web app. Roundcube is not. Is this Firefox home screen feature available on desktop or only on mobile? Anyway, we might want to work on this without waiting until Roundcube becomes a "real web app".

**Comment by seanm** [comment]
On desktop. I see it both on macOS and Ubuntu. I believe it's from Preferences > Home > Firefox Home Content > Shortcuts. I have it set to 4 rows. Then when you create a new tab, it shows this home screen with these 4 rows of icons.

**Comment by seanm** [comment]
Not sure what happened, but the issue is fixed for me now.  Maybe it was a Firefox update...
