### ISSUE TITLE
Webmail server is a format-less mess OR says "Server Error. Access Denied!"

### ISSUE THREAD

**Issue by theatreeducation** [roundcube/roundcubemail#8333]
I log into my email and see this... What's going on?
If the formatting is in place, it says "Access Denied" and I cannot see any emails. HELP!

<img width="1400" alt="Screen Shot 2021-11-23 at 3 31 05 PM" src="https://user-images.githubusercontent.com/94937821/143141802-55c32993-0118-459e-b902-4a4b94456dae.png">

**Comment by alecpl** [comment]
This is not a support forum.
