### ISSUE TITLE
Establish secure mySQL SSL Connection

### ISSUE THREAD

**Issue by Gill-Bates** [roundcube/roundcubemail#8334]
I am looking for a convinient way to establish a secure my-SQL SSL-Connection.

Currently I hacked a workaround by modifying `/program/lib/Roundcube/rcube_db.php` by adding a line of Code to the function `protected function dsn_options($dsn)`

`$result[PDO::MYSQL_ATTR_SSL_CA] = '/home/files/ca-clientcert.pem';`

![image](https://user-images.githubusercontent.com/25774289/143274430-861b7710-6211-4452-9239-8cf0feac6bbb.png)

I would expect an option inside `config.inc.php` like 

```
// Provide a Path to your local Certifcate if you want to establish a secure SSL-Connection
$config['db_ssl'] = "path/to/my/cert.pem";
```

**Comment by alecpl** [comment]
You can do this via the DSN string.
```
// Note: Various drivers support various additional arguments for connection,
//       for Mysql: key, cipher, cert, capath, ca, verify_server_cert,
//       for Postgres: application_name, sslmode, sslcert, sslkey, sslrootcert, sslcrl, sslcompression, service.
//       e.g. 'mysql://roundcube:@localhost/roundcubemail?verify_server_cert=false'
```
Another example: `mysql://roundcube:@localhost/roundcubemail?ca=path/to/my/cert.pem&verify_server_cert=false`
