### ISSUE TITLE
Idempotent (postgres)SQL scripts for initialization of the database

### ISSUE THREAD

**Issue by epsilon-0** [roundcube/roundcubemail#8336]
I am creating a few ansible roles for an email setup and was using roundcube for the webmail side and am having a bit of issue setting up the PostgresSQL properly.

Currently if I run the script twice (which is very frequent) the second run of the script fails.
One way, would be to make sure that the sql scripts are idempotent, so that running them the second time just does nothing, instead of failing.

I am not sure if this was already raised as an issue, my search did not show anything, but this would be a nice feature to have.

**Comment by alecpl** [comment]
How does it fail exactly? How do you run the script? What version?

**Comment by alecpl** [comment]
No feedback.
