### ISSUE TITLE
v1.5.0 in include_path missed path for "program/include"

### ISSUE THREAD

**Issue by lexxai** [roundcube/roundcubemail#8338]
Detected in FreeBSD port mail/roundcube-php74-1.5.0_1,1

log:
```
2021/11/24 18:37:53 [error] 88165#100301: *1359 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught IntlException: fopen(rcmail_
string_replacer.php): failed to open stream: No such file or directory in /usr/local/www/roundcube/program/lib/Roundcube/bootstrap.php:438
Stack trace:

```

![зображення](https://user-images.githubusercontent.com/3278842/143370274-7043aa24-e960-4d7b-bc59-2d88277e49df.png)

For quick solution recovered by tuning "include_path" with add to php.ini:

php-fpm.d/www.conf
```
php_value[include_path] = "/usr/local/www/roundcube/program/include"
```

**Comment by alecpl** [comment]
We have autoloader in https://github.com/roundcube/roundcubemail/blob/a980375271bdb957da9e2b4f503616727f67a042/program/include/iniset.php#L86 So, this looks to me as some FreeBSD package issue.

**Comment by lexxai** [comment]
Thanks for answer, but problem point on line 438 function rcube_autoload($classname) /Roundcube/bootstrap.php. 
https://github.com/roundcube/roundcubemail/blob/a980375271bdb957da9e2b4f503616727f67a042/program/lib/Roundcube/bootstrap.php#L414-L445

print result of test print content include_path before line 438:
 $aa=get_include_path();
  error_log("$aa\r\n");
  if ($fp = @fopen("$classname.php", 'r', true)) {

```
/usr/local/www/roundcube/vendor/pear/pear_exception:/usr/local/www/roundcube/vendor/pear/console_getopt:/usr/local/www/roundcube
/vendor/pear/pear-core-minimal/src:/usr/local/www/roundcube/vendor/pear/net_ldap2:/usr/local/www/roundcube/vendor/pear/auth_sasl:/usr/local/w
ww/roundcube/vendor/pear/console_commandline:/usr/local/www/roundcube/vendor/pear/crypt_gpg:/usr/local/www/roundcube/vendor/pear/mail_mime:/u
sr/local/www/roundcube/vendor/pear/net_socket:/usr/local/www/roundcube/vendor/pear/net_smtp:/usr/local/www/roundcube/program/lib
```

Where "include_path" must be filled in code for point help to FreeBSD maintainers ?

https://github.com/roundcube/roundcubemail/blob/a980375271bdb957da9e2b4f503616727f67a042/program/lib/Roundcube/bootstrap.php#L89-L97

I tuned Roundcube/bootstrap.php and it help for now instead global env.

```
if (!defined('RCUBE_INCLUDE_DIR')) {
    define('RCUBE_INCLUDE_DIR', RCUBE_INSTALL_PATH . 'program/include/');
}

// make sure the Roundcube include directory is in the include_path
$rcube_path = realpath(RCUBE_INCLUDE_DIR);
$sep        = PATH_SEPARATOR;
$regexp     = "!(^|$sep)" . preg_quote($rcube_path, '!') . "($sep|\$)!";
$path       = ini_get('include_path');

if (!preg_match($regexp, $path)) {
    set_include_path($path . PATH_SEPARATOR . $rcube_path);
}


```

**Comment by alecpl** [comment]
`program/include` does not have to be in the include path because there's the second autoloader I pointed you on.
