### ISSUE TITLE
CSS for plugin now being served

### ISSUE THREAD

**Issue by bibble235** [roundcube/roundcubemail#8341]
I am trying to install a plugin and realise it is not part of the official roundcube but looking to guidance. I have installed kolab but the images/css are returning 404 but the calendar is shown on the sidebar.

I am running this in a docker container using fpm. 
http://localhost/plugins/libkolab/skins/elastic/images/eye.svg - gives 404
http://localhost/skins/elastic/images/contactgroup.svg - 200

The permissions of the directories and files are identical and the plugin is specified in the config.inc.php
```
$config['plugins'] = [
    'debug_logger', 
    'emoticons', 
    'enigma', 
    'filesystem_attachments', 
    'http_authentication', 
    'identicon', 'show_additional_headers', 
    'vcard_attachments', 
    'zipdownload', 
    'calendar', 
    'newmail_notifier', 
    'libkolab', 
    'libcalendaring'];

``` 
thanks all.

**Comment by alecpl** [comment]
This is not a support forum.

**Comment by bibble235** [comment]
Many thanks for your help
