### ISSUE TITLE
Scrollbar color in dark mode too dark

### ISSUE THREAD

**Issue by 532910** [roundcube/roundcubemail#8345]
![image](https://user-images.githubusercontent.com/14617699/143807994-8c565b3e-537f-497f-a2f4-7d053aad2238.png)

v1.5.1

**Comment by alecpl** [comment]
Duplicate of #8309.

**Comment by 532910** [comment]
Sorry for lack of details, but I meant that scrollbar has low visibility, not his narrowness.

**Comment by alecpl** [comment]
I guess we could fix that.

**Comment by alecpl** [comment]
I switched scrollbar thumb color darkness from 30% to 25% (of the main color), should be enough.
