### ISSUE TITLE
Attachments throwing server error

### ISSUE THREAD

**Issue by CroTTpOrT** [roundcube/roundcubemail#8348]
A detailed explanation can be found in my StackOverflow question: https://stackoverflow.com/questions/69922324/roundcube-attachment-upload-internal-server-error

Basically, the problem is that Roundcube doesn't have any validation when closing the file that has been uploaded as an attachment in file "path/to/roundcube/program/lib/Roundcube/rcube_imap_generic.php" on line 430 so PHP is throwing server error.

I simply fixed that by changing code from this:
`protected function closeSocket()
    {
        @fclose($this->fp);
        $this->fp = null;
    }`

Into this:
`protected function closeSocket()
    {
        if($this->fp){
        @fclose($this->fp);
        }
        $this->fp = null;
    }`

**Comment by alecpl** [comment]
It has been already fixed in 1.5. The version you're using is not fully compatible with PHP8.
