### ISSUE TITLE
My 1.5.1 UI is not loading properly.  I can log in, but that's it.

### ISSUE THREAD

**Issue by courtens** [roundcube/roundcubemail#8350]
Not sure if this is a but.  (Running on Windows 10, Apache 2.4, PHP 8.1, with MariaDB 10.6)

I had `$config['default_host'] = '127.0.0.1';` in my config.inc.php

I changed it to `$config['default_host'] = 'localhost';` and now it looks like it is starting to work. But somehow only for skin _larry_ and not for skin _elastic_

With Logout I am getting

> REQUEST CHECK FAILED
> For your protection, access to this resource is secured against CSRF.
> If you see this, you probably didn't log out before leaving the web application.
> 
> Human interaction is now required to continue.
> 
> Please contact your server-administrator.

This is what it looks like if set to _elastic_
![image](https://user-images.githubusercontent.com/27327453/144642112-4256f77c-18ca-4eef-8500-9a53c97b056d.png)

**Comment by alecpl** [comment]
You would better ask on mailing list or forum. Looks like an installation/setup problem not a bug.
