### ISSUE TITLE
Session expiried after update to 1.5.1 (401 Not authorized)

### ISSUE THREAD

**Issue by DimmoK** [roundcube/roundcubemail#8354]
Hello!
Sorry for my bad English.

I have a problem: after update to 1.5.1 version session has been expiried from short time.
After a while, the session is exited. I try to login and I have a error, what my data is incoreect. I again try login and I have succeful.

On version 1.4.12 this problem has not.

**Comment by alecpl** [comment]
Duplicate of #8303 and maybe #8194.

**Comment by DimmoK** [comment]
@alecpl Thank's for your replace!
I updated php from 7.4 to 8.0 and session doesn't expiried!
it is work for me.
