### ISSUE TITLE
Question: Can you manage emails/read messages trough some endpoint?

### ISSUE THREAD

**Issue by IkeVoodoo** [roundcube/roundcubemail#8356]
Hello! I have RoundCube installed on my server, and it works great! The only thing is I wanted to use it for managing some temporary emails, is there some endpoint I can call to make/remove emails or not?

**Comment by alecpl** [comment]
Try to delete a message and check in browser console what request is used, but it will not work from outside of Roundcube. There's no documentation about this that  I could point to.
