### ISSUE TITLE
cannot send email at all - php error: fsockopen()

### ISSUE THREAD

**Issue by the-d-b** [roundcube/roundcubemail#8358]
I have not been able to send email at all since the last update.  I reverted my container to image roundcube/roundcubemail:1.5-rc-apache and immediately I started sending again.  Sounds like it is not just a config issue.  The errors I was seeing is...

errors: <0fecb728> PHP Error: fsockopen(): unable to connect to ssl://obsfuscated.server.com:587 (Unknown error) (POST /?_task=mail&_unlock=loading.....&_framed=1&_action=send),

errors: <0fecb728> PHP Error: Failed to connect socket: fsockopen(): unable to connect to ssl://obsfuscated.server.com:587 (Unknown error) (POST /?_task=mail&_unlock=loading.....&_framed=1&_action=send),

errors: <0fecb728> SMTP Error: Connection failed: Failed to connect socket: fsockopen(): unable to connect to ssl://obsfuscated.server.com:587 (Unknown error) in /var/www/html/program/lib/Roundcube/rcube.php on line 1774 (POST /?_task=mail&_unlock=loading.....&_framed=1&_action=send)

**Comment by alecpl** [comment]
Port 587 is usually used with STARTTLS, so you should use `tls://` prefix.
