### ISSUE TITLE
Default imap_host gives TLS error

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#8359]
As part of 893216cb297268d222ae49099e6654a304b72e3f the defaults for `imap_host` and `smtp_host` where changed to `tls://localhost:xxx` but unless you manually set the imap/smtp connection options to either skip peer verification or at leas not verify the peer name then it is unlikely either of these default configs will work out of the box because the certificate verification will fail.

**Comment by alecpl** [comment]
Right. Fixed.
