### ISSUE TITLE
roundcube update error

### ISSUE THREAD

**Issue by alxbr** [roundcube/roundcubemail#8361]
On debian 9 (stretch):
_apt upgrade_
...
roundcube-core (1.2.3+dfsg.1-4+deb9u9) wird eingerichtet ...
Determining localhost credentials from /etc/mysql/debian.cnf: succeeded.
dbconfig-common: writing config to /etc/dbconfig-common/roundcube.conf
dbconfig-common: flushing administrative password
PHP Warning:  Undefined variable $rcmail_config in /usr/share/roundcube/program/lib/Roundcube/rcube_config.php on line 323
PHP Warning:  Undefined variable $rcmail_config in /usr/share/roundcube/program/lib/Roundcube/rcube_config.php on line 323
PHP Warning:  Undefined array key 2 in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 118
PHP Warning:  Undefined array key "UTF-8" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 232
PHP Warning:  Undefined array key "UTF7-IMAP" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 233
PHP Warning:  Undefined array key "UTF-8" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 232
PHP Warning:  Undefined array key "UTF7-IMAP" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 233
PHP Warning:  Undefined array key "UTF-8" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 232
PHP Warning:  Undefined array key "UTF7-IMAP" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 233
PHP Warning:  Undefined array key "UTF-8" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 232
PHP Warning:  Undefined array key "UTF7-IMAP" in /usr/share/roundcube/program/lib/Roundcube/rcube_charset.php on line 233
PHP Warning:  Undefined variable $proto in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 1201
PHP Warning:  Undefined variable $proto in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 1201
PHP Warning:  Undefined array key "config_get" in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php:438
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_config.php(404): rcube_plugin_api->exec_hook()
#1 /usr/share/roundcube/program/include/rcmail.php(99): rcube_config->get()
#2 /usr/share/roundcube/program/include/rcmail.php(79): rcmail->startup()
#3 /usr/share/roundcube/program/include/clisetup.php(31): rcmail::get_instance()
#4 /usr/share/roundcube/bin/update.sh(31): require_once('...')
#5 {main}
  thrown in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438
PHP Warning:  Undefined array key "REMOTE_ADDR" in /usr/share/roundcube/program/lib/Roundcube/rcube.php on line 999
PHP Warning:  Undefined array key "config_get" in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php:438
Stack trace:
#0 /usr/share/roundcube/program/lib/Roundcube/rcube_config.php(404): rcube_plugin_api->exec_hook()
#1 /usr/share/roundcube/program/lib/Roundcube/rcube.php(1017): rcube_config->get()
#2 /usr/share/roundcube/program/include/rcmail.php(871): rcube->shutdown()
#3 [internal function]: rcmail->shutdown()
#4 {main}
  thrown in /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438
dpkg: Fehler beim Bearbeiten des Paketes roundcube-core (--configure):
 Unterprozess installiertes post-installation-Skript gab den Fehlerwert 255 zurück
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von roundcube-plugins:
 roundcube-plugins hängt ab von roundcube-core (= 1.2.3+dfsg.1-4+deb9u9); aber:
  Paket roundcube-core ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten des Paketes roundcube-plugins (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
dpkg: Abhängigkeitsprobleme verhindern Konfiguration von roundcube:
 roundcube hängt ab von roundcube-core (= 1.2.3+dfsg.1-4+deb9u9); aber:
  Paket roundcube-core ist noch nicht konfiguriert.

dpkg: Fehler beim Bearbeiten des Paketes roundcube (--configure):
 Abhängigkeitsprobleme - verbleibt unkonfiguriert
Fehler traten auf beim Bearbeiten von:
 roundcube-core
 roundcube-plugins
 roundcube
E: Sub-process /usr/bin/dpkg returned an error code (1)
...
how to fix this?

**Comment by alecpl** [comment]
You're trying to run an old Roundcube version on a newer PHP version. We do not support Debian packages, nor such old versions here.
