### ISSUE TITLE
segfol from email

### ISSUE THREAD

**Issue by vil451** [roundcube/roundcubemail#8362]
roundcube 1.5.1
this message bring segfault (11) apache web server
Return-Path: <zazuqujycusi@xn--vysx78fh5q.tw>
Delivered-To: dmitry.vlasenko@elephant-games.com
Received: from localhost (localhost [127.0.0.1])
       by mail1.elephant-games.com (Postfix) with ESMTP id 2051E8682ED;
       Tue, 14 Dec 2021 02:11:48 +0300 (MSK)
X-Virus-Scanned: amavisd-new at elephant-games.com
X-Spam-Flag: NO
X-Spam-Score: 3.815
X-Spam-Level: ***
X-Spam-Status: No, score=3.815 tagged_above=2 required=6.2
       tests=[BAYES_05=-0.5, RCVD_IN_SBL_CSS=3.335, RDNS_DYNAMIC=0.982,
       SPF_HELO_PASS=-0.001, SPF_PASS=-0.001] autolearn=no autolearn_force=no
Received: from mail1.elephant-games.com ([127.0.0.1])
       by localhost (mail1.elephant-games.com [127.0.0.1]) (amavisd-new, port 10024)
       with ESMTP id r6v7CC8LlkQP; Tue, 14 Dec 2021 02:11:46 +0300 (MSK)
Received: from xn--vysx78fh5q.tw (61-216-14-188.hinet-ip.hinet.net [61.216.14.188])
       by mail1.elephant-games.com (Postfix) with ESMTP id D77AB8682E8
       for <pr@elephant-games.com>; Tue, 14 Dec 2021 02:11:44 +0300 (MSK)
Date: Tue, 14 Dec 2021 7:11:44 +0800
From: =?utf-8?B?0JDRhNCw0L3QsNGB0LjQuSDQldGA0YjQvtCy?= <zazuqujycusi@xn--vysx78fh5q.tw>
X-Priority: 1 (High)
Message-ID: <384007652.20211214071144@xn--vysx78fh5q.tw>
To: pr@elephant-games.com
Subject: =?utf-8?B?0J3QvtCy0YvQuSDQv9GA0LDQudGBICDQvtGC0LTQtdC70YMg0LfQsA==?=
 =?utf-8?B?0LrRg9C/0L7QuuKApA==?=
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
0JTQvtCx0YDRi9C5INC00LXQvdGMISDQlNC40YDQtdC60YLQvtGA0YMsINCT0LvQsNCy0L3QvtC8
0YMt0JjQvdC20LXQvdC10YDRgywg0JzQtdGF0LDQvdC40LrRgyDQsiDQntCc0KLQoQoK0J/RgGVj
YyDQmtCUMjEyNtCVLjI1MDAwMNGALgrQn9GAZWNjINCz0LjQtNGAYdCy0LvQuNGHZWPQutC40Lkg
NjDRgi4xNzAwMDDRgC4K0JPQuNC70Yxv0YLQuNC9YSDQndCUMzMxOC4yNzAwMDDRgC4K0KJv0Lph
0YDQvW8t0LLQuNC90YJv0YBl0LfQvdGL0LkgMdC8NjPQsdGEMTAxINCg0JzQpiAzMDAwLjEyMDAw
MDDRgC4K0J9v0LJv0YBv0YLQvdGL0LkgY9GCb9C7IDc0MDAtMDIyNy4xNTAwMDDRgC4K0J9wZWNj
0L1v0LbQvdC40YbRiyDQndCSNTIyMi4xNzAwMDDRgC4K0KBh0LTQuGHQu9GM0L1vIGPQsmVw0LvQ
uNC70YzQvdGL0LkgMtC7NTPRgy4yNTAwMDDRgC4K0KJv0Lph0YDQvW8t0LLQuNC90YJv0YBl0LfQ
vdGL0LkgMTbQmjQw0KQxMDEg0L1v0LLRi9C5LjM1MDAwMDDRgC4K0Jpv0LzQv3BlY2NvcCBjIHBl
Y9C40LJlcG/QvCDQs2FwYdC20L3Ri9C5LjQwMDAw0YAuCtCib9C6YdGA0L1vLdCy0LjQvdGCb9GA
ZdC30L3Ri9C5IDHQnDY1INCg0JzQpiAzMDAw0LzQvC4zNTAwMDAw0YAuCm9j0L1hY9GC0LphLNC4
0L1j0YLRgNGD0Lxl0L3RgizQv2/Qsm/RgG/RgtC90YtlIGPRgm/Qu9GLLgrQntGC0YDQtdC30L3Q
vtC5INGB0YLQsNC90L7Qui7QptC10L3QsCAzMDAwMNGACmPRgtGAb9CzYdC70YzQvdGL0LkgN9CR
MzUuMTIwMDAw0YAuCtCgYdC00Lhh0LvRjNC9byBj0LJlcNC70LjQu9GM0L3Ri9C5IDI1NS4yNTAw
MDDRgC4K0KDQvtC70YzQs9Cw0L3Qs9C4LtCm0LXQvdCwIDEwMDAwMNGACtCTb9GA0LjQt2/QvdGC
YdC70YzQvW8g0YTRgGXQt2XRgNC90YvQuSA20YA4Mi4yMDAwMDAuCtCcZdGFYdC90LjRh2Vj0Lph
0Y8g0L/QuNC7YSA4NzLQvC42MDAwMNGALgrQk9C40LvRjG/RgtC40L1hINCd0JQzMzE20JMuMjUw
MDAw0YAuCtCS0YtjZdGH0L3Ri2Ug0L1v0LbQvdC40YbRiyDQndCaNDUxNiDQvW/QstGLZS4yNTAw
MDDRgC4K0Jpvb9GA0LTQuNC9YdGC0L1vINGAYWPRgm/Rh9C9b9C5IGPRgmHQvW/QuiAyZTQ0MGEu
NDUwMDAw0YAuCtCib9C6YdGA0L1vLdCy0LjQvdGCb9GAZdC30L3Ri9C5INCa0YPRgdC+0L0tMy4y
NTAwMDDRgC4K0JNh0LdvcGXQt9C6YSAgNDAwMDDRgC4K0JJh0LvRjNGG0YsgMTZ4MzE1MNC80Lwu
MTIwMDAwMNGALgrQom/QumHRgNC9by3QstC40L3Rgm/RgGXQt9C90YvQuSAx0Jw2NSDQoNCc0KYg
NTAwMNC80LwuNDUwMDAwMNGALgrQom/QumHRgNC9by3QstC40L3Rgm/RgGXQt9C90YvQuSAx0Jw2
MyDQoNCc0KYgMjgwMNC80LwuODUwMDAw0YAuCtCfcGVjY9C9b9C20L3QuNGG0YsgYy0yMjlhLjYw
MDAwLgpj0LJhcG/Rh9C90YvQuSDQv2/Qu9GDYdCy0YJv0Lxh0YIg0LLQtNGDLTUwNmMg0Lgg0L/Q
tNCzby01MTAuNzAwMDDRgC4K0JJl0YDRgtC40Lph0LvRjNC9byDRhNGAZdC3ZdGA0L3Ri9C5IEYy
LTI1MC4xODAwMDDRgC4K0J1h0LbQtGHQuiDQtNC4YdC8ZdGC0YAgNDAw0LzQvC41MDAwMNGALgrQ
lG/Qu9CxZdC20L3Ri9C5IDfQvDQzMC40NTAwMDDRgC4KCgrQktGB0LUg0YHRgtCw0L3QutC4INC/
0L7QtNC60LvRjtGH0LXQvdGLLiDQlNC80LjRgtGA0LjQuSA3OUnQl0k5N0k1NE8=

**Comment by alecpl** [comment]
Works fine for me. Anyway, in case of a segfault there's not much we can do as this would be a PHP bug.

**Comment by omatosan** [comment]
The problem is in the Spoofchecker::isSuspicious. You need to compile ext-intl with the latest available ICU library.
