### ISSUE TITLE
Problem with multi smtp server

### ISSUE THREAD

**Issue by KrystianPlichta** [roundcube/roundcubemail#8364]
I am trying to configure 2 separate smtp servers first using tls and second using ssl, for imap it works. I can't send with the second one, for the second one it works.

$config['default_host'] = array(
		'example.com' => 'server',
		'ssl://imap.example2.com:993' => 'server2');
$config['smtp_server'] = array(
	'example.com' => 'tls://example.com',
	'ssl://example2.com:993' => 'ssl://smtp.example2.com:465');

**Comment by johndoh** [comment]
```
// To specify different SMTP servers for different IMAP hosts provide an array
// of IMAP host (no prefix or port) and SMTP server e.g. ['imap.example.com' => 'smtp.example.net']
```
Note: no prefix or port.

**Comment by alecpl** [comment]
So, prefix and port is supported on the right side of `=>`.
