### ISSUE TITLE
1.5.1 PHP Fatal Error on CentOS 7

### ISSUE THREAD

**Issue by basmevissen** [roundcube/roundcubemail#8365]
An installation of 1.5.1 fails on CentOS 7 due to its old PHP version (5.4). Luckily, it only seem to fail on the emoticons plugin:

PHP Fatal error:  Can't use function return value in write context in /usr/share/roundcubemail/plugins/emoticons/emoticons.php on line 114

Not being a PHP programmer, I came up with this work-around that works on the CentOS 7 host and probably on all PHP versions:

```
--- plugins/emoticons/emoticons.php.dist	2021-11-22 22:12:11.000000000 +0100
+++ plugins/emoticons/emoticons.php	2021-12-16 00:46:17.719453814 +0100
@@ -111,10 +111,12 @@
     function preferences_save($args)
     {
         if ($args['section'] == 'mailview') {
-            $args['prefs']['emoticons_display'] = !empty(rcube_utils::get_input_value('_emoticons_display', rcube_utils::INPUT_POST));
+            $input_value = rcube_utils::get_input_value('_emoticons_display', rcube_utils::INPUT_POST);
+            $args['prefs']['emoticons_display'] = !empty($input_value);
         }
         else if ($args['section'] == 'compose') {
-            $args['prefs']['emoticons_compose'] = !empty(rcube_utils::get_input_value('_emoticons_compose', rcube_utils::INPUT_POST));
+            $input_value = rcube_utils::get_input_value('_emoticons_compose', rcube_utils::INPUT_POST);
+            $args['prefs']['emoticons_compose'] = !empty($input_value);
         }
```

Can a fix like this be considered so Roundcube 1.5.1 and newer can run on a default CentOS 7 installation?
Many thanks in advance!

Bas.

**Comment by basmevissen** [comment]
Note that there was an (old) patch [https://github.com/roundcube/roundcubemail/commit/800235f6826ef6109c23974463d4c4d497987b4f](url) in the 1.4.x branch that was not in master that just left out the empty(). That's why it was not a problem with 1.4.x.
The file plugins/newmail_notifier/newmail_notifier.php in 1.5.1 still seems to carry that patch however.

**Comment by johndoh** [comment]
The min PHP version for Roundcube 1.5 is 5.5

**Comment by alecpl** [comment]
Fixed anyway.

**Comment by basmevissen** [comment]
Thanks a lot! With CentOS 7 supported till mid 2024 and CentOS 8 (old style) out of support in a matter of weeks, a lot of people will be happy to have (unofficial) support for PHP 5.4.

Actually, as both PHP 5.4 and 5.5 are way out of support, I'm wondering why the 1.5.x releases are chosen to require 5.5 in the first place.

**Comment by alecpl** [comment]
I don't remember precisely why 5.5, but we wanted to stick to PHP5. Maybe some of the dependencies require 5.5. It's harder and harder to keep up with new PHP releases, and still support older ones. In 1.6 we'll require PHP >= 7.3. And the next will probably require PHP8.

**Comment by basmevissen** [comment]
Well, you did that yourself for the 1.5.x branch: https://github.com/roundcube/roundcubemail/commit/1cc9d4f566c911662fba51b93aafc8b58d60a1f5
Unfortunately, the commit doesn't contain more information on the reason.

I'll try to keep up with 1.5.x as long as I need to maintain that CentOS 7 box and revert to 1.4.x or install a custom PHP version if there are non-trivial fixed needed. Thank again for picking up a PHP 5.4 compat patch,
