### ISSUE TITLE
Where to find Logo/Branding?

### ISSUE THREAD

**Issue by keunes** [roundcube/roundcubemail#8366]
Hello everyone,

I just wanted to update the logo/icon of the Roundcube recipe for Franz/Ferdinand (https://github.com/jonathanjuursema/franz-roundcube). I had a quick look on the Roundcube website, but I couldn't find it.

Any idea where I can find the (official) SVG/PNG files of Roundcube?

Many thanks!

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/master/skins/elastic/images/logo.svg
