### ISSUE TITLE
Elastic - mobile - add attachment to mail - screen not scrolling

### ISSUE THREAD

**Issue by dropfree** [roundcube/roundcubemail#8367]
Hi,
using Elastic on mobile 
creating a new message and add attachments to the mail:
When I add several files as attachment, so that the list is longer than the screen, the screen is not scrolling and I cannot confirm the dialog, as the button is not visible any more. I only can cancel the dialog.

Roundcubemail 1.5.1
Android 11
2.340 x 1.080 (FHD+) / portrait
Mobile Firefox 95.2.0

**Comment by alecpl** [comment]
Could you provide a screenshot?

**Comment by dropfree** [comment]
Please see attached screen.
It is the attach image dialog while you create a new message.
As the list of files is long the close button for the dialog is not visible any more. Scrolling is not working. So I can only use android/browser back button
![Screenshot_20211221-153930_Firefox](https://user-images.githubusercontent.com/65235555/146960780-98116077-1cce-4d8c-a259-60a6f359dbae.jpg)
.

**Comment by alecpl** [comment]
So this is the "Insert image" dialog not the Options and Attachments section. I can't reproduce the issue using "responsive mode" in a desktop version of Firefox 95.

**Comment by dropfree** [comment]
I have the same behaviour on Chrome 96.0.4664.104 on the same Android mobile device.
No button, no scrolling.

**Comment by alecpl** [comment]
Confirmed with Chromium.

**Comment by alecpl** [comment]
Fixed.
