### ISSUE TITLE
1.5.1 Sieve variables non substituting anymore

### ISSUE THREAD

**Issue by saspol** [roundcube/roundcubemail#8374]
```
require ["editheader","fileinto","imap4flags"];
if header :contains "Received" "with ESMTP id"
{
	deleteheader "Subject";
	addheader :last "Subject" "⚠️ ${subject}";
}
```
If this matched $subject variable not becoming subject line but still remain as variable.
Before i upgrade from 1.4.x everything working as expected - email subject prepending with ⚠️

**Comment by alecpl** [comment]
Something's missing in the script. Where do you create the variable?

**Comment by saspol** [comment]
Changed like this and its working again. Dont really understand how and why this happens.

```
require ["editheader","fileinto","imap4flags", "variables"];
if header :contains "Received" "with ESMTP id"
{
  if header :matches "Subject" "*" {
    set "subject" "${1}";
	deleteheader "Subject";
	addheader :last "Subject" "⚠️ ${subject}";
  }
}
```

> Something's missing in the script. Where do you create the variable?
