### ISSUE TITLE
1.5.2 login issue

### ISSUE THREAD

**Issue by matzex** [roundcube/roundcubemail#8377]
Hi,
I upgraded today to 1.5.2 from 1.5.1 with the /bin/installto.sh script on Ubuntu 20.04 with Apache 2.4, PHP 7.4.27 and Dovecot 2.3.7.2.
For all users I get an error on the login page: 

> Connection to storage server failed.

In the logfile of roundcube the following error is logged for every failed login:
> [31-Dec-2021 01:02:38 +0100]: <5bjqmoso> IMAP Error: Login failed for USER against SERVER from SERVER-IP. Could not connect to SERVER-DOMAIN:143: Connection refused in /usr/share/roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (POST /?_task=login&_action=login)

Before the upgrade to 1.5.2 I had no problems and I did not change anything on the server beside the roundcube update. Do you have any idea what the problem can be?

Thanks
Matthias

**Comment by johndoh** [comment]
This is a bug tracker not a support forum. A `Connection refused` error on IMAP server connection does not on its own describe a bug, please provide more information.

I think you are saying that during the upgrade process your config information was unexpectedly changed but you have not given details of the before and after states of your `config.inc.php` file.
