### ISSUE TITLE
format=flowed message does not wrap

### ISSUE THREAD

**Issue by Player701** [roundcube/roundcubemail#8378]
I've got a message with ```Content-Type: text/plain; charset=us-ascii; format=flowed```, and most of its text is rendered as a one long line with a horizontal scrollbar at the bottom. According to what I know about ```format=flowed```, this should not be the case, and the text should wrap instead. This issue is present in Roundcube 1.5.2 with all three built-in skins (classic, elastic, larry), so it's not a template issue.

The message in question came from a public maillist, so I'm attaching it here (with some header data redacted): [Re Google and UK.COM domains.eml.zip](https://github.com/roundcube/roundcubemail/files/7796232/Re.Google.and.UK.COM.domains.eml.zip)

**Comment by alecpl** [comment]
Confirmed. It works correct in git-master.

**Comment by Player701** [comment]
Thank you for investigating this. Does it mean a fix will be included in the next 1.5.x point release?

**Comment by alecpl** [comment]
It should be fixed in git-master, I do not plan a backport to 1.5.

**Comment by Player701** [comment]
OK, guess I should wait for a 1.6 release then, don't want to use an unstable version. Thank you very much again.
