### ISSUE TITLE
Cookie "roundcube_sessauth" will soon be rejected

### ISSUE THREAD

**Issue by erikvanoosten** [roundcube/roundcubemail#8380]
Firefox 95 gives a warning in the console:

```
Cookie "roundcube_sessauth" will be soon rejected because it has the SameSite attribute set to None or an invalid value, without the secure attribute. 
```

Please add the `Secure`attribute.

See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#fixing_common_warnings

**Comment by erikvanoosten** [comment]
Note: I am running Roundcube behind a proxy which does the TLS termination.

**Comment by alecpl** [comment]
It think you just should enable this option:
```
// tell PHP that it should work as under secure connection
// even if it doesn't recognize it as secure ($_SERVER['HTTPS'] is not set)
// e.g. when you're running Roundcube behind a https proxy
// this option is mutually exclusive to 'force_https' and only either one of them should be set to true.
$config['use_https'] = false;
```

**Comment by erikvanoosten** [comment]
Thanks @alecpl ! I just found that setting as well and I wanted to test it before reporting back.
Indeed, that solves it!
