### ISSUE TITLE
PHP Warning with Roundcube 1.5.2 and 8.0.14

### ISSUE THREAD

**Issue by STR07** [roundcube/roundcubemail#8382]
I get an error when using  Roundcube 1.5.2 and the plugin: twofactor_gauthenticator_login along with PHP 8.0.14.

The error only exists since the PHP update and only occurs when pressing the Button "twofactor authenticator"..

Error:
[02-Jan-2022 19:36:02 Europe/Berlin] PHP Warning: Undefined array key "value" in /var/www/html/webmail/program/lib/Roundcube/html.php on line 578

Thank you very much in advance.

![Roundcube-Error](https://user-images.githubusercontent.com/25361543/147888153-fb0ecfc8-75cc-4527-9504-7ec38e9cbff9.png)

**Comment by alecpl** [comment]
Fixed.
