### ISSUE TITLE
Custom Links

### ISSUE THREAD

**Issue by MatthiasLohr** [roundcube/roundcubemail#8383]
Hi,

is there any option to add custom links additional to the E-Mail / Contacts / Settings menu bar in a less complicated way than writing a whole new plugin? I just want to add a link to an external settings page, where users can access the email provider's settings (e.g., for changing the password, adding mail aliases, etc.).

I searched for it, but I didn't found anything, neither in the core settings nor the plugin library.

If there is no such option (yet), please treat this issue as a feature request. Thanks!

Best regards
Matthias

**Comment by alecpl** [comment]
Plugin API is the way to go.

**Comment by MatthiasLohr** [comment]
Did so: https://plugins.roundcube.net/#/packages/matthiaslohr/roundcube-custom-links
