### ISSUE TITLE
cannot get any emails

### ISSUE THREAD

**Issue by sparky1234878** [roundcube/roundcubemail#8385]
i try to send emails to my roundcubemail account and i dont get any emails to my inbox i tried sending emails from different accounts to my roundcube mail and it just doesnt work i cant receive anything please help 

my mail: HectorFrost@eyeyaw.club

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
