### ISSUE TITLE
Disable the contact management features

### ISSUE THREAD

**Issue by azmeuk** [roundcube/roundcubemail#8390]
Hi. I have a CardDAV server and the roundcube plugin [rcmcarddav](https://github.com/mstilkerich/rcmcarddav) to load contacts from it.

I think having several tools to do one thing is confusing, especially for users that are not very familiar with computers. Thus I would like my users to have only one place to do contact management, and I would like to prioritize the CardDAV interface over the roundcube interface.

Thus, I would love to disable the *Contacts* view in roundcube, and prevent users to edit contacts there.

I suggest adding a configuration option that does just that (but do not disable contacts auto-completion). I am volunteer to provide a patch for this if it is OK to you.

What do you think?

**Comment by thomascube** [comment]
Maybe the config option [disabled_actions](/roundcube/roundcubemail/blob/master/config/defaults.inc.php#L466) already does the job for you. Add this to your config.inc.php:
```
$config['disabled_actions'] = ['addressbook'];
```

**Comment by azmeuk** [comment]
I wonder how I missed that. Thank you !
