### ISSUE TITLE
Elastic skin, adding new column in messages

### ISSUE THREAD

**Issue by arstanme** [roundcube/roundcubemail#8393]
Hi,
I'm trying to add a TO field as a column to the messages list.

I have set the config to include that TO field. I can see that the js API(or whatever it is called) returning in the array but the theme does not render that.

this.set_message_coltypes([\"threads\",\"to\",\"subject\",\"status\",\"fromto\",\"date\",\"size\",\"flag\",\"attachment\"],null,\"from\");

How can I add that TO column in the message list?

**Comment by alecpl** [comment]
It's not that easy, as in Elastic the list record has a special structure, you can't just add another "column". Look for this.env.widescreen_list_template in app.js. You'll likely also need to change some css styles.

**Comment by arstanme** [comment]
Thank you, it just did what I wanted! @alecpl
