### ISSUE TITLE
Attachment type validation

### ISSUE THREAD

**Issue by chethutth96** [roundcube/roundcubemail#8394]
Hi sir, my self chethan am looking for the plugin to validate attachment type when we are composing the mail we have a option to add some attachment in that i need to some of the valid attachment only can upload or send,

suppose i don't want to send .doc file in my roundcube for all users when they user tried to attach .doc file then he has to get a massage or any alert you can't send .doc file like that   i want is it possible to make that..?

kindly give the solution for this, i am waiting for your replay sir,

Thank you...

**Comment by alecpl** [comment]
You can write a plugin where you could use `attachment_upload` hook.

**Comment by chethutth96** [comment]
sir exactly i don't know how the flow is going. so that if there any plugins are there please tell me sir
