### ISSUE TITLE
how to filter file extension on roundcube?

### ISSUE THREAD

**Issue by fithon32** [roundcube/roundcubemail#8397]
my teacher wants me to try sending messages and attachments to a different account that I have previously created. I named the two accounts with the names mail1 and mail2

case study :
-mail1 sends messages and attachments to mail2
-attachments that can only be sent are only pdfs

(I'm speculating my teacher wants the attachment settings to be changed to only being able to send pdfs)

But I'm confused where to change it from, whether from the php roundcube file, php.ini, or postfix settings

Please help

**Comment by alecpl** [comment]
This is not the correct place for this kind of support. Ask on mailing list or forum.
