### ISSUE TITLE
Indexing/searching content body encrypted pgp email

### ISSUE THREAD

**Issue by adityaasoleh** [roundcube/roundcubemail#8400]
Hi,

How to search/indexing content email which encrypted by pgp ? Thanks

**Comment by alecpl** [comment]
You don't.

**Comment by ethhert** [comment]
is there a way to implement like protonmail/tutanota are doing it?
they somehow decrypt/index each body locally and then make it searchable

**Comment by ethhert** [comment]
> You don't.

is there a way to implement it in same way protonmail/tutanota are doing it?
they somehow decrypt/index each email body locally and then make it searchable
