### ISSUE TITLE
1.5.x  Elastic skin resets layout view for email previews

### ISSUE THREAD

**Issue by MASHtm** [roundcube/roundcubemail#8403]
This was already addressed for 1.4.x in  #6613. I left a comment there for 1.5.x, but it seems it was not noticed.

Coming from Skin Larry with "Desktop" layout...

If I switch to elastic skin (eg. with elastic4mobile plugin) and go back to larry afterwards the layout is permanently switched from "Desktop" to "Widescreen".

**Comment by alecpl** [comment]
The layout is re-set whenever you visit Mail interface, and it is not a per-skin setting. In fact, we do not have per-skin settings. So, I don't see an easy fix, and as it is imho not a big issue I propose a wontfix.

**Comment by buttercookie42** [comment]
What was wrong with the fix in 1.4.x?
If a skin doesn't support a certain setting, it should use some sort of sensible fallback, but it shouldn't modify the permanent settings unless the user actually goes into the settings menu and confirms the settings, shouldn't it?

**Comment by MASHtm** [comment]
it is a big issue in combination with elastic4mobile. And it worked and still works in 1.4 after it was fixed somehow. Closing it with "wontfix" is not very satisfying.

**Comment by kochs-online** [comment]
> it is a big issue in combination with elastic4mobile. And it worked and still works in 1.4 after it was fixed somehow. Closing it with "wontfix" is not very satisfying.

I agree. Switching between layouts and losing those settings every time is really annoying.

Why not ignore (but keep) settings that are unused by a certain skin?
