### ISSUE TITLE
Indexing/searching content body encrypted pgp email

### ISSUE THREAD

**Issue by ethhert** [roundcube/roundcubemail#8406]
is there a way to search body of PGP encrypted email ?
Tutanota and Protonmail somehow allow manual indexing that decrypt mail by mail and allow to search the body.
is there a way to do it in roundcube?

**Comment by alecpl** [comment]
It would be possible to implement, but I'm not a fan of this idea. You would have to store decrypted data on the server. You can say that we already store private keys, but we do not store the password for them. Anyway, it would require to open every email, or index only these messages that were opened at some point. I don't think that would be easy to do right.
