### ISSUE TITLE
Forwarding a PGP-signed HTML email breaks image references

### ISSUE THREAD

**Issue by rimas-kudelis** [roundcube/roundcubemail#8407]
When I configured **Roundcube 1.5.0** to always compose emails in HTML and attempted to forward a PGP-signed HTML email, an image which was embedded in the HTML was not displayed in the editor. Instead, only a "broken image" placeholder image was shown.

This is in addition to #8405, where that same email was not detected as HTML during forward/reply in the first place.

The email in question was sent using Thunderbird 91.5.0 and is structured like this:
- `multipart/signed`
  - `multipart/mixed`
    - `multipart/alternative`
      - `text/plain`
      - `multipart/related`
        - `text/html`
        - `image/png`
   - `application/pgp-signature`

**Comment by alecpl** [comment]
I'm unable to reproduce, but my message has a slightly different structure. Could you provide a sample message?

**Comment by rimas-kudelis** [comment]
@alecpl could I send it to you over email as an attachment?

**Comment by alecpl** [comment]
Works for me with fixes from #8405.
