### ISSUE TITLE
Problem with base64 attachments

### ISSUE THREAD

**Issue by mary-pe** [roundcube/roundcubemail#8408]
Hi,  
since updating Roundcube from version 1.3.9 to 1.5.0 I have problems with emails containings base 64 attachments.
I attached an example.
The  message contains an attachment (message.eml) that contains a base64-encoded attachment. In this case RC does not decode base64 attachment.
[base64_attachment_problem.eml.txt](https://github.com/roundcube/roundcubemail/files/7895952/base64_attachment_problem.eml.txt)

**Comment by alecpl** [comment]
There is a bug in our optimization for small message/rfc822 parts. There should be no problem if the attachment size is > 32768 bytes.

**Comment by alecpl** [comment]
Fixed.

**Comment by mary-pe** [comment]
Thanks!
