### ISSUE TITLE
The message_highlight plugin obscures message selection with the elastic skin.

### ISSUE THREAD

**Issue by davideder** [roundcube/roundcubemail#8410]
There is no visual indication of which e-mails are selected.

I believe it is because the message_highlight plugin adds a style to the <tr> tag, overriding the classes.  The message_highlight plugin probably should be adding a class to the <tr>, but that looks like a significant rewrite.

This is, however, easily remedied by adding the following to the styles.css in the elastic skin:

.listing .selected td.subject,.listing .selected td.threads,.listing .selected td.flags { background-color:#ebf9ff !important; }

I'm not sure this is the best fix, but it works.

I'm using roundcubemail-1.4.13 packaged by Fedora 34.

Thanks.

**Comment by alecpl** [comment]
I don't like it. This needs to be fixed in the plugin.
