### ISSUE TITLE
Allow Remote Resources requires Referrer

### ISSUE THREAD

**Issue by bs42** [roundcube/roundcubemail#8411]
The "To protect your privacy remote resources have been blocked." banner's Allow buttons seem to require the browser send a detailed Referrer header.

To replicate this issue, install roundcubemail into a sub directory instead of / on a site.  Either add "Referrer-Policy: origin" into the webserver/.htaccess or go into browser settings and disable sending Referrer.

Select an email with unsafe images and click the "Allow" button and the requests will be sent to / with the query string appended instead of to /subdirectory/

**Comment by alecpl** [comment]
Sounds like a duplicate of #8170.
