### ISSUE TITLE
Updating database schema (2020020101) Failed

### ISSUE THREAD

**Issue by ipflowss** [roundcube/roundcubemail#8412]
Hi there,
I just used the ./bin/installto.sh script and had the following error.  The upgrade was from RC 1.4.11 to 1.5.2

Is there anything I can do to save this situation?

<code>
NOTICE: New .htaccess file saved as .htaccess.new.

Running update script at target...
Executing database schema update.
Updating database schema (2020020100)... [OK]
Updating database schema (2020020101)... [FAILED]
ERROR: Error in DDL upgrade 2020020101: [1071] Specified key was too long; max key length is 767 bytes
All done.
</code>

**Comment by alecpl** [comment]
Have you seen this:
```
WARNING: If you use MySQL < 5.7.7 or MariaDB < 10.2.2 make sure to configure it with:
            innodb_large_prefix=1
            innodb_file_per_table=1
            innodb_file_format=Barracuda
```
in the UPGRADING file?

Duplicate.

**Comment by ipflowss** [comment]
Noob here.  Where is this configured?
