### ISSUE TITLE
Double quoted-printable encoding of pgp-signed messages with no attachments

### ISSUE THREAD

**Issue by bukauskas** [roundcube/roundcubemail#8413]
Roundcube Webmail 1.5.2 here.

It looks like that messages having non-ASCII characters which end up being quoted-printable encoded  (when Use MIME encoding for 8-bit characters is enabled)  are incorrectly encoded twice if a message is pgp-signed and has no other attachments other than the signature. 

[Testing_1.txt](https://github.com/roundcube/roundcubemail/files/7920076/Testing_1.txt)
[Testing_2.txt](https://github.com/roundcube/roundcubemail/files/7920077/Testing_2.txt)

The body of both examples is:

 _This is tęsting, tėsting, and testįng._

The first example (which has an attachment) is correctly encoded as:

`This is t=C4=99sting, t=C4=97sting, and test=C4=AFng.`

The second example (which has no attachment other than a pgp signature) incorrectly encoded as:

`This is t=3DC4=3D99sting, t=3DC4=3D97sting, and test=3DC4=3DAFng.`

The result of the second: distorted text and pgp  failing to validate.

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Fixed.
