### ISSUE TITLE
Upgrading to 1.5.2 needs variables configured

### ISSUE THREAD

**Issue by ipflowss** [roundcube/roundcubemail#8414]
Hi there,

I am a noob to the upgrade process.  the upgrade notes show three variables that need to be set.   Where do I set these variables?

<code>
            innodb_large_prefix=1
            innodb_file_per_table=1
            innodb_file_format=Barracuda
</code>

**Comment by alecpl** [comment]
In MySQL/MariaDB configuration file, usually in `[mysqld]` section.
