### ISSUE TITLE
Attachments sometimes disappear after (or rather during) sending

### ISSUE THREAD

**Issue by adalbertK22** [roundcube/roundcubemail#8415]
I'd like to ask you for help. 

Concerns RC 1.4.10 with database_attachments plugin activated. The same was observed without that plugin. 
PHP 7.4, opcache on, memory_limit 1024M, 

User uploads an attachment(s) (even very small, a few kB files), sends his email and sometimes the attachments disappears. Before database_attachments plugin was activated, I could find files uploaded by users with name rcmattach* (if I remember the name well).
When the problem occurs the message sent to SMTP server doesn't consist of attachments. The copy of message placed in Sent folder is stripped of uploaded attachments, as well. 
Unfortunately, I don't know how to reproduct the problem. What I have done is to add some rcube::write_log() calls in the code to try to monitor what's going on and below is what I'd discovered. I'm not PHP programmer and don't know where I should insert additional write_log() to get to know more.

Here is the example for disappeared attachment:

- POST from browser consist of _uploadid with value=_upload1642495343566_
- plugin **database_attachments**, function **upload**(), **key**=_129055137261e67d6337756658679521dfb5c7cd7aa332598f97216_
- file **attachments.inc**, line 155 (inside loop), code print_r($attachment, true) gives: _Array_
- file **sendmail.inc**, after definition of $COMPOSE, code print_r($COMPOSE['attachments'], true) is **empty string**
- file **sendmail.inc**, line ~168 after if ($files = ..., code $files is _129055137261e67d6337756658679521dfb5c7cd7aa332598f97216_
- file **sendmail.inc**, line ~172 (inside foreach ($files as $idx => $val), idx is _129055137261e67d6337756658679521dfb5c7cd7aa332598f97216_ and after $files[$idx] = $COMPOSE['attachments'][$idx]; the variable $files[$idx] **is empty**. If I understand the source code, it can't be empty because $COMPOSE['attachments'] was empty

Analogous example of an email with attachment properly sent by the same person, just a minute later (he knows that the problem sometimes appears):

- POST from browser consist of _uploadid with value=_upload1642495376640_
- plugin **database_attachments**, function **upload**(), **key**=_107138132961e67d824160c7c498038607464921ea6cd2f0a0b8f04_
- file **attachments.inc**, line 155 (inside loop), code print_r($attachment, true) gives: _Array_
- file **sendmail.inc**, after definition of $COMPOSE, code print_r($COMPOSE['attachments'], true) is **Array** **(here is the first difference!)**
- file **sendmail.inc**, line ~168 after if ($files = ..., code $files is _107138132961e67d824160c7c498038607464921ea6cd2f0a0b8f04_
- file **sendmail.inc**, line ~172 (inside foreach ($files as $idx => $val), idx is _107138132961e67d824160c7c498038607464921ea6cd2f0a0b8f04_ and after $files[$idx] = $COMPOSE['attachments'][$idx]; the variable $files[$idx] **is Array** **(the second difference)**. 

So, I interpret it as sometimes $COMPOSE['attachments'] is empty, maybe is not defined or the value is somewhere lost.

Have you perhaps encountered such problem? How to find the problem's source out? Thank you in advance.

**Comment by adalbertK22** [comment]
Do you think such behaviour is connected with a bug in RoundCube? 
@alecpl May I ask you for a comment?

**Comment by alecpl** [comment]
The list of compose attachments (with some metadata) is stored in session. So, something is wrong with the session.
- is this a single server installation?
- is Roundcube configured to store session in database or memcache or?
- when this happens is the mail composed in a separate browser window (thinking about some race condition)?
- what are other plugins installed?
- looking at sql_debug log might help (if the session is in DB), although the session data is base64 encoded
- this might not be easy to track down, same as the famous #5869.

**Comment by adalbertK22** [comment]
The answers are as follows:

- it is a single server installation
- RoundCube stores session in database (PostgreSQL)
- mails are not composed in a separate browser window
- I just turn sql_debug on now

I will take a look at #5869.

**Comment by adalbertK22** [comment]
Finally, my customer communicated problem one again. I checked previously set logs and here is what I've discovered:

- At first, email has been sent without attachments. After two minutes, remaining in the same session the next email has been sent. This time with a file properly attached.
- SQL logs seems that attachment has been properly inserted into cache table and later deleted in both cases.
- Array COMPOSE[attachments] (sendmail.inc, row 27) is empty in the first case, and contains file data in the second.
- Array session (sendmail.inc, few rows later) in the correct, second case contains:

```
    [compose_data_406383161625919dd30a17] => Array
        (
            [id] => 406383161625919dd30a17
            [param] => Array
                (
                    [mbox] => INBOX
                    [sent_mbox] => INBOX.Sent
                )

            [mailbox] => INBOX
            [attachments] => Array
                (
                    [406383161625919dd30a179d82ea87695a62e2f7ad7ad60ee473d5] => Array
                        (
                            [path] =>
                            [name] => filename.xml
                            [size] => 136243
                            [mimetype] => text/xml
                            [group] => 406383161625919dd30a17
                            [id] => 406383161625919dd30a179d82ea87695a62e2f7ad7ad60ee473d5
                        )
                )
        )
```

whereas in the first attempt the block is cleared of "attachments":

```
    [compose_data_16384288696259196f23b29] => Array
        (
            [id] => 16384288696259196f23b29
            [param] => Array
                (
                    [mbox] => INBOX
                    [sent_mbox] => INBOX.Sent
                )

            [mailbox] => INBOX
        )
```

Consequently, the email has been sent without attachment. Could you advice what should we check next?

**Comment by adalbertK22** [comment]
I've narrowed down my search by looking at another case:

An attachment is being uploaded, attachment.inc, between operations: 

``
$attachment = $RCMAIL->plugins->exec_hook('attachment_upload', array(
``

and

``
$RCMAIL->session->append($SESSION_KEY . '.attachments', $attachment['id'], $attachment);
``

Array $attachment contains:

```
(
    [path] =>
    [name] => filename.pdf
    [size] => 106264
    [mimetype] => application/pdf
    [group] => 155547772762610da0eb666
    [id] => 155547772762610da0eb666aee9a9cad6a50cb95ee882212671fcf4
)

```
Then $RCMAIL->session->append is called (file: lib/Roundcube/rcube_session.php, function append). Result:

``
$node = &$this->get_node(explode('.', $path), $_SESSION);
``

$node is empty and a few rows below that array contains what has been passed:

```
(
    [155547772762610da0eb666aee9a9cad6a50cb95ee882212671fcf4] => Array
        (
            [path] =>
            [name] => filename.pdf
            [size] => 106264
            [mimetype] => application/pdf
            [group] => 155547772762610da0eb666
            [id] => 155547772762610da0eb666aee9a9cad6a50cb95ee882212671fcf4
        )
)

```
Coming back to attachments.inc, after rcmail_attachment_success($attachment, $uploadid); I dumped the proper part of SESSION array and it seems it's ok here. Result of: print_r($_SESSION[$SESSION_KEY], true ):

```
(
    [id] => 155547772762610da0eb666
    [param] => Array
        (
            [mbox] => INBOX
            [sent_mbox] => INBOX.Sent
        )
    [mailbox] => INBOX
    [attachments] => Array
        (
            [155547772762610da0eb666aee9a9cad6a50cb95ee882212671fcf4] => Array
                (
                    [path] =>
                    [name] => filename.pdf
                    [size] => 106264
                    [mimetype] => application/pdf
                    [group] => 155547772762610da0eb666
                    [id] => 155547772762610da0eb666aee9a9cad6a50cb95ee882212671fcf4
                )
        )
)

```
When user sends his email, magic happens. File sendmail.inc, row ~50 i dump the whole SESSION array once again and get:

```
  (...)
    [compose_data_155547772762610da0eb666] => Array
        (
            [id] => 155547772762610da0eb666
            [param] => Array
                (
                    [mbox] => INBOX
                    [sent_mbox] => INBOX.Sent
                )
            [mailbox] => INBOX
        )
  (...)

```
What happend to the attachment? The same scenario I've discovered at another case today.

**Comment by adalbertK22** [comment]
The next portion of analysis for those interested.

An attachment has been added to a message:

> [22-Apr-2022` 08:54:03 +0200]: <424f807e> attachments.inc after session->append(), part of SESSION=Array

More than one minute later: one of many calls of lib/Roundcube/session/db.php read() function, when session array still contains data concerning the attachment:

> [22-Apr-2022 08:**55:31** +0200]: <424f807e> session db read() sql_arr=Array

And immediately update() function is called. What I've discovered the $newvars does NOT contain data concerning the attachment anymore:

> [22-Apr-2022 08:**55:31** +0200]: <424f807e> session db update() 

The email is being sending more than minute later - without the attachment of course:

> [22-Apr-2022 08:56:53 +0200]: <424f807e> sendmail.inc 26 DBG FROM SESSION: COMPOSE[attachments]=

@alecpl Could you point out what you think is worth of checking out next?

**Comment by alecpl** [comment]
I'm not sure. It might be some race condition or the session storage is somehow breaking the stored data.

Maybe we should consider storing all uploads metadata in a separate database table instead of the session. This way there would be no such problems. But would be a bigger task and a BC break.

**Comment by alecpl** [comment]
Attachments are now stored separately from the session. I consider this fixed.
