### ISSUE TITLE
plugins/enigma Crypt_GPG broken

### ISSUE THREAD

**Issue by the-djmaze** [roundcube/roundcubemail#8417]
While working on my own PGP issues.
https://github.com/the-djmaze/snappymail/issues/89
https://github.com/the-djmaze/snappymail/issues/172

I've noticed that Crypt_GPG is pretty old and lacking features.

Mostly GnuPG has issues with long homedir paths, as i also reported at:
https://github.com/php-gnupg/php-gnupg/issues/44

And Crypt_GPG_KeyGenerator can't generate ECC keys with curve.

Therefore i like to know if someone tested RoundCube that it can handle everything PGP/MIME ?

Because i like to know if i can sign/encrypt messages that i send with Kmail and SnappyMail.

**Comment by alecpl** [comment]
The enigma plugin does not generate keys server side. ECC keys are supported. I have no problems with PGP/MIME.

**Comment by the-djmaze** [comment]
Ok, thanks for the info

**Comment by the-djmaze** [comment]
@alecpl
> I have no problems with PGP/MIME.

Strange, because i discovered that Mailvelope does have issues with PGP/MIME

![afbeelding](https://user-images.githubusercontent.com/3752035/154075948-514ffa8d-03b2-45ed-a207-4d1fd95dbc10.png)

As you can see on the left, my system properly decrypts and verifies the message and shows the inline image.
As you can see on the right, Roundcube uses Mailvelope and can't verify the message and shows broken inline image.

I also tried with Mailvelope disabled, but Roundcube fails to use OpenPGP.js

Should i start a new issue or do you reopen this one?

**Comment by alecpl** [comment]
Mailvelope and Enigma are two separate beings. So, feel free to open a new ticket, but I'm not sure we can make Mailvelope work with PGP/MIME or whether we support that. Probably not.

As for Enigma, you need to be more precise.
