### ISSUE TITLE
Problem with attachment name in message/rfc822

### ISSUE THREAD

**Issue by mary-pe** [roundcube/roundcubemail#8418]
Hi,
I have a problem with the attached message. 
The name of the attached pdf is split into two lines inside the header and RC 1.5.0 is not able to decode the real name, showing  "Part 1.2.pdf".
Thanks

[attachment_problem.eml.txt](https://github.com/roundcube/roundcubemail/files/7934475/attachment_problem.eml.txt)

**Comment by alecpl** [comment]
The sample is malformed. I'd also suggest update to 1.5.2.

**Comment by mary-pe** [comment]
Thanks for the reply.
I download the RC 1.5.2 and the problem still exists. 
Furthermore why do you consider the sample malformed?
I parsed the message with Perl  MIME::Parser and it didn't find any errors. 
Thunderbir also opens the sample without errors.
Thanks!

**Comment by alecpl** [comment]
It's a message inside a message where the structure is malformed. It does not import into Roundcube. But anyway, if I fix the structure, I see no problem with attachment name. I suspect an IMAP server bug. Enable imap_debug option and check the BODYSTRUCTURE response from the server.

**Comment by mary-pe** [comment]
I opened this  sample with the same imap Server but using both RC 1.3.9 and RC 1.5.2, and only RC 1.5.2 shows the problem.
How do you suggest to proceed?
Could you please give me the fix you applied to the message?
Thanks

**Comment by alecpl** [comment]
Enable imap_debug and provide the log from the moment you open the message.

**Comment by mary-pe** [comment]
[imap_debug_rc.log](https://github.com/roundcube/roundcubemail/files/7958137/imap_debug_rc.log)

**Comment by alecpl** [comment]
Hmmm... this part looks pretty match the same here. How about the response to FETCH for the attachment part headers?

**Comment by mary-pe** [comment]
[imap_debug.log](https://github.com/roundcube/roundcubemail/files/7958252/imap_debug.log)

**Comment by alecpl** [comment]
Ok, this at least helped me to reproduce the issue. I'll investigate.

**Comment by mary-pe** [comment]
Ok, thank you.

**Comment by alecpl** [comment]
Fixed.
