### ISSUE TITLE
GDPR and showing email addresses

### ISSUE THREAD

**Issue by thomascube** [roundcube/roundcubemail#8421]
Hi Roundcube Development Team.

Please would you provide a single-click option in Roundcube which would
do these two things at the same time:
1) send an email to a number of recipients showing their names only (or
for a recipient whose name is not known, show only the first part of
their email address); and
2) NOT show their full email addresses?

This would enable Roundcube users to easily:
a) comply with GDPR principles;
b) reduce the risks of computer viruses etc. spreading; and
c) still enable recipients to see who else has received the email.

I would find this option extremely helpful indeed and I am confident
others would as well.

(feature request received by email)

**Comment by alecpl** [comment]
This does not make much sense to me. Maybe I can understand b), but a) and c)? This is going to be a wontfix.

**Comment by DaveCPH2** [comment]
I asked for this development. Sorry it does not make much sense to you. My email provider uses Roundcube and I work in the charity sector. When sending emails to all or only some, of a charity's committee or Members you can either use "Send" where everyone can everyone's names and email addresses or "Bcc" where no-one can see anything, not even the names of who has been included. Good practice seems to be the bigger the list of recipients the better it is to use Bcc. My suggestion would give you an option by a single click to not share everyone's email addresses (good practice for antivrus) but still see their names, or usernames (good practice in terms of communication and awareness of who has been emailed with what and who hasn't.) I would massively appreciate this capability. Would others?

**Comment by alecpl** [comment]
RFC 5322 does not really allow for that. You could
1. use fake email addresses,
2. use the (empty) group syntax, e.g. `"Recipient name":;`. I don't know how this is supported by various mail clients.

Anyway, this is a rare request and should be implemented with a plugin.
