### ISSUE TITLE
Hot Keys to Send Email

### ISSUE THREAD

**Issue by kduraiswami** [roundcube/roundcubemail#8423]
I would like to add a feature where you can use  cmd / ctrl + enter to send an email while in the compose view. Happy to do this myself if I can just get some guidance in the js file where it would fit best. Thank you for the consideration.

**Comment by alecpl** [comment]
`keyboard_shortcuts` plugin implements this. There's also `hotkeys` plugin. I don't think I'd accept this single shortcut feature.

**Comment by kduraiswami** [comment]
Hey, thank you for this suggestion. Are you able to tell me where to locate the keyboard_shortcuts or hotkeys plugin for Roundcube?

**Comment by alecpl** [comment]
You can find them at https://packagist.org
