### ISSUE TITLE
jpeg attachment not visible in 1.5 while visible in 1.4

### ISSUE THREAD

**Issue by arekm** [roundcube/roundcubemail#8425]
With roundcube 1.4 I see jpeg attachment, can view it and download it.
With roundcube 1.5 (1.5.2 tested) only xml is shown (skin doesn't matter from what I see).

[mail-no-jpg-bug-maybe.txt](https://github.com/roundcube/roundcubemail/files/7957612/mail-no-jpg-bug-maybe.txt)

(note that jpeg content is truncated to make txt smaller)

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by arekm** [comment]
commit a5c2b4360c731aa7cdd8ddbfc866953cf366d5f3
Author: Aleksander Machniak <alec@alec.pl>
Date:   Sat Aug 15 12:13:31 2020 +0200

    Fixes in context of undefined variables, and code style


broke this. Hunk that changes program/lib/Roundcube/rcube_message.php file according to my bisecting.


(testing this commit requires this fix:

commit 7d3d8064113fdbe1fa15bbb5d2b6e2f9ffd29fc3
Author: Aleksander Machniak <alec@alec.pl>
Date:   Sat Sep 5 08:46:01 2020 +0200

    Fix PHP Fatal error: Cannot access protected property rcube_message::$body (#7588)
)
