### ISSUE TITLE
Attachment icon stick at top message on iOS

### ISSUE THREAD

**Issue by JensSpanier** [roundcube/roundcubemail#8433]
Roundcube version `1.5.2`.
On iOS the attachment icons "stick" at the top message. I think the screenshots show it very clearly:

### Chrome `97.0.4692.99` on macOS:
![chrome](https://user-images.githubusercontent.com/42373861/151987623-10993ada-f601-4117-95dd-fe82a82533d7.png)

### Safari on iOS (`15.2.1`):
![IMG_1EBB5BFCEB85-1](https://user-images.githubusercontent.com/42373861/151988123-ddabe7e9-ebd3-4687-a1f7-bda2937123cc.jpeg)

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Looks like `position:relative` on `tr` elements is not supported in Safari. I see that adding `display:flex` fixes the issue, but I'll need to test it some more.

**Comment by alecpl** [comment]
Fixed.
