### ISSUE TITLE
SMTP password is changed incorrectly if it contains %p

### ISSUE THREAD

**Issue by aalonzi** [roundcube/roundcubemail#8435]
On one of the email boxes I encountered the following error while trying to send, only from roundcube:
  535 5.7.8 Error: authentication failed

After some tests I realized that the password sent to the server for authentication was not actually that of the box, that is, let's assume a password like:
`abcd%p`
was replaced with:
`abcdabcd%p`

this happens on line 176 of "**program / lib / Roundcube / rcube_smtp.php**":
`$smtp_pass = str_replace ('%p', $ rcube-> get_user_password(), $ CONFIG['smtp_pass']);`

Does it happen to others too?

**Comment by alecpl** [comment]
Yes. `%p` is a special template. I guess we should replace it only if `smtp_pass='%p'`. So, it is a bug.

**Comment by alecpl** [comment]
Fixed. As it is a minimal BC break I don't plan to backport this to 1.5.
