### ISSUE TITLE
Email content problem.

### ISSUE THREAD

**Issue by c7v** [roundcube/roundcubemail#8439]
### :wave: Hello!

My hosting provider uses your software to work with mail in the web interface. I found that when using your package to view email, the images are downloaded from the sender's server. This allows you to use an IP spy. The picture is loaded from the sender's server, so the sender's server has the ability to find out the IP address of the final recipient when the picture is loaded.

In addition to the IP address, it is possible to obtain: location, Internet provider, which browser and operating system he uses. With this information, you can determine the initial attack vector against the end user.

If I'm wrong, please forgive me. 🧑‍💻 

![Без названия (2)](https://user-images.githubusercontent.com/50216354/152749471-9e6d6b0d-c31f-4a7a-9d87-829af6e9b826.png)

**Comment by alecpl** [comment]
Preferences > Displaying Messages > Allow remote resources (images, styles)
