### ISSUE TITLE
Extra contact information in own addressbook plugin / backend

### ISSUE THREAD

**Issue by drscream** [roundcube/roundcubemail#8441]
I'm looking for a solution to add extra information to a contact by using the `example_addressbook` plugin. For example I would like to add extra `notes` to a contact.

Based on the static configuration from the [example]( https://github.com/roundcube/roundcubemail/blob/master/plugins/example_addressbook/example_addressbook_backend.php#L38) I expected to simple add the following to the array:

```php
'notes' => array ('test'),
```

But this isn't working and the details are not shown in the contact page. I'm sure I missing something and I would appreciate your help.

**Comment by alecpl** [comment]
Try to add `$coltypes` definition in `example_addressbook_backend` class:
```
public $coltypes = ['name' , 'firstname', 'surname', 'email', 'notes'];
```
