### ISSUE TITLE
Deprecation Notice: Return type of zipdownload_mbox_filter #18 

### ISSUE THREAD

**Issue by chrmah** [roundcube/roundcubemail#8442]
Arch Linux 5.15, PHP 8.1.2, Roundcube 1.5.2 and composer 2.5.5

Got the following installation messages and later in the php.logs :

....
 - Installing mstilkerich/carddavclient (v1.2.1): Extracting archive
Deprecation Notice: Return type of zipdownload_mbox_filter::filter($in, $out, &$consumed, $closing) should either be compatible with php_user_filter::filter($in, $out, &$consumed, bool $closing): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/webpage/public/plugins/zipdownload/zipdownload.php:405
Deprecation Notice: substr(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/webpage/public/program/lib/Roundcube/rcube.php:837
Deprecation Notice: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/webpage/public/program/lib/Roundcube/bootstrap.php:329
...

**Comment by alecpl** [comment]
1.5.2 is not compatible with PHP 8.1.
