### ISSUE TITLE
cannot receive or send an email from webmail

### ISSUE THREAD

**Issue by wawarozi** [roundcube/roundcubemail#8450]
We cannot receive or send email from webmail. Any solution for this issue?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

**Comment by amarioos** [comment]
I am currently experiencing an issue with my email account. When I send an email to someone, the email appears to be sent successfully, and I can see it in the sent items folder. However, the recipient never receives my emails.
