### ISSUE TITLE
plugins/enigma GnuPG decrypt inline images sometimes fail

### ISSUE THREAD

**Issue by the-djmaze** [roundcube/roundcubemail#8451]
When decrypting a message, the inline images are sometimes broken and sometimes not.

Here a screenshot when it is broken:
![afbeelding](https://user-images.githubusercontent.com/3752035/154094602-5467c34d-3dd1-4ccf-8626-1cef1d397d03.png)

Error log contains:
```
PHP Warning:  Undefined array key "content-id" in /roundcube/program/lib/Roundcube/rcube_message.php on line 912
PHP Warning:  Undefined array key "1.1.2" in /roundcube/program/include/rcmail_attachment_handler.php on line 64
PHP Warning:  Undefined array key "1.2" in /roundcube/program/include/rcmail_attachment_handler.php on line 64
```

Mailvelope has the [same issue](https://github.com/roundcube/roundcubemail/issues/8417#issuecomment-1040307808) but that can't be solved.

**Comment by alecpl** [comment]
I'd need steps to reproduce the issue. How to create such a message?

**Comment by the-djmaze** [comment]
1. Use [KMail](https://apps.kde.org/nl/kmail2/)
2. Create HTML message and embed image
3. Sign and Encrypt (kleopatra backend)
4. Send message
5. Login into RoundCube
6. Open the message

At step 6 it sometimes fails.

My setup:
- Apache 2.4
- PHP-FPM 8.0.15
- Firefox 97

**Comment by alecpl** [comment]
You mean it sometimes works and sometimes not for the same message?

Works for me with a message generated in Thunderbird, using Roundcube git-master.

**Comment by the-djmaze** [comment]
> You mean it sometimes works and sometimes not for the same message?

Yes.
As if the decrypted message is stored on server and then the embedded image is fetched from server.
But a second time the message is not decrypted (browser cache?!?) and then the image fetch fails because there is no decrypted mail image on the server.

I can't pinpoint the issue but you might?

**Comment by alecpl** [comment]
I don't think it has anything to do with the browser. Do you have `messages_cache` enabled in Roundcube config?

**Comment by alecpl** [comment]
No feedback. I don't know what to do with this.
