### ISSUE TITLE
1.4 -> 1.5 upgrade skips guzzle (and paragonie, psr, ralouphie, symfony) in vendor/

### ISSUE THREAD

**Issue by d33psky** [roundcube/roundcubemail#8453]
- used bin/installto.sh to upgrade from 1.4.11 to 1.5.2 . It ran OK and reported "This instance of Roundcube is up-to-date. Have fun! All done."
- ran into "Failed to load class GuzzleHttp\Client" issue #8112 when browsing to /installer/
- roundcubemail-1.5.2-complete.tar.gz has a directory ./roundcubemail-1.5.2/vendor/guzzlehttp/ BUT the target directory that installto.sh worked on does not have it.
- The same goes for paragonie, psr, ralouphie, symfony .

The (manual) fix is trivial, just copy those 5 vendor directories.

**Comment by alecpl** [comment]
We'd like to see the full output of the update script run. Depending on the type of installation it should sync the vendor folder, or suggest running composer update.

**Comment by d33psky** [comment]
It did mention composer : 
```
NOTICE: Update dependencies by running `php composer.phar update --no-dev`
```
Except, there is no composer.phar anywhere in the entire tree.

Here's the log I happened to capture : 
```
/var/www/ roundcubemail-1.5.2/bin/installto.sh /var/www/roundcube/
Upgrading from 1.4.11. Do you want to continue? (y/N)
y
Copying files to target location..../
cleandb.sh
...
mssql/2009103100.sql
...
larry/templates/settingsedit.html
deleting steps/utils/text2html.inc
...
.htaccess.new
done.

NOTICE: New .htaccess file saved as .htaccess.new.
NOTICE: The 'installer' directory still exists. You should remove it after the upgrade.

Running update script at target...
Executing database schema update.
Updating database schema (2020020100)... [OK]
Updating database schema (2020020101)... [OK]
Updating database schema (2020091000)... [OK]
Updating database schema (2020122900)... [OK]
NOTICE: Update dependencies by running `php composer.phar update --no-dev`
This instance of Roundcube is up-to-date.
Have fun!
All done.
```
ps. Would have been nice if the script kept its own log somewhere.

**Comment by ras07** [comment]
Same problem here, only copying the directories over didn't fix it. Also upgrading from 1.4.11 to 1.5.2.  The /installer page shows:

```GuzzleHttp\Client:  NOT OK(Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle)```

The tail end of the installer script output showed:
```
index.php
defaults.inc.php
composer.json-dist
CHANGELOG.md
README.md
UPGRADING
LICENSE
INSTALL
.htaccess.new
done.

NOTICE: New .htaccess file saved as .htaccess.new.
NOTICE: The 'installer' directory still exists. You should remove it after the upgrade.

Running update script at target...
Executing database schema update.
Updating database schema (2020020100)... [OK]
Updating database schema (2020020101)... [OK]
Updating database schema (2020091000)... [OK]
Updating database schema (2020122900)... [OK]
NOTICE: Update dependencies by running php composer.phar update --no-dev
This instance of Roundcube is up-to-date.
Have fun!
All done.

```
Likewise, there's no **composer.phar** file anywhere in the tree.
I copied the **guzzlehttp**/, **paragonie**/, **psr**/, **ralouphie**/ and **symfony**/ directories from **roundcubemail-1.5.2-complete.tar.gz** to <MyRoundcubeDir>/vendor and restarted Apache, but that didn't solve it; I still have the **GuzzleHttp\Client:  NOT OK** message on the installer page.

I did install carddav v4.3.0 after the upgrade and before I checked the install page; I believe carddav also makes use of guzzlehttp, so it's possible this factors in somehow.

**Comment by alecpl** [comment]
If `composer.json` file exists in the target directory of `installto.sh` script, it is assumed that the installation was made with use of composer. In this case the `vendor` folder is not being synchronized (because it could overwrite some dependencies installed after installation). At this point you're supposed to know how to use composer to update your dependencies. If there is no `composer.phar` file, try `composer update --no-dev`.
