### ISSUE TITLE
MySQL 8 - Updating database schema (2020020101)... [FAILED]"

### ISSUE THREAD

**Issue by Anagastes** [roundcube/roundcubemail#8457]
On my other installations are now the same error.

https://github.com/roundcube/roundcubemail/issues/8443

How can I fix this?

**Comment by alecpl** [comment]
What error precisely?

**Comment by Anagastes** [comment]
> What error precisely?

Upgrading from 1.5.0 to 1.5.2 on MySQL 8 using the normal procedure (./bin/installto)

Triggers exactly this error directly in the last step.

MySQL 8 - Updating database schema (2020020101)... [FAILED]

**Comment by Anagastes** [comment]
Is there any new information here?

**Comment by Mouldi** [comment]
it seems this is the error that happens due to 2020020101

Running update script at target...
Executing database schema update.
Updating database schema (2020020101)... [FAILED]
ERROR: Error in DDL upgrade 2020020101: [1091] Can't DROP 'user_id_fk_cache'; check that column/key exists
All done.

**Comment by Mouldi** [comment]
The problem was fixed after manually allowing MySQL large prefixes and commenting the foreign key drop in 2020020101

**Comment by Mouldi** [comment]
@Anagastes  Yes, it works as many times as you need to,  just open your database and check what's already created, comment out any alteration that was executed successfully and leave the rest. 
then re-execute the update

**Comment by Anagastes** [comment]
> @Anagastes Yes, it works as many times as you need to, just open your database and check what's already created, comment out any alteration that was executed successfully and leave the rest. then re-execute the update

Sorry, but I can't find an entry for this in my DB. And neither in update.sh nor in updatedb.sh. I think I am blind at the moment.

**Comment by Anagastes** [comment]
under brc_system I found the old entry 2020020100. Nothing more. :D

**Comment by alecpl** [comment]
The upgrade script will not fix the database and will not continue. And you didn't provide the exact error message. We can't help you here.
