### ISSUE TITLE
Problem with message/rfc822 attachment

### ISSUE THREAD

**Issue by mary-pe** [roundcube/roundcubemail#8458]
Hi,
I have a problem with the attached message.
It seems that body of the message/rfc822 attachment is not well parsed.
Thanks
[test_body.eml.txt](https://github.com/roundcube/roundcubemail/files/8119388/test_body.eml.txt)

**Comment by alecpl** [comment]
Confirmed. This is another issue in our optimization code for eml attachments with size < 32768 bytes. Problem here is that it is a multipart/mixed message with a single part.

**Comment by alecpl** [comment]
Fixed.
