### ISSUE TITLE
Support for SSHA256

### ISSUE THREAD

**Issue by mritzmann** [roundcube/roundcubemail#8459]
[Mailcow](https://github.com/mailcow/mailcow-dockerized) (a mailserver-suite based on postfix, dovecot, rspamd) recommends in the [documentation](https://mailcow.github.io/mailcow-dockerized-docs/third_party/third_party-roundcube/#enable-change-password-function-in-roundcube) to patch [`password.php`](https://github.com/roundcube/roundcubemail/blob/master/plugins/password/password.php) manually to make `ssha256` work. Of course, when Roundcube is updated, this can break. I was wondering if it would make sense to have this directly in Roundcube so that manual patching is no longer necessary.

I am not familiar with encryption standards in detail, but ssha256 seems to be one standard among many.

**Comment by TheFirstGoodmaN** [comment]
I tried to implement a solution for this issue in https://github.com/roundcube/roundcubemail/pull/8479, could someone review it?
