### ISSUE TITLE
Empty startup greeting in 1.5.2

### ISSUE THREAD

**Issue by nathanli97** [roundcube/roundcubemail#8461]
I got err 'Empty startup greeting' when I tried to log in to my account. by using IMAP over TLS.

Here is the log:

```
(Login failed for abc against abc.foo from ::1. Empty startup greeting (abc.foo:993))
```
My imap login settings in config.inc.php:
```
$config['default_host'] = 'tls://abc.foo';
$config['default_port'] = 993;
```

But I have try to comment the code in line 1041 of file rcube_imap_generic.php:
```php
// check for SSL
        if (!empty($this->prefs['ssl_mode']) && $this->prefs['ssl_mode'] != 'tls') {
            $host = $this->prefs['ssl_mode'] . '://' . $host;
        }
```

to

```php
// check for SSL
        //if (!empty($this->prefs['ssl_mode']) && $this->prefs['ssl_mode'] != 'tls') {
            $host = $this->prefs['ssl_mode'] . '://' . $host;
       //}
```

and seems Roundcube can connect to my IMAP server by using TLS on port 993 and log in successfully.
But I didn't know that is my server's issue or Roundcubemail's issue..

**Comment by alecpl** [comment]
Usually you use ssl:// prefix on port 993 and tls:// on port 143.
