### ISSUE TITLE
RC 1.6beta - issue with file program/lib/Roundcube/html.php

### ISSUE THREAD

**Issue by sneek2020** [roundcube/roundcubemail#8471]
Played around with:
- Roundcube 1.6beta
- PHP 8.1.13
- Plugin twofactor_gauthenticator (version 2021-12-09)

I noticed that the activation checkbox for plugin [twofactor_gauthenticator](https://plugins.roundcube.net/#/packages/alexandregz/twofactor_gauthenticator) no longer shows its active state. As soon as you check the activate checkbox and hit the save button the checkbox is emptied and you can no longer see whether the plugin is activated or not. In RC 1.5.2 it worked fine.

The issue seems to be related to changes made in _program/lib/Roundcube/html.php_ due to issue #8382. 

RC 1.6beta: If I change in _program/lib/Roundcube/html.php_ line 546:

`$this->attrib['checked'] = isset($this->attrib['value']) && ((string)$value == (string)$this->attrib['value']);`
	
into

`$this->attrib['checked'] = ((string)$value == (string)$this->attrib['value']) ?? "";`
	
all functionality works as expected again (also without PHP-errors like "Undefined array key").

**Comment by alecpl** [comment]
I believe this should be rather:
```
$this->attrib['checked'] = (string)$value == (string)($this->attrib['value'] ?? "");
```

**Comment by alecpl** [comment]
On the other hand, if you do not define the `value` attribute you should not expect the `checked` state to get ever set to `true`? Imho.

**Comment by alecpl** [comment]
Wontfix, but I pushed a small change in 3307eb6b28e.

**Comment by sneek2020** [comment]
I don't know why but https://github.com/roundcube/roundcubemail/commit/3307eb6b28ef66c215952517fdf7a8609084fc3b doesn't work for me while the following did: 
`$this->attrib['checked'] = (string)$value == (string)($this->attrib['value'] ?? "");`
It doesn't make any sense at first glance but it is what it is....
