### ISSUE TITLE
Uploading causes exit signal Segmentation fault and Multipart: Final boundary missing

### ISSUE THREAD

**Issue by InputOutputZ** [roundcube/roundcubemail#8472]
Hi there,

I think found a bug with uploading files in address book for contacts profile pictures and composing a message attachments.

Environment: Master Roundcube, Httpd, ModSec 3.0.6.

I receive HTTP 503 error when uploading picture in roundcube webmail and in httpd I receive:-

 child pid 79784 exit signal Segmentation fault (11)

I debugged ModSec, and I found rule 200002 had to be commented out otherwise throws Multipart: Final boundary missing.

```
SecRule REQBODY_ERROR "!@eq 0" \
"id:'200002', phase:2,t:none,log,deny,status:400,msg:'Failed to parse request body.',logdata:'%{reqbody_error_msg}',severity:2"
```

It seems the uploading file body data format submitted incorrectly and fails to pass ModSec validation.

I would appreciate if it was addressed in coming releases, with thanks.

Zakaria.

**Comment by alecpl** [comment]
What version? Is it browser-dependent? I see nothing wrong with the request body/structure.

**Comment by InputOutputZ** [comment]
Hi Alecpl, 

Its Roundcube: Version 1.6-git.

Sorry for the delay, I just had the chance to get back to you now. It's not browser dependant, refer to this bug https://github.com/SpiderLabs/ModSecurity/issues/1471. I think the matter it's Roundcube is being incompatible with ModSec security rules. In normal circumstance it should be passed but its raising negative positive flag and fails uploading.

I can send you email account credentials to test on my server? Please drop me your email on hi@zakaria.website if needed.

With thanks.

**Comment by alecpl** [comment]
It looks like that's nothing we can fix.

**Comment by joshuapinter** [comment]
@InputOutputZ Just wanted to say thanks for this. We were running into a similar issue where file uploads were being rejected for only some Users (not Roundcube related) and commenting out this one ModSecurity rule fixed it for us. Cheers.
