### ISSUE TITLE
lists-ext.kolabsys.com down?

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#8473]
----- The following addresses had permanent fatal errors -----
<[users@lists.roundcube.net](mailto:users@lists.roundcube.net)>

   ----- Transcript of session follows -----
<[users@lists.roundcube.net](mailto:users@lists.roundcube.net)>... Deferred: Connection timed out with lists-ext.kolabsys.com.
Message could not be delivered for 5 days
Message will be deleted from queue

**Comment by alecpl** [comment]
I see some messages from 18th and 19th of March in the list. So, is this still a problem?

**Comment by f1-outsourcing** [comment]
No still, probably some firewall or so 

Connection timed out with lists-ext.kolabsys.com.

```
[marc@svr ~]$ dig +short lists.roundcube.net
lists-ext.kolabsys.com.
212.103.80.138
[marc@svr ~]$ telnet lists.roundcube.net 25
Trying 212.103.80.138...
```

**Comment by alecpl** [comment]
I wonder why the lists are working despite that.
```
Received: from mailer.zakaria.website (mailer.zakaria.website [77.68.117.221])
 by ext-mx-in002.kolabsys.com (Postfix) with ESMTPS id E399CFBD
 for <users@lists.roundcube.net>; Sat,  6 Aug 2022 23:17:06 +0200 (CEST)
```
I'll ask the admins.

**Comment by f1-outsourcing** [comment]
I still have this I was sending some messages yesterday. I am not really experienced with roundcube programming, but hacked something together to get the bing image on the logon page. Weird is that it works only on the dark theme. Is it possible that someone can look at this code see if things are more or less according to roundcube best practices?

**Comment by f1-outsourcing** [comment]
```
----- The following addresses had permanent fatal errors -----
<[users@lists.roundcube.net](mailto:users@lists.roundcube.net)>

   ----- Transcript of session follows -----
<[users@lists.roundcube.net](mailto:users@lists.roundcube.net)>... Deferred: Connection timed out with lists-ext.kolabsys.com.
Message could not be delivered for 5 days
Message will be deleted from queue
```

**Comment by alecpl** [comment]
Lists are working now.
