### ISSUE TITLE
Context root (comm_path) not correct in 1.6_beta

### ISSUE THREAD

**Issue by vibpe** [roundcube/roundcubemail#8474]
Hello,

my setup is Roundcube running on Apache behind an Apache Proxy with a dedicated virtual host.

Example:
* Public reachable URL: mail.mydomain.tld
* Forwarding with Apache ProxyPass to internal.domain/roundcube
```
        ProxyPreserveHost   On
        ProxyRequests On
        ProxyPassReverse / http://interneal.domain/roundcube/
        ProxyPass / http://internal.domain/roundcube/
```
* Second Apache is hosting Roundcube at /roundcube
```
        Alias /roundcube/ /var/www/roundcube/htdocs/
        <Directory "/var/www/roundcube/htdocs">
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Require all granted
        </Directory>
```
The browser should use the virtual host mail.mydomain.tld without any sub path

After a successful login (at mail.mydomain.tld/ ) Roundcube 1.6_beta sends the browser to mail.mydomain.tld/roundcube/?_task=login
It should use the context root of the public reachable domain  (mail.mydomain.tld/?_task=login) not the path used by the internal domain.

If I inspect the login side's page source with the browser, I can find this: "comm_path":"/roundcube/?_task=login" which should be "comm_path":"/?_task=login"

This Apache behind Apache Proxy setup worked with Roundcube 1.5.2 and all previous versions.

**Comment by vibpe** [comment]
This rewrite rules in the internet facing Apache Proxy kind of work (mails are readable):
        RewriteEngine  on
        RewriteRule ^/roundcube/skins/(.*)$ /skins/$1 [R=301,L]
        RewriteRule    "^/roundcube/(.*)$"  "/" [PT]

**Comment by Bill-ColeUS** [comment]
Maybe relevant to your problem, but `ProxyRequests` should be off when you are doing a reverse proxy.

`ProxyRequests` is set to on, when doing a forward proxy and it is known as a potential security risk (allows your webserver to act as an Open Proxy unless properly secured).

reference: https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

**Comment by vibpe** [comment]
Thank you! I changed this configuration. But it has no impact on the original issue.

**Comment by alecpl** [comment]
This is probably related to #8170. If you provide a fix that works for every case, we'll consider it.

**Comment by shahid369** [comment]
@vibpe @alecpl 

Hello , did you found out any resolution for this ? I'm experiencing the same with roundcube version 1.6.4 
after login I'm expecting  the redirection to mydomain.com/?_task=login but as you've mentioned I'm seeing the "comm_path":"/roundcubemail/?_task=login" in the source and its causing a 404  when redirects, was working fine with version 1.5 , any hint will be appreciated , I'm running roundcube behind an nginx proxy 

location / {
            more_clear_headers Server;
            proxy_pass http://mydomain.com:port/roundcubemail/;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             }
