### ISSUE TITLE
Problems with Editing Signatures in Edge and Chrome

### ISSUE THREAD

**Issue by TheOneLight** [roundcube/roundcubemail#8476]
Hi, 

I tried to register on the Round Cube Forum website, but the system always considered my attempts to sign up as SPAM, so I am trying it here now.

Since January, I believe, I have been unable to edit any signatures in RoundCube when using the skin "Elastic" on Windows 10 in Edge or Chrome unless in the "InPrivate" / "Incognito" window, where it works. Of course, I could simply go there, but as that is a bit inconvenient and as it worked before for years, I wonder what the problem might be. 

When trying to access the signature field (where I can see my signature, which I had entered a while ago), the curser always jumps to the top of the page and does not stay in the signature field, so I cannot edit it.

I would be thankful for any advice, and, in case it is a bug, I simply wanted to make the developers aware of it by this note.

Thank you for providing RoundCube, which I have used for years.

**Comment by alecpl** [comment]
What version? Any errors in browser console? Is the signature in HTML or plain text mode? Does it work in the other mode?

**Comment by alecpl** [comment]
If it works in incognito, then maybe it is some browser extension interfering? The display/compose options have not much to do with identities html mode. Could you create a screenshot?

**Comment by TheOneLight** [comment]
Thank you for your reply. You are right - it is. I had wondered before, but not switched off all of them, I thought it could only be the add blocker. Instead, it was the password manager's plugin, I would have never guessed. They had an update then, I just did not draw the connection. I would have never guessed despite the obvious evidence that it could be a plugin... Thank you. I will contact them and let them know. One of the two plugins I would not really like to remove...  Again, thank you for your help, and all the best!
