### ISSUE TITLE
HTM signature

### ISSUE THREAD

**Issue by ColinLondon** [roundcube/roundcubemail#8478]
I am using version 1.4.11

I want to create an HTML signature, but there is no checkbox for this. Everything I see on Google says I should check this box, but it isn't there.

Has this functionality been discontinued, or am I missing something?

Cheers

**Comment by TheFirstGoodmaN** [comment]
Which Skin do you use?

In the elastic skin its hidden here  
![image](https://user-images.githubusercontent.com/1267672/159051649-ac02ad55-23bd-48b6-ae5e-3814a593b1be.png)

**Comment by alecpl** [comment]
No feedback.
