### ISSUE TITLE
Feature Request: Security badge

### ISSUE THREAD

**Issue by InputOutputZ** [roundcube/roundcubemail#8482]
Hi there,

I hope everyone is doing well, I just wanted to make feature request.

In mail view, beside headers dialog, if we can have security badge dialog like this.
<img width="685" alt="Screenshot 2022-03-21 at 18 19 56" src="https://user-images.githubusercontent.com/4721398/159338654-becb508e-0b40-4c50-b5b3-d8ee5cf0edd0.png">

To include in security analysis verifications extracted from headers and displayed in more user friendly and intuitive format to cover with sub-badges, TLS transport host verification, TLS version verification, DKIM valid verification host, ARC from instance 1 to last instance verification hosts, SPF verification host, DMARC verification domain as well as message content spam scanning score, coloured perhaps green, if <1, orange if 3< and red if >3.

I would very much appreciate to see this feature implemented, with thanks.

Zakaria.

**Comment by alecpl** [comment]
A good idea for a plugin.
