### ISSUE TITLE
mailcow quarantine attached eml

### ISSUE THREAD

**Issue by drlight17** [roundcube/roundcubemail#8486]
Hello!
I'm using mailcow-dockerized mailing system in production with roundcube instead of sogo. I've found out that one can only download attached released from the mailcow quarantine eml files. Are there any ways to open these attached eml files inside the roundcube (not only download)?
See [quarantine_example.zip](https://github.com/roundcube/roundcubemail/files/8331960/quarantine_example.zip) as an example

![image](https://user-images.githubusercontent.com/37434652/159674800-67c634de-1a07-44e4-b48b-14949f67587b.png)

**Comment by alecpl** [comment]
The attachment type is `application/octet-stream` instead of `message/rfc822`. We usually do not trust the file extension.

**Comment by drlight17** [comment]
> The attachment type is `application/octet-stream` instead of `message/rfc822`. We usually do not trust the file extension.

Ok. So, what should I do to open application/octet-stream attachment inside the RC?
