### ISSUE TITLE
Mark as read hotkey

### ISSUE THREAD

**Issue by ShadwDrgn** [roundcube/roundcubemail#8487]
There doesn't seem to be a hotkey that just marks the currently selected email(s) as read. I'm not sure if i'm just blind, as it seems unlikely this obvious feature would be missing. Can someone tell me what if any this shortcut is?

In gmail as an example i would hit I  and all currently selected emails would be marked immediately as read  and U to mark it unread. In outlook it's ctrl-q and ctrl-u for unread. in thunderbird it's M to toggle read/unread, in yahoo it's K for read and shift+K for unread. in Rainloop it's M to toggle.

Not sure what it is in roundcube.

Failing this I looked for a one click read/unread toggle button but that doesn't seem to exist either. The only way to mark an email as unread or read seems to be clicking "Mark" then clicking read or unread. This makes marking multiple emails as read very frustrating unless they have something in common I can search to use that "Mark all visible as read" option which usually is not the case.

**Comment by goodygh** [comment]
As far as I know roundcube itself can't do this, but there is a [plugin](https://github.com/texxasrulez/roundcube-plugin-keyboard_shortcuts) that does.

**Comment by alecpl** [comment]
The core implements only keyboard navigation, but plugins exist.

**Comment by necrevistonnezr** [comment]
None of the current plugins provide this functionality after the update to [Roundcube 1.6.1](https://github.com/roundcube/roundcubemail/releases/tag/1.6.1):

- None of the "keyboard_shortcuts" plugins (see https://github.com/corbosman/keyboard_shortcuts/network/members) work at all after the update. All other plugins are fine - but if I activate this one, Roundcube doesn't load anymore. I had last used https://github.com/texxasrulez/roundcube-plugin-keyboard_shortcuts
- https://github.com/random-cuber/hotkeys (also https://packagist.org/packages/random-cuber/hotkeys) doesn't have a "mark as read" functionality
