### ISSUE TITLE
Feature Request:  Add email address to header <title> after 'product_name'

### ISSUE THREAD

**Issue by chicagola** [roundcube/roundcubemail#8488]
Do you know how to change the page title of Roundcube Webmail so that it includes the email address in the <title> after 'product_name' when logged it?  For instance, if I login to Roundcube with the example https://webmail.domain.com/, it goes to the Inbox, and the page title display is "Roundcube Webmail :: Inbox". Do you know if there is a way that it can display "Roundcube Webmail :: [admin@domain.com] :: Inbox" ?  I do not see that option in usr/share/psa-roundcube/config/defaults.inc.php.  It would help to identify which email address we are logged into when viewing open browsers with multiple logins.

**Comment by alecpl** [comment]
No such option. You can modify the code in `rcmail_output_html::get_pagetitle()`

**Comment by chicagola** [comment]
Thank you Aleksander.  Can you tell me the code modification that I need to make in rcmail_output_html ?
