### ISSUE TITLE
MySQL 8 - Updating database schema (2020020101)... [FAILED]

### ISSUE THREAD

**Issue by Anagastes** [roundcube/roundcubemail#8490]
@alecpl 

It would have been very kind to say that you need the exact message.

It is exactly the message @mouldi "https://github.com/roundcube/roundcubemail/issues/8457" already mentioned.

Here you have it again. Sorry, but that is extremely unkind. I ask politely and want to help.

```
ERROR: Error in DDL upgrade 2020020101: [1091] Can't DROP FOREIGN KEY `brc_user_id_fk_cache`; check that it exists
```

**Comment by Anagastes** [comment]
Such an annoyed reaction is absolutely unnecessary, we are all human and want the software to be better.

**Comment by alecpl** [comment]
The error indicates that you're probably trying to execute the upgrade script a second time. I.e. the database is already in a state that the script can't deal with.

This is not a support forum.
