### ISSUE TITLE
Weird error - STARTLS failed - authentication failed

### ISSUE THREAD

**Issue by elvisef** [roundcube/roundcubemail#8491]
Hello.
Sorry to interrupt You but Ive got a weird error.
I cannot send anything using Roundcube client, because it notifies me about error with authentication.

Attaching screenshots.
One is from the client. The other is from the terminal - error log file.

It is weird because I did no changes with the server at all.
I was able to send emails up to 1st of April and it immediately stopped.
There was an error in the database with the session on 24th march, about duplicate entry (why ?) but Ive checked it now, there is no duplicates, and Ive just cleared session data and re-logged into my account. No changes.

What can be the issue here ?
I need to have it working but error logs do not tell anything important, or where to look.
Everything was set and working ;/ 
![2022-04-03_14-11](https://user-images.githubusercontent.com/25976749/161427718-607fa063-2c66-42fd-b54d-8b55c8f84aee.png)
![2022-04-03_14-12](https://user-images.githubusercontent.com/25976749/161427719-9ea7d6af-6c24-4014-bb18-03d42cd5ec9f.png)
![2022-04-03_14-19](https://user-images.githubusercontent.com/25976749/161427764-f8822654-a3eb-42d9-b591-672361c68ec7.png)

Some errors from "sessions.log"
![2022-04-03_14-22](https://user-images.githubusercontent.com/25976749/161427876-73556f53-e62c-4679-a67d-17d1b3d3bcfa.png)
![2022-04-03_14-23](https://user-images.githubusercontent.com/25976749/161427877-9e0458a1-69e4-43f5-9f43-28bc8f69eb06.png)
![2022-04-03_14-23_1](https://user-images.githubusercontent.com/25976749/161427878-d4b4bbd2-4d68-467c-beb6-6b6e35c42293.png)
![2022-04-03_14-23_2](https://user-images.githubusercontent.com/25976749/161427880-24ca4c16-3b71-4a6f-98fa-29b0e3cbc3cc.png)

**Comment by alecpl** [comment]
Maybe the ssl certificate expired, or sth like that.
