### ISSUE TITLE
Hungarian spelling problem

### ISSUE THREAD

**Issue by gmark08** [roundcube/roundcubemail#8492]
in the word "kűld" it is a short ü.
the picture shows where these should be fixed.

![hungarian_spellingproblem](https://user-images.githubusercontent.com/103028730/161916320-8d370f33-b878-4e90-b5a3-89e25647b098.PNG)

**Comment by alecpl** [comment]
This needs to be fixed in https://www.transifex.com/roundcube/roundcube-webmail/

**Comment by gmark08** [comment]
Thanks. I am currently waiting to be a member of the team.
