### ISSUE TITLE
Send button doesnt work

### ISSUE THREAD

**Issue by vluzrmos** [roundcube/roundcubemail#8494]
When I try to click on "Send" button nothing happens, no requests are made, no console log messages, but it shows up a message: "Connection Error (Failed to reach server)!"

Roundcube Version: 1.5.2-apache (docker)

Spellcheck is disabled in `config.docker.inc.php`:

```php
$config['enable_spellcheck'] = false;
```

I've tried already #5273 , changing session lifetime but its the same, button doesnt work.

**Comment by vluzrmos** [comment]
This line is causing the error, the "about:blank" page tiggers "load error" when the iframe is appended to the document body.

https://github.com/roundcube/roundcubemail/blob/master/program/js/app.js#L5124

My workaround solution was to change "about:blank" to "javascript:false;", that has the same effect of a blank page.

**Comment by alecpl** [comment]
Strange. You're the first user with this issue. What browser? Any specific error in browser console?

**Comment by vluzrmos** [comment]
> Strange. You're the first user with this issue. What browser? Any specific error in browser console?

I'm using Edge 100.0.1185.36 and Chrome 100.0.4896.75,
No console errors, no requests are made, just the notification with:
"Connection Error (Failed to reach server)!"

**Comment by alecpl** [comment]
Maybe it's some add-on or antivirus software interfering? Can you reproduce with Firefox?

**Comment by juanbits** [comment]
> I was experiencing the same issue, a cleanly installed Firefox or Chrome in incognito mode (which disables all plugins) worked which pointed me to a plug-in. In my case it was the Chrome [Dark Mode](https://chrome.google.com/webstore/detail/dark-mode/dmghijelimhndkbmpgbldicpogfkceaj) plugin interfering. Disabling that resolved the issue but I'm not sure how that plugin can cause this behaviour.

its very strange, i had the same problem until i see your comment, i think it was a problem on my server config, but disabling that extension now works.

thanks @fust

**Comment by brblakel** [comment]
Same issue with the chrome dark Mode plugin just now. I used it previously on Windows 10 chrome with no problems, but setting up new Windows 11 laptop with Chrome, and if the Dark Mode plugin is enable and I hit Send, the "sending message" thing appears and just spins forever.  No problems in other browsers, or a Guest window, or with the Dark Mode plugin disabled.

**Comment by Galibri** [comment]
The Dark Mode plugin of chrome store solved my issue. Not sure how this was blocking the send button. Finally Solved. Thanks @fust
