### ISSUE TITLE
Out-of-office reply does not have correct header

### ISSUE THREAD

**Issue by xammm** [roundcube/roundcubemail#8496]
Hey guys!

When setting up a filter for an out-of-office reply, the out-of-office emails do not have the name of the user in the header. In gmail those mails are just shown as "mail" (because the email address is mail@...). As a result those emails tend to end up in the spam folder. 

When sending an ordinary email, the emails have the proper header with the name.

Is this some limitation of roundcube or can this be configured?

Thanks
Max

**Comment by alecpl** [comment]
The reply sender address is optional, but can be specified in a form of `"Sender name" <sender@address.com>`.
