### ISSUE TITLE
Folder sort order

### ISSUE THREAD

**Issue by faca5** [roundcube/roundcubemail#8499]
Hello.

Is there a way to set permanent sort order for folders?

Drafts
Sent
Trash
Archive
Custom Folder 1
Custom Folder 2
Custom Folder 3

Example:
Custom Folder 1 has been moved before Drafts but all the time is moved back down (Outlook).

**Comment by alecpl** [comment]
Not possible, and there's a ticket already #5003.

**Comment by rufusz** [comment]
This ticket was closed, but also the duplicate [#5003](https://github.com/roundcube/roundcubemail/issues/5003) was apparently closed without a resolution. Am I missing something here?

**Comment by alecpl** [comment]
It wasn't closed.
