### ISSUE TITLE
Attached files are empty

### ISSUE THREAD

**Issue by nixoncheong** [roundcube/roundcubemail#8500]
This attachment is suspicious because its type doesn't match the type declared in the message. If you do not trust the sender, you shouldn't open it in the browser because it may contain malicious contents.

Expected: image/png (.png); found: application/x-empty
![Screenshot 2022-04-12 014338](https://user-images.githubusercontent.com/103436652/162784501-52905ee6-c3ba-46f4-adf9-821314eb6f55.png)

How do I fix the issue above? I try to change another devices to log in my mywebmail email, but the issue still exists as I still can't attach any file and send it to someone. Is there any bug with my account?

**Comment by nixoncheong** [comment]
@alecpl

**Comment by alecpl** [comment]
Not enough information. Looks like it is attaching empty files for some reason. You'll have to investigate what happens when you attach files. What version? What plugins? Any errors in log?
