### ISSUE TITLE
Create link for logo image.

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8501]
I have been trying to create a link for the logo inside roundcube.

![logo_link](https://user-images.githubusercontent.com/80302627/163016205-04a1fd57-4975-49d7-9975-870b033b75b8.png)

I followed the plugin instructions for creating a `<roundcube:button ...>` around the logo in `menu.html` but every time i added the button tag the logo image would disappear and not display on the page.

What is the correct way to hand edit `menu.html` for adding a link to the logo?
As a feature request it would be nice if this was built in, a URL we can define in `config.inc.php`.

**Comment by alecpl** [comment]
The easiest way would be to use `template_object_logo` hook (argument: `content`).

I'd accept a PR that adds possibility to set the URL via the `skin_logo` option.

**Comment by johndoh** [comment]
Adding support to skin_logo appears to be trivial, putting in something like
```php
if (($target = $this->get_template_logo('click')) !== null) {
    $attrib['onclick'] = "location.href='". $target ."'";
}
```
this adds support for a click while not breaking existing skins, e.g. Classic or Larry which already have `onclick` actions (they would simply be overwritten by the new config if specified).

The only wrinkle is the cursor, CSS needs to be added to change it to a pointer if conclick is specified. Or we could strip the onclick attrib out from the <img> tag and instead wrap it in an <a>. I think I prefer the second option, while it is a bigger change it feels more elegant to wrap the <img> in an <a> if a click event is required.

**Comment by Github-Citizen** [comment]
Created PR
https://github.com/roundcube/roundcubemail/pull/8509

**Comment by alecpl** [comment]
Thanks for the PR. Merged.
