### ISSUE TITLE
Advanced mail search syntax with more possibilities (without UI)

### ISSUE THREAD

**Issue by jdaviescoates** [roundcube/roundcubemail#8502]
One of the primary reasons I use Roundcube is that [it supports these search operators](https://docs.roundcube.net/doc/help/1.1/en_US/mail/searching.html):

    from:
    to:
    cc:
    bcc:
    subject:
    body:

However, like most people these days, I'm accustomed to be able to use all the [search operators available in Gmail](https://support.google.com/mail/answer/7190?hl=en).

I particularly miss:

```
has:attachment
- 
in:anywhere 
is:unread
is:read
size:
larger:
smaller:
older_than:
newer_than: 
OR
```

`in:anywhere` is already possible by adjusting scope in search options, but would be nicer to be able to do it directly from the search box
`older_than:` and `newer_than:` are kinda sorta [already available via the search options](https://github.com/roundcube/roundcubemail/issues/6006#issuecomment-1097453985), but again, it'd be much nicer to be able to do it from the search box
`OR` was requested over at #5094

**Comment by frontierpsycho** [comment]
`AND` would be great too, I think I'm missing that more than `OR`.

**Comment by alecpl** [comment]
Implemented. If there's something missing or can be improved, pull requests welcome.

**Comment by jdaviescoates** [comment]
> Implemented. If there's something missing or can be improved, pull requests welcome.

Wonderful, thanks!

Which ones did you implement? Just the ones mentioned in this thread, or ALL the search operators of Gmail?

Also, what version of Roundcube will these new search syntax options be available? 

Thanks again!

**Comment by alecpl** [comment]
It will be available in Roundcube 1.7.

**Comment by jdaviescoates** [comment]
> It will be available in Roundcube 1.7.

That's great, thanks!

Are you able to list which ones you've implemented?

(I'm wondering if eg in:sent etc got in there? I didn't explictly list it above, but it's one of the Gmail options)

Thanks again!

**Comment by alecpl** [comment]
Look at the diff and you'll see. No, in:sent wasn't implemented, actually anything that considers folder selection is tricky regarding the UI state, so it will need more consideration to implement correctly.

**Comment by jdaviescoates** [comment]
Thanks! It looks like the simplest place to see all extra bits you've added is line 124 onwards in the tests here:

[tests/Actions/Mail/Search.php](https://github.com/roundcube/roundcubemail/blob/31241485decbf79b875ca7cb10691a134f63fbf8/tests/Actions/Mail/Search.php)

You've added loads, many thanks! :smile:
