### ISSUE TITLE
How to stop Roundcube session ending when I close my laptop lid? 

### ISSUE THREAD

**Issue by jdaviescoates** [roundcube/roundcubemail#8504]
I don't want to have to login to my Roundcube every day. I want to be able to close my laptop and night, open it up again and the morning and continue where I left off.

How can I achieve this please?

I've tried adding:

`$rcmail_config['session lifetime‘] = 10080;`

To `app/data/customconfig.php` but as far as I can tell that hasn't made any difference at all.

**Comment by alecpl** [comment]
This is not supported.

**Comment by jdaviescoates** [comment]
Oh, that's a pity. So there is no way to keep the session alive? 
So what's the point/ actual purpose of the `session lifetime` and other similar config options?
