### ISSUE TITLE
virtuser_query and SSL/TLS

### ISSUE THREAD

**Issue by bfal78** [roundcube/roundcubemail#8505]
I test the Plugin to select the correct Mailserver from a MySQL Database for the user that is logging in.

I set $config['virtuser_query_dsn'] and
$config['virtuser_query'] = array('host' => "SELECT SERVER from SERVERS where EMAIL='%u'"); to collect The Mailserver.

It works but it seems to connect only without SSL oder TLS. If i modify the function user2host to set ssl:// bevor the argument. The Connection works also with ssl.
```
---------Before------
if ($sql_arr = $dbh->fetch_array($sql_result)) {
            $p['host'] = $sql_arr[0];
        }
--------After.............
if ($sql_arr = $dbh->fetch_array($sql_result)) {
            $p['host'] = "ssl://".$sql_arr[0];
        }
----------------
```
Is this a Bug? Or am I using the function incorrectly

**Comment by bfal78** [comment]
Sorry for the Bold text. I dont know why the Text ist now Bold

**Comment by alecpl** [comment]
That's right, the query have to return ssl:// or tls:// prefixed host name, you can also append a port number.
