### ISSUE TITLE
Empty password error in ha setup

### ISSUE THREAD

**Issue by schnes4** [roundcube/roundcubemail#8506]
Hi,

I deployed the roundcube Docker container (latest version) to my k8s cluster.
Everything works fine if I deploy only one replica. After scaling the deployment to 3 replicas, I always recive two errors:

* Connection to storage server failed
* Server Error: empty password

Sometimes the second error is not shown and the mails get loaded as expected.

It seems to be a problem with the session the password is stored in.

Is there a way to deploye multiple instances of roundcube?
What about the first error?

**Comment by alecpl** [comment]
It is possible, but not trivial. This is out of scope of this bugtracker.
