### ISSUE TITLE
Issue after commit #8435 : No more smtp authentification with CONFIG smtp_user smtp_pass values

### ISSUE THREAD

**Issue by mickael067** [roundcube/roundcubemail#8507]
Hi all,

This is a big issue after the commit #8435 on file program/lib/Roundcube/rcube_smtp.php

No more smtp authentification when $CONFIG['smtp_user']) and $CONFIG['smtp_pass']) have user and pass value.

My analyze:
$smtp_user and $smtp_pass was never set again to $CONFIG['smtp_user']) and $CONFIG['smtp_pass']) if value is not %u or %p

My proposal to solve the issue: https://github.com/roundcube/roundcubemail/pull/8508

Thanks.

**Comment by alecpl** [comment]
Fixed.
