### ISSUE TITLE
RC 1.5 doesn't render deeply nested message/rfc822 attachments properly (RC 1.4 does)

### ISSUE THREAD

**Issue by nsoggia** [roundcube/roundcubemail#8510]
Hi,
here is an [email sample](https://github.com/roundcube/roundcubemail/files/8523599/email_sample.zip) that RC 1.5.2 can't display properly. RC 1.4.13 has no issues.
RC shows the "unreadable.eml" headers followed by the raw mime part instead of the rendered body:

---
# RC 1.5:
![rc 1.5 fail](https://user-images.githubusercontent.com/18053505/164296041-54f4410e-25d1-43f2-8060-d03873ecca3a.png)

---
# RC 1.4:
![rc 1.4 win](https://user-images.githubusercontent.com/18053505/164296050-88de2ac7-8c5f-4e23-bf6c-7efaa68a97b3.png)

**Comment by alecpl** [comment]
Probably a duplicate of #8458.

**Comment by nsoggia** [comment]
It is.
In Italy we have this certified email system called PEC where the original message is wrapped along with its signature. We use it quite a lot.
The sample in [#8458](8458) seems a anonymized PEC indeed.
