### ISSUE TITLE
Folder tree delimiter sometimes wrong

### ISSUE THREAD

**Issue by tdeuling** [roundcube/roundcubemail#8515]
Hi,
I'm using the _ident_switch_ for switching between different account.

First I logged-in, the folder tree of my main account is build well. After I've changed to a different account and back to the main account the tree won't be build.

![Selection_1096](https://user-images.githubusercontent.com/1298841/165234412-3aa76dee-f45a-47c5-8751-2a75aa48945c.png)

By switching between the accounts, all other folder trees looks fine, but the main account folder tree is always unparsed. There are no JavaScript issues in the console. Only a few collapsable nodes are available by using the `.` delimiter. But for the system the default_delimiter is set to `/` and also the delimiter for all accounts.

What could be wrong - do I've a mis-configuration or is this a bug?

**Comment by alecpl** [comment]
That will be problem with the plugin which we do not support here.
