### ISSUE TITLE
1.5.2: Search input in elastic skin

### ISSUE THREAD

**Issue by rico666** [roundcube/roundcubemail#8516]
Disclaimer: I may be old an in general incompatible to this fluffy responsive mobile phone stuff as I use 99,x% of the time a Desktop - I also need glasses already.

BUT

Can someone tell me if I went blind entirely or where the search box in the elastic skin is? In order to search for a mail, I had to switch back to the classic view, seach (and find). Certainly I'm overlooking something? On the other hand please take this as feedback on software ergonomy (and functionality) of the elastic skin.

**Comment by alecpl** [comment]
It is above the messages list. There's a magnifying glass icon and "Search..." placeholder on the input.
