### ISSUE TITLE
Problem with aria-hidden in toolbar menu

### ISSUE THREAD

**Issue by AGoubs** [roundcube/roundcubemail#8517]
The toolbar menu are loaded with `aria-hidden=true` by default which create accessibility issues.
It is added for the popup menu on mobile view but also affect desktop view.   

It seems to come from ui.js in `popup_init()` where every items linked to a data-popup are hidden by default.

For exemple in the mail toolbar menu : 
`<ul class="menu toolbar listing iconized" id="toolbar-list-menu" aria-hidden="true">`

**Comment by alecpl** [comment]
Fixed.
