### ISSUE TITLE
mail_host ignored

### ISSUE THREAD

**Issue by mbadici** [roundcube/roundcubemail#8520]
I have some users which authenticate using uid ( withouth domain suffix). In the past when I set mail_host as default domain  the user identity is created using this value ( for example, if mail_host is example.ro , when I login as mihai the default e-mail will be mihai@example.ro) . But using the current version from git the default e-mail identity is still mihai@localhost
I didn't have since longtime users without domain so i'm not sure when and why this behavior was changed.
Thanks,
Mihai

**Comment by alecpl** [comment]
What do you have in imap_host, username_domain and mail_domain options?

**Comment by mbadici** [comment]
imap_host is localhost, the rother two where unset. mail_domain is what I search for but as I remember ( maybe wrong) I used mail_host in the past...

**Comment by alecpl** [comment]
I don't recal mail_host option existence.

**Comment by mbadici** [comment]
Well, it is a little bit older: https://www.roundcubeforum.net/index.php?topic=23277.0
But last time when I configured a server for authentication without domain part was probably 10 years ago . I have this field in my template since then but was never used... since this week :)
Thanks for clarification, mail_domain is more precise anyway.

**Comment by mbadici** [comment]
imap_host - localhost
The rest are empty.
It looks like mail_domain is the value I need to set, right?
So where is used mail_host ?
Thanks,
Mihai
