### ISSUE TITLE
Roundcube Version 1.6 remove Classic Skin? Typo?

### ISSUE THREAD

**Issue by pm-pm** [roundcube/roundcubemail#8521]
Hello,

i was looking for beta version and read "Removed the Classic and Larry skins from the release packages". Is this a typo?

Removing classic skin? The only skin useable on PC!
Please note: I want to WORK with emails and i DON´T want to play with emails on the screen. :-)
Please use the given space by a normal LCD Screen. Thanks.

pm-pm

**Comment by alecpl** [comment]
`composer require "roundcube/classic::~1.6.0"`

**Comment by pm-pm** [comment]
Dear Sir.
Is that an answer or just letters?
I am not a developer who understands with these few characters where the problem is.
It would be really nice to give a textual answer.

By the way: I installed Roundcube 1.6.rc today. Not nice to have ONLY the vertical layout with the big letters.

Thank you.

**Comment by alecpl** [comment]
This is the way to install extra skins. The same way you can install `roundcube/larry` skin.
