### ISSUE TITLE
Time differs between system time and time in log file

### ISSUE THREAD

**Issue by ssangho8** [roundcube/roundcubemail#8524]
Hi,
I'm using roundcube 1.4.8 on my CentOS mail server.

When I type 'timedatectl' on command line, it says
      Local time : 2022-05-03 13:11:25 KST
Universal time : 2022-05-03 04:11:25 UTC
         RTC  time : 2022-05-03 04:11:25 
        Time zone : Asia/Seoul (KST, +0900)

However, the time inside log file (smtp.log) shows 9 hours earlier (2022-05-03 04:11:25) which has to be 2022-05-03 13:11:25.

Please help.

**Comment by alecpl** [comment]
You should check Roundcube 1.5. Also, PHP has a separate setting for timezone. Check php.ini.

`php -r "echo date_default_timezone_get();"` will show you the PHP's default, but keep in mind that CLI might use different php.ini.
