### ISSUE TITLE
Spellchecker should ignore links

### ISSUE THREAD

**Issue by rakotak** [roundcube/roundcubemail#8527]
roundcube version : 1.4.7
aspell version : 0.60.7
pspell library : php7.4-pspell
pear Mail Mime version : 1.10.2  stable
----
rcube variables:
$config['spellcheck_engine'] = 'pspell';
$config['spellcheck_languages'] = array (
  'en' => 'English',
  'de' => 'Deutsch',
  'da' => 'Dansk',
  'fr' => 'Français',
  'it' => 'Italiano',
  'es' => 'Español',
);
-----

issue

when there is an URL in a signature (does not matter if the signature is plain text or HTML), "**Check spelling before send**" _always_ returns the mispellingsfound error regardless of the language of the spell check. The check in question seems to be set up inside `roundcube/program/steps/mail/sendmail.inc`

        $spellchecker = new rcube_spellchecker(rcube_utils::get_input_value('_lang', rcube_utils::INPUT_GPC));
        $spell_result = $spellchecker->check($message_body, $isHtml);

spell_result is indeed empty as I can confirm by trying to capture the variable via file_put_contents.

Can somebody please advise me on how to further debug this? Thanks in advance!

**Comment by alecpl** [comment]
Does it happen with every language? I don't see how it is possible to get `mispellingsfound` error with an empty `$spell_result`.

For debugging purposes you have `rcube::console($var);` which logs to logs/console.log. Please, provide `$message_body` and `$spell_result`.

**Comment by rakotak** [comment]
-----------
FR results:
-----------

`$message_body`

[08-May-2022 05:45:36 +0000]: <cbfrod5f> <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body style='font-size: 10pt'>
<p>test</p>
<div id="signature">-- <br />
<p class="p1"><span class="s1" style="font-family: 'arial black', sans-serif;">Cordialement,</span></p>
<p class="p1"><span class="s1" style="font-family: 'arial black', sans-serif;">visitez notre nouveau site web sur <span class="s2"><a href="http://www.redacted.com">www.redacted.com</a></span></span></p>
</div>

`$spell_result`

[08-May-2022 05:45:36 +0000]: <cbfrod5f> false

-----------
EN results:
-----------

`$message_body`


[08-May-2022 05:55:04 +0000]: <cbfrod5f> <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body style='font-size: 10pt'>
<p>test</p>
<div id="signature">-- <br />
<p class="p1"><span class="s1" style="font-family: 'arial black', sans-serif;">Greetings,</span></p>
<p class="p1"><span class="s1" style="font-family: 'arial black', sans-serif;">visit our new web site at <span class="s2"><a href="http://www.redacted.com">www.redacted.com</a></span></span></p>
</div>

`$spell_result`


[08-May-2022 05:55:04 +0000]: <cbfrod5f> false

**Comment by alecpl** [comment]
Ok, so the HTML is converted to plain text:
```
test

-- 
Greetings, 

visit our new web site at www.redacted.com
```
and the spellchecker considers `www.redacted.com` to be mispelled, which makes sense.

I guess it would make also sense to ignore any strings starting with `www.`. In case of `http://www.redacted.com` it will consider both `http` (when using English, but not for example Polish) and `www.redacted.com` a mispelling, so such also could be made ignored.

**Comment by alecpl** [comment]
Fixed. A backport to 1.4 is not planned.
