### ISSUE TITLE
SMTP send:  NOT OK(Authentication failure: STARTTLS failed (Code: ))

### ISSUE THREAD

**Issue by Noxillio** [roundcube/roundcubemail#8529]
Trying to finish setting up Roundcube, so close to being done especially when I initially thought the task would be impossible for my current setup. When testing SMTP in the end stage of the installation I receive an error. I have an error while testing IMAP as well but I'm going to make a separate issue for that.

```
SMTP send:  NOT OK(Authentication failure: STARTTLS failed (Code: ))
```

That's all I get.  I can send/receive emails fine and I can log into the mail account from my phone just fine as well using STARTTLS so it is set up properly there. Please advise.

**OS**: Windows Server 2022
**Web Server**: IIS 10
**PHP Version**: 8.0.0 (x64, NTS, VS19)
**Mail Server**: hMailServer 5.6.8-B2574

If other information is needed, please let me know.

**Comment by alecpl** [comment]
Probably some SSL issue. Try with:
```
$config['smtp_conn_options'] = [
   'ssl' => [
      'verify_peer'  => false
   ]
];
```

**Comment by VetheonGames** [comment]
> Probably some SSL issue. Try with:
> 
> ```
> $config['smtp_conn_options'] = [
>    'ssl' => [
>       'verify_peer'  => false
>    ]
> ];
> ```

Having same issue trying to setup RoundCube with Postfix and Dovecot on Cent OS Stream 8 with Certbot SSL. 

Adding this to config.inc.php does not solve the problem.

**Comment by VetheonGames** [comment]
I managed to get TLS working via adding a series of variations on different config options. I eventually started making random changes and eventually got it work. Couldn't explain how it got fixed but... it is now.

**Comment by flnogrim** [comment]
I added to config.inc.php this and it worked. I have Almalinux9, php 8.0.13 and roundecube 1.6.0

$config['smtp_host'] = 'tls://localhost';
$config['smtp_conn_options'] = array(
'ssl' => array(
'verify_peer' => false,
'verify_peer_name' => false,
),
);

Original post:  https://forum.howtoforge.com/threads/solved-roundcube-smtp-error-authentication-failure.73804/
