### ISSUE TITLE
IMAP connect:  NOT OK(Login failed for x@x.x against localhost from x.x.x.x. Could not connect to ssl://localhost:993: Unknown reason)

### ISSUE THREAD

**Issue by Noxillio** [roundcube/roundcubemail#8530]
When testing IMAP in the end stage of the installation I receive an error. I have an error while testing SMTP as well, but it is a different error and I have placed that in a separate issue.

```
IMAP connect:  NOT OK(Login failed for x@x.x against localhost from x.x.x.x. Could not connect to ssl://localhost:993: Unknown reason)
```
(First set of x's is my email address, second set is my own IP address from my home where I am performing the installation remotely)

That's all I get. My current setup works fine when sending and receiving from my phone using this mail account. Please advise.

**OS**: Windows Server 2022
**Web Server**: IIS 10
**PHP Version**: 8.0.0 (x64, NTS, VS19)
**Mail Server**: hMailServer 5.6.8-B2574

If other information is needed, please let me know.

**Comment by alecpl** [comment]
Probably some SSL issue. Try with:
```
$config['imap_conn_options'] = [
   'ssl' => [
      'verify_peer'  => false
   ]
];
```
