### ISSUE TITLE
Picklist does not display new message indication

### ISSUE THREAD

**Issue by wbiehl** [roundcube/roundcubemail#8531]
In the list of message display options in the group by subject option, the location or indication in which grouped message a new message is is not displayed.

**Comment by alecpl** [comment]
I don't understand. Maybe some screenshot?

**Comment by wbiehl** [comment]
Of course, the additional icon I want to remove is highlighted in the 
attachment.

---

Willians Biehl

Comercial,

TotalMail

  		Email:
  		***@***.***

  		Website:
  		https://www.totalmail.com.br

  		Phone:
  		+55 (48) 99921-8900

  		Address:
  		Cônego Miguel Giacca, Nova Veneza, SC

Em 17/05/2022 16:43, Aleksander Machniak escreveu:

> I don't understand. Maybe some screenshot?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you are subscribed to this 
> thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/roundcube/roundcubemail/issues/8531#issuecomment-1129250176
[2]

**Comment by alecpl** [comment]
The attachment didn't pass through.

**Comment by alecpl** [comment]
No feedback.
