### ISSUE TITLE
On smaller screens (1366 x 768), the folder pane is hidden so drag-n-drop to a folder is no longer possible

### ISSUE THREAD

**Issue by RalfJung** [roundcube/roundcubemail#8532]
One of my users has an older laptop with a resolution of 1366 x 768. Since a recent roundcube update that I installed, they can no longer use drag-n-drop to conveniently move an email to a different folder: the folder pane is not shown any more. It used to be shown in earlier versions of roundcube.

It is possible to make the folder pane reappear on screens of that size, so that users can sort mail via drag-n-drop again?

I currently have roundcube 1.5.2 installed.

**Comment by alecpl** [comment]
Three columns UI is available > 1200 px, so I can't confirm that.

**Comment by RalfJung** [comment]
Ah, turns out the browser window was not quite maximized. After maximizing it, the folder pane appears. Sorry for the noise and thanks for the help!
