### ISSUE TITLE
Slow login due to caldav plugin - takes  50+seconds

### ISSUE THREAD

**Issue by johnjaylward** [roundcube/roundcubemail#8533]
Installed via Mail-in-a-box, so I'm not sure what version I have (maybe 1.5.2 if I'm reading the logs correctly), but I tested the login process using the debug logging and found disabling the CalDav plugin resolves the issue.

Slow page load (Firefox Debugger. Example 44+seconds for initial login >60 sec for full page load)

![image](https://user-images.githubusercontent.com/383703/168661016-0ef5ba61-d17d-456a-bd17-2d4561f992d7.png)

In the imap.log debug log, I did see a delay, but it didn't seem relevant to the issue with caldav:

![image](https://user-images.githubusercontent.com/383703/168661275-94bc3ae8-2bda-4d38-bf64-d41919a7c57d.png)

In the sql.log file, the main slowdown appears to be the initial read from the caldav address books for the user:

![image](https://user-images.githubusercontent.com/383703/168661830-e8c261e6-1d2b-415a-b870-50563a947b20.png)

however, after the inital login, that query doesn't appear to be an issue anymore:

![image](https://user-images.githubusercontent.com/383703/168661772-63cb2481-b724-446f-9345-ce9ceebb97ed.png)

Log out, then back in I can reproduce the problem every time accross multiple users.

DB backend is Sqlite

**Comment by alecpl** [comment]
Maybe sqlite is the issue. We do not support external plugins here.
