### ISSUE TITLE
Roundcube Webmail 1.4.13 didn't fix Cross-site scripting (XSS) issue

### ISSUE THREAD

**Issue by mynameisfreedom** [roundcube/roundcubemail#8535]
This issue still happens, maybe in some different format.

Attackers are able to add sieve redirect/forward rules remotely. 

I am not sure how exactly they do it, but if I remove redirect/forward filter rules inside the Roundcube account, they add the rules just with simple email sending. 

The only solution I had left is to turn off webmail completely.

**Comment by alecpl** [comment]
With this level of information we'll not be able to do anything about this.

**Comment by mynameisfreedom** [comment]
Hi, @alecpl, I am aware of that, but I had to inform you. Email forwarding is a base for a super dangerous scam. 

Please, tell me what info would you need. It is super hard to catch what hackers are doing. I have their emails where they forward messages, and I have hundreds of their servers from where they send messages. 

Would something from the Email log help?

**Comment by alecpl** [comment]
I need a copy of the email message that is triggering the XSS issue. What makes you think this is an XSS issue? From the description it can be anything.
