### ISSUE TITLE
HTML email title tag content displayed in the body if contains HTML tags

### ISSUE THREAD

**Issue by ArkadiiVodolazskyi** [roundcube/roundcubemail#8540]
PHP version: **7.4.22 (Supports 64bit values)**
Mail server: **WPMailSMTP 3.4.0 for Wordpress**
Browsers: **Chrome 101 / Edge 101**
Operating systems: **Windows 10 / Pop!_OS 22.04**
Roundcube version: **1.5.2**
Roundcube plugins: **archive 3.5, filesystem_attachments 1.0, jqueryui 1.12.0, managesieve 9.4, newmail_notifier 0.8, zipdownload 3.4**.

How to reproduce:
- (using Wordpress 5.9.3 with plugins WPMailSMTP 3.4.0 and Newsletter 7.2.3+)
- create newsletter with any emoji in the title, send
- open in Roundcube client
- see **email title being output as plain text at the beginning** of an email

As I can understand there is some kind of unexpected parsing result while trying to output email data. 
Could you tell what can cause the issue?

Additional notices:
- the issue does not exist while not using emoji
- the same issue was noticed in Walla email client

Attachments:
- email [screenshot](https://user-images.githubusercontent.com/49953024/170034782-b8c3ce27-0038-4db1-9ed7-16dcd28af4dd.png), representing the issue
- [source_email.txt](https://github.com/roundcube/roundcubemail/files/8762648/source_email.txt)
- [email_headers.txt](https://github.com/roundcube/roundcubemail/files/8762714/email_headers.txt)

If logs are important to solve the issue, they will be provided separately as I don't have direct access to the Roundcube settings.

![image](https://user-images.githubusercontent.com/49953024/170034782-b8c3ce27-0038-4db1-9ed7-16dcd28af4dd.png)

**Comment by alecpl** [comment]
I'd need to see the full message source (not the html code of the page output).

**Comment by ArkadiiVodolazskyi** [comment]
[source_email_full.txt](https://github.com/roundcube/roundcubemail/files/8764076/source_email_full.txt)

**Comment by alecpl** [comment]
The html part contains this:
```
<title>לפתוח את הוויקנד עם 2 מוצרים במתנה<img src="https://s.w.org/images/core/emoji/13.1.0/72x72/1f381.png" alt="🎁 " class="wp-smiley"style="height: 1em; max-height: 1em;" /> את כבר שם ?? | פרסומת</title>
```
I'd say an image inside title is not allowed according to the html standard. 

Normally we remove the title from the content before we parse it, but because of the `<img>` tag this part does not work. So, the fix should actually be quite simple.

**Comment by alecpl** [comment]
Fixed.
