### ISSUE TITLE
Current HEAD: composer.json version issues for php8.1

### ISSUE THREAD

**Issue by rivimey** [roundcube/roundcubemail#8541]
I git-clone'd the current HEAD and found some issues with the composer.json file; it still includes the ext-php must be less than 7 constraint, despite the recent release notes saying php8.1 is now supported.

Having changed ext-php to include 8.1, there are a number of package updates that also must be updated to work with 8.1.

However, after doing this, I am still getting  WSOD (HTTP 500) for my site, but can't see any error messages in logs. Still working on that.

**Comment by alecpl** [comment]
It is ">=7.3"
https://github.com/roundcube/roundcubemail/blob/50992b9fc74966336419fd59276f969200731c81/composer.json-dist#L12
