### ISSUE TITLE
vacation reply

### ISSUE THREAD

**Issue by dtech4you** [roundcube/roundcubemail#8542]
As is the install works sends email and receives  email as well, my problem is I want when a filter auto responds to an incoming email. right now it creates a new thread. What I would like is when a the filter receives a email that meets criteria that it does a reply with same thread rather than new. if there is a way currently to do this i could not figure it out, if its a matter of paying someone to write code for this please comment and or reply.

**Comment by alecpl** [comment]
That part of the system is not controlled by Roundcube. The email is being send by the mail server.

**Comment by dtech4you** [comment]
I am really just asking for help and was hopping I could pay someone here to help me with it.

**Comment by dtech4you** [comment]
price would be $200USD kinda a bounty if you will.

**Comment by dtech4you** [comment]
https://i.imgur.com/9bvferI.png

I just wanted a option added here to do a reply. I am not really knowledgeable enough about the setup to know everything and how it works.
