### ISSUE TITLE
"Send" doesn't work on reply to email to undisclosed recipients

### ISSUE THREAD

**Issue by dseomn** [roundcube/roundcubemail#8543]
Roundcube: 1.4.13
jqueryui: 1.12.0

In my Sent folder, I have an email with the header `To: niet-openbare ontvangers: ;` (i.e., undisclosed recipients) and a Bcc header with the actual recipients. If I click reply all, add a Bcc header to the reply with the recipients I want, and click send, nothing happens. This shows up in the console though:

```
Uncaught TypeError: Cannot read properties of null (reading 'length')
    at rcube_check_email (common.js:453:24)
    at rcube_webmail.check_compose_address_fields (app.js:4904:10)
    at rcube_webmail.check_compose_input (app.js:4857:15)
    at rcube_webmail.command_handler (app.js:1253:58)
    at rcube_webmail.command (app.js:795:18)
    at HTMLButtonElement.onclick (?_task=mail&_action=compose&_id=411292027629120ef4ecc6:920:205)
```

Edit: If I remove `niet-openbare ontvangers:` from the `To` field of the reply, the send button works normally.

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/blob/282f0a2830576932ab8e089d88c93b0f177af3ca/program/js/common.js#L460

`input.match(rx)` can return null if there are no matches, so indeed we should check the result first. I.e. 
```diff
--- a/program/js/common.js
+++ b/program/js/common.js
@@ -456,8 +456,10 @@ function rcube_check_email(input, inline, count, strict)
       rx_flag = count ? 'ig' : 'i',
       rx = inline ? new RegExp('(^|<|'+delim+')'+addr_spec+'($|>|'+delim+')', rx_flag) : new RegExp('^'+addr_spec+'$', 'i');
 
-  if (count)
-    return input.match(rx).length;
+  if (count) {
+    var re = input.match(rx);
+    return re ? re.length : 0;
+  }
 
   return rx.test(input);
 };

```
but this might be only part of the solution.

**Comment by alecpl** [comment]
Also, it needs to be noted that `To: niet-openbare ontvangers: ;` is invalid according to RFC2822. A space is not allowed in a group name.

**Comment by dseomn** [comment]
> Also, it needs to be noted that `To: niet-openbare ontvangers: ;` is invalid according to RFC2822. A space is not allowed in a group name.

That was obsoleted by RFC5322, and the space looks valid to me. Using the definitions below, I think `niet-openbare` and `ontvangers` are both `1*atext` in `atom`. The space between them is `[CFWS]` in one of the two `atom`s, which are joined together in `1*word` in `phrase` in `display-name`.

https://datatracker.ietf.org/doc/html/rfc5322#section-3.4:

```
group           =   display-name ":" [group-list] ";" [CFWS]
display-name    =   phrase
```

https://datatracker.ietf.org/doc/html/rfc5322#section-3.2.5:

```
phrase          =   1*word / obs-phrase
word            =   atom / quoted-string
```

https://datatracker.ietf.org/doc/html/rfc5322#section-3.2.3:

```
atom            =   [CFWS] 1*atext [CFWS]
```

**Comment by alecpl** [comment]
This is not how I understand it. `[CFWS]` (a space and/or comment) is allowed at the end or start of the `display-name`. So, it is not allowed in the middle. `display-name` is one word only. If you have a space in the group name `quoted-string` should be used.

**Comment by alecpl** [comment]
I'm unable to reproduce the issue using git-master and 1.4 is not supported. So, I'm going to apply my proposed patch and ignore anything else here (as groups are anyway not supported).
