### ISSUE TITLE
Particular user db in Home folder

### ISSUE THREAD

**Issue by imsahiraf** [roundcube/roundcubemail#8548]
I am trying to make db for every particular mail in user folder but when I use getenv('HOME') and getenv('_RCUBE') it shows me unable to connect with db.

This is how I use it 
$config['db_dsnw'] = 'sqlite:///' . $_SERVER['HOME'] . '/etc/' . $_SERVER['_RCUBE'] . '.rcube.db?mode=0600';
$config['db_dsnw'] = 'sqlite:///' . getenv('HOME') . '/etc/' . getenv('_RCUBE') . '.rcube.db?mode=0600';

 In both the way I had tried.

If is there any other way then guide me I am new here.

**Comment by alecpl** [comment]
Ask on mailing list or forum.
