### ISSUE TITLE
Cannot save contact error when pressing Always allow from button on a message from a sender I am happy with

### ISSUE THREAD

**Issue by antonical** [roundcube/roundcubemail#8553]
Version 1.5.2
Ubuntu 20.04 

When I display a message that has content. RC rightly blocks resources and puts a message above the content with "To protect your privacy remote resources have been blocked." But give me the option to Allow (session based) or Always allow from button. However when I press the always allow from button I get an error saying.

Could not save the contact address. 

Apache access shows:

` "POST /webmail/?_task=mail&_framed=1&_action=addcontact HTTP/1.1" 200 1367 "https://mydomain/roundcube/?_task=mail&_caps=pdf=1,flash=0,tiff=0,webp=1,pgpmime=0&_uid=21&_mbox=INBOX&_framed=1&_action=preview" `
 
 There is nothing shown in the Apache error log

If I press the Allow button it shows the remote resources. But is not persistent.

Any help is appreciated as this is annoying.

I tried this on multiple domains with RC installed. I have the same error.

Cheers
Tony

**Comment by alecpl** [comment]
Does it happen for all email addresses? Maybe the email is invalid somehow? Can you provide content of the POST request?

**Comment by antonical** [comment]
The POST is in the text above. If that is not it then not sure what to provide you or how to provide it. Yes, it happens for all email addresses.

The error I get is exactly as described above. Allow shows the content and the error but is not persistent. Allow always shows the content and error and is not persistent

Cheers
Tony

**Comment by alecpl** [comment]
You posted the URL, not the content (body) of the request. You should be able to see this is the browser console. What addressbooks are you using? What plugins? Could you screenshot your addressbook preferences?

**Comment by ThomasCr** [comment]
Maybe the same error like in #8585
