### ISSUE TITLE
TinyMCE wrong parameter name (and proposal on the content)

### ISSUE THREAD

**Issue by szekeresa** [roundcube/roundcubemail#8555]
https://github.com/roundcube/roundcubemail/blob/ca264770fd14ce614a3d1ce03676116dd691b051/program/js/editor.js#L63

Correct name is: **paste_webkit_styles**  _(there is an "s" at the end)_

Ref: https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_webkit_styles

Proposed: `paste_webkit_styles: "color font-size font-family font-weight background-color"`
_(new values: font-weight background-color)_

**Comment by alecpl** [comment]
Fixed.
