### ISSUE TITLE
Use "to" address as "from" address when replying

### ISSUE THREAD

**Issue by thrdroom** [roundcube/roundcubemail#8556]
There should be a usersetting inside roundcube to use the "to" address as "from" address when replying.

This would be useful for users who use catch all addresses and use different addresses for different services. When I reply to an email it always changes to my default address (myname@mydomain.com). When I receive an email to servicename@mydomain.com I want to reply with the from address being servicename@mydomain.com, not myname@mydomain.com. I can edit the address manually, but sometimes I forget and I end up sending replies with myname@mydomain.com. servicename can be variable per email.

Current problematic situation:

1. Receive email incoming to servicename@mydomain.com
2. Reply from address should be myname@mydomain.com

New wanted situation:

1. Receive email incoming to servicename@mydomain.com
2. Reply from address should be servicename@mydomain.com

For reference, this option for example is built into thunderbird for a while now.

![065RFJJ](https://user-images.githubusercontent.com/5912061/172172218-3f41e39b-cedc-4aaa-8013-0e082543e216.png)

1. Go to Account Settings
2. Enable Reply from this identity when delivery headers match
3. Enter your domain prefixed by a wildcard (*), for example *@yourdomain.com
4. Close/confirm all your changes
5. Open an email that was sent to one of your catch-all addresses and click the reply button.
6. The FROM field should be the catch-all address and not your general address.

---
Related forum thread from 2009: [https://www.roundcubeforum.net/index.php?topic=4760.0](https://www.roundcubeforum.net/index.php?topic=4760.0)

**Comment by alecpl** [comment]
It's still not clear to me, but I've found https://bugzilla.mozilla.org/show_bug.cgi?id=1518025 so it may help.

A different approach is https://github.com/r3c/custom_from.

**Comment by bobemoe** [comment]
I am also looking for this functionality for the exact same use case.

My current workaround is based on the fact that the "to" address is used as the "from" address when replying **IF** it exists as an identity.  I have a script that extracts all the addresses I use (can be found in the From field on the items in my Sent box) and adds them as identities. The downside of this is I now have several hundred identities! 

Thanks @alecpl for the custom_from plugin it will be very useful for me, but doesn't solve the issue of having it populated automatically with the correct address.

**Comment by bobemoe** [comment]
Actually, I take back my previous comment. I've just tried "custom_from" plugin and it works perfectly solving this exact issue :)

**Comment by thrdroom** [comment]
> A different approach is https://github.com/r3c/custom_from.

_When replying to an e-mail sent to you through an address not in your identities list, plugin will automatically fire and set "From:" header to the address the original e-mail was sent to._

Perfect, the **custom_from** plugin does exactly what i needed.
