### ISSUE TITLE
Database upgrade failed: could not translate host name

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#8558]
I upgraded from 1.4.13 to 1.5.2 on Ubuntu 20.04 with the provided upgrade script and the files were copied fine. But now the installation is not operational because the database upgrade failed:

```
Running update script at target...
Executing database schema update.
ERROR: SQLSTATE[08006] [7] could not translate host name "dbname=web001_rcm" to address: Name or service not known
ERROR: Failed to connect to database
All done.
```

The bin/upgrade.sh script in the target directory has the same problem. I'm using a local Postgres database that has worked fine until now.

What should I do? The UPGRADE file doesn't handle this and the manual upgrade doesn't cover database issues. This is a critical error because everything is now broken and the service is unusable. I shouldn't have upgraded from an "LTS" version.

**Additional information:**

Here is the only database-related entry from my configuration file:

```
$config['db_dsnw'] = 'pgsql:///web001_rcm';
```

I haven't touched that file and it has worked fine. Looks like the new version has an undocumented breaking change that requires unknown work here.

**Comment by alecpl** [comment]
Might be a regression indeed. Here's some examples for the DSN syntax that should work:
```
//$config['db_dsnw'] = 'pgsql://user@tcp(localhost:5432)/roundcubemail';
//$config['db_dsnw'] = 'pgsql://user@unix(/var/run/postgresql)/roundcubemail';
//$config['db_dsnw'] = 'pgsql://user:pass@localhost/roundcubemail';
```

**Comment by ygoe** [comment]
I found the documentation for it. This works:

```
'pgsql://unix(/run/postgresql)/DBNAME'
```

But my original setting scheme is also mentioned for MDB2, so it's Roundcube that also tries to parse it and fails.

**Comment by alecpl** [comment]
Fixed.
