### ISSUE TITLE
unable to initialise database 

### ISSUE THREAD

**Issue by sakumo99** [roundcube/roundcubemail#8561]
I am having this issue with roundcube
![erro](https://user-images.githubusercontent.com/107371256/173254266-b5a88413-e92a-4ab0-9620-da73f9288de4.PNG)

**Comment by alecpl** [comment]
What version? Are you installing or upgrading? Did you read INSTALL file instructions?

**Comment by sakumo99** [comment]
> What version? Are you installing or upgrading? Did you read INSTALL file instructions?

I dont really know, can you tell me how am I able to verify it?
I was following some guide on youtube but theres where some steps that were very confusing so I lost my self a little

**Comment by alecpl** [comment]
Ask on mailing list or forum.
