### ISSUE TITLE
Enigma:  Settings->Preferences->Encryption->"Sign all messages by default" controls several settings in Compose window

### ISSUE THREAD

**Issue by githubgrscporg** [roundcube/roundcubemail#8565]
Starting with 1.6-rc, selecting Settings->Preferences->Encryption->"Sign all messages by default" results in all three of "Digitally sign this message", "Encrypt this message", and "Attach my public key" being selected in any Compose window.  I can still send signed, but un-encrypted email (without attached public key) by deselecting "Encrypt this message" and "Attach my public key" in each new Compose window.

Deselecting Settings->Preferences->Encryption->"Sign all messages by default" results in Compose windows with none of "Digitally sign this message", "Encrypt this message", nor "Attach my public key" selected.

As for Settings->Preferences->Encryption->"Encrypt all messages by default" and Settings->Preferences->Encryption->"Attach my public PGP key by default", it appears that their selection or non-selection has no bearing on the items selected in a Compose window.

Only Settings->Preferences->Encryption->"Sign all messages by default" seems significant, and it seems to control all three of the selections in Compose windows.

For comparison, these settings appear to work properly in 1.6-beta.

**Comment by githubgrscporg** [comment]
I am running this on a regularly updated Debian/Bullseye system, and have installed roundcube from roundcubemail-1.6-rc-complete.tar.gz

**Comment by alecpl** [comment]
Fixed.

**Comment by githubgrscporg** [comment]
I agree this is fixed.

I've tried several permutations of these settings, and everything appears to be in order -- this using roundcube from git-master from yesterday.
