### ISSUE TITLE
1.6 RC Message: Oops... something went wrong!

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#8567]
When i load RC 1.6-rc and click the first message, i get a error message:
![image](https://user-images.githubusercontent.com/14041522/173537869-477fc80e-fa65-4ab1-b0fe-b6ac1756f5fb.png)

If i click another e-mail for preview, the preview is loaded without any error. If i now click the faulty mail again, this works also. There is no error in the logfiles. The only thing i can see is this error in dev console of the browser (in this case Microsoft Edge):

![image](https://user-images.githubusercontent.com/14041522/173537322-499b92fb-3131-436e-9b6a-0f0c406d5c91.png)

**Comment by Offerel** [comment]
The problem occurs in the Inbox, but it may have something to do with a mail in the Drafts folder. After deleting a mail there, the problem no longer occurs in the Inbox or other folders. Before this was the case after every reload (reload without cache).

**Comment by Offerel** [comment]
It seems, im wrong. The error still exists. At the time when i get the message, i see the following in the dev console:
![image](https://user-images.githubusercontent.com/14041522/173559911-7c2bce51-30e6-4795-bd8f-a4f51f61625b.png)

Again, there is no error in the logfiles at the server

**Comment by alecpl** [comment]
There should be something in Roundcube logs directory. If not something's wrong with log configuration.

**Comment by Offerel** [comment]
It seems i have finally found the reason for that. I use RCMCardDAV with Roundcube to get contacts from SabreDAV. In RCMCardDAV is a dependency to GuzzleHttp what wasn't working with RC 1.6. After manually inserting a newer GuzzleHttp version in to the plugin, the message is gone completely. I have opened a issue on the plugin GitHub repository at https://github.com/mstilkerich/rcmcarddav/issues/385 
For me, this issue is solved. @alecpl : Feel free to close here.
