### ISSUE TITLE
Outdated Net_LDAP3 in Roundcube 1.6.0 RC

### ISSUE THREAD

**Issue by smsoft-ru** [roundcube/roundcubemail#8573]
The package of Roundcube 1.6.0 RC includes outdated version of Kolab Net_LDAP3 (in vendor/kolab directory). This version incorrectly works with PHP8: produces some "deprecated" messages to error log, and not able to establish connection with LDAP server.
Replacing two files: LDAP3.php and Result.php with corresponding ones from Kolab github site fixes this problem.

**Comment by alecpl** [comment]
The mirror at https://gitlab.com/roundcube/net_ldap3 was missing the v1.1.4 tag. This is fixed now.
