### ISSUE TITLE
Interal Server Error on RC (Appears to be a typo)

### ISSUE THREAD

**Issue by jbodycott** [roundcube/roundcubemail#8579]
Good morning,

After upgrading from the beta to the rc, I began to receive a server error when logging in with the following in the logs:

mail roundcube: PHP Fatal error:  Declaration of rcmail_output_json::command($cmd, ...$args) must be compatible with rcmail_output::command() in /opt/www/roundcubemail-1.6-rc/program/include/rcmail_output_json.php on line 100

Checking the commit (https://github.com/roundcube/roundcubemail/commit/fa65a683893f07eb9145472d08e234794bda5624), there appears to be a typo between the ellipsis (...) and $args leading to the error.  Removing this in my environment fixes the issue.  Thanks for all your hard work!

**Comment by alecpl** [comment]
Strange that it worked for me. Fixed.
