### ISSUE TITLE
drag and drop Adress from to: to cc:

### ISSUE THREAD

**Issue by tlrm-c** [roundcube/roundcubemail#8580]
Not urgent idea for further development:
If I reply to an email with multiple recipients, it would be useful if I could drag and drop people between To: to CC: and vice versa. Thank you all for the best webmail solution ever!

**Comment by alecpl** [comment]
It is possible in Elastic skin since 1.5. However, I just noticed there's some style issue (using git-master). So, we'll have to fix that.

**Comment by alecpl** [comment]
Fixed.
