### ISSUE TITLE
Copyright version at the bottom of the page is outdated

### ISSUE THREAD

**Issue by r0xANDt0l** [roundcube/roundcubemail#8582]
It says its 2021, but it's already 2022![Screenshot_2022-06-19-16-45-59-41_3aea4af51f236e4932235fdada7d1643.jpg](https://user-images.githubusercontent.com/41841903/174486766-1551f2a6-979d-412d-bdb2-49f834fb5e47.jpg)

**Comment by alecpl** [comment]
I removed the year.
