### ISSUE TITLE
Feature request: implement archive folder as other special folders (+ the archive button)

### ISSUE THREAD

**Issue by jiriks74** [roundcube/roundcubemail#8583]
Hi,
I'm switching to Roundcubemail from Rainloop as that one is basically not maintained anymore. So far I love how Roundcube works. I've added a plugin called [`ident_switch`](https://bitbucket.org/BoresExpress/ident_switch/src/master/) so that I could have multiple email accounts, like in rainloop, and added some other plugins for context menu, desktop notifications, etc...

Now to the problem/feature request:
The plugin [`ident_switch`](https://bitbucket.org/BoresExpress/ident_switch/src/master/), as I said, allows me to use multiple email accounts from different providers. The plugin supports saving special folders for each account and that works flawlessly. But when it comes to archive folder it does not work. the current archive plugin pulls the archive folder name from the server's email config (main email), not the email that is currently selected through [`ident_switch`](https://bitbucket.org/BoresExpress/ident_switch/src/master/). Because of this when I click archive the plugin creates a new folder that it moves emails into instead of using the one I selected. It uses the name selected on the main email.

The problem is that as it's a plugin [`ident_switch`](https://bitbucket.org/BoresExpress/ident_switch/src/master/) cannot change folder names as it does with other special folders.

Implementing the Archive folder as another special folder directly in the server would probably solve this as the [`ident_switch`](https://bitbucket.org/BoresExpress/ident_switch/src/master/) plugin would be able to provide custom name for the archive folder as it does for other special folders.

Would something like this be possible?

I'd try to help. bud I don't know php, so I'd be probably more trouble than help

**Comment by alecpl** [comment]
I think this might not be that easy. And as we do not support ident_switch plugin here I'll close the ticket. If you provide a pull request we'll consider.

**Comment by jiriks74** [comment]
@alecpl Ok, I understand that. But in that case I'd like to ask whether it would be possible to reopen this and tag this as `help wanter` (or something simmilar).  

I'll try to learn something about php and look into how special folders work. Hopefully I'll be able to figure out how to implement it in a way that would allow plugins to serve custom special folder names.
