### ISSUE TITLE
Invalid email address 

### ISSUE THREAD

**Issue by ThomasCr** [roundcube/roundcubemail#8585]
Hi,
I am using RC in Version 1.5.2 and want to permanently allow resources from a mail address.

But when I hit the button for it, I get a error that says that the mail address is invalid.

The address is info@lieferung.mediamarkt.de

I have seen that there was already a report #7935 where the problem was already discussed and resolved.

But I am getting the same error...?

Any idea?

Thanks in advance

Thomas

**Comment by alecpl** [comment]
I'll say the same as in the referred ticket. You have email_dns_check=true set, and this domain does not exist

**Comment by ThomasCr** [comment]
I expected that the independent trust list would not be checked against dns?! It should be a exception there. Or only check dns at sending mails!
