### ISSUE TITLE
Y'all I need major help

### ISSUE THREAD

**Issue by thisplatformisnotuserfriendlybooooo** [roundcube/roundcubemail#8586]
The company I work for uses Roundcube webmail. I've gone down the rabbit hole of trying to contact them. I am not a coder, I am not here to understand coding, I just need help figuring out why my email has a server error. I do not feel like I should have to figure out this issue on my own as I would like to just be a user not tech support for myself. But anyway.... Below is my issue....

As I'm typing an email a box will pop up saying, "server error!". I am able to close the box and continue typing BUT I'm unable to send the email. I then have to refresh the page which then I have to log back in. I send/receive a ton of files, I have to reattach each file, re-enter the correspondents and then retype the email. It takes forever to do and often times I have to do this multiple times. I'm loosing it!! Please help!

**Comment by alecpl** [comment]
Ask on the support forum, please.
