### ISSUE TITLE
newmail_notifier desktop-notification

### ISSUE THREAD

**Issue by asaage** [roundcube/roundcubemail#8587]
It would be nice to see the subject and sender in the desktop notification (as requested in https://github.com/roundcube/roundcubemail/issues/8360).

Other improvements like an updated logo and sound select-options would also be nice (https://github.com/roundcube/roundcubemail/issues/7826).

**Comment by alecpl** [comment]
So, why a new ticket?

**Comment by asaage** [comment]
> So,` why a new ticket?

- one is labeled as bug and you didn't say anything about point 3.
- the second one: i just found that while writing
- so i can work on it if i have some time to spend

**Comment by alecpl** [comment]
Added to the list in #7826.
