### ISSUE TITLE
Cannot sort on Starred emails

### ISSUE THREAD

**Issue by ShuggMcGlummfer** [roundcube/roundcubemail#8589]
To show only those emails that match pre-set unique criteria you can use the drop-down box which has things like All, Unread. Flagged and so on. You can also go to some columns and sort them there within the overall list. There is, however, no way to select out the Starred emails so they are at the top (or bottom, I suppose) as the click on at the column header is not active. Starred is also not an option within the drop-down box. The headers for Flagged & Attachments are similarly inactive, although you can still use the drop-down instead for those.

So, what we need is for the column header for sort Starred, Flagged and Attachments to be active. Similarly, Starred needs to be in the drop-down box so they can be viewed uniquely.

**Comment by alecpl** [comment]
Sorting by these is not easy because it cannot be done with a single SORT command. It's also not that common, so I don't think we'll spend time on this. Pull requests welcome.

Also, there's no "Starred" in Roundcube, there's only "Flagged" (which in many clients means the same).

**Comment by ShuggMcGlummfer** [comment]
Ah, I've assumed that the * (star) symbol that Roundcube shows in the email was for Starred, but it's actually Unread. Sorry about that. Still as shame that you can't click on the column.
