### ISSUE TITLE
1.6rc: cli tools fail to run

### ISSUE THREAD

**Issue by downtownallday** [roundcube/roundcubemail#8593]
As an example: `bin/msgimport.sh` reports:

```
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /usr/local/lib/roundcubemail/program/lib/Roundcube/bootstrap.php:86
Stack trace:
#0 /usr/local/lib/roundcubemail/program/include/iniset.php(78): require_once()
#1 /usr/local/lib/roundcubemail/program/include/clisetup.php(25): require_once('...')
#2 /usr/local/lib/roundcubemail/bin/msgimport.sh(20): require_once('...')
#3 {main}
  thrown in /usr/local/lib/roundcubemail/program/lib/Roundcube/bootstrap.php on line 86
Fatal error: Please check the Roundcube error log and/or server error logs for more information.
```

**Comment by downtownallday** [comment]
Should add that php is version 8.1.7 (from Ubuntu 22.04 Jammy)

**Comment by alecpl** [comment]
Looks like missing php's `mbstring` extension.

**Comment by Muncubus** [comment]
The same issue on 18.04 ...
PHP 8.2.5 (cli) (built: Apr 14 2023 04:26:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies

php-mbstring/bionic 1:7.2+60ubuntu1 all
php-symfony-polyfill-mbstring/bionic 1.6.0-2 all
php7.2-mbstring/now 7.2.34-38+ubuntu18.04.1+deb.sury.org+1 amd64 [установлен, локальный]
php8.0-mbstring/now 1:8.0.28-1+ubuntu18.04.1+deb.sury.org+1 amd64 [установлен, локальный]

**Comment by alecpl** [comment]
Pay attention to the numbers. You're running PHP 8.2.5 (in cli), yet you don't have php8.2-mbstring package installed.

**Comment by Muncubus** [comment]
Thanks. Due I can not find 8.2mbstring for 18.04... I have switch to php8.0 and all worked fine.
