### ISSUE TITLE
Button allow remote resources - broken link

### ISSUE THREAD

**Issue by rubenschulz** [roundcube/roundcubemail#8595]
When I open an e-mail with remote images in it, I get a notification that the images are blocked and a button to allow it.
When I click the button, the link goes wrong and the homepage of my website is displayed.

RoundCube is installed in the folder `/webmail`
When the link is clicked this folder seems to go missing, and the page is redirected to `/`, which is the website homepage.

I am using DirectAdmin with Custombuild to manage RoundCube, I have seen this behaviour on multiple VPSses.

**Comment by alecpl** [comment]
This sounds familiar. What version?

**Comment by alecpl** [comment]
Sounds like #8170, i.e. upgrade to 1.6 or change the referrer-policy.
