### ISSUE TITLE
Problem in mobile/tablet version 

### ISSUE THREAD

**Issue by lusitec** [roundcube/roundcubemail#8599]
When we click on the burger menu, the page is frozen and you cannot click inside the menu.

We can not access "Compose", "Mails", "Contacts" etc.

The problem happens in the mobile/tablet version.

Screenshot below is in the Portuguese version.

![20220628_220232](https://user-images.githubusercontent.com/57853525/176307939-dfd1722f-6b48-4e71-9fb8-40d403ac21f0.png)

**Comment by alecpl** [comment]
See #8557. Looks like calendar plugin issue.
