### ISSUE TITLE
Mobile phone issues with update Continued

### ISSUE THREAD

**Issue by Lav1d** [roundcube/roundcubemail#8601]
Sorry but alecpl's comment was not what I asked; I don't have problems accessing my emails. What I asked was.......

Tried using my Webmail on my phone which uses the Roundcube program and though **_I could access my emails_**, I couldn't use any of the functions in the menus as they are showing but dim and don't work. I can't use **_Select, Move, Delete_** or any other function and in the other menu **_I can't Log off_**.
Please advise what I can do to fix this on my Android mobile phone because I now have to use my computer instead to access the menus to move, delete etc as well as log off.
I use my Android mobile phone daily instead of my computer so this is an issue.

As mentioned this isn't a problem with accessing my emails. It's a change in the program after the update which doesn't allow access to the menus. Please re read my posting in this context and your help is appreciated.
Thanks

**Comment by alecpl** [comment]
We can't help you here. This is a known bug with calendar plugin, as it was mentioned in another ticket. Please, don't spam us.

**Comment by Lav1d** [comment]
Sorry Alecpl but I was asking for help and I don't spam anyone. Shame you couldn't help.
