### ISSUE TITLE
Bug in "Options" dropdown button for attachments

### ISSUE THREAD

**Issue by rc-pl** [roundcube/roundcubemail#8602]
Tested on 1.6 RC

1. Click "Compose new message"
2. Add an attachment to it
3. Click on "Options" dropdown button for attached file
4. Delete attachment
5. Add new attachment - "Options" dropdown button doesn't work anymore

**Comment by alecpl** [comment]
Strange. I was able to reproduce it once, but not anymore.

**Comment by alecpl** [comment]
Ok, the trick is to have the Options menu open when clicking Delete. It looks that for some reason the `#attachmentmenu` element is being removed from the page. No solution yet.

**Comment by alecpl** [comment]
Fixed.
