### ISSUE TITLE
Erro plugin managesieve

### ISSUE THREAD

**Issue by samueldietrick** [roundcube/roundcubemail#8607]
I'm using Roundcube Webmail 1.5.3, the php version I'm using is 7.4.

After installing the managesieve plugin I always get this error when trying to use it: https://prnt.sc/Hq9StJ37KIAg

**Comment by alecpl** [comment]
Check the Roundcube error log. In such cases there should be a more specific error message there.

**Comment by samueldietrick** [comment]
> Check the Roundcube error log. In such cases there should be a more specific error message there.

I managed to make the page appear, but it is giving an error when connecting to the server.
https://prnt.sc/DYspsJTH15PA

**Comment by alecpl** [comment]
And what do you see in the error log now? Looks like connection to managesieve server fails. Configuration issue.
