### ISSUE TITLE
feature request: subscribe multiple folders at once.

### ISSUE THREAD

**Issue by xxxmicrobexxx** [roundcube/roundcubemail#8608]
I am in the middle of importing mail for a customer.  There are hundreds (!) of folders.  When they are imported they are not subscribed by default.  I am having to go through the list and subscribe them manually which is tedious to say the least.

It would be a good feature to be able to "select all" folders and do a mass subscribe.

**Comment by alecpl** [comment]
Duplicate of #5090.
