### ISSUE TITLE
Messages from specifically "allowed" senders sometimes diverted to spam

### ISSUE THREAD

**Issue by sibelman** [roundcube/roundcubemail#8610]
Some, but not all, newsletters are getting shunted to spam from Letters from an American, https://heathercoxrichardson.substack.com/ 

Even specifically allowing E-mails from substack.com and postgun.com does not prevent this.  My ISP and I have tried to use "Allow" lists, but that has not fixed the issue.
[spamYES.txt](https://github.com/roundcube/roundcubemail/files/9078036/spamYES.txt)
[spamNO.txt](https://github.com/roundcube/roundcubemail/files/9078037/spamNO.txt)

My ISP now says it seems substack.com has been "black listed" by someone, citing this link:  
[https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a161.38.195.132&run=toolpage](https://mxtoolbox.com/SuperTool.aspx?action=blacklist:161.38.195.132&run=toolpage)
 
I'm hoping you can somehow persuade the relevant robot that these (admittedly quite political) newsletters are not spam.  I have more details, including headers from two successive days' messages, one blocked as spam and the other permitted (see attachments).
 
Best regards,
Steve Sibelman (sib@hevanet.com)

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
