### ISSUE TITLE
GuzzleHttp\Client:  NOT OK(Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle)

### ISSUE THREAD

**Issue by ichirugame** [roundcube/roundcubemail#8611]
If you have installed
GuzzleHttp\Client:  NOT OK(Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle)
Because it came out
composer require guzzlehttp/guzzle
composer require "roundcube/plugin-installer:>=0.2.0"
I ran, but it's still "GuzzleHttp\Client:  NOT OK(Failed to load class GuzzleHttp\Client from github.com/guzzle/guzzle)".
I also restarted the server, but it's the same.
What should i do?

**Comment by thatonedoseiai** [comment]
I also have the exact same issue. I tried a few Roundcube versions (1.5.1-1.5.3), and it had the same issue.
Currently running Ubuntu 20.04.4, PHP 8.1.7, Apache 2.4.41, guzzlehttp/guzzle 7.4.5, roundcube/plugin-installer 0.3.2, Composer 2.3.9, and I get the exact same errors. I've tried restarting PHP and Apache multiple times, including while trying different versions, and I've reinstalled everything that seemed relevant except for Apache and Ubuntu.

**Comment by alecpl** [comment]
I'm not sure what you're doing wrong, but if you just get the "complete" package of Roundcube it will be included.

Did you run the composer command in Roundcube's root directory? Does vendor/guzzlehttp/guzzle exist?

**Comment by thatonedoseiai** [comment]
I ran 'composer require guzzlehttp/guzzle' in the root directory or Roundcube and it worked. I couldn't find any documentation on where to install Guzzle or if it even mattered, so I just assumed it'd be like everything else, where you install it using a package manager, and it just works. Thank you so much.

**Comment by ichirugame** [comment]
`https://github.com/roundcube/roundcubemail/releases/download/1.5.3/roundcubemail-1.5.3-complete.tar.gz`No error when installing again with
