### ISSUE TITLE
Set default/primary key for for enigma plugins

### ISSUE THREAD

**Issue by adityaasoleh** [roundcube/roundcubemail#8612]
Hi,

I've multiple keys imported to enigma plugins , example : 
key id 1 : 12345
key id 2 : 67890

When trying to sign it always choose key id 1 (12345) for signing, how i can set to key id 2 (67890) for primary key by default ?
i've try to create gpg.conf on folder key user which set up on enigma config.inc.php, but its still choose key id 1 on roundcube 

Whether there's another setting for this to choose default/primary key ?

Thanks

**Comment by alecpl** [comment]
Enigma selects first key with current identity (email). There's no way to select another one. I'd say it's a rare use-case.
