### ISSUE TITLE
Multi line data:image URI's in emails are stripped from message display

### ISSUE THREAD

**Issue by dcegress** [roundcube/roundcubemail#8613]
In program/lib/Roundcube/rcube_washtml.php

The function wash_uri includes a check for the regex /^data:image\/([^,]+),(.+)$/i at line 427 (1.5.3)

This test fails when the base64 is split over multiple lines resulting in the image being removed from the rendered HTML.  

Removing the $ from the regex does make it work though.

**Comment by dcegress** [comment]
Looks like by default preg_match does not match line breaks with ',' unless the s modifier is used.  This change also fixed the problem.

preg_match('/^data:image\/([^,]+),(.+)$/is', $uri, $matches)

**Comment by alecpl** [comment]
Fixed.
