### ISSUE TITLE
Mobile navigability error

### ISSUE THREAD

**Issue by thiorte** [roundcube/roundcubemail#8614]
Friends yesterday I updated my cPanel & WHM v104.0.5 (STANDARD) where RoundCube is already native. After updating I noticed a navigability error in roundcube only on mobile.

Hug webmail on cell phone, in the right corner will appear 3 dots, click on it, on this screen it is not possible to browse, and when you click anywhere the screen closes.

I've already contacted cPanel and they gave me RoundCube support because it's not their native application.

Could support here let me know if they intend to upgrade Roundcube to a new version of whm/cpanel?

Thanks
![c7b24be2-b380-4e2c-9840-be33d84a1181](https://user-images.githubusercontent.com/1952394/178577470-33e17f86-ce16-4c6c-af14-84ab1629f79e.jpg)

**Comment by alecpl** [comment]
A known issue. Problem is with the calendar plugin. We can do nothing about it. Disable the plugin or try a newer version (of the plugin).

**Comment by thiorte** [comment]
Thanks for the answer. Excuse my ignorance, as I use cPanel, could you tell me how to remove calendar so Roundcube works correctly?

Thank you very much for your attention and help.

**Comment by thiorte** [comment]
Would it erase that line?
https://prnt.sc/dtrqFetpatpw
