### ISSUE TITLE
Problem using RoundCube on mobile devices

### ISSUE THREAD

**Issue by JohanBoshoffWebAware** [roundcube/roundcubemail#8615]
There is currently a problem when accessing Roundcube on mobile devices, including tablets and mobile phones.

When you read an email and want to forward the email, on the mobile device you need to click the three dots for the menu to forward.  When the menu opens, none of of the options are clickable.

This is on cPanel servers.

**Comment by alecpl** [comment]
I'm getting tired about this issue. Please, tell cPanel to disable calendar plugin, or update to a newer version.
