### ISSUE TITLE
Junk buttons missing?

### ISSUE THREAD

**Issue by Viss** [roundcube/roundcubemail#8616]
Attempting both a fresh install out of apt-get on ubuntu 22.04, and downloading the code from github, the buttons to mark a message as junk do not appear. 

The settings area does have the junk settings in it, but the main toolbar in the mail view doesn't have junk buttons. Not sure what needs to happen to enable them.

<img width="426" alt="image" src="https://user-images.githubusercontent.com/1756255/178799067-64461463-5b9d-4316-86bd-48c598b91b03.png">
<img width="533" alt="image" src="https://user-images.githubusercontent.com/1756255/178799153-ace49015-d2f5-4602-93a0-e8d8bc9949dd.png">

**Comment by codegain** [comment]
@Viss Have you enabled the `markasjunk` plugin in your config?

**Comment by Viss** [comment]
I had in a previous version, but it looks like in my efforts of trying different implementations of roundcube I overlooked this part with the fresh installations. Thanks for reminding me, this solved it!
<img width="625" alt="image" src="https://user-images.githubusercontent.com/1756255/179279026-765ab5fe-0c03-4a97-9022-a39f1b9bb032.png">
