### ISSUE TITLE
Problems with quoted-printable and base64 message content.

### ISSUE THREAD

**Issue by VasjaVI** [roundcube/roundcubemail#8620]
I installed roundcubemail according to this instruction - https://www.c-amie.co.uk/technical/installing-roundcube-webmail-under-iis-on-windows-server-2019/.
IIS 7.5, php-7.4.30, roundcubemail-1.5.3-complete.
1) If the message uses Content-Transfer-Encoding base64, then the code without decoding is displayed when viewed.
2) If the message uses Content-Transfer-Encoding quoted-printable (non-Latin characters, such "as =
=D0=A2=D0=B5=D1=81=D1=82"), then when viewed in html format it displays the code without decoding, when viewed in text format with decoding.
3) Downloaded attachments (docx, png) deteriorate when downloading (even their size differs from the original ones).

![1](https://user-images.githubusercontent.com/109460739/179393385-3da2810d-ed70-4abf-b248-2505a7791efe.png)
![2](https://user-images.githubusercontent.com/109460739/179393486-a150cac7-a5a8-46af-86b8-7f543e389280.png)

**Comment by alecpl** [comment]
Does it work with `$config['imap_disabled_caps'] = ['BINARY'];`?

**Comment by VasjaVI** [comment]
Yes. It solved all three problems.
(Sorry for my English)

**Comment by alecpl** [comment]
So, it is your IMAP server issues.
