### ISSUE TITLE
Feature Request: After select file to attach, perform the upload botton

### ISSUE THREAD

**Issue by dddns** [roundcube/roundcubemail#8630]
Howdy,

Would it be possible, to perform an update that is, when a file is selected for attach, after the select, perform the upload button, to skip one step?
This has been something that my users are requesting a lot.

Thanks in advanced,
Jorge

**Comment by alecpl** [comment]
I'm not sure what are you talking about? Maybe provide some screenshots. What skin? what version?

**Comment by dddns** [comment]
Hi,

Ok you're right!
Here's an image, so, when the users selected the file to upload, the system could perform the "upload" button imediatly, and skip one step, many users requested this.
Elastic and Larry theme has that feature,

Would it be possible to it in the default?

![image](https://user-images.githubusercontent.com/13902147/180952914-f7fdbcd4-5ba6-45aa-96ed-95e9f2e6c0f9.png)

**Comment by alecpl** [comment]
You're using the old skin which will likely do not get any improvements. Use the Elastic skin where it is improved.
