### ISSUE TITLE
href ids replaced without corresponding name ids corrections

### ISSUE THREAD

**Issue by oleg-indeez** [roundcube/roundcubemail#8632]
hello
I have found the following error: one of my centos stream 9 box daily sends logwatch report, which I configured as html. At start there's menu in html to ease the navigation within the report, e.g.:

&lt;!-- End header.html --&gt;
&lt;a name=top&gt;&lt;ul&gt;
   &lt;li&gt;&lt;a href="#1"&gt;LOGWATCH Summary&lt;/a&gt;
   &lt;li&gt;&lt;a href="#2"&gt;Kernel Audit&lt;/a&gt;
   &lt;li&gt;&lt;a href="#3"&gt;Cron&lt;/a&gt;
   &lt;li&gt;&lt;a href="#4"&gt;dnf-rpm&lt;/a&gt;
   ...

 It is original letter text (mail source). In the browseк it transfers to:

 &lt;ul&gt;&lt;a name="top"&gt;
   &lt;/a&gt;&lt;li&gt;&lt;a name="top"&gt;&lt;/a&gt;&lt;a href="#v11"&gt;LOGWATCH Summary&lt;/a&gt;
   &lt;/li&gt;&lt;li&gt;&lt;a href="#v12"&gt;Kernel Audit&lt;/a&gt;
   &lt;/li&gt;&lt;li&gt;&lt;a href="#v13"&gt;Cron&lt;/a&gt;
   &lt;/li&gt;&lt;li&gt;&lt;a href="#v14"&gt;dnf-rpm&lt;/a&gt;

with hrefs like `https://hostname/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=some_num0&_mbox=INBOX.xxx&_framed=1&_action=preview#v11`

but there's no navigation as the anchers names isn't changed, it's, for example:

&lt;h2&gt;&lt;a name="1"&gt;LOGWATCH Summary&lt;/a&gt;&lt;/h2&gt;

in both cases.

I'm trying to find the code that replaces href and names (seems to me that it's somewhere at program/js/app.js) but still have no idea how to correct this.

Please correct it either at href's url replacemnt or at name's. Thank you in advance

**Comment by oleg-indeez** [comment]
aah, I forgot! Sorry
I'm using `Roundcube Webmail 1.7-git [GIT 20220724.1345]` from git

**Comment by oleg-indeez** [comment]
I simplified the case w/ the same results: in editor add source html

&lt;p&gt;&lt;a href="#1"&gt;test link&lt;/a&gt;&lt;/p&gt;
&lt;hr style="margin-top: 172%;" /&gt;
&lt;h2&gt;&lt;a name="1"&gt;&lt;/a&gt;test anchor&lt;/h2&gt;

save it in draft folder and in preview test link href is `https://host/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=3259&_mbox=INBOX.Drafts&_framed=1&_action=preview#v11`

source in Chromium DevTool

&lt;div class="rcmBody" style="font-size: 10pt; font-family: Verdana,Geneva,sans-serif"&gt;
&lt;p&gt;&lt;a href="#v11"&gt;test link&lt;/a&gt;&lt;/p&gt;
&lt;hr style="margin-top: 172%"&gt;
&lt;h2&gt;&lt;a name="1"&gt;&lt;/a&gt;test anchor&lt;/h2&gt;
&lt;/div&gt;

**Comment by alecpl** [comment]
We need to add `$this->_css_prefix` to the `name` attribute on `<a>` elements. Somewhere in `rcube_washtml::wash_attribs()`.

**Comment by oleg-indeez** [comment]
the proposed patch
[program-lib-Roundcube-rcube_washtml.php-patch.txt](https://github.com/roundcube/roundcubemail/files/9218259/program-lib-Roundcube-rcube_washtml.php-patch.txt)

**Comment by alecpl** [comment]
Fixed.

**Comment by oleg-indeez** [comment]
hello. I noticed such a related rergression: when the link is activated, the buttons top margin is decreased and then it can not be scrolled/restored back to its original state - only reload the page in browser (e.g. `Ctrl+R`). See the screen-grabbed video:

https://user-images.githubusercontent.com/61268538/182364828-2e4d04ee-1ce1-4a49-bc3f-25ef10ffde90.mov

If i use interface links (like details or any interface button) it works as expected and the margins (visually) stay constant. I've `git pull`ed and update jsdeps + composer stuff - but the effect is repeatable and exists.

Source of the e-mail is quite simple and alike the one mentioned above:

&lt;p&gt;&lt;a href="#v11" name="v1top"&gt;top / to one&lt;/a&gt;&lt;/p&gt;
&lt;p style="margin-top: 777px;"&gt;&lt;a href="#v1top" name="v11"&gt;one / to top&lt;/a&gt;&lt;/p&gt;

(yes, it adds `v1` at the beginning every time a source code is edited, but i'm not bother as long as it adds everywhere and the code works as expected)

**Comment by alecpl** [comment]
Sorry, I missed that. Anyway, how is that a regression? This is a different issue and should have a separate ticket.

**Comment by oleg-indeez** [comment]
Never mind, as they say - better late than never =)
Well, now it's just the same - when click on `<a href=#id>`, it scrolls the page several pixels up, and they can be restored by page refresh (e.g. by pressing `Ctrl+R` ) only. The regression lives under Chromium (version 114.0.5735.133 (official build, for Linux Mint (64 bits)
BTW it doesn't happen in chromium and when in separate window - just tested
FireFox 114.0.2 (64-bits; Linux Mint build) is also regression-free.
