### ISSUE TITLE
Password update plugin error

### ISSUE THREAD

**Issue by mfpx** [roundcube/roundcubemail#8633]
Hi, I was trying to update the password for a user, but it failed, and it appears to fail for everyone (we don't really use that facility, but it's a good option to have).

Upon inspecting roundcube's logs, I've come across this:
`[29-Jul-2022 02:49:21 +0100]: <h91lecqu> DB Error: [1064] You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%c, 'ryan')' at line 1 (SQL Query: SELECT update_passwd(%c, 'ryan')) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 564 (POST /?_task=settings&_action=plugin.password-save)`

Note how the presumably formatted string isn't replaced with a value, but instead simply returns `%c`, likewise it also looks somewhat like a function call, i.e. `update_passwd()`.

Here's the relevant software versions:
```
PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
```
```
Roundcube Webmail 1.6.0
Copyright © 2005-2022, The Roundcube Dev Team
```
```
mariadb Ver 15.1 Distrib 10.6.7-MariaDB, for debian-linux-gnu (amd64) using  EditLine wrapper
```

Thanks

**Comment by alecpl** [comment]
The `%c` variable has been removed in Roundcube 1.6, but we need to change the default for `password_query` option to not use it. Btw, this default query is just a sample and does not work in most cases.

**Comment by alecpl** [comment]
Done.
