### ISSUE TITLE
PHP 7.4.30 "Unsupported PHP version. Required PHP >= 7.3."

### ISSUE THREAD

**Issue by tomkolp** [roundcube/roundcubemail#8635]
Centos Stream 8 (CWP repo) PHP 7.4.30 after updating Roundcube from 1.5 to 1.6, the message "Unsupported PHP version. Required PHP> = 7.3." Installation from the command line, no errors in the logs.

**Comment by alecpl** [comment]
The code in iniset.php is:
```
if (PHP_VERSION_ID < 70300) {
    die("Unsupported PHP version. Required PHP >= 7.3.");
}
```
I suspect you in fact do not use 7.4.

**Comment by tomkolp** [comment]
In fact, I had no idea that CWP Roundcube is the only one running on the old PHP version. At the moment, all that remains is to wait for the creators of CWP.
https://forum.centos-webpanel.com/index.php?topic=12064.0
