### ISSUE TITLE
PHP Error: Access denied for new user XXXXX

### ISSUE THREAD

**Issue by tessus** [roundcube/roundcubemail#8637]
After the upgrade from 1.5.3 to 1.6.0, I get the following error message:

```
PHP Error: Access denied for new user XXXXX. 'auto_create_user' is disabled in /data/projects/webmail/program/include/rcmail.php on line 815 (POST /mail/?_task=login&_action=login)
```

The web interface tells me `Login failed.`

What does this mean? The user `XXXXX` is not a new user. I have always used this user and password to login.

Please advise.

P.S.: The password is correct, because when I enter a wrong password, I get a different err msg: `IMAP Error: Login failed for XXXXX against HOST from IP`

**Comment by alecpl** [comment]
Did you read in the changelog about required config changes? Did imap host change? It looks like it can't find the user in Roundcube users table, and because 'auto_create_user' is disable it can't proceed.

**Comment by tessus** [comment]
Yes, I did. The install script also notified me of 2 changes and fixed them. I checked the config file and it seems fine.

The imap host did not change. The entire setup is the same. I only upgraded from 1.5.3 to 1.6.0.

This is what worries me. Why can't it read the user from the table? The schema upgrade was successful as well.

**Comment by alecpl** [comment]
you can enable sql_debug and see what query is being executed, then compare that with the existing users table record.

**Comment by tessus** [comment]
Ah, perfect. This helped. I didn't know about the `sql_debug` config option. My config file is quite old since it has been migrated every time a new version came out. Thus I never got any new options in the config file.

So what happened is that the installer did not migrate the `smtp_server` option, but rather just created `smtp_host` and set the default value. A bit strange, but ok. In theory it's ok, because my imap server is local, but I previously used the fqdn.
That's why the user/hostname combination could not be found in the table.

I fixed all that. Thanks a bunch again for your help.
