### ISSUE TITLE
Index shows "Oops... something went wrong!" if no 'config.inc.php' exists

### ISSUE THREAD

**Issue by mitchellvanbijleveld** [roundcube/roundcubemail#8638]
I am not 100% sure whether this is a bug or not and I actually like the behavior, but when visiting my Roundcube domain without configuring anything (never ran the installer and no config.inc.php exists), the page shows up as follows:

<img width="620" alt="Schermafbeelding 2022-07-30 om 01 30 24" src="https://user-images.githubusercontent.com/106330077/181860425-3bbeebc7-c21b-4b5a-8f51-a4a8e07bfbac.png">

After visiting /installer and/or creating a config.inc.php, the 'error message' is gone and I see the login window.

**Comment by alecpl** [comment]
As intended, if there's no config Roundcube can't connect to the database and proceed. An error message should be in the log.
