### ISSUE TITLE
smtp auth error after upgrade

### ISSUE THREAD

**Issue by damnms** [roundcube/roundcubemail#8639]
i had 1.5.3 running fine, then upgraded to 1.6.0, now i get an error. the error log contains:

[30-Jul-2022 16:19:01 +0200]: <rpa6qhvk> PHP Error: SMTP server does not support authentication (POST /?_task=mail&_unlock=loading1659190741401&_framed=1&_action=send)
[30-Jul-2022 16:19:01 +0200]: <rpa6qhvk> SMTP Error: Authentication failure: xxx.de
PIPELINING
SIZE 100000000
ETRN
STARTTLS
ENHANCEDSTATUSCODES
8BITMIME
DSN
SMTPUTF8
CHUNKING (Code: 250) in /var/lib/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /?_task=mail&_unlock=loading1659190741401&_framed=1&_action=send)

debian stable

edit:
as i dont have time to dig further into this (and must have the web client working), i moved the old folder (/var/lib/roundcube_backup, containing 1.5.3) back to /var/lib/roundcube and moved the broken one (1.6.0) to /var/lib/roundcube_broken. works again now. so something seems to be broken in migrating from 1.5.3->1.6.0

**Comment by navossoc** [comment]
Did you adjust your config.php?

https://github.com/roundcube/roundcubemail/releases/tag/1.6.0

There are some breaking changes, you will need to fix that first.

**Comment by damnms** [comment]
no i did not touch anything because the installer (updater) told me, it would do that for me. i answered 'y' in the dialog.

**Comment by alecpl** [comment]
You might need more recent Net_SMTP version for Roundcube 1.6. Also make sure you changed the config appropriately:
```
- renamed smtp_server to smtp_host
- removed smtp_port option (non-standard port can be set via smtp_host)
- set "localhost:587" as a default for smtp_host
```

**Comment by damnms** [comment]
is there more information about which version exactly is needed? it worked with 1.5.3, so if that changed, i would highly recommend to point that out in the README or UPGRADING, because then its broken with current debian stable.
regarding the settings: i would have expected the updater does exactly that.

**Comment by navossoc** [comment]
> is there more information about which version exactly is needed? it worked with 1.5.3, so if that changed, i would highly recommend to point that out in the README or UPGRADING, because then its broken with current debian stable. regarding the settings: i would have expected the updater does exactly that.

https://pear.php.net/package/Net_SMTP/download
1.10

**Comment by damnms** [comment]
the latest version available in debian stable is php-net-smtp                       1.9.0-1
is it a _must have_ to have that version or that package at all? why did it work in 1.5.3 even without that package?

**Comment by navossoc** [comment]
> the latest version available in debian stable is php-net-smtp 1.9.0-1 is it a _must have_ to have that version or that package at all? why did it work in 1.5.3 even without that package?

The package is needed in both versions (1.5 or 1.6), there is call to that new method `starttls` so that why it is required on 1.6.

You can try to  install pecl packages manually or something like docker.

**Comment by damnms** [comment]
> The package is needed in both versions (1.5 or 1.6)
it worked without that package in 1.5.3

**Comment by navossoc** [comment]
> > The package is needed in both versions (1.5 or 1.6)
> 
> it worked without that package in 1.5.3

AFAIK it was always needed.

https://github.com/roundcube/roundcubemail/blob/0121082842400ce1919ff4b4d36c991630b6988c/program/lib/Roundcube/rcube_smtp.php#L22

https://github.com/roundcube/roundcubemail/blob/0121082842400ce1919ff4b4d36c991630b6988c/program/lib/Roundcube/rcube_smtp.php#L128

Did you checked the vendor folder?
vendor/pear/net_smtp

**Comment by damnms** [comment]
i am noob with php "administration/deployment", i have no idea of pear and so on, only basic php programming.
in that case it is not required to use apt-get to install any package at all, it is shipped with roundcube?

**Comment by navossoc** [comment]
> i am noob with php "administration/deployment", i have no idea of pear and so on, only basic php programming. in that case it is not required to use apt-get to install any package at all, it is shipped with roundcube?

Did you install the SMTP package from debian? If so, may be that the problem, since it may be using the wrong version.

**Comment by damnms** [comment]
i installed it after the error indicated that package is missing. i removed it now, so its the same state i was before. but that does not fix anything, because the vendor/pear/smtp thingen is still the old one.

**Comment by navossoc** [comment]
You need to download the complete package to get the `vendor` folder as well...

**Comment by damnms** [comment]
i downloaded the complete package

**Comment by navossoc** [comment]
I don't think so...

I suggest you first try a clean install on another VM with the same debian version, just to make sure is not on your current install.

Since the required libs are bundled on the complete package.
Maybe is something with your include_path on php.

I'm running it on docker, so I'm not having this problem. I don't think I can help more than that...

[]'s

**Comment by damnms** [comment]
i always download the complete package and then do a ./bin/installto /var/lib/roundcube, confirm the upgrade and keep going.
this time however it is somehow broken. what happens on a fresh install with this pear folder? the files do not magically go there, so maybe i can run that command by myself to get the latest versions of the vendor classes

**Comment by navossoc** [comment]
The latest version 1.6.0 already comes with the required Net_SMTP version 1.10.

**Comment by damnms** [comment]
in that case the updater does not overwrite the vendor classes, thats why it fails.
i will try to overwrite the old file with the new one and see if it works then

**Comment by navossoc** [comment]
I think you should it manually:
https://github.com/roundcube/roundcubemail/blob/master/UPGRADING#L45

But as I said, I'm using it on docker.
So it's always "fresh files" on each release.

[]'s

**Comment by damnms** [comment]
> I think you should do it manually:

makes absolutely no sense if there is an update script that (should) do everything. as it does not, its  a bug.

**Comment by damnms** [comment]
closing this and separate the 2 bugs
