### ISSUE TITLE
Password change

### ISSUE THREAD

**Issue by hhwk** [roundcube/roundcubemail#8641]
Good afternoon! I changed my mailbox password and now I can't log in. I had a suspicion that this was due to the fact that I accidentally wrote the password not in English letters, but in Cyrillic. I want to find out what my password could convert your code into. Or are there any other solutions to this problem?
http://mail.jlchacha.com/?_task=login

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
