### ISSUE TITLE
bug: the updater does not correctly migrate config fields from 1.5.3 to 1.6

### ISSUE THREAD

**Issue by damnms** [roundcube/roundcubemail#8643]
because of some unrelated comments in #8639 i'm going to create this bug report.

steps to reproduce:
1) have an install of 1.5.3 configured with smtp_server
2) download the 1.6-complete tar.gz 
3) run the bin/installto script and point it to the 1.5.3 location
4) answer 'y' when it asks if it should migrate the old configs

expected:
all obsolete/deprecated config fields are renamed to the new one like: smtp_server -> smtp_host

actual behaviour: 
it does not change them or (iirc) even removed the smtp_host without creating any new entry

**Comment by alecpl** [comment]
Fixed.
