### ISSUE TITLE
Roundcube 1.6-git installer warning

### ISSUE THREAD

**Issue by teoberi** [roundcube/roundcubemail#8644]
PHP 8.0.21 or PHP 8.1.8
Roundcube Webmail Installer -> 2. Create config
/var/log/httpd/error_log

> [Mon Aug 01 12:24:43.722796 2022] [php:warn] [pid 25502] [client xxx:57001] PHP Warning:  Undefined array key "hostspec" in /var/www/htdocs/roundcube-1.6/installer/config.php on line 285, referer: https://yyy/roundcube-1.6/installer/index.php?_step=3
> [Mon Aug 01 12:24:43.722851 2022] [php:warn] [pid 25502] [client xxx:57001] PHP Warning:  Undefined array key "username" in /var/www/htdocs/roundcube-1.6/installer/config.php on line 289, referer: https://yyy/roundcube-1.6/installer/index.php?_step=3
> [Mon Aug 01 12:24:43.722872 2022] [php:warn] [pid 25502] [client xxx:57001] PHP Warning:  Undefined array key "password" in /var/www/htdocs/roundcube-1.6/installer/config.php on line 291, referer: https://yyy/roundcube-1.6/installer/index.php?_step=3

xxx = IP address
yyy = mail hostname

**Comment by alecpl** [comment]
Fixed.
