### ISSUE TITLE
bug: Updating 1.5.3 to 1.6 removes config options

### ISSUE THREAD

**Issue by jniggemann** [roundcube/roundcubemail#8645]
Updating from 1.5.3 to 1.6, the installer asked to fix my config. I said yes. Big mistake ;-)

The config option `$config['ip_check']` was silently deleted, as was `$config['enable_spellcheck']`.

**Comment by sebastian-schmid** [comment]
I also tried this feature at upgrade but ended with a config file which was not working. I moved the backup config file back in place and did the needed changes by hand.

**Comment by sebastian-schmid** [comment]
This Issue looks like a duplicate of #8643 isn't it?

**Comment by alecpl** [comment]
If the option is set to a default value it is being removed from the config. So, that's that. The other part might be that it's a duplicate of #8643.

**Comment by jniggemann** [comment]
> If the option is set to a default value it is being removed from the config. So, that's that.

Looking for documentation, I only found the [wiki](https://github.com/roundcube/roundcubemail/wiki/Configuration)) and it describes neither those options nor their default values. Where do I find that information?

Semi-unrelated: Since docs.roundcube.net is last updated in 2015, wouldn't it be better to shut it down altogether?

> I moved the backup config file back in place and did the needed changes by hand.

That's what I did, too. But the expectation set by displaying "Would you like me to correct the config?" is more like: Only change what needs changing, otherwise leave it untouched. Personally, while a very good faith effort, I find it a bit unfortunate to remove options from my config, even if they are default options.

Anyway: Duplicate of #8643, closing this.
