### ISSUE TITLE
Undefined property: rcube_message_header::$authres_status

### ISSUE THREAD

**Issue by kasak87** [roundcube/roundcubemail#8647]
I'm sorry to bother you. This is maybe not roundcube bug, but something else. 
I have tons of this messages in roundcube log:
this is from 1.6.0:
`[02-Aug-2022 16:37:21 UTC] PHP Warning:  Undefined property: rcube_message_header::$authres_status in /var/www/htdocs/roundcube/program/actions/mail/index.php on line 553`

And this was from 1.5.3:
`[29-Jul-2022 17:18:26 UTC] PHP Warning:  Undefined property: rcube_message_header::$authres_status in /var/www/htdocs/roundcube/program/actions/mail/index.php on line 551
`

I do **NOT** have plugin authres_status installed, and not have it in my config:
mx$ ls /var/www/htdocs/roundcube/plugins/                                                                                                                                              
acl                        contextmenu                example_addressbook        identity_select            new_user_identity          squirrelmail_usercopy      zipdownload
additional_message_headers database_attachments       filesystem_attachments     jqueryui                   newmail_notifier           subscriptions_option
archive                    debug_logger               help                       krb_authentication         password                   userinfo
attachment_reminder        dovecot_ident              hide_blockquote            managesieve                reconnect                  vcard_attachments
autologon                  emoticons                  http_authentication        markasjunk                 redundant_attachments      virtuser_file
autologout                 enigma                     identicon                  new_user_dialog            show_additional_headers    virtuser_query

mx$ grep plugins config/config.inc.php          
// List of active plugins (in plugins/ directory)
$config['plugins'] = array('autologon', 'archive', 'enigma', 'emoticons', 'managesieve', 'markasjunk', 'contextmenu', 'dovecot_ident');

I have only plugins "contextmenu" and "dovecot_ident" installed out of vanilla roundcube, but disabling them doesn't solve this issue. 
Where can it be?

**Comment by alecpl** [comment]
There's no "authres_status" string in the whole codebase, so it must come from a plugin.

Anyway, we might want to check for the property existence before using it, to prevent that warning.

**Comment by alecpl** [comment]
Maybe, if you had this plugin enabled before, it might get "injected" into user settings (a column in messages list).

**Comment by kasak87** [comment]
> Maybe, if you had this plugin enabled before, it might get "injected" into user settings (a column in messages list).

Yep, i had it before, but long time ago. Since then i had couple of clean reinstalls (copy old config.inc.php and db, nothing else)
is there any way to remove this "injected" column?

**Comment by FlyveHest** [comment]
Commenting to follow, I have had the authres plugin installed a long time ago as well (not enabled anymore), and are seeing these messages in the log as well.

It seems to be saved in users tables in the preferences column, but it can't just be removed as the string is a serialized array.

Seems like the plugin didn't clean up after itself when uninstalled.

**Comment by alecpl** [comment]
Fixed.
