### ISSUE TITLE
Question about multi domain

### ISSUE THREAD

**Issue by hgjo4824** [roundcube/roundcubemail#8648]
I don't know if I can write here, but I have a problem that I haven't been able to solve. I'm sorry to bother you.

I am going to install and use roundcube through the guide below.
https://www.linuxbabe.com/mail-server/setup-basic-postfix-mail-sever-ubuntu

Installation was completed through the guide, but there is a problem related to multi-domain.
Using postfixadmin, domain example.kr and example.co.kr were registered, and mailboxes username@example.kr and username@example.co.kr were created respectively.
If you send an email to both username@example.kr and username@example.co.kr, you cannot check the email sent to username@example.co.kr when you log in as username@example.kr.

Is there any way to solve this problem?
I know I shouldn't post something like this here, but I still do.
Sorry.

**Comment by alecpl** [comment]
These are two distinct users (accounts). Roundcube has no multi-account feature. Normally you could use "folder sharing" feature, setting some ACL on the imap server, then Roundcube could see other users folders, but this is IMAP server feature.
