### ISSUE TITLE
Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/php/Mail/mimePart.php:303

### ISSUE THREAD

**Issue by servoronine** [roundcube/roundcubemail#8649]
Hi,

After upgrading to Roundcube 1.6 and PHP8.1 (but same issue with PHP8.0), I am unable to send mails from Roundcube. Any time I try to send or save an email I get the following message in syslog:

**Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/php/Mail/mimePart.php:303**

The full stack trace looks like this:
**Aug  3 08:49:25 mailX roundcube: #6 /usr/share/nginx/roundcube/index.php(278): rcmail->action_handler()
Aug  3 08:49:25 mailX roundcube: #5 /usr/share/nginx/roundcube/program/include/rcmail.php(275): rcmail_action_mail_send->run()
Aug  3 08:49:25 mailX roundcube: #4 /usr/share/nginx/roundcube/program/actions/mail/send.php(249): rcmail_sendmail->save_message()
Aug  3 08:49:25 mailX roundcube: #3 /usr/share/nginx/roundcube/program/include/rcmail_sendmail.php(544): Mail_mime->getMessage()
Aug  3 08:49:25 mailX roundcube: #2 /usr/share/php/Mail/mime.php(715): Mail_mime->get()
Aug  3 08:49:25 mailX roundcube: #1 /usr/share/php/Mail/mime.php(1042): Mail_mimePart->encode()
Aug  3 08:49:25 mailX roundcube: #0 /usr/share/php/Mail/mimePart.php(313): Mail_mimePart->encode()**

There  is also an info message about deprecation - not sure if that is related:
**roundcube: PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/php/Mail/mime.php on line 893**

**Comment by alecpl** [comment]
Line numbers suggest this is some old version of Mail_mime package. Looks like you didn't update the composer dependencies. How did you do the upgrade?

**Comment by servoronine** [comment]
That was my initial thought as well. I upgraded using the installto.sh script. After that I executed the "composer update --no-dev", but ran into a few issues.

Since I could not find a better way to resolve them, I deleted the "vendor" directory as well as composer.lock file and then ran "composer install --no-dev" in order to reinstall all the dependencies.

Based on composer show command I now have the latest version of the pear/mail_mime package:
bacon/bacon-qr-code           2.0.7    BaconQrCode is a QR code generator for PHP.
dasprid/enum                  1.0.3    PHP 7.1 enum implementation
guzzlehttp/guzzle             7.4.5    Guzzle is a PHP HTTP client library
guzzlehttp/promises           1.5.1    Guzzle promises library
guzzlehttp/psr7               2.4.0    PSR-7 message implementation that also provides common utility methods
johndoh/contextmenu           3.3.1    Adds context menus with common tasks to various parts of Roundcube
masterminds/html5             2.7.5    An HTML5 parser and serializer.
pear/auth_sasl                v1.1.0   Abstraction of various SASL mechanism responses
pear/console_commandline      v1.2.4   A full featured command line options and arguments parser.
pear/console_getopt           v1.4.3   More info available on: http://pear.php.net/package/Console_Getopt
pear/crypt_gpg                v1.6.7   Provides an object oriented interface to the GNU Privacy Guard (GnuPG). It requires the GnuPG executable to be on the system.
**pear/mail_mime                1.10.11  Mail_Mime provides classes to create MIME messages**
pear/net_idna2                v0.2.0   More info available on: https://pear.php.net/package/Net_IDNA2
pear/net_sieve                1.4.5    More info available on: https://pear.php.net/package/Net_Sieve
pear/net_smtp                 1.10.0   An implementation of the SMTP protocol
pear/net_socket               v1.2.2   More info available on: http://pear.php.net/package/Net_Socket
pear/pear-core-minimal        v1.10.11 Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception           v1.0.2   The PEAR Exception base class.
psr/http-client               1.0.1    Common interface for HTTP clients
psr/http-factory              1.0.1    Common interfaces for PSR-7 HTTP message factories
psr/http-message              1.0.1    Common interface for HTTP messages
ralouphie/getallheaders       3.0.3    A polyfill for getallheaders.
roundcube/plugin-installer    0.3.2    A composer-installer for Roundcube plugins and skins.
roundcube/rtf-html-php        v2.1     RTF to HTML converter in PHP
symfony/deprecation-contracts v3.1.1   A generic function and convention to trigger deprecation notices

Is there anything else I am missing here? Thanks for your help!

**Comment by alecpl** [comment]
Oh, I missed that it is `/usr/share/php/Mail/mimePart.php`. It uses the (global) package installed in your system. I'd expect the vendor dependencies to have a higher prio, but I'm not sure about that.

**Comment by servoronine** [comment]
Do you know how it is getting to this directory? If I run "composer config --list --global" I get the following:

[vendor-dir] vendor (/usr/share/php/PEAR/vendor)
**[bin-dir] {$vendor-dir}/bin (/usr/share/php/PEAR/vendor/bin)**
[cache-dir] /root/.composer/cache
[data-dir] /root/.composer
[cache-files-dir] {$cache-dir}/files (/root/.composer/cache/files)
[cache-repo-dir] {$cache-dir}/repo (/root/.composer/cache/repo)
[cache-vcs-dir] {$cache-dir}/vcs (/root/.composer/cache/vcs)

But actually the vendor directory does not exist on my system. So it appears as if no global packages have ever been installed, at least by composer.

**Comment by servoronine** [comment]
Ok, I think I am getting closer to the root of the issue, but have no idea how to fix this properly. It appears that the offending package has been installed in the pre-composer days directly via pear. I ran "sudo pear list" and saw a bunch of old packages. I proceeded to run "sudo pear upgrade", these packages were upgraded and the issue is now resolved.

However when I tried to remove a global package (e.g. Mail_Mime), I got an error from Roundcube to say that the class was not found at all. So it is definitely searching for a global package and not the one under vendor folder (and if there is no global package installed it gives an error.

I appreciate, as we determined, this is not directly related to roundcube, but any thoughts on how to fix this properly so that it reads the vendor folder would be much appreciated.

**Comment by asterismo** [comment]
Hi, i'm running into this issue, the email keeps sending and never sends in the webmail. The errors.log shows this

[05-Mar-2024 17:59:23 UTC] PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/roundcube/vendor/pear/mail_mime/Mail/mimePart.php:314
Stack trace:                                                                                                                                    #0 /var/www/html/roundcube/vendor/pear/mail_mime/Mail/mime.php(1056): Mail_mimePart->encode()                                                       #1 /var/www/html/roundcube/program/lib/Roundcube/rcube.php(1748): Mail_mime->get()                     
#2 /var/www/html/roundcube/program/include/rcmail_sendmail.php(406): rcube->deliver_message()                                                       #3 /var/www/html/roundcube/program/actions/mail/send.php(234): rcmail_sendmail->deliver_message()
#4 /var/www/html/roundcube/program/include/rcmail.php(275): rcmail_action_mail_send->run()                                                          #5 /var/www/html/roundcube/index.php(279): rcmail->action_handler()
#6 {main}                                                                                                                                         thrown in /var/www/html/roundcube/vendor/pear/mail_mime/Mail/mimePart.php on line 314

and sudo pear list

INSTALLED PACKAGES, CHANNEL PEAR.PHP.NET:
=========================================
PACKAGE          VERSION STATE
Archive_Tar      1.4.14  stable
Auth_SASL        1.2.0   stable
Console_Getopt   1.4.3   stable
Date             1.4.7   stable
Mail_Mime        1.10.11 stable
Net_DNS2         1.5.0   stable
Net_SMTP         1.11.1  stable
Net_Socket       1.2.2   stable
PEAR             1.10.13 stable
PEAR_Manpages    1.10.0  stable
Structures_Graph 1.1.1   stable
XML_Util         1.4.5   stable

I'm running Debian 12 with php-fpm8.2

**Comment by alecpl** [comment]
This specific error was fixed in Mail_mime 1.10.2 https://github.com/pear/Mail_Mime/commit/54a61233dd99498722468e7c6e413505d6d8edf6

So, you're not using what you think.
