### ISSUE TITLE
Skins for managesieve plugin missing in 1.6.0

### ISSUE THREAD

**Issue by gabrielt** [roundcube/roundcubemail#8651]
Hi,

In the 1.6.0 package, under /plugins/managesieve/skins, the templates for classic and larry skins are missing. Only elastic is present. I had to copy them from the 1.5.3 package in order to make the managesieve plugin work.

Cheers.

**Comment by alecpl** [comment]
In 1.6.0 classic and larry skins are in separate repositories. The files are in the skin package.

**Comment by gabrielt** [comment]
Hi alecpl,

I am talking specifically about the managesieve plugin. The templates for classic/larry skin for this plugin are missing and not included in the main package nor in the skins packages.

Thanks,

**Comment by gabrielt** [comment]
Got it. Thanks.
