### ISSUE TITLE
Bug?! Javascript API event hooks

### ISSUE THREAD

**Issue by AuspeXeu** [roundcube/roundcubemail#8653]
From my understanding, the event mechanism can be seen as a singleton across the web ui. If that is the case, there is something strange going on. The first screenshot was taken when the page is loaded, the `init` event has 5 registered listeners. The second screenshot was taken when an email is selected from the message list. Here, the `init` event has only 3 registered listeners. This implies, that there are two different pools of listeners for the same event, doesn't it? Or do I not understand the concept correctly?

My listener registered via `rcmail.addEventListener('init', function (event) {...})` only fires once despite two `init` events being triggered.

![image](https://user-images.githubusercontent.com/2115696/183079360-43d56871-33cc-495e-8a48-6dc006a79acd.png)
![image](https://user-images.githubusercontent.com/2115696/183079519-a365f16c-e562-486a-abfd-bb62f45491a0.png)

**Comment by alecpl** [comment]
Messages are previewed in an iframe which has it's own "life".

**Comment by AuspeXeu** [comment]
Thanks for the clarification. That explains it!
