### ISSUE TITLE
line_length ignored if over 70 something when send_format_flowed = true

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8658]
All of these test happen when not selecting the `[Keep Formatting]` option. Selecting the keep formatting option over rides the following behavior.

Set `$config['send_format_flowed'] = true;`.
If `$config['line_length']` is less than 70 (for example 50) then word wrapping will happen at the number selected.
If `$config['line_length']` is over 80 (for example 200) it will still word wrap at 70-something, between 70 and 80 characters.

Because flowed is on, in the preview window you wont see the wrapping as RC re-formats the message, but if you look at the raw source you will see the line breaks.

If you set `$config['send_format_flowed'] = false;` then the message body will be correctly word wrapped where `$config['line_length']` tells it to regardless if it is lower or higher than 80.

**Comment by Github-Citizen** [comment]
Since MTA's will force a line break at 998 what i wish to have happen is set
```
$config['line_length'] = 990;
$config['send_format_flowed'] = true;
```
to allow the best possible chance of the receiving client to get formatting (as close as possible) as the sender intended.
As i like the idea of the Keep Formatting option, unfortunately the MTA's will line break you anyways so for me this would be a better option if i can get the above two settings to work together.

**Comment by Github-Citizen** [comment]
And while im here, is there a value i can add to `$config['dont_override']` to remove the [Keep Formatting] switch from the composer screen?

**Comment by alecpl** [comment]
If you look at `rcmail_sendmail::format_plain_body()` we enforce maximum line length to be 79 in flowed mode. 

RFC 2646 says "When generating Format=Flowed text, lines SHOULD be shorter than 80 characters". I know it's not a MUST, but I don't buy your arguments to allow using bigger value.
