### ISSUE TITLE
$config['session_lifetime']

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8659]
Does `$config['session_lifetime']` have any effect in v1.6 or is it dead code now?
From best i can tell both the session and auth cookies are set to `0` and live until browser is closed.

**Comment by alecpl** [comment]
It has the same effect as before. When user is logged in the session is kept alive. If the browser is closed (or the Internet connection dies) the session will be valid for as long as the session_lifetime. Note that the cookies are not reused by the browser after close.
