### ISSUE TITLE
Plugin hook config_get isn't over riding values in rcube.php :: session_init()

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8663]
I am trying to override the `$config['session_lifetime']` value using the plugin hook `'config_get'`.
I also tried setting the variable in the plugin `plugin/*/config.inc.php` hoping it would over write what is set in `config/config.inc.php`.

In `program/lib/Roundcube/rcube.php` line `458`
```
$lifetime      = $this->config->get('session_lifetime', 0) * 60;
```
`$lifetime` always gets the value in `config/config.inc.php` regardless of what the plugin does in the `plugin/*/config.inc.php` or `'config_get'` hook.

Does the code in `rcube.php` run before plugins get loaded or does it not call the hooks?
What is the best way for a plugin to override a value from `config/config.inc.php`?

**Comment by alecpl** [comment]
You have to use `onload()` method in your plugin. It will be executed before session.

**Comment by Github-Citizen** [comment]
Thank you, that worked, the plugin can now override `$config['session_lifetime']`.
Just to let you know, i could not find any mention of `onload()` in the plugin api docs/wiki.
