### ISSUE TITLE
Wrong `UNIQUE INDEX` for `responses` table on Postgresql

### ISSUE THREAD

**Issue by m4dz** [roundcube/roundcubemail#8664]
The `responses` table uses an index based on `user_id`.

Right now, with Postgresql, this index is created with the `UNIQUE INDEX` instruction, leading to a bug where users can have only one response associated to their account: https://github.com/roundcube/roundcubemail/blob/master/SQL/postgres/2021081000.sql#L19

The issue also existed with SQLite (https://github.com/roundcube/roundcubemail/blob/master/SQL/sqlite/2021081000.sql#L11) but seems to have to been fixed in the next migration (https://github.com/roundcube/roundcubemail/blob/master/SQL/sqlite/2021100300.sql#L112).

**Comment by alecpl** [comment]
It's also wrong in the migration files for SQLite.

**Comment by alecpl** [comment]
Fixed.
