### ISSUE TITLE
New Official Design UI

### ISSUE THREAD

**Issue by eveneme** [roundcube/roundcubemail#8665]
I think version 1.7 should bring a modernized look for the template.

**Comment by alecpl** [comment]
I will not do it, so chances are low.

**Comment by thomascube** [comment]
@eveneme Feel free to create a design for this modernized look you have in mind.

It's far more difficult and time consuming to draft the screen design for a complete application that opening Github issues with a one-line text.

**Comment by eveneme** [comment]
I can make a graphic design, but I will not code it.
