### ISSUE TITLE
PHP (8.1) warnings

### ISSUE THREAD

**Issue by iredmail** [roundcube/roundcubemail#8667]
- OS: Ubuntu 22.04
- PHP: 8.1.2 (shipped by Ubuntu)
- Roundcube: 1.6.0

Warning messages in log file:

> Aug  9 08:12:52 host roundcube: PHP Warning:  Undefined array key "__IP" in /opt/www/roundcubemail-1.6.0/program/lib/Roundcube/session/php.php on line 72
> Aug  9 08:12:52 host roundcube: PHP Warning:  Undefined array key "__MTIME" in /opt/www/roundcubemail-1.6.0/program/lib/Roundcube/session/php.php on line 73

**Comment by nicohell** [comment]
Hi

Same issue in program/lib/Roundcube/rcube_message.php with `if ($plugin['abort']) { `.
`if (isset($plugin['abort'])) {` should be better... no ?

**Comment by alecpl** [comment]
Fixed.

**Comment by iredmail** [comment]
Thanks @alecpl :)

**Comment by nicohell** [comment]
Thanks alecpl but you didn't modify test on` $plugin['abort'] ` (3 times) in program/lib/Roundcube/rcube_message.php...

**Comment by alecpl** [comment]
@nicohell Let's handle it separately. I'd need more info (complete error message). The 'abort' element should always be set as far as I can see.

**Comment by nicohell** [comment]
@alecpl here it is :) #8669
