### ISSUE TITLE
PHP 8.x Warnings :: Undefined array keys

### ISSUE THREAD

**Issue by nicohell** [roundcube/roundcubemail#8669]
OS: RockyLinux 8.5
PHP: 8.1.8
Roundcube: 1.6.0

We call Roundcube library from Laravel application to read mails using IMAP protocol : 
```
define("RCUBE_CONFIG_DIR", $roundcubePath."config");
require_once $roundcubePath.'program/lib/Roundcube/bootstrap.php';
$rcube = \rcube::get_instance();
$this->imapClient = $rcube->get_storage(); 
....
```
After migrating our app to Laravel 9 (that required ^PHP8) we encountered <<_Undefined array key "abort"_>> warning  in program/lib/Roundcube/rcube_message.php. 
Modifying 3 times `if ($plugin['abort']) {` by `if (isset($plugin['abort'])) {` in the file solves the issue.

**Comment by alecpl** [comment]
Ok, now this is more clear. Looks like your setup uses the `rcube_dummy_plugin_api` fallback instead of `rcube_plugin_api`. In this case the 'abort' flag might indeed be not set. I'll fix that.

**Comment by alecpl** [comment]
Fixed.
