### ISSUE TITLE
How to use composer 2.2 LTS when installing Roundcubemail 1.5.3?

### ISSUE THREAD

**Issue by basmevissen** [roundcube/roundcubemail#8672]
Hi,

I tried to upgrade Roundcubemail from version 1.5.2 to 1.5.3 on my Ubuntu 14.04 LTS ESM mail server. As this server is running fine and Ubuntu supports it until April 2024 (!), I do not plan on upgrading it soon.

However, I would like to keep some packages current, outside what Ubuntu can support. Roundcubemail in one of them. The 1.6.0 release requires a way newer PHP than 5.5.9 that I cannot provide for Roundcubemail. So I want to stick to 1.5.x.

Unfortunately, since version 1.5.3, composer 2.3 is required/used. This version does not support PHP < 5.6. The vendor/autoload.php script suggest to install composer 2.2 LTS version.  Merely installing composer 2.2.17 (latest 2.2 LTS) in the path as suggested in the error message was not sufficient (which was obvious after reading the file).

Any help is appreciated. I would like to avoid manually updating Roundcubemail as that might cause issues in the future.
My obvious request is also to keep the prerequisites for the whole 1.5.x branch the same.

Many thanks,

Bas.

**Comment by alecpl** [comment]
What makes you think that composer 2.3 is required? Is this the "allow-plugins" part? Does it throw an error on 2.2? I guess you can just remove this part from your composer.json file.

**Comment by basmevissen** [comment]
The script vendor/autoload.php script tells me that. It fails with an error at the next line when I remove the error message.

**Comment by alecpl** [comment]
Right. We shouldn't have used composer 2.3 to build the 1.5.3 package.

@basmevissen You can get the normal (not the "complete") release package from https://github.com/roundcube/roundcubemail/releases/tag/1.5.3, do the update and in the end run composer update.

@thomascube You think we should create a new release just for that?

**Comment by basmevissen** [comment]
That seems fine. Although it ends with an error:

Updating database schema (2020020101)... [FAILED]
ERROR: Error in DDL upgrade 2020020101: [1025] Error on rename of './roundcube/cache' to './roundcube/#sql2-47b-2b5' (errno: 152)
All done.

Not sure if it is related. I believe that previous upgrades went fine.

I only ran the installto script so far. Do I need to run anything else?

Thanks for the quick respons!

**Comment by johndoh** [comment]
Looks like your current db scheme is incorrect. See #8386
