### ISSUE TITLE
Roundcube update hk.

### ISSUE THREAD

**Issue by glnkglnk** [roundcube/roundcubemail#8673]
Hello,

This now

Server: Centos 7
Roundcube Version: Roundcube Webmail 1.4.11
PHP version:  7.1.4

If I update only Roundcube Version 1.6.0 on the server whose properties are written above, will any settings be broken? Is there any possibility of error in config files

**Comment by alecpl** [comment]
There's always such possibility, but in general it should work.

**Comment by glnkglnk** [comment]
![image](https://user-images.githubusercontent.com/111151546/184485657-117e85a4-1dc8-4e2c-8641-07db04125603.png)

they are not activated. How can I activate
