### ISSUE TITLE
How to user composer to get enigma plugin

### ISSUE THREAD

**Issue by mikygee** [roundcube/roundcubemail#8674]
Hello,
The enigma plugin
`https://github.com/roundcube/roundcubemail/tree/master/plugins/enigma`
has a composer.json file but I don't know how should I modify my composer.json to get it through the composer update command
Any idea ?

**Comment by alecpl** [comment]
As this is a core plugin, it's always available (the dependencies are in the core composer.json file), and you don't need any extra steps.
