### ISSUE TITLE
Couldn't receive email from one of the senders

### ISSUE THREAD

**Issue by jennivinejy** [roundcube/roundcubemail#8675]
![WhatsApp Image 2022-08-15 at 4 23 31 PM](https://user-images.githubusercontent.com/111275988/184607765-35ba54ee-7ee3-466f-bdc1-aef504b6c314.jpeg)

Hi , my email is jennivine@barbqplaza.com.my, one of the senders (marketing@barbqplaza.com.my) could not send email to me. Kindly advise/assist. Thank you.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
