### ISSUE TITLE
SMTP auth always fails

### ISSUE THREAD

**Issue by stariontech** [roundcube/roundcubemail#8676]
Roundcube 1.60 gives SMTP Error(): Authentication failed when trying to send mail.

Have tried EVERY combination of $config smtp_host and $config smtp_auth_type, and NONE of them work.

Able to log into, send and receive emails from several different email clients indicating mail server is functioning.

**Comment by alecpl** [comment]
There's been some issues with config migration. How the config looks now, and how it looked before (grep smtp_ config.inc.php)?

**Comment by stariontech** [comment]
This was a completely new installation of Roundcube.  I have compared old config.inc.php to the new one, and they are identical, except for the format of the $config_smtp_host and $config_smtp_auth_type.  As I stated, there is no combination of any of those that work.  Roundcube is currently sitting on our server only able to retrieve messages.

**Comment by BigWhoopM** [comment]
Hi stariontech,
i have the same problem. It seems that i cannot do secure auth with port 25 anymore.
Is this where you handle your smtp requests also?

if i use tls:// or ssl:// it overwrite my smtp_port config. Didnt know what to do either.

**Comment by alecpl** [comment]
smtp_port is no more. You can set the port in smtp_host. Problem is that smtp_server+smtp_port to smtp_host conversion does not work and need to be done manually.

**Comment by stariontech** [comment]
Yes, I already realize that.  And as I stated, any combination of the new smtp_host and smtp_auth_type does not work.  With or without ports.  It just simply doesn't work.

**Comment by BigWhoopM** [comment]
> i

ok but how?

@stariontech please give us your "grep smtp_ config.inc.php" output :)

**Comment by outsolos** [comment]
I'm having the exact same problem. After upgrading from 1.5.3 to 1.6.0 and changing the config parameters, I can login and read my email but sending email fails. Here's the output of `grep 'smtp_' config/config.inc.php` (redacted for privacy):

```
$config['smtp_host'] = 'tls://my.mail.host:587';
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
```

And here's the corresponding log after trying to send an email (redacted for privacy):

```
[24-Aug-2022 11:41:09 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method Net_SMTP::starttls() in /srv/roundcube/program/lib/Roundcube/rcube_smtp.php:164
Stack trace:
#0 /srv/roundcube/program/lib/Roundcube/rcube.php(284): rcube_smtp->connect()
#1 /srv/roundcube/program/lib/Roundcube/rcube.php(1784): rcube->smtp_init(true)
#2 /srv/roundcube/program/include/rcmail_sendmail.php(425): rcube->deliver_message(Object(Mail_mime), 'some.name@host...', 'Some Name...', NULL, NULL, Array, true)
#3 /srv/roundcube/program/actions/mail/send.php(245): rcmail_sendmail->deliver_message(Object(Mail_mime))
#4 /srv/roundcube/program/include/rcmail.php(275): rcmail_action_mail_send->run(Array)
#5 /srv/roundcube/index.php(278): rcmail->action_handler()
#6 /srv/roundcube/public_html/index.php(26): include('/srv/roundcube/...')
#7 {main}
in /srv/roundcube/program/lib/Roundcube/rcube_smtp.php on line 164
```

My mailserver logs the following (redacted for privacy):

```
Aug 24 11:41:09 mail postfix/smtpd[33955]: connect from my.web.host[10.0.100.2]
Aug 24 11:41:09 mail postfix/smtpd[33955]: lost connection after EHLO from my.web.host[10.0.100.2]
Aug 24 11:41:09 mail postfix/smtpd[33955]: disconnect from my.web.host[10.0.100.2] ehlo=1 commands=1
```

Any ideas?

**Comment by BigWhoopM** [comment]
[alecpl](https://github.com/alecpl) said in my other post that this is a known behavior.
You need to upgrade the vandor folder by yourself! That its working again.

=> [https://github.com/roundcube/roundcubemail/issues/8642](https://github.com/roundcube/roundcubemail/issues/8642)

**Comment by outsolos** [comment]
Thank you @BigWhoopM. Updating the vendor directory solved the issue 👍. Seems like `bin/installto.sh` needs fixing, as you suggested in https://github.com/roundcube/roundcubemail/issues/8642

**Comment by stariontech** [comment]
Is there a procedure for "upgrading the vendor folder"?  I don't see anything about how to do that.

**Comment by outsolos** [comment]
> Is there a procedure for "upgrading the vendor folder"? I don't see anything about how to do that.

I just rsynced the all contents of the vendor directory from the unpacked roundcubemail-1.6.0-complete.tar.gz to the vendor directory of my installation like this: `rsync -av --delete roundcubemail-1.6.0/vendor/ /srv/roundcube/vendor/`. That's it.

**Comment by stariontech** [comment]
Copied the vendor directory.  Still doesn't work.  Here is grep output of grep smtp_ config.inc.php

$config['smtp_host'] = 'masked.mailserver.com';
$config['smtp_auth_type'] = null;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';

**Comment by stariontech** [comment]
If I change the smtp_host to 'tls://masked.mailserver.com' I get this in the postfix error log:

SSL_accept error from masked.mailserver.com[xxx.xxx.xxx.xxx]: 0
Aug 28 13:48:58 mail postfix/smtpd[11727]: warning: TLS library problem: 11727:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1275:SSL alert number 48:
Aug 28 13:48:58 mail postfix/smtpd[11727]: lost connection after STARTTLS from masked.mailserver.com[xxx.xxx.xxx.xxx]

**Comment by outsolos** [comment]
@stariontech Can you also post the corresponding part from your roundcube error log?

**Comment by stariontech** [comment]
DSN (Code: 250) in /var/www/html/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /roundcube/?_task=mail&_unlock=loading1661712374644&_framed=1&_action=send)
[28-Aug-2022 13:46:36 -0500]: <nernq34l> PHP Error: SMTP server does not support authentication (POST /roundcube/?_task=mail&_unlock=loading1661712396060&_framed=1&_action=send)
[28-Aug-2022 13:46:36 -0500]: <nernq34l> SMTP Error: Authentication failure: masked.mailserver.com
PIPELINING
SIZE 31457280
VRFY
ETRN
STARTTLS
ENHANCEDSTATUSCODES
8BITMIME
DSN (Code: 250) in /var/www/html/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /roundcube/?_task=mail&_unlock=loading1661712396060&_framed=1&_action=send)
[28-Aug-2022 13:48:19 -0500]: <nernq34l> PHP Error: SMTP server does not support authentication (POST /roundcube/?_task=mail&_unlock=loading1661712499547&_framed=1&_action=send)
[28-Aug-2022 13:48:19 -0500]: <nernq34l> SMTP Error: Authentication failure: masked.mailserver.net
PIPELINING
SIZE 31457280
VRFY
ETRN
STARTTLS
ENHANCEDSTATUSCODES
8BITMIME
DSN (Code: 250) in /var/www/html/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /roundcube/?_task=mail&_unlock=loading1661712499547&_framed=1&_action=send)
[28-Aug-2022 13:48:56 -0500]: <nernq34l> PHP Error: STARTTLS failed (POST /roundcube/?_task=mail&_unlock=loading1661712535881&_framed=1&_action=send)
[28-Aug-2022 13:48:56 -0500]: <nernq34l> PHP Error: Invalid response code received from server (POST /roundcube/?_task=mail&_unlock=loading1661712535881&_framed=1&_action=send)
[28-Aug-2022 13:48:56 -0500]: <nernq34l> SMTP Error: STARTTLS failed: 2.0.0 Ready to start TLS (Code: 220) in /var/www/html/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /roundcube/?_task=mail&_unlock=loading1661712535881&_fram>
[28-Aug-2022 13:58:21 -0500]: <nernq34l> PHP Error: SMTP server does not support authentication (POST /roundcube/?_task=mail&_unlock=loading1661713101504&_framed=1&_action=send)
[28-Aug-2022 13:58:21 -0500]: <nernq34l> SMTP Error: Authentication failure: masked.mailserver.net
PIPELINING
SIZE 31457280
VRFY
ETRN
STARTTLS
ENHANCEDSTATUSCODES
8BITMIME
DSN (Code: 250) in /var/www/html/roundcube/program/lib/Roundcube/rcube.php on line 1795 (POST /roundcube/?_task=mail&_unlock=loading1661713101504&_framed=1&_action=send)

**Comment by alecpl** [comment]
So now it looks like SSL issue. Configuration is ok.

**Comment by stariontech** [comment]
Hm....so our mail server has not changed in years.  Our SSL certificate is updated annually.  All of our customers, and every client can connect to it with no problem.  Then a new version of Roundcube comes along and won't connect.  And that's suddenly an SSL issue?

**Comment by alecpl** [comment]
```
Aug 28 13:48:58 mail postfix/smtpd[11727]: warning: TLS library problem: 11727:error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca:s3_pkt.c:1275:SSL alert number 48:
```
It is something with PHP/SSL in your system, not much Roundcube can do about. Maybe `smtp_conn_options` could help, but it's not trivial. Also, make sure to include port in `smtp_host` to make sure it connects to the proper one.

**Comment by jrhopper** [comment]
I had this exact problem. Vendor folder was not updated via the install script.

**Comment by bigretromike** [comment]
> > Is there a procedure for "upgrading the vendor folder"? I don't see anything about how to do that.
> 
> I just rsynced the all contents of the vendor directory from the unpacked roundcubemail-1.6.0-complete.tar.gz to the vendor directory of my installation like this: `rsync -av --delete roundcubemail-1.6.0/vendor/ /srv/roundcube/vendor/`. That's it.

Thank you, removing /vendor/ and moving the one from complete package helped 👍

**Comment by Marvin261** [comment]
This solution works for me.
//$config['smtp_host'] = 'localhost:587';
$config['smtp_server'] = 'tls://yourmailserverurl:587'; // ref1

In Roundcube 1.6.7 or if you newly upgraded to latest version like 1.6.7
just remove or comment the $config['smtp_host'] and put this code $config['smtp_server'] = 'tls://yourmailserverurl:587';

PHP file directory is yourroundcubefolder/config/defaults.inc.php
