### ISSUE TITLE
Question about html editor fonts

### ISSUE THREAD

**Issue by hgjo4824** [roundcube/roundcubemail#8678]
Hello, I have installed roundcube from my company's internal mail in Korea and am using it well.

I have a question about the font of the html editor used when composing mail and writing signatures.

The font is very limited and the Hangul font does not exist.
![image](https://user-images.githubusercontent.com/80243788/185814951-a367f1d3-f313-48a0-a95e-4dceaaf34ac8.png)

Is there any way to add Korean fonts?
I checked the font list defined in font_defs through ~/roundcube/program/include/rcmail_action.php file.
I wonder if I can add it to the corresponding font list and how to add it.

If not, I'm wondering if I need to add the fonts to the tinymce editor itself, and how to add them.

thanks,

**Comment by alecpl** [comment]
I'm not a font expert, but note that we do not include fonts, we just define font-families. The rest is up to the browser/operating system. You're the first user complaining about Korean (or Asian for that matter) font issue, so maybe it's your local (your computer) issue.

Do you have problems with the plain text editor too? If this is TinyMCE issue we can do not much  about it.

**Comment by hgjo4824** [comment]
> I'm not a font expert, but note that we do not include fonts, we just define font-families. The rest is up to the browser/operating system. You're the first user complaining about Korean (or Asian for that matter) font issue, so maybe it's your local (your computer) issue.
> 
> Do you have problems with the plain text editor too? If this is TinyMCE issue we can do not much about it.

If you define a font family, is it correct that the available fonts are determined by the local fonts?
If yes, what pattern is used to define the font family?

**Comment by avatar1024** [comment]
I have exactly the same list of font the the person who open this issue. My OS is Linux and needless to say I do not use that kind of font anywhere on my system (they might be installed, but I don't use them and Firefox has a MUCH more extensive list of fonts available when I check the settings). I had to use Arial to write my emails which was painful, I'd like not to use any of that proprietary crap :). How is this set in Roundcube (how does it pull that list)?

**Comment by alecpl** [comment]
Configuration options has been implemented (#9177).
