### ISSUE TITLE
Delete, Reply etc. command button is not visible in Microsoft Edge

### ISSUE THREAD

**Issue by MahmudX** [roundcube/roundcubemail#8679]
**Reply**, **Reply All**, **Forward**, **Delete**, **Junk**, **Mark** and the **More** button is not visible in the Microsoft Edge browser.

> Here is a screenshot taken from Microsoft Edge browser

![image](https://user-images.githubusercontent.com/16564582/185097291-d2d46378-36ea-40d7-98a1-f76a3d2a6098.png)

> Here is a screenshot taken from Google Chrome browser.

![image](https://user-images.githubusercontent.com/16564582/185097472-bfc60e1c-73e8-402c-99aa-e95c9e67351b.png)

**Comment by alecpl** [comment]
What version of the browser?

**Comment by MahmudX** [comment]
Version 104.0.1293.54 (Official build) (64-bit)

**Comment by alecpl** [comment]
I'm unable to reproduce with 104.0.1293.63. Could you try an update? What plugins do you have enabled? Is the toolbar also not visible in Contacts?

**Comment by MahmudX** [comment]
Mysteriously everything was solved.
