### ISSUE TITLE
Unable to set 'Clear Trash on Logout' to 'all'

### ISSUE THREAD

**Issue by pmclaug** [roundcube/roundcubemail#8687]
In 'Settings' -> 'Server Settings'  Trying to set 'Clear Trash on logout' to all doesn't work.  It sets the logout_purge option to '1' in the database, but the form shows it being set to 'never'.

240:       case 'server':
241:           if (isset($a_user_prefs['logout_purge']) && !is_numeric($a_user_prefs['logout_purge'])) {
242:                $a_user_prefs['logout_purge'] = $a_user_prefs['logout_purge'] !== 'never';
            }

Looks like line 242 in program/actions/settings/prefs_save.php above is the culprit.   Should be :
      
     $a_user_prefs['logout_purge'] = ($a_user_prefs['logout_purge'] == 'never') ? '' : 'all';

**Comment by alecpl** [comment]
I confirm the issue on git-master.

**Comment by alecpl** [comment]
Fixed.
