### ISSUE TITLE
ManageSieve Plugin symlink creation

### ISSUE THREAD

**Issue by Github-Citizen** [roundcube/roundcubemail#8688]
The symlink created to enable sieve filters has two different behaviors.

The file that holds the rules is `filters.sieve`
The symlink to enable the rules is `.active_sieve`

The first time on new accounts, when you select [RoundCube Webmail > Settings > Filters] it creates the folders and files for sieve filters.
The symlink gets created as a full absolute path `.active_sieve -> /mnt/email/domain/user/sieve/filters.sieve`

After that, if you disable/enable the rules using [Settings > Filters > Actions > Enable/disable filter set] it creates the symlink as a relative path `.active_sieve -> filters.sieve` which i prefer.

When using mounted NFS for storage an absolute path can be problematic depending how different server instances access the mount. And if the mount name ever gets changed it would break most user's sieve filters.

I am willing to dig into the code to see if there is a solution to keep the path always relative. However i am unable to figure out where in the code the symlink gets created for the first time, or when rules get enabled/disabled. I didn't see anything in the plugin code so i suspect its buried in core rcube code some where.

**Comment by alecpl** [comment]
This part is not controlled by Roundcube. The plugin just uses managesieve protocol, what the managesieve server does internally is not something we have control over.
