### ISSUE TITLE
Attachment popup menu does not disappear after an action is selected

### ISSUE THREAD

**Issue by gszy** [roundcube/roundcubemail#8691]
Steps to reproduce:

1. Open a message that has an attachment.
2. Click the blue triangle next to the attachment name.
3. (The attachment menu is opened.)
4. Click “Download”.
5. I would expect the attachment menu to be closed/hidden at this point, but it stays open, even if later I open some other menus or dialogs.
6. The browser downloads the file.

Perhaps it is the desired behavior, but in traditional desktop applications, when one clicks on a menu entry, the menu usually disappears.

**Comment by alecpl** [comment]
Fixed.
