### ISSUE TITLE
IPV6 and IPV4 its not working

### ISSUE THREAD

**Issue by InputOutputZ** [roundcube/roundcubemail#8692]
Hi there,

I'm reporting a bug in sessions.

I noticed users session chooses to store for some reasons and instances, either IPV4 or the same wifi yet IPV6 and if one connection determines at some point to resolve and use IPV6, which it does, it will invalidate a session generated for the same user yet for IPV4 and while it should remain working as well as not from one critical point of view, as its considered if was invalidly another IP attempting to use the session while IP check is enabled, and therefore the session should be invalidated, however, I came across this situation where it seems rather more valid IP address given when I'm downloading email message file and for some reasons resolving to IPV4 for a user with session validated to IPV6, and resulting in invalidating the session as well as downloading the attachment failure.

So, I was wondering, if Roundcube, in session IPs column, to address this issue and add simultaneous IPv4 and IPv6 support for session validity logic,  i.e. when user logs in, RC checks IPV4 and IPV6 if present and supported and stores them, and validate against both IPs in all conditions if any of IPs are sent in connection, then it should be considered as valid IP address using a session that was validate to it along the other.

So far, the solutions that came to avail, either white listing IPs or forcing always connection to use IPV6 and fallback to IPV4.

Anyhow if anyone have any other, please let me know, as I would appreciate.

With thanks.

Zakaria.

**Comment by alecpl** [comment]
I'm not sure I understand the issue. Roundcube uses whatever IP is set in headers. See `rcube_utils::remote_addr()`. Are you saying that the browser changes IP address in HTTP request? How would we know that two addresses are "the same host"?

**Comment by InputOutputZ** [comment]
> I'm not sure I understand the issue. Roundcube uses whatever IP is set in headers. See `rcube_utils::remote_addr()`. Are you saying that the browser changes IP address in HTTP request? How would we know that two addresses are "the same host"?

True, getting IPV6 directly from IPV4 it is not possible, but my case, its I use VPN, that is IPV6 supported, and sometimes uses IPV4 and other IPV6 during the same Roundcube session, and remote_addr returns both IPs in different conditions leading to invalidating the session the first time, different IP is used than the one logged in with.

Yet, through RDNS we can find the two address for the same host e.g. let say a user is using a VPN, which has this IPV6 address 2a09::, and in some condition VPN sends this IPV4 185.222.222.222, to avoid unnecessarily invalidating the session, we need to validate both IPV4 and IPV6 before hand and to do this, its possible using the following:-

host 185.222.222.222
`222.222.222.185.in-addr.arpa domain name pointer public-dns-a.dns.sb.
`

Using the hostname, we can find the IPV6:-

host public-dns-a.dns.sb
```
public-dns-a.dns.sb has address 185.222.222.222
public-dns-a.dns.sb has IPv6 address 2a09::
```

If we can get these IPs included in the session table row ip column, or perhaps with Roundcube optional extra configuration for both IPV4 and IPV6 compatibility purposes, it would be better in my honest opinion, perhaps with option to enable ipv6_check beside ip_check.

**Comment by alecpl** [comment]
Personally I don't use the `ip_check` option. I think it has more issues than advantages. And I don't think it would be worth the effort to extend it even more. It should be possible to do this from a plugin.
