### ISSUE TITLE
Help icon not responsive

### ISSUE THREAD

**Issue by Bbertatum** [roundcube/roundcubemail#8694]
Using the elastic theme and with the "help" plugin enable we can see the icon is not responsive :

![image](https://user-images.githubusercontent.com/22146594/187647679-59a86c31-89f9-4dbc-8293-269df06f7598.png)
![image](https://user-images.githubusercontent.com/22146594/187647836-8354f43a-369e-4ab7-bcd2-db5c47e5d09c.png)
![image](https://user-images.githubusercontent.com/22146594/187647893-968253f7-b6f3-499b-91b6-a385d4fcc9ad.png)

Thanks for your support.

**Comment by alecpl** [comment]
What version? The icon is not supposed to be `?`. I'm unable to reproduce.
