### ISSUE TITLE
Request: SRS-compatible filter

### ISSUE THREAD

**Issue by RichardNeill** [roundcube/roundcubemail#8695]
Consider:
1. Sender,  alice@customer.com    (who has SPF correctly and strictly configured) writes to
2. Recipient, bob@supplier.com     (who has a server running Roundcube)

Bob wants to set up a vacation filter on Roundcube to copy or redirect all his mail to his manager,
3. Clara, clara@parentcompany.com

What will happen is that Clara gets Alice's mail delivered directly into her Spam folder, because of the SPF hard-fail. This cannot be fixed by Bob.

I think we need an option to have the message **remailed** rather than **redirected**, using SRS.
[If I've understood rightly, this means that the Roundcube should offer a filter to resend it from an address such as alice-customer-com-for-bob@supplier.com, or  send it direct from Bob, so that Clara's mailserver will accept the SPF record.]

Failing which, Roundcube should at least warn that a message-forward will no longer work reliably in the now-common-case where both sender and final-recipient have SPF.

**Comment by alecpl** [comment]
The filtering and redirecting is done by the imap server. Roundcube is just a managesieve client defining the rules. So, until there's some sieve extension that we could use (nothing comes from the top of my head) we can do nothing about this.

**Comment by RichardNeill** [comment]
That makes sense - but in this case, it might be helpful to add a warning so that at least the user is aware of the issue. Something like: "If you are forwarding email, and the original sender has SPF configured, then your recipient mailbox may treat the email as spam".

**Comment by alecpl** [comment]
I don't agree. It's not our responsibility to explain how email works.
