### ISSUE TITLE
Questions about version 1.5.3 LTS

### ISSUE THREAD

**Issue by fabiointegra** [roundcube/roundcubemail#8696]
Hi, we have 3 questions about this version:
1º Print in landscape in Google Chrome or Chromium: not works, only in portrait, Firefox works.
2º Print selected email more than 1 not possible, just one.
3º Print font size is soo small, but in view show ok.

Regards,
Fabio

**Comment by alecpl** [comment]
I don't see any questions ;)

1. Might be a bug. Need more info.
2. That would be feature request.
3. Need more info.

Feel free to create separate tickets for these with more details.
