### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by NunoTorradas** [roundcube/roundcubemail#8697]
First of all let me say that i'm not fluent in english...
I get this error were 1 message keep coming back as soon i mark it as "spam" and doen't stop.
I already block the e-mail, head etc... on filters and somehow this e-mail keeps coming and its not like staying just there he diseapear and apear every second.
How can i make this stop ?
Thank you

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
