### ISSUE TITLE
Make watermark.html use a specified logo

### ISSUE THREAD

**Issue by Flole998** [roundcube/roundcubemail#8699]
This line should be changed so that a logo specified using `$config['skin_logo']` is used and not the roundcube logo.

https://github.com/roundcube/roundcubemail/blob/3b16cbf3718089157f6b782b1267a9037d653f28/skins/elastic/watermark.html#L9

Same thing for the other skins aswell.

**Comment by alecpl** [comment]
It's not possible to change the image in there because this page is not a template. However,
```
// Location of the blank (watermark) frame page. By default it is the watermark.html
// file from the currently selected skin. Prepend name/path with a slash to use
// current skin folder. Remove the slash to point to a file in the Roundcube
// root directory. It can be also a full URL.
$config['blankpage_url'] = '/watermark.html';
```
