### ISSUE TITLE
Segfault when parsing punycode domains

### ISSUE THREAD

**Issue by serpentskiss** [roundcube/roundcubemail#8707]
RC version: 1.5.3
Sep 13 12:42:06 <server name> kernel: php-fpm[31921]: segfault at 0 ip 00007fbcebb1fce0 sp 00007fff16baea90 error 4 in libicui18n.so.50.2[7fbceb9a1000+1f0000]

Error when parsing punycode in the mail headers. Tested against RCv1.4.5, which parsed correctly
Example punycode domain that didn't parse: xn--s3cnx8bzcp4bt.com

**Comment by alecpl** [comment]
Looks like PHP bug. What version?

**Comment by serpentskiss** [comment]
PHP 7.4.30 (fpm-fcgi)
libicui18n.so.50.2

**Comment by alecpl** [comment]
Older versions of Roundcube did have an additional package for idna domains support. It was dropped in 1.5 and now php-intl is required instead. php-intl is based on icu library. So, this is not Roundcube bug.
