### ISSUE TITLE
Unsupported PHP version. Required PHP >= 7.3.

### ISSUE THREAD

**Issue by AJMALSARIM** [roundcube/roundcubemail#8709]
I Try on all version PHP7.2, PHP7.3, PHP8.0, and PHP8.1, but getting same error what is the solution??/

**Comment by alecpl** [comment]
You're doing something wrong. Note that usually PHP version in CLI is not the same as in the web server. You also have to restart web server (and/or php-fpm process).

**Comment by AJMALSARIM** [comment]
My current default php version
root@apps:/# php -version
PHP 8.0.22 (cli) (built: Aug 15 2022 09:47:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.22, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.22, Copyright (c), by Zend Technologies
I restarted with sudo service apache2 restart
but still getting same error
