### ISSUE TITLE
Mayor server implemented this format as standard. Please help with the complains?

### ISSUE THREAD

**Issue by martini09617** [roundcube/roundcubemail#8710]
So my server implemented this one as standard. I can't go back to the old one. My office is complaining that it is not having a clear overview. Can someone help and update?
1. The subject name is clearly visable, but you want to see the sender first in thick letters and with a higher font size.
2. All the emails should be in 1 row -> its 2 now. One of the reasons why the overview is not clear.
Can someone help?

**Comment by alecpl** [comment]
This is not going to happen.

**Comment by martini09617** [comment]
Tech persons working from tech -> instead of working from needs from the market. Always a bad call.
