### ISSUE TITLE
Problem exporting/importing emails

### ISSUE THREAD

**Issue by lusitec** [roundcube/roundcubemail#8714]
In RoundCube when we exporting/importing an email message to another mailbox within the roundcube, it's not possible and gives an error.

**It says this error:**

SERVER ERROR!
Could not load message.

If I go to cpanel, and copy the file in the file manager, it opens the email. Using the export/import function doesn't work.

**Comment by alecpl** [comment]
What do you exactly mean by "exporting/importing an email message to another mailbox"? See the error log. Also you can enable imap_debug in Roundcube to see what is going on. I suspect IMAP server issue.
