### ISSUE TITLE
Cannot print landscape mode bowsers like Google Chrome

### ISSUE THREAD

**Issue by fabiointegra** [roundcube/roundcubemail#8715]
Hi,
Using Firefox works normally using 'Print using the system dialog', but using others browsers like Google Chrome (Chromium, Edge, etc), not works, the output is portrait.

Video and print file showing what is happening:
https://integrasul-my.sharepoint.com/:f:/g/personal/fabio_integrasul_com_br/Eu8y63fs1kFHlWWNrH2scr4BzF-DJz4dygH08HkKU7mdqA?e=XkXJ1u

Regards,
Fabio Lima

**Comment by alecpl** [comment]
Does it work at all on any other pages (outside of Roundcube)? I have no idea if page html/css structure can impact this, rather it sounds like a browser bug.

**Comment by fabiointegra** [comment]
Hi Aleksander,
When using browser to others tasks and need print, landscape works in all browsers, and S.O. Windows and Linux.

Thank you for your reply.

**Comment by fabiointegra** [comment]
Hi Aleksander, 
What information is essential for this case?

**Comment by fabiointegra** [comment]
Version: Roundcube Webmail 1.5.3 LTS
Skin with problem:
Elastic
Skin working (Show option 'layout' to choose: landscape or portrait):
Larry and Classic.

Clean install, same issue.

**Comment by fabiointegra** [comment]
I solve this .... What I did was edit the file: /var/www/roundcubemail/skins/elastic/styles/styles.min.css, add @page{size:auto;} 
![image](https://user-images.githubusercontent.com/112642351/216728332-81c4db85-aca1-402f-9b05-0edd14a55d36.png)

Regards.
