### ISSUE TITLE
Enigma: What are the possible pgp drivers ?

### ISSUE THREAD

**Issue by mikygee** [roundcube/roundcubemail#8717]
Hello,

I have this directive in plugins/enigma/config.inc.php
`$config['enigma_pgp_driver'] = 'gnupg';`
But what are the different possible enigma_pgp_driver possibilities ? Is it documented somewhere ?

So far I have installed pgp5 on openbsd
```
# pkg_info | grep pgp
pgp-5.0ip2          Pretty Good Privacy 5.0i (world wide use)
```

Regards

**Comment by alecpl** [comment]
There's only one working driver currently, 'gnupg'. And gnupg installed on the server is required.

**Comment by mikygee** [comment]
Thank you for your answer.
