### ISSUE TITLE
Cannot connect when the data is set to a non local machine!

### ISSUE THREAD

**Issue by Haruka-Ayase** [roundcube/roundcubemail#8718]
When I set the other database in the LAN as the Roundcube database, it cannot complete the connection, and I will be prompted [DSN (write): NOT OK (SQLSTATE [HY000] [2002] php_network_getaddresses: getaddressinfo for 10.0.. 0.2 failed: Name or service not known)];

    Check DB config
    DSN (write):  NOT OK(SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for 10.0..0.2 failed: Name or service not known)
    Make sure that the configured database exists and that the user has write privileges
    DSN: mysql://mail:mailHjgandfeng.0@10.0..0.2/mail

**I can log in to the database through the command line.**

    root@Public:/var/www/mail/config# mysql -u mail -p -h 10.0.0.2 -D mail
    Enter password: 
    Welcome to the MySQL monitor.  Commands end with ; or \g.
    Your MySQL connection id is 1693
    Server version: 8.0.30-0ubuntu0.22.04.1 (Ubuntu)

    Copyright (c) 2000, 2022, Oracle and/or its affiliates.

    Oracle is a registered trademark of Oracle Corporation and/or its
    affiliates. Other names may be trademarks of their respective
    owners.

    Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

    mysql> 

I performed the following operations in the second step:

    MySQL              | Database type
    10.0..0.2          | Database server (omit for sqlite)
    mail               | Database name (use absolute path and filename for sqlite)
    mail               | Database user name (needs write permissions)(omit for sqlite)
    mailHjgandfeng.0   | Database password (omit for sqlite)
    rou_               | Optional prefix that will be added to database object names (tables and sequences).

How do I continue the installation process?

**Comment by johndoh** [comment]
It looks like you made a typo. `10.0..0.2` is not a valid IP address because of double dot in the middle. Then you get a PHP error because PHP cannot resolve the hostname that it thinks you entered.
