### ISSUE TITLE
elastic skin does NOT display IMAP flags, larry theme does

### ISSUE THREAD

**Issue by lrosenman** [roundcube/roundcubemail#8721]
Is there a way to get the elastic skin to display the IMAP flags?

**Comment by alecpl** [comment]
It definitely displays "flagged" state. So, what flags? Are you using some plugin?

**Comment by lrosenman** [comment]
<img width="1105" alt="Screen Shot 2022-09-19 at 9 32 57 AM" src="https://user-images.githubusercontent.com/2868525/191042688-dbec6776-e836-4a3b-b78a-9521a8f7fec9.png">

the only plugin is thunderbird_labels.

**Comment by lrosenman** [comment]
that is with the "Larry" theme, and with "elastic" they do NOT display.

I'm referring to the "GITHUB" and "ROUNDCUBEMAIL" flags above on the top right.

**Comment by alecpl** [comment]
So, this is an external plugin. We do not support "custom" IMAP keywords.

**Comment by lrosenman** [comment]
the larry skin shows it, why?

**Comment by alecpl** [comment]
This is up to the plugin to implement. The plugin is old, created when there was no Elastic, however I see some Elastic support in the plugin code. So, it might be a bug or just not implemented https://github.com/mike-kfed/roundcube-thunderbird_labels/issues/58
