### ISSUE TITLE
Missing details of MS Teams invitation

### ISSUE THREAD

**Issue by FH-pro** [roundcube/roundcubemail#8722]
I'm using the github web browser for my emails. However when I receive an MS Teams invitation I cannot see any details such as the timing.

**Comment by FH-pro** [comment]
I use the latest Firefox version. As far as I know I haven't installed any additional plugins.
![Screenshot missing Teams details](https://user-images.githubusercontent.com/114004708/191955797-98181fff-eef2-4183-b0ac-0bd4638fbfd1.JPG)

What is expected and is missing? Well, I would like to see the proposed date and time of an invitation before accepting it. As you can see on the attachment I can only recognize that I received a Teams invitation but I cannot see the date and time.

**Comment by FH-pro** [comment]
![Screenshot missing Teams details](https://user-images.githubusercontent.com/114004708/191956411-133edb41-b5e5-4ed4-8125-fd51e72730c9.JPG)

**Comment by FH-pro** [comment]
Neither can I accept or decline the meeting request.

**Comment by alecpl** [comment]
There's no calendaring features in Roundcube. You'd need some calendar plugin.

**Comment by FH-pro** [comment]
And which calendar plugin can I use and where can I find it?
