### ISSUE TITLE
Open email in new tab/windows without any tools

### ISSUE THREAD

**Issue by WojakGra** [roundcube/roundcubemail#8723]
Hi,
Is there a way to set something like read only mode for viewing emails without any tools?

![obraz](https://user-images.githubusercontent.com/39022177/191522659-32f82b96-21d0-4482-982c-ac76f68f3456.png)

**Comment by alecpl** [comment]
No. You can try `$config['disabled_actions']`, but it might not handle everything.

**Comment by WojakGra** [comment]
Used parameters _extwin=1 and _framed=1 in url. Using it shows the way I needed
