### ISSUE TITLE
Installation of calendar plugin

### ISSUE THREAD

**Issue by FH-pro** [roundcube/roundcubemail#8727]
Hi,

I am sure this questions has been treated before but still I couldn't find the right solution. How can I install and use a calendar plugin so that I can see the date and time of an invitation and reply to it? I don't use any mobile version on my phone. Only Firefox on my Windows Laptop.

**Comment by alecpl** [comment]
The plugin needs to be installed on the server where Roundcube is. We do not provide this level of support here.
