### ISSUE TITLE
(Broken Plugin)

### ISSUE THREAD

**Issue by iotalol** [roundcube/roundcubemail#8730]
Hello, I have an issue with roundcube. I am using a modified verison of elastic which may be the issue but when I try to use enigma I get this error in /var/log/roundcubemail/errors.log `PHP Error: Error loading template for enigma.keys in /usr/local/lib/roundcubemail/program/include/rcmail_output_html.php on line 804 (GET /mail/?_task=settings&_action=plugin.enigmakeys)` can anyone help? Thanks!

**Comment by alecpl** [comment]
You need `"extends": "elastic"` in your skin's `meta.json` file. If the skin is not "extending" a skin known to the plugin you have to create templates inside your skin (under `skins/<skin>/plugins/enigma/templates/`)

**Comment by iotalol** [comment]
Yeah, I have solved this issue yesterday forgot to close it, Cheers!
