### ISSUE TITLE
Toolbar for mail not accessible if mail body is too wide

### ISSUE THREAD

**Issue by zachol72** [roundcube/roundcubemail#8731]
Steps to reproduce:

1. Make sure to receive an email containing an URL at least 450 characters long.
2. Double-click on email in Inbox to open the mail without folders or Inbox showing.
3. Toolbar buttons will not show on smaller screens as they are centered over the email body and mail pane is not scrollable.

Perhaps a solution would be to align the toolbar content to the left?

![Screenshot_1](https://user-images.githubusercontent.com/38487567/192951607-0ee1f1af-6356-45a3-9759-81661fdeb46b.png)
![Screenshot_2](https://user-images.githubusercontent.com/38487567/192951609-06f7e693-1188-407a-8aa3-eaa9490e4828.png)

**Comment by alecpl** [comment]
I'm unable to reproduce. What version? It might be also one of the external plugins.

**Comment by zachol72** [comment]
Roundcube Webmail 1.5.2

Plugins:
archive | 3.5 | GPL-3,0+ |  
calendar | 3.5.11 | AGPL-3,0 | 
carddav | v4.3.0 | GPL-2,0 | 
cpanellogin | 11.58 | cPanel License (Proprietary) |  
cpanellogout | 11.58 | cPanel License (Proprietary) |  
filesystem_attachments | 1.0 | GPL-3,0+ |  
jqueryui | 1.12.0 | GPL-3,0+ |  
libcalendaring | 3.5.11 | AGPL-3,0 | 
libkolab | 3.5.11 | AGPL-3,0 | 
markasjunk | 2.0 | GPL-3,0+ |  
return_to_webmail | 11.106 | cPanel License (Proprietary)
