### ISSUE TITLE
Are there any plans to add expanding the config vars like %u in the additional_message_headers plugin?

### ISSUE THREAD

**Issue by Popyllol** [roundcube/roundcubemail#8732]
Hi,
I would like to use %u in an additional X-Header for later preocessing in our mail server.
To get it work I patched additional_message_headers.php like this:
```
--- additional_message_headers.php.orig	2022-09-29 13:30:23.249914271 +0200
+++ additional_message_headers.php	2022-09-29 13:33:32.497935478 +0200
@@ -38,6 +38,19 @@
         // additional email headers
         $additional_headers = $rcube->config->get('additional_message_headers', []);
 
+	// Expand the % config variables
+	$search = array(
+		'%u',
+		'%l',
+		'%d'
+	);
+	$replace = array(
+		$_SESSION['username'],
+		$rcube->user->get_username('local'),
+		$rcube->user->get_username('domain')
+	);
+	$additional_headers = str_replace($search, $replace, $additional_headers);
+
         if (!empty($additional_headers)) {
             $args['message']->headers($additional_headers, true);
         }
```
Is it planned to get such functionality in later versions of this plugin?
Thanks in advance,
   Lars

**Comment by alecpl** [comment]
Well, if we do this we would need a way to disable that, in case you wanted e.g. `%u` in the string not to be replaced.

FYI, better to use `$rcube->get_user_name()` and/or `$rcube->get_user_email()`.

**Comment by Popyllol** [comment]
Hi alecpl,
Thank you for your thoughts!
The %u as %u without replacement is often solved through double the % (%%u) like in printf. Could this be a solution you could accept?
Thank you for $rcube->get_user_name() and $rcube->get_user_email() I will change it in my code.
Greetings,
   Lars

**Comment by alecpl** [comment]
Yes. Please, create a pull request.

**Comment by Popyllol** [comment]
Hi Aleksander,
I created pull https://github.com/roundcube/roundcubemail/pull/8746 .
Greetings,
  Lars

**Comment by Popyllol** [comment]
Hi Aleksander,
is there a timeline when this will get into the master code?
Is there something missing?
Greetings,
   Lars

**Comment by Popyllol** [comment]
Hi,
is there anything I have to to do to get this pull #8746 commited?
Greetings,
  Lars

**Comment by alecpl** [comment]
Merged.
