### ISSUE TITLE
OAuth invalid refresh token

### ISSUE THREAD

**Issue by jtuta** [roundcube/roundcubemail#8734]
Hello,

I would like to open a discussion regarding OAuth and methods ` request_access_token(...)` and `refresh_access_token(...)`. Lets imagine a scenario that occurred in my deployment:

- Access token is not valid any more (time of validity has elapsed)
- RC tries to get new access token via refresh token
- And now lets imagine that for some reason refresh token is not either correct or valid any more (for example, OAuth server invalidated this token).
- When such event ocures - request to the server (in my case Keycloak server) fails with (HTTP code 400 and body: `{"error":"invalid_grant","error_description":"Token is not active"},`) and RequestException is thrown [here](https://github.com/roundcube/roundcubemail/blob/release-1.6/program/include/rcmail_oauth.php#L373) and gets cached [here](https://github.com/roundcube/roundcubemail/blob/release-1.6/program/include/rcmail_oauth.php#L402)
- On the fronted this produces an errors `Connection with IMAP server failed` and `Server error AUTHENTICATE XOAUTH2: A00001 NO [UNAVAILABLE] Temporary authentication failure`.
- The problem is that now client, cannot resume OAuth session (due to bad token) and cannot kill current roundcube session (logout button does not "work") in order to initialize new (fresh) login. Only option is to wait for RC session to expire or to go in developer tools and manually delete all the session cookies, in order to initialize new RC session.

Would you think that it might be wise to for example kill RC session in this `catch() {}` block? I am fully aware that this block would (and should) also catch `RequestExceptions` if for example OAuth server is really unavailable (due to e.g. network issues) and in such cases killing a session with perfectly fine refresh token would not be wise. 

I'd love to hear your take on this topic

**Comment by thomascube** [comment]
Fixed: kill session when receiving a 4xx response
