### ISSUE TITLE
OAuth2 plus additional accounts not wirking

### ISSUE THREAD

**Issue by hirsm** [roundcube/roundcubemail#8735]
I use OAuth2 for entering my mailbox with Roundcube. I wanted to add an additional account via [ident_switch plugin](https://bitbucket.org/BoresExpress/ident_switch/src/master/) to switch between accounts in one session.

When I try switching to the second account, login fails with this error:

``
IMAP Error: Login failed for <username> against tls://mail.example.com from <IP address>. AUTHENTICATE XOAUTH2: A0002 NO no mechanism available in /srv/data/www/html/roundcube/program/lib/Roundcube/rcube_imap.php
``

Obviously, Roundcube tries to connect to this server via OAuth2, too, which has to fail. The entered password for the second account is ignored.

Same behaviour with [additional_imap](https://github.com/texxasrulez/additional_imap) plugin.

**Comment by alecpl** [comment]
I'm afraid this has to be handled by these plugins.
