### ISSUE TITLE
550 Outgoing mail from "" has been suspended.

### ISSUE THREAD

**Issue by ilaahi** [roundcube/roundcubemail#8737]
Dear Sir,

Greetings of the day,

It is stated that i am facing a technical problem in my email (
[Info@ilaahi.com](mailto:Info@ilaahi.com)) from last few days. I am facing an error 550 Outgoing mail
from "(http://ilaahi.com/)" has been suspended when i compose email to anyone. My
incoming mails are smoothly working but outgoing mail service is not
working and appearing error 550.
In this regard it is requested that kindly assist me to resolve this issue
as this is my official email and my company's business is based on this, i
shall be very grateful for your prompt response.

Screenshot of error is attached here with.

Best Regards
Ilaahi International
![gmail](https://user-images.githubusercontent.com/114980551/193754969-1f4990c4-6969-40f7-a555-d4b04a70f29f.PNG)
![webmail send](https://user-images.githubusercontent.com/114980551/193754978-29ba58db-bc71-4ad9-89fb-cec52fa60514.PNG)
![webmail](https://user-images.githubusercontent.com/114980551/193754981-628e596e-37d8-4394-8102-4e54daba5b3b.PNG)

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

**Comment by ilaahi** [comment]
my hosting is coninue not e

> If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.
> 
> Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

my website hosting is continue not expaire
