### ISSUE TITLE
Show email adress in mailbox instead the name in list

### ISSUE THREAD

**Issue by wdburgdorf** [roundcube/roundcubemail#8740]
There is this ancient thread: https://github.com/roundcube/roundcubemail/issues/4344
E-Mail address can be displayed in individual messages. It should be possible to also see and sort by the address in lists.

**Comment by alecpl** [comment]
There's a setting to display both name and address, but it works only in mail preview not on the list. There's not enough room on the list to do this. You can see the email if you move mouse pointer over the sender name. I don't think we'll change that.

**Comment by wdburgdorf** [comment]
That is very unfortunate. If you don't want to put in the work to change it, I get that. I don't know how much time it would take you and how difficult you would find it to do that. But not enough room? If the address is shown, it takes just about the same amount of space as a name, which can be long, too. Most of the time the address is much more useful than the name, for me, at least. I would not have asked here, if I did not find it really important. I'd hope you'd at least put it up for debate. Thanks for your efforts!
