### ISSUE TITLE
Layout window is changing to widescreen

### ISSUE THREAD

**Issue by glraj70** [roundcube/roundcubemail#8741]
Hi,
After migrating the roundcube (1.4.11v) application to new server, few users layout windows is automatically changing to  widescreen.

Even after manually changing the layout window after few days the layout window changes to widescreen.

We have changed default to "list" in config.php , still this issue is not getting resolved.

Kindly suggest where is the issue happening 

Regards,
Rajesh G.L

**Comment by alecpl** [comment]
1.4 is not supported anymore.
