### ISSUE TITLE
You can login in your email with lowercase and uppercase symbols

### ISSUE THREAD

**Issue by zhan-dev** [roundcube/roundcubemail#8744]
Hello

When you login in your mail you can use different combination with lowercase and uppercase symbols and it works - you are in.

But the main problem is:
When you create your email - it is always creates in lowercase style. (for example TEST@mail.com = test@mail.com) - auto lower case.
But if you login in your email with upper case style or combo (lowercase + uppercase) - it also OK. 
You can do it like (TeSt@mail.com or tesT@mail.com) - and you are in. 
You also can got emails but your settings are different in your mail.

I mean if you login like test@mail.com your settings is not equal TeSt@mail.com and not equal tesT@mail.com.
You can create 3 different settings presets. No synchronization with email settings

So in case when I changed some settings like an admin in my colleagues mail, I do it in "lowercase mail" as default email which was created by me.
But if my team member login with uppercase symbols or some combo (lower letters + upper letters) he lose the settings what I added to his email.

The screen which illustrate this problem at the bottom of this page
(sorry but I deleted some info at this screens. Hope you can get the main idea)

To illustrate this problem I used a mail "signature". It is also works for any mail "settings"

1 email with 1 password but no synchronization with email settings

![image](https://user-images.githubusercontent.com/64002983/195573435-6cc205d2-d670-40e9-bd0e-694fa122f4ab.png)
![image](https://user-images.githubusercontent.com/64002983/195573716-4e05be36-032d-46c1-8d2a-da034c041ef8.png)

**Comment by alecpl** [comment]
```
// Forces conversion of logins to lower case.
// 0 - disabled, 1 - only domain part, 2 - domain and local part.
// If users authentication is case-insensitive this must be enabled.
// Note: After enabling it all user records need to be updated, e.g. with query:
//       UPDATE users SET username = LOWER(username);
$config['login_lc'] = 2;
```
