### ISSUE TITLE
Feature Request: Favorite folders to display them on top of the list

### ISSUE THREAD

**Issue by MarcoRemy** [roundcube/roundcubemail#8745]
Hi everyone. May I'm not the only one managing a lot of folders. Some of them are used more frequently than others. If they are located at a lower part of the ordered list you have to scroll all the way down to interact with them. To improve UX it would be great to kind of favorite [⭐] folders so they would be displayed/mirrored first in the list.

**Comment by alecpl** [comment]
Duplicate of #5003.
