### ISSUE TITLE
elastic skin: There's no priority icon in messages list.

### ISSUE THREAD

**Issue by AK666** [roundcube/roundcubemail#8751]
roundcubemail-1.6.0-complete

config.inc.php
`// These cols are shown in the message list. Available cols are:

// subject, from, to, fromto, cc, replyto, date, size, status, flag, attachment, priority

$config['list_cols'] = ['subject', 'status', 'fromto', 'date', 'size', 'flag', 'attachment', 'priority'];
`

server response
`this.add_message_row(51
 ,{"subject":"test"
  ,"fromto":"<span class=\"adr\"><span title=\"test@test.local\" class=\"rcmContactAddress\">test@test.local</span></span>"
  ,"date":"Today 00:03"
  ,"size":"370 b"
  ,"authres_status":""
  }
 ,{"flagged":1
  ,"seen":1
  ,"label3":1
  ,"prio":2
  ,"ctype":"text/plain"
  ,"mbox":"Drafts_imap"
  ,"extra_flags":{"tb_labels":["LABEL3"]}
  }
 ,false);

`

**Comment by alecpl** [comment]
That's right, you can't set/change columns for Elastic. Imo, priority is not a common feature and you're first person missing it since the skin is available. I'd rather remove the priority selector from the mail compose form and let someone to write a plugin for this.

**Comment by AK666** [comment]
oh, no! please didn`t do that!

please add reaction only to "prio" 1 (higest) and 2 (high) 
for example add prioN to id="msgicnrcmrowNTE" :
`<span id="msgicnrcmrowNTE" class="msgicon status prio{prio}" title=""></span>`

and to .css:

.messagelist td.subject span.msgicon.status.prio1:after,
.messagelist td.subject span.msgicon.status.prio2:after {
  cursor: pointer;
  font-size: 1rem;
  display: block;
  float: left;
  margin: 0 0.25rem 0 0;
  font-weight: 900;
  text-decoration: inherit;
  speak: none;
}
.messagelist td.subject span.msgicon.status.prio1:after {
  content: "!!";
}
.messagelist td.subject span.msgicon.status.prio2:after {
  content: "!";
}

**Comment by AK666** [comment]
>  you're first person missing it

i think it's wrong, 
most admins Googled: "roundcube mail priority show" , got no answers and do nothing else
there are has periodic weak attempts to solve this problem that the ends with "Ticket reopened with add options/leables Feature Request"
