### ISSUE TITLE
Enigma Plugin - Every Email Requiring Password Entry to Send and Open

### ISSUE THREAD

**Issue by micclay** [roundcube/roundcubemail#8752]
My Managed VPS tech support installed a "pre-downloaded" version of Enigma within an up-to-date version of WHM/cPanel.  Public keys were received and imported successfully.  However, I still get prompted to enter my Password every time I attempt to send or open an email.  Without entering the password, received emails remain encrypted and composed emails won't send.

VPS tech support replicated the issue as well.

Please advise!  We really need this to work automatically, so automated emails containing private info will be automatically encrypted when sent.

Thanks!!!

**Comment by alecpl** [comment]
There is optional support for passwordless keys since Roundcube 1.5, but you'd have to create the keys manually and import them. I guess this feature could be extended to allow passwordless keys generation.

Another option is Preferences > Encryption > Keep private key passwords for: the whole session, so you enter the password only once per session.

**Comment by micclay** [comment]
Thanks for the quick reply; much appreciated!!

We actually need the plugin to work automatically for instances triggered at unknown times, so I'll try creating them manually and importing them for passwordless keys.  I'm assuming I can simply create the keys using another service, then import the result, as simple as that.  If there's anything else that needs to be implemented for this to be fully configured, please let me know.

Thanks again!!

**Comment by micclay** [comment]
Unfortunately, Roundcube is still requiring a password to send, even though I successfully created a passwordless key using:  "gpg --batch --passphrase '' --quick-gen-key USER_ID default default" and imported it into Roundcube.  I tried simply clicking "OK" since there's no password associated with the Key, but that didn't work either.

Any recommendations?  Thanks!

**Comment by alecpl** [comment]
I said it's optional. `$config['enigma_passwordless'] = true;`

**Comment by micclay** [comment]
Is there a list of Enigma Options somewhere, so we have them all?  For example, can we configure passwordless for an individual email address as opposed to it being a global setting?  Thanks!

**Comment by alecpl** [comment]
You can't. The list of all options in config.inc.php.dist file.
