### ISSUE TITLE
Use encrypted mysql connection (in password plugin)

### ISSUE THREAD

**Issue by leahoswald** [roundcube/roundcubemail#8753]
The database for my mailserver is running on another server. Therefore I want to use the TLS encryption mariadb/mysql is providing.
For me it looks like there is no option in roundcube and especially the password plugin to tell the database layer to use SSL/TLS and to require it so there isn't a password leakage.  

If it is possible, please tell and document how. If not please add an option to enable encrypted database connections.

**Comment by alecpl** [comment]
I never tried that, but it is supported.
```
// Note: Various drivers support various additional arguments for connection,
//       for Mysql: key, cipher, cert, capath, ca, verify_server_cert,
//       for Postgres: application_name, sslmode, sslcert, sslkey, sslrootcert, sslcrl, sslcompression, service.
//       e.g. 'mysql://roundcube:@localhost/roundcubemail?verify_server_cert=false&ca=/path/to/ssl-cert.pem'
```

**Comment by leahoswald** [comment]
Ok, not that intuitive but will give it a try.
