### ISSUE TITLE
Undefined constant "INTL_IDNA_VARIANT_UTS46" after php update to 8.1

### ISSUE THREAD

**Issue by efelon** [roundcube/roundcubemail#8755]
Roundcube Webmail 1.6.0
nginx/1.14.2

After switching php from 7.3, where everything worked as expected, to 8.1 I get the following error: 
(`php composer.phar update --no-dev` was executed with php8.1 after the switch)

> PHP Fatal error:  Uncaught Error: Undefined constant "INTL_IDNA_VARIANT_UTS46" in /var/www/webmail/program/lib/Roundcube/rcube_utils.php:1146

I could fix the error like this:

```
        // $variant = INTL_IDNA_VARIANT_UTS46;
        $variant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : null;
```

Otherwise roundcube refuses to start.

**Comment by alecpl** [comment]
Looks like some ancient ICU versions might not have this constant defined. https://github.com/guzzle/guzzle/issues/2448

**Comment by efelon** [comment]
This is in my composer.json: `"guzzlehttp/guzzle": "^7.3.0",`
An this is what composer reports:
```
# php composer.phar show | grep guzzle
guzzlehttp/guzzle                    7.4.5              Guzzle is a PHP HTTP client library
guzzlehttp/promises                  1.5.1              Guzzle promises library
guzzlehttp/psr7                      2.4.0              PSR-7 message implementation that also provides common utility methods
```

**Comment by tnt** [comment]
> I could fix the error like this:
> 
> ```
>         // $variant = INTL_IDNA_VARIANT_UTS46;
>         $variant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : null;
> ```

Thanks for this. Works perfectly for me

**Comment by alecpl** [comment]
Hmmm... On my PHP 8.1 using `null` creates problems: `PHP Deprecated:  idn_to_ascii(): Passing null to parameter #3 ($variant) of type int is deprecated` and the result is empty. Using `0` does not print a warning, but causes `idn_to_ascii()` to return empty result. So, proposed solution does not sound right to me.

I wonder whether `INTL_IDNA_VARIANT_2003` constant could be used instead. Does it exist on your systems? However, it's deprecated since PHP 7.2.

**Comment by efelon** [comment]
Sorry for the late reply @alecpl , no the variable `INTL_IDNA_VARIANT_2003` is also not available.
```
[22-Nov-2022 15:19:08 Europe/Berlin] PHP Fatal error:  Uncaught Error: Undefined constant "INTL_IDNA_VARIANT_2003" in /var/www/webmail/program/lib/Roundcube/rcube_utils.php:1147
```

In the meantime I tested the same behaviour on Debian bullseye with the same result, but slightly newer version of guzzle:
```
guzzlehttp/guzzle                  7.5.0              Guzzle is a PHP HTTP c...
guzzlehttp/promises             1.5.2              Guzzle promises library
guzzlehttp/psr7                      2.4.3              PSR-7 message implemen...
```

**Comment by efelon** [comment]
Couldn't [symfony/polyfill-intl-idn](https://packagist.org/packages/symfony/polyfill-intl-idn) provide this variable? Or do you think there is just a OS php package missing?

**Comment by alecpl** [comment]
I thought you have 'intl' extension installed, and still got this error. But if do not have it, then you have to install it. It is required.

**Comment by efelon** [comment]
Yes indeed, `php8.1-intl` was missing and fixes the error. 

I didn't find a reference in the [requirements](https://github.com/roundcube/roundcubemail/wiki/Install-Requirements), and on the [installation page for Debian](https://github.com/roundcube/roundcubemail/wiki/Installation#debian) I missed it, sorry and thank you for your help.

**Comment by Code-TT** [comment]
`$variant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : null;`

This helped! Thank you!

**Comment by Sailing74** [comment]
Not entirely sure why this issue is closed. I just had the same problem on an Ubuntu 22.04 LTS with Roundcube 1.6.6 pop up. The solution suggested here works to fix the issue.

**Comment by priitl802** [comment]
Same thing.
`$variant = defined('INTL_IDNA_VARIANT_UTS46') ? INTL_IDNA_VARIANT_UTS46 : null;` 
saved the day.

Just upgraded php and it's modules to 8.2.19 over 8.2.14 and it broke down, Debian 11, Roundcube 1.6.5.

**Comment by jbellionjourdan** [comment]
Same today for me with php 8.3.8 on ArchLinux. intl is enabled in `/etc/php/php.ini`

**Comment by jonhnet** [comment]
Same today when apt-get upgrading a kinda-stale Debian bookworm system running a manually-installed roundcubemail-1.6.9.

My install had no `\`. The [current github does](https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_utils.php#L1230), but I pasted it into my intsall and it doesn't help.

The `:null` patch above got me back in business.

**Comment by Lutex** [comment]
If you're experiencing errors related to the `intl` extension while using RoundCube with PHP 8.x, follow this step-by-step guide to install and configure the extension properly. This solution was tested with PHP 8.2 but works with any recent version.

> The solution follows what was discussed in the RoundCube forum post, which points to this topic on GitHub, and which I expand upon below.
>
> "It's not specifically a Roundcube issue. It has to do with PHP's intl extension and the version of ICU you have on your system."  
> https://www.roundcubeforum.net/index.php?topic=30316.msg77140#msg77140


---

### 1️⃣ Install the required dependencies

#### Debian/Ubuntu:
```bash
apt-get update
apt-get install -y libicu-dev
```

#### CentOS / AlmaLinux / Red Hat:
```bash
yum install -y libicu libicu-devel
```

---

### 2️⃣ Install the `intl` extension for your PHP version

#### If you're using **aaPanel**:
You can install it via the panel or terminal:
```bash
bash <(curl -sSL https://node.aapanel.com/install/3/intl-ols.sh)
```

#### Or directly using `pecl`:
```bash
/www/server/php/82/bin/pecl install intl
```

> ⚠️ Replace `82` with your actual PHP version.

---

### 3️⃣ Edit `php.ini` to enable the extension

Find the path to your `php.ini` using `phpinfo()`.

Example (LiteSpeed):
```
/usr/local/lsws/lsphp82/etc/php/8.2/litespeed/php.ini
```

Add (or uncomment) the line:
```ini
extension=intl
```
Or:
```ini
extension=intl.so
```

---

### 4️⃣ Restart your PHP service

```bash
/etc/init.d/php-fpm-82 restart
```

---

### 5️⃣ Confirm the installation

```bash
php -m | grep intl
```

If you see `intl` in the result, everything is working ✅

You’ll also see an `intl` section in your `phpinfo()` output.

---

### ✅ Now you can access RoundCube without issues!
