### ISSUE TITLE
Support PKCE with OAuth2

### ISSUE THREAD

**Issue by JE4GLE** [roundcube/roundcubemail#8757]
[PKCE](https://oauth.net/2/pkce/) is an important security measure of the OAuth 2.0 workflow.

Roundcube currently does not support it and I would suggest integrating it.

Thank you!

**Comment by EdouardVanbelle** [comment]
Hello @JE4GLE, good idea !
As I am currently working on OAuth improvements, I will check your request

**Comment by Neustradamus** [comment]
@EdouardVanbelle: Nice idea!

**Comment by alecpl** [comment]
Implemented.

**Comment by vaminakov** [comment]
Seems it does not working with some IAMs.
I'm using zitadel, and when I set roundcube to use PKCE, the error in logs:
`roundcube[]: {"error":"invalid_request","error_description":"code_challenge required"}`
