### ISSUE TITLE
Unopened emails are showing as already read, please help

### ISSUE THREAD

**Issue by dragondoodles** [roundcube/roundcubemail#8763]
Hi. I am having trouble with my email. When I open my account for the day, new emails that I have received are showing up as already read. (As in, their subject line doesn't have bolded font the way unopened emails usually have). But while I am in Webmail with it actively opened on my computer, and new emails arrived, they do show up as bolded (unread). 

I went into settings and disabled automatically mark email as read when opened so that way I have to manually mark each email as read, hoping that would help the problem. It has not. 

As far as I know, no one else is accessing this account.

I want to make sure I don't miss any new emails that could be important.

Assuming this is a bug. Can anyone help me out? Thanks so much.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
