### ISSUE TITLE
Can't open attachments, extra line in file

### ISSUE THREAD

**Issue by Munrok** [roundcube/roundcubemail#8764]
I have encountered a rather strange problem: I cannot open attachments in Roundcube (as well as preview them). An "extra" line is added to the image files, which causes a problem with opening the files. After downloading the file and removing the line, the problem disappears.
This is not a problem with httpd. It also occurs when running with php -s. I checked on different versions of PHP: no change.

**Comment by alecpl** [comment]
I remember in the old days there was an issue that an empty line outside of `<?php ?>` code in plugin config files could cause that. It's shouldn't be an issue anymore, but I'd check that. Maybe in other php files too. So, check any file you modified.

**Comment by Munrok** [comment]
Yes, that was the reason, thank you.
