### ISSUE TITLE
Feature request: add "redirect" option (as opposed to "forward")

### ISSUE THREAD

**Issue by seanm** [roundcube/roundcubemail#8765]
As best as I can tell, Roundcube does not have a "redirect" feature, though of course it does have a "forward" feature.

It would be nice to support "redirect" too.  As I'm sure you're aware, it is sometimes (but not always) preferable to forwarding.

**Comment by alecpl** [comment]
Both are supported, so I'm not sure what are you talking about.

**Comment by seanm** [comment]
Oh! I'm clearly just not finding it then.  Where is the option to redirect a message and what's it labelled?

**Comment by alecpl** [comment]
Actually... What do you mean by 'redirect'? From what I see we support standard Sieve 'redirect' command for forwarding. So, how your 'redirect' is different from what we have?

**Comment by seanm** [comment]
Sorry for the delayed reply...

I'm having trouble finding any technical description of the differences between Forward and Redirect.  One not very helpful link: https://www.lifewire.com/redirecting-email-messages-1166732

But the distinction exists in most email clients I know, for example:

Apple Mail.app:

![image](https://user-images.githubusercontent.com/117260/205961740-881e82d4-a534-4862-8cd9-bd76bc6b16cb.png)

MailMate.app:

![image](https://user-images.githubusercontent.com/117260/205961484-97b2be70-90b0-44b8-8fed-1f5c10363439.png)

Thunderbird.app:

![image](https://user-images.githubusercontent.com/117260/205961638-b59bc968-c925-4c9b-87ff-d22400b64d80.png)


We use Redirect a lot, as the message gets better filtered by the receiver's mail rules in our experience.  The message also doesn't get mangled with a bunch of `<` quotation characters either.

**Comment by manfredu** [comment]
Am 2022-12-06 23:29, schrieb Sean McBride:

> That does seems like the same thing, thanks!
> 
> Is there a reason you don't use the same nomenclature ("Redirect") as 
> other MUAs?

Also the German translation "Erneut senden (falls unzustellbar)" (Resend 
(if undeliverable)) is completely misleading.
