### ISSUE TITLE
Error 500 on notofication email from Nextcloud

### ISSUE THREAD

**Issue by 80kk** [roundcube/roundcubemail#8768]
Hi,
I found today that Roundcube is throwing 500 error on one type of emails sent from Nextcloud with notification about activity.
Nginx log:
```
1.2.3.4 - - [29/Oct/2022:14:51:52 +0200] "GET /rc/?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=23356&_mbox=INBOX&_framed=1&_action=preview HTTP/2.0" 500 634 "https://mail.domain.com/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
```
PHP logs:
```
mailcowdockerized-php-fpm-mailcow-1  | 172.22.1.3 -  29/Oct/2022:15:09:19 +0200 "GET /rc/index.php" 500
```
Unfortunately I can't get more logs despite having this in my config:
```
$config['log_dir'] = 'logs/';
$config['debug_level'] = 1;
$config['sql_debug'] = true;
$config['imap_debug'] = true;
$config['smtp_debug'] = true;
$config['temp_dir'] = '/tmp';
```
RC is running within Mailcow's PHP-FPM container but I can't see the logs written anywhere.

**Comment by alecpl** [comment]
Does it work with all plugins disabled? What PHP version? I'm afraid we'll need the error message.

**Comment by 80kk** [comment]
PHP is:
```
PHP 8.0.19 (cli) (built: May 25 2022 20:07:43) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.19, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.19, Copyright (c), by Zend Technologies
```
How can I force RC to start writing logs despite already having the config above?

**Comment by 80kk** [comment]
I did manage to Roundcube start writing logs but I can't find any errors neither in sql.log, smtp.log, imap.log nor sendmail.log. I also found that I can't reply to random email (one so far). RC UI returns 500 saying `no response from server` but in fact email was sent. Does the `des_key` value is stored in the DB? If so is it possible to retrieve it?

**Comment by 80kk** [comment]
The problem was with `des_key` length (copy and paste issue) but it will be great to have this kind of error reported in the logs.
