### ISSUE TITLE
unquoted password with tilde (~) char

### ISSUE THREAD

**Issue by suprune20** [roundcube/roundcubemail#8772]
Roundcube does not quote a password if it contains ~ character. And our courier imap server, when it receives from roundcube the following login command:

LOGIN test@_our.org_ `Zipped~Network~753Mp`
answers:
NO Error in IMAP command received by server.

I fixed it putting line:
`list($code, $response) = $this->execute('LOGIN', [$this->escape($user, true), $this->escape($password, true)],`
instead of:
`list($code, $response) = $this->execute('LOGIN', [$this->escape($user), $this->escape($password)],`
in program/lib/Roundcube/rcube_imap_generic.php
Added `true `parameter means force_quotes

IMHO it makes nothing bad to quote any username, password and that does not contradict [imap rfc](https://www.rfc-editor.org/rfc/rfc3501) specification

**Comment by alecpl** [comment]
Looks like a Courier bug, but I guess we could force quotes in LOGIN.

**Comment by suprune20** [comment]
> Looks like a Courier bug, but I guess we could force quotes in LOGIN.

Courier seems to play it safe with tilde (~). [imap rfc](https://www.rfc-editor.org/rfc/rfc3501):
