### ISSUE TITLE
Can't connect Microsoft Exchange Account

### ISSUE THREAD

**Issue by acpnayak** [roundcube/roundcubemail#8774]
I need to know how I can connect Microsoft Exchange Account in Roundcube. I know Roundcube supports IMAP but not exchange.

Is there way to support exchange on Roundsube?

**Comment by alecpl** [comment]
Nope.

**Comment by acpnayak** [comment]
Thanks for the swift revert. Can it be done via some 3rd party plugins? Like Thunderbird uses OWL Plugin for supporting Exchange accounts?

OWL Plugin for Exchange:
https://addons.thunderbird.net/en-us/thunderbird/addon/owl-for-exchange/

Is there anything planned for supporting exchange accounts in the near future?
