### ISSUE TITLE
Prepared statement needs to be re-prepared error

### ISSUE THREAD

**Issue by syncgw** [roundcube/roundcubemail#8777]
Hi,
I found this [issue](https://github.com/roundcube/roundcubemail/issues/3155), but that did not help. I use a shared hoster mysql `8.0.31-0ubuntu0.20.04.1` und getting tons of message like:

`[04-Nov-2022 12:20:06 +0000]: <558506d8> DB Error: [1615] Prepared statement needs to be re-prepared (SQL Query: UPDATE `users` SET `last_login` = now() WHERE `user_id` = '7') in /hp/bv/ac/fw/www/mail/program/lib/Roundcube/rcube_db.php on line 564 (POST /)
[04-Nov-2022 12:25:02 +0000]: <1912462c> DB Error: [1615] Prepared statement needs to be re-prepared (SQL Query: UPDATE `users` SET `last_login` = now() WHERE `user_id` = '7') in /hp/bv/ac/fw/www/mail/program/lib/Roundcube/rcube_db.php on line 564 (POST /)`

Any idea how to avoid messages and get RoundCube working?

**Comment by alecpl** [comment]
It looks to me that's a problem with mysql. If you search the error message in google, you'll find some suggestions to increase some mysql limit options. I don't think it can be solved on the Roundcube side.

**Comment by syncgw** [comment]
I understand
