### ISSUE TITLE
Self host connect to gmail

### ISSUE THREAD

**Issue by LegendWasTaken** [roundcube/roundcubemail#8785]
I'm self hosting roundcubemail, and I would like to be able to connect gmail to my custom email. Fe; On my gmail account, send an email as myaccount@domain.com. And same the other way around (see emails from myaccount@domain.com on my gmail account).

I've done this before with hosting providers, but I'm unsure how to do it when I'm self hosting. My email works just fine on roundcube (I can send / receive just fine). The problem occurs when I try to connect either IMAP or SMTP from gmail.

I go to add the SMTP server, with the details being `mail.domain.com` (This is what I normally use to login to the normal panel). I've tried port 25, 465, and 587. And same username / password as when I login to the website GUI. But it's failed on all of them.
Error: Server returned error: "TLS Negotiation failed, the certificate doesn't match the host., code: 550"

I should note; I haven't setup SSL with roundcubemail as I wasn't able to figure out how to do it (I couldn't find a config for it in nginx for letsencrypt to do it's thing) 

Any help is appreciated. Thanks!

**Comment by LauraTaylorUK** [comment]
I think that google/gmail require that your SMTP has a valid certificate.

It is fairly easy to get one from [Let's Encrypt](https://letsencrypt.org/). I always suggest people avoid the certbot which is so badly programmed and instead use one of the popular bash clients (thats right bash!):

[ACME.sh](https://github.com/acmesh-official/acme.sh)
[Dehydrated](https://github.com/dehydrated-io/dehydrated)

Usually all major hosting control panels support Let's Encrypt, personally I prefer to use a more [secure self-hosting script](https://gitlab.com/noumenia/aetolos) which uses dehydrated by default.

My suggestion, is to not use a "mail." subdomain, but just use the FQDN of the server as the mail server host/domain (eg myserver.domain.com) thus the same certificate can be used for multiple services (dovecot, postfix, ngnix/apache, etc).

**Comment by LegendWasTaken** [comment]
> It is fairly easy to get one from [Let's Encrypt](https://letsencrypt.org/). I always suggest people avoid the certbot which is so badly programmed and instead use one of the popular bash clients (thats right bash!):

I had left out that I tried with LetsEncrypt too, but I couldn't find any real documentation on getting it working with Roundcube Webmail :( 

> Usually all major hosting control panels support Let's Encrypt, personally I prefer to use a more [secure self-hosting script](https://gitlab.com/noumenia/aetolos) which uses dehydrated by default.

I don't have any hosting control panel 😅, I'm just using a single server for my email and leaving it alone. Is this something I should look into? 

> My suggestion, is to not use a "mail." subdomain, but just use the FQDN of the server as the mail server host/domain (eg myserver.domain.com) thus the same certificate can be used for multiple services (dovecot, postfix, ngnix/apache, etc).

Could I have a bit more explanation on this part? What do you mean FQDN of the server? 


Thanks for the quick and thoughtful reply! Sorry I don't quite understand all of it, this world is a rabbit hole I'm yet to (but it seems im about to) dive into.
