### ISSUE TITLE
Roundcube 1.6 : corrupt attachments (Word, Excel, Powerpoint,..)

### ISSUE THREAD

**Issue by lorylus** [roundcube/roundcubemail#8787]
@alecpl 

There are topics in this Forum regarding this issue but I' m still having issue.

When I am trying to open word or excel attachments, I get an error message from word or excel, asking converters need to be installed . This issue appears only on roundcube users not MS Outlook.  Also the open button appears disabled.

TXT and PDF are not concerned  and attachments working fine.

Thanks for help!

Regards, 

https://user-images.githubusercontent.com/22031296/202225843-67e1a32f-884c-4864-94cb-be63476b775a.png
https://user-images.githubusercontent.com/22031296/202226459-22b8f0ba-9ac7-49c0-b3c1-a0cc73c00089.png

**Comment by alecpl** [comment]
"Open" is for attachment types supported by the browser. So, this is as expected.

As for the other issue. Download the file and try to find a difference to the original one. Usually attachments are being decoded by the IMAP server (for Roundcube) so, it may be an issue with the IMAP server. They also might get malformed by the HTTP server (Office files are usually compressed, so it might interfere with HTTP compression). There used to be also an issue with space/newline characters being added to the output by Roundcube if some of the PHP files (including config files) contains such characters before `<?php` or after `?>`.
