### ISSUE TITLE
managesieve: PHP 8.0 warning if using "redirect" action

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#8788]
Hi,

if using a managesieve filter (on Roundcube 1.5.3) with a "redirect" or "copy" action, a php warning is shown:

```
Warning: Trying to access array offset on value of type null in /plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 1071
```

This affects this line in rcube_sieve_engine:
```
                case 'redirect':
                case 'redirect_copy':
                    $target = $this->strip_value($act_targets[$idx]);
                    $domain = $this->strip_value($domain_targets[$idx]); // <-----

                    // force one of the configured domains
```

There are a few other warnings like these in other actions/rules (like using the "date" rule) which appear to use the same logic. 
From my small testing they are easily fixed with

```
$domain = $this->strip_value($domain_targets[$idx] ?? null);
```

but I don't know if thats the preferred/right way. Let me know how I should fix it and I can provide a PR.

**Comment by alecpl** [comment]
The fix for master and release-1.6 could use `??`, but for release-1.5 branch we'd need PHP5 compatible code.

**Comment by codegain** [comment]
I'm totally fine if this only makes it to the master branch if thats ok with you.

I'll patch it for my system until I upgrade to 1.6

**Comment by codegain** [comment]
Or this could also be fixed with something like

```
$domain = $this->strip_value(isset($domain_targets[$idx]) ? $domain_targets[$idx] : null));
```

**Comment by alecpl** [comment]
Create a pull request for master, we'll take care of 1.6. And we can ignore 1.5 in this case.
