### ISSUE TITLE
Session keeps expiring after upgrade from 1.4.8 to 1.6.0

### ISSUE THREAD

**Issue by Juvecu** [roundcube/roundcubemail#8791]
Firstly, thank you for providing this awesome webmail client. I have been using it for years and it's still my favourite :)

On 10 November I upgraded from 1.4.8 to 1.6.0. Since then I've noticed that I'm now getting logged out after an undertermined amount of time where before I would stay logged in until I closed my browser.

The problem exist using the current latest versions of both Firefox and Chrome. Browser security has been configured to whitelist my entire domain, cookies are allowed and there aren't any extensions interfering (I only use uBlock Origin and have disabled it as part of my troubleshooting.)

Having searched I've found a previously logged issue that exactly describes the problem I am experiencing: https://github.com/roundcube/roundcubemail/issues/8303

This issue has been marked Closed with a comment that it is fixed. There are additional comments after the closure advising the problem still exists, but these have not seen a response since the issue was closed on 13 March. Rather than adding to those comments I'm logging this new issue to raise the awareness that the problem is still active in case the additional comments on the original have gone unnoticed.

**Comment by alecpl** [comment]
What plugins are you using? What PHP version? Does the session expire when you're in a specific place/task in UI?

**Comment by Juvecu** [comment]
Hi, thanks for the response.

Here's a list of the plugins, I believe they are the same ones I used in 1.4.8. At the time it didn't occur to me to note the ones previously used before the upgrade.

<html><body>
		

Plugin | Version
-- | --
attachment_reminder | 1.1
emoticons | 3.0
filesystem_attachments | 1.0
identicon | 0.1 
jqueryui | 1.13.1 
managesieve | 9.4 
markasjunk | 2.0  
newmail_notifier | 0.8


</body>
</html>

`php -v` shows:
`PHP 7.4.3 (cli) (built: Nov  2 2022 09:53:44) ( NTS )`
`Copyright (c) The PHP Group`
`Zend Engine v3.4.0, Copyright (c) Zend Technologies`
`    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies`

I've not noticed that it happens on a specific place/task in the UI. As one would expect, most of the time the browser tab is left as is after having looked at an email. That is to say, I am viewing and email, finished reading it and leave it on display.

For what it's worth, I have several other things running on the same server, amongst them Nextcloud and Bitwarden, and I don't have similar problems with the web interface on those or any of the others.

**Comment by alecpl** [comment]
How about 1.6.1? Session expiration can be caused by so many factors that I don't know even where to start.

**Comment by Juvecu** [comment]
I've updated to 1.6.1 a while ago, no change. I suppose the problem can be caused by any number of external things, but I've got nothing else that exibits the same or remotely similar problems. No idea where to start, if I ever find out what it causing it I'll try to remember to let you know :)

**Comment by grinkevich** [comment]
```
root@core-1:~# php -v
PHP 8.4.8 (cli) (built: Jun  9 2025 13:50:18) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.4.8, Copyright (c) Zend Technologies
    with Zend OPcache v8.4.8, Copyright (c), by Zend Technologies
root@core-1:~# date +%H:%M:%S.%N
20:59:41.152871192
```
My system time BST is +1 from the server time - it was 21:59 on my check in console.
Plugins - almost default I think:
```
// Plugin configuration
$config['plugins'] = array(
    'archive',
    'zipdownload',
    'password',
    'additional_message_headers',
    'emoticons',
    'help',
    'newmail_notifier',
    'show_additional_headers',
    'vcard_attachments'
);
// Security settings
$config['session_lifetime'] = 360;
$config['ip_check'] = true;
$config['referer_check'] = true;
$config['x_frame_options'] = 'deny';
```
@alecpl  FYI if that helps :) Imho, BST time zone on the local PC vs remote server in Europe makes a difference!
