### ISSUE TITLE
PHP (8.1) Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#8794]
Roundcube 1.6
PHP 8.1

This is but one example of a few warnings triggered in PHP 8.1 with RC 1.6:

`PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in` https://github.com/roundcube/roundcubemail/blob/3f8c4680c3033d5e930333bc4276b0c455715b3f/program/lib/Roundcube/rcube_imap.php#L2870

**Comment by PolarianDev** [comment]
@ner00 Pretty sure this is due to the same issue which I reported in #8793

Seems like they have been using deprecated functions within their codebase, some of which have been deprecated for a long time...

**Comment by ner00** [comment]
Seems like it, but I'm following by example since I've seen multiple reports of deprecated code on a per-function-basis. Also, there's probably a ton of code that needs rewriting so, I don't really blame the team.

**Comment by PolarianDev** [comment]
Come to think of this I do not think this will cause any errors, so I believe my issue could be due to invalid configuration and not deprecated features 🤔 

@ner00 guess it will just have to be put on their todo list as a low priority, however it is important they stop using deprecated features as when php removes them the entire codebase will break!

**Comment by ner00** [comment]
I edited this code to suppress the errors but might just be avoiding a larger issue, instead of:
https://github.com/roundcube/roundcubemail/blob/3f8c4680c3033d5e930333bc4276b0c455715b3f/program/lib/Roundcube/rcube_imap.php#L2870

I now have:
```php
          $this->clear_message_cache($folder, !empty($all_mode) ? null : explode(',', $uids ?? ''));
```

**Comment by alecpl** [comment]
Fixed.
