### ISSUE TITLE
Elastic skin: desktop layout not working

### ISSUE THREAD

**Issue by netchild** [roundcube/roundcubemail#8797]
roundcube 1.6.0.

$config['layout']='desktop'; with the elastic skin doesn't give the preview on bottom as documented in defaults.inc.php, it shows the same layout like 'widescreen'.

**Comment by alecpl** [comment]
Elastic skin has no layouts support. There's a plugin https://github.com/johndoh/roundcube-elasticlayouts.

**Comment by netchild** [comment]
Then this is a documentation bug... the way it is written in defaults.inc.php makes one believe this is supposed to work.
