### ISSUE TITLE
Auto-choose correct identity when replying to a mail

### ISSUE THREAD

**Issue by stoecker** [roundcube/roundcubemail#8800]
When I have multiple identities defined, the identity matching the email address best should be selected and not simply the first one.

E.g. when I have identities abc@domain1.tld and xyz@domain2.tld and uvw@whatever.net then a reply to an email to uvw@whatever.net should select identity 3 and not 1.

It's clear that this wont always work, but at least it should try as best as it could by checking TO and CC fields for known addresses.

**Comment by alecpl** [comment]
I'm unable to reproduce the issue. What Roundcube version? What plugins enabled? Also, it might be needed to see in more detail how the identities look like and headers of the mail you reply to.

**Comment by SherryPV** [comment]
Settings: identity: settings: email  this field is being ignored (problem began after the last release)
