### ISSUE TITLE
Undefined array key "ssl_mode"

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#8804]
After enabling `imap_debug` I started getting my error log filled with the following warning:

`Undefined array key "ssl_mode" in /var/www/roundcube/program/lib/Roundcube/rcube_imap_generic.php on line 1053`
https://github.com/roundcube/roundcubemail/blob/3f8c4680c3033d5e930333bc4276b0c455715b3f/program/lib/Roundcube/rcube_imap_generic.php#L1053
I'm not entirely sure why this happens or why this line assumes that `ssl_mode` array key should be defined, mainly because previous code checks to see if `ssl_mode` is actually defined
https://github.com/roundcube/roundcubemail/blob/3f8c4680c3033d5e930333bc4276b0c455715b3f/program/lib/Roundcube/rcube_imap_generic.php#L1041
Regardless, my config sets the imap host as follows: `$config['imap_host'] = 'tls://hostname.tld:143';`

Since this behavior is exclusive to the debug mode, maybe it is by design, I just find it a bit curious because it can clutter a log file pretty quickly when you might be looking for other stuff. Is it by design, or maybe a misconfiguration on my part?

**Comment by ner00** [comment]
```php
          $_host = (!empty($this->prefs['ssl_mode']) && $this->prefs['ssl_mode'] == 'tls' ? 'tls://' : '') . $host . ':' . $this->prefs['port'];
```
This maybe?

**Comment by LionsSharks15** [comment]
I'm having the same issue. I can receive emails, but I can never send them successfully, I just get returned mail from the mail delivery system. Whenever I visit my webmail domain, I get the same "ssl_mode" error too. Really hoping someone can help.

**Comment by ner00** [comment]
@LionsSharks15 I don't think we have the same issue here, besides maybe the warning itself. I have no issues sending or receiving mail, just the warning. I assume you may have some config issue since you can receive fine but not send, which should be tied to SMTP protocol. Besides, I only get these warnings when enabling IMAP debug.

**Comment by alecpl** [comment]
Fixed.
