### ISSUE TITLE
1.6.0 - Debian Bullseye - After upgrade unable to compose HTML if calendar installed and not en_US

### ISSUE THREAD

**Issue by WarpinWolf** [roundcube/roundcubemail#8807]
Hi,

Not sure whether it is ok to report here - as for me the issue is solved. But maybe others stumble upon this.

I recently migrated my server. I also switched to Debian Bullseye (11.5) from Buster. Doing this I also migrated from 1.4.x to 1.6.0. I did so using the installto.sh after d/l and extracting the full roundcube package.

The upgrade went fine and only after a while I did notice that if I wanted to switch from text mode composing to html that "strange" things did happen - e.g. instead of a formatted input I suddenly saw html code displayed in the editor control.

I started to fiddle around with the settings of "Show HTML"  and "Compose HTML". But couldn't get a grip / solution on it. Instead it turned out that the "Switch Text to HTML" button did not work. If settings where "only HTML" then the editor component simply stayed unresponsive. if it was "text only" then "Switch to HTML" didn't do anything.

This did happen in all themes on various clients.

e.g. in Firefox I got this in the console:

```
Uncaught TypeError: t.ui is undefined
    setup_callback https://xxx/skins/elastic/ui.min.js?s=1658607434:13
    setup https://rxxx/program/js/editor.min.js?s=1658607434:31
    execCallback https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    zx https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    n https://rxxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    e https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    qt https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    e https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    bind https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    F https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    init https://xxx/program/js/tinymce/tinymce.min.js?s=1665079297:19
    rcube_text_editor https://rxxx/program/js/editor.min.js?s=1658607434:31
    editor_init https://xxx/program/js/app.min.js?s=1658607434:35
    init https://xxx/program/js/app.min.js?s=1658607434:35
    <anonymous> https://xxx/?_task=mail&_action=compose&_id=35659397563873b0113ff4:419
```

I used composer to (re-)install calendar, libkolab, libcalendaring. No avail...

Today I again wanted to paste an image but - didn't work work. So I did dig a little deeper.

Looking at the logs on the server I could see several entries like the following when clicking on the "Switch from Text to HTML" button.
```
[30-Nov-2022 14:15:40 Europe/Berlin] PHP Warning:  Undefined variable $attendees in /var/www/roundcube/plugins/calendar/localization/de_DE.inc on line 169
[30-Nov-2022 14:15:40 Europe/Berlin] PHP Warning:  Undefined variable $description in /var/www/roundcube/plugins/calendar/localization/de_DE.inc on line 170
[30-Nov-2022 14:15:40 Europe/Berlin] PHP Warning:  Undefined variable $url in /var/www/roundcube/plugins/calendar/localization/de_DE.inc on line 173
[30-Nov-2022 14:15:40 Europe/Berlin] PHP Warning:  Undefined variable $title in /var/www/roundcube/plugins/calendar/localization/de_DE.inc on line 176
[30-Nov-2022 14:15:40 Europe/Berlin] PHP Warning:  Undefined variable $date in /var/www/roundcube/plugins/calendar/localization/de_DE.inc on line 177
```

So I went to settings and changed my language from de_DE to en_US. And suddenly everything worked. Even after switching back to de_DE the functionality stayed. Could it be that the upgrade somehow needs to be carried out in en_US - if calendar is installed? That calendar plugin somehow fails and prevents proper loading of tinymce editor?

Here are some details:

Server: 
Debian Bullseye 11.5
PHP 8.1.13
Apache/2.4.54 (Debian)
PostgreSQL 14.6 (Debian 14.6-1.pgdg110+1)
Exim 4.94.2 
Dovecot 2.3.13

Client
Linux (Mageia 8)
- Chromium Version 107.0.5304.110
- Firefox 102.5.0esr (64-Bit)

Android
Chrome

Anyway - hope I didn't waste too much of your time - for me the issue is closed.

**Comment by alecpl** [comment]
We do not support external plugins here., but this localization issue will be fixed in the next calendar/tasklist plugin version.
