### ISSUE TITLE
Roundcube Mobile isn't downloading all emails

### ISSUE THREAD

**Issue by njchairdod** [roundcube/roundcubemail#8808]
I installed the mobile app and while it shows an email and says 1of 26, I can't seem to see the other 25 messages. It appears to not be downloading them.

**Comment by alecpl** [comment]
What app? We're not developing supporting any mobile apps here.

**Comment by njchairdod** [comment]
There is a Roundcube mobile app

**Comment by njchairdod** [comment]
I downloaded a Roundcube mobile app from the Google Playstore 

On 2022-12-01 09:53, Aleksander Machniak wrote:

> What app? We're not developing supporting any mobile apps here. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>

We advocate for legislators, educators, and administrators who will work
to maintain communities as well as a public education system that
supports and enhances our shared experiences regardless of religious
beliefs, cultural background, or sexual orientation. 

#dofd
#defenseofdemocracy
#notonourwatch 

 

Links:
------
[1]
https://github.com/roundcube/roundcubemail/issues/8808#issuecomment-1333885396
[2]
