### ISSUE TITLE
Can the roundcube framework stream emails?

### ISSUE THREAD

**Issue by LauraTaylorUK** [roundcube/roundcubemail#8812]
Hello everyone,

I'm sorry if this is not the right place to ask such a question.

I'm coding a postfix milter to scan email content and run various filters on file attachments. The milter protocol defines the transmission method of the email in small blocks. So my milter application receives these little blocks and runs various filters (regex, etc) on them.

Do you think it would be possible to use the roundcube framework this way, to extract file attachments? Thus load emails from disk or stream and not imap/pop3.

What is important, is that I can't load the entire contents of the email in memory due to constraints on the email servers. Thus, whatever tools I use, must be able to scan/parse the contents without loading the entire thing into memory.

I would appreciate some ideas.

Thank you.

PS:
I am looking at the roundcube framework, because roundcube is just awesome, I've been using it for many years with great success and very few problems that are always fixed by the dev team.

**Comment by alecpl** [comment]
Roundcube depends on BODYSTRUCTURE response from the IMAP server. We have a fallback mail parser, but it is not very good, and it parser the message in memory. So, I'm afraid Roundcube Framework is not for this use-case.

**Comment by LauraTaylorUK** [comment]
Ah I see. Thank you for the prompt answer.
