### ISSUE TITLE
Hard dependency on shell_exec when using Git based installation

### ISSUE THREAD

**Issue by oliverrahner** [roundcube/roundcubemail#8813]
When using a Git based installation, there is a hard dependency on `shell_exec` when trying to display the version information:

https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail_output_html.php#L1540

This should at least be `catch`ed, because otherwise it leads to a nasty error message when a regular user clicks on "Version" in the main menu when the hoster decided to disallow the use of `shell_exec`.

**Comment by alecpl** [comment]
I guess here we could check if the function exists and skip the git version check.

ps. we use `shell_exec()` and `exec()` in other places.

**Comment by oliverrahner** [comment]
I've been using the Git version for years, and also disabled shell_exec() since forever. These place don't seem to be very commonly used ones, I've never encountered another issue with this :)

**Comment by alecpl** [comment]
Fixed.
