### ISSUE TITLE
Translation Request

### ISSUE THREAD

**Issue by Keram-Yasin** [roundcube/roundcubemail#8815]
I would like ask for support to translate Roundcube Webmail into Uighur (Arabic) language. Since the language is not available for translation, I have made my request on Transfix 2 months, 3 weeks ago, my request is still pending and the language is still not available for translation. Can you please approve my request on Transfix so that I can start translation? Thanks.

**Comment by alecpl** [comment]
We do not have any languages codes that contain `@` as of yet. So, I'm not sure if any changes in the code would be required. Could this be just `ug`? Or the "default" is not arabic?

**Comment by Keram-Yasin** [comment]
@alecpl I don't understand what language code you meant. If you mean the language code of HTML, it's definitely correct. The standard language code of Uyghur language in HTML is "ug". The only thing to change is to use the following code in HTML tag: <html dir="rtl" lang="ug">;

**Comment by alecpl** [comment]
In Transifex you choose `ug@Arabic` not `ug`.

**Comment by Keram-Yasin** [comment]
@alecpl my mistake. sorry. can you please make it available now? Thanks.

**Comment by Keram-Yasin** [comment]
@alecpl thank you very much. you are very helpful. now i can start translation.

**Comment by Keram-Yasin** [comment]
I have been asking information about the integration of Uyghur language into Roundcube Webmail GUI via Transifex website and email, but neither of them helped me to communicate with Roundcube Webmail Developement Team. Thus, I am writing this comment here.

I had finished all the translations of Roundcube Webmail into Uyghur on Transifex several weeks ago. I had also make complete review of all the translations last week. I thought the Uyghur language will be available on release 1.6.1, but it does not seems to be available yet according to content of the localization directory of the repository. 

Can I ask when the Uyghur language will be available on Roundcube Webmail GUI? I would have provided coding support to make that happen if it's necessary.

**Comment by alecpl** [comment]
The localization has been included.

**Comment by alecpl** [comment]
Works for me. The language is 5th to last on the list.

**Comment by alecpl** [comment]
Oops, looks like it works only on my computer. I never pushed the localization folder. Fixed now. You have to get this folder from master. https://github.com/roundcube/roundcubemail/tree/master/program/localization/ug

**Comment by Keram-Yasin** [comment]
I have included the new localization folder. Then It appeared among the language list. Thank you, Sir! Your are very helpful.

**Comment by Keram-Yasin** [comment]
Hello @alecpl, 

I hope you are doing well. The Roundcube webmail is working pretty well with Uyghur language. And I am thinking if the Uyghur spell checking dictionary can be added to default Roundcube spellchecker (spell.roundcube.net). I have Pspell Uyghur dictionary files which works fine in local machine. It would be great if the dictionary is added to default Roundcube spellchecker.
[ug-dic.zip](https://github.com/roundcube/roundcubemail/files/13808243/ug-dic.zip)

**Comment by alecpl** [comment]
I don't think this will happen. You should not depend on our spellchecker service.
