### ISSUE TITLE
mb_strtolower error with Php81

### ISSUE THREAD

**Issue by DA4PKol** [roundcube/roundcubemail#8823]
Hello,
Performing an addressbook research Running roundcube 1.6 behind nginx and php81-fpm (Rocky Linux 9, remi php81) gives  : 
`PHP Fatal error:  Uncaught TypeError: mb_strtolower()`
Using php74-fpm instead of php81 is the temporary solution. 
Do I miss some parameter somewhere ? 
Best,
DA4PKol

**Comment by alecpl** [comment]
Strange. Is there some more context, e.g. code line number or traceback?

**Comment by DA4PKol** [comment]
Hello,
In logs/errors.log :

`[20-Dec-2022 10:29:54 Europe/Paris] PHP Fatal error:  Uncaught TypeError: mb_strtolower(): Argument #1 ($string) must be of type string, array given in /websites/rc/program/lib/Roundcube/rcube_addressbook.php:871
Stack trace:
#0 /websites/rc/program/lib/Roundcube/rcube_addressbook.php(871): mb_strtolower()
#1 /websites/rc/plugins/carddav/src/Addressbook.php(1776): rcube_addressbook->compare_search_value()
#2 /websites/rc/plugins/carddav/src/Addressbook.php(344): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->checkPostSearchFilter()
#3 /websites/rc/program/actions/contacts/search.php(131): MStilkerich\CardDavAddressbook4Roundcube\Addressbook->search()
#4 /websites/rc/program/actions/contacts/search.php(34): rcmail_action_contacts_search::contact_search()
#5 /websites/rc/program/include/rcmail.php(275): rcmail_action_contacts_search->run()
#6 /websites/rc/index.php(278): rcmail->action_handler()
#7 {main}
  thrown in /websites/rc/program/lib/Roundcube/rcube_addressbook.php on line 871`

Maybe it‘s the carddav plugin‘s fault…

**Comment by alecpl** [comment]
The code expects an addressbook item to be either a string or array of strings. It looks that here it is an array of arrays. So, this is probably something that the carddav plugin should take care of, but I suppose we could fix it too.

**Comment by mstilkerich** [comment]
FYI, in rcmcarddav this has been fixed with issue mstilkerich/rcmcarddav#410.

The array of arrays that was passed here was a list of structured addresses (from `$save_data[address]`). The native addressbook would call `compare_search_value()` only with single address items, which is an array of strings again. This is what rcmcarddav now does as well.

So I think you can close this issue.

**Comment by alecpl** [comment]
Fixed.
