### ISSUE TITLE
PHP Error: Invalid skin name

### ISSUE THREAD

**Issue by LauraTaylorUK** [roundcube/roundcubemail#8825]
In one of my webmail servers, running roundcube 1.6.0, came up with the following error:

```
roundcube[12807]: <kas8gt6n> PHP Error: Invalid skin name in /home/user/public_html/program/include/rcmail_output_html.php on line 323 (POST /?_task=settings&_action=save-prefs)
```

Is it something known and already fixed error? or something new? This was a clean install, not an upgrade.

Only the elastic skin is installed. My config also contains the following:

```php
$config['skin'] = 'elastic';
```

Thank you.

**Comment by alecpl** [comment]
Is this when you submit Settings > Preferences > User interface form? What do you see there? Are you using any plugins?

The error means that an invalid skin name has been provided (somewhere).

**Comment by LauraTaylorUK** [comment]
Yes that is correct, if i visit the Settings > Preferences > User Interface form and just click on "Save", I get the same error consistently.

```
roundcube[564230]: <qkqkvekf> PHP Error: Invalid skin name in /home/user/public_html/program/include/rcmail_output_html.php on line 323 (POST /?_task=settings&_action=save-prefs)
```

**Comment by alecpl** [comment]
Could you investigate the POST request content (via browser console)?

**Comment by LauraTaylorUK** [comment]
The raw POST request contents are:

```
_token=mwK43gerLCgO4ftnFo4kr0J0Wmceu1lL&_framed=1&_task=settings&_action=save-prefs&_section=general&_language=en_US&_timezone=Europe%2FBerlin&_time_format=H%3Ai&_date_format=d-m-Y&_pretty_date=1&_refresh_interval=1
```

**Comment by alecpl** [comment]
Ok, I wasn't able to reproduce because I had more than one skin available. The error happens only with a single skin. Fixed.
