### ISSUE TITLE
ldap addressbook tries to use VLV, despite being told not to do so, queries for VLV in cn=config instead in the rootDSE and logs error that cn=config does not announce VLV support

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#8833]
ldap.aegee.org is a public LDAP server, requiring STARTTLS, but no authentication.  The server supports SSS and VLV, which can be seen by calling:

> ldapsearch -ZZxH ldap://ldap.aegee.org -b "dc=aegee,dc=org" -s sub -E sss=ou:2.5.13.15 -E vlv="0/2/0/1"

The unauthenticated user has no access to the cn=config tree.

I use roundcube 1.6.0 with kolab/net_ldap3 v1.4.4.  In config/config.inc.php I have configured a public LDAP addressbook:
```php
$config['ldap_public']['ldap'] = array(
  'name' => 'LDAP (AEGEE Bodies)',
  'hosts' => array('tls://ldap.aegee.org'),
  'user_specific' => false,
  'base_dn' => 'cn=bodies,dc=aegee,dc=org',
  'fuzzy_search'   => true,
  'fieldmap' => array(
    'name'        => 'cn',
    'surname'     => 'sn',
    'firstname'   => 'givenName',
    'jobtitle'    => 'title',
    'email'       => 'mail:*',
    'phone:work'  => 'telephoneNumber',
    'street'      => 'postalAddress',
    'website'     => 'labeledURI',
    'zipcode'     => 'postalCode',
    'region'      => 'st',
    'locality'    => 'l',
    'organization' => 'o',
    'department'   => 'ou',
    'jobtitle'     => 'title',
    'notes'        => 'description',
  ),
  'scope' => 'one'
);
```
The above contains no VLV, so I assume VLV is disabled.  Nevertheless when I get the data over roundcube, the data are displayed, but error.log includes each time a line:

> [27-Dec-2022 16:46:52 UTC] PHP Warning:  ldap_search(): Search: No such object in /roundcubemail-1.6.0/vendor/kolab/net_ldap3/lib/Net/LDAP3.php on line 2141.

The line 2141 contains:
```
        $search_filter = '(objectclass=vlvsearch)';
        $index_filter  = '(objectclass=vlvindex)';

        $this->_debug("C: Search base dn: [$config_root_dn] scope [sub] with filter [$search_filter]");

        $search_result = ldap_search($this->conn, $config_root_dn, $search_filter, array('*'), 0, 0, 0);  // this is line 2141

        if ($search_result === false) {
            $this->_debug("S: " . ldap_error($this->conn));
            return array();
        }                                                                                                                               
```
The line `$this->_debug("C: Search base dn: [$config_root_dn] scope [sub] with filter [$search_filter]");` logs:
> [27-Dec-2022 16:56:41 +0000]: <bd40c173> C: Search base dn: [cn=config] scope [sub] with filter [(objectclass=vlvsearch)]

The anonymous user has no access to cn=config.  But the rootDSE looks so for the anonymous user:
```
ldapsearch -ZZxH ldap://ldap.aegee.org -b "" -s base +
# extended LDIF                                                     
#                                                                   
# LDAPv3                                                                                                                                
# base <> with scope baseObject
# filter: (objectclass=*)
# requesting: + 
#

#
dn:
structuralObjectClass: OpenLDAProotDSE
configContext: cn=config
namingContexts: dc=aegee,dc=org
monitorContext: cn=Monitor
supportedControl: 2.16.840.1.113730.3.4.9
supportedControl: 1.2.840.113556.1.4.473
supportedControl: 1.3.6.1.4.1.4203.1.9.1.1
supportedControl: 2.16.840.1.113730.3.4.18
supportedControl: 2.16.840.1.113730.3.4.2
supportedControl: 1.3.6.1.4.1.4203.1.10.1
supportedControl: 1.3.6.1.1.22
supportedControl: 1.2.840.113556.1.4.319
supportedControl: 1.2.826.0.1.3344810.2.3
supportedControl: 1.3.6.1.1.13.2
supportedControl: 1.3.6.1.1.13.1
supportedControl: 1.3.6.1.1.12
supportedExtension: 1.3.6.1.4.1.1466.20037
supportedExtension: 1.3.6.1.4.1.4203.1.11.1
supportedExtension: 1.3.6.1.4.1.4203.1.11.3
supportedExtension: 1.3.6.1.1.8
supportedExtension: 1.3.6.1.1.21.3 
supportedExtension: 1.3.6.1.1.21.1 
supportedFeatures: 1.3.6.1.1.14
supportedFeatures: 1.3.6.1.4.1.4203.1.5.1
supportedFeatures: 1.3.6.1.4.1.4203.1.5.2
supportedFeatures: 1.3.6.1.4.1.4203.1.5.3
supportedFeatures: 1.3.6.1.4.1.4203.1.5.4
supportedFeatures: 1.3.6.1.4.1.4203.1.5.5
supportedLDAPVersion: 3
supportedSASLMechanisms: GS2-IAKERB
supportedSASLMechanisms: GS2-KRB5
supportedSASLMechanisms: GSS-SPNEGO
supportedSASLMechanisms: GSSAPI
supportedSASLMechanisms: LOGIN
supportedSASLMechanisms: PLAIN
entryDN:
subschemaSubentry: cn=Subschema

# search result
search: 3
result: 0 Success

# numResponses: 2
# numEntries: 1
```
According to https://ldapwiki.com/wiki/Virtual%20List%20View%20Control VLV has the control OID 2.16.840.1.113730.3.4.9 and the server-side sort control has OID 1.2.840.113556.1.4.473 - https://ldapwiki.com/wiki/Server%20Side%20Sort%20Control . Both are present in the rootDSE.

The point is, that the LDAP configuration tells RoundCube that there is no VLV support, despite VLV being present, nevertheless net_ldap3(kolab) does try to utilize VLV, but instead of quering the rootDSE for VLV/SSS support, it sends requests ot cn=config, where it has not access, and then logs a line in error.log

**Comment by dilyanpalauzov** [comment]
After setting
```php
$config['ldap_public']['ldap'] = array(
  'config_root_dn' => false, 
)
```
roundcube stopped logging in /tmp/errors.log.

The documentation for the above option is `// Root DN to search config entries (e.g. vlv indexes)`.  For me it is unclear why access to `cn=config` is needed for an LDAP addressbook.  Even if it is needed for vlv-indexes (I do not know what a vlv index means), and LDAP3.php:line 2140 requests `$search_filter = '(objectclass=vlvsearch)'; $index_filter  = '(objectclass=vlvindex)';` for addressbooks where VLV is not enabled, there shall be no such queries.

While kolab/net/LDAP3.php includes `objectclass=vlvsearch` and `objectclass=vlvindex` I use as LDAP server OpenLDAP.  In its source directory there are no vlvsearch and vlvindex. (`git grep -i vlvindex`, `git grep -i vlvsearch`).  So likeley the vlvsearch and vlvindex objectclasess are vendor specific.

**Comment by alecpl** [comment]
VLV indexes are used for better performance. This code works with standard Kolab installations (with ds389 server).

Indeed `config_root_dn` is set by default to 'cn=config' and the `vlv` option is not set. Therefore the default behavior is to find the VLV index information under 'cn=config'.

To disable this you have to set any of these options to `false`. We already have them described in defaults.inc.php:
```
  'vlv'            => false,        // Enable Virtual List View to more efficiently fetch paginated data (if server supports it)
  'vlv_search'     => false,        // Use Virtual List View functions for autocompletion searches (if server supports it)
  'numsub_filter'  => '(objectClass=organizationalUnit)',   // with VLV, we also use numSubOrdinates to query the total number of records. Set this filter to get all numSubOrdinates attributes for counting
  'config_root_dn' => 'cn=config',  // Root DN to search config entries (e.g. vlv indexes)
```
We should make sure the `vlv` option, when omitted, defaults to `false`.

**Comment by dilyanpalauzov** [comment]
I see.  Why is it necessary to consult `cn=config` before performing a VLV request?  As can be seen by the next call, LVL can work without queuing `cn=config`:
> ldapsearch -ZZxH ldap://ldap.aegee.org -b "dc=aegee,dc=org" -s sub -E sss=ou:2.5.13.15 -E vlv="0/2/0/1"

**Comment by alecpl** [comment]
Not every search query can use the index (the same as in SQL databases), so we're getting index information to decide whether it can be used or not for a specific query. Unlike in SQL the code needs to know that.

**Comment by alecpl** [comment]
Actually the cn=config query can be omitted also when you know the exact indexes "formula", e.g.:
```
'vlv' => [
               [
                       'ou=People,dc=example,dc=org' => [
                               'scope' => 'sub',
                               'filter' => '(objectclass=inetorgperson)',
                               'sort' => [
                                       [
                                               'displayname',
                                               'sn',
                                               'givenname',
                                               'cn'
                                           ]
                                   ]
                           ]
                   ]
           ]
```
Or sth like this.

**Comment by dilyanpalauzov** [comment]
I would say the VLV index concept does not exist under OpenLDAP.  The above statements are relevant only for DS389.

How to configure OpenLDAP as addressbook in RoundCube, to use VLV, when the server supports VLV, but no VLV indices, and no ` numSubOrdinates`?

```php
  'fuzzy_search'   => true,                                                                    
  'vlv'            => true,        
  'vlv_search'     => true,             
  'numsub_filter'  => false,                                                                  
  'config_root_dn' => false,                                             
```

With the above configuration, and `$config['ldap_debug']= true;` the log is:
```
[02-Jan-2023 09:39:31 +0000]: <29bc4212> S: OK                                                                                  [0/1901]
[02-Jan-2023 09:39:31 +0000]: <29bc4212> C: Close
[02-Jan-2023 09:39:31 +0000]: <29bc4212> C: Connect [ldap://ldap.aegee.org:389:389]
[02-Jan-2023 09:39:31 +0000]: <29bc4212> S: OK
[02-Jan-2023 09:39:31 +0000]: <29bc4212> C: Search base dn: [cn=bodies,dc=aegee,dc=org] scope [one] with filter [(objectclass=*)]
[02-Jan-2023 09:39:31 +0000]: <29bc4212> Using function ldap_list on scope one ($ns_function is ldap_read)
[02-Jan-2023 09:39:31 +0000]: <29bc4212> C: (Without VLV) Setting a filter of (objectclass=*)
[02-Jan-2023 09:39:31 +0000]: <29bc4212> Executing search with return attributes: array (
  0 => 'cn',
  1 => 'sn',
  2 => 'givenname',
  3 => 'title',
  4 => 'mail',
  5 => 'telephonenumber',
  6 => 'postaladdress',
  7 => 'labeleduri',
  8 => 'postalcode',
  9 => 'st',
  10 => 'l',
  11 => 'departmentnumber',
  12 => 'ou',
  13 => 'description',
  14 => 'objectClass',
)
[02-Jan-2023 09:39:31 +0000]: <29bc4212> S: 180 record(s) found
[02-Jan-2023 09:39:31 +0000]: <29bc4212> C: Close
```
so VLV is not used, despite being supported by the server.

**Comment by dilyanpalauzov** [comment]
> ldapsearch -ZZxH ldap://ldap.aegee.org -b "dc=aegee,dc=org"

returns all entries and 

> ldapsearch -ZZxH ldap://ldap.aegee.org -b "dc=aegee,dc=org" -s sub -E sss=ou:2.5.13.15 -E vlv="0/2/0/1"

does the same with VLV and SSS enabled (but ends with 
```
# search result
search: 93
result: 50 Insufficient access
```
, likely when requesting the dc=aegee,dc=org, or ou=bodies,dc=aegee,dc=org leaves.)

Can you construct a VLV-LDAP query for ldapsearch, which is going to fail, (e.g. as there is no VLV index)

**Comment by dilyanpalauzov** [comment]
The query below does not return an Insufficient access error.  How can I construct a request with ldap.aegee.org, which fails for VLV, because there are missing VLV-indices?
> ldapsearch -ZZxH ldap://ldap.aegee.org -b "dc=aegee,dc=org" -s sub -E sss=ou:2.5.13.15 -E vlv="0/2/0/1"

For the record, the results contain:
```
# search result
search: 91
result: 0 Success
control: 1.2.840.113556.1.4.474 false MAMKAQA=
sortResult: (0) Success
control: 2.16.840.1.113730.3.4.10 false MBUCAgCwAgIAtwoBAAQIALsQXNl/AAA=
vlvResult: pos=176 count=183 context=ALsQXNl/AAA= (0) Success
```
so the number of answers is 183, despite having no ` numSubOrdinates ` attribute.

**Comment by dilyanpalauzov** [comment]
> The query below does not return an Insufficient access error. 

Correct query is:

> ldapsearch -ZZxH ldap://ldap.aegee.org -b "cn=bodies,dc=aegee,dc=org" -s one -E sss=ou:2.5.13.15 -E vlv="0/190/0/1"

It does end with
```

# search result
search: 4
result: 76 Virtual List View error
control: 2.16.840.1.113730.3.4.10 false MBQCAQACAgC0CgFNBAgw3B5U2X8AAA==
vlvResult: pos=0 count=180 context=MNweVNl/AAA= (77) Unknown error
```
but the results are valid and useful.

**Comment by alecpl** [comment]
Net_LDAP3 library probably does not allow that. I'm not an LDAP expert, so I can't say for sure that it would be possible with some code changes there.

I'll fix the default for `vlv` setting, as discussed above.

**Comment by alecpl** [comment]
Fixed.
