### ISSUE TITLE
Suggestion to show full sender email address

### ISSUE THREAD

**Issue by FreedomScapeIsNotAvailable** [roundcube/roundcubemail#8836]
As a hosting provider, upon inspecting a hacked email address I found that when viewing a fake email from apparently a bank, it shows only the Bank's name in the from section, while upon mousover it shows the actual sender address.

Users usually do not hover with a mouse to check the sender email

I would be much more effective preventing inadvertent clicks on fake emails to immediately see the sender name AND sender email address. 

This problem exposes all users to clicks and downloads from fake sources and should be addressed on an interface level by displaying the sender email address prominently in the email view form.

![rc1](https://user-images.githubusercontent.com/121544568/209783897-53b46a88-80fb-458c-a0ab-a2a7b20ac32b.jpg)
![rc2](https://user-images.githubusercontent.com/121544568/209784360-1168461e-cb71-4906-91f6-424f948c287a.jpg)

**Comment by test2a** [comment]
I would add, if I have to copy the email, I have to reply to that email, go to address box , double click on name, THEN copy the email address.

**Comment by alecpl** [comment]
There's already a config option to change that:
```
// Enables display of email address with name instead of a name (and address in title)
$config['message_show_email'] = false;
```
