### ISSUE TITLE
strip TYPE=OTHER from QR contact export

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#8838]
When I view the raw data of QR codes, exported by Roundcube 1.6.0 ,they contain lines like
```
EMAIL;TYPE=INTERNET;TYPE=OTHER:x@y.z
EMAIL;TYPE=INTERNET;TYPE=WORK:a@b.c
TEL:TYPE=other:+123 456
EMAIL:TYPE=INTERNET;TYPE=HOME:mm@nn.pp
```
* Please remove TYPE=OTHER from the QR code, this is not defined and only adds extra data.
* Consider removing TYPE=INTERNET.  vCard data exchange works perfectly well without spelling explicitly TYPE=INTERNET
* In case TYPE=INTERNET will be kept, please combine `TYPE=INTERNET;TYPE=HOME:` into `TYPE=INTERNET,HOME:`

As removig TYPE=OTHER reduces the transferred data over the QR image, please consider exporting to QR something else in addition, e.g. birthday of the contact

**Comment by dilyanpalauzov** [comment]
See also https://github.com/mstilkerich/rcmcarddav/issues/412 .

**Comment by alecpl** [comment]
TYPE=OTHER is indeed not standard, so we should probably drop it. Dropping TYPE=INTERNET also makes sense as it is a default in vCard v3, and does not exist in v4.

**Comment by dilyanpalauzov** [comment]
How is rcmcarddav supposed to inject contacts into Rouncube-addressbooks without sending TYPE=OTHER?

LDAP does also inject contacts into the roundcube addressbooks, but when these are exported over QR-code do not contain TYPE=OTHER, just TYPE=INTERNET.

**Comment by alecpl** [comment]
Fixed.
