### ISSUE TITLE
Any way to add safe sender email ids ?

### ISSUE THREAD

**Issue by test2a** [roundcube/roundcubemail#8841]
I am using roundcube from mailinabox. 

I have to receive emails from a government department and I don't seem to get any in the inbox. Maybe they are bouncing, maybe they are getting behind spam but I don't see any in the junk inbox. 

Is there a way to "know" any emails that are being rejected by the server or a way to have safe sender to bypass any constraints ?

**Comment by test2a** [comment]
I would add, I've been using miab for over almost 2 years now and most of the emails I have, I get them faster than I get on gmail or something. Roundcube is much better in that regard but  I cannot "mark as spam" or this "see emails not actually received"

**Comment by alecpl** [comment]
Sounds like a SMTP server question/issue not Roundcube.
