### ISSUE TITLE
Edit event in calendar failed

### ISSUE THREAD

**Issue by fabiointegra** [roundcube/roundcubemail#8842]
I'm able to create event and other things, but if I edit the evend created, the event is deleted. 
Only show "failed to save changed"
Skin: Elastic

RoundCubeMail: 1.5.3
![image](https://user-images.githubusercontent.com/112642351/210078912-605c3afe-4462-44b8-b9cd-a16b7a0d4284.png)

Event created:
![image](https://user-images.githubusercontent.com/112642351/210079036-475dddee-c2eb-448a-bc62-2c1640a5cd57.png)
![image](https://user-images.githubusercontent.com/112642351/210079090-7f5e86cc-02a2-40e8-bc96-eba00e0e0e18.png)

Event edited:
![image](https://user-images.githubusercontent.com/112642351/210079144-10f0d11c-ce0b-4602-ae1f-6eb57a59af5e.png)
![image](https://user-images.githubusercontent.com/112642351/210079186-00cbd7d7-f847-4540-a3d0-d2a16279e1ee.png)
![image](https://user-images.githubusercontent.com/112642351/210079223-da454b63-cd93-4f6e-a931-f7b69e7aea7c.png)

I created clean installation, but same occour, and not show in calendar:
![image](https://user-images.githubusercontent.com/112642351/210079490-fe078e2f-7cb7-4a2a-8d61-76e86444b649.png)

**Comment by alecpl** [comment]
Check the error log. We do not support Calendar plugin here.

**Comment by fabiointegra** [comment]
I edited SQL, if someone have this issue, just run this... 

`CREATE OR REPLACE FUNCTION events_sensitivity_not_null__fn()
  RETURNS TRIGGER 
  LANGUAGE PLPGSQL
  AS
$$
BEGIN
	IF NEW.sensitivity IS NULL THEN
		 NEW.sensitivity := 0;
	END IF;

	RETURN NEW;
END;
$$;



CREATE TRIGGER events_sensitivity_not_null__tr
  BEFORE UPDATE
  ON events
  FOR EACH ROW
  EXECUTE PROCEDURE events_sensitivity_not_null__fn();`
  
  After everthing is ok.
