### ISSUE TITLE
Email content is not rendered with "oops error"

### ISSUE THREAD

**Issue by vadimkim** [roundcube/roundcubemail#8844]
Hi, 
Some e-mailes can't be displayed. Server shows error:
```
[03-Jan-2023 09:37:01 Europe/Tallinn] PHP Fatal error:  Uncaught IntlException: filemtime(): stat failed for /usr/local/www/roundcub
e/plugins/jqueryui/js/i18n/datepicker-et.min.js in /usr/local/www/roundcube/program/include/rcmail_output_html.php:1068
Stack trace:
#0 /usr/local/www/roundcube/program/include/rcmail_output_html.php(1068): filemtime('/usr/local/www/...')
#1 /usr/local/www/roundcube/program/include/rcmail_output_html.php(1029): rcmail_output_html->file_mod('plugins/jqueryu...')
#2 [internal function]: rcmail_output_html->file_callback(Array)
#3 /usr/local/www/roundcube/program/include/rcmail_output_html.php(1008): preg_replace_callback('!(src|href|back...', Array, '<!DOCT
YPE html>...')
#4 /usr/local/www/roundcube/program/include/rcmail_output_html.php(2148): rcmail_output_html->fix_paths('<!DOCTYPE html>...')
#5 /usr/local/www/roundcube/program/include/rcmail_output_html.php(706): rcmail_output_html->_write('<!DOCTYPE html>...')
#6 /usr/local/www/roundcube/program/include/rcmail_output_html.php(845): rcmail_output_html->write('<!DOCTYPE html>...')
#7 /usr/local/www/roundcube/program/include/rcmail_output_html.php(654): rcmail_output_html->parse('message', false)
#8 /usr/local/www/roundcube/program/actions/mail/show.php(164): rcmail_output_html->send('message', false)
#9 /usr/local/www/roundcube/program/include/rcmail.php(275): rcmail_action_mail_show->run(Array)
#10 /usr/local/www/roundcube/index.php(278): rcmail->action_handler()
#11 {main}

```
What can be wrong? Thanks.

**Comment by alecpl** [comment]
This smells of some PHP bug. What OS/PHP version? Are you using OPcache?

**Comment by alecpl** [comment]
Oh, and there's already a few old tickets from FreeBSD users with similar errors. Make sure you restarted php-fpm, also you can try to update php-intl package.

**Comment by vadimkim** [comment]
You are right - I am using FreeBSD 13 with php81 and Intl library version 8.1.13
php-fpm restart, reinstall and upgrade of the packages didn't help.

**Comment by vadimkim** [comment]
The problem is found. It is a bug at the code. Particularly here (as stated in exception):
```
Uncaught IntlException: filemtime(): stat failed for /usr/local/www/roundcub
e/plugins/jqueryui/js/i18n/datepicker-et.min.js in /usr/local/www/roundcube/program/include/rcmail_output_html.php:1068
```
If you go to i18n folder you can find that there are no minified files, only *.js
Right now the workaround is to copy corresponding locale file to "min.js". In my case I just executed:
```
cp datepicker-et.js datepicker-et.min.js
```
After that everything starts to work normally.

**Comment by alecpl** [comment]
No. `@filemtime()` is a common technique to ignore a PHP warning if file does not exist. It should not throw an error, nor an exception. And for sure it has nothing to do with `IntlException`.

**Comment by vadimkim** [comment]
It doesn't matter if you throw an exception or ignore it. JS file is not loaded and thus e-mail context is not rendered. There are 2 options:

1. Either supply jquery roundcube plugin with minified JS files
2. Or fix the code and replace filename before loading by removing '.min' from it's name. 

If you re-open the issue I will try to make change nr. 2
