### ISSUE TITLE
Managesieve: base64 encoded vacation :from field

### ISSUE THREAD

**Issue by rgergo67** [roundcube/roundcubemail#8845]
Hello,

I have faced the following problem: 

When I create a vacation in roundcube and set the from field (Reply sender address) to **Ratting Gábor <ratting.gergo@uni-pannon.hu>** , the vacation e-mail that get's delivered has the from field: **From: "=?UTF-8?B?UmF0dGluZyBHw6Fib3I=?=" <ratting.gergo@uni-pannon.hu>**

![image](https://user-images.githubusercontent.com/143978/210326933-39568bbd-e883-48b4-9348-049d8860084e.png)

If I remove the =?UTF-8?B? part and base64 decode the remaining UmF0dGluZyBHw6Fib3I=?= I get Ratting Gábor. The problem occurs in thunderbird, webmail and gmail, in chrome and in firefox too.

When I use only ascii characters, there is no problem. Ratting Gabor <ratting.gergo@uni-pannon.hu> works well, only names with accents and other special characters are encoded to base64.

This was the commit that made able to add name part before the email address: https://github.com/roundcube/roundcubemail/pull/6763/commits/fca01abb6a0b476434aea7bc707fbdc69d47268e

As far as I could debug the issue, the following block causes the problem, here gets the plain text base64 encoded, but only if it has special characters (like űáéúő):
https://github.com/roundcube/roundcubemail/blob/a7f25ffb25a9199644761e49d21be92d7a23e3a8/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php#L243

Thank you for looking into it,
Best regards!

**Comment by dodver** [comment]
Hello,

As to provide some more information I quote an example sieve script that is generated by the Managesieve Roundcube plugin on server-side:

`require ["date","relational","vacation"];
# rule:[Irodán kívül]
if allof (currentdate :zone "+0100" :value "ge" "date" "2022-12-31", currentdate :zone "+0100" :value "le" "date" "2023-02-01")
{
        vacation :days 1 :subject "[ Automatikus válasz ] Szabadság" :from "=?UTF-8?B?TWFydG9uIEfDoWJvcg==?=<marton.gabor@uni-pannon.hu>" text:
Tisztelt Levélíró!

2022.09.14. napjától 2022.09.27. napjáig szabadságon vagyok, leveleimet korlátozottan látom.

Üdvözlettel:
.
;
}`

I suspect that the vacation extension of sieve makes an other round of base64 encoding on the string provided to the :from parameter. Obviously on the receiver side the From: mail header gets decoded only once, not twice, resulting in the aforementioned issue. 

Thanks for investigating the issue.
Gabor MARTON

**Comment by alecpl** [comment]
`Ratting Gábor ratting.gergo@uni-pannon.hu` is not a proper address form. It should be `Ratting Gábor <ratting.gergo@uni-pannon.hu>` or `"Ratting Gábor" <ratting.gergo@uni-pannon.hu>`.

That being said, if I use `Ratting Gábor ratting.gergo@uni-pannon.hu` the output script is  `:from "ratting.gergo@uni-pannon.pl"`, so I can't reproduce.

**Comment by alecpl** [comment]
Ok, I misunderstood the issue because Github is eating brackets. I now added some backticks in your last comment to display output properly.

The `:from` value is properly formatted/encoded according to https://www.rfc-editor.org/rfc/rfc5230.html#section-4.3. So, I think if there's a bug it is in your managesieve server, not Roundcube. Looks the server is encoding the encoded value again, while it should not.
