### ISSUE TITLE
IMAP doesn't connect

### ISSUE THREAD

**Issue by Shandeika** [roundcube/roundcubemail#8847]
At step 3 of the installation, it is suggested to check SMTP and IMAP. SMTP works, emails are sent and arrive in the mailbox, but there is a problem with IMAP.
```
Connecting to 92.53.104.48:143...
IMAP connect:  NOT OK(Login failed for administrator@example.com against 92.53.104.48 from MY_IP. Authentication failed.)
```
Tried ssl:// and tls:// with port 993, tried localhost and server name, but nothing works.
With ssl, this is the error:
```
Connecting to ssl://92.53.104.48:993...
IMAP connect:  NOT OK(Login failed for administrator@example.com against 92.53.104.48 from MY_IP. Could not connect to ssl://92.53.104.48:993: Unknown reason)
```
With https://pingability.com/mailtest .jsp checked the connectivity, everything works.
Help solve the problem, please :)

**Comment by alecpl** [comment]
"Unknown reason" usually means a problem with SSL certificate.

**Comment by Shandeika** [comment]
> "Unknown reason" usually means a problem with SSL certificate.

Come on with this SSL and certificate, even if it worked without encryption, but no.
Can you help?

**Comment by Shandeika** [comment]
Solved the problem by editing `config.inc.php`:
Added `$config['imap_auth_type'] there = 'LOGIN';`
I took the information from the file `defaults.inc.php`

I don't understand why this value is not set by default, however, it doesn't matter anymore :)
