### ISSUE TITLE
Release new roundcube version to bump net_stmp version

### ISSUE THREAD

**Issue by ibotty** [roundcube/roundcubemail#8848]
The problem below is fixed, but not yet released.  Roundcube fixes its dependencies. So all versions built from the release tarball don't include the fix in the updated dependency net_smtp.

Please release a new version that bump at least this dependency.

Thank you!

<del>
Reading [https://www.rfc-editor.org/rfc/rfc4954#section-4](RFC 4954 secton 4):

> Note that the AUTH command is still subject to the line length limitations defined in [[SMTP](https://www.rfc-editor.org/rfc/rfc4954#ref-SMTP)].  If use of the initial response argument would cause the AUTH command to exceed this length, the client MUST NOT use the initial response parameter (and instead proceed as defined in Section 5.1 of [[SASL](https://www.rfc-editor.org/rfc/rfc4954#ref-SASL)]).

I assume that the command that roundcube is sending is not standard compliant.  In fact in my installation the length of the auth command is 2149 characters.

[Microsoft](https://learn.microsoft.com/en-us/exchange/client-developer/legacy-protocols/how-to-authenticate-an-imap-pop-smtp-application-by-using-oauth) has a sample exchange.

This leads to problems with dovecot's submissiond, which enforces a limit (of 500 characters, maybe: I did not read the source closely).
</del>

**Comment by ibotty** [comment]
Hah.  When trying to fix this I noticed that it's already fixed in Net_SMTP.  Closing.  It's just neccessary to update to the latest version.

**Comment by alecpl** [comment]
Net_SMTP 1.10.1 will be included in the next release.
