### ISSUE TITLE
bug(postgresql): user_ids does not exist

### ISSUE THREAD

**Issue by DrBu7cher** [roundcube/roundcubemail#8849]
In the migration [2013042700](https://github.com/roundcube/roundcubemail/blob/master/SQL/postgres/2013042700.sql) the Sequence user_ids is supposed to be renamed to `users_seq`, but since it never get's created, it is failing to rename it.

**Comment by alecpl** [comment]
What exactly are you doing?

**Comment by DrBu7cher** [comment]
Installing roundcube?

**Comment by alecpl** [comment]
If you install Roundcube these migration files shouldn't be even used.

**Comment by DrBu7cher** [comment]
Good to know...
