### ISSUE TITLE
No data was saved.

### ISSUE THREAD

**Issue by imsahiraf** [roundcube/roundcubemail#8855]
Hi,

I am currently facing to issue with Roundcube.
1)The first one is with OS compatibility when I use RoundCube in OS like CentOS or Ubuntu it's the usage count proper but when I use Almalinux or Cloudlinux it shows unknown instead of Usage calculation.
2)The second one is with `roundcube_sessid` I am using two SQLite DB at a time whenever the user is on the login page I am using the default DB for all the Email users but while posting the data I am justifying their DB path with the login Credentials. And I am getting `Invalid Request, No Data was saved ` error. This is only happening in CentOS and Ubuntu Server but when I use Almulinux for the same it is working properly.

Any solution regarding this.
Thanks in advance.

**Comment by alecpl** [comment]
1) the IMAP server does not support or does not advertise QUOTA support over IMAP (CAPABILITY).
2) the logon form is secured with the session. So, it won't work if you store session in DB. But I don't really know what do you do exactly with that DB.

**Comment by imsahiraf** [comment]
1) We are using Dovecot Service for IMAP and its do support CentOS and Ubuntu only facing issue with Almalinux and Cloudlinux.
2)We are not storing session in DB I think RoundCube do it itself that's why DB is required on every page. So while trying to log in with Request we give the New DB path in the first attempt it got fails and shows an error but in the second one, it got succeeded. One more thing when we put `$auth['valid'] = true` it works fine but I think it could be a security bug so we are not trying this. And at last, we have been to `https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php` this page and found the below code.
```
if (empty($_COOKIE[ini_get('session.name')]) || $token !== $sess_tok) {
            $this->request_status = self::REQUEST_ERROR_TOKEN;
            return false;
        }
```
Here the or condition `$token !== $sess_tok` is getting true because at first login the sess_tok was stored in default DB, not in Main DB.

**Comment by imsahiraf** [comment]
1)We are using Dovecot Service for IMAP and its do support CentOS and Ubuntu only facing issue with Almalinux and Cloudlinux.

2)We are not storing session in DB I think RoundCube do it itself that's why DB is required on every page. So while trying to log in with Request we give the New DB path in the first attempt it got fails and shows an error but in the second one, it got succeeded. One more thing when we put $auth['valid'] = true it works fine but I think it could be a security bug so we are not trying this. And at last, we have been to https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube.php this page and found the below code.
```
if (empty($_COOKIE[ini_get('session.name')]) || $token !== $sess_tok) {
            $this->request_status = self::REQUEST_ERROR_TOKEN;
            return false;
        }
```
Here the or condition $token !== $sess_tok is getting true because at first login the sess_tok was stored in default DB, not in Main DB in `check_request` function. Any suggestions?
