### ISSUE TITLE
Cannot Log in to Email

### ISSUE THREAD

**Issue by williamjzeman** [roundcube/roundcubemail#8859]
All of a sudden there is a new log in page, and my username and password return a simple error message:

login failed

There is no remedy offered such as reset password, etc.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
