### ISSUE TITLE
Proxy doesn't support in Roundcube Latest Version

### ISSUE THREAD

**Issue by imsahiraf** [roundcube/roundcubemail#8863]
Hi,

I am now using Roundcube's Latest Version 1.6 but I cannot make a proxy. Previously we were using 1.4.11 and we were able to make a proxy, now we get the login page but while posting data it redirects to the original URL and gives us a 404 error.

Can anyone help regarding this.

**Comment by alecpl** [comment]
Sounds like a duplicate of #8738.
