### ISSUE TITLE
Iframe login

### ISSUE THREAD

**Issue by Liia-Dulher** [roundcube/roundcubemail#8864]
I am trying to put my roundcube into iframe. First I got only server send no response errors. After using [this issue](https://github.com/roundcube/roundcubemail/issues/7697) I was able to see login page. But I couldn't login. I used all tips from issue, but it didn't help. Then I looked at [this one](https://github.com/roundcube/roundcubemail/issues/6057), but as I can see code changed dramatically from version 1.3 to 1.6, which I have; and I cannot use issue. Also as I see that problem still exists. 
I used: add to **config.inc.php**:  ` $config['x_frame_options'] = false; $config['x_frame_origine'] = false;`.
Change in **rcube_utils.php** function *setcookie*: `$attrib['samesite'] = null;`
add to **rcube.php** into *session_init()*: `ini_set('session.cookie_samesite', NULL);`
Could you please help me with this?

**Comment by alecpl** [comment]
Not enough info, but it sounds like a config issue. Ask on mailing list or forum. Check all headers, browser console for errors.
