### ISSUE TITLE
Blank message when edit long draft

### ISSUE THREAD

**Issue by uniauto** [roundcube/roundcubemail#8866]
Hi. 

I have a long draft (around 1k lines), but now if I try to edit it, it show me a blank editor.
I know the text is there because I can see it using "view source code".
There not any console error.
I can see with Dev Tools that the text is inside a hidden textarea with id=composebody-content

Can roundcube handle long messages? its a bug?

Happend with Roundcube 1.6.0. 
Tried Elastic and Larry skins. Still happend.
Tried Google Chrome and Mozilla Firefox browsers. Still happend.
Tried copy text to new message. Still happend.
Tried copy text and remove random lines. Not happend. Added randon text again. Happend again.

Not happeing in old server with Roundcube 1.4.13 and Larry skin.

**Comment by alecpl** [comment]
This sounds like a TinyMCE bug. If I understand you're using the HTML mode, is that right? Any errors in browser console?

**Comment by alecpl** [comment]
Ok, I get it. Looks like a regression from #8108. I'll work on a fix.

**Comment by alecpl** [comment]
Fixed.
