### ISSUE TITLE
format_date results in a 500 error when $date is a DateTimeImmutable (kolab-plugins-tasklist)

### ISSUE THREAD

**Issue by conathan** [roundcube/roundcubemail#8867]
When testing out kolab-plugins-tasklist using the caldav driver (https://git.kolab.org/diffusion/RPK/history/dev%252Fmollekopf%252Fphp8-2/plugins/tasklist/ - Including the Fri Jan 13 commit) , I ran into the following:

<pre>
[17-Jan-2023 10:16:10 Canada/Pacific] PHP Fatal error:  Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, DateTimeImmutable given in /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/lib/Roundcube/rcube_utils.php:992
Stack trace:
#0 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/lib/Roundcube/rcube_utils.php(992): trim(Object(DateTimeImmutable))
#1 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/lib/Roundcube/rcube_utils.php(913): rcube_utils::clean_datestr(Object(DateTimeImmutable))
#2 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/include/rcmail.php(1548): rcube_utils::strtotime(Object(DateTimeImmutable))
#3 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/plugins/tasklist/tasklist.php(1193): rcmail->format_date(Object(DateTimeImmutable))
#4 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/plugins/tasklist/tasklist.php(1172): tasklist->encode_task(Array)
#5 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/plugins/tasklist/tasklist.php(1110): tasklist->tasks_data(Array)
#6 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/lib/Roundcube/rcube_plugin_api.php(573): tasklist->fetch_tasks()
#7 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/include/rcmail.php(255): rcube_plugin_api->exec_action('tasks.fetch')
#8 /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116165459/index.php(283): rcmail->action_handler()
#9 {main}
  thrown in /home/webapps/roundcube-bravenet/shared/www/roundcubemail.20230116171436/program/lib/Roundcube/rcube_utils.php on line 992
</pre>

Roundcube 1.5.3 (installed via EPEL), AlmaLinux 9.1

I fixed this by locally editing program/include/rcmail.php,
<pre>
public function format_date($date, $format = null, $convert = true)
-   if (is_object($date) && is_a($date, 'DateTime')) {
+  if (is_object($date) && (is_a($date, 'DateTime') || is_a($date, 'DateTimeImmutable'))) {
</pre>

Then comparing to Roundcube 1.6.0, I see it had a different fix that also seemed to work
<pre>
public function format_date($date, $format = null, $convert = true)
-   if (is_object($date) && is_a($date, 'DateTime')) {
+  if ($date instanceof DateTimeInterface) {
</pre>

**Comment by alecpl** [comment]
I guess we could backport this to 1.5 too, but it's not supported and there's no release planned in this branch.

**Comment by conathan** [comment]
For our own use,  we patch the version provided by epel (so won't impact us if this is addressed on roundcubemail 1.5.x or not),  

but I do suspect epel9 will be sticking with the 1.5.x branch for a while (I am not a epel developer), but Centos 7 (and earlier) have not seen them do a major version upgrade yet.

**Comment by alecpl** [comment]
Backported to the release-1.5 branch.
