### ISSUE TITLE
Cannot delete attachments on reply/forward

### ISSUE THREAD

**Issue by bsdice** [roundcube/roundcubemail#8868]
Running latest git master with PHP-FPM 8.2.1, Openresty 1.21.4.1.

Tested browsers were latest Chromium and also Pale Moon, on Arch.

When I select an older e-mail e.g. from Sent or the Archive which has a PDF attachment, press the Forward button so composer opens, then I want to delete that PDF from the e-mail, nothing happens. I can see the URL pointing to ...#delete, still nothing happens.

Bug? Feature? Thanks...

**Comment by alecpl** [comment]
Confirmed with draft edit. There were some significant changes regarding attachments handling in master. I'll take a look at this later.

**Comment by alecpl** [comment]
Fixed.

**Comment by bsdice** [comment]
Confirmed as working, awesome! :)
