### ISSUE TITLE
No emails come from notifications@elfsightmail.com

### ISSUE THREAD

**Issue by Elfsight100** [roundcube/roundcubemail#8871]
My name is Renata and I am an Elfsight Support Specialist. 

Recently one of the customers came to us and reported that his clients don't receive their emails from our email (notifications@elfsightmail.com). They have turned off spam protection, all emails come fine, but emails from our email - not. 

Could you please check if it's something wrong on your side?His clients use Roundcube. 

Also, could you please add this email to the white list of emails maybe?

**Comment by Elfsight100** [comment]
![#344951 Re_ Contact Form - Wolfgang Schroller - Go](https://user-images.githubusercontent.com/123156833/213657206-08e405bc-8fa6-4204-ac0b-33bd65f78f57.png)
Here is the reply which we have received from our customer.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

**Comment by Elfsight100** [comment]
-- Please reply above this line --


            Hello,

We have received your request 348695, thank you for contacting us!

We have been experiencing an unusually high number of requests these
days, so unfortunately, the response time is temporarily increased. We
are terribly sorry for the inconvenience.

Please expect our reply from 7:00 am to 5:00 pm CET Monday – Friday,
we will come to the rescue as promptly as possible.

While you're waiting, these are our recommendations:

	* Check out our Help Center - help.elfsight.com [1]
	* Ask the community for help - community.elfsight.com [2]
	* Provide your registered Elfsight account email if you're messaging
us from another email address.
	* Provide us with a direct link to the page with the widget. 

To send us any additional information, please reply to this message.

_________________

Regards,
Elfsight Support Team

Instagram [3] – take a look inside our team's real life


Links:
------
[1]
https://help.elfsight.com/?utm_source=email&utm_medium=elfsight&utm_campaign=auto-reply&utm_content=body-message&utm_keyword=step-1-help-center
[2] https://bit.ly/3Dlyxky
[3] https://elfsig.ht/3PP2sXq

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

  Connect with other Elfsight users — Community Forum [4]
Keep up with the news and updates — Changelog [5]
Get to know our amazing team — Instagram [6]

   SUPPORT, CUSTOMER SUPPORT SPECIALIST  7:00 am to 5:00 pm CET,
Monday to Friday  [7]



Links:
------
[1]
https://secure.helpscout.net/satisfaction/594331200/record/6345110202/1/
[2]
https://secure.helpscout.net/satisfaction/594331200/record/6345110202/2/
[3]
https://secure.helpscout.net/satisfaction/594331200/record/6345110202/3/
[4] https://bit.ly/3ISBqL1
[5] https://elfsig.ht/3AlDOYr
[6] https://elfsig.ht/3Bg8JYm
[7] https://bit.ly/3vmyzUr

**Comment by Elfsight100** [comment]
-- Please reply above this line --


            Hello,

We have received your request 348694, thank you for contacting us!

We have been experiencing an unusually high number of requests these
days, so unfortunately, the response time is temporarily increased. We
are terribly sorry for the inconvenience.

Please expect our reply from 7:00 am to 5:00 pm CET Monday – Friday,
we will come to the rescue as promptly as possible.

While you're waiting, these are our recommendations:

	* Check out our Help Center - help.elfsight.com [1]
	* Ask the community for help - community.elfsight.com [2]
	* Provide your registered Elfsight account email if you're messaging
us from another email address.
	* Provide us with a direct link to the page with the widget. 

To send us any additional information, please reply to this message.

_________________

Regards,
Elfsight Support Team

Instagram [3] – take a look inside our team's real life


Links:
------
[1]
https://help.elfsight.com/?utm_source=email&utm_medium=elfsight&utm_campaign=auto-reply&utm_content=body-message&utm_keyword=step-1-help-center
[2] https://bit.ly/3Dlyxky
[3] https://elfsig.ht/3PP2sXq

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]

  Connect with other Elfsight users — Community Forum [4]
Keep up with the news and updates — Changelog [5]
Get to know our amazing team — Instagram [6]

   SUPPORT, CUSTOMER SUPPORT SPECIALIST  7:00 am to 5:00 pm CET,
Monday to Friday  [7]



Links:
------
[1]
https://secure.helpscout.net/satisfaction/594331198/record/6345110170/1/
[2]
https://secure.helpscout.net/satisfaction/594331198/record/6345110170/2/
[3]
https://secure.helpscout.net/satisfaction/594331198/record/6345110170/3/
[4] https://bit.ly/3ISBqL1
[5] https://elfsig.ht/3AlDOYr
[6] https://elfsig.ht/3Bg8JYm
[7] https://bit.ly/3vmyzUr
