### ISSUE TITLE
php fatal error INTL_IDNA_VARIANT_UTS46

### ISSUE THREAD

**Issue by glenb77** [roundcube/roundcubemail#8875]
Using roundcube from arch linux many years. I don't know when this started but a few weeks ago it was fine. I am on php 8.13 and suddenly get 'Ooops something wrong' and in error log i have:

PHP Fatal error:  Uncaught Error: Undefined constant "INTL_IDNA_VARIANT_UTS46" in /usr/share/webapps/roundcubemail/program/lib/Roundcube/rcube_utils.php:1146

any way around this ? thanks i have php-intl and icu installed

**Comment by glenb77** [comment]
Apologies, this was a file conflict with my php-intl please close the issue. sorry again

**Comment by fighter777** [comment]
> Apologies, this was a file conflict with my php-intl please close the issue. sorry again

thank for you help, your issue is not useless ^^


apt-get remove php-intl
apt-get install php8.1-intl
