### ISSUE TITLE
Plugin Password/vpopmail and Mysql 8

### ISSUE THREAD

**Issue by gaffuso** [roundcube/roundcubemail#8877]
Dear,
I use roundcube 1.6 with plugin password and vpopmail.
The procedure Encrypt has been remove from mysql 8.0.
The query:
$config['password_query'] = 'UPDATE vpopmail set pw_passwd=Encrypt(%p,concat("$1$",right(md5(rand()),8 ),"$")),
pw_clear_passwd=%p where pw_name=%l and pw_domain=%d'; not work.

Have you solution?

Best Regards
Giovanni

**Comment by alecpl** [comment]
This is out of scope of this bug tracker. Maybe you should try vpopmaild driver.
