### ISSUE TITLE
roundcube 1.6.1 now requires php 8.1, is this expected?

### ISSUE THREAD

**Issue by ibotty** [roundcube/roundcubemail#8879]
At least indirectly.  Should this be reverted or at least announced somewhere?

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.
  Problem 1
    - symfony/deprecation-contracts is locked to version v3.2.0 and an update of this package was not requested.
    - symfony/deprecation-contracts v3.2.0 requires php >=8.1 -> your php version (8.0.20) does not satisfy that requirement.
  Problem 2
    - doctrine/instantiator is locked to version 2.0.0 and an update of this package was not requested.
    - doctrine/instantiator 2.0.0 requires php ^8.1 -> your php version (8.0.20) does not satisfy that requirement.
```

**Comment by alecpl** [comment]
Ok, so here's what's going on:
1. https://github.com/composer/composer/issues/5016 explains why `--no-dev` is ignored. The solution would be to remove `require-dev` section from composer.json when building a package. This will fix the issue of including dev dependencies and `doctrine/instantiator` package.
2. To solve  `symfony/deprecation-contracts` version issue we have to set platform.php=7.3 and remove use of `--ignore-platform-reqs` argument.

**Comment by alecpl** [comment]
Fixed in 510632250d985. The next release should not have this issue.

**Comment by alecpl** [comment]
I'm not sure about Debian, but in general... try `composer config platform.php 7.3` (or your PHP version) and then `composer update --no-dev`.

**Comment by darren12345** [comment]
Thanks. That seems to have worked.
