### ISSUE TITLE
Supported php 8.2

### ISSUE THREAD

**Issue by eveneme** [roundcube/roundcubemail#8881]
Please support php 7.2

**Comment by alecpl** [comment]
Which one exactly? ;) PHP 8.2 is supported, PHP 7.2 will not be.

**Comment by eveneme** [comment]
Sorry 8.2
Thanks!

**Comment by CodeShakingSheep** [comment]
Hi @alecpl ,
is PHP version 8.2 officially supported for Roundcube 1.6? If yes, can the official wiki page be updated? It still states

> Version 1.6
Initial release: 28 July 2022
PHP support: >=7.3 <=8.1

See https://github.com/roundcube/roundcubemail/wiki/Version-History.
Thanks.
