### ISSUE TITLE
How to change favicon & logos when using elastic skin

### ISSUE THREAD

**Issue by CombeeMike** [roundcube/roundcubemail#8882]
Hi,

I'm on a rather fresh install of `v1.5.3` and am trying to change the favicon and 2 logos (the small one in the upper right corner & the large one in the center when using the `elastic` skin:

![image](https://user-images.githubusercontent.com/30658772/214289989-ad9218d6-7c9a-4879-bc36-7dac9a719673.png)

Unfortunately this is way harder than I expected.

# What I've tried

I tried a few different approaches but none of them is working:

1. Use the `skin_logo` config with the following values:

    ```php
    $config['skin_logo'] = [
      "elastic:favicon" => "logos/favicon.ico",
      "favicon" => "logos/favicon.ico",
      "login" => "logos/lumi_646x534.jpg",
      "small" => "logos/logo.svg",
      "dark" => "logos/logo.svg",
      "small-dark" => "logos/logo.svg"
    ];
    ```
    All images are located in `roundcube_root/logos` and are reachable from the public absolute url `https://my.roundcube.com/logos/favicon.ico` etc.
    I tried different variations, with explicitly mentioning the skin, using a `*` instead, not mentioning the skin, absolute paths, relative paths etc. but none worked.
    The only custom logo which is actually shown is the `login` logo, everything else stays default.

2. Create a custom style which extends from `elastic` and only holds a very simple `meta.json` + the files `images/favicon.ico` & `images/logo.svg`:
    
    ```json
    {
      "name": "My Elastic",
      "author": "Michael",
      "extends": "elastic"
    }
    ```

3. Add an explicit `config` to the `meta.json` (based on [this forums post](https://www.roundcubeforum.net/index.php/topic,25149.msg68566.html#msg68566)):

    ```json
    {
      "name": "My Elastic",
      "author": "Michael",
      "extends": "elastic",
      "config": {
        "favicon": "/images/favicon.ico"
      }
    }
    ```

4. Replaced `favicon.ico` & `logo.svg` directly within `skins/elastic/images`
    -> ✅ Worked

In conclusion, options 1 - 3 did not work (neither my `favicon.ico`, nor my `logo.svg` were shown) and I was only able to use them by overwriting files within the original `elastic` skin (option 4), which I'd like to prevent if somehow possible.

# The question

What am I doing wrong?
I'd assume that option 1 would be the correct thing to do and should be working according to the comments above `skin_logo` [here](https://github.com/roundcube/roundcubemail/blob/master/config/defaults.inc.php).
Options 2 & 3 were only trial & error as I did not find any viable information on how to correctly extend an existing skin.

**Ps.:** I have the plugin `newmail_notifier` installed but also disabled it temporarily as I thought that it might interfere with the favicon but disabling it did not help either.

**Comment by LauraTaylorUK** [comment]
Version 1.5.x had pretty broken favicon/logos system, most of it did not work correctly.

You may need to upgrade to 1.6.1 to get things working. At least thats what I had to do. Here is what I'm using and it works:

```php
$config['skin_logo'] = array(
        "elastic:login[dark]"   => "logo-dark.png",
        "elastic:login"         => "logo-login.png",
        "elastic:*[dark]"       => "logo-dark.png",
        "*"                     => "logo.png"
);
```

About the favicon, I just replace the default one under `skins/elastic/images/favicon.ico`.

**Comment by CombeeMike** [comment]
@LauraTaylorUK Thanks for the info!
Just to get it right: You've overwritten the favicon because it doesn't work within the `skin_logo` array in `1.6.1` neither or are there any other reasons?

![image](https://user-images.githubusercontent.com/30658772/214590489-86291950-3257-4f86-9995-2e3237328cb7.png)

**Comment by LauraTaylorUK** [comment]
It did not work for me on a previous version (can't remember which one), since then my install script just overwrites the skin favicon.

I haven't tried with 1.6.1 to see if the issue was fixed.

**Comment by CombeeMike** [comment]
Ok, thank you for the info!
