### ISSUE TITLE
Upgrade: from 1.5.3 to 1.6.1 PHP Error: SMTP server does not support authentication

### ISSUE THREAD

**Issue by hristakiev** [roundcube/roundcubemail#8883]
Apache/2.4.38
PHP 7.3.31
When I try to send a letter with the old plugins and config says:
PHP Error: SMTP server does not support authentication
SMTP Error: Authentication failure
CHUNKING (Code: 250)  program/lib/Roundcube/rcube.php on line 1794

**Comment by alecpl** [comment]
Maybe some smtp_* settings has been lost in the config. Note, in 1.6.0 there was some changes regarding this. See changelog/release notes.

**Comment by hristakiev** [comment]
Thank you, for your reply.

Indeed was a problem from old config:

$config['smtp_server'] = 'localhost';

$config['smtp_port'] = 25;

to new 1.6.1

$config['smtp_host'] = 'localhost:25';
