### ISSUE TITLE
[question] permalinks for messages

### ISSUE THREAD

**Issue by szelga** [roundcube/roundcubemail#8886]
is there a feature somewhere to get permalinks for messages in RoundCube? currently the links you could get are not permanent, i.e., if you move the message from folder to folder, its link changes. if not, is there something about that exposed in API, so one could write a plugin implementing that?

**Comment by alecpl** [comment]
As far as I know there's no such thing in IMAP. I guess you'd have to to a search by Message-ID (in all folders), which would be less than optimal. Maybe there's some IMAP extension I'm not aware of.

**Comment by szelga** [comment]
thanks for the answer.
