### ISSUE TITLE
Cannot click show/edit filter using elastic skin

### ISSUE THREAD

**Issue by ptzulu** [roundcube/roundcubemail#8897]
Hi there.

I've been having this issue since elastic skin as been presented to the world :)
i've reinstalled multiple times, i've updated multiples times... and nothing changes the output...

screencast here for you guys to see
![Roundcube-Webmail](https://user-images.githubusercontent.com/9788819/215327043-9d388d35-3cc1-43e3-b369-3c5d1a7ccd9c.gif)

Any Help ?

Thank you!

**Comment by alecpl** [comment]
What version? What browser? Any errors in browser console?

**Comment by alecpl** [comment]
No feedback.
