### ISSUE TITLE
sharing calendar

### ISSUE THREAD

**Issue by loopguard404** [roundcube/roundcubemail#8899]
Hello, I installed the calendar plugin, everything works except that I can't share the calendar with other users. Is this feature only available in calendar plus ?

![image](https://user-images.githubusercontent.com/46474603/215386686-75587559-2489-4ca8-ad61-c30c561d3437.png)

**Comment by alecpl** [comment]
Sharing is possible only if you use Kolab driver. We do not support this plugin here.
