### ISSUE TITLE
Can't search for any e-mails

### ISSUE THREAD

**Issue by albstyle** [roundcube/roundcubemail#8903]
For quite some time now I'm unable to search for any e-mails in the search bar, it just simply doesn't go anywhere and stays thinking and thinking. Besides that any time a new e-mail arrives, the one I have currently open simply disapears and it's almost impossible to find it again, mostly because of the incapacity to search for it.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
