### ISSUE TITLE
Custom place in server and customize brand

### ISSUE THREAD

**Issue by ufo1990** [roundcube/roundcubemail#8907]
On my server I have custom place with doesn't change after update roundcube so I have few questions about this.
1. Any update roundcube doesn't change config file(config.inic.php) or watermark.html. I'm asking because I have have custom file confgi.inic.php.
2. How can I add custom style which won't overwrite after update? Can I add some parametr in config.inic.php or in antoher files?

**Comment by alecpl** [comment]
Use mailing list or forum, please.
