### ISSUE TITLE
ACL for authenticated users

### ISSUE THREAD

**Issue by SurajDadral** [roundcube/roundcubemail#8911]
Hi There,

The roundcube `acl` plugin doesn't have special `authenticated` identifier, which is supported by [dovecot](https://doc.dovecot.org/configuration_manual/acl/#acl-file-format).
Tried adding it here: https://github.com/roundcube/roundcubemail/blob/master/plugins/acl/acl.php#L32
And worked fine.
It will be good if this can be added by default in future versions of roundcube.

Thanks,

**Comment by alecpl** [comment]
Only `anyone` is mentioned in RFC4314. `anonymous` is supported by Cyrus IMAP, `authenticated` isn't.

I think we should rather set the default to `['anyone']`.

**Comment by SurajDadral** [comment]
Maybe an option can be given in config to list special identifiers, having default value `['anyone']`.

**Comment by alecpl** [comment]
There's an option already.

**Comment by SurajDadral** [comment]
Yes, got it with name `acl_specials`. This will do the job.
Thanks,

**Comment by alecpl** [comment]
The default set has been changed.
