### ISSUE TITLE
Duplicate recipients in the "To" and "Cc" fields

### ISSUE THREAD

**Issue by Krotyara86** [roundcube/roundcubemail#8912]
Hello.
After updating to version 1.6.1, when clicking "Reply to all" in the "Sent Items" folder, the recipients are duplicated in the "Cc" field.

**Comment by alecpl** [comment]
We'll need more details.

Does it happen with all plugins disabled? Precise steps to reproduce the issue, please. What are the email headers and what is the result?

**Comment by Krotyara86** [comment]
All plugins are disabled.

1. Open the Sent folder.
2. I choose any message, I click Reply to all.
3. The message reply window opens, with the same recipient in the Cc field as in the To field.

In a sent message, the To and Cc headers are filled in the same way.

**Comment by alecpl** [comment]
I'm unable to reproduce. What the sent message has in To and Cc? Which address is in your identities?

**Comment by johndoh** [comment]
I think its this line https://github.com/roundcube/roundcubemail/blob/master/program/include/rcmail_sendmail.php#L1129

*) Message is in your Sent box
*) Message is from your default identity to a an external address
*) message is To a single recipient
*) hit Reply All

If the message has To and Cc recipients you get both the To and Cc recipients in the Cc box on the compose screen.

It only happens with messages in the Sent folder

**Comment by Krotyara86** [comment]
Yes, that's right. There can only be multiple recipients, and they will all appear in the Cc field.

If you comment out the specified "if" block, then the problem does not appear.

> Which address is in your identities?

For example test@test.com

>  What the sent message has in To and Cc?

Initially, the message contains only the recipient in the To field, for example test2@domain.net

When I click Reply All, in the message creation window, in the To and Cc fields the address test2@domain.net

**Comment by alecpl** [comment]
Ok, this is caused by the cleanup in 825bcf5af70f072d5238f4eed95999b6016aa945. We have to bring back `$message->recipients`. It was making sure there are no duplicates.

**Comment by alecpl** [comment]
Fixed.
