### ISSUE TITLE
IMAP Test Login with SSL errored at TLS version incompatibility

### ISSUE THREAD

**Issue by bagasme** [roundcube/roundcubemail#8915]
Hi,

I'm trying to set up Roundcube for my internal network (actually hosted on my LXD container for private purposes). The mail server (domain: `ohmymail.net`) and RC app (domain:`web.ohmymail.net`) are installed on separate containers within the same "projects".

For the mail server, I set it up by following [tutorial from Linode](https://www.linode.com/docs/guides/email-with-postfix-dovecot-and-mysql/).

The RC configuration connecting to the mail server (IMAP and SMTP) is:

```
...
$config['imap_host'] = 'ssl://ohmymail.net:993';
$config['smtp_host'] = 'ssl://ohmymail.net:465';
```

The TLS certificate used by both mail server and RC app is ECDSA with SHA-384 certificate, issued by in-house CA where I have control.

When I tried to install Roundcube and test IMAP login, the Dovecot log says:

```
Feb  9 09:06:06 ohmymail dovecot: imap-login: Debug: SSL error: SSL_accept() failed: error:0A000418:SSL routines::tlsv1 alert unknown ca: SSL alert number 48
Feb  9 09:06:06 ohmymail dovecot: imap-login: Disconnected: Connection closed: SSL_accept() failed: error:0A000418:SSL routines::tlsv1 alert unknown ca: SSL alert number 48 (no auth attempts in 1 secs): user=<>, rip=fd42:998f:9868:a877:216:3eff:fef4:37b2, lip=fd42:998f:9868:a877:216:3eff:fe0a:d211, TLS handshaking: SSL_accept() failed: error:0A000418:SSL routines::tlsv1 alert unknown ca: SSL alert number 48, session=<WubnsED0fpD9QpmPmGiodwIWPv/+9Dey>
```

Following the similar issue discussed on [Let's Encrypt forum](https://community.letsencrypt.org/t/dovecot-error-certificate-unknown/167859) and from the log above, it seems like RC is forcing TLSv1.0, whereas my Dovecot configuration in the mail server specifies TLSv1.2 as minimum supported TLS version, thus the incompatibility error.

This issue occured whether `php-imap` package is installed or not.

Mutt and Thunderbird are not affected, as they use the correct TLS version when connecting to the mail server.

**Comment by alecpl** [comment]
Roundcube does not force that. It will be PHP's "fault".

You can use `$config['imap_conn_options']` option to set some SSL options. Something like:
```
$config['imap_conn_options'] = [
    'ssl' => [
        'crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
    ]
];
```
or sth like that. I'm not sure it works with `ssl://` or `tls://`. Also, maybe you need more recent PHP version.

**Comment by bagasme** [comment]
> Roundcube does not force that. It will be PHP's "fault".
> 
> You can use `$config['imap_conn_options']` option to set some SSL options. Something like:
> 
> ```
> $config['imap_conn_options'] = [
>     'ssl' => [
>         'crypto_method' => STREAM_CRYPTO_METHOD_TLSv1_2_CLIENT
>     ]
> ];
> ```
> 
> or sth like that. I'm not sure it works with `ssl://` or `tls://`. Also, maybe you need more recent PHP version.

Hello,

`imap_conn_options` takes all availabe options of [PHP SSL context](https://www.php.net/manual/en/context.ssl.php), but `crypto_method` isn't listed there, but rather as parameters of [`stream_socket_enable_crypto`](https://www.php.net/manual/en/function.stream-socket-enable-crypto.php).

I guess `crypto_method` should be explicitly set for `ssl://` transport in `program/lib/Roundcube/rcube_imap_generic.php` just like what have been done in `tls://`  transport, right?
