### ISSUE TITLE
Managesieve: Support :encodeurl (RFC 5435)

### ISSUE THREAD

**Issue by schittli** [roundcube/roundcubemail#8917]
Good evening

thank you very much for sharing your great work!

If one saves a sieve filter, then RoundCube reads all filter sets, analyzes the rules, and then, recreates all sieve rules.
Unfortunately, in this process, it happens that a working sieve filter set is changed in such a way that filters do not work afterward.

Frustratingly, RoundCubde silently removes sieve filter elements and kills the filter function 😢 

### Steps to reproduce:

1. Open the editor to directly edit the code with the sieve filter rules, the screenshot shows which editor I talk about:
    ![image](https://user-images.githubusercontent.com/8282673/218270156-8bedb064-3de4-432d-bfae-99f2b727e941.png)

3. In the header:
    `require ["body", … ,"variables"];`
   add: `"encoded-character"`:
    `require ["body", … ,"variables","encoded-character"];`
		
4. Now, we add a Rule to set a new sieve variable. Please note that we use `:encodeurl`
    ```
    # rule:[Set global variable NewMsgBody: NewMsgBody]
    if true
    {
      set :encodeurl "NewMsgBody" text:
    This is a multi-
    line message
    .
    ;
    }
    ```
5. Save the rules. Everything should be OK.
    You even can close and reopen the Roundcube Browser session: the Sieve rules code keeps everything
7. Open any sieve rule in the UI Editor (it does not matter which one). The screenshot shows which editor I talk about:
    ![image](https://user-images.githubusercontent.com/8282673/218270484-39cf5e19-2989-4840-8e1a-8c90889fcaf5.png)
8. Now, just press `save` to save the unchanged rule.

Now, if you open the sieve rules code editor, 
### then you can see that RoundCube has deleted important filter definition items 😢:

- in `require [...]`, 
    the element `"encoded-character"` got deleted, 
    even though the server knows this module and it can be successfully used in sieve rules.
- Roundcube silently changed the `set :encodeurl "NewMsgBody"` declaration, so that rule no longer works 😢.
    - The right definition is:
    `set :encodeurl "NewMsgBody" text: …`
    - Roundcube changed it to:
    `set "NewMsgBody" text: …`

### Propsal
* If RoundCube changes any sieve filter logic (if it removes filter definition elements), then at least a warning with the list of "erroneous" elements should be displayed.
* If possible, it would be great if the user then can choose to have RoundCube to keep the unknown elements anyway.

Thanks a lot, kind regards,
Thomas

**Comment by alecpl** [comment]
Roundcube will remove script features it does not support.

I'll keep the ticket open as a feature request to support `:encodeurl` parameter, as it's part of RFC5435 which is already supported.

`encoded-character` capability is another story. It's not required for `:encodeurl`.

**Comment by alecpl** [comment]
:encodeurl has been implemented.
