### ISSUE TITLE
Sieve Filter Editor: notify, element `:from`: please accept this kind of E-Mail: `'John Doe' <John.Doe@mydomain.com>`

### ISSUE THREAD

**Issue by schittli** [roundcube/roundcubemail#8918]
Good evening

RoundCube repors an error, if the user defines this kind of "from:" E-Mail Address:
`'John Doe' <John.Doe@mydomain.com>`
in this dialog:

![image](https://user-images.githubusercontent.com/8282673/218272882-99581bc5-7ce2-4673-acf0-abc8b695adf9.png)

Please, do accept this kind of E-Mail definition, because it is very useful to be able to define the E-Mail Address display value.

Thanks a lot, kind regards,
Thomas

**Comment by alecpl** [comment]
Indeed, we should fix that as we already support such input in other places.

Please, note that proper address format is with double-quotes.

**Comment by alecpl** [comment]
Done.

**Comment by schittli** [comment]
Hello @alecpl,
**thank you very much** for solving this issue!

Kind regards,
Thomas
