### ISSUE TITLE
Cannot access the roundcubemail website when using WIFI

### ISSUE THREAD

**Issue by niknazrin1998** [roundcube/roundcubemail#8921]
I have a problem that has been going on for about 6 months now. My workplace WIFI cannot seem to access the website steadily. What I meant by that is there are only certain times my workplace wifi can access the website eventhough the internet is completely fine. Unlike my personal hotspot, It can access the website without any problem at all. I have called the Internet Service Provider and they've helped me reset the wifi multiple times. It works right after the wifi reset but then later it will be inaccessible again. This frustrates me as I have no clue where the problem is.. and I have no solution other than to restart the wifi everytime this happens.
![Screenshot 2023-02-13 124910](https://user-images.githubusercontent.com/99280391/218373170-fbc52a86-ebcb-49a0-a12e-be59d0049bb8.png)

**Comment by alecpl** [comment]
I don't see how that's a Roundcube issue.
