### ISSUE TITLE
Microsoft 365

### ISSUE THREAD

**Issue by rjgout** [roundcube/roundcubemail#8926]
I get the following error:

AADSTS50011: The redirect URI 'https://domain.com/index.php/login/index.php/login/oauth' specified in the request does not match the redirect URIs configured for the application '------------'. Make sure the redirect URI sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/redirectUriMismatchError to learn more about how to fix this.

Trying to connect with Ouath. When I first click on Login with outlook button I get a imageless screen of the login page. Then when I click on login with outlook it gives me the error.

I am using the config from the defaults.inc.php file:

$config['oauth_provider'] = 'outlook';
$config['oauth_provider_name'] = 'Outlook.com';
$config['oauth_client_id'] = "---------------------";
$config['oauth_client_secret'] = "------------------";
$config['oauth_auth_uri'] = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize";
$config['oauth_token_uri'] = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
$config['oauth_identity_uri'] = "https://graph.microsoft.com/v1.0/me";
$config['oauth_identity_fields'] = ['email', 'userPrincipalName'];
$config['oauth_scope'] = "https://outlook.office365.com/IMAP.AccessAsUser.All https://outlook.office365.com/SMTP.Send User.Read offline_access";
$config['oauth_auth_parameters'] = ['nonce' => mt_rand()];

I am using version 1.6.1

Can someone help me getting it to work.

**Comment by alecpl** [comment]
Maybe #8878.

**Comment by rjgout** [comment]
When I add: $config['request_path'] = 'SCRIPT_NAME'; to the config I get an error in the bottom right after I login with outlook.

It says that it failed and that I should try again.

**Comment by rjgout** [comment]
Okay, I got it to work. The $config['oauth_client_secret'] should be the value instead of the secret-id. It only shows when you create a clientsecret. After that it is not visible anymore.
