### ISSUE TITLE
keep_alive not sent if refresh is sent

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#8927]
Hi,

I have a weird problem: I noticed that if you have your mail list open, the web interface only sends "refresh" actions periodically, but never a "keep-alive".

Looking in the JS console and in the sourcecode, this should not be possible and there should be some keep-alive requests, but I'm not seeing any (console open for over 1h):

![image](https://user-images.githubusercontent.com/11192306/219360577-0329457c-c5a8-47cf-ac60-ea1969bc58a0.png)

The "refresh" actions are triggered in a 10min interval. With a `session_lifetime` defined at 20min this happens to line-up exactly with the period calculated for the `_keepalive` time. Before any keep_alive request is sent, the handler checks if the `busy` Flag is set.

My guess is, that the `refresh` timer runs first, sets the `busy` flag and the `keep_alive` timer never gets executed.

I would suggest offsetting the `refresh` or `keep_alive` timer by some seconds if they happen to have the same interval.

Using roundcube 1.5.4

**Comment by alecpl** [comment]
This is intended. Keep-alive is only needed if there's no other request to the server for a while. Any request, including refresh is keeping the session alive.

Also, 1.5 is not supported anymore.

**Comment by codegain** [comment]
Got it 👍  I didn't know if this was intentional or not.

Regarding 1.5: It's still LTS (security updates) right? At least according to https://roundcube.net/download/
