### ISSUE TITLE
Different max_filesize for importing messages and attachments

### ISSUE THREAD

**Issue by codegain** [roundcube/roundcubemail#8932]
Hi,

I noticed that uploading attachments and importing messages use the same max_filesize derived from `upload_max_filesize`/`post_max_size` because no `file_size` is explicitly set in `message_import_form`:

https://github.com/roundcube/roundcubemail/blob/master/program/actions/mail/index.php#L1665

I would like to increase the limit for importing messages to like 100MB but keep the current maximum upload filesize of 20MB (because files bigger than that are often rejected by the recipient server anyway).

A configurable size limit for both of these actions would be ideal.

**Comment by alecpl** [comment]
There are other upload forms in Roundcube. I'm not sure if adding options for every of them would make sense. Create a pull request and we'll see.

You could use `max_message_size` setting to define max size of a sent message, therefore also limiting the attachments size. And increase the global limit.
