### ISSUE TITLE
Defining logo image with only a path causes the logo to be clickable and lead to the logo image

### ISSUE THREAD

**Issue by spantaleev** [roundcube/roundcubemail#8933]
I'm using Roundcube 1.6.1.

I've tried a bunch of combinations like these:

```php
// Relative to skin
$config['skin_logo'] = '/my-image.png';

// Relative to the document root
$config['skin_logo'] = 'my-image.png';

// Relative to the document root
$config['skin_logo'] = 'https://DOMAIN/my-image.png';
```

In all instances, HTML like this was generated:

```html
<img src="my-image.png" id="logo" alt="Logo" onclick="location.href='my-image.png';" style="cursor:pointer;">
```

My expectation was that if I don't mess with the new `skin_logo` format (`'[link]' => ...` stuff), then the logo would:

- either default to not being a link (e.g. `<img src="my-image.png" id="logo" alt="Logo" />`)
- default to a sane "home" URL - the base url or something (e.g. `<img src="my-image.png" id="logo" alt="Logo" onclick="location.href='/';" style="cursor:pointer;">`)

Instead, it's linking me to the logo image itself.. which is pointless. No one who clicks on the logo expects to see it in full size.

-----

This seems to be caused by https://github.com/roundcube/roundcubemail/pull/8509 and by `get_template_logo` doing weird stuff.

https://github.com/roundcube/roundcubemail/pull/8509 checks if the result of `$this->get_template_logo('link')` is `null` or not. If it gets a non-null result, it will link to it.

However, `get_template_logo` behaves strangely. When `$config['skin_logo']` is not an array (like in this case.. where it's a simple string), and we ask `get_template_logo` for something like `link` (e.g. `get_template_logo('link')`), then it simply returns the `$config['skin_logo']` value as is. See the `else` statement here: https://github.com/roundcube/roundcubemail/blob/85973477f465c5da21ff9b58af4386c7e57ec92e/program/include/rcmail_output_html.php#L2783-L2785

This is clearly wrong. Perhaps when `$type` is `link`, we need special handling (returning `null`)? Or maybe when `$type` is anything other than `null`, we need special handling  (returning `null`)?

-----

The `get_template_logo` function does too much. The `$config['skin_logo']` option also does too much.

It's no surprise that it's buggy.

-----

To work around the issue, I'm using an array (map) for `$config['skin_logo'] ` which explicitly defines both the logo image and the link, like this:

```php
$config['skin_logo'] = [
	'*' => '/logo.png', 
	'[link]' => '/',
];
```

**Comment by alecpl** [comment]
Fixed.
