### ISSUE TITLE
Unzip javascript dependencies with 7z

### ISSUE THREAD

**Issue by BeckeBauer** [roundcube/roundcubemail#8934]
When I install/upgrade javascript dependencies by executing `bin/install-jsdeps.sh`, the script stops since unzip is not present. My linux system uses 7z to unzip files instead. 

Is there an option to use 7z instead (e.g. by telling the scrip to look for 7z if unzip cannot be found)?

**Comment by alecpl** [comment]
It should be doable, but I think we should just use PHP zip extension which is a required one. Pull requests welcome.

ps. What distro is that?

**Comment by alecpl** [comment]
Thanks @johndoh, my mistake, the extension is indeed optional. Then the 7z fallback would still make sense I guess.

**Comment by BeckeBauer** [comment]
I am using the linux version distributed with Synology NAS. My current work around is to download found hier: [](https://oss.oracle.com/el4/unzip/unzip.html) https://oss.oracle.com/el4/unzip/unzip.html

**Comment by alecpl** [comment]
Done.

**Comment by BeckeBauer** [comment]
Thank you, it works perfectly 👍
