### ISSUE TITLE
Semikolon in password leads to faliure in Shibboleth environment

### ISSUE THREAD

**Issue by Axle245** [roundcube/roundcubemail#8936]
We are running Roundcube 1.6.0, the failure was quite hard to find. In the end just a password change led to solution. Everywhere else in the SSO enironment the password was working. In roundcube I was not able to login.

**Comment by alecpl** [comment]
Could you be more specific? Are you talking about a user password used to log in to Roundcube? Where did it fail exactly? IMAP authentication or somewhere else? Was it a problem with setting the password via Roundcube?

**Comment by Axle245** [comment]
The password is a user password. Shibboleth IdP worked as designed, gives the request back to the service provider. As I understood, there is communication between roundcube and Shibboleth SP. As roundcube tries to authenticate the user at IMAP, the failure happens

**Comment by alecpl** [comment]
I'm not sure what Shibboleth is exactly in this context. How do you know it's not an IMAP issue? You'd have to enable imap_debug in Roundcube and check the log. It would show whether Roundcube is sending a proper password to the IMAP server. Or did you setup some kind of SSO in Roundcube (but then I don't see how password would be involved)?

**Comment by bandisast** [comment]
>Or did you setup some kind of SSO

I believe that is the purpose of [Shibboleth](https://www.shibboleth.net/products/)

Are you perhaps using plain-text passwords?
