### ISSUE TITLE
Settings>Identities>Signature Box

### ISSUE THREAD

**Issue by DPWCo** [roundcube/roundcubemail#8940]
Recently I have become aware that entering signature info in Settings>Identities does not work the way it used to.

In HTML mode, I had direct access to HTML code creation and editing - now it seems I no longer do - for example if I want to include an image in my signature, I could directly specify the HTML code to do so ---- now it seems I can't. Apparently they want me to just "drag" an image into the code entry box, also I can not directly create a "TEXT" hyperlink or an "IMAGE" hyperlink.

If you already have previous HTML code in your signature, it does not display in HTML mode, so you can not edit it.

As soon as you toggle between "TEXT" and "HTML" entry mode ONCE, the signature entry box is often if not always COMPLETELY BLANK. Yet, if code has been defined, sometimes when composing a message, the signature works and sometimes it does not.

In other settings, I have "compose in HTML" option turned ON for composition of new messages.

My hosting provider has been un-able to figure this out.

cPanel Version | 106.0 (build 18)

Apache Version | 2.4.55

**Comment by alecpl** [comment]
What Roundcube version?  Any errors in Roundcube error log? Any errors in browser console? What browser?

**Comment by alecpl** [comment]
No feedback.
