### ISSUE TITLE
Default search mods

### ISSUE THREAD

**Issue by antiuser** [roundcube/roundcubemail#8943]
Hi there! I have a problem with default search checkboxes.
This is default settings
![image](https://user-images.githubusercontent.com/5499424/223942041-f92e672f-dc78-49b8-bc7b-dd859228b053.png)
But when user check any other boxes on the next search it will be reset, how to do this permanent? Or how to enable entire message search by default?

P. S. I tried to do this in config
`$config['search_mods'] = ['*' => ['subject'=>1, 'from'=>1, 'body'=>1], 'Sent' => ['subject'=>1, 'to'=>1]];
`but this is not help, nothing changed

Thank you

**Comment by antiuser** [comment]
After some research i found that search parameters saved after first logon and never changed in database even if something change in web interface.
One bad workaround do global default search_mod, then set NULL preferences in database and re-login to web interface. But this workaround is bad because drops other user settings.

BUG with saving user custom search in database

**Comment by antiuser** [comment]
Hmm, found one wonderful search platform - Apache Solr (and integrates to dovecot).
Search by 15 thousands emails by entire messages take 0.8 seconds. Will be great if roundcube became more adjustable by searching (assume, that administraror will use search platform).

Another question - how to enable default search by all directories?

**Comment by alecpl** [comment]
The search cope PR wasn't completed, and it hasn't been merged.

The search mods are being saved in the user prefs only when scope != 'all'.
