### ISSUE TITLE
Recovery password at login page

### ISSUE THREAD

**Issue by mvldebian** [roundcube/roundcubemail#8945]
Are there any updated plugins available with this feature? I've been looking but it's over 10 years old, and it depends on a plugin called taskbar that was abandoned.

**Comment by bbjork-work** [comment]
https://plugins.roundcube.net/#/packages/alfnru/password_recovery

**Comment by alecpl** [comment]
Password recovery can be done in many ways and requires user to provide some additional information (e.g. a phone number). Therefore it's not gonna happen in core.
