### ISSUE TITLE
Emoticons In R C 1.6.1

### ISSUE THREAD

**Issue by HighlyFavoredBA** [roundcube/roundcubemail#8947]
**I installed a new install of R C 1.6.1, and I uploaded a zip of the Emoticons directory that I've used for quite a white.  In the compose area, this Error message pops up (Failed to initialize plugin: emoticons).   Where can I find a up to date zip of the Emoticons directory?  Thanks!  :--)

My custom animated emojis are way too fun to not have!  :--)**

**Comment by alecpl** [comment]
There's a new version of TinyMCE and the emoticons plugin has been rewritten, it's not using images anymore.

**Comment by HighlyFavoredBA** [comment]
So, my animated emoticons are Obsolete?  The TinyMCE that I have with 1.6.1 is the same one that came with my 1.6.1 Install.  :--)

**Comment by HighlyFavoredBA** [comment]
With a fresh test install of 1.6.1, and turning the Emoticon plugin on, the Emoticons button shows up on my computer.  However, on phones, the updated TinyMCE Doesn't show the Emoticons button.

I'm still looking for a way to keep using custom animated emojis!  :--)

**Comment by HighlyFavoredBA** [comment]
Is there a Secure version that'll let me still use my custom animated emoticons, or does anybody have a clue how I can use my custom animated emoticons with the current version?!  :--)

**Comment by HighlyFavoredBA** [comment]
It looks like 1.4.13 is the Last version that allows me to use my non boring custom emoticons.  I currently plan to soon start using that version for as long as I can!  :--)
