### ISSUE TITLE
[Feature Request] On the Advanced Editor, allow emojis to open into a side panel alongside the editor instead of a popup window

### ISSUE THREAD

**Issue by Jieiku** [roundcube/roundcubemail#8949]
On the Advanced Editor, allow emojis to open into a side panel alongside the editor instead of a popup window.

The reason being is for the people love and make frequent use of emojis, they want them right there at their fingertips.

Currently you have to click to open the popup, then click to click on an emoji.

Is this part of roundcubes main code? or is this editor / emojis part of a library that roundcube uses? (If so which library, so I can ask there or see if I can make the change myself and submit as pull request)

![roundcube emojis](https://user-images.githubusercontent.com/106644/226123347-71bc2eaf-b280-4025-9bac-acce2bcb60d4.gif)

**Comment by alecpl** [comment]
It's a separate project https://github.com/tinymce/tinymce

**Comment by Jieiku** [comment]
Thanks! https://github.com/tinymce/tinymce/issues/8569

Maybe there is already a way to do it, if not maybe I can contribute.
