### ISSUE TITLE
When replying or forwarding, the signature is inserted below the original messages

### ISSUE THREAD

**Issue by twothreenine** [roundcube/roundcubemail#8954]
... but it should be inserted at the top, instead.

How it should look like:

```
This is a new message I'm writing

-- 
Here's my signature

-------------------------

By: xy
Sent: ...
To: xyz
Subject: ...

This is the message I'm trying to forward

On 2023-02-04 19:33, somebody wrote:
> This is an even older message
```

How it looks in v1.6.1:

```
This is a new message I'm writing

-------------------------

By: xy
Sent: ...
To: xyz
Subject: ...

This is the message I'm trying to forward

On 2023-02-04 19:33, somebody wrote:
> This is an even older message

-- 
Here's my signature
```

**Comment by alecpl** [comment]
Works for me. Is this in plain text mode? What do you have in Preferences > Compose Messages?

**Comment by twothreenine** [comment]
> What do you have in Preferences > Compose Messages?

I had the wrong setting for `When replying`: `Start new message below the quote`, changed it to above.
I wonder why that's the default setting, since replying above seems more common to me.
Anyways, thanks for the quick help.
