### ISSUE TITLE
Downloads: Unclear what "Dependent", "Complete" and "Framework" means

### ISSUE THREAD

**Issue by cweiske** [roundcube/roundcubemail#8955]
The download page https://roundcube.net/download/ offers three variants for version 1.6.1:
- Dependent
- Complete
- Framework

There is a footnote to "Dependent" that says
> 1. Dependent packages only contain sources which are licensed under the GPL but they require some third-party packages to be installed along with Roundcube. All requirements are listed in the INSTALL instructions within the package file.

... which tells me it is incomplete compared to "Complete".

But what is Framework for? What shall I download?

Is framework something I can build my own applications on top?

The installation instructions at https://github.com/roundcube/roundcubemail/wiki/Installation only say I shall "Download the archive file containing Roundcube" but also does not tell me which of the 3 variants I shall choose.

**Comment by alecpl** [comment]
Yes. As simple as that. Use "Complete" if you don't want to install dependencies by your own. Use "Framework" if you want to build an app using the framework part (folder program/lib/Roundcube) of Roundcube.
