### ISSUE TITLE
Upgrading RoundCube Webmail from v1.4.8 to 1.6.1

### ISSUE THREAD

**Issue by ssangho8** [roundcube/roundcubemail#8958]
Hi,

I'm currently using RoundCube Webmail v1.4.8 and trying to upgrade it to v1.6.1.

I noticed that I should run "installto.sh" to update, but I'm worried about the loss of data in use.

If I have few settings of RoundCube Webmail such as plugins, am I using Composer?

Also, is there any way to upgrade version without affecting any settings already in use?

**Comment by Waldmeisda** [comment]
I would suggest to install it into a new folder/vhost, slowly test your plugins. Once everything is working remove the old vhost/folder and replace it.  I had some issues with the new smtp settings and the new password schema for dovecot passwords (newer sha hash is used now.)
