### ISSUE TITLE
Roundcube OAuth login problems (auth0)

### ISSUE THREAD

**Issue by ncavallini** [roundcube/roundcubemail#8959]
Hi all,
I recently set up a Roundcube instance at https://mail.pcngroup.ch. 
I have OAuth setup (in a test environment) using auth0.com.
I'd lilke to use OAuth login to open the user's inbox in Roundcube. I therefore edited the `config.inc.php` this way:
```php
$config['oauth_provider'] = 'generic';
$config['oauth_provider_name'] = 'PCN ID';
$config['oauth_client_id'] = 'REDACTED';
$config['oauth_client_secret'] = 'REDACTED';
$config['oauth_auth_uri'] = 'https://pcngroup-test.eu.auth0.com/authorize/';
$config['oauth_token_uri'] = 'https://pcngroup-test.eu.auth0.com/oauth/token/';
$config['oauth_identity_uri'] = 'https://pcngroup-test.eu.auth0.com/userinfo/';
$config['oauth_scope'] = "email openid";
$config['oauth_auth_parameters'] = [];
$config['oauth_identity_fields'] = ['email'];
$config['oauth_login_redirect'] = true;
```
The are two problems that prevents users from logging in:

1. After logging in with the auth0 form (when it does show, because sometimes login just fails straight), I get redirected to a non-formatted roundcube login page and the login fails there (see pictures below). Moreover, console errors arise.
2. Callback URLs are inconsistent. If login fails, roundcube appends `index.php/login/oauth` each time to the URL, and this obviously creates a problem for auth0.

Does anyone experienced this in the past?
Thank you for your help.
Best,
ncavallini

<img width="301" alt="image" src="https://user-images.githubusercontent.com/73892369/228192271-b0b9b798-8473-426f-ade3-1485ab248aa4.png">
<img width="454" alt="image" src="https://user-images.githubusercontent.com/73892369/228192421-ae51f46f-cf35-4df9-a3f5-a1ba70d16ec5.png">

**Comment by felixauringer** [comment]
Hey, this issue is tracked [here](#8878). It is already fixed but not included in the current release. If you use an older release, OAuth should be working.

**Comment by ncavallini** [comment]
> Hey, this issue is tracked [here](https://github.com/roundcube/roundcubemail/issues/8878). It is already fixed but not included in the current release. If you use an older release, OAuth should be working.

Thanks, this solved the problem! Sorry for not seeing the other issue.

Regards
