### ISSUE TITLE
HTML Conversion Issues Within RoundCube ?????

### ISSUE THREAD

**Issue by acvegas** [roundcube/roundcubemail#8960]
I am creating an HTML message within cPanel/WHM RoundCube Mail Email Inbox. Does the cPanel/WHM RoundCube Mail Email Inbox allow for HTML Coding? If yes, it's not working correctly? How do I preview the HTML Message I have created within cPanel/WHM RoundCube Mail Email Inbox? NOTE: Before sending it to my client, I need to preview the HTML Code within the within cPanel/WHM Email Inbox area. See the images for clarification.

![HTML Issues 1](https://user-images.githubusercontent.com/29608103/228337954-36bb7499-7ba7-4050-ae95-40e9590ee2c0.png)

![HTML Issues 2](https://user-images.githubusercontent.com/29608103/228337960-ee26da0a-9d6b-4318-949b-fb98bad7bcd0.png)

![HTML Issues 3](https://user-images.githubusercontent.com/29608103/228337966-c54ebbab-4a15-4002-8a59-c483851340d6.png)

![HTML Issues 4](https://user-images.githubusercontent.com/29608103/228337967-177898f1-1dcc-443b-a221-66f18f74ff53.png)

(END)

**Comment by alecpl** [comment]
You're close. If you have a HTML code to use you can. Click the "three dots" button on the right side of the editor toolbar to show more buttons, there you'll find the HTML code button.

**Comment by acvegas** [comment]
> You're close. If you have a HTML code to use you can. Click the "three dots" button on the right side of the editor toolbar to show more buttons, there you'll find the HTML code button.

Ooohhh it's kinda hiding. Found it and it works. Thanks, Alecpl! :)
