### ISSUE TITLE
Connecting new bluehost roundcube email to Gmail error

### ISSUE THREAD

**Issue by Zorkdaork** [roundcube/roundcubemail#8963]
Hello, 

I've been following instructions (youtube) how to link my bluehost roundcube email to my gmail.

When i'm going through the 'check emails from other accounts' yellow box , I get an error:

-------------------------------------------------------------------------------
There is a problem connecting to mail.(personal email here)
--
  | The server has send this error back: "Connection timed out: There may be a problem with the settings you added. Please contact your other email provider to verify the correct server name and port."
Gebruikersnaam: |  
Wachtwoord: |  
POP-server: | Poort: 995

![problem linking roundcube to gmail](https://user-images.githubusercontent.com/129545752/229201336-aba8885b-7c04-4b35-9120-9d112c0ec579.png)

Would love some help on this.

**Comment by alecpl** [comment]
Roundcube is not a POP client.

**Comment by Zorkdaork** [comment]
Hey,

How can I link my roundcube to my gmail then? I keep seeing the same instructions and video's for linking both of them.
Kind regards
Elie
