### ISSUE TITLE
Problem to save responses

### ISSUE THREAD

**Issue by Davidwheeler1231** [roundcube/roundcubemail#8966]
To whom it may concern

I am having issues to save my responses. I always get the error 
"An error occurred while saving"
I am attaching a screenshot

![Screen Shot 2023-04-03 at 11 38 27 AM](https://user-images.githubusercontent.com/129773946/229559090-81a5cad4-be74-45c2-9bc8-9f5c7484ec23.png)

**Comment by ebouchez** [comment]
Hello,
After update to Roundcube Webmail 1.6.1, I have lost all my responses from previous version and get the exact same issue "An error occurred while saving" when trying to save a newly created response.

**Comment by alecpl** [comment]
Did you upgrade from an earlier version? You have to update your database schema.

**Comment by Davidwheeler1231** [comment]
Hello Alec, 
How can I do this?
Thank you
