### ISSUE TITLE
Identities issue when composing email

### ISSUE THREAD

**Issue by aldhyraka** [roundcube/roundcubemail#8970]
Hi,
We have an issue when composing emails through Roundcube. Usually, the identities (email account sender) should be showing by default but as you can check our attachment, the identities are not showing and we cannot add or create identity.

![roundcube1](https://user-images.githubusercontent.com/28332017/229985601-aa53d057-3a3e-4938-8a4c-e47f3246e3eb.jpg)
![roundcube2](https://user-images.githubusercontent.com/28332017/229985623-b4a18ae8-1850-428f-989b-80a873d2c6af.jpg)

As for information, we are using:
cPanel Version 110.0.1
Roundcube Version 1.6.0

Please help me to resolve this, so that when we try to compose an email, the identities will show automatically.

**Comment by alecpl** [comment]
It looks like you're using some external plugins we do not support.

**Comment by aldhyraka** [comment]
Can you explain which plugin you mean exactly?
Because we are using Roundcube from cPanel.
We have 2 servers with the same version of cPanel and Rouncube, but this issue is just what we found on one of the servers.
Both servers are identic with the same plugin and application.
So this is confusing me.

**Comment by NeonHorizon** [comment]
@aldhyraka did you get any luck with this?
Just had one of my CPanel servers get affected with the same issue.
Interestingly I have two servers as well and one is unaffected but that is on 1.5.2

**Comment by NeonHorizon** [comment]
I found the resolution for this issue here:
https://support.cpanel.net/hc/en-us/articles/13692428452759

Basically inside /var/cpanel/roundcube are a number of backups.
Pick one of them and restore like this:
`mysql roundcube < /var/cpanel/roundcube/roundcube.backup.sql.########`

**Comment by aldhyraka** [comment]
Hi @NeonHorizon thanks for your advice, my issue has been solved now with your instruction. it seems some table for Roundcube is missing, so it needs to restore.
