### ISSUE TITLE
Create new identity takes wrong email address

### ISSUE THREAD

**Issue by arekm** [roundcube/roundcubemail#8971]
**Tested on**

roundcube 1.5.3 and 1.6.1

**Problem**

Creating new identity, based on existing one, uses wrong email address in some cases where there are multiple email addresses used in identities.

**How to reproduce**

Scenario:

1) identities_level==0 in config

2) user adds Settings->Identities a identity for aaa@example.com and bbb@otherdomain.com 

3) config is changed to identities_level==1

Note: Also could be similar scenario where identities_level==1 is set all the time but 2) is done by external system directly into roundcube database and not from roundcube UI.

4) user clicks on identity bbb@otherdomain.com, sees "Create" and "Delete" buttons and clicks "Create"

5) identity edit form appears but with wrong "aaa@example.com" domain instead of proper "bbb@otherdomain.com" (and due to identities_level==1 user can't fix it "by hand")

**What should happen?**

"Create" on identity with email X should create new identity with exactly the same email (as this email already exists in system)
and not some "default" email.

**Comment by alecpl** [comment]
With identities_level=1 the email address is taken from the `users` table record. And this address is set when the user record is being created. You have to make sure these addresses are being created properly, e.g. using `mail_domain` setting.
