### ISSUE TITLE
Element not displaying

### ISSUE THREAD

**Issue by DerekWeiChao** [roundcube/roundcubemail#8972]
Local roundcube installation isn't displaying buttons properly in the options and attachments submenu. 

This is what it should look like
![mail2 version](https://user-images.githubusercontent.com/18562568/230225062-6328938f-edcd-4433-b127-b888510450c7.PNG)

This is what I have.
![Screenshot 2023-04-05 12 49 33 PM](https://user-images.githubusercontent.com/18562568/230225095-d110619b-d9a1-417c-bb9a-74efdd5237a3.png)

I looked around with 'inspect element' and noticed that this was missing from compose.html

||label for="enigmasignopt" class="custom-control-label" title=""|| == $0'
   ::before
   ::after
||/label||

(Had to replace the borders for html elements so that they could actually be viewed)

**Comment by alecpl** [comment]
Any javascript errors in browser console? Any other errors?

**Comment by DerekWeiChao** [comment]
None off the top of my head. I followed all the instructions in the installation for the dependent version, but after doing so, I noticed the buttons were still missing. When I went to inspect elements later, I noticed that the label was the discrepancy between the dependent and the complete version. Haven't found other errors just yet.

**Comment by alecpl** [comment]
Yeah, it might be some timing issue, as we use javascript to show some UI elements, especially on phones. We also have this problem when testing in CI, but I was never able to reproduce it on my own.

**Comment by alecpl** [comment]
Oops, I was actually thinking of #8968, but this might be a similar thing.

**Comment by DerekWeiChao** [comment]
![Uploading Screenshot 2023-04-06 10.37.15 AM.png…]()

This is what shows up when I open the compose page.

**Comment by alecpl** [comment]
Well,  you have 404 on some essential files. You did not install dependencies or sth.

**Comment by DerekWeiChao** [comment]
![bin jsdeps install](https://user-images.githubusercontent.com/18562568/230458118-4a02564c-8d32-40d5-86e9-52b38a241a54.png)

I ran bin/install-jsdeps.sh and these are the errors that popped up.

**Comment by alecpl** [comment]
What Roundcube version? What PHP version? What system/distribution is this?

I don't know why these `mv` operations fail. I didn't see this error before. Sometimes it could be because spaces in the path, but this does not look to be the case here.

**Comment by DerekWeiChao** [comment]
PHP version is 7.4.33, Roundcube version is 1.7-git (according to the index.php file).

I'm running this on a ChromeOS device. When I ran it with the complete version of Roundcube, it worked fine. However, the dependent version has been running into these errors.

**Comment by DerekWeiChao** [comment]
Solved the issue on my end. I had to create the deps folder in skins/elastic and then everything ran smoothly from there.
