### ISSUE TITLE
All plaintext parts in multipart messages have an extra leading newline

### ISSUE THREAD

**Issue by dapphp** [roundcube/roundcubemail#8973]
**Tested on**

Roundcube 1.6.1

**Problem**

The plain text part of a multipart message seems to get created with an extra leading newline when there shouldn't be one. The result is that all sent messages begin with an empty line that should not be there when viewing the plain text part.

It appears that the default HTML produced by the WYSIWYG editor results in some unwanted leading whitespace after going through `rcmail::html2text()`.

**How to reproduce**

Compose a new HTML message in the WYSIWYG editor and send it. Then, view the source of the sent and received emails. The plain text part begins with unwanted newlines.

**Example**

    <html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /></head><body style='font-size: 11pt'>
    <p>This is a message from Roundcube.</p>
    
    </body></html>

The resulting plain text when `var_dump`ed is:

    string(36) " 
    
    This is a message from Roundcube."

The whitespace as hex is: `200a0a`.

Here is what part of the MIME message looks like:

```
MIME-Version: 1.0
Date: Wed, 05 Apr 2023 15:09:01 -0700
From: <>
To: <>
Subject: Roundcube test
Message-ID: <c70fb3d6683e41f5eb0ba05b93fe0f8c@domain>
Content-Type: multipart/alternative;
 boundary="=_84355f91a5b51faf3d6161ab41305f3d"

--=_84355f91a5b51faf3d6161ab41305f3d
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed



This is a message from Roundcube.
--=_84355f91a5b51faf3d6161ab41305f3d
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 11pt'>
<p>foo</p>

</body></html>

--=_84355f91a5b51faf3d6161ab41305f3d--
```

**Expected result**

The resulting plain text without the leading newlines. e.g.: `This is a message from Roundcube.`

**Comment by alecpl** [comment]
Fixed.
