### ISSUE TITLE
Dovecot IMAP server login problem

### ISSUE THREAD

**Issue by baWxSteam** [roundcube/roundcubemail#8974]
Hi I'm struggling with a problem because when I've already made an account in mysql database and want to log into it I get this error

IMAP connect:  NOT OK(Login failed for roundcube@domain.com against localhost from <ip ipv6> (X-Forwarded-For: myip). Authentication failed.)

Please help me a lot I will be very grateful

**OS:** Ubuntu 20.04.6 LTS
**Web Server:**  Apache/2.4.56 (Ubuntu)
**PHP Version:** PHP 8.2.4 byt roundcube say _(Version:  OK(PHP 8.0.28 detected)_
**Mail Server:** IDK

**Comment by alecpl** [comment]
"Authentication failed" comes from the IMAP server, so you should be looking there. Also, you can enable imap_debug in Roundcube to see the "conversation" with the server.
