### ISSUE TITLE
ha ocurrido un error al guardar respuesta

### ISSUE THREAD

**Issue by wfmf9315** [roundcube/roundcubemail#8977]
Buenos dias, espero puedan apoyarme con este tema, resuelta que mis usuarios siempre responder correos con respuestas creadas, hace dos dias se borraron todas las respuestas de las cuentas y ya no me deja crear, cada que creo una marca que ha ocurrido un error. 

me podrian apoyar para solucionarlo, saludos, 

![error](https://user-images.githubusercontent.com/130781047/232100686-648f3ecd-dbbc-4393-be4b-dbe4abc955f7.PNG)

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
