### ISSUE TITLE
Auto-refresh doesn't work for custom created directories

### ISSUE THREAD

**Issue by clesssalvein** [roundcube/roundcubemail#8978]
**Roundcube Webmail 1.6.1
Managesieve 9.4**

Creating a custom directory:

![изображение](https://user-images.githubusercontent.com/9415718/232147936-a6829b6c-c7e6-4dba-8bed-e683651eccbf.png)

Creating a managesieve filter for "Move message to folder":

![изображение](https://user-images.githubusercontent.com/9415718/232149050-842de407-4c5e-409a-9f6f-c40de96f9309.png)

Auto-refresh ON:

![изображение](https://user-images.githubusercontent.com/9415718/232149390-05015a7d-1a63-4211-9e91-b7b98c0adcc3.png)

Send 2 emails (usual email and the email to move it to the custom created folder).

Thunderbird recieves and shows recieved emails (notifications) automatically (I don't have to refresh it manually):

![изображение](https://user-images.githubusercontent.com/9415718/232150567-1e9e1179-1f82-4696-b133-14d9e0f07647.png)

Roundcube doesn't show a notification in the custom folder (only in the standard Inbox folder)...

![изображение](https://user-images.githubusercontent.com/9415718/232151023-edf84388-d929-4ecb-b355-f0967d3705ed.png)

...until I refresh it manually!

![изображение](https://user-images.githubusercontent.com/9415718/232151652-46da5b08-1558-4c8b-beaa-03f92babc42b.png)

I was waiting for a few auto-refreshes, but it definitely doesn't refresh automatically.
So, auto-refresh doesn't work for custom created directories. Or is it some other problem?
I will be grateful if you help me solve this problem.

**Comment by alecpl** [comment]
Do you have this setting enabled? Preferences > Mailbox View > New Message > Check all folders for new messages

**Comment by clesssalvein** [comment]
Oh, it works, thank you very much!
Is there a parameter for "webmail/config/config.inc.php" in order to enable "Check all folders for new messages" for all users by default?

**Comment by clesssalvein** [comment]
I've already found it: $config['check_all_folders'] = true;
Thank you!
