### ISSUE TITLE
Upgrade Schema - Fatal error

### ISSUE THREAD

**Issue by icuthere** [roundcube/roundcubemail#8984]
Hello,

I'm running cPanel.

My first clue that I had a problem was that the responses table is not there.  

In order to get the updatedb.sh script to run, I upgraded to php 7.4.

Now I get this:

[root@server roundcube]# ./bin/updatedb.sh --package=roundcube --version=0.9.0 --dir=SQL
Fatal error: Please check the Roundcube error log and/or server error logs for more information.

/root/logs/roundcube/errors.log :

[19-Apr-2023 07:51:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function raise_error() in /usr/local/cpanel/base/3rdparty/roundcube/plugins/cpanellogin/cpanellogin.php:6
Stack trace:
#0 /usr/local/cpanel/base/3rdparty/roundcube/program/lib/Roundcube/rcube_plugin_api.php(204): include()
#1 /usr/local/cpanel/base/3rdparty/roundcube/program/lib/Roundcube/rcube_plugin_api.php(126): rcube_plugin_api->load_plugin('cpanellogin')
#2 /usr/local/cpanel/base/3rdparty/roundcube/program/include/rcmail.php(108): rcube_plugin_api->load_plugins(Array, Array)
#3 /usr/local/cpanel/base/3rdparty/roundcube/program/include/rcmail.php(86): rcmail->startup()
#4 /usr/local/cpanel/base/3rdparty/roundcube/program/include/clisetup.php(30): rcmail::get_instance()
#5 /usr/local/cpanel/base/3rdparty/roundcube/bin/updatedb.sh(23): require_once('/usr/local/cpan...')
#6 {main}
  thrown in /usr/local/cpanel/base/3rdparty/roundcube/plugins/cpanellogin/cpanellogin.php on line 6

Later i tried to use the web page install/index.php which go the db version error but the update button there fails (tried all versions).  That page somehow reports that I have php version 8 but I am sure that I have enabled 7.4.

Any help is appreciated.

**Comment by alecpl** [comment]
Normally when upgrading you have to update your plugins too. Here cpanellogin plugin is not compatible with this Roundcube version.

**Comment by alecpl** [comment]
You can disable all plugins, then execute the upgrade, then upgrade plugins, then re-enable them.

**Comment by icuthere** [comment]
Your help is appreciated. 

I have disabled all plugins and ran the updatedb.sh script again.  

I get the following error:

[root@server roundcube]# ./bin/updatedb.sh --package=roundcube --dir=SQL
ERROR: SQLSTATE[HY000] [14] unable to open database file
ERROR: Failed to connect to database

/root/logs/roundcube/errors.log :

[20-Apr-2023 20:21:36 UTC] PHP Warning:  touch(): Unable to create file /root/etc/.rcube.db because No such file or directory in /usr/local/cpanel/base/3rdparty/roundcube/program/lib/Roundcube/db/sqlite.php on line 39

I know the sql lite db is there because i went in and did some basic test queries.
