### ISSUE TITLE
Issue with style `xss_entity_decode` function

### ISSUE THREAD

**Issue by remdex** [roundcube/roundcubemail#8985]
Hi,

I have part of e-mail body that consists of this style.
```
<tr>
  <td class="gmail-xl80" style=font-family:&quot;\0022calibri Light\000022&quot;">paulmedc</td>
 </tr>
 ```
 
After roundcube renders HTML we get invalid characters in rendered style. Which forbids rendering output with `json_encode` and throws `Malformed UTF-8 characters, possibly incorrectly encoded in`
 
 Fix is to modify `rcube_utils::xss_entity_decode` to 
 
 Reference
 https://www.php.net/manual/en/function.mb-detect-encoding.php#50087
 
 We check that converted character is in UTF-8
 
 ```php
 public static function xss_entity_decode($content)
    {
        $callback = function($matches) {
            $string = chr(hexdec($matches[1]));
            return preg_match('%^(?:
                  [\x09\x0A\x0D\x20-\x7E]            # ASCII
                | [\xC2-\xDF][\x80-\xBF]             # non-overlong 2-byte
                |  \xE0[\xA0-\xBF][\x80-\xBF]        # excluding overlongs
                | [\xE1-\xEC\xEE\xEF][\x80-\xBF]{2}  # straight 3-byte
                |  \xED[\x80-\x9F][\x80-\xBF]        # excluding surrogates
                |  \xF0[\x90-\xBF][\x80-\xBF]{2}     # planes 1-3
                | [\xF1-\xF3][\x80-\xBF]{3}          # planes 4-15
                |  \xF4[\x80-\x8F][\x80-\xBF]{2}     # plane 16
            )*$%xs', $string) ? $string : '';
        };

        $out = html_entity_decode(html_entity_decode($content));
        $out = trim(preg_replace('/(^<!--|-->$)/', '', trim($out)));
        $out = preg_replace_callback('/\\\([0-9a-f]{2,6})\s*/i', $callback, $out);
        $out = preg_replace('/\\\([^0-9a-f])/i', '\\1', $out);
        $out = preg_replace('#/\*.*\*/#Ums', '', $out);
        $out = strip_tags($out);

        return $out;
    }
 ```

**Comment by alecpl** [comment]
Could you provide a whole email message?

**Comment by remdex** [comment]
I can't because of data sensitivity. This part I pasted is just HTML snippet. Which courses a problem.

It was in HTML Body message part. You can reproduce the problem easily by calling.

```
rcube_utils::xss_entity_decode('<tr>
  <td class="gmail-xl80" style=font-family:&quot;\0022calibri Light\000022&quot;">paulmedc</td>
 </tr>');
 ```
 
 You will see that output consists of invalid string character...

**Comment by alecpl** [comment]
I see there's a problem with this function, but I don't see any `Malformed UTF-8 characters, possibly incorrectly encoded...` errors. We're using `JSON_INVALID_UTF8_IGNORE` in `rcube_output::json_serialize()`. So is this the core problem or it's your custom code?

**Comment by remdex** [comment]
Hi, yes I used it in my custom function. Did not knew yours was using that flag. In that case perhaps can be closed...

**Comment by alecpl** [comment]
Yeah. `xss_entity_decode()` is probably not the place to clean up the malformed characters. It's a utility function that might be used with non-UTF8 input. I'm closing the ticket.
