### ISSUE TITLE
Event notification missing time

### ISSUE THREAD

**Issue by loopguard404** [roundcube/roundcubemail#8986]
When you create an event in the calendar, a message is sent with an invitation to the event. But this prompt is missing the time of the scheduled event.

In Thunderbird, the time of the scheduled event is displayed.

![image](https://user-images.githubusercontent.com/46474603/233586999-abbe2958-9806-4681-941c-5d4a47da5aae.png)

Roundcube Webmail 1.5.3
PHP 8.0.28

**Comment by alecpl** [comment]
We do not support Calendar plugin here. Go to https://git.kolab.org

**Comment by loopguard404** [comment]
The problem is not in the calendar, but in the web client.

Because on other email clients, the time is displayed

**Comment by alecpl** [comment]
No, it is not.
