### ISSUE TITLE
Just half of the screen available for writing when composing emails.  

### ISSUE THREAD

**Issue by soneghet** [roundcube/roundcubemail#8991]
![Desktop](https://user-images.githubusercontent.com/36213731/234367557-86f8d0fe-f9f5-4604-8425-3cba6f749e70.png)
![Mobile](https://user-images.githubusercontent.com/36213731/234367563-66b818bd-aaf0-4406-8e8d-9875e12fdc1e.jpg)

For some reason, I can access just the left part of the screen when I compose emails. 

Any suggestions would be very welcome. 

Thanks.

**Comment by alecpl** [comment]
What version? Try with all plugins disabled. cPanel uses plugins we do not support.
