### ISSUE TITLE
Impossible to send text with trailing spaces

### ISSUE THREAD

**Issue by Sertonix** [roundcube/roundcubemail#8993]
I would like to be able to send a plain text mail where the content is exactly what I typed (or pasted). This does include trailing spaces at the end of a line.
This may seem 100% useless but it is important when sending git patches via e-mail. The format is invalid if trailing spaces are ignored.

The lines seem to be stripped every time the email is saved or send.

A simple solution would be to just stop trimming the lines. If you want to keep that functionality by default you could also add an option.

I have encountered in the posteo web client.

**Comment by alecpl** [comment]
There is "Keep formatting" option in mail composer since Roundcube 1.6.0.
