### ISSUE TITLE
Hide information about quota, when there is no quota

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#8994]
I have no limit of my mailbox.  Roundcube displays at the bottom of the mailbox an indication, that I have used 0% of my quota.

Even when I set `$config['quota_zero_as_unlimited'] = true;` the information is still there, with a tooltip “Without limitations”

When there is no quota, Roundcube shall not tell the user that he uses 0% of it, as this information unnecessary consumes space.

**Comment by alecpl** [comment]
Confirmed. I suppose hiding the whole element for the 'unlimited' case might make sense.

**Comment by pabzm** [comment]
I'd take a shot at this – unless someone else is already working on it?

**Comment by alecpl** [comment]
Done.
