### ISSUE TITLE
Roundcube update dependencies (jQuery & UI 2016) in Plesk

### ISSUE THREAD

**Issue by aziizfarhat** [roundcube/roundcubemail#8997]
Hello,
I'm using plesk-roundcube 1.4.13-2.centos.7+p18.0.51.1+t230404.1037 (PLESK_18_0_51-dist) on Plesk Obsidian Web Pro Edition Version 18.0.51.
After a pentest, security manager said that I must update some javascript dependencies including jQuery - v3.4.1 and jQuery UI - v1.12.0 (wich is a little bit old : 2016-08-01) on my webmail.mywebsite.com
Roundcube is automatically installed on plesk and up to date on plesk extentions page, how can I resolve this dependencies problem ?

Plesk version	Plesk Obsidian Web Pro Edition Version 18.0.51

Thanks

**Comment by alecpl** [comment]
1.4 is old and not supported.
