### ISSUE TITLE
PHP 8.2 dynamic properties deprecation impact on Roundcube

### ISSUE THREAD

**Issue by nsoggia** [roundcube/roundcubemail#8998]
Hello,
while I was trying to propose a fix to [thunderbird labels](https://github.com/mike-kfed/roundcube-thunderbird_labels/pull/76) I also realized that the issue couldn't be fixed because @mike-kfed played a clever trick abusing the rcube_message_header class: [here](https://github.com/mike-kfed/roundcube-thunderbird_labels/blob/f2088fdb680e76be222faef2b8c627b606b2e728/thunderbird_labels.php#L313) he creates a dynamic property to be able to show some coloured labels in the message list, flooding my error.log with deprecation warnings.

I could ask you to add a `public $list_flags;` in rcube_message_header class and call it a day, but I would like to discuss a generalized solution that could work for all plug-ins.
My idea is to add a `public $plugin_data = array();` to every class that can be referenced by plugins: a dream and a nightmare at the same time.
I envisioned an array whose keys are the plugin name and the data, well, opaque.
Something like this: `$object->plugin_data['thunderbird_labels']['my_opaque'] = true;`

**Comment by mike-kfed** [comment]
assuming other plugins might use that PHP feature too, another fix is this attribute

```php
// ...
#[AllowDynamicProperties]
class rcube_message_header
{
// ...
```

that should make it fine for PHP 9.0 too.

side note: the warnings only show up when `program/lib/Roundcube/bootstrap.php`  has `error_reporting` changed to `E_ALL`

**Comment by mike-kfed** [comment]
Looking more into this, adding `public $list_flags;` is the correct fix together with `public $list_cols;` as this wiki description says <https://github.com/roundcube/roundcubemail/wiki/Plugin-Hooks#messages_list>  it's actually not a hack by me, the message header list_flags `$message->list_flags['extra_flags']` is supposed to exist for plugins to use.

**Comment by nsoggia** [comment]
> You can use it to set message headers, list_cols/list_flags and other rcube_mail_header variables

I just took a look at rcube_message_headers.php and it never had any list_cols or list_flags.
I looked around and I found those two methods in other classes (imap and db).

I'm guessing...
Probably the documentation meant: "you can modify the object as you like, or use it to obtain the message-id required by db->list_cols() or imap->list_flags()".

**Comment by mike-kfed** [comment]
in fact the `list_flags` are merged into the `flags` property and later available in javascript where the `extra_flags` array-sub-key / JS-object-property are accessible (the actual reason I use this) see `program/js/app.js` on line 2227

the merge happens in `program/actions/mail/index.php` line 593

so yes they "don't exist" as of now in rcube_message_header, but that is an oversight as the plugin docs show, and the code treating those properties confirms, hence my PR ^^ that adds those missing properties.

**Comment by nsoggia** [comment]
I see it now as well.
Undoubtedly $list_flags and $list_cols had to be there since the beginning.

**Comment by alecpl** [comment]
Fixed.
