### ISSUE TITLE
Forwarding email threads always forwards them as attachments

### ISSUE THREAD

**Issue by n-goncalves** [roundcube/roundcubemail#9007]
Hi, 

I am using roundcube 1.6.1 with PHP 8.0.22. 

My webmail is configured to show messages in threads. As written in the title, when I try to forward an email thread, the composed mail always treats each mail of the thread as attachments even if the default config is set to put them inline. I've also tried to change the user preference but to no avail. 

I hope my explanation is clear and looking forward for your input.

Thanks.

**Comment by alecpl** [comment]
That's right. Putting multiple messages content into one reply message body is not trivial and error prone. I don't think we'll change that. Is there an email client that does that?

**Comment by n-goncalves** [comment]
Gmail and Outlook both do it from what I can test. However Outlook loses any attachments in the thread. 

So it's by choice. While it might not be what some email client do, I can understand your reason. Feel free to close this then, thanks for the explanation.
