### ISSUE TITLE
phpunitest not passed

### ISSUE THREAD

**Issue by giovannidotpoli** [roundcube/roundcubemail#9010]
Hello everyone,
I run the test and I get 18 failed test, there is anyone who have the same issue ?

Regards

**Comment by giovannidotpoli** [comment]
for example i got this
`2) Framework_Csv2vcard::test_import_tb_plain
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 FN:Displayname\n
 N:Lastname;Firstname;;;\n
 NICKNAME:Nick\n
-EMAIL;TYPE=other:test@domain.tld\n
-EMAIL:next@domain.tld\n
+EMAIL;TYPE=INTERNET;TYPE=PREF:test@domain.tld\n
+EMAIL;TYPE=INTERNET;TYPE=OTHER:next@domain.tld\n
 TEL;TYPE=work:phone work\n
 TEL;TYPE=home:phone home\n
 TEL;TYPE=fax:fax\n
@@ @@
 X-DEPARTMENT:department\n
 ORG:Organization\n
 URL;TYPE=homepage:http://page.com\n
-URL:http://webpage.tld\n
+URL;TYPE=other:http://webpage.tld\n
 BDAY;VALUE=date:1970-11-15\n
 ADR;TYPE=home:;;Priv address;City;region;xx-xxx;USA\n
 ADR;TYPE=work:;;Addr work;Wcity;Wstate;33-333;Poland\n
 END:VCARD'

/var/www/html/tests/Framework/Csv2vcard.php:44`

**Comment by alecpl** [comment]
https://github.com/roundcube/roundcubemail/actions/workflows/tests.yml proves that tests are passing.

**Comment by giovannidotpoli** [comment]
Thanks
