### ISSUE TITLE
Cyrillic=???? mssql 

### ISSUE THREAD

**Issue by Skull09rus** [roundcube/roundcubemail#9012]
Hello everyone, there was a problem with russian when writing to the MSSQL database. Tell me please how to solve this problem.
Roundcube 1.6.1
MSSQL 2022
PHP 8.2
IIS
![IMAGE 2023-05-14 13:07:56](https://github.com/roundcube/roundcubemail/assets/37028615/ce07d466-3255-4d3b-95ec-7f7fd54a1b77)
![IMAGE 2023-05-14 13:07:58](https://github.com/roundcube/roundcubemail/assets/37028615/afb81983-4e06-471b-b32a-80ec3e97d962)

**Comment by alecpl** [comment]
We removed support for MS SQL Server in 1.7-git. I wouldn't expect any help from us regarding this engine. Ask on mailing list or forum.
