### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by zoclhas** [roundcube/roundcubemail#9017]
Hello,
I just made a roundcube instance (with nginx) on my VPS. Everything is loaded fine, but I can't seem to login into it. Getting a login failed at the URL and ` IMAP Error: Login failed for demo@mail.zaura.net against localhost from xx.xx.xx.xx AUTHENTICATE PLAIN: Authentication failed. in /var/www/roundcube/program/lib/Roundcube/rcube_imap.php on line 211 (POST /?_task=login&_action=login)`. 

I'm using dovecot for imap and I try logging in with localhost. And auto_create_user is enabled

**Comment by alecpl** [comment]
"Authentication failed" comes from the IMAP server, so you should be looking there. You can enable imap_debug in Roundcube to see more on what's going on, but maybe IMAP server logs already have a clue.

**Comment by turboMaCk** [comment]
We've also run into this issue after upgrade from 1.6.3 to 1.6.4. First few login attempts failed with this. Then it started working on its own without any action taken. The imap server was still working though (thunderbird connected to the IMAP server did not encounter any issues).

Also with `auto_create_user` enabled. In this case it happened on accounts that existed and worked correctly prior the so they should have existed in roundcube DB already.

This makes me think that there might in the end be some issue in roundcube. Let me know if you want me to create new issue or provide some addition information.
