### ISSUE TITLE
Undelivered mail return to sender

### ISSUE THREAD

**Issue by BabitaS04** [roundcube/roundcubemail#9021]
I have started using Webmail few days back but whenever i tried to send emails it return back to me with some error message from MAILER-DAEMON. i am adding screenshot for better understanding.
![processed-7cbc4415-c5a7-46ad-bb4d-71dd4c39dfd1_I8ScWh8w](https://github.com/roundcube/roundcubemail/assets/134672477/48094b29-f726-417e-bc58-cee8ceefbbf7)

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
