### ISSUE TITLE
URGENTE

### ISSUE THREAD

**Issue by Amabilesrl** [roundcube/roundcubemail#9023]
Buongiorno, 
questa mattina facendo l'accesso alla mail che utilizzo giornalmente per il mio lavoro non mi compaiono più le mail che avevo salvato nella cartella "RISPOSTE".

Vorrei se fosse possibile ripristinarle.

Ho provato anche a scriverle nuovamente ma non mi permette più di salvarle.

C'è una soluzione a questo problema?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
