### ISSUE TITLE
email

### ISSUE THREAD

**Issue by Amabilesrl** [roundcube/roundcubemail#9024]
this morning by logging into the
emails that I use every day for my work, the emails I had saved in the "REPLY" folder no longer appear.

I wish it were possible to restore them.

I also tried to write them again but it won't let me save them anymore.

Is there a solution to this problem?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

**Comment by Amabilesrl** [comment]
Sorry, I didn't know this. Thank you
