### ISSUE TITLE
Command `./bin/updatedb.sh --dir=./SQL --package roundcube` doesn't update `roundcube-version` in `system` table

### ISSUE THREAD

**Issue by iredmail** [roundcube/roundcubemail#9026]
Dear developers,

I'm trying to upgrade Roundcube on one server from 1.5.3 to 1.6.1 without interactive, one of the step is:

```
./bin/updatedb.sh --dir=./SQL --package roundcube
```

Turns out it doesn't update `roundcube-version` in SQL table "system". Is it a bug of `./bin/updatedb.sh`?

There's a command at the end of file `SQL/mysql.initial.sql` like below:
```
INSERT INTO `system` (`name`, `value`) VALUES ('roundcube-version', '2022081200');
```

Should we add similar commands (with different version numbers) in each `SQL/mysql/*.sql`?

**Comment by alecpl** [comment]
No. The table is supposed to be updated automatically via `rcmail_utils:::db_update_schema()`.

**Comment by iredmail** [comment]
ok, thanks @alecpl
