### ISSUE TITLE
Filter: Forwarding not working if more than 4 recipients

### ISSUE THREAD

**Issue by HanSolo72** [roundcube/roundcubemail#9030]
I have the following filter rule:

```
# rule:[My rule]
if allof (header :contains "to" "mail@mydomain.de", header :contains "subject" "my subject")
{
	redirect "mail@domain1.de";
	redirect "mail@domain2.de";
	redirect "mail@domain3.de";
	redirect "mail@domain4.de";
	redirect "mail@domain5.de";
	redirect "mail@domain6.de";
}
```

In the errors.log from /var/log/roundcubemail appears the following line, but I don't know if it has to do with my error:
[11-Jun-2023 15:31:20 +0200]: <tnd40rfs> PHP Error: roundcube: line 20: error: the false test accepts no sub-tests, but tests are specified. roundcube: error: validation failed. (POST /mail/?_task=settings&_action=plugin.managesieve-saveraw)

My version of Roundcube is 1.6.1 as part of Mailinabox.

**Comment by alecpl** [comment]
Look for sieve_max_redirects in dovecot's sieve configuration.
