### ISSUE TITLE
Send Email -> SMTP Failed

### ISSUE THREAD

**Issue by electro575** [roundcube/roundcubemail#9032]
Hi all,

I have upgraded my debian from Bullseye to Bookworm.

Php7.4 have been upgrade to php8.2.

I can login into my account on roundcube, read email, delete and treat.

I can't send an email because of "SMTP Failed".

Logs are following.

```
tail -f /var/lib/roundcube/logs/errors.log

PHP Deprecated:  Creation of dynamic property PEAR_Error::$callback is deprecated in /usr/share/php/PEAR.php on line 905
<qinul9ks> PHP Error: STARTTLS failed (POST /?_task=mail&_unlock=loading1686849060629&_framed=1&_action=send)

PHP Deprecated:  Creation of dynamic property PEAR_Error::$callback is deprecated in /usr/share/php/PEAR.php on line 905

<qinul9ks> PHP Error: Invalid response code received from server (POST /?_task=mail&_unlock=loading1686849060629&_framed=1&_action=send)

<qinul9ks> SMTP Error: STARTTLS failed: 2.0.0 Ready to start TLS (Code: 220) in /usr/share/roundcube/program/lib/Roundcube/rcube.php on line 1787 (POST /?_task=mail&_unlock=loading1686849060629&_framed=1&_action=send)
```

What can be a solution ?

Thank you a lot

**Comment by DrTron** [comment]
Same issue here, haven't found a reason yet, either.

**Comment by Receptionist-lifeforce** [comment]
Not getting an error message but same, cannot send emails. Just realized it started last week as well.

**Comment by DrTron** [comment]
Somehow, it autohealed for me, didn't change anything, neither in Roundcube nor in postfix. 
Very strange.

**Comment by electro575** [comment]
@Receptionist-lifeforce : it's again in the same state for you ? Me Too
@DrTron : nothing can change without changing ! What do you suppose changed ?

**Comment by DrTron** [comment]
@electro575 , I agree, that's irritating.
Sure, I did restart postfix, but that also happened after the upgrade when I rebooted the system.

**Comment by Receptionist-lifeforce** [comment]
How do you reboot the system. I've looked all through the settings and I cant find anything. And its been almost 2 weeks and we still can't send emails.. Very irritating
