### ISSUE TITLE
Request (again): Can we have an option to download all attachements at once (zip?)

### ISSUE THREAD

**Issue by freeeflyer** [roundcube/roundcubemail#9034]
Hi
Long ago we had the zipdownload plugin which is no longer available.
So the reason why the #617 was closed is no longer valid
The need for downloading all attachments at once is still there, can you include it natively ?
Thanks.
Nicolas

**Comment by alecpl** [comment]
The zipdownload plugin is a core plugin, and should be always available. So, I don't know what are you talking about.

**Comment by freeeflyer** [comment]
Ok I obviously missed it.. I searched on the plugin database..  
Sorry for bothering you.
