### ISSUE TITLE
Download folder for skins other than Elastic

### ISSUE THREAD

**Issue by rakotak** [roundcube/roundcubemail#9035]
I have enabled and configured (namely `mv zipdownload/config.inc.php.dist zipdownload/config.inc.php` - no other options at a glance) zipdownload and now multiple mails can be selected and downloaded as zip. However on Elastic there is no gear icon anywhere (as depicted in the 1.1 documentation here >> https://docs.roundcube.net/doc/help/1.1/en_US/mail/importexport.html - gear icons only available on Larry skin)

Do I have to do something special other than enabling the plugin to have it download whole folders?

Thanks.

**Comment by alecpl** [comment]
More > Download.
