### ISSUE TITLE
Roundcube sending literal '%u@%s' to mail server for mail submission

### ISSUE THREAD

**Issue by jameslbrown** [roundcube/roundcubemail#9039]
I have for SMTP settings:

$config['smtp_host'] = ‘ssl://my.mail.server.com:465';

// SMTP username (if required) if you use %u as the username Roundcube
// will use the current username for login
$config['smtp_user'] = '%u@%s';

// SMTP password (if required) if you use %p as the password Roundcube
// will use the current user's password for login
$config['smtp_pass'] = '%p';

// SMTP AUTH type (DIGEST-MD5, CRAM-MD5, LOGIN, PLAIN or empty to use
// best server supported one)
$config['smtp_auth_type'] = null;

My SMTP proxy logs:

info: authentication - login is used
warning: SMTP authentication failed from 127.0.0.1 on 127.0.0.1 - user: %u@%s
disconnected: session:388DB8258 127.0.0.1 - processing time 3 seconds

Ie it is not substituting the username and server name for %u and %s.

What am I doing wrong?

Version 1.6.1

Thanks,

James.

**Comment by alecpl** [comment]
This is not supported.
