### ISSUE TITLE
Location of attachment files : Related with capacity of server

### ISSUE THREAD

**Issue by sth00619** [roundcube/roundcubemail#9042]
My Roundcube version : 1.6.0
My Server Info : MySQL 5.7 + CentOS 7

**Questions : Mainly about dealing with capacity problems**
First, I wonder what happens if **Roundcube web mail exceeds the capacity** of the server.
If the number of users and the amount of emails they create exceeds the capacity of server, 
I was wondering if the system automatically delete the emails in the old order or if the system warn users to erase emails themselves.

Second, I want to know **where the attached file(attachments) is stored.**
For other informations, such as address or email address, it is stored in the 'collected_addresses' table or 'contacts' table.
Also, in the case email, the direct information cannot be checked in the database, but we can check the information of email.
We can check the information of the received email through file located in /home/vmail/domain/emailId/maildir/cur.
(For example, we can see the information of test01@test.com in /home/vmail/test.com/test01/maildir/cur)
We can see the information of the sent email through file located in /home/vmail/domain/emailId/Maildir/.Sent/cur.
Of course, the attachment appears in encrypted form in this folder, but what I want is whether administrator can delete the 
attachment manually.
Regarding the capacitym if the capacity limit of the mail server is close or exceeded, I want to secire the capacity by deleting old mail or removing the attachments, but as far as I know, I don't know how to manipulate attachments directly.

Third , I found that mail attachments settings exist at the end of the file in /etc/dovecot/conf.d/10-mail.conf.
Can I save the attched file by dividing it by domain and emailId just like the email by setting this part?
My current settings of 10-mail.conf file are as follows
![image](https://github.com/roundcube/roundcubemail/assets/97080735/e9771b0b-7359-4603-b62e-1e3c2ff66871)

**Comment by alecpl** [comment]
Roundcube is just an imap client. It needs some storage for database, but other than that it does not use much of the disk space. Mostly for temp files.

Dovecot is not part of Roundcube.

**Comment by sth00619** [comment]
Thank you for confirming it.
While I was searching for more information, I was able to find the answer to the question.

In general, Roundcube does not directly access the mail storage on the mail server.
Roundcube communicate with the mail server through the IMAP protocol to read and write mail.
Roundcube does not have a directory that stores "mail" on its own.
