### ISSUE TITLE
UPGRADING file is incomplete

### ISSUE THREAD

**Issue by HolgerAusB** [roundcube/roundcubemail#9045]
It took me some time to discover that I can't just run the installto.sh script to upgrade my installation, but that I have to download and unpack the new tar archive myself first. This should really be written in the UPGRADING file. I only found this in the wiki.

**Comment by alecpl** [comment]
Isn't that clear?:
```
There is a shell script (for unix based systems) that does the job for you.
To use it, unpack the archive of the new Roundcube version to a temporary location
(don't replace the Roundcube installation you want to update)
and cd into that directory. From there, run the following command in a shell:

  ./bin/installto.sh <TARGET-FOLDER>
```

**Comment by HolgerAusB** [comment]
Although I read the text several times, I must have missed that. Sorry about that.
