### ISSUE TITLE
Updating to 1.6.1 to 1.6.2 broke SMTP

### ISSUE THREAD

**Issue by DavidAnderson684** [roundcube/roundcubemail#9051]
Very similar issue to the one that occurred when upgrading from 1.6.0 to 1.6.1: https://github.com/roundcube/roundcubemail/issues/8889 .

This time after upgrading, Roundcube edited my `config.inc.php` so that it had no entry for `$config['smtp_host']` in it at all.

So, I restored the previous `config.inc.php` that was working on 1.6.1... this no longer worked. i.e. `ssl://mail.example.com:465` did not work... but this time, `tls://mail.example.com` (i.e. the one that stopped working on 1.6.1) now did work again.

**Comment by alecpl** [comment]
Could you provide your old config.inc.php file? Smtp options only.

**Comment by DavidAnderson684** [comment]
```
$config['smtp_host'] = 'ssl://mail.example.com:465';
$config['smtp_log'] = true;
$config['smtp_auth_type'] = '';
```

**Comment by alecpl** [comment]
Confirmed and fixed.
