### ISSUE TITLE
Can't send emails to gmail accounts

### ISSUE THREAD

**Issue by svzeeburg** [roundcube/roundcubemail#9053]
Every single email that I send to a gmail account fails. The error that occurs:

_Mail delivery failed: returning message to sender 

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error._

How can we fix this?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
