### ISSUE TITLE
PHP Error With No Visible Negative Effects

### ISSUE THREAD

**Issue by jbodycott** [roundcube/roundcubemail#9064]
Good evening,

Ubuntu 23.04 (current updates), rc-1.6.2, php 8.1.12, nginx 1.22.0

Thanks for all your efforts in chasing PHP errors.  I haven't scoured my logs to see when this one began, but I'm now seeing the following line (with various addresses in place of /mail and occasionally a POST instead of a GET).

roundcube: PHP Error: Failed to load plugin file /opt/www/roundcubemail/plugins/password/password.php in /opt/www/roundcubemail-1.6.2/program/lib/Roundcube/rcube_plugin_api.php on line 193 (GET /mail/)

I am not seeing any degradation in functionality at this time (all password functions appear to operate correctly), but the logs are quite noisy.  Let me know if you need any additional information.  Once more, thanks for your time and help!

**Comment by alecpl** [comment]
That error message indicates that the specified file is not readable by Roundcube (PHP). So, if there's an issue it's not Roundcube issue.

**Comment by jbodycott** [comment]
You were right, Aleksander.  www-data group permissions had been dropped from the 'password' folder.  Corrected them and all is happy and healthy.  Many thanks!
