### ISSUE TITLE
Wrong order of a multi-folder search result when sorted by size

### ISSUE THREAD

**Issue by woutput** [roundcube/roundcubemail#9065]
Hi all,
When I sort by size, Roundcube nicely and quickly sorts all my emails by size, but when I first sort by type "with attachment" and in "all folders" or in "this and subfolders", then the sorting by size doesn't work well. It looks like it is alphabetically sorting by the textual representation of the size instead of sorting by the actual size.
Expected behavior: sort by size always works, independent of search criteria: ![All sorted - correct](https://github.com/roundcube/roundcubemail/assets/14995512/d293e851-611d-4132-b3c1-f5a1945ef3f3)
Observed behavior: sort by size sometimes works, depending on search criteria: ![With attachments sorted - incorrect](https://github.com/roundcube/roundcubemail/assets/14995512/9726a9ff-3678-4b7c-a916-004f749efddf)

In my opinion this is a minor/low priority bug.

Thank you for this great software; it is my primary email interface that I've been using for many years!
woutput

**Comment by alecpl** [comment]
Fixed.

**Comment by woutput** [comment]
Wow, that was quick! Thanks @alecpl
