### ISSUE TITLE
mixed timestamp format in log

### ISSUE THREAD

**Issue by Blotosmetek** [roundcube/roundcubemail#9067]
Some of the entries in roundcube log have timezone same as the value of date.timezone in php.ini file:

`[13-Jul-2023 13:43:51 Europe/Warsaw] PHP Warning:  Undefined array key "" in /usr/share/roundcube/program/include/rcmail.php on line 971`

and some as numeric offset, like this:
`
[13-Jul-2023 13:38:09 +0200]: <srqtnp0a> PHP Error: Invalid response code received from server (POST /?_task=mail&_unlock=loading1689248289141&_framed=1&_action=send)`

I would think the format should be consistent across the whole log. Or is it a configuration problem at my site? 

RoundCube version 1.6.1, installed from Debian 12 package. PHP 8.2, same.

**Comment by alecpl** [comment]
The first message comes from the PHP itself and uses date format specified in the runtime environment (FPM, apache, etc.), and the other one comes from Roundcube using the format specified in `$config['log_date_format']`.

As far as I know there's no way to automatically make it use the same format, but you can make it the same with configuration.
