### ISSUE TITLE
kolab_2fa plugin doesn't check username_domain

### ISSUE THREAD

**Issue by andevz** [roundcube/roundcubemail#9069]
Hello, not exactly a roundcube issue, but your feedback would be appreciated. 

RC 1.6.2
php 7.3.5,
kolab_2fa plugin 3.5.11

Although a kolab_2fa plugin works perfecty with RC, it doesn't check `$config['username_domain']` or `$config['username_domain_forced']` params.
I undestand, it probably hasn't been designed to be used in RC  in the first place.

However a simple fix seems to work, unless it breaks something I overlooked. 
```
--- ./kolab_2fa.php.dist        2023-07-15 10:23:29.000000000 +0100
+++ ./kolab_2fa.php.suggested   2023-07-15 21:52:40.000000000 +0100
@@ -90,6 +90,14 @@
         $hostname = $_SESSION['hostname'] = $a_host['host'] ?: $args['host'];
         $username = !empty($_SESSION['kolab_auth_admin']) ? $_SESSION['kolab_auth_admin'] : $args['user'];

+       // process username_domain config settings
+       list($local, $domain) = explode('@', $username);
+       $username_domain = trim($rcmail->config->get('username_domain'), ' @');
+       $username_domain_forced = $rcmail->config->get('username_domain_forced');
+       if ($username_domain_forced || empty($domain)) $domain = $username_domain;
+       $username = $local . '@' . $domain;
+       $username = rtrim ($username,'@');
+
         // Convert username to lowercase. Copied from rcmail::login()
         $login_lc = $rcmail->config->get('login_lc', 2);
         if ($login_lc) {
@@ -128,7 +136,7 @@
             $_SESSION['kolab_2fa_nonce']   = bin2hex(openssl_random_pseudo_bytes(32));
             $_SESSION['kolab_2fa_factors'] = $factors;

-            $_SESSION['username'] = $args['user'];
+            $_SESSION['username'] = $username;
             $_SESSION['host']     = $args['host'];
             $_SESSION['password'] = $rcmail->encrypt($args['pass']);
```

An original kolab_2fa.php works well only when username is a full email address. Otherwsie, a factor lookup in user prefs is done by a username input only, which fails. Hence, even if a user has 2FA aleady set, those factor(s) wouldn't be used/checked at login.

I would appreciate your thoughts.
Thanks a lot.

**Comment by alecpl** [comment]
Done in https://git.kolab.org/rRPKfb9b3a7cffc8fb8c88e30f0a832fa8f426ab8f8e and https://git.kolab.org/rRPKa3d7737d834fbb4647a09e972dc91b72357acc4f
