### ISSUE TITLE
PHP warning about undefined array key "_from"

### ISSUE THREAD

**Issue by hannob** [roundcube/roundcubemail#9071]
I get warnings like this in my php error log:
```
PHP Warning:  Undefined array key "_from" in [path]/program/actions/mail/mark.php on line 113
```

This is the code here:
https://github.com/roundcube/roundcubemail/blob/94c78b350e872a42d0eb16206732619384a0abf9/program/actions/mail/mark.php#L113

I think by changing that line from
```
if ($_POST['_from'] == 'show') {
```
to something like
```
if (isset($_POST['_from']) && ($_POST['_from'] == 'show')) {
```
it would be avoided.

**Comment by alecpl** [comment]
Fixed.
