### ISSUE TITLE
My mail id purchased form Round cube is not receiving any emails from wordpress

### ISSUE THREAD

**Issue by GayathriKuru** [roundcube/roundcubemail#9079]
we are using an email purchased from round cube for receiving orders in a woocommerce site. But it is not receiving any mails particularly from wordpress. Even we have spoken with serverside and they too checked. They cant find any issues in the server side. Please provide solution

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
