### ISSUE TITLE
Roundcube Upgrade installto.sh: ERROR: Can use only one plugin for attachments/file uploads! Using 'filesystem_attachments', ignoring others.

### ISSUE THREAD

**Issue by Danrancan** [roundcube/roundcubemail#9080]
I just upgraded from roundcube 1.6.1 to roundcube 1.6.2. I followed the instructions from https://github.com/roundcube/roundcubemail/wiki/Upgrade using the `installto.sh` script. My Ubuntu sudo user is "`ubuntusudouser`". My Roundcube installation is located in `/var/www/roundcube`, and all files in it are owned by "`ubuntusudouser`" except the "`logs`" and "`temp`" directories, which are owned by `www-data`.

I Downloaded roundcube 1.6.2 but when I ran `installto.sh /var/www/roundcube/`, I recieved the following errors:

```
Running update script at target...
ERROR: Can use only one plugin for attachments/file uploads! Using 'filesystem_attachments', ignoring others.
Executing database schema update.
This instance of Roundcube is up-to-date.
Have fun!
All done.
```

What does this error mean? Does this mean there is something wrong with my upgraded roundcube installation? How can I correct this, or is it safe to ignore this error?

Thanks for any help.

**Comment by alecpl** [comment]
Check your configuration. You enabled more than one plugin for attachments handling. This is not supported.
