### ISSUE TITLE
DSN (write):  NOT OK for roundcube webmail

### ISSUE THREAD

**Issue by rcartists** [roundcube/roundcubemail#9082]
Hi, Sir,

localhost in what xampp control panel v.3.3.0 install etc.

Check DB config
DSN (write):  NOT OK  (SQLSTATE[HY000] [1045] Access denied for user 'rcmail'@'localhost' (using password: YES))

Please I need your help.

![roundcube-webmail-1](https://github.com/roundcube/roundcubemail/assets/140993683/9272ff69-1e0a-42c9-a2d9-c97b32832a01)

**Comment by alecpl** [comment]
Did you do:
```
CREATE USER rcmail@localhost IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON roundcube.* TO rcmail@localhost;
```

I'm closing the ticket as it's a setup issue. Use mailing list or forum.

**Comment by rcartists** [comment]
this where to not understand, please I need your help,
I am disabled and can't speak

**Comment by alecpl** [comment]
There's not much I can help. Read the INSTALL file about how to setup mysql database. Make sure to use proper user/database names. Do not use special characters in password.

**Comment by rcartists** [comment]
Sorry Sir, Not Understand please screenshot the video given to me. I need Your Help

**Comment by rcartists** [comment]
Please Sir, say nothing

**Comment by rcartists** [comment]
*Please Sir, say nothing*



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
07/31/23,
11:30:38 AM

**Comment by rcartists** [comment]
[alecpl] sir, Why didn't I leave a message for you?
