### ISSUE TITLE
PHP deprecated functions errors

### ISSUE THREAD

**Issue by DanielBecker715** [roundcube/roundcubemail#9083]
Using:
PHP8.2.8
Debian GNU/Linux 12 (bookworm)

`[31-Jul-2023 20:27:48 UTC] PHP Deprecated:  Creation of dynamic property reconnect::$imap_max_attempts is deprecated in /var/www/mail/plugins/reconnect/reconnect.php on line 19`

**Comment by alecpl** [comment]
Fixed.
