### ISSUE TITLE
Can't "Show source" in Elastic small/phone mode with x_frame_options=deny

### ISSUE THREAD

**Issue by gurnec** [roundcube/roundcubemail#9084]
## Steps to reproduce ##

1. Add config item:

    ```php
    $config['x_frame_options'] = 'deny';
    ```

2. Using the Elastic skin, narrow the window such that email previews are hidden.

3. Double-click an email to open it.

4. Click `⋮` (Menu) -> `More` -> `Show source`.

## Expected results ##

A `Show source` dialog appears with the email's plaintext source displayed in an iframe.

## Actual results ##

A `Show source` dialog appears with an error message such as `roundcubemail.example.com refused to connect`.

## Cause ##

Many actions eventually call `rcmail_output_html::write()` which alters the `X-Frame-Options` header from `deny` to `sameorigin` if the request is expected to be loaded into an iframe. The `mail_viewsource` action does not.

## Possible fix ##

Insert this line:

```php
$rcmail->output->page_headers();
```

before line 62 here:

https://github.com/roundcube/roundcubemail/blob/9e8e9a5ec0420a31cc35b59ce4a5fecb2bbf4580/program/actions/mail/viewsource.php#L61-L70

**Comment by alecpl** [comment]
Fixed.
