### ISSUE TITLE
Bug: delete default folder is possible

### ISSUE THREAD

**Issue by 1frederic** [roundcube/roundcubemail#9086]
When you go to parameters -> folder and made a right click on a default folder, you can delete it:

![delete_default_folder](https://github.com/roundcube/roundcubemail/assets/89577604/36a5e4a7-66e3-41b5-aff4-de2481953b00)

Can you protect default folders from deleting?

I put "$config['protect_default_folders'] = true;" in config/config.inc.php and i use the last roundcube version (1.6.2)

**Comment by alecpl** [comment]
The contextmenu is an external plugin and I'm unable to reproduce the issue using the most recent contextmenu version. The toolbar button is disabled properly.

That being said, we can consider whether we should make sure folders are protected additionally in the request handlers. Right now it's essentially only a UI convenience feature.

**Comment by 1frederic** [comment]
thank you for you answer
