### ISSUE TITLE
LDAP Address book search filter not taken into account

### ISSUE THREAD

**Issue by suprune20** [roundcube/roundcubemail#9089]
Looks like an error in the code:
https://github.com/roundcube/roundcubemail/blob/master/program/lib/Roundcube/rcube_ldap.php#L1023
        if ($filter = $this->filter) {
should be:
        if ($filter == $this->filter) {

**Comment by suprune20** [comment]
The above fix ( = -> ==) needs to be applied in [roundcube 1.6.2 complete](https://github.com/roundcube/roundcubemail/releases/download/1.6.2/roundcubemail-1.6.2-complete.tar.gz). As for the current code in github, I did not tested it

**Comment by m-bach** [comment]
Changing = to == fixes the initial adressbook view, but breaks searching.

I think the problem was fixed in commit 39bc7a5
