### ISSUE TITLE
"Filter" don't work correctly

### ISSUE THREAD

**Issue by SamieFanny** [roundcube/roundcubemail#9090]
The "Filters" does not work for all e-mails. Some filters have a condition with the "matching all of the following rules" option, and some have multiple conditions with the "matching any of the following rules" option. All filters are set to "From".
- I don't know about the Ruondcube version?!
- Browser is Google Chrome version 114.0.5735.199 (Official Build) (64-bit).
- the language is Dutch.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
