### ISSUE TITLE
To protect your privacy remote resources have been blocked. Allow. (Allow for all e-mails is missing)

### ISSUE THREAD

**Issue by bob7vogel** [roundcube/roundcubemail#9095]
I am on RoundCube 1.6.0 and i don't have control to change my version; my ISP does.  In previous versions when remote resources were blocked there were TWO options, one to ALLOW for one time use only, the other to ALLOW ALL, that is allow for all e-mails from that user to be unblocked automatically.  The second ALLOW ALL option no longer shows up.  My ISP (Green Geeks) says this is a software issue i must address with you.  so here goes.
Is this a bug?
Is this intentionally removed?  If so, do you plan to bring that option back in future releases?
I note that i see no options to configure this handling within the software.  If i've missed it do let me know how to configure it back please.   Thanks!

**Comment by alecpl** [comment]
Check your settings in:
Preferences > Displaying Messages > Main options > Allow remote resources (images, styles)
Preferences > Contacts > Collected Addresses > Store trusted senders in

ps. 1.6.2 is available.
