### ISSUE TITLE
Undefined array key "message" in ...program/include/rcmail_action.php on line 239

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#9098]
When i switch to Mail, i get 2 warnings in PHP/roundcube error log: 

`PHP Warning:  Undefined array key "message" in /path/to/program/include/rcmail_action.php on line 239`

Any idea, what can cause this issue?

BTW: I have disabled all plugins, to make sure, that this is a RC issue and not a plugin issue.

**Comment by alecpl** [comment]
Fixed.
