### ISSUE TITLE
Question: How to send message to user from plugin?

### ISSUE THREAD

**Issue by Offerel** [roundcube/roundcubemail#9099]
Is there a way to send a message or hint from a plugin to a user after login? In the form of a message box, mail in the inbox or popup? As a concrete example: For my Pictures plugin, a maintenance script can be run via CLI. If this maintenance script finds errors in pictures, I will collect the paths to these pictures in a text, store them somewhere and then send a message to the user after he has logged in. Currently my workaround is to send a mail to the user via the normal PHP mail() function. But I don't find this very elegant and would like to have an internal way. So far I haven't found anything. BTW: Directly after login means: Regardless of the plugin, hook or action, the user should receive a message. It would be nice if he can click on this to see more details.

**Comment by alecpl** [comment]
new_user_dialog plugin displays dialog after logon.

**Comment by Offerel** [comment]
Many thx for the tip. This is exactly what i  need. I have implemented it already in the dev branch of my plugin. Works fine.
