### ISSUE TITLE
MarkAsJunk: "mark as not spam" or "this message is not spam" action does not revert sa-learn previous actions

### ISSUE THREAD

**Issue by joinso** [roundcube/roundcubemail#9100]
Hi!
We setup our MarkAsJunk with this options:

$config['markasjunk_spam_cmd'] = '/bin/sa-learn --spam --username=%u --dbpath /var/spamassassin/bayes_db/ %f';

We do a test with a simple email. We mark as junk and we see this in the logs:

[16-Aug-2023 17:11:20 +0200]: <vq4vn345> /bin/sa-learn --spam --username=USERNAME_EMAIL --dbpath /var/spamassassin/bayes_db/ '/var/tmp/rcmSALearnjFpwTN'
Learned tokens from 1 message(s) (1 message(s) examined)

In the spamasssin database files we see this before "Mark As Junk":

sh-4.2# cd /var/spamassassin/bayes_db/
sh-4.2# ls -ltr
total 24
-rwxrwxrwx 1 root root 12288 Aug 16 16:52 bayes_toks
-rwxrwxrwx 1 root root 12288 Aug 16 16:52 bayes_seen

And after "mark as yunk":

sh-4.2# ls -ltr
total 24
-rwxrwxrwx 1 root root 12288 Aug 16 17:11 bayes_toks
-rwxrwxrwx 1 root root 12288 Aug 16 17:11 bayes_seen

It seems that the databases is touched but not increase in size.

Then we try "markasnotjunk" and the email is moved into Inbox, but the databases does not move:

sh-4.2# ls -ltr
total 24
-rwxrwxrwx 1 root root 12288 Aug 16 17:11 bayes_toks
-rwxrwxrwx 1 root root 12288 Aug 16 17:11 bayes_seen

It is normal?
I think that if I do "markasnotjunk" action, the spamassassin database must to be updated, no?

Regards,
Jordi
JOINSO

**Comment by joinso** [comment]
More info....
I do this:
spamassassin --lint -D
And I see this in the logs:
Aug 16 17:29:24.507 [22540] dbg: bayes: no dbs present, cannot tie DB R/O: = /var/spamassassin/bayes_db/bayes_toks
This is correct?
Regards,
Jordi
JOINSO

**Comment by johndoh** [comment]
did you set the config?
```php
// The command used to learn that a message is ham
// The command can contain the following macros that will be expanded as follows:
//      %u is replaced with the username (from the session info)
//      %l is replaced with the local part of the username (if the username is an email address)
//      %d is replaced with the domain part of the username (if the username is an email address or default mail domain if not)
//      %i is replaced with the email address from the user's default identity
//      %s is replaced with the email address the message is from
//      %f is replaced with the path to the message file
//      %h:<header name> is replaced with the content of that header from the message (lower case) eg: %h:x-dspam-signature
// If you do not want to run the command set this to null
$config['markasjunk_ham_cmd'] = null;
```
e.g. `/bin/sa-learn --ham --username=%u --dbpath /var/spamassassin/bayes_db/ %f`

**Comment by joinso** [comment]
Ok, I think you are right.
I do not know what "ham" means.
For people need to know what is ham: https://blog.barracuda.com/2013/10/03/ham-v-spam-whats-the-difference
This is my test:
Before markasjunk_spam:
sh-4.2# ls -ltr
total 24
-rwxrwxrwx 1 spamd spamd 12288 Aug 16 17:17 bayes_seen
-rwxrwxrwx 1 spamd spamd 12288 Aug 16 17:54 bayes_toks
After markasjunk_spam:
sh-4.2# ls -ltr
total 24
-rwxrwxrwx 1 spamd spamd 12288 Aug 19 12:31 bayes_toks
-rwxrwxrwx 1 spamd spamd 12288 Aug 19 12:31 bayes_seen
After markasjunk_ham:
sh-4.2# ls -ltr
total 24
-rwxrwxrwx 1 spamd spamd 12288 Aug 19 12:31 bayes_seen
-rwxrwxrwx 1 spamd spamd 12288 Aug 19 12:32 bayes_toks

A final question:
How I test that everything is setup correcty?
If I do:
spamassassin --lint -D
I still seeing this:
Aug 19 12:34:06.342 [8381] dbg: bayes: no dbs present, cannot tie DB R/O: = /var/spamassassin/bayes_db/bayes_toks

Thanks in advance!
