### ISSUE TITLE
you can upload maximum 20 files at once. 

### ISSUE THREAD

**Issue by lolminerxmrig** [roundcube/roundcubemail#9102]
Hi All.
can help me for change 20 files to 5000 files.
thanks a lot.

**Comment by alecpl** [comment]
https://www.google.com/search?q=How+can+I+upload+more+than+20+files+in+PHP%3F

**Comment by lolminerxmrig** [comment]
![image](https://github.com/roundcube/roundcubemail/assets/108659226/cce27e8f-38c5-4879-b015-b45114a868eb)
