### ISSUE TITLE
Unnecessary short notification popup every minute

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#9103]
I'm running the current version of Roundcube and when I'm reading a message, there's a small popup appearing in the lower right corner constantly every few seconds. I don't know what it says, it goes away too fast. So this black box on the white mail background keeps catching my attention, only to immediately waste it. Can this please be removed?

My browser is Firefox on Windows and I'm using the default theme in RC.

**Comment by alecpl** [comment]
Every few seconds? That does not make sense. You have to be more specific. What plugins are you using? What exactly does it say?

**Comment by ygoe** [comment]
Okay, I measured it now. It's 60 seconds. It just felt faster when I'm reading a text besides it.

I have no idea what it says. It's gone again within milliseconds. Just long enough to notice some black blob in that corner of the window, by far not long enough to focus it with your eyes or even read text.

Also happens in the Edge browser, to probably browser-independent.

**Comment by DalekDave** [comment]
I think he's talking about the mail refresh notification that you get, by
default, once a minute....

It's true that it appears and disappears really suddenly... I really wish
there was a 0.3 sec fade-out on that... :-)
Any chance someone could tell us the particular CSS class or ID to hack for
that?

With all best wishes,
Dave

**Comment by ygoe** [comment]
```
$config['plugins'] = array(
    'archive',
	'new_user_dialog',
	'tinymce_config',
	'vcard_attachments',
    'zipdownload',
);
```

Oh, a refresh notification? Why is such a thing needed? If there's something new, then show it, otherwise, what is the reason to report anything to the user?

**Comment by DalekDave** [comment]
It just reassures you that your mail is indeed getting checked and that
Roundcube is not just sitting there dead in the water... :-)

**Comment by ygoe** [comment]
Then update a low-contrast last update time somewhere. That doesn't change many pixels and doesn't distract unduly.

**Comment by ygoe** [comment]
On a slower connection I can now actually read that message from time to time. It says something like "Update is ongoing...". I don't know what it is updating, maybe the message list. But in the compose view there is nothing to update. Anyway, it's distracting and not helpful, so it shall go away.

**Comment by alecpl** [comment]
In mail list view it refreshes the list and unread counters. In mail composer it updates the draft with current message content (auto-save). Both intervals are configurable.

**Comment by ygoe** [comment]
Sorry, but how is this completed?! I didn't say I want these updates to stop. I was just referring to the inappropriately distracting visual appearance of this activity. It might well be removed altogether since I can simply expect automatic updates. Why does the app need to poke the user every time it has checked for updates, even when there's nothing new to show? That is just weird and not at all user-friendly.
