### ISSUE TITLE
Kolab Git is down (Erreur 503) - Impossible to install with composer

### ISSUE THREAD

**Issue by MetallianFR68** [roundcube/roundcubemail#9104]
Impossible to install Roundcube anymore with composer

Failed to execute git clone --mirror -- 'https://git.kolab.org/diffusion/PNL/php-net_ldap3.git' '/home/debian/.cache/composer/vcs/https---git.kolab.org-diffusion-PNL-php-net-ldap3.git/'

Kolab serveur is down since at least 1 week (Error 503 on all pages)

**Comment by alecpl** [comment]
There's some temporal problems with git.kolab.org at the moment, but the package is available on packagist, so it should work if you don't point the composer to the repository. In most recent composer.json in Roundcube we do not use "repositories" entry for this package.

**Comment by alecpl** [comment]
This has been fixed.
