### ISSUE TITLE
FEATURE copy prod database to develop

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9108]
Maybe a bit lazy request, but what about adding here something to copy the production database to develop so you can do the migration in develop, and test it in develop?

![installer](https://github.com/roundcube/roundcubemail/assets/13450219/09c747aa-a679-42f5-83f7-7b71a4e0e8b1)

**Comment by alecpl** [comment]
Dealing with database is not trivial. I would not bother with such an option. I doubt it is that useful.
