### ISSUE TITLE
Support for OpenID Connect RP-Initiated Logout

### ISSUE THREAD

**Issue by azmeuk** [roundcube/roundcubemail#9109]
I suggest implementing the [OIDC Connect RP-Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) specification.

> This specification complements the [OpenID Connect Core 1.0](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#OpenID.Core) [OpenID.Core] specification by enabling the Relying Party to request that an End-User be logged out by the OpenID Provider.

This is the "mirror" spec of #9110. This would allow users to be disconnected from other services when they log out from roundcube. This is very convenient for service providers offering several services (say nextcloud and roundcube for instance).

Technically this would consist in:
- Sending a request with a payload to the Identity Provider (IdP) when users disconnect from roundcube

Related to #8057

**Comment by alecpl** [comment]
Done.
