### ISSUE TITLE
Hyperlink text is incorrect for URL

### ISSUE THREAD

**Issue by stevenwhiz** [roundcube/roundcubemail#9111]
Found in Version: 1.6.1, 1.6.2

Configure Roundcube to compose messages using HTML.  In Settings, select Preferences and then Composing Messages.  For "Compose HTML messages", set to "always".

Compose a message to yourself with the following:

```
https://www.google.com

-Anonymous
```
When you created the email, notice that it correctly highlights the hyperlink text.  Send the mail.

Now view the email.  You will notice "-Anonymous" is included as part of the hyperlink.  In general, when it sees "https://...", it doesn't know where the hyperlink ends and tends to grab additional text and makes them part of the hyperlink.

Workaround: If you switch to "Plain text", then it correctly displays the hyperlink.

**Comment by alecpl** [comment]
I'm unable to reproduce. Could you provide the message source? That would tell us at least whether the issue is in composing or previewing the message.

Did you try with another browser?

**Comment by alecpl** [comment]
Still no luck in reproducing. Tested with Chrome and Firefox on Linux.

**Comment by stevenwhiz** [comment]
You can try on my system.  Go to https://mail.whizkidzcc.com.  Log in as "tester".  Password is the same.  I currently have plugins enabled, but I get the same results when I configure `$config['plugins'] = []`; in config/config.inc.php.

**Comment by alecpl** [comment]
Thanks. Looking at the sample message there I can see the HTML content in the message body is ok:
```
<body>
    <b>Hello,</b><br>
    <br>
    <a class="moz-txt-link-freetext" href="https://google.com">https://google.com</a><br>
    <br>
    -Steven<br>
  </body>
```
Somehow it gets malformed when previewing the message.

However, it works without issues on my Roundcube 1.6.3 installation, using the same email message.

**Comment by stevenwhiz** [comment]
Hmm...  I just upgraded to 1.6.3 and still see the same problem.  I went back to an older version, 1.4.9, and the problem existed back then.  If it makes any difference, I'm running this on Ubuntu 20.04.

**Comment by alecpl** [comment]
Try PHP8 if you can. Also, can you make sure you have "masterminds/html5" in your dependencies and what version?

**Comment by stevenwhiz** [comment]
Unfortunately, I can't switch to PHP 8 at this time.

I do see a directory named /vendor/masterminds/html5/.  The RELEASE.md file lists "2.7.6  (2021-08-18)" as the latest release. 
 How do you know if it's a dependency?

**Comment by alecpl** [comment]
I'm unable to reproduce, and I have no clue.

**Comment by stevenwhiz** [comment]
Do you have an idea of where the problem might be?  Is it in the masterminds/html5 code?

**Comment by alecpl** [comment]
Yes. I suspect masterminds/html5 or rcube_washtml class, but as I can't reproduce I suspect PHP itself.

**Comment by stevenwhiz** [comment]
Thanks for looking into this.  I discovered that this was a configuration error so I am closing this issue.  The php.ini had this in the file.
extension=dom.so

However, the PHP module was already including all extensions in /etc/php/7.4/apache2/conf.d, so this extension was included twice which ended up causing this problem.

**Comment by alecpl** [comment]
For reference, a known PHP issue https://github.com/php/php-src/issues/12215
