### ISSUE TITLE
Unable to connect to managesieve on 1.6.2

### ISSUE THREAD

**Issue by gomanuke** [roundcube/roundcubemail#9114]
Hi!
After upgrading on 1.6.2 got a 

```
[31-Aug-2023 10:53:52 +0500]: <e17lgbu5> PHP Error: Unable to connect to managesieve on localhost:4190 in /var/www/mail/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 227 (GE
T /mail/?_task=settings&_action=plugin.managesieve)
[31-Aug-2023 10:53:52 +0500]: <e17lgbu5> PHP Error: Not currently in AUTHORISATION state (GET /mail/?_task=settings&_action=plugin.managesieve)
[31-Aug-2023 10:53:52 +0500]: <e17lgbu5> PHP Error: Not currently connected (GET /mail/?_task=settings&_action=plugin.managesieve)
```

tcp   LISTEN 0      128                *:2000             *:*    users:(("dbmail-timsieve",pid=115629,fd=11))

/var/www/mail/plugins/managesieve/config.inc.php
$config['managesieve_port'] = 2000
$config['managesieve_host'] = 'localhost';

Would You advice, where i should to dig?

**Comment by gomanuke** [comment]
doesN"t work
$config['managesieve_port'] = 2000;
$config['managesieve_host'] = 'localhost';

DOES word

$config['managesieve_port'] = 2000;
$config['managesieve_host'] = 'localhost:2000';

What's wrong with it, guys?

**Comment by gomanuke** [comment]
The matter i use dbmail that have dbmail-sieve module, so i've checked etc/dbmail/dbmail.conf
[SIEVE]
port                  = 2000.

It proved ss -tulpn | grep sie
RC's syntax $config['managesieve_host'] = 'localhost:2000'; You already have.
Check what daemon gives You sieve function and what port it listen.

**Comment by himpierre** [comment]
I have found the reason why roundcube tried port 2000. The option managesieve_port is gone. :)

```
// Managesieve server host (and optional port). Default: localhost.
// Replacement variables supported in host name:
// %h - user's IMAP hostname
// %n - http hostname ($_SERVER['SERVER_NAME'])
// %d - domain (http hostname without the first part)
// For example %n = mail.domain.tld, %d = domain.tld
// If port is omitted it will be determined automatically using getservbyname()
// function, with 4190 as a fallback.
// Note: Add tls:// prefix to enable explicit STARTTLS
// or add ssl:// prefix to enable implicit SSL.
$config['managesieve_host'] = 'localhost';
```

cheers, t.
