### ISSUE TITLE
Cannot delete calendars in Roundcube

### ISSUE THREAD

**Issue by jbendsen69** [roundcube/roundcubemail#9116]
Hi,
When deleting calender I get a message 'Failed to save changes'

Please fix :-) 

Can you give me the folder path to manually delete them?

Thanks
Jesper

![0114](https://github.com/roundcube/roundcubemail/assets/37797430/c4a60289-f7fb-4858-9b6d-e91656e7103a)
![0113](https://github.com/roundcube/roundcubemail/assets/37797430/0b8a754d-bbad-43b5-8760-d5b804aff927)
![0115](https://github.com/roundcube/roundcubemail/assets/37797430/970fa96e-a508-41d0-8c12-f24348f08f68)

**Comment by dilyanpalauzov** [comment]
To my knowlegde there are several plugins called “calendar“, which are outside the standard roundcube package.

Why don’t you ask the developers of the calendar plugin on this?

**Comment by f1-outsourcing** [comment]
@jbendsen69 what plugin are you using? Did you do a bit of research or did you just download something? I am looking for something that works with 'any' caldav server.

**Comment by alecpl** [comment]
We do not support any calendar plugins here.
