### ISSUE TITLE
Duplicating return-path header

### ISSUE THREAD

**Issue by gomanuke** [roundcube/roundcubemail#9119]
Hi, guys!
I'm using exim+dbmail +RounCube (1.6.2) on Debian 11 and encountered with a problem of duplicating return-path header.
(dbmail shows it in log) So i'm trying to locate the root of problem (Exim, dbmail, external mail clients)

Would You explain does screenshot concern it? Why RoundCube display return-path as two strings? Or it's just a display nuances?
![image](https://github.com/roundcube/roundcubemail/assets/47693546/b79336b7-8779-4ca1-9a5d-3adba7a27078)

**Comment by johndoh** [comment]
Please provide the original message headers. You can get these by selecting the message then choosing "more" and "show source" on the toolbar. Specifically we need to see if the message source contains 2 Return-Path headers.

**Comment by gomanuke** [comment]
Here You are the result of echo "BODY1" | mail -s "TEST1" root

Return-Path: root@hq.domain.test
Return-path: <root@hq.domain.test>
Received: from [888.88.8.88] (port=60150 helo=hq.domain.test)
    by mail.domain.com with esmtp (Exim 4.94.2)
    (envelope-from <root@hq.domain.test>)
    id 1qcmx9-000mFI-Tp
    for oblako@domain.com; Sun, 03 Sep 2023 18:15:48 +0500
Received: by hq.domain.test (Postfix)
    id 0300B120DF6; Sun, 3 Sep 2023 18:15:47 +0500 (+05)
Delivered-To: root@hq.domain.test
Received: by hq.domain.test (Postfix, from userid 0)
    id 00229120EAD; Sun, 3 Sep 2023 18:15:46 +0500 (+05)
To: root@hq.domain.test
MIME-Version: 1.0
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: 8bit
Message-Id: <20230903131547.00229120EAD@hq.domain.test>
Date: Sun, 3 Sep 2023 18:15:46 +0500 (+05)
From: root <root@hq.domain.test>
X-SA-Exim-Connect-IP: 188.18.7.71
X-SA-Exim-Mail-From: root@hq.domain.test
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on front.domain
X-Spam-Level:
X-Spam-Status: No, score=0.2 required=5.0 tests=ALL_TRUSTED,DKIM_ADSP_NXDOMAIN,
    NO_DNS_FOR_FROM autolearn=no autolearn_force=no version=3.4.6
Subject: TEST1
X-SA-Exim-Version: 4.2.1 (built Sat, 13 Feb 2021 17:57:42 +0000)
X-SA-Exim-Scanned: Yes (on mail.domain.com)

**Comment by alecpl** [comment]
Not a Roundcube issue. Roundcube does not set this header.
