### ISSUE TITLE
FEATURE send message saves in same folder as message replied to

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9122]
Maybe nice to have an option to turn on, save send messages to same folder as the message is in that is being replied to.

**Comment by johndoh** [comment]
The option already exists: `Preferences > Composting Messasges > Place replies in the folder of the message being replied to` or `reply_same_folder` in the config file.

**Comment by f1-outsourcing** [comment]
Thanks!!!!
