### ISSUE TITLE
When i try to send a email with roundcube to gmail i get this error

### ISSUE THREAD

**Issue by MadaraV2492** [roundcube/roundcubemail#9124]
Here the error
<img width="479" alt="Screenshot 2023-09-04 222751" src="https://github.com/roundcube/roundcubemail/assets/116122089/6f5aae34-33fc-434f-b004-6fffdaedd458">

**Comment by johndoh** [comment]
That is a problem with your SMTP server, not a Roundcube issue.

Roundcube is not a service but free software, it is an IMAP client only. If you are not the person responsive for your mail server you should contact who ever is for support.
