### ISSUE TITLE
FEATURE maybe include updating the system table in the sql statements?

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9130]
Running these SQL/mysql/2020020101.sql does not update the version so your installer will always be whining about the schema.

**Comment by alecpl** [comment]
You're not supposed to run the SQL scripts manually, use the updatedb.sh (or installto.sh) scripts instead.

**Comment by f1-outsourcing** [comment]
I was not even thinking about running them. If this was not working from the web interface, why would it work from the command line? I had to correct a duplicate record, because previously this was case sensitive and now not.

I still think it would be nice to have 'better' sql statements. I am not even sure if transactions are being used or not.
