### ISSUE TITLE
No reverse-proxy after upgrade

### ISSUE THREAD

**Issue by r4yzs** [roundcube/roundcubemail#9134]
Hello,

After migrating my server from Debian 11 to 12, my reverse proxy is no longer working. Locally everything works, but when accessing through my reverse proxy, I get the initial login page and after entering any credentials, I receive a 404 page not found error.

My nginx reverse proxy conf :

Code: [[Select]](javascript:void(0);)

server{

    # DNS Record for catch request
    server_name webmail.guill4ume.fr;

    # Open block for process forward request
    location / {
        # Server where traffic is transferred
        proxy_pass http://10.0.0.12/roundcube/;
        # Include file proxy_params with general param
        include proxy_params;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/guill4ume.fr-0001/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/guill4ume.fr-0001/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server{
    if ($host = webmail.guill4ume.fr) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name webmail.guill4ume.fr;
    listen 80;
    return 404; # managed by Certbot

And my roundcube conf with apache :

Code: [[Select]](javascript:void(0);)

root@MAIL:~# cat /etc/apache2/sites-available/roundcube.conf
Alias /roundcube /var/lib/roundcube

<Directory /var/lib/roundcube/>
    AddType application/x-httpd-php .php
    Options +FollowSymLinks
    DirectoryIndex index.php

    # Les directives recommandées pour une sécurité améliorée
    Require all denied
    Require ip 127.0.0.1
    Require ip ::1
    Require ip 10.0.0.0/24

    <IfModule mod_php.c>
        php_flag register_globals Off
        php_flag magic_quotes_gpc Off
        php_flag magic_quotes_runtime Off
        php_flag short_open_tag On
    </IfModule>

</Directory>

On debian 12 :

- roundcube 1.6.1
- php 8.2.7 

Thanks you

**Comment by rickygm** [comment]
I am in the same situation, my reverse proxy nginx and the webmail on another computer with nginx

Nginx with Roundcube 

server {
  listen 80;
  server_name webmail.domain;
  root /var/www/webmail/;
  index index.php index.html index.htm;

  access_log /var/log/nginx/webmail.domain.access.log;
  error_log /var/log/nginx/webmail.domain.error.log;

  location / {
    try_files $uri $uri/ /index.php;
  }

  location ~ \.php$ {
    try_files $uri $uri/ /index.php;
    include /etc/nginx/fastcgi_params;
    fastcgi_pass unix:/run/php-fpm/www.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
  }
location ~ /.well-known/acme-challenge {
    allow all;
  }
 location ~ ^/(README|INSTALL|LICENSE|CHANGELOG|UPGRADING)$ {
    deny all;
  }
  location ~ ^/(bin|SQL)/ {
    deny all;
  }
 # A long browser cache lifetime can speed up repeat visits to your page
  location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {
       access_log        off;
       log_not_found     off;
       expires           360d;
  }
}

###. reverse proxy with Nginx 

upstream backend1007 {
	server x.x.x.x:80; ## 
	keepalive 2;
	}
	server {
	listen 80;
	server_name webmail.domain; #YourIP or domain
	return 301 https://$server_name$request_uri;  # redirect all to use ssl

	}

	server {
	listen 443 ssl http2;
	server_name webmail.domain;
	access_log /var/log/nginx/webmail.domain.access.log specialLog;
	error_log /var/log/nginx/webmail.domain.error.log;


location / {
	proxy_http_version 1.1;
	proxy_set_header Connection "";
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP  $remote_addr;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_connect_timeout 900s;
	proxy_send_timeout 900s;
	proxy_read_timeout 900s;
	proxy_buffer_size 64k;
	proxy_buffers 16 32k;
	proxy_busy_buffers_size 64k;
	proxy_redirect off;
	proxy_request_buffering off;
	proxy_buffering off;
	proxy_pass http://backend1007;

}

I saw that some have the same problem, but I don't see a specific solution

https://github.com/roundcube/roundcubemail/pull/8770

**Comment by alecpl** [comment]
Nginx setup is out of scope here.

**Comment by jult** [comment]
The issue appeared due to roundcube code changes, not nginx changes. Your essentially saying: Waaah, head in the sand, fingers in ears, blinders on. Because we're now back to using squirrelmail and snappymail. Work fine with a standard reverse proxy nginx config.
