### ISSUE TITLE
Browser Login Security Issue

### ISSUE THREAD

**Issue by IEales** [roundcube/roundcubemail#9138]
My web host uses Roundcube for web mail

In both Edge and Chrome, attempting to open a second account in another tab or instance, _opens the already open_ account.

Logging out, and Closing all browsers, opening a new browser instance and logging in with a URL 
https://webmail.omnis.com/roundcubemail/?_login&_user=[UserName]
***OPENS THE LOGGED OFF ACCOUNT WITHOUT PASSWORD PROMPT***

Thus, it appears the session cookie persists long after the session ended.

The host attitude is Roundcube is free and not their problem.

=================================

Web Host Version
Roundcube Webmail 1.6.2
Copyright © 2005-2022, The Roundcube Dev Team

Verified in Edge and Chrome on W10

Microsoft Edge
Version 116.0.1938.81 (Official build) (64-bit)

Chrome is up to date
Version 117.0.5938.63 (Official Build) (64-bit)

**Comment by eclipxe13** [comment]
I was unable to reproduce your issue on my installation.
Ask your provider to update Roundcube.

**Comment by IEales** [comment]
Thanks.On Sep 15, 2023 16:33, Carlos C Soto ***@***.***> wrote:
I was unable to reproduce your issue on my installation.
Ask your provider to update Roundcube.

**Comment by alecpl** [comment]
This is not normally possible. They might be using some plugin.
