### ISSUE TITLE
Elastic: UI uglifcation when adding Action row to Sieve Filter

### ISSUE THREAD

**Issue by rnkn** [roundcube/roundcubemail#9139]
## Description

There is a UI misalignment/corruption/uglification when adding a new Action row to a Sieve Filter in the Elastic skin. The initial dropdown should display the “Move message to” option but is blank, while the second dropdown is styled in the browser default style not the skin, and the add & delete buttons are misaligned. See attachment:

![IMG_0227](https://github.com/roundcube/roundcubemail/assets/1256849/254798ed-fb64-4a95-96d0-894e78591df5)

## To reproduce:

1. Navigate to Sieve Filters
2. Select an existing Filter or Create new
3. Select “+” on Actions row

## Expected results:

Row is added with consistent style.

## Actual results:

See above attachment.

## Version

Roundcube Webmail 1.6.1

**Comment by alecpl** [comment]
I'm unable to reproduce in 1.6.3.

What web browser? Are there any errors in browser console? What plugins are you using?

**Comment by rnkn** [comment]
The first screenshot is from Safari for iPadOS 16.6.1.

This screenshot is from Epiphany (aka Gnome Web) 44.6:

![IMG_0228](https://github.com/roundcube/roundcubemail/assets/1256849/c35643af-2df6-48d4-afcd-088c5f399eff)

The WebKit console gives the following when the Create button is selected:
```
[Warning] jQuery.Deferred exception: null is not an object (evaluating 's.style') (2) (jquery.min.js, line 36)
rule_header_select — managesieve.min.js:17:1226
(anonymous function) — managesieve.min.js:17:6614
each — jquery.min.js:36:2981
sieve_form_init — managesieve.min.js:17:6557
(anonymous function) — managesieve.min.js:17:9820
triggerEvent — common.min.js:28:8791
(anonymous function) — app.min.js:35:15183
(anonymous function) — inbox.purelymail.com:120
e — jquery.min.js:36:30011
(anonymous function) — jquery.min.js:36:30309
undefined
[Error] TypeError: null is not an object (evaluating 's.style')
	(anonymous function) (jquery.min.js:36:31678)
```

**Comment by alecpl** [comment]
Works for me in Firefox and Chrome.

The error is not clear because of the code minification. Could you made a test after temporarily removing managesieve.min.js file?

**Comment by rnkn** [comment]
This is Firefox for me:

![Screenshot from 2023-09-16 19-46-22](https://github.com/roundcube/roundcubemail/assets/1256849/266ac846-b329-41ea-a7fe-3f635b7d5035)

Sorry, I'm not sure what you mean by removing managesieve.min.js? (This is not my own Roundcube installation, it's my email provider.)

For completeness, here is the plugins list:

acl | 1.8
archive | 3.5
authres_status | 0.6.3
carddav | v5.0.1
contextmenu | 3.3.1 
custom-from | 1.6.7
database_attachments | 1.2 
filesystem_attachments | 1.0
hide_blockquote | 1.0
identity_select | 1.1 
identity_smtp | 1.6.0
jqueryui | 1.13.1
keyboard_shortcuts
managesieve | 9.4 
markasjunk | 2.0
message_highlight | 4.4 
newmail_notifier | 0.8 
purelymail_autologon | 1.0
purelymail_automatic_addressbook 
purelymail_message_alert | 1.0 
purelymail_partial 
zipdownload | 3.4

**Comment by alecpl** [comment]
Ok, so this is not browser specific, but rather server/setup specific. I suppose as an end-user you can't help much more with this issue.

**Comment by rnkn** [comment]
I received the following info from my provider:

> It seems like Roundcube bugs out if the relational and spamtest extensions aren't supported. Since those are useful extensions I'll add them, though technically the bug is Roundcube's.

**Comment by alecpl** [comment]
Thank you. I was able to reproduce the error if I disable these extensions.

**Comment by alecpl** [comment]
Fixed.
