### ISSUE TITLE
PGP-signed messages "Sender verification failed" in Protonmail

### ISSUE THREAD

**Issue by lemniskett** [roundcube/roundcubemail#9141]
Hi, I started using Roundcube 1.6.3 for sending signed emails, but for some reason sometimes Protonmail is unable to verify the sender of the email:
![1694923062_grim](https://github.com/roundcube/roundcubemail/assets/43294321/3ec695ca-2428-4bf1-a588-2672a0abae2c)
The issue is happening randomly but if the mail is long enough and includes HTML then it's very likely to happen, If I just send a mail containing one or two words the issue rarely occurs.

At first I thought it was my mail server problem but Thunderbird doesn't have similar issue, no matter how big the email is:
![1694923295_grim](https://github.com/roundcube/roundcubemail/assets/43294321/cff0fbb5-10a0-4134-bd2b-451575a60ad3)

Perhaps It's related to my PHP configuration or something in the PHP GnuPG's library, I'm not entirely sure, I've tried 3 different operating system for installing the PHP runtime (Debian, Ubuntu, Rocky Linux) but the issue persists, Here's the output from enigma_debug where the issue occur:
[enigma.log](https://github.com/roundcube/roundcubemail/files/12642039/enigma.log)

**Comment by alecpl** [comment]
What if you open the email with another client (Thunderbird)? Maybe that's just Protonmail issue.

What PHP version? What GnuPG version?

**Comment by lemniskett** [comment]
Hi @alecpl, "Sender Verification Failed" simply means the digital signature is invalid, and you were right! given the randomness, it's probably just Protonmail issue, I tested multiple emails from different providers from Thunderbird, and everything just works fine

Closing the issue, thanks!
