### ISSUE TITLE
v1.6.3 PHP warnings in installer step 3

### ISSUE THREAD

**Issue by mibyge** [roundcube/roundcubemail#9142]
Hello.

I'm trying to update to the latest version (v1.6.3), but running the installer afterwards gives the following error:

URL: https://domain.foo/installer/index.php?_step=3
PHP Warning:  Undefined array key "obsolete" in D:\path\installer\test.php on line 69
PHP Warning:  Undefined array key "dependencies" in D:\path\installer\test.php on line 85

I've also tried with a completely fresh installation from roundcubemail-1.6.3-complete.tar.gz to make sure my source was not corrupt, but that gives the same error.

I'm using PHP 8.1.21.

Thanks.

**Comment by alecpl** [comment]
Fixed.
