### ISSUE TITLE
Duplicate entries in identities and users table

### ISSUE THREAD

**Issue by ninadnshaha** [roundcube/roundcubemail#9144]
I am running 3 instances of Roundcube 1.5.2 on Centos 8.5 with MySQL Galera cluster and Memcache. The user base is quite high (in thousands).

Recently, I observed that my signature vanishes every time I log in again. Nothing in the logs, and even Galera synchronization is working properly. Also, any other user has not reported a similar issue.

While digging deeper, I found multiple entries in the identities table against my email address. Below are the details of the same.

I am not sure what this caused and how to debug this further. I request all to guide me with the same.

SQL Query: select identity_id, user_id, changed, del, standard, name, organization,email from identities where email="abc@example.com"; 

The result is:

+-------------+---------+---------------------+-----+----------+----------------+--------------+------------------+
| identity_id | user_id | changed             | del | standard | name           | organization | email            |
+-------------+---------+---------------------+-----+----------+----------------+--------------+------------------+
|          61 |      64 | 2022-04-08 19:55:24 |   0 |        1 | Abc Def    |              | abc@example.com |
|       69864 |   70140 | 2022-04-09 19:03:45 |   0 |        1 | Abc Def    |              | abc@example.com |
|       69932 |   70208 | 2022-04-09 19:58:18 |   0 |        1 | Abc Def    |              | abc@example.com |
|       69963 |   70239 | 2022-04-09 20:16:03 |   0 |        1 | Abc Def    |              | abc@example.com |
|       70187 |   70463 | 2022-04-10 09:12:36 |   0 |        1 | Abc Def    |              | abc@example.com |
|       70512 |   70788 | 2022-04-11 08:56:05 |   0 |        1 | Abc Def    |              | abc@example.com |
|       70807 |   71086 | 2022-04-11 13:12:03 |   0 |        1 | Abc Def    |              | abc@example.com |
|       71438 |   71723 | 2022-04-13 12:59:23 |   0 |        1 | Abc Def    |              | abc@example.com |
|       71497 |   71782 | 2022-04-13 16:04:59 |   0 |        1 |            |              | abc@example.com |
|       91552 |   91843 | 2022-07-25 18:52:33 |   0 |        1 | Abc Def |              | abc@example.com |
|       91906 |   92197 | 2022-07-26 15:59:43 |   0 |        1 | Abc Def |              | abc@example.com |
|       92309 |   92600 | 2022-07-27 18:10:41 |   0 |        1 | Abc Def |              | abc@example.com |
|       92583 |   92874 | 2022-07-28 18:57:42 |   0 |        1 | Abc Def |              | abc@example.com |
|       93172 |   93463 | 2022-08-01 15:32:20 |   0 |        1 | Abc Def |              | abc@example.com |
.
.
|      155787 |  156195 | 2023-09-14 13:29:48 |   0 |        1 | Abc Def |              | abc@example.com |
|      155954 |  156362 | 2023-09-15 16:03:14 |   0 |        1 | Abc Def |              | abc@example.com |
|      155957 |  156365 | 2023-09-15 16:05:37 |   0 |        1 | Abc Def |              | abc@example.com |
|      155960 |  156368 | 2023-09-15 16:06:24 |   0 |        1 | Abc Def |              | abc@example.com |
|      155964 |  156372 | 2023-09-15 16:08:57 |   0 |        1 | Abc Def |              | abc@example.com |
|      155967 |  156375 | 2023-09-15 16:09:52 |   0 |        1 | Abc Def |              | abc@example.com |
|      155968 |  156376 | 2023-09-15 18:01:15 |   0 |        1 | Abc Def |              | abc@example.com |
|      155973 |  156381 | 2023-09-15 16:16:59 |   0 |        1 | Abc Def |              | abc@example.com |
+-------------+---------+---------------------+-----+----------+----------------+--------------+------------------+
342 rows in set (0.00 sec)

mysql> select * from users where user_id="156374";
Empty set (0.00 sec)

mysql> select * from users where user_id="156375";
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
| user_id | username         | mail_host       | created             | last_login          | failed_login | failed_login_counter | language | preferences                                       |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
|  156375 | abc@example.com | imap.example.com | 2023-09-15 16:09:16 | 2023-09-15 16:09:16 | NULL         |                 NULL | en_GB    | a:1:{s:11:"client_hash";s:16:"fqBblnewnbZ2Aajs";} |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from users where user_id="156365";
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
| user_id | username         | mail_host       | created             | last_login          | failed_login | failed_login_counter | language | preferences                                       |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
|  156365 | abc@example.com | imap.example.com | 2023-09-15 16:05:37 | 2023-09-15 16:05:37 | NULL         |                 NULL | en_GB    | a:1:{s:11:"client_hash";s:16:"ny0cKjYDs3UIAtwD";} |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
1 row in set (0.00 sec)

mysql> select * from users where user_id="156368";
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
| user_id | username         | mail_host       | created             | last_login          | failed_login | failed_login_counter | language | preferences                                       |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
|  156368 | abc@example.com | imap.example.com | 2023-09-15 16:06:24 | 2023-09-15 16:06:24 | NULL         |                 NULL | en_GB    | a:1:{s:11:"client_hash";s:16:"ika3aP46jakExsvC";} |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
1 row in set (0.01 sec)

mysql> select * from users where user_id="156362";
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
| user_id | username         | mail_host       | created             | last_login          | failed_login | failed_login_counter | language | preferences                                       |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
|  156362 | abc@example.com | imap.example.com | 2023-09-15 16:02:31 | 2023-09-15 16:02:31 | NULL         |                 NULL | en_US    | a:1:{s:11:"client_hash";s:16:"PLVg20afbr0e6k4U";} |
+---------+------------------+-----------------+---------------------+---------------------+--------------+----------------------+----------+---------------------------------------------------+
1 row in set (0.00 sec)

The Roudcube version is set to

select * from system;
+-------------------+------------+
| name              | value      |
+-------------------+------------+
| roundcube-version | 2020122900 |
+-------------------+------------+
1 row in set (0.00 sec)

Initially, it was 1.4.3, and I have upgraded it to 1.5.2.
I took a backup of the database and then deleted all the entries related to my email and username.

After this, I logged in and created a signature, and logged out (Firefox)
Then, I opened Google Chrome and logged in again, there was no signature.

While checking the identities table in the database, I found 2 entries, one with a signature and one without a signature.
the only difference was with the default language. It was en_US in one entry and en_GB in another.

Also, I observed multiple duplicate entries for other users as well.

**Comment by alecpl** [comment]
As explained in the forum. This should not happen because of the unique key. So, it must be some Galera issue.

**Comment by valarauco** [comment]
Hello... I'm back. 

I want to reopen this issue because I think there's a problem with migration SQL/mysql/2020020101.sql.
We have Galara cluster with almost 100.000 users on Roundcube... after upgrading we had this same issue of duplicated entries.
I managed to isolate the issue to the collation change
 https://github.com/roundcube/roundcubemail/blob/16fe3ba8c5f3f866a29cb644d36426f62ebc054b/SQL/mysql/2020020101.sql#L30
 
Changing collation may generate an [index corruption](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/don-t-let-collation-versions-corrupt-your-postgresql-indexes/ba-p/1978394), so the recommendation is to reindex the table.

In MySQL it can be done with a null ALTER like `ALTER TABLE users ENGINE=innodb;`.
I propose to change 2020020101.sql and move the `ALTER TABLE users ROW_FORMAT=DYNAMIC;`. This solution worked for us, no errors on indexes and no duplicate entries allowed, as expected.

File should be like this:
```
-- Dropping foreign keys and changing table format is needed for some versions of MySQL (#7277)
ALTER TABLE `cache` DROP FOREIGN KEY `user_id_fk_cache`;
ALTER TABLE `cache_index` DROP FOREIGN KEY `user_id_fk_cache_index`;
ALTER TABLE `cache_thread` DROP FOREIGN KEY `user_id_fk_cache_thread`;
ALTER TABLE `cache_messages` DROP FOREIGN KEY `user_id_fk_cache_messages`;
ALTER TABLE `contactgroups` DROP FOREIGN KEY `user_id_fk_contactgroups`;
ALTER TABLE `contacts` DROP FOREIGN KEY `user_id_fk_contacts`;
ALTER TABLE `dictionary` DROP FOREIGN KEY `user_id_fk_dictionary`;
ALTER TABLE `filestore` DROP FOREIGN KEY `user_id_fk_filestore`;
ALTER TABLE `identities` DROP FOREIGN KEY `user_id_fk_identities`;
ALTER TABLE `searches` DROP FOREIGN KEY `user_id_fk_searches`;

ALTER TABLE `session` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `users` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `cache` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `cache_shared` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `cache_index` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `cache_thread` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `cache_messages` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `contacts` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `contactgroups` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `identities` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `dictionary` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `searches` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `filestore` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE `system` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `users` CHANGE `username` `username` varchar(128) BINARY NOT NULL;
ALTER TABLE `cache` CHANGE `cache_key` `cache_key` varchar(128) BINARY NOT NULL;
ALTER TABLE `cache_shared` CHANGE `cache_key` `cache_key` varchar(255) BINARY NOT NULL;
ALTER TABLE `cache_index` CHANGE `mailbox` `mailbox` varchar(255) BINARY NOT NULL;
ALTER TABLE `cache_thread` CHANGE `mailbox` `mailbox` varchar(255) BINARY NOT NULL;
ALTER TABLE `cache_messages` CHANGE `mailbox` `mailbox` varchar(255) BINARY NOT NULL;

ALTER TABLE `session` ROW_FORMAT=DYNAMIC;
ALTER TABLE `users` ROW_FORMAT=DYNAMIC;
ALTER TABLE `cache` ROW_FORMAT=DYNAMIC;
ALTER TABLE `cache_shared` ROW_FORMAT=DYNAMIC;
ALTER TABLE `cache_index` ROW_FORMAT=DYNAMIC;
ALTER TABLE `cache_thread` ROW_FORMAT=DYNAMIC;
ALTER TABLE `cache_messages` ROW_FORMAT=DYNAMIC;
ALTER TABLE `contacts` ROW_FORMAT=DYNAMIC;
ALTER TABLE `contactgroups` ROW_FORMAT=DYNAMIC;
ALTER TABLE `contactgroupmembers` ROW_FORMAT=DYNAMIC;
ALTER TABLE `identities` ROW_FORMAT=DYNAMIC;
ALTER TABLE `dictionary` ROW_FORMAT=DYNAMIC;
ALTER TABLE `searches` ROW_FORMAT=DYNAMIC;
ALTER TABLE `filestore` ROW_FORMAT=DYNAMIC;
ALTER TABLE `system` ROW_FORMAT=DYNAMIC;

ALTER TABLE `cache`
  ADD CONSTRAINT `user_id_fk_cache` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cache_index`
  ADD CONSTRAINT `user_id_fk_cache_index` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cache_thread`
  ADD CONSTRAINT `user_id_fk_cache_thread` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `cache_messages`
  ADD CONSTRAINT `user_id_fk_cache_messages` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `contactgroups`
  ADD CONSTRAINT `user_id_fk_contactgroups` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `contacts`
  ADD CONSTRAINT `user_id_fk_contacts` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `dictionary`
  ADD CONSTRAINT `user_id_fk_dictionary` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `filestore`
  ADD CONSTRAINT `user_id_fk_filestore` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `identities`
  ADD CONSTRAINT `user_id_fk_identities` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `searches`
  ADD CONSTRAINT `user_id_fk_searches` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE ON UPDATE CASCADE;
```

Is this an issue with galera? maybe. But for now, this patch solved our problem.
