### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by Almimi28230** [roundcube/roundcubemail#9145]
Hi,
I have this error in roundcubes's logs : PHP Fatal error:  Uncaught Error: Undefined constant PDO::MYSQL_ATTR_FOUND_ROWS
I can't update to the last version of roundcube 1.6.3.
Do you have an idea to fix it ?
Tkx a lot for all.

config : rdcube = 1.6.1
mariadb = 10.3.39
php =  8.2.10

**Comment by alecpl** [comment]
You need mysql and or pdo-mysql extension to PHP.

**Comment by Almimi28230** [comment]
When i do "php -m" i see modules pdo_mysql and pdo_sqlite installed.
One of them must be deleted ?

**Comment by wdsnyc** [comment]
Hi, I'm having a similar undefined constant issue as in this closed PHP fatal error case:

GET /roundcubemail - Uncaught Error: Undefined constant PDO::MYSQL_ATTR_FOUND_ROWS in /usr/share/roundcubemail/program/lib/Roundcube/db/mysql.php:129

Here is the stack trace:

Stack trace:
#0 /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php(168): rcube_db_mysql->dsn_options()
#1 /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php(154): rcube_db->conn_create()
#2 /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php(259): rcube_db->dsn_connect()
#3 /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php(450): rcube_db->db_connect()
#4 /usr/share/roundcubemail/program/lib/Roundcube/rcube_db.php(418): rcube_db->_query()
#5 /usr/share/roundcubemail/program/lib/Roundcube/session/db.php(113): rcube_db->query()
#6 [internal function]: rcube_session_db->read()
#7 /usr/share/roundcubemail/program/lib/Roundcube/rcube_session.php(141): session_start()
#8 /usr/share/roundcubemail/program/lib/Roundcube/rcube.php(495): rcube_session->start()
#9 /usr/share/roundcubemail/program/include/rcmail.php(649): rcube->session_init()
#10 /usr/share/roundcubemail/program/include/rcmail.php(118): rcmail->session_init()
#11 /usr/share/roundcubemail/program/include/rcmail.php(93): rcmail->startup()
#12 /usr/share/roundcubemail/index.php(43): rcmail::get_instance()
#13 {main}
  thrown in /usr/share/roundcubemail/program/lib/Roundcube/db/mysql.php on line 129

I'm running roundcubemail-1.6.11-2.fc43.noarch on Fedora 43

I am running the following versions of mariadb/mysql, php:

rpm -qa | egrep "mariadb|mysql|php"

mariadb-connector-c-config-3.4.5-2.fc43.noarch
mariadb-connector-c-3.4.5-2.fc43.x86_64
mariadb-common-10.11.13-9.fc43.noarch
mariadb-10.11.13-9.fc43.x86_64
mariadb-errmsg-10.11.13-9.fc43.noarch
mysql-selinux-1.0.14-2.fc43.noarch
mariadb-server-10.11.13-9.fc43.x86_64
mariadb-backup-10.11.13-9.fc43.x86_64
mariadb-cracklib-password-check-10.11.13-9.fc43.x86_64
mariadb-gssapi-server-10.11.13-9.fc43.x86_64
mariadb-server-utils-10.11.13-9.fc43.noarch
mariadb-client-utils-10.11.13-9.fc43.noarch
libtree-sitter-php-0.24.2-2.fc43.x86_64
php-common-8.4.14-1.fc43.x86_64
php-fpm-8.4.14-1.fc43.x86_64
php-pecl-zip-1.22.7-1.fc43.x86_64
php-8.4.14-1.fc43.x86_64
php-xml-8.4.14-1.fc43.x86_64
php-mbstring-8.4.14-1.fc43.x86_64
php-intl-8.4.14-1.fc43.x86_64
php-gd-8.4.14-1.fc43.x86_64
php-pdo-8.4.14-1.fc43.x86_64
php-cli-8.4.14-1.fc43.x86_64
php-opcache-8.4.14-1.fc43.x86_64
php-sodium-8.4.14-1.fc43.x86_64
php-process-8.4.14-1.fc43.x86_64
php-ldap-8.4.14-1.fc43.x86_64
php-enchant-8.4.14-1.fc43.x86_64

**Comment by alecpl** [comment]
Install php-pdo-mysql package.

**Comment by wdsnyc** [comment]
There is no package named php-pdo-mysql on Fedora 43.

**Comment by alecpl** [comment]
It may be php-mysqlnd package then.

**Comment by wdsnyc** [comment]
Ok so I installed the php-mysqlnd package. Now when I try to access the php code in my roundcubemail install location, /usr/share/roundcubemail, with the apache webserver I get these messages in the apache error_log, note the "declining URL fcgi://localhost/usr/share/roundcubemail/index.php" message.

[Fri Nov 28 12:02:41.918172 2025] [proxy:debug] [pid 8849:tid 8922] mod_proxy.c(1467): [client 127.0.0.1:58202] AH01143: Running scheme fcgi handler (attempt 0), referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918186 2025] [proxy_ajp:debug] [pid 8849:tid 8922] mod_proxy_ajp.c(788): [client 127.0.0.1:58202] AH00894: declining URL fcgi://localhost/usr/share/roundcubemail/index.php, referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918210 2025] [proxy_fcgi:debug] [pid 8849:tid 8922] mod_proxy_fcgi.c(1127): [client 127.0.0.1:58202] AH01076: url: fcgi://localhost/usr/share/roundcubemail/index.php proxyname: (null) proxyport: 0, referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918222 2025] [proxy_fcgi:debug] [pid 8849:tid 8922] mod_proxy_fcgi.c(1136): [client 127.0.0.1:58202] AH01078: serving URL fcgi://localhost/usr/share/roundcubemail/index.php, referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918254 2025] [proxy:debug] [pid 8849:tid 8922] proxy_util.c(2817): AH00942: FCGI: has acquired connection for (*:80)
[Fri Nov 28 12:02:41.918270 2025] [proxy:debug] [pid 8849:tid 8922] proxy_util.c(3261): [client 127.0.0.1:58202] AH00944: connecting fcgi://localhost/usr/share/roundcubemail/index.php to localhost:8000, referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918300 2025] [proxy:debug] [pid 8849:tid 8922] proxy_util.c(3327): [client 127.0.0.1:58202] AH02545: fcgi: has determined UDS as /run/php-fpm/www.sock (for localhost:8000), referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918316 2025] [proxy:debug] [pid 8849:tid 8922] proxy_util.c(3464): [client 127.0.0.1:58202] AH00947: connecting /usr/share/roundcubemail/index.php to /run/php-fpm/www.sock:0 (localhost:8000), referer: http://127.0.0.1/
[Fri Nov 28 12:02:41.918383 2025] [proxy:debug] [pid 8849:tid 8922] proxy_util.c(3846): AH02823: FCGI: connection established with Unix domain socket /run/php-fpm/www.sock (localhost:8000)
[Fri Nov 28 12:02:42.004877 2025] [proxy:debug] [pid 8849:tid 8922] proxy_util.c(2832): AH00943: FCGI: has released connection for (*:80)


I've tried running a local webserver using the built in php webserver in my roundcubemail location, php -S 127.0.0.1:8000, and this is all I get in the output:

root@frisco:/usr/share/roundcubemail# php -S 127.0.0.1:8000
[Fri Nov 28 11:59:09 2025] PHP 8.4.14 Development Server (http://127.0.0.1:8000) started
[Fri Nov 28 12:00:38 2025] 127.0.0.1:35816 Accepted
[Fri Nov 28 12:00:38 2025] 127.0.0.1:35816 [200]: GET /
[Fri Nov 28 12:00:38 2025] 127.0.0.1:35816 Closing
