### ISSUE TITLE
Duplicated translation for searchinterval1M and searchinterval1Y in es_ES/labels.inc

### ISSUE THREAD

**Issue by eherce** [roundcube/roundcubemail#9146]
Hi, I found out a duplicated text translation for Spanish in file program/localization/es_ES/labels.inc where two time spans have the same text in Spanish, is it possible to fix?

Lines 233 and 234 looks as follows:
$labels['searchinterval1M'] = 'más reciente que un mes';
$labels['searchinterval1Y'] = 'más reciente que un mes';

Translation for "searchinterval1Y should be "más reciente que un año", thanks in advance.
Eduardo,

**Comment by alecpl** [comment]
Fixed.

**Comment by eherce** [comment]
Thank you
