### ISSUE TITLE
Problem displaying attachments

### ISSUE THREAD

**Issue by lukaszmarcola** [roundcube/roundcubemail#9151]
I encountered a problem (bug?) in Roundcube 1.6.2 where, in a less specific situation, it does not display all attachments (only 3 out of 7), as if it did not see them at all. When downloading attachments as an archive, some are also skipped, although they are visible in the email source, after opening in Thunderbird they are all displayed correctly. The email is quite long, contains forwarded content and replies, but I can send its contents. Has anyone encountered such a issue? In Roundcube 1.6.3 the same situation, in other skins as well.

**Comment by iredmail** [comment]
I have similar issue here: Roundcube 1.6.3, email with a plain text part and an image attachment.
It shows plain text, but also shows an icon which treats plain text part as an attachment, even worse, no image attachment at all. Seems there's problem with email parser.

**Comment by alecpl** [comment]
Maybe related to #8870. I'd like to see some sample messages. You can remove image/text body, but keep the structure.

**Comment by iredmail** [comment]
Hi @alecpl 

How can i send you the sample email personally? Better give you the original raw message for easier troubleshooting.
You can contact me via email: zhb _at_ iredmail.org

**Comment by iredmail** [comment]
With permission of mail owner, here's the full email message which has the issue: https://dl.iredmail.org/modified.eml

I replaced few domain names by exampleX.com, hope it doesn't impact your troubleshooting.

**Comment by alecpl** [comment]
So, this is the same issue as in #8870. An `application/smil` message.
