### ISSUE TITLE
How to limit RC 's GUI to just Read and Reply

### ISSUE THREAD

**Issue by gomanuke** [roundcube/roundcubemail#9154]
Hi, guys!
I need to limit RC 's GUI to just Read and Reply functions. Nothing more to some types of users.
Is this possible thing?

Appreciate for ideas.

**Comment by gomanuke** [comment]
It seems to be a $config['disabled_actions'] = [];
But there are no description of and it looks as system wide, not a user specific...

**Comment by gomanuke** [comment]
I guess custom skin solves it...
./styles/styles.min.css

layout-menu,#rcmbtn108,#rcmbtn110,#messagemenulink,#toolbar-list-menu {visibility: hidden;min-width:0px;max-width:0px;width:0px}

**Comment by jdsn** [comment]
Note, that this only **hides** the actions in the webui but it does not prevents users from accessing them (might happen via unhiding with custom CSS changes on client side or maybe via stepping with the TAB key to the hidden actions and pressing enter).

**Comment by gomanuke** [comment]
You are right, no doubt. But does exist any other way? I mean per user restrictions...

**Comment by alecpl** [comment]
You can write a simple plugin that calls `rcube::get_instance->config->set('disabled_actions', $array);`.
