### ISSUE TITLE
Visualization mode

### ISSUE THREAD

**Issue by BioJairo** [roundcube/roundcubemail#9155]
Hi,

I have using Rondcube Webmal for a long time. Today I have a simple problem. I have changed, during configuration, the visualization way of the email to the last one (so simple, only white and text in general). The problem is that I cannot change back because the buttonns from the configuration menu do not work when clickin on them.

Is there any solution for that?
J

**Comment by alecpl** [comment]
I have no idea what you're talking about. Maybe some screenshot?

**Comment by BioJairo** [comment]
Attached the visualization of my email, and the options. When I click on the first about the ways of visualization, it does no open anything to change. All this buttons are like “locked”.

Jairo Robla Suárez
Research Gate<https://www.researchgate.net/profile/Jairo-Robla?ev=hdr_xprf&_tp=eyJjb250ZXh0Ijp7ImZpcnN0UGFnZSI6Il9kaXJlY3QiLCJwYWdlIjoicHJvZmlsZSIsInByZXZpb3VzUGFnZSI6ImhvbWUifX0> | Twitter<https://twitter.com/BioJairo> | Instagram<https://www.instagram.com/biologosalvaje>
Mi libro, ya disponible: «La astucia de los insectos<https://almuzaralibros.com/fichalibro.php?libro=5750&edi=6>»

Dept. Conservation Biology
Estación Biológica de Doñana (EBD-CSIC)
Avda. Américo Vespucio 26
41092, Sevilla, Spain.

De: Aleksander ***@***.***>
Enviado: viernes, 29 de septiembre de 2023 12:11
Para: ***@***.***>
CC: ***@***.***>; ***@***.***>
Asunto: Re: [roundcube/roundcubemail] Visualization mode (Issue #9155)


I have no idea what you're talking about. Maybe some screenshot?

**Comment by BioJairo** [comment]
![Error](https://github.com/roundcube/roundcubemail/assets/146463530/35f4f07b-22c2-4160-8513-9fade20589a0)

**Comment by BioJairo** [comment]
![Error](https://github.com/roundcube/roundcubemail/assets/146463530/f635d056-da5b-435d-bfc4-722adc8f05d7)

**Comment by alecpl** [comment]
Looks like something's missing. And I'm not sure even what theme or version it is. Are you an end user or an admin that installed the webmail software? I doubt I can help you.

**Comment by BioJairo** [comment]
My account is admin, but I'm an usar. It is weird because the different box options are like locked and when you click nothing is open...
________________________________

**Comment by BioJairo** [comment]
Why it is closed if it is no solved?
________________________________

**Comment by BioJairo** [comment]
Hi, I'm continue having the same problem, impossible to change the visualization. It is not solved. Do you have any recommendations for that? Because right now most of the parts are not working.
