### ISSUE TITLE
Message's way to folder "Sent"

### ISSUE THREAD

**Issue by gomanuke** [roundcube/roundcubemail#9157]
Hi, guys.

I ask for help to figure out a RC's action as MUA. 
Look, my RC configuration has two connections to MTA (exim) via 25 port and to MDA (dbmail-imapd) via 143 port
When RC sends message then it sends it to MTA via port 25. 

And is this correct understanding that it places message into folder "Sent" via port 143 (IMAP)? Or MTA should make it?

![image](https://github.com/roundcube/roundcubemail/assets/47693546/f2484c13-2566-4e68-8ec4-ae00bf29912d)

**Comment by alecpl** [comment]
Yes. This is what most clients do. Use SMTP to send the message, and then use IMAP to put the copy in the sender's mailbox.
