### ISSUE TITLE
Upgrade a multi-domain config with multiple database

### ISSUE THREAD

**Issue by lpellissier** [roundcube/roundcubemail#9158]
Hi,

I have one instance of Roundcube which serves multiple domains. So I use `$config['include_host_config']` array  to map a dedicated MariaDB database for each virtual host. So every RoundCube virtual host has its own `$config['db_dsnw']` DB declaration.
The upgrade process must modify one directory to change PHP/CSS/HTML/images files and multiple databases. But `installto.sh` doesn't read files pointed by `$config['include_host_config']` array and ignore all `$config['db_dsnw']` and doesn't find any DB to upgrade. How can I do that ?

Big thanks

**Comment by alecpl** [comment]
Why don't you use the same database for all instances?

CLI tools indeed do not handle your case properly as normally they do not have the host context.

However, I think you can do this by setting an env variable like this: `HTTP_HOST="hostname" bin/installto.sh /path/to/rc"`

**Comment by lpellissier** [comment]
Works fine when `installto.sh` is prefixed by `HTTP_HOST` env variable definition. Must be done for all virtual host to upgrade each DB.
If I use the same database for all instances, I suppose I have to define a custom table prefix `$config['db_prefix']`   for every instance ? So the upgrade problem is the same.
Thanks

**Comment by tanzirctrends** [comment]
@lpellissier hi, Have you added multiple domains in Roundcube?

**Comment by lpellissier** [comment]
> @lpellissier hi, Have you added multiple domains in Roundcube?

Yes but if Roundcube is serving domain1.com, domain2.com, domain3.com... You have to apply each Roudcube update 3 times :

```
HTTP_HOST="domain1.com" bin/installto.sh /www/roundcube"
HTTP_HOST="domain2.com" bin/installto.sh /www/roundcube"
HTTP_HOST="domain3.com" bin/installto.sh /www/roundcube"
```
As far as I know it's not documented, but it works !

**Comment by tanzirctrends** [comment]
@lpellissier Need to run just HTTP_HOST="domain2.com" bin/installto.sh /www/roundcube" in terminal?
I am not using bin/installto.sh file for domain1.com. and I am using nginx.
N.B: is /www/roundcube path roundcube direcotry?

Would you like to share share you installto.sh file

**Comment by alecpl** [comment]
@tanzirctrends I think you're missing the point of this ticket. It is about a very specific use-case and bin/installto.sh is part of Roundcube. It is not about "adding multiple domains".

**Comment by lpellissier** [comment]
@tanzirctrends You don't have to modify `install.sh`. For a multi domain Rouncube install, this is my `config.php`   with one DB per domain :

```
$config['include_host_config'] = array('domain1.org' => 'domain1-config.inc.php',
                                       'domain2.org' => 'domain2-config.inc.php',
                                       'domain3.org' => 'domain3-config.inc.php'
                               );
```

And `domain1-config.inc.php` :

```
$config['db_dsnw'] = 'mysql://roundcube_d1:passwd1@127.0.0.1/roundcube_d1';
$config['skin_logo'] = array(
  "login" => "/images/logo-domain1.png",
  "*" => "/images/logo-domain1.png",
   );
$config['mail_domain'] = 'domain1.org';
$config['product_name'] = 'Webmail domain1.org';
```

With this config, take care of upgrading Roundcube for every domain in order to update all databases. Of course all DB must be aligned with code. Files need to be upgraded only once but fortunately `install.sh` takes care of that.
