### ISSUE TITLE
non-numeric value  rcube_imap_generic.php 

### ISSUE THREAD

**Issue by lukaszmarcola** [roundcube/roundcubemail#9164]
Hello,
after updating roundcube to 1.6.3, we got many warnings as below. I checked that the rcube_imap_generic.php file was not changed. What could be the cause of the problem?  On 1.6.3 it works fine without these warnings.

`2023/10/10 10:54:48 [error] 176#176: *639661492 FastCGI sent in stderr: "PHP message: PHP Warning:  A non-numeric value encountered in program/lib/Roundcube/rcube_imap_generic.php on line 4095" while reading response header from upstream, client: 159.255.xxx.xxx, server: _, request: "POST /?_task=mail&_action=refresh HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "poczta.xxx.pl", referrer: "https://poczta.xxx.pl/?_task=mail&_mbox=INBOX"
`

**Comment by alecpl** [comment]
The warning does not make sense. 

https://github.com/roundcube/roundcubemail/blob/41756cc3331b495cc0b71886984474dc529dd31d/program/lib/Roundcube/rcube_imap_generic.php#L4095

What do you have in line 4095?

It maybe caused by some invalid/unexpected data passed to the method.

**Comment by lukaszmarcola** [comment]
Sorry, I added some minor changes and comments with timeout options, so my line 4095 refers to the compressMessageSet function:
``` php
  4070	    public static function compressMessageSet($messages, $force = false)
  4071	    {
  4072	        // given a comma delimited list of independent mid's,
  4073	        // compresses by grouping sequences together
  4074	        if (!is_array($messages)) {
  4075	            // if less than 255 bytes long, let's not bother
  4076	            if (!$force && strlen($messages) < 255) {
  4077	                return preg_match('/[^0-9:,*]/', $messages) ? 'INVALID' : $messages;
  4078	            }
  4079	
  4080	            // see if it's already been compressed
  4081	            if (strpos($messages, ':') !== false) {
  4082	                return preg_match('/[^0-9:,*]/', $messages) ? 'INVALID' : $messages;
  4083	            }
  4084	
  4085	            // separate, then sort
  4086	            $messages = explode(',', $messages);
  4087	        }
  4088	
  4089	        sort($messages);
  4090	
  4091	        $result = [];
  4092	        $start  = $prev = $messages[0];
  4093	
  4094	        foreach ($messages as $id) {
  4095	            $incr = $id - $prev;
  4096	            if ($incr > 1) { // found a gap
  4097	                if ($start == $prev) {
  4098	                    $result[] = $prev; // push single id
  4099	                }
  4100	                else {
```

**Comment by alecpl** [comment]
Something unexpected is passed to this method. The following patch could help us understand what it is. Then we could find a most proper fix. This issue indicates that the problem is likely in another place, so an exception trace might be very useful.
```diff
--- a/program/lib/Roundcube/rcube_imap_generic.php
+++ b/program/lib/Roundcube/rcube_imap_generic.php
@@ -4099,6 +4099,10 @@ class rcube_imap_generic
         $start  = $prev = $messages[0];
 
         foreach ($messages as $id) {
+            if (!is_numeric($id) || !is_numeric($prev)) {
+                rcube::console($messages, "INVALID: '{$id}' '{$prev}'");
+                throw new Exception("Invalid input");
+            }
             $incr = $id - $prev;
             if ($incr > 1) { // found a gap
                 if ($start == $prev) {

```

**Comment by alecpl** [comment]
Any feedback on this issue?

I'm suspecting that something might be passing `$messages = "*"` or `$messages = ["*"]` to this method, and we indeed would not handle that properly. But this is my assumption, and the real issue might be different.

**Comment by alecpl** [comment]
No feedback.
