### ISSUE TITLE
Duplicate Inbox folder

### ISSUE THREAD

**Issue by mattfbacon** [roundcube/roundcubemail#9166]
When the IMAP server reports the Inbox folder without using all-caps ("INBOX"), Roundcube shows Inbox twice. Note that the IMAP spec says that it has to be handled case-insensitively, as explained here: https://github.com/mjl-/mox/issues/80#issuecomment-1759489304

> For reference, INBOX being case-insensitive has been the case forever. See the mailbox ABNF syntax at the very old https://datatracker.ietf.org/doc/html/rfc1730#page-58
>
> ```
>    mailbox         ::= "INBOX" / astring
>                        ;; INBOX is case-insensitive; other names may be
>                        ;; case-sensitive depending on implementation.
> ```
> 
> And the more recent https://datatracker.ietf.org/doc/html/rfc9051#name-formal-syntax
> 
> ```
> mailbox         = "INBOX" / astring
>                     ; INBOX is case insensitive.  All case variants
>                     ; of INBOX (e.g., "iNbOx") MUST be interpreted as
>                     ; INBOX, not as an astring.  An astring that
>                     ; consists of the case-insensitive sequence
>                     ; "I" "N" "B" "O" "X" is considered
>                     ; to be an INBOX and not an astring.
>                     ; Refer to Section 5.1 for further
>                     ; semantic details of mailbox names.
> ```

In my testing, Dovecot reports INBOX in all caps and Roundcube shows Inbox once, but https://github.com/mjl-/mox reports it as Inbox and Roundcube shows it twice. Please implement case-insensitivity.

**Comment by alecpl** [comment]
This fix might be incomplete and probably there's a better place to do this (e.g. in rcube_imap_generic), but you can try it.
```diff
--- a/program/lib/Roundcube/rcube_imap.php
+++ b/program/lib/Roundcube/rcube_imap.php
@@ -2922,7 +2922,7 @@ class rcube_imap extends rcube_storage
 
         // INBOX should always be available
         if (in_array_nocase($root . $name, ['*', '%', 'INBOX', 'INBOX*'])
-            && (!$filter || $filter == 'mail') && !in_array('INBOX', $a_mboxes)
+            && (!$filter || $filter == 'mail') && !in_array_nocase('INBOX', $a_mboxes)
         ) {
             array_unshift($a_mboxes, 'INBOX');
         }
@@ -3054,7 +3054,7 @@ class rcube_imap extends rcube_storage
 
         // INBOX should always be available
         if (in_array_nocase($root . $name, ['*', '%', 'INBOX', 'INBOX*'])
-            && (!$filter || $filter == 'mail') && !in_array('INBOX', $a_mboxes)
+            && (!$filter || $filter == 'mail') && !in_array_nocase('INBOX', $a_mboxes)
         ) {
             array_unshift($a_mboxes, 'INBOX');
         }

```

**Comment by mattfbacon** [comment]
Just a quick case-sensitive search for "INBOX" in the codebase, excluding various irrelevant files, yields 66 matches. So while this patch you sent is a good start, I think this is going to require a deeper investigation to re-evaluate the "always uppercase" assumption.

**Comment by alecpl** [comment]
I was thinking about something like this:
```diff
--- a/program/lib/Roundcube/rcube_imap_generic.php
+++ b/program/lib/Roundcube/rcube_imap_generic.php
@@ -1658,6 +1658,18 @@ class rcube_imap_generic
                         $mailbox = rtrim($mailbox, $delim);
                     }
 
+                    // Make it easier for the client to deal with INBOX folder
+                    // by always returning the word with all capital letters
+                    if (strlen($mailbox) == 5
+                        && ($mailbox[0] == 'i' || $mailbox[0] == 'I')
+                        && ($mailbox[1] == 'n' || $mailbox[1] == 'N')
+                        && ($mailbox[2] == 'b' || $mailbox[2] == 'B')
+                        && ($mailbox[3] == 'o' || $mailbox[3] == 'O')
+                        && ($mailbox[4] == 'x' || $mailbox[4] == 'X')
+                    ) {
+                        $mailbox = 'INBOX';
+                    }
+
                     // Add to result array
                     if (!$lstatus) {
                         $folders[] = $mailbox;

```

**Comment by mattfbacon** [comment]
Ok.

**Comment by alecpl** [comment]
The last patch has been merged.
