### ISSUE TITLE
Roundcube does not properly honor `request_path` when logging in

### ISSUE THREAD

**Issue by sohmc** [roundcube/roundcubemail#9167]
This seems to be a continuation of #8738 #8170 

I host roundcube on `/roundcube/` and have configured it with my URL path as noted in the default configs:

```
$config['request_path'] = '/roundcube';
```

However, when I attempt to login, the login url attempts to `POST` to `/` instead of `/roundcube/`.

It's been some time since I've programmed in php but it _seems_ like the `action` parameter in the login form is not taking `$config['request_path']` into account and always using '/'.

On my browser, the `form` tag returns:

```
<form id="login-form" name="login-form" method="post" class="propform" action="/?_task=login" data-form-type="login">
```

I did my best to go through the source code, going as far as to find the function [`login_form`](https://github.com/roundcube/roundcubemail/blob/d08d1678847c93315d3f0883725deb0c37c2f7df/program/include/rcmail_output_html.php#L2316) but then got completely lost in the `form_tag` function and how the `action` parameter gets created.

In case it matters, my nginx config is as follows:

```
    location /roundcube/ {
        rewrite         /roundcube/(.*) /$1 break;
        proxy_pass      http://roundcube;
        proxy_set_header X-Forwarded-Path "/roundcube";
    }
```

As you can see, I also tried setting `request_path` to `HTTP_X_FORWARDED_PATH` along with `proxy_whitelist` to no avail.

Relevant bits:
- Running Roundcube 1.6.3 via docker image roundcube/roundcubemail:latest
- nginx via docker image nginx:latest-alpine

Thanks!

**Comment by sohmc** [comment]
I was able to fix my own issue.

The latest version of [roundcubemail-docker](https://github.com/roundcube/roundcubemail-docker/) offers a new environment variable: `ROUNDCUBEMAIL_REQUEST_PATH`.  Setting this to the appropriate value brings the behavior as expected.

Closing this issue.

**Comment by hp8wvvvgnj6asjm7** [comment]
> I was able to fix my own issue.
> 
> The latest version of [roundcubemail-docker](https://github.com/roundcube/roundcubemail-docker/) offers a new environment variable: `ROUNDCUBEMAIL_REQUEST_PATH`. Setting this to the appropriate value brings the behavior as expected.
> 
> Closing this issue.

could u post your solution?
