### ISSUE TITLE
Issue with EML attachment's MIME boundary end of section

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#9170]
Sometimes I download EMLs with Roundcube and then forward them with Thunderbird, and recently I started noticing that all of the attachments are corrupt **after** being forwarded by Thunderbird. At first I thought that the issue is with the client (Thundebird) that forwards the EML and not with the one that generates the original (and seemingly working) EML (Roundcube); after a few tests I believe Roundcube to be the problem, but I have no idea why that is the case.

The title may be confusing and my description as well, so I have attached a sample EML of the same e-mail using different clients to export it, and Roundcube is the only client that generates a different output, at the end of the attachment's base64 stream. Sometimes the MIME boundary is incomplete (like in this example), other times the MIME boundary is completely absent.

In this instance, just after the attachment's base64 encoding, **Roundcube** terminates the EML with incomplete MIME boundary:
`--=_3da87`
...while **Thunderbird** terminates the same EML with full MIME boundary:
`--=_3da87ec93ae9b96b61b033912d98b566--`

**Samples:**

- [test mail subject_roundcube.eml.txt](https://github.com/roundcube/roundcubemail/files/12915659/test.mail.subject_roundcube.eml.txt)

- [test mail subject_thunderbird.eml.txt](https://github.com/roundcube/roundcubemail/files/12915658/test.mail.subject_thunderbird.eml.txt)

- [test mail subject_snappymail.eml.txt](https://github.com/roundcube/roundcubemail/files/12915656/test.mail.subject_snappymail.eml.txt)

- [test mail subject_rainloop.eml.txt](https://github.com/roundcube/roundcubemail/files/12915657/test.mail.subject_rainloop.eml.txt)

**Comment by alecpl** [comment]
What version?

**Comment by ner00** [comment]
v1.6.3 - sorry. 

It's possible that v1.6.2 had this issue too but I didn't really pay attention at the time, unsure though.

**Comment by alecpl** [comment]
I'm unable to reproduce. I doubt it's Roundcube's fault. If you enable imap_debug in Roundcube config you can see what exactly is being sent from the IMAP server to Roundcube.

**Comment by alecpl** [comment]
The log does not explain it , you can't see if it's truncated because of a line length limit for debug.

The problem might be also in the http server layer or php itself.

**Comment by ner00** [comment]
There is a peculiarity about this, if I forward the message that I want to download as an attachment and then download it from inside the draft, the resulting EML is perfect. What could explain this different behavior from the mail list export/download functionality and the draft one?

**Comment by alecpl** [comment]
In one case you are getting the content "directly" from imap, in the other from a temp file.

**Comment by alecpl** [comment]
Looking again at the imap log you can find `RFC822.SIZE 250482` in the server response to `BODYSTRUCTURE` request.

**Comment by ner00** [comment]
Ok, the mail server seem to be at fault.

Thanks for helping along with this.

**Comment by ner00** [comment]
@alecpl quick question, what issues can I expect by removing the line below?
https://github.com/roundcube/roundcubemail/blob/54fa8222cfc1fd3469fe4a5065fc492135503536/program/lib/Roundcube/rcube_output.php#L258

**Comment by alecpl** [comment]
The browser not showing proper progress for download operations.

**Comment by KrinalPatel889** [comment]
@ner00 could you please visit reboot pro pepasspass thread. Sorry, I couldn't find any other way to reach you. :(
