### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#9171]
A specific e-mail message is giving an error instead of the message preview; I get the following error:
>**Oops... something went wrong!**
An internal error has occurred. Your request cannot be processed at this time.
_For administrators: Please check the application and/or server error logs for more information._

The **errors.log** shows the following:
```
[16-Oct-2023 19:01:50 Europe/London] PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in C:\xampp\htdocs\roundcubemail-1.6.4\program\lib\Roundcube\rcube_imap.php:2168
Stack trace:
#0 C:\xampp\htdocs\roundcubemail-1.6.4\program\lib\Roundcube\rcube_imap.php(2168): strtolower(Array)
#1 C:\xampp\htdocs\roundcubemail-1.6.4\program\lib\Roundcube\rcube_imap.php(2112): rcube_imap->structure_part(Array, 2, '0', NULL)
#2 C:\xampp\htdocs\roundcubemail-1.6.4\program\lib\Roundcube\rcube_imap.php(2008): rcube_imap->structure_part(Array, 2, '', Object(rcube_message_header))
#3 C:\xampp\htdocs\roundcubemail-1.6.4\program\lib\Roundcube\rcube_message.php(106): rcube_imap->get_message('5')
#4 C:\xampp\htdocs\roundcubemail-1.6.4\program\actions\mail\show.php(63): rcube_message->__construct('5', 'INBOX', false)
#5 C:\xampp\htdocs\roundcubemail-1.6.4\program\include\rcmail.php(282): rcmail_action_mail_show->run(Array)
#6 C:\xampp\htdocs\roundcubemail-1.6.4\index.php(278): rcmail->action_handler()
#7 {main}
  thrown in C:\xampp\htdocs\roundcubemail-1.6.4\program\lib\Roundcube\rcube_imap.php on line 2168
```

I suppose the issue is with the e-mail message itself or client that sent it, but I had mixed results viewing this e-mail and attachment in other clients: worked in Thunderbird and Rainloop, failed in Roundcube and SnappyMail.

Attached is a sample of the e-mail in question:  [Unrendered e-mail.eml.txt](https://github.com/roundcube/roundcubemail/files/12920415/Unrendered.e-mail.eml.txt)

**Comment by alecpl** [comment]
I'm unable to reproduce. Could you enable imap_debug and provide the content of `BODYSTRUCTURE` response for this message?

**Comment by ner00** [comment]
```
BODYSTRUCTURE (("TEXT" "HTML" ("CHARSET" "windows-1252") NIL NIL "quoted-printable" 227 10)("PDF; NAME="PDF 90192 20231016.PDF"" "PDF" ("NAME" "PDF 90192 20231016.pdf") NIL NIL "base64" 249564 NIL ("attachment" ("FILENAME" "PDF 90192 20231016.pdf"))) "MIXED" ("BOUNDARY" "bwxmRjyvLWUK=_NSzLnnwrcYm67OmryBDv") NIL NIL)
```

**Comment by alecpl** [comment]
The attachment part has an invalid header `Content-Type: pdf;`. And your IMAP server produces invalid body structure for this message part. My server handles that better, it also does not produce proper type/subtype fields, it uses instead text/plain, but it does produce a valid body structure.

Of course, our code should not throw errors in such cases, so this is something to fix.

That being said, making sense of such an invalid body structure is another story and I don't plan to work on this.

**Comment by alecpl** [comment]
Fixed.
