### ISSUE TITLE
exceptions on config.inc.php

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9173]
I had in 1.4(?) in the config.inc.php a little if statement for some accounts to redirected to a different imap/smtp ip. This is not working any more in 1.6. Where can I put such exceptions best?

**Comment by alecpl** [comment]
What exactly is not working?

**Comment by f1-outsourcing** [comment]
I had something like this

`if (in_array('%u', $sn)) { $config['smtp_host'] = );`

code like this is outputting

`rcube::write_log('errors', '>>> yeah');`

so I guess I only need to have the variable that contains the log in userid

**Comment by f1-outsourcing** [comment]
I assume this string %u substitution is done now at a later time. What/where should I change this hosts for a specific user?
