### ISSUE TITLE
Managesieve: filter rules missing "Subject, From, To"

### ISSUE THREAD

**Issue by bronkoo** [roundcube/roundcubemail#9175]
Hi,
on a fresh 1.6.3 installation it is not possible to select the Rules criteria "Subject, From, To"  because they are missing (should be above three dots) in drop down list:

![Screenshot from 2023-10-19 23-12-43](https://github.com/roundcube/roundcubemail/assets/36919549/e57ef89a-96bf-4b68-905b-799971ebb343)

Upgrade to 1.6.4 didn't solved this behavior.

Any confirmation or hints for me?

**Comment by alecpl** [comment]
It uses `$config['managesieve_default_headers'] = ['Subject', 'From', 'To'];` by default. So, did you change this option?

I can reproduce this with these obviously invalid values:
```
$config['managesieve_default_headers'] = [''];
// or 
$config['managesieve_default_headers'] = '';
```

I suppose we need to add some code making sure such values do no break the selector. Is this your case?

**Comment by bronkoo** [comment]
You are right, external installation script ([iRedMail](https://forum.iredmail.org/topic20105-roundcube-managesieve-filter-rules-missing-subject-from-to.html)) changed default setting...

Thanks a lot!

**Comment by alecpl** [comment]
Fixed.
