### ISSUE TITLE
attachments cover entire screen android

### ISSUE THREAD

**Issue by justin1100** [roundcube/roundcubemail#9178]
When attempting to access roundcube on any firefox or chrome browser on any android telephone, the attachments box covers the entire composure window. It is impossible to write a new message.

@
![Screenshot_2023-10-22-23-01-33](https://github.com/roundcube/roundcubemail/assets/148691472/9b67d338-aff0-4197-a4b8-16a0f5e6a4ef)

**Comment by alecpl** [comment]
Firs of all this old skin wasn't invented for mobile devices. Second, what version and plugins? Finally, it looks like there might be a javascript error, could you check the browser console?

**Comment by justin1100** [comment]
It is the default skin when logging in.
Version of what? the browser? What ever the latest version of the browser
from the google store is.
I cannot check a browser console.

**Comment by alecpl** [comment]
Version of Roundcube? Are you an end user or an admin? If you're an end user we can't help you.

**Comment by justin1100** [comment]
End user.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
