### ISSUE TITLE
RC 1.4.15 version

### ISSUE THREAD

**Issue by alaunay** [roundcube/roundcubemail#9180]
Hello,

This isn't worth an issue, but I don't know where to report it elsewhere... You forgot to bump the release number to 1.4.15 when you released it, it still prints 1.4.14.

**Comment by nradchenko** [comment]
Hit this issue after upgrade too, 1.4.14 is still displayed in "About" dialog.

**Comment by alecpl** [comment]
I made all version identifiers in git to be 1.4-git in this branch. Also, we stopped supporting 1.4 recently, and no more releases is planned for that line.

**Comment by alaunay** [comment]
I understand that 1.4 is out, but there's still a 1.4.15 tag:
https://github.com/roundcube/roundcubemail/releases/tag/1.4.15

Oh well.
