### ISSUE TITLE
THreaded view greyed out

### ISSUE THREAD

**Issue by sergedroz** [roundcube/roundcubemail#9182]
The two icons for list or threaded view are greyed out, and although clickable seem to have no effect. Mails are not displayed as threads. This is independent of the skin and affects both 1.6.4 and 1.5.5. The imap server supports THREADS and shows this *using capabilitz( to authenticated users. 

![Screenshot 2023-10-24 081906](https://github.com/roundcube/roundcubemail/assets/12233053/4022f19d-2f28-4adb-a5c1-25454018b4f9)

**Comment by alecpl** [comment]
Are you using imap proxy? Enable imap_debug and provide the log (starting when user logs in).

**Comment by sergedroz** [comment]
Hi Alex

Yes, so it seems capapilities are only checked once before login, but dovecot give the full set only after login. 


Oct 24 21:35:46 phoenix in.imapproxyd[1053]: ParseBannerAndCapability: Attempting to parse capability string: * OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN] Dovecot ready.
Oct 24 21:35:46 phoenix in.imapproxyd[1053]: ParseBannerAndCapability: Attempting to parse capability string: * CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE STARTTLS AUTH=PLAIN#015#0121 OK Pre-logi
n capabilities listed, post-login capabilities have more.
Oct 24 21:35:46 phoenix in.imapproxyd[1053]: main(): Binding to tcp 127.0.0.1:243
Oct 24 21:35:46 phoenix in.imapproxyd[1053]: main(): Using global statistics file '/var/run/pimpstats'
Oct 24 21:35:46 phoenix in.imapproxyd[1053]: Daemonize(): Configured to run in background mode.
Oct 24 21:35:46 phoenix in.imapproxyd[1057]: BecomeNonRoot(): Process will run as uid 99 (nobody) and gid 99 (nobody).
Oct 24 21:35:46 phoenix in.imapproxyd[1057]: BecomeNonRoot(): enabled no_new_privs
Oct 24 21:35:46 phoenix in.imapproxyd[1057]: main(): Launched ICC recycle thread with id 139917304022784
Oct 24 21:35:46 phoenix in.imapproxyd[1057]: main(): squirrelmail-imap_proxy version 1.2.8 [SVN] normal server startup.
Oct 24 21:36:13 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38282) no previous connection: creating a new one
Oct 24 21:36:13 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38282) on new sd [10]
Oct 24 21:36:13 phoenix in.imapproxyd[1057]: LOGOUT: '"user@example.com"' from server sd [10]
Oct 24 21:36:33 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38308) on existing sd [10]
Oct 24 21:36:33 phoenix in.imapproxyd[1057]: LOGOUT: '"user@example.com"' from server sd [10]
Oct 24 21:36:33 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38312) on existing sd [10]
Oct 24 21:36:33 phoenix in.imapproxyd[1057]: LOGOUT: '"user@example.com"' from server sd [10]
Oct 24 21:36:34 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38316) on existing sd [10]
Oct 24 21:36:34 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38320) no previous connection: creating a new one
Oct 24 21:36:34 phoenix in.imapproxyd[1057]: LOGIN: '"user@example.com"' (127.0.0.1:38320) on new sd [12]
Oct 24 21:36:34 phoenix in.imapproxyd[1057]: LOGOUT: '"user@example.com"' from server sd [12]

**Comment by alecpl** [comment]
We have a solution for proxies.
```
// By default IMAP capabilities are read after connection to IMAP server
// In some cases, e.g. when using IMAP proxy, there's a need to refresh the list
// after login. Set to True if you've got this case.
$config['imap_force_caps'] = false;
```
