### ISSUE TITLE
String replacement error in utils/error.php

### ISSUE THREAD

**Issue by rivimey** [roundcube/roundcubemail#9185]
The code at the end of program/actions/utils/error.php attempts to interpolate $skin in a string, but does so in a single-quoted string, so it fails. The correct definition is:

```
program/actions/utils/error.php:137:
            . '<link rel="stylesheet" type="text/css" href="skins/' . $skin . '/common.css" />'
```

**Comment by alecpl** [comment]
Hmmm... this code does not make a lot of sense as it assumes that common.css exists in all skins, which is not true. I'll investigate whether it makes sense to just remove this line.

**Comment by alecpl** [comment]
Fixed.
