### ISSUE TITLE
Official plugin newmail_notifier is not working

### ISSUE THREAD

**Issue by notprogrammer** [roundcube/roundcubemail#9195]
Hello, we have enabled the newmail_notifier plugin, and in the mailboxview settings I will enable browser, desktop and sound notification.

Roundcube is container instance.

When I click test for each option, only the audio test works.

We have enabled browser permissions. tested on chrome and firefox.

It does not signal any notification when an incoming message is received. Sound working perfect but nofication is not working.

I think the plugin is not working.

Please advise what I am doing wrong? 
![2023-10-27 16_40_42-MyDreams innovations s r o  Webmail __ Preferences](https://github.com/roundcube/roundcubemail/assets/21248300/a5b944d0-ea97-4ca8-aa44-1132ab59add8)

**Comment by alecpl** [comment]
All three types of notification work for me. What Roundcube version? Anything in the browser console?

"Browser notifications" is supposed to change the favicon. Does it not happen when testing?

**Comment by notprogrammer** [comment]
I already figured it out, I had "do not disturb" mode in Windows. I am sorry. Thanks for confirming the functionality.
