### ISSUE TITLE
Page jump list opens then closes immediately

### ISSUE THREAD

**Issue by andycouzens** [roundcube/roundcubemail#9196]
When first clicking in the page input control the popover appears then disappears immediately. Clicking a second time once it already has focus works as expected.

First noticed on 1.6.2 but this is still happening on 1.6.4, we're using the elastic skin.

Thanks,
Andy

**Comment by alecpl** [comment]
I'm unable to reproduce. What browser? Are you using any plugins?

**Comment by andycouzens** [comment]
Yes we're using the following plugins, some of which are custom pkugins.

    'managesieve',
    'shared_mbx_v2',
    'new_user_identity',
    'acl',
    'check_recipients',
    'tkn_auth',
    'idlelogoutv2',
    'messagesize',
    'contextmenu',
    'chpass',
    'reconnect'

When I encountered the issue I looked to see if there were any CSS conflicts i.e. CSS from our custom plugins maybe conflicting with the skin css etc. I couldn't spot anything (we've had conflicts previously that we resolved within our plugins) I appreciate that rc+ is not a vanilla skinned roundcube, but the issue also happened on their demo site, so it appeared it wasn't an issue specific to us and could possibly be an issue in roundcube.

I will try and turn off all plugins to eliminate them. Is there a demo site for roundcube that is just the vanilla skin that I can try and replicate on?

**Comment by andycouzens** [comment]
Just wondering if there was any further info on this? 

I've replicated using the official 1.6.5 docker image with no plugins configured, so it's definitely an issue with roundcube.

**Comment by alecpl** [comment]
I confirm the issue in Firefox and Chrome using git-master.

**Comment by alecpl** [comment]
Fixed.
