### ISSUE TITLE
Enabling a sticky "Details" button in config file, by the default?

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9197]
When viewing/reading an email, by the default, Roundcube shows only the;

"From XX <x@senderaddress.tld> on 28-10-2023 21:38" part.

However, clicking on the envelope icon; "Details", shows the "To:" as well. This is useful sometimes, to see the **CC**, **To**, as well as the original aliases the email was intended to be sent to.

Is there any way to set it as default?

![here](https://i.ibb.co/X8R13JC/header-default.png)

Thanks in advance! Much Regards.

**Comment by alecpl** [comment]
No, but the state is being saved in the browser storage. At least in master version. So, this should be enough.
