### ISSUE TITLE
Roundcube year in credits

### ISSUE THREAD

**Issue by mvldebian** [roundcube/roundcubemail#9199]
Roundcube Webmail 1.6.4
Copyright © 2005-2022, The Roundcube Dev Team

Pls update year

**Comment by alecpl** [comment]
It's updated in master, we usually do not update release branches.

**Comment by 4jNsY6fCVqZv** [comment]
> It's updated in master, we usually do not update release branches.

What exactly does this mean? In the web interface of version 1.6.10. the copyright still shows 2022.

**Comment by alecpl** [comment]
There's no need to update the year in something that is in "maintenance" mode. It will be updated in next major version.

**Comment by 4jNsY6fCVqZv** [comment]
for reference: https://github.com/roundcube/roundcubemail/commit/3cff118366272e47dca99b576b039a67bf638167
