### ISSUE TITLE
Elastic theme issues - reported by Chrome

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9202]
Using Roundcube 1.6.4 here with default 'Elastic' theme.

The developer mode - console page of Chrome reports the following warnings for that theme;

![1](https://i.ibb.co/PNSDNdj/rcube-report.png)

and

![2](https://i.ibb.co/4sKbCLV/rcube-report2.png)

Regards.

**Comment by alecpl** [comment]
This is just a recommendation. Do you have any issues with that missing property? The later case looks like not part of Roundcube core.
