### ISSUE TITLE
1.4.x - Patch needed

### ISSUE THREAD

**Issue by clusterx** [roundcube/roundcubemail#9205]
I recently updated many 1.4.14 RC installations (it took me 5 days) and now a security issue has appeared again after a few days of use v 1.4.15.
At the moment I am unable to update to v 1.5.x w/ these systems (like many others probably) due to system requirements, so it would only be fair to provide at least a security patch for the 1.4.15 users.

**Comment by alecpl** [comment]
1. We stopped supporting 1.4 recently.
2. Backporting to 1.4 is problematic for many reasons.
3. We do not have any CI for that branch.

I backported the fix in bf599fe1cfbb9a6 let me know if there are any issues.

**Comment by alecpl** [comment]
1.4.16 has been tagged. No official package is planned.
