### ISSUE TITLE
Connection error in HTML reply

### ISSUE THREAD

**Issue by omowomo** [roundcube/roundcubemail#9207]
Hello,

Some emails gives an connection error when replyin it. I looked at the HTML code of the email and in the HTML code is this:

```
`<style><!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:inherit;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;
	mso-ligatures:standardcontextual;
	mso-fareast-language:EN-US;}
span.E-mailStijl17
	{mso-style-type:personal-compose;
	font-family:"Calibri",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri",sans-serif;
	mso-fareast-language:EN-US;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}
--></style>

```
and then click on Reply > Send, I got the error: Connection error (Failed to reach the server).
Settings in Roundcube: Preferences > Composing Messages > Compose HTML messages: always

When I **reply** in plain text I don't got the error an't can't send it.
When I **forward** the message, the message is send without any error and it is delivered.

When I choose reply and then click on the button Code I see this:
```
<style type="text/css">@font-face
	{ font-family: "Cambria Math"; }
@font-face
	{ font-family: Calibri; }
@font-face
	{ font-family: inherit; }

#replybody1 p.v1MsoNormal, #replybody1 li.v1MsoNormal, #replybody1 div.v1MsoNormal
	{ margin: 0cm; font-size: 11.0pt; font-family: "Calibri",sans-serif; mso-ligatures: standardcontextual; mso-fareast-language: EN-US; }
#replybody1 span.v1E-mailStijl17
	{ mso-style-type: personal-compose; font-family: "Calibri",sans-serif; color: windowtext; }
#replybody1 .v1MsoChpDefault
	{ mso-style-type: export-only; font-family: "Calibri",sans-serif; mso-fareast-language: EN-US; }
@page WordSection1
	{ size: 612.0pt 792.0pt; margin: 70.85pt 70.85pt 70.85pt 70.85pt; }
#replybody1 div.v1WordSection1
	{ }</style>
```

When removing that code I can reply the message without any error.

**Comment by alecpl** [comment]
Check your server logs. I suspect some security software interfering. Without knowing what the error is we can't do much.

**Comment by omowomo** [comment]
It gives a conflict wit Mod_Security:

Access denied with code 403 (phase 2). Pattern match "image\\/svg\\+xml|text\\/(?:css|html|(?:x-)?(?:(?:ecma|java|vb)script|scriptlet)).|.application\\/x-shockwave-flash" at ARGS_POST:_message. [file "/usr/local/cwaf/rules/07_XSS_XSS.conf"] [line "69"] [id "212740"] [rev "6"] [msg "COMODO WAF: XSS Attack Detected||domain.xx|F|2"] [data "Matched Data: text/css\x22 found within ARGS_POST:_message: <styletype=\x22text/css\x22>@font-face{font-family:\x22cambriamath\x22;}@font-face{font-family:calibri;}@font-face{font-family:inherit;}"] [severity "CRITICAL"] [tag "CWAF"] [tag "XSS"]

I disabled rule 212740 in Mod_Security and the error is gone.

Thanks for the suggestion.
