### ISSUE TITLE
dovecot plugin fts_solr indexation failed

### ISSUE THREAD

**Issue by PascalJugla** [roundcube/roundcubemail#9212]
I'm posting this message to ask for help with dovecot and the fts and solr plugins. After a space problem on our mail server, I had to restart the postfix and dovecot services. Since then we no longer have indexing and search on our mailboxes. I tried to restart the various services involved without further success. Moreover, it is TOTALLY IMPOSSIBLE TO HAVE DIRECT HELP FROM ROUNCUBE!!! No way to find a direct link to request technical help!

**Comment by alecpl** [comment]
This is out of scope on this bugtracker.
