### ISSUE TITLE
The login is invalid

### ISSUE THREAD

**Issue by adeidowu** [roundcube/roundcubemail#9214]
We are getting the red box errors on sign-in page: 'The login is invalid' for multiple accounts.
![login-error](https://github.com/roundcube/roundcubemail/assets/40694735/c6c9cc9c-8bcd-496d-80b1-812e9aac112c)

**Comment by bodeme** [comment]
Have you checked the error message on your mailserver and/or the logs created by Roundcube? Does not seems to be a roundcube error, more likely a configuration issue.

Check your ```config.php```, activate logging, try again to login, check logs...

```
$config['debug_level'] = 4;
$config['imap_debug'] = true;
```

**Comment by adeidowu** [comment]
The issue is only being resolved when the password is changed. After a day or two, it goes back to invalid

**Comment by adeidowu** [comment]
This could be related to cPanel IP Address-based Protection. But i need someone to walk me through the step by step to correct this as i dont have many options under Tools > Security.

**Comment by alecpl** [comment]
"The login is invalid" does not come from Roundcube, so it might be cPanel plugin or something. We can't really help you.
