### ISSUE TITLE
Threads messages grouping

### ISSUE THREAD

**Issue by adminmowi** [roundcube/roundcubemail#9218]
Hi,

e-mails in threads view are only being grouped by a title of messages not by an IDs. 

In case of different messages with the same title those are grouped as a one thread where they are not supposed to.

**Comment by alecpl** [comment]
The grouping by thread is done according to IMAP standard by the IMAP server. You can see what's going on using imap_debug option. So, we'll need a proof this isn't an imap server bug, i.e. the debug log.

**Comment by miqp** [comment]
Hi. 
I have the same problem. Here are imap log, and screenshot, three different sender grouped in one thread - only subject is the same.
![obraz](https://github.com/roundcube/roundcubemail/assets/138004622/383568e2-73e9-41cc-a952-c8a1e571fd06)
[log.txt](https://github.com/roundcube/roundcubemail/files/13726285/log.txt)
