### ISSUE TITLE
More visible indicator of unread message in thread

### ISSUE THREAD

**Issue by testman42** [roundcube/roundcubemail#9224]
This is how thing look like right now:
![Screenshot_2023-11-22_11-24-44](https://github.com/roundcube/roundcubemail/assets/2620967/852f06be-305b-4bd1-aaef-b8a31d06ccd6)
Roundcube 1.6.0 (from YUNOHost)
Excuse my Inspect Element.
The only difference between the two is that a small dot in front of the topic name changes.
Would it not make sense to make the collapsed thread with unread message display in the same format as a normal unread message?
![Screenshot_2023-11-22_11-31-35](https://github.com/roundcube/roundcubemail/assets/2620967/dce97c1b-2120-4b25-b69e-dbda99aa1643)
Hunting down threads with unread messages is currently quite annoying.

I checked other issues, and closes that I could find was an old *closed* issue, so I'm not sure if it's about the same thing.
#2817

**Comment by alecpl** [comment]
It's not only the icon, but also underline on the subject. Thunderbird for example does the same.
