### ISSUE TITLE
Attachment disappears when forwarding mail

### ISSUE THREAD

**Issue by ssodk** [roundcube/roundcubemail#9225]
In some cases the attached file disappears when manually forwarding a mail.

- When displaying the initial mail, everything is good and Roundcube shows the attachment as expected.
- When "Forward" is clicked, and the "Compose" window is opened, there are no attachments.

Roundcube version: 1.6.5
PHP version: 8.0 (EL9)

Reproducer mail:
[testmail.txt](https://github.com/roundcube/roundcubemail/files/13450701/testmail.txt)

If the "Content-Type: text/html" section (lines 47-52) is removed then it works.

**Comment by alecpl** [comment]
Duplicate of #8650.
