### ISSUE TITLE
authentication failed on Imap and smtp on installer test config

### ISSUE THREAD

**Issue by FreakingG0d** [roundcube/roundcubemail#9226]
as title said I'm not sure what happened 

![image](https://github.com/roundcube/roundcubemail/assets/72702691/0ffdfd15-3a40-4478-838a-ab4a0d8f0e83)
![image](https://github.com/roundcube/roundcubemail/assets/72702691/1600d32b-e2b4-4f56-9d46-345f45320ee7)
![image](https://github.com/roundcube/roundcubemail/assets/72702691/f67c0bf4-5a24-4446-ac87-85e55287a306)
-$config['auto_create_user'] = false;    #i've created user and table
[file.zip](https://github.com/roundcube/roundcubemail/files/13466084/file.zip)
if more file is need i will paste it 
i have no idea what going on and just start on this pls be patient with me

**Comment by alecpl** [comment]
Configuration issue. Ask on Roundcube forum.
