### ISSUE TITLE
Open source email pioneer Roundcube joins the Nextcloud family

### ISSUE THREAD

**Issue by Neustradamus** [roundcube/roundcubemail#9230]
Open source email pioneer Roundcube joins the Nextcloud family:
- https://nextcloud.com/blog/open-source-email-pioneer-roundcube-comes-aboard-nextcloud/
- https://nextcloud.com/blog/roundcubes-future-at-nextcloud-an-interview-with-the-founders/

**Comment by alecpl** [comment]
Why did you post it here? Do you expect an answer or help with anything?

**Comment by Neustradamus** [comment]
@alecpl: It is to inform people because Mailing Lists are dead, there is no possibility to communicate with people except here.

Linked to:
- https://github.com/roundcube/roundcubemail/issues/9184

**Comment by alecpl** [comment]
There is https://www.roundcubeforum.net We're working on bringing lists back.

**Comment by thomascube** [comment]
A post on roundcube.net is on the way...
