### ISSUE TITLE
PHP warning on modcss.php - PHP 8.1.x

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9235]
Hello there.

Just wanted to inform about it here; getting the following interesting PHP warning with Roundcube 1.6.5 on PHP 8.1.24:

`[23-Nov-2023 16:24:56 America/New_York] PHP Warning:  Undefined array key "tmp-e3b18d74ec658f8c51320341f3aff38b.css" in /roundcube/program/actions/utils/modcss.php on line 32`

Regards.

**Comment by alecpl** [comment]
Fixed.
