### ISSUE TITLE
installto.sh - uneeded "php" on line 143

### ISSUE THREAD

**Issue by jezcaudle** [roundcube/roundcubemail#9237]
Line 143 of installto.sh:

system("cd` $target_dir && php bin/update.sh --version=$oldversion" . ($accept ? ' -y' : ''));`

I have multiple versions of PHP installed: 8.1, 8.2 and 8.3

If I run php8.1bin/installto.sh /path/ it will fail because it tries to use the default version of php, in my case 8.3

If I remove the "php" from line 143, then it will work.

**Comment by alecpl** [comment]
Fixed.
