### ISSUE TITLE
 PHP Warning:  Undefined array key on line 68

### ISSUE THREAD

**Issue by STR07** [roundcube/roundcubemail#9238]
We get the following PHP warnings with Roundcube 1.6.5 using PHP 8.1.26 and wanted to inform you about this.
We sadly don't know what triggers these warnings:

 PHP Warning:  Undefined array key "port" in /var/www/html/webmail/program/actions/mail/attachment_upload.php on line 68

Thank you very much in advance.

**Comment by alecpl** [comment]
Fixed.
