### ISSUE TITLE
use_secure_urls leads to 404 after clicking on CSRF message

### ISSUE THREAD

**Issue by Plaschke-Culturall** [roundcube/roundcubemail#9239]
We tried to enable the use of secure URLs in our roundcube installation.

For that we tried to set the following configuration in the file config.inc.php:
`$config['use_secure_urls'] = true;`

In our Apache2 configuration file default-ssl.conf we also added the lines:
`Alias /webmail /var/www/html/webmail`
and
```
<IfModule mod_rewrite.c>
   ...
    RewriteRule ^/webmail/[a-zA-Z0-9]{16}/(.*) /webmail/$1 [PT]
</IfModule>
```

When I then restart the apache server and open our webmail in Chrome I see the message that the request got secured against CSRF and that I have to click here to resume the previous session.
But when I click on the link I get an HTTP 404 error.

We are using Roundcube Webmail 1.6.5 and:
Server Version: Apache/2.4.x

Are we missing some further configuration?
Do we need to set asset_path or something? (I tried but it didn't change anything)

**Comment by alecpl** [comment]
Works for me. And this feature does not require other configuration. Maybe the RewriteRule does not work for some reason. Did you forget `RewriteEngine on`?
