### ISSUE TITLE
Multiple PHP warnings on PHP 8.0.x

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9242]
I got PHP 8.0.30 on my server, and receiving the following warnings in my webserver log file;

Roundcube version: 1.6.5

PHP Warning:  Undefined array key 2 in /rcube/program/include/rcmail_attachment_handler.php on line 64
PHP Warning:  Undefined array key "size" in /rcube/program/lib/Roundcube/rcube_message.php on line 1125

Also one "missing" file report:

[error] 74888#0: *880 open() "/rcube/skins/elastic/deps/Popper.js" failed (2: No such file or directory), request: "GET /webmail/skins/elastic/deps/Popper.js HTTP/1.1"

Regards.

**Comment by alecpl** [comment]
I fixed the warnings. I have no idea about the missing file error. Popper is supposed to be included in bootstrap.bundle.min.js, and there's nothing in Roundcube referencing Popper.js.
