### ISSUE TITLE
Two-factor authentication (2FA)

### ISSUE THREAD

**Issue by eveneme** [roundcube/roundcubemail#9247]
Adding Two-Factor Authentication to Roundcube.

**Comment by alecpl** [comment]
Some plugins exist. We do not plan to add this to the core.

**Comment by eveneme** [comment]
But they are paid.

**Comment by alecpl** [comment]
`kolab_2fa` is not.

**Comment by bugoff** [comment]
Since kolab_2fa is archived, is there any chance this could be included in the core?
https://github.com/thomascube/roundcube-plugin-kolab-2fa

I only found 1 paid plugin that doesn't require me to connect with their own platform.

**Comment by ott-asd** [comment]
@alecpl and @pabzm , could you please consider implementing this again? MFA and passwordless login have become essential security features todays world. Currently, we have to rely on 3rd-party plugins, but most are archived, unmaintained, or paid. Incorporating this as a core feature would be a massive improvement for security.

**Comment by pabzm** [comment]
I won't put time into it, but I think we could have a feature request for this open, maybe tagged as `help wanted`.
