### ISSUE TITLE
1.4.16 tag misses release and artifacts

### ISSUE THREAD

**Issue by tyranron** [roundcube/roundcubemail#9255]

**Comment by alecpl** [comment]
There will be no release. 1.4 is out of support.

**Comment by TheMrg** [comment]
is this security issue https://roundcube.net/news/2024/05/19/security-updates-1.6.7-and-1.5.7 in 1.4 LTS?
https://endoflife.date/roundcube says 1.4 has security support?
many thanks.

**Comment by alecpl** [comment]
endoflife.date is wrong. As far as I know we never promised end-of-support dates.
