### ISSUE TITLE
In Elastic skin, Roundcube removes trailing character in non-latin email addresses

### ISSUE THREAD

**Issue by mazerpazer** [roundcube/roundcubemail#9257]
When using Elastic skin, Roundcube UI removes the trailing character in a non-latin (IDN) email address when the user clicks away from the 'To' field in the UI.

This issue affects Roundcube versions 15.x - 1.6.5 and only appears when using Elastic skin.

It seems that the regex that is supposed to remove any non-alpha trailing characters is not configured to support unicode.

Proposed solution - change the regex, so it properly supports unicode encoding:

```
--- skins/elastic/ui.js.bak	2023-12-11 16:48:40.445899000 +0300
+++ skins/elastic/ui.js	2023-12-12 10:27:25.831659000 +0300
@@ -3413,7 +3413,7 @@
                     recipients.push({
                         name: '',
                         email: email.replace(/(^<|>$)/g, '') // trim < and > characters
-                            .replace(/[^a-z]$/gi, '') // remove trailing comma or any non-letter character at the end (#7899)
+                            .replace(/[^\p{L}]$/giu, '') // remove trailing comma or any non-letter character at the end (#7899)
                     });
 
                     str = str.replace(email, '').trim();
```

https://github.com/roundcube/roundcubemail/assets/35998503/1cf0e1b8-bd51-4daf-9344-e241caee150d

**Comment by alecpl** [comment]
Confirmed. The proposed solution will not work in IE11 and Safari 9, which are the supported browsers. so, we might need another fix or we change supported browsers to "Last 2 versions of Edge/Chrome/Firefox/Safari" only.

**Comment by alecpl** [comment]
Fixed.
