### ISSUE TITLE
'SMTP Error(): Connection to server failed'

### ISSUE THREAD

**Issue by edika99** [roundcube/roundcubemail#9260]
I've installed roundcube 1.6.5 but I'm having propblem sending email

The system is configured with a Postfix server and Dovecot with virtual emails
I'm able to read emails but I cannot send emails. 

'SMTP Error(): Connection to server failed'

Looking in postfix log I found this log

Dec 12 17:43:32 bracco postfix/smtpd[23177]: connect from localhost6.localdomain6[::1]
Dec 12 17:43:32 bracco postfix/smtpd[23177]: lost connection after STARTTLS from localhost6.localdomain6[::1]
Dec 12 17:43:32 bracco postfix/smtpd[23177]: disconnect from localhost6.localdomain6[::1] ehlo=1 starttls=1 commands=2

I've tried using another mail postifx server (spamtitan) in our network that does not require authetication and is used daily from all the clients in the LAN, but the result is the same:

Dec 12 17:50:38 polluce postfix/smtpd[92209]: connect from bracco.vci.dmz[10.0.0.187]
Dec 12 17:50:38 polluce postfix/smtpd[92209]: lost connection after STARTTLS from bracco.vci.dmz[10.0.0.187]
Dec 12 17:50:38 polluce postfix/smtpd[92209]: disconnect from bracco.vci.dmz[10.0.0.187] ehlo=1 starttls=1 commands=2

It looks roundcube connect to the server and immediatly disconnect.
The mail server does not require any authentication from the internal network so my config is very simple

$config['smtp_host'] = 'tls://localhost';
or in the second case
$config['smtp_host'] = 'tls://polluce.dmz';

I've read [this](https://github.com/roundcube/roundcubemail/issues/8676) post, very similar to mine but none of the suggested solution looks working.

Thanks

Edika

**Comment by alecpl** [comment]
Maybe certificate validation fails (self-signed cert?). Maybe `$config['smtp_debug'] = true;` will help.

**Comment by edika99** [comment]
Removing roundcube and reinstalling it solve the problem.

Thanks
