### ISSUE TITLE
Cannot install JS dependencies

### ISSUE THREAD

**Issue by tyranron** [roundcube/roundcubemail#9266]
[`tinymce-langs` URL](https://github.com/roundcube/roundcubemail/blob/1.6.5/jsdeps.json#L57-L60) started to [return 403](https://github.com/instrumentisto/roundcube-docker-image/actions/runs/7194458493/job/19595028767#step:5:2537):

https://www.tiny.cloud/tinymce-services-azure/1/i18n/download/?langs=ar,hy,az,eu,be,bs,bg_BG,ca,zh_CN,zh_TW,hr,cs,cs_CZ,da,nl,en_CA,en_GB,eo,et,fo,fi,fr_FR,fr_CH,gd,gl,ka_GE,de,de_AT,el,he_IL,hi_IN,hu_HU,is_IS,id,ga,it,ja,kab,km_KH,ko_KR,ku,ku_IQ,lv,lt,lb,mk_MK,ml_IN,nb_NO,oc,fa,fa_IR,pl,pt_BR,pt_PT,ro,ru,sk,sl_SI,es,es_MX,sv_SE,tg,ta,ta_IN,tt,th_TH,tr,tr_TR,ug,uk,uk_UA,vi,vi_VN,cy&v=5.8.2&extension=.zip

<img width="869" alt="Screenshot 2023-12-13 at 12 58 44" src="https://github.com/roundcube/roundcubemail/assets/7114909/192ec689-f118-4619-adb2-ce4b20ba87a9">

**Comment by alecpl** [comment]
Yeah, it stopped working yesterday. I informed TinyMCE at https://github.com/tinymce/tinymce/issues/9245. I'll work on a solution soon, but I'd like to know some more from them.

**Comment by tyranron** [comment]
@alecpl 

There is also the https://github.com/mklkj/tinymce-i18n repo, which can be used as direct `composer` or `npm`/`yarn` dependencies. The fun fact about it is:
```bash
$ git clone https://github.com/mklkj/tinymce-i18n
$ ls -l tinymce-i18n/langs5 | wc -l
      67
```
which is neither 38 nor 74 🙈🙈🙈🙈

**Comment by alecpl** [comment]
Fixed. Right now some languages might be missing, until TinyMCE fix that.
