### ISSUE TITLE
random errors when view mails w/ message `Oops... something went wrong! An internal error has occurred. Your request cannot be processed at this time.  For administrators: Please check the application and/or server error logs for more information.'

### ISSUE THREAD

**Issue by oleg-indeez** [roundcube/roundcubemail#9267]
Hello. After last `git pull` (now it's up to date with 'origin/master') when selecting messages sometimes this error appears. There's no obvious system with messages or it's format (html or plain text) - once it can be shown ok, but then it fails. In the error.log there're the following lines:

> [14-Dec-2023 22:56:49 +0300]: <xxx> PHP Error: Found unconstructed Spoofchecker in ...some path.../rcube.git/program/lib/Roundcube/rcube_spoofchecker.php on line 55 (GET /?_task=mail&_caps=pdf%3D1%2Cflash%3D0%2Ctiff%3D0%2Cwebp%3D1%2Cpgpmime%3D0&_uid=423611&_mbox=INBOX&_framed=1&_action=preview)
> [14-Dec-2023 22:56:49 Europe/Moscow] PHP Fatal error:  Uncaught IntlException: fopen(rcmail_string_replacer.php): Failed to open stream: No such file or directory in ...some path.../rcube.git/program/lib/Roundcube/bootstrap.php:447
Stack trace:
> #0 ...some path.../rcube.git/program/lib/Roundcube/bootstrap.php(447): fopen()
> #1 ...some path.../rcube.git/program/lib/Roundcube/rcube_text2html.php(148): rcube_autoload()
> #2 ...some path.../rcube.git/program/lib/Roundcube/rcube_text2html.php(133): rcube_text2html->converter()
> #3 ...some path.../rcube.git/program/lib/Roundcube/rcube_text2html.php(113): rcube_text2html->convert()
> #4 ...some path.../rcube.git/program/actions/mail/index.php(1093): rcube_text2html->get_html()
> #5 ...some path.../rcube.git/program/actions/mail/index.php(1062): rcmail_action_mail_index::plain_body()
> #6 ...some path.../rcube.git/program/actions/mail/show.php(738): rcmail_action_mail_index::print_body()
> #7 ...some path.../rcube.git/program/include/rcmail_output_html.php(1484): rcmail_action_mail_show::message_body()
> #8 [internal function]: rcmail_output_html->xml_command()
> #9 ...some path.../rcube.git/program/include/rcmail_output_html.php(1322): preg_replace_callback()
> #10 ...some path.../rcube.git/program/include/rcmail_output_html.php(825): rcmail_output_html->parse_xml()
> #11 ...some path.../rcube.git/program/include/rcmail_output_html.php(654): rcmail_output_html->parse()
> #12 ...some path.../rcube.git/program/actions/mail/show.php(164): rcmail_output_html->send()
> #13 ...some path.../rcube.git/program/include/rcmail.php(285): rcmail_action_mail_show->run()
> #14 ...some path.../rcube.git/index.php(278): rcmail->action_handler()
> #15 {main}
>   thrown in ...some path.../rcube.git/program/lib/Roundcube/bootstrap.php on line 447`

the file mentioned above exists at
`-rw-r--r--  1 www www 2438 14 дек.  17:31 ./program/include/rcmail_string_replacer.php`

There were no errors till the last `git pull` (yesterday evening I suppose). I've tried to `git clone` from the github to another catalog, set it up, but all was in vain: the same errors.

**Comment by alecpl** [comment]
The errors suggest something wrong with your PHP setup (`intl` extension).

**Comment by oleg-indeez** [comment]
Thank you for lightning and profound reply! I've missed the fact that recently upgraded FreeBSD itself w/o rebuilding php ports. Thank you for your advice and for roundcube too!
