### ISSUE TITLE
XSS via PDF attachment

### ISSUE THREAD

**Issue by UserHen** [roundcube/roundcubemail#9277]
Hello,

It is possible to trigger XSS via a PDF attachment. Please follow the below steps to reproduce:

1. Send the following PDF as an attachment.
```
%PDF-1.3
%âãÏÓ
1 0 obj
<</Pages 2 0 R /Type /Catalog>>
endobj
2 0 obj
<</Count 1 /Kids [3 0 R] /Type /Pages>>
endobj
3 0 obj
<</AA
  <</O
  <</JS
  (
try {
  app.alert\("XSS"\)
} catch \(e\) {
  app.alert\(e.message\);
}
    )
  /S /JavaScript>>>>
  /Annots [] /Contents 4 0 R /MediaBox [0 0 612 792] /Parent 2 0 R
  /Resources
  <</Font <</F1 <</BaseFont /Helvetica /Subtype /Type1 /Type /Font>>>>>>
  /Type /Page>>
endobj
4 0 obj
<</Length 21>>
stream

BT
/F1 24 Tf
ET
    
endstream
endobj
xref
0 5
0000000000 65535 f
0000000015 00000 n
0000000062 00000 n
0000000117 00000 n
0000000424 00000 n
trailer

<</Root 1 0 R /Size 5>>
startxref
493
%%EOF
```
2. Preview the PDF attachment from the received email.

Please let me know if you require any additional information.

**Comment by alecpl** [comment]
Roundcube does not preview PDF. So, I think we need more details.

- what Roundcube version? what plugins?
- what web browser? plugins?
- provide full email source.
- what exactly do you mean by "preview"? Open or Download option?

**Comment by UserHen** [comment]
Apologies on the wording. By preview I meant open the PDF without downloading it. Versions tested are 1.6.x and 1.4.x. The email is just a blank email with the above PDF attached. Tested in Brave and Chrome. Unsure on particular plugins.

**Comment by alecpl** [comment]
I confirm the alert in Chrome, but not Firefox. I think this is a bug in the PDF viewer component of the browser. I'm not sure if parsing binary pdf content is what Roundcube should do.

**Comment by alecpl** [comment]
Javascript in pdf is a feature. Question is whether this code can access Roundcube page or is properly sandboxed.

**Comment by giomke** [comment]
It is a pop-up box, not a XSS.
It is a feature of PDF, you can make similar PDF for Firefox and chrome with the help of "app.alert" function.
For example, the following payload works for both browsers 

```
%PDF-1.5
%öäüß
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
/OpenAction 3 0 R
/Lang (it-IT)
>>
endobj
2 0 obj
<<
/Type /Pages
/Resources 5 0 R
/MediaBox [0 0 595 841]
/Kids [6 0 R]
/Count 1
>>
endobj
3 0 obj
<<
/Type /Action
/S /JavaScript
/JS (app.alert\(1\);)
>>
endobj
7279
%%EOF
6 0 obj
<</Type /Page /Parent 2 0 R /Resources 5 0 R /MediaBox [0 0 595.3039370079 841.8897637795 ] /Annots [8 0 R 14 0 R 15 0 R ] /Group <</S /Transparency /CS /DeviceRGB /I true >> /Contents 9 0 R >> 
endobj
trailer
<</Size 256 /ID [(Ê¼¨bBhA¦Tløê°) (hK?&r4È9:á) ] /Root 1 0 R /Prev 7279 /Info 4 0 R >> 
startxref
8360
%%EOF
```

**Comment by UserHen** [comment]
Okay thanks for clarifying, I will close this issue. I will reopen if I am able to validate an impact to roundcube i.e lack of sandbox.

**Comment by progsmile** [comment]
@UserHen are there any findings regarding impact on roundcube out of sandbox? Please, let me know.

**Comment by UserHen** [comment]
@progsmile On an initial look it does not look like it is possible to perform actions such as accessing the DOM or making network requests, however I have not had a chance to fully test this. If I find any issues after further testing I will let you know
