### ISSUE TITLE
Password plugin SQL driver not supporting crypt method.

### ISSUE THREAD

**Issue by Hashfastr** [roundcube/roundcubemail#9293]
When using crypt passwords with SQL:
>- Crypt text passwords:
>  UPDATE users SET password=%P WHERE username=%u LIMIT 1

The crypt method remains undefined at:

https://github.com/roundcube/roundcubemail/blob/ffa298d41c6198c39f028ad419c3c3e94afeed0f/plugins/password/drivers/sql.php#L59 

Where is should look something like this: `password::hash_password($passwd, $method);` Otherwise the `hash_password` method defaults to a blank method causing an error. To my understanding there are configs parameters such as:

```php
$config['password_crypt_hash'] = 'sha512-crypt';
$config['password_hash_algorithm'] = 'sha512-crypt';
```

Which aren't respected. It seems like all encrypted passwords using this plugin with SQL is completely broken without this change. I've temporary fixed this by replacing the default method to `sha512-crypt` in the function which has allowed for full functionality to return.

**Comment by alecpl** [comment]
When the 2nd argument of hash_password() is empty, it will default to 'password_algorithm' option value. The options you're referring to do not exist. I suppose you missed some upgrade changes.
```
// Password hashing/crypting algorithm.
// Possible options: des-crypt, ext-des-crypt, md5-crypt, blowfish-crypt,
// sha256-crypt, sha512-crypt, md5, sha, smd5, ssha, ssha256, ssha512, samba, ad, dovecot, clear.
// Also supported are password_hash() algoriths: hash-bcrypt, hash-argon2i, hash-argon2id.
// Default: 'clear' (no hashing)
// For details see password::hash_password() method.
$config['password_algorithm'] = 'clear';
```
