### ISSUE TITLE
cannot install on PostgreSQL, Roundcube  DDL upgrade  script has errors

### ISSUE THREAD

**Issue by PeterFokkinga** [roundcube/roundcubemail#9295]
I am trying to install/run the  roundcube/roundcubemail:latest-fpm-alpine docker image 

However, it gives a fatal error:
```
roundcubemail  | roundcubemail found in /var/www/html - installing update...
roundcubemail  | Target installation already in version 1.6.5. Do you want to update again? (y/N)
roundcubemail  | Copying files to target location...done.
roundcubemail  |
roundcubemail  | Running update script at target...
roundcubemail  | WARNING: Mimetype to file extension mapping doesn't work properly!
roundcubemail  | Please check the 'mime_types' config option and run this script again.
roundcubemail  | Executing database schema update.
roundcubemail  | PHP Warning:  Undefined array key "1.6.5" in /var/www/html/program/include/rcmail_utils.php on line 163
roundcubemail  | Updating database schema (2013011000)... [OK]
roundcubemail  | Updating database schema (2013042700)... [FAILED]
roundcubemail  | ERROR: Error in DDL upgrade 2013042700: [7] ERROR:  relation "user_ids" does not exist
```

The offending statement in SQL/postgres/2013042700.sql is `ALTER SEQUENCE user_ids RENAME TO users_seq;` and grepping through the postgres.initial.sql file and the update scripts shows indeed that this sequence is never created.

Btw in that same file `ALTER SEQUENCE identity_ids RENAME TO identities_seq;` and `ALTER SEQUENCE contact_ids RENAME TO contacts_seq;` will also fail, the last two renames (contactgroups_ids and search_ids) are correct however.

**Comment by alecpl** [comment]
It does not make sense. The PHP warning suggests that you're not using 1.6.5, so what are you using? What are you upgrading from?

**Comment by PeterFokkinga** [comment]
Found the cause. 

The very first start of the docker failed because it couldn't reach the database (firewall issue). On subsequent starts it found the /var/www/html data from the first failed start and tried to "upgrade" that. It starts fine after I removed that data.

**Comment by CumpsD** [comment]
Thanks! This bit me too just now
