### ISSUE TITLE
upgrade from 1.6 to 1.6.5 fail with the installto.sh script

### ISSUE THREAD

**Issue by ewok2** [roundcube/roundcubemail#9300]
Hello
Download latest verstion 1.6.5 tar.gz
uncompress it
Going to the roundcube-1.6.5 directory
launching "./bin/installto.sh /var/www/roundcube/"

My conf : 
Ubuntu 22.04
roundcube 1.6.0
php8.2

get error message :
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /home/user/roundcubemail-1.6.5/program/lib/Roundcube/bootstrap.php:86
Stack trace:
#0 /home/user/roundcubemail-1.6.5/program/include/iniset.php(78): require_once()
#1 /home/user/roundcubemail-1.6.5/program/include/clisetup.php(25): require_once('...')
#2 /home/user/roundcubemail-1.6.5/bin/installto.sh(23): require_once('...')
#3 {main}
  thrown in /home/dimi/roundcubemail-1.6.5/program/lib/Roundcube/bootstrap.php on line 86

I have try to "install" 
sudo apt-get install php8.2-mbstring
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
php8.2-mbstring is already the newest version (8.2.14-1+ubuntu22.04.1+deb.sury.org+1).

Any idea of the problem?
Do I try to upgrade manualy?

Thanks

**Comment by alecpl** [comment]
Ubuntu has ability to use different PHP version for CLI and Apache. Mybe you're not using the version you think you are.

Not Roundcube issue.
