### ISSUE TITLE
Not receiving or sending emails from ANY email address in our Roundcube account

### ISSUE THREAD

**Issue by GEMCDrs** [roundcube/roundcubemail#9305]
For the last 2 days we have been unable to send any emails or receive any emails in any of our 7 email addresses associated with our Roundcube account. When we tried sending from our gmail account, we get no bounce-back/ undeliverable message in gmail but it doesn't come in to the roundcube email. When we send from roundcube, it looks like it went through but not in the sent folder and the recipient doesn't get anything. We've tried this from multiple computers and multiple external email addresses (not just gmail).

**Comment by Franck78** [comment]
"Roundcube Webmail is a browser-based multilingual IMAP client"

This program have nothing to do with sending or receiving or even contacting  SMTP servers except the one you have in the config.

Start by checking your smtp server, your imap server, and check Roundcube can access them.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
