### ISSUE TITLE
Crashed chrome (Aw snap)

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9311]
When I compose a mail, if I put an "i"  in the recipient box, Chrome crashes with aw-snap. However if I put a different letter, like x, it doesn't crash.

The details. I use dreamhost webmail.
I'm using a Android 8 cell phone and Chrome beta from Google play.
I have a contact with an i in its name but no contact with an x in its name.

No I don't expect you to be able to reproduce it. But I think this is the best place to file this issue. The Chrome team certainly wouldn't go buy a dreamhost account to test it and also wouldn't have the same contacts I had etc.

**Comment by jidanni** [comment]
Yes, there is a workaround, to still be able to send to Mr i..: Find one of the messages from him and simply tap on his email address. That way I avoid the deadly compose system name entry box.

**Comment by jidanni** [comment]
Yes, I could send you a screenshot but it's just the usual aw snap screenshot so never mind.

**Comment by alecpl** [comment]
What Roundcube version? What skin? What plugins? What Chrome version?

**Comment by jidanni** [comment]
Well https://webmail.dreamhost.com/?_task=mail&_mbox=INBOX# says
Roundcube Webmail 1.4.3
Copyright © 2005-2020, The Roundcube Dev Team
Installed plugins
Plugin	Version	License	Source
archive	3.4	GPLv3+
filesystem_attachments	1.0	GPLv3+
jqueryui	1.12.0	GPLv3+
zipdownload	3.4	GPLv3+

Browser:
https://play.google.com/store/apps/details?id=com.chrome.beta , freshest version.

Skin... well CTRL+U shows
```
 <link rel="stylesheet" href="skins/elastic/deps/bootstrap.min.css?s=1673506786">
 <link rel="stylesheet" type="text/css" href="plugins/jqueryui/themes/elastic/jquery-ui.css?s=1582145782">
<script src="https://kit.fontawesome.com/7d998cc9b7.js"></script>
 <link rel="stylesheet" href="skins/elastic/styles/styles.css?s=1673507063">
```
I mean I am just the lowest of user of their website...

**Comment by alecpl** [comment]
Roundcube 1.4 is out of support. It also looks like the skin is modified.
