### ISSUE TITLE
Entities in pseudo text/plain URLs not resolved

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9312]
I am using https://webmail.dreamhost.com .
It is using Roundcube Webmail 1.4.3 .
With these settings,
![20240121T111133](https://github.com/roundcube/roundcubemail/assets/1230959/e9e26e11-d282-42e1-9212-f616ec75fc34)

if an email comes in with only an HTML part,
a pseudo plain text part is created by roundcube.
![20240121T112100](https://github.com/roundcube/roundcubemail/assets/1230959/a8576ea6-8d13-4ac5-88fb-018b687790ab)

The problem is the links in that pseudo plain text part... well, what
should be plain "&" end up still being full `&amp;`s when the user
clicks them.
[sample_message.gz](https://github.com/roundcube/roundcubemail/files/13999891/sample_message.gz)
Yes, maybe the DreamHost corporation should update Roundcube.

**Comment by alecpl** [comment]
Confirmed with git-master.

**Comment by alecpl** [comment]
Fixed.
