### ISSUE TITLE
PHP Deprecated:  Calling get_class() without arguments is deprecated

### ISSUE THREAD

**Issue by teoberi** [roundcube/roundcubemail#9319]
From the httpd (Apache) log:

> [proxy_fcgi:error] ... Got error 'PHP message: PHP Deprecated:  Calling get_class() without arguments is deprecated in /var/www/htdocs/roundcube/vendor/pear/pear-core-minimal/src/PEAR.php on line 235', referer: ...

Some information:
https://wiki.php.net/rfc/deprecate_functions_with_overloaded_signatures

> Suggested backward compatible alternative: code which invokes get_class() without parameters should be modified to use self::class or get_class($this) instead

https://www.exakat.io/en/new-php-error-messages-in-php-8-3/

> In PHP 8.3, get_class() and get_parent_class()’s arguments are now compulsory. It must be provided as argument. This means using $this when inside a class.
Another option is to call get_called_class(), which acts as get_class() without arguments. get_called_class() also works with static methods, a.k.a. methods without access to $this.

**Comment by alecpl** [comment]
This would be a `pear/pear-core-minimal` issue. There was a fix for this in https://github.com/pear/pear-core-minimal/commit/0b21f0345e55e61a70306a2e1ad1bf7031c0add0, but they reverted that.

I opened the ticket: https://github.com/pear/pear-core-minimal/issues/16

**Comment by alecpl** [comment]
You can lock `pear/pear-core-minimal` in your composer.json to version `1.10.13` as a workaround for now.

**Comment by teoberi** [comment]
I have been using the so-called "complete" release package for some time and as such blocking pear/pear-core-minimal in composer.json does not help me.
Until the respective changes are made, I replaced `get_class()` with `self::class` in line 235.

**Comment by cscholz** [comment]
> self::class

Unfortunately, this does not solve the problem for me after the update. the web client can no longer be used. Hope for a fix soon.

**Comment by alecpl** [comment]
@cscholz That's an external plugin issue.

**Comment by alecpl** [comment]
The issue has been fixed in pear-core-minimal 1.10.15.

**Comment by vaelu** [comment]
@alecpl Shouldn't the composer.json file get updated to 1.10.15?

**Comment by ole1986** [comment]
I think the `pear-core-minimal` does not have anything to do with it
