### ISSUE TITLE
Ctrl+drag&drop should Copy, not Move an email

### ISSUE THREAD

**Issue by dilyanpalauzov** [roundcube/roundcubemail#9321]
When I press the Ctrl and then drag&drop an email between the folders of the same account, I expect that
• the email is not moved, but copied, and
• the cursor (moved object presentation) changes somehow to show the current operation is Copy.

**Comment by alecpl** [comment]
In Roundcube it is Shift + drag, When you drop you'll be asked to choose from "Copy" and "Move".

**Comment by dilyanpalauzov** [comment]
That is correct, but:
* once the dialogue “Copy or Move” is opened, it cannot be closed by the Escape key, and
* there is no different symbol (cursor) indicating normal “Move” from “Whether Move or Copy will be decided later”.
