### ISSUE TITLE
remove plugins.roundcube.net from composer.json-dist

### ISSUE THREAD

**Issue by johndoh** [roundcube/roundcubemail#9323]
the package repo at plugins.roundcube.net was frozen 3.5 years ago

> We’d like to make the switch on May 17th 2020. On this day, the repository data of plugins.roundcube.net will be frozen and the current Packagist service will be replaced by a read-only clone that’ll keep on serving requests from Composer to install Roundcube plugins. After that day, all updates and new registrations for Roundcube plugins need to be submitted to packagist.org.

may be now version 1.4 has reached EOL its time to remove
```js
    "repositories": [
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net"
        }
    ],
```
from composer.json-dist

Edit: Rather than removing it, [setting it to non canonical](https://getcomposer.org/doc/articles/repository-priorities.md#making-repositories-non-canonical) might be worth considering so packagist.org is always checked for newer versions.

**Comment by emtiu** [comment]
Making this change would resolve [this problem](https://github.com/roundcube/plugins2.roundcube.net/issues/35), where a plugin is always installed with an outdated version because of stale data on plugins.roundcube.net.

**Comment by alecpl** [comment]
I think we can do this in master.

**Comment by alecpl** [comment]
Done.
