### ISSUE TITLE
Folders set as collapsed render as expanded when parentheses in name

### ISSUE THREAD

**Issue by headbank** [roundcube/roundcubemail#9324]
Recent install of roundcubemail-1.6.3 paired with Dovecot on Raspberry Pi OS (Debian 12).

Maildir contains a number of subfolders (all at least one level deep from root) with names containing parenthesis "(...)" characters. After collapsing such a folder in the sidebar tree and navigating away or refreshing the page, on next render the folder is always expanded again. It's impossible to make collapsing stick for these folders.

No errors appearing in the logs.

**Comment by alecpl** [comment]
Screenshot please. Also, 1.6.6 is more recent.

**Comment by headbank** [comment]
Sorry, coming from Horde so not used to pace of updates ;) will check with updated version asap.

Screenshot:
![not-collapsed](https://github.com/roundcube/roundcubemail/assets/9446449/7d5aed5f-5174-4dbc-b904-2ca846f0250b)

**Comment by headbank** [comment]
Confirm issue still occurring on roundcubemail-1.6.6-complete.

**Comment by headbank** [comment]
Amended title because on inspection of AJAX save-pref action and rcmail.set_env() call in page source, the folders are saved as collapsed; the problem is they are not rendering as such in the UI.

I note that the bracket characters are not URLencoded in the collapsed_folders string payload, as other chars are (I tested with square and curly brackets, which do get URLencoded in the payload and do not trigger the bug - they stay collapsed as per expected behaviour). Feel this might be the source of the issue?

**Comment by headbank** [comment]
I haven't figured out where the code is that renders initial folder state, but I did see this:

/program/js/app.js:1779
```
      var reg = new RegExp('&'+urlencode(node.id)+'&');
      this.env[prefname] = this.env[prefname].replace(reg, '');
```
This code is for removing the target node from the pref string when it is expanded, but fails because your `urlencode()` function doesn't encode brackets, and the RegExp based on the resulting string is therefore b0rked. (On my install I can see this as the pref string still contains names-with-parens after they've been expanded.) Maybe a similar problem occurs wherever it is that initial render state is read?

Looking at the `urlencode()` function (/program/js/common.js:482), it is internally inconsistent because (the now almost universally-supported) `encodeURIComponent()` does not escape parentheses whereas `escape()` does. (So does PHP `rawurlencode()`, so the code does not live up to the comment above it about being compatible with that.)

I don't know if this would solve my problem (will test but can't just now) but to be PHP-compatible and consistent across very old browsers, the function could be changed to:
```
function urlencode(str)
{
  if (window.encodeURIComponent)
    return encodeURIComponent(str)
    .replace('*', '%2A')
    .replace('(', '%28')
    .replace(')', '%29');

  return escape(str)
    .replace('+', '%2B')
    .replace('*', '%2A')
    .replace('/', '%2F')
    .replace('@', '%40');
};
```
(No idea if this brings it into full compatibility, I only looked at the brackets.)

**Comment by headbank** [comment]
Confirm that the above edit resolves this bug for me: parentheses-bearing folders can be collapsed and stay that way. Not noticing any nightmarish side-effects yet.

I will note in addition that the characters `!`, `~` and `'` are also handled inconsistently between the two return-modes of `urlencode()` and PHP's `rawurlencode()`, though I don't believe any of these on their own have special meaning in RegExp.

**Comment by alecpl** [comment]
Thanks for the investigation. We do have `RegExp.escape` function already, we need to use it. I'll work an a proper fix soon.

**Comment by headbank** [comment]
Thanks. I've now seen at /program/include/rcmail_action.php:1229 how the behaviour does indeed depend on `urlencode()` and PHP `rawurlencode()` giving the same output, so FWIW that can almost be accomplished with the function as so:
```
function urlencode(str)
{
  if (window.encodeURIComponent)
    return encodeURIComponent(str)
    .replace('*', '%2A')
    .replace('(', '%28')
    .replace(')', '%29')
    .replace('!', '%21')
    .replace("'", '%27');

  return escape(str)
    .replace('+', '%2B')
    .replace('*', '%2A')
    .replace('/', '%2F')
    .replace('@', '%40')
    .replace('%7E', '~');
};
```
That harmonises all three outputs for all the chars on my keyboard (except `escape('£')` but that really broadens the scope lol).

**Comment by alecpl** [comment]
Fixed.
