### ISSUE TITLE
Sometimes it says Inbox is empty

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9333]
Yes, this is sort of hard to reproduce. You just have to encounter it once in a while.

And no, it's not the end of the world,  if Refresh doesn't fix it then closing the browser and logging in again will.

Okay, what's the problem? The problem is sometimes it says my entire Inbox is empty!

Now your normal user would panic and jump out the window or something.

Fortunately I'm more calm, cool and collected. So I just go back to the list of folders and indeed I see I really do have seven messages in the Inbox.

So then I just tap Inbox again and there  my messages are back.

However every so often I get this scare. Maybe  once every couple weeks or something. 

![Screenshot_20240131_140701_Chrome Beta.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/a7bc1205-a695-4186-b1b7-c737fda85be4)

![Screenshot_20240131_140714_Chrome Beta.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/6f0ef303-52aa-4ebc-a2ad-95656f1882aa)

I mean I'm already used to it. I don't panic or anything. But I just think I should let you know sooner or later.

Roundcube Webmail 1.4.3
Copyright © 2005-2020.

Sorry, that's the latest they got at Dreamhost.

**Comment by alecpl** [comment]
You're using old unsupported version. And it sounds like #9308.
