### ISSUE TITLE
Get access to roundcube only for authenticated users

### ISSUE THREAD

**Issue by rux2** [roundcube/roundcubemail#9337]
I'm trying to add roundcube to my laravel website : below folder's structure

public_html

app
public
resources
roundcube 
storage
now the problem is : i want that only user logged in my website can access to roundcube cause now if i type mywebsite.com/roundcube i can access to it even if i'm not authenticated. Also i would like to autocomplete email field with session user's email. Can someone help me? Thanks

**Comment by alecpl** [comment]
This is out of scope for this bug tracker. You will need to write a plugin. Ask on the forum, please.
