### ISSUE TITLE
Which PHP versions? Wiki is outdated

### ISSUE THREAD

**Issue by ygoe** [roundcube/roundcubemail#9339]
I read this:
https://github.com/roundcube/roundcubemail/wiki/Install-Requirements
And it says: "PHP 8 will be supported with Roundcube 1.5"

Well, we're at 1.6.6 now and PHP 8.0 is already EOL for some time. So which PHP versions can or should I use with Roundcube? 8.1 seems to be running fine, but I could also select 8.2 or 8.3. Could somebody please update that documentation? (And no, I can't do that, as I'm already asking for this information. A dev team member should do it.)

**Comment by alecpl** [comment]
We need to update this page. Yes PHP 8.3 shouldn't be a problem for Roundcube 1.6.

**Comment by alecpl** [comment]
Done.

**Comment by CodeShakingSheep** [comment]
Hi @alecpl ,
if PHP version 8.2 and 8.3 are officially supported for Roundcube 1.6 please also update https://github.com/roundcube/roundcubemail/wiki/Version-History. It still states

> Version 1.6
Initial release: 28 July 2022
PHP support: >=7.3 <=8.1

Thanks.
