### ISSUE TITLE
The problem with the personal card of the found LDAP user

### ISSUE THREAD

**Issue by VladislavKara** [roundcube/roundcubemail#9340]
Hello everyone.
I ran into a little problem when searching for users in the LDAP address book, when trying to open their personal card to look at their email or something else
I got `Error No. [700]` when I try to open the personal card of a found user. 
I see the following error in the browser console: `Uncaught TypeError: Cannot read properties of undefined (reading '_type')`
In log file: 
`[05-Feb-2024 06:02:47 +0000]: <kvjhf95s> PHP Error: Addressbook source (ADDRESSBOOK_NAME) not found! in /var/www/roundcube/program/include/rcmail.php on line 385 (GET /?_task=addressbook&_framed=1&_search=d303f7b4686a0c58b0a9272ba3c6a0b4&_cid=dWl
kPXdlYmRvemVyeixjbj11c2Vycyxjbj1hY2NvdW50cyxkYz1maSxkYz1jcnlwdG9uLGRjPXNopWRpbw-ADDRESSBOOK_NAME&_action=show&_source=)`

And this is a correct error because I don't have ADDRESSBOOK_NAME, the name of my address book in the config file is ADDRESSBOOK.NAME
But why is it try to find ADDRESSBOOK_NAME instead of ADDRESSBOOK.NAME

Requirements:
- Roundcube: v. 1.6.6 (This problem was in version 1.6.2)
- LDAP based on FreeIPA

P.S. Sorry if issue is duplicated, I didn't find any issue or solution for my problem.

Thanks in advance!

**Comment by alecpl** [comment]
Dot is not supported. It's mentioned in defaults.inc.php already
```
// In order to enable public ldap search, configure an array like the Verisign
// example further below. if you would like to test, simply uncomment the example.
// Array key must contain only safe characters, ie. a-zA-Z0-9_
$config['ldap_public'] = [];
```
