### ISSUE TITLE
Roundcube & Dovecot & Login

### ISSUE THREAD

**Issue by Keram-Yasin** [roundcube/roundcubemail#9341]
While I am testing doveadm-who command on dovecot server, I discovered that the Roundcube user is not shown on the command output even if the RC user is online(stay logged in). After this discovery, I made a special test in which all users are logged-out. Then, only a single user logs in with RC webmail and stays logged-in. The Dovecot log is shown below:

`Feb 05 09:51:20 myhost dovecot[1327]: imap-login: Login: user=<some.user@example.com>, method=PLAIN, rip=86.264.258.324, lip=192.168.1.*, mpid=8680, TLS, session=<IwjMkJ4Q8qXAqAEB>
Feb 05 09:51:20 myhost dovecot[1327]: imap(some.user@example.com)<8680><IwjMkJ4Q8qXAqAEB>: Disconnected: Logged out in=137 out=850 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=>
Feb 05 09:51:20 myhost dovecot[1327]: imap-login: Login: user=<some.user@example.com>, method=PLAIN, rip=86.264.258.324, lip=192.168.1.*, mpid=8682, TLS, session=<eEbPkJ4QAKbAqAEB>
Feb 05 09:51:20 myhost dovecot[1327]: imap(some.user@example.com)<8682><eEbPkJ4QAKbAqAEB>: Disconnected: Logged out in=125 out=846 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes=>
Feb 05 09:51:21 myhost dovecot[1327]: imap-login: Login: user=<some.user@example.com>, method=PLAIN, rip=86.264.258.324, lip=192.168.1.*, mpid=8686, TLS, session=<13nfkJ4QDqbAqAEB>
Feb 05 09:51:21 myhost dovecot[1327]: imap-login: Login: user=<some.user@example.com>, method=PLAIN, rip=86.264.258.324, lip=192.168.1.*, mpid=8687, TLS, session=<443fkJ4QFqbAqAEB>
Feb 05 09:51:21 myhost dovecot[1327]: imap(some.user@example.com)<8687><443fkJ4QFqbAqAEB>: Disconnected: Logged out in=251 out=1057 deleted=0 expunged=0 trashed=0 hdr_count=0 hdr_bytes>
Feb 05 09:51:21 myhost dovecot[1327]: imap(some.user@example.com)<8686><13nfkJ4QDqbAqAEB>: Disconnected: Logged out in=424 out=30236 deleted=0 expunged=0 trashed=0 hdr_count=50 hdr_byt>`

As shown on the Dovecot log, the user is shown as logged out immediately after log in. This makes doveadm-who command useless for RC users. This may also create security loophole for dovecot. 

I tried to search for a solution on Google to get this fixed. And found some relevant information especially with php module [suhosin]. But this seems to be solution for session issue. So I am writing here to ask for clarification about this situation.

**Comment by alecpl** [comment]
Roundcube session has nothing to do with Dovecot session. Also Roundcube does not keep the connection to the imap server all the time, instead it makes a new connection on every http request (that needs it)
