### ISSUE TITLE
RFC 1855

### ISSUE THREAD

**Issue by texxturum** [roundcube/roundcubemail#9342]
Dear Sir or Madame, 

I obey the RFC 1855 and send Emojis in text.

https://datatracker.ietf.org/doc/html/rfc1855

When I create a signature in Roundcube.

The signature gets cut at ​😊.

Why?

Regards,

texxturum.

**Comment by alecpl** [comment]
Emoji uses 4byte Unicode. We fixed that in Roundcube 1.5. References: #6535, #7113.

**Comment by texxturum** [comment]
Thanks​😊.
