### ISSUE TITLE
Catch all virtual identities

### ISSUE THREAD

**Issue by Dash** [roundcube/roundcubemail#9343]
Feature enhancement for virtual identity support:
When using a catch-all on a domain (e.g. *@mydomain.com), or virtual users (e.g. qualifier+user@gmail.com), there should be a way for this to be created dynamically as the sending identity (if temporary or otherwise).

I've had a hunt around the issues and can't find anybody talking about it, and have taken a bit of a dive into the code.  I tried injecting a dummy identity in rcmail_sendmail.php: identity_select, but by the time the UI loads it's returned to the static identity list, I assume because the JS UI is getting a list of identities and then trying to match the appropriate one (and failing due to it not existing).

I'm not sure therefore whether it's possible to have a temporary identity without reworking the UI - I'd appreciate somebody who knows a bit more about this to comment.  I guess another approach would be to create a permanent identity at this point, although it sounds heavy handed.

Both approaches is slightly at odds with the select_identity plugin hook, as this happens at the end of the function, so the identity array needs to be populated first, which if doing dynamically, really wants the capability of the plugin to really pin down valid matches.

My approach to config was just a blunt comma separate list of matching masks, which did the job.

**Comment by MiMoHo** [comment]
There seem to be various compatibility issues with the [custom_from plugin](https://github.com/r3c/custom_from) which conflicts with the standard logic defined by Roundcube resulting in saving issues and thereby falsely modified sender details when the draft is reopened. Better support in (reply) messages for modified sender details as defined or not defined by an identity are essential to support a wide range of reply options that could be introduced by an enhanced custom_from plugin such as
- "receiving email address only"
- "receiving email address with matching identity"
- "receiving email address with default identity"
- "default identity"

However, Roundcube tampers sender details like the BCC and Reply-to values specified in the default or matching identity when it is not supposed to, especially when the user made changes to the above listed reply options and saves and reopens the draft.
For an enhanced custom_from plugin, support for editing, saving and restoring modified identity values of a draft is crucial. Can this be improved @alecpl ?
