### ISSUE TITLE
Emails from the future

### ISSUE THREAD

**Issue by miglincit** [roundcube/roundcubemail#9348]
I know it sounds weird, but some spamers send emails with date information with years to come.
This is a screenshot from the Trash folder. 
![image](https://github.com/roundcube/roundcubemail/assets/4355544/990bc3fb-1a26-49dd-9b78-a8dc0b7ac721)

But: Those emails do not show up correctly sorted in the INBOX - there I had to select **Show New**  to find such emails. It does not help to change the sorting order of the date column.

Version:
Roundcube Webmail 1.3.17

Installed Plugins:
filesystem_attachments 1.0
jqueryui  1.12.0

best regards
Thomas

**Comment by alecpl** [comment]
Roundcube 1.3 is a very old version, out of support. That being said, you should be able to set sorting order in the messages list menu to "None" or "Received date".
