### ISSUE TITLE
Use draft settings on "Edit as new"

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9349]
It is not possible to "duplicate a message" in drafts. Could be nice if you have to send a few emails with the same content

**Comment by alecpl** [comment]
"More > Edit as new" should be good enough.

**Comment by f1-outsourcing** [comment]
Yes thanks! However this setting is not copied

"Delivery status notification"

"Return receipt" is copied (Should that not be read?)

**Comment by alecpl** [comment]
Maybe it would indeed make sense to use drafts settings in "Edit as new". Reopen.

**Comment by f1-outsourcing** [comment]
I prefer to have everything copied from the source message. So I can make one message 'perfect', and then only change the email address in each message I send.

**Comment by alecpl** [comment]
I did some tests. From what I see "Return receipt" flag is set on "Edit as new". However "Delivery status notification" is not.

**Comment by alecpl** [comment]
Done.
