### ISSUE TITLE
Threads messages grouping

### ISSUE THREAD

**Issue by miqp** [roundcube/roundcubemail#9355]
Problem described in [https://github.com/roundcube/roundcubemail/issues/9218](https://github.com/roundcube/roundcubemail/issues/9218). 
E-mails in threads view are only being grouped by a title of messages not by an IDs.

In case of different messages with the same title those are grouped as a one thread where they are not supposed to.

![obraz](https://github.com/roundcube/roundcubemail/assets/138004622/cbc2a027-9aed-4e2e-8cc9-986dfc03e5b7)

[log.txt](https://github.com/roundcube/roundcubemail/files/14283250/log.txt)

**Comment by alecpl** [comment]
As said before: The grouping by thread is done according to IMAP standard by the IMAP server. You can see what's going on using imap_debug option. So, we'll need a proof this isn't an imap server bug, i.e. the debug log.

The log does not contain THREAD request/response.

**Comment by miqp** [comment]
[imap.log](https://github.com/roundcube/roundcubemail/files/14296013/imap.log)
Log contains:
- login
- change view to threaded

**Comment by alecpl** [comment]
The log does not contain THREAD command request, only SORT. So, it does not make sense.

**Comment by alecpl** [comment]
If you're using `messages_cache` then check what happens if you disable it. What version?

**Comment by miqp** [comment]
Nothing changed when I comment out $config['messages_cache']. Version 1.6.4

**Comment by miqp** [comment]
> The log does not contain THREAD command request, only SORT. So, it does not make sense.

If THREAD isn't present in log, maybe RC didn't send this command in threaded view?

**Comment by alecpl** [comment]
Anyway, your server does not support THREAD=REFS, and I think THREAD=REFERENCES has the behavior you see.

**Comment by miqp** [comment]
I think not. As you can find in RFC https://www.rfc-editor.org/rfc/rfc5256.html

   REFERENCES

         The REFERENCES threading algorithm threads the searched
         messages by grouping them together in parent/child
         relationships based on which messages are replies to others.
         The parent/child relationships are built using two methods:
         reconstructing a message's ancestry using the references
         contained within it; and checking the original (not base)
         subject of a message to see if it is a reply to (or forward of)
         another message.
         
I use dovecot as imap server, he support threaded sort by default.
