### ISSUE TITLE
Email won't load after login screen

### ISSUE THREAD

**Issue by LisaRibs66** [roundcube/roundcubemail#9360]
ERR_ADDRESS_UNREACHABLE

Every time I try to log into Chrome on my laptop this is the message I receive. My email also won't load on Apple Mail or on Chrome mobile on my iPhone. Anyone else experiencing the server being down?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

**Comment by LisaRibs66** [comment]
This is not just an issue for my email, it seems that RoundCube server is down more widespread.
