### ISSUE TITLE
Multiple PHP Warnings - Roundcube 1.6.6

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9365]
Roundcube version: 1.6.6
PHP version: 8.1.27

Greetings. I'm getting the following warnings filling web server's log file that I'd like to report here;

```
PHP Warning:  Undefined array key "compose_data_194324102365d2d12709ef1" in /rcube/program/include/rcmail_attachment_handler.php on line 99

PHP Warning:  Undefined array key "compose_data_194324102365d2d12709ef1" in /rcube/program/include/rcmail_attachment_handler.php on line 99

PHP Warning:  Undefined array key "compose_data_194324102365d2d12709ef1" in /rcube/program/include/rcmail_attachment_handler.php on line 99

PHP Error: Invalid response code received from server (POST /webmail/?_task=mail&_unlock=loading1708334565079&_framed=1&_action=send)
```
In the same log file, the following line follows the warnings above -in case of any relate-;

`SMTP Error: Failed to add recipient 'x@domain.com': 5.1.1 <x@domain.com>: Recipient address rejected: User unknown in virtual mailbox table (Code: 550) in /rcube/program/lib/Roundcube/rcube.php on line 1794 (POST /webmail/?_task=mail&_unlock=loading1708334565079&_framed=1&_action=send)
`

Regards.

**Comment by ozgurkazancci** [comment]
And one more warning that I catched;

```
PHP Warning:  Undefined array key "11708333402027745800" in /rcube/program/actions/mail/attachment_upload.php on line 187

PHP Warning:  Undefined array key "11708333402027676300" in /rcube/program/actions/mail/attachment_upload.php on line 187
```

**Comment by alecpl** [comment]
Fixed.
