### ISSUE TITLE
Integration Open Graph

### ISSUE THREAD

**Issue by eveneme** [roundcube/roundcubemail#9368]
Implementing OpenGraph for shared links ensures they display in a more aesthetically pleasing manner, such as links from Google Drive, etc.

**Comment by eveneme** [comment]
It's about converting regular links in email messages to OpenGraph.

Example: https://tailgraph.com/

![image](https://github.com/roundcube/roundcubemail/assets/85762221/5fe7abc0-ae26-49be-b02c-a671045c60b5)

**Comment by alecpl** [comment]
Does not sound that interesting. Write a plugin.
