### ISSUE TITLE
Webmail Including Wrong Time Zone in Email Body of Calendar Invites

### ISSUE THREAD

**Issue by webmailblows** [roundcube/roundcubemail#9370]
Hello,

I'm a total rookie when it comes to this kind of stuff. I currently use Webmail to send meeting invites, as it is the only way I can send invites with my company email. However, when I do so, despite my Webmail being configured to reflect a Los Angeles time zone, the text in the body of the email invite will include the information for New York as well when the invite is opened in Gmail. 

<img width="921" alt="Screenshot 2024-02-28 112625" src="https://github.com/roundcube/roundcubemail/assets/161641997/e2b3b89e-834c-4593-93ed-95a5f38396a2">

<img width="1024" alt="Screenshot 2024-02-28 112407" src="https://github.com/roundcube/roundcubemail/assets/161641997/b9dd2068-07e5-49b7-bb6a-18dedbdb51ca">

I know it's not a problem on Google's end as when I send an invite through Gmail the time zone reflects my settings. I have tried changing to different time zones in my Webmail settings, but the New York information is always included. Is there a way to get rid of this information in the invite itself or to change it so that the correct Los Angeles time zone information is shown?

**Comment by alecpl** [comment]
This is an external plugin we do not support here.

**Comment by webmailblows** [comment]
Wow, thank you for being incredibly helpful and redirecting me to some other place where I might be able to receive assistance! I really appreciate it!
