### ISSUE TITLE
Email from one sender not being received

### ISSUE THREAD

**Issue by PeterPelicans** [roundcube/roundcubemail#9371]
My employer issues Employee Engagement Surveys every few months. I have received them in the past, but the last two have not arrived. They do not appear at all in my Track Delivery tool or anywhere else that I have looked (junk, spam, etc.). I have added the two email addresses that the survey company uses to my Whitelist and my Blacklist is empty, and still do not receive them.
The survey company uses AWS SES, and says that its emails have appropriate SPF and DKIM records.
Any suggestions?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
