### ISSUE TITLE
User real ip is not sending when smtp authentication/sending mail

### ISSUE THREAD

**Issue by chethutth96** [roundcube/roundcubemail#9374]
Hi 

I am facing some issue when i have configured smtp details as below like.
```bash
$config['smtp_server'] = 'tls://<smtp_hostname>';
$config['smtp_port'] = 587;                       
$config['smtp_user'] = '%u';                     
$config['smtp_pass'] = '%p';
```
When i am sending mail i am getting the Roundcube webmail hosted server IP instead of the user real IP address means https connection remote ip need to get. we have configured with apache2,  and also we checked in nginx, web servers but result is same.
if anything i need to do for to get real ip address, your suggestions are most welcome.

 
Below is the postfix logs which shows localhost
```bash
Feb 29 12:32:36 cloud postfix/smtpd[12133]: 640632BBBD: client=localhost[127.0.0.1], sasl_method=LOGIN, sasl_username=chethan@<domain.com>
Feb 29 12:32:36 cloud postfix/qmgr[2081]: 640632BBBD: from=<chethan@<domain.com>>, size=1230, nrcpt=1 (queue active)
```
if you required more information feel free to ping me.

For example when i configure same smtp details in thunderbird or any email clients i am getting 
`client=<user_real_ip`  in roundcube we are getting `client=localhost[127.0.0.1]`

**Comment by alecpl** [comment]
This will depend on what imap/smtp servers you have and what they support.

For dovecot you might use https://packagist.org/packages/takerukoushirou/roundcube-dovecot_client_ip plugin.

In Roundcube core there's also support for the proxy protocol:
```
// proxy_protocol is used to inject HAproxy style headers in the TCP stream
// See http://www.haproxy.org/download/1.6/doc/proxy-protocol.txt
// WARNING: Please note this is currently incompatible with implicit ssl,
// since the proxy protocol preamble is expected before the ssl handshake.
// $config['imap_conn_options'] = [
//    'ssl' => [
//        'verify_peer'  => true,
//        'verify_depth' => 3,
//        'cafile'       => '/etc/openssl/certs/ca.crt',
//    ],
//    'proxy_protocol' => 1 | 2 | [ // required (either version number (1|2) or array with 'version' key)
//        'version'       => 1 | 2, // required, if array
//        'remote_addr'   => $_SERVER['REMOTE_ADDR'], // optional
//        'remote_port'   => $_SERVER['REMOTE_PORT'], // optional
//        'local_addr'    => $_SERVER['SERVER_ADDR'], // optional
//        'local_port'    => $_SERVER['SERVER_PORT'], // optional
//    ],
// ];
```
For SMTP we have also support for `XCLIENT` extension:
```
// Pass the username (XCLIENT LOGIN) to the server
$config['smtp_xclient_login'] = false;

// Pass the remote IP (XCLIENT ADDR) to the server
$config['smtp_xclient_addr'] = false;
```
