### ISSUE TITLE
Marked as deleted => restore deleted message(s)

### ISSUE THREAD

**Issue by the0ne** [roundcube/roundcubemail#9375]
I can use RC to mark messages as deleted.
It seems it's not possible for me remove that "deleted" mark afterwards using RC, which would have the meaning of "restore" or "undelete" message.

**Comment by alecpl** [comment]
Since 1.6 there's a "Mark as undeleted" option in "Mark" menu. Also, I think the Read/Deleted icon is a button that does undelete.

**Comment by the0ne** [comment]
Thanks for the clarification, with Ubuntu I'm currently stuck on 1.5 - that explains why it's not there (for me).
The "Delete" button itself doesn't undelete a message if it's pressed again, I had tried that already.
