### ISSUE TITLE
List Columns Issue

### ISSUE THREAD

**Issue by timpsax** [roundcube/roundcubemail#9378]
Hi there, we have a new issue where List Columns function doesn't work. For example, if we move the From column to the left so that it's the first column shown, it erases all selections for List Columns in the settings. The only way we can have the columns displayed is Subject / From / Date. If we try to change that, it gets rid of all columns except Subject.

**Comment by alecpl** [comment]
What skin? What version? What plugins?

**Comment by timpsax** [comment]
Thanks!
Skin: Larry
Roundcube Webmail 1.6.0
Copyright © 2005-2022, The Roundcube Dev Team
<html><body>
<h3>Installed plugins</h3>

Plugin | Version | License | Source
-- | -- | -- | --
archive | 3.5 | GPL-3.0+ |  
calendar | 3.5.11 | AGPL-3.0 | Download
carddav | v4.4.4 | GPL-2.0 | Download
cpanelicsimport | 11.108 | cPanel License (Proprietary) |  
cpanellogin | 11.58 | cPanel License (Proprietary) |  
cpanellogout | 11.58 | cPanel License (Proprietary) |  
cpanelvcfimport | 11.108 | cPanel License (Proprietary) |  
filesystem_attachments | 1.0 | GPL-3.0+ |  
jqueryui | 1.13.1 | GPL-3.0+ |  
libcalendaring | 3.5.11 | AGPL-3.0 | Download
libkolab | 3.5.11 | AGPL-3.0 | Download
markasjunk | 2.0 | GPL-3.0+ |  
return_to_webmail | 11.106 | cPanel License (Proprietary) |  


</body>
</html>Installed plugins
Plugin	Version	License	Source
archive	3.5	[GPL-3.0+](http://www.gnu.org/licenses/gpl.html)	
calendar	3.5.11	[AGPL-3.0](http://www.gnu.org/licenses/agpl.html)	[Download](https://git.kolab.org/diffusion/RPK/)
carddav	v4.4.4	[GPL-2.0](http://www.gnu.org/licenses/gpl-2.0.html)	[Download](https://github.com/mstilkerich/rcmcarddav/)
cpanelicsimport	11.108	cPanel License (Proprietary)	
cpanellogin	11.58	cPanel License (Proprietary)	
cpanellogout	11.58	cPanel License (Proprietary)	
cpanelvcfimport	11.108	cPanel License (Proprietary)	
filesystem_attachments	1.0	[GPL-3.0+](http://www.gnu.org/licenses/gpl.html)	
jqueryui	1.13.1	[GPL-3.0+](http://www.gnu.org/licenses/gpl.html)	
libcalendaring	3.5.11	[AGPL-3.0](http://www.gnu.org/licenses/agpl.html)	[Download](https://git.kolab.org/diffusion/RPK/)
libkolab	3.5.11	[AGPL-3.0](http://www.gnu.org/licenses/agpl.html)	[Download](https://git.kolab.org/diffusion/RPK/)
markasjunk	2.0	[GPL-3.0+](http://www.gnu.org/licenses/gpl.html)	
return_to_webmail	11.106	cPanel License (Proprietary)

**Comment by alecpl** [comment]
1.6.0 is not a most recent version. I also suspect some cPanel plugins might cause this. So, first update, then test with all plugins disabled.

**Comment by pabzm** [comment]
No feedback and not reproducible, closing.
