### ISSUE TITLE
Message Searching - "executing too slow" Warning

### ISSUE THREAD

**Issue by bronkoo** [roundcube/roundcubemail#9379]
Hi,

when I try to search "Entire message" in "All folders" by keyword, the WebGUI gives me an "Server error! (error)" and log file prints:

`Mar 05 19:13:54 mail php-fpm[131]: [WARNING] [pool inet] child 324270, script '/opt/www/roundcubemail/index.php' (request: "GET /mail/index.php?_task=mail&_action=search&_interval=&_q=MY_KEYWORD&_headers=text&_layout=widescreen&_filter=ALL&_scope=all&_mbox=INBOX&_remote=1&_unlock=loading1709662423732&_=1709662406960") executing too slow (10.490542 sec), logging
Mar 05 19:13:54 mail php-fpm[131]: [NOTICE] child 324270 stopped for tracing
Mar 05 19:13:54 mail php-fpm[131]: [NOTICE] about to trace 324270
Mar 05 19:13:54 mail php-fpm[131]: [NOTICE] finished trace of 324270
`

There is an adjusting screw here...?

**Comment by alecpl** [comment]
Maybe some limit in php-fpm. How to make the search faster would be another story.
