### ISSUE TITLE
Insufficiently flagged encrypted emails

### ISSUE THREAD

**Issue by snan** [roundcube/roundcubemail#9380]
I don't know exactly why but when my friend sends me PGP encrypted emails from K-9, I can easily decrypt them with any of my MUA apps (and spamd also flags it as less likely to be spam because it sees that it's encrypted with my key), but when he sends them from Roundcube, all of my MUAs (including spamd) believe that the ---BEGIN PGP MESSAGE--- 28477adcd1828 stuff is just normal readable text and don't decrypt it (so I have to manually select the text and send it to a decryption app). Maybe it's because of content-type or something 🤷🏻‍♀️

**Comment by alecpl** [comment]
We'd need to see the sample message source. What Roundcube version? What GnuPG version?
