### ISSUE TITLE
Mail delivery failed: returning message to sender

### ISSUE THREAD

**Issue by 1342860833** [roundcube/roundcubemail#9382]
![image](https://github.com/roundcube/roundcubemail/assets/133962293/71b3cf25-7160-4f62-bae0-08ce686f5c42)
This problem occurs no matter what email I send, what is the reason?

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
