### ISSUE TITLE
Setting a subject prefix by default?

### ISSUE THREAD

**Issue by LoSong** [roundcube/roundcubemail#9383]
Hi,

since I'm using Roundcube for sending emails to a closed community of 100 or so members always in the same context, I want to predefine the subject with "[Context] ..." when starting a new mail.

I didn't find a plugin for that, so I'm looking for the code to realize it by hand and hardcoded.

Where can I find the respective code?

And, yes: I'm aware of the fact that this "hack" can be overwritten by an RC update.

Best

**Comment by alecpl** [comment]
Look for "subject" in `program/include/rcmail_sendmail.php`.
