### ISSUE TITLE
When starting a new email showing BCC by default?

### ISSUE THREAD

**Issue by LoSong** [roundcube/roundcubemail#9384]
Hi, 

since I'm using Roundcube for sending emails to a closed community of 100 or so members I want to enable the BCC: field by default when starting a new email.

I didn't find a plugin or setting for that, so I'm looking for the code to realize it by hand and hardcoded.

Where can I find the respective code?

BTW: It would be nice to preset my own email address in the TO: field too, but that's optional.

And, yes: I'm aware of the fact that this "hack" can be overwritten by an RC update.

Best

**Comment by alecpl** [comment]
Just define an identity with Bcc.
