### ISSUE TITLE
Upgrade issues to 1.6x from 1.5x

### ISSUE THREAD

**Issue by jasonmacer** [roundcube/roundcubemail#9385]
Earlier today I attempted a 1.4.2 to 1.6 update using the master branch, and it failed when attempting to install via ./bin/installto.sh and was "PHP Fatal error:  Uncaught Error: Class "GuzzleHttp\Client" not found". I was however able to update using the 1.5 branch. I am working to get the ispconfig3 plugins working so users can change their passwords. This feature is still not working and I am getting an "Soap Error: Could not connect to host", so i decided to try and upgrade to the 1.6 branch. I was able to download and extract roundcubemail-release-1.6 from the 1.6 zip file, and then I was able to upgrade it successfully.

After the upgrade when I visit there is now the following error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0".

This is a CentOS 7.9 machine running php 8.1 as the default php version. 

```
[root@vhost001 roundcubemail-release-1.6]# php -v
PHP 8.1.27 (cli) (built: Dec 19 2023 20:35:55) (NTS gcc x86_64)
```

It did originally have a 7.3.x version of PHP, but it was upgraded to 8.1, and then 7.3.x and 5.x were installed to support some specific needs. As mentioned earlier I am running ISPConfig 3, and when i throw a phpinfo.php file in the ISPConfig www directory it comes back as PHP Version 8.1.27. When I do the same in the roundcube/public_html folder it returns that the roundcube directory is using PHP Version 7.4.33.

How in the world is roundcube doing this when it should be using the default php version of the system, which is PHP Version 8.1.27.

Is there a setting I am missing somewhere?

Thanks!

**Comment by alecpl** [comment]
You're missing composer dependencies. If you get the full Roundcube package they are in `vendor` folder. If you have composer run `composer update`. If not make sure `vendor` folder is from the version you installed.
