### ISSUE TITLE
Migrated to Elastic - Settings -> Mailbox View -> Layout

### ISSUE THREAD

**Issue by micaelbolognini** [roundcube/roundcubemail#9386]
After upgrading to new version of Roundcube and elastic (dont know what the previous theme was based on). But I copied elastic and made my changes. But I see a setting that is not in the elastic theme:

![Skärmavbild 2024-03-15 kl  15 06 31](https://github.com/roundcube/roundcubemail/assets/1046797/48180508-26d4-489b-b544-de919c152fa3)

How do I get rid of that setting ?

**Comment by alecpl** [comment]
You removed config.supported_layouts from skins's `meta.json` file.

**Comment by micaelbolognini** [comment]
I did not.
