### ISSUE TITLE
How to ok Intl

### ISSUE THREAD

**Issue by Fate970730** [roundcube/roundcubemail#9387]
How can I enable
Intl: NOT OK(See https://www.php.net/manual/en/book.intl.php)
![Képernyőfelvétel (49)](https://github.com/roundcube/roundcubemail/assets/119739818/dcdbbfe7-60af-49ba-9e5b-ac9287bd48ff)

**Comment by nicofrand** [comment]
This is explained for various OS in the comments of the link provided: https://www.php.net/manual/en/intl.installation.php
