### ISSUE TITLE
Text instead of a table when forwarding HTML emails

### ISSUE THREAD

**Issue by tehabe** [roundcube/roundcubemail#9391]
For some reason when I forward an HTML email the sender information of the original email are put into a table instead of just a text. This is can break the layout in some cases.

**Comment by alecpl** [comment]
It's a table for HTML, and plain text for plain messages.

**Comment by tehabe** [comment]
I know. But I think this behaviour is a mistake because tables make it harder to deal with emails and it makes not much sense. I've seen layout issues in some clients. It is harder to copy something out of a table. etc. pp.
