### ISSUE TITLE
View headers: Close button didn't work

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9397]
Here no matter how many times I pushed the "X Close"  button, it wouldn't close.

![Screenshot_20240324_210544_Chrome Beta.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/35476442-18b8-4dc8-9136-1c684649d8dd)

**Comment by alecpl** [comment]
What Roundcube version? What browser? What plugins? Any error in browser console?

**Comment by jidanni** [comment]
Hmmm, view-source:https://webmail.dreamhost.com/ doesn't reveal the version. 

OK, copying "About" shows...

<h2 class="sysname" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: bold; line-height: 1.2; font-size: 1.5em; color: rgb(15, 60, 81); font-family: Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Roundcube Webmail 1.4.3</h2><p class="copyright" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(15, 60, 81); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Copyright © 2005-2020, The Roundcube Dev Team</p><p class="license" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgb(15, 60, 81); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">This program is free software; you can redistribute it and/or modify it under the terms of the<span> </span><a href="http://www.gnu.org/licenses/gpl.html" target="_blank" style="box-sizing: border-box; color: rgb(0, 115, 236); text-decoration: none; background-color: transparent;">GNU General Public License</a><span> </span>as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.<br style="box-sizing: border-box;">Some<span> </span><a href="https://roundcube.net/license" target="_blank" style="box-sizing: border-box; color: rgb(0, 115, 236); text-decoration: none; background-color: transparent;">exceptions</a><span> </span>for skins &amp; plugins apply.</p><div class="readtext table-responsive-sm" style="box-sizing: border-box; color: rgb(15, 60, 81); font-family: Roboto, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h3 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: bold; line-height: 1.2; font-size: 1.25em;">Installed plugins</h3>
Plugin | Version | License | Source
-- | -- | -- | --
archive | 3.4 | GPLv3+ |  
filesystem_attachments | 1.0 | GPLv3+ |  
jqueryui | 1.12.0 | GPLv3+ |  
zipdownload | 3.4 | GPLv3+ |  

</div>Roundcube Webmail 1.4.3
Copyright © 2005-2020, The Roundcube Dev Team

This program is free software; you can redistribute it and/or modify it under the terms of the [GNU General Public License](http://www.gnu.org/licenses/gpl.html) as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
Some [exceptions](https://roundcube.net/license) for skins & plugins apply.

Installed plugins
Plugin	Version	License	Source
archive	3.4	[GPLv3+](http://www.gnu.org/licenses/gpl-3.0.html)	
filesystem_attachments	1.0	[GPLv3+](http://www.gnu.org/licenses/gpl-3.0.html)	
jqueryui	1.12.0	[GPLv3+](http://www.gnu.org/licenses/gpl-3.0.html)	
zipdownload	3.4	[GPLv3+](http://www.gnu.org/licenses/gpl-3.0.html)
