### ISSUE TITLE
Unclear what LTS versions exist

### ISSUE THREAD

**Issue by T3rm1** [roundcube/roundcubemail#9399]
I couldn't find any reliable information about what LTS versions currently exists. The download page suggests that 1.5 is the only LTS version. Is this really true?

In Oct 2023 was a security release 1.6.4 / 1.5.5 / 1.4.15. So 1.4 was still supported back then. Then, one month later in Nov 2023, was another security release but only 1.6.5 / 1.5.6. No patch for 1.4. 

Does that mean there was nothing to fix for 1.4 or does it mean 1.4 ran out of LTS support? Where can I find information how long a LTS version is supported?

**Comment by alecpl** [comment]
There's no written policy for LTS. We drop support when we decide it's a burden to continue. The 1.5 will probably continue to be supported until the next major release, but this is not set in stone. https://roundcube.net/download/ lists the supported versions.

ps. I write "we", but this is essentially only on my plate currently.

**Comment by T3rm1** [comment]
Ok, so this means that for 1.4 further support was dropped with the 1.4.15 release. It would be nice if you could mention such an important decision in the release notes in the future. Thank you.

**Comment by alecpl** [comment]
It was noted in the news https://roundcube.net/news/2023/10/16/security-updates-1.5.5-and-1.4.15
