### ISSUE TITLE
Out of Office start and end time decrease by 1 day after saving and reloading page

### ISSUE THREAD

**Issue by ryansumma** [roundcube/roundcubemail#9403]
When I set an out of office date range, save it and reload the page it displays a different date than what I have set. To be more precise it is one day earlier.

for example when I set April 2nd to April 3rd, save and reload the page, I will be displayed April 1st to April 2nd. When I click on save and reload again, it will show March 31st to April 1st. 

My colleague can not reproduce this behavior. I have tried different browser and private sessions and emptying cache.

Anyone have an idea where I can start looking?

**Comment by alecpl** [comment]
Managesieve plugin has a debug option. I'd start there. Also, what Roundcube version? What date/time format in Preferences > User Interface? What PHP version? What timezone?

**Comment by alecpl** [comment]
No feedback. Not way to reproduce.

**Comment by mustenero** [comment]
Hi,
I can reproduce this issue consistently in Roundcube 1.7.2. Could this issue be reopened?

The timezone in the PHP configuration, Roundcube `config.inc.php`, and the user's settings is set to `Europe/Warsaw`. In July, the applicable offset is UTC+2.

Steps to reproduce:

1. Open the Out of Office settings.
2. Set the vacation period from `2026-07-15` to `2026-07-30`.
3. Leave the time fields empty, so the default time is `00:00`.
4. Save the settings.
5. Refresh or reopen the Out of Office page.

After reopening the page, Roundcube displays the period as `2026-07-14` to `2026-07-29`, one day earlier than the dates originally selected.

The generated Sieve filter contains the correct dates:

```sieve
currentdate :zone "+0200" :value "ge" "date" "2026-07-15"
currentdate :zone "+0200" :value "le" "date" "2026-07-30"
```

Therefore, the dates are saved correctly in the Sieve script, but they are displayed one day earlier in the Roundcube user interface.

The date is displayed correctly only when I explicitly set the start time to `02:00`. For example:

```sieve
currentdate :zone "+0200" :value "ge" "iso8601" "2026-07-15T02:00:00+02:00"
```

With `02:00`, the date is shown correctly as `2026-07-15`. With `00:00`, it is displayed as `2026-07-14`.

This suggests that the date is converted to UTC when the form is displayed, without being converted back to the user's `Europe/Warsaw` timezone.

**Comment by alecpl** [comment]
So, we call `rcmail::format_date()` which:
- calls `rcube_utils::strtotime()` with `$timezone=null`, which converts Y-m-d date into an integer (UTC) timestamp.
- converts the timestamp into DateTime object (`new \DateTime('@' . $timestamp)`), which uses the current timezone, instead of UTC.

So, something like this may work:
```diff
--- a/program/include/rcmail.php
+++ b/program/include/rcmail.php
@@ -1610,7 +1610,7 @@ class rcmail extends rcube
             }
 
             try {
-                $date = new \DateTime('@' . $timestamp);
+                $date = new \DateTime('@' . $timestamp, new \DateTimeZone('UTC'));
             } catch (\Exception $e) {
                 return '';
             }

```
but I feel this may also break other cases.

**Comment by alecpl** [comment]
> So, we call `rcmail::format_date()` which:
> 
>     * calls `rcube_utils::strtotime()` with `$timezone=null`, which converts Y-m-d date into an integer (UTC) timestamp.
>     * converts the timestamp into DateTime object (`new \DateTime('@' . $timestamp)`), which uses the current timezone, instead of UTC.

No. I was wrong. This DateTime object will use UTC timezone. Which means I don't know how to reproduce and what's going on.

**Comment by alecpl** [comment]
Ok, I found it in the end. `strtotime()` is shifting the timestamp if PHP timezone is other than UTC. That being said, the fix might not be straightforward.

Without even testing this yet, maybe just:
```diff
--- a/program/lib/Roundcube/rcube_utils.php
+++ b/program/lib/Roundcube/rcube_utils.php
@@ -1171,7 +1171,7 @@ class rcube_utils
     public static function strtotime($date, $timezone = null)
     {
         $date = self::clean_datestr($date);
-        $tzname = $timezone ? ' ' . $timezone->getName() : '';
+        $tzname = $timezone ? ' ' . $timezone->getName() : ' UTC';
 
         // unix timestamp
         if (is_numeric($date)) {

```

**Comment by mustenero** [comment]
UTC not working :(

This looks ok, for timezone Europe/Warsaw GMT +01:00

```diff
--- a/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php
+++ b/plugins/managesieve/lib/Roundcube/rcube_sieve_vacation.php
@@ -458,7 +458,7 @@ class rcube_sieve_vacation extends rcube_sieve_engine
             foreach (['from', 'to'] as $idx) {
                 if ($value = $date_value[$idx] ?? null) {
                     $date = !empty($value['datetime']) ? $value['datetime'] : $value['date'];
-                    $date_value[$idx] = $this->rc->format_date($date, $date_format, false);
+                    $date_value[$idx] = $this->rc->format_date($date, $date_format, true);
 
                     if (!empty($value['datetime'])) {
                         $date_value['time_' . $idx] = $this->rc->format_date($date, $time_format, true);
```

Not working with GMT -03:00 set in user preference, when I use empty time field for 2026-07-16:

```sieve
currentdate :zone "-0300" :value "ge" "iso8601" "2026-07-11T02:00:00-03:00", currentdate :zone "-0300" :value "le" "date" "2026-07-16")
```

When set 00:00 in time field and GMT -03:00 date shows ok in roundcubemail and sieve add iso8601 in configuration:

```sieve
currentdate :zone "-0300" :value "ge" "iso8601" "2026-07-11T02:00:00-03:00", currentdate :zone "-0300" :value "le" "iso8601" "2026-07-16T00:00:00-03:00")
```

**Comment by alecpl** [comment]
Your patch is not acceptable, I'm afraid. You mean my patch is not working? From what I see it should not matter what user timezone is, it matters what PHP timezone is. The point is to not convert the timezone. What PHP version?

**Comment by mustenero** [comment]
> Your patch is not acceptable, I'm afraid. You mean my patch is not working? From what I see it should not matter what user timezone is, it matters what PHP timezone is. The point is to not convert the timezone. What PHP version?

php 8.4
timezone in php Europe/Warsaw

**Comment by alecpl** [comment]
I set `date.timezone=Europe/Warsaw` in php.ini, and set user timezone in preferences the same. Without any patches I can reproduce the issue. My patch fixes it. Tested on PHP 8.4.

**Comment by mustenero** [comment]
> I set `date.timezone=Europe/Warsaw` in php.ini, and set user timezone in preferences the same. Without any patches I can reproduce the issue. My patch fixes it. Tested on PHP 8.4.

Yes, sorry you right, I change it manually and didn't add space before UTC.
Your fix works perfectly :)

**Comment by alecpl** [comment]
Fixed.
