### ISSUE TITLE
Roundcube mail not attaching .jpg in header anymore. Happened overnight

### ISSUE THREAD

**Issue by nmmatw** [roundcube/roundcubemail#9411]
First of all, forgive me, I am not a programmer or even in the IT field. I am trying to fix an issue that affects my team as best I can with my limited knowledge and resources. 

We have clients that have the ability to send us 'alerts' from their individual PCs via a mailsend.exe which routes to roundcube mail through a cPanel server. Roundcube then forwards our agents an email as an alert to our company Outlook mail so that they can remote into the client PC and resolve their technical support issue. 

We get the email alerts just fine but overnight from 2/1/24 to 2/2/24 the email alerts became jumbled and no longer display properly. The alert inline attaches a facility.txt file which appears as the body text and is supposed to attach a .jpg file that is a screenstream image to give our agents a quick overview of the clients desktop so they have an idea of what the issue is before connecting. 

Here is what the email looked like in roundcube on Feb 1st, client info has been redacted: 
![2 1 24 alert](https://github.com/roundcube/roundcubemail/assets/166137564/dd6efd3f-4947-4c2f-ab50-7c9eba0ef672)

And here is what it looked like after on Feb 2nd:
![2 2 24 alert](https://github.com/roundcube/roundcubemail/assets/166137564/749b9d06-bc15-403d-b659-14e30e513a64)

I know it shows Feb 1st in the screenshot, the email was sent form a different timezone but arrived Feb 2nd EST.

Here is how the emails appeared in Outlook prior to Feb 2nd with the .jpg file at the top then the facility.txt file embeds inline in the body neatly:
![Outlook Before](https://github.com/roundcube/roundcubemail/assets/166137564/d7408416-ac1e-4d51-be09-5df9bdd3d1f7)

And here is how it appears now, after Feb 2nd:
![Outlook After](https://github.com/roundcube/roundcubemail/assets/166137564/e9d477d2-5412-4b89-b761-4588dddf718f)

If the client does not have a screenstream .jpg then the facility.txt attaches as normal and is embedded inline the email body just fine, but if a .jpg file is available then it sends the jumbled coded email. I'll put in the mailsend code in for what we have on each PC, the code itself has not been changed on the PCs but I'll blank where I have to conceal our information.

IF EXIST "C:\Windows\system\web\screenstream*.jpg" (GOTO EMLP) ELSE (GOTO EML)

:EMLP
ren c:\windows\system\web\screenstream*.jpg screenstream.jpg
mailsend -name "M2 ALERT" -f ins********.com -smtp mail.*******.com -port 465 -sub "INSTANT ******** ALARM" -attach "c:\windows\system\facility.txt,text/plain,i" -attach "C:\Windows\system\web\screenstream.jpg,img/jpg" -t p*******@m*****.com -cc p******@m*****.com +bc e*********@m******.com  -ssl  -auth -user ins**********@m******.com -pass 2********
exit
:EML
mailsend -name "M2 ALERT" -f ins********.com -smtp mail.******.com -port 465 -sub "INSTANT ******* ALARM" < c:\windows\system\facility.txt -t p*******@m******.com -cc p*****@m****.com +bc e*********@m*****.com -ssl  -auth -user ins*******@m******.com -pass 2*******
exit

I'm wondering if there is something that could have changed either with cPanel or roundcube mail that I can change back since this seems to have happened over night and is happening with each and every client when they send an 'alert' to us. I have also routed the mailsend on a demo PC to different emails in gmail and icloud to see if it was a platform issue and it persist on all mail platforms. I think the source of the issue lies either in roundcube or cPanel but after poking around I can't find any settings that seem to have caused this. HTML is set to display in display message and composed messages for both roundcube and Outlook. 

If there is any insight to this, I'd be really appreciative. Again, I have no IT background, so I am very out of my depth here. I have almost no knowledge of roundcube and very little on cPanel as this set up was established quite a while ago long before I was part of my current team. All I know is the roundcube only seems to be a sort of springboard to forward the emails to our team on Outlook after the 'alert' button is pressed on a client pc and the mailsend.exe sends the information from the client PC to the cPanel server/roundcube mail which then forwards to the teams Outlook mail. 

If more information is needed I can try to provide it as best I can.

**Comment by alecpl** [comment]
The message structure is probably broken. Hard to tell without seen the full message source. Anyway, such issues are better asked on the forum.

**Comment by nmmatw** [comment]
> The message structure is probably broken. Hard to tell without seen the full message source. Anyway, such issues are better asked on the forum.


Understood, forgive my ignorance, could you point me in the direction of the forum? I am brand new to this site. Thanks!
