### ISSUE TITLE
Security vulnerability in Roundcube Framework

### ISSUE THREAD

**Issue by CTIHUY** [roundcube/roundcubemail#9413]
Vulnerability information has been sent through email.

**Comment by CTIHUY** [comment]
I sent to ***@***.*** also attached the report in this reply as
well.


Vào Th 6, 12 thg 4, 2024 vào lúc 16:24 Aleksander Machniak <
***@***.***> đã viết:

**Comment by CTIHUY** [comment]
I sent to hello@roundcube.net. I also attached the report in the reply email.

**Comment by alecpl** [comment]
This is the current policy on how to report security issues. https://github.com/roundcube/roundcubemail/security/policy
