### ISSUE TITLE
163 & 126 Mail Error,is support IMAP4 ID extension ?

### ISSUE THREAD

**Issue by cailong-dot** [roundcube/roundcubemail#9414]
+ OS:Gentoo Linux
+ Version:roundcube 1.6.6 compiled with change-password enigma exif fileinfo ldap postgres ssl vhosts zip 

### how can i do it?

**Comment by alecpl** [comment]
You probably just should configure Roundcube to use SSL/TLS.

**Comment by cailong-dot** [comment]
> You probably just should configure Roundcube to use SSL/TLS.
i configure imap & smtp as "ssl://smtp.163.com:465",but there are still issues

**Comment by cailong-dot** [comment]
i configure imap & smtp as "ssl://smtp.163.com:465",but there are still issues
