### ISSUE TITLE
i configure imap & smtp as "ssl://smtp.163.com:465",but there are still issues

### ISSUE THREAD

**Issue by cailong-dot** [roundcube/roundcubemail#9415]
You probably just should configure Roundcube to use SSL/TLS.

_Originally posted by @alecpl in https://github.com/roundcube/roundcubemail/issues/9414#issuecomment-2051037824_

**Comment by alecpl** [comment]
Please, go to https://www.roundcubeforum.net/ for help. This is not a bug.
