### ISSUE TITLE
Mouseover should always work, even if only the final word is truncated

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9416]
We are looking at the subjects in our inbox.

If we place the mouse upon this truncated title,

![Screenshot 2024-04-13 18 36 47](https://github.com/roundcube/roundcubemail/assets/1230959/fca41376-d5d8-4f99-91fd-d269b7a065b9)

indeed, a mouseover appears telling us the full title.

Except,
- if the "..." occurs on the final word

In such case, to learn what the rest of that word was, we can only
- guess, or
- open the message to see.

What's worse, if the "..." represent some CJK characters, then the "rest of the word" might represent a pretty significant amount of information!

Solution: the mouseover should show the whole Subject in all cases.

**Comment by alecpl** [comment]
Indeed the method we use is not precise enough. Some adjustments might be needed around `rcube_webmail.long_subject_title()`.

**Comment by alecpl** [comment]
Fixed.
