### ISSUE TITLE
stop removing style tags in wash_html

### ISSUE THREAD

**Issue by petersphilo** [roundcube/roundcubemail#9417]
Hello,

First, thank you so much for your work on RoundCube!

Would it be possible to stop removing 'style' tags in wash_html?

That would allow us to use custom css classes in signatures (or even in the body)..

i understand the possibility of namespace conflicts, but that seems like a risk worth taking..
or perhaps adding a config option in the main config file that switches between excluding styles tag and not excluding it?

Thank You So Much!

**Comment by alecpl** [comment]
I suppose it's a duplicate of #9338.

**Comment by petersphilo** [comment]
Sorry about that!
i couldn't find the other one for some reason..
Thank You!
