### ISSUE TITLE
cPanel RoundCube is down.

### ISSUE THREAD

**Issue by Secmas** [roundcube/roundcubemail#9421]
My server is cPanel using CloudLinux and it has RoundCube for webmail, but since this morning RoundCube is not showing any email info instead it shows:
Oops... something went wrong!
An internal error has occurred. Your request cannot be processed at this time.
For administrators: Please check the application and/or server error logs for more information.

Tried running:
1. rpm -qa | grep -i roundcube:
cpanel-roundcubemail-1.6.6.0-4.cp120~el9.noarch

2. Uninstalling only the Roundcube package:
rpm -e --justdb --nodeps cpanel-roundcubemail-1.5.2.1-6.cp11106.noarch

3. Use the check_cpanel_pkgs script to reinstall the appropriate Roundcube package, answering "y" at the prompt:
/scripts/check_cpanel_pkgs yes

But with no luck at all.

Any idea how to make RoundCube to work again?

Thanks.

**Comment by alecpl** [comment]
Check the Roundcube or PHP or HTTP server logs.
