### ISSUE TITLE
Make horizontal bars easier to see

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9425]
In this image there are three horizontal colored bars,
![Screenshot 2024-04-22 23 17 09](https://github.com/roundcube/roundcubemail/assets/1230959/414314e2-2397-4500-bf10-34d4401a4d7f)
But they are almost too light or thin to notice.
Therefore one's eye depends on the black dots etc. to tell the where one message ends and the next begins.

Roundcube version: No idea. No way to tell anymore. Sorry. I am just a https://webmail.dreamhost.com/ end user.

**Comment by alecpl** [comment]
It's been discussed before. This is not gonna happen.

**Comment by jidanni** [comment]
![Screenshot_20240503_224503_Chrome Beta.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/c6ba0968-d301-4c50-9f90-1964a4619193)

Well okay, but I would put the author below the subject. Because the subject is in such a bold face etc, that it is just like a header in HTML. So we expect things associated with that header to follow it.
