### ISSUE TITLE
Invalid request: default login page not working

### ISSUE THREAD

**Issue by HLFH** [roundcube/roundcubemail#9426]
`$request_valid` is returned false but username and password are correct.
In `index.php`:
```
$request_valid = !empty($_SESSION['temp']) && $RCMAIL->check_request();
```
The `check_request()` public function from https://github.com/roundcube/roundcubemail/blob/release-1.6/program/lib/Roundcube/rcube.php seems faulty.

The login of this page https://mail.example.com does not work (it raises an invalid request error) but this page https://mail.example.com/?_task=login works.
When https://mail.example.com sign in does not work, it redirects to https://mail.example.com/?_task=login that works (but where I have to login again).
It seems weird.

Version: 1.6.6

EDIT: it seems this code is raised:
```
        if (empty($_COOKIE[ini_get('session.name')]) || $token !== $sess_tok) {
            $this->request_status = self::REQUEST_ERROR_TOKEN;
            return false;
        }
```
The cookie is empty and $token differs from $sess_tok.

**Comment by alecpl** [comment]
No one has such issues, so I suppose something's wrong with your Roundcube setup. Try to get help on mailing list or forum.
