### ISSUE TITLE
Where is option to disable mail preview? (1.6.6)

### ISSUE THREAD

**Issue by Marxsal** [roundcube/roundcubemail#9432]
The mail preview takes up 2/3 of the screen and isn't needed. I went through the various settings and options and did not see the option to disable the preview. (That option is mentioned in documentation for 1.1).

Thank you!

**Comment by Dennis1993** [comment]
See here: https://github.com/roundcube/roundcubemail/issues/6458

**Comment by Marxsal** [comment]
So a feature that's been in there for a decade got dropped because someone randomly didn't find it personally useful?
