### ISSUE TITLE
Roundcube mail - Forgot Password option at Web Login Page

### ISSUE THREAD

**Issue by ikochar** [roundcube/roundcubemail#9433]
Requesting the introduce of the "Forgot Password" option in the upcoming update of Roundcube Mail **login Page**. This feature was missing in the all version, and it is an essential tool for managing multiple users who may forget their passwords.

The "Forgot Password" option is incredibly useful as it allows users to easily reset their passwords by receiving a link via email to their alternate email address. This streamlined process helps users regain access to their accounts without the need for manual intervention, reducing support requests and improving user experience.

I urge the development team to prioritize of this feature of Roundcube WebMail Login Page. 
I am using roundcube version 1.6.6.

**Comment by alecpl** [comment]
Problem is that an external email is usually not kept in a mail client. That does not mean it can't be added, but it can be done in many ways and is an idea for an external plugin.
