### ISSUE TITLE
3 bar menu clipped

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9435]
I clicked on the three bar menu, and this is what I saw.

![Screenshot_20240503_225254_Chrome Beta.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/46bbf5f6-a8d6-4633-ac24-1237a6f0fe69)

Seen at webmail.dreamhost.com. 

No I don't own the site, I'm just a simple user.

**Comment by alecpl** [comment]
Looks like a custom skin.
