### ISSUE TITLE
Possible IMAP UIDVALIDITY Issue: SEARCH search key not supported

### ISSUE THREAD

**Issue by ryanthomas-org** [roundcube/roundcubemail#9437]
Upon logging in successfully to IMAP, I am greeting with a `Server Error: UID SEARCH: SEARCH search key not supported` error. This error displays any time the inbox is loaded including upon login.

No messages display in the inbox although they should be there.

I suspect this is related to the fact that my mail host uses a 64-bit UIDVALIDITY. Mail clients like Thunderbird and Mutt accommodated these by truncating the value: https://github.com/neomutt/neomutt/commit/a8b82212d0e308fd741d386d4592aea2f14b55bf

This may be a violation of an IMAP standard but one common enough that other IMAP clients patch for it. I have been unsuccessful in getting my otherwise extremely reliable email (and DNS) host to do anything about it on their end.

Is this something that could easily be done here?

**Comment by alecpl** [comment]
I don't think this is UIDVALIDITY related. Could you enable imap_debug in Roundcube config and provide the log?

**Comment by ryanthomas-org** [comment]
Thank you for the follow up. I ended up finally switching mail hosts (from Dynadot) which did resolve this. Since I can't provide the log I'll close this out. Thanks again
