### ISSUE TITLE
Error in rcube_db.php on line 202

### ISSUE THREAD

**Issue by jkdi** [roundcube/roundcubemail#9439]
Since updating yesterday, i have this error: 

Apache:
++++++++++++++++++++++++
Oops... something went wrong!

An internal error has occurred. Your request cannot be processed at this time.

For administrators: Please check the application and/or server error logs for more information.
++++++++++++++++++++++++

Log:
[06-May-2024 06:39:35 +0000]: <7mel46fs> DB Error: SQLSTATE[HY000] [2002] No such file or directory in /usr/share/roundcube/program/lib/Roundcube/rcube_db.php on line 202 (GET /webmail/)

Line 202 shows this:
'line' => __LINE__, 'file' => __FILE__,

i change nothing in configuration ....

**Comment by alecpl** [comment]
Look for a fatal error in php/http server log.

**Comment by GLeurquin** [comment]
If anyone is getting this issue on truenas, what solved it for me is to delete all datasets for config, html and temps. Recreate them, and run `chmod -R www-data:www-data config`, `chmod -R www-data:www-data html`, `chmod -R www-data:www-data temps` BEFORE starting roundcube for the first time. For me it was a permission issue.
