### ISSUE TITLE
Mail delivery failed: returning message to sender

### ISSUE THREAD

**Issue by NoerSalehh** [roundcube/roundcubemail#9442]
Hi there,

I have a issue with roundcube webmail when sending emails to other email adresses. I can recieve emails with no problems but when i compose a email to send other adresses i get the following error (foodticket is the company im trying to reach via email) :

_This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [support+id485694@foodticketsupport.zendesk.com](mailto:support+id485694@foodticketsupport.zendesk.com)
    retry timeout exceeded
Reporting-MTA: dns; placeholder.transip.us

Action: failed
Final-Recipient: rfc822;[support+id485694@foodticketsupport.zendesk.com](mailto:support+id485694@foodticketsupport.zendesk.com)
Status: 5.0.0_

Does anyone have a fix for this error?

**Comment by alecpl** [comment]
Not Roundcube issue.
