### ISSUE TITLE
Oauth redirect uri

### ISSUE THREAD

**Issue by amend07** [roundcube/roundcubemail#9445]
Hello there,

recently I am working integration of roundcube with keycloak. After configuring all setup in the config.inc.php and defaults.inc.php file. After successful authentication using keycloak it redirected back to /index.php/login/oauth and shows "404 Not Found" error.

I checked similar error in https://github.com/roundcube/roundcubemail/issues/8191 but it confuses me how to configure the nginx server configuration. Is there any one who can help me?

with regards,

**Comment by alecpl** [comment]
Nginx configuration is out of scope for this bug tracker. Ask on mailing list or forum.
