### ISSUE TITLE
Mobile view is broken - no mails list

### ISSUE THREAD

**Issue by omegaholos** [roundcube/roundcubemail#9446]
Hi, I have a problem with my roundcube (1.6.0 and 1.6.6). On mobile after login screen I have blank screen, without mail list. Is there anything I could to get access to my mail list from mobile? (Problem occurs only in vertical view, checked on 3 smartphones and scaled down browser windw).
I have tried changing language and dark/light modes.

![screen](https://github.com/roundcube/roundcubemail/assets/169442983/2faa4695-5f49-4738-9d1c-702da90ec2b4)

**Comment by alecpl** [comment]
What plugins do you have enabled? Any errors in browser console? What is the exact screen size in pixels when that happens? What browser version?
