### ISSUE TITLE
The interface has changed.

### ISSUE THREAD

**Issue by contatondc** [roundcube/roundcubemail#9451]
Is it possible to use the old interface? I didn't find this option in the settings anymore.

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.

**Comment by pabzm** [comment]
@contatondc What do you mean by "interface"?

I had a different interpretation than @alecpl so I'm a little confused and would like to clarify.

**Comment by alecpl** [comment]
I've seen a few tickets recently where people noticed their webmail skin changed. Probably someone installed a Roundcube update on their servers without taking care about skins. The old Larry skin can still be installed, but is not included in the vanilla package. There's not much we can do about it.

**Comment by pabzm** [comment]
@alecpl Maybe people don't realize they can simply install "Larry" to get it back (which is great!), I wasn't sure about it either. So let's just repeatedly tell them :)

**Comment by alecpl** [comment]
Maybe, but I think that it's end-users that complain to us instead to their hosts.

**Comment by jidanni** [comment]
Actually I found a skin called Larry and turned it on. But it's totally not ready for a mobile phone.
