### ISSUE TITLE
Force factory skin choice to still be available, always

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9453]
In the following bug report, I will make the point, that is very important to leave the roundcube original skin as one of the choices in the skin list available to the user. 

It's going to take a while for me to fill in this bug report completely so please bear with me.

In the following image, we see the middleman provider has painstakingly created their own skins, two of them. 

![Screenshot_20240518-125218.jpg](https://github.com/roundcube/roundcubemail/assets/1230959/b823caa0-1550-4c89-bbbc-1e9ae12bdaba)

They have put in a lot of work and they're very happy with them, and they've even provided this instruction sheet about them.

https://help.dreamhost.com/hc/en-us/articles/360037700232-Changing-your-Webmail-Layout

The problem is, it's very hard for them to make sure they're skins will keep on working upgrade through upgrade. They just don't have all the different devices they need to test it. 

Therefore if a user with a certain device is having bad luck with one of their skins, it would be great to always have a final choice in that list, no matter if you want to call it vanilla, or if you want to call it factory, or original flavor or whatever just be sure to have the choice of whatever roundcube comes shipped with. Right there in the last place in the menu, with no way for that third party middleman to remove!

Let's examine what happens when a user tries to file the instructions in the above hyperlink I showed. 

Well they are supposed to go visit their preferences, but according to the image in 
https://github.com/roundcube/roundcubemail/issues/9435
we see they are not going to even be able to get to their preferences!

Okay that's about skins, now about plugins. Well I suppose the same problem might happen with plugins. Therefore there should be a choice somewhere to allow the **end** user to turn off all plugins too.

**Comment by alecpl** [comment]
We can't prevent the host from modifying Roundcube code (or just adding plugins that change/remove some features). Quite opposite, we provide people with tools to modify Roundcube installation to their needs. So, nope.

**Comment by alecpl** [comment]
I'll add that a request to make enabling/disabling some plugins by an end-user would make more sense, but for skins, not that much.

**Comment by jidanni** [comment]
In fact in my above image, you'll see Larry is called "Dreamhost Larry."  That means they messed up both of their skins. Leaving zero choices for the user to continue on reliably.

I assume they didn't fork the GitHub project and make their own version of Roundcube. Therefore Roundcube still has some control about leaving one guaranteed working fallback in the  skin list shown to the end user.

**Comment by alecpl** [comment]
It's open source, we have no control on someone else's installation, and we don't want to.
