### ISSUE TITLE
webmobile not sending or receiving mail

### ISSUE THREAD

**Issue by cdebeer47** [roundcube/roundcubemail#9459]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its recipients. This is a permanent error. The following address(es) failed:

  [@webmobile.co.za](mailto: @webmobile.co.za)
    host mail.webmobile.co.za [51.159.102.174]
    SMTP error from remote mail server after RCPT TO:<[@webmobile.co.za](@webmobile.co.za)>:
    554 5.7.1 <[@webmobile.co.za](@webmobile.co.za)>: Relay access denied
    <html>
<body>

Message not delivered Your message couldn't be delivered to @webmobile.co.zabecause the remote server is misconfigured. See the technical details below for more information. | Message not delivered Your message couldn't be delivered to @webmobile.co.za because the remote server is misconfigured. See the technical details below for more information. 
The response from the remote server was:
554 5.7.1 : Relay access denied

**Comment by cdebeer47** [comment]
i regestered my self many years ago online, issues started after roundcube update middle of last month. its a server error

**Comment by alecpl** [comment]
We provide the IMAP client software not the server (service). Whatever it is it's not a Roundcube issue. Maybe some configuration regarding SMTP needs some love.

**Comment by cdebeer47** [comment]
i dont know how to do this https://www.mailhub.co.za does not have smtp settings.
