### ISSUE TITLE
Gravatar

### ISSUE THREAD

**Issue by eveneme** [roundcube/roundcubemail#9464]
Option to add a Gravatar that will be displayed in other email clients, such as Gmail. It would be great if the Gravatar also appeared in the message list in Roundcube.

**Comment by johndoh** [comment]
A plugin already exists https://plugins.roundcube.net/#/packages/prodrigestivill/gravatar

**Comment by pabzm** [comment]
Closing this because there's the mentioned plugin for that feature. If you don't agree please let us know.
