### ISSUE TITLE
Enable php-intl Dependency

### ISSUE THREAD

**Issue by maybeizen** [roundcube/roundcubemail#9471]
So, a small issue with this part of RoundCube. I can't it to pick up php-intl anywhere on my system.

![image](https://github.com/roundcube/roundcubemail/assets/135663611/9a2fd065-6f8c-4d67-8dd0-5114306dd5c6)

I've reinstalled RoundCube, installed and reinstalled php-intl with `apt-get`, and followed the PHP documentation with little help.

Regardless, this issue continues to persist. Any information I am willing to provide, just for some simple assistance.

**Comment by alecpl** [comment]
PHP packages installation is out of scope of this bug tracker. On systems with multiple php versions you need to install proper package for currently used version, also do not forget to restart apache or php-fpm process.
