### ISSUE TITLE
"List columns" preferences not saved 

### ISSUE THREAD

**Issue by digiacs** [roundcube/roundcubemail#9474]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

In the mail view, click the "List options..." icon next to the Subject column
Select anything under "List columns"
Click "save"
Nothing happens and the preference is not saved.

### What version of Roundcube are you using?

160 on Chrome

**Comment by pabzm** [comment]
I'm guessing you're using the "Larry"-skin with a "Desktop" or "List" layout, is that right?

With Roundcube version 1.6.7 I cannot reproduce that problem. If I select other columns they get shown.

Can you update Roundcube to the latest release?

And/or send us a screenshot of your situation, in which the problem occurs?

**Comment by alecpl** [comment]
No feedback.
