### ISSUE TITLE
setting seems missing for horizontal alignment of e-mail list and "reading pane"

### ISSUE THREAD

**Issue by bob7vogel** [roundcube/roundcubemail#9478]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

since starting with Roundcube i have had my e-mail list on top of the screen and any selected single e-mail on the bottom of the screen.  With the latest release that option (just today 6/3) seems to be gone in settings.  Am i missing the right place to configure?  Was it removed by accident?  Screen shot enclosed of current config.  Basically i want the two right side columns in the screen shot to be configured to top and bottom of screen, not side by side.   Thanks.
<img width="1440" alt="Screen Shot 2024-06-03 at 19 24 04" src="https://github.com/roundcube/roundcubemail/assets/141861485/b5955c78-fc17-4b2c-b74e-fd7c18f8b9c6">

### What browser(s) are you seeing the problem on?

Firefox, Safari

### What version of PHP are you using?

no idea,  where would i find that?  not in APPS

### What version of Roundcube are you using?

1.6.6

**Comment by alecpl** [comment]
Ask the distributor/hoster.

**Comment by bob7vogel** [comment]
I have asked the distrbutor/hoster.  They have directed me to you.  I don't think this is a host issue.  Just as you don't determine the way my network is configured, they don't determine how your software works.

**Comment by alecpl** [comment]
The software has plugins and themes, some of them can be disabled or not installed. The Elastic skin that is the default indeed does not provide this option.

**Comment by bob7vogel** [comment]
This catch22 process is almost becoming fun:  My provider says:

I can certainly understand the frustration of seeing the look of Roundcube change.

Unfortunately, Roundcube has dropped support for the theme you had been using with the latest update for cPanel.

Larry - Support deprecated as of Roundcube 1.6.0.
Classic - Support deprecated as of Roundcube 1.4.0

This is the reason the option to change the theme is no longer found in Roundcube as the only theme they now support is Elastic.

So how about bringing support back.  I think it was Classic that i was using.

**Comment by pabzm** [comment]
@bob7vogel "Larry" is still installable on Roundcube v1.6, see <https://github.com/roundcube/larry>.
