### ISSUE TITLE
Oauth redirection error

### ISSUE THREAD

**Issue by amend07** [roundcube/roundcubemail#9483]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Hello there, 
I was using ISPConfig3 with roundcube. I add keycloak as oauth provider and fill the required fields. After a successful authentication in keycloak it leads to me this error:

> Oops... something went wrong!
> An internal error has occurred. Your request cannot be processed at this time.
> 
> For administrators: Please check the application and/or server error logs for more information. 

Is there any one who can help me?
regards,

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

v8.1.28

### What version of Roundcube are you using?

v1.5.0

### PHP errors

> PHP Fatal error:  Uncaught Error: Class "guzzlehttp\Client" not found in /usr/share/roundcube/program/include/rcmail_oauth.php:220
> Stack trace:
> #0 /usr/share/roundcube/program/actions/login/oauth.php(37): rcmail_oauth->request_access_token()
> #1 /usr/share/roundcube/index.php(203): rcmail_action_login_oauth->run()
> #2 /var/lib/roundcube/public_html/index.php(26): include('...')
> #3 {main}
>   thrown in /usr/share/roundcube/program/include/rcmail_oauth.php on line 220

**Comment by alecpl** [comment]
You miss a dependency. And we don't support 1.5.

**Comment by amend07** [comment]
so, what should i do ? which version should i have to install ?

**Comment by amend07** [comment]
I install the updated version which is v 1.6.7 and it shows me the following errors:
<9sicllrb> IMAP Error: Login failed for jo@zergaw.local against localhost from 10.123.5.5. AUTHENTICATE XOAUTH2: A0001 NO [ALERT] Unsupported authentication mechanism. in /usr/share/roundcube/program/lib/Roundcube/rcube_imap.php on line 201

**Comment by pabzm** [comment]
We cannot provide you with support for running and configuring Roundcube. You might try to post at the forum <https://www.roundcubeforum.net/>.
