### ISSUE TITLE
an issue with URLs in emails creating a block

### ISSUE THREAD

**Issue by AaomtVp** [roundcube/roundcubemail#9491]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

I don't know what to do to allow my emails going out and other people's emails to me to be able to have a website address / URL in it and not cause the email to be blocked.
Also, this wasn't a problem in the fall. I only started experiencing this problem a few months ago or so. What changed? And what do I need to do to be able to send people a link to website addresses and allow people to send me the same?
I don't understand some of the descriptions in the 2020 similar post, and no one replied to my reply to it.

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

cPanel, L.L.C. 110.0.33

### What version of Roundcube are you using?

cPanel, L.L.C. 110.0.33

**Comment by pabzm** [comment]
Hello @AaomtVp, we can't tell you what changed, because we don't run the software you're using, we only build it. Please speak to the people who run the server you're using, they might be able to answer your questions.

> I don't understand some of the descriptions in the 2020 similar post

Which post is that?
