### ISSUE TITLE
Does elastic support the managesieve raw editor?

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail#9497]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

https://github.com/roundcube/roundcubemail/blob/fa4cf6e1160242501cfe46289c7e62840ab0f04c/skins/elastic/README.md lists as "Known Issue":

> CodeMirror editor (in managesieve raw script editing mode) is broken.

But in my local setup I can use it successfully. Is that information outdated?

(If yes, is the other line ("Dialogs executed on page load are displayed out of screen") maybe outdated, too?)

### What version of Roundcube are you using?

"master"-branch

**Comment by alecpl** [comment]
It says "known issues with running less in Roundcube devel_mode". You missied the devel_mode part.

**Comment by pabzm** [comment]
> It says "known issues with running less in Roundcube devel_mode". You missied the devel_mode part.

Oh, right. Sorry for the noise.
