### ISSUE TITLE
Plugin hook for message_delete and message_move

### ISSUE THREAD

**Issue by JE4GLE** [roundcube/roundcubemail#9499]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

A plugin hook, which allows to get notified on message_delete and message_mvoe

### Motivation and context

I want to write a plugin, which logs these actions for legal reasons.

**Comment by alecpl** [comment]
I'm not sure an IMAP client is the proper tool for that, I think such things should be done on the IMAP server.

That being said, we have already 'message_saved' hook, so adding 'message_delete' and 'message_move' could be added too, I suppose. Provide a pull request, please.

**Comment by alecpl** [comment]
Done.
