### ISSUE TITLE
Is `ctype` a required extension?

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail#9505]
@alecpl The PHP-extension `Ctype` is only listed in the wiki-page, not in the `INSTALL`-file. It appears to be used in `vendor/bacon/bacon-qr-code/src/Encoder/Encoder.php` and `vendor/pear/crypt_gpg/Crypt/GPG/KeyGenerator.php`, both of which are installed by default, so I figure it is a required dependency – right?

(I'm cleaning up duplicated or differing information from wiki vs. repo, starting with
page `Install-Requirements` vs. file `INSTALL`)

**Comment by alecpl** [comment]
Please note that people that look at Wiki are most likely interested in production setups, so released versions. Documentation of master can differ.

I'm not 100% sure, but we might not use that part of the codebase that depends on ctype. We're not using KeyGenerator, I'm not sure about the Encoder.

**Comment by pabzm** [comment]
> Please note that people that look at Wiki are most likely interested in production setups, so released versions.
 
Yes, but it's still duplicated information that can get outdated easily.

Do you still want to keep the wiki-page around? I would suggest to replace its content by a short list of links to the INSTALL-file in the branches of supported versions.

> I'm not sure about the Encoder.

The relevant line in the Encode is called from here: 
https://github.com/roundcube/roundcubemail/blob/613629f83acff97845454f0bf2bf9b5f26bd0611/program/actions/contacts/qrcode.php#L114

So I guess it is still a dependency?

**Comment by pabzm** [comment]
I don't think it's that bad, because `Ctype` is enabled by default, so it's not a hurdle for most people – and it was a requirement already so we're not introducing something new, right?

But yes, we should still list it as a dependency: https://github.com/roundcube/roundcubemail/pull/9509

Thanks for your input!
