### ISSUE TITLE
Is MS SQL supported?

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail#9506]
The wiki-page `Install-Requirements` lists "MS SQL Server (2005 or newer)" as supported database server, while the `INSTALL`-file doesn't.

Which one is correct?

**Comment by alecpl** [comment]
Support for MS SQL and Oracle was removed in master. So, the wiki will need to be updated, but probably after next major stable release.

**Comment by pabzm** [comment]
I would like to use the repo as authoritative source and remove the wiki-page – ok?

In the repository we can manage differing information in the release-branches (and link to them, too) – that is a distinction we'd have to manage a second time on the wiki (or have outdated/premature/contradictory information there, which I'm trying to get rid of right now).
