### ISSUE TITLE
new_user_identity_match parameter has no effect

### ISSUE THREAD

**Issue by lspagnol** [roundcube/roundcubemail#9512]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Hi.

With RC 1.6.7, the parameter 'new_user_identity_match' of 'new_user_identity' plugin has no effect.

I saw this closed issue https://github.com/roundcube/roundcubemail/issues/9210
It fix a bug but it has introduced another one.

$config['new_user_identity_match'] = 'uid' -> should search on LDAP uid attribute but program/lib/Roundcube/rcube_ldap_generic.php always use LDAP 'cn' attribute (i saw it in logs on debug mode).

```
# tail -f /var/www/html/etud/logs/ldap.log 
  3 => 'objectClass',
)
[21-Jun-2024 13:08:27 +0200]: <3inoa3ve> S: 0 record(s) found
[21-Jun-2024 13:08:27 +0200]: <3inoa3ve> C: Search base dn: [ou=people,dc=univ-reims,dc=fr] scope [sub] with filter [(|(cn=demo001))]
[21-Jun-2024 13:08:27 +0200]: <3inoa3ve> Using function ldap_search on scope sub ($ns_function is ldap_search)
[21-Jun-2024 13:08:27 +0200]: <3inoa3ve> C: (Without VLV) Setting a filter of (|(cn=demo001))
[21-Jun-2024 13:08:27 +0200]: <3inoa3ve> Executing search with return attributes: array (
  0 => 'dn',
)
[21-Jun-2024 13:08:27 +0200]: <3inoa3ve> S: 0 record(s) found

```

So i use this ugly and temporary fix:

```
# cat /program/lib/Roundcube/rcube_ldap_generic.php.patch
329c329,333
<             $attributes = ['cn'];
---
> 
>             # Contournement BUG: le paramètre 'new_user_identity_match' du plugin 'new_user_identity' est ignoré
> #            $attributes = ['cn'];
>             $attributes = ['uid'];
```

Thanks in advance.
LS

### What browser(s) are you seeing the problem on?

Firefox

### What version of PHP are you using?

8.1

### What version of Roundcube are you using?

v1.6.7

**Comment by alecpl** [comment]
This is a field name (from fieldmap) not attribute.

**Comment by Egress-Phil** [comment]
We are also experiencing issue.  Our new user search is configured to look up by the 'uid' attribute, but the actual search is filtering by 'cn' and is resulting in broken data.

The code works on older versions of 1.6
