### ISSUE TITLE
"with attachment" filter fails on some fts engines 

### ISSUE THREAD

**Issue by exi** [roundcube/roundcubemail#9514]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

The standard email filter `with attachment` uses an imap filter for header `content-type` with value `multipart/m`, which assumes that whatever search engine is used does an implicit wildcard search for `multipart/m*`, which is not always the case, for example with fts_xapian in dovecot.

The IANA mime type list only lists [one sensible multi part type ](https://www.iana.org/assignments/media-types/media-types.xhtml#multipart) which matches this and that's `multipart/mixed`.

Could we change the roundcube filter to match exactly `multipart/mixed` here to allow for wider fts engine support?

### What browser(s) are you seeing the problem on?

Chrome, Edge, Firefox, Safari

### What version of PHP are you using?

V8.2

### What version of Roundcube are you using?

V1.7

**Comment by alecpl** [comment]
I guess we can change that.

In git-master we use 'application/', 'multipart/m', 'multipart/signed', 'multipart/report'. Is 'application/' not an issue?

**Comment by exi** [comment]
> Is 'application/' not an issue?

I have no idea, i just noticed that my attachments with `multipart/mixed` don't show up. I have not tested/checked `application/` yet but I would think that within an email, if there is any text at all, it will always be `multipart/*`.

**Comment by alecpl** [comment]
Fixed.
