### ISSUE TITLE
Don't mark mail as read after delay if webpage is hidden to the user

### ISSUE THREAD

**Issue by n-goncalves** [roundcube/roundcubemail#9523]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

What I propose is to use the [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) to stop the timer that sends the request to mark the mail as read the mail is hidden to the user. 

### Motivation and context

Currently, when you set a delay to mark a mail as read, if you open a new tab, the mail will still be marked as read after the delay has passed. That feels weird to me.

**Comment by pabzm** [comment]
It sounds sensible, but: Do you know of any email client that does this?

And would you be willing to contribute that feature?

**Comment by alecpl** [comment]
Is it really a big deal? While probably doable, I'm not sure we should complicate the code to handle this rare case.

**Comment by n-goncalves** [comment]
Sorry about the delay.

@pabzm I haven't seen any mail client do it and I can contribute towards that feature.
However after thinking about it, I agree with @alecpl that it probably adds more complexity for not a lot of benefit. 

It's fine with me if you decide to close this issue.

**Comment by pabzm** [comment]
Ok, without anyone really pushing it, this won't happen anyways, I guess. Thus I'm closing.
