### ISSUE TITLE
vacation single line issue

### ISSUE THREAD

**Issue by ibizara** [roundcube/roundcubemail#9524]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

On a single line vacation reason I get the following sieve created

`require ["date","relational","vacation"];
# rule:[Out of Office]
if allof (currentdate :zone "+0100" :value "ge" "iso8601" "2024-06-27T00:00:00+01:00", currentdate :zone "+0100" :value "le" "iso8601" "2024-06-28T00:00:00+01:00")
{
	vacation :days 1 :addresses "name@mydomain.com" :subject "Out of office" :from "name@mydomain" "Test out of office";
}
`

On a multiline I get

`require ["date","relational","vacation"];
# rule:[Out of Office]
if allof (currentdate :zone "+0100" :value "ge" "iso8601" "2024-06-27T00:00:00+01:00", currentdate :zone "+0100" :value "le" "iso8601" "2024-06-28T00:00:00+01:00")
{
	vacation :days 1 :addresses "name@mydomain.com" :subject "Out of office" :from "name@mydomain.com" text:
Test out of office
Line 2
.
;
}
`

The first breaks the email by setting MAIL FROM:<>

If I manually edit the sieve for the single line vacation reason with a newline after the email it works as expected.

### What browser(s) are you seeing the problem on?

Other

### What version of PHP are you using?

7.3

### What version of Roundcube are you using?

1.4.15

**Comment by ibizara** [comment]
Seems to be an Amazon SES issue, but how would I override the MAIL FROM being <>

https://repost.aws/questions/QU7gYWTZ-XT3eZz3VYiKGIrQ/amazon-ses-sieve-vacation-mail-from-not-working-following-rfc-5230

**Comment by pabzm** [comment]
Thanks for the feedback on the self-solution!
