### ISSUE TITLE
Filters > Reply with message > Reply sender address > Allow valid "Display Name <some@email.com>"

### ISSUE THREAD

**Issue by ibizara** [roundcube/roundcubemail#9526]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

When attempting to set a display name for the reply sender address, such as "`Display Name <some@email.com>`", you encounter the error messages "Please enter a valid email address" and "Filter form contains errors."

Currently, I'm unsure of an alternative method to achieve this within the Roundcube web UI. As it stands, I need to make this adjustment directly in the sieve file.

### Motivation and context

To have a display name for the reply sender address within a filter.

**Comment by alecpl** [comment]
Proper format is `Display Name <some@email.com>` (name can be in double-quotes) and it works for me. What version?

**Comment by ibizara** [comment]
Seems working now in managesieve version 9.4 - Allow display name with email address in vacation :from field (#6760)
