### ISSUE TITLE
500 - Server Error only on INBOX and not subfolders on Debian bookworm and Roundcube 1.4.8

### ISSUE THREAD

**Issue by jdmendez** [roundcube/roundcubemail#9527]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

After updating my server and installing the new roundcube with PHP 8.2.20, everything was working fine for a few days and an error on almost all my email's INBOX started to appear: 500 server Error, and no email was displayed for the inbox only.

Roundcube log show a fatal error:
 PHP Fatal error:  Uncaught TypeError: preg_split(): Argument #3 ($limit) must be of type int, string given in roundcubemail-1.4.8/program/lib/Roundcube/rcube_result_thread.php::496

It seems that the $start value of the while loop was becoming larger than the length of the rawdata variable.  The following line just before the end of the loop seems to have solve the issue.

if ($start>strlen($this->raw_data)) break;

The problem is gone now. Please check if this is a valid solution to the issue.

It also seems that this php file is only run for the INBOX and not for the subdirectories.

### What version of PHP are you using?

8.2.20

### What version of Roundcube are you using?

1.4.8

### PHP errors

 PHP Fatal error:  Uncaught TypeError: preg_split(): Argument #3 ($limit) must be of type int, string given in roundcubemail-1.4.8/program/lib/Roundcube/rcube_result_thread.php::496

**Comment by alecpl** [comment]
Use more recent Roundcube version. 1.4 is not supported anymore and will not work with PHP 8.2.

**Comment by jdmendez** [comment]
Thanks you for the advice. I will upgrade. Just want to point out that Roundcube veersion 1.4.8 is working with PHP 8.2 with the change I detailed above. But you are right, it is way better to upgrade. I will do that.
