### ISSUE TITLE
decouple frontend auth mechanism from IMAP backend auth

### ISSUE THREAD

**Issue by restena-sw** [roundcube/roundcubemail#9530]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

Right now, there seems to be an assumption that the frontend auth method is identical to the backend one. I.e. if OAuth2 is used for frontend, an IMAP server with OAuth2 support is required as a backend.

The requested feature is: make backend authentication configurable separate from frontend authentication. E.g. an organisation might have OAuth2 enabled web services ("SSO"), but an IMAP backend which can only do more classical auths.

This naturally requires info regarding what the password to use would be. In a typical deployment, a session-based time-limited password would come in with the OAuth claim. So, the feature would have to allow configuring where in the OAuth response to look for the username and password to use.

Some configuration pseudo-code to demonstrate:

$config["oauth_imapbackend_method"] = "PLAIN"; # defaults to "XOAUTH2" to stay compatible with current behaviour
$config["oauth_imapbackend_username_claim"] = "openid.username"; # only relevant when method != XOAUTH2
$config["oauth_imapbackend_password_claim"] = "customclaim.sessiontoken"; # only relevant when method != XOAUTH2

### Motivation and context

In our case, that backend is cyrus; with no possibility to configure OAuth2. Since there is a coherent SSO experience for all other web services, it would be a UX sin to use local username/password prompts for Roundcube.

We are now in a situation where a user can log into the frontend with OpenID Connect/OAuth2, and we generate a short-lived "password" that is only transmitted in this browser session to RoundCube.

We imagine that only modest amount of code are needed to switch backend auth to e.g. PLAIN and use the supplied "password" for the backend login (as would happen with local username/password frontend login too). However, we would prefer a real feature in the product over self-made shortcuts in the local deployed code. We can also sponsor this work - please get back to me if that is interesting.

**Comment by restena-sw** [comment]
Adding @restena-pyg - he is part of our webmail team and could beta-test the feature once available.

**Comment by alecpl** [comment]
I may have to entertain the same scenario, and implement that properly.

How would you propose to solve the password expiration? I guess the password should have the same expiration time as the token. Then when we refresh the token we get a new password. Any comments on that?

**Comment by restena-sw** [comment]
For best consistency, frontend and backend access should stop working simultaneously; that way, the frontend will force a re-auth at the good time, and get a new temporary password, and the old password is never tried on the backend.

So here is a clarification question about OIDC login in Roundcube: What happens at the moment the OIDC token expires? Is the user automatically logged out, and pushed back to the OIDC Provider login screen?
Or is the RoundCube session only checking the OIDC token as a one-off during a login, and afterwards has its own session management  and timeouts?

If the latter, the problem becomes somewhat complex as there might be a valid RoundCube session based on an expired access token, and that session will attempt to use the "stale" password beyond the lifetime of the token itself - which is a kind of undefined behaviour.

**Comment by alecpl** [comment]
Implemented.

The new option is `oauth_password_claim` and (together with `oauth_scopes`) is all you need to make this working. Works for me. I'll consider backporting this to 1.6, but the code in master changed a lot, so it might not be easy.

@restena-sw Regarding your questions, it's really out of scope to this ticket, but let me try to answer.

Roundcube will try to refresh the token (and get the new password claim) before the token expires, but if it does expire, the session is killed only if the refresh request failed. It's not killed if the refresh request succeeded, but for any reason the content was invalid. This is not my code, and I think it might need to be re-considered. It's undefined behavior territory right now, I think.
