### ISSUE TITLE
Update gl_ES translations from transifex

### ISSUE THREAD

**Issue by soymgomez** [roundcube/roundcubemail#9531]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

I see that https://app.transifex.com/roundcube/roundcube-webmail/content/ has updated the translations for the Galician language (gl_ES).

Is it possible to update this repository with the new translations?

Thank you very much

### Motivation and context

Translations are outdated

**Comment by alecpl** [comment]
Localization in master has been updated. I don't plan to update older version branches.
