### ISSUE TITLE
Not receiving any emails!

### ISSUE THREAD

**Issue by yasher3413** [roundcube/roundcubemail#9532]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

I am able to send emails only to addresses with the same domain, but I not able to receive anything at all and haven't recieved any mail since April 23. not able to recieve any codes either. When I sent an email from my personal, it says the email doesn't exist.

### What browser(s) are you seeing the problem on?

Safari, Other

### What version of Roundcube are you using?

v1.6.7

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
