### ISSUE TITLE
loop sends in progress

### ISSUE THREAD

**Issue by abdsarmai** [roundcube/roundcubemail#9533]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

I have configured a mail server but when I want to send an email I send in a loop so I looked at the firewall it's not that if someone can help me please.

### What browser(s) are you seeing the problem on?

Firefox

### What version of PHP are you using?

7.4.33

### What version of Roundcube are you using?

v.1.6.6

### JavaScript errors

Un en-tête X-Frame-Options non valide a été trouvé lors du chargement de « https://***.***.***.***/roundcube/?_task=mail&_unlock=loading1720041295202&_framed=1 » : « invalid » n’est pas une directive valide.

**Comment by alecpl** [comment]
Ask on mailing list or forum, please.
