### ISSUE TITLE
Autoresponder adding lines of code that are being marked as junk by major MSPs

### ISSUE THREAD

**Issue by stefpl00f** [roundcube/roundcubemail#9536]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

When the autoresponder is enabled (https://webmail.cloudmail.email/#settings/accounts/autoresponder) Yahoo and Gmail won't receive the autoresponse to Junk, Spam, anywhere at all. 

Outlook.com receives it but marks it as junk and states the following about it:
![image](https://github.com/roundcube/roundcubemail/assets/170770296/69e4796a-bdff-4444-987a-071398dcd559)

The indicated error seems like it's failing DKIM so won't let it through... The sender and from don't match. This was reported by one of our reseller's customers, as well as the reseller, and I have been able to recreate the scenario with my own account.

### What version of Roundcube are you using?

v1.6.6

**Comment by alecpl** [comment]
And what this has to do with Roundcube?
