### ISSUE TITLE
Bulk email dissapearance from roundcube webmail

### ISSUE THREAD

**Issue by supportmails** [roundcube/roundcubemail#9539]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

We use roundcube webmail for a client. We recently sent out an email to about 30ish email adresses, and expected their response. They started responding. But after a few days the communication dissapeared. Like they never responded. No matter how i adjust the filters the communication under subject "Revizija tečajeva na edu.hkms.hr platformi " doesn' exist (my mail to them exists, but their answers dissapeared)

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

1.6.0

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
