### ISSUE TITLE
Error when send mail on php 8+

### ISSUE THREAD

**Issue by dfxphoenix** [roundcube/roundcubemail#9540]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I can recreate the issue with all plugins disabled

### Describe the issue

As the title says, I get an error when I try to send an email on version 8+ of php, on 7.4 it works perfectly.
![image](https://github.com/roundcube/roundcubemail/assets/42915865/324a3198-709d-4872-82df-f62675e2e7c1)
The error occurs on any other roundcube version, roundcube logs are empty.

### What browser(s) are you seeing the problem on?

Chrome, Edge

### What version of PHP are you using?

8.3, 8.2, 8.1, 8.0

### What version of Roundcube are you using?

1.6.7

### JavaScript errors

POST https://mail.xopsys.ro/?_task=mail&_unlock=loading1720604538174&_framed=1 500 (Internal Server Error)

### PHP errors

No errors

**Comment by pabzm** [comment]
Please check or show us the server logs (from the `logs` directory) to find out what the problem is.

(In general Roundcubemail runs well on those PHP-versions, so it's probably a local problem of your installation.)

**Comment by dfxphoenix** [comment]
Server logs is empty, no php errors, no logs
![image](https://github.com/roundcube/roundcubemail/assets/42915865/f57a8065-fd65-472f-9b21-30780758771a)
![image](https://github.com/roundcube/roundcubemail/assets/42915865/f5631c22-bbdb-41f3-91ef-902fd1f346db)
I use cpanel for my websites

**Comment by dfxphoenix** [comment]
I have tested on XAMPP and works.
I think the problem is with the cPanel.
I created a ticket on my host to see if they can solve the problem.

**Comment by dfxphoenix** [comment]
I solved the problem by adding in .htaccess
AddHandler application/x-httpd-ea-php82___lsphp .php .php8 .phtml
