### ISSUE TITLE
RC not auto detecting timezone from Firefox

### ISSUE THREAD

**Issue by darren12345** [roundcube/roundcubemail#9541]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

RC Timezone is set to "Auto" in user interface, I am in the UK, current time is UTC+1. Browser is Firefox 128. 
Email times in mail folders are being displayed as UTC (ie. one hour earlier). If I manually set the timezone to "GMT+0000 Europe/London", the times are correct. "Auto" time zone is displaying the correct times in Edge. 
Have reproduced with all Firefox addons and all RC plugins disabled.
Screen shots attached for comparison.
![RC times](https://github.com/roundcube/roundcubemail/assets/12751052/0eabb74c-1d44-4c95-80f8-79d563e37be7)

### What browser(s) are you seeing the problem on?

Firefox

### What version of PHP are you using?

8.2.20

### What version of Roundcube are you using?

1.6.7

**Comment by pabzm** [comment]
Please set a proper title for this issue, and show use the value of `privacy.resistfingerprinting` in `about:config` in Firefox.

**Comment by darren12345** [comment]
> Please set a proper title for this issue, and show use the value of `privacy.resistfingerprinting` in `about:config` in Firefox.

Whoops! Corrected.

privacy.resistfingerprinting is set to False.

**Comment by pabzm** [comment]
Hm, I can't reproduce the problem with Firefox 128.0.

Which OS are you on? Can you open the "Web Developer Tools" console and show us what the return value of `new Date()` is?

**Comment by darren12345** [comment]
It's Widows 11 23H2 all up-to-date.

Running new Date() in the developer console gives:

Date Wed Jul 10 2024 11:32:44 GMT+0100 (British Summer Time)

Which is correct.

**Comment by darren12345** [comment]
Confirmed I also cannot reproduce it on another machine running FF 128. So it's just this one...🤔

**Comment by alecpl** [comment]
What about `Intl.DateTimeFormat().resolvedOptions().timeZone;` in console? This is what we do.

**Comment by pabzm** [comment]
> Confirmed I also cannot reproduce it on another machine running FF 128. So it's just this one...🤔

Then this is very likely not a Roundcube-related problem and I'd like to close this issue.

**Comment by darren12345** [comment]
Fair. I will close it for now.
