### ISSUE TITLE
Plain text URL differs from HTML URL

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9542]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

[k.eml.gz](https://github.com/user-attachments/files/16170577/k.eml.gz)
has a confirmation link. I clicked it but the website said wrong...
So then I clicked on HTML and then the link worked.

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

Dreamhost's

**Comment by pabzm** [comment]
As far as I can tell the plain text part of that message does not contain a blank space between the URL and the next characters, so I assume this is not Roundcubemail's fault. Also Thunderbird shows the message part in the same way, which strengthens my assumption.

Can you explain why you think that this is Roundcubemail's fault?

**Comment by jidanni** [comment]
OK. Sorry then.
