### ISSUE TITLE
`rcube_webmail.prototype` vs. `rcmail.addEventListener()`

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail#9544]
I'm seeing two code patterns to call js-functions from server code:

1. Implement the JS-function on `rcube_webmail.prototype` and then call it on the `rcmail` instance,
2. Add an event-listener to `rcmail` in JS, and from the server code make `rcmail` trigger it.

I'm wondering why both exist, since they serve identical purposes.

@alecpl Can we decide on one of them for future changes? Which one would you prefer? (I don't care much.)

**Comment by alecpl** [comment]
Well, when you have a lot of code it's cleaner to "extend" the `rcube_webmail` object. I think we should keep both. Our javascript code "style" is quite outdated.

**Comment by pabzm** [comment]
Ok. I'd then move towards using event-handlers in plugins and prototype-changes in core-code.
