### ISSUE TITLE
Use class `html` more often?

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail#9545]
I really like the approach of the `html` class for building HTML (the tag-methods more than the specialized classes), but I see it used only partially. In a lot of code places, HTML is written as concatenated strings, also code that is younger than the `html` class.

@alecpl Why is that? Is there any reason not to use `html` more often?

**Comment by alecpl** [comment]
No strong reason, but sometimes the code is just cleaner with strings. Another reason is that many developers providing code occasionally not necessarily know the html classes.
