### ISSUE TITLE
better error messages when config.inc.php does not have the right ownership / is not readable by roundcube

### ISSUE THREAD

**Issue by JohnRDOrazio** [roundcube/roundcubemail#9549]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

Roundcube should check whether the `config.inc.php` file and / or `default.inc.php` file is / are readable, and if not should show a more specific error rather than just "Internal error".

### Motivation and context

I recently ran into this situation when uninstalling and reinstalling Roundcube as a Plesk component. I recreated the `config.inc.php` file but forgot to change ownership of the file. I was getting an "Internal error" screen when trying to access webmail, but couldn't for the life of me figure out what was causing the error. I wound up creating a ticket with Plesk support, they didn't identify the exact issue but when they mentioned that probably it was some setting in the `config.inc.php` file that was causing the issue, that at least led me to look closer at the configuration file and realize that it probably didn't have the right ownership. As soon as I made the file group readable by `roundcube_sysgroup` voilà I was again able to access Roundcube webmail.

**Comment by alecpl** [comment]
Done.
