### ISSUE TITLE
Red circle assumes only two digits

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9553]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Here we see Inbox has 10 messages.

![Screenshot 2024-07-24 19 46 49](https://github.com/user-attachments/assets/3cb0a081-9580-4e0b-a6e7-d245e61dea69)

But on closer inspection, the number is really 9109!

The bug is the red circle assumes there are only two digits.

### What version of Roundcube are you using?

"rcversion":10500

**Comment by alecpl** [comment]
Roundcube 1.5 is not supported anymore. Also, you're using some custom skin.

**Comment by jidanni** [comment]
OK, I told them that, and they said

> Thank you for contacting DreamHost Support. My name is Carlos and I'll do
> my best to assist you.
> 
> Sorry for the delay on the response. Our Specialist team has mentioned
> that the current RoundCube version we use is still supported as seen
> here: https://endoflife.date/roundcube
> 
> We will still take a look to check if the issue you reported is related
> to the theme we provided.
> 
> I hope this information proves useful. Feel free to reply anytime should
> you have any further questions or if you need additional assistance. We'd
> be happy to help!

But then I told them that I got the info straight from you and not a 3rd party website. And they said:

> Thank you for reaching out and sharing your concerns regarding the
> version of Roundcube we are currently using for our webmail portal.
> 
> We understand the importance of staying updated with the latest versions
> of software to ensure security and performance. Our current version of
> Roundcube is indeed supported and receives regular security updates and
> maintenance patches. We follow a rigorous process to evaluate and
> implement updates to ensure stability and compatibility across our
> platform, and this includes careful testing and validation before any new
> version is rolled out.
> 
> The latest version of Roundcube does offer new features and security
> fixes. However, our priority is to maintain a stable and secure
> environment for all our users, which sometimes means waiting for a new
> version to mature before implementing it.
> 
> We assure you that we continually monitor and assess the best time to
> upgrade our systems. Your feedback is valuable to us, and we have noted
> your request for the latest Roundcube version.
> 
> Thank you for your understanding and patience. If you have any further
> concerns or questions, please feel free to let us know.

So I conclude that I extracted the version info wrong, and wish you would tell me the way I (non-root) can find the version info. Thanks! Currently all I know is hit CTRL+U in the browser and then CTRL+G "version", which is a rather poor method.

**Comment by alecpl** [comment]
1.5 is an LTS version which means it receives only security fixes at this point.
