### ISSUE TITLE
2fa -google or yubikey

### ISSUE THREAD

**Issue by msebastian100** [roundcube/roundcubemail#9555]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

i don't understand why 2fa with google auth/security key [yubikey] is not automatically included and active. 

an additional confirmation to the password

### Motivation and context

today, 2fa should be a standard function that does not have to be activated with a plugin. it simply has to be activated by default. Of course, the user should still be free to decide whether to use it.

**Comment by alecpl** [comment]
We're a small team, we can't do everything.
