### ISSUE TITLE
After updating from v1.6.7 to v1.6.8 cannot print image attachments from Firefox

### ISSUE THREAD

**Issue by ner00** [roundcube/roundcubemail#9571]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Instead of the image it shows a URL (in the printing preview and in the printed paper itself).  There's also an error in the browser's console (see 'JavaScript errors' section). The image is also glued to the leftmost side of the window instead of centered as it used to be. A couple screenshots below to better demonstrate the overall appearance of the issue.

**Behavior in v1.6.8 (within Firefox v128.0.3)**
![firefox_WYXLaRnGPQ](https://github.com/user-attachments/assets/190001af-47a9-4f36-b271-cb7391138b3d)

**Behavior in v1.6.7 (within Firefox v128.0.3)**
![firefox_Mzb2wV78gK](https://github.com/user-attachments/assets/f0b16dd6-49ea-47e2-82bd-f27fc00082c3)

### What browser(s) are you seeing the problem on?

Firefox

### What version of PHP are you using?

v8.1.10

### What version of Roundcube are you using?

v1.6.8

### JavaScript errors

[jquery.min.js:36:49986](https://localhost/roundcube/program/js/jquery.min.js?s=1722764718) `Content-Security-Policy: The page’s settings blocked an inline style (style-src-elem) from being applied because it violates the following directive: “default-src 'none'”`

**Comment by alecpl** [comment]
Confirmed. Looks like we set the CSP on attachment preview page too strict.

**Comment by alecpl** [comment]
Fixed.
