### ISSUE TITLE
make the home page more user-friendly

### ISSUE THREAD

**Issue by Dartech1** [roundcube/roundcubemail#9574]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

there was an update two days ago, since then the mail system looks completely different, the biggest problem is that half of the screen is taken up by things that are not absolutely important, such as the tabs on the left such as incoming mail, drafts. This column and the column next to it take up so much space on the screen that the email itself cannot be seen in its full width. I am attaching a picture, maybe you can check it. the previous system was much better, but this could also work if the left column could be pulled in more, not only as far as it allows now.
![Névtelen](https://github.com/user-attachments/assets/2db0b755-f674-489a-a471-668edd8cdb9a)

### Motivation and context

we use this mail system on a daily basis, it would make our job a lot easier if the above-mentioned problem were solved, but otherwise it would also be good if we could switch back to th
![Névtelen](https://github.com/user-attachments/assets/b40424f4-da32-4045-8ce4-fd53d2498ad1)
e old version, is that possible?

**Comment by alecpl** [comment]
You can resize the columns a bit with mouse by dragging by the column border. Not a bug.
