### ISSUE TITLE
SMTP auth fails with v1.6.8

### ISSUE THREAD

**Issue by Rafiot** [roundcube/roundcubemail#9577]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I can recreate the issue with all plugins disabled

### Describe the issue

This is a fresh install of Roundcube 1.6.8 on a tested & working self hosted postfix/dovecot setup, IMAP login works as expected, SMTP fails with the error below (works fine from thunderbird and from nextcloud mail).

I spent the evening messing with `config['smtp_host']` and as far as I cal tell, the content is ignored. I set it to anything, including something nonsensical that should not be able to connect, I keep getting the error below.

Also, `$config['smtp_debug'] = true;` never creates the `smtp.log` in the logs directory.

I feel like I'm missing something really stupid, but it's been a few hours and I cannot see what it is. Anyone has any idea? Or is that a bug in the latest release?

### What browser(s) are you seeing the problem on?

Firefox

### What version of PHP are you using?

8.2

### What version of Roundcube are you using?

v1.6.8

### PHP errors

```
[12-Aug-2024 00:22:30 +0000]: <bhn8et5l> PHP Error: SMTP server does not support authentication (POST /?_t
ask=mail&_unlock=loading1723422150097&_framed=1&_lang=en_US&_action=send)
[12-Aug-2024 00:22:30 +0000]: <bhn8et5l> SMTP Error: Authentication failure: mail.my-server.com
PIPELINING
SIZE 10240000
VRFY
ETRN
STARTTLS
ENHANCEDSTATUSCODES
8BITMIME
DSN
SMTPUTF8
CHUNKING (Code: 250) in /var/www/roundcube/program/lib/Roundcube/rcube.php on line 1794 (POST /?_task=mail&_unlock=loading1723422150097&_framed=1&_lang=en_US&_action=send)
```

**Comment by alecpl** [comment]
You have to use TLS/SSL via `$config['smtp_host']`. Usually it's done as `tls://your.server:587` or ssl://your.server:465`.

**Comment by Rafiot** [comment]
That's what I did, but even if I put `ssl://nonexistentdomain:465`, I get the same error. And somehow, I don't seem to be able to enable debug (or at least the file isn't created/no entries are written).

**Comment by Rafiot** [comment]
Alright, figure out the issue, as expected, it is PEBCAK: if you use nginx, you *must* run `service php8.2-fpm restart` when you change `config/config.inc.php` otherwise the changes aren't taken in account :clown_face:

**Comment by DK3369** [comment]
SMTP Error: STARTTLS failed: 4.7.0 TLS not available due to local problem (Code: 454) in 
program/lib/Roundcube/rcube.php on line 1794 (POST /?_task=mail&_unlock=loading1734615494676&_framed=1&_lang=en&_action=send)
