### ISSUE TITLE
Emails não são enviado

### ISSUE THREAD

**Issue by SilvanaOsorio** [roundcube/roundcubemail#9580]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Não consigo enviar email.

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

v1.6.0

### JavaScript errors

![image](https://github.com/user-attachments/assets/06239b72-a39d-40ca-b798-1daafa02a984)
[ERRO WEBMAIL.docx](https://github.com/user-attachments/files/16565518/ERRO.WEBMAIL.docx)

### PHP errors

This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a permanent error. The following address(es) failed:

  [an...a@gmail.com](mailto:an...a@gmail.com)
    retry timeout exceeded
Reporting-MTA: dns; vps-11952368.webmedula.com.br

Action: failed
Final-Recipient: rfc822;[an...a@gmail.com](mailto:an...a@gmail.com)
Status: 5.0.0

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
