### ISSUE TITLE
SPAM-Folder open Mail = Oppen all Extern Images!!!

### ISSUE THREAD

**Issue by Volk3rDE** [roundcube/roundcubemail#9583]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Hi,
Open email from INBOX, only loads external content if I confirm!
If a new email arrives in SPAM and you open it, the external content will be reloaded immediately!!!
I find that very critical, INBOX is safe and SPAM is a problem in my opinion or not???

Best regards 
Volk3r
PS: Sorry is Translator result :)

### What version of PHP are you using?

8.1

### What version of Roundcube are you using?

1.6.7

**Comment by pabzm** [comment]
I cannot reproduce that. Are you sure the content you see in the Spam folder is loaded from an external URL and is not embedded? Could you try to view the same message once in Inbox, and once in Spam, and logout&re-login again between? (The re-login is relevant because Roundcube temporarily saves your decision to show remote content per message in the sesion.)

**Comment by Volk3rDE** [comment]
Hi,
So I can't say whether it's loaded externally, but the messages are displayed in HTML with images. That's critical, isn't it?
When I look at the source code, I don't see HTML but rather cryptic code.

**Comment by pabzm** [comment]
> That's critical, isn't it?
 
Not necessarily, no.
 
 Can you upload the message here so we can check it?

**Comment by Volk3rDE** [comment]
Okay, her 2 Mails as Export
[Uploading ___SPAM___  .tar.gz…]()

**Comment by pabzm** [comment]
You inserted a link to this issue, not to the uploaded files, please try again.

**Comment by Volk3rDE** [comment]
[___SPAM___  .tar.gz](https://github.com/user-attachments/files/16623829/___SPAM___.tar.gz)

**Comment by Volk3rDE** [comment]
okay, thx for Watching, Testing and Feedback :)
