### ISSUE TITLE
Add smtp_host to login form

### ISSUE THREAD

**Issue by David-Grass-Feria** [roundcube/roundcubemail#9601]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

If roundcube not find any imap_host, you fill the form "server" on the login form. This is great.

### Motivation and context

Why not the same with smtp_host. It would be great, when the user can set his imap_host and smtp_host on the login form. 

example: Loginform
```
_user=userdomain
_pass=password
_imap_host= ssl://imap.server.com
_smtp_host= ssl://smtp.server.com
```

The big thing of this: You can add request parameters from a other app to the roundcube login form and pass the data.

I am not a big fan of this:
```
$config['default_host'] = [
    'ssl://imap.gmail.com'                                  => 'Gmail',
    'ssl://imap.web.de'                                     => 'WEB.DE',
    
];

$config['smtp_server'] = [
    'imap.gmail.com'                                        => 'ssl://smtp.gmail.com',
    'imap.web.de'                                           => 'ssl://smtp.web.de',
   
];
```

**Comment by alecpl** [comment]
I would rather remove the option to enter an imap server than add another field.

**Comment by David-Grass-Feria** [comment]
Roundcube is the best email client. This is not a criticism of you. I think that SMPT and IMAP is way too complicated in Roundcube. Every email client Gmail and the others use the full email address. All these config settings with ‘%h’ etc, make it confusing. This is very simple. If the input fields, imap_host and smtp_host are empty, then the settings from config.inc.php take effect. Absolutely simple and straightforward. And why is there a ‘mail_host’ column in the user table? There is no mail host, only an imap_host and smtp_host. This is all very confusing. Nevertheless, I have the greatest respect, Roundcube has been around since 2008 and is absolutely top!

**Comment by David-Grass-Feria** [comment]
But you don't know a simple trick how every user can create his own smtp_host? I don't want to interfere with the rcmail.php.

**Comment by pabzm** [comment]
@David-Grass-Feria What is your use-case for this?

In principal I'd also prefer to not allow users to enter server names, because there's too much potential for abuse. But maybe you have good arguments? Or maybe we can tell you to achieve your goal differently?

**Comment by David-Grass-Feria** [comment]
@pabzm No, there is no usecase for this. You and @alecpl give the correct answere. 
The problem ist: If the user can add the complete imap and smtp, then the user can use your mailclient with gmail or other services. And i unterstand now, there is no usecase for use roundcube with many imap servers. In the real world, nobody use a mailclient with different Email Providers. This is possible with Outlook or Thunderbird software, but there is usecase for this.

**Comment by pabzm** [comment]
Alright, thank you for the explanation! I'm closing this, then.
