### ISSUE TITLE
PHP Warning:  Undefined array key "style"

### ISSUE THREAD

**Issue by photoninger** [roundcube/roundcubemail#9611]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

After upgrading to roundcube-1.6.8 I see in errors.log:
PHP Warning:  Undefined array key "style" in /srv/www/roundcube/program/actions/mail/index.php on line 1192

Line 1192 is:
```
$attrs['style'] = ($attrs['style'] ? trim($attrs['style'], ';') . '; ' : '') . implode('; ', $style);
```

### What version of PHP are you using?

8.2

### What version of Roundcube are you using?

1.6.8

### PHP errors

 PHP Warning:  Undefined array key "style" in /srv/www/roundcube/program/actions/mail/index.php on line 1192

**Comment by alecpl** [comment]
Fixed.
