### ISSUE TITLE
No se puede acceder a este sitio

### ISSUE THREAD

**Issue by Eldestete** [roundcube/roundcubemail#9614]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Cuando intento acceder a cualquier usuario de Web Mail, nos figura No se puede acceder a este sitio

### What version of PHP are you using?

v7.2

### What version of Roundcube are you using?

v1.6.6

### JavaScript errors

No se puede acceder a este sitio

### PHP errors

No se puede acceder a este sitio

**Comment by pabzm** [comment]
You're talking to the developers of the software Roundcubemail, not the providers of your webmail service. We cannot help you with your problem. Please contact the people or company that provide you with your email address.
  
(If you do provide the service yourself, you can re-open this issue, but please write in english, and provide much more details about your setup and the problems.)

---
Traducido por una máquina:

Estás hablando con los desarrolladores del software Roundcubemail, no con los proveedores de tu servicio de webmail. No podemos ayudarle con su problema. Por favor, póngase en contacto con la persona o empresa que le proporciona su dirección de correo electrónico.

(Si usted mismo proporciona el servicio, puede reabrir este tema, pero por favor escriba en inglés, y proporcione muchos más detalles sobre su configuración y los problemas).
