### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by gabi-ramires** [roundcube/roundcubemail#9617]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I can recreate the issue with all plugins disabled

### Describe the issue

**Client Context:**
Hello! We are experiencing an issue where the client is receiving an email with a link that is being displayed incorrectly. The link automatically has "webmail" inserted before the URL, causing the client to be redirected back to their own webmail upon clicking.

When we copy the URL without the "webmail" prefix, the link works correctly.

Developer Context: The link being sent is likely (and I say likely because we cannot know how it is being sent, only how it is arriving) formatted as:

www.bmgconsig.com.br/ResetSenha?method=alterarSenha&t=eyJhbG....

instead of:

https://www.bmgconsig.com.br/ResetSenha?method=alterarSenha&t=eyJhbG....

That is, without the https:// prefix. This implies that Roundcube is interpreting it as a relative link, which causes it to automatically prepend https://webmail.kinghost.net/.

**Tests Performed:**

On our end, we tried:
1) Within the project webmail in roundcube/conf/config.inc.php, we attempted the following configurations:
``` 
$config['force_https'] = false;
$config['html_sanitizer'] = null;
$config['enable_html_sanitizer'] = false;
$config['strip_html_tags'] = false;
$config['prefer_plaintext'] = true;
$config['render_link_target'] = '_blank';
$config['mailto:parsing'] = true;
$config['mailto:add_link_additional'] = array(
    'www.' => 'http://',
);
```

2) Within webmail > settings > preferences > message display

- HTML display = enabled and disabled
- Allow remote resources (images, styles) = always

3) Within webmail > settings > preferences > user interface
- Associate email links (mailto:) for sending messages through webmail

None of these attempts resolved the behavior the client is experiencing.

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What version of PHP are you using?

7.4.33

### What version of Roundcube are you using?

1.4.11

**Comment by alecpl** [comment]
1.4 is an old version that we do not support. These options you added to the config file do not exist.

Upgrade to 1.6 and let us know if that helped. If it's still an issue provide an email message source.

**Comment by gabi-ramires** [comment]
Good morning!

We updated roundcube to version 1.6 and the error persists.
We believe that the link present in the body of the email is being triggered without using the HTTP protocol and because of this, roundcube is interpreting it as a relative link and automatically adding webmail.kinghost.com.br in front of the link.

We believe the email is being sent as follows:

```
<div class="pre">Usuário(a) bmg-camily para cadastar sua nova senha de acesso ao BMG<br>
    Consig: Click aqui. [<a rel="noreferrer" target="_blank"
        href="www.bmgconsig.com.br/ResetSenha?method=alterarSenha&t=eyJhbGciOiJIUzI1NiJ9.eyJ1c3VfY29kZSI6IjQyODJFOTRBNTI2MjQ4QzVCNEUxRjhERTgzNTA2RDU0IiwiY29kZSI6IjViMzA2MzlhLTczMkBqSjAiLCJzdWIiOiJibWctY2FtaWx5IiwiaWF0IjoxNzIzNzM0Mzg0LCJleHAiOjE3MjM3NjMxODR9.0pp93UtzVt0blAEf0AeaFJcghx3ov8OnS7VqWv8W-Pk">1</a>]<br>
    <br>
    Links:<br>
    ------<br>
    [1] <a rel="noreferrer" target="_blank"
        href="www.bmgconsig.com.br/ResetSenha?method=alterarSenha&t=eyJhbGciOiJIUzI1NiJ9.eyJ1c3VfY29kZSI6IjQyODJFOTRBNTI2MjQ4QzVCNEUxRjhERTgzNTA2RDU0IiwiY29kZSI6IjViMzA2MzlhLTczMkBqSjAiLCJzdWIiOiJibWctY2FtaWx5IiwiaWF0IjoxNzIzNzM0Mzg0LCJleHAiOjE3MjM3NjMxODR9.0pp93UtzVt0blAEf0AeaFJcghx3ov8OnS7VqWv8W-Pk">www.bmgconsig.com.br/ResetSenha?method=alterarSenha&t=eyJhbGciOiJIUzI1NiJ9.eyJ1c3VfY29kZSI6IjQyODJFOTRBNTI2MjQ4QzVCNEUxRjhERTgzNTA2RDU0IiwiY29kZSI6IjViMzA2MzlhLTczMkBqSjAiLCJzdWIiOiJibWctY2FtaWx5IiwiaWF0IjoxNzIzNzM0Mzg0LCJleHAiOjE3MjM3NjMxODR9.0pp93UtzVt0blAEf0AeaFJcghx3ov8OnS7VqWv8W-Pk</a>
</div>
```

**Comment by alecpl** [comment]
Links have to have protocol prefix. So, not Roundcube issue.

**Comment by gabi-ramires** [comment]
I tested by sending the same email to roundcube and gmail. Gmail arrives correctly. Isn't there some configuration we can do in roundcube?

**Comment by pabzm** [comment]
There is no configuration in Roundcube to change that behaviour.

That link uses invalid URLs, which gmail apparently attempts to fix, but Roundcube doesn't.

We also probably won't change that without heavy-weighing arguments, because we'd have to touch complicated code to change it.
