### ISSUE TITLE
French translation of RoundCube makes no sense whatsoever!

### ISSUE THREAD

**Issue by MarcTremblay1981** [roundcube/roundcubemail#9619]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

French translation of RoundCube makes no sense whatsoever... Like WTF is this?

<img width="369" alt="Screenshot 2024-08-29 at 10 23 13 AM" src="https://github.com/user-attachments/assets/5739b221-f67b-436e-a035-8ea9f30e645a">

Not sure how you guys translated RoundCube, but even Google Translate gets it right:

<img width="1302" alt="Screenshot 2024-08-29 at 10 25 39 AM" src="https://github.com/user-attachments/assets/9edeaf1b-b4c6-4e1a-89d8-d314d6f7ed6a">

### What browser(s) are you seeing the problem on?

Other

### What version of PHP are you using?

8.2

### What version of Roundcube are you using?

1.6.8

**Comment by alecpl** [comment]
We're using Transifex. https://app.transifex.com/roundcube/roundcube-webmail/translate/#fr/labels/9049602?q=text%3Asent

I can't find "Envoyérent" anywhere in Roundcube. Maybe that's from a skin or plugin?

**Comment by n-goncalves** [comment]
Hi,

I am also using Roundcube 1.6.8 in French. The default names of these folders in Roundcube are correct and haven't changed in a long time as shown by this file: https://github.com/roundcube/roundcubemail/blame/d26e4354f743c3195ba618afd427279c0600f751/program/localization/fr_FR/labels.inc#L33

I can also confirm that the defaults values in Roundcube are correctly applied as shown by this screenshot of my own instance of Roundcube.
![image](https://github.com/user-attachments/assets/d8557e8c-e29e-476e-8d7c-17245c8ea3bc)



"Camelote" and "Projets" aren't the default names of "Spam" and "Drafts" in French either. Are you sure there are no configuration/plugins/skins interfering with this ?

**Comment by MarcTremblay1981** [comment]
I went in the settings, then I set the language to English (US).  I checked and it was correctly displayed in English.  Then I went again in the settings and changed it to Français.  Then the correct the interface was correctly displayed in French.  I have no idea how/why this happened but after switching the language back and forth, it's now OK.  Sorry for the inconvenience.
