### ISSUE TITLE
Error 535 on free Webmail

### ISSUE THREAD

**Issue by CharlesWiggins** [roundcube/roundcubemail#9621]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Hello,

On the Free Webmail, I can't sent any email. Each time I get the error message "Error 535 : authentication failes.

Thanks,

Carsten Weber

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

Roundcube Webmail 1.6.8

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
