### ISSUE TITLE
Download file for RC 1.5.9 is actually 1.5.7 @roundcube.net/download

### ISSUE THREAD

**Issue by aartsr** [roundcube/roundcubemail#9623]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Seems like the gz-download is not (completely) current: https://github.com/roundcube/roundcubemail/releases/download/1.5.9/roundcubemail-1.5.9-complete.tar.gz. I tried upgraiding from 1.5.7 to 1.5.9 with this gz-file but it states that it's trying to update to 1.5.7 instead ;)

### What browser(s) are you seeing the problem on?

Other

### What version of Roundcube are you using?

1.5.7

**Comment by pabzm** [comment]
The tarball from that URL contains the code of Roundcube version 1.5.9, as far as I can tell. 

Please explain and show us in more detail what you've done and what the script outputs were. Without those details we can only guess, which wouldn't be helpful.

**Comment by aartsr** [comment]
Yesterday it output something like "upgrading from 1.57 to 1.57". Not sure what happened but today it worked, albeit with a small warning: 

WARNING: JavaScript dependencies update skipped. New jsdeps.json file not found.
NOTICE: The 'installer' directory still exists. You should remove it after the upgrade.

Running update script at target...
Executing database schema update.
ERROR: Error in DDL upgrade 2020091000: [1050] Table 'collected_addresses' already exists
Updating database schema (2020091000)... [FAILED]

Sorry for the confusion and thanks for your time.

**Comment by pabzm** [comment]
No worries, thank you for the feedback!

**Comment by pabzm** [comment]
(If the other warnings result in problems, please open a new issue!)
