### ISSUE TITLE
composer complains: could not detect the root package (roundcube/roundcubemail) version

### ISSUE THREAD

**Issue by emtiu** [roundcube/roundcubemail#9624]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

When running php `composer.phar update` from roundcube's directory, the update succeeds but produces a complaint:

```Composer could not detect the root package (roundcube/roundcubemail) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version```

Manually inserting `"version": "1.6.7",` into composer.json silences the warning.

### What version of PHP are you using?

v8.2.23

### What version of Roundcube are you using?

v1.6.7

### PHP errors

$ php composer.phar update
Composer could not detect the root package (roundcube/roundcubemail) version, defaulting to '1.0.0'. See https://getcomposer.org/root-version

**Comment by pabzm** [comment]
The warning occurs only if you don't have `git` installed, because then composer can't fallback to it to get a version number.

That said we could also set the version number in the released code – but maybe only if we'd ship a `composer.json` (in contrast to `composer.json-dist`). @alecpl What's the reason to do that? Can we change it?

**Comment by alecpl** [comment]
I tried `"version":"1.7-git"`, but composer didn't like that version number. Putting version there would also cause other problems. I think we should find another solution.

Maybe plugin-installer should "just" not require "roundcube/roundcubemail".

**Comment by pabzm** [comment]
@alecpl [The Makefile writes a version into it](https://github.com/roundcube/roundcubemail/blob/master/Makefile#L28) during the release process. Why do we not ship the `composer.json`?

**Comment by alecpl** [comment]
The new plan is to ship it for the next major release. There was no composer.json file before, it's a new thing. There's a lot of composer-related changes in master (and plugin-installer) in comparison to 1.6.

**Comment by pabzm** [comment]
I'm closing this because we'll have a version number in future released code, and for development setups `git` is a requirement anyway.

@emtiu Thank you for bringing this up, it helped to clarify some things!

**Comment by pabzm** [comment]
Feel free to re-open and fix this! I'm just trying to limit the number of open issues that don't have a clear way forward.

**Comment by DigiAngel** [comment]
I'm having this exact issue after upgrading.

**Comment by gerconmen** [comment]
Upgrading from 1.6.12 to 1.6.13 with same issue. I DO have git installed. Mostly it seems to work fine, but I don't yet know if it has broken anything, although:
Problem 1
    - Root composer.json requires phpunit/phpunit ^4.8.36 || ^5.7.21, found phpunit/phpunit[4.8.36, 5.7.21, ..., 5.7.27] but these were not loaded, because they are affected by security advisories

**Comment by alecpl** [comment]
> Upgrading from 1.6.12 to 1.6.13 with same issue. I DO have git installed. Mostly it seems to work fine, but I don't yet know if it has broken anything, although: Problem 1 - Root composer.json requires phpunit/phpunit ^4.8.36 || ^5.7.21, found phpunit/phpunit[4.8.36, 5.7.21, ..., 5.7.27] but these were not loaded, because they are affected by security advisories

Your composer.json is outdated. https://github.com/roundcube/roundcubemail/blob/release-1.6/composer.json-dist#L26
