### ISSUE TITLE
Adding invalid contact displayed saved instead of showing only error and allow resources annoyance.

### ISSUE THREAD

**Issue by akissz** [roundcube/roundcubemail#9628]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

When you add a contact to contacts and enter *@domain it says saved and then error. I assume it meant to say error only which would of been fine. On the other hand to me this is a valid entry but the software seems to have difficulty distinguishing. I say it is valid entry because this is they way I would normally enter a approved domain in contacts like a filter. I was trying to add this for a trusted contact so images would be displayed but it seems this is not how your program functions but it should. Also I think it is a problem when display HTML is disabled in settings that you can not select to allow resources. There should be a way to select allow resourced when HTML is disabled for quick display as needed. As it is currently you are required to click on multiple things which is not efficient. Sorry for including a lot in this but I see this all in real time so I decided to write it all.

### What version of PHP are you using?

8.3.1

### What version of Roundcube are you using?

1.6.8

**Comment by pabzm** [comment]
I'm not sure I understand correctly, but I can perfectly well enter `*@example.net` as email address:

<img width="734" alt="image" src="https://github.com/user-attachments/assets/a0b2bc48-5eeb-48a4-b019-e46225c00a65">

Please precisely explain what's different in your case.

(The other parts of your text I cannot really understand, sorry.)

**Comment by alecpl** [comment]
No feedback. I see a few feature requests here, feel free to create separate tickets for them.
