### ISSUE TITLE
Render PGP/MIME attachments in message pane for Mailvelope

### ISSUE THREAD

**Issue by andrewgdotcom** [roundcube/roundcubemail#9635]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

It would be very nice if Roundcube would natively support PGP/MIME with Mailvelope. To do this, PGP/MIME attachments need to be rendered in raw base64 format in the message pane, where Mailvelope will recognise them in the same way it recognises inline-PGP. If possible, this could only be done if a user preference is set, or (ideally) if Roundcube detects that Mailvelope is being used.

### Motivation and context

PGP/MIME is the preferred format for encrypted email, however in order for Mailvelope to process it, the encrypted attachment needs to be rendered in its raw form in the message pane. There exists a third-party plugin for this [1], however it appears to be abandoned and requires updating [2] to avoid triggering Mailvelope's Efail mitigations (specifically: if there is mixed encrypted and non-encrypted text in the message pane, Mailvelope refuses to display either). This functionality is simple enough that it should be possible to include it in the core software - but if not, an officially supported plugin would be sufficient.

[1] https://github.com/posteo/show_pgp_mime/
[2] https://github.com/posteo/show_pgp_mime/pull/6

**Comment by dkg** [comment]
I think you're asking for natively supporting *rendering* of PGP/MIME multipart/signed and multipart/encrypted messages.  Is that right?  just saying "natively support PGP/MIME" can mean a lot of things, including *sending* PGP/MIME messages.

It seems like if roundcube wants to facilitate mailvelope handling incoming PGP/MIME messages,  it ought to be able to feed the relevant parts of any message with a [multipart/signed](https://www.ietf.org/archive/id/draft-ietf-lamps-e2e-mail-guidance-16.html#section-4.1.2.1) or [multipart/encrypted](https://www.ietf.org/archive/id/draft-ietf-lamps-e2e-mail-guidance-16.html#section-4.1.2.2) structure to the mailvelope browser extension directly, without needing to put the in the raw base64 in a place that a non-mailvelope user would see it as line noise.

**Comment by andrewgdotcom** [comment]
It might be possible to render it in the HTML code but with a style attached that makes it invisible to humans but visible to javascript…

**Comment by alecpl** [comment]
If we do this I think it will be better to move existing Mailvelope-related code into a plugin, and add features there. Of course in core we can provide necessary plugin API changes.

**Comment by pabzm** [comment]
@andrewgdotcom Thank you for the suggestion!

I'm not sure though if there's a misunderstanding here, but as soon as you authorised your Roundcube-domain in Mailvelope's settings to use the API, Roundcube will provide PGP/MIME-messages to Mailvelope. So I guess your feature request is already implemented. Please correct me if I'm wrong.

(In recent versions of Roundcube you can enable that feature by clicking a button in "encryption" section of Roundcube's settings.)

**Comment by andrewgdotcom** [comment]
It seems I can no longer reproduce this issue. Classic schroedinbug. 😩 Sorry everyone.

**Comment by pabzm** [comment]
Not a problem, thank you for caring for Roundcube!

**Comment by andrewgdotcom** [comment]
Hm, while viewing of encrypted messages works, I still can't view signed messages using the Mailvelope interface - it just gets displayed with a "Digital Signature" attachment. Should I open a separate issue for that?

**Comment by pabzm** [comment]
As far as I know, Mailvelope can't handle signed (but unencrypted) emails as of yet. (At least it can't produce those for sending.) So if I'm right there, it would't make much sense to add glue code for a feature that doesn't (yet) exist.
