### ISSUE TITLE
Falha no login mesmo com dados corretos

### ISSUE THREAD

**Issue by Guizk7** [roundcube/roundcubemail#9636]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Sempre que tento fazer login com os dados corretos fica aparecendo a mensagem de "Falha no Login" 
![Screenshot_20240913_160423_Chrome](https://github.com/user-attachments/assets/48329255-0e9e-4ad5-8c04-4298d6ea29a7)

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

Estou no Android 

### What version of Roundcube are you using?

Estou no android

**Comment by alecpl** [comment]
If you have problems with your email account (e.g. cannot log in, emails got lost, etc.) or if you have questions how to configure your Outlook or mobile phone to get email, this isn't the right place to ask. Roundcube is not a service but free software which somebody installed for you.

Please contact your internet hosting provider or IT responsible instead. If you don't know who this might be, please review your bills and find out who you're paying for email and webhosting services.
