### ISSUE TITLE
Suggested correction to :443 of the password plugin README file concerning the zxcvbn driver

### ISSUE THREAD

**Issue by martin762** [roundcube/roundcubemail#9648]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

"Remove the line 443 from the documentation:
Set $config['password_zxcvbn_min_score'] to define minimum acceptable password strength score."
I have version 1.6.9. My experience with the above added to the config file is that it does nothing. In contrast the $config['password_zxcvbn_min_score'] entry works as intended. The zxcvbn driver, etc. has been loaded as required.

Am I correct with my above assertion in general or am I observing an exception? Happy to be corrected

### Motivation and context

If my observation is correct in general for current and future versions, then the documentation line  443 is no longer relevant. Happy to raise an appropriate  PR.
(also willing to suggest additional text to the section on the zxcvbn driver to make it more comprehensive

**Comment by alecpl** [comment]
Thanks. Fixed.
