### ISSUE TITLE
Undefined array key name encountered in get_vendor() function

### ISSUE THREAD

**Issue by nicohell** [roundcube/roundcubemail#9650]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

Undefined array key name encountered in get_vendor() function

### What version of PHP are you using?

8.2.x

### What version of Roundcube are you using?

1.6.9

### PHP errors

On line 661 of file program/lib/Roundcube/rcube_imap.php the test `$vendor  = (string) (!empty($ident) ? $ident['name'] : '');` returns  Undefined array key "name"
Here are the datas received  in $ident :
```
array (
  'NAME' => 'Zimbra',
  'VERSION' => '9.0.0_GA_4612',
  'RELEASE' => '20240412104050',
  'USER' => 'courrier@...',
  'SERVER' => 'fd376667-0000-4282-ac83-09617f120abc',
) 
```

**Comment by pabzm** [comment]
@nicohell  Thank you for the report!

**Comment by alecpl** [comment]
According to https://www.rfc-editor.org/rfc/rfc2971.html#section-3.3 the keys are indeed not case-sensitive.
