### ISSUE TITLE
Forward instead of redirect when filtering

### ISSUE THREAD

**Issue by Thatoo** [roundcube/roundcubemail#9651]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

Have forward option along with (existing) redirect option when filtering, the same way that when we are in Inbox, we can either redirect or forward. Unfortunately today, when filtering, we can only choose to redirect.

### Motivation and context

I have a bunch of emails I am filtering with Roundcube managesieve filters. I have them redirecting out to different addresses. The problem is the emails retain the original sender. I'd like the emails to forward or resend, not redirect. This way all mail looks like it's coming directly from the Roundcube box. Is this possible? Thanks!

This is a message I found on forum dating from 2014 and I was happy to see I'm not the only one to face with this missing feature.
https://www.roundcubeforum.net/index.php?topic=21617.0

**Comment by alecpl** [comment]
Don't forget Roundcube is just a sieve client. We're limited by Sieve capabilities and implementations.

There's a few extensions that come to mind RFC 5293 (addheader/deleteheader), RFC 5703 (enclose). The former is supported by Roundcube, but I didn't investigate if that's gonna work or not, and of course your server would have to support that too.
