### ISSUE TITLE
Oauth login redirects to login page

### ISSUE THREAD

**Issue by Marcohb99** [roundcube/roundcubemail#9652]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [x] I can recreate the issue with all plugins disabled

### Describe the issue

When I click the "Login with Keycloack" button, even before trying to request Keycloack, I am redirected to `/index.php/login/oauth`, which does nothing but reloading the login form. 
I've checked the `index.php` code and it does not recognize the `task` and `action` parameters when requested with the mentioned path.
```php
// handle oauth login requests
else if ($RCMAIL->task == 'login' && $RCMAIL->action == 'oauth' && $RCMAIL->oauth->is_enabled()) {
    $oauth_handler = new rcmail_action_login_oauth();
    $oauth_handler->run();
}
```
I know this is not the correct way to solve it, but since no issues reported here gave me a solution (example: changing the assets path to `'/'`), I made it work changing in `rcmail_oauth.php`:
Before
```php
    public function get_redirect_uri()
    {
        $url = $this->rcmail->url([], true, true);

        // rewrite redirect URL to not contain query parameters because some providers do not support this
        $url = preg_replace('/\?.*/', '', $url);

        return slashify($url) . 'index.php/login/oauth';
    }
```
After
```php
    public function get_redirect_uri()
    {
        $url = $this->rcmail->url([], true, true);

        // rewrite redirect URL to not contain query parameters because some providers do not support this
        $url = preg_replace('/\?.*/', '', $url);

        return slashify($url) . '?_task=login&_action=oauth';
    }
```

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

8.2

### What version of Roundcube are you using?

1.6.9

**Comment by alecpl** [comment]
Something's wrong with PATH_INFO. See https://github.com/roundcube/roundcubemail/blob/84e0bafa5bbb7f070a8cbe076f5288afc033212e/program/include/iniset.php#L68

**Comment by Marcohb99** [comment]
That's right, path info was always empty. Updating the nginx configuration solved the issue.
Thanks!
