### ISSUE TITLE
PHP Warning:  Undefined array key "style"

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9653]
Hi there. I'd like to report the following warning line, which I'm occassionally getting:

`PHP Warning:  Undefined array key "style" in /var/www/rcube/program/actions/mail/index.php on line 1192`

Roundcube: 1.6.9
PHP: 8.1.29

Regards.

**Comment by pabzm** [comment]
This is a duplicate of https://github.com/roundcube/roundcubemail/issues/9611
