### ISSUE TITLE
Pass all spam through (allow for external spam tools)

### ISSUE THREAD

**Issue by bcullman** [roundcube/roundcubemail#9660]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

Allow me to denote all email as Not Spam, no exceptions (aka allow me to use my own tools to manage spam)

### Motivation and context

I pay Hover for a personalized email address. I then forward this mail to GMail, which is the email client i use on a day to day basis.

This works well. However, occationally, Hover marks an email as spam, and does not forward it to gmail. This is frustrating. I don't need Hover to choose which email are or are not spam. I will determine that on my own using GMail.

To fix this, when i suspect an email has not been delivered, i log into Hover, and use their roundcubemail check to see if the email was marked as spam. If it was, I add the email to the allowed sender list, and then ask the sender to resend.

The trouble is, Hover has lately been marking more emails as spam than they used to, and because I normally dont interact with Hover directly, i never know when an email has been flagged as spam.

if I could either just add "*" in the allow list so that no emails are blocked as spam, -OR- if I could set the spam folder the same as the inbox folder so that they are not treated as spam, that would work. Perhaps I can already do this, but i don't see it documented anywhere.

**Comment by alecpl** [comment]
What "allow list" are you talking about? Changing Spam folder assignment would probably not solve anything. Sounds to me that Hover (whatever that is) - its SMTP server - is doing the filtering. There must be something, out of Roundcube's control, that places spam in the Spam folder. Often it's a sieve rule, but you may or may not have access to it.

**Comment by bcullman** [comment]
Settings > Spam Settings > Allowed Senders.

This is UI that RoundCubeMail provides. When I add emails to this list that were previously dropped in the spam folder, future emails from the same address are delivered to the inbox (where, for me, they are forwarded on to gmail, where i read them)

So, there _is_ something in Roundcube's control that is available to affect the flow of emails initially marked as spam. I am just asking for a way to not have to hand-add every email address - like does * work? If not, could it be made to work?

**Comment by alecpl** [comment]
This is an external plugin, maybe https://github.com/johndoh/roundcube-sauserprefs.
