### ISSUE TITLE
DB Error: [1062] Duplicate entry 'q9dhhiiiuh3hjq5bpfc1h3av2p' for key

### ISSUE THREAD

**Issue by ozgurkazancci** [roundcube/roundcubemail#9674]
Using: Roundcube 1.6.9, have this line in my error log file;

`[16-Oct-2024 22:43:21 +0600]: <q9dhhiii> DB Error: [1062] Duplicate entry 'q9dhhiiiuh3hjq5bpfc1h3av2p' for key 'PRIMARY' (SQL Query: INSERT INTO `session` (`sess_id`, `vars`, `ip`, `changed`) VALUES ('q9dhhiiiuh3hjq5bpfc1h3av2p', 'dGVtcHxiOjE7bGFuZ3VhZ2V8czo1OiJlbl9VUyI7dGFza3xzOjU6ImxvZ2luIjtza2luX2NvbmZpZ3xhOjc6e3M6MTc6InN1cHBvcnRlZF9sYXlvdXRzIjthOjE6e2k6MDtzOjEwOiJ3aWRlc2NyZWVuIjt9czoyMjoianF1ZXJ5X3VpX2NvbG9yc190aGVtZSI7czo5OiJib290c3RyYXAiO3M6MTg6ImVtYmVkX2Nzc19sb2NhdGlvbiI7czoxNzoiL3N0eWxlcy9lbWJlZC5jc3MiO3M6MTk6ImVkaXRvcl9jc3NfbG9jYXRpb24iO3M6MTc6Ii9zdHlsZXMvZW1iZWQuY3NzIjtzOjE3OiJkYXJrX21vZGVfc3VwcG9ydCI7YjoxO3M6MjY6Im1lZGlhX2Jyb3dzZXJfY3NzX2xvY2F0aW9uIjtzOjQ6Im5vbmUiO3M6MjE6ImFkZGl0aW9uYWxfbG9nb190eXBlcyI7YTozOntpOjA7czo0OiJkYXJrIjtpOjE7czo1OiJzbWFsbCI7aToyO3M6MTA6InNtYWxsLWRhcmsiO319cmVxdWVzdF90b2tlbnxzOjMyOiJqQjBuelEzR1Q2V1JrRHBXQmt1MUcybmV3OWxLZ1JBNyI7', '220.2x.xx.xx', now())) in /rcube/program/lib/Roundcube/rcube_db.php on line 577 (GET /webmail/?_task=mail&_mbox=Sent)`

Any idea?

Regards.

**Comment by pabzm** [comment]
To help you we would need much more information. How is the setup? Which PHP-version? A single server or multiple ones? Which database? A single database host or with replication? Etc.

**Comment by ozgurkazancci** [comment]
Thanks for your reply. The setup is a single server.

Database: MariaDB. PHP version is: 8.1.30 and virtual mail users are in SQL tables.

Postfix, Dovecot and PostfixAdmin software are used.

**Comment by pabzm** [comment]
Did you see the error only once or repeatedly?

If the latter, can you reproduce it?

**Comment by alecpl** [comment]
No feedback.
