### ISSUE TITLE
Buttons in new window should be all the way to the left

### ISSUE THREAD

**Issue by jidanni** [roundcube/roundcubemail#9679]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

Regarding "open in a new window". In that new window,
I have discovered, that the buttons I have marked,
sometimes are further to the right, and sometimes not.

It all depends on the content. If the content has long lines, the buttons will be further to the right.

This is wrong. The buttons should always be all the way to the left. No matter what width the content is.

### Motivation and context

![Screenshot 2024-10-25 18 40 06](https://github.com/user-attachments/assets/0c696534-bac7-46f1-a328-176831c1f101)

 Motivation: one day I could not find the Delete button, until I made the window Fullscreen and finally found it hiding way off in right field.

Version: no, not the latest. Just please see it if this still occurs.

**Comment by pabzm** [comment]
@jidanni Do you maybe have an example message to work with?

**Comment by alecpl** [comment]
I'm not able to reproduce. It's centered for me in both cases. What Roundcube version do you use? What browser?

**Comment by jidanni** [comment]
I use the Roundcube version found on https://webmail.dreamhost.com/ .

I use chrome 131
Browser screen width: 1133 pixels
Browser screen height: 577 pixels

**Comment by alecpl** [comment]
Dreamhost's version is 1.5.0. Old, and not supported.
