### ISSUE TITLE
Why allow/use old phpunit?

### ISSUE THREAD

**Issue by pabzm** [roundcube/roundcubemail#9683]
For our test suite we require phpunit `"^9.6.20 || ^10.0 || ^11.0"`. Thus after `composer upgrade … --prefer-lowest` the unit tests are run with phpunit v9.x instead of v11.x.

Is there a reason to use these old versions of the testing framework? Our testing tools should be up to date, no?

It made me some headaches today because phpunit v9 doesn't yet handle deprecations but simply outputs them, which messes with other output (e.g. dealing with HTTP headers).

**Comment by alecpl** [comment]
We're testing code on all supported PHP versions. So, until we drop support for 7.x and 8.0 we can't change that.

**Comment by pabzm** [comment]
Alright, thank you for the explanation, I didn't think of that!
