### ISSUE TITLE
Внесённые изменения

### ISSUE THREAD

**Issue by serzant3** [roundcube/roundcubemail#9699]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Здравствуйте, сегодня автоматически изменился вид почтового ящика, что очень не удобно.
Убедительная просьба вернуть предыдущий классический вид интерфейса или подсказать как это можно сделать самостоятельно.
Спасибо.

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

v.1.6.9

**Comment by pabzm** [comment]
Please write in english, so we can understand properly (without translation tools).

According to an automated translation you have a problem with the webmail you are using. Please contact the people that run the service for you. We only produce the software, we don't run it.

**Comment by serzant3** [comment]
> Пожалуйста, пишите на английском языке, чтобы мы могли правильно понять (без использования средств перевода).
> 
> Согласно автоматическому переводу у вас проблема с веб-почтой, которую вы используете. Пожалуйста, свяжитесь с людьми, которые управляют сервисом для вас. Мы только производим программное обеспечение, мы не запускаем его.

Здравствуйте.
Спасибо за ответ.
Описать проблему на английском языке (без использования средств перевода) не могу, так как им не владею, по этому не было путаницы оставлю как есть.
Я связался с людьми, которые предоставляют почтовый сервис. Они мне ответили на следующее:
<<К сожалению, вернуть старую тему интерфейса не удалось. webmile.hostings.com стоит на платформе Roundcube, администрируемой не мы. Сама платформа обновила у себя интерфейс и убрала возможность вручную изменить его>>
В итоге вид почтовой программы с кардинально измененной версией {Roundcube Webmail 1.6.9}, что очень не удобно.
Вопрос и просьба очень простые, вы можете дать ссылку на скачивание вашей почтовой программы для установки в Windows в КЛАССИЧЕСКОМ видео.
Спасибо.

**Comment by pabzm** [comment]
The previously used skin is called "larry" and is still installable in current versions of Roundcubemail: <https://github.com/roundcube/larry>.

That might not be the case for future versions – unless people step up and maintain it.

We don't provide installations with "larry" as default skin.
