### ISSUE TITLE
maybe nice to have a minimal default config example for roundcube/dovecot/keycloak

### ISSUE THREAD

**Issue by f1-outsourcing** [roundcube/roundcubemail#9702]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

I am missing some concepts of implementing openid/oauth. I think I have configured roundcube correctly for keycloak because I see in the dovecot logs requests to the keycloak server, but they are generating at some point 404. I also don't really know if this is related to roundcube sending incorrect data or misconfiguration in dovecot. 

So it would be nice if there was some up to date configuration example.

### Motivation and context

I am missing some concepts of implementing openid/oauth. I think I have configured roundcube correctly for keycloak because I see in the dovecot logs requests to the keycloak server, but they are generating at some point 404. I also don't really know if this is related to roundcube sending incorrect data or misconfiguration in dovecot. 

So it would be nice if there was some up to date configuration example.

**Comment by alecpl** [comment]
There are some samples in config/defaults.inc.php file. Dovecot/Keycloak configuration is another story. I'm not interested. A wiki page could be created.

**Comment by f1-outsourcing** [comment]
Do you know if it is possible to have a regular mail client like thunderbird login to dovecot, dovecot is creating some sso session, so when you open your browser you do not need to login any more?
I also don't really know how this should work and how the web browser should know who you are, but it is quite nice to be able to share these sessions between website applications.
