### ISSUE TITLE
keeps logging me out every couple of minutes 'server error'

### ISSUE THREAD

**Issue by millslucy42** [roundcube/roundcubemail#9711]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [X] I can recreate the issue with all plugins disabled

### Describe the issue

I used to be able to login fine and it kept me logged in.
Now, I get logged out every couple of minutes and it makes the email inbox unusable. 
A red box appears and says 'server error'. 

### What browser(s) are you seeing the problem on?

Chrome, Edge

### What version of PHP are you using?

what is php? 

### What version of Roundcube are you using?

1.6.8

### JavaScript errors

c5678836-a877-4e64-9d72-008072ed727e

**Comment by alecpl** [comment]
With this info we'll not be able to help. Any errors in Roundcube logs or HTTP server/PHP log? Anything specific in browser console? Are you an end-user or you are a Roundcube administrator?

**Comment by jstoorvo** [comment]
I'm suffering the same here. I might give you more details.

Using PHP 8.1.31 on a cPanel server, Apache  with nginx frontend.

I'm getting a 401 when https://www.xxxxx:2096/cpsess1489716507/3rdparty/roundcube/?_task=mail&_action=refresh

It used to work flawlessly.

[roundcube_errors.txt](https://github.com/user-attachments/files/18010416/roundcube_errors.txt)
[post_request.txt](https://github.com/user-attachments/files/18010417/post_request.txt)
