### ISSUE TITLE
Chrome is extremely slow Elastic theme.

### ISSUE THREAD

**Issue by koticik** [roundcube/roundcubemail#9712]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

When I try to log into my email through Chrome, it takes a very long time to open the inbox, and sometimes I can't log in at all and have to try again. Additionally, the address book is incredibly slow; it takes about a minute for the search window to open after clicking on the address book icon. I've tried the same actions in Firefox, and I don't experience any slowness issues.
Time Firefox
![firefox](https://github.com/user-attachments/assets/ed0c18f5-105e-41be-a614-65fe7fda8453)
Time Chrome
![chrome](https://github.com/user-attachments/assets/d33fd919-c4dc-46f8-9b5c-b9e086150697)
Measurements were taken using the same email account and the same computer.
The issue occurs when the Elastic theme is installed.

### What browser(s) are you seeing the problem on?

Chrome

### What version of PHP are you using?

PHP 8.1.2-1ubuntu2.19

### What version of Roundcube are you using?

Roundcube Webmail 1.5.3

**Comment by alecpl** [comment]
1.5 is in low maintenance mode. You'll have to update. Also I see the same refresh request could take a long time, but also short time. I doubt this is Roundcube issue.
