### ISSUE TITLE
Encrypted Rich Text Emails - PGP with HTML emails or markdown emails

### ISSUE THREAD

**Issue by p-sims** [roundcube/roundcubemail#9715]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed feature requests
- [X] I have [searched](https://plugins.roundcube.net/) for plugins that provide already provide the feature

### Proposal

RoundCube support either PGP encrypted Rich Text emails, either via allowing HTML emails to be encypted, or PGP encryption of plain text markdown which Roundcude transparently allows you to edit and view as rich text (Like opensource gitlab rich text editor for markdown comments).

### Motivation and context

Currently I believe PGP email encryption only works for plain text emails. This limits PGP encryption of emails becoming default (where recipients supports) and therefore wider adoptions.

Lots of people use some rich text formatting in most of there emails, whether that be a hyperlink, or embedded inline image, or Bold for emphasis, or bullet points. People shouldn't be forced to choose between rich text formatting and encryptions. Encrypted emails being like email 20 years ago is barrier to adoption, and potentially push people requiring end-to-end encryption away from email towards instant messaging or discussion platforms. 

At the Point PGP support is built into roundcube, surely the next step is Rich Text PGP support.

Personally I wonder if Markdown is better solution most of the time - given extent to which HTML is overkill for rich text support in most emails, and how it can lead to all sort of funky formatting if you copy some html in from web browser...

**Comment by alecpl** [comment]
If you use the enigma plugin you can encrypt HTML messages. So, I suspect you're talking about Mailvelope intergration. From what I understand the extension does not really support HTML. If someone proves me wrong we might reconsider. I don't think it makes sense to keep the ticket open.

**Comment by p-sims** [comment]
@alecpl - Thanks for this, good to have a solution.

I will just flag that there no information I could find about this plugin or what PGP support if offers on the [roundcube website](https://roundcube.net/), so I not sure how I could have found out about this plugin or fact it support HTML without someone pointing me in the right directions...

If you search enigma in the plugin list at [plugins.roundcube.net/#/ ](https://plugins.roundcube.net/#/) I note that it appears not to have an entry.... (not results are returned...)
