### ISSUE TITLE
Autoreply and move to trash filter combination not working

### ISSUE THREAD

**Issue by atlguy** [roundcube/roundcubemail#9729]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

We have users that would like to block certain senders and reply that their email has been blocked. If you set up a filter to first reply, then move to trash, neither rule gets executed. If you try to set this up as two rules, neither also works.

### What browser(s) are you seeing the problem on?

Chrome

### What version of Roundcube are you using?

v1.66

**Comment by alecpl** [comment]
Roundcube only creates Sieve scripts. It does not execute them. We also do not have control on the Sieve standard(s).

That being said it may be implementation dependent (i.e. your IMAP/Sieve server). For me, if I do:
```
    vacation :subject "test" "test";
    fileinto "Trash";
```
I get both actions executed without issues.
