### ISSUE TITLE
DB Error: [19] NOT NULL constraint failed

### ISSUE THREAD

**Issue by JulianAtkins** [roundcube/roundcubemail#9734]
### Prerequisites

- [X] I have [searched](https://github.com/roundcube/roundcubemail/issues?q=is%3Aissue) for duplicate or closed issues
- [ ] I can recreate the issue with all plugins disabled

### Describe the issue

Hello! Roundcube is awesome, thank you for your hard work, we really appreciate it!

Now about the problem, I am using the following plugins:
```
$config['plugins'] = array(
        'archive',
        'libkolab',
        'libcalendaring',
        'calendar',
);
```

And I'm getting tons for the following error:
```
Dec 16 17:47:48 server roundcube[78691]: <cj0jj3ss> DB Error: [19] NOT NULL constraint failed: events.sensitivity (SQL Query: UPDATE "events" SET "changed" = datetime('now'), "start" = '2024-12-17 10:00:00', "end" = '2024-12-17 12:00:00', "all_day" = '0', "sequence" = '0', "title" = 'subject ', "description" = 'info@
server.com', "location" = '', "free_busy" = '1', "priority" = '0', "sensitivity" = NULL, "status" = 'CONFIRMED', "attendees" = '[{"name":"somename","rsvp":false,"email":"someemail@server.com","role":"ORGANIZER","status":"ACCEPTED"},{"name":"otheremail@server.com","status":"ACCEPTED","role":"REQ-PARTICIPANT","cutype":"INDI
VIDUAL","rsvp":false,"email":"otheremail@server.com"}]', "alarms" = '[{"action":"DISPLAY","description":"This is an event reminder","trigger":"-PT30M"}]', "notifyat" = '2024-12-17 09:30:00' WHERE "event_id" = '3559' AND "calendar_id" IN ('22')) in /home/server/public_html/program/lib/Roundcube/rcube_db.php on line 577 (POST /?_task=calendar&_framed=1&_action=mailimportitip)
```

I am using SQLite3 as a database.

Thank you.

### What version of PHP are you using?

v7.4.33

### What version of Roundcube are you using?

v1.6.9

### JavaScript errors

none

### PHP errors

none

**Comment by alecpl** [comment]
This is an external plugin we do not support here.

I'm pretty sure the issue was already fixed in the plugin's code, but it wasn't yet released in the mirror. The fix is to change `null` into `0` at https://github.com/kolab-roundcube-plugins-mirror/calendar/blob/e11e26ed24c7a83c046322b01e1efbd080487c28/drivers/database/database_driver.php#L665

**Comment by alecpl** [comment]
Kolab does not provide these plugins via packagist, and one could not use their git (via packagist?) at some point. So we provided a mirror, but we're behind.
